-- =====================================================================
--  20_bank_sinif3.sql : 3-CU SINIF - AZ DILI, HEYAT BILGISI, INFORMATIKA
--
--  BU FAYL ELLE YAZILMIR - tools/sinif3.py yaradir:
--      python3 tools/sinif3.py
--
--  Az dili 8 + Heyat bilgisi 6 + Informatika 4 = 18 movzu x 10 = 380.
--  ext_key: az3-/hey3-/inf3-...
--  ON SERT: 14_movzular.sql ve 15_movzular_ederslik.sql islenmis olmalidir.
--  SONRA:   05_grants.sql yeniden islet.
-- =====================================================================

do $$
begin
  if not exists (select 1 from public.topics t join public.subjects s
      on s.id = t.subject_id
     where (s.slug, t.slug) in (('az-dili','az-3-isim'),
                                ('hayat-bilgisi','hey-3-yer-ay'),
                                ('informatika','inf-3-metn'))
     having count(*) = 3) then
    raise exception 'ONCE 14_movzular.sql ve 15_movzular_ederslik.sql isledilmelidir.';
  end if;
end $$;

delete from public.question_options o
 using public.questions q
 where o.question_id = q.id
   and q.owner_type = 'platform'
   and (q.ext_key like 'az3-%' or q.ext_key like 'hey3-%'
        or q.ext_key like 'inf3-%');

with d(ext, fenn, topic, diff, rub, body, why, opts, correct) as (values
('az3-sait-samit#1','az-dili','az-3-sait-samit',1,1,'Azərbaycan dilində neçə sait səs var?','Dilimizdə 9 sait var: a, e, ə, i, ı, o, ö, u, ü.',array['9','6','23','32'],1),
('az3-sait-samit#2','az-dili','az-3-sait-samit',1,1,'Hansı sırada yalnız saitlər verilib?','a, ı, u — hamısı saitdir.',array['a, ı, u','a, b, c','m, n, o','k, i, t'],1),
('az3-sait-samit#3','az-dili','az-3-sait-samit',2,1,'«Dəniz» sözündə neçə sait var?','Saitlər: ə, i — iki sait.',array['2','3','1','5'],1),
('az3-sait-samit#4','az-dili','az-3-sait-samit',2,1,'Qalın saitlər hansı sırada verilib?','Qalın saitlər: a, ı, o, u.',array['a, ı, o, u','ə, e, i, ö','a, ə, i, o','e, i, u, ü'],1),
('az3-sait-samit#5','az-dili','az-3-sait-samit',2,1,'İncə saitlər hansı sırada verilib?','İncə saitlər: ə, e, i, ö, ü.',array['ə, e, i, ö, ü','a, ı, o, u','a, e, i, o, u','b, c, d, f, g'],1),
('az3-sait-samit#6','az-dili','az-3-sait-samit',2,1,'«Məktəb» sözündə neçə samit var?','Samitlər: m, k, t, b — dörd samit.',array['4','2','6','3'],1),
('az3-sait-samit#7','az-dili','az-3-sait-samit',3,1,'Hansı samit kar samitdir?','«p» kar samitdir, cingiltili qarşılığı «b»-dir.',array['p','b','d','g'],1),
('az3-sait-samit#8','az-dili','az-3-sait-samit',3,1,'Hansı samit cingiltilidir?','«b» cingiltili samitdir, kar qarşılığı «p»-dir.',array['b','p','t','k'],1),
('az3-sait-samit#9','az-dili','az-3-sait-samit',1,1,'«Ana» sözü neçə səsdən ibarətdir?','A-n-a: üç səs.',array['3','2','4','5'],1),
('az3-sait-samit#10','az-dili','az-3-sait-samit',2,1,'Saitlər necə tələffüz olunur?','Saitlər səs yolunda maneəyə rast gəlmədən tələffüz olunur.',array['Maneəsiz','Maneə ilə','Yalnız pıçıltı ilə','Tələffüz olunmur'],1),
('az3-sait-samit#11','az-dili','az-3-sait-samit',2,1,'«Kölgə» sözündə hansı saitlər var?','Sözdəki saitlər: ö və ə.',array['ö, ə','k, l','o, a','g, ə'],1),
('az3-sait-samit#12','az-dili','az-3-sait-samit',2,1,'Yalnız samit səslərdən ibarət sıra hansıdır?','b, d, k — hamısı samitdir.',array['b, d, k','a, ı, u','ə, b, c','o, u, m'],1),
('az3-sait-samit#13','az-dili','az-3-sait-samit',2,1,'«Qapı» sözündə neçə səs var?','q-a-p-ı: dörd səs.',array['4','3','5','2'],1),
('az3-sait-samit#14','az-dili','az-3-sait-samit',1,1,'Hansı söz saitlə başlayır?','«Alma» sözünün ilk səsi a saitidir.',array['alma','kitab','dəftər','qələm'],1),
('az3-sait-samit#15','az-dili','az-3-sait-samit',3,1,'Kar samitə misal hansıdır?','«t» kar samitdir — səs tellərinin iştirakı olmadan deyilir.',array['t','b','d','g'],1),
('az3-sait-samit#16','az-dili','az-3-sait-samit',3,1,'«Dəmir» sözünün ilk səsi hansı qrupa aiddir?','«d» cingiltili samitdir.',array['Cingiltili samitdir','Kar samitdir','Qalın saitdir','İncə saitdir'],1),
('az3-sait-samit#17','az-dili','az-3-sait-samit',2,1,'Saitlər sözdə nəyi əmələ gətirir?','Heca saitin sayı qədərdir — saitlər heca yaradır.',array['Hecanı','Şəkilçini','Cümləni','Başlığı'],1),
('az3-sait-samit#18','az-dili','az-3-sait-samit',2,1,'«Ütü» sözündə hansı sait iki dəfə işlənib?','ü-t-ü: «ü» saiti iki dəfə işlənib.',array['ü','u','t','i'],1),
('az3-sait-samit#19','az-dili','az-3-sait-samit',2,1,'İncə saitlə başlayan söz hansıdır?','«Ördək» sözü incə «ö» saiti ilə başlayır.',array['ördək','armud','qoz','uşaq'],1),
('az3-sait-samit#20','az-dili','az-3-sait-samit',2,1,'«Külək» sözündəki saitlər hansı qrupdandır?','ü və ə incə saitlərdir.',array['İncə saitlər','Qalın saitlər','Kar samitlər','Cingiltili samitlər'],1),
('az3-isim#1','az-dili','az-3-isim',1,1,'İsim nəyi bildirir?','İsim əşyanın adını bildirir.',array['Əşyanın adını','Əlaməti','Hərəkəti','Miqdarı'],1),
('az3-isim#2','az-dili','az-3-isim',1,1,'Hansı söz isimdir?','«Dağ» — əşyanın adıdır, «nə?» sualına cavab verir.',array['dağ','qaçmaq','uca','beş'],1),
('az3-isim#3','az-dili','az-3-isim',1,1,'İsimlər hansı suallara cavab verir?','İsimlər «kim? nə?» suallarına cavab verir.',array['Kim? Nə?','Necə?','Nə edir?','Neçə?'],1),
('az3-isim#4','az-dili','az-3-isim',2,1,'Hansı söz xüsusi isimdir?','«Kür» — çayın xüsusi adıdır, böyük hərflə yazılır.',array['Kür','çay','şəhər','uşaq'],1),
('az3-isim#5','az-dili','az-3-isim',1,1,'Xüsusi isimlər necə yazılır?','İnsan, şəhər, çay adları böyük hərflə yazılır.',array['Böyük hərflə','Kiçik hərflə','Dırnaqda','Rəqəmlə'],1),
('az3-isim#6','az-dili','az-3-isim',2,1,'«Quşlar» sözü təkdədir, yoxsa cəmdə?','-lar şəkilçisi cəm bildirir.',array['Cəmdə','Təkdə','Heç biri','Hər ikisi'],1),
('az3-isim#7','az-dili','az-3-isim',2,1,'İsmin cəm şəkilçiləri hansılardır?','Cəm şəkilçiləri -lar, -lər-dir.',array['-lar, -lər','-da, -də','-a, -ə','-ın, -in'],1),
('az3-isim#8','az-dili','az-3-isim',2,1,'Hansı sırada yalnız isimlər verilib?','Kitab, meşə, günəş — hamısı əşya adıdır.',array['kitab, meşə, günəş','kitab, oxumaq, gözəl','meşə, yaşıl, getmək','günəş, isti, beş'],1),
('az3-isim#9','az-dili','az-3-isim',2,1,'«Bakı, Aysu, Araz» sözlərinin ümumi cəhəti nədir?','Hamısı xüsusi isimdir — ad bildirir və böyük hərflə yazılır.',array['Hamısı xüsusi isimdir','Hamısı feldir','Hamısı sifətdir','Hamısı cəmdədir'],1),
('az3-isim#10','az-dili','az-3-isim',3,1,'«Uşaqlar bağçada oynayırlar» cümləsində «bağçada» sözü hansı nitq hissəsidir?','«Bağça» əşya adıdır — isimdir.',array['İsim','Fel','Sifət','Say'],1),
('az3-isim#11','az-dili','az-3-isim',1,1,'«Şəhər» sözünün cəmi hansıdır?','-lər şəkilçisi ilə: şəhərlər.',array['şəhərlər','şəhərlar','şəhərcik','şəhərli'],1),
('az3-isim#12','az-dili','az-3-isim',2,1,'Ümumi isimə misal hansıdır?','«Çay» eyni qrupdan olan əşyaların ümumi adıdır.',array['çay','Kür','Bakı','Aysu'],1),
('az3-isim#13','az-dili','az-3-isim',2,1,'«Təbriz, Gəncə, Şuşa» sözləri hansı qrupa aiddir?','Hamısı şəhər adı — xüsusi isimdir.',array['Şəhər adları','Fellər','Sifətlər','Ay adları'],1),
('az3-isim#14','az-dili','az-3-isim',2,1,'İnsan adları hansı isimlərə aiddir?','Şəxs adları xüsusi isimdir.',array['Xüsusi isimlərə','Ümumi isimlərə','Fellərə','Sifətlərə'],1),
('az3-isim#15','az-dili','az-3-isim',2,1,'«Kitablar» sözündə cəm şəkilçisi hansıdır?','Qalın saitli sözə -lar artırılıb.',array['-lar','-lər','-çı','-lıq'],1),
('az3-isim#16','az-dili','az-3-isim',1,1,'Heyvan bildirən sözü seçin.','«Ceyran» heyvan adıdır.',array['ceyran','yaşıl','qaçmaq','hündür'],1),
('az3-isim#17','az-dili','az-3-isim',3,1,'«Dəniz sahilində uşaqlar oynayır» cümləsindəki isimləri seçin.','Əşya adı bildirənlər: dəniz, sahil, uşaqlar.',array['dəniz, sahil, uşaqlar','oynayır, uşaqlar','sahilində, oynayır','dəniz, oynayır'],1),
('az3-isim#18','az-dili','az-3-isim',2,1,'Cansız əşyanın adını bildirən söz hansıdır?','«Daş» cansız əşyadır, «nə?» sualına cavab verir.',array['daş','qaçır','gözəl','sürətlə'],1),
('az3-isim#19','az-dili','az-3-isim',2,1,'Hansı söz isim DEYİL?','«Yaşıl» əlamət bildirir, sifətdir.',array['yaşıl','qapı','quş','şagird'],1),
('az3-isim#20','az-dili','az-3-isim',1,1,'«Ana» sözünün cəm forması hansıdır?','Qalın saitli sözə -lar artırılır: analar.',array['analar','analər','anacıq','analı'],1),
('az3-sifet#1','az-dili','az-3-sifet',1,2,'Sifət nəyi bildirir?','Sifət əşyanın əlamətini bildirir.',array['Əşyanın əlamətini','Əşyanın adını','Hərəkəti','Miqdarı'],1),
('az3-sifet#2','az-dili','az-3-sifet',1,2,'Hansı söz sifətdir?','«Şirin» — əlamət bildirir: necə?',array['şirin','alma','yemək','iki'],1),
('az3-sifet#3','az-dili','az-3-sifet',1,2,'Sifətlər hansı suallara cavab verir?','Sifətlər «necə? nə cür? hansı?» suallarına cavab verir.',array['Necə? Nə cür?','Kim? Nə?','Nə edir?','Nə vaxt?'],1),
('az3-sifet#4','az-dili','az-3-sifet',2,2,'«Hündür bina» birləşməsində sifət hansıdır?','Bina necədir? — hündür.',array['hündür','bina','hər ikisi','heç biri'],1),
('az3-sifet#5','az-dili','az-3-sifet',2,2,'Hansı sırada yalnız sifətlər verilib?','Gözəl, dar, isti — hamısı əlamət bildirir.',array['gözəl, dar, isti','gözəl, ev, dar','isti, yay, gün','dar, küçə, uzun'],1),
('az3-sifet#6','az-dili','az-3-sifet',2,2,'Sifət cümlədə adətən hansı sözdən əvvəl gəlir?','Sifət ismin əlamətini bildirdiyi üçün isimdən əvvəl gəlir.',array['İsimdən','Feldən','Saydan','Cümlənin sonundakı sözdən'],1),
('az3-sifet#7','az-dili','az-3-sifet',2,2,'«Soyuq» sözünün əks mənalısı hansıdır?','Soyuq ↔ isti.',array['isti','sərin','buzlu','yaş'],1),
('az3-sifet#8','az-dili','az-3-sifet',2,2,'«Balaca pişik süd içir» cümləsində sifət hansıdır?','Pişik necədir? — balaca.',array['balaca','pişik','süd','içir'],1),
('az3-sifet#9','az-dili','az-3-sifet',2,2,'Əşyanın rəngini bildirən söz hansı nitq hissəsidir?','Rəng əlamətdir — sifətlə bildirilir.',array['Sifət','İsim','Fel','Say'],1),
('az3-sifet#10','az-dili','az-3-sifet',3,2,'Hansı söz sifət DEYİL?','«Yazmaq» hərəkət bildirir — feldir.',array['yazmaq','təmiz','qısa','dadlı'],1),
('az3-sifet#11','az-dili','az-3-sifet',2,2,'«Geniş» sözünün əks mənalısı hansıdır?','Geniş — dar əks mənalı sifətlərdir.',array['dar','böyük','uzun','açıq'],1),
('az3-sifet#12','az-dili','az-3-sifet',1,2,'«Şirin alma» birləşməsində əlamət bildirən söz hansıdır?','«Şirin» almanın dadını — əlamətini bildirir.',array['şirin','alma','birləşmə','söz'],1),
('az3-sifet#13','az-dili','az-3-sifet',2,2,'Dad bildirən sifəti seçin.','«Turş» dad bildirir.',array['turş','hündür','dəyirmi','səsli'],1),
('az3-sifet#14','az-dili','az-3-sifet',1,2,'«Qara» sözü nəyi bildirir?','Qara — rəng bildirən sifətdir.',array['Rəngi','Hərəkəti','Miqdarı','Səsi'],1),
('az3-sifet#15','az-dili','az-3-sifet',2,2,'Sifətlər hansı nitq hissəsini izah edir?','Sifət ismin əlamətini bildirir.',array['İsmi','Feli','Şəkilçini','Cümləni'],1),
('az3-sifet#16','az-dili','az-3-sifet',2,2,'«Cəsur» sözünün yaxın mənalısı hansıdır?','Cəsur və qorxmaz yaxın mənalıdır.',array['qorxmaz','qorxaq','yavaş','balaca'],1),
('az3-sifet#17','az-dili','az-3-sifet',2,2,'Hansı sırada əşyanın ölçüsünü bildirən sifətlər verilib?','Böyük, kiçik, uzun — ölçü bildirir.',array['böyük, kiçik, uzun','şirin, turş, duzlu','sarı, yaşıl, ağ','qaçmaq, gəlmək, getmək'],1),
('az3-sifet#18','az-dili','az-3-sifet',2,2,'«Təmiz otaq, səliqəli masa» birləşmələrindəki sifətlər nəyi bildirir?','Təmiz və səliqəli — əşyanın əlamətini bildirir.',array['Əlaməti','Hərəkəti','Sayı','Yeri'],1),
('az3-sifet#19','az-dili','az-3-sifet',2,2,'«Uzun — qısa» cütü nəyə misaldır?','Bir-birinin əksini bildirən sifətlərdir.',array['Əks mənalı sifətlərə','Yaxın mənalı sifətlərə','Fellərə','Xüsusi isimlərə'],1),
('az3-sifet#20','az-dili','az-3-sifet',2,2,'Hansı söz insanın xasiyyətini bildirən sifətdir?','«Mehriban» insanın xasiyyətini bildirir.',array['mehriban','taxta','qaçmaq','beş'],1),
('az3-fel#1','az-dili','az-3-fel',1,2,'Fel nəyi bildirir?','Fel hərəkəti bildirir.',array['Hərəkəti','Əşyanın adını','Əlaməti','Miqdarı'],1),
('az3-fel#2','az-dili','az-3-fel',1,2,'Hansı söz feldir?','«Oxumaq» hərəkət bildirir: nə etmək?',array['oxumaq','kitab','maraqlı','səhifə'],1),
('az3-fel#3','az-dili','az-3-fel',1,2,'Fellər hansı suallara cavab verir?','Fellər «nə edir? nə etdi? nə edəcək?» suallarına cavab verir.',array['Nə edir?','Kim? Nə?','Necə?','Hansı?'],1),
('az3-fel#4','az-dili','az-3-fel',2,2,'«Quş yuvasına uçur» cümləsində fel hansıdır?','Quş nə edir? — uçur.',array['uçur','quş','yuvasına','cümlədə fel yoxdur'],1),
('az3-fel#5','az-dili','az-3-fel',2,2,'Hansı sırada yalnız fellər verilib?','Gəlmək, getmək, baxmaq — hamısı hərəkət bildirir.',array['gəlmək, getmək, baxmaq','gəlmək, yol, uzaq','baxmaq, göz, iri','getmək, ayaq, tez'],1),
('az3-fel#6','az-dili','az-3-fel',3,2,'«Getmək» felinin inkarı hansıdır?','Felin inkarı -ma, -mə şəkilçisi ilə düzəlir: getməmək.',array['getməmək','gəlmək','getdi','gedəcək'],1),
('az3-fel#7','az-dili','az-3-fel',2,2,'Cümləni tamamlayın: «Şagirdlər şeiri əzbər …»','Cümləni fel tamamlayır: deyirlər.',array['deyirlər','kitab','maraqlı','məktəb'],1),
('az3-fel#8','az-dili','az-3-fel',3,2,'Hansı söz fel DEYİL?','«Qaçış» hərəkətin adıdır — isimdir; qalanları feldir.',array['qaçış','qaçmaq','tullanmaq','üzmək'],1),
('az3-fel#9','az-dili','az-3-fel',1,2,'«Danışmaq, gülmək, oxumaq» sözlərinin ümumi cəhəti nədir?','Hər üçü hərəkət bildirir — feldir.',array['Hamısı feldir','Hamısı isimdir','Hamısı sifətdir','Heç bir ümumi cəhəti yoxdur'],1),
('az3-fel#10','az-dili','az-3-fel',2,2,'«Külək bərk əsir» cümləsindəki feli göstərin.','Külək nə edir? — əsir.',array['əsir','külək','bərk','cümlədə fel yoxdur'],1),
('az3-fel#11','az-dili','az-3-fel',2,2,'«Yazmaq» felinin inkar forması necədir?','İnkar -ma, -mə şəkilçisi ilə düzəlir: yazmamaq.',array['yazmamaq','yazmaq','yazıçı','yazı'],1),
('az3-fel#12','az-dili','az-3-fel',1,2,'Hansı söz əşyanın hərəkətini deyil, adını bildirir?','«Stol» əşya adıdır, isimdir.',array['stol','qaçmaq','oxumaq','gülmək'],1),
('az3-fel#13','az-dili','az-3-fel',2,2,'«Uşaqlar həyətdə top oynayırlar» cümləsində fel hansıdır?','Hərəkəti «oynayırlar» sözü bildirir.',array['oynayırlar','uşaqlar','həyətdə','top'],1),
('az3-fel#14','az-dili','az-3-fel',2,2,'Fellər cümlədə adətən hansı üzv olur?','Hərəkət bildirən söz adətən xəbər olur.',array['Xəbər','Mübtəda','Başlıq','Şəkilçi'],1),
('az3-fel#15','az-dili','az-3-fel',2,2,'Hansı sırada bütün sözlər hərəkət bildirir?','Qaçmaq, tullanmaq, üzmək — hamısı feldir.',array['qaçmaq, tullanmaq, üzmək','qaçmaq, sürətli, meydan','top, oyun, uşaq','yaşıl, hündür, dar'],1),
('az3-fel#16','az-dili','az-3-fel',1,2,'«Danışır» sözünə «nə edir?» sualını vermək olarmı?','Bəli, fel «nə edir?» sualına cavab verir.',array['Bəli','Xeyr','Yalnız şeirdə','Yalnız yazıda'],1),
('az3-fel#17','az-dili','az-3-fel',2,2,'«Gülmək» sözünün əks mənalısı hansıdır?','Gülmək — ağlamaq əks mənalı fellərdir.',array['ağlamaq','sevinmək','qaçmaq','danışmaq'],1),
('az3-fel#18','az-dili','az-3-fel',1,2,'Cümləni tamamlayın: «Balıqlar suda …»','Balıqların hərəkətini «üzürlər» feli bildirir.',array['üzürlər','uçurlar','qaçırlar','yazırlar'],1),
('az3-fel#19','az-dili','az-3-fel',3,2,'«Oxu!» sözü nəyi bildirir?','Bu forma hərəkətə çağırış — əmr bildirir.',array['Əmri (hərəkətə çağırışı)','Sual verməyi','Əşyanın adını','Rəngi'],1),
('az3-fel#20','az-dili','az-3-fel',3,2,'Keçmişdə baş vermiş hərəkəti hansı söz bildirir?','«Gəldi» hərəkətin artıq baş verdiyini göstərir.',array['gəldi','gələcək','gəlir','gəl'],1),
('az3-soz-novleri#1','az-dili','az-3-soz-novleri',1,3,'Əşyanın adını bildirən sözlər necə adlanır?','Ad bildirən sözlər isimdir.',array['İsimlər','Sifətlər','Fellər','Saylar'],1),
('az3-soz-novleri#2','az-dili','az-3-soz-novleri',2,3,'«Sarı» sözü hansı söz növüdür?','Rəng əlamətdir — sifətdir.',array['Sifət','İsim','Fel','Say'],1),
('az3-soz-novleri#3','az-dili','az-3-soz-novleri',2,3,'«Uçmaq» sözü hansı nitq hissəsinə aiddir?','Hərəkət bildirir — feldir.',array['Fel','İsim','Sifət','Say'],1),
('az3-soz-novleri#4','az-dili','az-3-soz-novleri',3,3,'Hansı cərgədə «isim, sifət, fel» ardıcıllığı düzgündür?','Ev — isim, geniş — sifət, tikmək — fel.',array['ev, geniş, tikmək','geniş, ev, tikmək','tikmək, geniş, ev','ev, tikmək, geniş'],1),
('az3-soz-novleri#5','az-dili','az-3-soz-novleri',1,3,'Əlamət bildirən sözü seçin.','«Ağıllı» — necə? sualına cavab verir.',array['ağıllı','uşaq','oxuyur','on'],1),
('az3-soz-novleri#6','az-dili','az-3-soz-novleri',1,3,'Hərəkət bildirən sözü seçin.','«Üzmək» — nə etmək? sualına cavab verir.',array['üzmək','üzgüçü','sürətli','hovuz'],1),
('az3-soz-novleri#7','az-dili','az-3-soz-novleri',3,3,'«Beş» sözü nəyi bildirir?','«Beş» miqdar bildirir — saydır.',array['Miqdarı','Əlaməti','Hərəkəti','Əşyanın adını'],1),
('az3-soz-novleri#8','az-dili','az-3-soz-novleri',2,3,'«Qırmızı alma budaqdan düşdü» cümləsində hansı söz isimdir?','«Alma» əşya adıdır (budaq da isimdir).',array['alma','qırmızı','düşdü','cümlədə isim yoxdur'],1),
('az3-soz-novleri#9','az-dili','az-3-soz-novleri',2,3,'«Kitabxana» sözü hansı söz növüdür?','Yer adıdır — isimdir.',array['İsim','Sifət','Fel','Say'],1),
('az3-soz-novleri#10','az-dili','az-3-soz-novleri',3,3,'Hansı cüt «sifət + isim» qəlibinə uyğundur?','Uzun (necə?) + yol (nə?).',array['uzun yol','yol getmək','tez qaçmaq','beş kitab'],1),
('az3-soz-novleri#11','az-dili','az-3-soz-novleri',2,3,'«Sürətli qatar yola düşdü» cümləsində sifət hansıdır?','«Sürətli» qatarın əlamətini bildirir.',array['sürətli','qatar','yola','düşdü'],1),
('az3-soz-novleri#12','az-dili','az-3-soz-novleri',3,3,'«Dünən», «bu gün», «sabah» sözləri nəyi bildirir?','Bu sözlər hərəkətin zamanını bildirir.',array['Zamanı','Rəngi','Dadı','Əşyanın adını'],1),
('az3-soz-novleri#13','az-dili','az-3-soz-novleri',1,3,'Say bildirən sözü seçin.','«On» miqdar bildirən saydır.',array['on','hündür','yazmaq','quş'],1),
('az3-soz-novleri#14','az-dili','az-3-soz-novleri',2,3,'«Düşünmək» sözü hansı söz növüdür?','Hərəkət bildirir — feldir.',array['Fel','Sifət','Say','Şəkilçi'],1),
('az3-soz-novleri#15','az-dili','az-3-soz-novleri',2,3,'Miqdar bildirən sözlərə misal hansıdır?','İki, beş, on — miqdar bildirir.',array['iki, beş, on','ev, yol, su','gözəl, dar, isti','gəlmək, getmək'],1),
('az3-soz-novleri#16','az-dili','az-3-soz-novleri',2,3,'«Oxumaq, yazmaq, saymaq» sözləri hansı qrupdandır?','Hamısı hərəkət bildirir — feldir.',array['Fellər','İsimlər','Sifətlər','Saylar'],1),
('az3-soz-novleri#17','az-dili','az-3-soz-novleri',3,3,'Hansı cüt «isim + fel» qəlibinə uyğundur?','«Quş» isim, «uçur» feldir.',array['quş uçur','yaşıl çəmən','uzun yol','şirin çay'],1),
('az3-soz-novleri#18','az-dili','az-3-soz-novleri',2,3,'«Gözəl» və «çirkin» sözləri bir-birinə görə necədir?','Bir-birinin əksini bildirir.',array['Əks mənalıdır','Yaxın mənalıdır','Eyni sözdür','Hər ikisi feldir'],1),
('az3-soz-novleri#19','az-dili','az-3-soz-novleri',2,3,'«Ağ, boz, yaşıl» sözlərinin ümumi cəhəti nədir?','Hamısı rəng bildirən sifətdir.',array['Hamısı rəng bildirir','Hamısı feldir','Hamısı əşya adıdır','Hamısı saydır'],1),
('az3-soz-novleri#20','az-dili','az-3-soz-novleri',3,3,'Əşyanın sırasını bildirən söz hansıdır?','«Üçüncü» sıra bildirir.',array['üçüncü','üzmək','uca','usta'],1),
('az3-cumle#1','az-dili','az-3-cumle',1,3,'Cümlə nədir?','Cümlə bitmiş fikir bildirir.',array['Bitmiş fikir bildirən söz və ya söz birləşməsi','Hərflərin yığını','Təkcə bir söz','Şəkilçilər toplusu'],1),
('az3-cumle#2','az-dili','az-3-cumle',2,3,'Cümlənin baş üzvləri hansılardır?','Baş üzvlər mübtəda və xəbərdir.',array['Mübtəda və xəbər','İsim və sifət','Söz və heca','Sual və cavab'],1),
('az3-cumle#3','az-dili','az-3-cumle',2,3,'«Yarpaqlar töküldü» cümləsində mübtəda hansıdır?','Tökülən nədir? — Yarpaqlar.',array['Yarpaqlar','töküldü','hər ikisi','heç biri'],1),
('az3-cumle#4','az-dili','az-3-cumle',2,3,'«Uşaq şirin-şirin gülür» cümləsində xəbər hansıdır?','Uşaq nə edir? — gülür.',array['gülür','Uşaq','şirin-şirin','cümlədə xəbər yoxdur'],1),
('az3-cumle#5','az-dili','az-3-cumle',1,3,'Cümlənin birinci sözü necə yazılır?','Cümlə böyük hərflə başlanır.',array['Böyük hərflə başlanır','Kiçik hərflə yazılır','İxtisarla','Rəqəmlə'],1),
('az3-cumle#6','az-dili','az-3-cumle',2,3,'Azərbaycan dilində xəbər adətən cümlənin harasında olur?','Xəbər adətən cümlənin sonunda gəlir.',array['Sonunda','Əvvəlində','Ortasında','Qaydası yoxdur'],1),
('az3-cumle#7','az-dili','az-3-cumle',2,3,'Hansı yazılış cümlədir?','«Qar yağdı.» — bitmiş fikirdir.',array['Qar yağdı.','sürətli qaçmaq','gözəl hava','mavi səma'],1),
('az3-cumle#8','az-dili','az-3-cumle',3,3,'«Anam bazardan təzə meyvə aldı» cümləsində mübtəda hansıdır?','Alan kimdir? — Anam.',array['Anam','bazardan','meyvə','aldı'],1),
('az3-cumle#9','az-dili','az-3-cumle',2,3,'Cümlənin neçə baş üzvü var?','İki baş üzv: mübtəda və xəbər.',array['İki (mübtəda və xəbər)','Bir','Üç','Beş'],1),
('az3-cumle#10','az-dili','az-3-cumle',3,3,'«Oxuyur» sözü cümlədə adətən hansı üzv olur?','Fel cümlədə əsasən xəbər olur.',array['Xəbər','Mübtəda','Üzv olmur','Başlıq'],1),
('az3-cumle#11','az-dili','az-3-cumle',2,3,'«Şagirdlər kitab oxuyurlar» cümləsində xəbər hansıdır?','Hərəkəti bildirən «oxuyurlar» sözü xəbərdir.',array['oxuyurlar','şagirdlər','kitab','cümlə'],1),
('az3-cumle#12','az-dili','az-3-cumle',2,3,'«Kim?» sualına cavab verən baş üzv hansıdır?','Mübtəda «kim?», «nə?» suallarına cavab verir.',array['Mübtəda','Xəbər','Sifət','Şəkilçi'],1),
('az3-cumle#13','az-dili','az-3-cumle',2,3,'«Bu gün hava çox gözəldir» cümləsində mübtəda hansıdır?','«Nə?» sualına «hava» sözü cavab verir.',array['hava','bu gün','çox','gözəldir'],1),
('az3-cumle#14','az-dili','az-3-cumle',2,3,'Cümlədə sözlər arasında hansı əlaqə olmalıdır?','Sözlər bir-biri ilə məna əlaqəsinə girərək fikir bildirir.',array['Məna əlaqəsi','Heç bir əlaqə','Yalnız səs oxşarlığı','Yalnız uzunluq'],1),
('az3-cumle#15','az-dili','az-3-cumle',2,3,'«Atam işdən gec qayıtdı» cümləsində xəbər hansıdır?','Hərəkəti «qayıtdı» sözü bildirir.',array['qayıtdı','atam','işdən','gec'],1),
('az3-cumle#16','az-dili','az-3-cumle',2,3,'Hansı yazılış cümlə DEYİL?','Sadəcə sözlərin dalbadal düzülüşü fikir bildirmir.',array['yaşıl, meşə, uca','Qar yağır.','Uşaqlar oynayır.','Bahar gəldi.'],1),
('az3-cumle#17','az-dili','az-3-cumle',2,3,'«Balaca quş budağa qondu» cümləsində mübtəda hansıdır?','«Nə?» sualına «quş» sözü cavab verir.',array['quş','balaca','budağa','qondu'],1),
('az3-cumle#18','az-dili','az-3-cumle',1,3,'Cümləni tamamlayın: «Qışda hava …»','Fikri «soyuq olur» sözləri tamamlayır.',array['soyuq olur','kitab oxuyur','yaşıl rəngdədir','hecaya bölünür'],1),
('az3-cumle#19','az-dili','az-3-cumle',3,3,'«Uşaqlar bağda gül əkdilər» cümləsində hərəkətin yerini bildirən söz hansıdır?','«Harada?» sualına «bağda» sözü cavab verir.',array['bağda','uşaqlar','gül','əkdilər'],1),
('az3-cumle#20','az-dili','az-3-cumle',2,3,'«dərs», «başladı», «saat 9-da» sözlərindən düzgün cümlə qurun.','Sözlər məna ardıcıllığı ilə düzülür.',array['Dərs saat 9-da başladı.','Başladı dərs saat 9-da.','Saat başladı 9-da dərs.','Dərs başladı saat.'],1),
('az3-yazi-qaydasi#1','az-dili','az-3-yazi-qaydasi',2,4,'Düzgün yazılışı seçin.','Düzgün yazılış: məktəb.',array['məktəb','məktəp','mektəb','məktap'],1),
('az3-yazi-qaydasi#2','az-dili','az-3-yazi-qaydasi',1,4,'Xüsusi isimlər hansı hərflə başlanır?','Şəxs, şəhər, çay adları böyük hərflə yazılır.',array['Böyük hərflə','Kiçik hərflə','İstənilən hərflə','Saitlə'],1),
('az3-yazi-qaydasi#3','az-dili','az-3-yazi-qaydasi',2,4,'Söz sətirdən sətrə necə keçirilir?','Söz yalnız hecalarla keçirilir.',array['Hecalarla','Hərf-hərf','İstənilən yerdən','Keçirmək olmaz'],1),
('az3-yazi-qaydasi#4','az-dili','az-3-yazi-qaydasi',3,4,'Ay adları (yanvar, mart…) necə yazılır?','Ay adları kiçik hərflə yazılır.',array['Kiçik hərflə','Böyük hərflə','Dırnaqda','Rəqəmlə'],1),
('az3-yazi-qaydasi#5','az-dili','az-3-yazi-qaydasi',1,4,'Nəqli cümlə hansı işarə ilə bitir?','Adi məlumat bildirən cümlənin sonunda nöqtə qoyulur.',array['Nöqtə ilə','Sual işarəsi ilə','Vergüllə','Tire ilə'],1),
('az3-yazi-qaydasi#6','az-dili','az-3-yazi-qaydasi',2,4,'«Kitab» sözü hecalara necə bölünür?','Ki-tab: iki heca.',array['ki-tab','kit-ab','k-itab','kita-b'],1),
('az3-yazi-qaydasi#7','az-dili','az-3-yazi-qaydasi',2,4,'«Dovşan» sözündə neçə heca var?','Saitlər: o, a — iki sait, deməli iki heca.',array['2','3','1','4'],1),
('az3-yazi-qaydasi#8','az-dili','az-3-yazi-qaydasi',3,4,'Hansı sözü sətirdən sətrə keçirmək olmaz?','Birhecalı sözlər keçirilmir.',array['el','ana','kitab','dəftər'],1),
('az3-yazi-qaydasi#9','az-dili','az-3-yazi-qaydasi',3,4,'«günəş» sözü nə vaxt böyük hərflə yazılır?','Şəxs adı olanda: Günəş adlı qız.',array['Şəxs adı olanda','Cəmdə olanda','Heç vaxt','Həmişə'],1),
('az3-yazi-qaydasi#10','az-dili','az-3-yazi-qaydasi',2,4,'«Ananas» sözündə neçə heca var?','Saitlər: a, a, a — üç heca: a-na-nas.',array['3','2','4','6'],1),
('az3-yazi-qaydasi#11','az-dili','az-3-yazi-qaydasi',2,4,'«Qələm» sözü hecalara necə bölünür?','İki heca: qə-ləm.',array['qə-ləm','q-ələm','qəl-əm','qələ-m'],1),
('az3-yazi-qaydasi#12','az-dili','az-3-yazi-qaydasi',2,4,'Həftənin günləri (bazar ertəsi, çərşənbə…) necə yazılır?','Həftə günlərinin adları kiçik hərflə yazılır.',array['Kiçik hərflə','Həmişə böyük hərflə','Dırnaqda','Defislə'],1),
('az3-yazi-qaydasi#13','az-dili','az-3-yazi-qaydasi',1,4,'«Salam» sözü hecalara necə bölünür?','İki heca: sa-lam.',array['sa-lam','s-alam','sal-am','sala-m'],1),
('az3-yazi-qaydasi#14','az-dili','az-3-yazi-qaydasi',1,4,'«Sən hara gedirsən» cümləsinin sonunda hansı işarə olmalıdır?','Cümlə sual bildirir — sual işarəsi qoyulur.',array['Sual işarəsi','Nöqtə','Vergül','Defis'],1),
('az3-yazi-qaydasi#15','az-dili','az-3-yazi-qaydasi',3,4,'Sətirdən sətrə keçirmədə hansı bölgü SƏHVDİR?','Bir hərfi tək saxlamaq olmaz: k-itab səhvdir.',array['k-itab','ki-tab','dəf-tər','qə-ləm'],1),
('az3-yazi-qaydasi#16','az-dili','az-3-yazi-qaydasi',3,4,'«Ağac» sözünü sətirdən sətrə keçirmək olarmı?','«A-ğac» bölgüsündə bir hərf tək qalır — keçirmək olmaz.',array['Keçirmək olmaz','a-ğac kimi olar','ağ-ac kimi olar','İstənilən yerdən olar'],1),
('az3-yazi-qaydasi#17','az-dili','az-3-yazi-qaydasi',2,4,'«Nə gözəl mənzərə!» cümləsinin sonundakı işarə hansıdır?','Hiss-həyəcan bildirən cümlə nida işarəsi ilə bitir.',array['Nida işarəsi','Nöqtə','Sual işarəsi','Vergül'],1),
('az3-yazi-qaydasi#18','az-dili','az-3-yazi-qaydasi',2,4,'Hansı yazılış düzgündür?','Söz «yağış» kimi yazılır.',array['yağış','yagış','yağiş','yaqış'],1),
('az3-yazi-qaydasi#19','az-dili','az-3-yazi-qaydasi',2,4,'Vergül cümlədə nə üçün işlənir?','Sadalanan sözlər vergüllə ayrılır.',array['Sadalanan sözləri ayırmaq üçün','Cümləni bitirmək üçün','Sual vermək üçün','Bəzək üçün'],1),
('az3-yazi-qaydasi#20','az-dili','az-3-yazi-qaydasi',2,4,'«Əli bakıya getdi» cümləsindəki səhv nədir?','Şəhər adı xüsusi isimdir: Bakı böyük hərflə yazılmalıdır.',array['«Bakı» böyük hərflə yazılmalıdır','«Əli» kiçik yazılmalıdır','Nöqtə artıqdır','Səhv yoxdur'],1),
('az3-metn#1','az-dili','az-3-metn',2,4,'Mətni adi cümlələr yığınından fərqləndirən nədir?','Mətndə cümlələr məzmunca bir-biri ilə bağlıdır.',array['Cümlələrin məzmunca bağlılığı','Cümlələrin sayı','Sözlərin uzunluğu','Şəkilli olması'],1),
('az3-metn#2','az-dili','az-3-metn',2,4,'Mətnin başlığı nəyə uyğun seçilir?','Başlıq mətnin məzmununa uyğun olmalıdır.',array['Məzmuna','İlk hərfə','Cümlə sayına','Müəllifin adına'],1),
('az3-metn#3','az-dili','az-3-metn',2,4,'Nitq neçə cür olur?','Nitq şifahi və yazılı olur.',array['Şifahi və yazılı','Yalnız şifahi','Yalnız yazılı','Sürətli və yavaş'],1),
('az3-metn#4','az-dili','az-3-metn',1,4,'Hansı, şifahi nitqə aiddir?','Danışıq şifahi nitqdir.',array['Nağıl danışmaq','Məktub yazmaq','İnşa yazmaq','Dəftərə köçürmək'],1),
('az3-metn#5','az-dili','az-3-metn',2,4,'Hansı, yazılı nitqə aiddir?','Məktub yazmaq yazılı nitqdir.',array['Məktub yazmaq','Telefonla danışmaq','Mahnı oxumaq','Sual vermək'],1),
('az3-metn#6','az-dili','az-3-metn',2,4,'Mətndə cümlələr necə düzülməlidir?','Cümlələr məntiqi ardıcıllıqla düzülür.',array['Ardıcıl, məntiqi','Qarışıq','Uzunluğa görə','Əlifba sırası ilə'],1),
('az3-metn#7','az-dili','az-3-metn',1,4,'Həmsöhbəti dinləyərkən nə etmək düzgündür?','Sözünü kəsməmək hörmətin əlamətidir.',array['Sözünü kəsməmək','Ucadan danışmaq','Üzünə baxmamaq','Telefonla oynamaq'],1),
('az3-metn#8','az-dili','az-3-metn',2,4,'Mətn adətən neçə hissədən ibarət olur?','Giriş, əsas hissə, nəticə — üç hissə.',array['3 (giriş, əsas, nəticə)','1','5','10'],1),
('az3-metn#9','az-dili','az-3-metn',1,4,'Telefonla danışığa nədən başlamaq lazımdır?','Əvvəlcə salamlaşırlar.',array['Salamlaşmaqdan','Şikayətdən','Sağollaşmaqdan','Sualdan'],1),
('az3-metn#10','az-dili','az-3-metn',2,4,'Nağıl danışmaq hansı nitq növüdür?','Danışıq — şifahi nitqdir.',array['Şifahi','Yazılı','Heç biri','Hər ikisi'],1),
('az3-metn#11','az-dili','az-3-metn',2,4,'Mətnin hissələri hansı ardıcıllıqla düzülür?','Mətn giriş, əsas hissə və nəticədən ibarətdir.',array['Giriş, əsas hissə, nəticə','Nəticə, giriş, əsas hissə','Yalnız giriş','İstənilən qarışıq sıra'],1),
('az3-metn#12','az-dili','az-3-metn',2,4,'Məktub yazmaq hansı nitq növüdür?','Yazıya köçürülən nitq yazılı nitqdir.',array['Yazılı','Şifahi','Səssiz','Təsviri'],1),
('az3-metn#13','az-dili','az-3-metn',2,4,'Mətnə başlıq nə üçün qoyulur?','Başlıq mətnin məzmununu qısa şəkildə bildirir.',array['Məzmunu qısa bildirmək üçün','Mətni uzatmaq üçün','Bəzək üçün','Sətirləri saymaq üçün'],1),
('az3-metn#14','az-dili','az-3-metn',1,4,'Dinləyərkən başqasının sözünü kəsmək necə qiymətləndirilir?','Sözü kəsmək nəzakətsizlikdir.',array['Ədəbsizlik kimi','Nəzakət kimi','Kömək kimi','Diqqət kimi'],1),
('az3-metn#15','az-dili','az-3-metn',2,4,'Şifahi nitqə aid olanı seçin.','Şeir söyləmək danışıqla ifadə olunur.',array['Şeir söyləmək','İnşa yazmaq','Məktub yazmaq','İmla yazmaq'],1),
('az3-metn#16','az-dili','az-3-metn',2,4,'Mətndəki cümlələr nə ilə bağlıdır?','Bütün cümlələr ümumi mövzuya xidmət edir.',array['Ümumi mövzu ilə','Eyni hərflə','Eyni uzunluqla','Heç nə ilə'],1),
('az3-metn#17','az-dili','az-3-metn',1,4,'Telefon danışığını necə bitirmək düzgündür?','Danışıq sağollaşma ilə bitirilir.',array['Sağollaşmaqla','Səssiz qapatmaqla','Qışqırmaqla','Sualla'],1),
('az3-metn#18','az-dili','az-3-metn',2,4,'Nağılı dinləyib məzmununu danışmaq nəyi inkişaf etdirir?','Yenidən danışma nitqi və yaddaşı gücləndirir.',array['Nitqi və yaddaşı','Yalnız əl yazısını','Sürəti','Boyu'],1),
('az3-metn#19','az-dili','az-3-metn',3,4,'Mətn tərtib edərkən birinci nə müəyyənləşdirilir?','Əvvəlcə nə haqqında yazacağını — mövzunu seç.',array['Mövzu','Vergüllər','Sətir sayı','Şrift'],1),
('az3-metn#20','az-dili','az-3-metn',1,4,'Salamlaşmaq nəyin əlamətidir?','Salam vermək nəzakət qaydasıdır.',array['Nəzakətin','Tənbəlliyin','Qorxunun','Tələskənliyin'],1),
('hey3-cemiyyet#1','hayat-bilgisi','hey-3-cemiyyet',1,1,'Cəmiyyətdə insanlar bir-biri ilə necə davranmalıdır?','Qarşılıqlı hörmət cəmiyyətin təməlidir.',array['Hörmətlə','Biganə','Kobud','Yalnız tanışlarla nəzakətli'],1),
('hey3-cemiyyet#2','hayat-bilgisi','hey-3-cemiyyet',1,1,'Məktəb qaydalarına kim əməl etməlidir?','Qaydalar hamı üçündür.',array['Bütün şagirdlər','Yalnız növbətçilər','Yalnız birincilər','Heç kim'],1),
('hey3-cemiyyet#3','hayat-bilgisi','hey-3-cemiyyet',2,1,'Növbəyə riayət etmək nəyin əlamətidir?','Növbə gözləmək mədəni davranışdır.',array['Mədəniyyətin','Zəifliyin','Tələsməyin','Qorxaqlığın'],1),
('hey3-cemiyyet#4','hayat-bilgisi','hey-3-cemiyyet',2,1,'Kollektiv nədir?','Bir məqsəd üçün birgə çalışan insanlar kollektivdir.',array['Birgə fəaliyyət göstərən insanlar','Bir nəfər','Binaların cəmi','Yalnız qonşular'],1),
('hey3-cemiyyet#5','hayat-bilgisi','hey-3-cemiyyet',1,1,'Hansı davranış SƏHVDİR?','İctimai yerdə ucadan qışqırmaq başqalarını narahat edir.',array['Avtobusda ucadan qışqırmaq','Salam vermək','Növbə gözləmək','Zibili qutuya atmaq'],1),
('hey3-cemiyyet#6','hayat-bilgisi','hey-3-cemiyyet',2,1,'Nəqliyyatda kimə yer vermək lazımdır?','Yaşlılara, uşaqlı sərnişinlərə yer verilir.',array['Yaşlılara və körpəli sərnişinlərə','Heç kimə','Yalnız dostlara','Sürücüyə'],1),
('hey3-cemiyyet#7','hayat-bilgisi','hey-3-cemiyyet',2,1,'Dostluq nəyə əsaslanır?','Əsl dostluq etibar və sədaqət üzərində qurulur.',array['Etibara və sədaqətə','Hədiyyələrə','Qorxuya','Paxıllığa'],1),
('hey3-cemiyyet#8','hayat-bilgisi','hey-3-cemiyyet',1,1,'Ailə üzvlərinə kömək etmək kimin borcudur?','Ev işlərində hamı iştirak etməlidir.',array['Hər bir ailə üzvünün','Yalnız ananın','Yalnız uşaqların','Qonaqların'],1),
('hey3-cemiyyet#9','hayat-bilgisi','hey-3-cemiyyet',2,1,'Hansı, milli adət-ənənələrimizə aiddir?','Novruzda tonqal qalamaq qədim adətimizdir.',array['Novruzda tonqal qalamaq','Qonağı qarşılamamaq','Böyüyə salam verməmək','Süfrəni yığışdırmamaq'],1),
('hey3-cemiyyet#10','hayat-bilgisi','hey-3-cemiyyet',2,1,'Kiçiklərə münasibət necə olmalıdır?','Kiçiklərə qayğı göstərmək böyüklüyün əlamətidir.',array['Qayğı ilə','Biganə','Kobud','Əmrlə'],1),
('hey3-cemiyyet#11','hayat-bilgisi','hey-3-cemiyyet',1,1,'İctimai yerlərdə hansı davranış düzgündür?','İctimai yerdə sakit və nəzakətli olmaq lazımdır.',array['Sakit və nəzakətli olmaq','Ucadan qışqırmaq','Zibil atmaq','İtələşmək'],1),
('hey3-cemiyyet#12','hayat-bilgisi','hey-3-cemiyyet',1,1,'Başqasının əşyasını götürməzdən əvvəl nə etməli?','Sahibindən icazə almaq lazımdır.',array['İcazə almaq','Gizlətmək','Səssiz götürmək','Qaçmaq'],1),
('hey3-cemiyyet#13','hayat-bilgisi','hey-3-cemiyyet',1,1,'Qonşularla münasibət necə olmalıdır?','Qonşularla mehriban davranmaq lazımdır.',array['Mehriban','Kobud','Laqeyd','Paxıl'],1),
('hey3-cemiyyet#14','hayat-bilgisi','hey-3-cemiyyet',2,1,'Sinifdə növbətçinin vəzifəsi nədir?','Növbətçi sinfin səliqəsinə cavabdehdir.',array['Sinfin səliqəsinə baxmaq','Dərsi izah etmək','Qiymət yazmaq','Zəngi çalmaq'],1),
('hey3-cemiyyet#15','hayat-bilgisi','hey-3-cemiyyet',2,1,'«Salam», «təşəkkür», «bağışlayın» sözləri necə adlanır?','Bunlar nəzakət sözləridir.',array['Nəzakət sözləri','Fellər','Xüsusi isimlər','Saylar'],1),
('hey3-cemiyyet#16','hayat-bilgisi','hey-3-cemiyyet',2,1,'Kollektivdə mübahisəni necə həll etmək düzgündür?','Sakit danışıb razılığa gəlmək düzgün yoldur.',array['Danışıb razılığa gəlməklə','Dava ilə','Küsməklə','Qışqırmaqla'],1),
('hey3-cemiyyet#17','hayat-bilgisi','hey-3-cemiyyet',1,1,'Yaşlı adam avtobusa minəndə nə etməlisən?','Yaşlılara yer vermək hörmət əlamətidir.',array['Yerimi verməliyəm','Görməzliyə vurmalıyam','Pəncərəyə baxmalıyam','Gülməliyəm'],1),
('hey3-cemiyyet#18','hayat-bilgisi','hey-3-cemiyyet',2,1,'Verilmiş sözün üstündə durmaq nəyin əlamətidir?','Sözünə əməl edən adam etibarlıdır.',array['Etibarlılığın','Zəifliyin','Qorxaqlığın','Tənbəlliyin'],1),
('hey3-cemiyyet#19','hayat-bilgisi','hey-3-cemiyyet',2,1,'Məktəb əmlakını qorumaq kimin vəzifəsidir?','Partaları, kitabları hər şagird qorumalıdır.',array['Hər bir şagirdin','Yalnız direktorun','Yalnız növbətçinin','Heç kimin'],1),
('hey3-cemiyyet#20','hayat-bilgisi','hey-3-cemiyyet',3,1,'Xeyriyyəçilik nə deməkdir?','Ehtiyacı olanlara təmənnasız kömək etməkdir.',array['Ehtiyacı olanlara təmənnasız kömək','Pul yığmaq','Alver etmək','Hədiyyə gözləmək'],1),
('hey3-saglamliq#1','hayat-bilgisi','hey-3-saglamliq',2,1,'Gündəlik rejimə nə daxildir?','Yuxu, qidalanma, dərs və istirahət vaxtlarının bölgüsü.',array['Yuxu, qida və məşğuliyyət vaxtları','Yalnız oyun','Yalnız yemək','Yalnız dərs'],1),
('hey3-saglamliq#2','hayat-bilgisi','hey-3-saglamliq',1,1,'Səhər idmanı orqanizmə nə verir?','Səhər hərəkəti bədəni gümrahlaşdırır.',array['Gümrahlıq','Yorğunluq','Yuxusuzluq','Heç nə'],1),
('hey3-saglamliq#3','hayat-bilgisi','hey-3-saglamliq',1,1,'Dişləri gündə neçə dəfə fırçalamaq lazımdır?','Səhər və axşam — 2 dəfə.',array['2 dəfə','Həftədə 1 dəfə','Ayda 2 dəfə','Heç fırçalamamaq'],1),
('hey3-saglamliq#4','hayat-bilgisi','hey-3-saglamliq',2,1,'Vitaminlər ən çox hansı qidalarda olur?','Meyvə və tərəvəz vitamin mənbəyidir.',array['Meyvə və tərəvəzdə','Şirniyyatda','Çipslərdə','Qazlı içkilərdə'],1),
('hey3-saglamliq#5','hayat-bilgisi','hey-3-saglamliq',2,1,'Gözləri qorumaq üçün nə etmək lazımdır?','Ekrana yaxından və uzun müddət baxmaq gözləri yorur.',array['Ekrana yaxından uzun baxmamaq','Qaranlıqda kitab oxumaq','Günəşə birbaşa baxmaq','Heç nə etməmək'],1),
('hey3-saglamliq#6','hayat-bilgisi','hey-3-saglamliq',1,1,'Yeməkdən əvvəl mütləq nə edilməlidir?','Əllər sabunla yuyulmalıdır.',array['Əllər yuyulmalıdır','Qaçmaq lazımdır','Yatmaq lazımdır','Su içmək olmaz'],1),
('hey3-saglamliq#7','hayat-bilgisi','hey-3-saglamliq',2,1,'Soyuqdəymədən qorunmaq üçün nə vacibdir?','Havaya uyğun geyinmək lazımdır.',array['Havaya uyğun geyinmək','Nazik geyinmək','Buzlu su içmək','Papaqsız gəzmək'],1),
('hey3-saglamliq#8','hayat-bilgisi','hey-3-saglamliq',2,1,'Uzun müddət fasiləsiz telefonda oynamaq nəyə zərərdir?','Gözlərə və qamətə zərər verir.',array['Gözlərə və qamətə','Heç nəyə','Yalnız telefona','Yalnız ayaqlara'],1),
('hey3-saglamliq#9','hayat-bilgisi','hey-3-saglamliq',1,1,'Təmiz havada gəzinti insana nə verir?','Təmiz hava sağlamlığı möhkəmləndirir.',array['Sağlamlıq və gümrahlıq','Xəstəlik','Yorğunluq','Qorxu'],1),
('hey3-saglamliq#10','hayat-bilgisi','hey-3-saglamliq',2,1,'Mütəmadi idman nəyi möhkəmləndirir?','İdman əzələləri və iradəni gücləndirir.',array['Əzələləri və iradəni','Yalnız səsi','Yalnız yaddaşı','Heç nəyi'],1),
('hey3-saglamliq#11','hayat-bilgisi','hey-3-saglamliq',2,1,'Gün ərzində neçə dəfə yemək məsləhətdir?','Gündə 3-4 dəfə az-az yemək faydalıdır.',array['3-4 dəfə','1 dəfə','10 dəfə','Heç yeməmək'],1),
('hey3-saglamliq#12','hayat-bilgisi','hey-3-saglamliq',2,1,'Yatmazdan əvvəl hansı vərdiş faydalıdır?','Təmiz hava yuxunu yaxşılaşdırır.',array['Otağı havalandırmaq','Çox şirniyyat yemək','Telefonla oynamaq','Qəhvə içmək'],1),
('hey3-saglamliq#13','hayat-bilgisi','hey-3-saglamliq',1,1,'Qidalanmada nəyin çox olması zərərlidir?','Şirniyyatın çoxluğu dişlərə və orqanizmə zərərdir.',array['Şirniyyatın','Tərəvəzin','Meyvənin','Suyun'],1),
('hey3-saglamliq#14','hayat-bilgisi','hey-3-saglamliq',2,1,'İdman etməzdən əvvəl nə etmək lazımdır?','Əzələləri qızışdırmaq zədədən qoruyur.',array['Qızışma hərəkətləri','Çox yemək','Yatmaq','Soyuq su içmək'],1),
('hey3-saglamliq#15','hayat-bilgisi','hey-3-saglamliq',2,1,'Uşaq gündə təxminən neçə saat yatmalıdır?','Bu yaşda 9-10 saat yuxu lazımdır.',array['9-10 saat','3-4 saat','15-16 saat','1-2 saat'],1),
('hey3-saglamliq#16','hayat-bilgisi','hey-3-saglamliq',2,1,'Düzgün qamət üçün çantanı necə daşımaq lazımdır?','Çanta iki çiyində daşınmalıdır.',array['İki çiyində','Bir əldə sürüməklə','Başın üstündə','Boyunda'],1),
('hey3-saglamliq#17','hayat-bilgisi','hey-3-saglamliq',1,1,'Xəstələnəndə ilk növbədə kimə müraciət edilməlidir?','Böyüklərə deyib həkimə müraciət etmək lazımdır.',array['Böyüklərə və həkimə','Heç kimə','Dosta','Qonşu uşağa'],1),
('hey3-saglamliq#18','hayat-bilgisi','hey-3-saglamliq',2,1,'Səhər yeməyi niyə vacibdir?','Səhər yeməyi günə enerji verir.',array['Günə enerji verir','Yuxu gətirir','Vaxt aparır','Zərərlidir'],1),
('hey3-saglamliq#19','hayat-bilgisi','hey-3-saglamliq',2,1,'Güclü zökəm olanda məktəbə getmək düzgündürmü?','Xəstə halda evdə qalıb müalicə olunmaq lazımdır.',array['Xeyr, evdə müalicə olunmalı','Bəli, mütləq getməli','Fərqi yoxdur','Yalnız idman dərsinə'],1),
('hey3-saglamliq#20','hayat-bilgisi','hey-3-saglamliq',2,1,'Kompüter arxasında hər 30-40 dəqiqədən bir nə etmək lazımdır?','Fasilə verib gözləri dincəltmək lazımdır.',array['Fasilə verib gözləri dincəltmək','Səsi artırmaq','Ekrana yaxınlaşmaq','Yemək yemək'],1),
('hey3-yer-ay#1','hayat-bilgisi','hey-3-yer-ay',1,2,'Yer hansı formadadır?','Yer kürə formasındadır.',array['Kürə','Kvadrat','Düz lövhə','Üçbucaq'],1),
('hey3-yer-ay#2','hayat-bilgisi','hey-3-yer-ay',1,2,'Bizə işıq və istilik verən göy cismi hansıdır?','Günəş işıq və istilik mənbəyidir.',array['Günəş','Ay','Ulduzlar','Buludlar'],1),
('hey3-yer-ay#3','hayat-bilgisi','hey-3-yer-ay',2,2,'Ay nəyin peykidir?','Ay Yerin təbii peykidir.',array['Yerin','Günəşin','Marsın','Ulduzların'],1),
('hey3-yer-ay#4','hayat-bilgisi','hey-3-yer-ay',3,2,'Gecə və gündüz nəyə görə əmələ gəlir?','Yer öz oxu ətrafında fırlanır.',array['Yerin öz oxu ətrafında fırlanmasına görə','Günəşin sönməsinə görə','Ayın böyüməsinə görə','Buludların hərəkətinə görə'],1),
('hey3-yer-ay#5','hayat-bilgisi','hey-3-yer-ay',3,2,'Fəsillərin dəyişməsi nə ilə bağlıdır?','Yer Günəş ətrafında dövr edir.',array['Yerin Günəş ətrafında hərəkəti ilə','Küləklə','Ayın işığı ilə','Yağışla'],1),
('hey3-yer-ay#6','hayat-bilgisi','hey-3-yer-ay',2,2,'Yer Günəş ətrafında bir tam dövrü nə qədərə başa vurur?','Bir dövrə bir ilə başa gəlir.',array['1 ilə','1 günə','1 aya','1 saata'],1),
('hey3-yer-ay#7','hayat-bilgisi','hey-3-yer-ay',2,2,'Ay öz işığını yayırmı?','Ay Günəşin işığını əks etdirir.',array['Xeyr, Günəş işığını əks etdirir','Bəli, özü yanır','Yalnız qışda yayır','Yalnız gündüz yayır'],1),
('hey3-yer-ay#8','hayat-bilgisi','hey-3-yer-ay',2,2,'Qlobus nədir?','Qlobus Yerin kiçildilmiş modelidir.',array['Yerin kiçildilmiş modeli','Ayın xəritəsi','Oyuncaq top','Günəş saatı'],1),
('hey3-yer-ay#9','hayat-bilgisi','hey-3-yer-ay',1,2,'Yerin təbii peyki hansıdır?','Yerin bir təbii peyki var — Ay.',array['Ay','Günəş','Mars','Ulduz'],1),
('hey3-yer-ay#10','hayat-bilgisi','hey-3-yer-ay',1,2,'Gündüz göydə ən parlaq görünən göy cismi hansıdır?','Gündüz Günəş görünür.',array['Günəş','Ay','Ulduzlar','Planetlər'],1),
('hey3-yer-ay#11','hayat-bilgisi','hey-3-yer-ay',3,2,'Ayın Yer ətrafında tam dövrü nə qədər çəkir?','Ay Yer ətrafında təxminən bir aya dolanır.',array['Təxminən 1 ay','1 gün','1 saat','10 il'],1),
('hey3-yer-ay#12','hayat-bilgisi','hey-3-yer-ay',2,2,'Yerin öz oxu ətrafında tam dövrü nə qədər vaxt alır?','Bir tam dövr 24 saata — bir gün-gecəyə başa gəlir.',array['24 saat','1 il','1 həftə','12 saat'],1),
('hey3-yer-ay#13','hayat-bilgisi','hey-3-yer-ay',1,2,'Gecə göydə gördüyümüz parlaq nöqtələr nədir?','Onlar uzaq ulduzlardır.',array['Ulduzlar','Lampalar','Buludlar','Quşlar'],1),
('hey3-yer-ay#14','hayat-bilgisi','hey-3-yer-ay',2,2,'Xəritə nəyi təsvir edir?','Xəritə Yer səthini müstəvi üzərində göstərir.',array['Yer səthini müstəvi üzərində','Yalnız dənizləri','Yalnız evləri','Göy qurşağını'],1),
('hey3-yer-ay#15','hayat-bilgisi','hey-3-yer-ay',3,2,'Ayın görünüşünün dəyişməsi necə adlanır?','Ayın görünən hissəsinin dəyişməsi fazalar adlanır.',array['Ay fazaları','Günəş tutulması','Külək','Yağış'],1),
('hey3-yer-ay#16','hayat-bilgisi','hey-3-yer-ay',2,2,'Günəş hansı tərəfdən doğur?','Günəş şərqdən doğur, qərbdə batır.',array['Şərqdən','Qərbdən','Şimaldan','Cənubdan'],1),
('hey3-yer-ay#17','hayat-bilgisi','hey-3-yer-ay',2,2,'Yer səthinin böyük hissəsini nə tutur?','Yer səthinin çox hissəsi su ilə örtülüdür.',array['Su (okean və dənizlər)','Səhralar','Meşələr','Şəhərlər'],1),
('hey3-yer-ay#18','hayat-bilgisi','hey-3-yer-ay',3,2,'Kosmosa uçan ilk insan kimdir?','1961-ci ildə Yuri Qaqarin kosmosa uçub.',array['Yuri Qaqarin','Nizami Gəncəvi','Üzeyir Hacıbəyli','Xristofor Kolumb'],1),
('hey3-yer-ay#19','hayat-bilgisi','hey-3-yer-ay',2,2,'Yer hansı göy cisimləri qrupuna aiddir?','Yer Günəş ətrafında dolanan planetdir.',array['Planetlərə','Ulduzlara','Peyklərə','Kometlərə'],1),
('hey3-yer-ay#20','hayat-bilgisi','hey-3-yer-ay',2,2,'Gündüzün işıqlı olmasının səbəbi nədir?','Gündüz Yerin bizim tərəfimiz Günəşə baxır.',array['Günəş işığı','Ay işığı','Ulduzlar','Şimşək'],1),
('hey3-materiallar#1','hayat-bilgisi','hey-3-materiallar',2,3,'Şüşənin xassələri hansılardır?','Şüşə şəffafdır, amma tez sınır.',array['Şəffafdır və kövrəkdir','Yumşaqdır və əyilir','Suda əriyir','Yanmır və əyilir'],1),
('hey3-materiallar#2','hayat-bilgisi','hey-3-materiallar',2,3,'Hansı material suda batmır?','Taxta sudan yüngüldür — üzür.',array['Taxta','Dəmir','Daş','Şüşə'],1),
('hey3-materiallar#3','hayat-bilgisi','hey-3-materiallar',2,3,'Maqnitə hansı əşya yapışar?','Maqnit dəmir əşyaları cəzb edir.',array['Dəmir mismar','Taxta qələm','Plastik qaşıq','Kağız vərəq'],1),
('hey3-materiallar#4','hayat-bilgisi','hey-3-materiallar',2,3,'Kağız nədən hazırlanır?','Kağız oduncaqdan istehsal olunur.',array['Oduncaqdan','Daşdan','Şüşədən','Dəmirdən'],1),
('hey3-materiallar#5','hayat-bilgisi','hey-3-materiallar',1,3,'Hansı material elastikdir — dartılıb əvvəlki halına qayıdır?','Rezin elastikdir.',array['Rezin','Şüşə','Daş','Çini'],1),
('hey3-materiallar#6','hayat-bilgisi','hey-3-materiallar',3,3,'Metallar istiliyi necə keçirir?','Metallar istiliyi yaxşı keçirir — qaynar qaba toxunmaq olmaz.',array['Yaxşı keçirir','Heç keçirmir','Yalnız qışda keçirir','Yalnız suda keçirir'],1),
('hey3-materiallar#7','hayat-bilgisi','hey-3-materiallar',2,3,'Hansı əşya kövrəkdir — düşəndə sınar?','Çini boşqab kövrəkdir.',array['Çini boşqab','Rezin top','Parça dəsmal','Plastik vedrə'],1),
('hey3-materiallar#8','hayat-bilgisi','hey-3-materiallar',3,3,'Plastik tullantılar təbiətə niyə zərərlidir?','Plastik uzun illər çürümür, təbiəti çirkləndirir.',array['Uzun illər çürümür','Tez əriyir','Gübrəyə çevrilir','Suda həll olur'],1),
('hey3-materiallar#9','hayat-bilgisi','hey-3-materiallar',2,3,'Suyu hansı qabda qaynatmaq təhlükəsizdir?','Metal qab oda davamlıdır.',array['Metal qabda','Plastik qabda','Kağız qabda','Şüşə olmayan karton qabda'],1),
('hey3-materiallar#10','hayat-bilgisi','hey-3-materiallar',1,3,'Parçanın xassəsi hansıdır?','Parça yumşaqdır, əyilir, tikilə bilir.',array['Yumşaqdır və əyilir','Bərkdir və sınır','Şəffafdır','Suda batmır və əriyir'],1),
('hey3-materiallar#11','hayat-bilgisi','hey-3-materiallar',1,3,'Hansı material şəffafdır?','Şüşədən işıq keçir — şəffafdır.',array['Şüşə','Taxta','Dəmir','Gil'],1),
('hey3-materiallar#12','hayat-bilgisi','hey-3-materiallar',2,3,'Rezinin əsas xassəsi hansıdır?','Rezin dartılıb əvvəlki halına qayıdır.',array['Elastikdir','Kövrəkdir','Şəffafdır','Maqnitdir'],1),
('hey3-materiallar#13','hayat-bilgisi','hey-3-materiallar',1,3,'Taxtadan nə hazırlanır?','Mebel əsasən taxtadan hazırlanır.',array['Mebel','Şüşə qab','Mismar','Rezin top'],1),
('hey3-materiallar#14','hayat-bilgisi','hey-3-materiallar',1,3,'Hansı əşya metaldan hazırlanıb?','Qaşıq metaldan hazırlanır.',array['Qaşıq','Dəftər','Yastıq','Kağız təyyarə'],1),
('hey3-materiallar#15','hayat-bilgisi','hey-3-materiallar',2,3,'Gildən nə hazırlanır?','Dulusçular gildən qab-qacaq düzəldir.',array['Dulusçuluq qabları','Pəncərə şüşəsi','Dəmir qapı','Rezin təkər'],1),
('hey3-materiallar#16','hayat-bilgisi','hey-3-materiallar',2,3,'Pambıqdan hansı məmulat alınır?','Pambıqdan parça toxunur.',array['Parça','Şüşə','Mismar','Boru'],1),
('hey3-materiallar#17','hayat-bilgisi','hey-3-materiallar',2,3,'Hansı material suyu özünə çəkir (hopdurur)?','Kağız suyu tez hopdurur.',array['Kağız','Şüşə','Metal','Plastik'],1),
('hey3-materiallar#18','hayat-bilgisi','hey-3-materiallar',2,3,'Tullantıları növlərə ayırıb atmaq nəyə xidmət edir?','Çeşidləmə təbiəti qoruyur, təkrar emala kömək edir.',array['Təbiətin qorunmasına','Zibilin artmasına','Havanın çirklənməsinə','Heç nəyə'],1),
('hey3-materiallar#19','hayat-bilgisi','hey-3-materiallar',2,3,'Hansı material maqnitə yapışmaz?','Plastik maqnitə yapışmır.',array['Plastik','Dəmir mismar','Polad qaşıq','Dəmir açar'],1),
('hey3-materiallar#20','hayat-bilgisi','hey-3-materiallar',3,3,'Alüminium hansı materiallar qrupuna aiddir?','Alüminium yüngül metaldır.',array['Metallara','Parçalara','Şüşələrə','Ağaclara'],1),
('hey3-bayramlar#1','hayat-bilgisi','hey-3-bayramlar',1,3,'Novruz bayramı hansı fəsildə qeyd olunur?','Novruz yazın gəlişi bayramıdır.',array['Yazda','Qışda','Payızda','Yayda'],1),
('hey3-bayramlar#2','hayat-bilgisi','hey-3-bayramlar',1,3,'Hansı, Novruzun rəmzlərindəndir?','Səməni Novruzun əsas rəmzidir.',array['Səməni','Yolka','Balqabaq','Şam ağacı'],1),
('hey3-bayramlar#3','hayat-bilgisi','hey-3-bayramlar',3,3,'31 Dekabr hansı gündür?','31 Dekabr — Dünya Azərbaycanlılarının Həmrəyliyi Günüdür.',array['Dünya Azərbaycanlılarının Həmrəyliyi Günü','Zəfər Günü','Bilik Günü','Müəllim Günü'],1),
('hey3-bayramlar#4','hayat-bilgisi','hey-3-bayramlar',2,3,'Qənaət nə deməkdir?','Resurslardan israf etmədən istifadə etmək.',array['İsraf etmədən istifadə etmək','Heç nə xərcləməmək','Çox xərcləmək','Hər şeyi yığıb saxlamaq'],1),
('hey3-bayramlar#5','hayat-bilgisi','hey-3-bayramlar',1,3,'Suya qənaət üçün nə etməliyik?','Kranı boş yerə açıq qoymamaq lazımdır.',array['Kranı boş yerə açıq qoymamaq','Kranı həmişə açıq saxlamaq','Hər gün hovuz doldurmaq','Suyu dadmamaq'],1),
('hey3-bayramlar#6','hayat-bilgisi','hey-3-bayramlar',1,3,'İşığa qənaət üçün nə etməliyik?','Otaqdan çıxanda işığı söndürmək lazımdır.',array['Otaqdan çıxanda işığı söndürmək','Bütün lampaları yandırmaq','Gündüz də işıq yandırmaq','Heç vaxt söndürməmək'],1),
('hey3-bayramlar#7','hayat-bilgisi','hey-3-bayramlar',2,3,'Çörəyə münasibət necə olmalıdır?','Çörək zəhmətlə başa gəlir — israf etmək olmaz.',array['İsraf etməmək','Artığını atmaq','Oyun oynamaq','Yerə atmaq'],1),
('hey3-bayramlar#8','hayat-bilgisi','hey-3-bayramlar',3,3,'9 Noyabr hansı gündür?','9 Noyabr — Dövlət Bayrağı Günüdür.',array['Dövlət Bayrağı Günü','Yeni il','Novruz','Bilik Günü'],1),
('hey3-bayramlar#9','hayat-bilgisi','hey-3-bayramlar',2,3,'Novruz süfrəsinin şirniyyatları hansılardır?','Şəkərbura, paxlava, qoğal Novruz şirniyyatlarıdır.',array['Şəkərbura və paxlava','Tort və keks','Dondurma','Çips və qazlı içki'],1),
('hey3-bayramlar#10','hayat-bilgisi','hey-3-bayramlar',2,3,'Cib pulunu necə xərcləmək düzgündür?','Düşünülmüş, qənaətlə xərcləmək lazımdır.',array['Düşünülmüş və qənaətlə','Bir gündə hamısını','Yalnız oyunlara','Sayarkən itirmək'],1),
('hey3-bayramlar#11','hayat-bilgisi','hey-3-bayramlar',2,3,'Səməni Novruzda nəyin rəmzidir?','Səməni yazın gəlişinin və bolluğun rəmzidir.',array['Yazın və bolluğun','Qışın','Yağışın','Gecənin'],1),
('hey3-bayramlar#12','hayat-bilgisi','hey-3-bayramlar',2,3,'Novruzda qeyd olunan dörd çərşənbədən biri hansıdır?','Su, od, yel və torpaq çərşənbələri qeyd olunur.',array['Su çərşənbəsi','Qar çərşənbəsi','Daş çərşənbəsi','Külək bayramı'],1),
('hey3-bayramlar#13','hayat-bilgisi','hey-3-bayramlar',3,3,'28 May hansı bayramdır?','28 May — Müstəqillik Günüdür.',array['Müstəqillik Günü','Novruz bayramı','Bilik Günü','Yeni il'],1),
('hey3-bayramlar#14','hayat-bilgisi','hey-3-bayramlar',2,3,'Qənaət etməyi öyrənmək nə üçün vacibdir?','Qənaət sabaha ehtiyat saxlamağa imkan verir.',array['Sabaha ehtiyat qalması üçün','Çox xərcləmək üçün','Oyun üçün','Heç nə üçün'],1),
('hey3-bayramlar#15','hayat-bilgisi','hey-3-bayramlar',3,3,'Kağıza qənaət təbiətə necə kömək edir?','Kağız oduncaqdan alınır — qənaət etdikdə ağaclar az kəsilir.',array['Ağaclar az kəsilir','Yağış çox yağır','Günəş parlayır','Heç cür'],1),
('hey3-bayramlar#16','hayat-bilgisi','hey-3-bayramlar',2,3,'Bilik Günü hansı tarixdə qeyd olunur?','Dərs ili 15 Sentyabrda başlayır.',array['15 Sentyabr','1 Yanvar','20 Mart','31 Dekabr'],1),
('hey3-bayramlar#17','hayat-bilgisi','hey-3-bayramlar',3,3,'Cib pulunun bir hissəsini yığmaq necə adlanır?','Gələcək üçün pul toplamaq yığım (əmanət) adlanır.',array['Yığım (əmanət)','İsraf','Borc','Bəxşiş'],1),
('hey3-bayramlar#18','hayat-bilgisi','hey-3-bayramlar',1,3,'Novruz bayramında xonçaya nə qoyulur?','Xonçaya şam, səməni və şirniyyat qoyulur.',array['Şam, səməni və şirniyyat','Dəftər və qələm','Qar və buz','Yalnız çörək'],1),
('hey3-bayramlar#19','hayat-bilgisi','hey-3-bayramlar',3,3,'Dünya Azərbaycanlılarının Həmrəyliyi Günü hansı tarixdədir?','31 Dekabr Həmrəylik Günüdür.',array['31 Dekabr','8 Mart','9 Noyabr','15 Sentyabr'],1),
('hey3-bayramlar#20','hayat-bilgisi','hey-3-bayramlar',1,3,'Bayramda böyükləri təbrik etmək nəyin göstəricisidir?','Təbrik etmək hörmətin ifadəsidir.',array['Hörmətin','Tənbəlliyin','Qorxunun','Unutqanlığın'],1),
('hey3-tehlukesizlik#1','hayat-bilgisi','hey-3-tehlukesizlik',1,4,'Yolu keçmək üçün svetoforun hansı işığını gözləməliyik?','Piyada üçün yaşıl işıq yanmalıdır.',array['Yaşıl','Qırmızı','Sarı','İstənilən'],1),
('hey3-tehlukesizlik#2','hayat-bilgisi','hey-3-tehlukesizlik',1,4,'Küçəni haradan keçmək təhlükəsizdir?','Yalnız piyada keçidindən.',array['Piyada keçidindən','İstənilən yerdən','Maşınların arasından','Döngədən qaçaraq'],1),
('hey3-tehlukesizlik#3','hayat-bilgisi','hey-3-tehlukesizlik',2,4,'Evdə qaz iyi hiss edəndə nə etmək OLMAZ?','Qığılcım partlayışa səbəb ola bilər.',array['Kibrit yandırmaq','Pəncərəni açmaq','Böyüklərə demək','Evi tərk etmək'],1),
('hey3-tehlukesizlik#4','hayat-bilgisi','hey-3-tehlukesizlik',2,4,'Yanğın zamanı ilk növbədə nə etmək lazımdır?','112-yə zəng edib təhlükəli yerdən uzaqlaşmaq.',array['112-yə zəng edib evi tərk etmək','Gizlənmək','Özü söndürməyə çalışmaq','Heç nə etməmək'],1),
('hey3-tehlukesizlik#5','hayat-bilgisi','hey-3-tehlukesizlik',2,4,'Küçədə tapılan naməlum çantaya nə etməli?','Toxunmayıb böyüklərə xəbər vermək lazımdır.',array['Toxunmayıb böyüklərə demək','Açıb baxmaq','Evə aparmaq','Təpik vurmaq'],1),
('hey3-tehlukesizlik#6','hayat-bilgisi','hey-3-tehlukesizlik',1,4,'Elektrik rozetkasına nə salmaq olmaz?','Metal əşya cərəyan vurmasına səbəb olur.',array['Metal əşyalar','Cihazın öz ştepselini','Heç nə olmaz','Yalnız gündüz salmaq olar'],1),
('hey3-tehlukesizlik#7','hayat-bilgisi','hey-3-tehlukesizlik',2,4,'Velosipedi harada sürmək təhlükəsizdir?','Park və xüsusi zolaqlar bunun üçündür.',array['Parkda və xüsusi zolaqda','Maşın yolunda','Körpünün kənarında','Pilləkəndə'],1),
('hey3-tehlukesizlik#8','hayat-bilgisi','hey-3-tehlukesizlik',1,4,'Tanımadığın itə yaxınlaşmaq olarmı?','Naməlum heyvana yaxınlaşmaq təhlükəlidir.',array['Olmaz','Olar','Yalnız gecə olar','Yalnız qaçaraq olar'],1),
('hey3-tehlukesizlik#9','hayat-bilgisi','hey-3-tehlukesizlik',2,4,'Dərmanı uşağa kim verməlidir?','Dərmanı yalnız böyüklər, həkim təyinatı ilə verir.',array['Böyüklər, həkim təyinatı ilə','Uşaq özü','Sinif yoldaşı','Heç kim'],1),
('hey3-tehlukesizlik#10','hayat-bilgisi','hey-3-tehlukesizlik',2,4,'Su hövzəsində böyüksüz çimmək olarmı?','Təkbaşına çimmək təhlükəlidir.',array['Olmaz — təhlükəlidir','Olar','Yalnız isti gündə olar','Yalnız dayaz yerdə olar'],1),
('hey3-tehlukesizlik#11','hayat-bilgisi','hey-3-tehlukesizlik',1,4,'Piyada yolun hərəkət hissəsində oynaya bilərmi?','Yolda oynamaq qadağandır — maşınlar hərəkət edir.',array['Xeyr, qadağandır','Bəli, axşamlar','Bəli, topla','Bəli, dostla birgə'],1),
('hey3-tehlukesizlik#12','hayat-bilgisi','hey-3-tehlukesizlik',1,4,'Qaz sobasını uşaq özü yandıra bilərmi?','Qaz cihazlarını yalnız böyüklər işlədə bilər.',array['Xeyr, yalnız böyüklər','Bəli, hər vaxt','Bəli, kibrit olsa','Fərqi yoxdur'],1),
('hey3-tehlukesizlik#13','hayat-bilgisi','hey-3-tehlukesizlik',2,4,'Zəhərlənmə zamanı hansı nömrəyə zəng edilməlidir?','Təcili tibbi yardım 103-dür.',array['103 (təcili yardım)','101','102','104'],1),
('hey3-tehlukesizlik#14','hayat-bilgisi','hey-3-tehlukesizlik',1,4,'Nəqliyyatda pəncərədən əl çıxarmaq olarmı?','Hərəkət zamanı pəncərədən əl çıxarmaq təhlükəlidir.',array['Qəti olmaz','Olar, ehtiyatla','Yalnız sağ əli','Yalnız dayanacaqda'],1),
('hey3-tehlukesizlik#15','hayat-bilgisi','hey-3-tehlukesizlik',2,4,'Qışda buz bağlamış su hövzəsinə çıxmaq təhlükəlidirmi?','Buz sına bilər — çox təhlükəlidir.',array['Bəli, çox təhlükəlidir','Xeyr, təhlükəsizdir','Yalnız gündüz olar','Yalnız qaçaraq olar'],1),
('hey3-tehlukesizlik#16','hayat-bilgisi','hey-3-tehlukesizlik',2,4,'Evdə iti (kəsici) alətlərdən istifadə qaydası necədir?','Kəsici alətlər yalnız böyüklərin nəzarəti ilə işlədilir.',array['Yalnız böyüklərin nəzarəti ilə','Sərbəst, istənilən vaxt','Gizlicə','Oyun kimi'],1),
('hey3-tehlukesizlik#17','hayat-bilgisi','hey-3-tehlukesizlik',2,4,'Üzərində yazı olmayan butulkadakı mayeni dadmaq olarmı?','Naməlum maye zəhərli ola bilər — dadmaq əsla olmaz.',array['Əsla olmaz','Bir qurtum olar','İyləyib içmək olar','Şirindirsə olar'],1),
('hey3-tehlukesizlik#18','hayat-bilgisi','hey-3-tehlukesizlik',2,4,'Yol keçərkən telefonla məşğul olmaq nəyə səbəb ola bilər?','Diqqət yayınır — qəza baş verə bilər.',array['Qəzaya səbəb ola bilər','Vaxt qazandırır','Təhlükəsizdir','Heç nəyə'],1),
('hey3-tehlukesizlik#19','hayat-bilgisi','hey-3-tehlukesizlik',3,4,'İldırım zamanı harada gizlənmək TƏHLÜKƏLİDİR?','Hündür tək ağac ildırımı cəzb edir.',array['Hündür tək ağacın altında','Evdə','Avtomobildə','Alçaq yerdə'],1),
('hey3-tehlukesizlik#20','hayat-bilgisi','hey-3-tehlukesizlik',2,4,'Qapı zəngi çalınanda evdə tək olan uşaq nə etməlidir?','Qapını açmadan böyüklərə zəng etmək lazımdır.',array['Açmadan böyüklərə zəng etməli','Dərhal açmalı','Açarı verməli','Qışqırmalı'],1),
('inf3-informasiya#1','informatika','inf-3-informasiya',1,1,'İnformasiyanı hansı orqanlarla qəbul edirik?','Görmə, eşitmə, iybilmə, dadbilmə, toxunma — hiss orqanları ilə.',array['Hiss orqanları ilə','Yalnız əllərlə','Yalnız qulaqla','Saçla'],1),
('inf3-informasiya#2','informatika','inf-3-informasiya',1,1,'Gözlə qəbul edilən informasiya hansıdır?','Şəkil, yazı, rəng — görmə informasiyasıdır.',array['Görmə','Səs','Dad','Qoxu'],1),
('inf3-informasiya#3','informatika','inf-3-informasiya',1,1,'Musiqi hansı informasiya növüdür?','Musiqini qulaqla qəbul edirik — səs informasiyasıdır.',array['Səs','Görmə','Dad','Toxunma'],1),
('inf3-informasiya#4','informatika','inf-3-informasiya',2,1,'Hansı sırada hamısı informasiya mənbəyidir?','Kitab da, televizor da, insan da məlumat verir.',array['Kitab, televizor, insan','Kitab, daş, qum','Televizor, boş vərəq, daş','Divar, qapı, döşəmə'],1),
('inf3-informasiya#5','informatika','inf-3-informasiya',2,1,'Məktəb zənginin səsi bizə nə bildirir?','Zəng dərsin başlandığını və ya bitdiyini bildirir.',array['Dərsin başlandığını və ya bitdiyini','Havanın istiliyini','Günün tarixini','Heç nə'],1),
('inf3-informasiya#6','informatika','inf-3-informasiya',2,1,'Hansı, informasiya daşıyıcısıdır?','Disk üzərində məlumat saxlanılır.',array['Disk','Stul','Pəncərə','Ayaqqabı'],1),
('inf3-informasiya#7','informatika','inf-3-informasiya',2,1,'Dad informasiyasını hansı orqanla qəbul edirik?','Dadı dil ilə hiss edirik.',array['Dil ilə','Göz ilə','Qulaq ilə','Burun ilə'],1),
('inf3-informasiya#8','informatika','inf-3-informasiya',2,1,'Hansı hərəkət informasiyanın ötürülməsidir?','Məktub göndərəndə məlumat başqasına çatdırılır.',array['Məktub göndərmək','Yatmaq','Qaçmaq','Yemək yemək'],1),
('inf3-informasiya#9','informatika','inf-3-informasiya',3,1,'Qədim dövrdə insanlar məlumatı necə ötürürdülər?','Çaparlar və məktublarla.',array['Çaparla və məktubla','Telefonla','İnternetlə','Televizorla'],1),
('inf3-informasiya#10','informatika','inf-3-informasiya',2,1,'Toxunmaqla əşyanın hansı xassəsini öyrənmək olar?','Hamar və ya kobud olduğunu toxunmaqla bilirik.',array['Hamar və ya kobud olduğunu','Rəngini','Səsini','Adını'],1),
('inf3-informasiya#11','informatika','inf-3-informasiya',1,1,'Qulaqla hansı informasiyanı qəbul edirik?','Eşitmə orqanı səs informasiyasını qəbul edir.',array['Səs informasiyasını','Dad informasiyasını','Qoxu informasiyasını','Toxunma informasiyasını'],1),
('inf3-informasiya#12','informatika','inf-3-informasiya',2,1,'Şəkil və fotolar hansı informasiya növüdür?','Gözlə qəbul edilən təsvirlər qrafik informasiyadır.',array['Qrafik','Səs','Dad','Qoxu'],1),
('inf3-informasiya#13','informatika','inf-3-informasiya',1,1,'Burunla hansı informasiya qəbul edilir?','İybilmə orqanı qoxu informasiyası verir.',array['Qoxu','Səs','Rəng','Say'],1),
('inf3-informasiya#14','informatika','inf-3-informasiya',2,1,'Qədim insanlar informasiyanı saxlamaq üçün nəyə yazırdılar?','Yazı daş və gil lövhələr üzərində yaranıb.',array['Daşa və gil lövhələrə','Kompüterə','Telefona','Televizora'],1),
('inf3-informasiya#15','informatika','inf-3-informasiya',2,1,'Radiodan hansı növ informasiya alırıq?','Radio yalnız səs ötürür.',array['Səs (eşitmə)','Görüntü','Dad','Toxunma'],1),
('inf3-informasiya#16','informatika','inf-3-informasiya',2,1,'Kitabdan aldığımız informasiya hansı yolla qəbul edilir?','Kitabı gözlə oxuyuruq.',array['Görmə ilə','Qoxu ilə','Dad ilə','Toxunma ilə'],1),
('inf3-informasiya#17','informatika','inf-3-informasiya',2,1,'İnformasiyanın qorunub saxlanmasına misal hansıdır?','Foto yaddaş kartında saxlanılır.',array['Fotonun yaddaş kartında saxlanması','Topun atılması','Qapının açılması','Suyun qaynaması'],1),
('inf3-informasiya#18','informatika','inf-3-informasiya',2,1,'Jestlər və mimika nəyi ötürür?','Hərəkət və üz ifadələri də informasiya ötürür.',array['İnformasiyanı','Yalnız istiliyi','Yalnız qoxunu','Heç nəyi'],1),
('inf3-informasiya#19','informatika','inf-3-informasiya',2,1,'Hansı cihaz informasiyanı həm saxlayır, həm də ötürür?','Kompüter informasiyanı saxlayır və ötürür.',array['Kompüter','Stul','Qazan','Çətir'],1),
('inf3-informasiya#20','informatika','inf-3-informasiya',2,1,'İsti-soyuğu hansı hiss orqanı ilə duyuruq?','Toxunma — dəri ilə hiss olunur.',array['Dəri ilə','Gözlə','Qulaqla','Dillə'],1),
('inf3-alqoritm#1','informatika','inf-3-alqoritm',2,2,'Hansı, alqoritmə misaldır?','Yemək resepti addım-addım icra qaydasıdır.',array['Yemək resepti','Şəkil','Mahnı','Rəng'],1),
('inf3-alqoritm#2','informatika','inf-3-alqoritm',1,2,'Alqoritmdə addımlar necə düzülür?','Addımlar icra sırası ilə, ardıcıl düzülür.',array['Ardıcıl','Qarışıq','Sondan əvvələ','İstənilən kimi'],1),
('inf3-alqoritm#3','informatika','inf-3-alqoritm',2,2,'«Səhər oyan → ? → geyin» alqoritmində buraxılmış addım hansı ola bilər?','Oyanandan sonra üz-əl yuyulur.',array['Üzünü yu','Axşam yeməyi ye','Yat','Məktəbdən qayıt'],1),
('inf3-alqoritm#4','informatika','inf-3-alqoritm',2,2,'Alqoritmi kim və ya nə icra edə bilər?','İcraçı insan, robot və ya kompüter ola bilər.',array['İnsan, robot, kompüter','Yalnız insan','Yalnız daş','Heç kim'],1),
('inf3-alqoritm#5','informatika','inf-3-alqoritm',2,2,'Alqoritmin addımları qarışdırılsa, nə olar?','Ardıcıllıq pozulsa, nəticə səhv alınar.',array['Nəticə səhv alınar','Heç nə dəyişməz','Daha tez bitər','Nəticə yaxşılaşar'],1),
('inf3-alqoritm#6','informatika','inf-3-alqoritm',1,2,'«Başla» və «Son» alqoritmin nəyini bildirir?','Alqoritmin haradan başlayıb harada bitdiyini.',array['Başlanğıcını və sonunu','Rəngini','Çəkisini','Müəllifini'],1),
('inf3-alqoritm#7','informatika','inf-3-alqoritm',3,2,'Hansı, alqoritm DEYİL?','Mənasız söz yığınında ardıcıl addımlar yoxdur.',array['Mənasız söz yığını','Çay dəmləmə qaydası','Əl yuma qaydası','Misal həlli qaydası'],1),
('inf3-alqoritm#8','informatika','inf-3-alqoritm',2,2,'Gülü suvarma alqoritmində birinci addım hansıdır?','Əvvəlcə suqabına su doldurulur.',array['Suqabına su doldurmaq','Gülü dibindən kəsmək','Torpağı atmaq','Yarpaqları yumaq'],1),
('inf3-alqoritm#9','informatika','inf-3-alqoritm',3,2,'«Alqoritm» sözü haradan yaranıb?','Alim Əl-Xarəzminin adından yaranıb.',array['Alim Əl-Xarəzminin adından','Şəhər adından','Oyun adından','Heyvan adından'],1),
('inf3-alqoritm#10','informatika','inf-3-alqoritm',2,2,'Misalın addım-addım həlli alqoritmdirmi?','Bəli — ardıcıl icra olunan addımlardır.',array['Bəli','Xeyr','Yalnız çətin misallarda','Yalnız dərslikdə'],1),
('inf3-alqoritm#11','informatika','inf-3-alqoritm',1,2,'Addımların dəqiq ardıcıllığı nəyi əmələ gətirir?','Ardıcıl düzülmüş addımlar alqoritm yaradır.',array['Alqoritmi','Nağılı','Şəkli','Mahnını'],1),
('inf3-alqoritm#12','informatika','inf-3-alqoritm',2,2,'Çay dəmləmə alqoritmində «suyu qaynat» addımından sonra nə gəlir?','Su qaynadıqdan sonra çay dəmlənir.',array['Çayı dəmlə','Suyu doldur','Çaydanı al','Süfrəni yığışdır'],1),
('inf3-alqoritm#13','informatika','inf-3-alqoritm',2,2,'Alqoritm tərtib edərkən əvvəlcə nə müəyyən edilir?','Əvvəlcə məqsəd — nəyə nail olmaq istədiyin müəyyənləşir.',array['Məqsəd','Son addım','Rənglər','Musiqi'],1),
('inf3-alqoritm#14','informatika','inf-3-alqoritm',2,2,'Robot alqoritmi necə icra edir?','Robot göstərişlərə olduğu kimi, dəqiq əməl edir.',array['Göstərişlərə dəqiq əməl etməklə','İstədiyi kimi','Təsadüfi','Yarımçıq'],1),
('inf3-alqoritm#15','informatika','inf-3-alqoritm',2,2,'Hansı peşə sahibi kompüter üçün alqoritmlər qurur?','Proqramçı alqoritm qurub proqram yazır.',array['Proqramçı','Aşpaz','Sürücü','Həkim'],1),
('inf3-alqoritm#16','informatika','inf-3-alqoritm',2,2,'«Sağa dön, 2 addım irəli get» — bu nədir?','Bunlar icra üçün verilmiş göstərişlərdir.',array['İcra üçün göstərişlər','Nağıl','Tapmaca','Mahnı'],1),
('inf3-alqoritm#17','informatika','inf-3-alqoritm',2,2,'Alqoritmdə bir addımı buraxsaq nə baş verər?','Addım buraxılsa, məqsədə çatmaya bilərik.',array['Nəticə alınmaya bilər','Heç nə dəyişməz','Daha yaxşı olar','Alqoritm sürətlənər'],1),
('inf3-alqoritm#18','informatika','inf-3-alqoritm',2,2,'Səhər oyanışdan məktəbə qədər hərəkətlərin ardıcıllığı nəyə misaldır?','Gündəlik işlərin ardıcıllığı da alqoritmdir.',array['Gündəlik alqoritmə','Nağıla','Şeirə','Oyuna'],1),
('inf3-alqoritm#19','informatika','inf-3-alqoritm',3,2,'Alqoritmin sonlu olması nə deməkdir?','Alqoritm nə vaxtsa bitməlidir — addımları sonludur.',array['Addımların bitməsi','Sonsuz davam etməsi','Rəngli olması','Səsli olması'],1),
('inf3-alqoritm#20','informatika','inf-3-alqoritm',2,2,'Ağac əkmə alqoritmində birinci addım hansıdır?','Əvvəlcə çala qazılır.',array['Çala qazmaq','Ağacı sulamaq','Torpağı bərkitmək','Meyvəni dərmək'],1),
('inf3-kompyuter#1','informatika','inf-3-kompyuter',1,3,'Kompüterin əsas qurğuları hansılardır?','Sistem bloku, monitor, klaviatura və maus.',array['Sistem bloku, monitor, klaviatura, maus','Stol, stul, lampa','Kitab, dəftər, qələm','Televizor və pult'],1),
('inf3-kompyuter#2','informatika','inf-3-kompyuter',1,3,'Klaviatura nə üçündür?','Klaviatura ilə məlumat (hərf, rəqəm) daxil edilir.',array['Məlumat daxil etmək üçün','Səs eşitmək üçün','Şəkil göstərmək üçün','Çap etmək üçün'],1),
('inf3-kompyuter#3','informatika','inf-3-kompyuter',1,3,'Ekrandakı oxu (kursoru) hansı qurğu ilə hərəkət etdiririk?','Maus ekrandakı oxu idarə edir.',array['Maus','Printer','Dinamik','Mikrofon'],1),
('inf3-kompyuter#4','informatika','inf-3-kompyuter',2,3,'Kompüter arxasında iş vaxtı necə olmalıdır?','Məhdud vaxt, fasilələrlə işləmək lazımdır.',array['Məhdud, fasilələrlə','Bütün günü','Gecə boyu','Fasiləsiz'],1),
('inf3-kompyuter#5','informatika','inf-3-kompyuter',2,3,'Sistem blokunun içində nə yerləşir?','Prosessor və yaddaş sistem blokundadır.',array['Prosessor və yaddaş','Kitablar','Dinamik və mikrofon','Kağız və mürəkkəb'],1),
('inf3-kompyuter#6','informatika','inf-3-kompyuter',2,3,'Noutbuku masaüstü kompüterdən nə fərqləndirir?','Noutbuk yığcamdır, daşınabiləndir.',array['Daşına bilməsi','Ekranının olmaması','Klaviaturasının olmaması','İşləməməsi'],1),
('inf3-kompyuter#7','informatika','inf-3-kompyuter',2,3,'Planşet əsasən nə ilə idarə olunur?','Planşetin sensor ekranı toxunuşla işləyir.',array['Toxunuşla (sensor ekranla)','Pultla','Pedalla','Açarla'],1),
('inf3-kompyuter#8','informatika','inf-3-kompyuter',3,3,'«Enter» düyməsi nə edir?','Əmri təsdiqləyir, mətndə yeni sətrə keçirir.',array['Əmri təsdiqləyir','Kompüteri söndürür','Səsi artırır','Ekranı silir'],1),
('inf3-kompyuter#9','informatika','inf-3-kompyuter',2,3,'Faylları kompüterin harasında saxlayırıq?','Fayllar kompüterin yaddaşında saxlanılır.',array['Yaddaşında','Monitorunda','Mausunda','Naqilində'],1),
('inf3-kompyuter#10','informatika','inf-3-kompyuter',2,3,'Kompüter arxasında düzgün oturuş necədir?','Kürək düz, ekran gözdən aralı olmalıdır.',array['Kürək düz, ekrandan aralı','Ekrana yapışaraq','Uzanaraq','Ayaq üstə əyilərək'],1),
('inf3-kompyuter#11','informatika','inf-3-kompyuter',2,3,'Kompüterin «beyni» adlanan hissəsi hansıdır?','Bütün hesablamaları prosessor aparır.',array['Prosessor','Maus','Kabel','Dinamik'],1),
('inf3-kompyuter#12','informatika','inf-3-kompyuter',2,3,'Kompüter işləyərkən onu birdən elektrikdən ayırmaq olarmı?','Qəfil söndürəndə yazılmamış məlumat itə bilər.',array['Xeyr, məlumat itə bilər','Bəli, heç nə olmaz','Bəli, daha sürətli olar','Fərqi yoxdur'],1),
('inf3-kompyuter#13','informatika','inf-3-kompyuter',2,3,'Mausun sol düyməsi adətən nə üçün istifadə olunur?','Sol düymə ilə seçir və açırıq.',array['Seçmək və açmaq üçün','Səsi artırmaq üçün','İşığı yandırmaq üçün','Çap etmək üçün'],1),
('inf3-kompyuter#14','informatika','inf-3-kompyuter',1,3,'Qulaqlıq kompüterdən hansı informasiyanı çatdırır?','Qulaqlıqla səsi eşidirik.',array['Səsi','Şəkli','Mətni','Qoxunu'],1),
('inf3-kompyuter#15','informatika','inf-3-kompyuter',2,3,'Paint proqramında nə etmək olar?','Paint-də şəkil çəkilir və rənglənir.',array['Şəkil çəkmək','Mahnı yazmaq','Zəng etmək','Yemək sifariş etmək'],1),
('inf3-kompyuter#16','informatika','inf-3-kompyuter',1,3,'Kompüter oyunlarını həddindən artıq oynamaq nəyə zərərlidir?','Uzun oyun sağlamlığa və dərslərə mane olur.',array['Sağlamlığa və dərslərə','Heç nəyə','Yalnız mausa','Yalnız stola'],1),
('inf3-kompyuter#17','informatika','inf-3-kompyuter',2,3,'Kompüterə qoşulan əlavə qurğu hansıdır?','Printer kompüterə qoşulan qurğudur.',array['Printer','Stol','Kitab','Çanta'],1),
('inf3-kompyuter#18','informatika','inf-3-kompyuter',2,3,'Elektron poçt nə üçün istifadə olunur?','E-poçtla elektron məktublar göndərilir.',array['Məktub göndərmək üçün','Yemək sifarişi üçün yalnız','Şəkil çəkmək üçün','Oyun oynamaq üçün'],1),
('inf3-kompyuter#19','informatika','inf-3-kompyuter',2,3,'Kompüterlə iş bitəndə nə etmək lazımdır?','Kompüteri qaydasında söndürmək lazımdır.',array['Onu düzgün söndürmək','Elektrik kabelini dartmaq','Ekranı örtmək','Heç nə'],1),
('inf3-kompyuter#20','informatika','inf-3-kompyuter',3,3,'Hansı qurğular məlumatı kompüterdən KƏNARA verir?','Monitor göstərir, printer çap edir — hər ikisi çıxış qurğusudur.',array['Monitor və printer','Klaviatura və maus','Yalnız skaner','Yalnız mikrofon'],1),
('inf3-metn#1','informatika','inf-3-metn',1,4,'Mətn redaktoru nə üçündür?','Mətn yazmaq və onu düzəltmək üçün proqramdır.',array['Mətn yazmaq və düzəltmək üçün','Oyun oynamaq üçün','Mahnı dinləmək üçün','Şəkil çəkmək üçün'],1),
('inf3-metn#2','informatika','inf-3-metn',2,4,'Böyük hərf yazmaq üçün hansı düymədən istifadə olunur?','Shift saxlanılıb hərf basılır.',array['Shift','Space','Esc','Tab'],1),
('inf3-metn#3','informatika','inf-3-metn',1,4,'Sözlər arasında boşluq hansı düymə ilə qoyulur?','Boşluq (Space) düyməsi ilə.',array['Boşluq (Space)','Enter','Shift','Backspace'],1),
('inf3-metn#4','informatika','inf-3-metn',2,4,'Səhv yazılmış son hərfi hansı düymə silir?','Backspace kursordan soldakı simvolu silir.',array['Backspace','Enter','Shift','Caps Lock'],1),
('inf3-metn#5','informatika','inf-3-metn',2,4,'Yeni sətrə keçmək üçün hansı düymə basılır?','Enter yeni sətrə keçirir.',array['Enter','Space','Shift','Alt'],1),
('inf3-metn#6','informatika','inf-3-metn',2,4,'Hansı, mətn redaktorudur?','Word mətn redaktorudur.',array['Word','Kalkulyator','Saat','Musiqi pleyeri'],1),
('inf3-metn#7','informatika','inf-3-metn',2,4,'Yazdığın mətni itirməmək üçün nə etməlisən?','Sənədi yadda saxlamaq (Save) lazımdır.',array['Yadda saxlamaq (Save)','Kompüteri söndürmək','Ekranı bağlamaq','Heç nə'],1),
('inf3-metn#8','informatika','inf-3-metn',2,4,'Kursor nədir?','Mətndə yazının qoyulacağı yeri göstərən işarədir.',array['Yazı yerini göstərən işarə','Şəkil növü','Proqram adı','Düymə adı'],1),
('inf3-metn#9','informatika','inf-3-metn',1,4,'Hərfləri hansı qurğu ilə yığırıq?','Mətn klaviatura ilə yığılır.',array['Klaviatura ilə','Mausla','Dinamiklə','Printerlə'],1),
('inf3-metn#10','informatika','inf-3-metn',2,4,'Yazdığınız mətni kağıza köçürən qurğu hansıdır?','Printer mətni kağıza çap edir.',array['Printer','Skaner','Mikrofon','Dinamik'],1),
('inf3-metn#11','informatika','inf-3-metn',2,4,'Mətndə bütün hərfləri BÖYÜK yazmaq üçün hansı düymə qoşulur?','Caps Lock bütün hərfləri böyük edir.',array['Caps Lock','Boşluq','Enter','Esc'],1),
('inf3-metn#12','informatika','inf-3-metn',3,4,'Kursordan sağdakı simvolu hansı düymə silir?','Delete kursordan sağdakı simvolu silir.',array['Delete','Shift','Tab','Boşluq'],1),
('inf3-metn#13','informatika','inf-3-metn',2,4,'Mətn redaktorunda səhv yazılmış sözü necə düzəltmək olar?','Səhvi silib düzgün variantı yazmaq olar.',array['Silib yenidən yazmaq','Kağızla örtmək','Kompüteri söndürmək','Düzəltmək olmaz'],1),
('inf3-metn#14','informatika','inf-3-metn',2,4,'Yazının hərflərini böyütmək mümkündürmü?','Şrift ölçüsünü dəyişməklə hərflər böyüyür.',array['Bəli, şrift ölçüsü ilə','Xeyr, mümkün deyil','Yalnız çapda','Yalnız şəkildə'],1),
('inf3-metn#15','informatika','inf-3-metn',1,4,'Klaviaturada rəqəmlər harada yerləşir?','Rəqəmlər hərflərin üstündəki cərgədədir.',array['Yuxarı cərgədə','Ən altda','Mausun üstündə','Monitorda'],1),
('inf3-metn#16','informatika','inf-3-metn',2,4,'Mətni çap etməzdən əvvəl nə etmək məsləhətdir?','Əvvəlcə səhvləri yoxlamaq lazımdır.',array['Səhvləri yoxlamaq','Kompüteri söndürmək','Printeri açmaq','Musiqi qoşmaq'],1),
('inf3-metn#17','informatika','inf-3-metn',2,4,'«Ə», «ğ», «ş» hərflərini hansı klaviatura düzülüşündə yazmaq olar?','Bu hərflər Azərbaycan klaviaturasındadır.',array['Azərbaycan klaviaturasında','Yalnız ingilis','Heç birində','Yalnız rəqəm hissəsində'],1),
('inf3-metn#18','informatika','inf-3-metn',2,4,'Yazılmış mətni daha maraqlı etmək üçün nə əlavə etmək olar?','Mətnə şəkil əlavə etmək olar.',array['Şəkil','Daş','Yapışqan','Kağız'],1),
('inf3-metn#19','informatika','inf-3-metn',2,4,'Mətn redaktorunda yeni sənəd necə yaradılır?','«Yeni» (New) əmri yeni sənəd açır.',array['«Yeni» (New) əmri ilə','Kompüteri silkələməklə','Ekranı silməklə','Mausu dəyişməklə'],1),
('inf3-metn#20','informatika','inf-3-metn',3,4,'Kompüterdə yazılmış mətnin kağızdakı forması necə adlanır?','Kağıza çıxarılmış nüsxə çap nüsxəsidir.',array['Çap nüsxəsi','Yaddaş','Kursor','Fayl'],1),
('inf3-qrafik#1','informatika','inf-3-qrafik',1,3,'Paint proqramında karandaş aləti nə edir?','Karandaş aləti nazik xətt çəkir.',array['Nazik xətt çəkir','Şəkli silir','Səs çıxarır','Faylı bağlayır'],1),
('inf3-qrafik#2','informatika','inf-3-qrafik',2,3,'Palitra nədir?','Palitra rənglər toplusudur.',array['Rənglər toplusu','Alətlər qutusu','Fayl adı','Kompüter hissəsi'],1),
('inf3-qrafik#3','informatika','inf-3-qrafik',2,3,'Şəklin bir hissəsini seçmək üçün hansı alətdən istifadə olunur?','Seçmə aləti fraqmenti ayırır.',array['Seçmə aləti','Fırça','Silgi','Sprey'],1),
('inf3-qrafik#4','informatika','inf-3-qrafik',2,3,'Seçilmiş fraqmenti başqa yerə necə aparmaq olar?','Fraqmenti sürükləyib köçürmək olar.',array['Köçürməklə (sürükləməklə)','Kabellə','Printerlə','Aparmaq olmaz'],1),
('inf3-qrafik#5','informatika','inf-3-qrafik',2,3,'Paint-də fiqurun içini rəngləmək üçün hansı alət işlədilir?','Doldurma aləti qapalı sahəni rənglə doldurur.',array['Doldurma aləti','Mətn aləti','Lupa','Karandaş'],1),
('inf3-qrafik#6','informatika','inf-3-qrafik',2,3,'Çəkilmiş şəkli kompüterdə saxlamaq üçün hansı əmr verilir?','Saxla (Save) əmri şəkli fayl kimi yazır.',array['Saxla (Save) əmri','Sil əmri','Çap əmri yalnız','Bağla əmri'],1),
('inf3-qrafik#7','informatika','inf-3-qrafik',1,3,'Paint-də düz xətt çəkmək üçün hansı alət seçilir?','Xətt aləti düz xətt çəkməyə imkan verir.',array['Xətt aləti','Sprey','Silgi','Seçmə aləti'],1),
('inf3-qrafik#8','informatika','inf-3-qrafik',2,3,'Paint-də səhv əməliyyatı necə geri qaytarmaq olar?','Geri (Undo) əmri son əməliyyatı ləğv edir.',array['Geri (Undo) əmri ilə','Kompüteri söndürməklə','Ekranı silməklə','Mümkün deyil'],1),
('inf3-qrafik#9','informatika','inf-3-qrafik',2,3,'Şəklin fraqmentini silsək nə baş verər?','Silinmiş yer ağ (fon rəngində) qalar.',array['Həmin hissə ağ qalar','Bütün şəkil silinər','Şəkil böyüyər','Heç nə olmaz'],1),
('inf3-qrafik#10','informatika','inf-3-qrafik',2,3,'Rəng püskürdən (sprey) alət nə üçün istifadə olunur?','Sprey səpələnmiş rəng effekti verir.',array['Səpələnmiş rəng vurmaq üçün','Yazı yazmaq üçün','Faylı silmək üçün','Şəkli kiçiltmək üçün'],1),
('inf3-qrafik#11','informatika','inf-3-qrafik',2,3,'Paint-də hazır fiqurlara misal hansılardır?','Alətlər arasında düzbucaqlı, oval, çoxbucaqlı var.',array['Düzbucaqlı, oval, çoxbucaqlı','Yalnız ulduz','Yalnız ürək','Fiqur yoxdur'],1),
('inf3-qrafik#12','informatika','inf-3-qrafik',1,3,'Şəkli çəkməzdən əvvəl nəyi düşünmək faydalıdır?','Əvvəlcə nə çəkəcəyini fikirləşmək lazımdır.',array['Nə çəkəcəyini','Printerin rəngini','Kabelin uzunluğunu','Heç nəyi'],1),
('inf3-qrafik#13','informatika','inf-3-qrafik',2,3,'Böyüdücü (lupa) aləti nə üçündür?','Lupa şəklin hissəsini böyüdüb dəqiq işləməyə imkan verir.',array['Şəklin hissəsini böyütmək üçün','Şəkli silmək üçün','Rəng seçmək üçün','Fayl açmaq üçün'],1),
('inf3-qrafik#14','informatika','inf-3-qrafik',1,3,'Paint-də silgi aləti nəyi silir?','Silgi şəklin çəkilmiş hissəsini təmizləyir.',array['Şəklin çəkilmiş hissəsini','Faylın adını','Kompüterin yaddaşını','Proqramı'],1),
('inf3-qrafik#15','informatika','inf-3-qrafik',3,3,'Kompüterdə saxlanan şəkillər necə adlanır?','Şəkillər qrafik fayllar adlanır.',array['Qrafik fayllar','Mətn faylları','Səs faylları','Oyunlar'],1),
('inf3-qrafik#16','informatika','inf-3-qrafik',2,3,'Saxlanmış şəkil faylını yenidən açmaq üçün nə etməli?','Faylı tapıb açmaq lazımdır.',array['Faylı tapıb açmaq','Yeni şəkil çəkmək','Printeri qoşmaq','Mümkün deyil'],1),
('inf3-qrafik#17','informatika','inf-3-qrafik',1,3,'Paint-də işləyərkən rəng seçimi haradan edilir?','Rəng palitradan seçilir.',array['Palitradan','Klaviaturadan','Sistem blokundan','Dinamikdən'],1),
('inf3-qrafik#18','informatika','inf-3-qrafik',3,3,'Simmetrik naxış çəkmək üçün fraqmentlə hansı əməliyyat aparılır?','Fraqment çevrilir (əks etdirilir).',array['Çevirmə (əks etdirmə)','Silmə','Çap etmə','Səsləndirmə'],1),
('inf3-qrafik#19','informatika','inf-3-qrafik',2,3,'Şəklin arxa hissəsi necə adlanır?','Şəklin arxa hissəsi fon (arxa plan) adlanır.',array['Arxa plan (fon)','Palitra','Fraqment','Kursor'],1),
('inf3-qrafik#20','informatika','inf-3-qrafik',2,3,'Qrafik redaktorda çəkilmiş şəkli çap etmək olarmı?','Şəkli printerlə kağıza çap etmək mümkündür.',array['Bəli, printerlə','Xeyr, heç vaxt','Yalnız yayda','Yalnız ağ-qara'],1)
),
ins as (
  insert into public.questions
    (ext_key, owner_type, subject_id, level_id, topic_id, kind,
     body, explanation, difficulty, quarter, status)
  select d.ext, 'platform', s.id, l.id, tp.id, 'single',
         d.body, d.why, d.diff, d.rub, 'published'
    from d
    join public.subjects s on s.slug = d.fenn
    join public.programs p on p.slug = 'ibtidai'
    join public.levels   l on l.program_id = p.id and l.code = '3'
    join public.topics   tp on tp.subject_id = s.id and tp.slug = d.topic
  on conflict (ext_key) do update
    set body = excluded.body, explanation = excluded.explanation,
        difficulty = excluded.difficulty, quarter = excluded.quarter,
        topic_id = excluded.topic_id, level_id = excluded.level_id,
        subject_id = excluded.subject_id, status = 'published'
  returning id, ext_key
)
insert into public.question_options (question_id, ord, body, is_correct)
select ins.id, o.ord, o.txt, o.ord = d.correct
  from ins
  join d on d.ext = ins.ext_key,
  lateral unnest(d.opts) with ordinality as o(txt, ord);

do $$
declare n int; k int;
begin
  select count(*) into n from public.questions
   where owner_type = 'platform'
     and (ext_key like 'az3-%' or ext_key like 'hey3-%'
          or ext_key like 'inf3-%');
  if n <> 380 then
    raise exception 'sinif3 suallari: 380 gozlenilirdi, % tapildi', n;
  end if;
  select count(*) into k from public.questions q
   where (q.ext_key like 'az3-%' or q.ext_key like 'hey3-%'
          or q.ext_key like 'inf3-%')
     and ((select count(*) from public.question_options o
            where o.question_id = q.id) <> 4
       or (select count(*) from public.question_options o
            where o.question_id = q.id and o.is_correct) <> 1);
  if k > 0 then
    raise exception '% sualda variant qurulusu sehvdir', k;
  end if;
  select count(distinct topic_id) into k from public.questions
   where ext_key like 'az3-%' or ext_key like 'hey3-%'
      or ext_key like 'inf3-%';
  if k <> 19 then
    raise exception 'movzu sayi 19 deyil: %', k;
  end if;
  raise notice '3-cu sinif banki: % sual, 19 movzu (az dili, heyat bilgisi, informatika).', n;
end $$;
