-- =====================================================================
--  31_bank_sinif6.sql : 6-CI SINIF - AZ DILI, INGILIS DILI,
--                       INFORMATIKA, AZERBAYCAN TARIXI
--
--  BU FAYL ELLE YAZILMIR - tools/sinif6.py yaradir:
--      python3 tools/sinif6.py
--
--  Az dili 8 + Ingilis dili 8 + Informatika 5 + Tarix 3
--  = 24 movzu x 20 = 480.  ext_key: az6-/ing6-/inf6-/tarix6-...
--  ON SERT: 29_movzular_orta6.sql islenmis olmalidir.
--  SONRA:   05_grants.sql yeniden islet.
-- =====================================================================

do $$
begin
  if not exists (select 1 from public.topics t join public.subjects s
      on s.id = t.subject_id
     where (s.slug, t.slug) in (('az-dili','az-6-fonetika'),
                                ('ingilis-dili','ing-6-town'),
                                ('informatika','inf-6-internet'),
                                ('tarix','tarix-6-ibtidai'))
     having count(*) = 4) then
    raise exception 'ONCE 29_movzular_orta6.sql isledilmelidir.';
  end if;
end $$;

delete from public.question_options o
 using public.questions q
 where o.question_id = q.id
   and q.owner_type = 'platform'
   and (q.ext_key like 'az6-%' or q.ext_key like 'ing6-%'
        or q.ext_key like 'inf6-%' or q.ext_key like 'tarix6-%');

with d(ext, fenn, topic, diff, rub, body, why, opts, correct) as (values
('az6-fonetika#1','az-dili','az-6-fonetika',2,1,'«Ağıl» sözünə saitlə başlanan şəkilçi artıranda (ağlım) hansı hadisə baş verir?','İkinci hecanın saiti düşür — səsdüşümü baş verir.',array['Səsdüşümü','Səsartımı','Vurğu dəyişməsi','Heç nə'],1),
('az6-fonetika#2','az-dili','az-6-fonetika',2,1,'«Oğul» sözü «oğlu» formasında işlənəndə hansı sait düşür?','Oğul → oğlu: ikinci hecadakı «u» saiti düşür.',array['u','o','ğ','l'],1),
('az6-fonetika#3','az-dili','az-6-fonetika',2,1,'«Qapı» sözünə yönlük hal şəkilçisi artıranda (qapıya) hansı samit əlavə olunur?','İki sait arasına bitişdirici «y» samiti artırılır.',array['y','n','s','ş'],1),
('az6-fonetika#4','az-dili','az-6-fonetika',3,1,'«Dostlar» sözünün tələffüzündə hansı samit düşür?','Üç samit yanaşı gələndə ortadakı düşür: [doslar].',array['t','d','s','r'],1),
('az6-fonetika#5','az-dili','az-6-fonetika',2,1,'Vurğu nədir?','Sözdə hecalardan birinin daha qüvvətli deyilməsidir.',array['Hecanın qüvvətli deyilməsi','Sözün mənası','Hərflərin sayı','Cümlənin sonu'],1),
('az6-fonetika#6','az-dili','az-6-fonetika',2,1,'Azərbaycan dilində vurğu adətən hansı hecaya düşür?','Dilimizdə vurğu əsasən son hecaya düşür.',array['Son hecaya','İlk hecaya','Orta hecaya','İstənilən hecaya'],1),
('az6-fonetika#7','az-dili','az-6-fonetika',3,1,'«Haqq» sözünə saitlə başlanan şəkilçi artıranda necə yazılır?','Qoşa samit saxlanılır: haqqı.',array['haqqı','haqı','hağı','haqqqı'],1),
('az6-fonetika#8','az-dili','az-6-fonetika',3,1,'«Stəkan» tipli sözlərin tələffüzündə bəzən nə baş verir?','Söz əvvəlindəki qoşa samitin qarşısına sait artırılır: [istəkan] — səsartımı.',array['Səsartımı','Səsdüşümü','Vurğu itir','Samit düşür'],1),
('az6-fonetika#9','az-dili','az-6-fonetika',1,1,'Danışıq səslərini öyrənən dilçilik bölməsi necə adlanır?','Səsləri fonetika öyrənir.',array['Fonetika','Leksika','Qrammatika','Orfoqrafiya'],1),
('az6-fonetika#10','az-dili','az-6-fonetika',2,1,'«Meyvə» sözündə neçə səs və neçə hərf var?','M-e-y-v-ə: 5 səs, 5 hərf.',array['5 səs, 5 hərf','4 səs, 5 hərf','5 səs, 4 hərf','6 səs, 5 hərf'],1),
('az6-fonetika#11','az-dili','az-6-fonetika',2,1,'«Burun» sözü mənsubiyyətlə işlənəndə (burnum) hansı hadisə baş verir?','Sait düşür — səsdüşümü hadisəsidir.',array['Səsdüşümü','Səsartımı','Vurğu dəyişməsi','Heç nə'],1),
('az6-fonetika#12','az-dili','az-6-fonetika',2,1,'«Ailəyə» sözündə hansı bitişdirici samit işlənib?','Sait qoşalaşmasın deyə y artırılır: ailə-y-ə.',array['y','n','s','k'],1),
('az6-fonetika#13','az-dili','az-6-fonetika',2,1,'Ahəng qanunu nəyə əsaslanır?','Sözdə saitlərin qalın və ya incəliyə görə uyuşmasına.',array['Saitlərin uyuşmasına','Samitlərin sayına','Vurğunun yerinə','Hecaların sayına'],1),
('az6-fonetika#14','az-dili','az-6-fonetika',2,1,'«Səhər» sözündə vurğu hansı hecaya düşür?','Vurğu son hecaya düşür: sə-hər.',array['İkinci (son) hecaya','Birinci hecaya','Hər ikisinə','Heç birinə'],1),
('az6-fonetika#15','az-dili','az-6-fonetika',3,1,'«Sinif» sözünə saitlə başlanan şəkilçi artıranda necə yazılır?','İkinci sait düşür: sinfi.',array['sinfi','sinifi','siniffi','sinifyi'],1),
('az6-fonetika#16','az-dili','az-6-fonetika',3,1,'«Alın» sözü mənsubiyyət şəkilçisi ilə necə işlənir?','Sait düşür: alnı.',array['alnı','alını','alının','alnnı'],1),
('az6-fonetika#17','az-dili','az-6-fonetika',2,1,'Sözlərin tələffüz qaydalarını hansı lüğət göstərir?','Orfoepiya lüğəti tələffüzü göstərir.',array['Orfoepiya lüğəti','Orfoqrafiya lüğəti','İzahlı lüğət','Tərcümə lüğəti'],1),
('az6-fonetika#18','az-dili','az-6-fonetika',2,1,'Sözlərin düzgün yazılış qaydalarını hansı bölmə öyrənir?','Orfoqrafiya yazı qaydalarını öyrənir.',array['Orfoqrafiya','Orfoepiya','Leksika','Sintaksis'],1),
('az6-fonetika#19','az-dili','az-6-fonetika',3,1,'«Nəqliyyat» sözündə hansı qoşa samit var?','Nəqliyyat sözündə yy qoşa yazılır.',array['yy','qq','ll','tt'],1),
('az6-fonetika#20','az-dili','az-6-fonetika',3,1,'«Metr» tipli sözlərin tələffüzündə sonda nə baş verir?','Tələffüzdə sait artırılır: metir.',array['Səsartımı','Səsdüşümü','Vurğu itir','Samit düşür'],1),
('az6-yazi#1','az-dili','az-6-yazi',2,1,'Hansı söz defislə yazılır?','Təkrar sözlər defislə yazılır: qaça-qaça.',array['qaça-qaça','dəmiryol','günəbaxan','kitabxana'],1),
('az6-yazi#2','az-dili','az-6-yazi',2,1,'Sözlərin təkrarından yaranan mürəkkəb sözlər necə yazılır?','Təkrardan yaranan sözlər defislə yazılır.',array['Defislə','Bitişik','Ayrı','Dırnaqda'],1),
('az6-yazi#3','az-dili','az-6-yazi',2,1,'Mürəkkəb şəxs adları (Əli + ağa) necə yazılır?','Mürəkkəb adlar bitişik yazılır: Əlağa.',array['Bitişik','Defislə','Ayrı','Kiçik hərflə'],1),
('az6-yazi#4','az-dili','az-6-yazi',2,1,'Hansı mürəkkəb yer adı düzgün yazılıb?','Mürəkkəb yer adları bitişik yazılır: Ağdam.',array['Ağdam','Ağ-dam','Ağ dam','ağdam'],1),
('az6-yazi#5','az-dili','az-6-yazi',3,1,'«Alma-armud» tipli sözlər nəyi bildirir?','Yaxın əşyaların ümumiləşmiş toplusunu bildirir.',array['Ümumiləşmiş topluluğu','Yalnız bir əşyanı','Hərəkəti','Rəngi'],1),
('az6-yazi#6','az-dili','az-6-yazi',3,1,'«Foto-» hissəsi ilə başlanan alınma sözlər necə yazılır?','Bitişik yazılır: fotoaparat.',array['Bitişik','Defislə','Ayrı','Dırnaqda'],1),
('az6-yazi#7','az-dili','az-6-yazi',2,1,'Hansı söz bitişik yazılır?','Kitabxana mürəkkəb söz kimi bitişik yazılır.',array['kitabxana','qaça-qaça','az-çox','beş-üç'],1),
('az6-yazi#8','az-dili','az-6-yazi',2,1,'«Az çox», «azçox», «az-çox» yazılışlarından hansı düzgündür?','Əks mənalı təkrar sözlər defislə yazılır: az-çox.',array['az-çox','azçox','az çox','az. çox'],1),
('az6-yazi#9','az-dili','az-6-yazi',3,1,'«Vitse-» hissəsi ilə düzələn vəzifə adları necə yazılır?','Defislə yazılır: vitse-prezident.',array['Defislə','Bitişik','Ayrı','Böyük hərflə bitişik'],1),
('az6-yazi#10','az-dili','az-6-yazi',3,1,'Hiperonim nədir?','Ümumi anlayış bildirən sözdür: «meyvə» — «alma» üçün hiperonimdir.',array['Ümumi anlayış bildirən söz','Əks mənalı söz','Alınma söz','Təkrar söz'],1),
('az6-yazi#11','az-dili','az-6-yazi',2,1,'«Qara + qaş» sözlərindən yaranan mürəkkəb söz necə yazılır?','Bitişik yazılır: qaraqaş.',array['Bitişik (qaraqaş)','Defislə (qara-qaş)','Ayrı (qara qaş)','Dırnaqda'],1),
('az6-yazi#12','az-dili','az-6-yazi',2,1,'«Tez-tez» sözü niyə defislə yazılır?','Təkrar sözlərdən yarandığı üçün.',array['Təkrar söz olduğu üçün','Alınma olduğu üçün','Xüsusi ad olduğu üçün','Səhvən'],1),
('az6-yazi#13','az-dili','az-6-yazi',2,1,'«Şimal-qərb» tipli istiqamət bildirən sözlər necə yazılır?','Belə sözlər defislə yazılır.',array['Defislə yazılır','Bitişik yazılır','Ayrı yazılır','Böyük hərflə bitişik'],1),
('az6-yazi#14','az-dili','az-6-yazi',2,1,'«İstiot» sözü hansı sözlərdən yaranıb?','İsti və ot sözlərindən.',array['isti və ot','ist və iot','isti və od','is və tiot'],1),
('az6-yazi#15','az-dili','az-6-yazi',2,1,'Bitişik yazılan mürəkkəb sözü seçin.','Əlüzyuyan bitişik yazılır.',array['əlüzyuyan','əl-üzyuyan','əl üz yuyan','əl-üz-yuyan'],1),
('az6-yazi#16','az-dili','az-6-yazi',3,1,'Dar, konkret anlayış bildirən söz necə adlanır?','Hiponim adlanır (alma — meyvə sözünün hiponimidir).',array['Hiponim','Hiperonim','Omonim','Antonim'],1),
('az6-yazi#17','az-dili','az-6-yazi',3,1,'«BMT» tipli qısaltmalar necə adlanır?','İxtisarlar (abreviaturalar) adlanır.',array['İxtisarlar (abreviatura)','Mürəkkəb sözlər','Qoşmalar','Şəkilçilər'],1),
('az6-yazi#18','az-dili','az-6-yazi',2,1,'Mürəkkəb sözlər neçə kökdən ibarət olur?','İki və daha artıq kökdən.',array['İki və daha artıq','Yalnız bir','Yalnız üç','Kökü olmur'],1),
('az6-yazi#19','az-dili','az-6-yazi',2,1,'«Günə + baxan» sözləri birləşəndə hansı söz yaranır?','Günəbaxan mürəkkəb sözü.',array['günəbaxan','günə-baxan','günə baxan','gün-baxan'],1),
('az6-yazi#20','az-dili','az-6-yazi',2,1,'Sitatlar hansı işarə ilə göstərilir?','Dırnaq işarəsi ilə.',array['Dırnaq işarəsi ilə','Vergüllə','Tire ilə yalnız','Mötərizə ilə'],1),
('az6-soz-luget#1','az-dili','az-6-soz-luget',2,2,'Sözün başlanğıc forması necə olur?','Qrammatik şəkilçilərsiz forma başlanğıc formadır.',array['Qrammatik şəkilçisiz','Cəm şəkilçili','Hal şəkilçili','Mənsubiyyət şəkilçili'],1),
('az6-soz-luget#2','az-dili','az-6-soz-luget',2,2,'«Kitablarımızdan» sözünün başlanğıc forması hansıdır?','Şəkilçiləri atsaq: kitab.',array['kitab','kitablar','kitabımız','kitabdan'],1),
('az6-soz-luget#3','az-dili','az-6-soz-luget',2,2,'Hansı cərgədə eyniköklü sözlər verilib?','Duz, duzlu, duzsuz — hamısı «duz» kökündəndir.',array['duz, duzlu, duzsuz','duz, dad, tam','su, çay, göl','gəl, get, dur'],1),
('az6-soz-luget#4','az-dili','az-6-soz-luget',2,2,'«Yazı, yazıçı, yazmaq» sözlərini birləşdirən cəhət nədir?','Üçü də «yaz» kökündən yaranıb — eyniköklüdür.',array['Eyni kökdən yaranmaları','Eyni şəkilçi','Eyni heca sayı','Əks mənalı olmaları'],1),
('az6-soz-luget#5','az-dili','az-6-soz-luget',2,2,'«Su» kökündən yaranan sözü seçin.','Sulu = su + lu.',array['sulu','sükan','sürü','süd'],1),
('az6-soz-luget#6','az-dili','az-6-soz-luget',2,2,'Sözün lüğəvi (leksik) mənasını daşıyan hissəsi hansıdır?','Əsas mənanı kök daşıyır.',array['Kök','Cəm şəkilçisi','Hal şəkilçisi','Sonluq'],1),
('az6-soz-luget#7','az-dili','az-6-soz-luget',3,2,'«Dənizçilik» sözündə neçə şəkilçi var?','Dəniz + çi + lik: iki leksik şəkilçi.',array['2','1','3','0'],1),
('az6-soz-luget#8','az-dili','az-6-soz-luget',2,2,'«Başla» sözünün kökü hansıdır?','Başla = baş + la.',array['baş','başla','la','aş'],1),
('az6-soz-luget#9','az-dili','az-6-soz-luget',3,2,'Eyniköklü sözlər hansı yolla yaranır?','Kökə leksik (sözdüzəldici) şəkilçilər artırmaqla.',array['Kökə leksik şəkilçilər artırmaqla','Sözü təkrarlamaqla','Vurğunu dəyişməklə','Hərfləri dəyişməklə'],1),
('az6-soz-luget#10','az-dili','az-6-soz-luget',2,2,'«Duzlu» və «dadlı» sözləri eyniköklüdürmü?','Kökləri fərqlidir (duz və dad) — eyniköklü deyil.',array['Xeyr, kökləri fərqlidir','Bəli, eyniköklüdür','Hər ikisi köksüzdür','Bilmək olmaz'],1),
('az6-soz-luget#11','az-dili','az-6-soz-luget',2,2,'«Daş» kökündən yaranan söz hansıdır?','Daşlı — daş kökündən düzəlib.',array['daşlı','dişli','düşərgə','dəstə'],1),
('az6-soz-luget#12','az-dili','az-6-soz-luget',2,2,'«Yol, yolçu, yoldaş» sözlərinin ortaq cəhəti nədir?','Hamısı yol kökündən yaranıb.',array['Eyni kökdən yaranmaları','Eyni şəkilçiləri','Cəm olmaları','Alınma olmaları'],1),
('az6-soz-luget#13','az-dili','az-6-soz-luget',3,2,'«Məktəblilərdən» sözünü başlanğıc formaya salın.','Qrammatik şəkilçilər atılır: məktəbli.',array['məktəbli','məktəb','məktəblilər','məktəbdən'],1),
('az6-soz-luget#14','az-dili','az-6-soz-luget',2,2,'«Sulu» sözündə hansı şəkilçi var?','-lu leksik şəkilçisidir.',array['-lu (leksik)','-su (kök)','-ulu','-l (qrammatik)'],1),
('az6-soz-luget#15','az-dili','az-6-soz-luget',2,2,'«Baş» sözü ilə «başlıq» sözünün əlaqəsi nədir?','Başlıq baş kökündən düzəlib.',array['Kök və düzəltmə söz','Sinonimlər','Antonimlər','Əlaqəsizdirlər'],1),
('az6-soz-luget#16','az-dili','az-6-soz-luget',2,2,'Kök şəkilçisiz müstəqil işlənə bilərmi?','Bəli — kök müstəqil sözdür.',array['Bəli, müstəqil işlənir','Xeyr, heç vaxt','Yalnız cəmdə','Yalnız şeirdə'],1),
('az6-soz-luget#17','az-dili','az-6-soz-luget',3,2,'«Dəmir — dəmirçi — dəmirçilik» cərgəsi necə yaranıb?','Kökə ardıcıl leksik şəkilçilər artırılıb.',array['Ardıcıl şəkilçi artırmaqla','Sözləri birləşdirməklə','Təkrarla','Alınma yolu ilə'],1),
('az6-soz-luget#18','az-dili','az-6-soz-luget',2,2,'«Gül» sözünə hansı şəkilçi artırsaq peşə adı yaranar?','Gülçü — gül becərən.',array['-çü','-lük','-süz','-də'],1),
('az6-soz-luget#19','az-dili','az-6-soz-luget',2,2,'Lüğəvi məna daşımayan hissə hansıdır?','Şəkilçinin lüğəvi mənası yoxdur.',array['Şəkilçi','Kök','Söz','Cümlə'],1),
('az6-soz-luget#20','az-dili','az-6-soz-luget',2,2,'«Duz» kökünə «-suz» şəkilçisi artıranda hansı məna yaranır?','Yoxluq mənası: duzsuz.',array['Yoxluq (duzsuz)','Çoxluq','Peşə','Məkan'],1),
('az6-isim-hal#1','az-dili','az-6-isim-hal',2,2,'Dilimizdə ismin hallarının sayı neçədir?','İsmin 6 halı var.',array['6','5','4','9'],1),
('az6-isim-hal#2','az-dili','az-6-isim-hal',2,2,'«Kitabı oxudum» cümləsində «kitabı» hansı haldadır?','Nəyi? sualına cavab verir — təsirlik haldadır.',array['Təsirlik','Adlıq','Yönlük','Yerlik'],1),
('az6-isim-hal#3','az-dili','az-6-isim-hal',1,2,'Adlıq hal hansı suallara cavab verir?','Adlıq hal «kim? nə? hara?» suallarına cavab verir.',array['Kim? Nə?','Kimin? Nəyin?','Kimə? Nəyə?','Kimdən? Nədən?'],1),
('az6-isim-hal#4','az-dili','az-6-isim-hal',2,2,'«Məktəbin həyəti» birləşməsində «məktəbin» hansı haldadır?','Kimin? nəyin? — yiyəlik haldadır.',array['Yiyəlik','Təsirlik','Çıxışlıq','Adlıq'],1),
('az6-isim-hal#5','az-dili','az-6-isim-hal',3,2,'Qeyri-müəyyən yiyəlik hala uyğun nümunə hansıdır?','«Sinif otağı» — birinci tərəf şəkilçisizdir.',array['sinif otağı','sinfin otağı','sinifdə otaq','sinifdən otaq'],1),
('az6-isim-hal#6','az-dili','az-6-isim-hal',2,2,'«Evə» sözü hansı haldadır?','Haraya? — yönlük haldadır.',array['Yönlük','Yerlik','Çıxışlıq','Yiyəlik'],1),
('az6-isim-hal#7','az-dili','az-6-isim-hal',2,2,'«Şəhərdə» sözünün halı hansıdır?','Harada? — yerlik haldır.',array['Yerlik','Yönlük','Təsirlik','Adlıq'],1),
('az6-isim-hal#8','az-dili','az-6-isim-hal',2,2,'«Kənddən» sözü hansı haldadır?','Haradan? — çıxışlıq haldadır.',array['Çıxışlıq','Yerlik','Yönlük','Yiyəlik'],1),
('az6-isim-hal#9','az-dili','az-6-isim-hal',3,2,'«Kitab oxuyuram» cümləsində «kitab» sözü hansı halda işlənib?','Şəkilçisiz təsirlik — qeyri-müəyyən təsirlik haldadır.',array['Qeyri-müəyyən təsirlik','Adlıq','Yiyəlik','Yerlik'],1),
('az6-isim-hal#10','az-dili','az-6-isim-hal',3,2,'«Suyu içdim» və «su içdim» ifadələrinin fərqi nədir?','Birincidə müəyyən, ikincidə qeyri-müəyyən təsirlik hal işlənib.',array['Müəyyən və qeyri-müəyyən təsirlik','Hal fərqi yoxdur','Birinci cəmdir','İkinci yiyəlikdədir'],1),
('az6-isim-hal#11','az-dili','az-6-isim-hal',2,2,'Yiyəlik hal hansı suallara cavab verir?','Kimin? nəyin? suallarına.',array['Kimin? Nəyin?','Kimə? Nəyə?','Kimdə? Nədə?','Kimdən? Nədən?'],1),
('az6-isim-hal#12','az-dili','az-6-isim-hal',2,2,'«Hara?» sualına ismin hansı halı cavab verir?','Yönlük hal hara? sualına da cavab verir.',array['Yönlük','Adlıq','Yerlik','Yiyəlik'],1),
('az6-isim-hal#13','az-dili','az-6-isim-hal',2,2,'«Ağacda» sözü hansı haldadır?','-da şəkilçisi yerlik halın göstəricisidir.',array['Yerlik','Yönlük','Çıxışlıq','Təsirlik'],1),
('az6-isim-hal#14','az-dili','az-6-isim-hal',2,2,'Çıxışlıq hal hansı şəkilçilərlə düzəlir?','-dan, -dən şəkilçiləri ilə.',array['-dan, -dən','-da, -də','-a, -ə','-ı, -i'],1),
('az6-isim-hal#15','az-dili','az-6-isim-hal',2,2,'Yiyəlik halın şəkilçiləri hansılardır?','-ın, -in, -un, -ün (samitdən sonra).',array['-ın, -in, -un, -ün','-a, -ə','-dan, -dən','-lar, -lər'],1),
('az6-isim-hal#16','az-dili','az-6-isim-hal',2,2,'Adlıq halda isim hansı formada olur?','Hal şəkilçisi olmur — şəkilçisiz formadadır.',array['Şəkilçisiz','-ı şəkilçili','-da şəkilçili','-dan şəkilçili'],1),
('az6-isim-hal#17','az-dili','az-6-isim-hal',2,2,'«Qapını» sözü hansı haldadır?','-nı şəkilçisi müəyyən təsirlik halı göstərir.',array['Təsirlik','Yiyəlik','Yerlik','Adlıq'],1),
('az6-isim-hal#18','az-dili','az-6-isim-hal',3,2,'İsim nəyə görə hallanır?','Cümlədəki vəzifəsinə (əlaqəsinə) görə.',array['Cümlədəki vəzifəsinə görə','Hecaların sayına görə','Rənginə görə','Təsadüfən'],1),
('az6-isim-hal#19','az-dili','az-6-isim-hal',3,2,'«Evdən məktəbə» ifadəsində hansı hallar işlənib?','Evdən — çıxışlıq, məktəbə — yönlük.',array['Çıxışlıq və yönlük','Adlıq və yiyəlik','Yerlik və təsirlik','Yalnız adlıq'],1),
('az6-isim-hal#20','az-dili','az-6-isim-hal',2,2,'Hal şəkilçiləri hansı şəkilçilər qrupuna aiddir?','Söz yaratmır — qrammatik şəkilçilərdir.',array['Qrammatik','Leksik','Sözdüzəldici','Heç biri'],1),
('az6-qosma-baglayici#1','az-dili','az-6-qosma-baglayici',2,3,'Qoşma hansı nitq hissələri qrupuna aiddir?','Qoşma köməkçi nitq hissəsidir.',array['Köməkçi','Əsas','İsim qrupuna','Feil qrupuna'],1),
('az6-qosma-baglayici#2','az-dili','az-6-qosma-baglayici',2,3,'«Məktəbə qədər» birləşməsində «qədər» sözü nədir?','Qədər — məsafə/hüdud bildirən qoşmadır.',array['Qoşma','İsim','Feil','Sifət'],1),
('az6-qosma-baglayici#3','az-dili','az-6-qosma-baglayici',2,3,'Bağlayıcılar nəyi bağlayır?','Sözləri və cümlələri bir-birinə bağlayır.',array['Sözləri və cümlələri','Yalnız hecaları','Yalnız hərfləri','Heç nəyi'],1),
('az6-qosma-baglayici#4','az-dili','az-6-qosma-baglayici',1,3,'«Və, amma, lakin» sözləri hansı nitq hissəsidir?','Bunlar bağlayıcılardır.',array['Bağlayıcı','Qoşma','Əvəzlik','Zərf'],1),
('az6-qosma-baglayici#5','az-dili','az-6-qosma-baglayici',2,3,'«Üçün» qoşması əsasən hansı mənanı bildirir?','Üçün — məqsəd və səbəb bildirir.',array['Məqsəd və səbəb','Zaman','Rəng','Say'],1),
('az6-qosma-baglayici#6','az-dili','az-6-qosma-baglayici',2,3,'«Yağış yağdı, amma biz gəzintiyə çıxdıq» cümləsində bağlayıcı hansıdır?','Amma — qarşılaşdırma bağlayıcısıdır.',array['amma','yağış','biz','çıxdıq'],1),
('az6-qosma-baglayici#7','az-dili','az-6-qosma-baglayici',3,3,'«Qədər, kimi, üçün» qoşmaları əsasən hansı sözlərə qoşulur?','Qoşmalar adlara (isimlərə, əvəzliklərə) qoşulur.',array['Adlara','Yalnız feillərə','Bağlayıcılara','Nidalara'],1),
('az6-qosma-baglayici#8','az-dili','az-6-qosma-baglayici',3,3,'Hansı cümlədə «ilə» birgəlik bildirir?','«Dostu ilə gəldi» — birlikdə gəlmə bildirir.',array['Dostu ilə gəldi.','Qatarla getdi.','Qələm ilə yazdı.','Sevinclə danışdı.'],1),
('az6-qosma-baglayici#9','az-dili','az-6-qosma-baglayici',2,3,'Hansı cərgədə yalnız qoşmalar verilib?','Kimi, qədər, üçün — hamısı qoşmadır.',array['kimi, qədər, üçün','və, ki, amma','mən, sən, o','tez, gec, indi'],1),
('az6-qosma-baglayici#10','az-dili','az-6-qosma-baglayici',3,3,'«Lakin» bağlayıcısı cümlələr arasında hansı əlaqəni yaradır?','Lakin — qarşılaşdırma (ziddiyyət) bildirir.',array['Qarşılaşdırma','Səbəb','Zaman ardıcıllığı','Bərabərlik'],1),
('az6-qosma-baglayici#11','az-dili','az-6-qosma-baglayici',3,3,'«Sonra» qoşması hansı halda olan sözlə işlənir?','Çıxışlıq halla: dərsdən sonra.',array['Çıxışlıq halla','Adlıq halla yalnız','Təsirlik halla','Yerlik halla'],1),
('az6-qosma-baglayici#12','az-dili','az-6-qosma-baglayici',2,3,'«Həm … həm də» hansı növ bağlayıcıdır?','Birləşdirmə bağlayıcısıdır.',array['Birləşdirmə','Qarşılaşdırma','Bölüşdürmə','İnkar'],1),
('az6-qosma-baglayici#13','az-dili','az-6-qosma-baglayici',2,3,'«Və ya» bağlayıcısı hansı əlaqəni bildirir?','Seçmə-bölüşdürmə əlaqəsini.',array['Bölüşdürmə (seçmə)','Qarşılaşdırma','Səbəb','Nəticə'],1),
('az6-qosma-baglayici#14','az-dili','az-6-qosma-baglayici',2,3,'«Kimi» qoşması əsasən hansı mənanı bildirir?','Bənzətmə mənasını: aslan kimi.',array['Bənzətmə','Zaman yalnız','Məkan','Say'],1),
('az6-qosma-baglayici#15','az-dili','az-6-qosma-baglayici',2,3,'«Dərsdən əvvəl» birləşməsində qoşma hansıdır?','Əvvəl sözü qoşmadır.',array['əvvəl','dərs','-dən','heç biri'],1),
('az6-qosma-baglayici#16','az-dili','az-6-qosma-baglayici',2,3,'Qoşmalar aid olduqları sözlə necə yazılır?','Ayrı yazılır: səhərə qədər.',array['Ayrı yazılır','Bitişik yazılır','Defislə yazılır','Dırnaqda yazılır'],1),
('az6-qosma-baglayici#17','az-dili','az-6-qosma-baglayici',2,3,'«Çünki» bağlayıcısı hansı əlaqəni bildirir?','Səbəb bildirir.',array['Səbəb','Bənzətmə','Birləşdirmə','Zaman'],1),
('az6-qosma-baglayici#18','az-dili','az-6-qosma-baglayici',2,3,'«Nə … nə də» bağlayıcısı cümləyə hansı mənanı verir?','İnkar mənasını verir.',array['İnkar','Təsdiq','Sual','Əmr'],1),
('az6-qosma-baglayici#19','az-dili','az-6-qosma-baglayici',3,3,'Köməkçi nitq hissələrinin əsas xüsusiyyəti nədir?','Müstəqil leksik mənası olmur.',array['Müstəqil mənasının olmaması','Cümlə üzvü olmaları','Hallanmaları','Cəmlənmələri'],1),
('az6-qosma-baglayici#20','az-dili','az-6-qosma-baglayici',2,3,'«Ancaq» sözü hansı bağlayıcıların sinonimidir?','Amma, lakin bağlayıcılarının.',array['Amma, lakin','Və, ilə','Çünki, ona görə','Yaxud, və ya'],1),
('az6-say-numerativ#1','az-dili','az-6-say-numerativ',2,3,'Saylardan sonra gələn isimlər hansı formada işlənir?','Saydan sonra isim təkdə olur: beş kitab.',array['Təkdə','Cəmdə','Yiyəlik halda','Çıxışlıq halda'],1),
('az6-say-numerativ#2','az-dili','az-6-say-numerativ',2,3,'«Beş kitablar» ifadəsindəki səhv nədir?','Saydan sonra isim cəmlənmir — «beş kitab» olmalıdır.',array['İsim cəmdə olmamalıdır','Say səhv yazılıb','Söz sırası səhvdir','Səhv yoxdur'],1),
('az6-say-numerativ#3','az-dili','az-6-say-numerativ',3,3,'Numerativ sözlər hansılardır?','Sayla isim arasında işlənən sözlərdir: nəfər, ədəd, baş.',array['Sayla isim arasında işlənən sözlər','Yalnız sıra sayları','Rəng bildirən sözlər','Bağlayıcılar'],1),
('az6-say-numerativ#4','az-dili','az-6-say-numerativ',2,3,'«Üç nəfər tələbə» ifadəsində numerativ söz hansıdır?','İnsanlar üçün «nəfər» numerativi işlənir.',array['nəfər','üç','tələbə','ifadədə yoxdur'],1),
('az6-say-numerativ#5','az-dili','az-6-say-numerativ',3,3,'Heyvanların sayını bildirmək üçün hansı numerativ söz işlənir?','Heyvanlar üçün «baş» işlənir: on baş qoyun.',array['baş','nəfər','cild','top'],1),
('az6-say-numerativ#6','az-dili','az-6-say-numerativ',2,3,'«Dənə» numerativ sözü nə üçün işlənir?','Ayrı-ayrı əşyaların sayı üçün: beş dənə alma.',array['Əşyaların sayı üçün','İnsanların sayı üçün','Kitabların cildi üçün','Vaxt üçün'],1),
('az6-say-numerativ#7','az-dili','az-6-say-numerativ',2,3,'Hansı ifadə düzgündür?','Ayaqqabı cütlə sayılır: iki cüt ayaqqabı.',array['iki cüt ayaqqabı','iki nəfər ayaqqabı','iki baş ayaqqabı','iki cild ayaqqabı'],1),
('az6-say-numerativ#8','az-dili','az-6-say-numerativ',2,3,'Sıra sayları rəqəmlə necə yazılır?','Şəkilçi defislə yazılır: 5-ci.',array['5-ci','5ci','5 ci','5.ci'],1),
('az6-say-numerativ#9','az-dili','az-6-say-numerativ',3,3,'«Yüzlərlə insan» ifadəsində say nəyi bildirir?','Dəqiq olmayan çoxluğu bildirir.',array['Qeyri-müəyyən çoxluğu','Dəqiq sayı','Sıranı','Kəsri'],1),
('az6-say-numerativ#10','az-dili','az-6-say-numerativ',2,3,'«Xeyli» sözü hansı miqdarı bildirir?','Xeyli — qeyri-müəyyən miqdar bildirir.',array['Qeyri-müəyyən miqdarı','Dəqiq miqdarı','Sıra sayını','Kəsr sayını'],1),
('az6-say-numerativ#11','az-dili','az-6-say-numerativ',2,3,'«Nəfər» numerativ sözü kimlər üçün işlənir?','İnsanların sayı üçün işlənir.',array['İnsanlar üçün','Heyvanlar üçün','Əşyalar üçün','Bitkilər üçün'],1),
('az6-say-numerativ#12','az-dili','az-6-say-numerativ',2,3,'Cansız əşyaların sayında «dənə» ilə yanaşı hansı numerativ işlənir?','Ədəd sözü də işlənir: beş ədəd dəftər.',array['ədəd','nəfər','baş','nüsxə yalnız'],1),
('az6-say-numerativ#13','az-dili','az-6-say-numerativ',2,3,'Kəsr saylar nəyi bildirir?','Tamın hissəsini bildirir.',array['Tamın hissəsini','Sıranı','Təxmini sayı','Yalnız çoxluğu'],1),
('az6-say-numerativ#14','az-dili','az-6-say-numerativ',3,3,'«Yarım» sözü hansı say növünə aiddir?','Tamın yarısını bildirir — kəsr saydır.',array['Kəsr saya','Sıra sayına','Miqdar sayına yalnız','Saya aid deyil'],1),
('az6-say-numerativ#15','az-dili','az-6-say-numerativ',2,3,'«Onlarla ağac əkildi» cümləsində «onlarla» nəyi bildirir?','Qeyri-müəyyən çoxluğu bildirir.',array['Qeyri-müəyyən çoxluğu','Dəqiq sayı','Sıranı','Kəsri'],1),
('az6-say-numerativ#16','az-dili','az-6-say-numerativ',2,3,'Miqdar sayları hansı suallara cavab verir?','Neçə? nə qədər? suallarına.',array['Neçə? Nə qədər?','Neçənci?','Necə?','Harada?'],1),
('az6-say-numerativ#17','az-dili','az-6-say-numerativ',2,3,'«2-ci» yazılışı düzgündürmü?','Bəli, sıra sayı belə yazılır.',array['Bəli, düzgündür','Xeyr, səhvdir','Yalnız 2ci olar','Yalnız «ikinci» yazılar'],1),
('az6-say-numerativ#18','az-dili','az-6-say-numerativ',2,3,'«Beş-altı adam» ifadəsi hansı miqdarı bildirir?','Təxmini miqdarı bildirir.',array['Təxmini miqdarı','Dəqiq miqdarı','Sıranı','Kəsri'],1),
('az6-say-numerativ#19','az-dili','az-6-say-numerativ',2,3,'Sıra sayları hansı şəkilçilərlə düzəlir?','-ıncı, -inci, -uncu, -üncü.',array['-ıncı, -inci, -uncu, -üncü','-lar, -lər','-dan, -dən','-çı, -çi'],1),
('az6-say-numerativ#20','az-dili','az-6-say-numerativ',3,3,'«Cüt» numerativ sözü hansı əşyalar üçün işlənir?','Qoşa işlənən əşyalar üçün: bir cüt corab.',array['Qoşa işlənən əşyalar üçün','Tək əşyalar üçün','Yalnız insanlar üçün','Maye üçün'],1),
('az6-cumle-uzvleri#1','az-dili','az-6-cumle-uzvleri',2,4,'Tamamlıq hansı suallara cavab verir?','Tamamlıq hallara uyğun «kimi? nəyi? kimə? nəyə?» və s. suallarına cavab verir.',array['Kimi? Nəyi? Kimə? Nəyə?','Necə? Nə cür?','Nə vaxt? Harada?','Neçə? Neçənci?'],1),
('az6-cumle-uzvleri#2','az-dili','az-6-cumle-uzvleri',2,4,'«Şagird kitabı oxudu» cümləsində tamamlıq hansıdır?','Nəyi oxudu? — kitabı.',array['kitabı','şagird','oxudu','cümlədə yoxdur'],1),
('az6-cumle-uzvleri#3','az-dili','az-6-cumle-uzvleri',2,4,'Təyin cümlədə nəyi bildirir?','Təyin əşyanın əlamətini bildirir.',array['Əşyanın əlamətini','Hərəkətin vaxtını','Hərəkətin yerini','Hökmü'],1),
('az6-cumle-uzvleri#4','az-dili','az-6-cumle-uzvleri',2,4,'«Maraqlı film izlədik» cümləsində təyin hansıdır?','Hansı film? — maraqlı.',array['maraqlı','film','izlədik','cümlədə yoxdur'],1),
('az6-cumle-uzvleri#5','az-dili','az-6-cumle-uzvleri',2,4,'Zərflik cümlədə hansı suallara cavab verir?','Zərflik «necə? harada? nə vaxt?» suallarına cavab verir.',array['Necə? Harada? Nə vaxt?','Kim? Nə?','Kimin? Nəyin?','Neçənci?'],1),
('az6-cumle-uzvleri#6','az-dili','az-6-cumle-uzvleri',2,4,'«Uşaqlar həyətdə oynayır» cümləsində zərflik hansıdır?','Harada oynayır? — həyətdə.',array['həyətdə','uşaqlar','oynayır','cümlədə yoxdur'],1),
('az6-cumle-uzvleri#7','az-dili','az-6-cumle-uzvleri',3,4,'«Dünən qonaq gəldi» cümləsində «dünən» hansı üzvdür?','Nə vaxt? — zaman zərfliyidir.',array['Zaman zərfliyi','Tamamlıq','Təyin','Mübtəda'],1),
('az6-cumle-uzvleri#8','az-dili','az-6-cumle-uzvleri',2,4,'«Hansı?» sualına cavab verən cümlə üzvü hansıdır?','Əlamət bildirən üzv təyindir.',array['Təyin','Tamamlıq','Zərflik','Xəbər'],1),
('az6-cumle-uzvleri#9','az-dili','az-6-cumle-uzvleri',3,4,'«Kitabı dostuma verdim» cümləsində «dostuma» hansı üzvdür?','Kimə verdim? — tamamlıqdır.',array['Tamamlıq','Təyin','Zərflik','Mübtəda'],1),
('az6-cumle-uzvleri#10','az-dili','az-6-cumle-uzvleri',3,4,'İkinci dərəcəli üzvlər cümlədə nə edir?','Baş üzvlərin məzmununu genişləndirib dəqiqləşdirir.',array['Baş üzvləri izah edib genişləndirir','Cümləni qısaldır','Yalnız bəzək üçündür','Fikri dəyişdirir'],1),
('az6-cumle-uzvleri#11','az-dili','az-6-cumle-uzvleri',2,4,'Mübtəda cümlədə nəyi bildirir?','Haqqında danışılanı (iş görəni).',array['İş görəni (haqqında danışılanı)','Hərəkətin yerini','Əşyanın əlamətini yalnız','Sayı'],1),
('az6-cumle-uzvleri#12','az-dili','az-6-cumle-uzvleri',3,4,'Mübtəda ilə xəbər arasındakı uzlaşma nəyə əsaslanır?','Şəxsə və kəmiyyətə görə.',array['Şəxsə və kəmiyyətə görə','Rəngə görə','Hecaya görə','Uzlaşmır'],1),
('az6-cumle-uzvleri#13','az-dili','az-6-cumle-uzvleri',2,4,'«Quşlar yuva qurur» cümləsində xəbər hansıdır?','Hərəkəti bildirən söz: qurur.',array['qurur','quşlar','yuva','cümlə'],1),
('az6-cumle-uzvleri#14','az-dili','az-6-cumle-uzvleri',2,4,'«Dünən», «bu gün» sözləri hansı zərfliyi yaradır?','Zaman zərfliyi olur.',array['Zaman zərfliyi','Yer zərfliyi','Tərz zərfliyi','Təyin'],1),
('az6-cumle-uzvleri#15','az-dili','az-6-cumle-uzvleri',2,4,'«Sürətlə qaçdı» cümləsində «sürətlə» hansı zərflikdir?','Hərəkətin tərzini bildirir.',array['Tərzi-hərəkət','Zaman','Yer','Səbəb'],1),
('az6-cumle-uzvleri#16','az-dili','az-6-cumle-uzvleri',3,4,'Tamamlıq hansı hallarda olan sözlərlə ifadə olunur?','Adlıq və yiyəlikdən başqa hallarda.',array['Adlıq və yiyəlikdən başqa hallarda','Yalnız adlıqda','Yalnız yiyəlikdə','Halsız sözlərlə'],1),
('az6-cumle-uzvleri#17','az-dili','az-6-cumle-uzvleri',2,4,'«Yaşıl yarpaqlar» birləşməsində «yaşıl» cümlədə hansı üzv olur?','Əlamət bildirir — təyindir.',array['Təyin','Mübtəda','Xəbər','Zərflik'],1),
('az6-cumle-uzvleri#18','az-dili','az-6-cumle-uzvleri',2,4,'«Harada?» sualına hansı üzv cavab verir?','Yer zərfliyi cavab verir.',array['Yer zərfliyi','Tamamlıq','Təyin','Mübtəda'],1),
('az6-cumle-uzvleri#19','az-dili','az-6-cumle-uzvleri',2,4,'Cümlədə «nəyi?» sualı verilərsə hansı üzvü tapırıq?','Nəyi? sualına tamamlıq cavab verir.',array['Tamamlıq','Təyin','Zərflik','Xəbər'],1),
('az6-cumle-uzvleri#20','az-dili','az-6-cumle-uzvleri',3,4,'Müəyyən təsirlik halda tamamlıq hansı şəkilçiləri daşıyır?','-ı, -i, -u, -ü şəkilçilərini.',array['-ı, -i, -u, -ü','-da, -də','-dan, -dən','-ın, -in'],1),
('az6-soz-sirasi#1','az-dili','az-6-soz-sirasi',2,4,'Azərbaycan dilində mübtəda adətən cümlənin harasında durur?','Mübtəda adətən cümlənin əvvəlində gəlir.',array['Əvvəlində','Sonunda','Yalnız ortasında','Qaydası yoxdur'],1),
('az6-soz-sirasi#2','az-dili','az-6-soz-sirasi',3,4,'«Kitabı Aysu oxudu» cümləsində söz sırası nəyi qüvvətləndirir?','Önə çəkilən «kitabı» sözü məntiqi vurğu alır.',array['«Kitabı» sözünü','«Oxudu» sözünü','Heç nəyi','Cümlənin sonunu'],1),
('az6-soz-sirasi#3','az-dili','az-6-soz-sirasi',3,4,'Söz birləşməsində asılı tərəf adətən harada durur?','Asılı tərəf əsas tərəfdən əvvəl gəlir: dəniz sahili.',array['Əsas tərəfdən əvvəl','Əsas tərəfdən sonra','Cümlənin sonunda','İstənilən yerdə'],1),
('az6-soz-sirasi#4','az-dili','az-6-soz-sirasi',3,4,'«Dağların zirvəsi» birləşməsində tərəflər nə ilə bağlanıb?','Yiyəlik hal (-ların) və mənsubiyyət (-i) şəkilçiləri ilə.',array['Yiyəlik hal və mənsubiyyət şəkilçiləri ilə','Yalnız vurğu ilə','Bağlayıcı ilə','Qoşma ilə'],1),
('az6-soz-sirasi#5','az-dili','az-6-soz-sirasi',2,4,'Söz sırası dəyişəndə cümlədə nə dəyişə bilər?','Məna çaları və məntiqi vurğu dəyişir.',array['Məna çaları və vurğu','Hərflərin sayı','Sözlərin kökü','Heç nə'],1),
('az6-soz-sirasi#6','az-dili','az-6-soz-sirasi',2,4,'Söz birləşməsi cümlədən nə ilə fərqlənir?','Birləşmə bitmiş fikir bildirmir.',array['Bitmiş fikir bildirməməsi ilə','Sözlərin çoxluğu ilə','Böyük hərflə','Nöqtə ilə'],1),
('az6-soz-sirasi#7','az-dili','az-6-soz-sirasi',2,4,'İsmi birləşmənin əsas tərəfi adətən hansı nitq hissəsi olur?','Əsas tərəf isim olur: gözəl mənzərə.',array['İsim','Feil','Bağlayıcı','Nida'],1),
('az6-soz-sirasi#8','az-dili','az-6-soz-sirasi',3,4,'«Oxumaq arzusu» birləşməsində birinci tərəf hansı formadadır?','Oxumaq — məsdərdir.',array['Məsdər','Feili sifət','Sifət','Say'],1),
('az6-soz-sirasi#9','az-dili','az-6-soz-sirasi',2,4,'Cümlədə sözlər arasında əlaqəni nə yaradır?','Şəkilçilər və söz sırası əlaqə yaradır.',array['Şəkilçilər və söz sırası','Yalnız nöqtələr','Hərflərin rəngi','Sətirlər'],1),
('az6-soz-sirasi#10','az-dili','az-6-soz-sirasi',3,4,'«Mən məktəbə gedirəm» cümləsi hansı sıra qaydasına uyğundur?','Mübtəda + tamamlıq/zərflik + xəbər sırası ilə qurulub.',array['Mübtəda + zərflik + xəbər','Xəbər + mübtəda','Təyin + təyin + təyin','Sıra pozulub'],1),
('az6-soz-sirasi#11','az-dili','az-6-soz-sirasi',2,4,'Azərbaycan dilində xəbər cümlənin adətən hansı yerində gəlir?','Xəbər adətən sonda durur.',array['Sonunda','Əvvəlində','Ortasında hökmən','İstənilən yerdə fərqsiz'],1),
('az6-soz-sirasi#12','az-dili','az-6-soz-sirasi',2,4,'Təyin təyin etdiyi sözə nəzərən harada durur?','Təyin olunandan əvvəl gəlir.',array['Əvvəl','Sonra','Cümlənin sonunda','Ayrıca sətirdə'],1),
('az6-soz-sirasi#13','az-dili','az-6-soz-sirasi',2,4,'«Aysunun kitabı» birləşməsi hansı birləşmə növüdür?','Əsas tərəfi isimdir — ismi birləşmədir.',array['İsmi birləşmə','Feili birləşmə','Cümlə','Frazeologizm'],1),
('az6-soz-sirasi#14','az-dili','az-6-soz-sirasi',2,4,'Feili birləşmənin əsas tərəfi hansı nitq hissəsi olur?','Əsas tərəf feil (məsdər, feili sifət) olur.',array['Feil','İsim','Sifət','Say'],1),
('az6-soz-sirasi#15','az-dili','az-6-soz-sirasi',2,4,'«Kitab oxumaq» birləşməsi hansı növdəndir?','Əsas tərəf məsdərdir — feili birləşmədir.',array['Feili birləşmə','İsmi birləşmə','Sadə cümlə','Mürəkkəb söz'],1),
('az6-soz-sirasi#16','az-dili','az-6-soz-sirasi',2,4,'Söz sırasının pozulması nəyə səbəb ola bilər?','Fikir çətin anlaşılar.',array['Fikrin çətin anlaşılmasına','Sözlərin itməsinə','Hərflərin dəyişməsinə','Heç nəyə'],1),
('az6-soz-sirasi#17','az-dili','az-6-soz-sirasi',2,4,'«Sabah biz muzeyə gedəcəyik» cümləsində zaman zərfliyi harada durur?','Cümlənin əvvəlində gəlib.',array['Cümlənin əvvəlində','Cümlənin sonunda','Xəbərdən sonra','Cümlədə yoxdur'],1),
('az6-soz-sirasi#18','az-dili','az-6-soz-sirasi',3,4,'Söz birləşməsində əsas tərəf adətən hansı mövqedə olur?','Asılı tərəfdən sonra — sonda durur.',array['Sonda duran tərəfdir','Əvvəldə duran tərəfdir','Ortada olur','Mövqeyi yoxdur'],1),
('az6-soz-sirasi#19','az-dili','az-6-soz-sirasi',2,4,'Cümləni genişləndirmək üçün nə əlavə olunur?','İkinci dərəcəli üzvlər əlavə olunur.',array['İkinci dərəcəli üzvlər','Yalnız nida','Yalnız bağlayıcı','Hərflər'],1),
('az6-soz-sirasi#20','az-dili','az-6-soz-sirasi',2,4,'«Mənim dostum» birləşməsində asılı tərəf hansıdır?','Mənim — asılı tərəfdir.',array['mənim','dostum','hər ikisi','heç biri'],1),
('ing6-town#1','ingilis-dili','ing-6-town',2,1,'Which place sells bread and cakes?','Çörək və tort çörəkxanada (bakery) satılır.',array['bakery','library','bank','stadium'],1),
('ing6-town#2','ingilis-dili','ing-6-town',1,1,'A library is a place where we can ___.','Kitabxanada kitab oxuyuruq.',array['read books','swim','buy shoes','play football'],1),
('ing6-town#3','ingilis-dili','ing-6-town',1,1,'There ___ a big park in our town.','Təkdə: there is.',array['is','are','am','be'],1),
('ing6-town#4','ingilis-dili','ing-6-town',2,1,'Where can we buy medicine?','Dərman aptekdə satılır: at the chemist.',array['at the chemist','at the bakery','at the stadium','at the cinema'],1),
('ing6-town#5','ingilis-dili','ing-6-town',1,1,'«Museum» nə üçündür?','Muzeydə tarixi əşyalara baxırıq.',array['Tarixi əşyalara baxmaq üçün','Yemək almaq üçün','Üzmək üçün','Avtobus gözləmək üçün'],1),
('ing6-town#6','ingilis-dili','ing-6-town',2,1,'«I ___ go to the cinema on Sundays.» (həmişə)','Həmişə — always.',array['always','never','town','where'],1),
('ing6-town#7','ingilis-dili','ing-6-town',1,1,'«Never» nə deməkdir?','Never — heç vaxt.',array['Heç vaxt','Həmişə','Bəzən','Tez-tez'],1),
('ing6-town#8','ingilis-dili','ing-6-town',2,1,'«The bank is ___ the post office and the cafe.»','İkisinin arasında: between.',array['between','under','on','up'],1),
('ing6-town#9','ingilis-dili','ing-6-town',2,1,'«Are there any shops near here?» sualına qısa cavab hansıdır?','Cəmdə qısa cavab: Yes, there are.',array['Yes, there are.','Yes, there is.','Yes, it does.','No, they can.'],1),
('ing6-town#10','ingilis-dili','ing-6-town',2,1,'«Town» və «city» sözlərinin fərqi nədir?','City böyük şəhərdir, town kiçik şəhərdir.',array['City daha böyükdür','Town daha böyükdür','Eyni sözlərdir','İkisi də kənddir'],1),
('ing6-town#11','ingilis-dili','ing-6-town',1,1,'«Hospital» nədir?','Hospital — xəstəxana.',array['Xəstəxana','Məktəb','Mağaza','Kitabxana'],1),
('ing6-town#12','ingilis-dili','ing-6-town',2,1,'«Post office» nə üçündür?','Məktub və bağlama göndərmək üçün.',array['Məktub göndərmək üçün','Yemək almaq üçün','Film izləmək üçün','İdman üçün'],1),
('ing6-town#13','ingilis-dili','ing-6-town',2,1,'«Opposite» sözünün mənası nədir?','Opposite — qarşısında.',array['Qarşısında','Yanında','Arxasında','İçində'],1),
('ing6-town#14','ingilis-dili','ing-6-town',1,1,'«Turn left» əmri nə deməkdir?','Sola dön.',array['Sola dön','Sağa dön','Düz get','Dayan'],1),
('ing6-town#15','ingilis-dili','ing-6-town',2,1,'«Usually» sözünün mənası nədir?','Usually — adətən.',array['Adətən','Heç vaxt','Dərhal','Tezliklə'],1),
('ing6-town#16','ingilis-dili','ing-6-town',2,1,'«Sometimes» nə deməkdir?','Sometimes — bəzən.',array['Bəzən','Həmişə','Dünən','Sabah'],1),
('ing6-town#17','ingilis-dili','ing-6-town',1,1,'Where can we watch a film?','Filmi kinoteatrda izləyirik.',array['At the cinema','At the bakery','At the bank','At the chemist'],1),
('ing6-town#18','ingilis-dili','ing-6-town',1,1,'«Street» sözünün mənası nədir?','Street — küçə.',array['Küçə','Ev','Meydan','Bina'],1),
('ing6-town#19','ingilis-dili','ing-6-town',2,1,'«How can I get to the park?» sualı nəyi soruşur?','Parka gedən yolu.',array['Yolu','Vaxtı','Qiyməti','Havanı'],1),
('ing6-town#20','ingilis-dili','ing-6-town',1,1,'«Bridge» nə deməkdir?','Bridge — körpü.',array['Körpü','Yol','Tunel','Çəpər'],1),
('ing6-food#1','ingilis-dili','ing-6-food',2,1,'«Can I have some water, please?» cümləsi nəyi bildirir?','Can burada icazə və xahiş bildirir.',array['Nəzakətli xahişi','Əmri','Qadağanı','Təəccübü'],1),
('ing6-food#2','ingilis-dili','ing-6-food',2,1,'Which word is a vegetable?','Carrot (kök) tərəvəzdir; qalanları meyvədir.',array['carrot','apple','cherry','peach'],1),
('ing6-food#3','ingilis-dili','ing-6-food',1,1,'«Delicious» nə deməkdir?','Delicious — çox dadlı.',array['Çox dadlı','Acı','Soyuq','Boş'],1),
('ing6-food#4','ingilis-dili','ing-6-food',2,1,'«___ likes pizza.» (o — qız)','Qız üçün mübtəda əvəzliyi: She.',array['She','Her','Him','Us'],1),
('ing6-food#5','ingilis-dili','ing-6-food',2,1,'«I see ___ every day.» (onu — oğlanı)','Tamamlıq əvəzliyi: him.',array['him','he','his','she'],1),
('ing6-food#6','ingilis-dili','ing-6-food',2,1,'«Let us make a salad» cümləsi nədir?','Bu, təklifdir (gəlin salat hazırlayaq).',array['Təklif','Sual','Qadağa','Təəssüf'],1),
('ing6-food#7','ingilis-dili','ing-6-food',2,1,'«Fry» feili nə deməkdir?','Fry — qızartmaq.',array['Qızartmaq','Qaynatmaq','Doğramaq','Soyutmaq'],1),
('ing6-food#8','ingilis-dili','ing-6-food',2,1,'«Boil» feili hansı hərəkəti bildirir?','Boil — qaynatmaq.',array['Qaynatmaq','Qızartmaq','Kəsmək','Yumaq'],1),
('ing6-food#9','ingilis-dili','ing-6-food',2,1,'Which meal is in the middle of the day?','Günorta yeməyi — lunch.',array['lunch','breakfast','dinner','supper'],1),
('ing6-food#10','ingilis-dili','ing-6-food',2,1,'«Would you like some tea?» sualına nəzakətli cavab hansıdır?','Nəzakətli qəbul: Yes, please.',array['Yes, please.','Give me!','No!','Go away.'],1),
('ing6-food#11','ingilis-dili','ing-6-food',1,1,'Which word is a fruit?','Apple (alma) meyvədir.',array['apple','carrot','potato','onion'],1),
('ing6-food#12','ingilis-dili','ing-6-food',2,1,'«Sweet» sözünün mənası nədir?','Sweet — şirin.',array['Şirin','Acı','Duzlu','Turş'],1),
('ing6-food#13','ingilis-dili','ing-6-food',2,1,'«Cut the bread» nə deməkdir?','Çörəyi kəs.',array['Çörəyi kəs','Çörəyi bişir','Çörəyi at','Çörək al'],1),
('ing6-food#14','ingilis-dili','ing-6-food',2,1,'«I am hungry» cümləsi nəyi bildirir?','Ac olmağı bildirir.',array['Ac olmağı','Yorğun olmağı','Susamağı','Sevincli olmağı'],1),
('ing6-food#15','ingilis-dili','ing-6-food',1,1,'Which drink is usually hot?','Çay isti içilir.',array['tea','juice','cola','ice water'],1),
('ing6-food#16','ingilis-dili','ing-6-food',1,1,'«Salt» sözünün mənası nədir?','Salt — duz.',array['Duz','Şəkər','Un','İstiot'],1),
('ing6-food#17','ingilis-dili','ing-6-food',2,1,'«He ___ not like fish.»','III şəxs təkdə: does not.',array['does','do','is','are'],1),
('ing6-food#18','ingilis-dili','ing-6-food',2,1,'«Menu» nədir?','Yeməklərin siyahısı.',array['Yeməklərin siyahısı','Mətbəx aləti','Süfrə','Aşpaz'],1),
('ing6-food#19','ingilis-dili','ing-6-food',2,1,'«Taste» feilinin mənası nədir?','Taste — dadmaq.',array['Dadmaq','Tökmək','Doğramaq','Yumaq'],1),
('ing6-food#20','ingilis-dili','ing-6-food',3,1,'«Some milk» ifadəsində «some» nəyi bildirir?','Qeyri-müəyyən miqdarı bildirir.',array['Qeyri-müəyyən miqdarı','Dəqiq litri','Rəngi','Temperaturu'],1),
('ing6-holiday#1','ingilis-dili','ing-6-holiday',2,2,'«I was in Paris last summer» cümləsi hansı zamandadır?','Was — be feilinin keçmiş formasıdır: Past Simple.',array['Past Simple','Present Simple','Gələcək zaman','Past Continuous'],1),
('ing6-holiday#2','ingilis-dili','ing-6-holiday',2,2,'«There ___ many tourists on the beach yesterday.»','Cəmdə keçmiş: there were.',array['were','was','is','am'],1),
('ing6-holiday#3','ingilis-dili','ing-6-holiday',2,2,'«She ___ very happy on holiday.» (keçmiş)','She ilə: was.',array['was','were','are','be'],1),
('ing6-holiday#4','ingilis-dili','ing-6-holiday',1,2,'«Beach» nə deməkdir?','Beach — çimərlik.',array['Çimərlik','Dağ','Meşə','Muzey'],1),
('ing6-holiday#5','ingilis-dili','ing-6-holiday',1,2,'«Hotel» sözünün mənası nədir?','Hotel — mehmanxana.',array['Mehmanxana','Xəstəxana','Məktəb','Mağaza'],1),
('ing6-holiday#6','ingilis-dili','ing-6-holiday',2,2,'«Sightseeing» nə deməkdir?','Sightseeing — görməli yerləri gəzmək.',array['Görməli yerləri gəzmək','Yemək bişirmək','Ev tapşırığı etmək','Yatmaq'],1),
('ing6-holiday#7','ingilis-dili','ing-6-holiday',2,2,'Which one do you need to travel to another country?','Başqa ölkəyə pasportla gedirik.',array['passport','sofa','fridge','pillow'],1),
('ing6-holiday#8','ingilis-dili','ing-6-holiday',2,2,'«There was a swimming pool at the hotel.» — Oteldə nə var idi?','Swimming pool — üzgüçülük hovuzu.',array['Üzgüçülük hovuzu','Kitabxana','Stadion','Meşə'],1),
('ing6-holiday#9','ingilis-dili','ing-6-holiday',2,2,'«Suitcase» nədir?','Suitcase — çamadan.',array['Çamadan','Papaq','Xəritə','Bilet'],1),
('ing6-holiday#10','ingilis-dili','ing-6-holiday',2,2,'«What a holiday!» nidası nəyi ifadə edir?','Heyranlığı bildirir: necə də gözəl tətil!',array['Heyranlığı','Qəzəbi','Yorğunluğu','Sualı'],1),
('ing6-holiday#11','ingilis-dili','ing-6-holiday',2,2,'«We visited a museum.» — feil hansı zamandadır?','Visited — Past Simple.',array['Past Simple','Present Continuous','Future','Past Continuous'],1),
('ing6-holiday#12','ingilis-dili','ing-6-holiday',1,2,'«Ticket» sözünün mənası nədir?','Ticket — bilet.',array['Bilet','Çanta','Xəritə','Açar'],1),
('ing6-holiday#13','ingilis-dili','ing-6-holiday',1,2,'«Sea» nə deməkdir?','Sea — dəniz.',array['Dəniz','Göl','Çay','Dağ'],1),
('ing6-holiday#14','ingilis-dili','ing-6-holiday',2,2,'«We took photos» nə deməkdir?','Şəkil çəkdik.',array['Şəkil çəkdik','Şəkil sildik','Şəkil aldıq mağazadan','Şəkil satdıq'],1),
('ing6-holiday#15','ingilis-dili','ing-6-holiday',2,2,'«Where did you stay?» sualı nəyi soruşur?','Harada qaldığını.',array['Harada qaldığını','Nə yediyini','Kimi gördüyünü','Nə vaxt qayıtdığını'],1),
('ing6-holiday#16','ingilis-dili','ing-6-holiday',1,2,'«Sunny» sözü havanı necə təsvir edir?','Günəşli hava.',array['Günəşli','Yağışlı','Küləkli','Qarlı'],1),
('ing6-holiday#17','ingilis-dili','ing-6-holiday',2,2,'«Trip» sözünün mənası nədir?','Trip — səfər, gəzinti.',array['Səfər (gəzinti)','Yuxu','Dərs','Yemək'],1),
('ing6-holiday#18','ingilis-dili','ing-6-holiday',2,2,'«Souvenir» nədir?','Səfərdən gətirilən xatirə hədiyyəsi.',array['Xatirə hədiyyəsi','Sənəd','Nəqliyyat növü','Yemək adı'],1),
('ing6-holiday#19','ingilis-dili','ing-6-holiday',1,2,'«Last month» ifadəsinin mənası nədir?','Keçən ay.',array['Keçən ay','Gələn ay','Bu ay','Hər ay'],1),
('ing6-holiday#20','ingilis-dili','ing-6-holiday',2,2,'«Camp» sözü nəyi bildirir?','Camp — düşərgə.',array['Düşərgəni','Oteli','Muzeyi','Limanı'],1),
('ing6-stories#1','ingilis-dili','ing-6-stories',2,2,'«Walk» feilinin Past Simple forması hansıdır?','Qaydalı feil: walked.',array['walked','walking','walks','wolk'],1),
('ing6-stories#2','ingilis-dili','ing-6-stories',2,2,'«Write» feilinin keçmiş forması hansıdır?','Qaydasız feil: wrote.',array['wrote','writed','written by','writes'],1),
('ing6-stories#3','ingilis-dili','ing-6-stories',2,2,'«Once upon a time» ifadəsi nə deməkdir?','Nağıl başlanğıcı: biri var idi, biri yox idi.',array['Biri var idi, biri yox idi','Sonra görüşərik','Sabahın xeyir','Nə baş verdi'],1),
('ing6-stories#4','ingilis-dili','ing-6-stories',2,2,'«Tell» feilinin keçmişi hansıdır?','Qaydasız feil: told.',array['told','telled','tells','telling'],1),
('ing6-stories#5','ingilis-dili','ing-6-stories',3,2,'«They did not ___ the film.» boşluğu doldurun.','Did not-dan sonra əsas forma: like.',array['like','liked','likes','liking'],1),
('ing6-stories#6','ingilis-dili','ing-6-stories',2,2,'«___ week» (keçən həftə) — boşluğu doldurun.','Keçən — last: last week.',array['last','next','this','every'],1),
('ing6-stories#7','ingilis-dili','ing-6-stories',1,2,'Nağılda əsas obraz necə adlanır? (ingiliscə)','Əsas qəhrəman — hero.',array['hero','table','window','lesson'],1),
('ing6-stories#8','ingilis-dili','ing-6-stories',3,2,'«Begin» feilinin Past Simple forması hansıdır?','Qaydasız feil: began.',array['began','beginned','begins','begun to'],1),
('ing6-stories#9','ingilis-dili','ing-6-stories',2,2,'«The story ended happily.» — Hekayə necə bitdi?','Happily — xoşbəxt sonluqla.',array['Xoşbəxt sonluqla','Kədərlə','Sualla','Bitmədi'],1),
('ing6-stories#10','ingilis-dili','ing-6-stories',2,2,'«First, then, finally» sözləri mətndə nə üçün işlənir?','Hadisələrin ardıcıllığını göstərmək üçün.',array['Hadisələrin ardıcıllığı üçün','Rəngləri saymaq üçün','Sual vermək üçün','Salamlaşmaq üçün'],1),
('ing6-stories#11','ingilis-dili','ing-6-stories',2,2,'«Go» feilinin Past Simple forması hansıdır?','Go — went.',array['went','goed','gone','going'],1),
('ing6-stories#12','ingilis-dili','ing-6-stories',2,2,'«See» feilinin keçmiş forması hansıdır?','See — saw.',array['saw','seed','seen','sees'],1),
('ing6-stories#13','ingilis-dili','ing-6-stories',2,2,'«Character» sözü hekayədə nəyi bildirir?','Hekayənin obrazını.',array['Obrazı','Səhifəni','Müəllifi yalnız','Qiyməti'],1),
('ing6-stories#14','ingilis-dili','ing-6-stories',1,2,'«The end» ifadəsi nə deməkdir?','Son.',array['Son','Başlanğıc','Orta','Davamı var'],1),
('ing6-stories#15','ingilis-dili','ing-6-stories',2,2,'«Did you read the story? — Yes, I ___.»','Qısa cavab: did.',array['did','do','read not','was'],1),
('ing6-stories#16','ingilis-dili','ing-6-stories',1,2,'«Yesterday» sözünün mənası nədir?','Yesterday — dünən.',array['Dünən','Sabah','Bu gün','Keçən il'],1),
('ing6-stories#17','ingilis-dili','ing-6-stories',2,2,'«Fairy tale» nə deməkdir?','Fairy tale — nağıl.',array['Nağıl','Qəzet','Məktub','Reklam'],1),
('ing6-stories#18','ingilis-dili','ing-6-stories',2,2,'«He did not go to school.» cümləsi nəyi bildirir?','Keçmişdə getmədiyini.',array['Məktəbə getmədiyini','Məktəbə getdiyini','Məktəbə gedəcəyini','Məktəbi sevdiyini'],1),
('ing6-stories#19','ingilis-dili','ing-6-stories',3,2,'«Ago» sözü hansı zamanla işlənir?','Two days ago — Past Simple ilə.',array['Past Simple ilə','Future ilə','Present Continuous ilə','Heç biri ilə'],1),
('ing6-stories#20','ingilis-dili','ing-6-stories',3,2,'«Read» feilinin keçmiş forması necə yazılır?','Yazılış eyni qalır: read.',array['read (eyni yazılışla)','readed','red yalnız','reads'],1),
('ing6-journeys#1','ingilis-dili','ing-6-journeys',1,3,'Which is water transport?','Gəmi su nəqliyyatıdır: ship.',array['ship','bus','train','bike'],1),
('ing6-journeys#2','ingilis-dili','ing-6-journeys',1,3,'«Train» nə deməkdir?','Train — qatar.',array['Qatar','Təyyarə','Gəmi','Tramvay'],1),
('ing6-journeys#3','ingilis-dili','ing-6-journeys',2,3,'«Did they arrive on time?» sualına qısa cavab hansıdır?','Past Simple sualına: Yes, they did.',array['Yes, they did.','Yes, they do.','Yes, they are.','Yes, they can.'],1),
('ing6-journeys#4','ingilis-dili','ing-6-journeys',3,3,'«Could» feili nəyi bildirir?','Could — keçmişdə bacarığı bildirir.',array['Keçmişdə bacarığı','Gələcək planı','İndiki hərəkəti','Sahibliyi'],1),
('ing6-journeys#5','ingilis-dili','ing-6-journeys',2,3,'«When I was five, I ___ already swim.» (bacarırdım)','Keçmiş bacarıq: could.',array['could','can','will','am'],1),
('ing6-journeys#6','ingilis-dili','ing-6-journeys',2,3,'«Drive» feili hansı nəqliyyat vasitəsinə aiddir?','Maşını sürürük: drive a car.',array['Maşına','Ata','Velosipedə','Qayığa'],1),
('ing6-journeys#7','ingilis-dili','ing-6-journeys',2,3,'«Ride a horse» nə deməkdir?','Ata minmək.',array['Ata minmək','Maşın sürmək','Qaçmaq','Uçmaq'],1),
('ing6-journeys#8','ingilis-dili','ing-6-journeys',2,3,'«Where did you go last year?» sualı nə haqqındadır?','Keçən ilki səyahət haqqındadır.',array['Keçmiş səyahət haqqında','Gələcək plan haqqında','Bu günkü dərs haqqında','Yemək haqqında'],1),
('ing6-journeys#9','ingilis-dili','ing-6-journeys',2,3,'«By bus» ifadəsi nəyi bildirir?','Avtobusla getməyi bildirir.',array['Avtobusla getməyi','Avtobusu almağı','Avtobusda yaşamağı','Avtobusu yumağı'],1),
('ing6-journeys#10','ingilis-dili','ing-6-journeys',2,3,'«Journey» sözünün mənası nədir?','Journey — səyahət, yol.',array['Səyahət','Jurnal','Gündəlik','Hakim'],1),
('ing6-journeys#11','ingilis-dili','ing-6-journeys',1,3,'Which is air transport?','Təyyarə hava nəqliyyatıdır.',array['plane','ship','train','bus'],1),
('ing6-journeys#12','ingilis-dili','ing-6-journeys',1,3,'Təyyarələrin endiyi yer ingiliscə necə adlanır?','Hava limanı — airport.',array['airport','port','station','garage'],1),
('ing6-journeys#13','ingilis-dili','ing-6-journeys',2,3,'«Station» sözünün mənası nədir?','Station — vağzal, stansiya.',array['Vağzal (stansiya)','Mağaza','Məktəb','Park'],1),
('ing6-journeys#14','ingilis-dili','ing-6-journeys',2,3,'«We ___ to Ganja last week.» (getdik)','Go feilinin keçmişi: went.',array['went','go','gone','goes'],1),
('ing6-journeys#15','ingilis-dili','ing-6-journeys',3,3,'«Could you swim when you were six?» sualına qısa cavab hansıdır?','Yes, I could.',array['Yes, I could.','Yes, I can.','No, I am not.','Yes, I do.'],1),
('ing6-journeys#16','ingilis-dili','ing-6-journeys',1,3,'«Map» nə üçün lazımdır?','Yolu tapmaq üçün.',array['Yol tapmaq üçün','Yemək üçün','Yazmaq üçün','Geymək üçün'],1),
('ing6-journeys#17','ingilis-dili','ing-6-journeys',2,3,'«Fast train» ifadəsinin mənası nədir?','Sürətli qatar.',array['Sürətli qatar','Köhnə qatar','Boş qatar','Uzun yol'],1),
('ing6-journeys#18','ingilis-dili','ing-6-journeys',2,3,'«On foot» ifadəsi necə getməyi bildirir?','Piyada getməyi.',array['Piyada','Maşınla','Təyyarə ilə','Gəmi ilə'],1),
('ing6-journeys#19','ingilis-dili','ing-6-journeys',2,3,'«Arrive» feilinin mənası nədir?','Arrive — çatmaq.',array['Çatmaq','Yola düşmək','Dayanmaq','İtirmək'],1),
('ing6-journeys#20','ingilis-dili','ing-6-journeys',2,3,'«Bicycle» sözünün qısa forması hansıdır?','Bike — velosiped.',array['bike','bic','cycle car','bus'],1),
('ing6-heroes#1','ingilis-dili','ing-6-heroes',1,3,'«Brave» sifəti nə deməkdir?','Brave — cəsur.',array['Cəsur','Qorxaq','Tənbəl','Yorğun'],1),
('ing6-heroes#2','ingilis-dili','ing-6-heroes',1,3,'«Kind» sözünün mənası nədir?','Kind — mehriban, xeyirxah.',array['Mehriban','Qəzəbli','Paxıl','Kobud'],1),
('ing6-heroes#3','ingilis-dili','ing-6-heroes',3,3,'Past Continuous necə düzəlir?','was/were + feilin -ing forması.',array['was/were + feil-ing','do + feil','will + feil','have + feil-ed'],1),
('ing6-heroes#4','ingilis-dili','ing-6-heroes',2,3,'«She ___ reading a book at 5 oclock yesterday.»','She ilə Past Continuous: was reading.',array['was','were','is','do'],1),
('ing6-heroes#5','ingilis-dili','ing-6-heroes',2,3,'«They were ___ football when it started to rain.»','Past Continuous: were playing.',array['playing','play','played','plays'],1),
('ing6-heroes#6','ingilis-dili','ing-6-heroes',2,3,'«Scared» hansı hissi bildirir?','Scared — qorxmuş.',array['Qorxunu','Sevinci','Yorğunluğu','Aclığı'],1),
('ing6-heroes#7','ingilis-dili','ing-6-heroes',3,3,'«What were you doing at 7?» sualı hansı zamandadır?','Were + doing — Past Continuous.',array['Past Continuous','Present Simple','Past Simple','Gələcək zaman'],1),
('ing6-heroes#8','ingilis-dili','ing-6-heroes',2,3,'«Honest» sifəti necə insanı təsvir edir?','Honest — dürüst, düz danışan.',array['Dürüst insanı','Yalançı insanı','Tənbəl insanı','Qəzəbli insanı'],1),
('ing6-heroes#9','ingilis-dili','ing-6-heroes',2,3,'«Was he sleeping? — No, he ___.»','İnkar qısa cavab: was not.',array['was not','were not','did not','is not'],1),
('ing6-heroes#10','ingilis-dili','ing-6-heroes',1,3,'Qəhrəman (hero) adlandırdığımız insan nə edir?','Başqalarına kömək edir, cəsarət göstərir.',array['Başqalarına kömək edir','Yalnız yatır','Heç nə etmir','Qaçıb gizlənir'],1),
('ing6-heroes#11','ingilis-dili','ing-6-heroes',1,3,'«Strong» sifəti nə deməkdir?','Strong — güclü.',array['Güclü','Zəif','Balaca','Qoca'],1),
('ing6-heroes#12','ingilis-dili','ing-6-heroes',2,3,'«He was watching TV at 8 in the evening.» cümləsi hansı zamandadır?','Was + -ing — Past Continuous.',array['Past Continuous (davamedici keçmiş)','Present Simple','Past Simple','Future'],1),
('ing6-heroes#13','ingilis-dili','ing-6-heroes',2,3,'«While» bağlayıcısı hansı mənanı verir?','Olarkən, o zaman ki.',array['Olarkən (o vaxt ki)','Çünki','Amma','Sonra'],1),
('ing6-heroes#14','ingilis-dili','ing-6-heroes',1,3,'«Firefighter» kimdir?','Yanğınsöndürən.',array['Yanğınsöndürən','Müəllim','Aşpaz','Sürücü'],1),
('ing6-heroes#15','ingilis-dili','ing-6-heroes',2,3,'«Save» feilinin mənası nədir?','Save — xilas etmək.',array['Xilas etmək','İtirmək','Qorxutmaq','Atmaq'],1),
('ing6-heroes#16','ingilis-dili','ing-6-heroes',2,3,'«We ___ walking in the park at 5.»','We ilə: were.',array['were','was','is','am'],1),
('ing6-heroes#17','ingilis-dili','ing-6-heroes',2,3,'«Helpful» sifəti necə insanı bildirir?','Kömək etməyi sevən insanı.',array['Kömək edən insanı','Tənbəl insanı','Qorxaq insanı','Yalançı insanı'],1),
('ing6-heroes#18','ingilis-dili','ing-6-heroes',2,3,'What does a doctor do?','Həkim insanları müalicə edir.',array['Helps sick people','Cooks food','Drives a bus','Paints walls'],1),
('ing6-heroes#19','ingilis-dili','ing-6-heroes',2,3,'«I was not sleeping.» cümləsi nəyi bildirir?','Keçmişdə davam edən hərəkətin inkarını.',array['Yatmırdım (inkar)','Yatırdım','Yatacağam','Yataram'],1),
('ing6-heroes#20','ingilis-dili','ing-6-heroes',2,3,'«Polite» sözünün mənası nədir?','Polite — nəzakətli.',array['Nəzakətli','Kobud','Səsli','Yavaş'],1),
('ing6-ideas#1','ingilis-dili','ing-6-ideas',2,4,'«Invent» feili nə deməkdir?','Invent — ixtira etmək.',array['İxtira etmək','İtirmək','Silmək','Yemək'],1),
('ing6-ideas#2','ingilis-dili','ing-6-ideas',2,4,'«Discover» nə deməkdir?','Discover — kəşf etmək.',array['Kəşf etmək','Gizlətmək','Unutmaq','Satmaq'],1),
('ing6-ideas#3','ingilis-dili','ing-6-ideas',2,4,'«This book is ___.» (mənimki)','Yiyəlik əvəzliyi: mine.',array['mine','my','me','I'],1),
('ing6-ideas#4','ingilis-dili','ing-6-ideas',2,4,'«Yours» nə deməkdir?','Yours — səninki.',array['Səninki','Mənimki','Onunku','Bizimki'],1),
('ing6-ideas#5','ingilis-dili','ing-6-ideas',3,4,'«While I was cooking, the phone ___.» (Past Simple)','Qısa hadisə Past Simple ilə: rang.',array['rang','ring','ringing','rings'],1),
('ing6-ideas#6','ingilis-dili','ing-6-ideas',2,4,'«Technology» sözü nəyi əhatə edir?','Texniki vasitələri və ixtiraları.',array['Texniki vasitələri','Yalnız kitabları','Yalnız yeməkləri','Heyvanları'],1),
('ing6-ideas#7','ingilis-dili','ing-6-ideas',2,4,'«Design» feilinin mənası nədir?','Design — layihələndirmək, dizayn etmək.',array['Layihələndirmək','Dağıtmaq','Gözləmək','Oxumaq'],1),
('ing6-ideas#8','ingilis-dili','ing-6-ideas',3,4,'Uzun davam edən keçmiş hərəkəti hansı zaman bildirir?','Davamlı hərəkət — Past Continuous.',array['Past Continuous','Past Simple','Present Simple','Əmr forması'],1),
('ing6-ideas#9','ingilis-dili','ing-6-ideas',1,4,'«Screen» nə deməkdir?','Screen — ekran.',array['Ekran','Klaviatura','Printer','Naqil'],1),
('ing6-ideas#10','ingilis-dili','ing-6-ideas',1,4,'«Great idea!» ifadəsi nəyi bildirir?','Fikri bəyənməni bildirir: əla fikirdir!',array['Bəyənməni','Etirazı','Qorxunu','Yuxusuzluğu'],1),
('ing6-ideas#11','ingilis-dili','ing-6-ideas',1,4,'«Clever» sözünün mənası nədir?','Clever — ağıllı.',array['Ağıllı','Yorğun','Ac','Qəmgin'],1),
('ing6-ideas#12','ingilis-dili','ing-6-ideas',3,4,'«This computer is ___.» (bizimki)','Bizimki — ours.',array['ours','our','us','we'],1),
('ing6-ideas#13','ingilis-dili','ing-6-ideas',2,4,'«Whose book is this?» sualı nəyi soruşur?','Kitabın kimə aid olduğunu.',array['Kitabın kimin olduğunu','Kitabın rəngini','Kitabın qiymətini','Kitabın adını'],1),
('ing6-ideas#14','ingilis-dili','ing-6-ideas',1,4,'«Idea» sözünün mənası nədir?','Idea — fikir, ideya.',array['Fikir (ideya)','Alət','Otaq','Səs'],1),
('ing6-ideas#15','ingilis-dili','ing-6-ideas',3,4,'«He was reading when I came.» cümləsində hansı zamanlar işlənib?','Davam edən keçmiş + bitmiş keçmiş.',array['Past Continuous və Past Simple','İki Present Simple','Future və Past','İki Past Simple'],1),
('ing6-ideas#16','ingilis-dili','ing-6-ideas',2,4,'«Robot» insanlara nə ilə kömək edir?','Ağır və darıxdırıcı işləri görür.',array['İşləri yüngülləşdirir','Yemək yeyir','Yatır','Oxuyur yalnız'],1),
('ing6-ideas#17','ingilis-dili','ing-6-ideas',3,4,'«Theirs» nə deməkdir?','Theirs — onlarınkı.',array['Onlarınkı','Bizimki','Səninki','Mənimki'],1),
('ing6-ideas#18','ingilis-dili','ing-6-ideas',2,4,'«Useful» sifəti nə deməkdir?','Useful — faydalı.',array['Faydalı','Zərərli','Boş','Köhnə'],1),
('ing6-ideas#19','ingilis-dili','ing-6-ideas',2,4,'«Internet» ixtirası insanlara nə verdi?','Sürətli məlumat mübadiləsi imkanı.',array['Sürətli məlumat mübadiləsi','Yalnız oyun','Yalnız musiqi','Heç nə'],1),
('ing6-ideas#20','ingilis-dili','ing-6-ideas',3,4,'«Hers» sözü nəyi bildirir?','Hers — onunku (qadın haqqında).',array['Onunku (qadın)','Onunku (kişi)','Bizimki','Sizinki'],1),
('ing6-nature#1','ingilis-dili','ing-6-nature',1,4,'«Forest» nə deməkdir?','Forest — meşə.',array['Meşə','Dəniz','Səhra','Şəhər'],1),
('ing6-nature#2','ingilis-dili','ing-6-nature',1,4,'«River» sözünün mənası nədir?','River — çay.',array['Çay','Göl','Dağ','Ada'],1),
('ing6-nature#3','ingilis-dili','ing-6-nature',2,4,'«I want to protect nature.» — Danışan nə istəyir?','Protect — qorumaq: təbiəti qorumaq istəyir.',array['Təbiəti qorumaq','Təbiəti çirkləndirmək','Evdə qalmaq','Ağac kəsmək'],1),
('ing6-nature#4','ingilis-dili','ing-6-nature',1,4,'«Mountain» nə deməkdir?','Mountain — dağ.',array['Dağ','Düzənlik','Vadi','Sahil'],1),
('ing6-nature#5','ingilis-dili','ing-6-nature',3,4,'«Like, want, need» feilləri nəyi ifadə edir?','Bəyənməni, istəyi və ehtiyacı bildirir.',array['Bəyənmə, istək və ehtiyacı','Yalnız hərəkəti','Yalnız rəngi','Zamanı'],1),
('ing6-nature#6','ingilis-dili','ing-6-nature',2,4,'«We need clean air.» cümləsi nəyi bildirir?','Təmiz havaya ehtiyacımızı bildirir.',array['Təmiz havaya ehtiyacı','Yeməyə istəyi','Oyuna dəvəti','Yuxu vaxtını'],1),
('ing6-nature#7','ingilis-dili','ing-6-nature',2,4,'«Waterfall» nədir?','Waterfall — şəlalə.',array['Şəlalə','Quyu','Bulaq','Buzlaq'],1),
('ing6-nature#8','ingilis-dili','ing-6-nature',2,4,'«Wild animals» ifadəsi hansı heyvanları bildirir?','Wild — vəhşi (təbiətdə yaşayan) heyvanlar.',array['Vəhşi heyvanları','Ev heyvanlarını','Oyuncaqları','Balıqları'],1),
('ing6-nature#9','ingilis-dili','ing-6-nature',2,4,'«Desert» nə deməkdir?','Desert — səhra.',array['Səhra','Meşə','Bataqlıq','Çəmənlik'],1),
('ing6-nature#10','ingilis-dili','ing-6-nature',2,4,'«Do not drop litter!» xəbərdarlığı nə tələb edir?','Litter — zibil: zibil atmamağı tələb edir.',array['Zibil atmamağı','Sürətli qaçmağı','Səs salmamağı','Su içməməyi'],1),
('ing6-nature#11','ingilis-dili','ing-6-nature',1,4,'«Lake» nə deməkdir?','Lake — göl.',array['Göl','Dəniz','Çay','Bulaq'],1),
('ing6-nature#12','ingilis-dili','ing-6-nature',2,4,'«Pollution» sözü nəyi bildirir?','Pollution — çirklənmə.',array['Çirklənməni','Təmizliyi','Yağışı','Küləyi'],1),
('ing6-nature#13','ingilis-dili','ing-6-nature',2,4,'«Plant a tree» nə deməkdir?','Ağac əkmək.',array['Ağac əkmək','Ağac kəsmək','Ağaca dırmaşmaq','Ağac satmaq'],1),
('ing6-nature#14','ingilis-dili','ing-6-nature',1,4,'«Sky» sözünün mənası nədir?','Sky — səma.',array['Səma','Torpaq','Dəniz','Bulud yalnız'],1),
('ing6-nature#15','ingilis-dili','ing-6-nature',2,4,'«Recycling» nə üçün vacibdir?','Tullantılar yenidən emal olunur, təbiət qorunur.',array['Təbiəti qorumaq üçün','Daha çox zibil üçün','Pul xərcləmək üçün','Vacib deyil'],1),
('ing6-nature#16','ingilis-dili','ing-6-nature',1,4,'«Bear» hansı heyvandır?','Bear — ayı.',array['Ayı','Dovşan','Tülkü','Canavar'],1),
('ing6-nature#17','ingilis-dili','ing-6-nature',2,4,'«Island» nə deməkdir?','Island — ada.',array['Ada','Yarımada','Körfəz','Sahil'],1),
('ing6-nature#18','ingilis-dili','ing-6-nature',2,4,'«We must not cut down trees.» cümləsi nəyi qadağan edir?','Ağacları kəsməyi.',array['Ağac kəsməyi','Ağac əkməyi','Gəzməyi','Su içməyi'],1),
('ing6-nature#19','ingilis-dili','ing-6-nature',1,4,'«Weather» sözünün mənası nədir?','Weather — hava.',array['Hava','Su','Torpaq','Külək yalnız'],1),
('ing6-nature#20','ingilis-dili','ing-6-nature',1,4,'«Grass» nə deməkdir?','Grass — ot.',array['Ot','Gül','Kol','Yarpaq'],1),
('inf6-kompyuter#1','informatika','inf-6-kompyuter',2,1,'İkilik say sistemində hansı rəqəmlərdən istifadə olunur?','İkilik sistemdə yalnız 0 və 1 rəqəmləri var.',array['0 və 1','0-dan 9-a qədər','1 və 2','Yalnız 1'],1),
('inf6-kompyuter#2','informatika','inf-6-kompyuter',3,1,'1 meqabayt neçə kilobaytdır?','1 MB = 1024 KB.',array['1024','100','10','8'],1),
('inf6-kompyuter#3','informatika','inf-6-kompyuter',3,1,'«101» ikilik ədədi onluq say sistemində neçədir?','1·4 + 0·2 + 1·1 = 5.',array['5','101','3','6'],1),
('inf6-kompyuter#4','informatika','inf-6-kompyuter',2,1,'Hansı vahid daha böyükdür: meqabayt, yoxsa kilobayt?','1 MB = 1024 KB — meqabayt böyükdür.',array['Meqabayt','Kilobayt','Bərabərdirlər','Müqayisə olunmur'],1),
('inf6-kompyuter#5','informatika','inf-6-kompyuter',3,1,'Kompüterin daimi və müvəqqəti yaddaşları hansılardır?','Daimi — sərt disk, müvəqqəti — əməli yaddaş.',array['Sərt disk və əməli yaddaş','Monitor və maus','Printer və skaner','Dinamik və mikrofon'],1),
('inf6-kompyuter#6','informatika','inf-6-kompyuter',3,1,'Mətndəki hər simvol yaddaşda təxminən nə qədər yer tutur?','Bir simvol təxminən 1 bayt yer tutur.',array['1 bayt','1 kilobayt','1 meqabayt','100 bayt'],1),
('inf6-kompyuter#7','informatika','inf-6-kompyuter',3,1,'İkilik «1010» yazılışının onluq qarşılığını tapın.','1·8 + 0·4 + 1·2 + 0·1 = 10.',array['10','1010','4','20'],1),
('inf6-kompyuter#8','informatika','inf-6-kompyuter',2,1,'Verilənlərin ölçü vahidlərini kiçikdən böyüyə düzün.','bit < bayt < kilobayt < meqabayt.',array['bit, bayt, KB, MB','MB, KB, bayt, bit','bayt, bit, MB, KB','KB, MB, bit, bayt'],1),
('inf6-kompyuter#9','informatika','inf-6-kompyuter',2,1,'Monitordakı təsvir nələrdən yığılır?','Təsvir xırda nöqtələrdən — piksellərdən ibarətdir.',array['Piksellərdən','Hərflərdən','Damcılardan','Xətlərdən'],1),
('inf6-kompyuter#10','informatika','inf-6-kompyuter',3,1,'Kompüter söndürüləndə hansı yaddaşın məzmunu silinir?','Əməli (müvəqqəti) yaddaş təmizlənir.',array['Əməli yaddaşın','Sərt diskin','Fləş kartın','Heç birinin'],1),
('inf6-kompyuter#11','informatika','inf-6-kompyuter',3,1,'Bir qiqabaytda neçə meqabayt var?','1 GB = 1024 MB.',array['1024','100','10','1000000'],1),
('inf6-kompyuter#12','informatika','inf-6-kompyuter',2,1,'Kompüterin «beyni» sayılan qurğu hansıdır?','Prosessor bütün hesablamaları aparır.',array['Prosessor','Monitor','Klaviatura','Printer'],1),
('inf6-kompyuter#13','informatika','inf-6-kompyuter',2,1,'Verilənlərin emalını hansı qurğu yerinə yetirir?','Emalı prosessor aparır.',array['Prosessor','Səs ucaldıcı','Maus','Kamera'],1),
('inf6-kompyuter#14','informatika','inf-6-kompyuter',3,1,'Səs informasiyası kompüterdə hansı formada saxlanır?','Rəqəmsal (ikilik) kodda.',array['Rəqəmsal (ikilik) kodda','Kağızda','Lentdə yalnız','Saxlanmır'],1),
('inf6-kompyuter#15','informatika','inf-6-kompyuter',2,1,'Şəkil çox böyüdüləndə nə görünür?','Ayrı-ayrı piksellər görünür.',array['Piksellər','Hərflər','Notlar','Heç nə'],1),
('inf6-kompyuter#16','informatika','inf-6-kompyuter',2,1,'Fləş kart nə üçün istifadə olunur?','Məlumatı daşımaq və saxlamaq üçün.',array['Məlumat daşımaq üçün','Şəkil çəkmək üçün','Səs yazmaq üçün yalnız','İşıqlandırma üçün'],1),
('inf6-kompyuter#17','informatika','inf-6-kompyuter',3,1,'Hər simvol 1 bayt tutursa, 10 simvolluq söz nə qədər yer tutar?','10 simvol — 10 bayt.',array['10 bayt','1 bayt','10 bit','1 KB'],1),
('inf6-kompyuter#18','informatika','inf-6-kompyuter',3,1,'Onluq 7 ədədi ikilik say sistemində necə yazılır?','7 = 4 + 2 + 1 = 111.',array['111','101','110','100'],1),
('inf6-kompyuter#19','informatika','inf-6-kompyuter',2,1,'Verilənlər hansı qurğuda uzunmüddətli saxlanır?','Sərt diskdə saxlanır.',array['Sərt diskdə','Əməli yaddaşda','Prosessorda','Monitorda'],1),
('inf6-kompyuter#20','informatika','inf-6-kompyuter',2,1,'Klaviatura və maus hansı qurğular qrupuna aiddir?','Daxiletmə qurğularıdır.',array['Daxiletmə qurğularına','Xaricetmə qurğularına','Yaddaş qurğularına','Səs qurğularına'],1),
('inf6-proqram-teminati#1','informatika','inf-6-proqram-teminati',2,2,'Proqram təminatı nədir?','Kompüterdə işləyən bütün proqramların məcmusudur.',array['Kompüter proqramlarının məcmusu','Kompüterin qurğuları','Elektrik naqilləri','Kağız sənədlər'],1),
('inf6-proqram-teminati#2','informatika','inf-6-proqram-teminati',1,2,'Proqramı başlatmağın üsullarından biri hansıdır?','Nişanı üzərində ikiqat klik etmək.',array['Nişan üzərində ikiqat klik','Monitoru silkələmək','Naqili çıxarmaq','Ekranı söndürmək'],1),
('inf6-proqram-teminati#3','informatika','inf-6-proqram-teminati',3,2,'Abzasın formatlanmasına nə daxildir?','Sətirlərin düzləndirilməsi və abzas boşluğu.',array['Düzləndirmə və abzas boşluğu','Faylın silinməsi','Kompüterin təmiri','Şəklin çəkilməsi'],1),
('inf6-proqram-teminati#4','informatika','inf-6-proqram-teminati',2,2,'Elektron təqdimatın əsas elementi nədir?','Təqdimat slaydlardan ibarətdir.',array['Slayd','Cədvəl','Qovluq','Parol'],1),
('inf6-proqram-teminati#5','informatika','inf-6-proqram-teminati',2,2,'Slayda nələri əlavə etmək olar?','Mətn, şəkil, cədvəl və digər obyektləri.',array['Mətn, şəkil, cədvəl','Yalnız mətn','Yalnız rəqəmlər','Heç nə'],1),
('inf6-proqram-teminati#6','informatika','inf-6-proqram-teminati',2,2,'Təqdimat zamanı slaydlar necə göstərilir?','Müəyyən olunmuş ardıcıllıqla bir-birini əvəz edir.',array['Müəyyən ardıcıllıqla','Təsadüfi','Hamısı bir yerdə','Göstərilmir'],1),
('inf6-proqram-teminati#7','informatika','inf-6-proqram-teminati',2,2,'Mətnin görünüşünü yaxşılaşdırmaq üçün nəyi dəyişmək olar?','Şrifti, ölçünü və rəngi dəyişmək olar.',array['Şrifti və ölçünü','Kompüterin markasını','Otağın rəngini','Heç nəyi'],1),
('inf6-proqram-teminati#8','informatika','inf-6-proqram-teminati',3,2,'Cədvəl şəklində informasiya modelinə misal hansıdır?','Dərs cədvəli informasiya modelidir.',array['Dərs cədvəli','Futbol topu','Qələm','Çanta'],1),
('inf6-proqram-teminati#9','informatika','inf-6-proqram-teminati',2,2,'Hansı proqram elektron təqdimat hazırlamaq üçündür?','PowerPoint təqdimat proqramıdır.',array['PowerPoint','Kalkulyator','Saat','Paint'],1),
('inf6-proqram-teminati#10','informatika','inf-6-proqram-teminati',3,2,'Əməliyyat sistemi ilə tətbiqi proqramın fərqi nədir?','ƏS kompüteri idarə edir, tətbiqi proqram konkret iş görür.',array['ƏS idarə edir, tətbiqi proqram konkret iş görür','Fərq yoxdur','Tətbiqi proqram kompüteri yandırır','ƏS yalnız oyundur'],1),
('inf6-proqram-teminati#11','informatika','inf-6-proqram-teminati',3,2,'Hansı proqramlar sistem proqram təminatını təşkil edir?','Əməliyyat sistemi və drayverlər.',array['Əməliyyat sistemi və drayverlər','Yalnız oyunlar','Yalnız mətn redaktoru','Şəkillər'],1),
('inf6-proqram-teminati#12','informatika','inf-6-proqram-teminati',2,2,'Aşağıdakılardan hansı tətbiqi proqramdır?','Mətn redaktoru tətbiqi proqramdır.',array['Mətn redaktoru','Drayver','Əməliyyat sistemi','BIOS'],1),
('inf6-proqram-teminati#13','informatika','inf-6-proqram-teminati',2,2,'Slaydda başlıq nə üçündür?','Slaydın mövzusunu bildirmək üçün.',array['Mövzunu bildirmək üçün','Bəzək üçün yalnız','Yer tutmaq üçün','Vacib deyil'],1),
('inf6-proqram-teminati#14','informatika','inf-6-proqram-teminati',2,2,'Təqdimatda keçid effektləri nə verir?','Slaydlararası keçidi canlandırır.',array['Slaydlar arası keçidi canlandırır','Mətni silir','Kompüteri sürətləndirir','Səhvləri düzəldir'],1),
('inf6-proqram-teminati#15','informatika','inf-6-proqram-teminati',3,2,'Mətnin düzləndirilməsi növləri hansılardır?','Sola, sağa, mərkəzə və eninə görə.',array['Sola, sağa, mərkəzə, eninə','Yalnız sola','Yalnız mərkəzə','Yuxarı-aşağı'],1),
('inf6-proqram-teminati#16','informatika','inf-6-proqram-teminati',3,2,'Şriftin ölçüsü hansı vahidlə göstərilir?','Punktla ölçülür.',array['Punktla','Metrlə','Baytla','Dərəcə ilə'],1),
('inf6-proqram-teminati#17','informatika','inf-6-proqram-teminati',2,2,'Mətn sənədinə cədvəl əlavə etmək olarmı?','Bəli, cədvəl menyusundan.',array['Bəli, cədvəl menyusundan','Xeyr, olmaz','Yalnız şəkil kimi','Yalnız çapdan sonra'],1),
('inf6-proqram-teminati#18','informatika','inf-6-proqram-teminati',2,2,'Slaydda həddindən çox mətn yazmaq nə üçün pisdir?','Dinləyici oxuya bilmir, diqqət yayınır.',array['Oxumaq çətinləşir','Kompüter sınır','Rənglər itir','Pis deyil'],1),
('inf6-proqram-teminati#19','informatika','inf-6-proqram-teminati',3,2,'Qurğunu idarə edən xidməti proqram necə adlanır?','Belə proqram drayver adlanır.',array['Drayver','Oyun proqramı','Şəkil faylı','Qovluq'],1),
('inf6-proqram-teminati#20','informatika','inf-6-proqram-teminati',2,2,'Proqramın kompüterə yüklənməsi prosesi necə adlanır?','Quraşdırma (install) adlanır.',array['Quraşdırma (install)','Silinmə','Çap','Kopyalama'],1),
('inf6-alqoritm#1','informatika','inf-6-alqoritm',2,3,'Alqoritmin xassələrindən biri hansıdır?','Hər addım dəqiq və birmənalı olmalıdır — müəyyənlik.',array['Müəyyənlik (dəqiqlik)','Rənglilik','Uzunluq','Gizlilik'],1),
('inf6-alqoritm#2','informatika','inf-6-alqoritm',2,3,'Xətti alqoritm necə icra olunur?','Addımlar ardıcıl, hər biri bir dəfə icra olunur.',array['Addımlar ardıcıl, bir dəfə','Yalnız şərtlə','Sonsuz təkrarla','Sondan əvvələ'],1),
('inf6-alqoritm#3','informatika','inf-6-alqoritm',2,3,'Budaqlanan alqoritmdə nə baş verir?','Şərtdən asılı olaraq yol seçilir.',array['Şərtə görə yol seçilir','Addımlar silinir','Alqoritm dayanmır','Yalnız təkrar olur'],1),
('inf6-alqoritm#4','informatika','inf-6-alqoritm',2,3,'Dövri alqoritm nədir?','Addımların müəyyən sayda təkrarlandığı alqoritmdir.',array['Addımları təkrarlanan alqoritm','Tək addımlı alqoritm','Səhv alqoritm','Yazısız alqoritm'],1),
('inf6-alqoritm#5','informatika','inf-6-alqoritm',2,3,'«Əgər yağış yağırsa, çətir götür» — bu hansı alqoritm növüdür?','Şərt var — budaqlanan alqoritmdir.',array['Budaqlanan','Xətti','Dövri','Alqoritm deyil'],1),
('inf6-alqoritm#6','informatika','inf-6-alqoritm',2,3,'«Hasarın 20 taxtasını rənglə» məsələsi hansı alqoritmlə həll olunur?','Eyni iş 20 dəfə təkrarlanır — dövri alqoritm.',array['Dövri','Xətti','Budaqlanan','Heç biri'],1),
('inf6-alqoritm#7','informatika','inf-6-alqoritm',3,3,'Alqoritmin sonluluq xassəsi nə deməkdir?','Alqoritm sonlu sayda addımdan sonra bitməlidir.',array['Sonlu addımdan sonra bitməlidir','Heç vaxt bitməməlidir','Bir addımdan ibarət olmalıdır','Yazılmamalıdır'],1),
('inf6-alqoritm#8','informatika','inf-6-alqoritm',3,3,'Blok-sxemdə şərt (seçim) hansı fiqurla göstərilir?','Şərt romb fiqurunda yazılır.',array['Romb','Oval','Düzbucaqlı','Dairə'],1),
('inf6-alqoritm#9','informatika','inf-6-alqoritm',3,3,'Alqoritmin anlaşıqlılıq xassəsi nəyi tələb edir?','İcraçı hər əmri başa düşməlidir.',array['İcraçının əmrləri başa düşməsini','Rəngli yazılmasını','Uzun olmasını','Gizli qalmasını'],1),
('inf6-alqoritm#10','informatika','inf-6-alqoritm',2,3,'Alqoritmin icrasını kim və ya nə dayandıra bilər?','Son addım yerinə yetiriləndə alqoritm bitir.',array['Son addımın icrası','Küləyin əsməsi','Kağızın rəngi','Heç nə'],1),
('inf6-alqoritm#11','informatika','inf-6-alqoritm',3,3,'Alqoritmin kütləvilik xassəsi nə deməkdir?','Eyni tipli bütün məsələlərə tətbiq oluna bilməsi.',array['Oxşar məsələlərin hamısına tətbiq olunması','Yalnız bir məsələyə aid olması','Uzun olması','Şəkilli olması'],1),
('inf6-alqoritm#12','informatika','inf-6-alqoritm',2,3,'Xətti alqoritmə məişətdən misal hansıdır?','Çay dəmləmə ardıcıllığı addım-addım icra olunur.',array['Çay dəmləmə ardıcıllığı','Tənliyin qrafiki','Şəkil çəkmək istəyi','Təsadüfi seçim'],1),
('inf6-alqoritm#13','informatika','inf-6-alqoritm',2,3,'«Əgər hava soyuqdursa, palto gey, əks halda gödəkçə» — burada neçə yol var?','İki mümkün yol var.',array['2','1','3','4'],1),
('inf6-alqoritm#14','informatika','inf-6-alqoritm',3,3,'Dövri alqoritmdə təkrarlanan hissə necə adlanır?','Dövrün gövdəsi adlanır.',array['Dövrün gövdəsi','Dövrün başlığı','Şərt bloku','Son blok'],1),
('inf6-alqoritm#15','informatika','inf-6-alqoritm',2,3,'Alqoritmi icra edən qurğu və ya canlı necə adlanır?','İcraçı adlanır.',array['İcraçı','Müəllif','Proqramçı','İstifadəçi yalnız'],1),
('inf6-alqoritm#16','informatika','inf-6-alqoritm',2,3,'Blok-sxemdə oxlar nəyi göstərir?','Addımların icra istiqamətini.',array['İcra istiqamətini','Rəngi','Səhvləri','Sürəti'],1),
('inf6-alqoritm#17','informatika','inf-6-alqoritm',2,3,'Tam budaqlanmada neçə budaq olur?','Hə və yox — iki budaq.',array['İki (hə və yox)','Bir','Həmişə üç','Sonsuz'],1),
('inf6-alqoritm#18','informatika','inf-6-alqoritm',3,3,'Alqoritmin diskretlik xassəsi nə deməkdir?','Ayrı-ayrı addımlardan ibarət olması.',array['Ayrı-ayrı addımlardan ibarət olması','Bir bütöv hərəkət olması','Sonsuz olması','Sözsüz olması'],1),
('inf6-alqoritm#19','informatika','inf-6-alqoritm',3,3,'Budaqlanan alqoritmdə şərt ödənmədikdə nə baş verir?','Digər (əks) budaq icra olunur.',array['Digər budaq icra olunur','Proqram silinir','Kompüter sönür','Şərt təkrar yoxlanır sonsuz'],1),
('inf6-alqoritm#20','informatika','inf-6-alqoritm',3,3,'«Alqoritm» sözü hansı alimin adı ilə bağlıdır?','IX əsr alimi Əl-Xarəzminin adından yaranıb.',array['Əl-Xarəzmi','Nyuton','Arximed','Mendeleyev'],1),
('inf6-proqramlasdirma#1','informatika','inf-6-proqramlasdirma',3,3,'Proqramda dəyişən nədir?','Qiyməti dəyişə bilən adlandırılmış yaddaş sahəsidir.',array['Qiyməti dəyişən adlandırılmış sahə','Sabit ədəd','Kompüterin hissəsi','Şəkil faylı'],1),
('inf6-proqramlasdirma#2','informatika','inf-6-proqramlasdirma',2,3,'Scratch tipli mühitlərdə proqram nədən yığılır?','Hazır komanda bloklarından yığılır.',array['Bloklardan','Kağızdan','Naqillərdən','Şəkillərdən'],1),
('inf6-proqramlasdirma#3','informatika','inf-6-proqramlasdirma',2,3,'Proqramda «əgər … onda …» konstruksiyası nəyi həyata keçirir?','Şərtə görə seçimi (budaqlanmanı).',array['Seçimi (budaqlanmanı)','Təkrarı','Səs yazısını','Çapı'],1),
('inf6-proqramlasdirma#4','informatika','inf-6-proqramlasdirma',2,3,'Dövr (təkrarlama) əmri nə üçün istifadə olunur?','Eyni əmrləri dəfələrlə icra etmək üçün.',array['Əmrləri təkrarlamaq üçün','Proqramı silmək üçün','Ekranı söndürmək üçün','Fayl axtarmaq üçün'],1),
('inf6-proqramlasdirma#5','informatika','inf-6-proqramlasdirma',2,3,'Kvadrat çəkmək üçün «irəli get, sağa dön 90» əmrlərini neçə dəfə təkrarlamaq lazımdır?','Kvadratın 4 tərəfi var: 4 dəfə.',array['4','3','6','90'],1),
('inf6-proqramlasdirma#6','informatika','inf-6-proqramlasdirma',3,3,'ALPLogo-da «təkrar 6 [irəli 50 sağa 60]» proqramı hansı fiquru çəkər?','360 : 60 = 6 dönüş — altıbucaqlı alınır.',array['Altıbucaqlı','Kvadrat','Üçbucaq','Dairə'],1),
('inf6-proqramlasdirma#7','informatika','inf-6-proqramlasdirma',3,3,'Dəyişənə qiymət vermək əməliyyatı necə adlanır?','Qiymət vermə mənimsətmə adlanır.',array['Mənimsətmə','Silmə','Çapetmə','Axtarış'],1),
('inf6-proqramlasdirma#8','informatika','inf-6-proqramlasdirma',2,3,'Proqramlaşdırma mühitində musiqi necə səsləndirilir?','Not və səs əmrlərinin ardıcıllığı ilə.',array['Not əmrlərinin ardıcıllığı ilə','Mikrofonu sındırmaqla','Ekranı boyamaqla','Səsləndirmək olmur'],1),
('inf6-proqramlasdirma#9','informatika','inf-6-proqramlasdirma',2,3,'Proqramdakı səhv necə adlanır?','Proqram səhvi xəta (baq) adlanır.',array['Xəta (baq)','Blok','Slayd','Kursor'],1),
('inf6-proqramlasdirma#10','informatika','inf-6-proqramlasdirma',2,3,'Dövrün icrası nə vaxt dayanır?','Verilmiş təkrar sayı bitəndə dayanır.',array['Təkrar sayı bitəndə','Heç vaxt','Kompüter istəyəndə','Təsadüfi anda'],1),
('inf6-proqramlasdirma#11','informatika','inf-6-proqramlasdirma',2,3,'ALPLogo-da «irəli 100» əmri nə edir?','Bağanı 100 addım irəli aparır.',array['Bağanı 100 addım irəli aparır','Bağanı silir','Rəngi dəyişir','Proqramı bağlayır'],1),
('inf6-proqramlasdirma#12','informatika','inf-6-proqramlasdirma',3,3,'Üçbucaq çəkmək üçün təkrar əmrində dönmə bucağı neçə olmalıdır?','360 : 3 = 120 dərəcə.',array['120','90','60','45'],1),
('inf6-proqramlasdirma#13','informatika','inf-6-proqramlasdirma',3,3,'Dəyişənin adı necə başlamalıdır?','Hərflə başlamalıdır.',array['Hərflə','Rəqəmlə','Boşluqla','Nöqtə ilə'],1),
('inf6-proqramlasdirma#14','informatika','inf-6-proqramlasdirma',3,3,'Proqramda «say = say + 1» əməliyyatı nə edir?','Sayğacın qiymətini bir artırır.',array['Sayğacı bir artırır','Sayğacı sıfırlayır','Proqramı dayandırır','Səhv verir hökmən'],1),
('inf6-proqramlasdirma#15','informatika','inf-6-proqramlasdirma',3,3,'Musiqi əmrində notun uzunluğu nəyi bildirir?','Səsin davametmə müddətini.',array['Səsin davametmə müddətini','Səsin rəngini','Notun adını','Mahnının sözlərini'],1),
('inf6-proqramlasdirma#16','informatika','inf-6-proqramlasdirma',2,3,'Scratch mühitində personaj necə adlanır?','Sprayt adlanır.',array['Sprayt','Slayd','Sətir','Sxem'],1),
('inf6-proqramlasdirma#17','informatika','inf-6-proqramlasdirma',2,3,'«Bayraq klikləndikdə» bloku nə edir?','Proqramın icrasını başladır.',array['Proqramı başladır','Proqramı silir','Səsi artırır','Rəngi dəyişir'],1),
('inf6-proqramlasdirma#18','informatika','inf-6-proqramlasdirma',3,3,'Şərt blokundakı yoxlama hansı cavabları verə bilər?','Hə (doğru) və ya yox (yalan).',array['Hə və ya yox cavabı','Yalnız rəqəm','Yalnız mətn','Şəkil'],1),
('inf6-proqramlasdirma#19','informatika','inf-6-proqramlasdirma',1,3,'Alqoritmi proqram şəklində yazan şəxs necə adlanır?','Proqramçı adlanır.',array['Proqramçı','Rəssam','Bəstəkar','Sürücü'],1),
('inf6-proqramlasdirma#20','informatika','inf-6-proqramlasdirma',3,3,'Proqramda xətanı tapıb düzəltmə prosesi necə adlanır?','Sazlama (debugging) adlanır.',array['Sazlama (debugging)','Formatlama','Çap','Kopyalama'],1),
('inf6-internet#1','informatika','inf-6-internet',2,4,'İnternetdə axtarış üçün açar sözlər necə seçilməlidir?','Qısa və dəqiq sözlər daha yaxşı nəticə verir.',array['Qısa və dəqiq','Çox uzun cümlələr','Təsadüfi hərflər','Yalnız rəqəmlər'],1),
('inf6-internet#2','informatika','inf-6-internet',1,4,'Elektron poçt ünvanında hansı işarə mütləq olur?','E-poçt ünvanında @ işarəsi olur.',array['@','%','&','№'],1),
('inf6-internet#3','informatika','inf-6-internet',2,4,'E-məktuba fayl əlavə etmək necə adlanır?','Əlavə olunan fayl qoşma (attachment) adlanır.',array['Qoşma (attachment)','Slayd','Blok','Kursor'],1),
('inf6-internet#4','informatika','inf-6-internet',3,4,'İnformasiya resursları ilə işin ilk mərhələsi nədir?','Əvvəlcə axtarışın məqsədi müəyyən edilir.',array['Məqsədi müəyyən etmək','Nəticəni çap etmək','Kompüteri söndürmək','Şəkil çəkmək'],1),
('inf6-internet#5','informatika','inf-6-internet',2,4,'Brauzerin ünvan sətrinə nə yazılır?','Saytın ünvanı (URL) yazılır.',array['Saytın ünvanı','Parol','Ev ünvanı','Telefon nömrəsi'],1),
('inf6-internet#6','informatika','inf-6-internet',2,4,'Naməlum göndəricidən gələn e-məktubun qoşmasını açmaq olarmı?','Olmaz — virus ola bilər.',array['Olmaz — virus ola bilər','Olar, təhlükəsizdir','Yalnız gecə olar','Yalnız şəkildirsə olar'],1),
('inf6-internet#7','informatika','inf-6-internet',3,4,'«WWW» qısaltması nəyi bildirir?','World Wide Web — Dünya hörümçək toru.',array['World Wide Web','Windows Word Work','Web Windows World','Wide Word Web'],1),
('inf6-internet#8','informatika','inf-6-internet',2,4,'E-məktubda «Mövzu» (Subject) sətri nə üçündür?','Məktubun nə haqqında olduğunu qısa bildirmək üçün.',array['Məktubun mövzusunu bildirmək üçün','Parol yazmaq üçün','Şəkil çəkmək üçün','Heç nə üçün'],1),
('inf6-internet#9','informatika','inf-6-internet',3,4,'Axtarış nəticələrindən etibarlı olanı necə seçmək olar?','Rəsmi və tanınmış mənbələrə üstünlük verilir.',array['Rəsmi mənbələrə üstünlük verməklə','İlk çıxana inanmaqla','Ən rəngli sayta girməklə','Təsadüfi seçməklə'],1),
('inf6-internet#10','informatika','inf-6-internet',2,4,'İnternet hesabının parolunu kimə demək olar?','Parol yalnız valideynlə bölüşülə bilər, başqa heç kimə.',array['Yalnız valideynə','Bütün dostlara','İnternetdəki tanışlara','Hamıya'],1),
('inf6-internet#11','informatika','inf-6-internet',3,4,'Sayt ünvanındakı «.az» hissəsi nəyi bildirir?','Azərbaycan milli domenini.',array['Azərbaycan domenini','Saytın rəngini','Saytın yaşını','Parolu'],1),
('inf6-internet#12','informatika','inf-6-internet',2,4,'E-məktub yazanda hansı nəzakət qaydasına əməl olunur?','Salamlaşmaq və mövzunu göstərmək.',array['Salamlaşmaq və mövzunu yazmaq','Böyük hərflərlə qışqırmaq','İmzasız göndərmək','Boş göndərmək'],1),
('inf6-internet#13','informatika','inf-6-internet',2,4,'Arzuolunmaz kütləvi reklam məktubları necə adlanır?','Belə məktublar spam adlanır.',array['Spam','Qoşma','Domen','Parol'],1),
('inf6-internet#14','informatika','inf-6-internet',2,4,'Sosial şəbəkədə tanımadığın şəxsin dostluq təklifinə nə etməli?','Qəbul etməmək daha təhlükəsizdir.',array['Qəbul etməməli','Dərhal qəbul etməli','Ünvanını verməli','Şəklini göndərməli'],1),
('inf6-internet#15','informatika','inf-6-internet',3,4,'Axtarışda dırnaq içində yazılan ifadə nəyi bildirir?','Dəqiq ifadənin axtarılmasını.',array['Dəqiq ifadəni axtarmağı','Şəkil axtarmağı','Səs axtarmağı','Heç nəyi'],1),
('inf6-internet#16','informatika','inf-6-internet',2,4,'Onlayn lüğət və ensiklopediyalar hansı resurslara aiddir?','Təhsil (informasiya) resurslarına.',array['Təhsil resurslarına','Oyun resurslarına','Reklamlara','Spama'],1),
('inf6-internet#17','informatika','inf-6-internet',2,4,'Eyni məktubu iki fərqli ünvana yollamaq mümkündürmü?','Bəli, ünvanları əlavə etməklə.',array['Bəli, ünvanları əlavə etməklə','Xeyr, olmaz','Yalnız gecə olar','Yalnız şəkilsiz olar'],1),
('inf6-internet#18','informatika','inf-6-internet',3,4,'İnternetdə müəllif hüququ nəyi qoruyur?','Yaradıcı işləri (mətn, şəkil, musiqi).',array['Yaradıcı işləri','Parolları','Kompüterin rəngini','Elektrik xəttini'],1),
('inf6-internet#19','informatika','inf-6-internet',2,4,'Həddindən artıq internet istifadəsi nəyə səbəb ola bilər?','Asılılığa və vaxt itkisinə.',array['Asılılığa','Güclənməyə','Yaxşı yuxuya','Heç nəyə'],1),
('inf6-internet#20','informatika','inf-6-internet',2,4,'Etibarlı parol necə olmalıdır?','Uzun, hərf və rəqəmlərdən ibarət.',array['Uzun, hərf və rəqəmli','Ad günü tarixi','Yalnız 123','Öz adın'],1),
('tarix6-ibtidai#1','tarix','tarix-6-ibtidai',1,1,'«E.ə.» qısaltması nə deməkdir?','Eramızdan əvvəl deməkdir.',array['Eramızdan əvvəl','Ən əvvəl','Erkən əsr','Əsrdən əvvəl'],1),
('tarix6-ibtidai#2','tarix','tarix-6-ibtidai',1,1,'100 il hansı zaman vahidini təşkil edir?','100 il bir əsrdir (yüzillik).',array['Əsr','Minillik','Onillik','Ay'],1),
('tarix6-ibtidai#3','tarix','tarix-6-ibtidai',2,1,'Azıx mağarasında tapılmış qədim insan necə adlandırılır?','Azıx mağarasının qədim sakini azıxantrop adlanır.',array['Azıxantrop','Neandertal','Firon','Sərkərdə'],1),
('tarix6-ibtidai#4','tarix','tarix-6-ibtidai',1,1,'İbtidai insanlar əvvəlcə harada yaşayırdılar?','İlk insanlar mağaralarda məskunlaşırdılar.',array['Mağaralarda','Çoxmərtəbəli binalarda','Gəmilərdə','Qalalarda'],1),
('tarix6-ibtidai#5','tarix','tarix-6-ibtidai',2,1,'Qobustan qayaüstü rəsmləri nəyi əks etdirir?','Qədim insanların həyatını: ov, rəqs, qayıqlar.',array['Qədim insanların həyatını','Müasir şəhərləri','Kosmik gəmiləri','Dəmir yollarını'],1),
('tarix6-ibtidai#6','tarix','tarix-6-ibtidai',2,1,'İbtidai insanlar niyə birlikdə (icma halında) yaşayırdılar?','Tək yaşamaq təhlükəli idi — birgə ovlanıb qorunurdular.',array['Birgə ovlanmaq və qorunmaq üçün','Şəhər salmaq üçün','Ticarət üçün','Yarış üçün'],1),
('tarix6-ibtidai#7','tarix','tarix-6-ibtidai',2,1,'Əkinçilik və maldarlıq yarananda insanların həyatında nə dəyişdi?','İnsanlar oturaq həyata keçdilər.',array['Oturaq həyata keçdilər','Mağaraya qayıtdılar','Ovçuluğu tam atdılar və ac qaldılar','Heç nə dəyişmədi'],1),
('tarix6-ibtidai#8','tarix','tarix-6-ibtidai',2,1,'Tunc dövrü hansı dövrdən sonra başlayır?','Əvvəl daş dövrü, sonra tunc dövrü gəlir.',array['Daş dövründən','Dəmir dövründən','Orta əsrlərdən','Müasir dövrdən'],1),
('tarix6-ibtidai#9','tarix','tarix-6-ibtidai',3,1,'Tarixi hadisələrin zamanını öyrənən sahə necə adlanır?','Zaman hesabını xronologiya öyrənir.',array['Xronologiya','Biologiya','Coğrafiya','Astronomiya'],1),
('tarix6-ibtidai#10','tarix','tarix-6-ibtidai',2,1,'Erkən dövlətlər hansı ehtiyacdan yaranırdı?','İdarəetmə və müdafiə ehtiyacından.',array['İdarəetmə və müdafiə ehtiyacından','Oyun üçün','Bayram keçirmək üçün','Təsadüfən'],1),
('tarix6-ibtidai#11','tarix','tarix-6-ibtidai',3,1,'Daş dövrü hansı mərhələlərə bölünür?','Paleolit, mezolit və neolit.',array['Paleolit, mezolit, neolit','Tunc və dəmir','Qədim və yeni','Bölünmür'],1),
('tarix6-ibtidai#12','tarix','tarix-6-ibtidai',2,1,'İbtidai icmada əmək bölgüsü kimlər arasında idi?','Kişilər və qadınlar arasında.',array['Kişilər və qadınlar arasında','Uşaqlar arasında yalnız','Dövlətlər arasında','Yox idi'],1),
('tarix6-ibtidai#13','tarix','tarix-6-ibtidai',2,1,'Ovçuluqda mezolit dövründə hansı alət meydana gəldi?','Ox və yay ovçuluğu asanlaşdırdı.',array['Ox və yay','Traktor','Dəmir qılınc','Tüfəng'],1),
('tarix6-ibtidai#14','tarix','tarix-6-ibtidai',2,1,'Neolit dövründə insanlar nəyi öyrəndilər?','Əkinçilik və dulusçuluğu.',array['Əkinçilik və dulusçuluğu','Yazı makinasını','Gəmiçiliyi yalnız','Heç nəyi'],1),
('tarix6-ibtidai#15','tarix','tarix-6-ibtidai',2,1,'Qəbilə nədir?','Qohum icmaların birliyidir.',array['Qohum icmaların birliyi','Bir ailə','Bir şəhər','Bir dövlət'],1),
('tarix6-ibtidai#16','tarix','tarix-6-ibtidai',2,1,'Tayfa birlikləri hansı məqsədlə yaranırdı?','Birgə müdafiə və təsərrüfat üçün.',array['Birgə müdafiə üçün','Oyun üçün','Səyahət üçün','Ticarət qadağası üçün'],1),
('tarix6-ibtidai#17','tarix','tarix-6-ibtidai',3,1,'Eramızdan əvvəlki tarixlər hansı sıra ilə sayılır?','E.ə. tarixlər azalan sıra ilə gedir.',array['Azalan sıra ilə','Artan sıra ilə','Qarışıq','Sayılmır'],1),
('tarix6-ibtidai#18','tarix','tarix-6-ibtidai',2,1,'Mis dövründən sonra hansı dövr gəlir?','Tunc dövrü gəlir.',array['Tunc dövrü','Daş dövrü','Dəmir dövrü əvvəl','Buz dövrü'],1),
('tarix6-ibtidai#19','tarix','tarix-6-ibtidai',3,1,'Sənətkarlığın ayrılması nəyə səbəb oldu?','Mübadilənin və ticarətin yaranmasına.',array['Mübadilənin yaranmasına','Ovçuluğun bitməsinə','Yazının itməsinə','Heç nəyə'],1),
('tarix6-ibtidai#20','tarix','tarix-6-ibtidai',2,1,'Arxeoloji qazıntılarda tapılan əşyalar necə adlanır?','Maddi mədəniyyət abidələri.',array['Maddi mədəniyyət abidələri','Yeni məhsullar','Sənədlər yalnız','Xəritələr'],1),
('tarix6-qedim-dovletler#1','tarix','tarix-6-qedim-dovletler',3,2,'Manna dövləti hansı ərazidə yaranmışdır?','Manna Urmiya gölü ətrafında yaranmışdır.',array['Urmiya gölü ətrafında','Xəzərin şimalında','Qara dəniz sahilində','Kür çayının mənbəyində'],1),
('tarix6-qedim-dovletler#2','tarix','tarix-6-qedim-dovletler',3,2,'Manna dövləti təxminən nə vaxt yaranmışdır?','Manna e.ə. IX əsrdə yaranmışdır.',array['E.ə. IX əsrdə','Eramızın X əsrində','1918-ci ildə','E.ə. I əsrdə'],1),
('tarix6-qedim-dovletler#3','tarix','tarix-6-qedim-dovletler',3,2,'Atropatena dövlətinin banisi kimdir?','Dövləti sərkərdə Atropat yaratmışdır.',array['Atropat','İranzu','Cavanşir','Babək'],1),
('tarix6-qedim-dovletler#4','tarix','tarix-6-qedim-dovletler',3,2,'Albaniyada IV əsrdə hansı din dövlət dini elan olundu?','Albaniyada xristianlıq qəbul edildi.',array['Xristianlıq','Buddizm','Şamanizm','Heç bir din'],1),
('tarix6-qedim-dovletler#5','tarix','tarix-6-qedim-dovletler',3,2,'Skiflər Azərbaycan ərazisində hansı qurumu yaratmışdılar?','Skif (işğuz) padşahlığı yaranmışdı.',array['Skif padşahlığı','Roma imperiyası','Misir fironluğu','Xanlıq'],1),
('tarix6-qedim-dovletler#6','tarix','tarix-6-qedim-dovletler',3,2,'Manna dövlətinin qüdrətli hökmdarı kim olmuşdur?','İranzu Mannanın qüdrətli hökmdarı idi.',array['İranzu','Atropat','Tomris','Nadir şah'],1),
('tarix6-qedim-dovletler#7','tarix','tarix-6-qedim-dovletler',2,2,'Qədim dövlətlərin əhalisi əsasən nə ilə məşğul olurdu?','Əkinçilik və maldarlıq əsas təsərrüfat sahələri idi.',array['Əkinçilik və maldarlıqla','Kosmik tədqiqatlarla','Kino çəkilişi ilə','Neft hasilatı ilə'],1),
('tarix6-qedim-dovletler#8','tarix','tarix-6-qedim-dovletler',3,2,'Atropatenanın paytaxtı hansı şəhər idi?','Paytaxt Qazaka şəhəri idi.',array['Qazaka','Bakı','Gəncə','Şamaxı'],1),
('tarix6-qedim-dovletler#9','tarix','tarix-6-qedim-dovletler',2,2,'Albaniya ərazisindən axan əsas çay hansı idi?','Kür çayı Albaniyanın əsas çayı idi.',array['Kür','Nil','Dunay','Volqa'],1),
('tarix6-qedim-dovletler#10','tarix','tarix-6-qedim-dovletler',3,2,'Azərbaycan e.ə. VI əsrdə hansı imperiyanın tərkibinə qatılmışdı?','Əhəmənilər imperiyasının tərkibinə qatılmışdı.',array['Əhəmənilər','Roma','Osmanlı','Monqol'],1),
('tarix6-qedim-dovletler#11','tarix','tarix-6-qedim-dovletler',3,2,'Manna hansı dövlətlərlə mübarizə aparırdı?','Assuriya və Urartu ilə.',array['Assuriya və Urartu ilə','Roma ilə','Çinlə','Misirlə'],1),
('tarix6-qedim-dovletler#12','tarix','tarix-6-qedim-dovletler',2,2,'Atropatena dövlətinin adı nədən yaranmışdır?','Sərkərdə Atropatın adından.',array['Atropatın adından','Dağın adından','Çayın adından','Şəhərin adından'],1),
('tarix6-qedim-dovletler#13','tarix','tarix-6-qedim-dovletler',2,2,'Qəbələ hansı dövlətin paytaxtı idi?','Albaniyanın paytaxtı idi.',array['Albaniyanın','Mannanın','Atropatenanın','Skif padşahlığının'],1),
('tarix6-qedim-dovletler#14','tarix','tarix-6-qedim-dovletler',3,2,'Atropatena hansı hadisədən sonra müstəqil dövlət oldu?','Makedoniyalı İsgəndərin yürüşlərindən sonra.',array['İsgəndərin yürüşlərindən sonra','Neft tapılandan sonra','Xanlıqlardan sonra','Sovet dövründən sonra'],1),
('tarix6-qedim-dovletler#15','tarix','tarix-6-qedim-dovletler',2,2,'Qədim dövlətlərdə ordunun əsasını kimlər təşkil edirdi?','Süvarilər və piyadalar.',array['Süvarilər və piyadalar','Təyyarəçilər','Dənizçilər yalnız','Tankçılar'],1),
('tarix6-qedim-dovletler#16','tarix','tarix-6-qedim-dovletler',3,2,'Albaniya əhalisi hansı tayfalardan ibarət idi?','26 tayfadan: albanlar, utilər və başqaları.',array['26 tayfadan (albanlar, utilər və b.)','Bir tayfadan','Yalnız köçərilərdən','Yalnız yunanlardan'],1),
('tarix6-qedim-dovletler#17','tarix','tarix-6-qedim-dovletler',3,2,'Mannanın paytaxtı hansı şəhər idi?','İzirtu şəhəri idi.',array['İzirtu','Qazaka','Qəbələ','Bakı'],1),
('tarix6-qedim-dovletler#18','tarix','tarix-6-qedim-dovletler',3,2,'Əhəmənilər dövründə ölkə hansı vahidlərlə idarə olunurdu?','Satraplıqlara bölünmüşdü.',array['Satraplıqlar şəklində','Xanlıqlar şəklində','Respublikalarla','Şəhər dövlətləri ilə'],1),
('tarix6-qedim-dovletler#19','tarix','tarix-6-qedim-dovletler',2,2,'Atropatenada hansı din geniş yayılmışdı?','Zərdüştilik yayılmışdı.',array['Zərdüştilik','Buddizm','Xristianlıq','İslam'],1),
('tarix6-qedim-dovletler#20','tarix','tarix-6-qedim-dovletler',2,2,'Atropatena iqtisadiyyatı hansı sahələrdə inkişaf etmişdi?','Sənətkarlıq və ticarətdə.',array['Sənətkarlıq və ticarətdə','Yalnız balıqçılıqda','Neft emalında','Turizmdə'],1),
('tarix6-erken-orta#1','tarix','tarix-6-erken-orta',2,3,'III əsrdə Azərbaycan hansı imperiyanın hakimiyyəti altına düşdü?','Azərbaycan Sasani imperiyasının tərkibinə qatıldı.',array['Sasanilər','Roma','Osmanlı','Britaniya'],1),
('tarix6-erken-orta#2','tarix','tarix-6-erken-orta',3,3,'Feodal münasibətləri nəyə əsaslanırdı?','İri torpaq sahibliyinə əsaslanırdı.',array['Torpaq sahibliyinə','Zavod istehsalına','İnternet ticarətinə','Dəniz quldurluğuna'],1),
('tarix6-erken-orta#3','tarix','tarix-6-erken-orta',2,3,'Sasani imperiyası hansı ölkənin ərazisində yaranmışdı?','Sasanilər dövləti İran ərazisində yaranmışdı.',array['İranda','Misirdə','Yunanıstanda','Hindistanda'],1),
('tarix6-erken-orta#4','tarix','tarix-6-erken-orta',2,3,'Feodalizmdə torpağın əsas sahibləri kimlər idi?','Torpaqlar feodallara məxsus idi.',array['Feodallar','Kəndlilər','Uşaqlar','Tacirlər'],1),
('tarix6-erken-orta#5','tarix','tarix-6-erken-orta',2,3,'Asılı kəndlilər feodal üçün nə edirdilər?','Torpağı becərir, vergi və mükəlləfiyyətlər ödəyirdilər.',array['Torpağı becərib vergi verirdilər','Dövləti idarə edirdilər','Orduya komandanlıq edirdilər','Heç nə etmirdilər'],1),
('tarix6-erken-orta#6','tarix','tarix-6-erken-orta',3,3,'Mehranilər sülaləsi harada hakimiyyətdə olmuşdur?','Mehranilər Albaniyada hakimiyyətdə idilər.',array['Albaniyada','Misirdə','Romada','Çində'],1),
('tarix6-erken-orta#7','tarix','tarix-6-erken-orta',3,3,'Cavanşir hansı dövlətin hökmdarı idi?','Cavanşir Albaniya dövlətinin hökmdarı idi.',array['Albaniyanın','Mannanın','Səfəvilərin','Osmanlının'],1),
('tarix6-erken-orta#8','tarix','tarix-6-erken-orta',3,3,'Sasanilər dövründə Azərbaycanda hansı din geniş yayılmışdı?','Zərdüştilik (atəşpərəstlik) yayılmışdı.',array['Zərdüştilik','Buddizm','Protestantlıq','Şintoizm'],1),
('tarix6-erken-orta#9','tarix','tarix-6-erken-orta',2,3,'Atəşgahlar nə idi?','Od (atəş) məbədləri idi.',array['Od məbədləri','Bazarlar','Məktəblər','Limanlar'],1),
('tarix6-erken-orta#10','tarix','tarix-6-erken-orta',3,3,'Sasani hakimiyyətinə qarşı üsyanların əsas səbəbi nə idi?','Ağır vergilər və zülm üsyanlara səbəb olurdu.',array['Ağır vergilər və zülm','Bayramların çoxluğu','Torpağın bolluğu','Səbəb yox idi'],1),
('tarix6-erken-orta#11','tarix','tarix-6-erken-orta',3,3,'Albaniyada V əsrdə hansı mədəni hadisə baş verdi?','Alban əlifbası yaradıldı.',array['Alban əlifbası yaradıldı','Dəmir yolu çəkildi','Universitet açıldı','Qəzet çıxdı'],1),
('tarix6-erken-orta#12','tarix','tarix-6-erken-orta',2,3,'Ərəb xilafəti Azərbaycanı hansı əsrdə işğal etdi?','VII əsrdə işğal etdi.',array['VII əsrdə','III əsrdə','XII əsrdə','XX əsrdə'],1),
('tarix6-erken-orta#13','tarix','tarix-6-erken-orta',2,3,'İslam dini Azərbaycanda nə vaxtdan yayılmağa başladı?','Ərəb işğalından sonra.',array['Ərəb işğalından sonra','Sasanilərdən əvvəl','XX əsrdə','Skiflər dövründə'],1),
('tarix6-erken-orta#14','tarix','tarix-6-erken-orta',2,3,'Xürrəmilər hərəkatının rəhbəri kim idi?','Babək rəhbərlik edirdi.',array['Babək','Cavanşir','Atropat','İranzu'],1),
('tarix6-erken-orta#15','tarix','tarix-6-erken-orta',3,3,'Babək hərəkatı təqribən nə qədər davam etdi?','20 ildən artıq davam etdi.',array['20 ildən artıq','2 il','100 il','6 ay'],1),
('tarix6-erken-orta#16','tarix','tarix-6-erken-orta',3,3,'Ərəblərin qeyri-müsəlmanlardan aldığı can vergisi necə adlanırdı?','Cizyə adlanırdı.',array['Cizyə','Xərac yalnız torpaqdan','Gömrük','Bac'],1),
('tarix6-erken-orta#17','tarix','tarix-6-erken-orta',3,3,'Girdiman dövləti hansı sülalə ilə bağlıdır?','Mehranilər sülaləsi ilə.',array['Mehranilərlə','Səfəvilərlə','Əhəmənilərlə','Atabəylərlə'],1),
('tarix6-erken-orta#18','tarix','tarix-6-erken-orta',2,3,'Feodal cəmiyyətində əsas sərvət nə idi?','Torpaq əsas sərvət idi.',array['Torpaq','Neft','Kağız pul','Qızıl yalnız'],1),
('tarix6-erken-orta#19','tarix','tarix-6-erken-orta',3,3,'Natural təsərrüfat nə deməkdir?','Hər şeyin öz təsərrüfatında istehsal olunması.',array['Hər şeyin öz təsərrüfatında istehsalı','Hər şeyin bazardan alınması','Fabrik istehsalı','Xarici ticarət'],1),
('tarix6-erken-orta#20','tarix','tarix-6-erken-orta',2,3,'Bəzz qalası ilə bağlı hərəkat necə adlanırdı?','Xürrəmilər hərəkatı.',array['Xürrəmilər hərəkatı','Dekabristlər','Səlib yürüşü','Qızılbaşlar'],1)
),
ins as (
  insert into public.questions
    (ext_key, owner_type, subject_id, level_id, topic_id, kind,
     body, explanation, difficulty, quarter, status)
  select d.ext, 'platform', s.id, l.id, tp.id, 'single',
         d.body, d.why, d.diff, d.rub, 'published'
    from d
    join public.subjects s on s.slug = d.fenn
    join public.programs p on p.slug = 'orta'
    join public.levels   l on l.program_id = p.id and l.code = '6'
    join public.topics   tp on tp.subject_id = s.id and tp.slug = d.topic
  on conflict (ext_key) do update
    set body = excluded.body, explanation = excluded.explanation,
        difficulty = excluded.difficulty, quarter = excluded.quarter,
        topic_id = excluded.topic_id, level_id = excluded.level_id,
        subject_id = excluded.subject_id, status = 'published'
  returning id, ext_key
)
insert into public.question_options (question_id, ord, body, is_correct)
select ins.id, o.ord, o.txt, o.ord = d.correct
  from ins
  join d on d.ext = ins.ext_key,
  lateral unnest(d.opts) with ordinality as o(txt, ord);

do $$
declare n int; k int;
begin
  select count(*) into n from public.questions
   where owner_type = 'platform'
     and (ext_key like 'az6-%' or ext_key like 'ing6-%'
          or ext_key like 'inf6-%' or ext_key like 'tarix6-%');
  if n <> 480 then
    raise exception 'sinif6 suallari: 480 gozlenilirdi, % tapildi', n;
  end if;
  select count(*) into k from public.questions q
   where (q.ext_key like 'az6-%' or q.ext_key like 'ing6-%'
          or q.ext_key like 'inf6-%' or q.ext_key like 'tarix6-%')
     and ((select count(*) from public.question_options o
            where o.question_id = q.id) <> 4
       or (select count(*) from public.question_options o
            where o.question_id = q.id and o.is_correct) <> 1);
  if k > 0 then
    raise exception '% sualda variant qurulusu sehvdir', k;
  end if;
  select count(distinct topic_id) into k from public.questions
   where ext_key like 'az6-%' or ext_key like 'ing6-%'
      or ext_key like 'inf6-%' or ext_key like 'tarix6-%';
  if k <> 24 then
    raise exception 'movzu sayi 24 deyil: %', k;
  end if;
  raise notice '6-ci sinif banki: % sual, 24 movzu (az, ing, inf, tarix).', n;
end $$;
