-- =====================================================================
--  38_bank_riy8.sql : RIYAZIYYAT 8 PLATFORMA SUAL BANKI (orta mekteb)
--
--  BU FAYL ELLE YAZILMIR - tools/riy8.py yaradir:
--      python3 tools/riy8.py
--
--  11 movzu x 40 sual = 440.  ext_key: riy8-<movzu>#<sira>.
--  ON SERT: 37_movzular_orta8.sql islenmis olmalidir.
--  SONRA:   05_grants.sql yeniden islet.
-- =====================================================================

do $$
begin
  if not exists (
    select 1 from public.topics t
      join public.subjects s on s.id = t.subject_id
     where s.slug = 'riyaziyyat' and t.slug = 'riy-8-pifaqor') then
    raise exception 'ONCE 37_movzular_orta8.sql isledilmelidir (riy-8-* movzulari yoxdur).';
  end if;
end $$;

delete from public.question_options o
 using public.questions q
 where o.question_id = q.id
   and q.owner_type = 'platform'
   and q.ext_key like 'riy8-%';

with d(ext, topic, diff, rub, body, why, opts, correct) as (values
('riy8-kvadrat-kok#1','riy-8-kvadrat-kok',1,1,'√49 neçəyə bərabərdir?','7² = 49, deməli √49 = 7.',array['7','9','24,5','49'],1),
('riy8-kvadrat-kok#2','riy-8-kvadrat-kok',2,1,'√81 + √16 cəmini tapın.','9 + 4 = 13.',array['13','12','97','5'],1),
('riy8-kvadrat-kok#3','riy-8-kvadrat-kok',3,1,'Hansı ədəd irrasional ədəddir?','√2 sonsuz dövrsüz onluq kəsrdir — irrasionaldır.',array['√2','0,5','3/4','7'],1),
('riy8-kvadrat-kok#4','riy-8-kvadrat-kok',2,1,'121 ədədinin kvadrat kökü neçədir?','11² = 121.',array['11','12','60,5','21'],1),
('riy8-kvadrat-kok#5','riy-8-kvadrat-kok',2,1,'(√5)² neçəyə bərabərdir?','Kökün kvadratı kökaltı ifadəyə bərabərdir: 5.',array['5','25','10','2,5'],1),
('riy8-kvadrat-kok#6','riy-8-kvadrat-kok',3,1,'√18 ifadəsini sadələşdirin.','√18 = √(9·2) = 3√2.',array['3√2','9√2','2√3','6√3'],1),
('riy8-kvadrat-kok#7','riy-8-kvadrat-kok',3,1,'√a · √b nəyə bərabərdir? (a, b ≥ 0)','Köklərin hasili hasilin kökünə bərabərdir: √(ab).',array['√(a·b)','√(a+b)','a·b','√a + √b'],1),
('riy8-kvadrat-kok#8','riy-8-kvadrat-kok',2,1,'Həqiqi ədədlər çoxluğuna hansı ədədlər daxildir?','Rasional və irrasional ədədlərin birliyi.',array['Rasional və irrasional ədədlər','Yalnız natural ədədlər','Yalnız kəsrlər','Yalnız mənfi ədədlər'],1),
('riy8-kvadrat-kok#9','riy-8-kvadrat-kok',2,1,'√36 · √25 hasilini tapın.','6 · 5 = 30.',array['30','61','11','900'],1),
('riy8-kvadrat-kok#10','riy-8-kvadrat-kok',2,1,'x² = 64 tənliyinin müsbət kökü neçədir?','8² = 64, müsbət kök 8-dir.',array['8','32','16','4'],1),
('riy8-kvadrat-kok#11','riy-8-kvadrat-kok',2,1,'√144 − √100 fərqini hesablayın.','12 − 10 = 2.',array['2','22','44','4'],1),
('riy8-kvadrat-kok#12','riy-8-kvadrat-kok',2,1,'√625 neçəyə bərabərdir?','25² = 625.',array['25','35','312,5','45'],1),
('riy8-kvadrat-kok#13','riy-8-kvadrat-kok',3,1,'√7 · √28 hasilini hesablayın.','√(7 · 28) = √196 = 14.',array['14','196','35','21'],1),
('riy8-kvadrat-kok#14','riy-8-kvadrat-kok',2,1,'√(16 · 25) neçəyə bərabərdir?','√16 · √25 = 4 · 5 = 20.',array['20','40','400','41'],1),
('riy8-kvadrat-kok#15','riy-8-kvadrat-kok',3,1,'√50 ifadəsini sadələşdirin.','√50 = √(25 · 2) = 5√2.',array['5√2','2√5','25√2','10√5'],1),
('riy8-kvadrat-kok#16','riy-8-kvadrat-kok',3,1,'Köklərin nisbəti √a : √b hansı ifadəyə bərabərdir? (a ≥ 0, b > 0)','Köklərin nisbəti nisbətin kökünə bərabərdir.',array['√(a : b)','√(a − b)','a : b','√a − √b'],1),
('riy8-kvadrat-kok#17','riy-8-kvadrat-kok',2,1,'Aşağıdakılardan hansı rasional ədəddir?','0,25 = 1/4 — rasionaldır; √3, √7 və π irrasionaldır.',array['0,25','√3','π','√7'],1),
('riy8-kvadrat-kok#18','riy-8-kvadrat-kok',2,1,'2√3 + 5√3 cəmini hesablayın.','Eyni köklü hədlər toplanır: 7√3.',array['7√3','7√6','10√3','2√15'],1),
('riy8-kvadrat-kok#19','riy-8-kvadrat-kok',2,1,'√225 neçəyə bərabərdir?','15² = 225.',array['15','25','112,5','16'],1),
('riy8-kvadrat-kok#20','riy-8-kvadrat-kok',1,1,'Ədəd oxunda √9 hansı nöqtəyə uyğun gəlir?','√9 = 3.',array['3','9','4,5','81'],1),
('riy8-kvadrat-kok#21','riy-8-kvadrat-kok',2,1,'√729 neçəyə bərabərdir?','27 · 27 = 729.',array['27','23','29','33'],1),
('riy8-kvadrat-kok#22','riy-8-kvadrat-kok',2,1,'Kökü hesablayın: √(36 · 49).','√36 · √49 = 6 · 7 = 42.',array['42','36','49','84'],1),
('riy8-kvadrat-kok#23','riy-8-kvadrat-kok',2,1,'√12 ifadəsini sadələşdirin.','√12 = √(4·3) = 2√3.',array['2√3','3√2','4√3','6'],1),
('riy8-kvadrat-kok#24','riy-8-kvadrat-kok',2,1,'7√2 − 3√2 fərqini hesablayın.','(7 − 3)√2 = 4√2.',array['4√2','10√2','4','√2'],1),
('riy8-kvadrat-kok#25','riy-8-kvadrat-kok',2,1,'√0,25 neçəyə bərabərdir?','0,5 · 0,5 = 0,25.',array['0,5','0,05','2,5','0,625'],1),
('riy8-kvadrat-kok#26','riy-8-kvadrat-kok',2,1,'x² = 121 tənliyinin kökləri hansılardır?','Həm 11, həm −11 uyğundur.',array['±11','Yalnız 11','Yalnız −11','±12'],1),
('riy8-kvadrat-kok#27','riy-8-kvadrat-kok',2,1,'√5 rasionaldır, yoxsa irrasional?','5 tam kvadrat deyil — kökü irrasionaldır.',array['İrrasionaldır','Rasionaldır','Tam ədəddir','Naturaldır'],1),
('riy8-kvadrat-kok#28','riy-8-kvadrat-kok',2,1,'√(a²) ifadəsi a ≥ 0 üçün nəyə bərabərdir?','Kök kvadratı yox edir: a.',array['a-ya','a²-yə','−a-ya','1-ə'],1),
('riy8-kvadrat-kok#29','riy-8-kvadrat-kok',2,1,'√2 ≈ ? — təqribi qiyməti hansıdır?','√2 ≈ 1,41.',array['1,41','1,73','2,24','1,2'],1),
('riy8-kvadrat-kok#30','riy-8-kvadrat-kok',3,1,'Hasili kök altında birləşdirin: √13 · √52.','√(13·52) = √676 = 26.',array['26','13','52','676'],1),
('riy8-kvadrat-kok#31','riy-8-kvadrat-kok',2,1,'Kökaltı ifadə mənfi ola bilərmi (həqiqi ədədlərdə)?','Mənfi ədədin həqiqi kökü yoxdur.',array['Xeyr, ola bilməz','Bəli, həmişə','Yalnız cüt ədədlərdə','Yalnız sıfırda'],1),
('riy8-kvadrat-kok#32','riy-8-kvadrat-kok',2,1,'√64 + √36 cəmini addım-addım tapın.','8 + 6 = 14.',array['14-ə bərabərdir','10-a bərabərdir','100-ə bərabərdir','12-yə bərabərdir'],1),
('riy8-kvadrat-kok#33','riy-8-kvadrat-kok',2,1,'0,09-un kvadrat kökü neçədir?','0,3 · 0,3 = 0,09.',array['0,3','0,03','0,9','3'],1),
('riy8-kvadrat-kok#34','riy-8-kvadrat-kok',1,1,'Kök işarəsinin altındakı ədəd necə adlanır?','Kökaltı ifadə adlanır.',array['Kökaltı ifadə','Əmsal','Qüvvət üstü','Məxrəc'],1),
('riy8-kvadrat-kok#35','riy-8-kvadrat-kok',2,1,'π ədədi hansı çoxluğa aiddir?','π sonsuz dövrsüz kəsrdir.',array['İrrasional ədədlərə','Rasional ədədlərə','Tam ədədlərə','Natural ədədlərə'],1),
('riy8-kvadrat-kok#36','riy-8-kvadrat-kok',2,1,'√(49/64) kəsrinin kökünü tapın.','√49/√64 = 7/8.',array['7/8','8/7','49/64','7/64'],1),
('riy8-kvadrat-kok#37','riy-8-kvadrat-kok',2,1,'İrrasional ədədin onluq yazılışı necədir?','Sonsuzdur və dövr etmir.',array['Sonsuz, dövrsüz','Sonlu','Sonsuz dövri','Həmişə tamdır'],1),
('riy8-kvadrat-kok#38','riy-8-kvadrat-kok',3,1,'2√5 ifadəsini tam kök şəklinə salın.','2√5 = √(4·5) = √20.',array['√20','√10','√7','√25'],1),
('riy8-kvadrat-kok#39','riy-8-kvadrat-kok',2,1,'Həqiqi ədədlər çoxluğu hansı iki çoxluğun birləşməsidir?','Rasionallar və irrasionallar birlikdə.',array['Rasional və irrasionalın','Tam və mənfilərin','Cüt və təklərin','Müsbət və kəsrlərin'],1),
('riy8-kvadrat-kok#40','riy-8-kvadrat-kok',3,1,'√10 hansı iki qonşu tam ədəd arasındadır?','9 < 10 < 16 — deməli 3 < √10 < 4.',array['3 ilə 4 arasında','2 ilə 3 arasında','4 ilə 5 arasında','9 ilə 10 arasında'],1),
('riy8-pifaqor#1','riy-8-pifaqor',2,1,'Pifaqor teoremi hansı üçbucağa tətbiq olunur?','Teorem düzbucaqlı üçbucaq üçündür.',array['Düzbucaqlı üçbucağa','İstənilən üçbucağa','Yalnız bərabərtərəfliyə','Dördbucaqlıya'],1),
('riy8-pifaqor#2','riy-8-pifaqor',2,1,'Pifaqor teoreminin düsturu hansıdır?','Hipotenuzun kvadratı katetlərin kvadratları cəminə bərabərdir.',array['c² = a² + b²','c = a + b','c² = a² − b²','c = a · b'],1),
('riy8-pifaqor#3','riy-8-pifaqor',2,1,'Katetlər 3 və 4 olarsa, hipotenuz neçədir?','√(9 + 16) = √25 = 5.',array['5','7','12','25'],1),
('riy8-pifaqor#4','riy-8-pifaqor',2,1,'Katetlər 5 və 12 olarsa, hipotenuzu tapın.','√(25 + 144) = √169 = 13.',array['13','17','60','169'],1),
('riy8-pifaqor#5','riy-8-pifaqor',3,1,'Hipotenuz 13, katetlərdən biri 5-dirsə, o biri kateti tapın.','√(169 − 25) = √144 = 12.',array['12','8','18','144'],1),
('riy8-pifaqor#6','riy-8-pifaqor',2,1,'Hipotenuz üçbucağın hansı tərəfidir?','Düz bucağın qarşısındakı ən böyük tərəfdir.',array['Düz bucaq qarşısındakı tərəf','Ən kiçik tərəf','İstənilən tərəf','Hündürlük'],1),
('riy8-pifaqor#7','riy-8-pifaqor',3,1,'Tərəfləri 7, 24 və 25 olan üçbucaq düzbucaqlıdırmı?','7² + 24² = 49 + 576 = 625 = 25² — bəli.',array['Bəli','Xeyr','Yalnız bərabəryanlıdırsa','Müəyyən etmək olmaz'],1),
('riy8-pifaqor#8','riy-8-pifaqor',3,1,'Kvadratın diaqonalı tərəfindən neçə dəfə böyükdür?','d = a√2 — √2 dəfə böyükdür.',array['√2 dəfə','2 dəfə','4 dəfə','Bərabərdir'],1),
('riy8-pifaqor#9','riy-8-pifaqor',3,1,'Katetləri a olan bərabəryanlı düzbucaqlı üçbucağın hipotenuzu nəyə bərabərdir?','c = √(a² + a²) = a√2.',array['a√2','2a','a²','a/2'],1),
('riy8-pifaqor#10','riy-8-pifaqor',3,1,'Düzbucaqlının tərəfləri 9 və 12-dirsə, diaqonalı neçədir?','√(81 + 144) = √225 = 15.',array['15','21','13','225'],1),
('riy8-pifaqor#11','riy-8-pifaqor',2,1,'Düzbucaqlı üçbucağın katetləri 8 və 15-dirsə, hipotenuzunu hesablayın.','√(64 + 225) = √289 = 17.',array['17','23','120','289'],1),
('riy8-pifaqor#12','riy-8-pifaqor',3,1,'Hipotenuzu 25, bir kateti 7 olan üçbucağın o biri katetini hesablayın.','√(625 − 49) = √576 = 24.',array['24','18','32','576'],1),
('riy8-pifaqor#13','riy-8-pifaqor',3,1,'Tərəfləri 6, 8 və 11 olan üçbucaq düzbucaqlıdırmı?','6² + 8² = 100, 11² = 121 — bərabər deyil, düzbucaqlı deyil.',array['Xeyr','Bəli','Yalnız bərabəryanlıdırsa','Müəyyən etmək olmaz'],1),
('riy8-pifaqor#14','riy-8-pifaqor',3,1,'Bərabəryanlı düzbucaqlı üçbucağın hipotenuzu 4√2-dirsə, kateti neçədir?','c = a√2 olduğundan a = 4.',array['4','8','4√2','2√2'],1),
('riy8-pifaqor#15','riy-8-pifaqor',2,1,'Pifaqor üçlüyü nədir?','c² = a² + b² şərtini ödəyən üç natural ədəddir (məs. 3, 4, 5).',array['c² = a² + b² şərtini ödəyən üç natural ədəd','İstənilən üç ədəd','Üç cüt ədəd','Üç sadə ədəd'],1),
('riy8-pifaqor#16','riy-8-pifaqor',3,1,'Aşağıdakılardan hansı Pifaqor üçlüyüdür?','8² + 15² = 289 = 17² — Pifaqor üçlüyüdür.',array['8, 15, 17','5, 6, 7','2, 3, 4','10, 11, 12'],1),
('riy8-pifaqor#17','riy-8-pifaqor',3,1,'Kvadratın tərəfi 10-dursa, diaqonalı nəyə bərabərdir?','d = a√2 = 10√2.',array['10√2','20','100','10'],1),
('riy8-pifaqor#18','riy-8-pifaqor',3,1,'Düzbucaqlının eni 12, diaqonalı 20-dirsə, uzunluğunu tapın.','√(400 − 144) = √256 = 16.',array['16','8','32','256'],1),
('riy8-pifaqor#19','riy-8-pifaqor',3,1,'Divara söykənən 5 m-lik nərdivanın aşağı ucu divardan 3 m aralıdır. Nərdivan divarda hansı hündürlüyə çatır?','√(25 − 9) = √16 = 4 m.',array['4 m','2 m','8 m','16 m'],1),
('riy8-pifaqor#20','riy-8-pifaqor',3,1,'Katetləri 20 və 21 olan üçbucağın hipotenuzu neçədir?','√(400 + 441) = √841 = 29.',array['29','41','420','31'],1),
('riy8-pifaqor#21','riy-8-pifaqor',3,1,'Katetləri 9 və 40 olan düzbucaqlı üçbucağın hipotenuzunu tapın.','81 + 1600 = 1681 = 41².',array['41','49','31','1681'],1),
('riy8-pifaqor#22','riy-8-pifaqor',3,1,'Hipotenuz 50, katetlərdən biri 14-dürsə, o biri kateti tapın.','2500 − 196 = 2304 = 48².',array['48','36','64','44'],1),
('riy8-pifaqor#23','riy-8-pifaqor',2,1,'Pifaqor teoremi sözlə necə ifadə olunur?','c² = a² + b².',array['Katetlərin kvadratları cəmi hipotenuzun kvadratıdır','Tərəflərin cəmi perimetrdir','Bucaqların cəmi 180°-dir','Sahə oturacaq vur hündürlükdür'],1),
('riy8-pifaqor#24','riy-8-pifaqor',3,1,'Tərəfləri 9, 12, 15 olan üçbucaq düzbucaqlıdırmı?','81 + 144 = 225 = 15² — bəli.',array['Bəli, düzbucaqlıdır','Xeyr, deyil','Bərabərtərəflidir','Müəyyən olunmur'],1),
('riy8-pifaqor#25','riy-8-pifaqor',3,1,'Kvadratın diaqonalı 5√2-dirsə, tərəfi neçədir?','d = a√2 olduğundan a = 5.',array['5-ə bərabərdir','10-a bərabərdir','√2-yə bərabərdir','25-ə bərabərdir'],1),
('riy8-pifaqor#26','riy-8-pifaqor',2,1,'Düz künc yoxlaması üçün ustalar hansı üçlüyü işlədir?','3-4-5 üçlüyü düz bucaq verir.',array['3-4-5 üçlüyünü','1-2-3 üçlüyünü','2-3-4 üçlüyünü','5-6-7 üçlüyünü'],1),
('riy8-pifaqor#27','riy-8-pifaqor',2,1,'İkiqat Pifaqor üçlüyü: 3-4-5-i 2-yə vursaq hansı üçlük alınar?','6-8-10 da Pifaqor üçlüyüdür.',array['6-8-10','5-6-7','9-12-14','4-5-6'],1),
('riy8-pifaqor#28','riy-8-pifaqor',2,1,'Ekranın diaqonalı düzbucaqlı ölçülərdən necə tapılır?','Diaqonal hipotenuz kimidir.',array['Pifaqor teoremi ilə','Perimetrlə','Sahə ilə','Ölçmək olmur'],1),
('riy8-pifaqor#29','riy-8-pifaqor',3,1,'Katetlərdən biri 12, hipotenuz 13 olan üçbucağın sahəsini tapın.','O biri katet 5; S = 12·5 : 2 = 30.',array['Sahəsi 30-dur','Sahəsi 60-dır','Sahəsi 78-dir','Sahəsi 65-dir'],1),
('riy8-pifaqor#30','riy-8-pifaqor',3,1,'Bərabəryanlı düzbucaqlı üçbucaqda katet 6-dırsa, hipotenuz nəyə bərabərdir?','c = a√2 = 6√2.',array['6√2','12','6','36'],1),
('riy8-pifaqor#31','riy-8-pifaqor',3,1,'Rombun diaqonalları 12 və 16-dırsa, tərəfini tapın.','Yarılar 6 və 8; tərəf √(36+64) = 10.',array['10 vahid','14 vahid','28 vahid','20 vahid'],1),
('riy8-pifaqor#32','riy-8-pifaqor',3,1,'Nöqtə (16; 30) koordinat başlanğıcından hansı məsafədədir?','√(256 + 900) = √1156 = 34.',array['34','46','30','36'],1),
('riy8-pifaqor#33','riy-8-pifaqor',3,1,'Pifaqor teoreminin tərsi nəyi yoxlamağa imkan verir?','Tərəflərə görə düz bucağın olmasını.',array['Üçbucağın düzbucaqlı olmasını','Sahəni','Perimetri','Oxşarlığı'],1),
('riy8-pifaqor#34','riy-8-pifaqor',3,1,'Katetlər bərabərdirsə (a = b), hipotenuz düsturu necə yazılır?','c = √(2a²) = a√2.',array['c = a√2','c = 2a','c = a²','c = a/2'],1),
('riy8-pifaqor#35','riy-8-pifaqor',3,1,'c² = 1089 olduqda hipotenuz c neçədir?','33² = 1089.',array['33','34','39','43'],1),
('riy8-pifaqor#36','riy-8-pifaqor',3,1,'Qapı çərçivəsi 0,9 m enində, 1,2 m hündürlüyündədir. Diaqonalı neçədir?','0,81 + 1,44 = 2,25 = 1,5².',array['1,5 m','2,1 m','1,2 m','2,25 m'],1),
('riy8-pifaqor#37','riy-8-pifaqor',1,1,'Pifaqor hansı ölkənin alimidir?','Pifaqor qədim yunan riyaziyyatçısıdır.',array['Yunanıstanın','Misirin','Romanın','Hindistanın'],1),
('riy8-pifaqor#38','riy-8-pifaqor',2,1,'Düzbucaqlı üçbucaqda hipotenuz katetdən qısa ola bilərmi?','Hipotenuz ən uzun tərəfdir.',array['Xeyr, ola bilməz','Bəli, bəzən','Həmişə qısadır','Bərabər olurlar'],1),
('riy8-pifaqor#39','riy-8-pifaqor',3,1,'Üçbucağın tərəfləri 5, 5, 5√2-dirsə, ən böyük bucağı neçədir?','5² + 5² = (5√2)² — düz bucaq var.',array['90 dərəcə','60 dərəcə','45 dərəcə','120 dərəcə'],1),
('riy8-pifaqor#40','riy-8-pifaqor',3,1,'13 metrlik kabel dirəyin başından yerə çəkilib, dirəkdən 5 m aralıda bərkidilib. Dirəyin hündürlüyü neçədir?','169 − 25 = 144 = 12².',array['12 metr','8 metr','18 metr','13 metr'],1),
('riy8-kvadrat-tenlik#1','riy-8-kvadrat-tenlik',2,2,'Kvadrat tənliyin ümumi şəkli hansıdır?','ax² + bx + c = 0 (a ≠ 0).',array['ax² + bx + c = 0','ax + b = 0','a/x = b','ax³ = 0'],1),
('riy8-kvadrat-tenlik#2','riy-8-kvadrat-tenlik',2,2,'x² − 9 = 0 tənliyinin kökləri hansılardır?','x² = 9; x = 3 və x = −3.',array['3 və −3','Yalnız 3','9 və −9','Kökü yoxdur'],1),
('riy8-kvadrat-tenlik#3','riy-8-kvadrat-tenlik',2,2,'Diskriminant hansı düsturla hesablanır?','D = b² − 4ac.',array['D = b² − 4ac','D = b² + 4ac','D = 2a − b','D = a² − c²'],1),
('riy8-kvadrat-tenlik#4','riy-8-kvadrat-tenlik',3,2,'D < 0 olduqda kvadrat tənliyin neçə həqiqi kökü var?','Mənfi diskriminantda həqiqi kök yoxdur.',array['Həqiqi kökü yoxdur','Bir kökü var','İki kökü var','Sonsuz kökü var'],1),
('riy8-kvadrat-tenlik#5','riy-8-kvadrat-tenlik',3,2,'x² − 5x + 6 = 0 tənliyinin kökləri hansılardır?','Vietaya görə: cəm 5, hasil 6 — köklər 2 və 3.',array['2 və 3','1 və 6','−2 və −3','5 və 6'],1),
('riy8-kvadrat-tenlik#6','riy-8-kvadrat-tenlik',3,2,'x² + 4x = 0 tənliyini həll edin.','x(x + 4) = 0; x = 0 və x = −4.',array['0 və −4','Yalnız −4','0 və 4','2 və −2'],1),
('riy8-kvadrat-tenlik#7','riy-8-kvadrat-tenlik',3,2,'D = 0 olduqda tənliyin neçə kökü olur?','Bir (ikiqat) kök olur.',array['Bir (ikiqat) kök','İki müxtəlif kök','Kök olmur','Üç kök'],1),
('riy8-kvadrat-tenlik#8','riy-8-kvadrat-tenlik',3,2,'x² + px + q = 0 tənliyində köklərin cəmi nəyə bərabərdir?','Viet teoreminə görə cəm −p-yə bərabərdir.',array['−p','p','q','−q'],1),
('riy8-kvadrat-tenlik#9','riy-8-kvadrat-tenlik',3,2,'x² = 11x tənliyinin sıfırdan fərqli kökü neçədir?','x(x − 11) = 0; sıfırdan fərqli kök 11-dir.',array['11','−11','121','1'],1),
('riy8-kvadrat-tenlik#10','riy-8-kvadrat-tenlik',2,2,'2x² − 8 = 0 tənliyinin müsbət kökü neçədir?','x² = 4; müsbət kök 2.',array['2','4','8','16'],1),
('riy8-kvadrat-tenlik#11','riy-8-kvadrat-tenlik',2,2,'x² = 49 tənliyini həll edin.','x = 7 və x = −7.',array['7 və −7','Yalnız 7','49 və −49','Kökü yoxdur'],1),
('riy8-kvadrat-tenlik#12','riy-8-kvadrat-tenlik',2,2,'Diskriminant müsbət olduqda tənliyin kökləri haqqında nə demək olar?','D > 0 olduqda iki müxtəlif həqiqi kök var.',array['İki müxtəlif həqiqi kökü var','Kökü yoxdur','Bir kökü var','Sonsuz kökü var'],1),
('riy8-kvadrat-tenlik#13','riy-8-kvadrat-tenlik',3,2,'Viet teoreminə görə x² + px + q = 0 tənliyində köklərin hasili nəyə bərabərdir?','Hasil q-yə bərabərdir.',array['q','−q','p','−p'],1),
('riy8-kvadrat-tenlik#14','riy-8-kvadrat-tenlik',3,2,'x² − 7x + 10 = 0 tənliyinin kökləri hansılardır?','Cəmi 7, hasili 10 olan ədədlər: 2 və 5.',array['2 və 5','1 və 10','−2 və −5','3 və 4'],1),
('riy8-kvadrat-tenlik#15','riy-8-kvadrat-tenlik',2,2,'Hansı tənliyin kökləri 10 və −10-dur?','x² − 100 = 0 tənliyinin kökləri ±10-dur.',array['x² − 100 = 0','x² + 100 = 0','x² − 10 = 0','x + 10 = 0'],1),
('riy8-kvadrat-tenlik#16','riy-8-kvadrat-tenlik',3,2,'x² + 6x + 9 = 0 tənliyinin neçə kökü var?','D = 36 − 36 = 0 — bir (ikiqat) kök.',array['Bir (ikiqat) kök','İki müxtəlif kök','Kök yoxdur','Üç kök'],1),
('riy8-kvadrat-tenlik#17','riy-8-kvadrat-tenlik',2,2,'Kvadrat tənlikdə a əmsalı hansı şərti ödəməlidir?','a = 0 olsa tənlik xətti olar; a ≠ 0 olmalıdır.',array['a ≠ 0','a > 0','a = 1','a < 0'],1),
('riy8-kvadrat-tenlik#18','riy-8-kvadrat-tenlik',3,2,'x² − 18x + 77 = 0 tənliyinin köklərinin cəmi neçədir?','Viet teoreminə görə cəm 18-dir.',array['18','77','−18','9'],1),
('riy8-kvadrat-tenlik#19','riy-8-kvadrat-tenlik',2,2,'Aşağıdakılardan hansı natamam kvadrat tənlikdir?','c əmsalı sıfırdır: x² − 5x = 0 natamamdır.',array['x² − 5x = 0','x² + 3x + 2 = 0','x² − x + 1 = 0','2x + 1 = 0'],1),
('riy8-kvadrat-tenlik#20','riy-8-kvadrat-tenlik',2,2,'Kökləri 4 və 6 olan kvadrat tənlikdə köklərin hasili neçədir?','4 · 6 = 24.',array['24','10','46','2'],1),
('riy8-kvadrat-tenlik#21','riy-8-kvadrat-tenlik',3,2,'x² − 3x − 10 = 0 tənliyinin kökləri hansılardır?','Hasil −10, cəm 3: köklər 5 və −2.',array['5 və −2','−5 və 2','5 və 2','−5 və −2'],1),
('riy8-kvadrat-tenlik#22','riy-8-kvadrat-tenlik',2,2,'Diskriminantı hesablayın: x² − 6x + 5 = 0.','D = 36 − 20 = 16.',array['D = 16','D = 56','D = 4','D = −16'],1),
('riy8-kvadrat-tenlik#23','riy-8-kvadrat-tenlik',2,2,'Natamam tənlik x² − 16 = 0 neçə kökə malikdir?','x = ±4 — iki kök.',array['İki kökə (±4)','Bir kökə','Kökü yoxdur','Dörd kökə'],1),
('riy8-kvadrat-tenlik#24','riy-8-kvadrat-tenlik',2,2,'Vietə görə köklərin cəmini deyin: x² − 9x + 20 = 0.','Cəm −p = 9.',array['9-a bərabərdir','20-yə bərabərdir','−9-a bərabərdir','11-ə bərabərdir'],1),
('riy8-kvadrat-tenlik#25','riy-8-kvadrat-tenlik',2,2,'5x² = 0 tənliyinin kökü neçədir?','x² = 0, x = 0.',array['x = 0','x = 5','Kökü yoxdur','x = ±5'],1),
('riy8-kvadrat-tenlik#26','riy-8-kvadrat-tenlik',2,2,'ax² + bx + c = 0-da b = 0 və ya c = 0 olan tənlik necə adlanır?','Belə tənlik natamamdır.',array['Natamam tənlik','Tam tənlik','Xətti tənlik','Rasional tənlik'],1),
('riy8-kvadrat-tenlik#27','riy-8-kvadrat-tenlik',3,2,'x² + 8x + 16 = 0 tənliyinin kökünü tapın.','(x + 4)² = 0, x = −4.',array['x = −4','x = 4','x = ±4','x = 8'],1),
('riy8-kvadrat-tenlik#28','riy-8-kvadrat-tenlik',3,2,'Kökləri −3 və 7 olan tənlikdə köklərin cəmi və hasili hansı cütdür?','Cəm 4, hasil −21.',array['Cəm 4, hasil −21','Cəm −4, hasil 21','Cəm 10, hasil −21','Cəm 4, hasil 21'],1),
('riy8-kvadrat-tenlik#29','riy-8-kvadrat-tenlik',3,2,'2x² − 5x + 2 = 0 tənliyinin böyük kökü neçədir?','Köklər 2 və 1/2 — böyüyü 2.',array['x = 2','x = 1/2','x = 5','x = −2'],1),
('riy8-kvadrat-tenlik#30','riy-8-kvadrat-tenlik',3,2,'Tənlik qurun: kökləri 2 və 5-dir (Vietə görə).','Cəm 7, hasil 10: x² − 7x + 10 = 0.',array['x² − 7x + 10 = 0','x² + 7x + 10 = 0','x² − 10x + 7 = 0','x² − 7x − 10 = 0'],1),
('riy8-kvadrat-tenlik#31','riy-8-kvadrat-tenlik',2,2,'D > 0, D = 0, D < 0 halları nəyi müəyyən edir?','Diskriminant köklərin sayını göstərir.',array['Köklərin sayını','Əmsalları','Qrafikin rəngini','Tənliyin dərəcəsini'],1),
('riy8-kvadrat-tenlik#32','riy-8-kvadrat-tenlik',2,2,'x² = 5x tənliyini vuruqlara ayırmaqla həll edin: köklər hansılardır?','x(x − 5) = 0: köklər 0 və 5.',array['0 və 5','Yalnız 5','Yalnız 0','±5'],1),
('riy8-kvadrat-tenlik#33','riy-8-kvadrat-tenlik',1,2,'Kvadrat tənliyin ən çoxu neçə həqiqi kökü ola bilər?','İkinci dərəcəli tənlikdə ən çoxu iki kök.',array['İki kökü','Bir kökü','Üç kökü','Sonsuz kökü'],1),
('riy8-kvadrat-tenlik#34','riy-8-kvadrat-tenlik',3,2,'9x² − 1 = 0 tənliyinin kökləri hansılardır?','x² = 1/9, x = ±1/3.',array['±1/3','±3','±1/9','±9'],1),
('riy8-kvadrat-tenlik#35','riy-8-kvadrat-tenlik',2,2,'x² + 2x − 35 = 0 tənliyində köklərin hasili Vietə görə neçədir?','Hasil q = −35.',array['−35','35','−2','2'],1),
('riy8-kvadrat-tenlik#36','riy-8-kvadrat-tenlik',3,2,'Tam kvadrat ayırma üsulu hansı düstura əsaslanır?','Cəmin kvadratı düsturuna.',array['Cəmin kvadratına','Kublar fərqinə','Vietə','Pifaqora'],1),
('riy8-kvadrat-tenlik#37','riy-8-kvadrat-tenlik',3,2,'Məsələ: hasilləri 63, cəmləri 16 olan iki ədəd hansılardır?','7 · 9 = 63, 7 + 9 = 16.',array['7 və 9','6 və 10','8 və 8','3 və 21'],1),
('riy8-kvadrat-tenlik#38','riy-8-kvadrat-tenlik',2,2,'Müsbət kökü tapın: 3x² = 27 olarsa x neçədir?','x² = 9, x = 3.',array['x = 3','x = 9','x = 27','x = √3'],1),
('riy8-kvadrat-tenlik#39','riy-8-kvadrat-tenlik',2,2,'Diskriminant 49-dursa, kök düsturunda √D nəyə bərabərdir?','√49 = 7.',array['√D = 7','√D = 49','√D = 14','√D = 24,5'],1),
('riy8-kvadrat-tenlik#40','riy-8-kvadrat-tenlik',2,2,'Kvadrat funksiyanın qrafiki hansı əyridir?','y = ax² + bx + c qrafiki paraboladır.',array['Parabola','Düz xətt','Çevrə','Hiperbola'],1),
('riy8-dordbucaqlilar#1','riy-8-dordbucaqlilar',2,2,'Paraleloqramın qarşı tərəfləri necədir?','Qarşı tərəflər paralel və bərabərdir.',array['Paralel və bərabərdir','Perpendikulyar','Həmişə fərqlidir','Kəsişir'],1),
('riy8-dordbucaqlilar#2','riy-8-dordbucaqlilar',2,2,'Rombun bütün tərəfləri haqqında nə demək olar?','Rombda bütün tərəflər bərabərdir.',array['Bərabərdir','Fərqlidir','Paralel deyil','Ölçüsüzdür'],1),
('riy8-dordbucaqlilar#3','riy-8-dordbucaqlilar',2,2,'Dördbucaqlının daxili bucaqlarının cəmi neçədir?','Dördbucaqlıda bucaqların cəmi 360°-dir.',array['360°','180°','90°','540°'],1),
('riy8-dordbucaqlilar#4','riy-8-dordbucaqlilar',3,2,'Paraleloqramın diaqonalları kəsişmə nöqtəsində nə edir?','Diaqonallar yarıya bölünür.',array['Yarıya bölünür','Perpendikulyar olur','Kəsişmir','Bərabərləşir'],1),
('riy8-dordbucaqlilar#5','riy-8-dordbucaqlilar',3,2,'Rombun diaqonalları bir-birinə necədir?','Diaqonallar perpendikulyardır və yarıya bölünür.',array['Perpendikulyardır','Paraleldir','Bərabərdir həmişə','Kəsişmir'],1),
('riy8-dordbucaqlilar#6','riy-8-dordbucaqlilar',2,2,'Trapesiyanın hansı tərəfləri paraleldir?','Oturacaqları paraleldir.',array['Oturacaqları','Yan tərəfləri','Bütün tərəfləri','Heç biri'],1),
('riy8-dordbucaqlilar#7','riy-8-dordbucaqlilar',3,2,'Kvadrat hansı fiqurların xüsusi halıdır?','Kvadrat həm düzbucaqlı, həm də rombdur.',array['Düzbucaqlının və rombun','Yalnız trapesiyanın','Yalnız üçbucağın','Dairənin'],1),
('riy8-dordbucaqlilar#8','riy-8-dordbucaqlilar',3,2,'Düzbucaqlının diaqonalları haqqında nə demək olar?','Düzbucaqlının diaqonalları bərabərdir.',array['Bərabərdirlər','Perpendikulyardırlar həmişə','Kəsişmirlər','Tərəfə bərabərdirlər'],1),
('riy8-dordbucaqlilar#9','riy-8-dordbucaqlilar',3,2,'Trapesiyanın orta xətti nəyə bərabərdir?','Oturacaqların cəminin yarısına.',array['Oturacaqlar cəminin yarısına','Yan tərəflərin cəminə','Hündürlüyə','Perimetrə'],1),
('riy8-dordbucaqlilar#10','riy-8-dordbucaqlilar',3,2,'Paraleloqramın qonşu bucaqlarının cəmi neçədir?','Qonşu bucaqların cəmi 180°-dir.',array['180°','90°','360°','60°'],1),
('riy8-dordbucaqlilar#11','riy-8-dordbucaqlilar',2,2,'Paraleloqramın qarşı bucaqları haqqında nə demək olar?','Qarşı bucaqlar bərabərdir.',array['Cüt-cüt bərabərdir','Cəmi 90°-dir','Həmişə itidir','Fərqlidir'],1),
('riy8-dordbucaqlilar#12','riy-8-dordbucaqlilar',2,2,'Yan tərəfləri bərabər olan trapesiya necə adlanır?','Bərabəryanlı trapesiya.',array['Bərabəryanlı trapesiya','Düzbucaqlı trapesiya','Paraleloqram','Romb'],1),
('riy8-dordbucaqlilar#13','riy-8-dordbucaqlilar',2,2,'Perimetri 72 olan kvadratın tərəfi neçədir?','72 : 4 = 18.',array['18','36','9','24'],1),
('riy8-dordbucaqlilar#14','riy-8-dordbucaqlilar',3,2,'Rombun diaqonalları onun bucaqlarını necə bölür?','Diaqonallar bucaqları yarıya bölür (bissektrisadır).',array['Yarıya bölür (bissektrisadır)','Üç yerə bölür','Bölmür','İxtiyari bölür'],1),
('riy8-dordbucaqlilar#15','riy-8-dordbucaqlilar',1,2,'Düzbucaqlının hər bucağı neçə dərəcədir?','Düzbucaqlıda bütün bucaqlar 90°-dir.',array['90°','60°','120°','45°'],1),
('riy8-dordbucaqlilar#16','riy-8-dordbucaqlilar',3,2,'Paraleloqramın diaqonalı onu hansı fiqurlara bölür?','Diaqonal paraleloqramı iki bərabər üçbucağa bölür.',array['İki bərabər üçbucağa','İki kvadrata','Dörd romba','İki trapesiyaya'],1),
('riy8-dordbucaqlilar#17','riy-8-dordbucaqlilar',3,2,'Kvadratın diaqonalları haqqında hansı fikir doğrudur?','Kvadratda diaqonallar həm bərabərdir, həm perpendikulyardır.',array['Bərabər və perpendikulyardır','Yalnız bərabərdir','Yalnız perpendikulyardır','Kəsişmir'],1),
('riy8-dordbucaqlilar#18','riy-8-dordbucaqlilar',2,2,'Hansı dördbucaqlının yalnız bir cüt paralel tərəfi var?','Trapesiyanın yalnız oturacaqları paraleldir.',array['Trapesiya','Paraleloqram','Kvadrat','Romb'],1),
('riy8-dordbucaqlilar#19','riy-8-dordbucaqlilar',2,2,'Paraleloqramın tərəfləri 6 və 9-dursa, perimetri neçədir?','P = 2 · (6 + 9) = 30.',array['30','15','54','60'],1),
('riy8-dordbucaqlilar#20','riy-8-dordbucaqlilar',2,2,'Tərəfi 7 olan rombun perimetri neçədir?','P = 4 · 7 = 28.',array['28','14','49','21'],1),
('riy8-dordbucaqlilar#21','riy-8-dordbucaqlilar',2,2,'Paraleloqramın bir bucağı 70°-dirsə, qonşu bucağı neçədir?','180 − 70 = 110.',array['110°','70°','90°','20°'],1),
('riy8-dordbucaqlilar#22','riy-8-dordbucaqlilar',2,2,'Rombun diaqonalları hansı bucaq altında kəsişir?','Diaqonallar perpendikulyardır: 90°.',array['Düz bucaq altında','İti bucaq altında','Kor bucaq altında','İstənilən bucaq altında'],1),
('riy8-dordbucaqlilar#23','riy-8-dordbucaqlilar',1,2,'Trapesiyanın paralel tərəfləri necə adlanır?','Paralel tərəflər oturacaqlardır.',array['Oturacaqlar','Yan tərəflər','Diaqonallar','Hündürlüklər'],1),
('riy8-dordbucaqlilar#24','riy-8-dordbucaqlilar',2,2,'Kvadratın diaqonalı ilə tərəfi arasındakı bucaq neçədir?','Diaqonal bucağı yarıya bölür: 45°.',array['45°','90°','60°','30°'],1),
('riy8-dordbucaqlilar#25','riy-8-dordbucaqlilar',3,2,'Paraleloqramın perimetri 40, bir tərəfi 3-dürsə, qonşu tərəfi neçədir?','(40 − 6) : 2 = 17.',array['17','37','20','34'],1),
('riy8-dordbucaqlilar#26','riy-8-dordbucaqlilar',2,2,'Düzbucaqlıda diaqonallar kəsişmə nöqtəsində necə bölünür?','Diaqonallar yarı bölünür.',array['Yarı-yarıya','1 : 2 nisbətində','Bölünmür','1 : 3 nisbətində'],1),
('riy8-dordbucaqlilar#27','riy-8-dordbucaqlilar',3,2,'Rombda diaqonallar həm də nədir?','Diaqonallar bucaqları yarıya bölür.',array['Bucaq tənbölənləri','Hündürlüklər','Orta xətlər','Perimetrlər'],1),
('riy8-dordbucaqlilar#28','riy-8-dordbucaqlilar',2,2,'Hansı paraleloqramın diaqonalları bərabərdir?','Düzbucaqlının diaqonalları bərabərdir.',array['Düzbucaqlının','Adi paraleloqramın','Rombun','Heç birinin'],1),
('riy8-dordbucaqlilar#29','riy-8-dordbucaqlilar',2,2,'Trapesiyanın oturacaqları 12 və 30-dursa, orta xətti neçədir?','(12 + 30) : 2 = 21.',array['21','42','18','15'],1),
('riy8-dordbucaqlilar#30','riy-8-dordbucaqlilar',3,2,'Kvadratın diaqonalları hansı üç xassəni birləşdirir?','Bərabər, perpendikulyar və tənböləndir.',array['Hər üçünü','Yalnız bərabərliyi','Yalnız perpendikulyarlığı','Heç birini'],1),
('riy8-dordbucaqlilar#31','riy-8-dordbucaqlilar',2,2,'Paraleloqramın qarşı bucaqlarından biri 65°-dirsə, digəri neçədir?','Qarşı bucaqlar bərabərdir.',array['65°','115°','125°','90°'],1),
('riy8-dordbucaqlilar#32','riy-8-dordbucaqlilar',2,2,'Dördbucaqlının üç bucağı 90°, 80°, 100°-dirsə, dördüncü bucaq neçədir?','360 − 270 = 90.',array['90°','100°','80°','70°'],1),
('riy8-dordbucaqlilar#33','riy-8-dordbucaqlilar',2,2,'Romb ilə kvadratın fərqi nədir?','Kvadratın bütün bucaqları düzdür.',array['Kvadratda bucaqlar düzdür','Rombun tərəfləri fərqlidir','Fərq yoxdur','Kvadratda diaqonal yoxdur'],1),
('riy8-dordbucaqlilar#34','riy-8-dordbucaqlilar',3,2,'Düzbucaqlının perimetri 62, uzunluğu 12-dirsə, eni neçədir?','(62 − 24) : 2 = 19.',array['19','50','26','31'],1),
('riy8-dordbucaqlilar#35','riy-8-dordbucaqlilar',2,2,'Bərabəryanlı trapesiyanın oturacaq bucaqları necədir?','Oturacağa bitişik bucaqlar bərabərdir.',array['Bərabərdirlər','Fərqlidirlər','Cəmi 90°-dir','Həmişə kordur'],1),
('riy8-dordbucaqlilar#36','riy-8-dordbucaqlilar',2,2,'Paraleloqram olmaq üçün dördbucaqlının qarşı tərəfləri necə olmalıdır?','Qarşı tərəflər cüt-cüt paralel olmalıdır.',array['Paralel və bərabər','Perpendikulyar','Yalnız bərabər','Kəsişən'],1),
('riy8-dordbucaqlilar#37','riy-8-dordbucaqlilar',3,2,'Kvadratın diaqonalları onu neçə konqruyent üçbucağa bölür?','İki diaqonal dörd bərabər üçbucaq yaradır.',array['4 üçbucaq','2 üçbucaq','6 üçbucaq','8 üçbucaq'],1),
('riy8-dordbucaqlilar#38','riy-8-dordbucaqlilar',2,2,'Trapesiyanın orta xətti oturacaqlara nəzərən necə yerləşir?','Orta xətt oturacaqlara paraleldir.',array['Onlara paraleldir','Perpendikulyar','Bucaq altında','Kəsişir'],1),
('riy8-dordbucaqlilar#39','riy-8-dordbucaqlilar',1,2,'Dördbucaqlıların hansında bütün tərəflər və bütün bucaqlar bərabərdir?','Bu xassələri kvadrat birləşdirir.',array['Kvadratda','Rombda','Düzbucaqlıda','Trapesiyada'],1),
('riy8-dordbucaqlilar#40','riy-8-dordbucaqlilar',2,2,'Rombun perimetri 88-dirsə, tərəfi neçədir?','88 : 4 = 22.',array['22','44','11','84'],1),
('riy8-rasional-ifade#1','riy-8-rasional-ifade',2,2,'Rasional kəsrin məxrəci hansı qiyməti ala bilməz?','Məxrəc sıfır ola bilməz.',array['Sıfır','Bir','Mənfi ədəd','Kəsr'],1),
('riy8-rasional-ifade#2','riy-8-rasional-ifade',2,2,'x/(x − 3) ifadəsi x-in hansı qiymətində mənasızdır?','x = 3 olduqda məxrəc sıfırdır.',array['x = 3','x = 0','x = −3','Həmişə mənalıdır'],1),
('riy8-rasional-ifade#3','riy-8-rasional-ifade',3,2,'Qüvvətin qüvvəti qaydası ilə (a²)³ neçə olar?','Qüvvətin qüvvəti: üstlər vurulur — a⁶.',array['a⁶','a⁵','a⁸','a⁹'],1),
('riy8-rasional-ifade#4','riy-8-rasional-ifade',2,2,'6x² : (2x) ifadəsini sadələşdirin.','6 : 2 = 3; x² : x = x — nəticə 3x.',array['3x','3x²','4x','12x'],1),
('riy8-rasional-ifade#5','riy-8-rasional-ifade',3,2,'1/a + 1/b cəmi nəyə bərabərdir?','Ortaq məxrəc ab: (a + b)/(ab).',array['(a + b)/(ab)','2/(a + b)','1/(a + b)','(a·b)/(a+b)'],1),
('riy8-rasional-ifade#6','riy-8-rasional-ifade',2,2,'Kəsri ixtisar etmək nə deməkdir?','Surət və məxrəci eyni ifadəyə bölmək.',array['Surət və məxrəci eyni ifadəyə bölmək','Kəsri silmək','Məxrəci atmaq','Kəsri çevirmək'],1),
('riy8-rasional-ifade#7','riy-8-rasional-ifade',3,2,'x² − 4 kəsri x − 2 ifadəsinə bölünsə nə alınar? (x ≠ 2)','x² − 4 = (x − 2)(x + 2); nəticə x + 2.',array['x + 2','x − 2','x + 4','x² − 2'],1),
('riy8-rasional-ifade#8','riy-8-rasional-ifade',2,2,'a⁰ nəyə bərabərdir? (a ≠ 0)','Sıfırıncı qüvvət 1-ə bərabərdir.',array['1','0','a','−1'],1),
('riy8-rasional-ifade#9','riy-8-rasional-ifade',3,2,'Mənfi qüvvət qaydasına görə a⁻¹ necə yazılır?','Mənfi birinci qüvvət tərs ədəddir: 1/a.',array['1/a','−a','a','0'],1),
('riy8-rasional-ifade#10','riy-8-rasional-ifade',3,2,'(2x)³ neçə olar?','2³ · x³ = 8x³.',array['8x³','6x³','2x³','8x'],1),
('riy8-rasional-ifade#11','riy-8-rasional-ifade',2,2,'a⁴ · a³ hasili neçə olar?','Eyni əsaslı qüvvətlər vurulanda üstlər toplanır: a⁷.',array['a⁷','a¹²','a¹','2a⁷'],1),
('riy8-rasional-ifade#12','riy-8-rasional-ifade',2,2,'a⁸ : a² bölməsinin nəticəsi hansı qüvvətdir?','Bölmədə üstlər çıxılır: a⁶.',array['a⁶','a⁴','a¹⁰','a¹⁶'],1),
('riy8-rasional-ifade#13','riy-8-rasional-ifade',2,2,'3x ifadəsinin kvadratı neçədir?','(3x)² = 9x².',array['9x²','3x²','6x²','9x'],1),
('riy8-rasional-ifade#14','riy-8-rasional-ifade',3,2,'10x⁵ kəsri 5x²-yə bölündükdə nə alınar?','10 : 5 = 2, x⁵ : x² = x³ — nəticə 2x³.',array['2x³','5x³','2x⁷','15x³'],1),
('riy8-rasional-ifade#15','riy-8-rasional-ifade',2,2,'5/(x + 7) kəsrinin məxrəcini sıfır edən qiymət hansıdır?','x + 7 = 0, yəni x = −7.',array['x = −7','x = 7','x = 5','x = 0'],1),
('riy8-rasional-ifade#16','riy-8-rasional-ifade',3,2,'Fərqin kvadratı (a − b)² necə açılır?','Fərqin kvadratı: a² − 2ab + b².',array['a² − 2ab + b²','a² + b²','a² − b²','a² + 2ab − b²'],1),
('riy8-rasional-ifade#17','riy-8-rasional-ifade',3,2,'(a + b)(a − b) hasili nəyə bərabərdir?','Kvadratlar fərqi: a² − b².',array['a² − b²','a² + b²','(a + b)²','2a − 2b'],1),
('riy8-rasional-ifade#18','riy-8-rasional-ifade',3,2,'x² − 25 ifadəsini vuruqlara ayırıb (x + 5)-ə bölsək nə alınar?','x² − 25 = (x + 5)(x − 5); nəticə x − 5.',array['x − 5','x + 5','x − 25','5 − x'],1),
('riy8-rasional-ifade#19','riy-8-rasional-ifade',2,2,'Kəsrin surətini və məxrəcini eyni sıfırdan fərqli ifadəyə vursaq kəsr necə dəyişər?','Kəsrin qiyməti dəyişməz — əsas xassə.',array['Dəyişməz','İki dəfə artar','Sıfır olar','Tərsinə çevrilər'],1),
('riy8-rasional-ifade#20','riy-8-rasional-ifade',2,2,'2/x + 3/x cəmini hesablayın.','Məxrəclər eynidir: (2 + 3)/x = 5/x.',array['5/x','6/x','5/2x','6/x²'],1),
('riy8-rasional-ifade#21','riy-8-rasional-ifade',2,2,'b⁵ · b⁵ hasili hansı qüvvətdir?','Üstlər toplanır: b¹⁰.',array['b¹⁰','b²⁵','2b⁵','b⁵'],1),
('riy8-rasional-ifade#22','riy-8-rasional-ifade',3,2,'(3a²)³ qüvvətini açın.','3³ = 27; (a²)³ = a⁶.',array['27a⁶','9a⁶','27a⁵','3a⁶'],1),
('riy8-rasional-ifade#23','riy-8-rasional-ifade',2,2,'x⁻³ mənfi qüvvəti necə yazılır?','x⁻³ = 1/x³.',array['1/x³','−x³','x³','3/x'],1),
('riy8-rasional-ifade#24','riy-8-rasional-ifade',2,2,'4/y − 1/y fərqini hesablayın.','(4 − 1)/y = 3/y.',array['3/y','5/y','3','4/y²'],1),
('riy8-rasional-ifade#25','riy-8-rasional-ifade',2,2,'(x + 3)/(x + 3) kəsri x ≠ −3 üçün nəyə bərabərdir?','Bərabər ifadələrin nisbəti 1-dir.',array['1-ə bərabərdir','0-a bərabərdir','x-ə bərabərdir','3-ə bərabərdir'],1),
('riy8-rasional-ifade#26','riy-8-rasional-ifade',3,2,'8a³b : (4ab) qismətini sadələşdirin.','8:4 = 2; a³:a = a²; b:b = 1.',array['2a²','2a²b','4a²','2a³'],1),
('riy8-rasional-ifade#27','riy-8-rasional-ifade',2,2,'Kəsr nə vaxt sıfra bərabərdir?','Surət 0, məxrəc 0 deyil.',array['Surət sıfır, məxrəc yox','Məxrəc sıfır olanda','Hər ikisi sıfır olanda','Heç vaxt'],1),
('riy8-rasional-ifade#28','riy-8-rasional-ifade',2,2,'7/(x − 2) kəsri hansı x-də mənasızdır?','Məxrəc sıfır olanda: x = 2.',array['x = 2-də','x = 7-də','x = −2-də','x = 0-da'],1),
('riy8-rasional-ifade#29','riy-8-rasional-ifade',3,2,'x²/x⁵ ifadəsini mənfi qüvvətlə yazın.','x² : x⁵ = x⁻³.',array['x⁻³','x³','x⁻⁷','x⁷'],1),
('riy8-rasional-ifade#30','riy-8-rasional-ifade',3,2,'(x² − 9)/(x + 3) kəsrini ixtisar edin.','x² − 9 = (x−3)(x+3); ixtisar: x − 3.',array['x − 3','x + 3','x − 9','x + 9'],1),
('riy8-rasional-ifade#31','riy-8-rasional-ifade',2,2,'Cəbri kəsrləri toplamaq üçün nə tapılır?','Əvvəlcə ortaq məxrəc tapılır.',array['Ortaq məxrəc','Ortaq surət','Diskriminant','Modul'],1),
('riy8-rasional-ifade#32','riy-8-rasional-ifade',2,2,'Mənfi qüvvəti hesablayın: 2⁻² hansı kəsrə bərabərdir?','2⁻² = 1/2² = 1/4.',array['1/4','−4','4','−1/4'],1),
('riy8-rasional-ifade#33','riy-8-rasional-ifade',2,2,'a⁵ : a⁵ qisməti neçədir?','a⁰ = 1.',array['1 (a⁰)','a','0','a¹⁰'],1),
('riy8-rasional-ifade#34','riy-8-rasional-ifade',3,2,'(2x/5) · (10/x) hasilini sadələşdirin.','2 · 10 / 5 = 4; x-lər ixtisar olunur.',array['4-ə bərabərdir','2x-ə bərabərdir','20-yə bərabərdir','4/x-ə bərabərdir'],1),
('riy8-rasional-ifade#35','riy-8-rasional-ifade',2,2,'Kəsrin surət və məxrəcinin işarəsini eyni anda dəyişmək olarmı?','Kəsr dəyişməz: −a/−b = a/b.',array['Bəli, olar','Xeyr, olmaz','Yalnız surətin','Yalnız məxrəcin'],1),
('riy8-rasional-ifade#36','riy-8-rasional-ifade',1,2,'x/2 + x/2 cəmi nəyə bərabərdir?','2x/2 = x.',array['x-ə','x²-yə','x/4-ə','2x-ə'],1),
('riy8-rasional-ifade#37','riy-8-rasional-ifade',2,2,'Qüvvətlərin qisməti qaydası hansıdır?','aᵐ : aⁿ = aᵐ⁻ⁿ.',array['Üstlər çıxılır','Üstlər toplanır','Üstlər vurulur','Üstlər bölünür'],1),
('riy8-rasional-ifade#38','riy-8-rasional-ifade',2,2,'(a/b)² kvadratı necə açılır?','Surət və məxrəc kvadrata yüksəlir.',array['a²/b²','a²/b','a/b²','2a/2b'],1),
('riy8-rasional-ifade#39','riy-8-rasional-ifade',2,2,'5x⁰ ifadəsinin qiyməti neçədir (x ≠ 0)?','x⁰ = 1; 5 · 1 = 5.',array['5-dir','0-dır','1-dir','50-dir'],1),
('riy8-rasional-ifade#40','riy-8-rasional-ifade',3,2,'Mürəkkəb kəsri sadələşdirərkən nə edilir?','Kəsrə bölmə tərsinə vurma ilə əvəzlənir.',array['Bölmə vurmaya çevrilir','Kəsr silinir','Məxrəclər toplanır','Surətlər çıxılır'],1),
('riy8-sahe#1','riy-8-sahe',3,3,'Rombun diaqonalları 14 və 4 olarsa, sahəsi neçədir?','S = (14 · 4) : 2 = 28.',array['28','56','18','112'],1),
('riy8-sahe#2','riy-8-sahe',2,3,'Tərəfi 9 sm olan kvadratın sahəsi neçədir?','S = 9² = 81 sm².',array['81 sm²','36 sm²','18 sm²','27 sm²'],1),
('riy8-sahe#3','riy-8-sahe',2,3,'Üçbucağın sahə düsturu hansıdır?','S = (oturacaq · hündürlük) : 2.',array['S = (a · h) : 2','S = a · h','S = a + h','S = 2(a + h)'],1),
('riy8-sahe#4','riy-8-sahe',2,3,'Paraleloqramın oturacağı 7, hündürlüyü 8 olarsa, sahəsi neçədir?','S = 7 · 8 = 56.',array['56','28','15','30'],1),
('riy8-sahe#5','riy-8-sahe',3,3,'Oturacaqları 5 və 9, hündürlüyü 6 olan trapesiyanın sahəsini tapın.','S = (5 + 9) : 2 · 6 = 42.',array['42','84','20','70'],1),
('riy8-sahe#6','riy-8-sahe',2,3,'Katetləri 10 və 7 olan düzbucaqlı üçbucağın sahəsi neçədir?','S = (10 · 7) : 2 = 35.',array['35','70','17','34'],1),
('riy8-sahe#7','riy-8-sahe',3,3,'Çevrənin uzunluğu hansı düsturla tapılır?','C = 2πr.',array['C = 2πr','C = πr²','C = 4πr','C = r²'],1),
('riy8-sahe#8','riy-8-sahe',3,3,'Dairənin sahəsi hansı düsturla hesablanır?','S = πr².',array['S = πr²','S = 2πr','S = πd','S = r³'],1),
('riy8-sahe#9','riy-8-sahe',3,3,'Radiusu 10 olan dairənin sahəsi neçə π-dir?','S = π · 10² = 100π.',array['100π','20π','10π','1000π'],1),
('riy8-sahe#10','riy-8-sahe',2,3,'Fiqur iki hissəyə bölünərsə, sahəsi necə tapılır?','Hissələrin sahələrinin cəmi kimi.',array['Hissələrin sahələri cəmi kimi','Hissələrin fərqi kimi','Böyük hissəyə görə','Tapılmır'],1),
('riy8-sahe#11','riy-8-sahe',2,3,'Tərəfləri 8 və 12 olan düzbucaqlının sahəsi neçədir?','S = 8 · 12 = 96.',array['96','40','20','48'],1),
('riy8-sahe#12','riy-8-sahe',3,3,'Radiusu 6 olan çevrənin uzunluğu neçə π-dir?','C = 2π · 6 = 12π.',array['12π','36π','6π','3π'],1),
('riy8-sahe#13','riy-8-sahe',2,3,'Oturacağı 12, hündürlüyü 9 olan üçbucağın sahəsini hesablayın.','S = (12 · 9) : 2 = 54.',array['54','108','21','42'],1),
('riy8-sahe#14','riy-8-sahe',3,3,'Diaqonalları 10 və 12 olan rombun sahəsi neçədir?','S = (10 · 12) : 2 = 60.',array['60','120','22','44'],1),
('riy8-sahe#15','riy-8-sahe',2,3,'Sahəsi 121 sm² olan kvadratın tərəfinin uzunluğunu tapın.','a² = 121, a = 11 sm.',array['11 sm','22 sm','60,5 sm','121 sm'],1),
('riy8-sahe#16','riy-8-sahe',3,3,'Dairənin radiusu 5 vahiddirsə, sahəsi π ilə necə ifadə olunur?','S = π · 5² = 25π.',array['25π','10π','5π','125π'],1),
('riy8-sahe#17','riy-8-sahe',2,3,'Paraleloqramın sahə düsturu hansıdır?','S = oturacaq · hündürlük.',array['S = a · h','S = (a · h) : 2','S = a + h','S = 4a'],1),
('riy8-sahe#18','riy-8-sahe',3,3,'Trapesiyanın sahəsi hansı düsturla hesablanır?','Oturacaqların cəminin yarısı hündürlüyə vurulur.',array['S = (a + b) : 2 · h','S = a · b · h','S = 2(a + b)','S = a² + b²'],1),
('riy8-sahe#19','riy-8-sahe',3,3,'Kvadratın perimetri 40-dırsa, sahəsi neçədir?','Tərəf 40 : 4 = 10; S = 100.',array['100','80','1600','40'],1),
('riy8-sahe#20','riy-8-sahe',2,3,'Eni 4 m, uzunluğu 15 m olan otağın sahəsi neçə kvadratmetrdir?','S = 4 · 15 = 60 m².',array['60 m²','19 m²','38 m²','120 m²'],1),
('riy8-sahe#21','riy-8-sahe',1,3,'Düzbucaqlının sahəsini tapın: tərəflər 11 və 6.','S = 11 · 6 = 66.',array['66','34','17','72'],1),
('riy8-sahe#22','riy-8-sahe',2,3,'Dairənin radiusu 3-dürsə, sahəsi π ilə neçədir?','S = πr² = 9π.',array['9π','6π','3π','12π'],1),
('riy8-sahe#23','riy-8-sahe',2,3,'Diametri 20 olan çevrənin uzunluğu neçə π-dir?','C = πd = 20π.',array['20π','10π','40π','100π'],1),
('riy8-sahe#24','riy-8-sahe',2,3,'Paraleloqram: oturacaq 15, hündürlük 6. Sahəsini tapın.','S = 15 · 6 = 90.',array['90','45','21','180'],1),
('riy8-sahe#25','riy-8-sahe',3,3,'Kvadratın sahəsi 144-dürsə, perimetri neçədir?','Tərəf 12; P = 48.',array['48','36','144','24'],1),
('riy8-sahe#26','riy-8-sahe',3,3,'Üçbucağın sahəsi 93, hündürlüyü 6-dırsa, oturacağı neçədir?','a = 2S : h = 186 : 6 = 31.',array['31','15,5','62','99'],1),
('riy8-sahe#27','riy-8-sahe',3,3,'Rombun sahəsi 66, bir diaqonalı 6-dırsa, o biri diaqonalı tapın.','d₂ = 2S : d₁ = 132 : 6 = 22.',array['22','11','60','132'],1),
('riy8-sahe#28','riy-8-sahe',2,3,'Mürəkkəb fiqurun sahəsi necə tapılır?','Fiqur hissələrə bölünüb sahələr toplanır.',array['Hissələrin sahələri toplanır','Perimetrlər toplanır','Ən böyük hissə götürülür','Tapılmır'],1),
('riy8-sahe#29','riy-8-sahe',1,3,'π ədədinin təqribi qiyməti neçədir?','π ≈ 3,14.',array['3,14','3,41','2,14','3,04'],1),
('riy8-sahe#30','riy-8-sahe',3,3,'Trapesiyanın sahəsini hesablayın: oturacaqlar 7 və 13, hündürlük 4.','S = (7 + 13) : 2 · 4 = 40.',array['40','80','20','364'],1),
('riy8-sahe#31','riy-8-sahe',2,3,'Dairə sektoru 90°-lik olarsa, dairənin sahəsinin hansı hissəsidir?','90/360 = 1/4.',array['Dörddə biri','Yarısı','Üçdə biri','Səkkizdə biri'],1),
('riy8-sahe#32','riy-8-sahe',3,3,'10 000 sm² hansı sahə vahidinə bərabərdir?','100 sm = 1 m; 10 000 sm² = 1 m².',array['1 m²','10 m²','100 m²','0,1 m²'],1),
('riy8-sahe#33','riy-8-sahe',3,3,'Çevrənin uzunluğu 31,4-dürsə, radiusu təqribən neçədir?','r = C : (2π) ≈ 31,4 : 6,28 = 5.',array['Təqribən 5','Təqribən 10','Təqribən 3,14','Təqribən 15,7'],1),
('riy8-sahe#34','riy-8-sahe',2,3,'Sahəni tapın: düzbucaqlı üçbucağın katetləri 9 və 6-dır.','S = 9 · 6 : 2 = 27.',array['27','54','15','13,5'],1),
('riy8-sahe#35','riy-8-sahe',1,3,'Sahə vahidi olmayan hansıdır: m², sm², litr, hektar?','Litr həcm vahididir.',array['Litr','Hektar','m²','sm²'],1),
('riy8-sahe#36','riy-8-sahe',2,3,'Divar 6 m × 3 m-dir, pəncərə 2 m²-dir. Rənglənəcək sahə neçədir?','18 − 2 = 16.',array['16 m²','18 m²','20 m²','9 m²'],1),
('riy8-sahe#37','riy-8-sahe',3,3,'İki konqruyent düzbucaqlı üçbucaqdan hansı fiqur yığmaq olar?','Hipotenuzlar birləşdirilərsə düzbucaqlı alınır.',array['Düzbucaqlı','Beşbucaqlı','Dairə','Trapesiya yalnız'],1),
('riy8-sahe#38','riy-8-sahe',2,3,'Dairənin sahəsi 49π-dirsə, radiusu neçədir?','r² = 49, r = 7.',array['Radius 7-dir','Radius 49-dur','Radius 14-dür','Radius 24,5-dir'],1),
('riy8-sahe#39','riy-8-sahe',3,3,'Kvadrat və düzbucaqlının sahələri bərabərdirsə, perimetrləri də bərabərdirmi?','Sahə bərabərliyi perimetr bərabərliyi demək deyil.',array['Mütləq deyil','Həmişə bərabərdir','Heç vaxt','Yalnız kiçiklərdə'],1),
('riy8-sahe#40','riy-8-sahe',1,3,'Çevrənin uzunluğu düsturunda 2πr-də r nəyi bildirir?','r — çevrənin radiusudur.',array['Radiusu','Diametri','Sahəni','Perimetri'],1),
('riy8-rasional-tenlik#1','riy-8-rasional-tenlik',2,3,'Rasional tənlik hansı tənlikdir?','Rasional ifadələrdən ibarət tənlikdir.',array['Rasional ifadələrdən ibarət tənlik','Yalnız kvadrat tənlik','Köklü tənlik','Bərabərsizlik'],1),
('riy8-rasional-tenlik#2','riy-8-rasional-tenlik',3,3,'x/(x − 1) = 0 tənliyinin kökü neçədir?','Kəsr sıfırdır — surət sıfır olmalıdır: x = 0.',array['0','1','−1','Kökü yoxdur'],1),
('riy8-rasional-tenlik#3','riy-8-rasional-tenlik',3,3,'Rasional tənliyi həll edərkən nəyi yoxlamaq vacibdir?','Məxrəci sıfır edən qiymətlər kök ola bilməz.',array['Məxrəci sıfır edən qiymətləri','Surəti','Tənliyin uzunluğunu','Heç nəyi'],1),
('riy8-rasional-tenlik#4','riy-8-rasional-tenlik',2,3,'12/x = 4 tənliyinin kökü neçədir?','x = 12 : 4 = 3.',array['3','48','8','4'],1),
('riy8-rasional-tenlik#5','riy-8-rasional-tenlik',2,3,'(x + 2)/5 = 2 tənliyini həll edin.','x + 2 = 10; x = 8.',array['8','12','0','10'],1),
('riy8-rasional-tenlik#6','riy-8-rasional-tenlik',2,3,'1/x = 1/9 tənliyinin kökü neçədir?','Kəsrlər bərabərdirsə, məxrəclər bərabərdir: x = 9.',array['9','1/9','−9','3'],1),
('riy8-rasional-tenlik#7','riy-8-rasional-tenlik',3,3,'Kənar kök nədir?','Çevirmələr zamanı alınan, lakin tənliyi ödəməyən kökdür.',array['Tənliyi ödəməyən alınmış kök','Ən böyük kök','Mənfi kök','İlk tapılan kök'],1),
('riy8-rasional-tenlik#8','riy-8-rasional-tenlik',3,3,'x/2 + x/3 = 5 tənliyinin kökü neçədir?','Ortaq məxrəc 6: 3x + 2x = 30; x = 6.',array['6','5','30','12'],1),
('riy8-rasional-tenlik#9','riy-8-rasional-tenlik',3,3,'20/x = x/5 tənliyinin müsbət kökü neçədir?','x² = 100; müsbət kök 10.',array['10','100','4','25'],1),
('riy8-rasional-tenlik#10','riy-8-rasional-tenlik',3,3,'Tənliyin iki tərəfini məxrəcə vuranda nə nəzərə alınmalıdır?','Məxrəcin sıfırdan fərqli olması.',array['Məxrəcin sıfır olmaması','Surətin böyüklüyü','Kökün işarəsi','Heç nə'],1),
('riy8-rasional-tenlik#11','riy-8-rasional-tenlik',2,3,'42/x = 2 tənliyində x neçəyə bərabərdir?','x = 42 : 2 = 21.',array['21','84','40','44'],1),
('riy8-rasional-tenlik#12','riy-8-rasional-tenlik',2,3,'x-in dörddə biri 9-a bərabərdirsə, x neçədir?','x/4 = 9; x = 36.',array['36','13','5','2,25'],1),
('riy8-rasional-tenlik#13','riy-8-rasional-tenlik',2,3,'(x − 4)/3 = 9 tənliyinin kökü neçədir?','x − 4 = 27; x = 31.',array['31','23','27','39'],1),
('riy8-rasional-tenlik#14','riy-8-rasional-tenlik',3,3,'1/x = 0,04 bərabərliyində x-i tapın.','x = 1 : 0,04 = 25.',array['25','0,04','4','40'],1),
('riy8-rasional-tenlik#15','riy-8-rasional-tenlik',3,3,'x/7 = 28/x tənliyinin müsbət kökü neçədir?','x² = 196; müsbət kök 14.',array['14','196','4','35'],1),
('riy8-rasional-tenlik#16','riy-8-rasional-tenlik',3,3,'10/(x − 18) = 2 tənliyinin kökü neçədir?','x − 18 = 5; x = 23.',array['23','13','28','20'],1),
('riy8-rasional-tenlik#17','riy-8-rasional-tenlik',3,3,'1/(x − 6) = 4 tənliyində hansı qiymət kök ola bilməz?','x = 6 məxrəci sıfır edir.',array['x = 6','x = 4','x = 0','x = −6'],1),
('riy8-rasional-tenlik#18','riy-8-rasional-tenlik',3,3,'x/3 − x/4 = 5 tənliyinin kökü neçədir?','Ortaq məxrəc 12: 4x − 3x = 60; x = 60.',array['60','35','5','12'],1),
('riy8-rasional-tenlik#19','riy-8-rasional-tenlik',2,3,'x : 5 = 8 : 2 nisbətindən x-i tapın.','x = 5 · 8 : 2 = 20.',array['20','80','13','11'],1),
('riy8-rasional-tenlik#20','riy-8-rasional-tenlik',3,3,'Tənliyin hər iki tərəfini (x − 1)-ə vurduqda hansı şərt qoyulmalıdır?','x − 1 sıfır olmamalıdır: x ≠ 1.',array['x ≠ 1','x > 1','x = 1','Şərt lazım deyil'],1),
('riy8-rasional-tenlik#21','riy-8-rasional-tenlik',2,3,'36/x = 4 tənliyinin kökünü tapın.','x = 36 : 4 = 9.',array['x = 9','x = 32','x = 40','x = 144'],1),
('riy8-rasional-tenlik#22','riy-8-rasional-tenlik',3,3,'Müsbət kökü tapın: x/6 = 24/x.','x² = 144, x = 12.',array['x = 12','x = 4','x = 144','x = 6'],1),
('riy8-rasional-tenlik#23','riy-8-rasional-tenlik',2,3,'x-i tapın: 1/x = 0,2 olarsa.','x = 1 : 0,2 = 5.',array['x = 5','x = 0,2','x = 2','x = 50'],1),
('riy8-rasional-tenlik#24','riy-8-rasional-tenlik',2,3,'(x + 6)/4 = 5 tənliyini həll edin.','x + 6 = 20, x = 14.',array['x = 14','x = 26','x = 20','x = 4'],1),
('riy8-rasional-tenlik#25','riy-8-rasional-tenlik',3,3,'x/4 − x/6 = 2 tənliyinin kökünü tapın.','(3x − 2x)/12 = 2, x = 24.',array['x = 24','x = 12','x = 2','x = 48'],1),
('riy8-rasional-tenlik#26','riy-8-rasional-tenlik',2,3,'15/(x + 1) = 3 tənliyinin kökü neçədir?','x + 1 = 5, x = 4.',array['x = 4','x = 5','x = 14','x = −1'],1),
('riy8-rasional-tenlik#27','riy-8-rasional-tenlik',2,3,'Tənlikdə məxrəcdə dəyişən varsa, həllin sonunda nə yoxlanılır?','Tapılan kök məxrəci sıfır etməməlidir.',array['Məxrəcin sıfır olmaması','Surətin böyüklüyü','İşarələrin sayı','Qrafikin rəngi'],1),
('riy8-rasional-tenlik#28','riy-8-rasional-tenlik',2,3,'Kökü tapın: x/(x + 5) = 0.','Surət sıfır olmalıdır: x = 0.',array['x = 0','x = −5','x = 5','Kökü yoxdur'],1),
('riy8-rasional-tenlik#29','riy-8-rasional-tenlik',3,3,'Tənasüb kimi həll edin: 50/x = x/2, x > 0.','x² = 100, x = 10.',array['x = 10','x = 25','x = 100','x = 5'],1),
('riy8-rasional-tenlik#30','riy-8-rasional-tenlik',2,3,'x-i nisbətdən çıxarın: x : 3 = 20 : 4.','x = 3 · 20 : 4 = 15.',array['x = 15','x = 5','x = 60','x = 12'],1),
('riy8-rasional-tenlik#31','riy-8-rasional-tenlik',2,3,'Orta sürət: 120 km yol 2 saatdadırsa, sürət düsturu necə yazılır?','Sürət yolun vaxta nisbətidir.',array['v = 120/2','v = 2/120','v = 120 · 2','v = 120 − 2'],1),
('riy8-rasional-tenlik#32','riy-8-rasional-tenlik',2,3,'(2x − 1)/3 = 5 tənliyinin kökü neçədir?','2x − 1 = 15, x = 8.',array['x = 8','x = 7','x = 16','x = 3'],1),
('riy8-rasional-tenlik#33','riy-8-rasional-tenlik',3,3,'Hansı əməl kənar kök yarada bilər?','Hər iki tərəfi məxrəcə vurmaq kənar kök verə bilər.',array['Məxrəcə vurma','Toplama','Çıxma','Sadələşdirmə'],1),
('riy8-rasional-tenlik#34','riy-8-rasional-tenlik',3,3,'1/x + 1/(2x) = 1/4 tənliyinin kökü neçədir?','3/(2x) = 1/4, 2x = 12, x = 6.',array['x = 6','x = 3','x = 12','x = 8'],1),
('riy8-rasional-tenlik#35','riy-8-rasional-tenlik',1,3,'a/b = c/d bərabərliyi necə adlanır?','İki nisbətin bərabərliyi tənasübdür.',array['Tənasüb','Tənlik deyil','Bərabərsizlik','Eynilik'],1),
('riy8-rasional-tenlik#36','riy-8-rasional-tenlik',2,3,'9/x = 3/7 tənliyinin kökünü tapın.','x = 9 · 7 : 3 = 21.',array['x = 21','x = 3','x = 7','x = 63'],1),
('riy8-rasional-tenlik#37','riy-8-rasional-tenlik',2,3,'x/8 = 0 tənliyinin kökü neçədir?','Surət sıfır olmalıdır.',array['Sıfırdır','Səkkizdir','Kökü yoxdur','İstənilən ədəd'],1),
('riy8-rasional-tenlik#38','riy-8-rasional-tenlik',3,3,'Hərəkət məsələləri çox vaxt hansı tip tənliyə gətirilir?','Vaxt = yol/sürət kəsrləri rasional tənlik qurur.',array['Rasional tənliklərə','Kvadrat kök tənliklərinə','Bərabərsizliklərə','Sistemsiz həllərə'],1),
('riy8-rasional-tenlik#39','riy-8-rasional-tenlik',3,3,'(x − 2)/(x − 2) = 1 bərabərliyi hansı x üçün doğru deyil?','x = 2-də kəsr mənasızdır.',array['x = 2 üçün','x = 1 üçün','x = 0 üçün','Həmişə doğrudur'],1),
('riy8-rasional-tenlik#40','riy-8-rasional-tenlik',2,3,'5/x = 30/42 tənliyinin kökünü tapın.','x = 5 · 42 : 30 = 7.',array['x = 7','x = 5','x = 35','x = 6'],1),
('riy8-oxsarliq#1','riy-8-oxsarliq',2,3,'Oxşar fiqurlar necə fiqurlardır?','Formaca eyni, ölçüləri mütənasib fiqurlardır.',array['Formaca eyni, ölçücə mütənasib','Tamamilə eyni','Sahəcə bərabər','Həmişə konqruyent'],1),
('riy8-oxsarliq#2','riy-8-oxsarliq',3,3,'Oxşarlıq əmsalı nədir?','Uyğun tərəflərin nisbətidir.',array['Uyğun tərəflərin nisbəti','Bucaqların cəmi','Sahələrin fərqi','Perimetrlərin hasili'],1),
('riy8-oxsarliq#3','riy-8-oxsarliq',2,3,'Oxşar üçbucaqların uyğun bucaqları necədir?','Uyğun bucaqlar bərabərdir.',array['Bərabərdir','Mütənasibdir','Fərqlidir','Cəmi 90°-dir'],1),
('riy8-oxsarliq#4','riy-8-oxsarliq',3,3,'Oxşarlıq əmsalı 3 olarsa, sahələrin nisbəti neçədir?','Sahələr k² kimi nisbətdədir: 9.',array['9','3','6','27'],1),
('riy8-oxsarliq#5','riy-8-oxsarliq',3,3,'Üçbucaqların oxşarlıq əlamətlərindən biri hansıdır?','İki bucağa görə oxşarlıq.',array['İki bucağa görə','Perimetrə görə','Sahəyə görə','Rəngə görə'],1),
('riy8-oxsarliq#6','riy-8-oxsarliq',3,3,'Xəritə oxşarlığın hansı tətbiqidir?','Ərazinin kiçildilmiş oxşar təsviridir.',array['Ərazinin kiçildilmiş oxşarı','Böyüdülmüş şəkil','Təsadüfi çertyoj','Oxşarlıqla bağlı deyil'],1),
('riy8-oxsarliq#7','riy-8-oxsarliq',3,3,'Tərəfləri 2 dəfə böyüdülən kvadratın sahəsi neçə dəfə artar?','Sahə k² dəfə artır: 4 dəfə.',array['4','2','8','16'],1),
('riy8-oxsarliq#8','riy-8-oxsarliq',3,3,'Oxşar üçbucaqlarda perimetrlərin nisbəti nəyə bərabərdir?','Oxşarlıq əmsalına bərabərdir.',array['Oxşarlıq əmsalına','Əmsalın kvadratına','Həmişə 1-ə','Sahələr nisbətinə'],1),
('riy8-oxsarliq#9','riy-8-oxsarliq',3,3,'△ABC ~ △DEF və AB/DE = 1/2 olarsa, hansı üçbucaq böyükdür?','AB tərəfi DE-nin yarısıdır — DEF böyükdür.',array['DEF','ABC','Bərabərdirlər','Bilmək olmaz'],1),
('riy8-oxsarliq#10','riy-8-oxsarliq',2,3,'Gündəlik həyatda oxşar fiqurlara misal hansıdır?','Fotonun müxtəlif ölçülü çapları oxşar fiqurlardır.',array['Fotonun böyüdülmüş çapı','İki fərqli formalı daş','Kvadrat və dairə','Hərflər'],1),
('riy8-oxsarliq#11','riy-8-oxsarliq',3,3,'İki oxşar fiqurda əmsal k = 5-dirsə, sahələr hansı nisbətdədir?','Sahələr k² nisbətindədir: 25 : 1.',array['25 : 1','5 : 1','10 : 1','125 : 1'],1),
('riy8-oxsarliq#12','riy-8-oxsarliq',3,3,'Üç tərəfə görə oxşarlıq əlaməti nəyi tələb edir?','Uyğun tərəflərin mütənasib olmasını.',array['Uyğun tərəflərin mütənasibliyini','Bucaqların cəmini','Sahələrin bərabərliyini','Perimetrlərin bərabərliyini'],1),
('riy8-oxsarliq#13','riy-8-oxsarliq',3,3,'k = 3 və kiçik üçbucağın perimetri 12-dirsə, böyük üçbucağın perimetri neçədir?','Perimetr əmsala mütənasibdir: 12 · 3 = 36.',array['36','15','108','4'],1),
('riy8-oxsarliq#14','riy-8-oxsarliq',3,3,'Xəritədə 1 : 1000000 miqyası nəyi göstərir?','Xəritədəki 1 sm yerdə 10 km-ə uyğundur.',array['1 sm-in 10 km-ə uyğun olduğunu','1 sm-in 1 m-ə uyğun olduğunu','Xəritənin köhnə olduğunu','Ərazinin sahəsini'],1),
('riy8-oxsarliq#15','riy-8-oxsarliq',2,3,'Oxşar fiqurların uyğun tərəfləri 4 : 7 nisbətindədirsə, oxşarlıq əmsalı neçədir?','Əmsal tərəflərin nisbətidir: 4/7.',array['4/7','7/4','28','3/7'],1),
('riy8-oxsarliq#16','riy-8-oxsarliq',2,3,'İki kvadrat həmişə oxşardırmı?','Bəli — bütün kvadratlar formaca eynidir.',array['Bəli','Xeyr','Yalnız bərabərdirsə','Yalnız kiçikdirsə'],1),
('riy8-oxsarliq#17','riy-8-oxsarliq',3,3,'Bucaqları 90°, 60° və 30° olan bütün üçbucaqlar bir-birinə necədir?','Bucaqları eyni olan üçbucaqlar oxşardır.',array['Oxşardır','Bərabərdir','Perpendikulyardır','Paraleldir'],1),
('riy8-oxsarliq#18','riy-8-oxsarliq',3,3,'Oxşarlıq əmsalı 1 olan fiqurlar necə adlanır?','k = 1 olduqda fiqurlar bərabərdir (konqruyentdir).',array['Bərabər (konqruyent) fiqurlar','Simmetrik fiqurlar','Perpendikulyar fiqurlar','Qeyri-oxşar fiqurlar'],1),
('riy8-oxsarliq#19','riy-8-oxsarliq',3,3,'Kölgə üsulu ilə hündürlük ölçmək nəyə əsaslanır?','Cisim və kölgəsinin yaratdığı üçbucaqların oxşarlığına.',array['Üçbucaqların oxşarlığına','Pifaqor teoreminə','Çevrənin uzunluğuna','Simmetriyaya'],1),
('riy8-oxsarliq#20','riy-8-oxsarliq',3,3,'AB = 6, KL = 18 olarsa, KLM üçbucağının ABC-yə oxşarlıq əmsalı hansıdır?','k = 18 : 6 = 3.',array['k = 3','k = 12','k = 1/2','k = 24'],1),
('riy8-oxsarliq#21','riy-8-oxsarliq',3,3,'k = 2 üçün oxşar fiqurların sahələri hansı nisbətdədir?','Sahələr k² nisbətində: 4 : 1.',array['4 : 1','2 : 1','8 : 1','16 : 1'],1),
('riy8-oxsarliq#22','riy-8-oxsarliq',2,3,'İki üçbucağın iki bucağı bərabərdirsə, üçbucaqlar haqqında nə demək olar?','İki bucaq əlaməti ilə oxşardırlar.',array['Oxşardırlar','Konqruyentdirlər','Bərabərdirlər','Heç nə demək olmaz'],1),
('riy8-oxsarliq#23','riy-8-oxsarliq',2,3,'△ABC ~ △DEF, AB = 4, DE = 12. Əmsal neçədir?','12 : 4 = 3.',array['k = 3','k = 4','k = 1/3','k = 8'],1),
('riy8-oxsarliq#24','riy-8-oxsarliq',2,3,'Oxşar üçbucaqların perimetrləri 15 və 45-dirsə, əmsal neçədir?','45 : 15 = 3.',array['3-ə bərabərdir','30-a bərabərdir','9-a bərabərdir','1/3-ə bərabərdir'],1),
('riy8-oxsarliq#25','riy-8-oxsarliq',3,3,'Planda 1 : 500 miqyasında 2 sm neçə metrə uyğundur?','2 · 500 = 1 000 sm = 10 m.',array['10 metrə','5 metrə','100 metrə','1 metrə'],1),
('riy8-oxsarliq#26','riy-8-oxsarliq',2,3,'Oxşarlıq çevrilməsində bucaqlar dəyişirmi?','Oxşarlıqda bucaqlar saxlanır.',array['Xeyr, dəyişmir','Bəli, k dəfə artır','Bəli, azalır','Yalnız düz bucaqlar dəyişir'],1),
('riy8-oxsarliq#27','riy-8-oxsarliq',2,3,'Bütün bərabərtərəfli üçbucaqlar bir-birinə oxşardırmı?','Bucaqları həmişə 60°-dir — oxşardırlar.',array['Bəli, oxşardır','Xeyr, deyil','Yalnız kiçiklər','Yalnız bərabər olanlar'],1),
('riy8-oxsarliq#28','riy-8-oxsarliq',2,3,'k əmsallı oxşarlıqda uzunluqlar necə dəyişir?','Bütün uzunluqlar k dəfə dəyişir.',array['k dəfə','k² dəfə','2k dəfə','Dəyişmir'],1),
('riy8-oxsarliq#29','riy-8-oxsarliq',3,3,'Sahələri 9 : 25 nisbətində olan oxşar fiqurların tərəfləri hansı nisbətdədir?','Tərəflər √9 : √25 = 3 : 5.',array['3 : 5','9 : 25','81 : 625','1 : 3'],1),
('riy8-oxsarliq#30','riy-8-oxsarliq',2,3,'Fotoşəkilin böyüdülməsi hansı çevrilmədir?','Forma saxlanır, ölçü dəyişir — oxşarlıqdır.',array['Oxşarlıq çevrilməsi','Konqruyentlik','Simmetriya','Döndərmə'],1),
('riy8-oxsarliq#31','riy-8-oxsarliq',2,3,'△ABC ~ △MNK yazılışında ∠C-yə hansı bucaq uyğundur?','Üçüncü hərflər uyğundur: K.',array['∠K','∠M','∠N','∠A'],1),
('riy8-oxsarliq#32','riy-8-oxsarliq',3,3,'1 m-lik payanın kölgəsi 2 m, ağacın kölgəsi 12 m-dir. Ağacın hündürlüyü neçədir?','Nisbət 1 : 2 — hündürlük 12 : 2 = 6 m.',array['6 metr','24 metr','12 metr','3 metr'],1),
('riy8-oxsarliq#33','riy-8-oxsarliq',3,3,'Oxşar üçbucaqlarda uyğun medianlar hansı nisbətdədir?','Bütün xətti elementlər k nisbətindədir.',array['Əmsal nisbətində','k² nisbətində','Bərabərdir','İxtiyari'],1),
('riy8-oxsarliq#34','riy-8-oxsarliq',2,3,'k = 1/2 olarsa, ikinci fiqur birinciyə görə necədir?','Ölçülər yarıya enir.',array['İki dəfə kiçikdir','İki dəfə böyükdür','Bərabərdir','Dörd dəfə böyükdür'],1),
('riy8-oxsarliq#35','riy-8-oxsarliq',3,3,'Oxşarlıq və konqruyentlik arasında əlaqə nədir?','k = 1 olduqda oxşarlıq konqruyentlikdir.',array['Konqruyentlik k = 1 oxşarlıqdır','Əlaqə yoxdur','Oxşarlıq həmişə konqruyentlikdir','Əksinədir'],1),
('riy8-oxsarliq#36','riy-8-oxsarliq',2,3,'Perimetri 20 olan üçbucaq k = 4 ilə böyüdülsə, yeni perimetr neçə olar?','20 · 4 = 80.',array['80 olar','24 olar','320 olar','5 olar'],1),
('riy8-oxsarliq#37','riy-8-oxsarliq',3,3,'Xəritədə 1 sm = 2 km-dirsə, miqyas hansıdır?','2 km = 200 000 sm.',array['1 : 200 000','1 : 2 000','1 : 20 000','1 : 2 000 000'],1),
('riy8-oxsarliq#38','riy-8-oxsarliq',1,3,'Oxşar fiqurların formaları haqqında nə demək olar?','Forma eyni, ölçü fərqli ola bilər.',array['Eynidir','Fərqlidir','Həmişə kvadratdır','Yoxdur'],1),
('riy8-oxsarliq#39','riy-8-oxsarliq',3,3,'Üçbucağın orta xətlərindən yaranan üçbucaq əsl üçbucağa hansı əmsalla oxşardır?','Orta xətlər yarı ölçülüdür: k = 1/2.',array['k = 1/2','k = 2','k = 1/4','k = 1'],1),
('riy8-oxsarliq#40','riy-8-oxsarliq',3,3,'Sahəsi 4 dəfə artan kvadratın tərəfi neçə dəfə artıb?','√4 = 2 dəfə.',array['2 dəfə','4 dəfə','8 dəfə','16 dəfə'],1),
('riy8-berabersizlik#1','riy-8-berabersizlik',2,4,'x + 5 > 9 bərabərsizliyinin həlli hansıdır?','x > 9 − 5 = 4.',array['x > 4','x < 4','x > 14','x = 4'],1),
('riy8-berabersizlik#2','riy-8-berabersizlik',3,4,'Bərabərsizliyin iki tərəfi mənfi ədədə vurulanda nə baş verir?','Bərabərsizlik işarəsi əksinə dəyişir.',array['İşarə əksinə dəyişir','İşarə dəyişmir','Bərabərlik alınır','Həll itir'],1),
('riy8-berabersizlik#3','riy-8-berabersizlik',2,4,'2x < 10 bərabərsizliyini həll edin.','x < 10 : 2 = 5.',array['x < 5','x > 5','x < 20','x = 5'],1),
('riy8-berabersizlik#4','riy-8-berabersizlik',3,4,'−3x > 12 bərabərsizliyinin həlli hansıdır?','Mənfiyə bölərkən işarə dəyişir: x < −4.',array['x < −4','x > −4','x < 4','x > 4'],1),
('riy8-berabersizlik#5','riy-8-berabersizlik',3,4,'x ≥ 2 həlləri ədəd oxunda necə göstərilir?','2 nöqtəsi daxil olmaqla sağa yönəlmiş şüa.',array['2-dən sağa şüa (2 daxil)','2-dən sola şüa','Yalnız 2 nöqtəsi','Bütün ox'],1),
('riy8-berabersizlik#6','riy-8-berabersizlik',2,4,'1 < x < 7 bərabərsizliyini ödəyən ən böyük tam ədəd neçədir?','7-dən kiçik ən böyük tam ədəd 6-dır.',array['6','7','5','1'],1),
('riy8-berabersizlik#7','riy-8-berabersizlik',2,4,'a > b və b > c olarsa, a ilə c arasında hansı münasibət var?','Tranzitivlik: a > c.',array['a > c','a < c','a = c','Münasibət yoxdur'],1),
('riy8-berabersizlik#8','riy-8-berabersizlik',2,4,'x − 7 ≤ 0 bərabərsizliyinin həlli hansıdır?','x ≤ 7.',array['x ≤ 7','x ≥ 7','x < 0','x = 7'],1),
('riy8-berabersizlik#9','riy-8-berabersizlik',2,4,'Bərabərsizliyin iki tərəfinə eyni ədəd əlavə edəndə işarə dəyişirmi?','Xeyr — toplama işarəni dəyişmir.',array['Xeyr, dəyişmir','Bəli, həmişə dəyişir','Yalnız mənfidə dəyişir','Bərabərlik olur'],1),
('riy8-berabersizlik#10','riy-8-berabersizlik',3,4,'5 − x > 1 bərabərsizliyini həll edin.','−x > −4; işarə dəyişir: x < 4.',array['x < 4','x > 4','x < −4','x > 6'],1),
('riy8-berabersizlik#11','riy-8-berabersizlik',2,4,'4x ≥ 20 bərabərsizliyinin həlli hansıdır?','x ≥ 20 : 4 = 5.',array['x ≥ 5','x ≤ 5','x ≥ 16','x = 5'],1),
('riy8-berabersizlik#12','riy-8-berabersizlik',2,4,'x + 3 < 1 bərabərsizliyini ödəyən x-lər hansılardır?','x < 1 − 3 = −2.',array['x < −2','x > −2','x < 4','x < 2'],1),
('riy8-berabersizlik#13','riy-8-berabersizlik',3,4,'−5 ≤ x ≤ 10 aralığında neçə tam ədəd var?','−5-dən 10-a qədər: 16 tam ədəd.',array['16','15','10','5'],1),
('riy8-berabersizlik#14','riy-8-berabersizlik',2,4,'2 < x < 6 bərabərsizliyini ödəyən tam ədədlər hansılardır?','Aralıqdakı tamlar: 3, 4 və 5.',array['3, 4 və 5','2, 3, 4, 5 və 6','3 və 4','4 və 5'],1),
('riy8-berabersizlik#15','riy-8-berabersizlik',2,4,'x² ≥ 0 bərabərsizliyi hansı x-lər üçün doğrudur?','İstənilən həqiqi ədədin kvadratı mənfi deyil.',array['Bütün həqiqi ədədlər üçün','Yalnız müsbətlər üçün','Yalnız mənfilər üçün','Heç bir x üçün'],1),
('riy8-berabersizlik#16','riy-8-berabersizlik',3,4,'6 − 2x ≤ 0 bərabərsizliyinin həlli hansıdır?','−2x ≤ −6; mənfiyə bölərkən işarə dəyişir: x ≥ 3.',array['x ≥ 3','x ≤ 3','x ≥ −3','x ≤ −3'],1),
('riy8-berabersizlik#17','riy-8-berabersizlik',2,4,'Bərabərsizliyin hər iki tərəfini müsbət ədədə böləndə işarə necə olur?','Müsbətə bölmə işarəni dəyişmir.',array['Dəyişmir','Əksinə dəyişir','Bərabərlik olur','İtir'],1),
('riy8-berabersizlik#18','riy-8-berabersizlik',2,4,'a < b olarsa, a + 10 ilə b + 10 arasında hansı münasibət olar?','Hər iki tərəfə eyni ədəd əlavə etmək işarəni saxlayır.',array['a + 10 < b + 10','a + 10 > b + 10','a + 10 = b + 10','Müqayisə etmək olmaz'],1),
('riy8-berabersizlik#19','riy-8-berabersizlik',2,4,'x/3 > 2 bərabərsizliyinin həlli hansıdır?','x > 2 · 3 = 6.',array['x > 6','x < 6','x > 2/3','x = 6'],1),
('riy8-berabersizlik#20','riy-8-berabersizlik',2,4,'Ədəd oxunda x < 0 bərabərsizliyi hansı hissəni göstərir?','Sıfırdan solda qalan bütün nöqtələri.',array['Sıfırdan solda qalan hissəni','Sıfırdan sağda qalan hissəni','Yalnız sıfırı','Bütün oxu'],1),
('riy8-berabersizlik#21','riy-8-berabersizlik',2,4,'x − 4 > 6 bərabərsizliyinin həlli hansıdır?','x > 6 + 4 = 10.',array['x > 10','x < 10','x > 2','x ≥ 10'],1),
('riy8-berabersizlik#22','riy-8-berabersizlik',3,4,'−2x ≤ 8 bərabərsizliyini həll edin.','Mənfiyə bölərkən işarə çevrilir: x ≥ −4.',array['x ≥ −4','x ≤ −4','x ≥ 4','x ≤ 4'],1),
('riy8-berabersizlik#23','riy-8-berabersizlik',2,4,'Bərabərsizliyin tərəflərini mənfi ədədə böləndə nə edilməlidir?','İşarə əks tərəfə çevrilməlidir.',array['İşarə əksinə çevrilir','İşarə saxlanılır','Tərəflər silinir','Bərabərlik yazılır'],1),
('riy8-berabersizlik#24','riy-8-berabersizlik',3,4,'3 ≤ x < 8 aralığını ödəyən tam ədədləri sadalayın.','3 daxildir, 8 daxil deyil.',array['3, 4, 5, 6, 7','4, 5, 6, 7','3, 4, 5, 6, 7, 8','4, 5, 6, 7, 8'],1),
('riy8-berabersizlik#25','riy-8-berabersizlik',3,4,'5x − 3 > 2x + 9 bərabərsizliyini həll edin.','3x > 12, x > 4.',array['x > 4','x < 4','x > 12','x > 3'],1),
('riy8-berabersizlik#26','riy-8-berabersizlik',3,4,'İkiqat bərabərsizlik −1 < x ≤ 2 aralıq şəklində necə yazılır?','Sol uc açıq, sağ uc qapalıdır.',array['(−1; 2] aralığı ilə','[−1; 2] aralığı ilə','(−1; 2) aralığı ilə','[−1; 2) aralığı ilə'],1),
('riy8-berabersizlik#27','riy-8-berabersizlik',3,4,'a < b olarsa −a ilə −b arasında hansı münasibət var?','Mənfiyə vuranda işarə çevrilir: −a > −b.',array['−a > −b','−a < −b','−a = −b','Müəyyən olunmur'],1),
('riy8-berabersizlik#28','riy-8-berabersizlik',2,4,'Beşə bölmə: x/5 ≤ 1 olduqda x-lər hansı çoxluqdur?','x ≤ 5.',array['x ≤ 5','x ≥ 5','x < 5','x ≤ 1/5'],1),
('riy8-berabersizlik#29','riy-8-berabersizlik',2,4,'Bərabərsizliklər sistemi x > 2 və x < 7 birlikdə nəyi verir?','Ortaq hissə: 2 < x < 7.',array['2 < x < 7','x > 7','x < 2','Həll yoxdur'],1),
('riy8-berabersizlik#30','riy-8-berabersizlik',3,4,'0 · x > 5 bərabərsizliyinin həlli varmı?','Sol tərəf həmişə 0-dır, 5-dən böyük ola bilməz.',array['Xeyr, yoxdur','Bəli, sonsuz','x = 5','x > 0'],1),
('riy8-berabersizlik#31','riy-8-berabersizlik',3,4,'7 − 3x ≥ 1 bərabərsizliyini həll edin.','−3x ≥ −6, x ≤ 2.',array['x ≤ 2','x ≥ 2','x ≤ −2','x ≥ 6'],1),
('riy8-berabersizlik#32','riy-8-berabersizlik',2,4,'x² < 0 bərabərsizliyinin neçə həlli var?','Kvadrat mənfi ola bilməz.',array['Heç bir həlli yoxdur','Bir həlli var','İki həlli var','Sonsuz həlli var'],1),
('riy8-berabersizlik#33','riy-8-berabersizlik',2,4,'Ən azı 12 bal toplamaq şərti hansı bərabərsizliklə yazılır?','«Ən azı» — böyük və ya bərabər deməkdir.',array['x ≥ 12','x > 12','x ≤ 12','x = 12'],1),
('riy8-berabersizlik#34','riy-8-berabersizlik',2,4,'2(x − 3) < 10 bərabərsizliyini həll edin.','x − 3 < 5, x < 8.',array['x < 8','x > 8','x < 5','x < 2'],1),
('riy8-berabersizlik#35','riy-8-berabersizlik',1,4,'a > 0 və b > 0 olarsa hasil a·b haqqında nə demək olar?','Müsbətlərin hasili müsbətdir.',array['Müsbətdir','Mənfidir','Sıfırdır','Müəyyən olunmur'],1),
('riy8-berabersizlik#36','riy-8-berabersizlik',2,4,'x < 4 və x < 9 şərtlərini birlikdə ödəyən çoxluq hansıdır?','Daha dar şərt x < 4-dür.',array['x < 4 çoxluğu','x < 9 çoxluğu','4 < x < 9','Boş çoxluq'],1),
('riy8-berabersizlik#37','riy-8-berabersizlik',1,4,'Ciddi olmayan bərabərsizlik işarələri hansılardır?','Bərabərliyə icazə verən işarələr: ≤ və ≥.',array['≤ və ≥','< və >','= və ≠','+ və −'],1),
('riy8-berabersizlik#38','riy-8-berabersizlik',3,4,'4 − x ≥ 4 bərabərsizliyinin həlli hansıdır?','−x ≥ 0, x ≤ 0.',array['x ≤ 0','x ≥ 0','x ≤ 4','x ≥ 4'],1),
('riy8-berabersizlik#39','riy-8-berabersizlik',2,4,'«3 ədədi x-dən kiçikdir» fikri necə yazılır?','3 < x, yəni x > 3.',array['x > 3','x < 3','x ≥ 3','x = 3'],1),
('riy8-berabersizlik#40','riy-8-berabersizlik',3,4,'İki müsbət ədəddən böyüyünün tərs ədədi (1/a) necə olur?','Ədəd böyüdükcə tərsi kiçilir.',array['Daha kiçik olur','Daha böyük olur','Bərabər olur','Mənfi olur'],1),
('riy8-triqonometrik#1','riy-8-triqonometrik',3,4,'Düzbucaqlı üçbucaqda bucağın sinusu nəyin nisbətidir?','Qarşı katetin hipotenuza nisbətidir.',array['Qarşı katetin hipotenuza','Bitişik katetin hipotenuza','Hipotenuzun katetə','Katetlərin bir-birinə'],1),
('riy8-triqonometrik#2','riy-8-triqonometrik',3,4,'Kosinus hansı nisbətdir?','Bitişik katetin hipotenuza nisbətidir.',array['Bitişik katetin hipotenuza','Qarşı katetin hipotenuza','Hipotenuzun katetə','Bucağın tərəfə'],1),
('riy8-triqonometrik#3','riy-8-triqonometrik',3,4,'Tangens nəyə bərabərdir?','Qarşı katetin bitişik katetə nisbətinə.',array['Qarşı katetin bitişik katetə nisbətinə','Katetin hipotenuza nisbətinə','Hipotenuzun yarısına','Bucaqların cəminə'],1),
('riy8-triqonometrik#4','riy-8-triqonometrik',3,4,'sin 30° neçəyə bərabərdir?','sin 30° = 1/2.',array['1/2','√3/2','1','√2/2'],1),
('riy8-triqonometrik#5','riy-8-triqonometrik',3,4,'cos 60° neçəyə bərabərdir?','cos 60° = 1/2.',array['1/2','√3/2','0','2'],1),
('riy8-triqonometrik#6','riy-8-triqonometrik',3,4,'tan 45° neçəyə bərabərdir?','45°-də katetlər bərabərdir: tan 45° = 1.',array['1','1/2','√2','0'],1),
('riy8-triqonometrik#7','riy-8-triqonometrik',3,4,'1 − sin²α ifadəsi nəyə bərabərdir?','Əsas eynilikdən: 1 − sin²α = cos²α.',array['cos²α','sin²α','tan²α','0'],1),
('riy8-triqonometrik#8','riy-8-triqonometrik',3,4,'Koordinat başlanğıcından A(6; 8) nöqtəsinə qədər məsafə neçədir?','√(36 + 64) = √100 = 10.',array['10','14','48','100'],1),
('riy8-triqonometrik#9','riy-8-triqonometrik',3,4,'Paralel köçürmə zamanı fiqurun nəyi dəyişmir?','Forması və ölçüləri dəyişmir, yalnız yeri dəyişir.',array['Forması və ölçüləri','Yeri','Hər şeyi dəyişir','Yalnız rəngi'],1),
('riy8-triqonometrik#10','riy-8-triqonometrik',3,4,'Ox simmetriyasında (inikasda) fiqur necə alınır?','Fiqurun güzgü əksi alınır, ölçülər saxlanır.',array['Güzgü əksi alınır','Fiqur böyüyür','Fiqur kiçilir','Fiqur itir'],1),
('riy8-triqonometrik#11','riy-8-triqonometrik',3,4,'30 dərəcəli bucağın kosinusu hansı qiymətə malikdir?','cos 30° = √3/2.',array['√3/2','1/2','√2/2','2'],1),
('riy8-triqonometrik#12','riy-8-triqonometrik',3,4,'sin 45° hansı qiymətə bərabərdir?','sin 45° = √2/2.',array['√2/2','√3/2','1/3','2/√3'],1),
('riy8-triqonometrik#13','riy-8-triqonometrik',3,4,'Əsas triqonometrik eynilik hansıdır?','sin²α + cos²α = 1.',array['sin²α + cos²α = 1','sin α + cos α = 1','sin²α − cos²α = 1','sin α · cos α = 1'],1),
('riy8-triqonometrik#14','riy-8-triqonometrik',3,4,'tan α sinus və kosinus vasitəsilə necə ifadə olunur?','tan α = sin α / cos α.',array['sin α / cos α','cos α / sin α','sin α · cos α','1 / sin α'],1),
('riy8-triqonometrik#15','riy-8-triqonometrik',2,4,'M(9; 23) nöqtəsinin ordinatı neçədir?','İkinci koordinat ordinatdır: 23.',array['23','9','32','14'],1),
('riy8-triqonometrik#16','riy-8-triqonometrik',2,4,'Koordinat müstəvisində oxların kəsişdiyi nöqtə necə adlanır?','Bu, koordinat başlanğıcıdır: O(0; 0).',array['Koordinat başlanğıcı','Absis','Ordinat','Vahid nöqtə'],1),
('riy8-triqonometrik#17','riy-8-triqonometrik',3,4,'Mərkəzi simmetriyada fiqur nəyə nəzərən əks olunur?','Bir nöqtəyə (simmetriya mərkəzinə) nəzərən.',array['Nöqtəyə nəzərən','Düz xəttə nəzərən','Müstəviyə nəzərən','Çevrəyə nəzərən'],1),
('riy8-triqonometrik#18','riy-8-triqonometrik',3,4,'Döndərmə zamanı fiqurun hansı xassəsi saxlanır?','Ölçülər dəyişmir — fiqur konqruyent qalır.',array['Ölçüləri (fiqur konqruyent qalır)','Vəziyyəti','Bucaqları böyüyür','Tərəfləri qısalır'],1),
('riy8-triqonometrik#19','riy-8-triqonometrik',3,4,'B(0; 7) nöqtəsi koordinat müstəvisində harada yerləşir?','Absisi sıfırdır — ordinat oxunun üzərindədir.',array['Ordinat oxunun üzərində','Absis oxunun üzərində','Başlanğıcda','III rübdə'],1),
('riy8-triqonometrik#20','riy-8-triqonometrik',3,4,'Başlanğıcdan C(20; 21) nöqtəsinə qədər məsafəni hesablayın.','√(400 + 441) = √841 = 29.',array['29','41','441','20'],1),
('riy8-triqonometrik#21','riy-8-triqonometrik',2,4,'sin 60° neçəyə bərabərdir?','sin 60° = √3/2.',array['√3/2','1/2','√2/2','1'],1),
('riy8-triqonometrik#22','riy-8-triqonometrik',3,4,'cos 30° ilə sin 60° arasında hansı münasibət var?','Hər ikisi √3/2-dir.',array['Bərabərdirlər (√3/2)','Fərqlidirlər','Cəmi 1-dir','Hasilləri 0-dır'],1),
('riy8-triqonometrik#23','riy-8-triqonometrik',3,4,'tan 30° neçəyə bərabərdir?','tan 30° = 1/√3 = √3/3.',array['√3/3','√3','1/2','1'],1),
('riy8-triqonometrik#24','riy-8-triqonometrik',3,4,'Bucağın sinusu 3/5-dirsə və bucaq itidirsə, kosinusu neçədir?','cos = √(1 − 9/25) = 4/5.',array['4/5','3/5','2/5','5/4'],1),
('riy8-triqonometrik#25','riy-8-triqonometrik',2,4,'sin²α + cos²α cəmi neçəyə bərabərdir?','Əsas eynilik: cəm 1-dir.',array['1-ə bərabərdir','0-a bərabərdir','2-yə bərabərdir','α-dan asılıdır'],1),
('riy8-triqonometrik#26','riy-8-triqonometrik',2,4,'Katet 6, hipotenuz 10 olan üçbucaqda qarşı bucağın sinusu neçədir?','sin = 6/10 = 0,6.',array['0,6','0,8','6','1,67'],1),
('riy8-triqonometrik#27','riy-8-triqonometrik',2,4,'cos 90° neçəyə bərabərdir?','cos 90° = 0.',array['Sıfra bərabərdir','Birə bərabərdir','√2/2-yə bərabərdir','Təyin olunmayıb'],1),
('riy8-triqonometrik#28','riy-8-triqonometrik',2,4,'Fırlanma (döndərmə) hansı nöqtə ətrafında aparılır?','Döndərmə mərkəz ətrafında olur.',array['Mərkəz nöqtəsi ətrafında','İxtiyari xətt üzrə','Kənar nöqtədə','Oxların kəsişməsində deyil'],1),
('riy8-triqonometrik#29','riy-8-triqonometrik',2,4,'A(5; 0) nöqtəsində ordinat sıfırdır. Nöqtə hansı oxdadır?','Ordinatı sıfır olan nöqtələr absis oxundadır.',array['Absis oxunda','Ordinat oxunda','III rübdə','Başlanğıcda'],1),
('riy8-triqonometrik#30','riy-8-triqonometrik',3,4,'sin α = cos α olan iti bucaq hansıdır?','45°-də sinus və kosinus bərabərdir.',array['45° bucağı','30° bucağı','60° bucağı','90° bucağı'],1),
('riy8-triqonometrik#31','riy-8-triqonometrik',3,4,'tan 60° neçəyə bərabərdir?','tan 60° = √3.',array['√3','√3/3','1','1/2'],1),
('riy8-triqonometrik#32','riy-8-triqonometrik',2,4,'Paralel köçürmədə fiqurun bütün nöqtələri necə hərəkət edir?','Hamısı eyni istiqamətdə, eyni məsafəyə.',array['Eyni istiqamətdə, eyni qədər','Fərqli istiqamətlərdə','Mərkəzə doğru','Hərəkət etmir'],1),
('riy8-triqonometrik#33','riy-8-triqonometrik',2,4,'Simmetriya mərkəzi olan fiqura misal göstərin.','Dairənin mərkəzi simmetriya mərkəzidir.',array['Dairə','İxtiyari üçbucaq','Trapesiya','Beşbucaqlı'],1),
('riy8-triqonometrik#34','riy-8-triqonometrik',3,4,'Kotangens tangenslə hansı münasibətdədir?','cot α = 1/tan α.',array['Qarşılıqlı tərsdir','Bərabərdir','Cəmi 1-dir','Fərqi 1-dir'],1),
('riy8-triqonometrik#35','riy-8-triqonometrik',3,4,'cos α = 12/13 və α itidirsə, sin α neçədir?','sin = √(1 − 144/169) = 5/13.',array['5/13','12/13','13/12','7/13'],1),
('riy8-triqonometrik#36','riy-8-triqonometrik',3,4,'Hündürlük 30 m, kölgə 30 m olarsa, günəş şüasının düşmə bucağı neçədir?','tan = 1 — bucaq 45°.',array['45 dərəcə','30 dərəcə','60 dərəcə','90 dərəcə'],1),
('riy8-triqonometrik#37','riy-8-triqonometrik',1,4,'M(−4; 3) yazılışında birinci ədəd hansı koordinatdır?','Birinci ədəd absisdir.',array['Absisdir (−4)','Ordinatdır (−4)','Absisdir (3)','Modul (4)'],1),
('riy8-triqonometrik#38','riy-8-triqonometrik',2,4,'Katetlər 7 və 7-dirsə, bucağın tangensi neçədir?','tan = 7/7 = 1.',array['tan = 1','tan = 7','tan = 0','tan = 49'],1),
('riy8-triqonometrik#39','riy-8-triqonometrik',3,4,'Döndərmə 180° olduqda hansı çevrilmə alınır?','180° döndərmə mərkəzi simmetriyadır.',array['Mərkəzi simmetriya','Ox simmetriyası','Paralel köçürmə','Oxşarlıq'],1),
('riy8-triqonometrik#40','riy-8-triqonometrik',2,4,'sin 90° neçəyə bərabərdir?','sin 90° = 1.',array['Vahidə bərabərdir','Sıfra bərabərdir','√2/2-yə bərabərdir','İkiyə bərabərdir'],1),
('riy8-ehtimal#1','riy-8-ehtimal',2,4,'Zər atılanda 6 düşməsi ehtimalı neçədir?','Altı üzdən biri: 1/6.',array['1/6','1/2','6','1/3'],1),
('riy8-ehtimal#2','riy-8-ehtimal',3,4,'Kartlar 1-dən 10-a qədər nömrələnib. Təsadüfi kartın 10-a bölünən olması ehtimalı neçədir?','Yalnız 10 uyğundur: 1/10.',array['1/10','1/5','10','1/2'],1),
('riy8-ehtimal#3','riy-8-ehtimal',3,4,'Qutuda 3 ağ və 7 qara kürə var. Ağ kürə çıxarma ehtimalı neçədir?','3/10.',array['3/10','7/10','3/7','1/3'],1),
('riy8-ehtimal#4','riy-8-ehtimal',3,4,'Statistik sıranın amplitudu nədir?','Ən böyük qiymətlə ən kiçiyin fərqidir.',array['Ən böyüklə ən kiçiyin fərqi','Qiymətlərin cəmi','Orta qiymət','Ən çox təkrarlanan'],1),
('riy8-ehtimal#5','riy-8-ehtimal',3,4,'7, 2, 9, 4 sırasının amplitudu neçədir?','9 − 2 = 7.',array['7','9','2','22'],1),
('riy8-ehtimal#6','riy-8-ehtimal',3,4,'Nisbi tezlik necə tapılır?','Hadisənin baş vermə sayı bütün təcrübələrin sayına bölünür.',array['Hadisə sayı təcrübə sayına bölünür','Təcrübə sayı vurulur','Cəm alınır','Fərq alınır'],1),
('riy8-ehtimal#7','riy-8-ehtimal',3,4,'Zərdə 3-ə bölünən ədəd düşməsi ehtimalı neçədir?','Uyğun hallar: 3 və 6 — 2/6 = 1/3.',array['1/3','1/2','1/6','2/3'],1),
('riy8-ehtimal#8','riy-8-ehtimal',3,4,'100 lotereya biletindən 5-i uduşludur. Uduş ehtimalı neçədir?','5/100 = 1/20.',array['1/20','1/5','5','1/100'],1),
('riy8-ehtimal#9','riy-8-ehtimal',3,4,'Bütün mümkün nəticələrin ehtimallarının cəmi nəyə bərabərdir?','Cəm həmişə vahidə (1-ə) bərabərdir.',array['Vahidə (1-ə)','Sıfıra','Yüzə','Nəticədən asılıdır'],1),
('riy8-ehtimal#10','riy-8-ehtimal',2,4,'İki zər atılanda düşən ədədlərin cəmi ən çoxu neçə ola bilər?','6 + 6 = 12.',array['12','6','36','11'],1),
('riy8-ehtimal#11','riy-8-ehtimal',2,4,'Mümkün olmayan hadisənin ehtimalı neçədir?','Baş verə bilməyən hadisənin ehtimalı sıfırdır.',array['0','1','1/2','−1'],1),
('riy8-ehtimal#12','riy-8-ehtimal',2,4,'Yəqin (hökmən baş verən) hadisənin ehtimalı neçədir?','Yəqin hadisənin ehtimalı vahiddir.',array['1 (vahid)','0','1/2','100'],1),
('riy8-ehtimal#13','riy-8-ehtimal',2,4,'Sikkə atılanda gerb düşməsi ehtimalı neçədir?','İki üzdən biri: 0,5.',array['0,5','0,25','1','2'],1),
('riy8-ehtimal#14','riy-8-ehtimal',3,4,'Zər atılanda 5-dən böyük ədəd düşməsi ehtimalı neçədir?','Yalnız 6 uyğundur: 1/6.',array['1/6','5/6','1/5','1/2'],1),
('riy8-ehtimal#15','riy-8-ehtimal',3,4,'Qutuda 4 qırmızı və 6 mavi kürə var. Mavi kürə çıxarma ehtimalı neçədir?','6/10 = 3/5.',array['3/5','2/5','6/4','1/6'],1),
('riy8-ehtimal#16','riy-8-ehtimal',3,4,'10, 20, 26, 30, 44 sırasının medianı neçədir?','Sıralanmış beş ədədin ortadakısı: 26.',array['26','20','30','44'],1),
('riy8-ehtimal#17','riy-8-ehtimal',2,4,'15, 25, 45 və 55 ədədlərinin ədədi ortası neçədir?','(15 + 25 + 45 + 55) : 4 = 140 : 4 = 35.',array['35','45','140','25'],1),
('riy8-ehtimal#18','riy-8-ehtimal',2,4,'Statistik məlumatın modası nədir?','Ən çox təkrarlanan qiymətdir.',array['Ən çox təkrarlanan qiymət','Ən böyük qiymət','Orta qiymət','İlk qiymət'],1),
('riy8-ehtimal#19','riy-8-ehtimal',3,4,'İki sikkə atılanda hər ikisinin gerb düşməsi ehtimalı neçədir?','1/2 · 1/2 = 1/4.',array['1/4','1/2','1/3','2/4'],1),
('riy8-ehtimal#20','riy-8-ehtimal',3,4,'1-dən 30-a qədər nömrələnmiş biletlərdən 7-yə bölünən nömrə çıxma ehtimalı neçədir?','Uyğun nömrələr: 7, 14, 21, 28 — 4/30 = 2/15.',array['2/15','7/30','1/7','4/7'],1),
('riy8-ehtimal#21','riy-8-ehtimal',2,4,'Zər atılanda tək ədəd düşməsi ehtimalı neçədir?','Təklər: 1, 3, 5 — 3/6 = 1/2.',array['3/6 = 1/2','1/6','2/6','4/6'],1),
('riy8-ehtimal#22','riy-8-ehtimal',2,4,'Torbada 7 qoz və 3 fındıq var. Fındıq çıxarma ehtimalı neçədir?','3/10.',array['3/10','7/10','3/7','1/3'],1),
('riy8-ehtimal#23','riy-8-ehtimal',2,4,'52 kartlıq dəstdən ürək çıxma ehtimalı neçədir (13 ürək)?','13/52 = 1/4.',array['13/52 = 1/4','1/52','13/39','1/13'],1),
('riy8-ehtimal#24','riy-8-ehtimal',3,4,'6, 9, 9, 12, 14 sırasının modası və medianı hansı cütdür?','Moda 9 (təkrarlanır), median ortadakı 9-dur.',array['Moda 9, median 9','Moda 9, median 12','Moda 12, median 9','Moda 6, median 14'],1),
('riy8-ehtimal#25','riy-8-ehtimal',2,4,'40, 50, 96 ədədlərinin ədədi ortası neçədir?','186 : 3 = 62.',array['62','60','64','186'],1),
('riy8-ehtimal#26','riy-8-ehtimal',2,4,'Ehtimal 0,15-dirsə, əks hadisənin ehtimalı neçədir?','1 − 0,15 = 0,85.',array['0,85','0,15','0,5','1,15'],1),
('riy8-ehtimal#27','riy-8-ehtimal',3,4,'Üç atışın hamısında gerb: ehtimalı hesablayın.','(1/2)³ = 1/8.',array['1/8','1/2','1/4','3/8'],1),
('riy8-ehtimal#28','riy-8-ehtimal',2,4,'Sıranın ən böyük üzvü 40, ən kiçiyi 8-dirsə, amplitudu neçədir?','40 − 8 = 32.',array['32','48','40','8'],1),
('riy8-ehtimal#29','riy-8-ehtimal',2,4,'Tezlik cədvəli nəyi göstərir?','Hər qiymətin neçə dəfə rast gəlindiyini.',array['Qiymətlərin təkrar sayını','Rəngləri','Cədvəlin ölçüsünü','Sıranın adını'],1),
('riy8-ehtimal#30','riy-8-ehtimal',3,4,'1-dən 20-yə qədər nömrələnmiş kartlardan 4-ə bölünən çıxma ehtimalı neçədir?','4, 8, 12, 16, 20 — 5 kart: 5/20 = 1/4.',array['5/20 = 1/4','4/20','1/20','6/20'],1),
('riy8-ehtimal#31','riy-8-ehtimal',1,4,'Ehtimalın qiyməti hansı aralıqdadır?','Ehtimal 0-dan 1-ə qədərdir.',array['0 ilə 1 arasında','−1 ilə 1 arasında','0 ilə 100 arasında','İstənilən qiymət'],1),
('riy8-ehtimal#32','riy-8-ehtimal',3,4,'Cüt sayda üzvü olan sıranın medianı necə tapılır?','Ortadakı iki qiymətin ortası götürülür.',array['Ortadakı ikisinin ortası ilə','Ən böyük qiymətlə','İlk qiymətlə','Moda ilə'],1),
('riy8-ehtimal#33','riy-8-ehtimal',3,4,'İki zərin cəminin 2 olması ehtimalı neçədir?','Yalnız 1+1: 1/36.',array['1/36','2/36','1/12','1/6'],1),
('riy8-ehtimal#34','riy-8-ehtimal',2,4,'60 şagirddən 24-ü qızdır. Təsadüfi seçimin qız olması ehtimalı neçədir?','24/60 = 2/5.',array['2/5','3/5','24/36','1/24'],1),
('riy8-ehtimal#35','riy-8-ehtimal',3,4,'Böyük say qanunu: atış sayı artdıqca nisbi tezlik nəyə yaxınlaşır?','Tezlik ehtimala yaxınlaşır.',array['Ehtimala','Sıfıra','Modaya','Amplituda'],1),
('riy8-ehtimal#36','riy-8-ehtimal',3,4,'Uyuşmayan hadisələr nədir?','Eyni sınaqda birgə baş verə bilməyənlər.',array['Eyni anda baş verməyənlər','Həmişə birgə baş verənlər','Ehtimalı bərabər olanlar','Mümkünsüz hadisələr'],1),
('riy8-ehtimal#37','riy-8-ehtimal',3,4,'5, 5, 6, 7, 7 sırasında neçə moda var?','Həm 5, həm 7 iki dəfə təkrarlanır.',array['İki moda','Bir moda','Moda yoxdur','Üç moda'],1),
('riy8-ehtimal#38','riy-8-ehtimal',2,4,'200 detaldan 8-i zaydır. Təsadüfi detalın zay olması ehtimalı neçədir?','8/200 = 0,04.',array['0,04','0,4','0,08','0,8'],1),
('riy8-ehtimal#39','riy-8-ehtimal',2,4,'Orta qiymət 4,5-dirsə və 10 qiymət varsa, cəm neçədir?','4,5 × 10 = 45.',array['45','4,5','14,5','450'],1),
('riy8-ehtimal#40','riy-8-ehtimal',2,4,'Proqnozun etibarlılığı nədən asılıdır?','Məlumat çox olduqca proqnoz dəqiqləşir.',array['Məlumatın həcmindən','Kağızın rəngindən','Cədvəlin enindən','Heç nədən'],1)
),
ins as (
  insert into public.questions
    (ext_key, owner_type, subject_id, level_id, topic_id, kind,
     body, explanation, difficulty, quarter, status)
  select d.ext, 'platform', s.id, l.id, tp.id, 'single',
         d.body, d.why, d.diff, d.rub, 'published'
    from d
    join public.subjects s on s.slug = 'riyaziyyat'
    join public.programs p on p.slug = 'orta'
    join public.levels   l on l.program_id = p.id and l.code = '8'
    join public.topics   tp on tp.subject_id = s.id and tp.slug = d.topic
  on conflict (ext_key) do update
    set body = excluded.body, explanation = excluded.explanation,
        difficulty = excluded.difficulty, quarter = excluded.quarter,
        topic_id = excluded.topic_id, level_id = excluded.level_id,
        subject_id = excluded.subject_id, status = 'published'
  returning id, ext_key
)
insert into public.question_options (question_id, ord, body, is_correct)
select ins.id, o.ord, o.txt, o.ord = d.correct
  from ins
  join d on d.ext = ins.ext_key,
  lateral unnest(d.opts) with ordinality as o(txt, ord);

do $$
declare n int; k int;
begin
  select count(*) into n from public.questions
   where owner_type = 'platform' and ext_key like 'riy8-%';
  if n <> 440 then
    raise exception 'riy8 suallari: 440 gozlenilirdi, % tapildi', n;
  end if;
  select count(*) into k from public.questions q
   where q.ext_key like 'riy8-%'
     and ((select count(*) from public.question_options o
            where o.question_id = q.id) <> 4
       or (select count(*) from public.question_options o
            where o.question_id = q.id and o.is_correct) <> 1);
  if k > 0 then
    raise exception '% sualda variant qurulusu sehvdir', k;
  end if;
  select count(distinct topic_id) into k from public.questions
   where ext_key like 'riy8-%';
  if k <> 11 then
    raise exception 'movzu sayi 11 deyil: %', k;
  end if;
  raise notice 'Riyaziyyat 8 banki: % sual, 11 movzu.', n;
end $$;
