-- =====================================================================
--  42_bank_riy9.sql : RIYAZIYYAT 9 PLATFORMA SUAL BANKI (orta mekteb)
--
--  BU FAYL ELLE YAZILMIR - tools/riy9.py yaradir:
--      python3 tools/riy9.py
--
--  10 movzu x 40 sual = 400.  ext_key: riy9-<movzu>#<sira>.
--  ON SERT: 41_movzular_orta9.sql islenmis olmalidir.
--  SONRA:   05_grants.sql yeniden islet.
-- =====================================================================

do $$
begin
  if not exists (
    select 1 from public.topics t
      join public.subjects s on s.id = t.subject_id
     where s.slug = 'riyaziyyat' and t.slug = 'riy-9-kok') then
    raise exception 'ONCE 41_movzular_orta9.sql isledilmelidir (riy-9-* movzulari yoxdur).';
  end if;
end $$;

delete from public.question_options o
 using public.questions q
 where o.question_id = q.id
   and q.owner_type = 'platform'
   and q.ext_key like 'riy9-%';

with d(ext, topic, diff, rub, body, why, opts, correct) as (values
('riy9-kok#1','riy-9-kok',1,1,'27 ədədinin kub kökü neçədir?','3³ = 27, deməli ∛27 = 3.',array['3','9','27','81'],1),
('riy9-kok#2','riy-9-kok',2,1,'∛64 · ∛8 hasilini hesablayın.','∛64 = 4, ∛8 = 2; 4 · 2 = 8.',array['8','6','12','72'],1),
('riy9-kok#3','riy-9-kok',1,1,'16 ədədinin dördüncü dərəcədən kökünü tapın.','2⁴ = 16, deməli ⁴√16 = 2.',array['2','4','8','16'],1),
('riy9-kok#4','riy-9-kok',2,1,'5⁻² qüvvətinin qiyməti hansı kəsrə bərabərdir?','5⁻² = 1/5² = 1/25.',array['1/25','1/10','25','10'],1),
('riy9-kok#5','riy-9-kok',2,1,'8^(2/3) qiymətini tapın.','8^(2/3) = (∛8)² = 2² = 4.',array['4','16','2','6'],1),
('riy9-kok#6','riy-9-kok',2,1,'27^(1/3) · 27^(2/3) hasilı neçədir?','Üstlər toplanır: 27^(1/3+2/3) = 27¹ = 27.',array['27','9','3','81'],1),
('riy9-kok#7','riy-9-kok',1,1,'a^(1/2) yazılışı hansı ifadəni bildirir?','Yarım üst kvadrat kökdür: a^(1/2) = √a.',array['√a','a/2','a²','2a'],1),
('riy9-kok#8','riy-9-kok',2,1,'∛5 ədədi hansı ədədlər çoxluğuna aiddir?','∛5 tam və ya kəsr şəklində yazıla bilmir - irrasionaldır.',array['İrrasional ədədlərə','Natural ədədlərə','Tam ədədlərə','Rasional ədədlərə'],1),
('riy9-kok#9','riy-9-kok',1,1,'Mənfi 7,3 ədədinin mütləq qiyməti neçədir?','Mütləq qiymət məsafədir: |−7,3| = 7,3.',array['7,3','−7,3','0','3,7'],1),
('riy9-kok#10','riy-9-kok',2,1,'Ədəd oxunda −2 ilə 5 nöqtələri arasındakı məsafə neçə vahiddir?','5 − (−2) = 7 vahid.',array['7 vahid','3 vahid','10 vahid','2 vahid'],1),
('riy9-kok#11','riy-9-kok',2,1,'Mənfi 125 ədədinin kub kökü neçədir?','(−5)³ = −125, deməli kub kök −5-dir.',array['−5','5','−25','25'],1),
('riy9-kok#12','riy-9-kok',3,1,'√(a²) ifadəsi nəyə bərabərdir?','Kvadrat kök mənfi olmur: √(a²) = |a|.',array['|a|','a','−a','a²'],1),
('riy9-kok#13','riy-9-kok',2,1,'2√3 · 5√3 hasilini tapın.','2 · 5 · (√3)² = 10 · 3 = 30.',array['30','10√3','15','90'],1),
('riy9-kok#14','riy-9-kok',2,1,'√50 ifadəsində vuruğu kök işarəsi altından çıxarın.','√50 = √(25 · 2) = 5√2.',array['5√2','2√5','25√2','10√5'],1),
('riy9-kok#15','riy-9-kok',2,1,'3√2 ifadəsini kök işarəsi altına daxil edin.','3√2 = √(9 · 2) = √18.',array['√18','√6','√12','√36'],1),
('riy9-kok#16','riy-9-kok',3,1,'√12 + √27 cəmini sadələşdirin.','2√3 + 3√3 = 5√3.',array['5√3','√39','6√3','5√6'],1),
('riy9-kok#17','riy-9-kok',1,1,'(√7)² neçəyə bərabərdir?','Kvadrat kökün kvadratı ədədin özüdür: 7.',array['7','49','√7','14'],1),
('riy9-kok#18','riy-9-kok',3,1,'16^(3/4) neçəyə bərabərdir?','16^(3/4) = (⁴√16)³ = 2³ = 8.',array['8','12','64','6'],1),
('riy9-kok#19','riy-9-kok',1,1,'10⁰ + 10¹ cəmi neçədir?','1 + 10 = 11.',array['11','10','100','0'],1),
('riy9-kok#20','riy-9-kok',3,1,'0,00042 ədədini standart şəkildə yazın.','0,00042 = 4,2 · 10⁻⁴.',array['4,2 · 10⁻⁴','4,2 · 10⁴','42 · 10⁻⁵ standart deyil, düz','0,42 · 10⁻³ standart deyil'],1),
('riy9-kok#21','riy-9-kok',2,1,'Kökün xassəsinə görə ∛a · ∛b nəyə bərabərdir?','Eyni dərəcəli köklər vurulanda ∛(ab) alınır.',array['∛(ab)','∛(a+b)','∛a + ∛b','ab'],1),
('riy9-kok#22','riy-9-kok',2,1,'√0,04 neçəyə bərabərdir?','0,2² = 0,04, deməli √0,04 = 0,2.',array['0,2','0,02','0,4','2'],1),
('riy9-kok#23','riy-9-kok',2,1,'Kökün xassəsi ilə √(9 · 49) hasilını hesablayın.','√9 · √49 = 3 · 7 = 21.',array['21','441','12','58'],1),
('riy9-kok#24','riy-9-kok',2,1,'32 ədədinin beşinci dərəcədən kökü neçədir?','2⁵ = 32, deməli ⁵√32 = 2.',array['2','4','6,4','16'],1),
('riy9-kok#25','riy-9-kok',2,1,'13^(1/2) · 13^(1/2) hasilı neçədir?','Üstlər toplanır: 13^1 = 13.',array['13','√13','169','26'],1),
('riy9-kok#26','riy-9-kok',2,1,'Ədədi çoxluqlardan hansı ən genişdir?','N ⊂ Z ⊂ Q ⊂ R - həqiqi ədədlər hamısını əhatə edir.',array['Həqiqi ədədlər çoxluğu','Natural ədədlər çoxluğu','Tam ədədlər çoxluğu','Rasional ədədlər çoxluğu'],1),
('riy9-kok#27','riy-9-kok',1,1,'−4 ədədi natural deyil, bəs hansı çoxluğa daxildir?','Mənfi tam ədədlər Z çoxluğuna daxildir.',array['Tam ədədlərə (Z)','Yalnız irrasionala','Natural ədədlərə','Heç birinə'],1),
('riy9-kok#28','riy-9-kok',2,1,'0,333... dövri kəsri hansı adi kəsrə bərabərdir?','0,(3) = 3/9 = 1/3.',array['1/3','1/30','3/10','1/9'],1),
('riy9-kok#29','riy-9-kok',2,1,'√5 ədədi hansı iki qonşu tam ədəd arasındadır?','2² = 4 < 5 < 9 = 3², deməli 2 < √5 < 3.',array['2 ilə 3 arasında','1 ilə 2 arasında','4 ilə 5 arasında','5 ilə 6 arasında'],1),
('riy9-kok#30','riy-9-kok',2,1,'(2/3)⁻¹ neçəyə bərabərdir?','Mənfi birinci qüvvət kəsri çevirir: 3/2.',array['3/2','2/3','−2/3','−3/2'],1),
('riy9-kok#31','riy-9-kok',2,1,'a⁴ · a⁻⁴ hasilı neçəyə bərabərdir (a sıfır deyil)?','a^(4−4) = a⁰ = 1.',array['1','0','a⁸','a'],1),
('riy9-kok#32','riy-9-kok',2,1,'√75 : √3 nisbətini hesablayın.','√(75 : 3) = √25 = 5.',array['5','25','√72','15'],1),
('riy9-kok#33','riy-9-kok',2,1,'Kub kökü 4 olan ədəd hansıdır?','4³ = 64.',array['64','12','16','256'],1),
('riy9-kok#34','riy-9-kok',2,1,'49^(1/2) + 4^(1/2) cəmi neçədir?','7 + 2 = 9.',array['9','53','11','5'],1),
('riy9-kok#35','riy-9-kok',2,1,'Rasional üstlü qüvvətin xassəsinə görə (a^(1/3))³ nəyə bərabərdir?','Üstlər vurulur: a^(1/3·3) = a.',array['a','a³','a^(1/9)','3a'],1),
('riy9-kok#36','riy-9-kok',2,1,'Hansı ifadənin qiyməti tam ədəddir?','∛27 = 3 tam ədəddir, qalanlar irrasionaldır.',array['∛27','√3','√8','⁴√5'],1),
('riy9-kok#37','riy-9-kok',1,1,'−(−3,8) ifadəsinin qiyməti neçədir?','Mənfinin mənfisi müsbətdir: 3,8.',array['3,8','−3,8','0','8,3'],1),
('riy9-kok#38','riy-9-kok',2,1,'1000-in kub kökü ilə 100-ün kvadrat kökünün cəmi neçədir?','10 + 10 = 20.',array['20','10','110','200'],1),
('riy9-kok#39','riy-9-kok',2,1,'π ədədini adi kəsr şəklində dəqiq yazmaq mümkündürmü?','π irrasionaldır - kəsrlə dəqiq ifadə olunmur.',array['Xeyr, mümkün deyil (irrasionaldır)','Bəli, 22/7 dəqiqdir','Bəli, 3,14 dəqiqdir','Bəli, 314/100 dəqiqdir'],1),
('riy9-kok#40','riy-9-kok',2,1,'Eyni əsaslı qüvvətlərin hasilində üstlər necə yazılır?','Əsas saxlanılır, üstlər toplanır.',array['Toplanır','Vurulur','Çıxılır','Bölünür'],1),
('riy9-cevre#1','riy-9-cevre',1,1,'Mərkəzi bucaq nəyə bərabərdir?','Mərkəzi bucaq söykəndiyi qövsün dərəcə ölçüsünə bərabərdir.',array['Söykəndiyi qövsün dərəcə ölçüsünə','Qövsün yarısına','Həmişə 90 dərəcəyə','Diametrə'],1),
('riy9-cevre#2','riy-9-cevre',2,1,'Çevrə daxilinə çəkilmiş bucaq söykəndiyi qövsün hansı hissəsinə bərabərdir?','Daxilə çəkilmiş bucaq qövsün yarısına bərabərdir.',array['Yarısına','Özünə','Dörddə birinə','İki mislinə'],1),
('riy9-cevre#3','riy-9-cevre',2,1,'Qövsün dərəcə ölçüsü 80° olarsa, ona söykənən daxilə çəkilmiş bucaq neçə dərəcədir?','80 : 2 = 40°.',array['40°','80°','160°','20°'],1),
('riy9-cevre#4','riy-9-cevre',2,1,'Diametrə söykənən daxilə çəkilmiş bucaq neçə dərəcədir?','Yarımçevrəyə söykənən bucaq düz bucaqdır - 90°.',array['90°','45°','180°','60°'],1),
('riy9-cevre#5','riy-9-cevre',1,1,'Mərkəzi bucaq 68° olarsa, uyğun qövsün dərəcə ölçüsü neçədir?','Qövs mərkəzi bucağa bərabərdir: 68°.',array['68°','34°','136°','112°'],1),
('riy9-cevre#6','riy-9-cevre',2,1,'Radiusu 6 sm olan çevrənin uzunluğunu π ilə ifadə edin.','C = 2πr = 2π · 6 = 12π sm.',array['12π sm','6π sm','36π sm','3π sm'],1),
('riy9-cevre#7','riy-9-cevre',3,1,'Radiusu 9 sm olan çevrədə 60°-lik qövsün uzunluğu neçədir?','l = (60/360) · 2π · 9 = 3π sm.',array['3π sm','9π sm','6π sm','π sm'],1),
('riy9-cevre#8','riy-9-cevre',2,1,'Toxunan toxunma nöqtəsinə çəkilmiş radiusla hansı bucaq əmələ gətirir?','Toxunan radiusa perpendikulyardır - 90°.',array['90° (perpendikulyardır)','45°','İxtiyari bucaq','0°'],1),
('riy9-cevre#9','riy-9-cevre',1,1,'Vətər nədir?','Çevrənin iki nöqtəsini birləşdirən düz xətt parçasıdır.',array['Çevrənin iki nöqtəsini birləşdirən parça','Mərkəzdən keçməyən düz xətt','Çevrəyə toxunan düz xətt','Qövsün uzunluğu'],1),
('riy9-cevre#10','riy-9-cevre',1,1,'Çevrənin ən böyük vətəri hansıdır?','Mərkəzdən keçən vətər - diametr ən böyükdür.',array['Diametr','Radius','Toxunan','İxtiyari vətər'],1),
('riy9-cevre#11','riy-9-cevre',2,1,'Mərkəzdən vətərə endirilmiş perpendikulyar vətəri necə bölür?','Perpendikulyar vətəri yarıya bölür.',array['İki bərabər hissəyə','Nisbəti 1:2 olan hissələrə','Bölmür','Üç hissəyə'],1),
('riy9-cevre#12','riy-9-cevre',2,1,'Mərkəzdən bərabər məsafədə olan vətərlər bir-birinə necədir?','Belə vətərlərin uzunluqları bərabərdir.',array['Bərabərdir','Biri iki dəfə böyükdür','Perpendikulyardır','Paralel ola bilməz'],1),
('riy9-cevre#13','riy-9-cevre',2,1,'Xaricdəki nöqtədən çevrəyə çəkilmiş iki toxunan parçası haqqında nə demək olar?','Toxunan parçaları bərabərdir.',array['Uzunluqları bərabərdir','Biri həmişə uzundur','Cəmi diametrə bərabərdir','Perpendikulyardırlar'],1),
('riy9-cevre#14','riy-9-cevre',2,1,'Daxilə çəkilmiş bucaq 35° olarsa, söykəndiyi qövs neçə dərəcədir?','Qövs bucağın iki mislidir: 70°.',array['70°','35°','17,5°','140°'],1),
('riy9-cevre#15','riy-9-cevre',2,1,'Eyni qövsə söykənən daxilə çəkilmiş bucaqlar haqqında nə demək olar?','Hamısı qövsün yarısına, yəni bir-birinə bərabərdir.',array['Hamısı bərabərdir','Cəmi 180°-dir','Hamısı fərqlidir','Hamısı düz bucaqdır'],1),
('riy9-cevre#16','riy-9-cevre',3,1,'Çevrənin iki vətəri kəsişəndə parçaların hasilləri necə olur?','Bir vətərin parçalarının hasilı o birininkinə bərabərdir.',array['Bərabər olur','Fərqli olur','Cəmi sıfır olur','Həmişə 1 olur'],1),
('riy9-cevre#17','riy-9-cevre',3,1,'Toxunanla vətər arasındakı bucaq nəyə bərabərdir?','Tutduğu qövsün yarısına bərabərdir.',array['Tutduğu qövsün yarısına','Tutduğu qövsə','Həmişə 45°-yə','Mərkəzi bucağa'],1),
('riy9-cevre#18','riy-9-cevre',1,1,'Diametri 14 sm olan çevrənin radiusu neçədir?','r = d : 2 = 7 sm.',array['7 sm','28 sm','14 sm','3,5 sm'],1),
('riy9-cevre#19','riy-9-cevre',1,1,'Yarımçevrənin dərəcə ölçüsü neçədir?','Tam çevrə 360°, yarısı 180°-dir.',array['180°','90°','360°','120°'],1),
('riy9-cevre#20','riy-9-cevre',3,1,'Xaricdəki nöqtədən çəkilmiş iki kəsən arasındakı bucaq necə tapılır?','Tutulan qövslərin fərqinin yarısı kimi.',array['Qövslər fərqinin yarısı kimi','Qövslər cəminin yarısı kimi','Böyük qövsə bərabərdir','Həmişə 60°-dir'],1),
('riy9-cevre#21','riy-9-cevre',2,1,'Uzunluğu 20π sm olan çevrənin radiusu neçədir?','2πr = 20π, r = 10 sm.',array['10 sm','20 sm','5 sm','40 sm'],1),
('riy9-cevre#22','riy-9-cevre',2,1,'Mərkəzi bucağı 90° olan qövs çevrənin hansı hissəsidir?','90/360 = 1/4 hissəsidir.',array['Dörddə biri','Yarısı','Üçdə biri','Səkkizdə biri'],1),
('riy9-cevre#23','riy-9-cevre',1,1,'Daxilə çəkilmiş bucağın təpəsi harada yerləşir?','Təpəsi çevrənin üzərindədir.',array['Çevrənin üzərində','Mərkəzdə','Çevrədən xaricdə','Vətərin ortasında'],1),
('riy9-cevre#24','riy-9-cevre',2,1,'Radius 5 sm, mərkəzdən düz xəttə məsafə 5 sm-dirsə, düz xətt çevrəyə nədir?','Məsafə radiusa bərabərdirsə, düz xətt toxunandır.',array['Toxunandır','Kəsəndir','Kəsişmir','Diametrdir'],1),
('riy9-cevre#25','riy-9-cevre',2,1,'Mərkəzdən düz xəttə məsafə radiusdan böyükdürsə, düz xətt çevrəni neçə nöqtədə kəsir?','Belə düz xətt çevrə ilə kəsişmir.',array['Heç bir nöqtədə','Bir nöqtədə','İki nöqtədə','Üç nöqtədə'],1),
('riy9-cevre#26','riy-9-cevre',1,1,'Kəsən çevrəni neçə nöqtədə kəsir?','Kəsən çevrə ilə iki nöqtədə kəsişir.',array['İki nöqtədə','Bir nöqtədə','Heç bir nöqtədə','Dörd nöqtədə'],1),
('riy9-cevre#27','riy-9-cevre',2,1,'120°-lik qövsə söykənən daxilə çəkilmiş bucaq neçə dərəcədir?','120 : 2 = 60°.',array['60°','120°','240°','30°'],1),
('riy9-cevre#28','riy-9-cevre',2,1,'Çevrənin uzunluğunun diametrə nisbəti hansı ədəddir?','C : d = π (təqribən 3,14).',array['π ədədi','2 ədədi','Radius','Diametr'],1),
('riy9-cevre#29','riy-9-cevre',3,1,'İki toxunan arasındakı bucaq 40° olarsa, kiçik qövs neçə dərəcədir?','(360 − x − x = qövslər) fərqin yarısı 40°: böyük − kiçik = 80, cəm 360, kiçik = 140°.',array['140°','80°','160°','40°'],1),
('riy9-cevre#30','riy-9-cevre',2,1,'Vətərə perpendikulyar olan diametr uyğun qövsü necə bölür?','Qövsü də iki bərabər hissəyə bölür.',array['İki bərabər qövsə','Nisbəti 2:1 olan qövslərə','Bölmür','Dörd qövsə'],1),
('riy9-cevre#31','riy-9-cevre',3,1,'Radiusu 8 sm olan çevrədə 45°-lik qövsün uzunluğu neçədir?','l = (45/360) · 16π = 2π sm.',array['2π sm','4π sm','8π sm','π sm'],1),
('riy9-cevre#32','riy-9-cevre',2,1,'Konsentrik çevrələr hansı çevrələrdir?','Mərkəzləri eyni, radiusları fərqli çevrələrdir.',array['Mərkəzi eyni olan çevrələr','Radiusu eyni olan çevrələr','Toxunan çevrələr','Kəsişən çevrələr'],1),
('riy9-cevre#33','riy-9-cevre',2,1,'Daxilə çəkilmiş 90°-lik bucaq hansı vətərə söykənir?','Düz bucaq diametrə söykənir.',array['Diametrə','Radiusa','Ən kiçik vətərə','Toxunana'],1),
('riy9-cevre#34','riy-9-cevre',3,1,'Bir nöqtədən çəkilmiş toxunan parçasının kvadratı nəyə bərabərdir?','Kəsənin parçalarının hasilinə bərabərdir.',array['Kəsənin parçalarının hasilinə','Kəsənin cəminə','Radiusun kvadratına','Diametrə'],1),
('riy9-cevre#35','riy-9-cevre',1,1,'Tam çevrənin dərəcə ölçüsü neçədir?','Tam dövr 360°-dir.',array['360°','180°','90°','270°'],1),
('riy9-cevre#36','riy-9-cevre',3,1,'Radius 10 sm, vətərə mərkəzdən məsafə 6 sm olarsa, vətərin yarısı neçədir?','√(10² − 6²) = √64 = 8 sm.',array['8 sm','4 sm','6 sm','16 sm'],1),
('riy9-cevre#37','riy-9-cevre',2,1,'l = πrα/180 düsturunda α nəyi bildirir?','α qövsün dərəcə ölçüsüdür.',array['Qövsün dərəcə ölçüsünü','Radiusu','Vətəri','Sahəni'],1),
('riy9-cevre#38','riy-9-cevre',3,1,'Eyni vətərə söykənən iki qövsün dərəcə ölçülərinin cəmi neçədir?','İki qövs bütöv çevrəni tamamlayır: 360°.',array['360°','180°','90°','Vətərdən asılıdır'],1),
('riy9-cevre#39','riy-9-cevre',1,1,'Diametrin uc nöqtələri çevrəni hansı hissələrə bölür?','Çevrə iki yarımçevrəyə bölünür.',array['İki yarımçevrəyə','Dörd rübə','Üç qövsə','Bölmür'],1),
('riy9-cevre#40','riy-9-cevre',2,1,'Çevrənin bir nöqtəsindən ona neçə toxunan çəkmək olar?','Toxunma nöqtəsindən yalnız bir toxunan keçir.',array['Yalnız bir','İki','Sonsuz sayda','Heç bir'],1),
('riy9-funksiya#1','riy-9-funksiya',1,1,'y = x² funksiyasının qrafiki necə adlanır?','Kvadratik funksiyanın qrafiki paraboladır.',array['Parabola','Hiperbola','Düz xətt','Çevrə'],1),
('riy9-funksiya#2','riy-9-funksiya',1,1,'y = ax² + bx + c funksiyasında a müsbət olduqda parabolanın qolları hansı istiqamətə yönəlir?','a > 0 olduqda qollar yuxarı yönəlir.',array['Yuxarı','Aşağı','Sağa','Sola'],1),
('riy9-funksiya#3','riy-9-funksiya',2,1,'Parabolanın qolları aşağı yönəlirsə, a əmsalı haqqında nə demək olar?','Qollar aşağı olduqda baş əmsal mənfidir.',array['a mənfidir','a müsbətdir','a sıfırdır','a haqqında heç nə demək olmaz'],1),
('riy9-funksiya#4','riy-9-funksiya',2,1,'y = x² − 6x + 5 parabolasının simmetriya oxunun absisi neçədir?','x = −b/(2a) = 6/2 = 3.',array['x = 3','x = −3','x = 6','x = 5'],1),
('riy9-funksiya#5','riy-9-funksiya',3,1,'y = x² − 6x + 5 funksiyasının qrafiki absis oxunu hansı nöqtələrdə kəsir?','x² − 6x + 5 = 0; köklər 1 və 5.',array['x = 1 və x = 5','x = 2 və x = 3','x = −1 və x = −5','Kəsmir'],1),
('riy9-funksiya#6','riy-9-funksiya',2,1,'Parabolanın təpə nöqtəsi hansı nöqtədir?','Simmetriya oxu üzərindəki ən yüksək və ya ən alçaq nöqtədir.',array['Simmetriya oxu üzərindəki ekstremum nöqtəsi','Oy oxunu kəsdiyi nöqtə','İxtiyari nöqtə','Başlanğıc nöqtəsi'],1),
('riy9-funksiya#7','riy-9-funksiya',2,1,'y = (x − 2)² + 3 parabolasının təpə nöqtəsi hansıdır?','Təpə (2; 3) nöqtəsidir.',array['(2; 3)','(−2; 3)','(2; −3)','(3; 2)'],1),
('riy9-funksiya#8','riy-9-funksiya',2,1,'y = x² + 4 qrafiki y = x² qrafikindən necə alınır?','Qrafik 4 vahid yuxarı sürüşdürülür.',array['4 vahid yuxarı sürüşdürməklə','4 vahid aşağı sürüşdürməklə','4 vahid sağa sürüşdürməklə','4 dəfə sıxmaqla'],1),
('riy9-funksiya#9','riy-9-funksiya',3,1,'y = (x + 5)² qrafiki y = x² qrafikindən necə alınır?','Mötərizədəki +5 qrafiki 5 vahid sola aparır.',array['5 vahid sola sürüşdürməklə','5 vahid sağa sürüşdürməklə','5 vahid yuxarı sürüşdürməklə','Dəyişmir'],1),
('riy9-funksiya#10','riy-9-funksiya',2,1,'a müsbət olduqda kvadratik funksiyanın ən kiçik qiyməti harada alınır?','Ən kiçik qiymət təpə nöqtəsində olur.',array['Təpə nöqtəsində','Oy oxunda','Sıfır nöqtələrində','Sonsuzluqda'],1),
('riy9-funksiya#11','riy-9-funksiya',3,1,'y = 2x² − 8x + 1 funksiyasının təpə nöqtəsinin absisi neçədir?','x = −b/(2a) = 8/4 = 2.',array['x = 2','x = 4','x = −2','x = 8'],1),
('riy9-funksiya#12','riy-9-funksiya',2,1,'y = |x| funksiyasının qrafiki necə görünür?','Başlanğıcdan çıxan V şəkilli sınıq xəttdir.',array['V hərfi şəklində sınıq xətt','Parabola','Düz xətt','Çevrə'],1),
('riy9-funksiya#13','riy-9-funksiya',2,1,'y = |x| funksiyasının ən kiçik qiyməti neçədir?','Modul mənfi olmur, minimum |0| = 0-dır.',array['0','1','−1','Yoxdur'],1),
('riy9-funksiya#14','riy-9-funksiya',2,1,'Tərs mütənasibliyi göstərən y = k/x funksiyasının qrafiki hansı əyridir?','Tərs mütənasibliyin qrafiki hiperboladır.',array['Hiperbola','Parabola','Sinusoid','Paralel xətlər'],1),
('riy9-funksiya#15','riy-9-funksiya',2,1,'y = 12/x funksiyasının qrafiki hansı rüblərdən keçir?','k = 12 > 0 olduğundan I və III rüblərdən keçir.',array['I və III rüblərdən','II və IV rüblərdən','Yalnız I rübdən','Bütün rüblərdən'],1),
('riy9-funksiya#16','riy-9-funksiya',2,1,'Funksiyanın sıfırları nədir?','Qrafikin absis oxunu kəsdiyi nöqtələrin absisləridir.',array['Qrafikin Ox oxunu kəsdiyi nöqtələrin absisləri','Oy oxunu kəsdiyi nöqtələr','Təpə nöqtəsi','Qiymətlər çoxluğu'],1),
('riy9-funksiya#17','riy-9-funksiya',2,1,'y = x² − 9 funksiyasının sıfırlarını tapın.','x² = 9; x = 3 və x = −3.',array['x = 3 və x = −3','x = 9 və x = −9','Yalnız x = 3','Sıfırları yoxdur'],1),
('riy9-funksiya#18','riy-9-funksiya',2,1,'f(x) = x² + 2x üçün f(3) neçədir?','9 + 6 = 15.',array['15','11','9','21'],1),
('riy9-funksiya#19','riy-9-funksiya',3,1,'y = ax² + bx + c funksiyasında c əmsalı qrafikdə nəyi göstərir?','x = 0 olduqda y = c - qrafikin Oy oxunu kəsdiyi nöqtədir.',array['Oy oxunu kəsdiyi nöqtəni','Təpə nöqtəsini','Simmetriya oxunu','Qolların istiqamətini'],1),
('riy9-funksiya#20','riy-9-funksiya',3,1,'y = x² − 4x + 7 funksiyasının ən kiçik qiyməti neçədir?','Təpədə x = 2, y = 4 − 8 + 7 = 3.',array['3','7','2','−1'],1),
('riy9-funksiya#21','riy-9-funksiya',3,1,'Diskriminant mənfi olarsa, parabola absis oxu ilə neçə nöqtədə kəsişir?','D < 0 olduqda həqiqi kök yoxdur - kəsişmir.',array['Heç bir nöqtədə','Bir nöqtədə','İki nöqtədə','Üç nöqtədə'],1),
('riy9-funksiya#22','riy-9-funksiya',3,1,'Parabola absis oxunu iki müxtəlif nöqtədə kəsirsə, diskriminant haqqında nə deyilir?','İki müxtəlif kök üçün D müsbət olmalıdır.',array['Müsbətdir','Mənfidir','Sıfırdır','Təyin olunmur'],1),
('riy9-funksiya#23','riy-9-funksiya',2,1,'y = −x² funksiyasının ən böyük qiyməti neçədir?','Qollar aşağı baxır, maksimum təpədə: 0.',array['0','−1','1','Yoxdur'],1),
('riy9-funksiya#24','riy-9-funksiya',1,1,'f(x) = 3x − 1 funksiyası hansı funksiya növüdür?','Birdərəcəli ifadə xətti funksiyadır.',array['Xətti funksiya','Kvadratik funksiya','Tərs mütənasiblik','Modullu funksiya'],1),
('riy9-funksiya#25','riy-9-funksiya',2,1,'y = x² funksiyası hansı qiymətlərdə azalandır?','Parabola x < 0 olduqda azalır.',array['x sıfırdan kiçik olduqda','x sıfırdan böyük olduqda','Heç vaxt','Bütün qiymətlərdə'],1),
('riy9-funksiya#26','riy-9-funksiya',2,1,'Funksiyanın təyin oblastı nədir?','Arqumentin ala bildiyi qiymətlər çoxluğudur.',array['Arqumentin ala bildiyi qiymətlər çoxluğu','Funksiyanın qiymətləri','Qrafikin uzunluğu','Sıfırların sayı'],1),
('riy9-funksiya#27','riy-9-funksiya',2,1,'y = 1/(x − 4) funksiyasının təyin oblastına hansı ədəd daxil deyil?','x = 4 olduqda məxrəc sıfır olur.',array['4','−4','0','1'],1),
('riy9-funksiya#28','riy-9-funksiya',2,1,'y = √x funksiyası hansı qiymətlərdə təyin olunub?','Kök altı mənfi ola bilməz: x ≥ 0.',array['x ≥ 0 olduqda','x > 1 olduqda','Bütün x-lərdə','x < 0 olduqda'],1),
('riy9-funksiya#29','riy-9-funksiya',3,1,'Cüt funksiyanın qrafiki nəyə görə simmetrikdir?','Cüt funksiya Oy oxuna görə simmetrikdir.',array['Oy oxuna görə','Ox oxuna görə','Başlanğıca görə','Simmetrik deyil'],1),
('riy9-funksiya#30','riy-9-funksiya',3,1,'y = x³ funksiyası tək, yoxsa cüt funksiyadır?','(−x)³ = −x³ olduğundan tək funksiyadır.',array['Təkdir','Cütdür','Həm tək, həm cüt','Heç biri'],1),
('riy9-funksiya#31','riy-9-funksiya',2,1,'Parabolanın simmetriya oxunun düsturu hansıdır?','Simmetriya oxu x = −b/(2a) düz xəttidir.',array['x = −b/(2a)','x = b/a','y = c','x = −c/b'],1),
('riy9-funksiya#32','riy-9-funksiya',2,1,'y = 2x² və y = x² parabolalarından hansı daha dardır?','Əmsal böyüdükcə parabola daralır: y = 2x².',array['y = 2x²','y = x²','Eynidirlər','Müqayisə olunmur'],1),
('riy9-funksiya#33','riy-9-funksiya',2,1,'f(x) = x² − 5x funksiyası üçün f(−1) neçədir?','1 + 5 = 6.',array['6','−6','4','−4'],1),
('riy9-funksiya#34','riy-9-funksiya',2,1,'Qrafiki koordinat başlanğıcından keçən funksiya hansıdır?','y = 3x² üçün x = 0 olduqda y = 0.',array['y = 3x²','y = x² + 1','y = 1/x','y = x − 2'],1),
('riy9-funksiya#35','riy-9-funksiya',3,1,'y = |x − 3| funksiyasının ən kiçik qiyməti hansı nöqtədə alınır?','Modul sıfır olanda: x = 3.',array['x = 3-də','x = −3-də','x = 0-da','Alınmır'],1),
('riy9-funksiya#36','riy-9-funksiya',3,1,'Təpəsi (2; −1) olan, qolları yuxarı parabolanın qiymətlər çoxluğu hansıdır?','Minimum −1-dir: y ≥ −1.',array['y ≥ −1','y ≤ −1','y ≥ 2','Bütün ədədlər'],1),
('riy9-funksiya#37','riy-9-funksiya',3,1,'y = k/x-də k mənfi olduqda hiperbola hansı rüblərdə yerləşir?','k < 0 üçün qraf II və IV rüblərdədir.',array['II və IV rüblərdə','I və III rüblərdə','Yalnız II rübdə','Bütün rüblərdə'],1),
('riy9-funksiya#38','riy-9-funksiya',2,1,'Funksiyanın qrafiki üzərindəki nöqtənin koordinatları nəyi ödəyir?','Koordinatlar funksiyanın düsturunu ödəyir.',array['Funksiyanın düsturunu','Yalnız x oxunu','Heç nəyi','Yalnız müsbətliyi'],1),
('riy9-funksiya#39','riy-9-funksiya',2,1,'y = x² − 2x − 8 parabolasının Oy oxunu kəsdiyi nöqtə hansıdır?','x = 0 olduqda y = −8: nöqtə (0; −8).',array['(0; −8)','(0; 8)','(−8; 0)','(0; −2)'],1),
('riy9-funksiya#40','riy-9-funksiya',1,1,'Artan funksiya hansı funksiyadır?','Arqument artdıqca qiyməti də artan funksiyadır.',array['Arqument artdıqca qiyməti artan funksiya','Qiyməti sabit qalan funksiya','Arqument artdıqca azalan funksiya','Qrafiki qapalı əyri olan'],1),
('riy9-cevre-tenliyi#1','riy-9-cevre-tenliyi',2,2,'A(1; 2) və B(4; 6) nöqtələri arasındakı məsafə neçədir?','√(3² + 4²) = √25 = 5 vahid.',array['5 vahid','7 vahid','25 vahid','3 vahid'],1),
('riy9-cevre-tenliyi#2','riy-9-cevre-tenliyi',2,2,'İki nöqtə arasındakı məsafə düsturu hansıdır?','Məsafə koordinat fərqlərinin kvadratları cəminin köküdür.',array['√((x₂−x₁)² + (y₂−y₁)²)','(x₂−x₁) + (y₂−y₁)','|x₂−x₁| · |y₂−y₁|','(x₂+x₁)/2'],1),
('riy9-cevre-tenliyi#3','riy-9-cevre-tenliyi',2,2,'Mərkəzi başlanğıcda, radiusu 7 olan çevrənin tənliyi hansıdır?','x² + y² = r² = 49.',array['x² + y² = 49','x² + y² = 7','x + y = 49','x² − y² = 49'],1),
('riy9-cevre-tenliyi#4','riy-9-cevre-tenliyi',2,2,'x² + y² = 36 çevrəsinin radiusu neçədir?','r² = 36, r = 6.',array['6','36','18','12'],1),
('riy9-cevre-tenliyi#5','riy-9-cevre-tenliyi',2,2,'(x − 3)² + (y + 2)² = 25 çevrəsinin mərkəzi hansı nöqtədir?','Mərkəz (3; −2) nöqtəsidir.',array['(3; −2)','(−3; 2)','(3; 2)','(−3; −2)'],1),
('riy9-cevre-tenliyi#6','riy-9-cevre-tenliyi',2,2,'(x − 1)² + (y − 8)² = 25 çevrəsinin radiusu neçədir?','r = √25 = 5.',array['r = 5','r = 25','r = 8','r = 1'],1),
('riy9-cevre-tenliyi#7','riy-9-cevre-tenliyi',2,2,'Mərkəzi (1; 4), radiusu 3 olan çevrənin tənliyini yazın.','(x − 1)² + (y − 4)² = 9.',array['(x − 1)² + (y − 4)² = 9','(x + 1)² + (y + 4)² = 9','(x − 1)² + (y − 4)² = 3','x² + y² = 9'],1),
('riy9-cevre-tenliyi#8','riy-9-cevre-tenliyi',2,2,'A(−2; 0) və B(6; 0) parçasının orta nöqtəsi hansıdır?','((−2+6)/2; 0) = (2; 0).',array['(2; 0)','(4; 0)','(−4; 0)','(2; 6)'],1),
('riy9-cevre-tenliyi#9','riy-9-cevre-tenliyi',2,2,'Parçanın orta nöqtəsinin koordinatları necə tapılır?','Uc nöqtələrin uyğun koordinatlarının ədədi ortası kimi.',array['Uc nöqtələrin koordinatlarının ədədi ortası kimi','Koordinatların hasili kimi','Koordinatların fərqi kimi','Təsadüfi seçilir'],1),
('riy9-cevre-tenliyi#10','riy-9-cevre-tenliyi',2,2,'(5; 0) nöqtəsi x² + y² = 25 çevrəsinin üzərindədirmi?','5² + 0² = 25 - tənliyi ödəyir.',array['Bəli, üzərindədir','Xeyr, daxilindədir','Xeyr, xaricindədir','Müəyyən etmək olmur'],1),
('riy9-cevre-tenliyi#11','riy-9-cevre-tenliyi',3,2,'Vahid çevrədə sin α nöqtənin hansı koordinatına uyğundur?','Sinus nöqtənin ordinatıdır.',array['Ordinatı ilə','Absisi ilə','Radiusu ilə','Heç biri ilə'],1),
('riy9-cevre-tenliyi#12','riy-9-cevre-tenliyi',3,2,'Vahid çevrədə cos α nəyə uyğundur?','Kosinus nöqtənin absisidir.',array['Nöqtənin absisinə','Nöqtənin ordinatına','Qövsün uzunluğuna','Diametrə'],1),
('riy9-cevre-tenliyi#13','riy-9-cevre-tenliyi',2,2,'30 dərəcəlik bucağın sinusu hansı qiymətə malikdir?','sin 30° = 1/2.',array['1/2','√3/2','√2/2','1'],1),
('riy9-cevre-tenliyi#14','riy-9-cevre-tenliyi',2,2,'60 dərəcəlik bucağın kosinusunun qiymətini göstərin.','cos 60° = 0,5.',array['0,5','0,6','√3','0,866'],1),
('riy9-cevre-tenliyi#15','riy-9-cevre-tenliyi',2,2,'45 dərəcəlik bucağın tangensi neçəyə bərabərdir?','tan 45° = 1.',array['1','√2','1/2','0'],1),
('riy9-cevre-tenliyi#16','riy-9-cevre-tenliyi',2,2,'Dairə sektoru nədir?','İki radius və onların arasındakı qövslə əhatələnən hissədir.',array['İki radius və qövs arasındakı hissə','Vətərlə qövs arasındakı hissə','Dairənin yarısı','Çevrənin xarici hissəsi'],1),
('riy9-cevre-tenliyi#17','riy-9-cevre-tenliyi',3,2,'Radiusu 6 sm olan dairədə 90°-lik sektorun sahəsi neçədir?','S = (90/360) · π · 36 = 9π sm².',array['9π sm²','36π sm²','6π sm²','18π sm²'],1),
('riy9-cevre-tenliyi#18','riy-9-cevre-tenliyi',2,2,'Sektorun sahəsi tam dairənin sahəsindən necə tapılır?','Mərkəzi bucağın 360°-yə nisbəti qədər hissə götürülür.',array['Qövsün dərəcəsinə mütənasib hissə kimi','Həmişə yarısı kimi','Radius qədər azaltmaqla','Tapıla bilmir'],1),
('riy9-cevre-tenliyi#19','riy-9-cevre-tenliyi',2,2,'Radiusu 10 sm olan dairənin sahəsini π ilə ifadə edin.','S = πr² = 100π sm².',array['100π sm²','10π sm²','20π sm²','1000π sm²'],1),
('riy9-cevre-tenliyi#20','riy-9-cevre-tenliyi',2,2,'Dairə seqmenti nədir?','Vətərlə qövs arasında qalan hissədir.',array['Vətərlə qövs arasındakı hissə','İki radius arasındakı hissə','Dairənin mərkəzi','Toxunanla qövs arasındakı hissə'],1),
('riy9-cevre-tenliyi#21','riy-9-cevre-tenliyi',2,2,'M(9; 12) nöqtəsinin koordinat başlanğıcından uzaqlığını hesablayın.','√(81 + 144) = √225 = 15.',array['15 vahiddir','21 vahiddir','108 vahiddir','225 vahiddir'],1),
('riy9-cevre-tenliyi#22','riy-9-cevre-tenliyi',2,2,'(x − a)² + (y − b)² = r² tənliyində a və b nəyi bildirir?','a və b mərkəzin koordinatlarıdır.',array['Mərkəzin koordinatlarını','Radiusları','Toxunanın əmsallarını','Qövsün ölçüsünü'],1),
('riy9-cevre-tenliyi#23','riy-9-cevre-tenliyi',1,2,'x² + y² = 1 çevrəsi necə adlanır?','Radiusu 1 olan bu çevrə vahid çevrədir.',array['Vahid çevrə','Böyük çevrə','Sıfır çevrə','Qütb çevrəsi'],1),
('riy9-cevre-tenliyi#24','riy-9-cevre-tenliyi',3,2,'sin α = 0,6 olarsa, cos²α neçəyə bərabərdir?','cos²α = 1 − sin²α = 1 − 0,36 = 0,64.',array['0,64','0,36','0,4','0,8'],1),
('riy9-cevre-tenliyi#25','riy-9-cevre-tenliyi',3,2,'180 dərəcəlik bucağın sinusu neçədir?','sin 180° = 0.',array['Sıfra bərabərdir','Birə bərabərdir','Mənfi birdir','Yarımdır'],1),
('riy9-cevre-tenliyi#26','riy-9-cevre-tenliyi',3,2,'Radiusu 4 sm, mərkəzi bucağı 45° olan sektorun sahəsi neçədir?','S = (45/360) · 16π = 2π sm².',array['2π sm²','4π sm²','8π sm²','π sm²'],1),
('riy9-cevre-tenliyi#27','riy-9-cevre-tenliyi',2,2,'M(x; y) nöqtəsi başlanğıcdan r məsafəsindədirsə, hansı bərabərlik doğrudur?','Məsafə düsturuna görə x² + y² = r².',array['x² + y² = r²','x + y = r','xy = r²','x² − y² = r²'],1),
('riy9-cevre-tenliyi#28','riy-9-cevre-tenliyi',2,2,'A(0; 3) və B(4; 0) nöqtələri arasındakı məsafəni tapın.','√(16 + 9) = √25; AB = 5.',array['AB = 5','AB = 7','AB = 12','AB = 25'],1),
('riy9-cevre-tenliyi#29','riy-9-cevre-tenliyi',2,2,'(x + 2)² + y² = 16 çevrəsinin mərkəzi hansı nöqtədədir?','Mərkəz (−2; 0) nöqtəsidir.',array['(−2; 0)','(2; 0)','(0; −2)','(−2; 16)'],1),
('riy9-cevre-tenliyi#30','riy-9-cevre-tenliyi',3,2,'x² + y² = 16 çevrəsi Oy oxunu hansı nöqtələrdə kəsir?','x = 0 olduqda y = ±4.',array['(0; 4) və (0; −4)','(4; 0) və (−4; 0)','(0; 16) və (0; −16)','Kəsmir'],1),
('riy9-cevre-tenliyi#31','riy-9-cevre-tenliyi',2,2,'Sıfır dərəcəlik bucağın kosinusu neçədir?','cos 0° = 1.',array['Birə bərabərdir','Sıfra bərabərdir','Mənfi birdir','Təyin olunmur'],1),
('riy9-cevre-tenliyi#32','riy-9-cevre-tenliyi',2,2,'S = πr²α/360 düsturunda α nədir?','α sektorun mərkəzi bucağının dərəcə ölçüsüdür.',array['Mərkəzi bucağın dərəcə ölçüsü','Radius','Vətərin uzunluğu','Seqmentin hündürlüyü'],1),
('riy9-cevre-tenliyi#33','riy-9-cevre-tenliyi',2,2,'A(2; 3) nöqtəsinin absis oxuna görə simmetrik nöqtəsi hansıdır?','Ordinatın işarəsi dəyişir: (2; −3).',array['(2; −3)','(−2; 3)','(−2; −3)','(3; 2)'],1),
('riy9-cevre-tenliyi#34','riy-9-cevre-tenliyi',2,2,'A(2; 3) nöqtəsinin koordinat başlanğıcına görə simmetriki hansıdır?','Hər iki koordinatın işarəsi dəyişir: (−2; −3).',array['(−2; −3)','(2; −3)','(−2; 3)','(3; 2)'],1),
('riy9-cevre-tenliyi#35','riy-9-cevre-tenliyi',3,2,'Radiusu 3 sm olan yarımdairənin sahəsi neçədir?','S = (π · 9) / 2 = 4,5π sm².',array['4,5π sm²','9π sm²','3π sm²','6π sm²'],1),
('riy9-cevre-tenliyi#36','riy-9-cevre-tenliyi',3,2,'x² + y² = 9 çevrəsi ilə y = 3 düz xətti neçə ortaq nöqtəyə malikdir?','(0; 3)-də toxunur - bir ortaq nöqtə.',array['Bir (toxunur)','İki','Heç bir','Sonsuz sayda'],1),
('riy9-cevre-tenliyi#37','riy-9-cevre-tenliyi',3,2,'Radiusu 2 dəfə böyüdülmüş dairənin sahəsi əvvəlkindən neçə dəfə böyükdür?','Sahə radiusun kvadratı ilə mütənasibdir: 4 dəfə.',array['4 dəfə','2 dəfə','8 dəfə','16 dəfə'],1),
('riy9-cevre-tenliyi#38','riy-9-cevre-tenliyi',3,2,'sin 90° + cos 90° cəmi neçədir?','1 + 0 = 1.',array['Cəmi 1-dir','Cəmi 0-dır','Cəmi 2-dir','Cəmi 0,5-dir'],1),
('riy9-cevre-tenliyi#39','riy-9-cevre-tenliyi',3,2,'Koordinatları (cos α; sin α) olan nöqtə harada yerləşir?','Belə nöqtələr vahid çevrənin üzərindədir.',array['Vahid çevrə üzərində','Absis oxunda','Parabola üzərində','Hiperbola üzərində'],1),
('riy9-cevre-tenliyi#40','riy-9-cevre-tenliyi',2,2,'İki nöqtənin absisleri bərabərdirsə, aralarındakı məsafə necə tapılır?','Məsafə ordinatlar fərqinin moduluna bərabərdir.',array['Ordinatlar fərqinin modulu kimi','Absislərin cəmi kimi','Koordinatların hasili kimi','Sıfırdır'],1),
('riy9-tenlikler#1','riy-9-tenlikler',3,2,'x³ − 4x = 0 tənliyinin köklərini tapın.','x(x² − 4) = 0; köklər 0, 2 və −2.',array['0; 2; −2','Yalnız 0','2; −2','0; 4'],1),
('riy9-tenlikler#2','riy-9-tenlikler',2,2,'x⁴ = 16 tənliyinin həqiqi kökləri hansılardır?','x² = 4 olduğundan x = ±2.',array['2 və −2','Yalnız 2','4 və −4','16'],1),
('riy9-tenlikler#3','riy-9-tenlikler',1,2,'|x| = 6 tənliyinin kökləri hansılardır?','Modulu 6 olan ədədlər: 6 və −6.',array['6 və −6','Yalnız 6','Yalnız −6','36'],1),
('riy9-tenlikler#4','riy-9-tenlikler',2,2,'|x − 2| = 5 tənliyinin kökləri hansılardır?','x − 2 = 5 və ya x − 2 = −5; x = 7 və x = −3.',array['7 və −3','5 və −5','3 və −7','2 və 5'],1),
('riy9-tenlikler#5','riy-9-tenlikler',2,2,'|x| = −3 tənliyinin neçə kökü var?','Modul mənfi ola bilməz - kök yoxdur.',array['Kökü yoxdur','Bir kökü','İki kökü','Üç kökü'],1),
('riy9-tenlikler#6','riy-9-tenlikler',2,2,'√x = 9 tənliyinin kökü neçədir?','Hər iki tərəfi kvadrata: x = 81.',array['81','3','18','9'],1),
('riy9-tenlikler#7','riy-9-tenlikler',2,2,'√(x + 1) = 4 tənliyinin kökü neçədir?','x + 1 = 16; x = 15.',array['15','17','3','5'],1),
('riy9-tenlikler#8','riy-9-tenlikler',2,2,'İrrasional tənliyi həll edərkən sonda nə yoxlanılmalıdır?','Kvadrata yüksəltmə kənar kök verə bilər - yoxlama vacibdir.',array['Alınan köklərin tənliyi ödəməsi','Tənliyin dərəcəsi','Məxrəcin işarəsi','Heç nə yoxlanılmır'],1),
('riy9-tenlikler#9','riy-9-tenlikler',2,2,'(x − 3)(x + 8) = 0 tənliyinin kökləri hansılardır?','Vuruqlardan biri sıfırdır: x = 3 və ya x = −8.',array['3 və −8','−3 və 8','3 və 8','−3 və −8'],1),
('riy9-tenlikler#10','riy-9-tenlikler',2,2,'Rasional tənlikdə məxrəc üçün hansı şərt qoyulur?','Məxrəc sıfır ola bilməz.',array['Sıfırdan fərqli olması','Müsbət olması','Tam ədəd olması','Şərt qoyulmur'],1),
('riy9-tenlikler#11','riy-9-tenlikler',2,2,'1/x = 5 tənliyinin kökü neçədir?','x = 1/5.',array['1/5','5','−5','0,2 yazılışı ilə 2'],1),
('riy9-tenlikler#12','riy-9-tenlikler',2,2,'x/(x − 2) = 0 tənliyinin kökü neçədir?','Kəsr sıfırdır, surət sıfır olanda: x = 0 (x = 2 yasaqdır).',array['x = 0','x = 2','x = −2','Kökü yoxdur'],1),
('riy9-tenlikler#13','riy-9-tenlikler',1,2,'Tənliklər sistemi nə vaxt həll olunmuş sayılır?','Bütün tənlikləri eyni anda ödəyən qiymətlər tapılanda.',array['Bütün tənlikləri ödəyən qiymətlər tapılanda','Bir tənlik həll olunanda','Qrafik çəkiləndə','Məxrəclər atılanda'],1),
('riy9-tenlikler#14','riy-9-tenlikler',2,2,'x + y = 10 və x − y = 2 sistemini həll edin.','Toplasaq 2x = 12; x = 6, y = 4.',array['x = 6; y = 4','x = 4; y = 6','x = 5; y = 5','x = 8; y = 2'],1),
('riy9-tenlikler#15','riy-9-tenlikler',2,2,'y = x² və y = 9 sistemində x-in qiymətləri hansılardır?','x² = 9; x = 3 və x = −3.',array['3 və −3','Yalnız 3','9 və −9','81'],1),
('riy9-tenlikler#16','riy-9-tenlikler',2,2,'Sistemin cəbri həll üsulları hansılardır?','Əvəzetmə və tərəf-tərəfə toplama üsulları.',array['Əvəzetmə və toplama üsulları','Yalnız qrafik üsul','Yalnız təxmin üsulu','Üsul yoxdur'],1),
('riy9-tenlikler#17','riy-9-tenlikler',3,2,'x · y = 12 və x + y = 7 sisteminin müsbət həlli hansıdır?','3 · 4 = 12 və 3 + 4 = 7.',array['x = 3; y = 4','x = 2; y = 6','x = 1; y = 12','x = 5; y = 2'],1),
('riy9-tenlikler#18','riy-9-tenlikler',2,2,'x⁵ = 32 tənliyinin kökü neçədir?','2⁵ = 32; x = 2.',array['x = 2','x = 5','x = 16','x = 32'],1),
('riy9-tenlikler#19','riy-9-tenlikler',2,2,'Üçüncü dərəcəli tənliyin ən çoxu neçə həqiqi kökü ola bilər?','Dərəcə qədər: ən çoxu 3 kökü.',array['3 kökü','1 kökü','5 kökü','Sonsuz sayda'],1),
('riy9-tenlikler#20','riy-9-tenlikler',3,2,'(x² − 1)(x² − 4) = 0 tənliyinin neçə kökü var?','x = ±1 və x = ±2 - cəmi 4 kök.',array['4 kökü','2 kökü','3 kökü','Kökü yoxdur'],1),
('riy9-tenlikler#21','riy-9-tenlikler',2,2,'2/(x + 1) = 1/3 tənliyinin kökü neçədir?','x + 1 = 6; x = 5.',array['x = 5','x = 6','x = −5','x = 7'],1),
('riy9-tenlikler#22','riy-9-tenlikler',2,2,'|2x| = 10 tənliyinin kökləri hansılardır?','2x = ±10; x = 5 və x = −5.',array['5 və −5','10 və −10','Yalnız 5','20'],1),
('riy9-tenlikler#23','riy-9-tenlikler',2,2,'√(2x) = 6 tənliyinin kökü neçədir?','2x = 36; x = 18.',array['18','12','3','36'],1),
('riy9-tenlikler#24','riy-9-tenlikler',2,2,'x³ = −27 tənliyinin kökü neçədir?','(−3)³ = −27; x = −3.',array['−3','3','−9','9 mənfi işarə ilə deyil'],1),
('riy9-tenlikler#25','riy-9-tenlikler',1,2,'x = 2 ədədi 3x − 6 = 0 tənliyinin kökü sayılırmı?','3 · 2 − 6 = 0 doğrudur - kökdür.',array['Bəli, tənliyi ödəyir','Xeyr, ödəmir','Yalnız təxminidir','Yoxlamaq olmur'],1),
('riy9-tenlikler#26','riy-9-tenlikler',2,2,'x² = 7x tənliyini həll edin.','x² − 7x = 0; x(x − 7) = 0; köklər 0 və 7.',array['0 və 7','Yalnız 7','7 və −7','Yalnız 0'],1),
('riy9-tenlikler#27','riy-9-tenlikler',2,2,'x⁴ − 5x² + 4 = 0 şəklindəki tənlik necə adlanır?','Kvadrat tənliyə gətirilən bikvadrat tənlikdir.',array['Bikvadrat tənlik','Xətti tənlik','İrrasional tənlik','Modullu tənlik'],1),
('riy9-tenlikler#28','riy-9-tenlikler',3,2,'x⁴ − 5x² + 4 = 0 tənliyinin kökləri hansılardır?','x² = 1 və x² = 4; köklər ±1 və ±2.',array['±1 və ±2','±4 və ±5','Yalnız 1 və 4','Kökü yoxdur'],1),
('riy9-tenlikler#29','riy-9-tenlikler',2,2,'Tənliklər sisteminin həndəsi mənası nədir?','Həllər qrafiklərin kəsişmə nöqtələridir.',array['Qrafiklərin kəsişmə nöqtələri','Qrafiklərin sahəsi','Oxların kəsişməsi','Mənası yoxdur'],1),
('riy9-tenlikler#30','riy-9-tenlikler',3,2,'Biri xətti, digəri kvadrat olan sistemin ən çoxu neçə həlli olar?','Düz xətt parabolanı ən çoxu iki nöqtədə kəsir.',array['İki həlli','Bir həlli','Üç həlli','Sonsuz həlli'],1),
('riy9-tenlikler#31','riy-9-tenlikler',2,2,'İki ədədin cəmi 15, fərqi 3-dür. Böyük ədəd neçədir?','(15 + 3) : 2 = 9.',array['9','6','12','18'],1),
('riy9-tenlikler#32','riy-9-tenlikler',2,2,'|x + 4| = 0 tənliyinin kökü neçədir?','Modul sıfırdır, deməli x + 4 = 0; x = −4.',array['x = −4','x = 4','Kökü yoxdur','x = 0'],1),
('riy9-tenlikler#33','riy-9-tenlikler',2,2,'(x − 6)² = 0 tənliyinin neçə kökü var?','x = 6 ikiqat kökdür - bir qiymət.',array['Bir (ikiqat) kökü','İki müxtəlif kökü','Kökü yoxdur','Üç kökü'],1),
('riy9-tenlikler#34','riy-9-tenlikler',2,2,'3/x + 2 = 5 tənliyini həll edin.','3/x = 3; x = 1.',array['x = 1','x = 3','x = −1','x = 1/3'],1),
('riy9-tenlikler#35','riy-9-tenlikler',2,2,'y = 2x ifadəsini ikinci tənlikdə yerinə yazmaq hansı üsuldur?','Bu, əvəzetmə üsuludur.',array['Əvəzetmə üsulu ilə','Toplama üsulu ilə','Qrafik üsulla','Yoxlama üsulu ilə'],1),
('riy9-tenlikler#36','riy-9-tenlikler',2,2,'İki naməlumlu bir tənliyin neçə həlli ola bilər?','Belə tənliyi sonsuz sayda cüt ödəyir.',array['Sonsuz sayda','Yalnız bir','Yalnız iki','Heç bir'],1),
('riy9-tenlikler#37','riy-9-tenlikler',2,2,'x³ + y = 30 və y = 3 sistemində x neçədir?','x³ = 27; x = 3.',array['x = 3','x = 27','x = 2','x = −3'],1),
('riy9-tenlikler#38','riy-9-tenlikler',3,2,'Tənliyin hər iki tərəfini kvadrata yüksəltmək nəyə səbəb ola bilər?','Tənliyi ödəməyən kənar kök yarana bilər.',array['Kənar kök yaranmasına','Kökün itməsinə həmişə','Heç nəyə','Tənliyin xətti olmasına'],1),
('riy9-tenlikler#39','riy-9-tenlikler',3,2,'Düzbucaqlının perimetri 28 sm, sahəsi 48 sm²-dir. Tərəfləri hansılardır?','Cəm 14, hasil 48: tərəflər 6 və 8.',array['6 sm və 8 sm','4 sm və 12 sm','7 sm və 7 sm','2 sm və 24 sm'],1),
('riy9-tenlikler#40','riy-9-tenlikler',3,2,'x(x + 1)(x − 5) = 0 tənliyinin köklərinin cəmi neçədir?','Köklər 0, −1, 5; cəm 4-dür.',array['Cəmi 4-dür','Cəmi 6-dır','Cəmi 5-dir','Cəmi 0-dır'],1),
('riy9-coxbucaqli#1','riy-9-coxbucaqli',2,2,'Qabarıq n-bucaqlının daxili bucaqlarının cəmi hansı düsturla tapılır?','Cəm (n − 2) · 180° düsturu ilə hesablanır.',array['(n − 2) · 180°','n · 180°','(n + 2) · 90°','n · 360°'],1),
('riy9-coxbucaqli#2','riy-9-coxbucaqli',2,2,'Qabarıq altıbucaqlının daxili bucaqlarının cəmi neçə dərəcədir?','(6 − 2) · 180 = 720°.',array['720°','540°','360 dərəcədən az','1080°'],1),
('riy9-coxbucaqli#3','riy-9-coxbucaqli',3,2,'Daxili bucaqlarının cəmi 540° olan çoxbucaqlının neçə tərəfi var?','(n − 2) · 180 = 540; n = 5.',array['5 tərəfi','4 tərəfi','6 tərəfi','3 tərəfi'],1),
('riy9-coxbucaqli#4','riy-9-coxbucaqli',2,2,'İstənilən qabarıq çoxbucaqlının xarici bucaqlarının cəmi neçədir?','Xarici bucaqların cəmi həmişə 360 dərəcədir.',array['360 dərəcə','180 dərəcə','Tərəf sayından asılıdır','720 dərəcə'],1),
('riy9-coxbucaqli#5','riy-9-coxbucaqli',1,2,'Düzgün çoxbucaqlı hansı çoxbucaqlıdır?','Bütün tərəfləri və bucaqları bərabər olandır.',array['Bütün tərəfləri və bucaqları bərabər olan','Yalnız tərəfləri bərabər olan','Yalnız bucaqları bərabər olan','İxtiyari qabarıq çoxbucaqlı'],1),
('riy9-coxbucaqli#6','riy-9-coxbucaqli',3,2,'Düzgün səkkizbucaqlının bir daxili bucağı neçə dərəcədir?','(8 − 2) · 180 / 8 = 135°.',array['135°','120°','144°','108°'],1),
('riy9-coxbucaqli#7','riy-9-coxbucaqli',1,2,'Düzgün üçbucağın bir bucağı neçə dərəcədir?','180 : 3 = 60°.',array['60°','90°','45°','30°'],1),
('riy9-coxbucaqli#8','riy-9-coxbucaqli',3,2,'Düzgün onbucaqlının bir xarici bucağı neçə dərəcədir?','360 : 10 = 36°.',array['36°','144°','18°','72°'],1),
('riy9-coxbucaqli#9','riy-9-coxbucaqli',2,2,'Hər üçbucağın xaricinə çevrə çəkmək olarmı?','Bəli, hər üçbucağın xaricinə çevrə çəkilir.',array['Bəli, həmişə','Yalnız düzbucaqlıya','Yalnız bərabərtərəfliyə','Heç vaxt'],1),
('riy9-coxbucaqli#10','riy-9-coxbucaqli',3,2,'Üçbucağın xaricinə çəkilmiş çevrənin mərkəzi haradadır?','Tərəflərin orta perpendikulyarlarının kəsişməsindədir.',array['Tərəflərin orta perpendikulyarlarının kəsişməsində','Tənbölənlərin kəsişməsində','Medianların kəsişməsində','İxtiyari nöqtədə'],1),
('riy9-coxbucaqli#11','riy-9-coxbucaqli',3,2,'Üçbucağın daxilinə çəkilmiş çevrənin mərkəzi haradadır?','Bucaqların tənbölənlərinin kəsişməsindədir.',array['Bucaqların tənbölənlərinin kəsişməsində','Orta perpendikulyarların kəsişməsində','Hündürlüklərin kəsişməsində','Ağırlıq mərkəzində'],1),
('riy9-coxbucaqli#12','riy-9-coxbucaqli',3,2,'Dördbucaqlının xaricinə çevrə çəkilə bilməsi üçün şərt nədir?','Qarşı bucaqların cəmi 180° olmalıdır.',array['Qarşı bucaqların cəmi 180° olmalıdır','Bütün tərəflər bərabər olmalıdır','Diaqonallar perpendikulyar olmalıdır','Şərt yoxdur'],1),
('riy9-coxbucaqli#13','riy-9-coxbucaqli',2,2,'Çevrə daxilinə çəkilmiş dördbucaqlının qarşı bucaqlarının cəmi neçədir?','Qarşı bucaqlar 180° verir.',array['180°','90°','270°','İxtiyaridir'],1),
('riy9-coxbucaqli#14','riy-9-coxbucaqli',3,2,'Dördbucaqlının daxilinə çevrə çəkilməsi üçün şərt nədir?','Qarşı tərəflərin cəmləri bərabər olmalıdır.',array['Qarşı tərəflərin cəmləri bərabər olmalıdır','Bucaqlar bərabər olmalıdır','Diaqonallar bərabər olmalıdır','Perimetr cüt olmalıdır'],1),
('riy9-coxbucaqli#15','riy-9-coxbucaqli',2,2,'Düzgün çoxbucaqlının daxilinə və xaricinə çəkilmiş çevrələrin mərkəzləri necədir?','Hər iki mərkəz üst-üstə düşür.',array['Üst-üstə düşür','Fərqlidir','Simmetrikdir','Tərəf üzərindədir'],1),
('riy9-coxbucaqli#16','riy-9-coxbucaqli',3,2,'Tərəfi a olan bərabərtərəfli üçbucağın sahə düsturu hansıdır?','S = a²√3/4.',array['a²√3/4','a²/2','3a','a³'],1),
('riy9-coxbucaqli#17','riy-9-coxbucaqli',3,2,'Tərəfi 4 sm olan kvadratın xaricinə çəkilmiş çevrənin radiusu neçədir?','R = diaqonalın yarısı = 4√2/2 = 2√2 sm.',array['2√2 sm','4 sm','2 sm','4√2 sm'],1),
('riy9-coxbucaqli#18','riy-9-coxbucaqli',2,2,'Tərəfi 6 sm olan kvadratın daxilinə çəkilmiş çevrənin radiusu neçədir?','r = tərəfin yarısı = 3 sm.',array['3 sm','6 sm','3√2 sm','12 sm'],1),
('riy9-coxbucaqli#19','riy-9-coxbucaqli',3,2,'Düzgün altıbucaqlının tərəfi xaricə çəkilmiş çevrənin radiusu ilə necə bağlıdır?','Altıbucaqlıda tərəf radiusa bərabərdir.',array['Bərabərdir (a = R)','İki dəfə böyükdür','Yarısıdır','Bağlılıq yoxdur'],1),
('riy9-coxbucaqli#20','riy-9-coxbucaqli',3,2,'Perimetri p, daxilə çəkilmiş çevrənin radiusu r olan çoxbucaqlının sahəsi hansı düsturla tapılır?','S = p · r / 2.',array['S = p · r / 2','S = p · r','S = p + r','S = p² · r'],1),
('riy9-coxbucaqli#21','riy-9-coxbucaqli',2,2,'Beşbucaqlının diaqonallarının sayı neçədir?','n(n − 3)/2 = 5 · 2/2 = 5.',array['5 diaqonal','10 diaqonal','2 diaqonal','8 diaqonal'],1),
('riy9-coxbucaqli#22','riy-9-coxbucaqli',2,2,'n-bucaqlının bir təpəsindən neçə diaqonal çəkmək olar?','Qonşu olmayan təpələrə: n − 3 diaqonal.',array['n − 3','n − 1','n','n − 2'],1),
('riy9-coxbucaqli#23','riy-9-coxbucaqli',2,2,'Qabarıq çoxbucaqlı hansı çoxbucaqlıdır?','Bütün daxili bucaqları 180°-dən kiçik olandır.',array['Bütün daxili bucaqları 180°-dən kiçik olan','Bucağı 180°-dən böyük olan','Yalnız üçbucaq','Tərəfləri əyri olan'],1),
('riy9-coxbucaqli#24','riy-9-coxbucaqli',1,2,'Düzgün dördbucaqlı hansı fiqurdur?','Tərəfləri və bucaqları bərabər dördbucaqlı kvadratdır.',array['Kvadrat','Romb','Düzbucaqlı','Trapesiya'],1),
('riy9-coxbucaqli#25','riy-9-coxbucaqli',3,2,'Daxili bucaqlarının cəmi 1080° olan çoxbucaqlının neçə tərəfi var?','(n − 2) · 180 = 1080; n = 8.',array['8 tərəfi','6 tərəfi','10 tərəfi','12 tərəfi'],1),
('riy9-coxbucaqli#26','riy-9-coxbucaqli',2,2,'Düzgün n-bucaqlının bir daxili bucağının düsturu hansıdır?','Bucaq (n − 2) · 180° / n-dir.',array['(n − 2) · 180° / n','360° / n','180° / n','n · 90°'],1),
('riy9-coxbucaqli#27','riy-9-coxbucaqli',2,2,'Diaqonalı 10 sm olan kvadratın xaricinə çəkilmiş çevrənin radiusu neçədir?','R = diaqonalın yarısı = 5 sm.',array['5 sm','10 sm','5√2 sm','2,5 sm'],1),
('riy9-coxbucaqli#28','riy-9-coxbucaqli',1,2,'Çoxbucaqlının perimetri nədir?','Bütün tərəflərinin uzunluqları cəmidir.',array['Tərəflərinin uzunluqları cəmi','Diaqonalların cəmi','Bucaqların cəmi','Sahənin yarısı'],1),
('riy9-coxbucaqli#29','riy-9-coxbucaqli',3,2,'Bərabərtərəfli üçbucaqda daxilə və xaricə çəkilmiş çevrələrin radiuslarının nisbəti neçədir?','r : R = 1 : 2.',array['1 : 2','1 : 3','2 : 3','1 : 4'],1),
('riy9-coxbucaqli#30','riy-9-coxbucaqli',3,2,'Altıbucaqlının diaqonallarının ümumi sayı neçədir?','6 · 3/2 = 9.',array['9 diaqonal','6 diaqonal','12 diaqonal','3 diaqonal'],1),
('riy9-coxbucaqli#31','riy-9-coxbucaqli',2,2,'Düzgün altıbucaqlı neçə bərabərtərəfli üçbucağa bölünür?','Mərkəzdən təpələrə çəkilən radiuslar 6 üçbucaq verir.',array['6 üçbucağa','4 üçbucağa','8 üçbucağa','3 üçbucağa'],1),
('riy9-coxbucaqli#32','riy-9-coxbucaqli',1,2,'Tərəfi 2 sm olan düzgün altıbucaqlının perimetri neçədir?','6 · 2 = 12 sm.',array['12 sm','8 sm','6 sm','10 sm'],1),
('riy9-coxbucaqli#33','riy-9-coxbucaqli',3,2,'Düzgün çoxbucaqlının apofemi nədir?','Mərkəzdən tərəfə endirilmiş perpendikulyardır.',array['Mərkəzdən tərəfə endirilmiş perpendikulyar','Ən uzun diaqonal','Tərəflərin cəmi','Xarici bucaq'],1),
('riy9-coxbucaqli#34','riy-9-coxbucaqli',2,2,'Kvadratın daxilinə çəkilmiş çevrənin diametri nəyə bərabərdir?','Diametr kvadratın tərəfinə bərabərdir.',array['Kvadratın tərəfinə','Kvadratın diaqonalına','Perimetrin yarısına','Sahəyə'],1),
('riy9-coxbucaqli#35','riy-9-coxbucaqli',3,2,'Bir daxili bucağı 100° olan düzgün çoxbucaqlı ola bilərmi?','(n−2)·180/n = 100 tam n vermir - ola bilməz.',array['Xeyr, ola bilməz','Bəli, beşbucaqlı','Bəli, altıbucaqlı','Bəli, onbucaqlı'],1),
('riy9-coxbucaqli#36','riy-9-coxbucaqli',3,2,'Üçbucağın sahəsi 24 sm², perimetri 24 sm-dirsə, daxilə çəkilmiş çevrənin radiusu neçədir?','S = p·r/2; 24 = 12r; r = 2 sm.',array['r = 2 sm','r = 4 sm','r = 1 sm','r = 12 sm'],1),
('riy9-coxbucaqli#37','riy-9-coxbucaqli',2,2,'Dörd tərəfi bərabər, bucaqları isə düz olmayan dördbucaqlı hansıdır?','Belə fiqur rombdur.',array['Romb','Kvadrat','Trapesiya','Paraleloqram deyil'],1),
('riy9-coxbucaqli#38','riy-9-coxbucaqli',2,2,'Xarici bucaq özünə qonşu daxili bucaqla birlikdə neçə dərəcə təşkil edir?','Qonşu bucaqlar kimi cəmi 180°-dir.',array['180°-yə qədər (qonşu bucaqdır)','360° təşkil edir','90° təşkil edir','Cəm sabit deyil'],1),
('riy9-coxbucaqli#39','riy-9-coxbucaqli',3,2,'Düzgün beşbucaqlının simmetriya oxlarının sayı neçədir?','Düzgün n-bucaqlının n simmetriya oxu var: 5.',array['5 ox','2 ox','10 ox','Oxu yoxdur'],1),
('riy9-coxbucaqli#40','riy-9-coxbucaqli',1,2,'Arı şanında hansı düzgün çoxbucaqlı forması müşahidə olunur?','Şan gözcükləri düzgün altıbucaqlıdır.',array['Düzgün altıbucaqlı','Kvadrat','Düzgün üçbucaq','Dairə'],1),
('riy9-berabersizlik#1','riy-9-berabersizlik',2,3,'x² − 9 < 0 bərabərsizliyinin həlli hansıdır?','Köklər ±3; parabola arasında mənfidir: −3 < x < 3.',array['−3 < x < 3','x > 3','x < −3','Bütün ədədlər'],1),
('riy9-berabersizlik#2','riy-9-berabersizlik',2,3,'x² > 25 bərabərsizliyini ödəyən x-lər hansılardır?','Modulu 5-dən böyük ədədlər: x < −5 və ya x > 5.',array['x < −5 və ya x > 5','−5 < x < 5','Yalnız x > 5','x = ±5'],1),
('riy9-berabersizlik#3','riy-9-berabersizlik',2,3,'Kvadrat bərabərsizliyi həll etmək üçün əvvəlcə nə tapılır?','Uyğun kvadrat tənliyin kökləri tapılır.',array['Uyğun tənliyin kökləri','Perimetr','Funksiyanın qiyməti','Diaqonal'],1),
('riy9-berabersizlik#4','riy-9-berabersizlik',2,3,'İntervallar üsulunda ədəd oxunda nələr qeyd olunur?','İfadəni sıfra çevirən nöqtələr qeyd olunur.',array['İfadənin sıfırları','Yalnız müsbət ədədlər','Kəsr hissələr','Cüt ədədlər'],1),
('riy9-berabersizlik#5','riy-9-berabersizlik',2,3,'(x − 1)(x − 7) < 0 bərabərsizliyinin həlli hansıdır?','Köklər arasında hasil mənfidir: 1 < x < 7.',array['1 < x < 7','x < 1','x > 7','1 və 7'],1),
('riy9-berabersizlik#6','riy-9-berabersizlik',3,3,'(x + 2)(x − 3) ifadəsi hansı aralıqlarda müsbətdir?','Köklərdən kənarda müsbətdir: x < −2 və x > 3.',array['x < −2 və x > 3 olduqda','−2 < x < 3 olduqda','Yalnız x > 0 olduqda','Heç vaxt'],1),
('riy9-berabersizlik#7','riy-9-berabersizlik',2,3,'Modulu 4-dən kiçik olan neçə tam ədəd var?','−3-dən 3-ə qədər: 7 tam ədəd.',array['7 tam ədəd','8 tam ədəd','6 tam ədəd','9 tam ədəd'],1),
('riy9-berabersizlik#8','riy-9-berabersizlik',2,3,'|x| > 2 bərabərsizliyini ödəyən ədədlər hansılardır?','Modulu 2-dən böyük: x < −2 və ya x > 2.',array['x < −2 və ya x > 2','−2 < x < 2','Yalnız x > 2','x = ±2'],1),
('riy9-berabersizlik#9','riy-9-berabersizlik',3,3,'|x − 5| ≤ 3 bərabərsizliyinin həlli hansı parçadır?','−3 ≤ x − 5 ≤ 3; 2 ≤ x ≤ 8.',array['2 ≤ x ≤ 8','−3 ≤ x ≤ 3','5 ≤ x ≤ 8','x ≥ 2 yalnız'],1),
('riy9-berabersizlik#10','riy-9-berabersizlik',2,3,'Xətti bərabərsizliklər sisteminin həlli necə tapılır?','Ayrı-ayrı həllərin kəsişməsi götürülür.',array['Həllərin kəsişməsi kimi','Həllərin birləşməsi kimi','Ən böyük həll kimi','Təsadüfi seçimlə'],1),
('riy9-berabersizlik#11','riy-9-berabersizlik',2,3,'x > 2 və x > 5 sisteminin həlli hansıdır?','Hər ikisini ödəyən: x > 5.',array['x > 5','x > 2','2 < x < 5','x < 5'],1),
('riy9-berabersizlik#12','riy-9-berabersizlik',2,3,'x > 1 və x < 4 sisteminin həlli hansı aralıqdır?','Kəsişmə (1; 4) intervalıdır.',array['(1; 4) aralığı','(4; 1) aralığı','x > 4','Boş çoxluq'],1),
('riy9-berabersizlik#13','riy-9-berabersizlik',2,3,'x > 3 və x < 1 sisteminin həlli varmı?','Eyni anda ödəyən ədəd yoxdur - boş çoxluqdur.',array['Yoxdur (boş çoxluqdur)','x = 2','1 < x < 3','Bütün ədədlər'],1),
('riy9-berabersizlik#14','riy-9-berabersizlik',2,3,'−2x < 6 bərabərsizliyini −2-yə bölərkən işarə necə olur?','Mənfiyə bölərkən işarə dəyişir: x > −3.',array['Dəyişib x > −3 alınır','Dəyişmir, x < −3 qalır','x < 3 alınır','Bərabərlik yaranır'],1),
('riy9-berabersizlik#15','riy-9-berabersizlik',2,3,'x² + 1 > 0 bərabərsizliyinin həlli hansıdır?','Kvadrat üstəgəl bir həmişə müsbətdir.',array['Bütün həqiqi ədədlər','Yalnız müsbətlər','Yalnız x > 1','Həlli yoxdur'],1),
('riy9-berabersizlik#16','riy-9-berabersizlik',2,3,'x² ≤ 0 bərabərsizliyini ödəyən yeganə ədəd hansıdır?','Kvadrat yalnız sıfırda sıfra bərabərdir.',array['x = 0','x = 1','x = −1','Belə ədəd yoxdur'],1),
('riy9-berabersizlik#17','riy-9-berabersizlik',3,3,'Kökləri olmayan (D < 0, a > 0) kvadrat üçhədlinin işarəsi necədir?','Parabola oxu kəsmir, qollar yuxarı - həmişə müsbət.',array['Həmişə müsbətdir','Həmişə mənfidir','İşarəsini dəyişir','Sıfırdır'],1),
('riy9-berabersizlik#18','riy-9-berabersizlik',3,3,'İntervallar üsulunda qonşu intervallarda işarələr necə dəyişir?','Sadə köklərdə işarə növbə ilə dəyişir.',array['Növbə ilə (sadə köklərdə)','Heç dəyişmir','Təsadüfi','Yalnız sonda'],1),
('riy9-berabersizlik#19','riy-9-berabersizlik',3,3,'√x < 3 bərabərsizliyinin həlli hansıdır?','Kök üçün x ≥ 0 və x < 9: 0 ≤ x < 9.',array['0 ≤ x < 9','x < 9 yalnız','x < 3','x > 9'],1),
('riy9-berabersizlik#20','riy-9-berabersizlik',2,3,'√x > 2 bərabərsizliyinin həlli hansıdır?','Kvadrata yüksəldək: x > 4.',array['x > 4','x > 2','0 < x < 4','x ≥ 0'],1),
('riy9-berabersizlik#21','riy-9-berabersizlik',3,3,'Bərabərsizliklər heyəti (məcmusu) nə vaxt ödənilir?','Heç olmasa bir bərabərsizlik ödəniləndə.',array['Heç olmasa biri ödəniləndə','Hamısı ödəniləndə','Heç biri ödənilməyəndə','Yalnız ikisi ödəniləndə'],1),
('riy9-berabersizlik#22','riy-9-berabersizlik',2,3,'Üçdə biri 2-dən kiçik olmayan ən kiçik tam ədəd hansıdır?','x/3 ≥ 2; x ≥ 6; ən kiçiyi 6-dır.',array['x = 6','x = 3','x = 2','x = 7'],1),
('riy9-berabersizlik#23','riy-9-berabersizlik',2,3,'2 < x ≤ 7 yazılışı hansı çoxluğu bildirir?','Bir ucu daxil olan yarımintervaldır.',array['Yarımintervalı','Parçanı','İntervalı','Şüanı'],1),
('riy9-berabersizlik#24','riy-9-berabersizlik',3,3,'(x − 4)² > 0 bərabərsizliyi hansı x-lərdə ödənilir?','Kvadrat yalnız x = 4-də sıfırdır, qalan hallarda müsbətdir.',array['x = 4-dən başqa hamısında','Bütün x-lərdə','Yalnız x > 4-də','Heç birində'],1),
('riy9-berabersizlik#25','riy-9-berabersizlik',3,3,'x² − 6x + 9 ≤ 0 bərabərsizliyinin həlli hansıdır?','(x − 3)² ≤ 0 yalnız x = 3-də ödənilir.',array['Yalnız x = 3','x ≤ 3','x ≥ 3','Həlli yoxdur'],1),
('riy9-berabersizlik#26','riy-9-berabersizlik',2,3,'(x − 2)/(x + 3) ifadəsinin işarəsini araşdırarkən hansı nöqtələr qeyd olunur?','Surətin və məxrəcin sıfırları: 2 və −3.',array['2 və −3 nöqtələri','0 və 1 nöqtələri','Yalnız 2 nöqtəsi','Yalnız −3 nöqtəsi'],1),
('riy9-berabersizlik#27','riy-9-berabersizlik',3,3,'(x − 2)/(x + 3) > 0 bərabərsizliyinin həlli hansıdır?','Hər ikisi eyni işarəli olanda: x < −3 və ya x > 2.',array['x < −3 və ya x > 2','−3 < x < 2','x > 2 yalnız','x = −3 daxil hamısı'],1),
('riy9-berabersizlik#28','riy-9-berabersizlik',2,3,'|x| ≤ a (a müsbətdir) bərabərsizliyi nəyə çevrilir?','İkiqat bərabərsizliyə: −a ≤ x ≤ a.',array['−a ≤ x ≤ a ikiqat bərabərsizliyinə','x ≤ a yalnız','x ≥ −a yalnız','Bərabərliyə'],1),
('riy9-berabersizlik#29','riy-9-berabersizlik',1,3,'5 − x > 0 bərabərsizliyinin həlli hansıdır?','x tərəfə keçirək: x < 5.',array['x < 5','x > 5','x < −5','x ≥ 5'],1),
('riy9-berabersizlik#30','riy-9-berabersizlik',2,3,'(2; 6) intervalına neçə tam ədəd düşür?','3, 4 və 5 - cəmi 3 tam ədəd.',array['3 tam ədəd','4 tam ədəd','5 tam ədəd','2 tam ədəd'],1),
('riy9-berabersizlik#31','riy-9-berabersizlik',3,3,'x² < 16 bərabərsizliyinə neçə tam ədəd həll daxildir?','−3-dən 3-ə qədər: 7 tam ədəd.',array['7 tam ədəd','8 tam ədəd','6 tam ədəd','4 tam ədəd'],1),
('riy9-berabersizlik#32','riy-9-berabersizlik',1,3,'Bərabərsizliyin həlli çoxluğu boşdursa, bu nə deməkdir?','Onu ödəyən heç bir ədəd yoxdur.',array['Heç bir ədəd ödəmir','Hər ədəd ödəyir','Yalnız sıfır ödəyir','Səhv var'],1),
('riy9-berabersizlik#33','riy-9-berabersizlik',2,3,'7 > 4 və 4 > 1 münasibətlərindən 7 ilə 1 üçün hansı nəticə çıxır?','Tranzitivliyə görə 7 > 1.',array['7 > 1 (tranzitivlik)','7 < 1','7 = 1','Nəticə çıxmır'],1),
('riy9-berabersizlik#34','riy-9-berabersizlik',3,3,'√(x − 1) ≤ 2 bərabərsizliyinin həlli hansıdır?','x − 1 ≥ 0 və x − 1 ≤ 4: 1 ≤ x ≤ 5.',array['1 ≤ x ≤ 5','x ≤ 5 yalnız','x ≥ 1 yalnız','1 < x < 4'],1),
('riy9-berabersizlik#35','riy-9-berabersizlik',2,3,'Kvadrat bərabərsizliyin həllində parabola nədən kömək edir?','Qolların istiqamətini və kökləri əyani göstərir.',array['Qolların istiqamətini və kökləri göstərir','Perimetri hesablayır','Modulu tapır','Kömək etmir'],1),
('riy9-berabersizlik#36','riy-9-berabersizlik',2,3,'−3 ≤ x < 2 aralığında ən kiçik tam ədəd hansıdır?','Sol uc daxildir: −3.',array['−3','−2','0','2'],1),
('riy9-berabersizlik#37','riy-9-berabersizlik',1,3,'4x − 8 ≤ 0 bərabərsizliyinin həlli hansıdır?','4x ≤ 8; x ≤ 2.',array['x ≤ 2','x ≥ 2','x ≤ −2','x < 8'],1),
('riy9-berabersizlik#38','riy-9-berabersizlik',1,3,'x² ≥ 0 bərabərsizliyi hansı x-lərdə doğrudur?','Kvadrat heç vaxt mənfi olmur.',array['Bütün x-lərdə','Yalnız müsbətlərdə','Yalnız x = 0-da','Heç birində'],1),
('riy9-berabersizlik#39','riy-9-berabersizlik',3,3,'1 < 2x − 3 < 7 ikiqat bərabərsizliyini həll edin.','4 < 2x < 10; 2 < x < 5.',array['2 < x < 5','1 < x < 7','4 < x < 10','−2 < x < 5'],1),
('riy9-berabersizlik#40','riy-9-berabersizlik',2,3,'Bərabərsizliklər sistemi ədəd oxunda necə həll olunur?','Hər həll oxda göstərilir, ortaq hissə götürülür.',array['Hər həllin oxda kəsişməsi tapılır','Oxda hamısı birləşdirilir','Ox işlədilmir','Yalnız uclar götürülür'],1),
('riy9-vektorlar#1','riy-9-vektorlar',1,3,'Vektor nədir?','İstiqamətə malik düz xətt parçasıdır.',array['İstiqamətə malik parça','İxtiyari əyri','Yalnız ədəd','Bucaq növü'],1),
('riy9-vektorlar#2','riy-9-vektorlar',1,3,'Başlanğıcı və sonu üst-üstə düşən vektor necə adlanır?','Belə vektor sıfır vektordur.',array['Sıfır vektor','Vahid vektor','Əks vektor','Kollinear vektor'],1),
('riy9-vektorlar#3','riy-9-vektorlar',2,3,'A(1; 2) və B(4; 6) üçün AB vektorunun koordinatları hansılardır?','Sondan başlanğıc çıxılır: (4−1; 6−2) = (3; 4).',array['(3; 4)','(5; 8)','(−3; −4)','(4; 3)'],1),
('riy9-vektorlar#4','riy-9-vektorlar',2,3,'Koordinatları (3; 4) olan vektorun modulu neçədir?','√(9 + 16) = √25 = 5.',array['5-ə bərabərdir','7-yə bərabərdir','12-yə bərabərdir','25-ə bərabərdir'],1),
('riy9-vektorlar#5','riy-9-vektorlar',2,3,'Kollinear vektorlar hansılardır?','Paralel düz xətlər üzərində yerləşən vektorlardır.',array['Paralel düz xətlər üzərində yerləşən vektorlar','Perpendikulyar vektorlar','Bərabər olmayan vektorlar','Yalnız əks vektorlar'],1),
('riy9-vektorlar#6','riy-9-vektorlar',2,3,'a(2; 5) və b(4; 10) vektorları kollineardırmı?','b = 2a olduğundan kollineardırlar.',array['Bəli, b = 2a','Xeyr','Yalnız modulca','Müəyyən etmək olmur'],1),
('riy9-vektorlar#7','riy-9-vektorlar',2,3,'Əks vektorlar hansı vektorlardır?','Modulları bərabər, istiqamətləri əks olanlar.',array['Modulları bərabər, istiqamətləri əks','Modulları fərqli, istiqamətləri eyni','Perpendikulyar olanlar','Başlanğıcları eyni olanlar'],1),
('riy9-vektorlar#8','riy-9-vektorlar',2,3,'a(1; 3) və b(2; −1) vektorlarının cəminin koordinatları hansılardır?','(1+2; 3−1) = (3; 2).',array['(3; 2)','(3; 4)','(−1; 4)','(2; −3)'],1),
('riy9-vektorlar#9','riy-9-vektorlar',2,3,'a(5; 7) və b(2; 3) üçün a − b fərqinin koordinatları hansılardır?','(5−2; 7−3) = (3; 4).',array['(3; 4)','(7; 10)','(−3; −4)','(3; 10)'],1),
('riy9-vektorlar#10','riy-9-vektorlar',2,3,'Vektorların toplanmasında üçbucaq qaydası nədir?','Birinin sonuna digərinin başlanğıcı qoyulur.',array['Birinin sonuna digərinin başlanğıcı qoyulur','Başlanğıclar birləşdirilir','Sonlar birləşdirilir','Modullar toplanır yalnız'],1),
('riy9-vektorlar#11','riy-9-vektorlar',2,3,'Paraleloqram qaydası hansı halda istifadə olunur?','Ümumi başlanğıclı iki vektorun cəmini tapmaq üçün.',array['Ümumi başlanğıclı vektorların cəmi üçün','Vektoru ədədə vurmaq üçün','Modulu tapmaq üçün','Perpendikulyarlıq yoxlamaq üçün'],1),
('riy9-vektorlar#12','riy-9-vektorlar',2,3,'3 · a(2; −1) hasilinin koordinatları hansılardır?','(3·2; 3·(−1)) = (6; −3).',array['(6; −3)','(6; 3)','(5; 2)','(2; −3)'],1),
('riy9-vektorlar#13','riy-9-vektorlar',2,3,'Vektoru mənfi ədədə vuranda istiqaməti necə olur?','İstiqamət əksinə dönür.',array['Əksinə dönür','Dəyişmir','Perpendikulyar olur','Sıfırlanır'],1),
('riy9-vektorlar#14','riy-9-vektorlar',1,3,'Vahid vektor hansı vektordur?','Uzunluğu vahidə bərabər olan vektordur.',array['Uzunluğu 1 olan vektor','Ən uzun vektor','Sıfır vektor','Üfüqi vektor'],1),
('riy9-vektorlar#15','riy-9-vektorlar',2,3,'Bərabər vektorlar hansı şərtləri ödəməlidir?','Həm modulları, həm istiqamətləri eyni olmalıdır.',array['Modulları və istiqamətləri eyni olmalıdır','Yalnız modulları eyni olmalıdır','Yalnız başlanğıcları eyni olmalıdır','Heç bir şərt yoxdur'],1),
('riy9-vektorlar#16','riy-9-vektorlar',2,3,'a(0; 8) vektorunun modulu neçədir?','√(0 + 64) = 8.',array['8-ə bərabərdir','0-a bərabərdir','64-ə bərabərdir','4-ə bərabərdir'],1),
('riy9-vektorlar#17','riy-9-vektorlar',2,3,'Başlanğıcdan M(6; 8) nöqtəsinə yönələn vektorun modulu neçədir?','√(36 + 64) = √100 = 10.',array['10-a bərabərdir','14-ə bərabərdir','48-ə bərabərdir','100-ə bərabərdir'],1),
('riy9-vektorlar#18','riy-9-vektorlar',2,3,'Paralel köçürmə nədir?','Bütün nöqtələrin eyni vektor qədər sürüşdürülməsidir.',array['Bütün nöqtələrin eyni vektor qədər sürüşdürülməsi','Fiqurun fırladılması','Fiqurun böyüdülməsi','Fiqurun əks olunması'],1),
('riy9-vektorlar#19','riy-9-vektorlar',1,3,'Paralel köçürmədə fiqurun ölçüləri necə dəyişir?','Hərəkətdir - ölçülər dəyişmir.',array['Dəyişmir','İki dəfə artır','Azalır','Formadan asılıdır'],1),
('riy9-vektorlar#20','riy-9-vektorlar',2,3,'Konqruyent fiqurlar hansılardır?','Hərəkətlə üst-üstə düşən fiqurlardır.',array['Hərəkətlə üst-üstə düşən fiqurlar','Sahələri fərqli fiqurlar','Yalnız çevrələr','Oxşar, lakin fərqli ölçülü fiqurlar'],1),
('riy9-vektorlar#21','riy-9-vektorlar',3,3,'Vektorun meyil bucağı hansı oxdan ölçülür?','Müsbət absis oxundan ölçülür.',array['Müsbət Ox oxu ilə','Oy oxu ilə','İxtiyari düz xətlə','Ölçülmür'],1),
('riy9-vektorlar#22','riy-9-vektorlar',3,3,'Modulu |a|, meyil bucağı α olan vektorun absis komponenti hansı düsturla tapılır?','x komponenti |a| · cos α-dır.',array['|a| · cos α','|a| · sin α','|a| · tan α','|a| + cos α'],1),
('riy9-vektorlar#23','riy-9-vektorlar',2,3,'a(4; 0) vektoru hansı ox boyunca yönəlib?','Ordinatı sıfırdır - absis oxu boyunca.',array['Absis oxu boyunca','Ordinat oxu boyunca','Heç bir ox boyunca','Hər iki ox boyunca'],1),
('riy9-vektorlar#24','riy-9-vektorlar',2,3,'İki vektorun cəmi sıfır vektordursa, onlar necə vektorlardır?','Belə vektorlar əks vektorlardır.',array['Əks vektorlardır','Perpendikulyardırlar','Hər ikisi vahiddir','Kollinear deyillər'],1),
('riy9-vektorlar#25','riy-9-vektorlar',2,3,'a(1; 2) və b(3; 6) üçün b − a fərqi hansıdır?','(3−1; 6−2) = (2; 4).',array['(2; 4)','(4; 8)','(−2; −4)','(3; 12)'],1),
('riy9-vektorlar#26','riy-9-vektorlar',2,3,'Kollinear olmayan vektorların cəmi hansı qaydalarla tapılır?','Üçbucaq və ya paraleloqram qaydası ilə.',array['Üçbucaq və ya paraleloqram qaydası ilə','Yalnız modullar toplanmaqla','Çıxma ilə','Tapıla bilmir'],1),
('riy9-vektorlar#27','riy-9-vektorlar',2,3,'k · a vektoru a ilə nə vaxt eyni istiqamətli olur?','k müsbət olduqda istiqamət saxlanılır.',array['k müsbət olduqda','k mənfi olduqda','k sıfır olduqda','Heç vaxt'],1),
('riy9-vektorlar#28','riy-9-vektorlar',2,3,'AB və BA vektorları haqqında nə demək olar?','Modulları bərabər, istiqamətləri əksdir.',array['Bir-birinin əksidir','Bərabərdirlər','Perpendikulyardırlar','Kollinear deyillər'],1),
('riy9-vektorlar#29','riy-9-vektorlar',2,3,'Hərəkət (həndəsi çevirmə) fiqurun nəyini saxlayır?','Nöqtələr arasındakı məsafələri saxlayır.',array['Nöqtələr arasındakı məsafələri','Yalnız rəngini','Yalnız adını','Heç nəyi'],1),
('riy9-vektorlar#30','riy-9-vektorlar',3,3,'Paralel köçürmə A(2; 1) nöqtəsini (5; 3)-ə aparıb. Köçürmə vektoru hansıdır?','(5−2; 3−1) = (3; 2).',array['(3; 2)','(7; 4)','(2; 3)','(−3; −2)'],1),
('riy9-vektorlar#31','riy-9-vektorlar',1,3,'Fizikada vektorlarla hansı kəmiyyətlər göstərilir?','Qüvvə, sürət kimi istiqamətli kəmiyyətlər.',array['Qüvvə və sürət kimi kəmiyyətləri','Yalnız kütlə','Yalnız zaman','Temperatur'],1),
('riy9-vektorlar#32','riy-9-vektorlar',2,3,'Sıfır vektorun istiqaməti necədir?','Sıfır vektorun istiqaməti təyin olunmur.',array['Təyin olunmur','Həmişə sağa','Həmişə yuxarı','Ox oxu boyunca'],1),
('riy9-vektorlar#33','riy-9-vektorlar',2,3,'a(−2; 7) vektorunun əks vektoru hansıdır?','Koordinatların işarələri dəyişir: (2; −7).',array['(2; −7)','(−2; −7)','(7; −2)','(2; 7)'],1),
('riy9-vektorlar#34','riy-9-vektorlar',3,3,'İki kollinear vektorun koordinatları arasında hansı münasibət var?','Uyğun koordinatlar mütənasibdir.',array['Mütənasibdirlər','Bərabərdirlər həmişə','Cəmi sıfırdır','Münasibət yoxdur'],1),
('riy9-vektorlar#35','riy-9-vektorlar',2,3,'Vektorların komponentlərlə toplanması necə aparılır?','Uyğun koordinatlar toplanır.',array['Uyğun koordinatlar toplanır','Modullar vurulur','Bucaqlar toplanır','Koordinatlar vurulur'],1),
('riy9-vektorlar#36','riy-9-vektorlar',3,3,'|a| = 3, |b| = 4 və vektorlar perpendikulyardır. Cəmin modulu neçədir?','√(9 + 16) = 5.',array['Modulu 5-dir','Modulu 7-dir','Modulu 1-dir','Modulu 12-dir'],1),
('riy9-vektorlar#37','riy-9-vektorlar',2,3,'M(x; y) nöqtəsi a(p; q) vektoru ilə köçürülərsə, yeni koordinatlar hansılardır?','Koordinatlara komponentlər əlavə olunur.',array['(x + p; y + q)','(x − p; y − q)','(xp; yq)','(p; q)'],1),
('riy9-vektorlar#38','riy-9-vektorlar',1,3,'Vektorun uzunluğu mənfi ola bilərmi?','Modul məsafədir - mənfi olmur.',array['Xeyr, modul mənfi olmur','Bəli, hər qiymət alır','Yalnız əks vektorlarda','Yalnız sıfır vektorda'],1),
('riy9-vektorlar#39','riy-9-vektorlar',2,3,'2a + 3a cəmi hansı vektordur?','Eyni vektorun əmsalları toplanır: 5a.',array['5a','6a','a','5a²'],1),
('riy9-vektorlar#40','riy-9-vektorlar',3,3,'Dönmə və simmetriya hansı çevirmələrin növləridir?','Onlar hərəkətin (məsafə saxlayan çevirmənin) növləridir.',array['Hərəkətin (çevirmənin)','Proyeksiyanın','Ölçmə üsullarının','Heç nəyin'],1),
('riy9-silsile#1','riy-9-silsile',1,4,'Ədədi ardıcıllıq nədir?','Müəyyən qayda ilə nömrələnib düzülmüş ədədlər sırasıdır.',array['Müəyyən qayda ilə düzülmüş ədədlər sırası','İxtiyari hərflər yığını','Yalnız cüt ədədlər','Həndəsi fiqurlar sırası'],1),
('riy9-silsile#2','riy-9-silsile',1,4,'3; 7; 11; 15; ... ardıcıllığında növbəti hədd neçədir?','Hər hədd 4 artır: 15 + 4 = 19.',array['19','18','20','16'],1),
('riy9-silsile#3','riy-9-silsile',2,4,'Ədədi silsilə hansı ardıcıllıqdır?','Qonşu hədlərin fərqi sabit olan ardıcıllıqdır.',array['Qonşu hədlərin fərqi sabit olan','Qonşu hədlərin nisbəti sabit olan','Azalan istənilən sıra','Təsadüfi ədədlər sırası'],1),
('riy9-silsile#4','riy-9-silsile',1,4,'Ədədi silsilədə d hərfi nəyi bildirir?','d silsilənin fərqidir.',array['Silsilənin fərqini','İlk həddi','Hədlərin sayını','Cəmi'],1),
('riy9-silsile#5','riy-9-silsile',2,4,'İlk həddi 5, fərqi 3 olan ədədi silsilənin dördüncü həddi neçədir?','a₄ = 5 + 3 · 3 = 14.',array['14','11','17','20'],1),
('riy9-silsile#6','riy-9-silsile',2,4,'Ədədi silsilənin n-ci həddinin düsturu hansıdır?','aₙ = a₁ + (n − 1)d.',array['aₙ = a₁ + (n − 1)d','aₙ = a₁ · dⁿ','aₙ = n · d','aₙ = a₁ − nd'],1),
('riy9-silsile#7','riy-9-silsile',2,4,'2; 5; 8; ... silsiləsinin onuncu həddi neçədir?','a₁₀ = 2 + 9 · 3 = 29.',array['29','26','32','30'],1),
('riy9-silsile#8','riy-9-silsile',2,4,'İlk həddi 10, fərqi −2 olan ədədi silsilə necə silsilədir?','Fərq mənfidir - hədlər azalır.',array['Azalan silsilə','Artan silsilə','Sabit silsilə','Həndəsi silsilə'],1),
('riy9-silsile#9','riy-9-silsile',3,4,'Ədədi silsilədə hər hədd qonşu hədlərin nəyidir?','Ortadakı hədd qonşuların ədədi ortasıdır.',array['Ədədi ortasıdır','Hasilinin köküdür','Cəmidir','Fərqidir'],1),
('riy9-silsile#10','riy-9-silsile',2,4,'Ədədi silsilənin ilk n həddinin cəmi düsturu hansıdır?','Sₙ = (a₁ + aₙ) · n / 2.',array['Sₙ = (a₁ + aₙ) · n / 2','Sₙ = a₁ · n','Sₙ = aₙ − a₁','Sₙ = (a₁ · aₙ) / 2'],1),
('riy9-silsile#11','riy-9-silsile',3,4,'1-dən 100-ə qədər natural ədədlərin cəmi neçədir?','S = (1 + 100) · 100 / 2 = 5050.',array['5050','5000','10100','4950'],1),
('riy9-silsile#12','riy-9-silsile',3,4,'İlk həddi 4, fərqi 5 olan silsilənin ilk 10 həddinin cəmi neçədir?','S₁₀ = (2·4 + 9·5) · 10/2 = 53 · 5 = 265.',array['265','245','530','225'],1),
('riy9-silsile#13','riy-9-silsile',2,4,'Həndəsi silsilə hansı ardıcıllıqdır?','Qonşu hədlərin nisbəti sabit olan ardıcıllıqdır.',array['Qonşu hədlərin nisbəti sabit olan','Qonşu hədlərin fərqi sabit olan','Yalnız artan sıra','Kvadratlar sırası'],1),
('riy9-silsile#14','riy-9-silsile',1,4,'Həndəsi silsilədə q hərfi nəyi bildirir?','q silsilənin vuruğudur (məxrəcidir).',array['Silsilənin vuruğunu (məxrəcini)','İlk həddi','Hədlərin cəmini','Fərqi'],1),
('riy9-silsile#15','riy-9-silsile',2,4,'İlk həddi 2, vuruğu 3 olan həndəsi silsilənin dördüncü həddi neçədir?','b₄ = 2 · 3³ = 54.',array['54','18','24','162'],1),
('riy9-silsile#16','riy-9-silsile',2,4,'Həndəsi silsilənin n-ci həddinin düsturu hansıdır?','bₙ = b₁ · qⁿ⁻¹.',array['bₙ = b₁ · qⁿ⁻¹','bₙ = b₁ + (n−1)q','bₙ = qⁿ','bₙ = b₁ · n'],1),
('riy9-silsile#17','riy-9-silsile',2,4,'5; 10; 20; 40; ... silsiləsinin vuruğu neçədir?','10 : 5 = 2.',array['q = 2','q = 5','q = 10','q = 1/2'],1),
('riy9-silsile#18','riy-9-silsile',3,4,'Həndəsi silsilədə hər həddin kvadratı nəyə bərabərdir?','Qonşu hədlərin hasilinə bərabərdir.',array['Qonşu hədlərin hasilinə','Qonşuların cəminə','Fərqlərin kvadratına','Vuruğa'],1),
('riy9-silsile#19','riy-9-silsile',3,4,'İlk həddi 81, vuruğu 1/3 olan silsilənin üçüncü həddi neçədir?','b₃ = 81 · (1/3)² = 81/9 = 9.',array['9-a bərabərdir','27-yə bərabərdir','3-ə bərabərdir','1-ə bərabərdir'],1),
('riy9-silsile#20','riy-9-silsile',2,4,'Sonsuz azalan həndəsi silsilə hansı şərtlə olur?','Vuruğun modulu vahiddən kiçik olmalıdır.',array['|q| < 1 olduqda','|q| > 1 olduqda','q = 1 olduqda','q = 0 olduqda yalnız'],1),
('riy9-silsile#21','riy-9-silsile',3,4,'Sonsuz azalan həndəsi silsilənin cəmi hansı düsturla tapılır?','S = b₁ / (1 − q).',array['S = b₁/(1 − q)','S = b₁ · (1 − q)','S = b₁/(1 + q)','S = q/b₁'],1),
('riy9-silsile#22','riy-9-silsile',3,4,'İlk həddi 6, vuruğu 1/2 olan sonsuz silsilənin cəmi neçədir?','S = 6 / (1 − 1/2) = 12.',array['Cəmi 12-dir','Cəmi 6-dır','Cəmi 3-dür','Cəmi 24-dür'],1),
('riy9-silsile#23','riy-9-silsile',3,4,'0,(6) dövri kəsri hansı adi kəsrə bərabərdir?','0,(6) = 6/9 = 2/3.',array['2/3','3/2','6/10','1/6'],1),
('riy9-silsile#24','riy-9-silsile',2,4,'1; 4; 9; 16; ... ardıcıllığının qaydası nədir?','Hədlər natural ədədlərin kvadratlarıdır.',array['Natural ədədlərin kvadratları','Cüt ədədlər','Sadə ədədlər','Fərqi 3 olan silsilə'],1),
('riy9-silsile#25','riy-9-silsile',2,4,'7; 7; 7; ... ardıcıllığı hansı silsilədir?','Fərqi sıfır olan sabit silsilədir.',array['d = 0 olan sabit silsilə','Artan silsilə','Azalan silsilə','Silsilə deyil'],1),
('riy9-silsile#26','riy-9-silsile',2,4,'a₅ = 20 və a₆ = 26 olan ədədi silsilənin fərqi neçədir?','d = 26 − 20 = 6.',array['d = 6','d = 46','d = 5','d = −6'],1),
('riy9-silsile#27','riy-9-silsile',3,4,'Ədədi silsilədə a₁ = 3 və a₃ = 11-dirsə, fərq neçədir?','a₃ = a₁ + 2d; 2d = 8; d = 4.',array['d = 4','d = 8','d = 2','d = 11'],1),
('riy9-silsile#28','riy-9-silsile',3,4,'3; 6; 12; ... həndəsi silsiləsinin ilk 5 həddinin cəmi neçədir?','3 + 6 + 12 + 24 + 48 = 93.',array['93','45','96','63'],1),
('riy9-silsile#29','riy-9-silsile',2,4,'Həddi aₙ = 2n + 1 düsturu ilə verilən ardıcıllığın səkkizinci həddi neçədir?','a₈ = 2 · 8 + 1 = 17.',array['17','16','15 deyil, çünki n = 7 deyil','19'],1),
('riy9-silsile#30','riy-9-silsile',2,4,'Aşağıdakılardan hansı həndəsi silsilədir?','2; 6; 18; 54 - hər hədd 3 dəfə artır.',array['2; 6; 18; 54','2; 4; 6; 8','1; 2; 4; 7','5; 10; 15; 20'],1),
('riy9-silsile#31','riy-9-silsile',2,4,'İlk həddi 100, fərqi −7 olan silsilənin beşinci həddi neçədir?','a₅ = 100 − 4 · 7 = 72.',array['72','65','79','93'],1),
('riy9-silsile#32','riy-9-silsile',3,4,'Bankda illik faizlə artan məbləğ hansı silsilə üzrə artır?','Hər il eyni vuruqla artır - həndəsi silsilə.',array['Həndəsi silsilə üzrə','Ədədi silsilə üzrə','Sabit qalır','Qaydasız artır'],1),
('riy9-silsile#33','riy-9-silsile',2,4,'Bərabər hündürlüklü pillələrlə qalxma hündürlükləri hansı silsiləni əmələ gətirir?','Hər pillədə eyni qədər artır - ədədi silsilə.',array['Ədədi silsilə','Həndəsi silsilə','Sonsuz silsilə','Heç bir silsilə'],1),
('riy9-silsile#34','riy-9-silsile',2,4,'b₃ = 12 və b₄ = 24 olan həndəsi silsilənin vuruğu neçədir?','q = 24 : 12 = 2.',array['q = 2','q = 12','q = 36','q = 1/2'],1),
('riy9-silsile#35','riy-9-silsile',2,4,'10; 7; 4; 1; ... silsiləsinin fərqi neçədir?','7 − 10 = −3.',array['d = −3','d = 3','d = −7','d = 10'],1),
('riy9-silsile#36','riy-9-silsile',1,4,'aₙ = a₁ + (n − 1)d düsturunda n nəyi göstərir?','n həddin sıra nömrəsidir.',array['Həddin nömrəsini','Fərqi','Cəmi','Vuruğu'],1),
('riy9-silsile#37','riy-9-silsile',3,4,'İki ədədin arasına onların ədədi ortası yazılarsa, üçlük nə əmələ gətirir?','Alınan üç ədəd ədədi silsilə təşkil edir.',array['Ədədi silsilə təşkil edir','Həndəsi silsilə olur','Təsadüfi sıra olur','Heç nə'],1),
('riy9-silsile#38','riy-9-silsile',2,4,'Hədləri müsbət olan həndəsi silsilədə q > 1 olarsa, silsilə necədir?','Hər hədd əvvəlkindən böyükdür - artandır.',array['Artandır','Azalandır','Sabitdir','Sonludur'],1),
('riy9-silsile#39','riy-9-silsile',3,4,'1 + 1/2 + 1/4 + 1/8 + ... cəmi hansı ədədə yaxınlaşır?','S = 1/(1 − 1/2) = 2.',array['Cəm 2-yə yaxınlaşır','Cəm 1-ə yaxınlaşır','Sonsuzluğa gedir','Cəm 4-ə yaxınlaşır'],1),
('riy9-silsile#40','riy-9-silsile',2,4,'Ədədi silsilənin ilk 20 həddinin cəmini tapmaq üçün nələri bilmək kifayətdir?','İlk hədd və fərq kifayətdir.',array['İlk həddi və fərqi','Yalnız son həddi','Bütün hədləri əzbər','Vuruğu'],1),
('riy9-ehtimal#1','riy-9-ehtimal',1,4,'Tezlik paylanması cədvəlinin hər sətrində nələr yazılır?','Qiymət və onun neçə dəfə rast gəlindiyi (tezliyi).',array['Qiymət və onun tezliyi','Yalnız qiymətlər','Yalnız cəmlər','Sıra nömrələri yalnız'],1),
('riy9-ehtimal#2','riy-9-ehtimal',2,4,'Nisbi tezlik necə hesablanır?','Tezlik ümumi müşahidə sayına bölünür.',array['Tezliyin ümumi saya nisbəti kimi','Tezliklərin hasili kimi','Ən böyük tezlik kimi','Cəmlərin fərqi kimi'],1),
('riy9-ehtimal#3','riy-9-ehtimal',2,4,'Tezlik histoqramı nədir?','Tezliklərin sütunlu diaqramla təsviridir.',array['Tezliklərin sütunlarla təsviri','Dairəvi cədvəl','Ədədlərin siyahısı','Xəritə növü'],1),
('riy9-ehtimal#4','riy-9-ehtimal',2,4,'Tezlik poliqonu necə qurulur?','Tezlik nöqtələri sınıq xətlə birləşdirilir.',array['Tezlik nöqtələrini birləşdirməklə','Sütunları rəngləməklə','Dairə bölməklə','Cədvəl çəkməklə'],1),
('riy9-ehtimal#5','riy-9-ehtimal',2,4,'2; 3; 3; 4; 8 sırasının ədədi ortası neçədir?','(2+3+3+4+8)/5 = 20/5 = 4.',array['4-ə bərabərdir','3-ə bərabərdir','5-ə bərabərdir','8-ə bərabərdir'],1),
('riy9-ehtimal#6','riy-9-ehtimal',2,4,'4 kitabı rəfə neçə müxtəlif üsulla düzmək olar?','P₄ = 4! = 24.',array['24 üsulla','16 üsulla','12 üsulla','4 üsulla'],1),
('riy9-ehtimal#7','riy-9-ehtimal',2,4,'5 nəfər növbəyə neçə üsulla düzülə bilər?','P₅ = 5! = 120.',array['120 üsulla','25 üsulla','60 üsulla','5 üsulla'],1),
('riy9-ehtimal#8','riy-9-ehtimal',2,4,'n elementin yerdəyişmələrinin sayı hansı düsturla tapılır?','Pₙ = n! (n faktorial).',array['n! (n faktorial)','n²','2n','n + 1'],1),
('riy9-ehtimal#9','riy-9-ehtimal',3,4,'0! (sıfır faktorial) neçəyə bərabərdir?','Tərifə görə 0! = 1.',array['1-ə bərabərdir','0-a bərabərdir','Təyin olunmur','Sonsuzdur'],1),
('riy9-ehtimal#10','riy-9-ehtimal',3,4,'Təkrarlı permutasiya nə vaxt istifadə olunur?','Elementlər arasında eyniləri olduqda.',array['Eyni elementlər olduqda','Elementlər az olduqda','Sıra vacib olmayanda','Heç vaxt'],1),
('riy9-ehtimal#11','riy-9-ehtimal',3,4,'ANA sözünün hərflərindən neçə müxtəlif düzülüş almaq olar?','3!/2! = 3 (iki A eynidir).',array['3 düzülüş','6 düzülüş','9 düzülüş','2 düzülüş'],1),
('riy9-ehtimal#12','riy-9-ehtimal',3,4,'Yerləşdirmənin yerdəyişmədən fərqi nədir?','Yerləşdirmədə elementlərin yalnız bir hissəsi seçilib düzülür.',array['Yerləşdirmədə elementlərin bir hissəsi seçilir','Fərq yoxdur','Yerləşdirmədə sıra vacib deyil','Yerdəyişmə yalnız hərflər üçündür'],1),
('riy9-ehtimal#13','riy-9-ehtimal',3,4,'5 elementdən 2-sinin yerləşdirmələrinin sayı neçədir?','A(5,2) = 5 · 4 = 20.',array['20 yerləşdirmə','10 yerləşdirmə','25 yerləşdirmə','7 yerləşdirmə'],1),
('riy9-ehtimal#14','riy-9-ehtimal',2,4,'Kombinezon (C) nə vaxt işlədilir?','Seçimdə sıra vacib olmayanda.',array['Sıra vacib olmayanda','Sıra vacib olanda','Elementlər eyni olanda','Yalnız ədədlərdə'],1),
('riy9-ehtimal#15','riy-9-ehtimal',3,4,'6 nəfərdən 2 nəfərlik komanda neçə üsulla seçilə bilər?','C(6,2) = 15.',array['15 üsulla','30 üsulla','12 üsulla','36 üsulla'],1),
('riy9-ehtimal#16','riy-9-ehtimal',2,4,'C(5, 5) neçəyə bərabərdir?','Hamısını seçməyin bir yolu var.',array['1 (yeganə üsul)','5','25','120'],1),
('riy9-ehtimal#17','riy-9-ehtimal',2,4,'Klassik ehtimal hansı nisbətlə hesablanır?','Əlverişli halların sayı bütün halların sayına bölünür.',array['Əlverişli halların sayının bütün hallara nisbəti','Bütün halların əlverişlilərə nisbəti','Halların cəmi ilə','Halların fərqi ilə'],1),
('riy9-ehtimal#18','riy-9-ehtimal',2,4,'Ehtimalın qiyməti hansı aralıqda dəyişir?','Ehtimal 0 ilə 1 arasında olur.',array['0 ilə 1 arasında','−1 ilə 1 arasında','0 ilə 100 arasında yalnız tam','1-dən böyük'],1),
('riy9-ehtimal#19','riy-9-ehtimal',1,4,'Qutuda yalnız ağ kürəciklər var. Qara kürəcik çıxarma ehtimalı neçədir?','Belə hadisə mümkün deyil - ehtimal sıfırdır.',array['Sıfırdır','Vahiddir','Yarımdır','Mənfidir'],1),
('riy9-ehtimal#20','riy-9-ehtimal',1,4,'Yəqin hadisənin ehtimalı neçəyə bərabərdir?','Mütləq baş verən hadisə üçün P = 1.',array['1-ə bərabərdir','0-a bərabərdir','0,5-ə bərabərdir','2-yə bərabərdir'],1),
('riy9-ehtimal#21','riy-9-ehtimal',2,4,'Qutuda 4 qırmızı və 6 göy kürəcik var. Qırmızı çıxarma ehtimalı neçədir?','P = 4/10 = 2/5.',array['2/5','3/5','4/6','1/4'],1),
('riy9-ehtimal#22','riy-9-ehtimal',2,4,'Kartlar 1-dən 9-a qədər nömrələnib. Təsadüfi kartın 5-ə bölünməsi ehtimalı neçədir?','Yalnız 5 uyğundur: P = 1/9.',array['1/9','5/9','1/5','2/9'],1),
('riy9-ehtimal#23','riy-9-ehtimal',2,4,'Hadisə ilə əks hadisənin ehtimallarının cəmi neçədir?','P(A) + P(Ā) = 1.',array['Cəmi 1 olur','Cəmi 0 olur','Cəmi 2 olur','Cəm dəyişkəndir'],1),
('riy9-ehtimal#24','riy-9-ehtimal',2,4,'P(A) = 0,45 olduqda əks hadisənin ehtimalını tapın.','P(Ā) = 1 − 0,45 = 0,55.',array['0,55','0,45','0,65','1,45'],1),
('riy9-ehtimal#25','riy-9-ehtimal',3,4,'Tezlik paylanmasına görə ədədi orta necə tapılır?','Qiymət-tezlik hasillərinin cəmi ümumi saya bölünür.',array['Qiymət-tezlik hasilləri cəmi ümumi saya bölünür','Ən böyük qiymət götürülür','Tezliklər vurulur','Qiymətlər çıxılır'],1),
('riy9-ehtimal#26','riy-9-ehtimal',2,4,'20 şagirddən 5-i əlaçıdır. Təsadüfi şagirdin əlaçı olması ehtimalı neçədir?','P = 5/20 = 1/4.',array['1/4','1/5','1/20','3/4'],1),
('riy9-ehtimal#27','riy-9-ehtimal',2,4,'C(n, 1) neçəyə bərabərdir?','n elementdən birini n üsulla seçmək olar.',array['n-ə bərabərdir','1-ə bərabərdir','n!-ə bərabərdir','0-a bərabərdir'],1),
('riy9-ehtimal#28','riy-9-ehtimal',2,4,'Sikkə iki dəfə atılır. Neçə müxtəlif nəticə mümkündür?','2 · 2 = 4 nəticə.',array['4 nəticə','2 nəticə','3 nəticə','8 nəticə'],1),
('riy9-ehtimal#29','riy-9-ehtimal',2,4,'1, 2, 3 rəqəmlərindən təkrarsız neçə üçrəqəmli ədəd düzəltmək olar?','3! = 6 ədəd.',array['6 ədəd','9 ədəd','3 ədəd','27 ədəd'],1),
('riy9-ehtimal#30','riy-9-ehtimal',2,4,'Verilənlər sırasında moda hansı qiymətdir?','Ən çox təkrarlanan qiymətdir.',array['Ən çox təkrarlanan qiymət','Ən böyük qiymət','Ortadakı qiymət','İlk qiymət'],1),
('riy9-ehtimal#31','riy-9-ehtimal',2,4,'Sıralanmış 1; 3; 5; 9; 11 sırasının medianı neçədir?','Ortadakı (üçüncü) hədd 5-dir.',array['5-dir','3-dür','9-dur','6-dır'],1),
('riy9-ehtimal#32','riy-9-ehtimal',3,4,'Nisbi tezliklərin cəmi neçəyə bərabərdir?','Bütün nisbi tezliklərin cəmi vahiddir.',array['Vahidə bərabərdir','Sıfra bərabərdir','Müşahidələrin sayına','Yüzə bərabərdir hər zaman'],1),
('riy9-ehtimal#33','riy-9-ehtimal',3,4,'7 komanda bir-biri ilə bir dəfə oynayarsa, neçə oyun keçirilər?','C(7,2) = 21 oyun.',array['21 oyun','42 oyun','14 oyun','7 oyun'],1),
('riy9-ehtimal#34','riy-9-ehtimal',2,4,'100 biletdən 2-si uduşludur. Bir biletlə uduş ehtimalı neçədir?','P = 2/100 = 1/50.',array['1/50','1/100','2/98','1/2'],1),
('riy9-ehtimal#35','riy-9-ehtimal',2,4,'Histoqramda sütunun hündürlüyü nəyi göstərir?','Uyğun qiymətin tezliyini göstərir.',array['Tezliyi','Qiymətin özünü','Sıranın nömrəsini','Cəmi'],1),
('riy9-ehtimal#36','riy-9-ehtimal',2,4,'P(A) = 1 olduqda A necə hadisədir?','Ehtimalı vahid olan hadisə yəqin hadisədir.',array['Yəqin hadisədir','Mümkün olmayan hadisədir','Təsadüfi hadisədir','Əks hadisədir'],1),
('riy9-ehtimal#37','riy-9-ehtimal',3,4,'Hər mövqedə 10 rəqəm ola bilən 4 rəqəmli kodların sayı neçədir?','10⁴ = 10 000.',array['10 000 kod','1 000 kod','40 kod','4 000 kod'],1),
('riy9-ehtimal#38','riy-9-ehtimal',3,4,'Sınaqların sayı artdıqca nisbi tezlik nəyə yaxınlaşır?','Hadisənin ehtimalına yaxınlaşır.',array['Hadisənin ehtimalına','Sıfra','Sonsuzluğa','Tezliyin kvadratına'],1),
('riy9-ehtimal#39','riy-9-ehtimal',3,4,'KİTAB sözünün 5 müxtəlif hərfindən neçə yerdəyişmə düzəlir?','P₅ = 5! = 120.',array['120 yerdəyişmə','25 yerdəyişmə','60 yerdəyişmə','10 yerdəyişmə'],1),
('riy9-ehtimal#40','riy-9-ehtimal',2,4,'C(4, 2) neçəyə bərabərdir?','4 · 3 / 2 = 6.',array['6-ya bərabərdir','8-ə bərabərdir','12-yə bərabərdir','4-ə bərabərdir'],1)
),
ins as (
  insert into public.questions
    (ext_key, owner_type, subject_id, level_id, topic_id, kind,
     body, explanation, difficulty, quarter, status)
  select d.ext, 'platform', s.id, l.id, tp.id, 'single',
         d.body, d.why, d.diff, d.rub, 'published'
    from d
    join public.subjects s on s.slug = 'riyaziyyat'
    join public.programs p on p.slug = 'orta'
    join public.levels   l on l.program_id = p.id and l.code = '9'
    join public.topics   tp on tp.subject_id = s.id and tp.slug = d.topic
  on conflict (ext_key) do update
    set body = excluded.body, explanation = excluded.explanation,
        difficulty = excluded.difficulty, quarter = excluded.quarter,
        topic_id = excluded.topic_id, level_id = excluded.level_id,
        subject_id = excluded.subject_id, status = 'published'
  returning id, ext_key
)
insert into public.question_options (question_id, ord, body, is_correct)
select ins.id, o.ord, o.txt, o.ord = d.correct
  from ins
  join d on d.ext = ins.ext_key,
  lateral unnest(d.opts) with ordinality as o(txt, ord);

do $$
declare n int; k int;
begin
  select count(*) into n from public.questions
   where owner_type = 'platform' and ext_key like 'riy9-%';
  if n <> 400 then
    raise exception 'riy9 suallari: 400 gozlenilirdi, % tapildi', n;
  end if;
  select count(*) into k from public.questions q
   where q.ext_key like 'riy9-%'
     and ((select count(*) from public.question_options o
            where o.question_id = q.id) <> 4
       or (select count(*) from public.question_options o
            where o.question_id = q.id and o.is_correct) <> 1);
  if k > 0 then
    raise exception '% sualda variant qurulusu sehvdir', k;
  end if;
  select count(distinct topic_id) into k from public.questions
   where ext_key like 'riy9-%';
  if k <> 10 then
    raise exception 'movzu sayi 10 deyil: %', k;
  end if;
  raise notice 'Riyaziyyat 9 banki: % sual, 10 movzu.', n;
end $$;
