-- =====================================================================
--  46_bank_riy10.sql : RIYAZIYYAT 10 PLATFORMA SUAL BANKI (orta mekteb)
--
--  BU FAYL ELLE YAZILMIR - tools/riy10.py yaradir:
--      python3 tools/riy10.py
--
--  10 movzu x 40 sual = 400.  ext_key: riy10-<movzu>#<sira>.
--  ON SERT: 45_movzular_orta10.sql islenmis olmalidir.
--  SONRA:   05_grants.sql yeniden islet.
-- =====================================================================

do $$
begin
  if not exists (
    select 1 from public.topics t
      join public.subjects s on s.id = t.subject_id
     where s.slug = 'riyaziyyat' and t.slug = 'riy-10-funksiya') then
    raise exception 'ONCE 45_movzular_orta10.sql isledilmelidir (riy-10-* movzulari yoxdur).';
  end if;
end $$;

delete from public.question_options o
 using public.questions q
 where o.question_id = q.id
   and q.owner_type = 'platform'
   and q.ext_key like 'riy10-%';

with d(ext, topic, diff, rub, body, why, opts, correct) as (values
('riy10-funksiya#1','riy-10-funksiya',1,1,'f(x) = 2x + 3 funksiyası üçün f(5) qiymətini tapın.','f(5) = 2 · 5 + 3 = 13.',array['13','10','8','16'],1),
('riy10-funksiya#2','riy-10-funksiya',1,1,'f(x) = x² − 4 funksiyası üçün f(−3) neçədir?','f(−3) = (−3)² − 4 = 9 − 4 = 5.',array['5','−13','13','−5'],1),
('riy10-funksiya#3','riy-10-funksiya',1,1,'Arqumentin ala bildiyi bütün qiymətlər çoxluğu funksiyanın hansı xarakteristikasıdır?','Bu çoxluq funksiyanın təyin oblastıdır.',array['Təyin oblastıdır','Qiymətlər çoxluğudur','Sıfırlar çoxluğudur','Dövrüdür'],1),
('riy10-funksiya#4','riy-10-funksiya',2,1,'y = 1/(x − 2) funksiyasının təyin oblastına hansı ədəd daxil deyil?','Məxrəc sıfır ola bilməz: x − 2 = 0, yəni x = 2 daxil deyil.',array['2','0','−2','1'],1),
('riy10-funksiya#5','riy-10-funksiya',2,1,'Kökaltı funksiya y = √x üçün arqumentin yolverilən qiymətləri hansı şərtlə verilir?','Kök altındakı ifadə mənfi ola bilməz: x ≥ 0.',array['x ≥ 0','x > 1','Bütün ədədlər','x ≤ 0'],1),
('riy10-funksiya#6','riy-10-funksiya',2,1,'Cüt funksiyanın qrafiki hansı oxa görə simmetrikdir?','Cüt funksiyanın qrafiki ordinat oxuna görə simmetrikdir.',array['Ordinat oxuna görə','Absis oxuna görə','y = x düz xəttinə görə','Heç bir oxa görə'],1),
('riy10-funksiya#7','riy-10-funksiya',2,1,'Tək funksiyanın qrafiki nəyə görə simmetrikdir?','Tək funksiyanın qrafiki koordinat başlanğıcına görə simmetrikdir.',array['Koordinat başlanğıcına görə','Ordinat oxuna görə','Absis oxuna görə','x = 1 düz xəttinə görə'],1),
('riy10-funksiya#8','riy-10-funksiya',2,1,'f(−x) = f(x) bərabərliyini ödəyən funksiya necə adlanır?','Bu bərabərlik cüt funksiyanın tərifidir.',array['Cüt funksiya','Tək funksiya','Dövri funksiya','Tərs funksiya'],1),
('riy10-funksiya#9','riy-10-funksiya',2,1,'Arqumentin işarəsi dəyişəndə qiymətinin yalnız işarəsi dəyişən funksiya necə adlanır?','f(−x) = −f(x): bu, tək funksiyanın tərifidir.',array['Tək funksiya','Cüt funksiya','Sabit funksiya','Mürəkkəb funksiya'],1),
('riy10-funksiya#10','riy-10-funksiya',2,1,'y = x³ funksiyası cütdür, yoxsa təkdir?','(−x)³ = −x³ olduğundan funksiya təkdir.',array['Təkdir','Cütdür','Həm cüt, həm təkdir','Nə cüt, nə təkdir'],1),
('riy10-funksiya#11','riy-10-funksiya',2,1,'n cüt natural ədəd olduqda y = xⁿ funksiyasının qrafiki hansı oxa görə simmetrik olur?','Cüt qüvvət funksiyası cütdür - qrafiki ordinat oxuna görə simmetrikdir.',array['Ordinat oxuna','Absis oxuna','Başlanğıc nöqtəyə','Heç nəyə'],1),
('riy10-funksiya#12','riy-10-funksiya',1,1,'Artan funksiyada arqument artdıqca funksiyanın qiyməti necə dəyişir?','Artan funksiyada böyük arqumentə böyük qiymət uyğundur.',array['Artır','Azalır','Dəyişmir','Əvvəl azalır, sonra artır'],1),
('riy10-funksiya#13','riy-10-funksiya',2,1,'y = −2x + 5 funksiyası artandır, yoxsa azalandır?','Bucaq əmsalı mənfi (−2) olduğundan funksiya azalandır.',array['Azalandır','Artandır','Sabitdir','Dövridir'],1),
('riy10-funksiya#14','riy-10-funksiya',2,1,'g(x) = x + 1 və f(x) = x² olarsa, f(g(2)) qiymətini tapın.','g(2) = 3, f(3) = 9.',array['9','5','4','6'],1),
('riy10-funksiya#15','riy-10-funksiya',2,1,'y = x + 4 funksiyasının tərs funksiyası hansıdır?','y = x + 4 tənliyindən x = y − 4; tərs funksiya y = x − 4.',array['y = x − 4','y = 4 − x','y = 4x','y = x + 4'],1),
('riy10-funksiya#16','riy-10-funksiya',2,1,'y = 3x funksiyasının tərs funksiyası hansıdır?','y = 3x tənliyindən x = y/3; tərs funksiya y = x/3.',array['y = x/3','y = 3/x','y = −3x','y = x − 3'],1),
('riy10-funksiya#17','riy-10-funksiya',2,1,'Funksiyanın qrafiki ordinat oxunu ən çoxu neçə nöqtədə kəsə bilər?','Hər x-ə bir y uyğun olduğundan OY oxu ilə ən çoxu bir kəsişmə ola bilər.',array['Bir nöqtədə','İki nöqtədə','Üç nöqtədə','Sonsuz sayda nöqtədə'],1),
('riy10-funksiya#18','riy-10-funksiya',2,1,'y = f(x) + 3 çevrilməsi qrafiki necə dəyişir?','Qrafik 3 vahid yuxarı sürüşür.',array['3 vahid yuxarı sürüşdürür','3 vahid aşağı sürüşdürür','3 vahid sağa sürüşdürür','3 dəfə dartır'],1),
('riy10-funksiya#19','riy-10-funksiya',3,1,'y = f(x − 2) çevrilməsi qrafiki hansı istiqamətdə sürüşdürür?','Arqumentdən 2 çıxılması qrafiki 2 vahid sağa sürüşdürür.',array['2 vahid sağa','2 vahid sola','2 vahid yuxarı','2 vahid aşağı'],1),
('riy10-funksiya#20','riy-10-funksiya',3,1,'y = −f(x) çevrilməsi qrafiki necə dəyişir?','Qrafik absis oxuna görə simmetrik əks olunur.',array['Absis oxuna görə əks etdirir','Ordinat oxuna görə əks etdirir','Yuxarı sürüşdürür','Dəyişmir'],1),
('riy10-funksiya#21','riy-10-funksiya',3,1,'f(x) = x (x ≥ 0 olduqda) və f(x) = −x (x < 0 olduqda) hissə-hissə funksiyası hansı funksiyadır?','Bu, modul funksiyasıdır: y = |x|.',array['y = |x| modul funksiyası','y = x² kvadrat funksiya','y = 1/x tərs mütənasiblik','y = x³ kub funksiya'],1),
('riy10-funksiya#22','riy-10-funksiya',1,1,'f(x) = |x| funksiyası üçün f(−7) neçədir?','|−7| = 7.',array['7','−7','0','14'],1),
('riy10-funksiya#23','riy-10-funksiya',2,1,'Yuxarıya açılan y = x² + 1 parabolası üçün funksiyanın ala bildiyi ən kiçik qiymət neçədir?','x² ≥ 0 olduğundan ən kiçik qiymət x = 0-da alınır: y = 1.',array['1','0','−1','2'],1),
('riy10-funksiya#24','riy-10-funksiya',2,1,'y = 5 sabit funksiyasının qrafiki nədir?','Sabit funksiyanın qrafiki absis oxuna paralel düz xətdir.',array['Absis oxuna paralel düz xətt','Ordinat oxuna paralel düz xətt','Başlanğıcdan keçən düz xətt','Parabola'],1),
('riy10-funksiya#25','riy-10-funksiya',3,1,'f(x) = x² − 6x + 8 funksiyasının sıfırlarını tapın.','x² − 6x + 8 = 0 tənliyinin kökləri: x = 2 və x = 4.',array['2 və 4','1 və 8','−2 və −4','3 və 5'],1),
('riy10-funksiya#26','riy-10-funksiya',2,1,'Funksiyanın sıfırı nədir?','Funksiyanın sıfırı f(x) = 0 bərabərliyini ödəyən arqument qiymətidir.',array['f(x) = 0 olduğu arqument qiyməti','Funksiyanın ən böyük qiyməti','x = 0 nöqtəsindəki qiymət','Qrafikin rəngi'],1),
('riy10-funksiya#27','riy-10-funksiya',3,1,'n cüt natural ədəd olduqda y = xⁿ funksiyasının qiymətlər çoxluğu hansıdır?','Cüt qüvvət mənfi olmur: qiymətlər çoxluğu y ≥ 0.',array['Mənfi olmayan ədədlər (y ≥ 0)','Bütün həqiqi ədədlər','Yalnız müsbət ədədlər','Yalnız tam ədədlər'],1),
('riy10-funksiya#28','riy-10-funksiya',3,1,'f(x) = 3x − 1 və g(x) = 2x olarsa, f(g(3)) qiymətini tapın.','g(3) = 6, f(6) = 3 · 6 − 1 = 17.',array['17','16','15','18'],1),
('riy10-funksiya#29','riy-10-funksiya',2,1,'Mürəkkəb funksiya nədir?','Mürəkkəb funksiyada bir funksiyanın arqumenti başqa funksiyadır: f(g(x)).',array['Bir funksiyanın arqumentinin başqa funksiya olması','İki funksiyanın cəmi','Funksiyanın qrafikinin mürəkkəb görünməsi','Çoxhədli funksiya'],1),
('riy10-funksiya#30','riy-10-funksiya',3,1,'Tərs funksiyanın qrafiki verilmiş funksiyanın qrafiki ilə hansı xəttə görə simmetrikdir?','Qarşılıqlı tərs funksiyaların qrafikləri y = x düz xəttinə görə simmetrikdir.',array['y = x düz xəttinə görə','Absis oxuna görə','Ordinat oxuna görə','y = −x düz xəttinə görə'],1),
('riy10-funksiya#31','riy-10-funksiya',3,1,'y = 2x + 6 funksiyasının tərs funksiyası hansıdır?','y = 2x + 6 tənliyindən x = (y − 6)/2; tərs funksiya y = (x − 6)/2.',array['y = (x − 6)/2','y = (x + 6)/2','y = 2x − 6','y = 6 − 2x'],1),
('riy10-funksiya#32','riy-10-funksiya',1,1,'Hər bir x qiymətinə yeganə y qiyməti qarşı qoyan uyğunluq necə adlanır?','Belə uyğunluq funksiya adlanır.',array['Funksiya','Bərabərsizlik','Çoxluq','Silsilə'],1),
('riy10-funksiya#33','riy-10-funksiya',1,1,'Funksiya hansı üsullarla verilə bilər?','Funksiya düsturla, cədvəllə və qrafiklə verilə bilər.',array['Düstur, cədvəl və qrafiklə','Yalnız düsturla','Yalnız qrafiklə','Yalnız sözlə'],1),
('riy10-funksiya#34','riy-10-funksiya',3,1,'y = x² funksiyası hansı aralıqda azalandır?','Parabolanın sol qolunda - x ≤ 0 aralığında funksiya azalandır.',array['x ≤ 0 aralığında','x ≥ 0 aralığında','Bütün oxda','Heç bir aralıqda'],1),
('riy10-funksiya#35','riy-10-funksiya',2,1,'y = 1/x funksiyası cütdür, yoxsa təkdir?','1/(−x) = −1/x olduğundan funksiya təkdir.',array['Təkdir','Cütdür','Həm cüt, həm təkdir','Sabitdir'],1),
('riy10-funksiya#36','riy-10-funksiya',1,1,'f(2) = 7 yazılışı nəyi bildirir?','Bu yazılış x = 2 olduqda funksiyanın qiymətinin 7 olduğunu göstərir.',array['x = 2 olduqda funksiyanın qiyməti 7-dir','Funksiya 2-dən 7-yə qədər artır','Qrafik (7; 2) nöqtəsindən keçir','Funksiyanın sıfırı 7-dir'],1),
('riy10-funksiya#37','riy-10-funksiya',3,1,'y = 2f(x) çevrilməsi qrafikə necə təsir edir?','Qrafik ordinat oxu istiqamətində 2 dəfə dartılır.',array['OY istiqamətində 2 dəfə dartır','OX istiqamətində 2 dəfə sıxır','2 vahid yuxarı sürüşdürür','Heç bir təsiri yoxdur'],1),
('riy10-funksiya#38','riy-10-funksiya',2,1,'f(x) = x² − 9 funksiyasının neçə sıfırı var?','x² − 9 = 0 tənliyinin iki kökü var: x = 3 və x = −3.',array['2','1','0','3'],1),
('riy10-funksiya#39','riy-10-funksiya',2,1,'Aşağıya açılan y = −x² + 4 parabolasının zirvəsinin ordinatı neçədir?','Zirvə x = 0-dadır: y = 4 - bu, funksiyanın ən böyük qiymətidir.',array['4','0','−4','2'],1),
('riy10-funksiya#40','riy-10-funksiya',2,1,'y = √(x − 5) funksiyasının təyin oblastı hansıdır?','Kök altı mənfi olmamalıdır: x − 5 ≥ 0, yəni x ≥ 5.',array['x ≥ 5','x > 0','x ≤ 5','Bütün ədədlər'],1),
('riy10-feza#1','riy-10-feza',1,1,'Fəzada iki müstəvi kəsişdikdə nə alınır?','İki müstəvinin kəsişməsi düz xətdir.',array['Düz xətt','Nöqtə','Çevrə','Parça'],1),
('riy10-feza#2','riy-10-feza',1,1,'Bir düz xətt üzərində olmayan üç nöqtədən neçə müstəvi keçir?','Belə üç nöqtədən yalnız bir müstəvi keçir.',array['Yalnız bir','İki','Üç','Sonsuz sayda'],1),
('riy10-feza#3','riy-10-feza',1,1,'Fəzada bir müstəvidə yerləşən və kəsişməyən düz xətlər necə adlanır?','Bir müstəvidə yerləşib kəsişməyən düz xətlər paraleldir.',array['Paralel düz xətlər','Çarpaz düz xətlər','Perpendikulyar düz xətlər','Üst-üstə düşən düz xətlər'],1),
('riy10-feza#4','riy-10-feza',2,1,'Bir müstəvidə yerləşməyən və kəsişməyən düz xətlər necə adlanır?','Belə düz xətlər çarpaz düz xətlər adlanır.',array['Çarpaz düz xətlər','Paralel düz xətlər','Perpendikulyar düz xətlər','Toxunan düz xətlər'],1),
('riy10-feza#5','riy-10-feza',2,1,'Düz xəttin müstəviyə paralel olması nə deməkdir?','Paralel olduqda düz xəttin müstəvi ilə ortaq nöqtəsi olmur.',array['Ortaq nöqtələri yoxdur','Bir ortaq nöqtələri var','İki ortaq nöqtələri var','Düz xətt müstəvidə yerləşir'],1),
('riy10-feza#6','riy-10-feza',2,1,'Düz xətt müstəviyə perpendikulyardırsa, o, müstəvidəki nəyə perpendikulyardır?','Perpendikulyar düz xətt müstəvidəki bütün düz xətlərə perpendikulyardır.',array['Müstəvidəki bütün düz xətlərə','Yalnız bir düz xəttə','Yalnız iki düz xəttə','Heç bir düz xəttə'],1),
('riy10-feza#7','riy-10-feza',2,1,'Nöqtədən müstəviyə çəkilmiş məsafələrdən ən qısası hansıdır?','Ən qısa məsafə perpendikulyarın uzunluğudur.',array['Perpendikulyar','İxtiyari mail','Ən uzun mail','Qövs'],1),
('riy10-feza#8','riy-10-feza',3,1,'Üç perpendikulyar teoremi nə haqqındadır?','Teorem mailə və onun proyeksiyasına perpendikulyarlıq arasındakı əlaqəni verir.',array['Mailin proyeksiyasına perpendikulyarlıq haqqında','Üçbucağın sahəsi haqqında','Çevrənin uzunluğu haqqında','Kvadratın diaqonalı haqqında'],1),
('riy10-feza#9','riy-10-feza',2,1,'İkiüzlü bucaq nədir?','Bir düz xətdən çıxan iki yarımmüstəvinin əmələ gətirdiyi fiqur ikiüzlü bucaqdır.',array['İki yarımmüstəvinin əmələ gətirdiyi fiqur','İki nöqtə arasındakı məsafə','Üçbucağın iki bucağı','Çevrənin iki qövsü'],1),
('riy10-feza#10','riy-10-feza',2,1,'İki paralel müstəvi üçüncü müstəvi ilə kəsişdikdə alınan kəsişmə xətləri necə olur?','Kəsişmə xətləri bir-birinə paralel olur.',array['Paralel','Perpendikulyar','Çarpaz','Üst-üstə düşən'],1),
('riy10-feza#11','riy-10-feza',2,1,'Perpendikulyar 3 sm, proyeksiya 4 sm olarsa, mailin uzunluğu neçə santimetrdir?','Pifaqor teoremi ilə: mail = √(3² + 4²) = √25 = 5 sm.',array['5','7','6','12'],1),
('riy10-feza#12','riy-10-feza',3,1,'Mail 13 sm, perpendikulyar 5 sm olarsa, proyeksiyanın uzunluğu neçə santimetrdir?','Proyeksiya = √(13² − 5²) = √144 = 12 sm.',array['12','8','18','9'],1),
('riy10-feza#13','riy-10-feza',3,1,'Mail 10 sm, proyeksiyası 6 sm olarsa, perpendikulyarın uzunluğu neçə santimetrdir?','Perpendikulyar = √(10² − 6²) = √64 = 8 sm.',array['8','4','16','7'],1),
('riy10-feza#14','riy-10-feza',3,1,'Nöqtədən müstəviyə çəkilmiş iki mail bərabərdirsə, onların proyeksiyaları necə olur?','Bərabər maillərin proyeksiyaları da bərabərdir.',array['Bərabərdir','Fərqlidir','Biri sıfırdır','Müqayisə olunmur'],1),
('riy10-feza#15','riy-10-feza',2,1,'Otağın tavanı ilə divarının kəsişməsi hansı həndəsi anlayışın modelidir?','Tavan və divar müstəvilərinin kəsişməsi düz xətt boyunca gedir.',array['İki müstəvinin kəsişmə xəttinin','Paralel müstəvilərin','Çarpaz düz xətlərin','Nöqtənin'],1),
('riy10-feza#16','riy-10-feza',2,1,'Stolun ayağının döşəməyə söykənməsi hansı vəziyyətin modelidir?','Şaquli ayaq üfüqi döşəməyə perpendikulyar düz xəttin modelidir.',array['Düz xəttin müstəviyə perpendikulyarlığının','İki müstəvinin paralelliyinin','Düz xətlərin çarpazlığının','Nöqtələrin bərabərliyinin'],1),
('riy10-feza#17','riy-10-feza',2,1,'İki paralel müstəvi arasındakı məsafə necə ölçülür?','Məsafə müstəvilər arasındakı ortaq perpendikulyarın uzunluğu ilə ölçülür.',array['Ortaq perpendikulyarın uzunluğu ilə','İxtiyari mail ilə','Ən uzun parça ilə','Qövsün uzunluğu ilə'],1),
('riy10-feza#18','riy-10-feza',1,1,'Fəza koordinat sistemində neçə ox var və onlar hansılardır?','Fəzada üç qarşılıqlı perpendikulyar ox var: Ox, Oy, Oz.',array['Üçdür: Ox, Oy, Oz','İkidir: Ox, Oy','Dörddür','Birdir'],1),
('riy10-feza#19','riy-10-feza',1,1,'Fəzada nöqtənin vəziyyəti neçə ədədlə (koordinatla) təyin olunur?','Fəzada nöqtə üç koordinatla verilir: (x; y; z).',array['Üç ədədlə (x; y; z)','İki ədədlə','Bir ədədlə','Dörd ədədlə'],1),
('riy10-feza#20','riy-10-feza',3,1,'A(1; 2; 2) nöqtəsinin koordinat başlanğıcından məsafəsini tapın.','Məsafə = √(1² + 2² + 2²) = √9 = 3.',array['3 vahid','5 vahid','9 vahid','4 vahid'],1),
('riy10-feza#21','riy-10-feza',2,1,'M(0; 0; 5) nöqtəsi hansı koordinat oxu üzərində yerləşir?','Yalnız z koordinatı sıfırdan fərqlidir - nöqtə Oz oxundadır.',array['Oz oxu üzərində','Ox oxu üzərində','Oy oxu üzərində','Heç bir oxda'],1),
('riy10-feza#22','riy-10-feza',2,1,'Perpendikulyar müstəvilər arasındakı ikiüzlü bucaq neçə dərəcədir?','Perpendikulyar müstəvilər 90 dərəcəlik ikiüzlü bucaq əmələ gətirir.',array['90','45','180','60'],1),
('riy10-feza#23','riy-10-feza',3,1,'Düz xətlə müstəvi arasındakı bucaq nəyə bərabərdir?','Bu bucaq düz xətlə onun müstəvi üzərindəki proyeksiyası arasındakı bucaqdır.',array['Düz xətlə proyeksiyası arasındakı bucağa','Həmişə 90 dərəcəyə','Həmişə 45 dərəcəyə','İxtiyari bucağa'],1),
('riy10-feza#24','riy-10-feza',2,1,'Kubun qonşu üzləri bir-biri ilə hansı bucaq altında kəsişir?','Kubun qonşu üzləri perpendikulyardır - 90 dərəcə altında kəsişir.',array['90 dərəcə altında','60 dərəcə altında','45 dərəcə altında','120 dərəcə altında'],1),
('riy10-feza#25','riy-10-feza',1,1,'Fəzada iki nöqtədən neçə düz xətt keçirmək olar?','İki nöqtədən yalnız bir düz xətt keçir.',array['Yalnız bir düz xətt','İki düz xətt','Üç düz xətt','Sonsuz sayda'],1),
('riy10-feza#26','riy-10-feza',3,1,'Müstəvini birqiymətli təyin etmək üçün düz xəttə əlavə nə lazımdır?','Düz xətt və onun xaricindəki bir nöqtə müstəvini birqiymətli təyin edir.',array['Xaricindəki bir nöqtə','Üzərindəki bir nöqtə','Başqa bir çarpaz xətt','Heç nə'],1),
('riy10-feza#27','riy-10-feza',3,1,'Paralel iki düz xətdən biri müstəvini kəsirsə, ikincisi necə olur?','Paralel xətlərdən biri müstəvini kəsirsə, digəri də onu kəsir.',array['O da müstəvini kəsir','Müstəviyə paralel qalır','Müstəvidə yerləşir','Yox olur'],1),
('riy10-feza#28','riy-10-feza',3,1,'Divara söykənən 5 metrlik nərdivanın aşağı ucu divardan 3 metr aralıdır. Nərdivan divarın hansı hündürlüyünə çatır?','Hündürlük = √(5² − 3²) = √16 = 4 metr.',array['4 metrə','2 metrə','8 metrə','3 metrə'],1),
('riy10-feza#29','riy-10-feza',2,1,'Açıq qapının müstəvisi ilə döşəmə müstəvisi adətən necə yerləşir?','Qapı tavası döşəməyə perpendikulyar müstəvidədir.',array['Perpendikulyar yerləşir','Paralel yerləşir','Üst-üstə düşür','Çarpaz sayılır'],1),
('riy10-feza#30','riy-10-feza',3,1,'Çarpaz düz xətlər arasındakı bucaq necə tapılır?','Xətlərdən biri paralel köçürülərək kəsişən vəziyyətə gətirilir.',array['Paralel köçürmə ilə kəsişən vəziyyətə gətirilir','Ölçülə bilmir','Həmişə sıfır sayılır','Həmişə 180 dərəcə sayılır'],1),
('riy10-feza#31','riy-10-feza',2,1,'Düz xəttin xaricindəki nöqtədən ona paralel neçə düz xətt keçirmək olar?','Nöqtədən verilmiş düz xəttə paralel yalnız bir düz xətt keçir.',array['Yalnız bir dənə','İki dənə','Heç bir','Sonsuz sayda paralel'],1),
('riy10-feza#32','riy-10-feza',2,1,'Kubun bir təpəsindən neçə til çıxır?','Kubun hər təpəsində üç til görüşür.',array['3','4','2','6'],1),
('riy10-feza#33','riy-10-feza',2,1,'Düz xətt müstəvini kəsirsə, onların neçə ortaq nöqtəsi olur?','Kəsən düz xəttin müstəvi ilə bir ortaq nöqtəsi olur.',array['Bir','İki','Üç','Sonsuz sayda ortaq nöqtə'],1),
('riy10-feza#34','riy-10-feza',2,1,'Eyni nöqtədən çəkilmiş mail ilə perpendikulyardan hansı uzundur?','Mail həmişə perpendikulyardan uzundur.',array['Mail perpendikulyardan uzundur','Perpendikulyar maildən uzundur','Bərabərdirlər','Müqayisə mümkün deyil'],1),
('riy10-feza#35','riy-10-feza',3,1,'Nöqtədən müstəviyə çəkilmiş bərabər maillərin müstəvi ilə əmələ gətirdiyi bucaqlar necədir?','Bərabər maillər müstəvi ilə bərabər bucaqlar əmələ gətirir.',array['Bərabərdir','Həmişə fərqlidir','Cəmi 90 dərəcədir','Sıfırdır'],1),
('riy10-feza#36','riy-10-feza',2,1,'Günəş şüaları altında şaquli dirəyin yerə düşən kölgəsi həndəsi olaraq nədir?','Kölgə dirəyin (mailin ucunun) müstəvi üzərindəki proyeksiyasıdır.',array['Proyeksiyaya misaldır','Perpendikulyara misaldır','İkiüzlü bucağa misaldır','Çevrəyə misaldır'],1),
('riy10-feza#37','riy-10-feza',3,1,'Fəzada z = 0 şərtini ödəyən bütün nöqtələr harada yerləşir?','z = 0 olan nöqtələr Oxy koordinat müstəvisini təşkil edir.',array['Oxy müstəvisində','Oz oxunda','Oyz müstəvisində','Bir nöqtədə'],1),
('riy10-feza#38','riy-10-feza',3,1,'İki müstəvinin paralellik əlaməti hansıdır?','Bir müstəvinin iki kəsişən düz xətti digər müstəviyə paraleldirsə, müstəvilər paraleldir.',array['Birinin iki kəsişən xətti digərinə paraleldirsə','Bir ortaq nöqtələri varsa','Kəsişmə xətləri varsa','Hər ikisi şaquli olduqda'],1),
('riy10-feza#39','riy-10-feza',2,1,'Tetraedrin neçə üzü var?','Tetraedr dörd üçbucaq üzdən ibarətdir.',array['4 üz','6 üz','8 üz','3 üz'],1),
('riy10-feza#40','riy-10-feza',2,1,'Müstəvidən kənar nöqtədən müstəviyə neçə perpendikulyar endirmək olar?','Nöqtədən müstəviyə yalnız bir perpendikulyar endirmək olar.',array['Yalnız bir perpendikulyar','İki perpendikulyar','Üç perpendikulyar','Sonsuz sayda perpendikulyar'],1),
('riy10-triq-ifade#1','riy-10-triq-ifade',1,1,'Açıq bucağın (180 dərəcənin) radian ölçüsü nəyə bərabərdir?','180 dərəcə π radiana bərabərdir.',array['π radian','2π radian','π/2 radian','π/4 radian'],1),
('riy10-triq-ifade#2','riy-10-triq-ifade',2,1,'π/6 radian neçə dərəcədir?','π/6 · 180/π = 30 dərəcə.',array['30','60','45','90'],1),
('riy10-triq-ifade#3','riy-10-triq-ifade',2,1,'45 dərəcəlik bucağı radianla ifadə edin.','45 · π/180 = π/4 radian.',array['π/4','π/3','π/6','π/2'],1),
('riy10-triq-ifade#4','riy-10-triq-ifade',1,1,'Düz bucağın radian ölçüsü nədir?','90 dərəcə π/2 radiana bərabərdir.',array['π/2','π','π/4','2π'],1),
('riy10-triq-ifade#5','riy-10-triq-ifade',1,1,'Vahid çevrə nədir?','Vahid çevrə mərkəzi koordinat başlanğıcında, radiusu 1 olan çevrədir.',array['Radiusu 1 olan çevrə','Diametri 1 olan çevrə','Uzunluğu 1 olan çevrə','Sahəsi 1 olan çevrə'],1),
('riy10-triq-ifade#6','riy-10-triq-ifade',2,1,'Vahid çevrə üzərindəki dönmə nöqtəsinin ordinatı hansı funksiyanın qiymətidir?','Nöqtənin ordinatı sin α-dır.',array['Sinusun','Kosinusun','Tangensin','Kotangensin'],1),
('riy10-triq-ifade#7','riy-10-triq-ifade',2,1,'Vahid çevrə üzərindəki dönmə nöqtəsinin absisi hansı funksiyanı verir?','Nöqtənin absisi cos α-dır.',array['Kosinusu','Sinusu','Tangensi','Kotangensi'],1),
('riy10-triq-ifade#8','riy-10-triq-ifade',2,1,'tan α nisbət şəklində necə yazılır?','Tangens sinusun kosinusa nisbətidir.',array['sin α / cos α','cos α / sin α','1 / sin α','sin α · cos α'],1),
('riy10-triq-ifade#9','riy-10-triq-ifade',2,1,'Radiusu 5 sm olan çevrədə 2 radianlıq mərkəzi bucağa uyğun qövsün uzunluğunu tapın.','l = αR = 2 · 5 = 10 sm.',array['10 sm','7 sm','25 sm','5 sm'],1),
('riy10-triq-ifade#10','riy-10-triq-ifade',3,1,'Radiusu 3 sm, mərkəzi bucağı 2 radian olan sektorun sahəsini tapın.','S = αR²/2 = 2 · 9 / 2 = 9 sm².',array['9 sm²','6 sm²','18 sm²','12 sm²'],1),
('riy10-triq-ifade#11','riy-10-triq-ifade',2,1,'Dönmə bucağı hansı istiqamətdə müsbət sayılır?','Saat əqrəbinin əksi istiqamətdə dönmə müsbət sayılır.',array['Saat əqrəbinin əksinə','Saat əqrəbi istiqamətində','Yalnız aşağıya doğru','İxtiyari istiqamətdə'],1),
('riy10-triq-ifade#12','riy-10-triq-ifade',3,1,'sin(90° − α) ifadəsi nəyə bərabərdir?','Çevirmə düsturuna görə sin(90° − α) = cos α.',array['cos α','sin α','−cos α','tan α'],1),
('riy10-triq-ifade#13','riy-10-triq-ifade',3,1,'Çevirmə düsturuna görə cos(90° − α) hansı funksiya ilə əvəz olunur?','cos(90° − α) = sin α.',array['sin α ilə','cos α ilə','−sin α ilə','ctg α ilə'],1),
('riy10-triq-ifade#14','riy-10-triq-ifade',3,1,'sin(180° − α) nəyə bərabərdir?','II rübdə sinus müsbətdir: sin(180° − α) = sin α.',array['sin α','−sin α','cos α','−cos α'],1),
('riy10-triq-ifade#15','riy-10-triq-ifade',3,1,'cos(180° − α) ifadəsini sadələşdirdikdə hansı nəticə alınır?','II rübdə kosinus mənfidir: cos(180° − α) = −cos α.',array['−cos α','cos α','sin α','−sin α'],1),
('riy10-triq-ifade#16','riy-10-triq-ifade',2,1,'sin(−α) nəyə bərabərdir?','Sinus tək funksiyadır: sin(−α) = −sin α.',array['−sin α','sin α','cos α','−cos α'],1),
('riy10-triq-ifade#17','riy-10-triq-ifade',2,1,'Kosinusun cütlüyünə görə cos(−α) nəyə bərabərdir?','Kosinus cüt funksiyadır: cos(−α) = cos α.',array['cos α','−cos α','−sin α','sin α'],1),
('riy10-triq-ifade#18','riy-10-triq-ifade',3,1,'Sinusun toplama düsturu hansıdır?','sin(α + β) = sin α cos β + cos α sin β.',array['sin α cos β + cos α sin β','sin α sin β − cos α cos β','sin α + sin β','sin α cos β − cos α sin β'],1),
('riy10-triq-ifade#19','riy-10-triq-ifade',3,1,'cos(α − β) ifadəsinin açılışı hansıdır?','cos(α − β) = cos α cos β + sin α sin β.',array['cos α cos β + sin α sin β','cos α cos β − sin α sin β','cos α − cos β','sin α cos β + cos α sin β'],1),
('riy10-triq-ifade#20','riy-10-triq-ifade',3,1,'İkiqat bucağın sinusu hansı düsturla hesablanır?','sin 2α = 2 sin α cos α.',array['2 sin α cos α','sin²α − cos²α','2 sin α','sin α + cos α'],1),
('riy10-triq-ifade#21','riy-10-triq-ifade',3,1,'İkiqat bucağın kosinusu üçün düstur hansıdır?','cos 2α = cos²α − sin²α.',array['cos²α − sin²α','2 cos α','cos²α + sin²α','2 cos α sin α'],1),
('riy10-triq-ifade#22','riy-10-triq-ifade',3,1,'Bucaq sürəti 4 rad/san, radius 2 m olarsa, xətti sürəti tapın.','v = ωR = 4 · 2 = 8 m/san.',array['8 m/san','6 m/san','2 m/san','16 m/san'],1),
('riy10-triq-ifade#23','riy-10-triq-ifade',3,1,'Fırlanan nöqtə 10 saniyədə 20 radian dönürsə, bucaq sürəti neçə rad/san-dır?','ω = 20/10 = 2 rad/san.',array['2 rad/san','10 rad/san','200 rad/san','5 rad/san'],1),
('riy10-triq-ifade#24','riy-10-triq-ifade',3,1,'sin²α = 0,19 olarsa, əsas eynilikdən istifadə edərək cos²α-nı tapın.','cos²α = 1 − sin²α = 1 − 0,19 = 0,81.',array['0,81','0,19','0,91','1,19'],1),
('riy10-triq-ifade#25','riy-10-triq-ifade',2,1,'tan α · ctg α hasili nəyə bərabərdir?','Tangens və kotangens qarşılıqlı tərs ədədlərdir: hasilləri 1-ə bərabərdir.',array['1-ə bərabərdir','0-a bərabərdir','2-yə bərabərdir','α-dan asılıdır'],1),
('riy10-triq-ifade#26','riy-10-triq-ifade',3,1,'1 + tan²α cəmi nəyə bərabərdir?','Eyniliyə görə 1 + tan²α = 1/cos²α.',array['1/cos²α','1/sin²α','cos²α','sin²α'],1),
('riy10-triq-ifade#27','riy-10-triq-ifade',3,1,'390 dərəcəlik dönmə bucağının son tərəfi hansı bucağınkı ilə üst-üstə düşür?','390° − 360° = 30°: son tərəflər üst-üstə düşür.',array['30 dərəcənin','60 dərəcənin','90 dərəcənin','180 dərəcənin'],1),
('riy10-triq-ifade#28','riy-10-triq-ifade',2,1,'Saat əqrəbi istiqamətindəki dönmə bucağı hansı işarə ilə götürülür?','Saat əqrəbi istiqamətində dönmə mənfi sayılır.',array['Mənfi','Müsbət','Sıfır','İşarəsiz'],1),
('riy10-triq-ifade#29','riy-10-triq-ifade',2,1,'ctg α nisbət şəklində necə yazılır?','Kotangens kosinusun sinusa nisbətidir.',array['cos α / sin α','sin α / cos α','1 / cos α','sin α · cos α'],1),
('riy10-triq-ifade#30','riy-10-triq-ifade',3,1,'1 − cos²α ifadəsi nəyə bərabərdir?','Əsas eynilikdən: 1 − cos²α = sin²α.',array['sin²α','cos²α','tan²α','1'],1),
('riy10-triq-ifade#31','riy-10-triq-ifade',1,1,'sin 0° qiyməti neçədir?','0 dərəcəyə uyğun nöqtənin ordinatı sıfırdır.',array['0','1','−1','1/2'],1),
('riy10-triq-ifade#32','riy-10-triq-ifade',2,1,'Vahid çevrədə 0 dərəcəyə uyğun nöqtənin absisi neçədir?','0 dərəcəyə uyğun nöqtə (1; 0)-dır, absis 1-dir.',array['1','0','−1','1/2'],1),
('riy10-triq-ifade#33','riy-10-triq-ifade',2,1,'Vahid çevrənin ən yuxarı nöqtəsinə uyğun sinus qiyməti nədir?','Ən yuxarı nöqtə 90 dərəcəyə uyğundur: sin 90° = 1.',array['Vahid (1)','Sıfır','Mənfi vahid','1/2 qiyməti'],1),
('riy10-triq-ifade#34','riy-10-triq-ifade',2,1,'Çevirmə düsturları nə üçün istifadə olunur?','İxtiyari bucağın funksiyasını iti bucağın funksiyasına gətirmək üçün.',array['İxtiyari bucağı iti bucağa gətirmək üçün','Bucağı böyütmək üçün','Qrafik çəkmək üçün','Tənlik qurmaq üçün'],1),
('riy10-triq-ifade#35','riy-10-triq-ifade',3,1,'sin 150° qiymətini tapın.','sin 150° = sin(180° − 30°) = sin 30° = 1/2.',array['1/2','−1/2','√3/2','1'],1),
('riy10-triq-ifade#36','riy-10-triq-ifade',3,1,'cos 120° qiymətini tapın.','cos 120° = −cos 60° = −1/2.',array['−1/2','1/2','−√3/2','0'],1),
('riy10-triq-ifade#37','riy-10-triq-ifade',3,1,'tan 180° qiyməti neçədir?','tan 180° = sin 180° / cos 180° = 0 / (−1) = 0.',array['0','1','−1','Təyin olunmayıb'],1),
('riy10-triq-ifade#38','riy-10-triq-ifade',1,1,'π radianlıq bucağın dərəcə ölçüsü neçədir?','π radian 180 dərəcəyə bərabərdir.',array['180','90','360','60'],1),
('riy10-triq-ifade#39','riy-10-triq-ifade',1,1,'«Triqonometriya» sözünün hərfi mənası nədir?','Yunanca triqonon - üçbucaq, metreo - ölçürəm: üçbucaq ölçmə.',array['Üçbucaq ölçmə','Çevrə çəkmə','Bucaq bölmə','Ədəd sayma'],1),
('riy10-triq-ifade#40','riy-10-triq-ifade',2,1,'2π radianlıq dönmə neçə tam dövrə uyğundur?','2π radian bir tam dövrə - 360 dərəcəyə uyğundur.',array['Bir tam dövrə','İki tam dövrə','Yarım dövrə','Dörddə bir dövrə'],1),
('riy10-sinus-kosinus#1','riy-10-sinus-kosinus',2,2,'Sinuslar teoremi üçbucaqda hansı nisbətin sabitliyini ifadə edir?','Tərəfin qarşı bucağın sinusuna nisbəti bütün tərəflər üçün eynidir.',array['Tərəfin qarşı bucağın sinusuna nisbətinin','Tərəflərin cəminin','Bucaqların hasilinin','Hündürlüklərin fərqinin'],1),
('riy10-sinus-kosinus#2','riy-10-sinus-kosinus',3,2,'Sinuslar teoremində a/sin A nisbəti nəyə bərabərdir?','Bu nisbət xaricə çəkilmiş çevrənin diametrinə - 2R-ə bərabərdir.',array['Xaricə çəkilmiş çevrənin diametrinə (2R)','Daxilə çəkilmiş çevrənin radiusuna','Perimetrin yarısına','Sahəyə'],1),
('riy10-sinus-kosinus#3','riy-10-sinus-kosinus',2,2,'Kosinuslar teoreminin düsturu hansıdır?','c² = a² + b² − 2ab·cos C.',array['c² = a² + b² − 2ab·cos C','c² = a² + b² + 2ab','c = a + b − cos C','c² = a² − b²'],1),
('riy10-sinus-kosinus#4','riy-10-sinus-kosinus',2,2,'Kosinuslar teoremi hansı məşhur teoremin ümumiləşməsidir?','C = 90° olduqda cos C = 0 və düstur Pifaqor teoreminə çevrilir.',array['Pifaqor teoreminin','Fales teoreminin','Viyet teoreminin','Üç perpendikulyar teoreminin'],1),
('riy10-sinus-kosinus#5','riy-10-sinus-kosinus',3,2,'Üçbucaqda a = 5, b = 8, C = 60° olarsa, c tərəfini tapın (cos 60° = 0,5).','c² = 25 + 64 − 2·5·8·0,5 = 89 − 40 = 49; c = 7.',array['7','9','6','13'],1),
('riy10-sinus-kosinus#6','riy-10-sinus-kosinus',3,2,'Üçbucaqda a = 7, b = 8, C = 120° olarsa, c tərəfini tapın (cos 120° = −0,5).','c² = 49 + 64 + 2·7·8·0,5 = 113 + 56 = 169; c = 13.',array['13','12','15','11'],1),
('riy10-sinus-kosinus#7','riy-10-sinus-kosinus',2,2,'C bucağı 90° olduqda kosinuslar teoremi hansı bərabərliyə çevrilir?','cos 90° = 0 olduğundan c² = a² + b² alınır.',array['c² = a² + b²','c = a + b','c² = a² − b²','c² = 2ab'],1),
('riy10-sinus-kosinus#8','riy-10-sinus-kosinus',2,2,'Üçbucağın sahəsi iki tərəf və aralarındakı bucaqla hansı düsturla tapılır?','S = (1/2)·a·b·sin C.',array['S = (1/2)·a·b·sin C','S = a·b·cos C','S = (1/2)·(a + b)·C','S = a·b·C'],1),
('riy10-sinus-kosinus#9','riy-10-sinus-kosinus',3,2,'a = 6, b = 8, C = 30° olan üçbucağın sahəsini tapın (sin 30° = 0,5).','S = (1/2)·6·8·0,5 = 12.',array['12','24','48','6'],1),
('riy10-sinus-kosinus#10','riy-10-sinus-kosinus',3,2,'Üçbucaqda cos C < 0 olarsa, C bucağı necə bucaqdır?','Kosinusu mənfi olan bucaq kütdür.',array['Küt bucaqdır','İti bucaqdır','Düz bucaqdır','Açıq bucaqdır'],1),
('riy10-sinus-kosinus#11','riy-10-sinus-kosinus',3,2,'Üçbucaqda cos C > 0 olarsa, C bucağı hansı növdəndir?','Kosinusu müsbət olan bucaq itidir.',array['İti bucaqdır','Küt bucaqdır','Düz bucaqdır','Tam bucaqdır'],1),
('riy10-sinus-kosinus#12','riy-10-sinus-kosinus',3,2,'a = 10 və sin A = 0,5 olarsa, üçbucağın xaricinə çəkilmiş çevrənin diametri neçədir?','2R = a/sin A = 10/0,5 = 20.',array['20','10','5','40'],1),
('riy10-sinus-kosinus#13','riy-10-sinus-kosinus',3,2,'a = 8, A = 30° olarsa, xaricə çəkilmiş çevrənin radiusunu tapın (sin 30° = 0,5).','2R = 8/0,5 = 16; R = 8.',array['8','16','4','32'],1),
('riy10-sinus-kosinus#14','riy-10-sinus-kosinus',3,2,'Üçbucağın iki bucağı 50° və 60°-dirsə, üçüncü bucağın qarşısındakı tərəf hansıdır?','Üçüncü bucaq 70°-dir - ən böyükdür; qarşısındakı tərəf ən uzundur.',array['Ən uzun tərəf','Ən qısa tərəf','Orta tərəf','Təyin etmək olmur'],1),
('riy10-sinus-kosinus#15','riy-10-sinus-kosinus',2,2,'Sinuslar teoremi ilə üçbucağın hansı elementlərini tapmaq olar?','Bir tərəf və iki bucaq verildikdə qalan tərəfləri tapmaq olar.',array['Bir tərəf və iki bucaqla qalan tərəfləri','Yalnız sahəni','Yalnız perimetri','Yalnız hündürlüyü'],1),
('riy10-sinus-kosinus#16','riy-10-sinus-kosinus',2,2,'Kosinuslar teoremi ilə hansı halda üçüncü tərəf tapılır?','İki tərəf və aralarındakı bucaq verildikdə üçüncü tərəf tapılır.',array['İki tərəf və aralarındakı bucaq verildikdə','Üç bucaq verildikdə','Yalnız perimetr verildikdə','Heç bir halda'],1),
('riy10-sinus-kosinus#17','riy-10-sinus-kosinus',2,2,'Sinuslar teoremindən çıxan nəticəyə görə üçbucağın ən uzun tərəfi harada yerləşir?','Böyük bucağın sinusu böyükdür - ən uzun tərəf ən böyük bucağın qarşısındadır.',array['Ən böyük bucağın qarşısında','Ən kiçik bucağın qarşısında','İxtiyari bucağın qarşısında','Həmişə düz bucağın qarşısında'],1),
('riy10-sinus-kosinus#18','riy-10-sinus-kosinus',2,2,'a = 3, b = 4, C = 90° üçbucağında c tərəfi neçədir?','c² = 9 + 16 = 25; c = 5.',array['5-ə bərabərdir','7-yə bərabərdir','6-ya bərabərdir','12-yə bərabərdir'],1),
('riy10-sinus-kosinus#19','riy-10-sinus-kosinus',2,2,'Bərabəryanlı üçbucaqda oturacağa bitişik bucaqların sinusları necədir?','Bərabər bucaqların sinusları da bərabərdir.',array['Bərabər olur','Fərqli olur','Cəmi 1 olur','Hasili 1 olur'],1),
('riy10-sinus-kosinus#20','riy-10-sinus-kosinus',3,2,'sin A = sin B olarsa, üçbucağın A və B bucaqları üçün nə demək olar?','Üçbucaqda bu bərabərlikdən A = B alınır - üçbucaq bərabəryanlıdır.',array['A = B - üçbucaq bərabəryanlıdır','A > B','A + B = 90°','Heç nə demək olmaz'],1),
('riy10-sinus-kosinus#21','riy-10-sinus-kosinus',3,2,'Üçbucağın tərəfləri 5, 5 və 5-dirsə, hər bucağın kosinusu neçədir?','Bərabərtərəfli üçbucağın bucaqları 60°-dir: cos 60° = 0,5.',array['0,5','1','0','0,6'],1),
('riy10-sinus-kosinus#22','riy-10-sinus-kosinus',2,2,'İki tərəfi 4 və 6, aralarındakı bucağı 90° olan üçbucağın sahəsi neçədir?','S = (1/2)·4·6·sin 90° = 12.',array['12-yə bərabərdir','24-ə bərabərdir','10-a bərabərdir','48-ə bərabərdir'],1),
('riy10-sinus-kosinus#23','riy-10-sinus-kosinus',3,2,'Kosinuslar teoremində 2ab·cos C həddi hansı halda sıfır olur?','cos C = 0, yəni C = 90° olduqda bu hədd sıfırlanır.',array['C = 90° olduqda','C = 60° olduqda','C = 45° olduqda','Heç vaxt'],1),
('riy10-sinus-kosinus#24','riy-10-sinus-kosinus',2,2,'Üçbucağın tərəfləri 2, 3 və 4-dürsə, ən böyük bucaq hansı tərəfin qarşısındadır?','Ən böyük bucaq ən uzun tərəfin - 4-ün qarşısındadır.',array['4 tərəfinin qarşısında','2 tərəfinin qarşısında','3 tərəfinin qarşısında','Bütün bucaqlar bərabərdir'],1),
('riy10-sinus-kosinus#25','riy-10-sinus-kosinus',3,2,'Sinuslar teoremindən istifadə edərək b tərəfini tapın: a = 6, sin A = 0,6, sin B = 0,8.','b = a·sin B/sin A = 6·0,8/0,6 = 8.',array['8-ə bərabərdir','6-ya bərabərdir','10-a bərabərdir','4-ə bərabərdir'],1),
('riy10-sinus-kosinus#26','riy-10-sinus-kosinus',3,2,'Üçbucaqda a² + b² > c² olarsa, c tərəfinin qarşısındakı bucaq necədir?','Bu halda cos C > 0 olur - C iti bucaqdır.',array['İtidir','Kütdür','Düzdür','Açıqdır'],1),
('riy10-sinus-kosinus#27','riy-10-sinus-kosinus',3,2,'Üçbucaqda a² + b² < c² olarsa, C bucağı hansı növdəndir?','Bu halda cos C < 0 olur - C küt bucaqdır.',array['Kütdür','İtidir','Düzdür','Sıfırdır'],1),
('riy10-sinus-kosinus#28','riy-10-sinus-kosinus',3,2,'Paraleloqramın diaqonalını tapmaq üçün hansı teoremdən istifadə etmək əlverişlidir?','İki tərəf və aralarındakı bucaq məlumdursa, kosinuslar teoremi tətbiq olunur.',array['Kosinuslar teoremindən','Fales teoremindən','Viyet teoremindən','Üç perpendikulyar teoremindən'],1),
('riy10-sinus-kosinus#29','riy-10-sinus-kosinus',3,2,'Sinuslar teoremini tətbiq etmək üçün ən azı nə məlum olmalıdır?','Bir tərəf və onun qarşısındakı bucaq (əlavə bir element ilə) məlum olmalıdır.',array['Tərəf və qarşısındakı bucaq','Yalnız üç bucaq','Yalnız perimetr','Yalnız sahə'],1),
('riy10-sinus-kosinus#30','riy-10-sinus-kosinus',2,2,'Üçbucağın bucaqları 30°, 60° və 90°-dirsə, ən qısa tərəf hansı bucağın qarşısındadır?','Ən qısa tərəf ən kiçik bucağın - 30°-nin qarşısındadır.',array['30° bucağının qarşısında','60° bucağının qarşısında','90° bucağının qarşısında','İxtiyari yerdə'],1),
('riy10-sinus-kosinus#31','riy-10-sinus-kosinus',3,2,'a = 5, b = 5, C = 60° üçbucağında c-ni tapın (cos 60° = 0,5).','c² = 25 + 25 − 25 = 25; c = 5 - üçbucaq bərabərtərəflidir.',array['5 vahid','10 vahid','7 vahid','3 vahid'],1),
('riy10-sinus-kosinus#32','riy-10-sinus-kosinus',3,2,'Sahəsi 15, tərəfləri a = 6 və b = 10 olan üçbucaqda sin C neçədir?','15 = (1/2)·6·10·sin C; sin C = 15/30 = 0,5.',array['0,5','0,25','1','0,75'],1),
('riy10-sinus-kosinus#33','riy-10-sinus-kosinus',3,2,'Xaricə çəkilmiş çevrənin diametri 10, sin A = 0,7 olarsa, a tərəfi neçədir?','a = 2R·sin A = 10·0,7 = 7.',array['7-yə bərabərdir','5-ə bərabərdir','14-ə bərabərdir','3-ə bərabərdir'],1),
('riy10-sinus-kosinus#34','riy-10-sinus-kosinus',2,2,'Kosinuslar teoremi ilə üçbucağın bucağını tapmaq üçün nə məlum olmalıdır?','Üç tərəf məlum olduqda istənilən bucağın kosinusu tapılır.',array['Üç tərəfi','Yalnız bir tərəfi','Yalnız iki bucağı','Yalnız sahəsi'],1),
('riy10-sinus-kosinus#35','riy-10-sinus-kosinus',3,2,'Tərəfləri 6, 8, 10 olan üçbucaq necə üçbucaqdır?','6² + 8² = 100 = 10²: Pifaqor bərabərliyi ödənir - üçbucaq düzbucaqlıdır.',array['Düzbucaqlı','Kütbucaqlı','Bərabərtərəfli','İtibucaqlı'],1),
('riy10-sinus-kosinus#36','riy-10-sinus-kosinus',3,2,'Üçbucağın iki bucağının sinusları bərabərdirsə, qarşı tərəflər necədir?','Sinuslar teoreminə görə qarşı tərəflər də bərabərdir.',array['Onlar da bərabərdir','Fərqlidir','Biri ikiqatdır','Müqayisə olunmur'],1),
('riy10-sinus-kosinus#37','riy-10-sinus-kosinus',2,2,'Üçbucaqda A = 45° və B = 45° olarsa, C bucağı neçə dərəcədir?','C = 180° − 45° − 45° = 90°.',array['90','45','60','100'],1),
('riy10-sinus-kosinus#38','riy-10-sinus-kosinus',3,2,'İki tərəfi bərabər üçbucaqda bu tərəflərin qarşısındakı bucaqların kosinusları necədir?','Bərabər bucaqların kosinusları da bərabərdir.',array['Kosinuslar da bərabərdir','Əks işarəlidir','Cəmi sıfırdır','Fərqlidir'],1),
('riy10-sinus-kosinus#39','riy-10-sinus-kosinus',3,2,'sin 90° qiymətindən istifadə edərək düzbucaqlı üçbucağın sahə düsturunu yazın (katetlər a, b).','S = (1/2)·a·b·sin 90° = (1/2)·a·b.',array['S = (1/2)·a·b','S = a·b','S = a + b','S = 2ab'],1),
('riy10-sinus-kosinus#40','riy-10-sinus-kosinus',1,2,'Kosinuslar teoremini ilk dəfə sistemli şəkildə hansı sahənin alimləri inkişaf etdirmişdir?','Teoremin kökləri qədim həndəsəyə, inkişafı Şərq riyaziyyatçılarına gedib çıxır.',array['Riyaziyyatçılar - həndəsəçilər','Kimyaçılar','Bioloqlar','Coğrafiyaçılar'],1),
('riy10-triq-qrafik#1','riy-10-triq-qrafik',1,2,'Dövri funksiya nədir?','Qiymətləri müəyyən addımla (dövrlə) təkrarlanan funksiya dövri adlanır.',array['Qiymətləri müəyyən addımla təkrarlanan funksiya','Həmişə artan funksiya','Qrafiki düz xətt olan funksiya','Təyin oblastı boş olan funksiya'],1),
('riy10-triq-qrafik#2','riy-10-triq-qrafik',2,2,'y = sin x funksiyasının ən kiçik müsbət dövrü nədir?','Sinusun ən kiçik müsbət dövrü 2π-dir.',array['2π','π','π/2','4π'],1),
('riy10-triq-qrafik#3','riy-10-triq-qrafik',2,2,'y = cos x funksiyasının ən kiçik müsbət dövrü nəyə bərabərdir?','Kosinusun da ən kiçik müsbət dövrü 2π-dir.',array['2π-yə','π-yə','π/4-ə','3π-yə'],1),
('riy10-triq-qrafik#4','riy-10-triq-qrafik',1,2,'y = sin x funksiyasının qrafiki necə adlanır?','Sinus funksiyasının qrafiki sinusoid adlanır.',array['Sinusoid','Parabola','Hiperbola','Tangensoid'],1),
('riy10-triq-qrafik#5','riy-10-triq-qrafik',2,2,'y = sin x funksiyasının qiymətlər çoxluğu hansıdır?','Sinusun qiymətləri −1-dən 1-ə qədərdir: [−1; 1].',array['[−1; 1] parçası','Bütün həqiqi ədədlər','[0; 1] parçası','[−2; 2] parçası'],1),
('riy10-triq-qrafik#6','riy-10-triq-qrafik',2,2,'y = cos x qrafiki ordinat oxunu hansı nöqtədə kəsir?','cos 0 = 1 olduğundan qrafik OY oxunu (0; 1) nöqtəsində kəsir.',array['(0; 1) nöqtəsində','(0; 0) nöqtəsində','(0; −1) nöqtəsində','(1; 0) nöqtəsində'],1),
('riy10-triq-qrafik#7','riy-10-triq-qrafik',2,2,'y = 2 sin x funksiyasının amplitudu neçədir?','Amplitud sinusun qarşısındakı əmsalın modulu - 2-dir.',array['2-dir','1-dir','4-dür','1/2-dir'],1),
('riy10-triq-qrafik#8','riy-10-triq-qrafik',3,2,'y = sin 2x funksiyasının ən kiçik müsbət dövrü nədir?','Dövr T = 2π/2 = π.',array['π','2π','4π','π/4'],1),
('riy10-triq-qrafik#9','riy-10-triq-qrafik',3,2,'y = tan x funksiyasının ən kiçik müsbət dövrü nədir?','Tangensin dövrü π-dir.',array['π-yə bərabərdir','2π-yə bərabərdir','4π-yə bərabərdir','π/2-yə bərabərdir'],1),
('riy10-triq-qrafik#10','riy-10-triq-qrafik',2,2,'y = tan x funksiyasının qrafiki necə adlanır?','Tangensin qrafiki tangensoid adlanır.',array['Tangensoid','Sinusoid','Parabola','Ellips'],1),
('riy10-triq-qrafik#11','riy-10-triq-qrafik',2,2,'y = sin x + 2 funksiyasının ən böyük qiyməti neçədir?','sin x-in maksimumu 1-dir: 1 + 2 = 3.',array['3','2','1','5'],1),
('riy10-triq-qrafik#12','riy-10-triq-qrafik',2,2,'y = 3 cos x funksiyasının ən kiçik qiyməti neçədir?','cos x-in minimumu −1-dir: 3 · (−1) = −3.',array['−3','3','0','−1'],1),
('riy10-triq-qrafik#13','riy-10-triq-qrafik',3,2,'y = sin x qrafikinin absis oxu ilə kəsişdiyi nöqtələr hansı bərabərliyi ödəyir?','Kəsişmə nöqtələrində sin x = 0, yəni x = πn.',array['sin x = 0 (x = πn)','sin x = 1','cos x = 0','x = 0 yalnız'],1),
('riy10-triq-qrafik#14','riy-10-triq-qrafik',2,2,'y = sin x funksiyası cütdür, yoxsa təkdir?','sin(−x) = −sin x olduğundan sinus tək funksiyadır.',array['Tək funksiyadır','Cüt funksiyadır','Həm cüt, həm təkdir','Heç biri deyil'],1),
('riy10-triq-qrafik#15','riy-10-triq-qrafik',2,2,'y = cos x funksiyası cütlüyünə görə hansı funksiyadır?','cos(−x) = cos x olduğundan kosinus cüt funksiyadır.',array['Cüt funksiyadır','Tək funksiyadır','Sabit funksiyadır','Xətti funksiyadır'],1),
('riy10-triq-qrafik#16','riy-10-triq-qrafik',1,2,'Aşağıdakılardan hansı dövri hadisəyə misaldır?','Ürək döyüntüsü müəyyən dövrlə təkrarlanan hadisədir.',array['Ürək döyüntüsü','Ağacın böyüməsi','Daşın düşməsi','Buzun əriməsi'],1),
('riy10-triq-qrafik#17','riy-10-triq-qrafik',2,2,'y = sin x funksiyası [0; π/2] parçasında necə dəyişir?','Bu parçada sinus 0-dan 1-ə qədər artır.',array['Artandır','Azalandır','Sabitdir','Təyin olunmayıb'],1),
('riy10-triq-qrafik#18','riy-10-triq-qrafik',3,2,'y = sin x funksiyası maksimum qiymətini hansı nöqtələrdə alır?','Maksimum 1 qiyməti x = π/2 + 2πn nöqtələrində alınır.',array['x = π/2 + 2πn nöqtələrində','x = πn nöqtələrində','x = 0 nöqtəsində yalnız','Heç bir nöqtədə'],1),
('riy10-triq-qrafik#19','riy-10-triq-qrafik',2,2,'y = cos x funksiyasının ən böyük qiyməti neçədir?','Kosinusun maksimumu 1-dir.',array['1-ə bərabərdir','2-yə bərabərdir','Sıfırdır','π-yə bərabərdir'],1),
('riy10-triq-qrafik#20','riy-10-triq-qrafik',3,2,'y = sin(x − π/3) qrafiki y = sin x qrafikindən necə alınır?','Qrafik π/3 vahid sağa sürüşdürülür.',array['π/3 vahid sağa sürüşdürməklə','π/3 vahid sola sürüşdürməklə','π/3 vahid yuxarı sürüşdürməklə','3 dəfə dartmaqla'],1),
('riy10-triq-qrafik#21','riy-10-triq-qrafik',2,2,'y = sin x + 1 qrafiki y = sin x qrafikindən necə alınır?','Qrafik 1 vahid yuxarı sürüşdürülür.',array['1 vahid yuxarı sürüşdürməklə','1 vahid aşağı sürüşdürməklə','1 vahid sağa sürüşdürməklə','Əks etdirməklə'],1),
('riy10-triq-qrafik#22','riy-10-triq-qrafik',2,2,'y = A sin x funksiyasında amplitud nəyi göstərir?','Amplitud |A| - qrafikin ox xəttindən ən böyük meyletməsidir.',array['Ən böyük meyletməni (|A|)','Dövrün uzunluğunu','Qrafikin rəngini','Kəsişmə nöqtəsini'],1),
('riy10-triq-qrafik#23','riy-10-triq-qrafik',3,2,'Arqumenti yarıya bölündükdə - y = sin(x/2) üçün dövr sin x-in dövründən neçə dəfə böyük olur?','T = 2π/(1/2) = 4π: dövr 2 dəfə böyüyür.',array['2 dəfə (T = 4π)','Dəyişmir','2 dəfə kiçilir','4 dəfə (T = 8π)'],1),
('riy10-triq-qrafik#24','riy-10-triq-qrafik',3,2,'y = tan x funksiyası hansı nöqtələrdə təyin olunmayıb?','Tangens cos x = 0 olan x = π/2 + πn nöqtələrində təyin olunmayıb.',array['cos x = 0 olan nöqtələrdə (x = π/2 + πn)','sin x = 0 olan nöqtələrdə','x = 0 nöqtəsində','Heç bir nöqtədə'],1),
('riy10-triq-qrafik#25','riy-10-triq-qrafik',3,2,'y = ctg x funksiyası hansı nöqtələrdə təyin olunmayıb?','Kotangens sin x = 0 olan x = πn nöqtələrində təyin olunmayıb.',array['sin x = 0 olan nöqtələrdə','cos x = 0 olan nöqtələrdə','Bütün nöqtələrdə təyin olunub','x = 1 nöqtəsində'],1),
('riy10-triq-qrafik#26','riy-10-triq-qrafik',2,2,'Rəqqasın rəqsi hərəkəti hansı funksiya ilə modelləşdirilir?','Harmonik rəqslər sinus (kosinus) funksiyası ilə təsvir olunur.',array['Sinus funksiyası ilə','Xətti funksiya ilə','Kvadrat funksiya ilə','Loqarifmik funksiya ilə'],1),
('riy10-triq-qrafik#27','riy-10-triq-qrafik',3,2,'y = cos x qrafiki hansı əyri ilə eynidır?','Kosinusoid π/2 sürüşdürülmüş sinusoiddir.',array['Sürüşdürülmüş sinusoidlə','Parabola ilə','Düz xətlə','Çevrə ilə'],1),
('riy10-triq-qrafik#28','riy-10-triq-qrafik',3,2,'y = sin x və y = cos x qrafikləri bir-birindən hansı çevrilmə ilə alınır?','cos x = sin(x + π/2): qrafiklər π/2 sürüşmə ilə bir-birinə keçir.',array['π/2 vahid sürüşmə ilə','OX-a görə əks etdirmə ilə','2 dəfə dartma ilə','Heç bir çevrilmə ilə'],1),
('riy10-triq-qrafik#29','riy-10-triq-qrafik',2,2,'y = −sin x qrafiki y = sin x qrafikindən necə alınır?','Qrafik absis oxuna görə əks etdirilir.',array['Absis oxuna görə əks etdirməklə','Ordinat oxuna görə əks etdirməklə','Yuxarı sürüşdürməklə','Dövrü dəyişməklə'],1),
('riy10-triq-qrafik#30','riy-10-triq-qrafik',3,2,'y = cos x funksiyasının sıfırları hansı nöqtələrdədir?','cos x = 0 bərabərliyi x = π/2 + πn nöqtələrində ödənir.',array['x = π/2 + πn nöqtələrində','x = πn nöqtələrində','x = 2πn nöqtələrində','Sıfırları yoxdur'],1),
('riy10-triq-qrafik#31','riy-10-triq-qrafik',2,2,'Günün uzunluğunun il ərzində dəyişməsi hansı tip funksiya ilə təsvir oluna bilər?','Bu, təkrarlanan hadisədir - dövri funksiya ilə modelləşdirilir.',array['Dövri funksiya ilə','Daim artan funksiya ilə','Sabit funksiya ilə','Kvadrat funksiya ilə'],1),
('riy10-triq-qrafik#32','riy-10-triq-qrafik',2,2,'Amplitudu 5 olan y = 5 sin x funksiyası hansı parçadan qiymətlər alır?','Amplitud 5-dir: qiymətlər [−5; 5] parçasındadır.',array['[−5; 5]','[−1; 1]','[0; 5]','Bütün ədədlər'],1),
('riy10-triq-qrafik#33','riy-10-triq-qrafik',3,2,'Harmonik rəqs hansı düsturla yazılır?','Harmonik rəqs x = A sin(ωt + φ) şəklində təsvir olunur.',array['x = A sin(ωt + φ)','x = At + φ','x = Aω/t','x = A + t²'],1),
('riy10-triq-qrafik#34','riy-10-triq-qrafik',3,2,'İkinci rübə uyğun [π/2; π] parçasında sinus funksiyası artır, yoxsa azalır?','Bu parçada sinus 1-dən 0-a qədər azalır.',array['Azalır','Artır','Sabit qalır','Kəsilir'],1),
('riy10-triq-qrafik#35','riy-10-triq-qrafik',2,2,'T dövrlü dövri funksiya üçün f(x + T) nəyə bərabərdir?','Dövriliyin tərifinə görə f(x + T) = f(x).',array['f(x)-ə','f(T)-yə','Sıfıra','f(x) + T-yə'],1),
('riy10-triq-qrafik#36','riy-10-triq-qrafik',3,2,'y = tan x funksiyasının qiymətlər çoxluğu hansıdır?','Tangens bütün həqiqi qiymətləri alır.',array['Bütün həqiqi ədədlər','[−1; 1] parçası','[0; π] parçası','Yalnız müsbət ədədlər'],1),
('riy10-triq-qrafik#37','riy-10-triq-qrafik',2,2,'Sinusoidin absis oxundan ən böyük uzaqlığı (y = sin x üçün) neçədir?','Sinusun amplitudu 1-dir: ən böyük uzaqlıq 1 vahiddir.',array['1 vahid','2 vahid','π vahid','Sonsuzdur'],1),
('riy10-triq-qrafik#38','riy-10-triq-qrafik',3,2,'y = cos 2x funksiyasının ən kiçik müsbət dövrü nədir?','T = 2π/2 = π.',array['π radian','2π radian','4π radian','π/3 radian'],1),
('riy10-triq-qrafik#39','riy-10-triq-qrafik',2,2,'y = 4 sin x funksiyasının amplitudu neçədir?','Amplitud əmsalın moduludur: 4.',array['4','1','8','2π'],1),
('riy10-triq-qrafik#40','riy-10-triq-qrafik',2,2,'Dəyişən elektrik cərəyanının zamana görə dəyişməsi hansı qrafiklə təsvir olunur?','Dəyişən cərəyan harmonik qanunla dəyişir - qrafiki sinusoiddir.',array['Sinusoidlə','Düz xətlə','Parabola ilə','Pilləli xətlə'],1),
('riy10-coxuzlu#1','riy-10-coxuzlu',1,2,'Çoxüzlü nədir?','Çoxüzlü hər tərəfdən çoxbucaqlılarla hüdudlanmış fəza cismidir.',array['Çoxbucaqlılarla hüdudlanmış fəza cismi','Müstəvi fiqur','Əyri səthli cisim','Nöqtələr çoxluğu'],1),
('riy10-coxuzlu#2','riy-10-coxuzlu',1,2,'Prizmanın oturacaqları bir-birinə görə necədir?','Prizmanın oturacaqları bərabər və paralel çoxbucaqlılardır.',array['Bərabər və paraleldir','Fərqli və perpendikulyar','Yalnız biri çoxbucaqlıdır','Həmişə üçbucaqdır'],1),
('riy10-coxuzlu#3','riy-10-coxuzlu',2,2,'Düz prizmada yan tillər oturacağa necə yerləşir?','Düz prizmada yan tillər oturacağa perpendikulyardır.',array['Perpendikulyar','Paralel','45 dərəcə altında','İxtiyari'],1),
('riy10-coxuzlu#4','riy-10-coxuzlu',2,2,'Düz prizmanın yan üzləri hansı fiqurlardır?','Düz prizmanın yan üzləri düzbucaqlılardır.',array['Düzbucaqlılar','Üçbucaqlar','Trapesiyalar','Çevrələr'],1),
('riy10-coxuzlu#5','riy-10-coxuzlu',2,2,'Üçbucaq prizmanın neçə üzü var?','2 oturacaq + 3 yan üz = 5 üz.',array['5 üzü','6 üzü','4 üzü','3 üzü'],1),
('riy10-coxuzlu#6','riy-10-coxuzlu',2,2,'Düzbucaqlı paralelepipedin üzləri hansı fiqurlardır və neçədir?','Paralelepipedin 6 üzü var, hamısı düzbucaqlıdır.',array['6 düzbucaqlı','4 kvadrat','8 üçbucaq','5 paraleloqram'],1),
('riy10-coxuzlu#7','riy-10-coxuzlu',1,2,'Düzbucaqlı paralelepipedin neçə tili var?','Paralelepipedin 12 tili var: hər ölçüdən 4 ədəd.',array['12 tili','8 tili','6 tili','10 tili'],1),
('riy10-coxuzlu#8','riy-10-coxuzlu',1,2,'Kubun neçə təpəsi var?','Kubun 8 təpəsi var.',array['8 təpəsi','6 təpəsi','12 təpəsi','4 təpəsi'],1),
('riy10-coxuzlu#9','riy-10-coxuzlu',2,2,'Tili 5 sm olan kubun tam səthinin sahəsi neçə kvadrat santimetrdir?','S = 6a² = 6 · 25 = 150 sm².',array['150 sm²','125 sm²','100 sm²','75 sm²'],1),
('riy10-coxuzlu#10','riy-10-coxuzlu',3,2,'Ölçüləri 2, 3 və 4 sm olan düzbucaqlı paralelepipedin tam səthinin sahəsini tapın.','S = 2(2·3 + 3·4 + 2·4) = 2 · 26 = 52 sm².',array['52 sm²','24 sm²','26 sm²','48 sm²'],1),
('riy10-coxuzlu#11','riy-10-coxuzlu',2,2,'Oturacağının perimetri 12 sm, hündürlüyü 5 sm olan düz prizmanın yan səthinin sahəsini tapın.','S(yan) = P · h = 12 · 5 = 60 sm².',array['60 sm²','17 sm²','30 sm²','120 sm²'],1),
('riy10-coxuzlu#12','riy-10-coxuzlu',1,2,'Piramidanın yan üzləri hansı fiqurlardır?','Piramidanın yan üzləri ortaq təpəli üçbucaqlardır.',array['Üçbucaqlar','Kvadratlar','Trapesiyalar','Paraleloqramlar'],1),
('riy10-coxuzlu#13','riy-10-coxuzlu',2,2,'Dördbucaqlı piramidanın neçə üzü var?','1 oturacaq + 4 yan üz = 5 üz.',array['5 üzü var','4 üzü var','6 üzü var','8 üzü var'],1),
('riy10-coxuzlu#14','riy-10-coxuzlu',3,2,'Düzgün piramidanın apofemi nədir?','Apofem yan üzün təpədən oturacaq tilinə çəkilmiş hündürlüyüdür.',array['Yan üzün oturacaq tilinə çəkilən hündürlüyü','Oturacağın diaqonalı','Yan tilin uzunluğu','Oturacağın perimetri'],1),
('riy10-coxuzlu#15','riy-10-coxuzlu',2,2,'Düzgün piramidanın oturacağı hansı fiqurdur?','Düzgün piramidanın oturacağı düzgün çoxbucaqlıdır.',array['Düzgün çoxbucaqlı','İxtiyari üçbucaq','Çevrə','Trapesiya'],1),
('riy10-coxuzlu#16','riy-10-coxuzlu',2,2,'Kəsik piramida necə alınır?','Piramida oturacağa paralel müstəvi ilə kəsildikdə kəsik piramida alınır.',array['Piramidanın oturacağa paralel müstəvi ilə kəsilməsindən','İki prizmanın birləşməsindən','Kubun yarıya bölünməsindən','Çevrənin fırlanmasından'],1),
('riy10-coxuzlu#17','riy-10-coxuzlu',3,2,'Kəsik piramidanın oturacaqları bir-birinə görə necədir?','Kəsik piramidanın oturacaqları oxşar çoxbucaqlılardır.',array['Oxşar çoxbucaqlılardır','Bərabər fiqurlardır','Perpendikulyar fiqurlardır','Həmişə kvadratdır'],1),
('riy10-coxuzlu#18','riy-10-coxuzlu',2,2,'Prizmanın hündürlüyü nədir?','Hündürlük oturacaq müstəviləri arasındakı məsafədir.',array['Oturacaqlar arasındakı məsafə','Ən uzun til','Oturacağın perimetri','Diaqonalın yarısı'],1),
('riy10-coxuzlu#19','riy-10-coxuzlu',2,2,'Kubun bir üzünün sahəsi 16 sm²-dirsə, tam səthinin sahəsi neçədir?','Tam səth = 6 · 16 = 96 sm².',array['96 sm²','64 sm²','32 sm²','48 sm²'],1),
('riy10-coxuzlu#20','riy-10-coxuzlu',2,2,'Üçbucaq piramidanın neçə təpəsi var?','Oturacağın 3 təpəsi + 1 zirvə = 4 təpə.',array['4 təpəsi','3 təpəsi','5 təpəsi','6 təpəsi'],1),
('riy10-coxuzlu#21','riy-10-coxuzlu',3,2,'Beşbucaqlı prizmanın neçə tili var?','2 · 5 oturacaq tili + 5 yan til = 15 til.',array['15','10','12','20'],1),
('riy10-coxuzlu#22','riy-10-coxuzlu',2,2,'Altıbucaqlı prizmanın neçə üzü var?','2 oturacaq + 6 yan üz = 8 üz.',array['8 üz','6 üz','12 üz','10 üz'],1),
('riy10-coxuzlu#23','riy-10-coxuzlu',2,2,'Düzgün dördbucaqlı prizmanın oturacağı hansı fiqurdur?','Düzgün dördbucaqlı prizmanın oturacağı kvadratdır.',array['Kvadrat','Romb','Trapesiya','Beşbucaqlı'],1),
('riy10-coxuzlu#24','riy-10-coxuzlu',2,2,'Maili prizma hansı prizmadır?','Yan tilləri oturacağa perpendikulyar olmayan prizma mailidir.',array['Yan tilləri oturacağa perpendikulyar olmayan','Oturacağı üçbucaq olan','Hündürlüyü böyük olan','Üzləri bərabər olan'],1),
('riy10-coxuzlu#25','riy-10-coxuzlu',2,2,'Prizmanın tam səthi necə hesablanır?','Tam səth yan səthlə iki oturacağın sahələrinin cəmidir.',array['Yan səth + iki oturacağın sahəsi','Yalnız yan səth','Oturacaqların hasili','Perimetrin kvadratı'],1),
('riy10-coxuzlu#26','riy-10-coxuzlu',3,2,'Oturacaq tili 6 sm, apofemi 5 sm olan düzgün dördbucaqlı piramidanın yan səthini tapın.','S(yan) = (1/2) · P · l = (1/2) · 24 · 5 = 60 sm².',array['60 sm²','30 sm²','120 sm²','44 sm²'],1),
('riy10-coxuzlu#27','riy-10-coxuzlu',1,2,'İkiyamaclı ev damı hansı həndəsi cismi xatırladır?','Belə dam üçbucaq oturacaqlı prizmanı xatırladır.',array['Üçbucaq prizmanı','Kubu','Kürəni','Silindri'],1),
('riy10-coxuzlu#28','riy-10-coxuzlu',1,2,'Misir ehramları hansı həndəsi cismin formasındadır?','Ehramlar düzgün dördbucaqlı piramida formasındadır.',array['Düzgün dördbucaqlı piramidanın','Kubun','Prizmanın','Konusun'],1),
('riy10-coxuzlu#29','riy-10-coxuzlu',2,2,'Texniki rəsmdə çoxüzlünün müxtəlif tərəflərdən görünüşləri nə üçün çəkilir?','Üç görünüş cismin formasını tam təsəvvür etməyə imkan verir.',array['Formanı tam təsvir etmək üçün','Rəsmi bəzəmək üçün','Kağız doldurmaq üçün','Rəng seçmək üçün'],1),
('riy10-coxuzlu#30','riy-10-coxuzlu',3,2,'Prizmanın diaqonal kəsiyi hansı müstəvi kəsikdir?','Diaqonal kəsik qonşu olmayan yan tillərdən keçən kəsikdir.',array['Qonşu olmayan yan tillərdən keçən kəsik','Oturacağa paralel kəsik','Bir tildən keçən kəsik','Səthə toxunan müstəvi'],1),
('riy10-coxuzlu#31','riy-10-coxuzlu',3,2,'Kubun diaqonal kəsiyi hansı fiqurdur?','Kubun diaqonal kəsiyi düzbucaqlıdır.',array['Düzbucaqlı','Kvadrat həmişə','Üçbucaq','Altıbucaqlı həmişə'],1),
('riy10-coxuzlu#32','riy-10-coxuzlu',3,2,'Kub üçün üzlərin sayı ilə təpələrin sayının cəmindən tillərin sayını çıxdıqda neçə alınır?','Eyler düsturu: Ü + T − t = 6 + 8 − 12 = 2.',array['2-yə bərabərdir','0-a bərabərdir','6-ya bərabərdir','4-ə bərabərdir'],1),
('riy10-coxuzlu#33','riy-10-coxuzlu',2,2,'Düzgün tetraedrin üzləri hansı fiqurlardır?','Düzgün tetraedrin dörd üzü də bərabərtərəfli üçbucaqdır.',array['Bərabərtərəfli üçbucaqlar','Kvadratlar','Düzbucaqlılar','Beşbucaqlılar'],1),
('riy10-coxuzlu#34','riy-10-coxuzlu',3,2,'Ölçüləri 4, 4 və 7 sm olan düzbucaqlı paralelepipedin diaqonalını tapın.','d = √(16 + 16 + 49) = √81 = 9 sm.',array['9 sm','15 sm','11 sm','8 sm'],1),
('riy10-coxuzlu#35','riy-10-coxuzlu',2,2,'Düzgün prizma hansı prizmadır?','Oturacağı düzgün çoxbucaqlı olan düz prizma düzgün prizma adlanır.',array['Oturacağı düzgün çoxbucaqlı olan düz prizma','İxtiyari maili prizma','Oturacağı çevrə olan cisim','Bütün üzləri üçbucaq olan cisim'],1),
('riy10-coxuzlu#36','riy-10-coxuzlu',2,2,'Piramidanın hündürlüyü haradan haraya endirilir?','Hündürlük zirvədən oturacaq müstəvisinə perpendikulyar endirilir.',array['Zirvədən oturacaq müstəvisinə','Oturacaqdan yan üzə','Bir tildən digərinə','Apofemin ortasından'],1),
('riy10-coxuzlu#37','riy-10-coxuzlu',3,2,'Oturacağının perimetri 18 sm, hündürlüyü 3 sm olan düz prizmanın yan səthi neçədir?','S(yan) = 18 · 3 = 54 sm².',array['54 sm²','21 sm²','27 sm²','108 sm²'],1),
('riy10-coxuzlu#38','riy-10-coxuzlu',2,2,'Aşağıdakı cisimlərdən hansı çoxüzlü deyil?','Silindrin səthi əyridir - o, çoxüzlü deyil.',array['Silindr','Kub','Prizma','Piramida'],1),
('riy10-coxuzlu#39','riy-10-coxuzlu',3,2,'Kəsik piramidanın yan üzləri hansı fiqurlardır?','Kəsik piramidanın yan üzləri trapesiyalardır.',array['Trapesiyalar','Üçbucaqlar','Kvadratlar','Çevrələr'],1),
('riy10-coxuzlu#40','riy-10-coxuzlu',3,2,'Düzgün altıbucaqlı prizmanın oturacağının hər daxili bucağı neçə dərəcədir?','Düzgün altıbucaqlının daxili bucağı 120 dərəcədir.',array['120','90','60','135'],1),
('riy10-triq-tenlik#1','riy-10-triq-tenlik',2,3,'arcsin a nədir?','arcsin a - sinusu a-ya bərabər olan, [−π/2; π/2] parçasındakı bucaqdır.',array['Sinusu a olan [−π/2; π/2] parçasındakı bucaq','Kosinusu a olan bucaq','a-nın kvadrat kökü','a bucağının sinusu'],1),
('riy10-triq-tenlik#2','riy-10-triq-tenlik',3,3,'arcsin(1/2) qiymətini tapın.','sin(π/6) = 1/2 olduğundan arcsin(1/2) = π/6.',array['π/6','π/3','π/2','π/4'],1),
('riy10-triq-tenlik#3','riy-10-triq-tenlik',3,3,'arccos(1/2) qiymətini tapın.','cos(π/3) = 1/2 olduğundan arccos(1/2) = π/3.',array['π/3-ə bərabərdir','π/6-ya bərabərdir','π/2-yə bərabərdir','π-yə bərabərdir'],1),
('riy10-triq-tenlik#4','riy-10-triq-tenlik',3,3,'arctan 1 qiymətini tapın.','tan(π/4) = 1 olduğundan arctan 1 = π/4.',array['π/4','π/3','π/6','π'],1),
('riy10-triq-tenlik#5','riy-10-triq-tenlik',3,3,'arccos 1 qiyməti neçədir?','cos 0 = 1 olduğundan arccos 1 = 0.',array['Sıfırdır','π-dir','π/2-dir','1-dir'],1),
('riy10-triq-tenlik#6','riy-10-triq-tenlik',2,3,'sin x = 0 tənliyinin ümumi həlli hansıdır?','Sinus πn nöqtələrində sıfırlanır: x = πn.',array['x = πn','x = π/2 + πn','x = 2πn yalnız','x = π/4 + πn'],1),
('riy10-triq-tenlik#7','riy-10-triq-tenlik',2,3,'cos x = 0 tənliyinin ümumi həlli hansıdır?','Kosinus π/2 + πn nöqtələrində sıfırlanır.',array['x = π/2 + πn','x = πn','x = 2πn','x = π + 2πn'],1),
('riy10-triq-tenlik#8','riy-10-triq-tenlik',3,3,'sin x = 1 tənliyinin ümumi həlli hansıdır?','Sinus maksimumu π/2 + 2πn nöqtələrində alır.',array['x = π/2 + 2πn','x = πn','x = π + 2πn','x = π/2 + πn'],1),
('riy10-triq-tenlik#9','riy-10-triq-tenlik',3,3,'cos x = 1 tənliyinin ümumi həlli hansıdır?','Kosinus 1 qiymətini tam dövrlərdə alır: x = 2πn.',array['x = 2πn','x = πn','x = π/2 + 2πn','x = π + πn'],1),
('riy10-triq-tenlik#10','riy-10-triq-tenlik',2,3,'sin x = 2 tənliyinin neçə həlli var?','|sin x| ≤ 1 olduğundan sin x = 2 tənliyinin həlli yoxdur.',array['Həlli yoxdur','Bir həlli var','İki həlli var','Sonsuz həlli var'],1),
('riy10-triq-tenlik#11','riy-10-triq-tenlik',2,3,'cos x = −5 tənliyi barədə nə demək olar?','|cos x| ≤ 1 olduğundan tənliyin kökü yoxdur.',array['Kökü yoxdur','Bir kökü var','Kökü x = −5-dir','Sonsuz kökü var'],1),
('riy10-triq-tenlik#12','riy-10-triq-tenlik',2,3,'sin x = a tənliyinin həlli olması üçün a hansı şərti ödəməlidir?','Sinusun qiymətləri [−1; 1]-dədir: |a| ≤ 1 olmalıdır.',array['|a| ≤ 1','a > 0','a < 2','a istənilən ədəd ola bilər'],1),
('riy10-triq-tenlik#13','riy-10-triq-tenlik',3,3,'sin x = 1/2 tənliyinin ümumi həlli hansıdır?','x = (−1)ⁿ · π/6 + πn.',array['x = (−1)ⁿ·π/6 + πn','x = π/6 yalnız','x = ±π/6 + 2πn deyil, πn','x = π/3 + 2πn'],1),
('riy10-triq-tenlik#14','riy-10-triq-tenlik',3,3,'Ümumi həlli x = ±π/3 + 2πn olan ən sadə triqonometrik tənlik hansıdır?','cos x = 1/2 tənliyinin həlli x = ±π/3 + 2πn-dir.',array['cos x = 1/2','sin x = 1/2','tan x = 1/2','cos x = 2'],1),
('riy10-triq-tenlik#15','riy-10-triq-tenlik',3,3,'tan x = 1 tənliyinin ümumi həlli hansıdır?','x = π/4 + πn.',array['x = π/4 + πn','x = π/4 + 2πn','x = π/2 + πn','x = πn'],1),
('riy10-triq-tenlik#16','riy-10-triq-tenlik',3,3,'tan x = 0 tənliyinin həlli hansıdır?','Tangens sin x = 0 olduqda sıfırlanır: x = πn.',array['x = πn (n tam ədəddir)','x = π/2 + πn','x = π/4 + πn','Həlli yoxdur'],1),
('riy10-triq-tenlik#17','riy-10-triq-tenlik',3,3,'Sinusun ən kiçik qiymətini aldığı nöqtələrin ümumi düsturu hansıdır?','sin x = −1 minimumu x = −π/2 + 2πn nöqtələrində alınır.',array['x = −π/2 + 2πn','x = π/2 + 2πn','x = πn','x = π + πn'],1),
('riy10-triq-tenlik#18','riy-10-triq-tenlik',3,3,'Kosinusun minimum qiymətinə uyğun gələn ümumi həll hansıdır?','cos x = −1 olduqda x = π + 2πn.',array['x = π + 2πn','x = 2πn','x = π/2 + πn','x = π/4 + 2πn'],1),
('riy10-triq-tenlik#19','riy-10-triq-tenlik',3,3,'[0; 2π] parçasında sin x = 0 tənliyinin neçə kökü var?','Köklər: 0, π və 2π - cəmi 3 kök.',array['3 kökü','1 kökü','2 kökü','4 kökü'],1),
('riy10-triq-tenlik#20','riy-10-triq-tenlik',3,3,'[0; 2π] parçasında cos x = 0 tənliyinin neçə kökü var?','Köklər: π/2 və 3π/2 - cəmi 2 kök.',array['2 kökü','3 kökü','1 kökü','5 kökü'],1),
('riy10-triq-tenlik#21','riy-10-triq-tenlik',3,3,'arcsin funksiyasının qiymətlər çoxluğu hansıdır?','arcsin qiymətləri [−π/2; π/2] parçasındadır.',array['[−π/2; π/2]','[0; π]','[−1; 1]','Bütün ədədlər'],1),
('riy10-triq-tenlik#22','riy-10-triq-tenlik',3,3,'arccos funksiyasının qiymətlər çoxluğu hansıdır?','arccos qiymətləri [0; π] parçasındadır.',array['[0; π]','[−π/2; π/2]','[−1; 1]','[0; 2π]'],1),
('riy10-triq-tenlik#23','riy-10-triq-tenlik',3,3,'arcsin(−a) ifadəsi nəyə bərabərdir?','arcsin tək funksiyadır: arcsin(−a) = −arcsin a.',array['−arcsin a','arcsin a','π − arcsin a','π + arcsin a'],1),
('riy10-triq-tenlik#24','riy-10-triq-tenlik',3,3,'arccos(−a) ifadəsi nəyə bərabərdir?','arccos üçün: arccos(−a) = π − arccos a.',array['π − arccos a','−arccos a','arccos a','π + arccos a'],1),
('riy10-triq-tenlik#25','riy-10-triq-tenlik',2,3,'2 sin x = 1 tənliyini ən sadə şəklə salın.','Hər iki tərəfi 2-yə bölürük: sin x = 1/2.',array['sin x = 1/2','sin x = 2','x = 1/2','sin 2x = 1'],1),
('riy10-triq-tenlik#26','riy-10-triq-tenlik',3,3,'sin²x = 1 tənliyinin həlli hansıdır?','sin x = ±1, yəni x = π/2 + πn.',array['x = π/2 + πn','x = πn','x = 2πn','Həlli yoxdur'],1),
('riy10-triq-tenlik#27','riy-10-triq-tenlik',1,3,'Triqonometrik tənlik nədir?','Naməlumu triqonometrik funksiya işarəsi altında olan tənlikdir.',array['Naməlumu triqonometrik funksiya altında olan tənlik','Yalnız kvadrat tənlik','Həndəsi bərabərsizlik','Ədədi ifadə'],1),
('riy10-triq-tenlik#28','riy-10-triq-tenlik',3,3,'cos x = 0,5 tənliyinin ən kiçik müsbət kökü hansıdır?','Ən kiçik müsbət kök x = π/3-dür.',array['π/3','π/6','2π/3','π'],1),
('riy10-triq-tenlik#29','riy-10-triq-tenlik',3,3,'tan x = √3 tənliyinin ümumi həlli hansıdır?','tan(π/3) = √3: x = π/3 + πn.',array['x = π/3 + πn','x = π/6 + πn','x = π/3 + 2πn','x = √3 + πn'],1),
('riy10-triq-tenlik#30','riy-10-triq-tenlik',3,3,'sin 2x = 0 tənliyinin həlli hansıdır?','2x = πn, buradan x = πn/2.',array['x = πn/2','x = πn','x = 2πn','x = π/2 + πn'],1),
('riy10-triq-tenlik#31','riy-10-triq-tenlik',3,3,'arctan funksiyasının qiymətlər çoxluğu hansıdır?','arctan qiymətləri (−π/2; π/2) intervalındadır.',array['(−π/2; π/2) intervalı','[0; π] parçası','[−1; 1] parçası','Bütün ədədlər'],1),
('riy10-triq-tenlik#32','riy-10-triq-tenlik',3,3,'0 < a < 1 olduqda [0; π] parçasında sin x = a tənliyinin neçə kökü var?','Köklər x = arcsin a və x = π − arcsin a-dır: iki kök.',array['İki kökü','Bir kökü','Üç kökü','Kökü yoxdur'],1),
('riy10-triq-tenlik#33','riy-10-triq-tenlik',3,3,'2sin²x − sin x = 0 tənliyi hansı üsulla həll olunur?','sin x(2 sin x − 1) = 0 - vuruqlara ayırma üsulu ilə.',array['Vuruqlara ayırma ilə','Loqarifmləmə ilə','Qrafik çəkmədən kök tapmaq olmur','Hədləri atmaqla'],1),
('riy10-triq-tenlik#34','riy-10-triq-tenlik',3,3,'cos²x − 1 = 0 tənliyinin həlli hansıdır?','cos x = ±1, yəni x = πn.',array['x = πn olur','x = π/2 + πn olur','x = π/4 + πn olur','Həlli yoxdur'],1),
('riy10-triq-tenlik#35','riy-10-triq-tenlik',3,3,'Rəqqasın tarazlıq vəziyyətindən keçdiyi anlar hansı tənliklə tapılır?','Meyletmə sıfır olur - sinuslu ifadə sıfıra bərabər götürülür.',array['Sin ifadəsinin sıfıra bərabərliyi ilə','Kosinusun vahidə bərabərliyi ilə','Tangensin sonsuzluğu ilə','Loqarifmik tənliklə'],1),
('riy10-triq-tenlik#36','riy-10-triq-tenlik',3,3,'arcsin 1 qiymətini tapın.','sin(π/2) = 1 olduğundan arcsin 1 = π/2.',array['π/2','0','π','1'],1),
('riy10-triq-tenlik#37','riy-10-triq-tenlik',3,3,'arccos 0 qiyməti nəyə bərabərdir?','cos(π/2) = 0 olduğundan arccos 0 = π/2.',array['π/2-dir','0-dır','π-dir','2π-dir'],1),
('riy10-triq-tenlik#38','riy-10-triq-tenlik',2,3,'Ən sadə triqonometrik tənliklər hansılardır?','sin x = a, cos x = a və tan x = a şəklindəki tənliklər.',array['sin x = a, cos x = a, tan x = a','x² = a','log x = a','x + a = 0'],1),
('riy10-triq-tenlik#39','riy-10-triq-tenlik',3,3,'sin x = √3/2 tənliyinin [0; π/2] parçasındakı kökü hansıdır?','sin(π/3) = √3/2: kök x = π/3-dür.',array['x = π/3','x = π/6','x = π/4','x = π/2'],1),
('riy10-triq-tenlik#40','riy-10-triq-tenlik',2,3,'Triqonometrik tənliyin qrafik üsulla həlli necə aparılır?','Sol və sağ tərəflərin qrafikləri qurulur, kəsişmə nöqtələrinin absisləri tapılır.',array['Qrafiklərin kəsişmə nöqtələri tapılır','Qrafikin sahəsi hesablanır','Qrafik rənglənir','Qrafik silinir'],1),
('riy10-hecm#1','riy-10-hecm',1,3,'Prizmanın həcmi hansı düsturla hesablanır?','V = S(oturacaq) · h.',array['V = S(oturacaq) · h','V = S · h / 3','V = P · h','V = 6a²'],1),
('riy10-hecm#2','riy-10-hecm',2,3,'Tili 4 sm olan kubun həcmini tapın.','V = a³ = 4³ = 64 sm³.',array['64 sm³','16 sm³','12 sm³','48 sm³'],1),
('riy10-hecm#3','riy-10-hecm',2,3,'Ölçüləri 2, 3 və 5 sm olan düzbucaqlı paralelepipedin həcmini tapın.','V = 2 · 3 · 5 = 30 sm³.',array['30 sm³','10 sm³','60 sm³','25 sm³'],1),
('riy10-hecm#4','riy-10-hecm',1,3,'Piramidanın həcmi hansı düsturla hesablanır?','V = S(oturacaq) · h / 3.',array['V = S · h / 3','V = S · h','V = S · h / 2','V = P · h / 3'],1),
('riy10-hecm#5','riy-10-hecm',2,3,'Oturacağının sahəsi 12 sm², hündürlüyü 5 sm olan piramidanın həcmini tapın.','V = 12 · 5 / 3 = 20 sm³.',array['20 sm³','60 sm³','30 sm³','17 sm³'],1),
('riy10-hecm#6','riy-10-hecm',2,3,'Həcmi 27 sm³ olan kubun tili neçə santimetrdir?','a³ = 27, a = 3 sm.',array['3 sm','9 sm','27 sm','6 sm'],1),
('riy10-hecm#7','riy-10-hecm',2,3,'Oturacağının sahəsi 10 sm², hündürlüyü 7 sm olan prizmanın həcmini tapın.','V = 10 · 7 = 70 sm³.',array['70 sm³','35 sm³','17 sm³','210 sm³'],1),
('riy10-hecm#8','riy-10-hecm',1,3,'Həcm hansı vahidlərlə ölçülür?','Həcm kub vahidlərlə - sm³, m³ ilə ölçülür.',array['Kub vahidlərlə (sm³, m³)','Kvadrat vahidlərlə','Uzunluq vahidləri ilə','Dərəcə ilə'],1),
('riy10-hecm#9','riy-10-hecm',2,3,'Eyni oturacaqlı və eyni hündürlüklü piramida ilə prizmanın həcmləri necə fərqlənir?','Piramidanın həcmi prizmanınkından 3 dəfə kiçikdir.',array['Piramidanınki 3 dəfə kiçikdir','Bərabərdirlər','Piramidanınki 2 dəfə böyükdür','Prizmanınki 3 dəfə kiçikdir'],1),
('riy10-hecm#10','riy-10-hecm',3,3,'Fəza fiqurunun xətti ölçüləri 2 dəfə artırıldıqda həcmi neçə dəfə artır?','Həcm xətti ölçünün kubu kimi dəyişir: 2³ = 8 dəfə.',array['8 dəfə artır','2 dəfə artır','4 dəfə artır','6 dəfə artır'],1),
('riy10-hecm#11','riy-10-hecm',3,3,'Oxşar fiqurların həcmləri nisbəti xətti ölçülər nisbətinin hansı qüvvəsinə bərabərdir?','Həcmlər nisbəti oxşarlıq əmsalının kubuna bərabərdir.',array['Kubuna','Kvadratına','Birinci qüvvəsinə','Dördüncü qüvvəsinə'],1),
('riy10-hecm#12','riy-10-hecm',3,3,'Oxşar fiqurların səthlərinin sahələri nisbəti nəyə bərabərdir?','Səthlər nisbəti oxşarlıq əmsalının kvadratına bərabərdir.',array['Oxşarlıq əmsalının kvadratına','Oxşarlıq əmsalının kubuna','Oxşarlıq əmsalına','Həmişə vahidə'],1),
('riy10-hecm#13','riy-10-hecm',3,3,'Kəsik piramidanın həcmini tapmaq üçün hansı kəmiyyətlər lazımdır?','İki oturacağın sahələri və hündürlük lazımdır.',array['İki oturacağın sahələri və hündürlük','Yalnız perimetr','Yalnız apofem','Yalnız yan səth'],1),
('riy10-hecm#14','riy-10-hecm',3,3,'Ölçüləri 40 sm, 30 sm və 50 sm olan akvariumun tutumu neçə litrdir?','V = 40·30·50 = 60000 sm³ = 60 litr.',array['60 litr','6 litr','600 litr','120 litr'],1),
('riy10-hecm#15','riy-10-hecm',3,3,'Aşağıdakı fiqurlardan hansının simmetriya mərkəzi var?','Kubun diaqonallarının kəsişdiyi nöqtə onun simmetriya mərkəzidir.',array['Kub','İxtiyari piramida','Kəsik piramida','Tetraedr'],1),
('riy10-hecm#16','riy-10-hecm',3,3,'Kubun simmetriya mərkəzi harada yerləşir?','Mərkəz kubun diaqonallarının kəsişmə nöqtəsindədir.',array['Diaqonalların kəsişməsində','Bir təpəsində','Bir üzünün mərkəzində','Kubdan kənarda'],1),
('riy10-hecm#17','riy-10-hecm',2,3,'Ölçüləri 5, 4 və 3 m olan otağın həcmi neçə kubmetrdir?','V = 5 · 4 · 3 = 60 m³.',array['60 m³','12 m³','47 m³','120 m³'],1),
('riy10-hecm#18','riy-10-hecm',3,3,'Oturacağının sahəsi 24 sm², hündürlüyü 10 sm olan piramidanın həcmini tapın.','V = 24 · 10 / 3 = 80 sm³.',array['80 sm³','240 sm³','34 sm³','120 sm³'],1),
('riy10-hecm#19','riy-10-hecm',3,3,'Həcmi 90 sm³, oturacağının sahəsi 15 sm² olan prizmanın hündürlüyünü tapın.','h = V/S = 90/15 = 6 sm.',array['6 sm','75 sm','15 sm','3 sm'],1),
('riy10-hecm#20','riy-10-hecm',3,3,'Kubun tili 2 dəfə kiçildikdə həcmi neçə dəfə azalır?','Həcm 2³ = 8 dəfə azalır.',array['8 dəfə azalır','2 dəfə azalır','4 dəfə azalır','16 dəfə azalır'],1),
('riy10-hecm#21','riy-10-hecm',3,3,'Oturacaq tili 3 sm, hündürlüyü 4 sm olan düzgün dördbucaqlı piramidanın həcmini tapın.','V = 3² · 4 / 3 = 12 sm³.',array['12 sm³','36 sm³','9 sm³','24 sm³'],1),
('riy10-hecm#22','riy-10-hecm',2,3,'Hansı cismin həcmi oturacaq sahəsi ilə hündürlük hasilinin üçdə birinə bərabərdir?','Bu düstur piramidanın həcm düsturudur.',array['Piramidanın','Prizmanın','Kubun','Paralelepipedin'],1),
('riy10-hecm#23','riy-10-hecm',1,3,'Tikintidə betonun miqdarı adətən hansı vahidlə ölçülür?','Beton kubmetrlə hesablanır.',array['Kubmetrlə','Kiloqramla yalnız','Litrlə yalnız','Metrlə'],1),
('riy10-hecm#24','riy-10-hecm',3,3,'Kubun həcmi ilə tam səthinin ədədi qiymətləri bərabərdirsə (a³ = 6a²), tili neçədir?','a³ = 6a² tənliyindən a = 6.',array['a = 6','a = 3','a = 1','a = 12'],1),
('riy10-hecm#25','riy-10-hecm',3,3,'Tilləri 1:2 nisbətində olan iki kubun həcmləri hansı nisbətdədir?','Həcmlər 1³:2³ = 1:8 nisbətindədir.',array['1:8','1:2','1:4','1:6'],1),
('riy10-hecm#26','riy-10-hecm',3,3,'Ölçüləri 25 sm, 12 sm və 6 sm olan kərpicin həcmini tapın.','V = 25 · 12 · 6 = 1800 sm³.',array['1800 sm³','180 sm³','900 sm³','43 sm³'],1),
('riy10-hecm#27','riy-10-hecm',3,3,'Həcmi 30 sm³, oturacağının sahəsi 18 sm² olan piramidanın hündürlüyünü tapın.','30 = 18 · h / 3 = 6h; h = 5 sm.',array['5 sm','6 sm','10 sm','3 sm'],1),
('riy10-hecm#28','riy-10-hecm',3,3,'Maili prizmanın həcmi necə hesablanır?','Yenə V = S(oturacaq) · h; h - oturacaqlar arasındakı məsafədir.',array['V = S(oturacaq) · h düsturu ilə','Maili prizmanın həcmi tapılmır','Yalnız yan səthlə','Perimetrlə hündürlüyün hasili ilə'],1),
('riy10-hecm#29','riy-10-hecm',3,3,'Kubun fırlanma simmetriya oxu varmı?','Üzlərin mərkəzlərindən keçən oxlar fırlanma oxlarıdır.',array['Bəli, var','Xeyr, yoxdur','Yalnız bir dənə','Yalnız kürədə olur'],1),
('riy10-hecm#30','riy-10-hecm',1,3,'Anbarın həcmini bilmək praktikada nə üçün lazımdır?','Həcm anbarın tutumunu - nə qədər yük yerləşəcəyini göstərir.',array['Tutumu hesablamaq üçün','Rəngini seçmək üçün','Ünvanını tapmaq üçün','Heç nə üçün'],1),
('riy10-hecm#31','riy-10-hecm',3,3,'Yük yeri 12 m³ olan vaqona həcmi 0,5 m³ olan neçə qutu yerləşər?','12 / 0,5 = 24 qutu.',array['24 qutu','6 qutu','12 qutu','48 qutu'],1),
('riy10-hecm#32','riy-10-hecm',2,3,'Piramidanın hündürlüyü artdıqca (oturacaq sabit) həcmi necə dəyişir?','V = S·h/3: hündürlük artdıqca həcm artır.',array['Artır','Azalır','Dəyişmir','Sıfırlanır'],1),
('riy10-hecm#33','riy-10-hecm',3,3,'Həcmləri bərabər olan iki fiqurun səthlərinin sahələri həmişə bərabərdirmi?','Xeyr - eyni həcmli fiqurların səthləri fərqli ola bilər.',array['Xeyr, fərqli ola bilər','Bəli, həmişə bərabərdir','Yalnız kublarda fərqlidir','Səth həcmdən asılıdır'],1),
('riy10-hecm#34','riy-10-hecm',1,3,'V = a³ düsturu hansı cismin həcmini verir?','Bu, tili a olan kubun həcm düsturudur.',array['Kubun','Piramidanın','Üçbucaq prizmanın','Kəsik piramidanın'],1),
('riy10-hecm#35','riy-10-hecm',2,3,'Prizmanın oturacağının sahəsi 3 dəfə artırılsa (hündürlük sabit), həcmi necə dəyişər?','V = S·h: həcm də 3 dəfə artar.',array['3 dəfə artar','9 dəfə artar','Dəyişməz','3 dəfə azalar'],1),
('riy10-hecm#36','riy-10-hecm',3,3,'Piramidanın bütün xətti ölçüləri yarıya endirilsə, həcmi neçə dəfə azalar?','Həcm 2³ = 8 dəfə kiçilər.',array['8 dəfə kiçilər','2 dəfə kiçilər','4 dəfə kiçilər','3 dəfə kiçilər'],1),
('riy10-hecm#37','riy-10-hecm',2,3,'Tili 2 m olan kub formalı su çəninin həcmi neçə kubmetrdir?','V = 2³ = 8 m³.',array['8 m³','4 m³','6 m³','2 m³'],1),
('riy10-hecm#38','riy-10-hecm',3,3,'Düzgün tetraedrin həcmini hesablamaq üçün nəyi bilmək kifayətdir?','Bütün tillər bərabərdir - tilin uzunluğu kifayətdir.',array['Tilinin uzunluğunu','Yalnız rəngini','Yalnız kütləsini','Heç nəyi'],1),
('riy10-hecm#39','riy-10-hecm',2,3,'Fəzada müstəviyə görə simmetriyaya gündəlik həyatdan misal hansıdır?','Güzgüdəki əks müstəviyə görə simmetriyadır.',array['Güzgüdəki əks','Kölgənin uzanması','Topun diyirlənməsi','Suyun axması'],1),
('riy10-hecm#40','riy-10-hecm',3,3,'Kub şəklində qutunun içinə yerləşən ən böyük kürənin diametri nəyə bərabərdir?','Kürə üzlərə toxunur: diametr kubun tilinə bərabərdir.',array['Kubun tilinə','Kubun diaqonalına','Tilin yarısına','Perimetrə'],1),
('riy10-ustlu-loqarifm#1','riy-10-ustlu-loqarifm',2,4,'y = aˣ üstlü funksiyasında a əsası hansı şərtləri ödəməlidir?','Üstlü funksiyada əsas müsbət və vahiddən fərqli olmalıdır.',array['a > 0 və a ≠ 1','a < 0','a = 1','a istənilən ədəddir'],1),
('riy10-ustlu-loqarifm#2','riy-10-ustlu-loqarifm',2,4,'a > 1 olduqda y = aˣ funksiyası necə funksiyadır?','Əsas vahiddən böyük olduqda üstlü funksiya artandır.',array['Artandır','Azalandır','Sabitdir','Dövridir'],1),
('riy10-ustlu-loqarifm#3','riy-10-ustlu-loqarifm',2,4,'0 < a < 1 olduqda y = aˣ funksiyası necə dəyişir?','Əsas vahiddən kiçik olduqda üstlü funksiya azalandır.',array['Azalandır','Artandır','Sabitdir','Təyin olunmayıb'],1),
('riy10-ustlu-loqarifm#4','riy-10-ustlu-loqarifm',2,4,'2ˣ = 16 tənliyinin kökünü tapın.','16 = 2⁴ olduğundan x = 4.',array['x = 4','x = 8','x = 2','x = 16'],1),
('riy10-ustlu-loqarifm#5','riy-10-ustlu-loqarifm',2,4,'3ˣ = 27 tənliyinin kökünü tapın.','27 = 3³ olduğundan x = 3.',array['x = 3','x = 9','x = 27','x = 6'],1),
('riy10-ustlu-loqarifm#6','riy-10-ustlu-loqarifm',2,4,'5ˣ = 1 tənliyinin kökü neçədir?','İstənilən müsbət əsasın sıfırıncı qüvvəti 1-dir: x = 0.',array['x = 0','x = 1','x = 5','Kökü yoxdur'],1),
('riy10-ustlu-loqarifm#7','riy-10-ustlu-loqarifm',2,4,'log_a b ifadəsi nəyi göstərir?','Loqarifm - a əsasının b-ni almaq üçün yüksəldilməli olduğu qüvvət üstüdür.',array['b-ni almaq üçün a-nın yüksəldildiyi qüvvət üstünü','a ilə b-nin hasilini','a-nın b-yə nisbətini','b-nin kvadrat kökünü'],1),
('riy10-ustlu-loqarifm#8','riy-10-ustlu-loqarifm',2,4,'log₂ 8 qiymətini tapın.','2³ = 8 olduğundan log₂ 8 = 3.',array['3-ə bərabərdir','4-ə bərabərdir','2-yə bərabərdir','8-ə bərabərdir'],1),
('riy10-ustlu-loqarifm#9','riy-10-ustlu-loqarifm',2,4,'log₃ 9 qiymətini tapın.','3² = 9 olduğundan log₃ 9 = 2.',array['2-yə bərabərdir','3-ə bərabərdir','9-a bərabərdir','6-ya bərabərdir'],1),
('riy10-ustlu-loqarifm#10','riy-10-ustlu-loqarifm',2,4,'lg 1000 qiyməti neçədir?','10³ = 1000 olduğundan lg 1000 = 3.',array['Üçə bərabərdir','Yüzə bərabərdir','Minə bərabərdir','Ona bərabərdir'],1),
('riy10-ustlu-loqarifm#11','riy-10-ustlu-loqarifm',3,4,'log₂ 32 qiymətini tapın.','2⁵ = 32 olduğundan log₂ 32 = 5.',array['5-ə bərabərdir','16-ya bərabərdir','6-ya bərabərdir','4-ə bərabərdir'],1),
('riy10-ustlu-loqarifm#12','riy-10-ustlu-loqarifm',2,4,'İstənilən əsas üçün log_a 1 neçəyə bərabərdir?','a⁰ = 1 olduğundan log_a 1 = 0.',array['0-a bərabərdir','1-ə bərabərdir','a-ya bərabərdir','Təyin olunmayıb'],1),
('riy10-ustlu-loqarifm#13','riy-10-ustlu-loqarifm',2,4,'log_a a ifadəsi neçəyə bərabərdir?','a¹ = a olduğundan log_a a = 1.',array['Vahidə bərabərdir','Sıfra bərabərdir','a-ya bərabərdir','İkiyə bərabərdir'],1),
('riy10-ustlu-loqarifm#14','riy-10-ustlu-loqarifm',2,4,'Loqarifmin arqumenti hansı şərti ödəməlidir?','Loqarifm yalnız müsbət ədədlərdən götürülür: arqument müsbət olmalıdır.',array['Müsbət olmalıdır','Mənfi olmalıdır','Tam olmalıdır','Heç bir şərt yoxdur'],1),
('riy10-ustlu-loqarifm#15','riy-10-ustlu-loqarifm',3,4,'Hasilin loqarifmi hansı qaydayla açılır?','log(xy) = log x + log y.',array['log(xy) = log x + log y','log(xy) = log x · log y','log(xy) = log x − log y','log(xy) = x·y·log'],1),
('riy10-ustlu-loqarifm#16','riy-10-ustlu-loqarifm',3,4,'Nisbətin loqarifmi hansı qaydayla açılır?','log(x/y) = log x − log y.',array['log(x/y) = log x − log y','log(x/y) = log x + log y','log(x/y) = log x / log y','log(x/y) = log y − log x'],1),
('riy10-ustlu-loqarifm#17','riy-10-ustlu-loqarifm',3,4,'Qüvvətin loqarifmi hansı qaydayla hesablanır?','log xⁿ = n · log x.',array['log xⁿ = n·log x','log xⁿ = (log x)ⁿ','log xⁿ = n + log x','log xⁿ = log n · x'],1),
('riy10-ustlu-loqarifm#18','riy-10-ustlu-loqarifm',2,4,'y = log_a x funksiyasının təyin oblastı hansıdır?','Loqarifm yalnız müsbət arqumentdə təyin olunub: x > 0.',array['x > 0','x ≥ 0','Bütün ədədlər','x > 1'],1),
('riy10-ustlu-loqarifm#19','riy-10-ustlu-loqarifm',3,4,'y = aˣ üstlü funksiyasının qiymətlər çoxluğu hansıdır?','Üstlü funksiya yalnız müsbət qiymətlər alır.',array['Müsbət ədədlər','Bütün həqiqi ədədlər','Mənfi olmayan ədədlər','Tam ədədlər'],1),
('riy10-ustlu-loqarifm#20','riy-10-ustlu-loqarifm',3,4,'2ˣ > 8 bərabərsizliyinin həllini tapın.','8 = 2³; əsas 1-dən böyükdür, işarə saxlanır: x > 3.',array['x > 3','x < 3','x > 8','x ≥ 2'],1),
('riy10-ustlu-loqarifm#21','riy-10-ustlu-loqarifm',3,4,'(1/2)ˣ > 1 bərabərsizliyinin həllini tapın.','1 = (1/2)⁰; əsas 1-dən kiçikdir, işarə dəyişir: x < 0.',array['x < 0','x > 0','x > 1','x < 1'],1),
('riy10-ustlu-loqarifm#22','riy-10-ustlu-loqarifm',3,4,'log₂ x = 5 tənliyinin kökünü tapın.','x = 2⁵ = 32.',array['x = 32','x = 10','x = 25','x = 64'],1),
('riy10-ustlu-loqarifm#23','riy-10-ustlu-loqarifm',3,4,'log₃ x = 2 tənliyinin kökünü tapın.','x = 3² = 9.',array['x = 9','x = 6','x = 8','x = 3'],1),
('riy10-ustlu-loqarifm#24','riy-10-ustlu-loqarifm',3,4,'lg x = 0 tənliyinin kökü neçədir?','x = 10⁰ = 1.',array['x = 1','x = 0','x = 10','Kökü yoxdur'],1),
('riy10-ustlu-loqarifm#25','riy-10-ustlu-loqarifm',2,4,'Üstlü və loqarifmik funksiyalar bir-birinə görə hansı funksiyalardır?','y = aˣ və y = log_a x qarşılıqlı tərs funksiyalardır.',array['Qarşılıqlı tərs funksiyalardır','Eyni funksiyalardır','Bir-birinin cəmidir','Əlaqəsizdirlər'],1),
('riy10-ustlu-loqarifm#26','riy-10-ustlu-loqarifm',2,4,'y = 2ˣ funksiyasının qrafiki hansı nöqtədən keçir?','2⁰ = 1: qrafik (0; 1) nöqtəsindən keçir.',array['(0; 1) nöqtəsindən','(1; 0) nöqtəsindən','(0; 0) nöqtəsindən','(2; 0) nöqtəsindən'],1),
('riy10-ustlu-loqarifm#27','riy-10-ustlu-loqarifm',3,4,'y = log₂ x funksiyasının qrafiki hansı nöqtədən keçir?','log₂ 1 = 0: qrafik (1; 0) nöqtəsindən keçir.',array['(1; 0) nöqtəsindən','(0; 1) nöqtəsindən','(0; 0) nöqtəsindən','(2; 2) nöqtəsindən'],1),
('riy10-ustlu-loqarifm#28','riy-10-ustlu-loqarifm',3,4,'Zəlzələlərin gücünü ölçən Rixter şkalası hansı şkaladır?','Rixter şkalası loqarifmik şkaladır.',array['Loqarifmik şkaladır','Xətti şkaladır','Kvadratik şkaladır','Dairəvi şkaladır'],1),
('riy10-ustlu-loqarifm#29','riy-10-ustlu-loqarifm',3,4,'Səsin gurluğunu ölçən desibel şkalası hansı funksiyaya əsaslanır?','Desibel şkalası loqarifmik funksiyaya əsaslanır.',array['Loqarifmik funksiyaya','Xətti funksiyaya','Triqonometrik funksiyaya','Kvadrat funksiyaya'],1),
('riy10-ustlu-loqarifm#30','riy-10-ustlu-loqarifm',3,4,'4ˣ = 2 tənliyinin kökünü tapın.','4ˣ = 2²ˣ = 2¹, buradan 2x = 1, x = 1/2.',array['x = 1/2','x = 2','x = 1/4','x = 8'],1),
('riy10-ustlu-loqarifm#31','riy-10-ustlu-loqarifm',2,4,'Bakteriyaların sayının hər saat iki dəfə artması hansı funksiya ilə modelləşdirilir?','İkiqat artım y = 2ˣ üstlü funksiyası ilə təsvir olunur.',array['Üstlü funksiya ilə','Xətti funksiya ilə','Loqarifmik azalma ilə','Sabit funksiya ilə'],1),
('riy10-ustlu-loqarifm#32','riy-10-ustlu-loqarifm',1,4,'Üstlü tənlik hansı tənlikdir?','Naməlumu qüvvət üstündə olan tənlik üstlü tənlikdir.',array['Naməlumu qüvvət üstündə olan tənlik','Naməlumu kök altında olan tənlik','Xətti tənlik','Kvadrat tənlik'],1),
('riy10-ustlu-loqarifm#33','riy-10-ustlu-loqarifm',3,4,'2ˣ⁺¹ = 8 tənliyinin kökünü tapın.','8 = 2³: x + 1 = 3, x = 2.',array['x = 2','x = 3','x = 4','x = 7'],1),
('riy10-ustlu-loqarifm#34','riy-10-ustlu-loqarifm',3,4,'Loqarifmik tənliyin tapılan kökünü yoxlamaq nə üçün vacibdir?','Arqument müsbət olmalıdır - kənar kök yarana bilər.',array['Kənar kök yarana bildiyi üçün','Yoxlama vacib deyil','Kök həmişə mənfidir','Tənliyin həlli olmur'],1),
('riy10-ustlu-loqarifm#35','riy-10-ustlu-loqarifm',2,4,'lg 10 qiyməti neçədir?','10¹ = 10 olduğundan lg 10 = 1.',array['Birə bərabərdir','Sıfra bərabərdir','Ona bərabərdir','Yüzə bərabərdir'],1),
('riy10-ustlu-loqarifm#36','riy-10-ustlu-loqarifm',3,4,'y = log₂(x − 1) funksiyasının təyin oblastı hansıdır?','x − 1 > 0 olmalıdır: x > 1.',array['x > 1','x > 0','x ≥ 1','Bütün ədədlər'],1),
('riy10-ustlu-loqarifm#37','riy-10-ustlu-loqarifm',3,4,'10ˣ = 0,1 tənliyinin kökünü tapın.','0,1 = 10⁻¹ olduğundan x = −1.',array['x = −1','x = 1','x = 0,1','x = −10'],1),
('riy10-ustlu-loqarifm#38','riy-10-ustlu-loqarifm',1,4,'a ≠ 0 olduqda a⁰ neçəyə bərabərdir?','Sıfırdan fərqli ədədin sıfırıncı qüvvəti vahiddir.',array['Vahid','Sıfır','a-nın özü','Təyin olunmayıb'],1),
('riy10-ustlu-loqarifm#39','riy-10-ustlu-loqarifm',3,4,'(1/3)ˣ < 1/9 bərabərsizliyinin həllini tapın.','1/9 = (1/3)²; əsas 1-dən kiçikdir, işarə dəyişir: x > 2.',array['x > 2','x < 2','x > 9','x < 0'],1),
('riy10-ustlu-loqarifm#40','riy-10-ustlu-loqarifm',3,4,'y = aˣ funksiyasının qrafiki hansı oxu kəsmir?','Üstlü funksiya sıfır qiymət almır - qrafik absis oxunu kəsmir.',array['Absis oxunu','Ordinat oxunu','Hər iki oxu','Qrafik ox kəsmir anlayışı yoxdur'],1),
('riy10-statistika#1','riy-10-statistika',2,4,'Baş külli (baş toplum) nədir?','Baş külli öyrənilən obyektlərin hamısının çoxluğudur.',array['Öyrənilən obyektlərin hamısı','Yalnız seçilmiş hissə','Ən böyük ədəd','Cədvəlin başlığı'],1),
('riy10-statistika#2','riy-10-statistika',2,4,'Seçmə nədir?','Seçmə baş küllidən tədqiqat üçün götürülən hissədir.',array['Baş küllidən götürülən hissə','Bütün obyektlər','Ən yaxşı nəticələr','Təsadüfi ədədlər cədvəli'],1),
('riy10-statistika#3','riy-10-statistika',2,4,'Təsadüfi seçmədə hər obyektin seçilmə şansı necə olmalıdır?','Təsadüfi seçmədə hər obyektin düşmə ehtimalı bərabər olmalıdır.',array['Bərabər olmalıdır','Fərqli olmalıdır','Yalnız birincilərdə böyük olmalıdır','Sıfır olmalıdır'],1),
('riy10-statistika#4','riy-10-statistika',2,4,'Reprezentativ seçmə hansı seçmədir?','Baş küllinin tərkibini düzgün əks etdirən seçmə reprezentativdir.',array['Baş küllini düzgün təmsil edən','Ən böyük seçmə','Yalnız könüllülərdən ibarət','Ən qısa müddətli'],1),
('riy10-statistika#5','riy-10-statistika',2,4,'(a + b)² açılışının əmsalları hansılardır?','(a + b)² = a² + 2ab + b²: əmsallar 1, 2, 1.',array['1, 2, 1','1, 1, 1','2, 2, 2','1, 3, 1'],1),
('riy10-statistika#6','riy-10-statistika',3,4,'Kub binomunun - (a + b)³ ifadəsinin açılışında əmsallar hansı sıra ilə düzülür?','(a + b)³ = a³ + 3a²b + 3ab² + b³: əmsallar 1, 3, 3, 1.',array['1, 3, 3, 1','1, 2, 2, 1','3, 3, 3, 3','1, 4, 4, 1'],1),
('riy10-statistika#7','riy-10-statistika',2,4,'Paskal üçbucağında hər ədəd necə alınır?','Hər ədəd üstündəki iki qonşu ədədin cəmidir.',array['Üstdəki iki qonşu ədədin cəmindən','Üstdəki ədədlərin hasilindən','Sətir nömrəsindən','Təsadüfi seçmədən'],1),
('riy10-statistika#8','riy-10-statistika',3,4,'C(4, 2) - 4 elementdən 2-sinin seçilmə yollarının sayını tapın.','C(4,2) = 4!/(2!·2!) = 6.',array['6','8','12','4'],1),
('riy10-statistika#9','riy-10-statistika',3,4,'C(5, 2) birləşmələrinin sayını hesablayın.','C(5,2) = 5!/(2!·3!) = 10.',array['10','20','5','15'],1),
('riy10-statistika#10','riy-10-statistika',3,4,'İstənilən n üçün C(n, 0) neçəyə bərabərdir?','Heç nə seçməməyin bir yolu var: C(n,0) = 1.',array['Həmişə 1-dir','Həmişə 0-dır','n-ə bərabərdir','n²-yə bərabərdir'],1),
('riy10-statistika#11','riy-10-statistika',2,4,'Bernulli sınağı hansı sınaqdır?','Yalnız iki nəticəsi (uğur/uğursuzluq) olan təkrarlanan sınaqdır.',array['İki nəticəli təkrarlanan sınaq','Üç nəticəli sınaq','Nəticəsiz sınaq','Yalnız bir dəfə aparılan ölçmə'],1),
('riy10-statistika#12','riy-10-statistika',3,4,'Simmetrik sikkə 3 dəfə atılır. Düz 2 dəfə gerb düşməsi ehtimalını tapın.','P = C(3,2)·(1/2)³ = 3/8.',array['3/8','1/8','1/2','2/3'],1),
('riy10-statistika#13','riy-10-statistika',2,4,'Bernulli sxemində uğur ehtimalı p, uğursuzluq ehtimalı q olarsa, p + q cəmi nəyə bərabərdir?','Uğur və uğursuzluq bütün halları əhatə edir: p + q = 1.',array['Vahidə (1-ə)','Sıfra','İkiyə','p·q hasilinə'],1),
('riy10-statistika#14','riy-10-statistika',3,4,'Bernulli sxemində n = 2, k = 2, p = 1/2 olduqda ehtimalı hesablayın.','P = C(2,2)·(1/2)² = 1/4.',array['1/4','1/2','3/4','1/8'],1),
('riy10-statistika#15','riy-10-statistika',1,4,'Statistik məlumatlar hansı üsullarla təqdim olunur?','Məlumatlar cədvəl və diaqramlarla təqdim olunur.',array['Cədvəl və diaqramlarla','Yalnız şeirlə','Yalnız şəkillərlə','Təqdim olunmur'],1),
('riy10-statistika#16','riy-10-statistika',3,4,'Fasiləsiz verilənlərin tezliklərini göstərən bitişik sütunlu qrafik necə adlanır?','Belə qrafik histoqram adlanır.',array['Histoqram','Sinusoid','Piktoqram','Xəritə'],1),
('riy10-statistika#17','riy-10-statistika',2,4,'Seçmənin həcmi nədir?','Seçmənin həcmi ona daxil olan obyektlərin sayıdır.',array['Seçmədəki obyektlərin sayı','Ən böyük qiymət','Qiymətlərin cəmi','Cədvəlin eni'],1),
('riy10-statistika#18','riy-10-statistika',3,4,'C(6, 2) birləşmələrinin sayını hesablayın.','C(6,2) = 6!/(2!·4!) = 15.',array['15','12','30','6'],1),
('riy10-statistika#19','riy-10-statistika',3,4,'(a + b)ⁿ açılışında neçə hədd olur?','Açılışda n + 1 hədd olur.',array['n + 1','n','2n','n − 1'],1),
('riy10-statistika#20','riy-10-statistika',3,4,'Paskal üçbucağının n = 4 sətri hansıdır?','Dördüncü sətir: 1, 4, 6, 4, 1.',array['1, 4, 6, 4, 1','1, 3, 3, 1','1, 5, 10, 10, 5, 1','1, 2, 1'],1),
('riy10-statistika#21','riy-10-statistika',3,4,'Bernulli düsturu hansıdır?','P(k) = C(n,k) · pᵏ · qⁿ⁻ᵏ.',array['P = C(n,k)·pᵏ·qⁿ⁻ᵏ','P = n·p·k','P = pⁿ + qᵏ','P = C(n,k)/n'],1),
('riy10-statistika#22','riy-10-statistika',3,4,'Sorğuda məktəbin hər sinfindən bərabər sayda şagird götürülməsi hansı seçmə üsuludur?','Qruplar üzrə aparılan belə seçmə təbəqəli seçmədir.',array['Təbəqəli (qruplaşdırılmış) seçmə','Tam siyahıya alma','İxtiyari seçmə','Seçmə deyil'],1),
('riy10-statistika#23','riy-10-statistika',3,4,'Seçmə üzrə hesablanmış orta qiymət nəyi qiymətləndirmək üçün istifadə olunur?','Seçmə ortası baş küllinin orta qiymətini qiymətləndirir.',array['Baş küllinin orta qiymətini','Seçmənin rəngini','Cədvəlin ölçüsünü','Sınağın müddətini'],1),
('riy10-statistika#24','riy-10-statistika',3,4,'Uğur ehtimalı 1/3 olan sınaq iki dəfə təkrarlanır. Hər ikisinin uğurlu olması ehtimalını tapın.','P = (1/3)² = 1/9.',array['1/9','2/3','1/3','2/9'],1),
('riy10-statistika#25','riy-10-statistika',1,4,'«Statistika» sözü mənşəcə nə ilə bağlıdır?','Söz latınca status - vəziyyət, dövlət sözündən yaranıb.',array['Dövlətə aid məlumatlarla (status)','Musiqi ilə','İdmanla','Dənizçiliklə'],1),
('riy10-statistika#26','riy-10-statistika',3,4,'Rəy sorğusunun yalnız internet istifadəçiləri arasında aparılması hansı problemə yol açır?','Seçmə əhalini tam təmsil etmir - reprezentativlik pozulur.',array['Reprezentativlik pozulur','Nəticə dəqiqləşir','Heç bir problem olmur','Seçmə böyüyür'],1),
('riy10-statistika#27','riy-10-statistika',3,4,'(x + 1)⁴ açılışında x³-ün əmsalı neçədir?','Əmsal C(4,1) = 4-dür.',array['4-ə bərabərdir','6-ya bərabərdir','1-ə bərabərdir','3-ə bərabərdir'],1),
('riy10-statistika#28','riy-10-statistika',3,4,'(a + b)ⁿ açılışındakı bütün binom əmsallarının cəmi nəyə bərabərdir?','a = b = 1 qoyduqda cəm 2ⁿ alınır.',array['2ⁿ','n²','n + 1','n!'],1),
('riy10-statistika#29','riy-10-statistika',2,4,'C(7, 1) neçəyə bərabərdir?','7 elementdən birini 7 cür seçmək olar.',array['7 üsulla','1 üsulla','14 üsulla','21 üsulla'],1),
('riy10-statistika#30','riy-10-statistika',3,4,'Simmetrik sikkə 5 dəfə atılır. Hər beşində gerb düşməsi ehtimalını tapın.','P = (1/2)⁵ = 1/32.',array['1/32','1/5','1/16','5/32'],1),
('riy10-statistika#31','riy-10-statistika',3,4,'Bernulli sxemində ayrı-ayrı sınaqlar bir-birindən necə olmalıdır?','Sınaqlar asılı olmayan olmalıdır - biri digərinə təsir etməməlidir.',array['Asılı olmayan','Bir-birindən asılı','Eyni nəticəli','Ardıcıl artan'],1),
('riy10-statistika#32','riy-10-statistika',2,4,'Bütün baş küllini yoxlamaq əvəzinə seçmə nə üçün aparılır?','Seçmə vaxta və resurslara qənaət edir.',array['Vaxt və resurslara qənaət üçün','Nəticəni gizlətmək üçün','Malumatı çoxaltmaq üçün','Səbəbsiz'],1),
('riy10-statistika#33','riy-10-statistika',3,4,'Lampaların keyfiyyəti nə üçün başdan-başa deyil, seçmə ilə yoxlanılır?','Yoxlama zamanı lampa sıradan çıxır - hamısını yoxlamaq mümkün deyil.',array['Yoxlama məhsulu sıradan çıxardığı üçün','Lampalar az olduğu üçün','Qanun qadağan etdiyi üçün','Səbəbsiz adətdir'],1),
('riy10-statistika#34','riy-10-statistika',3,4,'C(8, 8) birləşməsinin qiyməti neçədir?','Bütün 8 elementi birdən seçməyin yalnız bir yolu var.',array['Bir','Səkkiz','Sıfır','Altmış dörd'],1),
('riy10-statistika#35','riy-10-statistika',3,4,'(a + b)⁵ açılışında neçə hədd var?','Hədlərin sayı 5 + 1 = 6-dır.',array['6 hədd','5 hədd','10 hədd','4 hədd'],1),
('riy10-statistika#36','riy-10-statistika',2,4,'Paskal üçbucağının hər sətrinin kənar ədədləri hansılardır?','Hər sətir 1 ilə başlayıb 1 ilə qurtarır.',array['1-lərdir','0-lardır','Sətir nömrəsidir','Təsadüfidir'],1),
('riy10-statistika#37','riy-10-statistika',3,4,'Sınaqların sayı artdıqca hadisənin nisbi tezliyi nəyə yaxınlaşır?','Böyük ədədlər qanununa görə tezlik hadisənin ehtimalına yaxınlaşır.',array['Hadisənin ehtimalına','Sıfra','Sonsuzluğa','Sınaq sayına'],1),
('riy10-statistika#38','riy-10-statistika',3,4,'Bernulli sxemində n sınaqda uğurların gözlənilən orta sayı nəyə bərabərdir?','Orta say n·p hasilinə bərabərdir.',array['n·p','n + p','n/p','p/n'],1),
('riy10-statistika#39','riy-10-statistika',2,4,'Sorğu vərəqələrindəki cavabların cədvəlləşdirilib ümumiləşdirilməsi hansı mərhələdir?','Bu, statistik məlumatın emalı mərhələsidir.',array['Məlumatın emalı','Məlumatın toplanması','Proqnoz vermə','Sorğunun elanı'],1),
('riy10-statistika#40','riy-10-statistika',1,4,'Bernulli sxemi adını daşıyan Yakob Bernulli hansı sahənin alimi olub?','Yakob Bernulli isveçrəli riyaziyyatçıdır.',array['Riyaziyyatçı','Kimyaçı','Coğrafiyaçı','Rəssam'],1)
),
ins as (
  insert into public.questions
    (ext_key, owner_type, subject_id, level_id, topic_id, kind,
     body, explanation, difficulty, quarter, status)
  select d.ext, 'platform', s.id, l.id, tp.id, 'single',
         d.body, d.why, d.diff, d.rub, 'published'
    from d
    join public.subjects s on s.slug = 'riyaziyyat'
    join public.programs p on p.slug = 'orta'
    join public.levels   l on l.program_id = p.id and l.code = '10'
    join public.topics   tp on tp.subject_id = s.id and tp.slug = d.topic
  on conflict (ext_key) do update
    set body = excluded.body, explanation = excluded.explanation,
        difficulty = excluded.difficulty, quarter = excluded.quarter,
        topic_id = excluded.topic_id, level_id = excluded.level_id,
        subject_id = excluded.subject_id, status = 'published'
  returning id, ext_key
)
insert into public.question_options (question_id, ord, body, is_correct)
select ins.id, o.ord, o.txt, o.ord = d.correct
  from ins
  join d on d.ext = ins.ext_key,
  lateral unnest(d.opts) with ordinality as o(txt, ord);

do $$
declare n int; k int;
begin
  select count(*) into n from public.questions
   where owner_type = 'platform' and ext_key like 'riy10-%';
  if n <> 400 then
    raise exception 'riy10 suallari: 400 gozlenilirdi, % tapildi', n;
  end if;
  select count(*) into k from public.questions q
   where q.ext_key like 'riy10-%'
     and ((select count(*) from public.question_options o
            where o.question_id = q.id) <> 4
       or (select count(*) from public.question_options o
            where o.question_id = q.id and o.is_correct) <> 1);
  if k > 0 then
    raise exception '% sualda variant qurulusu sehvdir', k;
  end if;
  select count(distinct topic_id) into k from public.questions
   where ext_key like 'riy10-%';
  if k <> 10 then
    raise exception 'movzu sayi 10 deyil: %', k;
  end if;
  raise notice 'Riyaziyyat 10 banki: % sual, 10 movzu.', n;
end $$;
