-- =====================================================================
--  50_bank_riy11.sql : RIYAZIYYAT 11 PLATFORMA SUAL BANKI (orta mekteb)
--
--  BU FAYL ELLE YAZILMIR - tools/riy11.py yaradir:
--      python3 tools/riy11.py
--
--  10 movzu x 40 sual = 400.  ext_key: riy11-<movzu>#<sira>.
--  ON SERT: 49_movzular_orta11.sql islenmis olmalidir.
--  SONRA:   05_grants.sql yeniden islet.
-- =====================================================================

do $$
begin
  if not exists (
    select 1 from public.topics t
      join public.subjects s on s.id = t.subject_id
     where s.slug = 'riyaziyyat' and t.slug = 'riy-11-toreme') then
    raise exception 'ONCE 49_movzular_orta11.sql isledilmelidir (riy-11-* movzulari yoxdur).';
  end if;
end $$;

delete from public.question_options o
 using public.questions q
 where o.question_id = q.id
   and q.owner_type = 'platform'
   and q.ext_key like 'riy11-%';

with d(ext, topic, diff, rub, body, why, opts, correct) as (values
('riy11-coxhedli#1','riy-11-coxhedli',2,1,'P(x) = x² + 3x + 1 çoxhədlisinin x = 2 nöqtəsindəki qiymətini tapın.','P(2) = 4 + 6 + 1 = 11.',array['11','9','7','14'],1),
('riy11-coxhedli#2','riy-11-coxhedli',2,1,'Qalıq teoreminə görə P(x) çoxhədlisinin (x − a)-ya bölünməsindən alınan qalıq nəyə bərabərdir?','Qalıq P(a) qiymətinə bərabərdir.',array['P(a)','P(0)','a','Sıfır həmişə'],1),
('riy11-coxhedli#3','riy-11-coxhedli',3,1,'P(x) = x² − 5x + 6 çoxhədlisinin (x − 3)-ə bölünməsindən qalığı tapın.','Qalıq P(3) = 9 − 15 + 6 = 0.',array['0','3','6','−6'],1),
('riy11-coxhedli#4','riy-11-coxhedli',2,1,'P(a) = 0 olduqda (x − a) çoxhədli üçün nədir?','Vuruqlar teoreminə görə (x − a) çoxhədlinin vuruğudur.',array['Vuruğudur','Qalığıdır','Əmsalıdır','Dərəcəsidir'],1),
('riy11-coxhedli#5','riy-11-coxhedli',2,1,'x² − 9 çoxhədlisi hansı vuruqlara ayrılır?','Kvadratlar fərqi: (x − 3)(x + 3).',array['(x − 3)(x + 3)','(x − 9)(x + 1)','(x − 3)²','(x + 3)²'],1),
('riy11-coxhedli#6','riy-11-coxhedli',2,1,'i² qiyməti nəyə bərabərdir?','Xəyali vahidin kvadratı: i² = −1.',array['−1','1','i','0'],1),
('riy11-coxhedli#7','riy-11-coxhedli',3,1,'i⁴ qiyməti neçədir?','i⁴ = (i²)² = (−1)² = 1.',array['1','−1','i','−i'],1),
('riy11-coxhedli#8','riy-11-coxhedli',3,1,'(2 + 3i) + (1 − i) cəmini tapın.','Həqiqi və xəyali hissələr ayrıca toplanır: 3 + 2i.',array['3 + 2i','3 + 4i','1 + 2i','2 + 3i'],1),
('riy11-coxhedli#9','riy-11-coxhedli',3,1,'3 + 4i kompleks ədədinin modulunu tapın.','|z| = √(9 + 16) = √25 = 5.',array['Modul 5-dir','Modul 7-dir','Modul 25-dir','Modul 1-dir'],1),
('riy11-coxhedli#10','riy-11-coxhedli',3,1,'x² + 1 = 0 tənliyinin kökləri hansı ədədlərdir?','Həqiqi kökü yoxdur; kompleks kökləri x = ±i-dir.',array['x = ±i','x = ±1','x = 0','Kökü yoxdur heç bir çoxluqda'],1),
('riy11-coxhedli#11','riy-11-coxhedli',2,1,'Kompleks ədəd hansı şəkildə yazılır?','Kompleks ədədin cəbri şəkli a + bi-dir.',array['a + bi','a·b','a/b yalnız','√a yalnız'],1),
('riy11-coxhedli#12','riy-11-coxhedli',3,1,'Cəbrin əsas teoreminə görə n dərəcəli çoxhədlinin kompleks çoxluqda neçə kökü var?','Təkrarlar nəzərə alınmaqla düz n kökü var.',array['n kökü','Həmişə bir kökü','Sonsuz kökü','Kökü olmur'],1),
('riy11-coxhedli#13','riy-11-coxhedli',1,1,'Çoxhədlinin dərəcəsi nəyə görə təyin olunur?','Dərəcə ən böyük qüvvətli həddin qüvvət üstüdür.',array['Ən böyük qüvvət üstünə görə','Hədlərin sayına görə','Sərbəst həddə görə','Əmsalların cəminə görə'],1),
('riy11-coxhedli#14','riy-11-coxhedli',1,1,'x³ + 2x² − 5 çoxhədlisinin dərəcəsi neçədir?','Ən böyük qüvvət 3-dür.',array['3','2','5','6'],1),
('riy11-coxhedli#15','riy-11-coxhedli',2,1,'Çoxhədlinin çoxhədliyə bölünməsi hansı əməliyyata bənzəyir?','Bölmə ədədlərin qalıqlı bölünməsinə bənzər aparılır.',array['Ədədlərin qalıqlı bölünməsinə','Vurma cədvəlinə','Kök almaya','Loqarifmlamaya'],1),
('riy11-coxhedli#16','riy-11-coxhedli',3,1,'P(x) = x² + bx + 6 çoxhədlisinin bir kökü x = 2-dirsə, b-ni tapın.','P(2) = 4 + 2b + 6 = 0, buradan b = −5.',array['b = −5','b = 5','b = −3','b = 2'],1),
('riy11-coxhedli#17','riy-11-coxhedli',3,1,'Tam əmsallı çoxhədlinin rasional kökləri harada axtarılır?','Sərbəst həddin bölənləri arasında axtarılır.',array['Sərbəst həddin bölənləri arasında','İstənilən ədədlər arasında','Yalnız mənfi ədədlərdə','Yalnız kəsrlərdə'],1),
('riy11-coxhedli#18','riy-11-coxhedli',2,1,'x² − 4x + 4 çoxhədlisi hansı şəkildə yazılır?','Tam kvadrat: (x − 2)².',array['(x − 2)²','(x + 2)²','(x − 4)²','(x − 2)(x + 2)'],1),
('riy11-coxhedli#19','riy-11-coxhedli',2,1,'Rasional funksiya nədir?','İki çoxhədlinin nisbəti şəklində funksiyadır.',array['Çoxhədlilərin nisbəti','Yalnız xətti funksiya','Kök funksiyası','Triqonometrik funksiya'],1),
('riy11-coxhedli#20','riy-11-coxhedli',2,1,'y = 1/(x − 3) rasional funksiyası hansı nöqtədə təyin olunmayıb?','Məxrəc sıfır olan x = 3 nöqtəsində təyin olunmayıb.',array['x = 3 nöqtəsində','x = 0 nöqtəsində','x = −3 nöqtəsində','x = 1 nöqtəsində'],1),
('riy11-coxhedli#21','riy-11-coxhedli',3,1,'(1 + i)(1 − i) hasilini hesablayın.','Kvadratlar fərqi: 1 − i² = 1 + 1 = 2.',array['2 alınır','0 alınır','2i alınır','1 alınır'],1),
('riy11-coxhedli#22','riy-11-coxhedli',1,1,'Kompleks ədədin xəyali hissəsi hansı hərflə işarələnən vahidlə yazılır?','Xəyali vahid i hərfi ilə işarələnir.',array['i','e','π','x'],1),
('riy11-coxhedli#23','riy-11-coxhedli',3,1,'5 − 2i ədədinin qoşması hansıdır?','Qoşma ədəddə xəyali hissənin işarəsi dəyişir: 5 + 2i.',array['5 + 2i','−5 + 2i','−5 − 2i','2 − 5i'],1),
('riy11-coxhedli#24','riy-11-coxhedli',2,1,'P(x) = 2x + 6 çoxhədlisinin kökü hansıdır?','2x + 6 = 0, buradan x = −3.',array['x = −3','x = 3','x = 6','x = −6'],1),
('riy11-coxhedli#25','riy-11-coxhedli',2,1,'Çoxhədli funksiyanın qrafiki hansı xüsusiyyətə malikdir?','Qrafik kəsilməz əyri xəttdir.',array['Kəsilməz əyridir','Həmişə düz xətdir','Qırıq-qırıqdır','Yalnız nöqtələrdir'],1),
('riy11-coxhedli#26','riy-11-coxhedli',3,1,'x³ − x çoxhədlisinin neçə həqiqi kökü var?','x(x − 1)(x + 1) = 0: üç kök - 0, 1, −1.',array['3 kökü var','1 kökü var','2 kökü var','Kökü yoxdur'],1),
('riy11-coxhedli#27','riy-11-coxhedli',3,1,'İki çoxhədlinin cəminin dərəcəsi ən çoxu nəyə bərabərdir?','Cəmin dərəcəsi böyük dərəcədən böyük ola bilməz.',array['Böyük dərəcəyə','Dərəcələrin hasilinə','Dərəcələrin cəminə həmişə','Sıfra'],1),
('riy11-coxhedli#28','riy-11-coxhedli',2,1,'Kompleks ədədlər hansı tənliklərin həlli üçün daxil edilib?','Həqiqi kökü olmayan (məsələn, x² = −1) tənliklər üçün.',array['Həqiqi kökü olmayan tənliklər üçün','Xətti tənliklər üçün','Yalnız bərabərsizliklər üçün','Heç nə üçün'],1),
('riy11-coxhedli#29','riy-11-coxhedli',2,1,'(x − 1)(x − 2)(x − 3) çoxhədlisinin dərəcəsi neçədir?','Üç xətti vuruğun hasili üçüncü dərəcəlidir.',array['3-dür','1-dir','6-dır','2-dir'],1),
('riy11-coxhedli#30','riy-11-coxhedli',3,1,'P(x) çoxhədlisi (x − 1)-ə qalıqsız bölünürsə, P(1) neçədir?','Qalıq teoreminə görə P(1) = 0.',array['P(1) = 0','P(1) = 1','P(1) = −1','Təyin olunmur'],1),
('riy11-coxhedli#31','riy-11-coxhedli',3,1,'2 + 0i kompleks ədədi hansı çoxluğa da aiddir?','Xəyali hissə sıfırdırsa, ədəd həqiqidir.',array['Həqiqi ədədlərə','Yalnız xəyali ədədlərə','Heç bir çoxluğa','Yalnız natural ədədlərə'],1),
('riy11-coxhedli#32','riy-11-coxhedli',3,1,'Horner sxemi nə üçün istifadə olunur?','Çoxhədlinin qiymətini və bölünməsini sürətli hesablamaq üçün.',array['Çoxhədlini sürətli hesablamaq üçün','Qrafik çəkmək üçün','İnteqral almaq üçün','Bucaq ölçmək üçün'],1),
('riy11-coxhedli#33','riy-11-coxhedli',3,1,'Çoxhədlinin sərbəst həddi qrafikdə nəyi göstərir?','Sərbəst hədd qrafikin OY oxunu kəsdiyi nöqtəni verir.',array['OY oxu ilə kəsişməni','OX oxu ilə kəsişməni','Qrafikin rəngini','Dövrü'],1),
('riy11-coxhedli#34','riy-11-coxhedli',3,1,'(3i)² qiymətini hesablayın.','(3i)² = 9i² = −9.',array['−9','9','−3','9i'],1),
('riy11-coxhedli#35','riy-11-coxhedli',3,1,'İkidərəcəli tənliyin diskriminantı mənfi olduqda kökləri hansı çoxluqdadır?','D < 0 olduqda köklər kompleks ədədlərdir.',array['Kompleks ədədlər çoxluğunda','Natural ədədlərdə','Müsbət həqiqi ədədlərdə','Tam ədədlərdə'],1),
('riy11-coxhedli#36','riy-11-coxhedli',2,1,'P(x) = x² + 1 çoxhədlisinin həqiqi kökləri varmı?','x² + 1 > 0 həmişə - həqiqi kök yoxdur.',array['Yoxdur - ifadə həmişə müsbətdir','Bəli, iki kökü var','Bəli, bir kökü var','Sonsuz kökü var'],1),
('riy11-coxhedli#37','riy-11-coxhedli',3,1,'Rasional funksiyanın qrafikində şaquli asimptot harada yaranır?','Məxrəcin sıfırlarında (kəsilmə nöqtələrində) yaranır.',array['Məxrəcin sıfırlarında','Surətin sıfırlarında','Koordinat başlanğıcında həmişə','Heç harada'],1),
('riy11-coxhedli#38','riy-11-coxhedli',3,1,'Çoxhədlilər hansı əməllərə görə qapalıdır?','Cəm, fərq və hasil yenə çoxhədli verir.',array['Toplama, çıxma, vurmaya görə','Yalnız bölməyə görə','Kök almaya görə','Heç bir əmələ görə'],1),
('riy11-coxhedli#39','riy-11-coxhedli',3,1,'x² = −4 tənliyinin kompleks kökləri hansılardır?','x = ±2i.',array['x = ±2i','x = ±2','x = ±4i','x = 4'],1),
('riy11-coxhedli#40','riy-11-coxhedli',2,1,'Çoxhədlinin qrafiki OX oxunu kəsdiyi nöqtələr nəyi göstərir?','Bu nöqtələr çoxhədlinin həqiqi kökləridir.',array['Həqiqi kökləri','Əmsalları','Dərəcəni','Sərbəst həddi'],1),
('riy11-feza-vektor#1','riy-11-feza-vektor',1,1,'Fəzada vektor neçə koordinatla verilir?','Fəza vektoru üç koordinatla (x; y; z) verilir.',array['Üç koordinatla','İki koordinatla','Bir koordinatla','Dörd koordinatla'],1),
('riy11-feza-vektor#2','riy-11-feza-vektor',3,1,'a(2; 3; 6) vektorunun uzunluğunu tapın.','|a| = √(4 + 9 + 36) = √49 = 7.',array['7','11','5','49'],1),
('riy11-feza-vektor#3','riy-11-feza-vektor',2,1,'a(1; 2; 3) və b(4; 5; 6) vektorlarının cəmini tapın.','Uyğun koordinatlar toplanır: (5; 7; 9).',array['(5; 7; 9)','(4; 10; 18)','(3; 3; 3)','(5; 7; 8)'],1),
('riy11-feza-vektor#4','riy-11-feza-vektor',2,1,'İki vektorun skalyar hasili koordinatlarla necə hesablanır?','a·b = x₁x₂ + y₁y₂ + z₁z₂.',array['Uyğun koordinatların hasillərinin cəmi ilə','Uzunluqların cəmi ilə','Koordinatların fərqi ilə','Yalnız bucaqla'],1),
('riy11-feza-vektor#5','riy-11-feza-vektor',3,1,'a(1; 2; 2) və b(2; 1; −2) vektorlarının skalyar hasilini tapın.','a·b = 2 + 2 − 4 = 0.',array['0 (perpendikulyardır)','4','8','−4'],1),
('riy11-feza-vektor#6','riy-11-feza-vektor',2,1,'Skalyar hasil sıfır olduqda vektorlar bir-birinə görə necədir?','Sıfır hasil perpendikulyarlığı göstərir.',array['Perpendikulyardır','Paraleldir','Bərabərdir','Əksdir'],1),
('riy11-feza-vektor#7','riy-11-feza-vektor',2,1,'Kollinear vektorlar hansı vektorlardır?','Bir düz xətt üzərində və ya paralel xətlərdə yerləşən vektorlardır.',array['Paralel istiqamətli vektorlar','Perpendikulyar vektorlar','Yalnız vahid vektorlar','Sıfır vektorlar yalnız'],1),
('riy11-feza-vektor#8','riy-11-feza-vektor',3,1,'a(2; 4; 6) və b(1; 2; 3) vektorları arasında hansı münasibət var?','a = 2b - vektorlar kollineardır.',array['Kollineardır','Perpendikulyardır','Bərabərdir','Əlaqəsizdir'],1),
('riy11-feza-vektor#9','riy-11-feza-vektor',2,1,'Müstəvinin ümumi tənliyi hansı şəkildədir?','ax + by + cz + d = 0.',array['ax + by + cz + d = 0','y = kx + b yalnız','x² + y² = r²','xyz = 1'],1),
('riy11-feza-vektor#10','riy-11-feza-vektor',3,1,'Sferanın mərkəzi koordinat başlanğıcında olduqda tənliyi necə yazılır?','x² + y² + z² = R².',array['x² + y² + z² = R²','x + y + z = R','x² + y² = R²','xyz = R³'],1),
('riy11-feza-vektor#11','riy-11-feza-vektor',2,1,'x² + y² + z² = 25 sferasının radiusu neçədir?','R² = 25, R = 5.',array['R = 5','R = 25','R = 10','R = 12,5'],1),
('riy11-feza-vektor#12','riy-11-feza-vektor',3,1,'Vektorun başlanğıcı A(1; 1; 1), sonu B(3; 4; 5)-dir. AB vektorunun koordinatlarını tapın.','Son çıx başlanğıc: (2; 3; 4).',array['(2; 3; 4)','(4; 5; 6)','(3; 4; 5)','(1; 1; 1)'],1),
('riy11-feza-vektor#13','riy-11-feza-vektor',1,1,'Sıfır vektorun uzunluğu neçədir?','Sıfır vektorun uzunluğu 0-dır.',array['Sıfra bərabərdir','1-dir','Təyin olunmur','Sonsuzdur'],1),
('riy11-feza-vektor#14','riy-11-feza-vektor',1,1,'Vahid vektorun uzunluğu neçəyə bərabərdir?','Vahid vektorun uzunluğu 1-dir.',array['1 vahid','0','2 vahid','İstənilən'],1),
('riy11-feza-vektor#15','riy-11-feza-vektor',2,1,'k·a(1; 2; 3) vektoru k = 3 olduqda hansı koordinatları alır?','Hər koordinat 3-ə vurulur: (3; 6; 9).',array['(3; 6; 9)','(4; 5; 6)','(1; 2; 3)','(3; 2; 1)'],1),
('riy11-feza-vektor#16','riy-11-feza-vektor',2,1,'İki nöqtə arasındakı məsafə fəzada hansı düsturla tapılır?','d = √((x₂−x₁)² + (y₂−y₁)² + (z₂−z₁)²).',array['Koordinat fərqlərinin kvadratları cəminin kökü ilə','Koordinatların cəmi ilə','Koordinatların hasili ilə','Yalnız qrafiklə'],1),
('riy11-feza-vektor#17','riy-11-feza-vektor',3,1,'A(0; 0; 0) və B(3; 4; 12) nöqtələri arasındakı məsafəni tapın.','d = √(9 + 16 + 144) = √169 = 13.',array['13','19','12','7'],1),
('riy11-feza-vektor#18','riy-11-feza-vektor',3,1,'Skalyar hasil vasitəsilə vektorlar arasındakı hansı kəmiyyət tapılır?','İki vektor arasındakı bucağın kosinusu tapılır.',array['Bucağın kosinusu','Sahə','Həcm','Perimetr'],1),
('riy11-feza-vektor#19','riy-11-feza-vektor',2,1,'z = 0 müstəvisi hansı koordinat müstəvisidir?','z = 0 Oxy müstəvisinin tənliyidir.',array['Oxy müstəvisi','Oxz müstəvisi','Oyz müstəvisi','Heç biri'],1),
('riy11-feza-vektor#20','riy-11-feza-vektor',3,1,'İki müstəvi paralel olduqda tənliklərindəki əmsallar necə olur?','a, b, c əmsalları mütənasib olur.',array['Mütənasib olur','Bərabər olmur heç vaxt','Cəmi sıfır olur','Hasili mənfi olur'],1),
('riy11-feza-vektor#21','riy-11-feza-vektor',2,1,'Qarşılıqlı əks vektorların cəmi nəyə bərabərdir?','a + (−a) = sıfır vektor.',array['Sıfır vektora','Vahid vektora','2a-ya','Təyin olunmur'],1),
('riy11-feza-vektor#22','riy-11-feza-vektor',2,1,'Paralel köçürmə zamanı fiqurun hansı xassələri saxlanır?','Ölçülər və forma dəyişmir.',array['Ölçü və forma','Yalnız rəng','Heç nə','Yalnız bir tərəf'],1),
('riy11-feza-vektor#23','riy-11-feza-vektor',3,1,'Fəzada simmetriya mərkəzinə görə çevrilmədə nöqtənin koordinatları necə dəyişir?','Başlanğıca görə simmetriyada işarələr əksinə dəyişir.',array['İşarələri əksinə dəyişir','İki dəfə artır','Dəyişmir','Sıfırlanır'],1),
('riy11-feza-vektor#24','riy-11-feza-vektor',3,1,'M(2; −3; 5) nöqtəsinin başlanğıca görə simmetrik nöqtəsi hansıdır?','İşarələr dəyişir: (−2; 3; −5).',array['(−2; 3; −5)','(2; 3; 5)','(−2; −3; −5)','(5; −3; 2)'],1),
('riy11-feza-vektor#25','riy-11-feza-vektor',3,1,'Skalyar hasil a·a nəyə bərabərdir?','a·a = |a|² - uzunluğun kvadratı.',array['|a|²','0','1','2|a|'],1),
('riy11-feza-vektor#26','riy-11-feza-vektor',2,1,'Fəzada Dekart koordinat sistemini kim təklif etmişdir?','Sistem Rene Dekartın adı ilə bağlıdır.',array['Rene Dekart','Nyuton','Evklid','Pifaqor'],1),
('riy11-feza-vektor#27','riy-11-feza-vektor',3,1,'a(x; 4; 0) vektoru b(1; 2; 0) vektoruna kollineardırsa, x neçədir?','Mütənasiblik: x/1 = 4/2 = 2, x = 2.',array['x = 2 olmalıdır','x = 4 olmalıdır','x = 8 olmalıdır','x = 1 olmalıdır'],1),
('riy11-feza-vektor#28','riy-11-feza-vektor',3,1,'Düz xətlə müstəvinin paralellik şərti vektorlarla necə ifadə olunur?','İstiqamət vektoru normal vektora perpendikulyar olmalıdır.',array['İstiqamət vektoru normala perpendikulyar','Vektorlar bərabər','Vektorlar kollinear','Şərt yoxdur'],1),
('riy11-feza-vektor#29','riy-11-feza-vektor',3,1,'Müstəvinin normal vektoru tənlikdən necə tapılır?','ax + by + cz + d = 0 tənliyində n(a; b; c).',array['Əmsallardan: n(a; b; c)','Sərbəst hədddən','Kökaltından','Tapılmır'],1),
('riy11-feza-vektor#30','riy-11-feza-vektor',2,1,'Vektorlar fizikada hansı kəmiyyətləri təsvir edir?','Qüvvə, sürət kimi istiqamətli kəmiyyətləri.',array['Qüvvə və sürəti','Temperaturu','Kütləni','Zamanı'],1),
('riy11-feza-vektor#31','riy-11-feza-vektor',3,1,'(1; 0; 0), (0; 1; 0), (0; 0; 1) vektorları necə adlanır?','Bunlar koordinat oxlarının vahid ort vektorlarıdır.',array['Ort vektorlar','Sıfır vektorlar','Əks vektorlar','Kollinear cüt'],1),
('riy11-feza-vektor#32','riy-11-feza-vektor',3,1,'Sferanın mərkəzi C(1; 2; 3), radiusu 2 olduqda tənliyi hansıdır?','(x−1)² + (y−2)² + (z−3)² = 4.',array['(x−1)² + (y−2)² + (z−3)² = 4','(x+1)² + (y+2)² + (z+3)² = 4','x² + y² + z² = 4','(x−1) + (y−2) + (z−3) = 2'],1),
('riy11-feza-vektor#33','riy-11-feza-vektor',2,1,'İki vektorun fərqi necə tapılır?','Uyğun koordinatlar çıxılır.',array['Uyğun koordinatların fərqi ilə','Uzunluqların nisbəti ilə','Bucaqların cəmi ilə','Tapılmır'],1),
('riy11-feza-vektor#34','riy-11-feza-vektor',2,1,'a(5; 0; 0) vektoru hansı ox boyunca yönəlib?','Yalnız x koordinatı sıfırdan fərqlidir - Ox oxu boyunca.',array['Ox oxu boyunca','Oy oxu boyunca','Oz oxu boyunca','Heç bir ox boyunca'],1),
('riy11-feza-vektor#35','riy-11-feza-vektor',3,1,'Fəzada fırlanma çevrilməsi nəyin ətrafında aparılır?','Fırlanma ox ətrafında aparılır.',array['Ox ətrafında','Müstəvi ətrafında','Sfera ətrafında','Vektor boyunca yalnız'],1),
('riy11-feza-vektor#36','riy-11-feza-vektor',1,1,'Perpendikulyar vektorlar arasındakı bucaq neçə dərəcədir?','Perpendikulyarlıq 90 dərəcə deməkdir.',array['90','0','180','45'],1),
('riy11-feza-vektor#37','riy-11-feza-vektor',2,1,'Eyni istiqamətli vahid vektorlar arasındakı bucaq neçədir?','Eyni istiqamətdə bucaq 0 dərəcədir.',array['0 dərəcə','90 dərəcə','180 dərəcə','60 dərəcə'],1),
('riy11-feza-vektor#38','riy-11-feza-vektor',2,1,'Vektorların toplanmasının üçbucaq qaydası nədir?','Birinin sonundan ikinci qoyulur, cəm başlanğıcdan sona yönəlir.',array['Ardıcıl qoyub başlanğıcı sonla birləşdirmək','Uzunluqları toplamaq yalnız','Bucaqları toplamaq','Koordinatları vurmaq'],1),
('riy11-feza-vektor#39','riy-11-feza-vektor',2,1,'Fəza koordinat sistemində neçə koordinat müstəvisi var?','Oxy, Oxz, Oyz - üç müstəvi.',array['3 müstəvi','2 müstəvi','1 müstəvi','6 müstəvi'],1),
('riy11-feza-vektor#40','riy-11-feza-vektor',2,1,'Vektorun koordinatları onun hansı xassələrini tam təyin edir?','Uzunluğunu və istiqamətini təyin edir.',array['Uzunluq və istiqamətini','Yalnız rəngini','Yalnız adını','Heç nəyi'],1),
('riy11-limit#1','riy-11-limit',2,1,'lim(x→2) x² limitini hesablayın.','Kəsilməz funksiyada limit qiymətə bərabərdir: 2² = 4.',array['4','2','8','0'],1),
('riy11-limit#2','riy-11-limit',2,1,'lim(x→1) (3x + 2) limitini tapın.','3·1 + 2 = 5.',array['5 alınır','3 alınır','2 alınır','6 alınır'],1),
('riy11-limit#3','riy-11-limit',2,1,'Funksiyanın nöqtədə limiti nəyi göstərir?','Arqument nöqtəyə yaxınlaşdıqca funksiyanın yaxınlaşdığı qiyməti.',array['Funksiyanın yaxınlaşdığı qiyməti','Funksiyanın ən böyük qiymətini','Qrafikin rəngini','Törəməni'],1),
('riy11-limit#4','riy-11-limit',2,1,'Cəmin limiti xassəsinə görə lim(f + g) nəyə bərabərdir?','Limitlərin cəminə bərabərdir.',array['lim f + lim g','lim f · lim g','lim f − lim g','Sıfra'],1),
('riy11-limit#5','riy-11-limit',3,1,'lim(x→0) (sin x)/x xüsusi limiti nəyə bərabərdir?','Bu məşhur limit 1-ə bərabərdir.',array['Vahidə bərabərdir','Sıfra bərabərdir','Sonsuzluğa bərabərdir','π-yə bərabərdir'],1),
('riy11-limit#6','riy-11-limit',2,1,'x sonsuzluğa yaxınlaşdıqca 1/x limiti neçədir?','Payda böyüdükcə kəsr sıfra yaxınlaşır.',array['Sıfra yaxınlaşır','1-ə yaxınlaşır','Sonsuzluğa gedir','−1 olur'],1),
('riy11-limit#7','riy-11-limit',2,1,'Funksiya nöqtədə kəsilməz olduqda limit nəyə bərabərdir?','Limit funksiyanın həmin nöqtədəki qiymətinə bərabərdir.',array['Funksiyanın qiymətinə','Sıfra','Sonsuzluğa','Təyin olunmur'],1),
('riy11-limit#8','riy-11-limit',3,1,'y = 1/(x − 2) funksiyasının şaquli asimptotu hansıdır?','Məxrəcin sıfrında: x = 2 düz xətti.',array['x = 2 düz xətti','y = 2 düz xətti','x = 0 oxu','y = 0 oxu'],1),
('riy11-limit#9','riy-11-limit',3,1,'y = 1/x funksiyasının üfüqi asimptotu hansıdır?','x→∞ olduqda y→0: asimptot y = 0.',array['y = 0','x = 0','y = 1','x = 1'],1),
('riy11-limit#10','riy-11-limit',2,1,'aₙ = 1/n ardıcıllığının limiti neçədir?','n artdıqca 1/n sıfra yaxınlaşır.',array['0','1','n','Sonsuzluq'],1),
('riy11-limit#11','riy-11-limit',2,1,'Limiti olan ardıcıllıq necə adlanır?','Limiti olan ardıcıllıq yığılan adlanır.',array['Yığılan','Dağılan','Sabit','Sonsuz'],1),
('riy11-limit#12','riy-11-limit',3,1,'lim(x→3) (x² − 9)/(x − 3) limitini hesablayın.','Vuruqlara ayırıb ixtisar: lim (x + 3) = 6.',array['6-ya bərabərdir','0-a bərabərdir','9-a bərabərdir','Təyin olunmur'],1),
('riy11-limit#13','riy-11-limit',2,1,'Hasilin limiti xassəsi necə ifadə olunur?','Hasilin limiti limitlərin hasilinə bərabərdir.',array['Limitlərin hasilinə bərabərdir','Limitlərin cəminə bərabərdir','Həmişə sıfırdır','Xassə yoxdur'],1),
('riy11-limit#14','riy-11-limit',1,1,'Sabit ədədin limiti nəyə bərabərdir?','Sabitin limiti elə özüdür.',array['Sabitin özünə','Sıfra','Birə','Sonsuzluğa'],1),
('riy11-limit#15','riy-11-limit',2,1,'Funksiyanın kəsilmə nöqtəsi nədir?','Kəsilməzlik şərtinin pozulduğu nöqtədir.',array['Kəsilməzliyin pozulduğu nöqtə','Ən böyük qiymət nöqtəsi','Qrafikin ortası','Həmişə sıfır nöqtəsi'],1),
('riy11-limit#16','riy-11-limit',3,1,'lim(x→0) (5x)/x limitini tapın.','İxtisardan sonra limit 5-dir.',array['Limit 5-dir','Limit 0-dır','Limit 1-dir','Limit sonsuzdur'],1),
('riy11-limit#17','riy-11-limit',2,1,'x→∞ olduqda x² funksiyası necə davranır?','Funksiya sonsuzluğa yaxınlaşır - sonsuz limit.',array['Sonsuzluğa yaxınlaşır','Sıfra yaxınlaşır','1-ə yaxınlaşır','Dəyişmir'],1),
('riy11-limit#18','riy-11-limit',1,1,'Kəsilməz funksiyanın qrafiki necə çəkilir?','Qrafik qələmi qaldırmadan çəkilə bilir.',array['Qələmi qaldırmadan','Yalnız nöqtələrlə','Yalnız xətkeşlə','Çəkilə bilmir'],1),
('riy11-limit#19','riy-11-limit',3,1,'aₙ = 5n/n ardıcıllığının limitini tapın.','5n/n = 5 sabitdir - limit 5-ə bərabərdir.',array['5-ə bərabərdir','Sıfra bərabərdir','Sonsuzdur','1-ə bərabərdir'],1),
('riy11-limit#20','riy-11-limit',2,1,'lim(x→4) √x limitini hesablayın.','Kök funksiyası kəsilməzdir: √4 = 2.',array['2','4','16','0'],1),
('riy11-limit#21','riy-11-limit',3,1,'Nisbətin limiti hansı şərtlə limitlərin nisbətinə bərabərdir?','Məxrəcin limiti sıfırdan fərqli olmalıdır.',array['Məxrəcin limiti sıfır olmadıqda','Həmişə','Heç vaxt','Surət sıfır olduqda'],1),
('riy11-limit#22','riy-11-limit',3,1,'0/0 şəkilli qeyri-müəyyənlik necə aradan qaldırılır?','İfadə çevrilir - vuruqlara ayrılıb ixtisar olunur.',array['Çevirib ixtisar etməklə','Limit yoxdur deməklə','Sıfır yazmaqla','Qiymət qoymaqla birbaşa'],1),
('riy11-limit#23','riy-11-limit',3,1,'y = (x² + 1)/x funksiyasının x = 0 nöqtəsində vəziyyəti necədir?','Məxrəc sıfırlanır - funksiya təyin olunmayıb, şaquli asimptot var.',array['Təyin olunmayıb','Kəsilməzdir','Qiyməti sıfırdır','Qiyməti 1-dir'],1),
('riy11-limit#24','riy-11-limit',3,1,'lim(x→0) cos x limitini tapın.','Kosinus kəsilməzdir: cos 0 = 1.',array['1-dir','0-dır','−1-dir','π-dir'],1),
('riy11-limit#25','riy-11-limit',2,1,'Ardıcıllığın limiti tərifində n hansı qiymətlərə yaxınlaşır?','n sonsuzluğa yaxınlaşır.',array['Sonsuzluğa','Sıfra','Birə','Mənfi sonsuzluğa'],1),
('riy11-limit#26','riy-11-limit',3,1,'Həndəsi silsilədə |q| < 1 olduqda hədlər limiti neçədir?','Hədlər sıfra yaxınlaşır.',array['Sıfra doğru azalır','1-ə yaxınlaşır','q-ya bərabər qalır','Sonsuzlaşır'],1),
('riy11-limit#27','riy-11-limit',3,1,'lim(x→2) (x + 3)(x − 1) limitini hesablayın.','5 · 1 = 5.',array['5 olur','6 olur','4 olur','10 olur'],1),
('riy11-limit#28','riy-11-limit',3,1,'Funksiya limitinin yeganəliyi nə deməkdir?','Nöqtədə limit varsa, o yeganədir.',array['Limit varsa yeganədir','İki limit ola bilər','Limit həmişə sıfırdır','Limit yoxdur'],1),
('riy11-limit#29','riy-11-limit',2,1,'y = x² funksiyası bütün oxda kəsilməzdirmi?','Çoxhədli funksiyalar hər yerdə kəsilməzdir.',array['Bəli, hər yerdə kəsilməzdir','Yalnız x > 0-da','Yalnız x < 0-da','Heç yerdə'],1),
('riy11-limit#30','riy-11-limit',3,1,'lim(x→∞) (2x + 1)/x limitini tapın.','2 + 1/x → 2.',array['2-yə yaxınlaşır','1-ə yaxınlaşır','Sıfra düşür','Sonsuzlaşır'],1),
('riy11-limit#31','riy-11-limit',2,1,'Asimptot qrafikə münasibətdə necə xətdir?','Qrafikin sonsuz yaxınlaşdığı, lakin kəsmədiyi xətdir.',array['Qrafikin sonsuz yaxınlaşdığı xətt','Qrafiki iki yerə bölən xətt','Qrafikin özü','Perpendikulyar xətt həmişə'],1),
('riy11-limit#32','riy-11-limit',2,1,'Limitlər nəzəriyyəsi riyaziyyatın hansı bölməsinin əsasını qoyur?','Limit anlayışı riyazi analizin təməlidir.',array['Riyazi analizin','Yalnız həndəsənin','Yalnız cəbrin','Statistikanın yalnız'],1),
('riy11-limit#33','riy-11-limit',3,1,'lim(x→0) (x² + x)/x limitini hesablayın.','İxtisar: lim (x + 1) = 1.',array['Limit 1-dir','Limit 0-dır','Limit 2-dir','Limit yoxdur'],1),
('riy11-limit#34','riy-11-limit',3,1,'Sıçrayışlı kəsilmə hansı funksiyalarda görünür?','Hissə-hissə verilmiş funksiyalarda qiymət sıçrayışı ola bilər.',array['Hissə-hissə verilmiş funksiyalarda','Çoxhədlilərdə','Sinusda','Sabit funksiyada'],1),
('riy11-limit#35','riy-11-limit',3,1,'x→∞ olduqda 5 − 1/x ifadəsinin limiti neçədir?','1/x → 0, limit 5-ə bərabərdir.',array['5-ə bərabərdir','4-ə bərabərdir','Sonsuzdur','Sıfırdır'],1),
('riy11-limit#36','riy-11-limit',3,1,'aₙ = (−1)ⁿ ardıcıllığının limiti varmı?','Hədlər −1 və 1 arasında sıçrayır - limit yoxdur.',array['Limiti yoxdur','Bəli, 1-dir','Bəli, −1-dir','Bəli, 0-dır'],1),
('riy11-limit#37','riy-11-limit',3,1,'Kəsilməzlik iqtisadi proseslərin modelləşdirilməsində nəyi bildirir?','Prosesin sıçrayışsız, rəvan dəyişməsini bildirir.',array['Rəvan dəyişməni','Kəskin böhranı','Prosesin dayanmasını','Heç nəyi'],1),
('riy11-limit#38','riy-11-limit',3,1,'lim(x→1) (x³ − 1)/(x − 1) limitini hesablayın.','x³−1 = (x−1)(x²+x+1); limit 1+1+1 = 3.',array['3-ə bərabərdir','1-ə bərabərdir','0-a bərabərdir','Limitsizdir'],1),
('riy11-limit#39','riy-11-limit',3,1,'Funksiyanın sağ və sol limitləri fərqli olduqda nöqtədə limit varmı?','Yalnız sağ və sol limitlər bərabər olduqda limit var.',array['Xeyr, limit olmur','Bəli, cəmi götürülür','Bəli, böyüyü götürülür','Bəli, hasili götürülür'],1),
('riy11-limit#40','riy-11-limit',3,1,'Limit anlayışı hansı praktik məsələdə istifadə olunur?','Ani sürətin təyini limitə əsaslanır.',array['Ani sürətin təyinində','Perimetrin ölçülməsində yalnız','Rəng seçimində','Heç bir məsələdə'],1),
('riy11-firlanma#1','riy-11-firlanma',2,2,'Silindr hansı fiqurun fırlanmasından alınır?','Düzbucaqlının tərəfi ətrafında fırlanmasından alınır.',array['Düzbucaqlının','Üçbucağın','Dairənin','Kvadratın yalnız'],1),
('riy11-firlanma#2','riy-11-firlanma',2,2,'Konus hansı fiqurun fırlanmasından alınır?','Düzbucaqlı üçbucağın katet ətrafında fırlanmasından alınır.',array['Düzbucaqlı üçbucağın','Kvadratın','Trapesiyanın','Çevrənin'],1),
('riy11-firlanma#3','riy-11-firlanma',2,2,'Kürə hansı fiqurun fırlanmasından yaranır?','Yarımdairənin diametr ətrafında fırlanmasından yaranır.',array['Yarımdairənin','Düzbucaqlının','Üçbucağın','Altıbucaqlının'],1),
('riy11-firlanma#4','riy-11-firlanma',2,2,'Silindrin yan səthinin sahəsi hansı düsturla hesablanır?','S(yan) = 2πrh.',array['2πrh','πr²h','4πr²','πrl'],1),
('riy11-firlanma#5','riy-11-firlanma',3,2,'Radiusu 3, hündürlüyü 5 olan silindrin yan səthinin sahəsini tapın.','S = 2π·3·5 = 30π.',array['30π','15π','45π','9π'],1),
('riy11-firlanma#6','riy-11-firlanma',2,2,'Silindrin tam səthi yan səthdən əlavə nəyi ehtiva edir?','İki oturacaq dairəsinin sahəsini.',array['İki oturacaq dairəsini','Bir oturacağı yalnız','Ox kəsiyini','Diaqonalı'],1),
('riy11-firlanma#7','riy-11-firlanma',2,2,'Konusun yan səthinin sahəsi hansı düsturla tapılır?','S(yan) = πrl (l - doğuran).',array['πrl','2πrh','πr²','4πr²'],1),
('riy11-firlanma#8','riy-11-firlanma',2,2,'Konusun doğuranı nədir?','Zirvəni oturacaq çevrəsi ilə birləşdirən parçadır.',array['Zirvə ilə çevrəni birləşdirən parça','Oturacağın diametri','Hündürlük','Radiusun yarısı'],1),
('riy11-firlanma#9','riy-11-firlanma',3,2,'Radiusu 3, doğuranı 5 olan konusun yan səthinin sahəsini tapın.','S = π·3·5 = 15π.',array['15π','30π','45π','8π'],1),
('riy11-firlanma#10','riy-11-firlanma',2,2,'Kürənin səthinin sahəsi hansı düsturla hesablanır?','S = 4πR².',array['4πR²','πR²','2πR','πR³'],1),
('riy11-firlanma#11','riy-11-firlanma',3,2,'Radiusu 3 olan kürənin səthinin sahəsini tapın.','S = 4π·9 = 36π.',array['36π','9π','12π','27π'],1),
('riy11-firlanma#12','riy-11-firlanma',3,2,'Silindrin ox kəsiyi hansı fiqurdur?','Ox kəsiyi düzbucaqlıdır.',array['Düzbucaqlı','Üçbucaq','Dairə','Trapesiya'],1),
('riy11-firlanma#13','riy-11-firlanma',3,2,'Konusun ox kəsiyi hansı fiqurdur?','Ox kəsiyi bərabəryanlı üçbucaqdır.',array['Bərabəryanlı üçbucaq','Kvadrat','Dairə','Romb'],1),
('riy11-firlanma#14','riy-11-firlanma',3,2,'Silindrin oturacağa paralel kəsiyi hansı fiqurdur?','Kəsik oturacağa bərabər dairədir.',array['Dairə','Ellips həmişə','Üçbucaq','Kvadrat'],1),
('riy11-firlanma#15','riy-11-firlanma',2,2,'Kəsik konus necə alınır?','Konusun oturacağa paralel müstəvi ilə kəsilməsindən alınır.',array['Konusun paralel kəsilməsindən','Silindrin əyilməsindən','Kürənin bölünməsindən','Prizmanın yonulmasından'],1),
('riy11-firlanma#16','riy-11-firlanma',3,2,'Kürənin müstəvi ilə kəsiyi hansı fiqurdur?','İstənilən müstəvi kəsiyi dairədir.',array['Dairə','Ellips','Kvadrat','Üçbucaq'],1),
('riy11-firlanma#17','riy-11-firlanma',3,2,'Kürəyə toxunan müstəvi ilə kürənin neçə ortaq nöqtəsi olur?','Toxunan müstəvi ilə bir ortaq nöqtə olur.',array['Bir','İki','Sonsuz','Heç bir'],1),
('riy11-firlanma#18','riy-11-firlanma',3,2,'Silindrin doğuranı hansı elementinə bərabərdir?','Silindrdə doğuran hündürlüyə bərabərdir.',array['Hündürlüyünə','Radiusuna','Diametrinə','Ox kəsiyinə'],1),
('riy11-firlanma#19','riy-11-firlanma',3,2,'Doğuranı 5, radiusu 3 olan konusun hündürlüyünü tapın.','h = √(l² − r²) = √(25 − 9) = 4.',array['4 vahid','5 vahid','3 vahid','8 vahid'],1),
('riy11-firlanma#20','riy-11-firlanma',3,2,'Oxşar fiqurların səthlərinin sahələri nisbəti oxşarlıq əmsalının hansı qüvvəsidir?','Səthlər nisbəti əmsalın kvadratıdır.',array['Kvadratı','Kubu','Özü','Dördüncü qüvvəsi'],1),
('riy11-firlanma#21','riy-11-firlanma',1,2,'Konservi bankası hansı həndəsi cismin formasındadır?','Banka silindr formasındadır.',array['Silindr','Konus','Kürə','Piramida'],1),
('riy11-firlanma#22','riy-11-firlanma',1,2,'Dondurma külahı hansı fiqura bənzəyir?','Külah konus formasındadır.',array['Konusa','Silindrə','Kürəyə','Kuba'],1),
('riy11-firlanma#23','riy-11-firlanma',1,2,'Futbol topu hansı həndəsi cismin modelidir?','Top kürə formasındadır.',array['Kürənin','Konusun','Silindrin','Prizmanın'],1),
('riy11-firlanma#24','riy-11-firlanma',2,2,'Kürənin səthi ilə mərkəz arasındakı məsafə bütün nöqtələr üçün necədir?','Bütün səth nöqtələri mərkəzdən radius qədər uzaqdadır.',array['Bərabərdir (radiusa)','Fərqlidir','Sıfırdır','Sonsuzdur'],1),
('riy11-firlanma#25','riy-11-firlanma',3,2,'Silindrin radiusu 2 dəfə artırılsa (h sabit), yan səthi necə dəyişər?','S = 2πrh: yan səth 2 dəfə artar.',array['2 dəfə artar','4 dəfə artar','Dəyişməz','8 dəfə artar'],1),
('riy11-firlanma#26','riy-11-firlanma',3,2,'Kürənin radiusu 2 dəfə artırılsa, səthi neçə dəfə artar?','S = 4πR²: səth 4 dəfə artar.',array['4 dəfə','2 dəfə','8 dəfə','16 dəfə'],1),
('riy11-firlanma#27','riy-11-firlanma',3,2,'Kəsik konusun oturacaqları hansı fiqurlardır?','Fərqli radiuslu iki dairədir.',array['Fərqli radiuslu iki dairə','Bərabər iki kvadrat','İki üçbucaq','Dairə və kvadrat'],1),
('riy11-firlanma#28','riy-11-firlanma',3,2,'Mürəkkəb fırlanma cisimlərinin səthi necə hesablanır?','Hissələrin səthlərinin cəmi kimi hesablanır.',array['Hissələrin cəmi kimi','Yalnız ən böyük hissə ilə','Hesablanmır','Təxminlə yalnız'],1),
('riy11-firlanma#29','riy-11-firlanma',1,2,'Diametri 10 olan kürənin radiusu neçədir?','R = d/2 = 5.',array['Radius 5-dir','Radius 10-dur','Radius 20-dir','Radius 2,5-dir'],1),
('riy11-firlanma#30','riy-11-firlanma',2,2,'Silindrin hündürlüyü nəyə perpendikulyar ölçülür?','Oturacaqlar arasındakı perpendikulyar məsafədir.',array['Oturacaqlara','Yan səthə','Doğurana','Diaqonala'],1),
('riy11-firlanma#31','riy-11-firlanma',2,2,'İdman kubokunun gövdəsi çox vaxt hansı fırlanma fiqurudur?','Kubok gövdəsi kəsik konusa bənzəyir.',array['Kəsik konus','Kub','Piramida','Prizma'],1),
('riy11-firlanma#32','riy-11-firlanma',1,2,'Yer kürəsinin forması təqribən hansı həndəsi fiqura yaxındır?','Yer təqribən kürə formasındadır.',array['Kürəyə','Konusa','Silindrə','Kuba'],1),
('riy11-firlanma#33','riy-11-firlanma',2,2,'Konusun hündürlüyü haradan endirilir?','Zirvədən oturacağın mərkəzinə endirilir.',array['Zirvədən oturacağın mərkəzinə','Doğurandan çevrəyə','Radiusdan diametrə','Çevrədən çevrəyə'],1),
('riy11-firlanma#34','riy-11-firlanma',3,2,'Radiusu r olan dairənin sahəsi kürənin səthi düsturunda hansı əmsalla fərqlənir?','Kürənin səthi dairə sahəsindən 4 dəfə böyükdür.',array['4 dəfə böyükdür','2 dəfə böyükdür','Bərabərdir','π dəfə böyükdür'],1),
('riy11-firlanma#35','riy-11-firlanma',3,2,'Silindrin yan səthi açıldıqda hansı fiqur alınır?','Açılış düzbucaqlıdır.',array['Düzbucaqlı','Dairə','Üçbucaq','Sektor'],1),
('riy11-firlanma#36','riy-11-firlanma',3,2,'Konusun yan səthi açıldıqda hansı fiqur alınır?','Açılış dairə sektorudur.',array['Dairə sektoru','Düzbucaqlı','Kvadrat','Trapesiya'],1),
('riy11-firlanma#37','riy-11-firlanma',3,2,'Ox kəsiyi kvadrat olan silindrdə hündürlük radiusla necə bağlıdır?','Kəsik kvadratdırsa h = 2r.',array['h = 2r','h = r','h = r/2','h = 4r'],1),
('riy11-firlanma#38','riy-11-firlanma',2,2,'Fırlanma fiqurlarını digər cisimlərdən fərqləndirən nədir?','Onların səthi fırlanma ilə yaranır və ox simmetriyası var.',array['Fırlanma oxu simmetriyası','Yalnız düz üzlər','Təpə nöqtələrinin çoxluğu','Heç nə'],1),
('riy11-firlanma#39','riy-11-firlanma',3,2,'Boru hansı həndəsi fiqurların birləşməsidir?','Boru iki silindr arasındakı hissədir.',array['İki silindr arasındakı hissə','İki konus','İki kürə','Kub və silindr'],1),
('riy11-firlanma#40','riy-11-firlanma',2,2,'Günbəz formalı dam hansı fiqurun hissəsinə bənzəyir?','Günbəz yarımkürəyə bənzəyir.',array['Yarımkürəyə','Konusun ox kəsiyinə','Silindrin oturacağına','Prizmaya'],1),
('riy11-toreme#1','riy-11-toreme',2,2,'Funksiyanın törəməsi fiziki mənada nəyi ifadə edir?','Törəmə dəyişmənin ani sürətidir.',array['Dəyişmənin ani sürətini','Funksiyanın ən böyük qiymətini','Qrafikin sahəsini','Dövrü'],1),
('riy11-toreme#2','riy-11-toreme',2,2,'y = x² funksiyasının törəməsi hansıdır?','(x²)ʹ = 2x.',array['2x','x','x²','2'],1),
('riy11-toreme#3','riy-11-toreme',2,2,'y = x³ funksiyasının törəməsini tapın.','(x³)ʹ = 3x².',array['3x²','x²','3x','x³'],1),
('riy11-toreme#4','riy-11-toreme',1,2,'Sabit ədədin törəməsi nəyə bərabərdir?','Sabitin törəməsi sıfırdır.',array['Sıfra','Özünə','Birə','Sonsuzluğa'],1),
('riy11-toreme#5','riy-11-toreme',2,2,'y = 5x funksiyasının törəməsi neçədir?','(5x)ʹ = 5.',array['5','5x','0','x'],1),
('riy11-toreme#6','riy-11-toreme',2,2,'Cəmin törəməsi qaydası necədir?','(f + g)ʹ = fʹ + gʹ.',array['Törəmələrin cəminə bərabərdir','Törəmələrin hasilinə bərabərdir','Həmişə sıfırdır','Cəmin kvadratıdır'],1),
('riy11-toreme#7','riy-11-toreme',3,2,'f(x) = x² funksiyası üçün fʹ(3) qiymətini tapın.','fʹ(x) = 2x, fʹ(3) = 6.',array['6','9','3','12'],1),
('riy11-toreme#8','riy-11-toreme',3,2,'Hasilin törəməsi qaydası hansıdır?','(fg)ʹ = fʹg + fgʹ.',array['fʹg + fgʹ','fʹgʹ','fʹg − fgʹ','fg'],1),
('riy11-toreme#9','riy-11-toreme',3,2,'Nisbətin törəməsi düsturunda məxrəcdə nə durur?','(f/g)ʹ = (fʹg − fgʹ)/g².',array['g²','g','fʹ','f²'],1),
('riy11-toreme#10','riy-11-toreme',3,2,'(sin x)ʹ törəməsi hansıdır?','(sin x)ʹ = cos x.',array['cos x','−cos x','sin x','−sin x'],1),
('riy11-toreme#11','riy-11-toreme',3,2,'(cos x)ʹ törəməsi hansıdır?','(cos x)ʹ = −sin x.',array['−sin x','sin x','cos x','−cos x'],1),
('riy11-toreme#12','riy-11-toreme',3,2,'(eˣ)ʹ törəməsi nəyə bərabərdir?','Eksponentin törəməsi özüdür: eˣ.',array['eˣ','xeˣ','e','1'],1),
('riy11-toreme#13','riy-11-toreme',3,2,'(ln x)ʹ törəməsi hansıdır?','(ln x)ʹ = 1/x.',array['1/x','ln x','x','eˣ'],1),
('riy11-toreme#14','riy-11-toreme',3,2,'Mürəkkəb funksiyanın törəməsi hansı qayda ilə tapılır?','Zəncir qaydası: xarici funksiyanın törəməsi vur daxilinin törəməsi.',array['Zəncir qaydası ilə','Yalnız cəm qaydası ilə','Toplama ilə','Qayda yoxdur'],1),
('riy11-toreme#15','riy-11-toreme',3,2,'y = (2x + 1)³ funksiyasının törəməsini tapın.','Zəncir qaydası: 3(2x+1)²·2 = 6(2x+1)².',array['6(2x + 1)²','3(2x + 1)²','(2x + 1)²','6x²'],1),
('riy11-toreme#16','riy-11-toreme',3,2,'İkinci tərtib törəmə necə tapılır?','Törəmənin törəməsi götürülür.',array['Törəmənin törəməsi kimi','Törəmənin kvadratı kimi','İnteqralla','İki dəfə vurmaqla'],1),
('riy11-toreme#17','riy-11-toreme',3,2,'y = x³ funksiyasının ikinci törəməsini tapın.','yʹ = 3x², yʺ = 6x.',array['6x','3x²','6','x'],1),
('riy11-toreme#18','riy-11-toreme',2,2,'Yol funksiyasının zamana görə törəməsi nəyi verir?','Yolun törəməsi sürətdir.',array['Sürəti','Təcili birbaşa','Kütləni','Qüvvəni'],1),
('riy11-toreme#19','riy-11-toreme',3,2,'Sürət funksiyasının törəməsi hansı kəmiyyəti verir?','Sürətin törəməsi təcildir.',array['Təcili','Yolu','İmpulsu','Enerjini'],1),
('riy11-toreme#20','riy-11-toreme',3,2,'f(x) = 3x² + 2x funksiyasının törəməsini tapın.','fʹ(x) = 6x + 2.',array['6x + 2','3x + 2','6x','x² + 2'],1),
('riy11-toreme#21','riy-11-toreme',2,2,'f(x) = 7 funksiyasının törəməsi istənilən nöqtədə neçədir?','Sabit funksiyanın törəməsi 0-dır.',array['0-dır','7-dir','1-dir','x-dir'],1),
('riy11-toreme#22','riy-11-toreme',3,2,'Törəmənin həndəsi mənası nədir?','Toxunanın bucaq əmsalıdır.',array['Toxunanın bucaq əmsalı','Qrafikin sahəsi','Əyrinin uzunluğu','Kəsənin uzunluğu'],1),
('riy11-toreme#23','riy-11-toreme',3,2,'Toxunan üfüqi olduqda törəmə hansı qiyməti alır?','Üfüqi toxunanda bucaq əmsalı sıfırdır.',array['Sıfır','Bir','Sonsuz','Mənfi bir'],1),
('riy11-toreme#24','riy-11-toreme',3,2,'Kök funksiyasının diferensiallanması hansı nəticəni verir?','(√x)ʹ = 1/(2√x).',array['1/(2√x)','√x','2√x','1/√x'],1),
('riy11-toreme#25','riy-11-toreme',3,2,'f(x) = x² − 4x funksiyası üçün fʹ(x) = 0 tənliyini həll edin.','2x − 4 = 0, x = 2.',array['x = 2','x = 4','x = 0','x = −2'],1),
('riy11-toreme#26','riy-11-toreme',2,2,'Diferensiallama nə deməkdir?','Funksiyanın törəməsinin tapılması prosesidir.',array['Törəmənin tapılması','İnteqralın tapılması','Qrafikin çəkilməsi','Limitin silinməsi'],1),
('riy11-toreme#27','riy-11-toreme',3,2,'(x⁵)ʹ törəməsini tapın.','(xⁿ)ʹ = nxⁿ⁻¹: 5x⁴.',array['5x⁴','x⁴','5x⁵','4x⁵'],1),
('riy11-toreme#28','riy-11-toreme',2,2,'Fərqin törəməsi qaydası necədir?','(f − g)ʹ = fʹ − gʹ.',array['Törəmələrin fərqinə bərabərdir','Törəmələrin cəminə','Həmişə sıfıra','Hasilə'],1),
('riy11-toreme#29','riy-11-toreme',3,2,'y = 4x³ funksiyasının törəməsini tapın.','yʹ = 12x².',array['12x²','4x²','12x³','3x²'],1),
('riy11-toreme#30','riy-11-toreme',2,2,'Sabit vuruq törəmə işarəsindən necə çıxarılır?','(c·f)ʹ = c·fʹ - sabit çıxarılır.',array['Olduğu kimi çıxarılır','Kvadrata yüksəldilir','Sıfırlanır','Tərsi götürülür'],1),
('riy11-toreme#31','riy-11-toreme',3,2,'f(x) = sin x üçün fʹ(0) qiymətini tapın.','fʹ(x) = cos x, fʹ(0) = 1.',array['fʹ(0) = 1','fʹ(0) = 0','fʹ(0) = −1','fʹ(0) = π'],1),
('riy11-toreme#32','riy-11-toreme',3,2,'Törəmə anlayışını riyaziyyata hansı alimlər gətirmişdir?','Nyuton və Leybnis diferensial hesabı yaratmışlar.',array['Nyuton və Leybnis','Evklid və Pifaqor','Dekart və Fales','Herodot və Platon'],1),
('riy11-toreme#33','riy-11-toreme',3,2,'Funksiya nöqtədə törəməyə malikdirsə, o nöqtədə necədir?','Diferensiallanan funksiya həmin nöqtədə kəsilməzdir.',array['Kəsilməzdir','Kəsilir','Təyin olunmayıb','Maksimumdadır'],1),
('riy11-toreme#34','riy-11-toreme',3,2,'y = 1/x funksiyasının törəməsi hansıdır?','(1/x)ʹ = −1/x².',array['−1/x²','1/x²','ln x','−x'],1),
('riy11-toreme#35','riy-11-toreme',3,2,'Əhalinin artım sürəti hansı riyazi əməllə qiymətləndirilir?','Artım funksiyasının törəməsi ilə qiymətləndirilir.',array['Törəmə ilə','Toplama ilə yalnız','Bölmə ilə yalnız','Qiymətləndirilmir'],1),
('riy11-toreme#36','riy-11-toreme',3,2,'f(x) = 2x² + 3x + 1 üçün fʹ(1) qiymətini tapın.','fʹ(x) = 4x + 3, fʹ(1) = 7.',array['7','6','4','3'],1),
('riy11-toreme#37','riy-11-toreme',3,2,'(tan x)ʹ törəməsi hansıdır?','(tan x)ʹ = 1/cos²x.',array['1/cos²x','1/sin²x','cos x','−1/cos²x'],1),
('riy11-toreme#38','riy-11-toreme',1,2,'y = x funksiyasının törəməsi neçədir?','(x)ʹ = 1.',array['1','x','0','2x'],1),
('riy11-toreme#39','riy-11-toreme',3,2,'Törəmə iqtisadiyyatda nəyin ölçülməsində istifadə olunur?','Dəyişmə tempinin - məsələn, xərcin artım sürətinin.',array['Dəyişmə tempinin','Yalnız qiymətin özünün','Yalnız çəkinin','Heç nəyin'],1),
('riy11-toreme#40','riy-11-toreme',3,2,'y = x² qrafikinə x = 1 nöqtəsində çəkilən toxunanın bucaq əmsalını tapın.','k = yʹ(1) = 2.',array['k = 2','k = 1','k = 4','k = 0'],1),
('riy11-firlanma-hecm#1','riy-11-firlanma-hecm',2,2,'Silindrin həcmi hansı düsturla hesablanır?','V = πr²h.',array['πr²h','2πrh','πr²h/3','4πr³/3'],1),
('riy11-firlanma-hecm#2','riy-11-firlanma-hecm',3,2,'Radiusu 2, hündürlüyü 3 olan silindrin həcmini tapın.','V = π·4·3 = 12π.',array['12π','6π','24π','4π'],1),
('riy11-firlanma-hecm#3','riy-11-firlanma-hecm',2,2,'Konusun həcmi hansı düsturla tapılır?','V = πr²h/3.',array['πr²h/3','πr²h','πrl','4πr³/3'],1),
('riy11-firlanma-hecm#4','riy-11-firlanma-hecm',3,2,'Radiusu 3, hündürlüyü 5 olan konusun həcmini tapın.','V = π·9·5/3 = 15π.',array['15π','45π','5π','9π'],1),
('riy11-firlanma-hecm#5','riy-11-firlanma-hecm',2,2,'Kürənin həcmi hansı düsturla hesablanır?','V = 4πR³/3.',array['4πR³/3','4πR²','πR³','2πR³/3'],1),
('riy11-firlanma-hecm#6','riy-11-firlanma-hecm',3,2,'Radiusu 3 olan kürənin həcmini tapın.','V = 4π·27/3 = 36π.',array['36π','27π','12π','108π'],1),
('riy11-firlanma-hecm#7','riy-11-firlanma-hecm',3,2,'Eyni oturacaq və hündürlüklü silindrlə konusun həcmləri necə fərqlənir?','Konusun həcmi silindrinkindən 3 dəfə kiçikdir.',array['Konusunki 3 dəfə kiçikdir','Bərabərdirlər','Konusunki 2 dəfə böyükdür','Silindrinki 3 dəfə kiçikdir'],1),
('riy11-firlanma-hecm#8','riy-11-firlanma-hecm',3,2,'Kürənin radiusu 2 dəfə artırılsa, həcmi neçə dəfə artar?','V ~ R³: həcm 8 dəfə artar.',array['8 dəfə','4 dəfə','2 dəfə','6 dəfə'],1),
('riy11-firlanma-hecm#9','riy-11-firlanma-hecm',3,2,'Silindrin hündürlüyü 2 dəfə artırılsa (r sabit), həcmi necə dəyişər?','V = πr²h: həcm 2 dəfə artar.',array['2 dəfə artar','4 dəfə artar','Dəyişməz','8 dəfə artar'],1),
('riy11-firlanma-hecm#10','riy-11-firlanma-hecm',3,2,'Kəsik konusun həcmini tapmaq üçün hansı kəmiyyətlər lazımdır?','İki oturacağın radiusları və hündürlük lazımdır.',array['İki radius və hündürlük','Yalnız doğuran','Yalnız perimetr','Yalnız diaqonal'],1),
('riy11-firlanma-hecm#11','riy-11-firlanma-hecm',3,2,'Oxşar fırlanma fiqurlarının həcmləri nisbəti hansı qanunla dəyişir?','Həcmlər oxşarlıq əmsalının kubu ilə mütənasibdir.',array['Əmsalın kubu ilə','Əmsalın kvadratı ilə','Əmsalın özü ilə','Dəyişmir'],1),
('riy11-firlanma-hecm#12','riy-11-firlanma-hecm',3,2,'Radiusu 1, hündürlüyü 6 olan silindrin həcmini tapın.','V = π·1·6 = 6π.',array['6π','12π','3π','π'],1),
('riy11-firlanma-hecm#13','riy-11-firlanma-hecm',1,2,'Silindrik su çəninin tutumunu bilmək üçün nəyi hesablamaq lazımdır?','Çənin həcmini hesablamaq lazımdır.',array['Həcmini','Yalnız səthini','Yalnız radiusunu','Rəngini'],1),
('riy11-firlanma-hecm#14','riy-11-firlanma-hecm',3,2,'Diametri 6, hündürlüyü 4 olan konusun həcmini tapın.','r = 3; V = π·9·4/3 = 12π sm³ (vahidlə).',array['12π','36π','9π','24π'],1),
('riy11-firlanma-hecm#15','riy-11-firlanma-hecm',2,2,'Yarımkürənin həcmi kürənin həcminin hansı hissəsidir?','Yarımkürə tam kürənin yarısıdır.',array['Yarısıdır','Üçdə biridir','Dörddə biridir','Bərabərdir'],1),
('riy11-firlanma-hecm#16','riy-11-firlanma-hecm',2,2,'V = πr²h düsturu ilə hansı praktik məsələ həll olunur?','Boru və çənlərin tutumu hesablanır.',array['Çənin tutumunun hesablanması','Yolun uzunluğu','Bucağın ölçüsü','Sürətin tapılması'],1),
('riy11-firlanma-hecm#17','riy-11-firlanma-hecm',2,2,'Konus formalı qumun topasının həcmi hansı düsturla qiymətləndirilir?','Konus həcmi düsturu ilə: πr²h/3.',array['πr²h/3 ilə','4πR³/3 ilə','2πrh ilə','πd ilə'],1),
('riy11-firlanma-hecm#18','riy-11-firlanma-hecm',3,2,'Kürə şəkilli balonun həcmi radius 3 dəfə artdıqda neçə dəfə artar?','3³ = 27 dəfə artar.',array['27 dəfə','9 dəfə','3 dəfə','81 dəfə'],1),
('riy11-firlanma-hecm#19','riy-11-firlanma-hecm',1,2,'Silindr və konusun həcm düsturlarındakı π ədədi təqribən neçədir?','π ≈ 3,14.',array['3,14','2,72','1,41','9,81'],1),
('riy11-firlanma-hecm#20','riy-11-firlanma-hecm',3,2,'Kəsik konusun həcmi tam konusdan necə alına bilər?','Böyük konusdan kiçik konusun həcmi çıxılır.',array['Böyükdən kiçiyin çıxılması ilə','Toplama ilə','Vurma ilə','Alına bilməz'],1),
('riy11-firlanma-hecm#21','riy-11-firlanma-hecm',3,2,'Hündürlüyü bərabər iki silindrdən radiusu 2 dəfə böyük olanın həcmi neçə dəfə böyükdür?','V ~ r²: 4 dəfə böyükdür.',array['4 dəfə','2 dəfə','8 dəfə','16 dəfə'],1),
('riy11-firlanma-hecm#22','riy-11-firlanma-hecm',2,2,'Kürənin həcm düsturunda radius hansı qüvvətdədir?','V = 4πR³/3 - üçüncü qüvvətdə.',array['Üçüncü','İkinci','Birinci','Dördüncü'],1),
('riy11-firlanma-hecm#23','riy-11-firlanma-hecm',2,2,'1 litr neçə kubik santimetrə bərabərdir?','1 litr = 1000 sm³.',array['1000 sm³','100 sm³','10 sm³','10000 sm³'],1),
('riy11-firlanma-hecm#24','riy-11-firlanma-hecm',3,2,'Radiusu 3, hündürlüyü 7 olan silindrin həcmini tapın.','V = π·9·7 = 63π.',array['63π','21π','42π','9π'],1),
('riy11-firlanma-hecm#25','riy-11-firlanma-hecm',3,2,'Fırlanma fiqurlarının həcmləri hansı ali riyaziyyat aləti ilə çıxarılır?','Həcm düsturları inteqralla əsaslandırılır.',array['İnteqralla','Yalnız xətkeşlə','Kompasla','Təxminlə'],1),
('riy11-firlanma-hecm#26','riy-11-firlanma-hecm',3,2,'Konusun hündürlüyü 3 dəfə artsa (r sabit), həcmi necə dəyişər?','V ~ h: 3 dəfə artar.',array['3 dəfə artar','9 dəfə artar','27 dəfə artar','Dəyişməz'],1),
('riy11-firlanma-hecm#27','riy-11-firlanma-hecm',3,2,'Su ilə dolu yarımkürə qabın tutumu R = 3 olduqda neçədir?','V = (1/2)·36π = 18π.',array['18π','36π','9π','12π'],1),
('riy11-firlanma-hecm#28','riy-11-firlanma-hecm',2,2,'Mühəndislikdə boruların tutumu hansı fiqurun həcmi kimi hesablanır?','Boru silindr kimi hesablanır.',array['Silindrin','Konusun','Kürənin','Kubun'],1),
('riy11-firlanma-hecm#29','riy-11-firlanma-hecm',1,2,'Hansı cismin həcmi 4πR³/3 düsturu ilə tapılır?','Bu, kürənin həcm düsturudur.',array['Kürənin','Silindrin','Konusun','Prizmanın'],1),
('riy11-firlanma-hecm#30','riy-11-firlanma-hecm',3,2,'Konus formalı qıfın tutumu r = 3, h = 2 olduqda neçədir?','V = π·9·2/3 = 6π.',array['6π','18π','3π','9π'],1),
('riy11-firlanma-hecm#31','riy-11-firlanma-hecm',3,2,'Bərabər həcmli kürə və silindrin xarici görünüşcə fərqi nədir?','Formaları fərqlidir - həcm bərabərliyi formanı təyin etmir.',array['Formaları fərqli qala bilər','Mütləq eyni formadadırlar','Kürə həmişə böyükdür','Silindr həmişə böyükdür'],1),
('riy11-firlanma-hecm#32','riy-11-firlanma-hecm',3,2,'Dünya okeanının su həcmini qiymətləndirmək üçün hansı fiqur modelindən istifadə etmək olar?','Kürə təbəqəsi (sferik qat) modelindən.',array['Kürə təbəqəsi modelindən','Kub modelindən','Konus modelindən','Model lazım deyil'],1),
('riy11-firlanma-hecm#33','riy-11-firlanma-hecm',3,2,'Silindrin oturacağının sahəsi 10, hündürlüyü 6-dırsa, həcmi neçədir?','V = S·h = 60.',array['60','16','30','100'],1),
('riy11-firlanma-hecm#34','riy-11-firlanma-hecm',3,2,'Ballonların qaz tutumu artırılmaq istənirsə, hansı ölçünün artırılması daha səmərəlidir?','Radiusun artırılması - həcm kubla artır.',array['Radiusun','Yalnız rəngin','Yalnız çəkinin','Heç birinin'],1),
('riy11-firlanma-hecm#35','riy-11-firlanma-hecm',3,2,'Kəsik konus formalı vedrənin həcmi hansı radiuslarla hesablanır?','Alt və üst oturacaqların radiusları ilə.',array['Alt və üst radiuslarla','Yalnız orta radiusla','Yalnız doğuranla','Perimetrlə'],1),
('riy11-firlanma-hecm#36','riy-11-firlanma-hecm',3,2,'Fırlanma fiquru olan cisimlərin istehsalda üstünlüyü nədir?','Torna dəzgahında asan emal olunurlar.',array['Asan emal olunmaları','Ağır olmaları','Bahalı olmaları','Kövrək olmaları'],1),
('riy11-firlanma-hecm#37','riy-11-firlanma-hecm',2,2,'π ədədi hansı nisbəti ifadə edir?','Çevrənin uzunluğunun diametrə nisbətidir.',array['Çevrənin diametrə nisbətini','Sahənin perimetrə nisbətini','Radiusun sahəyə nisbətini','Heç nəyi'],1),
('riy11-firlanma-hecm#38','riy-11-firlanma-hecm',3,2,'Hündürlükləri bərabər konus və silindrin həcmləri bərabərdirsə, radiusları necədir?','Konusun radiusu böyük olmalıdır (√3 dəfə).',array['Konusunki böyükdür','Bərabərdir','Silindrinki böyükdür','Müqayisə olunmur'],1),
('riy11-firlanma-hecm#39','riy-11-firlanma-hecm',3,2,'Kürənin həcmi 36π-dirsə, radiusu neçədir?','4πR³/3 = 36π, R³ = 27, R = 3.',array['R = 3','R = 6','R = 9','R = 27'],1),
('riy11-firlanma-hecm#40','riy-11-firlanma-hecm',1,2,'Fırlanma fiqurlarının həcm düsturlarını bilmək hansı peşələrdə lazımdır?','Mühəndis, memar və texnoloqlara lazımdır.',array['Mühəndis və memarlara','Yalnız rəssamlara','Yalnız müğənnilərə','Heç kimə'],1),
('riy11-arasdirma#1','riy-11-arasdirma',2,3,'Funksiya aralıqda artan olduqda törəməsi hansı işarədədir?','Artan funksiyada fʹ(x) > 0.',array['Müsbətdir','Mənfidir','Sıfırdır','Təyin olunmur'],1),
('riy11-arasdirma#2','riy-11-arasdirma',2,3,'Funksiya aralıqda azalan olduqda törəməsi necədir?','Azalan funksiyada fʹ(x) < 0.',array['Mənfidir','Müsbətdir','Sıfırdır','Sonsuzdur'],1),
('riy11-arasdirma#3','riy-11-arasdirma',2,3,'Böhran nöqtəsi hansı nöqtədir?','Törəmənin sıfır olduğu və ya olmadığı nöqtədir.',array['Törəmənin sıfır olduğu nöqtə','Qrafikin ən sağ nöqtəsi','OY ilə kəsişmə','İxtiyari nöqtə'],1),
('riy11-arasdirma#4','riy-11-arasdirma',3,3,'f(x) = x² − 6x funksiyasının böhran nöqtəsini tapın.','fʹ = 2x − 6 = 0, x = 3.',array['x = 3','x = 6','x = −3','x = 0'],1),
('riy11-arasdirma#5','riy-11-arasdirma',3,3,'Törəmə müsbətdən mənfiyə keçdikdə böhran nöqtəsində nə olur?','Funksiyanın maksimumu olur.',array['Maksimum','Minimum','Kəsilmə','Asimptot'],1),
('riy11-arasdirma#6','riy-11-arasdirma',3,3,'Törəmə mənfidən müsbətə keçdikdə nöqtədə nə olur?','Funksiyanın minimumu olur.',array['Minimum','Maksimum','Sıçrayış','Heç nə'],1),
('riy11-arasdirma#7','riy-11-arasdirma',2,3,'Ekstremum nöqtələri hansı nöqtələrin ümumi adıdır?','Maksimum və minimum nöqtələrinin.',array['Maksimum və minimum nöqtələrinin','Kəsilmə nöqtələrinin','Sıfırların','Asimptotların'],1),
('riy11-arasdirma#8','riy-11-arasdirma',2,3,'f(x) = x² funksiyasının minimum nöqtəsi hansıdır?','fʹ = 2x = 0: x = 0-da minimum.',array['x = 0','x = 1','x = −1','Minimum yoxdur'],1),
('riy11-arasdirma#9','riy-11-arasdirma',3,3,'f(x) = −x² + 4x funksiyasının maksimum nöqtəsini tapın.','fʹ = −2x + 4 = 0, x = 2.',array['x = 2 nöqtəsi','x = 4 nöqtəsi','x = −2 nöqtəsi','x = 0 nöqtəsi'],1),
('riy11-arasdirma#10','riy-11-arasdirma',2,3,'Funksiyanın qrafikini qurmazdan əvvəl törəmə ilə nə müəyyən edilir?','Artma-azalma aralıqları və ekstremumlar müəyyən edilir.',array['Artma-azalma və ekstremumlar','Yalnız rəng','Yalnız adı','Heç nə'],1),
('riy11-arasdirma#11','riy-11-arasdirma',2,3,'Optimallaşdırma məsələsi nəyi tapmağı tələb edir?','Kəmiyyətin ən böyük və ya ən kiçik qiymətini.',array['Ən böyük/ən kiçik qiyməti','Orta qiyməti yalnız','Təsadüfi qiyməti','Cəmi'],1),
('riy11-arasdirma#12','riy-11-arasdirma',3,3,'Perimetri sabit olan düzbucaqlılar içində sahəsi ən böyük olan hansıdır?','Kvadrat maksimal sahə verir.',array['Kvadrat','Uzunsov düzbucaqlı','İstənilən biri','Yoxdur'],1),
('riy11-arasdirma#13','riy-11-arasdirma',3,3,'f(x) = x³ − 3x funksiyasının böhran nöqtələrini tapın.','fʹ = 3x² − 3 = 0, x = ±1.',array['x = ±1','x = 0','x = 3','x = ±3'],1),
('riy11-arasdirma#14','riy-11-arasdirma',3,3,'Parçada funksiyanın ən böyük qiyməti harada axtarılır?','Böhran nöqtələrində və parçanın uclarında.',array['Böhran nöqtələri və uclarda','Yalnız ortada','Yalnız uclarda','Qrafikdən kənarda'],1),
('riy11-arasdirma#15','riy-11-arasdirma',3,3,'f(x) = x² funksiyasının [0; 3] parçasında ən böyük qiymətini tapın.','Artan funksiyada ən böyük qiymət sağ ucda: f(3) = 9.',array['9','0','3','6'],1),
('riy11-arasdirma#16','riy-11-arasdirma',3,3,'İkinci törəmə müsbət olduqda qrafik necə yönəlib?','Qabarıqlığı aşağı (çökük) olur.',array['Çökükdür (qabarıqlıq aşağı)','Qabarıqdır yuxarı','Düz xətdir','Kəsilir'],1),
('riy11-arasdirma#17','riy-11-arasdirma',2,3,'Maksimum nöqtəsində funksiyanın qiyməti ətrafdakı qiymətlərdən necədir?','Ətrafdakılardan böyükdür.',array['Böyükdür','Kiçikdir','Bərabərdir','Sıfırdır'],1),
('riy11-arasdirma#18','riy-11-arasdirma',3,3,'Materialdan qənaətlə qutu düzəltmək məsələsi hansı üsulla həll olunur?','Törəmə ilə optimallaşdırma üsulu ilə.',array['Törəmə ilə optimallaşdırma','Təxminlə','Şablonla','Qrafiksiz olmur'],1),
('riy11-arasdirma#19','riy-11-arasdirma',3,3,'f(x) = x³ funksiyasının x = 0 nöqtəsində ekstremumu varmı?','fʹ = 3x² işarəsini dəyişmir - ekstremum yoxdur.',array['Xeyr, yoxdur','Bəli, maksimum','Bəli, minimum','İki ekstremum var'],1),
('riy11-arasdirma#20','riy-11-arasdirma',2,3,'Funksiyanın araşdırılması sxeminə nə daxildir?','Təyin oblastı, törəmə, ekstremumlar, qrafik.',array['Təyin oblastı, törəmə, ekstremumlar','Yalnız cədvəl','Yalnız rənglər','Yalnız adlar'],1),
('riy11-arasdirma#21','riy-11-arasdirma',3,3,'Sürətin maksimum olduğu anda təcil neçədir?','Ekstremumda törəmə (təcil) sıfırdır.',array['Sıfırdır','Maksimumdur','Mənfidir hökmən','Sonsuzdur'],1),
('riy11-arasdirma#22','riy-11-arasdirma',2,3,'f(x) = 2x + 5 funksiyasının ekstremumu varmı?','Xətti funksiya monotondur - ekstremum yoxdur.',array['Xeyr, monotondur','Bəli, x = 5-də','Bəli, x = 2-də','Bəli, x = 0-da'],1),
('riy11-arasdirma#23','riy-11-arasdirma',3,3,'Mənfəətin maksimallaşdırılması məsələsində hansı şərt yazılır?','Mənfəət funksiyasının törəməsi sıfıra bərabər edilir.',array['Törəmə sıfıra bərabər edilir','Funksiya sıfırlanır','Qiymət artırılır sonsuz','Şərt yoxdur'],1),
('riy11-arasdirma#24','riy-11-arasdirma',3,3,'f(x) = x² − 2x + 3 funksiyasının minimum qiymətini tapın.','x = 1-də minimum: f(1) = 1 − 2 + 3 = 2.',array['2-yə bərabərdir','1-ə bərabərdir','3-ə bərabərdir','0-a bərabərdir'],1),
('riy11-arasdirma#25','riy-11-arasdirma',2,3,'Funksiyanın sıfırları qrafikdə nəyi göstərir?','Qrafikin OX oxu ilə kəsişmə nöqtələrini.',array['OX ilə kəsişmələri','OY ilə kəsişməni','Ekstremumları','Asimptotları'],1),
('riy11-arasdirma#26','riy-11-arasdirma',2,3,'Monoton funksiya hansı funksiyadır?','Bütün aralıqda yalnız artan və ya yalnız azalan funksiya.',array['Yalnız artan və ya yalnız azalan','Gah artan, gah azalan','Sabit yalnız','Dövri'],1),
('riy11-arasdirma#27','riy-11-arasdirma',3,3,'İkitərtibli törəmə hərəkət məsələsində nəyi verir?','Yolun ikinci törəməsi təcildir.',array['Təcili','Sürəti','Yolu','İmpulsu'],1),
('riy11-arasdirma#28','riy-11-arasdirma',2,3,'fʹ(x) > 0 aralığında qrafik hansı istiqamətdə gedir?','Qrafik yuxarı qalxır.',array['Yuxarı qalxır','Aşağı enir','Üfüqidir','Şaquli düşür'],1),
('riy11-arasdirma#29','riy-11-arasdirma',3,3,'Çəpərlə düzbucaqlı sahə ayırma məsələsində maksimum sahə hansı halda alınır?','Tərəflər optimal seçildikdə - kvadrata yaxın olduqda.',array['Kvadrata yaxın formada','Ən dar formada','Ən uzun formada','Fərq etmir'],1),
('riy11-arasdirma#30','riy-11-arasdirma',3,3,'f(x) = x⁴ funksiyasının x = 0 nöqtəsində nəyi var?','x = 0-da minimum var.',array['Minimumu','Maksimumu','Kəsilməsi','Asimptotu'],1),
('riy11-arasdirma#31','riy-11-arasdirma',3,3,'Qrafikin əyilmə (döngə) nöqtəsi hansı törəmə ilə tapılır?','İkinci törəmənin sıfırları ilə tapılır.',array['İkinci törəmə ilə','Birinci törəmə ilə yalnız','İnteqralla','Tapılmır'],1),
('riy11-arasdirma#32','riy-11-arasdirma',2,3,'Ən az material sərfi ilə ən böyük tutum məsələsi harada tətbiq olunur?','Qablaşdırma istehsalında tətbiq olunur.',array['Qablaşdırma istehsalında','Yalnız şeirdə','Yalnız musiqidə','Tətbiq olunmur'],1),
('riy11-arasdirma#33','riy-11-arasdirma',3,3,'f(x) funksiyası üçün fʹ(a) = 0 və fʺ(a) > 0 olduqda a nöqtəsi nədir?','İkinci törəmə müsbətdirsə - minimumdur.',array['Minimum nöqtəsi','Maksimum nöqtəsi','Kəsilmə nöqtəsi','Sıfır deyil'],1),
('riy11-arasdirma#34','riy-11-arasdirma',3,3,'Populyasiyanın artım qrafikinin ən dik yeri nəyi bildirir?','Artım sürətinin (törəmənin) maksimumunu.',array['Artım sürətinin maksimumunu','Populyasiyanın azaldığını','Qrafikin səhvini','Heç nəyi'],1),
('riy11-arasdirma#35','riy-11-arasdirma',2,3,'y = x² − 4 funksiyasının sıfırlarını tapın.','x² = 4, x = ±2.',array['x = ±2','x = 4','x = ±4','x = 2 yalnız'],1),
('riy11-arasdirma#36','riy-11-arasdirma',3,3,'Funksiyanın qiymətlər çoxluğunu araşdırmada nə kömək edir?','Ekstremum qiymətləri və davranış sərhədləri.',array['Ekstremumlar və sərhəd davranışı','Yalnız rənglər','Yalnız cədvəl','Heç nə'],1),
('riy11-arasdirma#37','riy-11-arasdirma',3,3,'Törəmənin işarə dəyişmədiyi böhran nöqtəsində nə olur?','Ekstremum olmur - funksiya monotonluğunu saxlayır.',array['Ekstremum olmur','Mütləq maksimum olur','Mütləq minimum olur','Funksiya kəsilir'],1),
('riy11-arasdirma#38','riy-11-arasdirma',3,3,'Silindrik konservin ən az materialla hazırlanması hansı riyazi məsələdir?','Bu, optimallaşdırma məsələsidir.',array['Optimallaşdırma məsələsi','Limit məsələsi yalnız','Ehtimal məsələsi','Kombinatorika'],1),
('riy11-arasdirma#39','riy-11-arasdirma',3,3,'f(x) = 3x² üçün hansı aralıqda funksiya azalandır?','fʹ = 6x < 0: x < 0 aralığında azalandır.',array['x < 0','x > 0','Bütün oxda','Heç yerdə'],1),
('riy11-arasdirma#40','riy-11-arasdirma',1,3,'Araşdırma nəticəsində qurulan qrafik nəyi əyani göstərir?','Funksiyanın bütün əsas xassələrini.',array['Funksiyanın xassələrini','Yalnız bir nöqtəni','Yalnız adını','Kağızın ölçüsünü'],1),
('riy11-inteqral#1','riy-11-inteqral',2,3,'İbtidai funksiya nədir?','Törəməsi verilmiş funksiyaya bərabər olan funksiyadır.',array['Törəməsi verilmiş funksiyaya bərabər funksiya','Ən sadə funksiya','Birinci funksiya','Xətti funksiya'],1),
('riy11-inteqral#2','riy-11-inteqral',2,3,'f(x) = 2x funksiyasının ibtidai funksiyası hansıdır?','(x²)ʹ = 2x olduğundan F(x) = x² + C.',array['x² + C','2x² + C','2 + C','x + C'],1),
('riy11-inteqral#3','riy-11-inteqral',2,3,'Qeyri-müəyyən inteqralda C sabiti nəyi bildirir?','İbtidai funksiyaların sabitə qədər fərqləndiyini.',array['İbtidailərin sabitə qədər fərqini','Səhvi','Sahəni','Dövrü'],1),
('riy11-inteqral#4','riy-11-inteqral',3,3,'∫3x² dx inteqralını tapın.','İbtidai: x³ + C.',array['x³ + C','3x³ + C','6x + C','x² + C'],1),
('riy11-inteqral#5','riy-11-inteqral',2,3,'Müəyyən inteqral həndəsi olaraq nəyi ifadə edir?','Əyri ilə OX oxu arasındakı fiqurun sahəsini.',array['Əyrialtı fiqurun sahəsini','Əyrinin uzunluğunu yalnız','Qrafikin rəngini','Toxunanın əmsalını'],1),
('riy11-inteqral#6','riy-11-inteqral',3,3,'Nyuton-Leybnis düsturu nəyi əlaqələndirir?','Müəyyən inteqralı ibtidai funksiyanın qiymətləri ilə.',array['İnteqralı ibtidai ilə','Törəməni limitlə yalnız','Sahəni perimetrlə','Heç nəyi'],1),
('riy11-inteqral#7','riy-11-inteqral',3,3,'∫₀² x dx müəyyən inteqralını hesablayın.','F(x) = x²/2; F(2) − F(0) = 2.',array['2','4','1','0'],1),
('riy11-inteqral#8','riy-11-inteqral',3,3,'∫₀¹ 3x² dx inteqralını hesablayın.','F(x) = x³; 1 − 0 = 1.',array['1-ə bərabərdir','3-ə bərabərdir','0-a bərabərdir','2-yə bərabərdir'],1),
('riy11-inteqral#9','riy-11-inteqral',2,3,'Sabitin inteqralı ∫a dx nəyə bərabərdir?','∫a dx = ax + C.',array['ax + C','a + C','a²x','x + C'],1),
('riy11-inteqral#10','riy-11-inteqral',2,3,'İnteqrallama ilə diferensiallama bir-birinə görə hansı əməllərdir?','Qarşılıqlı tərs əməllərdir.',array['Qarşılıqlı tərs','Eyni əməl','Əlaqəsiz','Yalnız oxşar'],1),
('riy11-inteqral#11','riy-11-inteqral',2,3,'Cəmin inteqralı hansı qaydaya tabedir?','İnteqralların cəminə bərabərdir.',array['İnteqralların cəminə bərabərdir','Hasilə bərabərdir','Fərqə bərabərdir həmişə','Qayda yoxdur'],1),
('riy11-inteqral#12','riy-11-inteqral',3,3,'∫₀¹ 2x dx inteqralı hansı fiqurun sahəsini verir?','y = 2x xətti altındakı üçbucağın sahəsini (= 1).',array['Üçbucağın sahəsini','Kvadratın sahəsini','Dairənin sahəsini','Trapesiyanın perimetrini'],1),
('riy11-inteqral#13','riy-11-inteqral',2,3,'Müəyyən inteqralın aşağı və yuxarı sərhədləri nəyi göstərir?','İnteqrallama aralığının uclarını.',array['İnteqrallama aralığını','Funksiyanın qiymətlərini','Qrafikin rəngini','Cədvəlin ölçüsünü'],1),
('riy11-inteqral#14','riy-11-inteqral',3,3,'∫₁³ 2 dx inteqralını hesablayın.','2x: 6 − 2 = 4.',array['4','2','6','8'],1),
('riy11-inteqral#15','riy-11-inteqral',3,3,'İki əyri arasındakı sahə necə tapılır?','Üst funksiyadan alt funksiyanın fərqinin inteqralı ilə.',array['Fərqin inteqralı ilə','Cəmin inteqralı ilə','Hasilin inteqralı ilə','Tapılmır'],1),
('riy11-inteqral#16','riy-11-inteqral',3,3,'Fırlanmadan alınan cismin həcmi hansı vasitə ilə hesablanır?','Müəyyən inteqralla hesablanır.',array['Müəyyən inteqralla','Yalnız xətkeşlə','Perimetrlə','Təxminlə yalnız'],1),
('riy11-inteqral#17','riy-11-inteqral',3,3,'∫cos x dx inteqralı hansıdır?','∫cos x dx = sin x + C.',array['sin x + C','−sin x + C','cos x + C','tan x + C'],1),
('riy11-inteqral#18','riy-11-inteqral',3,3,'∫sin x dx inteqralı hansıdır?','∫sin x dx = −cos x + C.',array['−cos x + C','cos x + C','sin x + C','−sin x + C'],1),
('riy11-inteqral#19','riy-11-inteqral',3,3,'Sürət funksiyasının inteqralı nəyi verir?','Sürətin inteqralı gedilən yolu verir.',array['Gedilən yolu','Təcili','Qüvvəni','Kütləni'],1),
('riy11-inteqral#20','riy-11-inteqral',3,3,'F(x) = x² + 5 funksiyası hansı funksiyanın ibtidaisidir?','Fʹ = 2x - deməli f(x) = 2x-in ibtidaisidir.',array['f(x) = 2x','f(x) = x','f(x) = 5','f(x) = x³'],1),
('riy11-inteqral#21','riy-11-inteqral',3,3,'Müəyyən inteqralın qiyməti C sabitindən asılıdırmı?','Fərq alınarkən C ixtisar olunur - asılı deyil.',array['Xeyr, asılı deyil','Bəli, birbaşa asılıdır','Yalnız müsbət C-də','Yalnız mənfi C-də'],1),
('riy11-inteqral#22','riy-11-inteqral',3,3,'∫x³ dx inteqralını tapın.','x⁴/4 + C.',array['x⁴/4 + C','3x² + C','x³ + C','4x⁴ + C'],1),
('riy11-inteqral#23','riy-11-inteqral',3,3,'İnteqralın xassəsinə görə ∫ₐᵃ f(x) dx nəyə bərabərdir?','Sərhədlər üst-üstə düşdükdə inteqral sıfırdır.',array['Sıfra','Birə','f(a)-ya','Sonsuzluğa'],1),
('riy11-inteqral#24','riy-11-inteqral',3,3,'İnteqralın sərhədlərinin yerini dəyişdikdə nə baş verir?','İnteqralın işarəsi dəyişir.',array['İşarəsi dəyişir','Qiyməti ikiqat olur','Dəyişmir','Sıfırlanır'],1),
('riy11-inteqral#25','riy-11-inteqral',2,3,'Əyrixətli trapesiya nədir?','Əyri, OX oxu və iki şaquli xətlə hüdudlanan fiqurdur.',array['Əyri ilə OX arasındakı hüdudlu fiqur','Adi trapesiya','Dairə hissəsi','Üçbucaq'],1),
('riy11-inteqral#26','riy-11-inteqral',3,3,'∫₀¹ (2x + 1) dx inteqralını hesablayın.','x² + x: (1 + 1) − 0 = 2.',array['İnteqral 2-dir','İnteqral 3-dür','İnteqral 1-dir','İnteqral 4-dür'],1),
('riy11-inteqral#27','riy-11-inteqral',2,3,'İnteqral hesabının yaradıcılarından biri kimdir?','Nyuton və Leybnis inteqral hesabını inkişaf etdirmişlər.',array['Leybnis','Pifaqor','Evklid','Herodot'],1),
('riy11-inteqral#28','riy-11-inteqral',2,3,'Sabit vuruq inteqral işarəsindən çıxarıla bilərmi?','Bəli, ∫c·f dx = c∫f dx.',array['Bəli, çıxarılır','Xeyr, qadağandır','Yalnız mənfi olduqda','Yalnız tam ədəddirsə'],1),
('riy11-inteqral#29','riy-11-inteqral',3,3,'Mənfi qiymətli funksiyanın inteqralı sahə ilə necə bağlıdır?','İnteqral mənfi çıxır - sahənin əks işarəlisidir.',array['Sahənin əks işarəlisidir','Sahəyə bərabərdir birbaşa','Əlaqəsizdir','Həmişə sıfırdır'],1),
('riy11-inteqral#30','riy-11-inteqral',3,3,'∫eˣ dx inteqralı nəyə bərabərdir?','∫eˣ dx = eˣ + C.',array['eˣ + C','xeˣ + C','eˣ⁺¹','ln x + C'],1),
('riy11-inteqral#31','riy-11-inteqral',3,3,'Su axınının sərfindən ümumi həcmi tapmaq üçün nə edilir?','Sərf funksiyası zamana görə inteqrallanır.',array['Sərf inteqrallanır','Sərf diferensiallanır','Sərf loqarifmlanır','Heç nə'],1),
('riy11-inteqral#32','riy-11-inteqral',3,3,'∫(1/x) dx inteqralı hansıdır (x > 0)?','∫dx/x = ln x + C.',array['ln x + C','1/x² + C','x + C','eˣ + C'],1),
('riy11-inteqral#33','riy-11-inteqral',3,3,'y = x² əyrisi altında [0; 3] aralığındakı sahəni tapın.','x³/3: 27/3 − 0 = 9.',array['9','27','3','6'],1),
('riy11-inteqral#34','riy-11-inteqral',3,3,'Fizikada görülən iş qüvvə funksiyasından necə tapılır?','Qüvvənin yola görə inteqralı ilə.',array['Qüvvənin inteqralı ilə','Qüvvənin törəməsi ilə','Qüvvənin kvadratı ilə','Tapılmır'],1),
('riy11-inteqral#35','riy-11-inteqral',3,3,'İnteqralın additivlik xassəsi nə deməkdir?','Aralığı hissələrə bölüb inteqralları toplamaq olar.',array['Aralıq üzrə bölünüb toplana bilər','İnteqral bölünməzdir','Yalnız vurula bilər','Xassə yoxdur'],1),
('riy11-inteqral#36','riy-11-inteqral',3,3,'İqtisadiyyatda ümumi xərc marjinal xərcdən necə alınır?','Marjinal xərc funksiyası inteqrallanır.',array['İnteqrallamaqla','Diferensiallamaqla','Kvadrata yüksəltməklə','Alınmır'],1),
('riy11-inteqral#37','riy-11-inteqral',3,3,'∫₀² 4x dx inteqralını hesablayın.','2x²: 8 − 0 = 8.',array['8','4','16','2'],1),
('riy11-inteqral#38','riy-11-inteqral',2,3,'Qeyri-müəyyən inteqralın nəticəsi nədir?','İbtidai funksiyalar ailəsidir (+C ilə).',array['İbtidai funksiyalar ailəsi','Bir ədəd','Bir nöqtə','Qrafik rəngi'],1),
('riy11-inteqral#39','riy-11-inteqral',2,3,'İnteqral işarəsi hansı hərfdən yaranıb?','Uzadılmış S hərfindən (summa sözündən).',array['Uzadılmış S hərfindən','İ hərfindən','Q hərfindən','Təsadüfi işarədən'],1),
('riy11-inteqral#40','riy-11-inteqral',3,3,'Nyuton-Leybnis düsturuna görə ∫ₐᵇ f dx nəyə bərabərdir?','F(b) − F(a) fərqinə.',array['F(b) − F(a)','F(a) − F(b)','F(b)·F(a)','F(b) + F(a)'],1),
('riy11-statistika#1','riy-11-statistika',2,4,'3, 5, 7, 9 verilənlərinin ədədi ortasını tapın.','(3+5+7+9)/4 = 24/4 = 6.',array['6','5','7','24'],1),
('riy11-statistika#2','riy-11-statistika',2,4,'1, 3, 5, 7, 9 sıralanmış verilənlərinin medianını tapın.','Beş ədədin ortadakısı - üçüncüsü: 5.',array['5','3','7','4'],1),
('riy11-statistika#3','riy-11-statistika',2,4,'2, 2, 3, 5, 8 verilənlərində moda hansıdır?','Ən çox təkrarlanan qiymət 2-dir.',array['Moda 2-dir','Moda 3-dür','Moda 5-dir','Moda 8-dir'],1),
('riy11-statistika#4','riy-11-statistika',2,4,'Verilənlər sırasının kənarlanması (genişliyi) necə tapılır?','Ən böyük qiymətdən ən kiçiyi çıxılır.',array['Ən böyükdən ən kiçiyin fərqi ilə','Qiymətlərin cəmi ilə','Ortanın yarısı ilə','Modanın kvadratı ilə'],1),
('riy11-statistika#5','riy-11-statistika',3,4,'4, 10, 6, 8 verilənlərinin kənarlanmasını tapın.','10 − 4 = 6.',array['6-dır','4-dür','10-dur','2-dir'],1),
('riy11-statistika#6','riy-11-statistika',3,4,'Cüt sayda verilənlərdə median necə tapılır?','Ortadakı iki qiymətin ədədi ortası götürülür.',array['Ortadakı iki qiymətin ortası','Ən böyük qiymət','İlk qiymət','Moda ilə eyni'],1),
('riy11-statistika#7','riy-11-statistika',3,4,'2, 4, 6, 8 verilənlərinin medianını tapın.','(4 + 6)/2 = 5.',array['Median 5-dir','Median 4-dür','Median 6-dır','Median 7-dir'],1),
('riy11-statistika#8','riy-11-statistika',3,4,'Normal paylanmanın qrafiki hansı formadadır?','Simmetrik zəng əyrisi formasındadır.',array['Zəng əyrisi','Düz xətt','Pilləli','Dairə'],1),
('riy11-statistika#9','riy-11-statistika',3,4,'Normal paylanmada orta, median və moda bir-birinə görə necədir?','Simmetriyaya görə üçü üst-üstə düşür.',array['Üst-üstə düşür','Həmişə fərqlidir','Yalnız orta böyükdür','Yalnız moda böyükdür'],1),
('riy11-statistika#10','riy-11-statistika',3,4,'Qutu-qulp diaqramı hansı göstəriciləri əyani göstərir?','Median, kvartillər və kənar qiymətləri göstərir.',array['Median və kvartilləri','Yalnız ortanı','Yalnız cəmi','Funksiya qrafikini'],1),
('riy11-statistika#11','riy-11-statistika',3,4,'Kvartillər verilənləri neçə hissəyə bölür?','Kvartillər sıranı dörd bərabər hissəyə bölür.',array['Dörd hissəyə','İki hissəyə','Üç hissəyə','On hissəyə'],1),
('riy11-statistika#12','riy-11-statistika',2,4,'Təsadüfi hadisə nədir?','Baş verib-verməyəcəyi qabaqcadan məlum olmayan hadisədir.',array['Nəticəsi qabaqcadan bilinməyən hadisə','Mütləq baş verən hadisə','Heç vaxt baş verməyən hadisə','Yalnız oyun'],1),
('riy11-statistika#13','riy-11-statistika',2,4,'«Sabah günəş doğacaq» kimi mütləq baş verən hadisəyə hansı ehtimal uyğundur?','Yəqin hadisə üçün P = 1.',array['P = 1','P = 0','P = 0,5','P = 100'],1),
('riy11-statistika#14','riy-11-statistika',2,4,'Zər atarkən 7 düşməsi hadisəsinin ehtimalı neçədir?','Zərdə 7 üzü yoxdur - hadisə mümkün deyil, P = 0.',array['0-a bərabərdir','1/7-dir','1/6-dır','1-ə bərabərdir'],1),
('riy11-statistika#15','riy-11-statistika',3,4,'P(A) = 0,7 olduqda əks hadisənin ehtimalını tapın.','P(Ā) = 1 − 0,7 = 0,3.',array['0,3','0,7','1,7','0'],1),
('riy11-statistika#16','riy-11-statistika',3,4,'Asılı olmayan iki hadisənin birgə baş vermə ehtimalı necə tapılır?','Ehtimallar vurulur.',array['Ehtimalların hasili ilə','Ehtimalların cəmi ilə hökmən','Fərqi ilə','Tapılmır'],1),
('riy11-statistika#17','riy-11-statistika',3,4,'Uyuşmayan hadisələrdən birinin baş vermə ehtimalı necə tapılır?','Ehtimallar toplanır.',array['Ehtimalların cəmi ilə','Hasili ilə','Nisbəti ilə','Kvadratı ilə'],1),
('riy11-statistika#18','riy-11-statistika',3,4,'P(A) = 0,5 və P(B) = 0,4 olan asılı olmayan hadisələrin birgə ehtimalını tapın.','P = 0,5·0,4 = 0,2.',array['0,2','0,9','0,1','0,45'],1),
('riy11-statistika#19','riy-11-statistika',2,4,'Statistik göstəricilərdən hansı «tipik» qiyməti xarakterizə edir?','Orta, median və moda mərkəzi meyl göstəriciləridir.',array['Orta, median, moda','Yalnız kənarlanma','Yalnız say','Heç biri'],1),
('riy11-statistika#20','riy-11-statistika',3,4,'Verilənlərdə bir qiymət kəskin fərqlənirsə, hansı göstərici daha etibarlıdır?','Kənar qiymətlərə median daha davamlıdır.',array['Median','Ədədi orta','Cəm','Kvadratlar cəmi'],1),
('riy11-statistika#21','riy-11-statistika',2,4,'10, 20, 30 qiymətlərinin ədədi ortasını tapın.','60/3 = 20.',array['20','30','10','60'],1),
('riy11-statistika#22','riy-11-statistika',3,4,'Sinifdə boyların paylanması hansı formaya yaxın olur?','Bioloji göstəricilər adətən normal paylanmaya yaxındır.',array['Normal paylanmaya','Düz xəttə','Sabit qiymətə','Sonsuz artıma'],1),
('riy11-statistika#23','riy-11-statistika',3,4,'Moda hansı verilənlər üçün xüsusilə faydalıdır?','Kateqorik (rəqəmsal olmayan) verilənlər üçün.',array['Kateqorik verilənlər üçün','Yalnız kəsrlər üçün','Heç nə üçün','Yalnız mənfi ədədlər üçün'],1),
('riy11-statistika#24','riy-11-statistika',2,4,'Ehtimal hansı aralıqda qiymətlər alır?','Ehtimal 0 ilə 1 arasındadır.',array['0-dan 1-ə qədər','−1-dən 1-ə','0-dan 100-ə yalnız','İstənilən ədəd'],1),
('riy11-statistika#25','riy-11-statistika',3,4,'Verilənlərin paylanma formasını əyani göstərən qrafik hansıdır?','Histoqram paylanmanı əyani göstərir.',array['Histoqram','Xəritə','Portret','Sxem-plan'],1),
('riy11-statistika#26','riy-11-statistika',3,4,'Qutu-qulp diaqramında qutunun daxilindəki xətt nəyi göstərir?','Xətt medianı göstərir.',array['Medianı','Ortanı','Modanı','Cəmi'],1),
('riy11-statistika#27','riy-11-statistika',3,4,'5, 5, 5, 5 verilənlərinin kənarlanması neçədir?','Bütün qiymətlər eynidir: 5 − 5 = 0.',array['Sıfırdır','5-dir','20-dir','1-dir'],1),
('riy11-statistika#28','riy-11-statistika',2,4,'Bir zərin atılmasında mümkün nəticələrin sayı neçədir?','Zərin 6 üzü var - 6 nəticə.',array['6 nəticə','1 nəticə','12 nəticə','36 nəticə'],1),
('riy11-statistika#29','riy-11-statistika',3,4,'Simmetrik paylanmada verilənlərin yarısı mediandan hansı tərəfdədir?','Yarısı soldadır, yarısı sağda.',array['Yarısı hər tərəfdə','Hamısı sağda','Hamısı solda','Heç biri yanında'],1),
('riy11-statistika#30','riy-11-statistika',2,4,'Statistik təhlilin ilk addımı nədir?','Verilənlərin toplanması və nizamlanmasıdır.',array['Verilənlərin toplanması','Nəticənin elanı','Qrafikin rənglənməsi','Təxmin'],1),
('riy11-statistika#31','riy-11-statistika',3,4,'İki qrupun nəticələrini müqayisə etmək üçün hansı diaqram əlverişlidir?','Yanaşı qurulmuş qutu-qulp diaqramları.',array['Yanaşı qutu-qulp diaqramları','Tək rəqəm','Yazılı mətn yalnız','Xəritə'],1),
('riy11-statistika#32','riy-11-statistika',3,4,'Böyük ədədlər qanununa görə çoxlu təkrar sınaqda nisbi tezlik hansı qiymət ətrafında sabitləşir?','Nisbi tezlik hadisənin nəzəri ehtimalı ətrafında sabitləşir.',array['Nəzəri ehtimal ətrafında','Həmişə 0 ətrafında','Həmişə 1 ətrafında','Sınaq sayı ətrafında'],1),
('riy11-statistika#33','riy-11-statistika',2,4,'«50-50 şans» ifadəsi hansı ehtimala uyğundur?','P = 0,5 ehtimalına.',array['0,5','1','0','5'],1),
('riy11-statistika#34','riy-11-statistika',3,4,'1, 2, 2, 3, 3, 3 verilənlərində moda hansıdır?','3 ən çox (üç dəfə) təkrarlanır.',array['3','2','1','6'],1),
('riy11-statistika#35','riy-11-statistika',3,4,'Orta qiymət kənar (anomal) qiymətə qarşı necə davranır?','Orta kənar qiymətdən güclü təsirlənir.',array['Güclü təsirlənir','Heç təsirlənmir','Yalnız kiçilir','Yalnız böyüyür'],1),
('riy11-statistika#36','riy-11-statistika',2,4,'Sorğu nəticələrinin ümumiləşdirilməsində hansı orta istifadə olunur?','Ədədi orta ən çox istifadə olunan göstəricidir.',array['Ədədi orta','Həndəsi yalnız','Heç biri','Təsadüfi ədəd'],1),
('riy11-statistika#37','riy-11-statistika',2,4,'P(A) + P(Ā) cəmi həmişə neçəyə bərabərdir?','Hadisə ilə əksinin ehtimalları cəmi 1-dir.',array['1-ə','0-a','2-yə','0,5-ə'],1),
('riy11-statistika#38','riy-11-statistika',2,4,'Verilənlərin sayı çox olduqda onlar necə təqdim olunur?','Qruplaşdırılıb tezlik cədvəli və qrafiklərlə.',array['Qruplaşdırılıb cədvəl-qrafiklə','Bir-bir sadalanır yalnız','Gizlədilir','Yalnız yadda saxlanır'],1),
('riy11-statistika#39','riy-11-statistika',3,4,'Normal paylanmada qiymətlərin əksəriyyəti harada cəmlənir?','Ortanın ətrafında cəmlənir.',array['Ortanın ətrafında','Kənarlarda','Yalnız solda','Yalnız sağda'],1),
('riy11-statistika#40','riy-11-statistika',1,4,'Statistika hansı sahələrdə qərar qəbuluna kömək edir?','İqtisadiyyat, tibb, təhsil - demək olar hər sahədə.',array['Demək olar bütün sahələrdə','Heç bir sahədə','Yalnız idmanda','Yalnız oyunlarda'],1),
('riy11-tenlikler#1','riy-11-tenlikler',2,4,'İrrasional tənlik hansı tənlikdir?','Naməlumu kök işarəsi altında olan tənlikdir.',array['Naməlumu kök altında olan','Yalnız xətti','Yalnız kvadrat','Loqarifmli yalnız'],1),
('riy11-tenlikler#2','riy-11-tenlikler',2,4,'√x = 3 tənliyinin kökünü tapın.','Hər iki tərəf kvadrata: x = 9.',array['x = 9','x = 3','x = 6','x = 81'],1),
('riy11-tenlikler#3','riy-11-tenlikler',3,4,'√(x + 1) = 2 tənliyinin kökünü tapın.','x + 1 = 4, x = 3.',array['x = 3','x = 4','x = 1','x = 5'],1),
('riy11-tenlikler#4','riy-11-tenlikler',2,4,'İrrasional tənliyi həll edərkən sonda nə mütləq yoxlanılmalıdır?','Kənar köklərin olub-olmaması yoxlanılır.',array['Kənar köklər','Qrafikin rəngi','Cavabın cütlüyü','Heç nə'],1),
('riy11-tenlikler#5','riy-11-tenlikler',3,4,'√x = −2 tənliyinin həqiqi kökü varmı?','Kvadrat kök mənfi ola bilməz - kök yoxdur.',array['Xeyr, yoxdur','x = 4','x = −4','x = 2'],1),
('riy11-tenlikler#6','riy-11-tenlikler',3,4,'Kvadrata yüksəltmə zamanı kənar kök nə üçün yarana bilər?','Kvadrata yüksəltmə qeyri-ekvivalent çevirmədir.',array['Çevirmə qeyri-ekvivalent olduğu üçün','Səhv hesablamadan yalnız','Kağız çatışmadığı üçün','Yarana bilməz'],1),
('riy11-tenlikler#7','riy-11-tenlikler',3,4,'√(2x) = 4 tənliyinin kökünü tapın.','2x = 16, x = 8.',array['x = 8','x = 4','x = 2','x = 16'],1),
('riy11-tenlikler#8','riy-11-tenlikler',3,4,'Üstlü tənliklər sistemi hansı üsulla həll edilə bilər?','Eyni əsasa gətirib qüvvət üstlərini bərabərləşdirməklə.',array['Eyni əsasa gətirməklə','Yalnız qrafiklə','Təxminlə','Həll olunmur'],1),
('riy11-tenlikler#9','riy-11-tenlikler',3,4,'2ˣ⁺ʸ = 8 və 2ˣ⁻ʸ = 2 sistemindən x-i tapın.','x + y = 3, x − y = 1; x = 2.',array['x = 2','x = 1','x = 3','x = 4'],1),
('riy11-tenlikler#10','riy-11-tenlikler',3,4,'Həmin sistemdə (x + y = 3, x − y = 1) y neçədir?','y = 3 − 2 = 1.',array['y = 1','y = 2','y = 0','y = 3'],1),
('riy11-tenlikler#11','riy-11-tenlikler',2,4,'Loqarifmik tənliyin təyin oblastında hansı şərt olmalıdır?','Loqarifm altındakı ifadə müsbət olmalıdır.',array['Arqument müsbət olmalıdır','Arqument mənfi olmalıdır','Arqument tam olmalıdır','Şərt yoxdur'],1),
('riy11-tenlikler#12','riy-11-tenlikler',3,4,'log₂(x − 1) = 3 tənliyinin kökünü tapın.','x − 1 = 8, x = 9.',array['x = 9','x = 8','x = 7','x = 4'],1),
('riy11-tenlikler#13','riy-11-tenlikler',3,4,'İki loqarifmin bərabərliyindən (eyni əsasla) nə alınır?','Arqumentlərin bərabərliyi alınır.',array['Arqumentlər bərabərdir','Əsaslar fərqlidir','Cavab sıfırdır','Heç nə'],1),
('riy11-tenlikler#14','riy-11-tenlikler',3,4,'√(x²) ifadəsi nəyə bərabərdir?','√(x²) = |x| - modula bərabərdir.',array['|x|','x həmişə','−x həmişə','x²'],1),
('riy11-tenlikler#15','riy-11-tenlikler',3,4,'İrrasional bərabərsizlikdə √f(x) < a (a > 0) hansı şərtlər qoyulur?','f(x) ≥ 0 və f(x) < a² şərtləri birgə.',array['f(x) ≥ 0 və f(x) < a²','Yalnız f(x) < a','f(x) > a² yalnız','Şərt yoxdur'],1),
('riy11-tenlikler#16','riy-11-tenlikler',2,4,'Tənliklər sistemini həll etmək nə deməkdir?','Bütün tənlikləri eyni anda ödəyən qiymətləri tapmaq.',array['Bütün tənlikləri ödəyən qiymətləri tapmaq','Bir tənliyi atmaq','Qrafik çəkmək yalnız','Cavabı təxmin etmək'],1),
('riy11-tenlikler#17','riy-11-tenlikler',3,4,'√x + 2 = 0 tənliyinin həlli barədə nə demək olar?','√x = −2 mümkün deyil - həll yoxdur.',array['Həlli yoxdur','x = 4','x = −4','x = 0'],1),
('riy11-tenlikler#18','riy-11-tenlikler',3,4,'lg x = 2 tənliyinin kökünü tapın.','x = 10² = 100.',array['x = 100','x = 20','x = 2','x = 1000'],1),
('riy11-tenlikler#19','riy-11-tenlikler',2,4,'Üstlü tənlikdə əsaslar bərabər olduqda nə bərabərləşdirilir?','Qüvvət üstləri bərabərləşdirilir.',array['Qüvvət üstləri','Əsaslar yenidən','Sərbəst hədlər','Heç nə'],1),
('riy11-tenlikler#20','riy-11-tenlikler',2,4,'5ˣ = 125 tənliyinin kökünü tapın.','125 = 5³, x = 3.',array['x = 3-dür','x = 5-dir','x = 25-dir','x = 15-dir'],1),
('riy11-tenlikler#21','riy-11-tenlikler',3,4,'√(x − 2) = x − 4 tənliyini kvadrata yüksəltdikdən sonra hansı addım vacibdir?','Tapılan köklərin yoxlanılması vacibdir.',array['Kökləri yoxlamaq','Cavabı ikiqat artırmaq','Tənliyi atmaq','Yenidən kök almaq'],1),
('riy11-tenlikler#22','riy-11-tenlikler',3,4,'Loqarifmik tənliklər sistemində ilk addım adətən nədir?','Loqarifmlərdən qurtulub adi sistemə keçmək.',array['Adi sistemə keçmək','Dərhal qrafik çəkmək','Kökləri atmaq','Sistemi silmək'],1),
('riy11-tenlikler#23','riy-11-tenlikler',3,4,'4ˣ = 64 tənliyinin kökü neçədir?','64 = 4³, x = 3 - yoxla: 4³=64.',array['x = 3 alınır','x = 4 alınır','x = 16 alınır','x = 2 alınır'],1),
('riy11-tenlikler#24','riy-11-tenlikler',3,4,'ODM (təyin oblastı) irrasional tənlikdə nəyi məhdudlaşdırır?','Kök altının mənfi olmamasını tələb edir.',array['Kökaltı ifadənin işarəsini','Cavabın rəngini','Tənliyin uzunluğunu','Heç nəyi'],1),
('riy11-tenlikler#25','riy-11-tenlikler',2,4,'log₃(x) = log₃(7) bərabərliyindən x-i tapın.','Arqumentlər bərabərdir: x = 7.',array['x = 7','x = 3','x = 21','x = 1'],1),
('riy11-tenlikler#26','riy-11-tenlikler',2,4,'Sistemin həlli olan (x; y) cütü qrafik olaraq nəyi göstərir?','Qrafiklərin kəsişmə nöqtəsini.',array['Kəsişmə nöqtəsini','Qrafikin rəngini','Oxların adını','Heç nəyi'],1),
('riy11-tenlikler#27','riy-11-tenlikler',3,4,'√(3x + 1) = 4 tənliyinin kökünü tapın.','3x + 1 = 16, x = 5.',array['x = 5','x = 4','x = 3','x = 15'],1),
('riy11-tenlikler#28','riy-11-tenlikler',3,4,'Üstlü tənliyin hər iki tərəfini loqarifmləmək nə vaxt əlverişlidir?','Əsasları eyniləşdirmək mümkün olmadıqda.',array['Əsaslar eyniləşməyəndə','Həmişə qadağandır','Yalnız qrafik olduqda','Heç vaxt'],1),
('riy11-tenlikler#29','riy-11-tenlikler',3,4,'İrrasional tənliyin qrafik həlli necə aparılır?','Tərəflərin qrafiklərinin kəsişməsi tapılır.',array['Qrafiklərin kəsişməsi ilə','Yalnız cədvəllə','Yalnız kalkulyatorla','Aparılmır'],1),
('riy11-tenlikler#30','riy-11-tenlikler',3,4,'Loqarifmik tənlikdə tapılan kök arqumenti mənfi edirsə, o kök necə adlanır?','Belə kök kənar kökdür və atılır.',array['Kənar kök','Əsas kök','İkiqat kök','Yeganə kök'],1),
('riy11-tenlikler#31','riy-11-tenlikler',3,4,'2ˣ = 10 tənliyinin kökü hansı şəkildə yazılır?','x = log₂10.',array['x = log₂10','x = 5','x = lg 2','x = 10/2'],1),
('riy11-tenlikler#32','riy-11-tenlikler',3,4,'Tənliklərin ekvivalentliyi nə deməkdir?','Eyni köklər çoxluğuna malik olmalarıdır.',array['Köklərinin eyniliyi','Uzunluqlarının eyniliyi','Rənglərinin eyniliyi','Heç nə'],1),
('riy11-tenlikler#33','riy-11-tenlikler',2,4,'√x · √x hasili nəyə bərabərdir (x ≥ 0)?','√x·√x = x.',array['x','√x','x²','2√x'],1),
('riy11-tenlikler#34','riy-11-tenlikler',3,4,'İki naməlumlu iki tənlikdən ibarət sistemin neçə həlli ola bilər?','Bir, bir neçə, sonsuz sayda və ya heç olmaya bilər.',array['Müxtəlif: bir, çox və ya heç biri','Həmişə bir','Həmişə iki','Həmişə sonsuz'],1),
('riy11-tenlikler#35','riy-11-tenlikler',2,4,'3ˣ = 1 tənliyinin kökünü tapın.','İstənilən əsasın sıfırıncı qüvvəti 1-dir: x = 0.',array['x = 0','x = 1','x = 3','Kökü yoxdur'],1),
('riy11-tenlikler#36','riy-11-tenlikler',2,4,'İrrasional tənliklər hansı sahələrdə qarşıya çıxır?','Fizika və həndəsə məsələlərində (məsafə, dövr düsturlarında).',array['Fizika və həndəsə məsələlərində','Yalnız tarixdə','Yalnız musiqidə','Heç yerdə'],1),
('riy11-tenlikler#37','riy-11-tenlikler',3,4,'log₂x + log₂(x) = 6 tənliyindən x-i tapın.','2log₂x = 6, log₂x = 3, x = 8.',array['x = 8','x = 6','x = 3','x = 64'],1),
('riy11-tenlikler#38','riy-11-tenlikler',2,4,'Kvadrat köklü ifadənin təyin oblastı üçün şərt hansıdır?','Kökaltı ifadə mənfi olmamalıdır.',array['Kökaltı ≥ 0','Kökaltı > 1','Kökaltı < 0','Şərt yoxdur'],1),
('riy11-tenlikler#39','riy-11-tenlikler',3,4,'Üstlü və loqarifmik tənliklər hansı real prosesləri modelləşdirir?','Artım-azalma proseslərini (faiz, radioaktivlik).',array['Artım və azalma proseslərini','Yalnız həndəsi fiqurları','Yalnız hərəkəti','Heç nəyi'],1),
('riy11-tenlikler#40','riy-11-tenlikler',2,4,'Sistemdə əvəzetmə üsulunun mahiyyəti nədir?','Bir tənlikdən dəyişən tapılıb digərində yerinə yazılır.',array['Dəyişəni tapıb digərində yazmaq','Tənlikləri atmaq','Qrafiki silmək','Cavabı təxmin etmək'],1)
),
ins as (
  insert into public.questions
    (ext_key, owner_type, subject_id, level_id, topic_id, kind,
     body, explanation, difficulty, quarter, status)
  select d.ext, 'platform', s.id, l.id, tp.id, 'single',
         d.body, d.why, d.diff, d.rub, 'published'
    from d
    join public.subjects s on s.slug = 'riyaziyyat'
    join public.programs p on p.slug = 'orta'
    join public.levels   l on l.program_id = p.id and l.code = '11'
    join public.topics   tp on tp.subject_id = s.id and tp.slug = d.topic
  on conflict (ext_key) do update
    set body = excluded.body, explanation = excluded.explanation,
        difficulty = excluded.difficulty, quarter = excluded.quarter,
        topic_id = excluded.topic_id, level_id = excluded.level_id,
        subject_id = excluded.subject_id, status = 'published'
  returning id, ext_key
)
insert into public.question_options (question_id, ord, body, is_correct)
select ins.id, o.ord, o.txt, o.ord = d.correct
  from ins
  join d on d.ext = ins.ext_key,
  lateral unnest(d.opts) with ordinality as o(txt, ord);

do $$
declare n int; k int;
begin
  select count(*) into n from public.questions
   where owner_type = 'platform' and ext_key like 'riy11-%';
  if n <> 400 then
    raise exception 'riy10 suallari: 400 gozlenilirdi, % tapildi', n;
  end if;
  select count(*) into k from public.questions q
   where q.ext_key like 'riy11-%'
     and ((select count(*) from public.question_options o
            where o.question_id = q.id) <> 4
       or (select count(*) from public.question_options o
            where o.question_id = q.id and o.is_correct) <> 1);
  if k > 0 then
    raise exception '% sualda variant qurulusu sehvdir', k;
  end if;
  select count(distinct topic_id) into k from public.questions
   where ext_key like 'riy11-%';
  if k <> 10 then
    raise exception 'movzu sayi 10 deyil: %', k;
  end if;
  raise notice 'Riyaziyyat 11 banki: % sual, 10 movzu.', n;
end $$;
