-- =====================================================================
--  56_bank_edebiyyat11.sql : EDEBIYYAT 11 BANKI
--
--  BU FAYL ELLE YAZILMIR - tools/edebiyyat11.py yaradir:
--      python3 tools/edebiyyat11.py
--
--  8 movzu x 31 sual = 248.  Her movzuda 4 asan + 15 orta + 12 cetin.
--  ext_key: edeb11-...
--  ON SERT: 55_movzular_edebiyyat11.sql islenmis olmalidir.
--  SONRA:   05_grants.sql yeniden islet.
-- =====================================================================

do $$
begin
  if not exists (select 1 from public.topics t join public.subjects s
      on s.id = t.subject_id
     where s.slug = 'edebiyyat' and t.slug in
           ('edeb-11-tenqidi-realizm', 'edeb-11-nezeriyye')
     having count(*) = 2) then
    raise exception 'ONCE 55_movzular_edebiyyat11.sql isledilmelidir.';
  end if;
end $$;

delete from public.question_options o
 using public.questions q
 where o.question_id = q.id
   and q.owner_type = 'platform'
   and q.ext_key like 'edeb11-%';

with d(ext, fenn, topic, diff, rub, body, why, opts, correct) as (values
('edeb11-tenqidi-realizm#1','edebiyyat','edeb-11-tenqidi-realizm',1,1,'«Molla Nəsrəddin» jurnalının banisi kimdir?','Jurnalı 1906-cı ildə Tiflisdə Cəlil Məmmədquluzadə nəşr etdirmişdir.',array['Cəlil Məmmədquluzadə','Mirzə Ələkbər Sabir','Hüseyn Cavid','Əhməd Cavad'],1),
('edeb11-tenqidi-realizm#2','edebiyyat','edeb-11-tenqidi-realizm',1,1,'Mirzə Ələkbər Sabirin şeirlər toplusu necə adlanır?','Şairin satirik şeirləri «Hophopnamə» adı ilə toplanmışdır.',array['Hophopnamə','Divan','Xəmsə','Hədiqətüs-süəda'],1),
('edeb11-tenqidi-realizm#3','edebiyyat','edeb-11-tenqidi-realizm',1,1,'Cəlil Məmmədquluzadənin «Anamın kitabı» əsəri hansı janrdadır?','«Anamın kitabı» dram (pyes) janrındadır.',array['Dram','Roman','Poema','Hekayə'],1),
('edeb11-tenqidi-realizm#4','edebiyyat','edeb-11-tenqidi-realizm',1,1,'Tənqidi realizm ədəbiyyatın hansı cəhətini önə çəkir?','Cəmiyyətin nöqsanlarını açıb tənqid etməyi önə çəkir.',array['Cəmiyyətin nöqsanlarının tənqidini','Xəyali aləmin təsvirini','Keçmişin tərənnümünü','Təbiətin vəsfini yalnız'],1),
('edeb11-tenqidi-realizm#5','edebiyyat','edeb-11-tenqidi-realizm',2,1,'«Molla Nəsrəddin» jurnalı ilk dəfə harada nəşr olunmuşdur?','Jurnalın ilk nömrələri Tiflisdə çıxmışdır.',array['Tiflisdə','Bakıda','Gəncədə','İrəvanda'],1),
('edeb11-tenqidi-realizm#6','edebiyyat','edeb-11-tenqidi-realizm',2,1,'Cəlil Məmmədquluzadə hansı təxəllüslə tanınırdı?','Yazıçı «Molla Nəsrəddin» təxəllüsü ilə də tanınırdı.',array['Molla Nəsrəddin','Hophop','Sabir','Şəhriyar'],1),
('edeb11-tenqidi-realizm#7','edebiyyat','edeb-11-tenqidi-realizm',2,1,'«Anamın kitabı» əsərində üç qardaş hansı üç mədəni yönü təmsil edir?','Rus, İran və Osmanlı təhsili almış qardaşlar üç ayrı yönü təmsil edir.',array['Rus, İran və Osmanlı yönünü','Yalnız Avropa yönünü','Yalnız Şərq yönünü','Heç bir yönü'],1),
('edeb11-tenqidi-realizm#8','edebiyyat','edeb-11-tenqidi-realizm',2,1,'«Anamın kitabı»nda ana obrazı nəyi simvollaşdırır?','Zəhrabəyim obrazı ana dilini və milli birliyi simvollaşdırır.',array['Ana dilini və milli birliyi','Var-dövləti','Xarici təhsili','Şəhər həyatını'],1),
('edeb11-tenqidi-realizm#9','edebiyyat','edeb-11-tenqidi-realizm',2,1,'«Anamın kitabı»nın əsas ideyası nədir?','Millətin parçalanmaması, ana dili və milli birlik ideyasıdır.',array['Milli birlik və ana dili','Var-dövlət yığmaq','Xaricə köçmək','Təhsildən imtina'],1),
('edeb11-tenqidi-realizm#10','edebiyyat','edeb-11-tenqidi-realizm',2,1,'Cəlil Məmmədquluzadənin məşhur hekayələrindən biri hansıdır?','«Poçt qutusu» yazıçının tanınmış hekayələrindəndir.',array['Poçt qutusu','Qızılgül olmayaydı','Şəhidlər','Dəli Kür'],1),
('edeb11-tenqidi-realizm#11','edebiyyat','edeb-11-tenqidi-realizm',2,1,'Cəlil Məmmədquluzadənin «Ölülər» əsəri hansı janrdadır?','«Ölülər» faciəli komediya - tragikomediyadır.',array['Komediya','Poema','Roman','Qəzəl'],1),
('edeb11-tenqidi-realizm#12','edebiyyat','edeb-11-tenqidi-realizm',2,1,'Mirzə Ələkbər Sabir hansı şəhərdə doğulmuşdur?','Sabir 1862-ci ildə Şamaxıda doğulmuşdur.',array['Şamaxıda','Gəncədə','Naxçıvanda','Şuşada'],1),
('edeb11-tenqidi-realizm#13','edebiyyat','edeb-11-tenqidi-realizm',2,1,'Sabirin şeirləri əsasən hansı nəşrdə çap olunurdu?','Şeirlərinin çoxu «Molla Nəsrəddin» jurnalında çıxırdı.',array['Molla Nəsrəddin jurnalında','Əkinçi qəzetində','Kaspi qəzetində','Füyuzat jurnalında'],1),
('edeb11-tenqidi-realizm#14','edebiyyat','edeb-11-tenqidi-realizm',2,1,'Sabirin «Hophop» təxəllüsü nə ilə bağlıdır?','Şair satirik şeirlərini bu təxəllüslə imzalayırdı.',array['Satirik şeirlərinin imzası idi','Doğulduğu kəndin adıdır','Atasının adıdır','Jurnalın adıdır'],1),
('edeb11-tenqidi-realizm#15','edebiyyat','edeb-11-tenqidi-realizm',2,1,'Sabir satirasının əsas hədəfi nə idi?','Cəhalət, mövhumat və geriliyə qarşı yönəlmişdi.',array['Cəhalət və mövhumat','Təbiət gözəllikləri','Məhəbbət mövzusu','Tarixi qəhrəmanlıq'],1),
('edeb11-tenqidi-realizm#16','edebiyyat','edeb-11-tenqidi-realizm',2,1,'«Neylərdin, ilahi?!» şeirində şair kimə müraciət edir?','Şeirdə şair Allaha müraciət formasında cəmiyyəti tənqid edir.',array['Allaha müraciət formasındadır','Şaha müraciət edir','Ordusuna müraciət edir','Uşaqlara müraciət edir'],1),
('edeb11-tenqidi-realizm#17','edebiyyat','edeb-11-tenqidi-realizm',2,1,'Tənqidi realizm cərəyanının Azərbaycanda mərkəzi hansı nəşr idi?','«Molla Nəsrəddin» jurnalı cərəyanın mərkəzi idi.',array['Molla Nəsrəddin','Füyuzat','Əkinçi','Ziya'],1),
('edeb11-tenqidi-realizm#18','edebiyyat','edeb-11-tenqidi-realizm',2,1,'Satira nədir?','Nöqsanları kəskin gülüş və istehza ilə tənqid edən bədii üsuldur.',array['Nöqsanları gülüşlə tənqid edən üsul','Təbiəti vəsf edən janr','Tarixi salnamə növü','Nəsr şəkli'],1),
('edeb11-tenqidi-realizm#19','edebiyyat','edeb-11-tenqidi-realizm',2,1,'Cəlil Məmmədquluzadə və Sabirin yaradıcılığındakı ortaq cəhət nədir?','Hər ikisi cəmiyyətin gerilik və cəhalətini satira ilə tənqid edirdi.',array['Cəhaləti satira ilə tənqid etməsi','Romantik xəyal aləmi','Tarixi mövzulara üstünlük','Təbiət lirikası'],1),
('edeb11-tenqidi-realizm#20','edebiyyat','edeb-11-tenqidi-realizm',3,1,'Tənqidi realizm dövrünə aid «əsər - müəllif» cütlüyü hansı düzgündür?','«Anamın kitabı» Məmmədquluzadənin, «Hophopnamə» Sabirin, «İblis» Cavidindir.',array['Anamın kitabı - C.Məmmədquluzadə','Hophopnamə - Hüseyn Cavid','İblis - Mirzə Ələkbər Sabir','Ölülər - Əhməd Cavad'],1),
('edeb11-tenqidi-realizm#21','edebiyyat','edeb-11-tenqidi-realizm',3,1,'Hadisələri ardıcıllıqla düzün: 1 - «Anamın kitabı»nın yazılması; 2 - «Əkinçi» qəzetinin nəşri; 3 - «Molla Nəsrəddin» jurnalının nəşrə başlaması.','«Əkinçi» 1875, «Molla Nəsrəddin» 1906, «Anamın kitabı» 1920-ci ilə aiddir.',array['2 - 3 - 1','3 - 2 - 1','2 - 1 - 3','1 - 2 - 3'],1),
('edeb11-tenqidi-realizm#22','edebiyyat','edeb-11-tenqidi-realizm',3,1,'«Anamın kitabı» haqqında aşağıdakılardan hansı SƏHVDİR?','Əsər dram janrındadır; roman deyil.',array['Əsər roman janrında yazılmışdır','Əsərdə üç qardaş üç ayrı mədəni yönü təmsil edir','Ana obrazı milli birliyi simvollaşdırır','Müəllifi Cəlil Məmmədquluzadədir'],1),
('edeb11-tenqidi-realizm#23','edebiyyat','edeb-11-tenqidi-realizm',3,1,'«Anamın kitabı»nda bacı obrazının əsərdəki rolu nədir?','Gülbahar ananın vəsiyyətini qoruyan, milli dəyərlərə sadiq obrazdır.',array['Ananın vəsiyyətini qoruyur','Qardaşları bir-birinə qarşı qoyur','Xaricə köçməyi təklif edir','Əsərdə iştirak etmir'],1),
('edeb11-tenqidi-realizm#24','edebiyyat','edeb-11-tenqidi-realizm',3,1,'Aşağıdakı «şəxs - təxəllüs» cütlüklərindən hansı düzgündür?','Sabirin təxəllüsü Hophop, Məmmədquluzadənin isə Molla Nəsrəddin idi.',array['M.Ə.Sabir - Hophop','C.Məmmədquluzadə - Hophop','Hüseyn Cavid - Molla Nəsrəddin','Əhməd Cavad - Sabir'],1),
('edeb11-tenqidi-realizm#25','edebiyyat','edeb-11-tenqidi-realizm',3,1,'Sabirin satirasında «başqasının dili ilə danışma» üsulu nəyə xidmət edir?','Şair tənqid etdiyi adamın dilindən yazır - onun düşüncəsi öz-özünü ifşa edir.',array['Obrazın öz sözü ilə ifşa olunmasına','Şairin fikrini gizlətməyə','Şeirin qafiyəsini asanlaşdırmağa','Mövzunu dəyişməyə'],1),
('edeb11-tenqidi-realizm#26','edebiyyat','edeb-11-tenqidi-realizm',3,1,'Tənqidi realizmlə maarifçi realizmin əsas fərqi nədir?','Maarifçilər maariflə düzəlişə ümid edirdi, tənqidi realistlər sistemin özünü ifşa edirdi.',array['Biri maarifə ümid edir, digəri sistemi ifşa edir','Biri sistemi ifşa edir, digəri maarifə ümid edir','Biri şeirdə, digəri dramda təzahür edir','Maarifçi realizm yalnız dramda olur'],1),
('edeb11-tenqidi-realizm#27','edebiyyat','edeb-11-tenqidi-realizm',3,1,'«Molla Nəsrəddin» jurnalının satirik gücünü artıran vasitə hansı idi?','Mətnlə yanaşı karikaturalar oxucuya birbaşa təsir edirdi.',array['Karikaturalar','Elmi məqalələr','Şəkilsiz elanlar','Xəritələr'],1),
('edeb11-tenqidi-realizm#28','edebiyyat','edeb-11-tenqidi-realizm',3,1,'Cəlil Məmmədquluzadənin «Poçt qutusu» hekayəsində əsas ifşa hədəfi nədir?','Savadsızlıq və cəhalət - Novruzəli məktubu poçt qutusunu tanımadığı üçün itirir.',array['Savadsızlıq və cəhalət','Var-dövlət hərisliyi','Şəhər həyatının çətinliyi','Təbiətin dağıdılması'],1),
('edeb11-tenqidi-realizm#29','edebiyyat','edeb-11-tenqidi-realizm',3,1,'Aşağıdakı «nəşr - il» cütlüklərindən hansı düzgündür?','«Əkinçi» 1875, «Molla Nəsrəddin» 1906-cı ildə nəşrə başlamışdır.',array['Molla Nəsrəddin - 1906','Əkinçi - 1906','Molla Nəsrəddin - 1875','Füyuzat - 1875'],1),
('edeb11-tenqidi-realizm#30','edebiyyat','edeb-11-tenqidi-realizm',3,1,'Sabir yaradıcılığının Azərbaycan şeirinə gətirdiyi yenilik nədir?','Satiranı ictimai mübarizə silahına çevirdi və canlı danışıq dilini şeirə gətirdi.',array['Satiranı ictimai silaha çevirdi','Əruz vəznindən imtina etdi tam','Yalnız məhəbbət lirikası yazdı','Nəsrə keçdi'],1),
('edeb11-tenqidi-realizm#31','edebiyyat','edeb-11-tenqidi-realizm',3,1,'Tənqidi realizm dövrü hansı illəri əhatə edir?','Dövr XIX əsrin 90-cı illərindən 1920-ci ilə qədəri əhatə edir.',array['XIX əsrin sonundan 1920-ci ilədək','XVIII əsrin ortalarından XIX əsrədək','1920-ci ildən 1960-cı ilədək','1960-cı ildən 1990-cı ilədək'],1),
('edeb11-romantizm#1','edebiyyat','edeb-11-romantizm',1,1,'«İblis» faciəsinin müəllifi kimdir?','«İblis» mənzum faciəsi Hüseyn Cavidin qələmindəndir.',array['Hüseyn Cavid','Cəfər Cabbarlı','Səməd Vurğun','Mir Cəlal'],1),
('edeb11-romantizm#2','edebiyyat','edeb-11-romantizm',1,1,'Hüseyn Cavid hansı şəhərdə doğulmuşdur?','Şair 1882-ci ildə Naxçıvanda doğulmuşdur.',array['Naxçıvanda','Şamaxıda','Gəncədə','Şuşada'],1),
('edeb11-romantizm#3','edebiyyat','edeb-11-romantizm',1,1,'Romantizm cərəyanı nəyə üstünlük verir?','Yüksək ideal, güclü hiss və xəyal aləminə üstünlük verir.',array['İdeal və xəyal aləminə','Gündəlik məişət təsvirinə','Statistik faktlara','Elmi sübutlara'],1),
('edeb11-romantizm#4','edebiyyat','edeb-11-romantizm',1,1,'Azərbaycan Xalq Cümhuriyyətinin himninin sözlərinin müəllifi kimdir?','Himnin sözləri Əhməd Cavada məxsusdur.',array['Əhməd Cavad','Hüseyn Cavid','Mirzə Ələkbər Sabir','Səməd Vurğun'],1),
('edeb11-romantizm#5','edebiyyat','edeb-11-romantizm',2,1,'«İblis» əsəri hansı janrdadır?','Əsər mənzum faciədir - şeirlə yazılmış dramdır.',array['Mənzum faciə','Roman','Hekayə','Qəzəl'],1),
('edeb11-romantizm#6','edebiyyat','edeb-11-romantizm',2,1,'«İblis» faciəsinin baş qəhrəmanı kimdir?','Əsərin mərkəzində Arif obrazı dayanır.',array['Arif','Vaqif','Oqtay','Cahandar ağa'],1),
('edeb11-romantizm#7','edebiyyat','edeb-11-romantizm',2,1,'«İblis» əsərində Rəna obrazı kimdir?','Rəna Arifin sevdiyi qızdır.',array['Arifin sevdiyi qız','Arifin anası','Vasifin bacısı deyil, düşməni','İblisin köməkçisi'],1),
('edeb11-romantizm#8','edebiyyat','edeb-11-romantizm',2,1,'«İblis» əsərinin əsas ideyası nədir?','Şər insanın öz içindədir - müharibə və xəyanət insanı iblisləşdirir.',array['Şərin mənbəyi insanın özüdür','Müharibə qaçılmazdır','Var-dövlət xoşbəxtlik gətirir','Təbiət insandan güclüdür'],1),
('edeb11-romantizm#9','edebiyyat','edeb-11-romantizm',2,1,'«İblis» əsəri hansı tarixi şəraitdə yazılmışdır?','Birinci Dünya müharibəsi dövründə - 1918-ci ildə yazılmışdır.',array['Birinci Dünya müharibəsi dövründə','İkinci Dünya müharibəsi dövründə','XIX əsrin əvvəlində','Müstəqillik dövründə'],1),
('edeb11-romantizm#10','edebiyyat','edeb-11-romantizm',2,1,'Hüseyn Cavidin taleyi necə olmuşdur?','1937-ci il repressiyasının qurbanı olmuş, 1941-ci ildə Sibirdə vəfat etmişdir.',array['Repressiya qurbanı olub Sibirdə vəfat etmişdir','Xaricə mühacirət etmişdir','Uzun ömür sürüb Bakıda vəfat etmişdir','Müharibədə həlak olmuşdur'],1),
('edeb11-romantizm#11','edebiyyat','edeb-11-romantizm',2,1,'Hüseyn Cavidin nəşi hansı ildə vətənə gətirilmişdir?','Şairin nəşi 1982-ci ildə Naxçıvana gətirilmişdir.',array['1982','1956','1991','1937'],1),
('edeb11-romantizm#12','edebiyyat','edeb-11-romantizm',2,1,'Hüseyn Cavidin əsərlərindən biri hansıdır?','«Şeyx Sənan» şairin məşhur mənzum faciələrindəndir.',array['Şeyx Sənan','Anamın kitabı','Dəli Kür','Açıq kitab'],1),
('edeb11-romantizm#13','edebiyyat','edeb-11-romantizm',2,1,'Cavid dramaturgiyasının səciyyəvi cəhəti nədir?','Əsərləri mənzumdur və fəlsəfi-romantik məzmun daşıyır.',array['Mənzum və fəlsəfi-romantik olması','Sənədli olması','Yalnız məişət mövzusu','Qısa hekayə forması'],1),
('edeb11-romantizm#14','edebiyyat','edeb-11-romantizm',2,1,'Əhməd Cavadın «Azərbaycan bayrağına» şeirində nə tərənnüm olunur?','Üçrəngli bayraq və müstəqillik ideyası tərənnüm olunur.',array['Üçrəngli bayraq və müstəqillik','Təbiət gözəllikləri','Şəhər həyatı','Elmi kəşflər'],1),
('edeb11-romantizm#15','edebiyyat','edeb-11-romantizm',2,1,'Əhməd Cavadın taleyi necə olmuşdur?','Şair 1937-ci il repressiyasının qurbanı olmuşdur.',array['Repressiya qurbanı olmuşdur','Mühacirətdə yaşamışdır','Müharibədə həlak olmuşdur','Uzun ömür sürmüşdür'],1),
('edeb11-romantizm#16','edebiyyat','edeb-11-romantizm',2,1,'Romantizm cərəyanının Azərbaycanda əsas nümayəndələri kimlərdir?','Hüseyn Cavid, Əhməd Cavad, Məhəmməd Hadi romantizmin nümayəndələridir.',array['Cavid, Ə.Cavad, M.Hadi','Sabir, Məmmədquluzadə, Ə.Haqverdiyev','Mir Cəlal, İ.Şıxlı, Anar','Vaqif, Zakir, Nəbati'],1),
('edeb11-romantizm#17','edebiyyat','edeb-11-romantizm',2,1,'Romantiklərin əsas dayaq nəşri hansı idi?','«Füyuzat» jurnalı romantik ədəbiyyatın mərkəzi sayılırdı.',array['Füyuzat','Molla Nəsrəddin','Əkinçi','Kaspi'],1),
('edeb11-romantizm#18','edebiyyat','edeb-11-romantizm',2,1,'Cavidin «İblis» əsərinin sonunda hansı sual qoyulur?','İblisin kim olduğu sualı verilir - cavab insanın özündə axtarılır.',array['İblis kimdir sualı','Vətən nədir sualı','Elm nədir sualı','Sərvət nədir sualı'],1),
('edeb11-romantizm#19','edebiyyat','edeb-11-romantizm',2,1,'Romantizmlə tənqidi realizmin fərqi nədədir?','Romantizm ideal və xəyala, tənqidi realizm mövcud gerçəkliyin ifşasına söykənir.',array['Biri ideala, digəri gerçəkliyin ifşasına söykənir','Fərq yoxdur','İkisi də yalnız nəsrdir','İkisi də tarixi mövzu yazır'],1),
('edeb11-romantizm#20','edebiyyat','edeb-11-romantizm',3,1,'Romantizm dövrünə aid «əsər - müəllif» cütlüklərindən hansı düzgündür?','«İblis» və «Şeyx Sənan» Cavidin, «Səsli qız» Əhməd Cavadındır.',array['Şeyx Sənan - Hüseyn Cavid','İblis - Əhməd Cavad','Səsli qız - Hüseyn Cavid','Hophopnamə - Əhməd Cavad'],1),
('edeb11-romantizm#21','edebiyyat','edeb-11-romantizm',3,1,'Hadisələri ardıcıllıqla düzün: 1 - Hüseyn Cavidin nəşinin vətənə gətirilməsi; 2 - «İblis» faciəsinin yazılması; 3 - Cavidin repressiyaya məruz qalması.','«İblis» 1918, repressiya 1937, nəşin gətirilməsi 1982.',array['2 - 3 - 1','3 - 2 - 1','2 - 1 - 3','1 - 2 - 3'],1),
('edeb11-romantizm#22','edebiyyat','edeb-11-romantizm',3,1,'Hüseyn Cavid haqqında aşağıdakılardan hansı SƏHVDİR?','Cavid mühacirətə getməmiş, repressiyaya məruz qalıb Sibirdə vəfat etmişdir.',array['Şair mühacirətdə - Türkiyədə vəfat etmişdir','«İblis» faciəsi mənzum şəkildə yazılmışdır','Şair Naxçıvanda doğulmuşdur','Nəşi 1982-ci ildə vətənə gətirilmişdir'],1),
('edeb11-romantizm#23','edebiyyat','edeb-11-romantizm',3,1,'«İblis» faciəsində müharibə mövzusunun qoyuluşu nə ilə səciyyəvidir?','Müharibə konkret tərəflərin deyil, insandakı şərin nəticəsi kimi göstərilir.',array['Şərin insandan doğduğu göstərilir','Bir tərəf haqlı sayılır','Müharibə tərənnüm olunur','Mövzu ümumiyyətlə yoxdur'],1),
('edeb11-romantizm#24','edebiyyat','edeb-11-romantizm',3,1,'Romantizmin bədii dilində üstünlük təşkil edən vasitə hansıdır?','Rəmz, obrazlı təşbeh və yüksək üslub üstünlük təşkil edir.',array['Rəmz və yüksək üslub','Sənədli dəqiqlik','Rəqəm və statistika','Danışıq şivəsi'],1),
('edeb11-romantizm#25','edebiyyat','edeb-11-romantizm',3,1,'Aşağıdakı «şair - şeir» cütlüklərindən hansı düzgündür?','«Azərbaycan bayrağına» və «Səsli qız» Əhməd Cavadın şeirləridir.',array['Əhməd Cavad - Səsli qız','Hüseyn Cavid - Səsli qız','Sabir - Azərbaycan bayrağına','Səməd Vurğun - Səsli qız'],1),
('edeb11-romantizm#26','edebiyyat','edeb-11-romantizm',3,1,'«Füyuzat» və «Molla Nəsrəddin» nəşrləri arasındakı əsas fərq nədir?','«Füyuzat» romantik-ideal, «Molla Nəsrəddin» satirik-realist mövqedə idi.',array['Biri romantik, digəri satirik idi','İkisi də eyni mövqedə dayanırdı','İkisi də elmi-texniki jurnal idi','İkisi də uşaqlar üçün nəşr olunurdu'],1),
('edeb11-romantizm#27','edebiyyat','edeb-11-romantizm',3,1,'Cavidin qəhrəmanlarının səciyyəvi cəhəti nədir?','Onlar fərdi taleyi deyil, ümumbəşəri ideya uğrunda mübarizəni təmsil edir.',array['Ümumbəşəri ideyanı təmsil edirlər','Yalnız məişət qayğısı çəkirlər','Tarixi sənədə əsaslanırlar','Komik obrazlardır'],1),
('edeb11-romantizm#28','edebiyyat','edeb-11-romantizm',3,1,'Romantizm dövründə yaranan əsərlərdə Şərq mövzusuna müraciət nə ilə izah olunur?','Şərq tarixi və əfsanələri ümumbəşəri ideyaları ifadə üçün zəngin material verirdi.',array['Ümumbəşəri ideya üçün material verirdi','Sənədli mənbə axtarışı ilə bağlı idi','Coğrafi maraqdan doğan meyl idi','Dil öyrənmək məqsədi daşıyırdı'],1),
('edeb11-romantizm#29','edebiyyat','edeb-11-romantizm',3,1,'1937-ci il repressiyası Azərbaycan ədəbiyyatına necə təsir etdi?','Cavid, Müşfiq, Ə.Cavad kimi bir nəsil yazıçı məhv edildi, yaradıcılıq azadlığı boğuldu.',array['Bütöv bir yazıçı nəsli məhv edildi','Ədəbiyyat sürətlə inkişaf etdi','Nəsr janrları xüsusi yüksəliş yaşadı','Ədəbi tənqid müstəqillik qazandı'],1),
('edeb11-romantizm#30','edebiyyat','edeb-11-romantizm',3,1,'Aşağıdakı «şair - doğum yeri» cütlüklərindən hansı düzgündür?','Cavid Naxçıvanda, Sabir Şamaxıda, Vurğun Qazaxda doğulmuşdur.',array['Hüseyn Cavid - Naxçıvan','Mirzə Ələkbər Sabir - Naxçıvan','Hüseyn Cavid - Şamaxı','Səməd Vurğun - Şamaxı'],1),
('edeb11-romantizm#31','edebiyyat','edeb-11-romantizm',3,1,'Romantizmin Azərbaycan ədəbiyyatındakı tarixi rolu nədir?','Milli özünüdərki və istiqlal ideyasını bədii şəkildə formalaşdırdı.',array['Milli özünüdərki formalaşdırdı','Yalnız əyləncə funksiyası daşıdı','Elmi biliyi yaydı','Xalq mahnılarını topladı'],1),
('edeb11-cabbarli-vurgun#1','edebiyyat','edeb-11-cabbarli-vurgun',1,2,'«Sevil» pyesinin müəllifi kimdir?','Pyes Cəfər Cabbarlının qələmindən çıxmışdır.',array['Cəfər Cabbarlı','Səməd Vurğun','Mir Cəlal','Rəsul Rza'],1),
('edeb11-cabbarli-vurgun#2','edebiyyat','edeb-11-cabbarli-vurgun',1,2,'Səməd Vurğunun «Vaqif» əsəri hansı janrdadır?','«Vaqif» mənzum dram janrındadır.',array['Mənzum dram','Roman','Hekayə','Qəzəl'],1),
('edeb11-cabbarli-vurgun#3','edebiyyat','edeb-11-cabbarli-vurgun',1,2,'Səməd Vurğun hansı bölgədə doğulmuşdur?','Şair Qazax bölgəsində, Yuxarı Salahlı kəndində doğulmuşdur.',array['Qazaxda','Şəkidə','Göyçayda','Naxçıvanda'],1),
('edeb11-cabbarli-vurgun#4','edebiyyat','edeb-11-cabbarli-vurgun',1,2,'Cəfər Cabbarlı ədəbiyyatın əsasən hansı sahəsində tanınır?','O, ilk növbədə dramaturq kimi tanınır.',array['Dramaturgiyada','Uşaq şeirində','Ədəbi tərcümədə','Elmi-fantastik nəsrdə'],1),
('edeb11-cabbarli-vurgun#5','edebiyyat','edeb-11-cabbarli-vurgun',2,2,'«Sevil» pyesində əsas ideya hansıdır?','Qadının azadlığı, təhsil alması və şəxsiyyət kimi formalaşmasıdır.',array['Qadın azadlığı və maarifi','Var-dövlət hərisliyi','Hərbi vətənpərvərlik','Kənd təsərrüfatı islahatı'],1),
('edeb11-cabbarli-vurgun#6','edebiyyat','edeb-11-cabbarli-vurgun',2,2,'«Almaz» pyesinin baş qəhrəmanı hansı peşə sahibidir?','Almaz kənddə çalışan gənc müəllimədir.',array['Kənd müəllimi','Həkim','Mühəndis','Tacir'],1),
('edeb11-cabbarli-vurgun#7','edebiyyat','edeb-11-cabbarli-vurgun',2,2,'Cəfər Cabbarlının «Od gəlini» əsərinin mövzusu hansı dövrdən götürülüb?','Əsər ərəb işğalı və ona qarşı azadlıq hərəkatı dövrünə həsr olunub.',array['Ərəb işğalı dövründən','Səfəvilər dövründən','Rusiya imperiyası dövründən','İkinci Dünya müharibəsi dövründən'],1),
('edeb11-cabbarli-vurgun#8','edebiyyat','edeb-11-cabbarli-vurgun',2,2,'«Oqtay Eloğlu» pyesi hansı sahənin problemlərinə həsr olunmuşdur?','Əsər milli teatrın yaranması yolundakı çətinliklərdən bəhs edir.',array['Milli teatrın','Neft sənayesinin','Kənd təsərrüfatının','Tibb elminin'],1),
('edeb11-cabbarli-vurgun#9','edebiyyat','edeb-11-cabbarli-vurgun',2,2,'«1905-ci ildə» pyesində Cəfər Cabbarlı hansı hadisəni qələmə almışdır?','Çarizmin qızışdırdığı milli qırğını və onun əsl səbəblərini.',array['Çarizmin qızışdırdığı milli qırğını','Uzunmüddətli aclıq illərini','Güclü zəlzələ fəlakətini','Dəniz gəmisinin qəzasını'],1),
('edeb11-cabbarli-vurgun#10','edebiyyat','edeb-11-cabbarli-vurgun',2,2,'Səməd Vurğunun «Azərbaycan» şeirinin aparıcı motivi nədir?','Şeir vətənə məhəbbət və vətən həsrəti motivi üzərində qurulub.',array['Vətənə məhəbbət','Elmi kəşflərin təbliği','Şəhər həyatının tənqidi','Dini mövzuların şərhi'],1),
('edeb11-cabbarli-vurgun#11','edebiyyat','edeb-11-cabbarli-vurgun',2,2,'«Vaqif» mənzum dramında Vaqifin qarşısında duran tarixi şəxsiyyət kimdir?','Dramda əsas qarşıdurma Ağa Məhəmməd şah Qacar ilədir.',array['Ağa Məhəmməd şah Qacar','Şah İsmayıl Xətai','Nadir şah Əfşar','Şah Abbas'],1),
('edeb11-cabbarli-vurgun#12','edebiyyat','edeb-11-cabbarli-vurgun',2,2,'«Vaqif» dramında Eldar obrazı kimi təmsil edir?','Eldar xalq içindən çıxmış, haqsızlığa üsyan edən gəncdir.',array['Xalq içindən çıxmış üsyankar gənci','Saray şairini','Xarici ölkənin elçisini','Din xadimini'],1),
('edeb11-cabbarli-vurgun#13','edebiyyat','edeb-11-cabbarli-vurgun',2,2,'Səməd Vurğunun «Fərhad və Şirin» əsəri hansı klassik süjet əsasında yazılıb?','Əsər Nizaminin «Xosrov və Şirin» poemasının süjeti üzərində qurulub.',array['«Xosrov və Şirin» süjeti üzərində','«Koroğlu» dastanı üzərində','«Dədə Qorqud» boyları üzərində','«Leyli və Məcnun» süjeti üzərində'],1),
('edeb11-cabbarli-vurgun#14','edebiyyat','edeb-11-cabbarli-vurgun',2,2,'Səməd Vurğun Azərbaycanda ilk dəfə hansı fəxri ada layiq görülmüşdür?','O, respublikada ilk Xalq şairi adını almışdır.',array['Xalq şairi','Xalq yazıçısı','Xalq artisti','Əməkdar müəllim'],1),
('edeb11-cabbarli-vurgun#15','edebiyyat','edeb-11-cabbarli-vurgun',2,2,'Cəfər Cabbarlı ədəbiyyatdan başqa hansı sahədə fəaliyyət göstərmişdir?','O, kino üçün ssenarilər yazmış, milli kinonun inkişafına təsir etmişdir.',array['Kino ssenarisi yazmışdır','Musiqi bəstələmişdir','Memarlıqla məşğul olmuşdur','Heykəltəraşlıqla məşğul olmuşdur'],1),
('edeb11-cabbarli-vurgun#16','edebiyyat','edeb-11-cabbarli-vurgun',2,2,'«Sevil» pyesində Balaş obrazı nəyi ifadə edir?','Balaş milli kökündən uzaqlaşan, ailəsini utanc sayan ziyalı tipidir.',array['Milli kökündən uzaqlaşan ziyalını','Fədakar kənd müəllimini','Sadə zəhmətkeş kəndlini','Vətənpərvər cəbhə əsgərini'],1),
('edeb11-cabbarli-vurgun#17','edebiyyat','edeb-11-cabbarli-vurgun',2,2,'Aşağıdakılardan hansı Səməd Vurğunun poemasıdır?','«Muğan» Səməd Vurğunun poemasıdır.',array['«Muğan»','«Qızılgül olmayaydı»','«Gülüstan»','«Heydərbabaya salam»'],1),
('edeb11-cabbarli-vurgun#18','edebiyyat','edeb-11-cabbarli-vurgun',2,2,'«Almaz» pyesindəki əsas konflikt nədir?','Yeni maarif ideyası ilə köhnə mühitin qarşıdurmasıdır.',array['Maarif ideyası ilə köhnə mühitin qarşıdurması','İki ailə arasında miras davası','Şəhərlə kəndin ticarət rəqabəti','Ordudakı intizam məsələsi'],1),
('edeb11-cabbarli-vurgun#19','edebiyyat','edeb-11-cabbarli-vurgun',2,2,'«Od gəlini» pyesinin baş qəhrəmanı kimdir?','Əsərin mərkəzində üsyançı Elxan obrazı dayanır.',array['Elxan','Aydın','Oqtay','Balaş'],1),
('edeb11-cabbarli-vurgun#20','edebiyyat','edeb-11-cabbarli-vurgun',3,2,'«Solğun çiçəklər», «Sevil» və «Vaqif» əsərləri yazılma ardıcıllığı ilə necə düzülür? (1 - «Sevil», 2 - «Solğun çiçəklər», 3 - «Vaqif»)','«Solğun çiçəklər» 1917-ci, «Sevil» 1928-ci, «Vaqif» 1937-ci ildə yazılıb.',array['2 - 1 - 3','1 - 2 - 3','3 - 1 - 2','1 - 3 - 2'],1),
('edeb11-cabbarli-vurgun#21','edebiyyat','edeb-11-cabbarli-vurgun',3,2,'Aşağıdakı «əsər - yazılma ili» cütlüklərindən hansı düzgündür?','«Sevil» 1928-ci ildə, «Almaz» isə 1931-ci ildə yazılmışdır.',array['«Sevil» - 1928','«Sevil» - 1931','«Almaz» - 1928','«Od gəlini» - 1931'],1),
('edeb11-cabbarli-vurgun#22','edebiyyat','edeb-11-cabbarli-vurgun',3,2,'«Sevil» pyesində Balaşın ailəsindən uzaqlaşmasının əsas səbəbi nədir?','Balaş yeni mühitə uyğunlaşdıqca arvadını və öz kökünü geridə qalmış saydı.',array['Yeni mühitə uyğunlaşıb ailəsini geri sayması','Sevilin şəhərə köçüb onu tərk etməsi','Atakişinin onu evdən qovması','Gülüşün ailəni ayırmağa çalışması'],1),
('edeb11-cabbarli-vurgun#23','edebiyyat','edeb-11-cabbarli-vurgun',3,2,'Cəfər Cabbarlının əsərləri haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','«Oqtay Eloğlu» teatr mühitindən bəhs edir, neft sənayesindən yox.',array['«Oqtay Eloğlu» neft sənayesinə həsr olunub','«Od gəlini» tarixi mövzuda yazılıb','«Sevil» qadın azadlığından bəhs edir','«Almaz» kənd həyatını əks etdirir'],1),
('edeb11-cabbarli-vurgun#24','edebiyyat','edeb-11-cabbarli-vurgun',3,2,'Cabbarlı və Vurğunun əsərləri üzrə «əsər - janr» cütlüyü hansı düzgündür?','«Vaqif» mənzum dram, «Azərbaycan» şeir, «Muğan» isə poemadır.',array['«Vaqif» - mənzum dram','«Azərbaycan» - poema','«Muğan» - mənzum dram','«Almaz» - poema'],1),
('edeb11-cabbarli-vurgun#25','edebiyyat','edeb-11-cabbarli-vurgun',3,2,'Cabbarlı və Vurğunun əsərləri üzrə «obraz - əsər» cütlüyü hansı düzgündür?','Eldar «Vaqif» dramının, Elxan «Od gəlini»nin, Balaş «Sevil»in obrazıdır.',array['Eldar - «Vaqif»','Elxan - «Sevil»','Balaş - «Od gəlini»','Almaz - «Vaqif»'],1),
('edeb11-cabbarli-vurgun#26','edebiyyat','edeb-11-cabbarli-vurgun',3,2,'Cəfər Cabbarlı ilə Səməd Vurğunun yaradıcılığındakı ortaq cəhət hansıdır?','Hər ikisi dram janrına müraciət etmiş, səhnə əsərləri yazmışdır.',array['Hər ikisi dram janrında əsər yazmışdır','Hər ikisi roman janrında əsər yazmışdır','Hər ikisi sərbəst şeirin banisi sayılır','Hər ikisi Cənubi Azərbaycanda doğulmuşdur'],1),
('edeb11-cabbarli-vurgun#27','edebiyyat','edeb-11-cabbarli-vurgun',3,2,'Səməd Vurğunun üç əsəri yazılma ardıcıllığı ilə necə düzülür? (1 - «Azərbaycan», 2 - «Fərhad və Şirin», 3 - «Komsomol poeması»)','«Komsomol poeması» 1930-cu illərin əvvəlində, «Azərbaycan» 1935-ci, «Fərhad və Şirin» 1941-ci ildə yazılmışdır.',array['3 - 1 - 2','1 - 2 - 3','2 - 3 - 1','1 - 3 - 2'],1),
('edeb11-cabbarli-vurgun#28','edebiyyat','edeb-11-cabbarli-vurgun',3,2,'Səməd Vurğunun əsərləri haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','«Fərhad və Şirin» mənzum dramdır, roman deyil.',array['«Fərhad və Şirin» roman janrındadır','«Vaqif» mənzum dram janrındadır','«Muğan» poema janrındadır','«Azərbaycan» lirik şeirdir'],1),
('edeb11-cabbarli-vurgun#29','edebiyyat','edeb-11-cabbarli-vurgun',3,2,'Cəfər Cabbarlının hansı əsəri «Sevil» ilə eyni ildə yazılmışdır?','«Sevil» və «Od gəlini» 1928-ci ildə, «Almaz» və «1905-ci ildə» 1931-ci, «Yaşar» isə 1932-ci ildə yazılmışdır.',array['«Od gəlini»','«Almaz»','«1905-ci ildə»','«Yaşar»'],1),
('edeb11-cabbarli-vurgun#30','edebiyyat','edeb-11-cabbarli-vurgun',3,2,'«1905-ci ildə» pyesində qırğının əsas səbəbi kimi nə göstərilir?','Pyesdə qırğının kökündə çar hakimiyyətinin xalqları qarşı-qarşıya qoyması dayanır.',array['Çar hakimiyyətinin xalqları qarşı qoyması','Ticarət yollarına nəzarət uğrunda mübarizə','Din xadimlərinin şəxsi ədavəti','Torpaq islahatının gecikdirilməsi'],1),
('edeb11-cabbarli-vurgun#31','edebiyyat','edeb-11-cabbarli-vurgun',3,2,'Aşağıdakı «yazıçı - fəaliyyət sahəsi» cütlüklərindən hansı düzgündür?','Cabbarlı dramaturq və kino ssenaristi, Vurğun isə şair və mənzum dram müəllifidir.',array['Cəfər Cabbarlı - kino ssenaristi','Səməd Vurğun - kino ssenaristi','Cəfər Cabbarlı - ensiklopediya redaktoru','Səməd Vurğun - satirik hekayə müəllifi'],1),
('edeb11-rza-mircelal#1','edebiyyat','edeb-11-rza-mircelal',1,2,'«Bir gəncin manifesti» romanının müəllifi kimdir?','Roman Mir Cəlalın qələmindən çıxmışdır.',array['Mir Cəlal','Rəsul Rza','İlyas Əfəndiyev','İsmayıl Şıxlı'],1),
('edeb11-rza-mircelal#2','edebiyyat','edeb-11-rza-mircelal',1,2,'Rəsul Rza Azərbaycan poeziyasında hansı şeir formasının ustadı sayılır?','O, sərbəst şeirin ən görkəmli ustadlarındandır.',array['Sərbəst şeirin','Qəzəlin','Rübainin','Qəsidənin'],1),
('edeb11-rza-mircelal#3','edebiyyat','edeb-11-rza-mircelal',1,2,'Mir Cəlal hansı ədəbi növdə daha çox tanınır?','Mir Cəlal ilk növbədə nasir - hekayə və roman müəllifidir.',array['Nəsrdə','Dramaturgiyada','Lirik şeirdə','Ədəbi tərcümədə'],1),
('edeb11-rza-mircelal#4','edebiyyat','edeb-11-rza-mircelal',1,2,'Rəsul Rzanın «Rənglər» silsiləsi hansı ədəbi formadadır?','«Rənglər» şeir silsiləsidir.',array['Şeir silsiləsi','Hekayələr toplusu','Dram əsəri','Roman'],1),
('edeb11-rza-mircelal#5','edebiyyat','edeb-11-rza-mircelal',2,2,'Rəsul Rza hansı şəhərdə doğulmuşdur?','Şair 1910-cu ildə Göyçayda doğulmuşdur.',array['Göyçayda','Şəkidə','Qazaxda','Ərdəbildə'],1),
('edeb11-rza-mircelal#6','edebiyyat','edeb-11-rza-mircelal',2,2,'Rəsul Rzanın «Qızılgül olmayaydı» poeması kimin taleyinə həsr olunub?','Poema repressiya qurbanı olmuş şair Mikayıl Müşfiqin taleyindən bəhs edir.',array['Mikayıl Müşfiqin','Hüseyn Cavidin','Əhməd Cavadın','Səməd Vurğunun'],1),
('edeb11-rza-mircelal#7','edebiyyat','edeb-11-rza-mircelal',2,2,'Mir Cəlalın ilk romanı hansıdır?','«Dirilən adam» yazıçının ilk romanıdır.',array['«Dirilən adam»','«Bir gəncin manifesti»','«Açıq kitab»','«Yaşıdlarım»'],1),
('edeb11-rza-mircelal#8','edebiyyat','edeb-11-rza-mircelal',2,2,'Mir Cəlal hansı klassik şairin sənətkarlığına dair monoqrafiya yazmışdır?','Onun «Füzuli sənətkarlığı» monoqrafiyası ədəbiyyatşünaslıqda mühüm yer tutur.',array['Füzulinin','Nizaminin','Nəsiminin','Xətainin'],1),
('edeb11-rza-mircelal#9','edebiyyat','edeb-11-rza-mircelal',2,2,'«Bir gəncin manifesti» romanının baş qəhrəmanı kimdir?','Romanın mərkəzində Mərdan obrazı dayanır.',array['Mərdan','Oqtay','Almaz','Elxan'],1),
('edeb11-rza-mircelal#10','edebiyyat','edeb-11-rza-mircelal',2,2,'Aşağıdakılardan hansı Mir Cəlalın satirik hekayəsidir?','«Anket Anketov» Mir Cəlalın məşhur satirik hekayəsidir.',array['«Anket Anketov»','«Rənglər»','«Gülüstan»','«Dəli Kür»'],1),
('edeb11-rza-mircelal#11','edebiyyat','edeb-11-rza-mircelal',2,2,'Rəsul Rzanın şeirlərində hansı cəhət önə çıxır?','Fəlsəfi düşüncə və qeyri-adi obrazlılıq onun şeirinin əsas cəhətidir.',array['Fəlsəfi düşüncə və obrazlılıq','Nağılvari süjet qurulusu','Dini rəvayətlərin şərhi','Tarixi salnamə üslubu'],1),
('edeb11-rza-mircelal#12','edebiyyat','edeb-11-rza-mircelal',2,2,'Rəsul Rza uzun müddət hansı böyük nəşrin rəhbəri olmuşdur?','O, Azərbaycan Sovet Ensiklopediyasına baş redaktor olmuşdur.',array['Azərbaycan Sovet Ensiklopediyasının','Dövlət Arxivinin','Milli Kitabxananın','Dilçilik İnstitutunun'],1),
('edeb11-rza-mircelal#13','edebiyyat','edeb-11-rza-mircelal',2,2,'«Bir gəncin manifesti» romanı hansı dövrün həyatını əks etdirir?','Roman XX əsrin əvvəllərindəki ictimai həyatı canlandırır.',array['XX əsrin əvvəllərini','XV əsri','XIX əsrin ortalarını','İkinci Dünya müharibəsi illərini'],1),
('edeb11-rza-mircelal#14','edebiyyat','edeb-11-rza-mircelal',2,2,'Rəsul Rzanın «Rənglər» silsiləsində hər şeir nə üzərində qurulur?','Hər şeir bir rəngin doğurduğu assosiasiya və düşüncə üzərində qurulur.',array['Bir rəngin doğurduğu assosiasiya','Bir tarixi hadisənin təsviri','Bir nağıl süjeti','Bir xalq mahnısının motivi'],1),
('edeb11-rza-mircelal#15','edebiyyat','edeb-11-rza-mircelal',2,2,'Mir Cəlalın hekayələrində aparıcı bədii vasitə hansıdır?','Yumor və satira onun hekayələrinin aparıcı vasitəsidir.',array['Yumor və satira','Mübaliğəli qəhrəmanlıq','Mistik təsvir','Quru elmi şərh'],1),
('edeb11-rza-mircelal#16','edebiyyat','edeb-11-rza-mircelal',2,2,'Rəsul Rzanın həyat yoldaşı olan tanınmış şairə kimdir?','Şairin həyat yoldaşı Nigar Rəfibəyli olmuşdur.',array['Nigar Rəfibəyli','Mirvarid Dilbazi','Xurşidbanu Natəvan','Mədinə Gülgün'],1),
('edeb11-rza-mircelal#17','edebiyyat','edeb-11-rza-mircelal',2,2,'Mir Cəlal harada anadan olmuşdur?','Yazıçı Cənubi Azərbaycanın Ərdəbil bölgəsində doğulmuşdur.',array['Ərdəbildə','Gəncədə','Şəkidə','Bakıda'],1),
('edeb11-rza-mircelal#18','edebiyyat','edeb-11-rza-mircelal',2,2,'«Bir gəncin manifesti» romanında qabardılan əsas ictimai problem nədir?','Sosial ədalətsizlik və yoxsul ailənin faciəsi ön plandadır.',array['Sosial ədalətsizlik və yoxsulluq','Elmi kəşf uğrunda mübarizə','Dəniz səyahəti macərası','Şəhərsalma problemləri'],1),
('edeb11-rza-mircelal#19','edebiyyat','edeb-11-rza-mircelal',2,2,'Rəsul Rzanın oğlu olan tanınmış yazıçı kimdir?','Yazıçı Anar Rəsul Rza ilə Nigar Rəfibəylinin oğludur.',array['Anar','Elçin','Sabir Əhmədli','Çingiz Hüseynov'],1),
('edeb11-rza-mircelal#20','edebiyyat','edeb-11-rza-mircelal',3,2,'Mir Cəlalın üç əsəri yazılma ardıcıllığı ilə necə düzülür? (1 - «Dirilən adam», 2 - «Yaşıdlarım», 3 - «Bir gəncin manifesti»)','«Dirilən adam» 1935-ci, «Bir gəncin manifesti» 1939-cu, «Yaşıdlarım» isə 1940-cı illərin ortalarında yazılmışdır.',array['1 - 3 - 2','1 - 2 - 3','3 - 1 - 2','2 - 1 - 3'],1),
('edeb11-rza-mircelal#21','edebiyyat','edeb-11-rza-mircelal',3,2,'Rəsul Rza və Mir Cəlala aid «əsər - müəllif» cütlüyü hansı düzgündür?','«Rənglər» Rəsul Rzanın, «Açıq kitab» isə Mir Cəlalın əsəridir.',array['«Rənglər» - Rəsul Rza','«Rənglər» - Mir Cəlal','«Açıq kitab» - Rəsul Rza','«Qızılgül olmayaydı» - Mir Cəlal'],1),
('edeb11-rza-mircelal#22','edebiyyat','edeb-11-rza-mircelal',3,2,'Rəsul Rza haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Rəsul Rza əruz vəznində deyil, əsasən sərbəst şeirdə yazmışdır.',array['Əsasən əruz vəznində yazmışdır','Sərbəst şeirin inkişafında rol oynamışdır','«Rənglər» silsiləsi onun qələmindəndir','«Qızılgül olmayaydı» poeması ona məxsusdur'],1),
('edeb11-rza-mircelal#23','edebiyyat','edeb-11-rza-mircelal',3,2,'Rəsul Rzanın sərbəst şeirə üstünlük verməsinin əsas səbəbi nə idi?','Şair fikri ənənəvi vəzn və qafiyə qəliblərindən azad etmək istəyirdi.',array['Fikri vəzn qəliblərindən azad etmək istəyi','Xalq şeiri formalarını canlandırmaq istəyi','Klassik əruzu bərpa etmək niyyəti','Dram dilinə yaxınlaşmaq cəhdi'],1),
('edeb11-rza-mircelal#24','edebiyyat','edeb-11-rza-mircelal',3,2,'Aşağıdakı «obraz - əsər» cütlüklərindən hansı doğrudur?','Mərdan «Bir gəncin manifesti» romanının obrazıdır.',array['Mərdan - «Bir gəncin manifesti»','Mərdan - «Dirilən adam»','Almaz - «Bir gəncin manifesti»','Elxan - «Dirilən adam»'],1),
('edeb11-rza-mircelal#25','edebiyyat','edeb-11-rza-mircelal',3,2,'Rəsul Rza ilə Mir Cəlalın yaradıcılığını fərqləndirən əsas cəhət hansıdır?','Rəsul Rza poeziyada, Mir Cəlal isə nəsrdə yazmışdır.',array['Biri poeziyada, digəri nəsrdə yazmışdır','Biri nəsrdə, digəri dramda yazmışdır','Biri tərcümədə, digəri tənqiddə çalışmışdır','Biri uşaq ədəbiyyatında, digəri publisistikada işləmişdir'],1),
('edeb11-rza-mircelal#26','edebiyyat','edeb-11-rza-mircelal',3,2,'Mir Cəlal haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Mir Cəlal mənzum dram yazmamışdır; o, nasir və ədəbiyyatşünas idi.',array['Mənzum dram müəllifidir','«Dirilən adam» onun romanıdır','Füzuli sənətkarlığını araşdırmışdır','Satirik hekayələr müəllifidir'],1),
('edeb11-rza-mircelal#27','edebiyyat','edeb-11-rza-mircelal',3,2,'Mir Cəlalın «Dirilən adam» və «Bir gəncin manifesti» romanları arasında neçə il fərq var?','«Dirilən adam» 1935-ci, «Bir gəncin manifesti» 1939-cu ildə yazılıb.',array['4 il','2 il','7 il','11 il'],1),
('edeb11-rza-mircelal#28','edebiyyat','edeb-11-rza-mircelal',3,2,'Aşağıdakı «şəxs - fəaliyyət» cütlüklərindən hansı düzgündür?','Nigar Rəfibəyli şairə, Anar isə nasir və dramaturqdur.',array['Nigar Rəfibəyli - şairə','Nigar Rəfibəyli - dramaturq','Anar - Xalq şairi','Mir Cəlal - ensiklopediya redaktoru'],1),
('edeb11-rza-mircelal#29','edebiyyat','edeb-11-rza-mircelal',3,2,'«Qızılgül olmayaydı» poemasının yaranmasına səbəb olan hadisə hansıdır?','Poema Mikayıl Müşfiqin repressiya qurbanı olması faciəsi üzərində qurulub.',array['Mikayıl Müşfiqin repressiya qurbanı olması','Hüseyn Cavidin nəşinin vətənə gətirilməsi','Səməd Vurğunun Xalq şairi seçilməsi','Əhməd Cavadın himn mətnini yazması'],1),
('edeb11-rza-mircelal#30','edebiyyat','edeb-11-rza-mircelal',3,2,'Mir Cəlal və Rəsul Rzanın əsərləri üzrə «əsər - janr» cütlüyü hansı doğrudur?','«Bir gəncin manifesti» roman, «Anket Anketov» hekayə, «Rənglər» isə şeir silsiləsidir.',array['«Bir gəncin manifesti» - roman','«Anket Anketov» - roman','«Rənglər» - poema','«Dirilən adam» - hekayə'],1),
('edeb11-rza-mircelal#31','edebiyyat','edeb-11-rza-mircelal',3,2,'Mir Cəlal və Rəsul Rzanın doğulduğu yerlər haqqında hansı fikir doğrudur?','Mir Cəlal Ərdəbildə, Rəsul Rza isə Göyçayda doğulmuşdur.',array['Mir Cəlal Ərdəbildə, Rəsul Rza Göyçayda','Mir Cəlal Göyçayda, Rəsul Rza Ərdəbildə','Mir Cəlal Bakıda, Rəsul Rza Ərdəbildə','Mir Cəlal Göyçayda, Rəsul Rza Bakıda'],1),
('edeb11-ozunuderk#1','edebiyyat','edeb-11-ozunuderk',1,3,'«Dəli Kür» romanının müəllifi kimdir?','Roman İsmayıl Şıxlının qələmindən çıxmışdır.',array['İsmayıl Şıxlı','İlyas Əfəndiyev','Mir Cəlal','Rəsul Rza'],1),
('edeb11-ozunuderk#2','edebiyyat','edeb-11-ozunuderk',1,3,'«Söyüdlü arx» əsərinin müəllifi kimdir?','«Söyüdlü arx» İlyas Əfəndiyevin romanıdır.',array['İlyas Əfəndiyev','İsmayıl Şıxlı','Mir Cəlal','Bəxtiyar Vahabzadə'],1),
('edeb11-ozunuderk#3','edebiyyat','edeb-11-ozunuderk',1,3,'«Dəli Kür» romanının baş qəhrəmanı kimdir?','Əsərin mərkəzində Cahandar ağa obrazı dayanır.',array['Cahandar ağa','Şamxal','Əşrəf','Mərdan'],1),
('edeb11-ozunuderk#4','edebiyyat','edeb-11-ozunuderk',1,3,'İsmayıl Şıxlı hansı bölgədə doğulmuşdur?','Yazıçı Qazax rayonunun İkinci Şıxlı kəndində doğulmuşdur.',array['Qazax rayonunda','Şəki rayonunda','Füzuli rayonunda','Göyçay rayonunda'],1),
('edeb11-ozunuderk#5','edebiyyat','edeb-11-ozunuderk',2,3,'İlyas Əfəndiyev Azərbaycan teatrında hansı üslubun banisi sayılır?','O, lirik-psixoloji dram üslubunun əsasını qoymuşdur.',array['Lirik-psixoloji dramın','Satirik komediyanın','Tarixi faciənin','Musiqili komediyanın'],1),
('edeb11-ozunuderk#6','edebiyyat','edeb-11-ozunuderk',2,3,'«Dəli Kür» romanında hadisələr hansı çayın sahilində cərəyan edir?','Roman Kür çayı sahilindəki kənd həyatını təsvir edir.',array['Kür çayının','Araz çayının','Samur çayının','Qanıx çayının'],1),
('edeb11-ozunuderk#7','edebiyyat','edeb-11-ozunuderk',2,3,'«Dəli Kür»də Cahandar ağa obrazı nəyi təmsil edir?','O, dağılmaqda olan patriarxal dünyanın son nümayəndəsidir.',array['Dağılmaqda olan patriarxal dünyanı','Yeni sənaye şəhərini','Xaricdə təhsil almış ziyalını','Din xadimlərinin nüfuzunu'],1),
('edeb11-ozunuderk#8','edebiyyat','edeb-11-ozunuderk',2,3,'«Dəli Kür» romanında Əşrəf obrazı nəyə can atır?','Əşrəf təhsilə və yeni həyat qaydalarına can atır.',array['Təhsilə və yeni həyata','Var-dövlət toplamağa','Hərbi karyeraya','Ticarətlə zənginləşməyə'],1),
('edeb11-ozunuderk#9','edebiyyat','edeb-11-ozunuderk',2,3,'İlyas Əfəndiyevin «Mahnı dağlarda qaldı» əsəri hansı janrdadır?','Əsər dram (pyes) janrındadır.',array['Dram','Roman','Poema','Hekayə'],1),
('edeb11-ozunuderk#10','edebiyyat','edeb-11-ozunuderk',2,3,'İlyas Əfəndiyev hansı tarixi şəxsiyyət haqqında dram yazmışdır?','O, şairə Xurşidbanu Natəvanın həyatına dram həsr etmişdir.',array['Xurşidbanu Natəvan','Molla Pənah Vaqif','Şah İsmayıl Xətai','Nizami Gəncəvi'],1),
('edeb11-ozunuderk#11','edebiyyat','edeb-11-ozunuderk',2,3,'Aşağıdakılardan hansı İlyas Əfəndiyevin romanıdır?','«Körpüsalanlar» İlyas Əfəndiyevin romanıdır.',array['«Körpüsalanlar»','«Dəli Kür»','«Açıq kitab»','«Rənglər»'],1),
('edeb11-ozunuderk#12','edebiyyat','edeb-11-ozunuderk',2,3,'İsmayıl Şıxlının ilk romanı hansıdır?','«Ayrılan yollar» yazıçının ilk romanıdır.',array['«Ayrılan yollar»','«Dəli Kür»','«Ölən dünyam»','«Üçatılan»'],1),
('edeb11-ozunuderk#13','edebiyyat','edeb-11-ozunuderk',2,3,'«Dəli Kür» romanı hansı dövrün hadisələrini əks etdirir?','Roman XX əsrin ilk onilliklərindəki kənd həyatını canlandırır.',array['XX əsrin ilk onilliklərini','XVI əsri','XIX əsrin ortalarını','İkinci Dünya müharibəsi illərini'],1),
('edeb11-ozunuderk#14','edebiyyat','edeb-11-ozunuderk',2,3,'İlyas Əfəndiyevin dramlarında hansı cəhət önə çıxır?','Qəhrəmanın daxili aləminin incə psixoloji təhlili önə çıxır.',array['Qəhrəmanın daxili aləminin təhlili','Kütləvi döyüş səhnələri','Detektiv süjet qurulusu','Fantastik təsvirlər'],1),
('edeb11-ozunuderk#15','edebiyyat','edeb-11-ozunuderk',2,3,'İsmayıl Şıxlının həyatındakı hansı təcrübə əsərlərinə güclü təsir etmişdir?','Yazıçı İkinci Dünya müharibəsində cəbhədə olmuş, bu təcrübə əsərlərinə hopmuşdur.',array['Cəbhədə keçirdiyi illər','Xaricdə təhsil illəri','Dənizçilik təcrübəsi','Diplomatik xidməti'],1),
('edeb11-ozunuderk#16','edebiyyat','edeb-11-ozunuderk',2,3,'«Dəli Kür» romanında Şamxal atası ilə hansı münasibətdədir?','Şamxal ataya qarşı çıxır, onun qaydalarını qəbul etmir.',array['Ataya qarşı çıxan oğuldur','Ataya sözsüz tabe olan oğuldur','Atasını əvəz edən böyük qardaşdır','Ailədən uzaqda böyümüş oğuldur'],1),
('edeb11-ozunuderk#17','edebiyyat','edeb-11-ozunuderk',2,3,'İlyas Əfəndiyev hansı fəxri ada layiq görülmüşdür?','Ona Xalq yazıçısı fəxri adı verilmişdir.',array['Xalq yazıçısı','Xalq şairi','Xalq artisti','Əməkdar həkim'],1),
('edeb11-ozunuderk#18','edebiyyat','edeb-11-ozunuderk',2,3,'İlyas Əfəndiyevin oğlu olan tanınmış yazıçı kimdir?','Yazıçı Elçin İlyas Əfəndiyevin oğludur.',array['Elçin','Anar','Sabir Əhmədli','Əkrəm Əylisli'],1),
('edeb11-ozunuderk#19','edebiyyat','edeb-11-ozunuderk',2,3,'İsmayıl Şıxlının son romanlarından biri hansıdır?','«Ölən dünyam» yazıçının son dövr romanlarındandır.',array['«Ölən dünyam»','«Söyüdlü arx»','«Yaşıdlarım»','«Açıq kitab»'],1),
('edeb11-ozunuderk#20','edebiyyat','edeb-11-ozunuderk',3,3,'Aşağıdakı üç hadisə zaman ardıcıllığı ilə necə düzülür? (1 - «Dəli Kür» romanı, 2 - «Ayrılan yollar» romanı, 3 - İsmayıl Şıxlının doğulması)','İsmayıl Şıxlı 1919-cu ildə doğulub, «Ayrılan yollar» 1950-ci illərin sonunda, «Dəli Kür» isə 1960-cı illərdə nəşr olunub.',array['3 - 2 - 1','1 - 2 - 3','2 - 3 - 1','3 - 1 - 2'],1),
('edeb11-ozunuderk#21','edebiyyat','edeb-11-ozunuderk',3,3,'İ.Əfəndiyev və İ.Şıxlıya aid «əsər - müəllif» cütlüyü hansı doğrudur?','«Dəli Kür» İsmayıl Şıxlının, «Söyüdlü arx» İlyas Əfəndiyevindir.',array['«Dəli Kür» - İsmayıl Şıxlı','«Dəli Kür» - İlyas Əfəndiyev','«Söyüdlü arx» - İsmayıl Şıxlı','«Ölən dünyam» - İlyas Əfəndiyev'],1),
('edeb11-ozunuderk#22','edebiyyat','edeb-11-ozunuderk',3,3,'İlyas Əfəndiyev haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','«Dəli Kür» İsmayıl Şıxlının romanıdır, İlyas Əfəndiyevin deyil.',array['«Dəli Kür» romanının müəllifidir','«Söyüdlü arx» onun romanıdır','Lirik-psixoloji dramlar yazmışdır','Xalq yazıçısı adına layiq görülüb'],1),
('edeb11-ozunuderk#23','edebiyyat','edeb-11-ozunuderk',3,3,'Cahandar ağanın faciəsinin əsas səbəbi nədir?','Dəyişən zamanla köhnə həyat qaydalarının toqquşması onu məhvə aparır.',array['Zamanla köhnə qaydaların toqquşması','Ailəsinin torpaqsız qalması','Uzaq şəhərə köçmək məcburiyyəti','Ticarətdə uğursuzluğa düşməsi'],1),
('edeb11-ozunuderk#24','edebiyyat','edeb-11-ozunuderk',3,3,'«Dəli Kür» üzrə «obraz - əsər» cütlüklərindən hansı düzgündür?','Cahandar ağa «Dəli Kür» romanının obrazıdır.',array['Cahandar ağa - «Dəli Kür»','Cahandar ağa - «Söyüdlü arx»','Mərdan - «Dəli Kür»','Şamxal - «Ayrılan yollar»'],1),
('edeb11-ozunuderk#25','edebiyyat','edeb-11-ozunuderk',3,3,'İlyas Əfəndiyev və İsmayıl Şıxlının yaradıcılığındakı ortaq cəhət hansıdır?','Hər ikisi nəsrdə çalışmış və Xalq yazıçısı adına layiq görülmüşdür.',array['Hər ikisi Xalq yazıçısı adını almışdır','Hər ikisi əsasən poeziyada yazmışdır','Hər ikisi Cənubi Azərbaycanda doğulmuşdur','Hər ikisi ensiklopediya redaktoru olmuşdur'],1),
('edeb11-ozunuderk#26','edebiyyat','edeb-11-ozunuderk',3,3,'«Dəli Kür» romanı haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Romanın hadisələri müharibə illərində deyil, XX əsrin əvvəlində keçir.',array['Hadisələr İkinci Dünya müharibəsindən bəhs edir','Cahandar ağa əsərin mərkəzi obrazıdır','Hadisələr Kür sahilindəki kənddə keçir','Şamxal Cahandar ağanın oğludur'],1),
('edeb11-ozunuderk#27','edebiyyat','edeb-11-ozunuderk',3,3,'İlyas Əfəndiyev ilə İsmayıl Şıxlının doğum illəri arasında neçə il fərq var?','İlyas Əfəndiyev 1914-cü ildə, İsmayıl Şıxlı 1919-cu ildə doğulmuşdur.',array['5 il','2 il','9 il','14 il'],1),
('edeb11-ozunuderk#28','edebiyyat','edeb-11-ozunuderk',3,3,'Aşağıdakı «yazıçı - üslub» cütlüklərindən hansı doğrudur?','Lirik-psixoloji dram İlyas Əfəndiyevin adı ilə bağlıdır.',array['İlyas Əfəndiyev - lirik-psixoloji dram','İsmayıl Şıxlı - lirik-psixoloji dram','İlyas Əfəndiyev - satirik hekayə','İsmayıl Şıxlı - sərbəst şeir'],1),
('edeb11-ozunuderk#29','edebiyyat','edeb-11-ozunuderk',3,3,'Şamxalın atası ilə toqquşmasının kökündə nə dayanır?','Nəsil dəyişməsi və yeni həyat tərzinin köhnə qaydaları sıxışdırmasıdır.',array['Nəsil dəyişməsi və yeni həyat tərzi','Torpaq mülkiyyəti üstündə mübahisə','Qonşu kəndlə ticarət rəqabəti','Şəhərdə təhsil almaq istəyi'],1),
('edeb11-ozunuderk#30','edebiyyat','edeb-11-ozunuderk',3,3,'İsmayıl Şıxlının iki romanı haqqında hansı fikir doğrudur?','«Ayrılan yollar» daha əvvəl, «Dəli Kür» isə sonra yazılmışdır.',array['«Ayrılan yollar» əvvəl, «Dəli Kür» sonra','«Dəli Kür» əvvəl, «Ayrılan yollar» sonra','Hər ikisi eyni ildə yazılıb','Hər ikisi müharibədən əvvəl yazılıb'],1),
('edeb11-ozunuderk#31','edebiyyat','edeb-11-ozunuderk',3,3,'Özünüdərk mövzusu bu iki yazıçının əsərlərində necə təzahür edir?','Milli kökə, keçmişə və adət-ənənəyə yeni gözlə baxmaqla təzahür edir.',array['Milli kökə və keçmişə yeni baxışla','Xarici ölkə həyatının təsviri ilə','Elmi-texniki tərəqqinin tərənnümü ilə','Dini rəvayətlərin bədii şərhi ilə'],1),
('edeb11-istiqlal#1','edebiyyat','edeb-11-istiqlal',1,3,'«Gülüstan» poemasının müəllifi kimdir?','Poema Bəxtiyar Vahabzadənin qələmindən çıxmışdır.',array['Bəxtiyar Vahabzadə','Məmməd Araz','Xəlil Rza Ulutürk','Rəsul Rza'],1),
('edeb11-istiqlal#2','edebiyyat','edeb-11-istiqlal',1,3,'Bəxtiyar Vahabzadə hansı şəhərdə doğulmuşdur?','Şair 1925-ci ildə Şəkidə doğulmuşdur.',array['Şəkidə','Qazaxda','Göyçayda','Naxçıvanda'],1),
('edeb11-istiqlal#3','edebiyyat','edeb-11-istiqlal',1,3,'«Gülüstan» poemasının əsas mövzusu nədir?','Poema xalqın iki yerə bölünməsi faciəsindən bəhs edir.',array['Xalqın iki yerə bölünməsi','Sənaye inqilabı','Dəniz səyahəti','Kənd təsərrüfatı islahatı'],1),
('edeb11-istiqlal#4','edebiyyat','edeb-11-istiqlal',1,3,'Bəxtiyar Vahabzadə hansı fəxri ada layiq görülmüşdür?','Ona Xalq şairi fəxri adı verilmişdir.',array['Xalq şairi','Xalq artisti','Əməkdar müəllim','Əməkdar rəssam'],1),
('edeb11-istiqlal#5','edebiyyat','edeb-11-istiqlal',2,3,'Bəxtiyar Vahabzadənin «Şəhidlər» əsəri hansı hadisəyə həsr olunub?','Əsər 20 Yanvar faciəsinin qurbanlarına həsr olunmuşdur.',array['20 Yanvar faciəsinə','Xocalı soyqırımına','İkinci Dünya müharibəsinə','1937-ci il repressiyasına'],1),
('edeb11-istiqlal#6','edebiyyat','edeb-11-istiqlal',2,3,'«Gülüstan» poemasının yazılması şairə hansı nəticəni gətirdi?','Şair təqib olundu və universitetdəki işindən uzaqlaşdırıldı.',array['Təqib olunub işindən uzaqlaşdırıldı','Dövlət mükafatı aldı','Xaricə səfərə göndərildi','Akademiyaya üzv seçildi'],1),
('edeb11-istiqlal#7','edebiyyat','edeb-11-istiqlal',2,3,'Məmməd Arazın məşhur şeirlərindən biri hansıdır?','«Ayağa dur, Azərbaycan!» Məmməd Arazın məşhur şeiridir.',array['«Ayağa dur, Azərbaycan!»','«Gülüstan»','«Rənglər»','«Heydərbabaya salam»'],1),
('edeb11-istiqlal#8','edebiyyat','edeb-11-istiqlal',2,3,'Xəlil Rza Ulutürk ədəbiyyat tarixinə hansı adla düşmüşdür?','O, istiqlal şairi kimi tanınır.',array['İstiqlal şairi','Uşaq şairi','Satira ustası','Ədəbi tənqidçi'],1),
('edeb11-istiqlal#9','edebiyyat','edeb-11-istiqlal',2,3,'Bəxtiyar Vahabzadənin «Muğam» əsəri hansı janrdadır?','«Muğam» poema janrındadır.',array['Poema','Roman','Hekayə','Komediya'],1),
('edeb11-istiqlal#10','edebiyyat','edeb-11-istiqlal',2,3,'Aşağıdakılardan hansı Bəxtiyar Vahabzadənin dramıdır?','«Vicdan» şairin dram əsəridir.',array['«Vicdan»','«Almaz»','«Sevil»','«Dəli Kür»'],1),
('edeb11-istiqlal#11','edebiyyat','edeb-11-istiqlal',2,3,'İstiqlal ədəbiyyatının əsas ideyası nədir?','Milli azadlıq və dövlət müstəqilliyi ideyasıdır.',array['Milli azadlıq və müstəqillik','Sənaye tərəqqisi','Şəhər həyatının tərənnümü','Elmi kəşflərin təbliği'],1),
('edeb11-istiqlal#12','edebiyyat','edeb-11-istiqlal',2,3,'«Gülüstan» poemasında Araz çayı nəyin nişanına çevrilir?','Araz bölünmüş xalqın ayrılıq nişanına çevrilir.',array['Bölünmüş xalqın ayrılıq nişanının','Bolluq və bərəkətin','Ticarət yolunun','Sərhədsiz dostluğun'],1),
('edeb11-istiqlal#13','edebiyyat','edeb-11-istiqlal',2,3,'Bəxtiyar Vahabzadənin yaradıcılığında hansı mövzu aparıcıdır?','Vətən, ana dili və milli kimlik mövzusu aparıcıdır.',array['Vətən və ana dili','Kosmos və elm','Dəniz macəraları','Şəhər memarlığı'],1),
('edeb11-istiqlal#14','edebiyyat','edeb-11-istiqlal',2,3,'Xəlil Rza Ulutürk 1990-cı ildə hansı hadisə ilə üzləşdi?','O, həbs olunub Moskvada saxlanılmışdır.',array['Həbs olunub Moskvada saxlanıldı','Xaricə mühacirət etdi','Akademiyaya rəhbər seçildi','Ordudan tərxis olundu'],1),
('edeb11-istiqlal#15','edebiyyat','edeb-11-istiqlal',2,3,'Məmməd Araz hansı bölgədə doğulmuşdur?','Şair Naxçıvanın Şahbuz bölgəsində doğulmuşdur.',array['Naxçıvanda','Şəkidə','Lənkəranda','Qubada'],1),
('edeb11-istiqlal#16','edebiyyat','edeb-11-istiqlal',2,3,'Bəxtiyar Vahabzadənin «Şəhidlər» əsəri hansı ildə yazılmışdır?','Əsər 1990-cı ildə, faciədən dərhal sonra yazılmışdır.',array['1990','1988','1993','1995'],1),
('edeb11-istiqlal#17','edebiyyat','edeb-11-istiqlal',2,3,'İstiqlal ədəbiyyatının yüksəliş dövrü hansı illərə təsadüf edir?','Yüksəliş 1980-ci illərin sonu - 1990-cı illərin əvvəlinə düşür.',array['1980-ci illərin sonuna','1930-cu illərə','1950-ci illərə','1960-cı illərin ortasına'],1),
('edeb11-istiqlal#18','edebiyyat','edeb-11-istiqlal',2,3,'Bəxtiyar Vahabzadə ədəbi yaradıcılıqla yanaşı hansı işlə məşğul olmuşdur?','O, uzun illər universitetdə müəllim və ədəbiyyatşünas kimi çalışmışdır.',array['Universitet müəllimi kimi','Həkim kimi','Mühəndis kimi','Diplomat kimi'],1),
('edeb11-istiqlal#19','edebiyyat','edeb-11-istiqlal',2,3,'«Gülüstan» poeması hansı ildə yazılmışdır?','Poema 1959-cu ildə yazılmışdır.',array['1959','1937','1970','1990'],1),
('edeb11-istiqlal#20','edebiyyat','edeb-11-istiqlal',3,3,'Aşağıdakı üç hadisə zaman ardıcıllığı ilə necə düzülür? (1 - Gülüstan müqaviləsi, 2 - «Gülüstan» poeması, 3 - «Şəhidlər» əsəri)','Müqavilə 1813-cü ildə, poema 1959-cu ildə, «Şəhidlər» 1990-cı ildə.',array['1 - 2 - 3','2 - 1 - 3','3 - 2 - 1','2 - 3 - 1'],1),
('edeb11-istiqlal#21','edebiyyat','edeb-11-istiqlal',3,3,'Aşağıdakı «əsər - il» cütlüklərindən hansı düzgündür?','«Şəhidlər» 1990-cı ildə, «Gülüstan» poeması isə 1959-cu ildə yazılıb.',array['«Şəhidlər» - 1990','«Gülüstan» - 1990','«Şəhidlər» - 1959','«Gülüstan» - 1813'],1),
('edeb11-istiqlal#22','edebiyyat','edeb-11-istiqlal',3,3,'Bəxtiyar Vahabzadə haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','«Rənglər» silsiləsi Rəsul Rzaya məxsusdur.',array['«Rənglər» silsiləsinin müəllifidir','«Gülüstan» poemasını yazmışdır','«Vicdan» dramının müəllifidir','Şəkidə doğulmuşdur'],1),
('edeb11-istiqlal#23','edebiyyat','edeb-11-istiqlal',3,3,'«Gülüstan» poemasının hakimiyyət tərəfindən xoş qarşılanmamasının səbəbi nə idi?','Poema xalqın bölünməsini açıq şəkildə xatırladırdı.',array['Xalqın bölünməsini xatırlatması','Dini mövzuya toxunması','Xarici dildə yazılması','Klassik vəznə uyğun gəlməməsi'],1),
('edeb11-istiqlal#24','edebiyyat','edeb-11-istiqlal',3,3,'Aşağıdakı «şair - əsər» cütlüklərindən hansı doğrudur?','«Ayağa dur, Azərbaycan!» Məmməd Arazın şeiridir.',array['Məmməd Araz - «Ayağa dur, Azərbaycan!»','Bəxtiyar Vahabzadə - «Ayağa dur, Azərbaycan!»','Məmməd Araz - «Gülüstan»','Xəlil Rza Ulutürk - «Muğam»'],1),
('edeb11-istiqlal#25','edebiyyat','edeb-11-istiqlal',3,3,'Bəxtiyar Vahabzadə ilə Xəlil Rza Ulutürkün yaradıcılığındakı ortaq cəhət hansıdır?','Hər ikisi milli azadlıq və istiqlal mövzusunda yazmışdır.',array['Hər ikisi milli azadlıq mövzusunda yazmışdır','Hər ikisi satirik hekayə müəllifidir','Hər ikisi eyni şəhərdə doğulmuşdur','Hər ikisi roman janrında çalışmışdır'],1),
('edeb11-istiqlal#26','edebiyyat','edeb-11-istiqlal',3,3,'İstiqlal ədəbiyyatı haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Bu ədəbiyyat XIX əsrdə deyil, XX əsrin sonunda güclənmişdir.',array['Əsasən XIX əsrdə formalaşmışdır','Milli azadlıq ideyasını önə çəkir','20 Yanvar hadisələri onda əks olunub','Bəxtiyar Vahabzadə onun nümayəndəsidir'],1),
('edeb11-istiqlal#27','edebiyyat','edeb-11-istiqlal',3,3,'«Gülüstan» poeması ilə «Şəhidlər» əsərinin yazılması arasında neçə il keçmişdir?','Poema 1959-cu ildə, «Şəhidlər» isə 1990-cı ildə yazılmışdır.',array['31 il','21 il','41 il','11 il'],1),
('edeb11-istiqlal#28','edebiyyat','edeb-11-istiqlal',3,3,'Aşağıdakı «şair - doğulduğu yer» cütlüklərindən hansı düzgündür?','Bəxtiyar Vahabzadə Şəkidə, Məmməd Araz Naxçıvanda doğulmuşdur.',array['Bəxtiyar Vahabzadə - Şəki','Məmməd Araz - Şəki','Bəxtiyar Vahabzadə - Naxçıvan','Xəlil Rza Ulutürk - Şəki'],1),
('edeb11-istiqlal#29','edebiyyat','edeb-11-istiqlal',3,3,'20 Yanvar faciəsinin Azərbaycan poeziyasına təsiri necə oldu?','Şəhidlik və müqavimət mövzusu poeziyada güclə önə çıxdı.',array['Şəhidlik və müqavimət mövzusu önə çıxdı','Məhəbbət lirikası aparıcı mövzuya çevrildi','Tarixi salnamə üslubu üstünlük qazandı','Şeir dili klassik əruza qayıtdı'],1),
('edeb11-istiqlal#30','edebiyyat','edeb-11-istiqlal',3,3,'«Gülüstan» poemasında hansı iki tarixi fakt qarşılaşdırılır?','1813-cü il müqaviləsi və onun doğurduğu ayrılıq qarşılaşdırılır.',array['1813-cü il müqaviləsi və sonrakı ayrılıq','1918-ci il istiqlalı və 1920-ci il işğalı','1937-ci il repressiyası və müharibə illəri','1991-ci il müstəqilliyi və Qarabağ münaqişəsi'],1),
('edeb11-istiqlal#31','edebiyyat','edeb-11-istiqlal',3,3,'İstiqlal ədəbiyyatı üzrə «əsər - janr» cütlüklərindən hansı düzgündür?','«Gülüstan» poema, «Vicdan» dram janrındadır.',array['«Gülüstan» - poema','«Vicdan» - poema','«Muğam» - dram','«Şəhidlər» - roman'],1),
('edeb11-cenub-dunya#1','edebiyyat','edeb-11-cenub-dunya',1,4,'«Heydərbabaya salam» poemasının müəllifi kimdir?','Poemanı Məhəmmədhüseyn Şəhriyar yazmışdır.',array['Məhəmmədhüseyn Şəhriyar','Səməd Behrəngi','Bulud Qaraçorlu Səhənd','Balaş Azəroğlu'],1),
('edeb11-cenub-dunya#2','edebiyyat','edeb-11-cenub-dunya',1,4,'«Hamlet» faciəsinin müəllifi kimdir?','Faciənin müəllifi Uilyam Şekspirdir.',array['Uilyam Şekspir','Onore de Balzak','Ernest Heminquey','Lev Tolstoy'],1),
('edeb11-cenub-dunya#3','edebiyyat','edeb-11-cenub-dunya',1,4,'Səməd Behrənginin ən məşhur nağılı hansıdır?','«Balaca qara balıq» onun ən məşhur nağılıdır.',array['«Balaca qara balıq»','«Qoca və dəniz»','«Ağ gəmi»','«Faust»'],1),
('edeb11-cenub-dunya#4','edebiyyat','edeb-11-cenub-dunya',1,4,'Məhəmmədhüseyn Şəhriyar hansı şəhərdə doğulmuşdur?','Şair Təbrizdə doğulmuşdur.',array['Təbrizdə','Bakıda','Ərdəbildə','Tehranda'],1),
('edeb11-cenub-dunya#5','edebiyyat','edeb-11-cenub-dunya',2,4,'«Heydərbabaya salam» poemasında Heydərbaba nədir?','Heydərbaba Təbriz yaxınlığındakı dağın adıdır.',array['Bir dağın adı','Bir çayın adı','Bir şəhərin adı','Bir kitabın adı'],1),
('edeb11-cenub-dunya#6','edebiyyat','edeb-11-cenub-dunya',2,4,'Məhəmmədhüseyn Şəhriyar hansı iki dildə əsərlər yazmışdır?','Şair həm Azərbaycan, həm də fars dilində yazmışdır.',array['Azərbaycan və fars dillərində','Azərbaycan və rus dillərində','Fars və ərəb dillərində','Türk və ingilis dillərində'],1),
('edeb11-cenub-dunya#7','edebiyyat','edeb-11-cenub-dunya',2,4,'Səməd Behrəngi əsas peşəsinə görə kim idi?','O, kənd məktəblərində çalışan müəllim idi.',array['Müəllim','Həkim','Mühəndis','Hüquqşünas'],1),
('edeb11-cenub-dunya#8','edebiyyat','edeb-11-cenub-dunya',2,4,'«Sazımın sözü» əsəri hansı abidənin motivləri üzərində qurulub?','Bulud Qaraçorlu Səhəndin əsəri «Kitabi-Dədə Qorqud» motivlərinə əsaslanır.',array['«Kitabi-Dədə Qorqud»','«Koroğlu»','«Şahnamə»','«Xəmsə»'],1),
('edeb11-cenub-dunya#9','edebiyyat','edeb-11-cenub-dunya',2,4,'«Qoca və dəniz» əsərinin müəllifi kimdir?','Əsərin müəllifi Ernest Heminqueydir.',array['Ernest Heminquey','Qabriel Qarsia Markes','Çingiz Aytmatov','Nazim Hikmət'],1),
('edeb11-cenub-dunya#10','edebiyyat','edeb-11-cenub-dunya',2,4,'«Faust» əsərinin müəllifi hansı ölkənin yazıçısıdır?','«Faust»un müəllifi alman yazıçısı Hötedir.',array['Almaniyanın','Fransanın','İngiltərənin','İtaliyanın'],1),
('edeb11-cenub-dunya#11','edebiyyat','edeb-11-cenub-dunya',2,4,'Çingiz Aytmatov hansı xalqın ədəbiyyatının görkəmli nümayəndəsidir?','Aytmatov qırğız ədəbiyyatının görkəmli nümayəndəsidir.',array['Qırğız','Özbək','Qazax','Tatar'],1),
('edeb11-cenub-dunya#12','edebiyyat','edeb-11-cenub-dunya',2,4,'Nazim Hikmət hansı ölkənin şairidir?','Nazim Hikmət Türkiyə şairidir.',array['Türkiyənin','İranın','Rusiyanın','Bolqarıstanın'],1),
('edeb11-cenub-dunya#13','edebiyyat','edeb-11-cenub-dunya',2,4,'«Yüz ilin tənhalığı» romanının müəllifi kimdir?','Romanın müəllifi Qabriel Qarsia Markesdir.',array['Qabriel Qarsia Markes','Lev Tolstoy','Onore de Balzak','Uilyam Şekspir'],1),
('edeb11-cenub-dunya#14','edebiyyat','edeb-11-cenub-dunya',2,4,'Cənubi Azərbaycan ədəbiyyatının aparıcı mövzusu nədir?','Ana dili, vətən həsrəti və azadlıq arzusu aparıcı mövzudur.',array['Ana dili və vətən həsrəti','Sənaye tərəqqisi','Dəniz səyahətləri','Şəhər memarlığı'],1),
('edeb11-cenub-dunya#15','edebiyyat','edeb-11-cenub-dunya',2,4,'«Balaca qara balıq» nağılının əsas ideyası nədir?','Nağıl azadlıq, cəsarət və yeni dünyanı görmək arzusundan bəhs edir.',array['Azadlıq və cəsarət axtarışı','Var-dövlət toplamaq','Ailə ənənəsini qorumaq','Elm öyrənməyin çətinliyi'],1),
('edeb11-cenub-dunya#16','edebiyyat','edeb-11-cenub-dunya',2,4,'«Qorio ata» romanının müəllifi kimdir?','Romanın müəllifi fransız yazıçısı Onore de Balzakdır.',array['Onore de Balzak','Ernest Heminquey','Çingiz Aytmatov','Rəsul Həmzətov'],1),
('edeb11-cenub-dunya#17','edebiyyat','edeb-11-cenub-dunya',2,4,'«Heydərbabaya salam» poeması hansı dildə yazılmışdır?','Poema Azərbaycan dilində, ana dilində yazılmışdır.',array['Azərbaycan dilində','Fars dilində','Ərəb dilində','Rus dilində'],1),
('edeb11-cenub-dunya#18','edebiyyat','edeb-11-cenub-dunya',2,4,'1945-1946-cı il hadisələrindən sonra bir sıra cənublu şair harada yaşayıb-yaratdı?','Onlar Şimali Azərbaycana keçib burada yaradıcılığını davam etdirdilər.',array['Şimali Azərbaycanda','Türkiyədə','Almaniyada','Misirdə'],1),
('edeb11-cenub-dunya#19','edebiyyat','edeb-11-cenub-dunya',2,4,'«Mənim Dağıstanım» əsərinin müəllifi kimdir?','Əsərin müəllifi Rəsul Həmzətovdur.',array['Rəsul Həmzətov','Nazim Hikmət','Çingiz Aytmatov','Lev Tolstoy'],1),
('edeb11-cenub-dunya#20','edebiyyat','edeb-11-cenub-dunya',3,4,'Aşağıdakı üç əsər yazılma ardıcıllığı ilə necə düzülür? (1 - «Hamlet», 2 - «Yüz ilin tənhalığı», 3 - «Faust»)','«Hamlet» XVII əsrin əvvəlində, «Faust» XIX əsrin birinci yarısında, «Yüz ilin tənhalığı» isə XX əsrin ikinci yarısında yazılmışdır.',array['1 - 3 - 2','1 - 2 - 3','3 - 1 - 2','2 - 1 - 3'],1),
('edeb11-cenub-dunya#21','edebiyyat','edeb-11-cenub-dunya',3,4,'Cənub şairlərinə aid «əsər - müəllif» cütlüklərindən hansı doğrudur?','«Heydərbabaya salam» Şəhriyarın, «Sazımın sözü» Səhəndin əsəridir.',array['«Heydərbabaya salam» - Şəhriyar','«Sazımın sözü» - Şəhriyar','«Balaca qara balıq» - Səhənd','«Heydərbabaya salam» - Behrəngi'],1),
('edeb11-cenub-dunya#22','edebiyyat','edeb-11-cenub-dunya',3,4,'Məhəmmədhüseyn Şəhriyar haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','«Sazımın sözü» Bulud Qaraçorlu Səhəndin əsəridir.',array['«Sazımın sözü» əsərinin müəllifidir','«Heydərbabaya salam» onun poemasıdır','Təbrizdə doğulmuşdur','İki dildə əsər yazmışdır'],1),
('edeb11-cenub-dunya#23','edebiyyat','edeb-11-cenub-dunya',3,4,'Cənubi Azərbaycan ədəbiyyatında ana dili mövzusunun güclü olmasının səbəbi nədir?','Ana dilində təhsilin və nəşrin məhdudlaşdırılması bu mövzunu ön plana çıxarmışdır.',array['Ana dilində təhsilin məhdudlaşdırılması','Yazı ənənəsinin gec formalaşması','Xalq şeirinin unudulması','Mətbəənin gec yaranması'],1),
('edeb11-cenub-dunya#24','edebiyyat','edeb-11-cenub-dunya',3,4,'Aşağıdakı «yazıçı - ölkə» cütlüklərindən hansı düzgündür?','Heminquey ABŞ, Balzak Fransa, Nazim Hikmət Türkiyə ədəbiyyatındandır.',array['Ernest Heminquey - ABŞ','Ernest Heminquey - İngiltərə','Onore de Balzak - ABŞ','Nazim Hikmət - Almaniya'],1),
('edeb11-cenub-dunya#25','edebiyyat','edeb-11-cenub-dunya',3,4,'Şəhriyar və Səməd Behrənginin yaradıcılığındakı ortaq cəhət hansıdır?','Hər ikisi Cənubi Azərbaycanda yaşayıb-yaratmış, ana dilinə bağlı olmuşdur.',array['Hər ikisi Cənubi Azərbaycanda yaratmışdır','Hər ikisi nağıl janrında yazmışdır','Hər ikisi Bakıda təhsil almışdır','Hər ikisi poema janrında yazmışdır'],1),
('edeb11-cenub-dunya#26','edebiyyat','edeb-11-cenub-dunya',3,4,'Dünya ədəbiyyatı haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','«Qoca və dəniz» Heminqueyin əsəridir, Markesin deyil.',array['«Qoca və dəniz» Markesin əsəridir','«Hamlet» Şekspirin faciəsidir','«Faust» Hötenin əsəridir','«Qorio ata» Balzakın romanıdır'],1),
('edeb11-cenub-dunya#27','edebiyyat','edeb-11-cenub-dunya',3,4,'Dünya və cənub ədəbiyyatı üzrə «əsər - janr» cütlüyü hansı doğrudur?','«Heydərbabaya salam» poema, «Hamlet» faciə janrındadır.',array['«Heydərbabaya salam» - poema','«Balaca qara balıq» - poema','«Hamlet» - roman','«Qorio ata» - faciə'],1),
('edeb11-cenub-dunya#28','edebiyyat','edeb-11-cenub-dunya',3,4,'Şəhriyarın doğum ili ilə «Heydərbabaya salam»ın yazılma ili arasında neçə il var?','Şair 1906-cı ildə doğulub, poemanın birinci hissəsi 1954-cü ildə yazılıb.',array['48 il','28 il','38 il','58 il'],1),
('edeb11-cenub-dunya#29','edebiyyat','edeb-11-cenub-dunya',3,4,'Səməd Behrənginin nağıllarının uşaq ədəbiyyatından artıq məna daşımasının səbəbi nədir?','O, nağıl dilindən istifadə edərək ictimai fikir ifadə edirdi.',array['Nağıl dilində ictimai fikir ifadə etməsi','Uzun süjet qurulusuna malik olması','Xarici dildən tərcümə edilməsi','Şeirlə yazılmış olması'],1),
('edeb11-cenub-dunya#30','edebiyyat','edeb-11-cenub-dunya',3,4,'Şəhriyar və Səhəndin əsərləri haqqında hansı fikir doğrudur?','Şəhriyar Heydərbaba dağını, Səhənd isə Dədə Qorqud dünyasını qələmə alıb.',array['Biri Heydərbabanı, digəri Dədə Qorqudu qələmə alıb','Biri Dədə Qorqudu, digəri Heydərbabanı qələmə alıb','Hər ikisi Dədə Qorqud motivlərinə əsaslanır','Hər ikisi fars dilində yazılıb'],1),
('edeb11-cenub-dunya#31','edebiyyat','edeb-11-cenub-dunya',3,4,'Aşağıdakı «əsər - ədəbiyyat» cütlüklərindən hansı düzgündür?','«Ağ gəmi» qırğız, «Mənim Dağıstanım» isə Dağıstan ədəbiyyatına aiddir.',array['«Ağ gəmi» - qırğız ədəbiyyatı','«Ağ gəmi» - Dağıstan ədəbiyyatı','«Mənim Dağıstanım» - qırğız ədəbiyyatı','«Hamlet» - fransız ədəbiyyatı'],1),
('edeb11-nezeriyye#1','edebiyyat','edeb-11-nezeriyye',1,4,'Ədəbiyyatın üç əsas növü hansılardır?','Ədəbiyyatın növləri lirika, epos və dramdır.',array['Lirika, epos, dram','Roman, hekayə, povest','Qəzəl, qəsidə, rübai','Nəsr, nəzm, tərcümə'],1),
('edeb11-nezeriyye#2','edebiyyat','edeb-11-nezeriyye',1,4,'Rübai neçə misradan ibarətdir?','Rübai dörd misralı şeir formasıdır.',array['4','2','8','14'],1),
('edeb11-nezeriyye#3','edebiyyat','edeb-11-nezeriyye',1,4,'Sonet neçə misradan ibarətdir?','Sonet on dörd misralı şeir formasıdır.',array['14','4','8','20'],1),
('edeb11-nezeriyye#4','edebiyyat','edeb-11-nezeriyye',1,4,'Bənzətmə (təşbeh) nədir?','İki əşya və ya hadisənin oxşar cəhətinə görə tutuşdurulmasıdır.',array['İki əşyanın oxşarlığa görə tutuşdurulması','Sözün əks mənada işlənməsi','Hadisənin böyüdülərək verilməsi','Sətrin təkrarlanması'],1),
('edeb11-nezeriyye#5','edebiyyat','edeb-11-nezeriyye',2,4,'Metafora nədir?','Sözün oxşarlıq əsasında məcazi mənada işlədilməsidir.',array['Sözün məcazi mənada işlədilməsi','İki misranın qafiyələnməsi','Hadisələrin ardıcıllığı','Əsərin bölmələrə ayrılması'],1),
('edeb11-nezeriyye#6','edebiyyat','edeb-11-nezeriyye',2,4,'Epitet hansı vəzifəni daşıyır?','Epitet bədii təyin kimi çıxış edir.',array['Bədii təyin verir','Səsləri təkrarlayır','Süjeti bağlayır','Vəzni müəyyən edir'],1),
('edeb11-nezeriyye#7','edebiyyat','edeb-11-nezeriyye',2,4,'Mübaliğə hansı bədii vasitədir?','Mübaliğə şişirtmə vasitəsidir.',array['Şişirtmə','Kiçiltmə','Səs təkrarı','Qarşılaşdırma'],1),
('edeb11-nezeriyye#8','edebiyyat','edeb-11-nezeriyye',2,4,'Azərbaycan klassik şeirində hansı vəzn əsas olmuşdur?','Klassik şeirdə əruz vəzni əsas olmuşdur.',array['Əruz vəzni','Heca vəzni','Sərbəst şeir','Ağ şeir'],1),
('edeb11-nezeriyye#9','edebiyyat','edeb-11-nezeriyye',2,4,'Xalq şeirində hansı vəzn işlənir?','Xalq şeiri heca vəznində qurulur.',array['Heca vəzni','Əruz vəzni','Sərbəst şeir','Sonet forması'],1),
('edeb11-nezeriyye#10','edebiyyat','edeb-11-nezeriyye',2,4,'Süjetin hansı elementi hadisələrin ən gərgin anıdır?','Ən gərgin an kulminasiya adlanır.',array['Kulminasiya','Ekspozisiya','Düyün','Sonluq'],1),
('edeb11-nezeriyye#11','edebiyyat','edeb-11-nezeriyye',2,4,'Ekspozisiya süjetin hansı hissəsidir?','Ekspozisiya şəraitin və obrazların tanıdıldığı başlanğıcdır.',array['Şəraitin tanıdıldığı başlanğıc','Ən gərgin an','Münaqişənin həlli','Əsərin sonluğu'],1),
('edeb11-nezeriyye#12','edebiyyat','edeb-11-nezeriyye',2,4,'Realizm cərəyanı nəyi əsas götürür?','Realizm həyatın olduğu kimi, gerçək təsvirini əsas götürür.',array['Həyatın olduğu kimi təsvirini','Xəyali aləmin qurulmasını','Qədim miflərin bərpasını','Dini rəvayətlərin şərhini'],1),
('edeb11-nezeriyye#13','edebiyyat','edeb-11-nezeriyye',2,4,'Romantizm cərəyanının səciyyəvi cəhəti nədir?','İdeal aləmə, güclü hisslərə və xəyala üstünlük verilməsidir.',array['İdeal aləmə və güclü hisslərə üstünlük','Statistik dəqiqlik','Sənədli təsvir','Quru elmi şərh'],1),
('edeb11-nezeriyye#14','edebiyyat','edeb-11-nezeriyye',2,4,'Lirik qəhrəman anlayışı nəyi bildirir?','Şeirdə duyğu və düşüncələri ifadə olunan obrazı bildirir.',array['Şeirdə duyğuları ifadə olunan obrazı','Romanın baş qəhrəmanını','Dramın quruluşçu rejissorunu','Nağılın söyləyicisini'],1),
('edeb11-nezeriyye#15','edebiyyat','edeb-11-nezeriyye',2,4,'Qafiyə nədir?','Misra sonlarındakı səs uyğunluğudur.',array['Misra sonlarındakı səs uyğunluğu','Misradakı heca sayı','Şeirin mövzusu','Bəndlərin sayı'],1),
('edeb11-nezeriyye#16','edebiyyat','edeb-11-nezeriyye',2,4,'Rədif nədir?','Qafiyədən sonra eyni şəkildə təkrarlanan sözdür.',array['Qafiyədən sonra təkrarlanan söz','Misradakı vurğulu heca','Bəndin ilk misrası','Şeirin adı'],1),
('edeb11-nezeriyye#17','edebiyyat','edeb-11-nezeriyye',2,4,'Poema hansı əlamətinə görə adi lirik şeirdən fərqlənir?','Poema həcmli olur və süjet üzərində qurulur.',array['Həcmli və süjetli olması','Qafiyəsiz olması','Nəsrlə yazılması','Səhnə üçün yazılması'],1),
('edeb11-nezeriyye#18','edebiyyat','edeb-11-nezeriyye',2,4,'Faciə dram növünün hansı formasıdır?','Kəskin münaqişənin qəhrəmanın həlakı ilə bitdiyi formadır.',array['Qəhrəmanın həlakı ilə bitən forma','Gülüş doğuran forma','Musiqi ilə müşayiət olunan forma','Nağıl üstündə qurulan forma'],1),
('edeb11-nezeriyye#19','edebiyyat','edeb-11-nezeriyye',2,4,'Ədəbi əsərdə ideya nəyi bildirir?','Müəllifin əsərdə irəli sürdüyü əsas fikri bildirir.',array['Müəllifin irəli sürdüyü əsas fikri','Hadisələrin sırasını','Obrazların sayını','Əsərin həcmini'],1),
('edeb11-nezeriyye#20','edebiyyat','edeb-11-nezeriyye',3,4,'Ədəbi cərəyanlar tarixi ardıcıllıqla necə düzülür? (1 - romantizm, 2 - klassisizm, 3 - realizm)','Klassisizm daha erkən, sonra romantizm, ardınca realizm formalaşmışdır.',array['2 - 1 - 3','1 - 2 - 3','3 - 2 - 1','2 - 3 - 1'],1),
('edeb11-nezeriyye#21','edebiyyat','edeb-11-nezeriyye',3,4,'Aşağıdakı «termin - tərif» cütlüklərindən hansı düzgündür?','Rədif qafiyədən sonra təkrarlanan sözdür.',array['Rədif - təkrarlanan söz','Qafiyə - heca sayı','Vəzn - misra sonundakı uyğunluq','Bənd - şeirin mövzusu'],1),
('edeb11-nezeriyye#22','edebiyyat','edeb-11-nezeriyye',3,4,'Şeir formaları haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Sonet səkkiz deyil, on dörd misradan ibarətdir.',array['Sonet səkkiz misradan ibarətdir','Rübai dörd misradan ibarətdir','Qəzəl klassik lirik janrdır','Poema süjetli şeir əsəridir'],1),
('edeb11-nezeriyye#23','edebiyyat','edeb-11-nezeriyye',3,4,'Epitet ilə metafora arasındakı əsas fərq nədir?','Epitet bədii təyin yaradır, metafora isə məcazi məna qurur.',array['Epitet bədii təyin, metafora məcaz yaradır','Epitet məcaz, metafora bədii təyin yaradır','Hər ikisi eyni vəzifəni daşıyır','Epitet vəznlə, metafora qafiyə ilə bağlıdır'],1),
('edeb11-nezeriyye#24','edebiyyat','edeb-11-nezeriyye',3,4,'Ədəbi janrlar üzrə «əsər - janr» cütlüklərindən hansı doğrudur?','«Leyli və Məcnun» poema, «Hophopnamə» isə şeirlər toplusudur.',array['«Leyli və Məcnun» - poema','«Leyli və Məcnun» - dram','«Hophopnamə» - roman','«Vaqif» - poema'],1),
('edeb11-nezeriyye#25','edebiyyat','edeb-11-nezeriyye',3,4,'Sərbəst şeiri ənənəvi şeirdən fərqləndirən əsas cəhət hansıdır?','Sərbəst şeirdə sabit vəzn və qafiyə qəlibi gözlənilmir.',array['Sabit vəzn və qafiyə qəlibinin gözlənilməməsi','Misra sayının məhdudlaşdırılması','Bəndlərin bərabər bölünməsi','Klassik bəhrlərə əsaslanması'],1),
('edeb11-nezeriyye#26','edebiyyat','edeb-11-nezeriyye',3,4,'Vəznlər haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Uzun və qısa hecalara əsaslanan əruzdur, heca vəzni deyil.',array['Heca vəzni hecaların uzunluğuna əsaslanır','Əruz vəznində hecaların uzunluğu əsasdır','Heca vəznində heca sayı əsasdır','Sərbəst şeirdə sabit vəzn gözlənilmir'],1),
('edeb11-nezeriyye#27','edebiyyat','edeb-11-nezeriyye',3,4,'Aşağıdakı «cərəyan - səciyyəvi cəhət» cütlüklərindən hansı düzgündür?','Realizm həyatı olduğu kimi, romantizm isə ideal aləmi təsvir edir.',array['Realizm - həyatın olduğu kimi təsviri','Romantizm - həyatın olduğu kimi təsviri','Realizm - ideal aləmə üstünlük','Klassisizm - sərbəst formaya üstünlük'],1),
('edeb11-nezeriyye#28','edebiyyat','edeb-11-nezeriyye',3,4,'Poema ilə roman arasındakı əsas fərq nədir?','Poema nəzmlə, roman isə nəsrlə yazılır.',array['Biri nəzmlə, digəri nəsrlə yazılır','Biri nəsrlə, digəri nəzmlə yazılır','Hər ikisi səhnə üçün yazılır','Biri lirik, digəri dram növünə aiddir'],1),
('edeb11-nezeriyye#29','edebiyyat','edeb-11-nezeriyye',3,4,'Süjet elementləri düzgün ardıcıllıqla necə düzülür? (1 - ekspozisiya, 2 - kulminasiya, 3 - sonluq)','Əvvəlcə şərait tanıdılır, sonra gərginlik zirvəyə çatır, sonda həll olunur.',array['1 - 2 - 3','2 - 1 - 3','3 - 1 - 2','1 - 3 - 2'],1),
('edeb11-nezeriyye#30','edebiyyat','edeb-11-nezeriyye',3,4,'Faciə ilə komediya arasındakı əsas fərq nədir?','Faciədə qəhrəman həlak olur, komediya isə gülüş doğurur.',array['Faciədə qəhrəman həlak olur, komediyada gülüş doğur','Komediyada qəhrəman həlak olur, faciədə gülüş doğur','Hər ikisi lirik növə aiddir','Faciə nəsrlə, komediya nəzmlə yazılır'],1),
('edeb11-nezeriyye#31','edebiyyat','edeb-11-nezeriyye',3,4,'Aşağıdakı «bədii vasitə - nümunə» cütlüklərindən hansı düzgündür?','«Dağ boyda ürək» ifadəsi şişirtmə, yəni mübaliğədir.',array['Mübaliğə - dağ boyda ürək','Epitet - dağ boyda ürək','Mübaliğə - qara gözlər','Təşbeh - qızıl payız'],1)
),
ins as (
  insert into public.questions
    (ext_key, owner_type, subject_id, level_id, topic_id, kind,
     body, explanation, difficulty, quarter, status)
  select d.ext, 'platform', s.id, tp.level_id, tp.id, 'single',
         d.body, d.why, d.diff, d.rub, 'published'
    from d
    join public.subjects s on s.slug = d.fenn
    join public.topics   tp on tp.subject_id = s.id and tp.slug = d.topic
  on conflict (ext_key) do update
    set body = excluded.body, explanation = excluded.explanation,
        difficulty = excluded.difficulty, quarter = excluded.quarter,
        topic_id = excluded.topic_id, level_id = excluded.level_id,
        subject_id = excluded.subject_id, status = 'published'
  returning id, ext_key
)
insert into public.question_options (question_id, ord, body, is_correct)
select ins.id, o.ord, o.txt, o.ord = d.correct
  from ins
  join d on d.ext = ins.ext_key,
  lateral unnest(d.opts) with ordinality as o(txt, ord);

do $$
declare n int; k int;
begin
  select count(*) into n from public.questions
   where owner_type = 'platform' and ext_key like 'edeb11-%';
  if n <> 248 then
    raise exception 'Edebiyyat 11 suallari: 248 gozlenilirdi, % tapildi', n;
  end if;
  select count(*) into k from public.questions q
   where q.ext_key like 'edeb11-%'
     and ((select count(*) from public.question_options o
            where o.question_id = q.id) <> 4
       or (select count(*) from public.question_options o
            where o.question_id = q.id and o.is_correct) <> 1);
  if k > 0 then
    raise exception '% sualda variant qurulusu sehvdir', k;
  end if;
  select count(distinct topic_id) into k from public.questions
   where ext_key like 'edeb11-%';
  if k <> 8 then
    raise exception 'movzu sayi 8 deyil: %', k;
  end if;
  --  Her movzuda en azi 12 cetin sual olmalidir ki, muellim BIR
  --  movzudan 10 sualliq cetin test yiga bilsin
  select count(*) into k from (
    select q.topic_id from public.questions q
     where q.ext_key like 'edeb11-%' and q.difficulty = 3
     group by q.topic_id having count(*) < 12) z;
  if k > 0 then
    raise exception '% movzuda 12-den az cetin sual var', k;
  end if;
  raise notice 'Edebiyyat 11 banki: % sual, 8 movzu (her birinde 12 cetin).', n;
end $$;
