-- =====================================================================
--  59_bank_edebiyyat10.sql : EDEBIYYAT 10 BANKI
--
--  BU FAYL ELLE YAZILMIR - tools/edebiyyat10.py yaradir:
--      python3 tools/edebiyyat10.py
--
--  8 movzu x 31 sual = 248.  Her movzuda 4 asan + 15 orta + 12 cetin.
--  ext_key: edeb11-...
--  ON SERT: 58_movzular_edebiyyat9_10.sql islenmis olmalidir.
--  SONRA:   05_grants.sql yeniden islet.
-- =====================================================================

do $$
begin
  if not exists (select 1 from public.topics t join public.subjects s
      on s.id = t.subject_id
     where s.slug = 'edebiyyat' and t.slug in
           ('edeb-10-sifahi', 'edeb-10-maarifci')
     having count(*) = 2) then
    raise exception 'ONCE 58_movzular_edebiyyat9_10.sql isledilmelidir.';
  end if;
end $$;

delete from public.question_options o
 using public.questions q
 where o.question_id = q.id
   and q.owner_type = 'platform'
   and q.ext_key like 'edeb10-%';

with d(ext, fenn, topic, diff, rub, body, why, opts, correct) as (values
('edeb10-sifahi#1','edebiyyat','edeb-10-sifahi',1,1,'Şifahi xalq ədəbiyyatının əsas əlaməti nədir?','Bu əsərlərin konkret müəllifi məlum olmur, xalq yaradıcılığıdır.',array['Müəllifinin məlum olmaması','Kitab şəklində yazılması','Bir müəllifə aid olması','Xarici dildə yaranması'],1),
('edeb10-sifahi#2','edebiyyat','edeb-10-sifahi',1,1,'Bayatı neçə misradan ibarətdir?','Bayatı dörd misralı şeir formasıdır.',array['4','2','6','8'],1),
('edeb10-sifahi#3','edebiyyat','edeb-10-sifahi',1,1,'Aşıq hansı musiqi alətində çalır?','Aşığın əsas aləti sazdır.',array['Saz','Tar','Kaman','Ney'],1),
('edeb10-sifahi#4','edebiyyat','edeb-10-sifahi',1,1,'Lətifə janrının ən məşhur qəhrəmanı kimdir?','Lətifələrin əsas qəhrəmanı Molla Nəsrəddindir.',array['Molla Nəsrəddin','Koroğlu','Dədə Qorqud','Kərəm'],1),
('edeb10-sifahi#5','edebiyyat','edeb-10-sifahi',2,1,'Bayatının hər misrasında neçə heca olur?','Bayatı yeddi hecalı misralardan qurulur.',array['7','5','8','11'],1),
('edeb10-sifahi#6','edebiyyat','edeb-10-sifahi',2,1,'Bayatının qafiyə quruluşu necədir?','Bayatıda birinci, ikinci və dördüncü misralar qafiyələnir.',array['a-a-b-a','a-b-a-b','a-a-a-a','a-b-b-a'],1),
('edeb10-sifahi#7','edebiyyat','edeb-10-sifahi',2,1,'«Əsli və Kərəm» hansı dastan növünə aiddir?','Bu, məhəbbət dastanıdır.',array['Məhəbbət dastanı','Qəhrəmanlıq dastanı','Tarixi salnamə','Mərasim nəğməsi'],1),
('edeb10-sifahi#8','edebiyyat','edeb-10-sifahi',2,1,'Ağı nə zaman söylənir?','Ağı yas mərasimində, itki üstündə söylənir.',array['Yas mərasimində','Toy mərasimində','Novruz bayramında','Əkin vaxtı'],1),
('edeb10-sifahi#9','edebiyyat','edeb-10-sifahi',2,1,'Laylay kimə oxunur?','Laylay beşikdəki körpəni yatırtmaq üçün oxunur.',array['Beşikdəki körpəyə','Cəbhəyə gedənə','Gələn qonağa','Bayram tonqalında'],1),
('edeb10-sifahi#10','edebiyyat','edeb-10-sifahi',2,1,'Holavar hansı əmək sahəsi ilə bağlıdır?','Holavar əkinçilikdə, cüt sürərkən oxunan nəğmədir.',array['Əkinçiliklə','Balıqçılıqla','Dəmirçiliklə','Xalçaçılıqla'],1),
('edeb10-sifahi#11','edebiyyat','edeb-10-sifahi',2,1,'Sayaçı sözü hansı təsərrüfat sahəsi ilə bağlıdır?','Sayaçı sözü heyvandarlıqla, qoyun sürüsü ilə bağlıdır.',array['Heyvandarlıqla','Bağçılıqla','Ticarətlə','Ovçuluqla'],1),
('edeb10-sifahi#12','edebiyyat','edeb-10-sifahi',2,1,'Dastanların quruluşunda hansı iki forma növbələşir?','Dastanda nəsr hissəsi ilə nəzm parçaları növbələşir.',array['Nəzm və nəsr','İki ayrı nəzm forması','Nəsr və not yazısı','Şeir və rəsm'],1),
('edeb10-sifahi#13','edebiyyat','edeb-10-sifahi',2,1,'Atalar sözünün əsas xüsusiyyəti nədir?','Qısa formada dərin hikmət ifadə etməsidir.',array['Qısa formada hikmət ifadə etməsi','Uzun süjetli olması','Sazla oxunması','Müəllifinin bəlli olması'],1),
('edeb10-sifahi#14','edebiyyat','edeb-10-sifahi',2,1,'Tapmaca nəyə xidmət edir?','Əşyanı əlamətlərinə görə tapmağa, zehni itiləməyə xidmət edir.',array['Əşyanı əlamətinə görə tapmağa','Yas mərasiminə','Toy adətinə','Əkin işinə'],1),
('edeb10-sifahi#15','edebiyyat','edeb-10-sifahi',2,1,'«Koroğlu» hansı dastan növünə aiddir?','«Koroğlu» qəhrəmanlıq dastanıdır.',array['Qəhrəmanlıq dastanı','Məhəbbət dastanı','Ailə-məişət nağılı','Mərasim nəğməsi'],1),
('edeb10-sifahi#16','edebiyyat','edeb-10-sifahi',2,1,'Nağılın ənənəvi başlanğıc ifadəsi hansıdır?','Nağıllar çox vaxt «Biri var idi, biri yox idi» ilə başlayır.',array['«Biri var idi, biri yox idi»','«Göydən üç alma düşdü»','«Nağıl burada bitdi»','«Zaman keçdi, illər ötdü»'],1),
('edeb10-sifahi#17','edebiyyat','edeb-10-sifahi',2,1,'Şifahi ədəbiyyat əsərlərinin variantlarının olmasının səbəbi nədir?','Əsərlər ağızdan-ağıza keçdiyi üçün hər söyləyicidə bir qədər dəyişir.',array['Ağızdan-ağıza keçməsi','Kitab şəklində çap olunması','Bir müəllifin yazması','Xarici dildən tərcümə edilməsi'],1),
('edeb10-sifahi#18','edebiyyat','edeb-10-sifahi',2,1,'Qoşma neçə misralı bənddən ibarətdir?','Qoşmanın hər bəndi dörd misradan ibarətdir.',array['Dörd misralı bənddən','İki misralı bənddən','Beş misralı bənddən','Altı misralı bənddən'],1),
('edeb10-sifahi#19','edebiyyat','edeb-10-sifahi',2,1,'Yanıltmac nəyə xidmət edir?','Düzgün və aydın tələffüzün məşqinə xidmət edir.',array['Düzgün tələffüzün məşqinə','Yas mərasiminə','Əkin işinə','Ov ayininə'],1),
('edeb10-sifahi#20','edebiyyat','edeb-10-sifahi',3,1,'Aşağıdakı «janr - səciyyəvi cəhət» cütlüklərindən hansı düzgündür?','Bayatı yeddi hecalı dördlükdür, qoşma isə on bir hecalıdır.',array['Bayatı - yeddi hecalı dördlük','Qoşma - yeddi hecalı dördlük','Bayatı - on bir hecalı dördlük','Atalar sözü - dörd misralı şeir'],1),
('edeb10-sifahi#21','edebiyyat','edeb-10-sifahi',3,1,'Şifahi xalq ədəbiyyatı haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Dastanlarda nəsrlə yanaşı nəzm parçaları da olur.',array['Dastanlar bütövlükdə nəsrlə söylənir','Bayatı dörd misralı şeir formasıdır','Ağı yas mərasimi ilə bağlıdır','Holavar əkinçilik nəğməsidir'],1),
('edeb10-sifahi#22','edebiyyat','edeb-10-sifahi',3,1,'Məhəbbət dastanı ilə qəhrəmanlıq dastanının əsas fərqi nədir?','Birində eşq, digərində el və vətən uğrunda mübarizə əsasdır.',array['Birində eşq, digərində vətən uğrunda mübarizə','Birində vətən uğrunda mübarizə, digərində eşq','Biri nəzmlə, digəri bütövlükdə nəsrlə söylənir','Birində nağılçı, digərində ozan iştirak edir'],1),
('edeb10-sifahi#23','edebiyyat','edeb-10-sifahi',3,1,'Aşağıdakı «əsər - dastan növü» cütlüklərindən hansı doğrudur?','«Aşıq Qərib» məhəbbət, «Koroğlu» isə qəhrəmanlıq dastanıdır.',array['«Aşıq Qərib» - məhəbbət dastanı','«Koroğlu» - məhəbbət dastanı','«Aşıq Qərib» - qəhrəmanlıq dastanı','«Əsli və Kərəm» - qəhrəmanlıq dastanı'],1),
('edeb10-sifahi#24','edebiyyat','edeb-10-sifahi',3,1,'Aşıqların eyni dastanı hər dəfə bir qədər fərqli söyləməsinin səbəbi nədir?','Mətn yazıya köçürülmür, yaddaşda saxlanıb şifahi ötürülür.',array['Mətnin yaddaşda saxlanıb şifahi ötürülməsi','Mətnin kitabda çap olunması','Dastanların xarici dildə yazılması','Musiqi alətinin vaxtaşırı dəyişməsi'],1),
('edeb10-sifahi#25','edebiyyat','edeb-10-sifahi',3,1,'Aşağıdakı «nəğmə - məşğuliyyət» cütlüklərindən hansı düzgündür?','Holavar əkinçilik, sayaçı sözü isə heyvandarlıq nəğməsidir.',array['Holavar - əkinçilik','Sayaçı sözü - əkinçilik','Holavar - heyvandarlıq','Laylay - ovçuluq'],1),
('edeb10-sifahi#26','edebiyyat','edeb-10-sifahi',3,1,'Xalq ədəbiyyatı janrları haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Lətifə qısa, gülüş doğuran janrdır, qəhrəmanlıq əsəri deyil.',array['Lətifə uzun süjetli qəhrəmanlıq əsəridir','Tapmaca əşyanı əlamətinə görə tanıdır','Atalar sözü qısa hikmətli ifadədir','Laylay körpə üçün oxunur'],1),
('edeb10-sifahi#27','edebiyyat','edeb-10-sifahi',3,1,'Bayatı ilə qoşmanın misrasındakı heca sayı arasında neçə heca fərq var?','Bayatı yeddi, qoşma on bir hecalıdır.',array['4 heca','2 heca','6 heca','1 heca'],1),
('edeb10-sifahi#28','edebiyyat','edeb-10-sifahi',3,1,'Aşağıdakı «obraz - əsər növü» cütlüklərindən hansı doğrudur?','Dədə Qorqud oğuz eposunun, Molla Nəsrəddin lətifələrin obrazıdır.',array['Dədə Qorqud - oğuz eposu','Molla Nəsrəddin - oğuz eposu','Dədə Qorqud - lətifələr','Koroğlu - məhəbbət dastanı'],1),
('edeb10-sifahi#29','edebiyyat','edeb-10-sifahi',3,1,'Nağılla dastan arasındakı əsas fərq nədir?','Dastanda nəzm parçaları olur, nağıl isə bütövlükdə nəsrdir.',array['Dastanda nəzm olur, nağıl bütövlükdə nəsrdir','Nağılda nəzm olur, dastan bütövlükdə nəsrdir','Hər ikisi bütövlükdə nəzmlə söylənir','Hər ikisi yazılı şəkildə yayılır'],1),
('edeb10-sifahi#30','edebiyyat','edeb-10-sifahi',3,1,'Mərasim və əmək nəğmələrinin yaranmasının kökündə nə dayanır?','Bu nəğmələr birbaşa əmək prosesinin özündən doğulmuşdur.',array['Əmək prosesinin özü','Saray şeiri ənənəsi','Yazılı ədəbiyyatın təsiri','Qonşu ölkələrin təsiri'],1),
('edeb10-sifahi#31','edebiyyat','edeb-10-sifahi',3,1,'Aşıq yaradıcılığı haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Aşıq şeiri heca vəznindədir, əruz yazılı ədəbiyyatın vəznidir.',array['Aşıq şeiri əruz vəzninə əsaslanır','Qoşma dörd misralı bənddən ibarətdir','Aşığın əsas aləti sazdır','Dastanlar aşıq repertuarındadır'],1),
('edeb10-dede-qorqud#1','edebiyyat','edeb-10-dede-qorqud',1,1,'«Kitabi-Dədə Qorqud» hansı xalqın eposudur?','Epos oğuz türklərinin qəhrəmanlıq abidəsidir.',array['Oğuz türklərinin','Ərəblərin','Farsların','Yunanların'],1),
('edeb10-dede-qorqud#2','edebiyyat','edeb-10-dede-qorqud',1,1,'«Kitabi-Dədə Qorqud» neçə boydan ibarətdir?','Eposda on iki boy vardır.',array['12','7','20','5'],1),
('edeb10-dede-qorqud#3','edebiyyat','edeb-10-dede-qorqud',1,1,'Dədə Qorqud eposda kim kimi təsvir olunur?','O, ad qoyan, məsləhət verən müdrik ozan və ağsaqqaldır.',array['Müdrik ozan və ağsaqqal','Gənc döyüşçü','Xarici ölkə elçisi','Karvan taciri'],1),
('edeb10-dede-qorqud#4','edebiyyat','edeb-10-dede-qorqud',1,1,'Eposun dili hansıdır?','Epos oğuz türkcəsində yaranmışdır.',array['Oğuz türkcəsi','Ərəb dili','Fars dili','Yunan dili'],1),
('edeb10-dede-qorqud#5','edebiyyat','edeb-10-dede-qorqud',2,1,'Eposun neçə əlyazma nüsxəsi məlumdur?','İki nüsxə məlumdur: Drezden və Vatikan nüsxələri.',array['İki','Bir','Beş','On'],1),
('edeb10-dede-qorqud#6','edebiyyat','edeb-10-dede-qorqud',2,1,'Vatikan nüsxəsində neçə boy var?','Vatikan nüsxəsində altı boy vardır.',array['6','12','2','9'],1),
('edeb10-dede-qorqud#7','edebiyyat','edeb-10-dede-qorqud',2,1,'Boyların mətnindəki şeir parçaları hansı adla tanınır?','Onlar soylama adlanır.',array['Soylama','Qəzəl','Rübai','Qoşma'],1),
('edeb10-dede-qorqud#8','edebiyyat','edeb-10-dede-qorqud',2,1,'«Salur Qazanın evinin yağmalandığı boy»da Qazanın həyat yoldaşı kimdir?','Qazan xanın həyat yoldaşı Burla xatundur.',array['Burla xatun','Nigar xanım','Banuçiçək','Selcan xatun'],1),
('edeb10-dede-qorqud#9','edebiyyat','edeb-10-dede-qorqud',2,1,'Həmin boyda Qazan xanın oğlunun adı nədir?','Qazan xanın oğlu Uruzdur.',array['Uruz','Beyrək','Basat','Səgrək'],1),
('edeb10-dede-qorqud#10','edebiyyat','edeb-10-dede-qorqud',2,1,'Qazanın sürülərini düşməndən qoruyan obraz kimdir?','Sürüləri Qaraca Çoban qoruyur.',array['Qaraca Çoban','Dəli Domrul','Qanturalı','Yeynək'],1),
('edeb10-dede-qorqud#11','edebiyyat','edeb-10-dede-qorqud',2,1,'Qaraca Çoban düşmənə qarşı hansı silahdan istifadə edir?','O, sapandla daş atıb düşməni saxlayır.',array['Sapand','Ox-kaman','Qılınc','Nizə'],1),
('edeb10-dede-qorqud#12','edebiyyat','edeb-10-dede-qorqud',2,1,'Oğuz elinin xanlar xanı kimdir?','Oğuzun xanlar xanı Bayandır xandır.',array['Bayandır xan','Qazan xan','Şöklü Məlik','Dirsə xan'],1),
('edeb10-dede-qorqud#13','edebiyyat','edeb-10-dede-qorqud',2,1,'«Dirsə xan oğlu Buğac» boyunda oğlan hansı işə görə ad alır?','O, meydanda buğanı öldürdüyü üçün Buğac adını alır.',array['Buğanı öldürdüyünə görə','Ov quşu tutduğuna görə','Qala aldığına görə','İlk dəfə ata mindiyinə görə'],1),
('edeb10-dede-qorqud#14','edebiyyat','edeb-10-dede-qorqud',2,1,'Təpəgözü məğlub edən qəhrəman kimdir?','Təpəgözü Basat məğlub edir.',array['Basat','Beyrək','Uruz','Yeynək'],1),
('edeb10-dede-qorqud#15','edebiyyat','edeb-10-dede-qorqud',2,1,'Eposda qadın obrazları necə təsvir olunur?','Onlar ata minən, ox atan, döyüşə qatılan igidlər kimi verilir.',array['Ata minib döyüşən igidlər kimi','Yalnız ev işində','Danışmayan obrazlar kimi','Yad eldən gələnlər kimi'],1),
('edeb10-dede-qorqud#16','edebiyyat','edeb-10-dede-qorqud',2,1,'«Kitabi-Dədə Qorqud»un 1300 illiyi hansı ildə qeyd olunmuşdur?','Yubiley 2000-ci ildə qeyd olunmuşdur.',array['2000','1990','1975','2010'],1),
('edeb10-dede-qorqud#17','edebiyyat','edeb-10-dede-qorqud',2,1,'Eposun müqəddiməsində əsasən nədən danışılır?','Dədə Qorqudun özündən və oğuz elinin adət-ənənəsindən.',array['Dədə Qorqud və oğuz adətlərindən','Səfəvi dövlətindən','Nizaminin həyatından','Koroğlunun dəlilərindən'],1),
('edeb10-dede-qorqud#18','edebiyyat','edeb-10-dede-qorqud',2,1,'«Dəli Domrul» boyunun əsas mövzusu nədir?','İnsanın ölümlə üz-üzə gəlməsi və həyat sevgisidir.',array['Ölümlə üz-üzə gəlmək','Toy mərasimi','Ticarət səfəri','Əkin işləri'],1),
('edeb10-dede-qorqud#19','edebiyyat','edeb-10-dede-qorqud',2,1,'Boylarda oğuza hücum edən düşmən başçısı kimdir?','Boylarda düşmən başçısı Şöklü Məlikdir.',array['Şöklü Məlik','Bayandır xan','Qaraca Çoban','Dədə Qorqud'],1),
('edeb10-dede-qorqud#20','edebiyyat','edeb-10-dede-qorqud',3,1,'Aşağıdakı «boy - qəhrəman» cütlüklərindən hansı düzgündür?','Təpəgözü Basat, buğanı isə Buğac məğlub edir.',array['Təpəgöz boyu - Basat','Təpəgöz boyu - Beyrək','Dəli Domrul boyu - Basat','Buğac boyu - Uruz'],1),
('edeb10-dede-qorqud#21','edebiyyat','edeb-10-dede-qorqud',3,1,'«Kitabi-Dədə Qorqud» haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Epos oğuz türkcəsində yaranmışdır, fars dilində deyil.',array['Epos fars dilində yaranmışdır','Epos on iki boydan ibarətdir','Dədə Qorqud ad qoyan müdrikdir','Boylarda nəzm parçaları vardır'],1),
('edeb10-dede-qorqud#22','edebiyyat','edeb-10-dede-qorqud',3,1,'Drezden və Vatikan nüsxələri arasındakı fərq nədir?','Drezden nüsxəsində on iki, Vatikan nüsxəsində altı boy var.',array['Birində on iki, digərində altı boy var','Birində altı, digərində iki boy var','Hər ikisində on iki boy var','Biri nəzmlə, digəri nəsrlə yazılıb'],1),
('edeb10-dede-qorqud#23','edebiyyat','edeb-10-dede-qorqud',3,1,'Qazan xanın evinin yağmalanmasına şərait yaradan səbəb nədir?','Qazan uzun ova getmiş, ev qorunmasız qalmışdı.',array['Qazanın uzun ova getməsi','Bayandır xanla mübahisəsi','Burla xatunun qonaqlığa getməsi','Qaraca Çobanın sürünü itirməsi'],1),
('edeb10-dede-qorqud#24','edebiyyat','edeb-10-dede-qorqud',3,1,'Aşağıdakı «obraz - rol» cütlüklərindən hansı doğrudur?','Qaraca Çoban sürünü qoruyur, Şöklü Məlik isə düşmən başçısıdır.',array['Qaraca Çoban - sürünü qoruyan','Şöklü Məlik - sürünü qoruyan','Qaraca Çoban - oğuz xanı','Uruz - düşmən başçısı'],1),
('edeb10-dede-qorqud#25','edebiyyat','edeb-10-dede-qorqud',3,1,'«Kitabi-Dədə Qorqud» ilə «Koroğlu» dastanının ortaq cəhəti nədir?','Hər ikisi qəhrəmanlıq mövzusunda xalq yaradıcılığı nümunəsidir.',array['Hər ikisi qəhrəmanlıq mövzusundadır','Hər ikisi məhəbbət dastanıdır','Hər ikisinin müəllifi bəllidir','Hər ikisi fars dilində yaranıb'],1),
('edeb10-dede-qorqud#26','edebiyyat','edeb-10-dede-qorqud',3,1,'Boyların məzmunu haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','«Dəli Domrul» boyu ölüm və həyat sevgisindən bəhs edir.',array['«Dəli Domrul» boyu toy mərasimindən bəhs edir','«Basat» boyunda Təpəgöz məğlub edilir','«Buğac» boyunda oğlan buğanı öldürür','«Salur Qazan» boyunda ev yağmalanır'],1),
('edeb10-dede-qorqud#27','edebiyyat','edeb-10-dede-qorqud',3,1,'«Salur Qazanın evinin yağmalandığı boy»da hadisələr necə sıralanır? (1 - düşmənin məğlub edilməsi, 2 - Qazanın ova getməsi, 3 - evin yağmalanması)','Əvvəlcə Qazan ova gedir, sonra ev yağmalanır, sonda düşmən məğlub olur.',array['2 - 3 - 1','1 - 2 - 3','3 - 2 - 1','2 - 1 - 3'],1),
('edeb10-dede-qorqud#28','edebiyyat','edeb-10-dede-qorqud',3,1,'Aşağıdakı «əsər - janr» cütlüklərindən hansı düzgündür?','«Kitabi-Dədə Qorqud» epos, «Dəhnamə» isə poemadır.',array['«Kitabi-Dədə Qorqud» - epos','«Kitabi-Dədə Qorqud» - qəzəl','«Dəhnamə» - epos','«Sığmazam» - epos'],1),
('edeb10-dede-qorqud#29','edebiyyat','edeb-10-dede-qorqud',3,1,'Eposda qadın obrazlarının döyüşkən verilməsi nəyi göstərir?','Oğuz cəmiyyətində qadının yüksək mövqeyini göstərir.',array['Qadının cəmiyyətdəki yüksək mövqeyini','Kişi obrazlarının azlığını','Ov ənənəsinin olmamasını','Yazılı ədəbiyyatın güclü təsirini'],1),
('edeb10-dede-qorqud#30','edebiyyat','edeb-10-dede-qorqud',3,1,'Dədə Qorqud və Bayandır xan haqqında hansı fikir doğrudur?','Dədə Qorqud ozan-ağsaqqal, Bayandır xan isə xanlar xanıdır.',array['Biri ozan-ağsaqqal, digəri xanlar xanıdır','Biri xanlar xanı, digəri düşmən başçısıdır','Hər ikisi düşmən tərəfin obrazıdır','Hər ikisi çoban obrazıdır'],1),
('edeb10-dede-qorqud#31','edebiyyat','edeb-10-dede-qorqud',3,1,'Aşağıdakı «boy - mövzu» cütlüklərindən hansı doğrudur?','«Dəli Domrul» ölüm və həyat, «Buğac» isə ad qoyma boyudur.',array['Dəli Domrul boyu - ölüm və həyat','Buğac boyu - ölüm və həyat','Dəli Domrul boyu - ad qoyma','Təpəgöz boyu - toy mərasimi'],1),
('edeb10-nizami#1','edebiyyat','edeb-10-nizami',1,2,'Nizami Gəncəvi hansı şəhərdə yaşayıb-yaratmışdır?','Şair bütün ömrünü Gəncədə keçirmişdir.',array['Gəncədə','Şamaxıda','Təbrizdə','Şuşada'],1),
('edeb10-nizami#2','edebiyyat','edeb-10-nizami',1,2,'Nizaminin beş poemadan ibarət külliyyatı necə adlanır?','Beş poema «Xəmsə» adı altında birləşir.',array['«Xəmsə»','«Divan»','«Dəhnamə»','«Hophopnamə»'],1),
('edeb10-nizami#3','edebiyyat','edeb-10-nizami',1,2,'«İskəndərnamə» hansı janrdadır?','«İskəndərnamə» poemadır.',array['Poema','Roman','Hekayə','Dram'],1),
('edeb10-nizami#4','edebiyyat','edeb-10-nizami',1,2,'Nizami əsərlərini hansı dildə yazmışdır?','Şair əsərlərini fars dilində qələmə almışdır.',array['Fars dilində','Ərəb dilində','Yunan dilində','Rus dilində'],1),
('edeb10-nizami#5','edebiyyat','edeb-10-nizami',2,2,'«Xəmsə»yə daxil olan ilk poema hansıdır?','«Sirlər xəzinəsi» «Xəmsə»nin ilk poemasıdır.',array['«Sirlər xəzinəsi»','«Yeddi gözəl»','«İskəndərnamə»','«Leyli və Məcnun»'],1),
('edeb10-nizami#6','edebiyyat','edeb-10-nizami',2,2,'«İskəndərnamə» neçə hissədən ibarətdir?','Poema iki hissədən ibarətdir.',array['İki','Üç','Beş','Yeddi'],1),
('edeb10-nizami#7','edebiyyat','edeb-10-nizami',2,2,'«İskəndərnamə»nin hissələri necə adlanır?','Hissələr «Şərəfnamə» və «İqbalnamə» adlanır.',array['«Şərəfnamə» və «İqbalnamə»','«Divan» və «Xəmsə»','«Dəhnamə» və «Nəsihətnamə»','«Şahnamə» və «Xəmsə»'],1),
('edeb10-nizami#8','edebiyyat','edeb-10-nizami',2,2,'«İskəndərnamə»də Bərdə hökmdarı kimdir?','Bərdə hökmdarı Nüşabədir.',array['Nüşabə','Şirin','Leyli','Məhinbanu'],1),
('edeb10-nizami#9','edebiyyat','edeb-10-nizami',2,2,'Nüşabə obrazının səciyyəvi cəhəti nədir?','O, ağıllı və müdrik qadın hökmdar kimi verilir.',array['Ağıllı və müdrik qadın hökmdar','Zalım hökmdar','Sadə kəndli qadın','Yad ölkə elçisi'],1),
('edeb10-nizami#10','edebiyyat','edeb-10-nizami',2,2,'«İskəndərnamə»də İskəndər obrazı hansı mərhələlərdən keçir?','O, əvvəlcə fateh, sonra alim-hökmdar, sonda peyğəmbər kimi verilir.',array['Fateh, alim, peyğəmbər','Tacir, əsgər, çoban','Şair, rəssam, memar','Aşiq, dərviş, tacir'],1),
('edeb10-nizami#11','edebiyyat','edeb-10-nizami',2,2,'Nizami yaradıcılığında hansı ideya aparıcıdır?','Ədalətli hökmdar və ədalətli cəmiyyət ideyası aparıcıdır.',array['Ədalətli hökmdar və cəmiyyət','Var-dövlət toplamaq','Döyüş qənimətinin bölgüsü','Səyahət macəraları'],1),
('edeb10-nizami#12','edebiyyat','edeb-10-nizami',2,2,'«Xosrov və Şirin» poemasında dağı yaran aşiq obrazı kimdir?','Bu obraz Fərhaddır.',array['Fərhad','İskəndər','Məcnun','Bəhram'],1),
('edeb10-nizami#13','edebiyyat','edeb-10-nizami',2,2,'«Yeddi gözəl» poemasının mərkəzində hansı hökmdar dayanır?','Poemanın mərkəzində Bəhram obrazı dayanır.',array['Bəhram','Xosrov','İskəndər','Qeys'],1),
('edeb10-nizami#14','edebiyyat','edeb-10-nizami',2,2,'Nizaminin saraya bağlanmamasının səbəbi nə ilə izah olunur?','Şair yaradıcılıq müstəqilliyini qorumaq istəyirdi.',array['Yaradıcılıq müstəqilliyini qorumaq','Uzaq ölkədə yaşaması','Saray dilini bilməməsi','Səfər çətinliyi'],1),
('edeb10-nizami#15','edebiyyat','edeb-10-nizami',2,2,'Nizamidən sonra beş poema yazmaq ənənəsi necə adlanır?','Bu ənənə xəmsəçilik adlanır.',array['Xəmsəçilik','Divançılıq','Dastançılıq','Aşıqlıq'],1),
('edeb10-nizami#16','edebiyyat','edeb-10-nizami',2,2,'Nizami hansı əsrdə yaşamışdır?','Şair XII əsrdə yaşamışdır.',array['XII əsrdə','IX əsrdə','XV əsrdə','XVIII əsrdə'],1),
('edeb10-nizami#17','edebiyyat','edeb-10-nizami',2,2,'«Sirlər xəzinəsi» hansı səciyyə daşıyır?','Poema didaktik-fəlsəfi səciyyəlidir.',array['Didaktik-fəlsəfi','Sırf məhəbbət','Sənədli-tarixi','Satirik'],1),
('edeb10-nizami#18','edebiyyat','edeb-10-nizami',2,2,'«Leyli və Məcnun» poemasında aşiqin əsl adı nədir?','Aşiqin əsl adı Qeysdir.',array['Qeys','Fərhad','Bəhram','Xosrov'],1),
('edeb10-nizami#19','edebiyyat','edeb-10-nizami',2,2,'İskəndər uzaq səfərlərində əsasən nəyi axtarır?','O, həqiqəti və kamil cəmiyyəti axtarır.',array['Həqiqət və kamil cəmiyyət','Yalnız döyüş qəniməti','Uzun ömür iksiri','Yeni ticarət yolu'],1),
('edeb10-nizami#20','edebiyyat','edeb-10-nizami',3,2,'Nizaminin üç poeması «Xəmsə»dəki sıra ilə necə düzülür? (1 - «İskəndərnamə», 2 - «Sirlər xəzinəsi», 3 - «Xosrov və Şirin»)','«Sirlər xəzinəsi» birinci, «Xosrov və Şirin» ikinci, «İskəndərnamə» isə sonuncu poemadır.',array['2 - 3 - 1','1 - 2 - 3','3 - 2 - 1','2 - 1 - 3'],1),
('edeb10-nizami#21','edebiyyat','edeb-10-nizami',3,2,'Aşağıdakı «poema - qəhrəman» cütlüklərindən hansı düzgündür?','«Yeddi gözəl»in mərkəzində Bəhram, «İskəndərnamə»də İskəndər dayanır.',array['«Yeddi gözəl» - Bəhram','«Yeddi gözəl» - İskəndər','«İskəndərnamə» - Bəhram','«Xosrov və Şirin» - Qeys'],1),
('edeb10-nizami#22','edebiyyat','edeb-10-nizami',3,2,'Nizami haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','«Xəmsə» beş poemadan ibarətdir.',array['«Xəmsə» dörd poemadan ibarətdir','Nizami Gəncədə yaşamışdır','«İskəndərnamə» iki hissəlidir','Nüşabə Bərdə hökmdarıdır'],1),
('edeb10-nizami#23','edebiyyat','edeb-10-nizami',3,2,'«İskəndərnamə»nin iki hissəsi arasındakı fərq nədir?','Birində fateh, digərində müdrik və peyğəmbər İskəndər verilir.',array['Birində fateh, digərində müdrik İskəndər','Birində müdrik, digərində uşaqlıq illəri','Hər ikisində eyni hadisələr təkrarlanır','Biri nəzmlə, digəri nəsrlə yazılıb'],1),
('edeb10-nizami#24','edebiyyat','edeb-10-nizami',3,2,'Nizaminin saray şairi olmaqdan uzaq durması yaradıcılığına necə təsir etdi?','Fikir müstəqilliyini və hökmdarlara tənqidi baxışını qorumasına imkan verdi.',array['Fikir müstəqilliyini qorudu','Əsərlərinin sayını azaltdı','Onu tarixi mövzudan uzaqlaşdırdı','Dilini xalq dilindən ayırdı'],1),
('edeb10-nizami#25','edebiyyat','edeb-10-nizami',3,2,'Nizaminin poemaları üzrə «obraz - əsər» cütlüyü hansı doğrudur?','Nüşabə «İskəndərnamə»nin, Fərhad «Xosrov və Şirin»in obrazıdır.',array['Nüşabə - «İskəndərnamə»','Nüşabə - «Yeddi gözəl»','Fərhad - «İskəndərnamə»','Bəhram - «Leyli və Məcnun»'],1),
('edeb10-nizami#26','edebiyyat','edeb-10-nizami',3,2,'Nizami və Füzulinin «Leyli və Məcnun» əsərləri arasındakı əsas fərq nədir?','Nizaminin poeması fars, Füzulininki isə Azərbaycan dilindədir.',array['Biri fars, digəri Azərbaycan dilindədir','Biri Azərbaycan, digəri ərəb dilindədir','Hər ikisi eyni dildə yazılıb','Biri poema, digəri dramdır'],1),
('edeb10-nizami#27','edebiyyat','edeb-10-nizami',3,2,'Nizaminin əsərləri haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','«Dəhnamə» Şah İsmayıl Xətayinin əsəridir.',array['«Dəhnamə» Nizaminin poemasıdır','«Yeddi gözəl» Nizaminin poemasıdır','«Sirlər xəzinəsi» ona məxsusdur','«Xosrov və Şirin» «Xəmsə»yə daxildir'],1),
('edeb10-nizami#28','edebiyyat','edeb-10-nizami',3,2,'Aşağıdakı «əsər - əsas ideya» cütlüklərindən hansı düzgündür?','«İskəndərnamə»də ədalətli cəmiyyət axtarışı əsas yer tutur.',array['«İskəndərnamə» - ədalətli cəmiyyət axtarışı','«İskəndərnamə» - tacir sərgüzəşti','«Leyli və Məcnun» - ədalətli cəmiyyət axtarışı','«Sirlər xəzinəsi» - döyüş salnaməsi'],1),
('edeb10-nizami#29','edebiyyat','edeb-10-nizami',3,2,'Nizaminin İskəndəri peyğəmbərlik mərtəbəsinə qaldırmasının səbəbi nədir?','Şair tarixi şəxsiyyət deyil, ideal insan obrazı yaratmaq istəyirdi.',array['İdeal insan obrazı yaratmaq istəyi','Tarixi mənbələri dəqiq təkrarlamaq','Saray sifarişini yerinə yetirmək','Yunan ədəbiyyatını tərcümə etmək'],1),
('edeb10-nizami#30','edebiyyat','edeb-10-nizami',3,2,'Üç şair yaşadıqları dövrün ardıcıllığı ilə necə düzülür? (1 - Nəsimi, 2 - Füzuli, 3 - Nizami)','Nizami XII, Nəsimi XIV-XV, Füzuli isə XVI əsrdə yaşamışdır.',array['3 - 1 - 2','1 - 2 - 3','2 - 3 - 1','1 - 3 - 2'],1),
('edeb10-nizami#31','edebiyyat','edeb-10-nizami',3,2,'Nizami və Xətayi haqqında hansı fikir doğrudur?','Nizami fars dilində, Xətayi isə ana dilində yazmışdır.',array['Biri farsca, digəri ana dilində yazmışdır','Biri ana dilində, digəri ərəbcə yazmışdır','Hər ikisi ana dilində yazmışdır','Hər ikisi ərəb dilində yazmışdır'],1),
('edeb10-nesimi-xetayi#1','edebiyyat','edeb-10-nesimi-xetayi',1,2,'«Sığmazam» qəzəlinin müəllifi kimdir?','Qəzəlin müəllifi İmadəddin Nəsimidir.',array['İmadəddin Nəsimi','Şah İsmayıl Xətayi','Məhəmməd Füzuli','Nizami Gəncəvi'],1),
('edeb10-nesimi-xetayi#2','edebiyyat','edeb-10-nesimi-xetayi',1,2,'Şah İsmayıl Xətayi hansı dövlətin banisidir?','O, Səfəvi dövlətinin banisidir.',array['Səfəvi dövlətinin','Qaraqoyunlu dövlətinin','Şirvanşahlar dövlətinin','Atabəylər dövlətinin'],1),
('edeb10-nesimi-xetayi#3','edebiyyat','edeb-10-nesimi-xetayi',1,2,'«Dəhnamə» əsərinin müəllifi kimdir?','«Dəhnamə» Şah İsmayıl Xətayinin poemasıdır.',array['Şah İsmayıl Xətayi','İmadəddin Nəsimi','Nizami Gəncəvi','Molla Pənah Vaqif'],1),
('edeb10-nesimi-xetayi#4','edebiyyat','edeb-10-nesimi-xetayi',1,2,'Nəsiminin şeirləri hansı vəzndədir?','Nəsimi əruz vəznində yazmışdır.',array['Əruz vəznində','Heca vəznində','Sərbəst şeirdə','Ağ şeirdə'],1),
('edeb10-nesimi-xetayi#5','edebiyyat','edeb-10-nesimi-xetayi',2,2,'Nəsimi hansı təlimin ardıcılı olmuşdur?','O, hürufilik təliminin ardıcılı idi.',array['Hürufiliyin','Nəqşibəndiliyin','Mövləviliyin','Bektaşiliyin'],1),
('edeb10-nesimi-xetayi#6','edebiyyat','edeb-10-nesimi-xetayi',2,2,'Hürufilik təliminin banisi kimdir?','Təlimin banisi Fəzlullah Nəimidir.',array['Fəzlullah Nəimi','Şah İsmayıl','Nizami Gəncəvi','Əhməd Yəsəvi'],1),
('edeb10-nesimi-xetayi#7','edebiyyat','edeb-10-nesimi-xetayi',2,2,'Nəsimi harada edam olunmuşdur?','Şair Hələb şəhərində edam olunmuşdur.',array['Hələbdə','Bağdadda','Təbrizdə','Şamaxıda'],1),
('edeb10-nesimi-xetayi#8','edebiyyat','edeb-10-nesimi-xetayi',2,2,'Nəsimi neçə dildə divan yaratmışdır?','O, Azərbaycan, fars və ərəb dillərində divan yaratmışdır.',array['Üç dildə','Bir dildə','İki dildə','Beş dildə'],1),
('edeb10-nesimi-xetayi#9','edebiyyat','edeb-10-nesimi-xetayi',2,2,'«Sığmazam» qəzəlində şair nəyi tərənnüm edir?','İnsanın böyüklüyünü və kainata sığmayan mənəvi gücünü.',array['İnsanın böyüklüyünü','Var-dövləti','Saray həyatını','Ov səhnələrini'],1),
('edeb10-nesimi-xetayi#10','edebiyyat','edeb-10-nesimi-xetayi',2,2,'Şah İsmayıl Xətayi hansı ildə Səfəvi dövlətinin əsasını qoymuşdur?','Səfəvi dövləti 1501-ci ildə qurulmuşdur.',array['1501','1405','1600','1747'],1),
('edeb10-nesimi-xetayi#11','edebiyyat','edeb-10-nesimi-xetayi',2,2,'Xətayinin dövlətinin paytaxtı hansı şəhər idi?','Paytaxt Təbriz idi.',array['Təbriz','Bakı','Gəncə','Şamaxı'],1),
('edeb10-nesimi-xetayi#12','edebiyyat','edeb-10-nesimi-xetayi',2,2,'«Dəhnamə» sözünün mənası nədir?','«Dəhnamə» on məktub deməkdir.',array['On məktub','Beş xəzinə','Yeddi gözəl','Üç nəsihət'],1),
('edeb10-nesimi-xetayi#13','edebiyyat','edeb-10-nesimi-xetayi',2,2,'«Dəhnamə» ədəbiyyat tarixində nə ilə əlamətdardır?','Ana dilində yazılmış ilk məhəbbət poemalarındandır.',array['Ana dilində ilk məhəbbət poemalarındandır','İlk satirik poemadır','İlk tarixi romandır','İlk dram əsəridir'],1),
('edeb10-nesimi-xetayi#14','edebiyyat','edeb-10-nesimi-xetayi',2,2,'Xətayi hansı vəznlərdə yazmışdır?','O, həm əruz, həm də heca vəznində yazmışdır.',array['Həm əruz, həm heca vəznində','Ancaq əruz vəznində','Ancaq sərbəst şeirdə','Ancaq nəsrlə'],1),
('edeb10-nesimi-xetayi#15','edebiyyat','edeb-10-nesimi-xetayi',2,2,'Xətayinin müraciət etdiyi xalq şeiri formaları hansılardır?','O, qoşma və gəraylı formalarında da yazmışdır.',array['Qoşma və gəraylı','Sonet və rübai','Qəsidə və mərsiyə','Tapmaca və yanıltmac'],1),
('edeb10-nesimi-xetayi#16','edebiyyat','edeb-10-nesimi-xetayi',2,2,'Nəsimi hansı şəhərdə doğulmuşdur?','Şair Şamaxıda doğulmuşdur.',array['Şamaxıda','Gəncədə','Təbrizdə','Bakıda'],1),
('edeb10-nesimi-xetayi#17','edebiyyat','edeb-10-nesimi-xetayi',2,2,'Nəsiminin şeirlərində insanın ilahi ilə vəhdəti fikri necə ifadə olunur?','Bu fikir «ənəlhəq» ifadəsi ilə verilir.',array['«Ənəlhəq» ifadəsi ilə','Döyüş çağırışı ilə','Ticarət qaydası ilə','Təbiət təsviri ilə'],1),
('edeb10-nesimi-xetayi#18','edebiyyat','edeb-10-nesimi-xetayi',2,2,'Şah İsmayıl şeirlərini hansı təxəllüslə yazmışdır?','O, Xətayi təxəllüsü ilə yazmışdır.',array['Xətayi','Füzuli','Nəsimi','Vaqif'],1),
('edeb10-nesimi-xetayi#19','edebiyyat','edeb-10-nesimi-xetayi',2,2,'Nəsimi yaradıcılığının əsas mövzusu nədir?','İnsan və onun mənəvi azadlığıdır.',array['İnsan və mənəvi azadlıq','Saray mərasimləri','Ticarət yolları','Ov ənənəsi'],1),
('edeb10-nesimi-xetayi#20','edebiyyat','edeb-10-nesimi-xetayi',3,2,'Aşağıdakı «şair - əsər» cütlüklərindən hansı düzgündür?','«Sığmazam» Nəsiminin, «Dəhnamə» isə Xətayinin əsəridir.',array['Nəsimi - «Sığmazam»','Xətayi - «Sığmazam»','Nəsimi - «Dəhnamə»','Nizami - «Dəhnamə»'],1),
('edeb10-nesimi-xetayi#21','edebiyyat','edeb-10-nesimi-xetayi',3,2,'Nəsimi haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Şair Hələbdə edam olunmuşdur, Bağdadda deyil.',array['Nəsimi Bağdadda edam olunmuşdur','Nəsimi hürufilik təliminin ardıcılı idi','«Sığmazam» onun qəzəlidir','O, üç dildə divan yaratmışdır'],1),
('edeb10-nesimi-xetayi#22','edebiyyat','edeb-10-nesimi-xetayi',3,2,'Nəsimi ilə Xətayinin yaradıcılığındakı əsas fərq nədir?','Xətayi əruzla yanaşı heca vəzninə də müraciət etmişdir.',array['Xətayi heca vəzninə də müraciət etmişdir','Nəsimi heca vəznində divan yaratmışdır','Hər ikisi eyni vəzndə yazmışdır','Xətayi əsərlərini fars dilində yazmışdır'],1),
('edeb10-nesimi-xetayi#23','edebiyyat','edeb-10-nesimi-xetayi',3,2,'Nəsiminin edam olunmasının səbəbi nə idi?','Onun yaydığı hürufilik təlimi dövrün rəsmi dairələrində küfr sayılırdı.',array['Hürufilik təliminin küfr sayılması','Saraya vergi verməməsi','Yad dövlətlə ticarət etməsi','Şeirlərini fars dilində yazması'],1),
('edeb10-nesimi-xetayi#24','edebiyyat','edeb-10-nesimi-xetayi',3,2,'Aşağıdakı üç hadisə zaman ardıcıllığı ilə necə düzülür? (1 - Səfəvi dövlətinin qurulması, 2 - Nəsiminin edamı, 3 - Nəsiminin doğulması)','Nəsimi 1369-cu ildə doğulub, 1417-ci ildə edam olunub, Səfəvi dövləti isə 1501-ci ildə qurulub.',array['3 - 2 - 1','1 - 2 - 3','2 - 3 - 1','3 - 1 - 2'],1),
('edeb10-nesimi-xetayi#25','edebiyyat','edeb-10-nesimi-xetayi',3,2,'Aşağıdakı «şəxs - fəaliyyət» cütlüklərindən hansı doğrudur?','Xətayi həm şair, həm dövlət başçısı olmuşdur.',array['Xətayi - şair və dövlət başçısı','Nəsimi - şair və dövlət başçısı','Xətayi - hürufiliyin banisi','Fəzlullah Nəimi - Səfəvi hökmdarı'],1),
('edeb10-nesimi-xetayi#26','edebiyyat','edeb-10-nesimi-xetayi',3,2,'Nəsimi və Xətayinin doğulduğu yerlər haqqında hansı fikir doğrudur?','Nəsimi Şamaxıda, Xətayi isə Ərdəbildə doğulmuşdur.',array['Nəsimi Şamaxıda, Xətayi Ərdəbildə','Nəsimi Ərdəbildə, Xətayi Şamaxıda','Nəsimi Təbrizdə, Xətayi Şamaxıda','Nəsimi Ərdəbildə, Xətayi Təbrizdə'],1),
('edeb10-nesimi-xetayi#27','edebiyyat','edeb-10-nesimi-xetayi',3,2,'Xətayi haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','«Dəhnamə» ana dilində - Azərbaycan dilində yazılmışdır.',array['«Dəhnamə» fars dilində yazılmışdır','Xətayi Səfəvi dövlətinin banisidir','«Dəhnamə» on məktubdan ibarətdir','O, qoşma və gəraylı yazmışdır'],1),
('edeb10-nesimi-xetayi#28','edebiyyat','edeb-10-nesimi-xetayi',3,2,'Nəsimi və Xətayinin əsərləri üzrə «əsər - janr» cütlüyü hansı doğrudur?','«Dəhnamə» poema, «Sığmazam» isə qəzəldir.',array['«Dəhnamə» - poema','«Sığmazam» - poema','«Dəhnamə» - qəzəl','«Sığmazam» - dastan'],1),
('edeb10-nesimi-xetayi#29','edebiyyat','edeb-10-nesimi-xetayi',3,2,'Xətayinin ana dilində yazmasının ədəbiyyat tarixi üçün əhəmiyyəti nədir?','Ana dilli şeir dövlət səviyyəsində dəstək qazanıb gücləndi.',array['Ana dilli şeirin güclənməsi','Fars şeirinin yayılması','Ərəb dilinin geniş öyrənilməsi','Tərcümə ənənəsinin başlanması'],1),
('edeb10-nesimi-xetayi#30','edebiyyat','edeb-10-nesimi-xetayi',3,2,'Aşağıdakı «əsər - yazıldığı dil» cütlüklərindən hansı doğrudur?','«Dəhnamə» Azərbaycan, «Xəmsə» isə fars dilindədir.',array['«Dəhnamə» - Azərbaycan dili','«Xəmsə» - Azərbaycan dili','«Dəhnamə» - ərəb dili','«İskəndərnamə» - Azərbaycan dili'],1),
('edeb10-nesimi-xetayi#31','edebiyyat','edeb-10-nesimi-xetayi',3,2,'Nizami və Nəsiminin yaşadığı dövr haqqında hansı fikir doğrudur?','Nizami XII, Nəsimi isə XIV-XV əsrdə yaşamışdır.',array['Nizami XII, Nəsimi XIV-XV əsrdə','Nəsimi XII, Nizami XIV-XV əsrdə','Hər ikisi XII əsrdə yaşamışdır','Hər ikisi XV əsrdə yaşamışdır'],1),
('edeb10-fuzuli#1','edebiyyat','edeb-10-fuzuli',1,3,'Azərbaycan dilində «Leyli və Məcnun» poemasının müəllifi kimdir?','Ana dilində bu poemanı Məhəmməd Füzuli yazmışdır.',array['Məhəmməd Füzuli','Nizami Gəncəvi','İmadəddin Nəsimi','Şah İsmayıl Xətayi'],1),
('edeb10-fuzuli#2','edebiyyat','edeb-10-fuzuli',1,3,'Füzuli neçə dildə divan yaratmışdır?','Şair Azərbaycan, fars və ərəb dillərində divan yaratmışdır.',array['Üç dildə','İki dildə','Dörd dildə','Bir dildə'],1),
('edeb10-fuzuli#3','edebiyyat','edeb-10-fuzuli',1,3,'Füzuli yaradıcılığının mərkəzində hansı mövzu dayanır?','Şairin yaradıcılığının mərkəzində eşq və məhəbbət dayanır.',array['Eşq və məhəbbət','Ov və səyahət','Ticarət işləri','Memarlıq sənəti'],1),
('edeb10-fuzuli#4','edebiyyat','edeb-10-fuzuli',1,3,'«Şikayətnamə» hansı formada yazılmışdır?','«Şikayətnamə» nəsrlə yazılmışdır.',array['Nəsrlə','Qəzəl formasında','Qoşma formasında','Dastan formasında'],1),
('edeb10-fuzuli#5','edebiyyat','edeb-10-fuzuli',2,3,'Füzulinin poemasında Məcnuna kömək etməyə çalışan obraz kimdir?','Nofəl Məcnuna kömək etməyə çalışan obrazdır.',array['Nofəl','İbn Səlam','Zeyd','Bəhram'],1),
('edeb10-fuzuli#6','edebiyyat','edeb-10-fuzuli',2,3,'Leylini ailəsi kimə ərə verir?','Leyli İbn Səlama ərə verilir.',array['İbn Səlam','Nofəl','Qeys','Zeyd'],1),
('edeb10-fuzuli#7','edebiyyat','edeb-10-fuzuli',2,3,'«Məni candan usandırdı» qəzəlinin rədifi hansıdır?','Qəzəlin rədifi «cananım mənim»dir.',array['«cananım mənim»','«gözüm mənim»','«yarım mənim»','«dostum mənim»'],1),
('edeb10-fuzuli#8','edebiyyat','edeb-10-fuzuli',2,3,'«Şikayətnamə»də şair kimi tənqid edir?','Əsərdə rüşvətxor məmurlar və süründürməçilik tənqid olunur.',array['Rüşvətxor məmurları','Kənd əməkçilərini','Aşıq sənətkarlarını','Karvan tacirlərini'],1),
('edeb10-fuzuli#9','edebiyyat','edeb-10-fuzuli',2,3,'Füzulinin «Hədiqətüs-süəda» əsəri hansı formadadır?','Bu, nəsrlə yazılmış əsərdir.',array['Nəsr əsəridir','Qəzəllər toplusudur','Dastandır','Dramdır'],1),
('edeb10-fuzuli#10','edebiyyat','edeb-10-fuzuli',2,3,'Füzuli hansı bölgədə yaşayıb-yaratmışdır?','Şair Kərbəla və Bağdad bölgəsində yaşamışdır.',array['Kərbəla və Bağdad bölgəsində','Gəncə və Bərdədə','Şamaxı və Bakıda','Təbriz və Ərdəbildə'],1),
('edeb10-fuzuli#11','edebiyyat','edeb-10-fuzuli',2,3,'Füzulinin «Leyli və Məcnun» poeması hansı ənənənin davamıdır?','Nizamidən gələn xəmsəçilik və məsnəvi ənənəsinin davamıdır.',array['Xəmsəçilik və məsnəvi ənənəsinin','Aşıq dastanı ənənəsinin','Xalq lətifəsi ənənəsinin','Salnamə yazma ənənəsinin'],1),
('edeb10-fuzuli#12','edebiyyat','edeb-10-fuzuli',2,3,'Füzulinin poemasında eşq necə şərh olunur?','Dünyəvi eşq tədricən ilahi eşq səviyyəsinə yüksəlir.',array['Dünyəvi eşqdən ilahi eşqə yüksəlir','Sadə məişət hadisəsi kimi','Ticarət razılaşması kimi','Döyüş səbəbi kimi'],1),
('edeb10-fuzuli#13','edebiyyat','edeb-10-fuzuli',2,3,'Üzeyir Hacıbəyli hansı operanı Füzulinin sözləri əsasında yazmışdır?','Bəstəkar «Leyli və Məcnun» operasını yazmışdır.',array['«Leyli və Məcnun»','«Koroğlu»','«Arşın mal alan»','«O olmasın, bu olsun»'],1),
('edeb10-fuzuli#14','edebiyyat','edeb-10-fuzuli',2,3,'Həmin opera ədəbiyyat və musiqi tarixində nə ilə əlamətdardır?','O, Şərqdə yazılmış ilk operadır.',array['Şərqdə ilk opera olması','İlk balet olması','İlk kinofilm olması','İlk xalq mahnısı olması'],1),
('edeb10-fuzuli#15','edebiyyat','edeb-10-fuzuli',2,3,'Füzuli hansı əsrdə yaşamışdır?','Şair XVI əsrdə yaşamışdır.',array['XVI əsrdə','XII əsrdə','XIX əsrdə','XIV əsrdə'],1),
('edeb10-fuzuli#16','edebiyyat','edeb-10-fuzuli',2,3,'«Bəngü Badə» əsəri hansı səciyyə daşıyır?','Əsər alleqorik səciyyəlidir.',array['Alleqorik','Sənədli','Tarixi salnamə','Elmi-praktik'],1),
('edeb10-fuzuli#17','edebiyyat','edeb-10-fuzuli',2,3,'Füzulinin ana dilində yazdığı şeirlərin dili haqqında nə demək olar?','Ana dilində yüksək bədii səviyyəli, obrazlı dil yaratmışdır.',array['Yüksək bədii səviyyəli obrazlı dil','Yalnız ərəb sözlərindən ibarət','Sadə gündəlik danışıq dili','Tərcümə dilinin izləri'],1),
('edeb10-fuzuli#18','edebiyyat','edeb-10-fuzuli',2,3,'Məcnunun çöllərə düşməsinin səbəbi nədir?','O, Leylidən ayrı salındığı üçün ağlını itirib çöllərə düşür.',array['Leylidən ayrı salınması','Ticarətdə uğursuzluğu','Döyüşdə məğlub olması','Ailəsinin köçüb getməsi'],1),
('edeb10-fuzuli#19','edebiyyat','edeb-10-fuzuli',2,3,'Poemanın sonunda aşiqlərin taleyi necə olur?','Hər ikisi həlak olur, eşqləri isə əbədiləşir.',array['Hər ikisi həlak olur','Evlənib xoşbəxt olurlar','Ayrı ölkələrə köçürlər','Bir-birini unudurlar'],1),
('edeb10-fuzuli#20','edebiyyat','edeb-10-fuzuli',3,3,'«Leyli və Məcnun» poemasında «obraz - rol» cütlüklərindən hansı düzgündür?','Nofəl Məcnunun himayədarı, İbn Səlam isə Leylinin əridir.',array['Nofəl - Məcnunun himayədarı','İbn Səlam - Məcnunun himayədarı','Nofəl - Leylinin əri','Zeyd - Leylinin atası'],1),
('edeb10-fuzuli#21','edebiyyat','edeb-10-fuzuli',3,3,'Füzuli haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','«Xəmsə» Nizami Gəncəviyə məxsusdur.',array['«Xəmsə» külliyyatının müəllifidir','«Şikayətnamə» onun nəsr əsəridir','O, üç dildə divan yaratmışdır','«Leyli və Məcnun» onun poemasıdır'],1),
('edeb10-fuzuli#22','edebiyyat','edeb-10-fuzuli',3,3,'Füzulinin qəzəli ilə poeması arasındakı əsas fərq nədir?','Qəzəl kiçik lirik formadır, poema isə süjetli iri əsərdir.',array['Biri kiçik lirik forma, digəri süjetli iri əsərdir','Biri süjetli iri əsər, digəri kiçik lirik formadır','Hər ikisi eyni həcmdə əsərlərdir','Biri nəsrlə, digəri nəzmlə yazılır'],1),
('edeb10-fuzuli#23','edebiyyat','edeb-10-fuzuli',3,3,'«Şikayətnamə»nin yazılmasına səbəb olan hadisə nə idi?','Şairə təyin edilmiş vəzifə haqqının verilməməsi.',array['Vəzifə haqqının verilməməsi','Kitabının çap olunmaması','Vətənindən sürgün edilməsi','Saraya dəvət olunmaması'],1),
('edeb10-fuzuli#24','edebiyyat','edeb-10-fuzuli',3,3,'Füzulinin əsərləri üzrə «əsər - janr» cütlüklərindən hansı doğrudur?','«Şikayətnamə» nəsr əsəri, «Leyli və Məcnun» isə poemadır.',array['«Şikayətnamə» - nəsr əsəri','«Şikayətnamə» - qəzəl','«Leyli və Məcnun» - nəsr əsəri','«Bəngü Badə» - qəzəl'],1),
('edeb10-fuzuli#25','edebiyyat','edeb-10-fuzuli',3,3,'Aşağıdakı üç hadisə zaman ardıcıllığı ilə necə düzülür? (1 - Üzeyir Hacıbəylinin operası, 2 - Füzulinin poeması, 3 - Nizaminin poeması)','Nizami XII əsrdə, Füzuli XVI əsrdə yazmış, opera isə 1908-ci ildə səhnəyə qoyulmuşdur.',array['3 - 2 - 1','1 - 2 - 3','2 - 3 - 1','2 - 1 - 3'],1),
('edeb10-fuzuli#26','edebiyyat','edeb-10-fuzuli',3,3,'Füzuli və Nəsiminin yazdıqları dillər haqqında hansı fikir doğrudur?','Hər ikisi Azərbaycan, fars və ərəb dillərində divan yaratmışdır.',array['Hər ikisi üç dildə divan yaratmışdır','Füzuli iki, Nəsimi bir dildə yazmışdır','Hər ikisi ana dilində yazmamışdır','Füzuli ana dilində əsər yazmamışdır'],1),
('edeb10-fuzuli#27','edebiyyat','edeb-10-fuzuli',3,3,'Poemanın məzmunu haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Poemanın sonunda aşiqlər qovuşmur, hər ikisi həlak olur.',array['Sonda aşiqlər evlənib xoşbəxt olur','Məcnunun əsl adı Qeysdir','Nofəl Məcnuna kömək etməyə çalışır','Poema əruz vəznində yazılıb'],1),
('edeb10-fuzuli#28','edebiyyat','edeb-10-fuzuli',3,3,'Aşağıdakı «şair - yaşadığı əsr» cütlüklərindən hansı düzgündür?','Füzuli XVI, Nizami XII, Nəsimi isə XIV-XV əsrdə yaşamışdır.',array['Füzuli - XVI əsr','Füzuli - XII əsr','Nizami - XVI əsr','Nəsimi - XVI əsr'],1),
('edeb10-fuzuli#29','edebiyyat','edeb-10-fuzuli',3,3,'Füzulinin poemasının Azərbaycan ədəbiyyatı üçün əhəmiyyəti nədir?','Ana dilində yazılmış ilk kamil məhəbbət poemasıdır.',array['Ana dilində ilk məhəbbət poeması','Ədəbiyyatda ilk satirik əsər','Ədəbiyyatda ilk nəsr nümunəsi','Ədəbiyyatda ilk dram əsəri'],1),
('edeb10-fuzuli#30','edebiyyat','edeb-10-fuzuli',3,3,'Füzulinin əsərləri üzrə «əsər - müəllif» cütlüyü hansı doğrudur?','«Hədiqətüs-süəda» Füzulinin, «Sığmazam» isə Nəsiminin əsəridir.',array['«Hədiqətüs-süəda» - Füzuli','«Hədiqətüs-süəda» - Nəsimi','«Sığmazam» - Füzuli','«Dəhnamə» - Füzuli'],1),
('edeb10-fuzuli#31','edebiyyat','edeb-10-fuzuli',3,3,'Aşağıdakı «əsər - bəstəkar» cütlüklərindən hansı düzgündür?','«Leyli və Məcnun» operasını Üzeyir Hacıbəyli bəstələmişdir.',array['«Leyli və Məcnun» operası - Üzeyir Hacıbəyli','«Leyli və Məcnun» operası - Müslüm Maqomayev','«Koroğlu» operası - Məhəmməd Füzuli','«Arşın mal alan» - Nizami Gəncəvi'],1),
('edeb10-koroglu-vaqif#1','edebiyyat','edeb-10-koroglu-vaqif',1,3,'«Koroğlu» dastanının baş qəhrəmanının əsl adı nədir?','Koroğlunun əsl adı Rövşəndir.',array['Rövşən','Eyvaz','Həmzə','Dəmirçioğlu'],1),
('edeb10-koroglu-vaqif#2','edebiyyat','edeb-10-koroglu-vaqif',1,3,'Koroğlunun qərargahı necə adlanır?','Koroğlunun qərargahı Çənlibeldir.',array['Çənlibel','Şuşa','Bərdə','Ərzurum'],1),
('edeb10-koroglu-vaqif#3','edebiyyat','edeb-10-koroglu-vaqif',1,3,'Molla Pənah Vaqif hansı vəznə üstünlük vermişdir?','Vaqif heca vəznində yazmışdır.',array['Heca vəzninə','Əruz vəzninə','Sərbəst şeirə','Ağ şeirə'],1),
('edeb10-koroglu-vaqif#4','edebiyyat','edeb-10-koroglu-vaqif',1,3,'«Pəri» şeirinin müəllifi kimdir?','«Pəri» Molla Pənah Vaqifin qoşmasıdır.',array['Molla Pənah Vaqif','Məhəmməd Füzuli','İmadəddin Nəsimi','Qasım bəy Zakir'],1),
('edeb10-koroglu-vaqif#5','edebiyyat','edeb-10-koroglu-vaqif',2,3,'Koroğlunun atasının adı nədir?','Koroğlunun atası Alı kişidir.',array['Alı kişi','Həsən xan','Cəfər paşa','Bəlli Əhməd'],1),
('edeb10-koroglu-vaqif#6','edebiyyat','edeb-10-koroglu-vaqif',2,3,'Alı kişinin gözlərini kim kor etdirmişdir?','Onun gözlərini Həsən xan kor etdirmişdir.',array['Həsən xan','Cəfər paşa','Eyvaz','Həmzə'],1),
('edeb10-koroglu-vaqif#7','edebiyyat','edeb-10-koroglu-vaqif',2,3,'Koroğlunun atlarının adları hansılardır?','Onun atları Qırat və Düratdır.',array['Qırat və Dürat','Ağqır və Boz','Şəbdiz və Gülgün','Düldül və Rəxş'],1),
('edeb10-koroglu-vaqif#8','edebiyyat','edeb-10-koroglu-vaqif',2,3,'Koroğlunun həyat yoldaşının adı nədir?','Koroğlunun həyat yoldaşı Nigar xanımdır.',array['Nigar xanım','Burla xatun','Leyli','Pəri'],1),
('edeb10-koroglu-vaqif#9','edebiyyat','edeb-10-koroglu-vaqif',2,3,'«Həmzənin Qıratı qaçırması» qolunda Həmzə hansı cildə girir?','Həmzə çoban cildinə girərək Çənlibelə soxulur.',array['Çoban cildinə','Tacir cildinə','Dərviş cildinə','Elçi cildinə'],1),
('edeb10-koroglu-vaqif#10','edebiyyat','edeb-10-koroglu-vaqif',2,3,'Koroğlu atını geri qaytarmaq üçün hansı cildə girir?','Koroğlu aşıq cildinə girərək düşmən sarayına daxil olur.',array['Aşıq cildinə','Tacir cildinə','Çoban cildinə','Əsgər cildinə'],1),
('edeb10-koroglu-vaqif#11','edebiyyat','edeb-10-koroglu-vaqif',2,3,'Koroğlu obrazının səciyyəvi cəhəti nədir?','O, həm igid döyüşçü, həm də saz çalıb şeir deyən aşıqdır.',array['Həm igid, həm aşıq olması','Karvan taciri olması','Saray məmuru olması','Din xadimi olması'],1),
('edeb10-koroglu-vaqif#12','edebiyyat','edeb-10-koroglu-vaqif',2,3,'«Koroğlu» dastanındakı bölmələr necə adlanır?','Dastanın bölmələri qol adlanır.',array['Qol','Boy','Bənd','Fəsil'],1),
('edeb10-koroglu-vaqif#13','edebiyyat','edeb-10-koroglu-vaqif',2,3,'Vaqif hansı xanlıqda vəzir olmuşdur?','O, Qarabağ xanlığında vəzir olmuşdur.',array['Qarabağ xanlığında','Şirvan xanlığında','Quba xanlığında','Naxçıvan xanlığında'],1),
('edeb10-koroglu-vaqif#14','edebiyyat','edeb-10-koroglu-vaqif',2,3,'Vaqif hansı şəhərdə yaşayıb fəaliyyət göstərmişdir?','Şair Şuşada yaşayıb fəaliyyət göstərmişdir.',array['Şuşada','Gəncədə','Şamaxıda','Bakıda'],1),
('edeb10-koroglu-vaqif#15','edebiyyat','edeb-10-koroglu-vaqif',2,3,'Vaqif şeirlərində gözəlliyi necə təsvir edir?','O, real, yerli gözəlləri adları ilə təsvir edir.',array['Real, yerli gözəlləri','Yalnız xəyali obrazları','Mifik varlıqları','Qədim hökmdarları'],1),
('edeb10-koroglu-vaqif#16','edebiyyat','edeb-10-koroglu-vaqif',2,3,'Vaqifin hansı şairlə deyişməsi məşhurdur?','Onun Molla Vəli Vidadi ilə deyişməsi məşhurdur.',array['Molla Vəli Vidadi ilə','Qasım bəy Zakirlə','Aşıq Ələsgərlə','Seyid Əzim Şirvani ilə'],1),
('edeb10-koroglu-vaqif#17','edebiyyat','edeb-10-koroglu-vaqif',2,3,'Vaqifin «Görmədim» əsəri hansı şeir formasındadır?','«Görmədim» müxəmməs formasındadır.',array['Müxəmməs','Qəzəl','Rübai','Sonet'],1),
('edeb10-koroglu-vaqif#18','edebiyyat','edeb-10-koroglu-vaqif',2,3,'Vaqif Azərbaycan şeirində hansı istiqamətin banisi sayılır?','O, realist şeirin banisi sayılır.',array['Realizmin','Romantizmin','Simvolizmin','Klassisizmin'],1),
('edeb10-koroglu-vaqif#19','edebiyyat','edeb-10-koroglu-vaqif',2,3,'Vaqifin həyatı necə sona çatmışdır?','Şair 1797-ci ildə Şuşada edam edilmişdir.',array['Şuşada edam edilmişdir','Sürgündə vəfat etmişdir','Uzun ömür sürüb Bakıda vəfat etmişdir','Xaricə mühacirət etmişdir'],1),
('edeb10-koroglu-vaqif#20','edebiyyat','edeb-10-koroglu-vaqif',3,3,'«Koroğlu» dastanında «obraz - rol» cütlüklərindən hansı düzgündür?','Alı kişi Koroğlunun atası, Nigar xanım isə həyat yoldaşıdır.',array['Alı kişi - Koroğlunun atası','Həsən xan - Koroğlunun atası','Alı kişi - Koroğlunun dəlisi','Nigar xanım - Koroğlunun anası'],1),
('edeb10-koroglu-vaqif#21','edebiyyat','edeb-10-koroglu-vaqif',3,3,'«Koroğlu» dastanı haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Koroğlunun qərargahı Çənlibeldir.',array['Koroğlunun qərargahı Şuşadır','Koroğlunun atı Qıratdır','Dastan qollardan ibarətdir','Koroğlu saz çalıb şeir deyir'],1),
('edeb10-koroglu-vaqif#22','edebiyyat','edeb-10-koroglu-vaqif',3,3,'«Koroğlu» dastanında qəhrəmanlıq nəyin uğrunda göstərilir?','Zülmə qarşı, elin haqqı və ədalət uğrunda göstərilir.',array['Zülmə qarşı, elin haqqı uğrunda','Şəxsi var-dövlət uğrunda','Ticarət yolları uğrunda','Saray vəzifəsi uğrunda'],1),
('edeb10-koroglu-vaqif#23','edebiyyat','edeb-10-koroglu-vaqif',3,3,'Koroğlunun Həsən xana qarşı üsyanının səbəbi nədir?','Həsən xan onun atası Alı kişinin gözlərini kor etdirmişdi.',array['Atasının gözlərinin kor edilməsi','Atının oğurlanması','Torpaqlarının əlindən alınması','Dostunun sürgün edilməsi'],1),
('edeb10-koroglu-vaqif#24','edebiyyat','edeb-10-koroglu-vaqif',3,3,'Dastandakı üç hadisə zaman ardıcıllığı ilə necə düzülür? (1 - Çənlibelin qurulması, 2 - Qıratın oğurlanması, 3 - Alı kişinin kor edilməsi)','Əvvəlcə Alı kişi kor edilir, sonra Çənlibel qurulur, daha sonra Qırat oğurlanır.',array['3 - 1 - 2','1 - 2 - 3','2 - 1 - 3','1 - 3 - 2'],1),
('edeb10-koroglu-vaqif#25','edebiyyat','edeb-10-koroglu-vaqif',3,3,'Aşağıdakı «şəxs - vəzifə» cütlüklərindən hansı doğrudur?','Vaqif Qarabağ xanlığında vəzir vəzifəsində olmuşdur.',array['Vaqif - Qarabağ xanlığının vəziri','Vidadi - Qarabağ xanlığının vəziri','Vaqif - Şirvan xanlığının vəziri','Zakir - Qarabağ xanlığının vəziri'],1),
('edeb10-koroglu-vaqif#26','edebiyyat','edeb-10-koroglu-vaqif',3,3,'Vaqif haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Vaqif heca vəznində yazmışdır, əruzda deyil.',array['Vaqif əruz vəzninə üstünlük vermişdir','Vaqif Şuşada yaşayıb fəaliyyət göstərmişdir','«Pəri» onun qoşmasıdır','O, realist şeirin banisi sayılır'],1),
('edeb10-koroglu-vaqif#27','edebiyyat','edeb-10-koroglu-vaqif',3,3,'Vaqif və Füzulinin şeir vəzni haqqında hansı fikir doğrudur?','Vaqif heca, Füzuli isə əruz vəznində yazmışdır.',array['Vaqif hecada, Füzuli əruzda yazmışdır','Vaqif əruzda, Füzuli hecada yazmışdır','Hər ikisi heca vəznində yazmışdır','Hər ikisi əruz vəznində yazmışdır'],1),
('edeb10-koroglu-vaqif#28','edebiyyat','edeb-10-koroglu-vaqif',3,3,'Vaqifin əsərləri üzrə «əsər - forma» cütlüyü hansı düzgündür?','«Görmədim» müxəmməs, «Pəri» isə qoşmadır.',array['«Görmədim» - müxəmməs','«Pəri» - müxəmməs','«Görmədim» - qəzəl','«Sığmazam» - qoşma'],1),
('edeb10-koroglu-vaqif#29','edebiyyat','edeb-10-koroglu-vaqif',3,3,'Vaqif şeirinin xalq arasında geniş yayılmasının səbəbi nədir?','Sadə xalq dili və heca vəzni onu hamıya anlaşıqlı edirdi.',array['Sadə xalq dili və heca vəzni','Fars dilində yazılması','Saray mühitinə bağlılığı','Mürəkkəb əruz quruluşu'],1),
('edeb10-koroglu-vaqif#30','edebiyyat','edeb-10-koroglu-vaqif',3,3,'Xalq yaradıcılığı haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','«Koroğlu» qəhrəmanlıq dastanıdır, məhəbbət dastanı deyil.',array['«Koroğlu» məhəbbət dastanıdır','«Koroğlu» qollardan ibarətdir','Nigar xanım dastanın obrazıdır','Dəlilər Çənlibeldə toplaşır'],1),
('edeb10-koroglu-vaqif#31','edebiyyat','edeb-10-koroglu-vaqif',3,3,'Erkən yeni dövr əsərləri üzrə «əsər - növ» cütlüyü hansı doğrudur?','«Koroğlu» qəhrəmanlıq dastanı, «Pəri» isə qoşmadır.',array['«Koroğlu» - qəhrəmanlıq dastanı','«Koroğlu» - məhəbbət dastanı','«Pəri» - qəhrəmanlıq dastanı','«Dəhnamə» - qəhrəmanlıq dastanı'],1),
('edeb10-axundzade#1','edebiyyat','edeb-10-axundzade',1,4,'Mirzə Fətəli Axundzadə Azərbaycan ədəbiyyatında hansı sahənin banisidir?','O, Azərbaycan dramaturgiyasının banisidir.',array['Dramaturgiyanın','Qəzəlin','Dastanın','Bayatının'],1),
('edeb10-axundzade#2','edebiyyat','edeb-10-axundzade',1,4,'«Aldanmış kəvakib» hansı janrdadır?','Əsər povest - nəsr əsəridir.',array['Povest','Komediya','Qəzəl','Dastan'],1),
('edeb10-axundzade#3','edebiyyat','edeb-10-axundzade',1,4,'Axundzadə neçə komediya yazmışdır?','O, altı komediya yazmışdır.',array['Altı','Üç','On','İki'],1),
('edeb10-axundzade#4','edebiyyat','edeb-10-axundzade',1,4,'Mirzə Fətəli Axundzadə hansı şəhərdə doğulmuşdur?','Yazıçı Nuxada - indiki Şəkidə doğulmuşdur.',array['Nuxada','Şuşada','Gəncədə','Bakıda'],1),
('edeb10-axundzade#5','edebiyyat','edeb-10-axundzade',2,4,'Axundzadə ömrünün böyük hissəsini harada keçirmişdir?','O, ömrünün böyük hissəsini Tiflisdə keçirmişdir.',array['Tiflisdə','Təbrizdə','İstanbulda','Peterburqda'],1),
('edeb10-axundzade#6','edebiyyat','edeb-10-axundzade',2,4,'«Müsyö Jordan» komediyasında müsyö Jordan kimdir?','O, Azərbaycana gəlmiş fransız botanik alimidir.',array['Fransız botanik alimi','Yerli tacir','Saray münəccimi','Rus zabiti'],1),
('edeb10-axundzade#7','edebiyyat','edeb-10-axundzade',2,4,'«Müsyö Jordan» komediyasında cadugər obrazı kimdir?','Cadugər obrazı dərviş Məstəli şahdır.',array['Dərviş Məstəli şah','Hatəmxan ağa','Şahbaz bəy','Müsyö Jordan'],1),
('edeb10-axundzade#8','edebiyyat','edeb-10-axundzade',2,4,'Şahbaz bəy hara getmək istəyir?','O, təhsil almaq üçün Parisə getmək istəyir.',array['Parisə','Moskvaya','Tehrana','Bağdada'],1),
('edeb10-axundzade#9','edebiyyat','edeb-10-axundzade',2,4,'Şəhrəbanu xanım Məstəli şahdan nə istəyir?','O, Parisin xarab olmasını, səfərin baş tutmamasını istəyir.',array['Parisin xarab olmasını','Yeni ev tikməsini','Xəzinə tapmasını','Xəstəni sağaltmasını'],1),
('edeb10-axundzade#10','edebiyyat','edeb-10-axundzade',2,4,'«Müsyö Jordan»da tənqid olunan əsas nöqsan nədir?','Cadugərliyə inam və cəhalət tənqid olunur.',array['Cadugərliyə inam və cəhalət','Elmi tədqiqat işi','Ticarətin genişlənməsi','Səyahət həvəsi'],1),
('edeb10-axundzade#11','edebiyyat','edeb-10-axundzade',2,4,'«Aldanmış kəvakib»də hadisələr hansı hökmdarın dövründə keçir?','Hadisələr Şah Abbasın dövründə cərəyan edir.',array['Şah Abbasın','Şah İsmayılın','Nadir şahın','Ağa Məhəmməd şahın'],1),
('edeb10-axundzade#12','edebiyyat','edeb-10-axundzade',2,4,'«Aldanmış kəvakib»də müvəqqəti şah təyin olunan şəxs kimdir?','Müvəqqəti şah təyin olunan Yusif Sərracdır.',array['Yusif Sərrac','Hacı Qara','Heydər bəy','Məstəli şah'],1),
('edeb10-axundzade#13','edebiyyat','edeb-10-axundzade',2,4,'«Aldanmış kəvakib»də nə tənqid olunur?','Ulduz falına, münəccimlərin sözünə kor-koranə inam tənqid olunur.',array['Ulduz falına inam','Ticarətin genişlənməsi','Təhsilin yayılması','Əkinçilik üsulu'],1),
('edeb10-axundzade#14','edebiyyat','edeb-10-axundzade',2,4,'Axundzadə hansı sahədə islahat layihəsi irəli sürmüşdür?','O, əlifba islahatı layihəsi irəli sürmüşdür.',array['Əlifba islahatı','Vergi islahatı','Ordu islahatı','Torpaq islahatı'],1),
('edeb10-axundzade#15','edebiyyat','edeb-10-axundzade',2,4,'«Hacı Qara» komediyasının baş obrazı hansı tipi təmsil edir?','O, xəsis tacir tipini təmsil edir.',array['Xəsis taciri','Fədakar müəllimi','İgid sərkərdəni','Saray şairini'],1),
('edeb10-axundzade#16','edebiyyat','edeb-10-axundzade',2,4,'Axundzadənin fəlsəfi əsəri hansıdır?','«Kəmalüddövlə məktubları» onun fəlsəfi əsəridir.',array['«Kəmalüddövlə məktubları»','«Şikayətnamə»','«Aldanmış kəvakib»','«Dəhnamə»'],1),
('edeb10-axundzade#17','edebiyyat','edeb-10-axundzade',2,4,'Axundzadə komediyalarını hansı illərdə yazmışdır?','Komediyalar 1850-1855-ci illərdə yazılmışdır.',array['1850-1855-ci illərdə','1800-1810-cu illərdə','1890-1900-cü illərdə','1920-1930-cu illərdə'],1),
('edeb10-axundzade#18','edebiyyat','edeb-10-axundzade',2,4,'Axundzadə Tiflisdə hansı vəzifədə çalışmışdır?','O, canişinlik idarəsində tərcüməçi işləmişdir.',array['Tərcüməçi','Həkim','Memar','Sərkərdə'],1),
('edeb10-axundzade#19','edebiyyat','edeb-10-axundzade',2,4,'Axundzadənin komediyaları hansı ədəbi metoda aiddir?','Onun komediyaları realizmə aiddir.',array['Realizmə','Romantizmə','Simvolizmə','Sentimentalizmə'],1),
('edeb10-axundzade#20','edebiyyat','edeb-10-axundzade',3,4,'Axundzadənin əsərləri üzrə «əsər - janr» cütlüyü hansı düzgündür?','«Aldanmış kəvakib» povest, «Hacı Qara» isə komediyadır.',array['«Aldanmış kəvakib» - povest','«Aldanmış kəvakib» - komediya','«Hacı Qara» - povest','«Müsyö Jordan» - povest'],1),
('edeb10-axundzade#21','edebiyyat','edeb-10-axundzade',3,4,'Mirzə Fətəli Axundzadə haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','O, altı komediya yazmışdır.',array['On beş komediya yazmışdır','O, dramaturgiyanın banisi sayılır','«Aldanmış kəvakib» onun povestidir','Ömrünün çoxunu Tiflisdə keçirmişdir'],1),
('edeb10-axundzade#22','edebiyyat','edeb-10-axundzade',3,4,'Axundzadənin komediyaları ilə «Aldanmış kəvakib» arasındakı fərq nədir?','Komediyalar səhnə üçün, povest isə oxucu üçün yazılmışdır.',array['Biri səhnə üçün, digəri oxu üçün yazılıb','Biri oxu üçün, digəri səhnə üçün yazılıb','Hər ikisi səhnə əsəridir','Hər ikisi mənzum əsərdir'],1),
('edeb10-axundzade#23','edebiyyat','edeb-10-axundzade',3,4,'Şəhrəbanu xanımın Məstəli şaha müraciətinin səbəbi nədir?','O, qızının nişanlısının Parisə getməsinin qarşısını almaq istəyir.',array['Nişanlının Parisə getməsinin qarşısını almaq','Ailəsinə var-dövlət qazandırmaq','Xəstə qohumunu sağaltmaq','Torpaq mübahisəsini həll etmək'],1),
('edeb10-axundzade#24','edebiyyat','edeb-10-axundzade',3,4,'Aşağıdakı üç hadisə zaman ardıcıllığı ilə necə düzülür? (1 - komediyaların yazılması, 2 - Axundzadənin doğulması, 3 - «Aldanmış kəvakib»in yazılması)','Axundzadə 1812-ci ildə doğulub, komediyaları 1850-1855-ci illərdə, «Aldanmış kəvakib»i isə 1857-ci ildə yazıb.',array['2 - 1 - 3','1 - 2 - 3','3 - 2 - 1','1 - 3 - 2'],1),
('edeb10-axundzade#25','edebiyyat','edeb-10-axundzade',3,4,'Axundzadənin əsərləri üzrə «obraz - əsər» cütlüyü hansı doğrudur?','Məstəli şah «Müsyö Jordan»ın, Yusif Sərrac «Aldanmış kəvakib»in obrazıdır.',array['Məstəli şah - «Müsyö Jordan»','Məstəli şah - «Hacı Qara»','Yusif Sərrac - «Müsyö Jordan»','Hacı Qara - «Aldanmış kəvakib»'],1),
('edeb10-axundzade#26','edebiyyat','edeb-10-axundzade',3,4,'XIX əsr əsərləri haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','«Hacı Qara» Axundzadənin komediyasıdır.',array['«Hacı Qara» Füzulinin əsəridir','«Müsyö Jordan» komediyadır','«Aldanmış kəvakib» nəsr əsəridir','«Kəmalüddövlə məktubları» fəlsəfi əsərdir'],1),
('edeb10-axundzade#27','edebiyyat','edeb-10-axundzade',3,4,'Axundzadə və Vaqifin ədəbiyyat tarixindəki rolu haqqında hansı fikir doğrudur?','Vaqif realist şeirin, Axundzadə isə dramaturgiyanın banisidir.',array['Biri realist şeirin, digəri dramaturgiyanın banisidir','Biri dramaturgiyanın, digəri qəzəlin banisidir','Hər ikisi dramaturgiyanın banisidir','Hər ikisi realist şeirin banisidir'],1),
('edeb10-axundzade#28','edebiyyat','edeb-10-axundzade',3,4,'Axundzadənin əlifba islahatı təklifinin əsas məqsədi nə idi?','Yazını sadələşdirib savadlanmanı asanlaşdırmaq idi.',array['Savadlanmanı asanlaşdırmaq','Xarici ticarəti genişləndirmək','Saray yazışmasını sadələşdirmək','Şeir vəznini dəyişmək'],1),
('edeb10-axundzade#29','edebiyyat','edeb-10-axundzade',3,4,'Aşağıdakı «əsər - tənqid hədəfi» cütlüklərindən hansı düzgündür?','«Aldanmış kəvakib» ulduz falına inamı, «Hacı Qara» isə xəsisliyi ifşa edir.',array['«Aldanmış kəvakib» - ulduz falına inam','«Müsyö Jordan» - ulduz falına inam','«Aldanmış kəvakib» - xəsislik','«Hacı Qara» - cadugərlik'],1),
('edeb10-axundzade#30','edebiyyat','edeb-10-axundzade',3,4,'«Müsyö Jordan» komediyasında Parisin xarab olması necə izah olunur?','Fransadakı inqilab xəbəri Məstəli şahın caduları ilə təsadüfən üst-üstə düşür.',array['İnqilabla üst-üstə düşən təsadüf kimi','Məstəli şahın həqiqi caduları kimi','Şahbaz bəyin uydurması kimi','Hatəmxan ağanın qərarı kimi'],1),
('edeb10-axundzade#31','edebiyyat','edeb-10-axundzade',3,4,'Maarifçi realizm dövrü haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Bu dövr XIX əsrdə formalaşmışdır.',array['Dövr XX əsrin ortalarında formalaşıb','Axundzadə bu dövrün nümayəndəsidir','Dövrün əsas ideyası maarifçilikdir','«Əkinçi» qəzeti bu dövrdə çıxıb'],1),
('edeb10-maarifci#1','edebiyyat','edeb-10-maarifci',1,4,'«Müsibəti-Fəxrəddin» əsərinin müəllifi kimdir?','Əsərin müəllifi Nəcəf bəy Vəzirovdur.',array['Nəcəf bəy Vəzirov','Qasım bəy Zakir','Seyid Əzim Şirvani','Aşıq Ələsgər'],1),
('edeb10-maarifci#2','edebiyyat','edeb-10-maarifci',1,4,'«Müsibəti-Fəxrəddin» hansı janrdadır?','Əsər faciədir - Azərbaycan ədəbiyyatında ilk faciə sayılır.',array['Faciə','Komediya','Poema','Qəzəl'],1),
('edeb10-maarifci#3','edebiyyat','edeb-10-maarifci',1,4,'Aşıq Ələsgər hansı sənətin nümayəndəsidir?','O, aşıq sənətinin görkəmli nümayəndəsidir.',array['Aşıq sənətinin','Saray şeirinin','Dramaturgiyanın','Nəsrin'],1),
('edeb10-maarifci#4','edebiyyat','edeb-10-maarifci',1,4,'İlk Azərbaycan dilli qəzet hansıdır?','İlk Azərbaycan dilli qəzet «Əkinçi»dir.',array['«Əkinçi»','«Molla Nəsrəddin»','«Füyuzat»','«Kaspi»'],1),
('edeb10-maarifci#5','edebiyyat','edeb-10-maarifci',2,4,'«Əkinçi» qəzeti hansı ildə nəşrə başlamışdır?','Qəzet 1875-ci ildə nəşrə başlamışdır.',array['1875','1905','1850','1920'],1),
('edeb10-maarifci#6','edebiyyat','edeb-10-maarifci',2,4,'«Əkinçi» qəzetinin naşiri kimdir?','Qəzetin naşiri Həsən bəy Zərdabidir.',array['Həsən bəy Zərdabi','Cəlil Məmmədquluzadə','Əli bəy Hüseynzadə','Nəcəf bəy Vəzirov'],1),
('edeb10-maarifci#7','edebiyyat','edeb-10-maarifci',2,4,'Qasım bəy Zakir hansı ədəbi ənənəni davam etdirmişdir?','O, Vaqifin realist şeir ənənəsini davam etdirmişdir.',array['Vaqif ənənəsini','Nizami xəmsəçiliyini','Nəsimi hürufiliyini','Ozan-aşıq dastanı ənənəsini'],1),
('edeb10-maarifci#8','edebiyyat','edeb-10-maarifci',2,4,'Qasım bəy Zakir hansı janrlarda daha güclü olmuşdur?','O, satira və təmsil janrlarında güclü olmuşdur.',array['Satira və təmsildə','Elmi traktatda','Tarixi salnamədə','Musiqili komediyada'],1),
('edeb10-maarifci#9','edebiyyat','edeb-10-maarifci',2,4,'Qasım bəy Zakir kiminlə məktublaşmışdır?','O, Mirzə Fətəli Axundzadə ilə məktublaşmışdır.',array['M.F.Axundzadə ilə','Nizami Gəncəvi ilə','Şah İsmayıl Xətayi ilə','Məhəmməd Füzuli ilə'],1),
('edeb10-maarifci#10','edebiyyat','edeb-10-maarifci',2,4,'Aşıq Ələsgər hansı mahalda doğulmuşdur?','Aşıq Ələsgər Göyçə mahalında doğulmuşdur.',array['Göyçə mahalında','Qarabağda','Şirvanda','Naxçıvanda'],1),
('edeb10-maarifci#11','edebiyyat','edeb-10-maarifci',2,4,'Aşıq Ələsgərin əsas şeir formaları hansılardır?','O, qoşma, gəraylı və təcnis formalarında yazmışdır.',array['Qoşma, gəraylı, təcnis','Qəzəl, qəsidə, rübai','Sonet, ballada, elegiya','Məsnəvi, mərsiyə, mədhiyyə'],1),
('edeb10-maarifci#12','edebiyyat','edeb-10-maarifci',2,4,'Seyid Əzim Şirvani hansı şəhərdə yaşamışdır?','O, Şamaxıda yaşayıb-yaratmışdır.',array['Şamaxıda','Şuşada','Gəncədə','Lənkəranda'],1),
('edeb10-maarifci#13','edebiyyat','edeb-10-maarifci',2,4,'Seyid Əzim Şirvani hansı sahədə fəaliyyət göstərmişdir?','O, maarifçilik və məktəb işi ilə məşğul olmuşdur.',array['Maarifçilik və məktəb işi','Hərbi xidmət','Karvan ticarəti','Memarlıq'],1),
('edeb10-maarifci#14','edebiyyat','edeb-10-maarifci',2,4,'Seyid Əzim Şirvani hansı qəzetlə əməkdaşlıq etmişdir?','O, «Əkinçi» qəzeti ilə əməkdaşlıq etmişdir.',array['«Əkinçi» ilə','«Molla Nəsrəddin» ilə','«Füyuzat» ilə','«Həyat» ilə'],1),
('edeb10-maarifci#15','edebiyyat','edeb-10-maarifci',2,4,'«Müsibəti-Fəxrəddin»in baş qəhrəmanı hansı tipi təmsil edir?','Fəxrəddin maarifçi gənc tipini təmsil edir.',array['Maarifçi gənci','Xəsis taciri','Saray münəccimini','Karvanbaşını'],1),
('edeb10-maarifci#16','edebiyyat','edeb-10-maarifci',2,4,'Fəxrəddinin faciəsinin bilavasitə səbəbi nədir?','O, köhnə adət olan qan davasının qurbanı olur.',array['Qan davası','Ticarət borcu','Uzaq səfər','Ağır xəstəlik'],1),
('edeb10-maarifci#17','edebiyyat','edeb-10-maarifci',2,4,'«Müsibəti-Fəxrəddin» hansı ildə yazılmışdır?','Əsər 1896-cı ildə yazılmışdır.',array['1896','1850','1920','1937'],1),
('edeb10-maarifci#18','edebiyyat','edeb-10-maarifci',2,4,'Nəcəf bəy Vəzirov hansı şəhərdə doğulmuşdur?','Yazıçı Şuşada doğulmuşdur.',array['Şuşada','Şamaxıda','Nuxada','Gəncədə'],1),
('edeb10-maarifci#19','edebiyyat','edeb-10-maarifci',2,4,'Maarifçi realizm dövrünün əsas ideyası nədir?','Maarif və elm vasitəsilə cəmiyyəti islah etmək ideyasıdır.',array['Maarif və elmlə cəmiyyəti islah etmək','Keçmişə qayıtmaq','Xəyali aləmə qaçmaq','Saray həyatını tərənnüm etmək'],1),
('edeb10-maarifci#20','edebiyyat','edeb-10-maarifci',3,4,'XIX əsr şairləri üzrə «əsər - müəllif» cütlüyü hansı düzgündür?','«Dağlar» Aşıq Ələsgərin, «Guş qıl» isə Seyid Əzim Şirvaninindir.',array['«Dağlar» - Aşıq Ələsgər','«Dağlar» - Qasım bəy Zakir','«Guş qıl» - Aşıq Ələsgər','«Müsibəti-Fəxrəddin» - Seyid Əzim Şirvani'],1),
('edeb10-maarifci#21','edebiyyat','edeb-10-maarifci',3,4,'XIX əsr ədəbiyyatı haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','«Müsibəti-Fəxrəddin» faciədir, komediya deyil.',array['«Müsibəti-Fəxrəddin» komediyadır','Aşıq Ələsgər Göyçədə doğulmuşdur','«Əkinçi» 1875-ci ildə nəşrə başlayıb','Zakir satira ustası sayılır'],1),
('edeb10-maarifci#22','edebiyyat','edeb-10-maarifci',3,4,'«Müsibəti-Fəxrəddin»in faciə, «Hacı Qara»nın komediya sayılmasının səbəbi nədir?','Birində qəhrəman həlak olur, digəri isə gülüş doğurur.',array['Birində qəhrəman həlak olur, digərində gülüş doğur','Birində gülüş doğur, digərində qəhrəman həlak olur','Biri nəzmlə, digəri nəsrlə yazılıb','Biri poema, digəri hekayədir'],1),
('edeb10-maarifci#23','edebiyyat','edeb-10-maarifci',3,4,'Fəxrəddinin ölümü ilə müəllif nəyi göstərmək istəyir?','Köhnə adətlərin maarifçi qüvvəni məhv etdiyini göstərir.',array['Köhnə adətlərin maarifçini məhv etdiyini','Ticarətin zərərli olduğunu','Səyahətin təhlükəli olduğunu','Təhsilin lazımsız olduğunu'],1),
('edeb10-maarifci#24','edebiyyat','edeb-10-maarifci',3,4,'Aşağıdakı üç hadisə zaman ardıcıllığı ilə necə düzülür? (1 - «Əkinçi» qəzeti, 2 - «Müsibəti-Fəxrəddin», 3 - «Molla Nəsrəddin» jurnalı)','«Əkinçi» 1875-ci, «Müsibəti-Fəxrəddin» 1896-cı, «Molla Nəsrəddin» isə 1906-cı ildə çıxmışdır.',array['1 - 2 - 3','2 - 1 - 3','3 - 2 - 1','1 - 3 - 2'],1),
('edeb10-maarifci#25','edebiyyat','edeb-10-maarifci',3,4,'XIX əsr maarifçiləri üzrə «şəxs - fəaliyyət» cütlüyü hansı doğrudur?','«Əkinçi»nin naşiri Həsən bəy Zərdabi olmuşdur.',array['Həsən bəy Zərdabi - «Əkinçi»nin naşiri','Nəcəf bəy Vəzirov - «Əkinçi»nin naşiri','Həsən bəy Zərdabi - aşıq sənətkarı','Aşıq Ələsgər - qəzet naşiri'],1),
('edeb10-maarifci#26','edebiyyat','edeb-10-maarifci',3,4,'XIX əsr sənətkarları haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Aşıq şeiri heca vəznindədir, əruzda deyil.',array['Aşıq Ələsgər əruz vəznində yazmışdır','Seyid Əzim Şirvani Şamaxıda yaşamışdır','Zakir Vaqif ənənəsini davam etdirmişdir','Vəzirov «Müsibəti-Fəxrəddin»i yazmışdır'],1),
('edeb10-maarifci#27','edebiyyat','edeb-10-maarifci',3,4,'Aşıq Ələsgər və Seyid Əzim Şirvaninin yaradıcılığı arasındakı fərq nədir?','Biri şifahi aşıq, digəri yazılı ədəbiyyat nümayəndəsidir.',array['Biri şifahi aşıq, digəri yazılı ədəbiyyat nümayəndəsidir','Biri yazılı, digəri şifahi ənənəyə bağlıdır','Hər ikisi şifahi aşıq ənənəsindəndir','Hər ikisi dramaturgiya ilə məşğul olmuşdur'],1),
('edeb10-maarifci#28','edebiyyat','edeb-10-maarifci',3,4,'XIX əsr əsərləri üzrə «əsər - janr» cütlüyü hansı düzgündür?','«Müsibəti-Fəxrəddin» faciə, «Dağlar» isə qoşmadır.',array['«Müsibəti-Fəxrəddin» - faciə','«Müsibəti-Fəxrəddin» - komediya','«Dağlar» - faciə','«Badi-səba» - faciə'],1),
('edeb10-maarifci#29','edebiyyat','edeb-10-maarifci',3,4,'«Əkinçi» qəzetinin nəşrinin ədəbi həyat üçün əhəmiyyəti nədir?','Maarifçi fikrin geniş yayılmasına yol açdı.',array['Maarifçi fikrin geniş yayılmasına yol açdı','Saray şeirinin güclənməsinə səbəb oldu','Aşıq sənətinin yaranmasına gətirdi','Dastan janrının doğulmasına səbəb oldu'],1),
('edeb10-maarifci#30','edebiyyat','edeb-10-maarifci',3,4,'Aşağıdakı «sənətkar - yaşadığı əsr» cütlüklərindən hansı doğrudur?','Aşıq Ələsgər XIX-XX əsrlərdə yaşamışdır.',array['Aşıq Ələsgər - XIX-XX əsrlər','Aşıq Ələsgər - XVI əsr','Nizami Gəncəvi - XIX əsr','Məhəmməd Füzuli - XIX əsr'],1),
('edeb10-maarifci#31','edebiyyat','edeb-10-maarifci',3,4,'Vəzirov və Axundzadənin dramaturgiyadakı rolu haqqında hansı fikir doğrudur?','Axundzadə ilk komediyaları, Vəzirov isə ilk faciəni yazmışdır.',array['Biri ilk komediyaları, digəri ilk faciəni yazıb','Biri ilk faciəni, digəri ilk povesti yazıb','Hər ikisi ilk faciəni yazıb','Hər ikisi ancaq komediya yazıb'],1)
),
ins as (
  insert into public.questions
    (ext_key, owner_type, subject_id, level_id, topic_id, kind,
     body, explanation, difficulty, quarter, status)
  select d.ext, 'platform', s.id, tp.level_id, tp.id, 'single',
         d.body, d.why, d.diff, d.rub, 'published'
    from d
    join public.subjects s on s.slug = d.fenn
    join public.topics   tp on tp.subject_id = s.id and tp.slug = d.topic
  on conflict (ext_key) do update
    set body = excluded.body, explanation = excluded.explanation,
        difficulty = excluded.difficulty, quarter = excluded.quarter,
        topic_id = excluded.topic_id, level_id = excluded.level_id,
        subject_id = excluded.subject_id, status = 'published'
  returning id, ext_key
)
insert into public.question_options (question_id, ord, body, is_correct)
select ins.id, o.ord, o.txt, o.ord = d.correct
  from ins
  join d on d.ext = ins.ext_key,
  lateral unnest(d.opts) with ordinality as o(txt, ord);

do $$
declare n int; k int;
begin
  select count(*) into n from public.questions
   where owner_type = 'platform' and ext_key like 'edeb10-%';
  if n <> 248 then
    raise exception 'Edebiyyat 10 suallari: 248 gozlenilirdi, % tapildi', n;
  end if;
  select count(*) into k from public.questions q
   where q.ext_key like 'edeb10-%'
     and ((select count(*) from public.question_options o
            where o.question_id = q.id) <> 4
       or (select count(*) from public.question_options o
            where o.question_id = q.id and o.is_correct) <> 1);
  if k > 0 then
    raise exception '% sualda variant qurulusu sehvdir', k;
  end if;
  select count(distinct topic_id) into k from public.questions
   where ext_key like 'edeb10-%';
  if k <> 8 then
    raise exception 'movzu sayi 8 deyil: %', k;
  end if;
  --  Her movzuda en azi 12 cetin sual olmalidir ki, muellim BIR
  --  movzudan 10 sualliq cetin test yiga bilsin
  select count(*) into k from (
    select q.topic_id from public.questions q
     where q.ext_key like 'edeb10-%' and q.difficulty = 3
     group by q.topic_id having count(*) < 12) z;
  if k > 0 then
    raise exception '% movzuda 12-den az cetin sual var', k;
  end if;
  raise notice 'Edebiyyat 10 banki: % sual, 8 movzu (her birinde 12 cetin).', n;
end $$;
