-- =====================================================================
--  60_bank_edebiyyat9.sql : EDEBIYYAT 9 BANKI
--
--  BU FAYL ELLE YAZILMIR - tools/edebiyyat9.py yaradir:
--      python3 tools/edebiyyat9.py
--
--  8 movzu x 31 sual = 248.  Her movzuda 4 asan + 15 orta + 12 cetin.
--  ext_key: edeb11-...
--  ON SERT: 58_movzular_edebiyyat9_10.sql islenmis olmalidir.
--  SONRA:   05_grants.sql yeniden islet.
-- =====================================================================

do $$
begin
  if not exists (select 1 from public.topics t join public.subjects s
      on s.id = t.subject_id
     where s.slug = 'edebiyyat' and t.slug in
           ('edeb-9-milli-demokratik', 'edeb-9-dunya')
     having count(*) = 2) then
    raise exception 'ONCE 58_movzular_edebiyyat9_10.sql isledilmelidir.';
  end if;
end $$;

delete from public.question_options o
 using public.questions q
 where o.question_id = q.id
   and q.owner_type = 'platform'
   and q.ext_key like 'edeb9-%';

with d(ext, fenn, topic, diff, rub, body, why, opts, correct) as (values
('edeb9-milli-demokratik#1','edebiyyat','edeb-9-milli-demokratik',1,1,'«Azərbaycan bayrağına» şeirinin müəllifi kimdir?','Şeirin müəllifi Əhməd Cavaddır.',array['Əhməd Cavad','Cəfər Cabbarlı','Səməd Vurğun','Mikayıl Müşfiq'],1),
('edeb9-milli-demokratik#2','edebiyyat','edeb-9-milli-demokratik',1,1,'Milli-demokratik hərəkat dövrü hansı illəri əhatə edir?','Dövr XX əsrin əvvəlindən 1920-ci ilə qədəri əhatə edir.',array['XX əsrin əvvəli - 1920-ci il','1941-1945-ci illər','1960-1990-cı illər','1991-ci ildən sonrakı illər'],1),
('edeb9-milli-demokratik#3','edebiyyat','edeb-9-milli-demokratik',1,1,'Azərbaycan Xalq Cümhuriyyəti hansı ildə qurulmuşdur?','Cümhuriyyət 1918-ci ildə qurulmuşdur.',array['1918','1905','1936','1991'],1),
('edeb9-milli-demokratik#4','edebiyyat','edeb-9-milli-demokratik',1,1,'«Ana» şeirinin müəllifi kimdir?','Şeirin müəllifi Cəfər Cabbarlıdır.',array['Cəfər Cabbarlı','Əhməd Cavad','Abdulla Şaiq','Rəsul Rza'],1),
('edeb9-milli-demokratik#5','edebiyyat','edeb-9-milli-demokratik',2,1,'Əhməd Cavad hansı bölgədə doğulmuşdur?','Şair Şəmkir bölgəsində doğulmuşdur.',array['Şəmkirdə','Xızıda','Bakıda','Şuşada'],1),
('edeb9-milli-demokratik#6','edebiyyat','edeb-9-milli-demokratik',2,1,'Əhməd Cavad hansı dövlət rəmzinin mətn müəllifidir?','O, Azərbaycan Dövlət Himninin sözlərinin müəllifidir.',array['Dövlət Himninin','Dövlət Gerbinin','Dövlət möhürünün','Dövlət nişanının'],1),
('edeb9-milli-demokratik#7','edebiyyat','edeb-9-milli-demokratik',2,1,'Azərbaycan Dövlət Himninin musiqisi kimə məxsusdur?','Himnin musiqisi Üzeyir Hacıbəyliyə məxsusdur.',array['Üzeyir Hacıbəyliyə','Müslüm Maqomayevə','Qara Qarayevə','Fikrət Əmirova'],1),
('edeb9-milli-demokratik#8','edebiyyat','edeb-9-milli-demokratik',2,1,'Cümhuriyyətin üçrəngli bayrağının rəngləri hansılardır?','Bayraq mavi, qırmızı və yaşıl rənglərdən ibarətdir.',array['Mavi, qırmızı, yaşıl','Ağ, mavi, qırmızı','Qırmızı, sarı, yaşıl','Yaşıl, ağ, qara'],1),
('edeb9-milli-demokratik#9','edebiyyat','edeb-9-milli-demokratik',2,1,'«Azərbaycan bayrağına» şeirində hansı hiss aparıcıdır?','Vətənpərvərlik və istiqlal sevinci aparıcıdır.',array['Vətənpərvərlik və istiqlal sevinci','Təbiət təsviri həvəsi','Ticarət marağı','Yol çətinliyi duyğusu'],1),
('edeb9-milli-demokratik#10','edebiyyat','edeb-9-milli-demokratik',2,1,'«Ana» şeirinin mövzusu nədir?','Şeirin mövzusu ana məhəbbəti və fədakarlığıdır.',array['Ana məhəbbəti və fədakarlığı','Dəniz səyahəti','Şəhər memarlığı','Elmi kəşflər'],1),
('edeb9-milli-demokratik#11','edebiyyat','edeb-9-milli-demokratik',2,1,'Cəfər Cabbarlı hansı bölgədə doğulmuşdur?','Yazıçı Xızıda doğulmuşdur.',array['Xızıda','Şəmkirdə','Şamaxıda','Lənkəranda'],1),
('edeb9-milli-demokratik#12','edebiyyat','edeb-9-milli-demokratik',2,1,'Əhməd Cavad hansı ildə repressiya qurbanı olmuşdur?','Şair 1937-ci ildə repressiya qurbanı olmuşdur.',array['1937','1920','1945','1956'],1),
('edeb9-milli-demokratik#13','edebiyyat','edeb-9-milli-demokratik',2,1,'Milli-demokratik dövr ədəbiyyatının aparıcı ideyası nədir?','Milli oyanış və istiqlal ideyasıdır.',array['Milli oyanış və istiqlal','Sənaye tərəqqisi','Dəniz ticarəti','Saray həyatı'],1),
('edeb9-milli-demokratik#14','edebiyyat','edeb-9-milli-demokratik',2,1,'«Çırpınırdı Qara dəniz» şeirinin müəllifi kimdir?','Şeirin müəllifi Əhməd Cavaddır.',array['Əhməd Cavad','Abdulla Şaiq','Almas İldırım','Süleyman Rüstəm'],1),
('edeb9-milli-demokratik#15','edebiyyat','edeb-9-milli-demokratik',2,1,'Azərbaycan Xalq Cümhuriyyəti neçə il yaşamışdır?','Cümhuriyyət 1918-1920-ci illərdə, iki il yaşamışdır.',array['İki il','On il','Beş il','Bir ay'],1),
('edeb9-milli-demokratik#16','edebiyyat','edeb-9-milli-demokratik',2,1,'Bu dövr ədəbiyyatının əsas mövzusu nə idi?','Vətən, bayraq və azadlıq mövzusu idi.',array['Vətən, bayraq və azadlıq','Kosmos və texnika','Dəniz macəraları','Saray intriqaları'],1),
('edeb9-milli-demokratik#17','edebiyyat','edeb-9-milli-demokratik',2,1,'Cəfər Cabbarlı sonrakı illərdə hansı sahədə tanındı?','O, sonralar dramaturq kimi tanındı.',array['Dramaturgiyada','Rəssamlıqda','Musiqi bəstəkarlığında','Memarlıqda'],1),
('edeb9-milli-demokratik#18','edebiyyat','edeb-9-milli-demokratik',2,1,'Əhməd Cavadın şeirlərinin dili necədir?','Dili sadə, xalq danışığına yaxındır.',array['Sadə və xalq dilinə yaxın','Ağır ərəb-fars tərkibli','Süni tərcümə dili','Elmi termin dili'],1),
('edeb9-milli-demokratik#19','edebiyyat','edeb-9-milli-demokratik',2,1,'Bu dövrün şairləri hansı bayrağı tərənnüm edirdilər?','Onlar Cümhuriyyətin üçrəngli bayrağını tərənnüm edirdilər.',array['Cümhuriyyətin üçrəngli bayrağını','Qırmızı bayrağı','Ağ bayrağı','Qara bayrağı'],1),
('edeb9-milli-demokratik#20','edebiyyat','edeb-9-milli-demokratik',3,1,'Milli-demokratik dövr üzrə «əsər - müəllif» cütlüyü hansı düzgündür?','«Azərbaycan bayrağına» Əhməd Cavadın, «Ana» isə Cabbarlının şeiridir.',array['«Azərbaycan bayrağına» - Əhməd Cavad','«Azərbaycan bayrağına» - Cəfər Cabbarlı','«Ana» - Əhməd Cavad','«Həyat sevgisi» - Əhməd Cavad'],1),
('edeb9-milli-demokratik#21','edebiyyat','edeb-9-milli-demokratik',3,1,'Bu dövr haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Cümhuriyyət 1918-ci ildə qurulmuşdur.',array['Cümhuriyyət 1936-cı ildə qurulmuşdur','Əhməd Cavad himnin sözlərini yazmışdır','Cümhuriyyətin bayrağı üçrənglidir','Cəfər Cabbarlı Xızıda doğulmuşdur'],1),
('edeb9-milli-demokratik#22','edebiyyat','edeb-9-milli-demokratik',3,1,'Aşağıdakı üç hadisə zaman ardıcıllığı ilə necə düzülür? (1 - Əhməd Cavadın repressiyası, 2 - Cümhuriyyətin qurulması, 3 - Cümhuriyyətin süqutu)','Cümhuriyyət 1918-ci ildə qurulub, 1920-ci ildə süqut edib, Əhməd Cavad isə 1937-ci ildə repressiyaya məruz qalıb.',array['2 - 3 - 1','1 - 2 - 3','3 - 2 - 1','2 - 1 - 3'],1),
('edeb9-milli-demokratik#23','edebiyyat','edeb-9-milli-demokratik',3,1,'Bu dövrdə bayraq mövzusunun ədəbiyyata gəlməsinin səbəbi nədir?','Müstəqil dövlətin - Xalq Cümhuriyyətinin qurulmasıdır.',array['Müstəqil dövlətin qurulması','Sənaye inqilabının başlanması','Yeni əlifbaya keçilməsi','Xarici ədəbiyyatın tərcüməsi'],1),
('edeb9-milli-demokratik#24','edebiyyat','edeb-9-milli-demokratik',3,1,'Dövlət himni üzrə «şəxs - rol» cütlüyü hansı doğrudur?','Sözlər Əhməd Cavadın, musiqi Üzeyir Hacıbəylinindir.',array['Üzeyir Hacıbəyli - himnin bəstəkarı','Əhməd Cavad - himnin bəstəkarı','Üzeyir Hacıbəyli - himnin sözlərinin müəllifi','Cəfər Cabbarlı - himnin bəstəkarı'],1),
('edeb9-milli-demokratik#25','edebiyyat','edeb-9-milli-demokratik',3,1,'İki şairin doğulduğu yerlər haqqında hansı fikir doğrudur?','Əhməd Cavad Şəmkirdə, Cəfər Cabbarlı isə Xızıda doğulmuşdur.',array['Əhməd Cavad Şəmkirdə, Cabbarlı Xızıda','Əhməd Cavad Xızıda, Cabbarlı Şəmkirdə','Əhməd Cavad Bakıda, Cabbarlı Şuşada','Əhməd Cavad Şuşada, Cabbarlı Bakıda'],1),
('edeb9-milli-demokratik#26','edebiyyat','edeb-9-milli-demokratik',3,1,'Dövrün sərhədləri haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Milli-demokratik dövr XX əsrin əvvəlindən 1920-ci ilə qədərdir.',array['Bu dövr 1960-1990-cı illəri əhatə edir','Dövrün ideyası milli oyanışdır','Əhməd Cavad bu dövrün şairidir','Cümhuriyyət bu dövrdə qurulmuşdur'],1),
('edeb9-milli-demokratik#27','edebiyyat','edeb-9-milli-demokratik',3,1,'Əhməd Cavadın repressiyaya məruz qalması nə ilə bağlı idi?','O, milli istiqlal mövzusunda yazdığı üçün təqib olunurdu.',array['Milli istiqlal mövzusunda yazması','Xarici dildə yazması','Dram janrına keçməsi','Tərcümə ilə məşğul olması'],1),
('edeb9-milli-demokratik#28','edebiyyat','edeb-9-milli-demokratik',3,1,'Bu dövr əsərləri üzrə «əsər - mövzu» cütlüyü hansı doğrudur?','«Azərbaycan bayrağına» istiqlal, «Ana» isə ana məhəbbəti mövzusundadır.',array['«Azərbaycan bayrağına» - istiqlal','«Ana» - istiqlal','«Azərbaycan bayrağına» - ana məhəbbəti','«Ana» - dəniz səfəri'],1),
('edeb9-milli-demokratik#29','edebiyyat','edeb-9-milli-demokratik',3,1,'Cümhuriyyətin süqutu ilə Əhməd Cavadın repressiyası arasında neçə il var?','Cümhuriyyət 1920-ci ildə süqut edib, şair 1937-ci ildə repressiyaya məruz qalıb.',array['17 il','7 il','27 il','2 il'],1),
('edeb9-milli-demokratik#30','edebiyyat','edeb-9-milli-demokratik',3,1,'Milli-demokratik dövr ilə sovet dövrü ədəbiyyatının fərqi nədir?','Birincidə milli istiqlal, ikincidə sinfi ideologiya önə çəkilirdi.',array['Milli-demokratik dövrdə istiqlal önə çəkilirdi','Sovet dövründə istiqlal önə çəkilirdi','Milli-demokratik dövrdə sinfi ideologiya əsas idi','Hər iki dövrdə eyni mövzular işlənirdi'],1),
('edeb9-milli-demokratik#31','edebiyyat','edeb-9-milli-demokratik',3,1,'Bayraq rəngləri üzrə «rəng - məna» cütlüyü hansı düzgündür?','Mavi türkçülüyü, qırmızı müasirliyi, yaşıl isə islam mədəniyyətini bildirir.',array['Yaşıl - islam mədəniyyəti','Mavi - islam mədəniyyəti','Yaşıl - türkçülük','Qırmızı - islam mədəniyyəti'],1),
('edeb9-repressiya#1','edebiyyat','edeb-9-repressiya',1,1,'«Anabacı» hekayəsinin müəllifi kimdir?','Hekayənin müəllifi Abdulla Şaiqdir.',array['Abdulla Şaiq','Mikayıl Müşfiq','Almas İldırım','Seyid Hüseyn'],1),
('edeb9-repressiya#2','edebiyyat','edeb-9-repressiya',1,1,'Mikayıl Müşfiq hansı ədəbi növün nümayəndəsidir?','Müşfiq poeziyanın görkəmli nümayəndəsidir.',array['Poeziyanın','Dramaturgiyanın','Ədəbi tənqidin','Tərcümənin'],1),
('edeb9-repressiya#3','edebiyyat','edeb-9-repressiya',1,1,'«Zeybək qızı» əsərinin müəllifi kimdir?','Əsərin müəllifi Yusif Vəzir Çəmənzəminlidir.',array['Yusif Vəzir Çəmənzəminli','Abdulla Şaiq','Mir Cəlal','Anar'],1),
('edeb9-repressiya#4','edebiyyat','edeb-9-repressiya',1,1,'1937-ci il hadisələri ədəbiyyat tarixinə hansı adla düşmüşdür?','Bu illər repressiya illəri kimi tanınır.',array['Repressiya illəri','Maarifçilik illəri','İntibah dövrü','Mülayimləşmə dövrü'],1),
('edeb9-repressiya#5','edebiyyat','edeb-9-repressiya',2,1,'Bu mərhələ hansı illəri əhatə edir?','Mərhələ 1920-1940-cı illəri əhatə edir.',array['1920-1940-cı illər','1875-1900-cü illər','1960-1990-cı illər','1991-ci ildən sonrakı illər'],1),
('edeb9-repressiya#6','edebiyyat','edeb-9-repressiya',2,1,'Abdulla Şaiq hansı sahədə xüsusilə tanınır?','O, uşaq ədəbiyyatı və pedaqoji fəaliyyəti ilə tanınır.',array['Uşaq ədəbiyyatı və pedaqogika','Hərbi tarix','Kimya elmi','Memarlıq sənəti'],1),
('edeb9-repressiya#7','edebiyyat','edeb-9-repressiya',2,1,'«Anabacı» hansı janrdadır?','«Anabacı» hekayədir.',array['Hekayə','Poema','Dram','Qəzəl'],1),
('edeb9-repressiya#8','edebiyyat','edeb-9-repressiya',2,1,'Aşağıdakılardan hansı Yusif Vəzir Çəmənzəminlinin romanıdır?','«Qan içində» onun tarixi romanıdır.',array['«Qan içində»','«Gələcək gün»','«Ağ dəvə»','«Məhşər»'],1),
('edeb9-repressiya#9','edebiyyat','edeb-9-repressiya',2,1,'Yusif Vəzir Çəmənzəminli hansı şəhərdə doğulmuşdur?','Yazıçı Şuşada doğulmuşdur.',array['Şuşada','Bakıda','Gəncədə','Naxçıvanda'],1),
('edeb9-repressiya#10','edebiyyat','edeb-9-repressiya',2,1,'Almas İldırımın həyatında hansı hadisə həlledici olmuşdur?','O, vətəni tərk edib mühacirətə getmişdir.',array['Vətəndən mühacirətə getməsi','Uzun müddət nazir olması','Xaricdə təhsil alması','Ordu komandiri olması'],1),
('edeb9-repressiya#11','edebiyyat','edeb-9-repressiya',2,1,'«Əsir Azərbaycanım» şeirində hansı hiss ifadə olunur?','Vətən həsrəti və əsarət ağrısı ifadə olunur.',array['Vətən həsrəti və əsarət ağrısı','Bayram sevinci','Ov təəssüratı','Elmi maraq'],1),
('edeb9-repressiya#12','edebiyyat','edeb-9-repressiya',2,1,'Mikayıl Müşfiqin taleyi necə olmuşdur?','Şair repressiyanın qurbanı olmuşdur.',array['Repressiyanın qurbanı olmuşdur','Uzun ömür sürmüşdür','Mühacirətdə yaşamışdır','Cəbhədə həlak olmuşdur'],1),
('edeb9-repressiya#13','edebiyyat','edeb-9-repressiya',2,1,'«Həyat sevgisi» şeirində şair nəyi tərənnüm edir?','Şeirdə yaşamaq eşqi tərənnüm olunur.',array['Yaşamaq eşqini','Müharibə qələbəsini','Ticarət uğurunu','Saray həyatını'],1),
('edeb9-repressiya#14','edebiyyat','edeb-9-repressiya',2,1,'Aşağıdakılardan hansı Mikayıl Müşfiqin şeiridir?','«Yenə o bağ olaydı» Müşfiqin məşhur şeiridir.',array['«Yenə o bağ olaydı»','«Təbrizim»','«Əsgər məktubu»','«İstiqlal»'],1),
('edeb9-repressiya#15','edebiyyat','edeb-9-repressiya',2,1,'Seyid Hüseyn ədəbiyyatın hansı sahəsində də fəaliyyət göstərmişdir?','O, ədəbi tənqid sahəsində də çalışmışdır.',array['Ədəbi tənqiddə','Hərbi işdə','Tibb sahəsində','Memarlıqda'],1),
('edeb9-repressiya#16','edebiyyat','edeb-9-repressiya',2,1,'Proletkult cərəyanı ədəbiyyatdan nəyi tələb edirdi?','O, sinfi mübarizə mövzusunu ön plana çəkməyi tələb edirdi.',array['Sinfi mübarizə mövzusunu','Klassik əruz vəznini','Dini mövzuları','Saray mədhiyyəsini'],1),
('edeb9-repressiya#17','edebiyyat','edeb-9-repressiya',2,1,'Repressiya dövründə yazıçılara qarşı hansı ittiham irəli sürülürdü?','Onlar əsasən millətçilikdə ittiham olunurdular.',array['Millətçilikdə ittiham olunurdular','Vergidən yayınmada','Ticarət pozuntusunda','Torpaq mübahisəsində'],1),
('edeb9-repressiya#18','edebiyyat','edeb-9-repressiya',2,1,'Çəmənzəminli Xalq Cümhuriyyəti dövründə hansı vəzifədə olmuşdur?','O, Cümhuriyyətin Türkiyədəki səfiri olmuşdur.',array['Türkiyədə səfir','Maliyyə naziri','Ordu komandiri','Universitet rektoru'],1),
('edeb9-repressiya#19','edebiyyat','edeb-9-repressiya',2,1,'Bu dövrün ədəbiyyatında hansı ziddiyyət özünü göstərir?','Rəsmi ideoloji tələblə şairin daxili dünyası arasındakı ziddiyyət.',array['Rəsmi tələblə daxili dünya arasında','Şəhərlə kənd arasında','Elmlə ticarət arasında','Şeirlə musiqi arasında'],1),
('edeb9-repressiya#20','edebiyyat','edeb-9-repressiya',3,1,'Bu dövr üzrə «əsər - müəllif» cütlüklərindən hansı düzgündür?','«Həyat sevgisi» Müşfiqin, «Anabacı» isə Abdulla Şaiqin əsəridir.',array['«Həyat sevgisi» - Mikayıl Müşfiq','«Həyat sevgisi» - Abdulla Şaiq','«Anabacı» - Mikayıl Müşfiq','«Zeybək qızı» - Almas İldırım'],1),
('edeb9-repressiya#21','edebiyyat','edeb-9-repressiya',3,1,'Repressiya dövrü haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','«Anabacı» hekayədir, poema deyil.',array['«Anabacı» poemadır','«Anabacı» Abdulla Şaiqin əsəridir','Müşfiq repressiyanın qurbanı olmuşdur','Çəmənzəminli Şuşada doğulmuşdur'],1),
('edeb9-repressiya#22','edebiyyat','edeb-9-repressiya',3,1,'Aşağıdakı üç hadisə zaman ardıcıllığı ilə necə düzülür? (1 - Çəmənzəminlinin həyatının sonu, 2 - Cümhuriyyətin süqutu, 3 - Müşfiqin repressiyaya məruz qalması)','Cümhuriyyət 1920-ci ildə süquta uğrayıb, Müşfiq 1937-ci ildə həbs olunub, Çəmənzəminli isə 1943-cü ildə həyatını itirib.',array['2 - 3 - 1','1 - 2 - 3','3 - 1 - 2','2 - 1 - 3'],1),
('edeb9-repressiya#23','edebiyyat','edeb-9-repressiya',3,1,'Almas İldırımın mühacirətə getməsinin səbəbi nədir?','Sovet rejiminin təzyiqi onu vətəni tərk etməyə məcbur etmişdir.',array['Sovet rejiminin təzyiqi','Xaricdə təhsil almaq istəyi','Ailə ticarətinin genişlənməsi','Diplomatik təyinat alması'],1),
('edeb9-repressiya#24','edebiyyat','edeb-9-repressiya',3,1,'Bu dövr yazıçıları üzrə «şəxs - tale» cütlüyü hansı doğrudur?','Almas İldırım mühacirətə getmiş, Müşfiq isə repressiyaya məruz qalmışdır.',array['Almas İldırım - mühacirət','Mikayıl Müşfiq - mühacirət','Almas İldırım - uzun saray xidməti','Abdulla Şaiq - mühacirət'],1),
('edeb9-repressiya#25','edebiyyat','edeb-9-repressiya',3,1,'Müşfiq və Çəmənzəminlinin taleyi haqqında hansı fikir doğrudur?','Hər ikisi repressiyanın qurbanı olmuşdur.',array['Hər ikisi repressiyanın qurbanı olmuşdur','Hər ikisi mühacirətdə yaşamışdır','Biri mühacir, digəri nazir olmuşdur','Hər ikisi uzun ömür sürmüşdür'],1),
('edeb9-repressiya#26','edebiyyat','edeb-9-repressiya',3,1,'Dövrün ədəbi mühiti haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Proletkult klassik əruzu deyil, sinfi mübarizə mövzusunu tələb edirdi.',array['Proletkult klassik əruzu tələb edirdi','Dövr 1920-1940-cı illəri əhatə edir','1937-ci il repressiya ili sayılır','Müşfiq bu dövrün şairidir'],1),
('edeb9-repressiya#27','edebiyyat','edeb-9-repressiya',3,1,'Abdulla Şaiq və Mikayıl Müşfiqin yaradıcılığındakı fərq nədir?','Şaiq uşaq ədəbiyyatı, Müşfiq isə lirik poeziya ilə tanınır.',array['Şaiq uşaq ədəbiyyatı, Müşfiq lirika ilə tanınır','Şaiq lirika, Müşfiq uşaq ədəbiyyatı ilə tanınır','Hər ikisi dramaturq kimi tanınır','Hər ikisi ədəbi tənqidçi kimi tanınır'],1),
('edeb9-repressiya#28','edebiyyat','edeb-9-repressiya',3,1,'Bu dövr əsərləri üzrə «əsər - janr» cütlüyü hansı düzgündür?','«Zeybək qızı» hekayə, «Qan içində» isə romandır.',array['«Zeybək qızı» - hekayə','«Zeybək qızı» - roman','«Həyat sevgisi» - hekayə','«Qan içində» - hekayə'],1),
('edeb9-repressiya#29','edebiyyat','edeb-9-repressiya',3,1,'Bu dövrdə bir çox şairin əsərində ikili ovqatın yaranma səbəbi nədir?','Rəsmi ideoloji tələblə daxili duyğunun toqquşması.',array['Rəsmi tələblə duyğunun toqquşması','Xarici dilin güclü təsiri','Şeir vəzninin dəyişməsi','Nəşr sayının kəskin artması'],1),
('edeb9-repressiya#30','edebiyyat','edeb-9-repressiya',3,1,'Bu dövr şəxsiyyətləri üzrə «şəxs - vəzifə» cütlüyü hansı doğrudur?','Çəmənzəminli Cümhuriyyətin Türkiyədəki səfiri olmuşdur.',array['Çəmənzəminli - Cümhuriyyətin səfiri','Mikayıl Müşfiq - Cümhuriyyətin səfiri','Çəmənzəminli - maliyyə naziri','Abdulla Şaiq - Cümhuriyyətin səfiri'],1),
('edeb9-repressiya#31','edebiyyat','edeb-9-repressiya',3,1,'Repressiya dövrü ilə milli-demokratik dövr arasındakı əsas fərq nədir?','Milli-demokratik dövrdə istiqlal açıq deyilirdi, sonrakı dövrdə isə yox.',array['Milli-demokratik dövrdə istiqlal açıq deyilirdi','Repressiya dövründə istiqlal açıq deyilirdi','Hər iki dövrdə eyni sərbəstlik vardı','Hər iki dövrdə mövzu seçimi sərbəst idi'],1),
('edeb9-muharibe#1','edebiyyat','edeb-9-muharibe',1,2,'«Təbrizim» şeirinin müəllifi kimdir?','Şeirin müəllifi Süleyman Rüstəmdir.',array['Süleyman Rüstəm','Səməd Vurğun','Mir Cəlal','Mehdi Hüseyn'],1),
('edeb9-muharibe#2','edebiyyat','edeb-9-muharibe',1,2,'«Gələcək gün» romanının müəllifi kimdir?','Romanın müəllifi Mirzə İbrahimovdur.',array['Mirzə İbrahimov','Mir Cəlal','Mehdi Hüseyn','Süleyman Rüstəm'],1),
('edeb9-muharibe#3','edebiyyat','edeb-9-muharibe',1,2,'Müharibə və mülayimləşmə mərhələsi hansı illəri əhatə edir?','Mərhələ 1941-1960-cı illəri əhatə edir.',array['1941-1960-cı illər','1920-1940-cı illər','1961-1990-cı illər','1991-ci ildən sonrakı illər'],1),
('edeb9-muharibe#4','edebiyyat','edeb-9-muharibe',1,2,'«Ananın öyüdü» şeirinin müəllifi kimdir?','Şeirin müəllifi Səməd Vurğundur.',array['Səməd Vurğun','Əhməd Cavad','Rəsul Rza','Əli Kərim'],1),
('edeb9-muharibe#5','edebiyyat','edeb-9-muharibe',2,2,'«Ananın öyüdü» şeirində ana oğluna nə öyüd verir?','Ana oğluna vətəni namusla qorumağı öyüd verir.',array['Vətəni namusla qorumağı','Ticarətlə məşğul olmağı','Uzaq şəhərə köçməyi','Təhsildən əl çəkməyi'],1),
('edeb9-muharibe#6','edebiyyat','edeb-9-muharibe',2,2,'«Təbrizim» şeirinin mövzusu nədir?','Şeirin mövzusu Cənubi Azərbaycan həsrətidir.',array['Cənubi Azərbaycan həsrəti','Şəhər tikintisi','Dəniz səfəri','Elmi kəşf'],1),
('edeb9-muharibe#7','edebiyyat','edeb-9-muharibe',2,2,'Mir Cəlalın «Vətən yaraları» əsəri hansı janrdadır?','Əsər hekayə janrındadır.',array['Hekayə','Poema','Dram','Qəzəl'],1),
('edeb9-muharibe#8','edebiyyat','edeb-9-muharibe',2,2,'«Gələcək gün» romanı hansı bölgənin hadisələrindən bəhs edir?','Roman Cənubi Azərbaycandakı hadisələrdən bəhs edir.',array['Cənubi Azərbaycanın','Qarabağın','Şirvanın','Naxçıvanın'],1),
('edeb9-muharibe#9','edebiyyat','edeb-9-muharibe',2,2,'«Nişan üzüyü» əsərinin müəllifi kimdir?','Əsərin müəllifi Mehdi Hüseyndir.',array['Mehdi Hüseyn','Mirzə İbrahimov','Süleyman Rüstəm','Anar'],1),
('edeb9-muharibe#10','edebiyyat','edeb-9-muharibe',2,2,'İkinci Dünya müharibəsi dövrü ədəbiyyatının əsas mövzusu nə idi?','Vətənin müdafiəsi və qəhrəmanlıq mövzusu idi.',array['Vətənin müdafiəsi və qəhrəmanlıq','Saray həyatı','Ticarət qaydaları','Kosmos səfərləri'],1),
('edeb9-muharibe#11','edebiyyat','edeb-9-muharibe',2,2,'Süleyman Rüstəmin yaradıcılığında hansı mövzu geniş yer tutur?','Onun yaradıcılığında Cənub mövzusu geniş yer tutur.',array['Cənub mövzusu','Dəniz macərası','Memarlıq','Kimya elmi'],1),
('edeb9-muharibe#12','edebiyyat','edeb-9-muharibe',2,2,'«Vətən yaraları» hekayəsində müharibənin hansı tərəfi göstərilir?','Arxa cəbhədəki insan taleləri göstərilir.',array['Arxa cəbhədəki insan taleləri','Dəniz döyüşləri','Kosmos yarışı','Saray çəkişməsi'],1),
('edeb9-muharibe#13','edebiyyat','edeb-9-muharibe',2,2,'Aşağıdakılardan hansı Mirzə İbrahimovun romanıdır?','«Böyük dayaq» Mirzə İbrahimovun romanıdır.',array['«Böyük dayaq»','«Ağ dəvə»','«Məhşər»','«Qan içində»'],1),
('edeb9-muharibe#14','edebiyyat','edeb-9-muharibe',2,2,'Mülayimləşmə dövrü nə vaxt başlamışdır?','Mülayimləşmə 1950-ci illərin ortalarında başlamışdır.',array['1950-ci illərin ortalarında','1920-ci illərin əvvəlində','1990-cı illərin sonunda','1900-cü illərin əvvəlində'],1),
('edeb9-muharibe#15','edebiyyat','edeb-9-muharibe',2,2,'Müharibə illərində şeirin əsas vəzifəsi nə idi?','Xalqa ruh yüksəkliyi və mübarizə əzmi vermək idi.',array['Xalqa ruh yüksəkliyi vermək','Elmi biliyi yaymaq','Ticarəti təbliğ etmək','Memarlığı öyrətmək'],1),
('edeb9-muharibe#16','edebiyyat','edeb-9-muharibe',2,2,'«Ananın öyüdü» şeirində ana obrazı nəyi təmsil edir?','Ana obrazı vətəni və xalqı təmsil edir.',array['Vətəni və xalqı','Şəhər həyatını','Ticarət mühitini','Saray adətini'],1),
('edeb9-muharibe#17','edebiyyat','edeb-9-muharibe',2,2,'Bu dövrdə Cənub mövzusunun güclənməsinin səbəbi nədir?','1945-1946-cı illərdəki milli hərəkat bu mövzunu gücləndirdi.',array['1945-1946-cı il hadisələri','Sənaye tikintisi','Yeni əlifbaya keçid','Kosmos uçuşları'],1),
('edeb9-muharibe#18','edebiyyat','edeb-9-muharibe',2,2,'Mehdi Hüseyn hansı ədəbi növdə çalışmışdır?','O, əsasən nəsrdə çalışmışdır.',array['Nəsrdə','Aşıq şeirində','Bədii tərcümədə','Uşaq şeirində'],1),
('edeb9-muharibe#19','edebiyyat','edeb-9-muharibe',2,2,'Şəxsiyyətə pərəstiş dövrü ədəbiyyata necə təsir etmişdir?','Mövzu seçimini məhdudlaşdırmış, sərbəstliyi azaltmışdır.',array['Mövzu seçimini məhdudlaşdırmışdır','Mövzunu tamamilə sərbəstləşdirmişdir','Şeir janrını aradan qaldırmışdır','Nəsr janrını qadağan etmişdir'],1),
('edeb9-muharibe#20','edebiyyat','edeb-9-muharibe',3,2,'Müharibə dövrü üzrə «əsər - müəllif» cütlüyü hansı düzgündür?','«Təbrizim» Süleyman Rüstəmin, «Ananın öyüdü» Səməd Vurğunundur.',array['«Təbrizim» - Süleyman Rüstəm','«Təbrizim» - Səməd Vurğun','«Ananın öyüdü» - Süleyman Rüstəm','«Gələcək gün» - Mir Cəlal'],1),
('edeb9-muharibe#21','edebiyyat','edeb-9-muharibe',3,2,'Bu dövr əsərləri haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','«Gələcək gün» romandır, hekayə deyil.',array['«Gələcək gün» hekayədir','«Gələcək gün» Mirzə İbrahimovundur','«Vətən yaraları» Mir Cəlalındır','«Təbrizim» Süleyman Rüstəmindir'],1),
('edeb9-muharibe#22','edebiyyat','edeb-9-muharibe',3,2,'Aşağıdakı üç hadisə zaman ardıcıllığı ilə necə düzülür? (1 - müharibənin başlanması, 2 - mülayimləşmənin başlanması, 3 - Cənubdakı milli hərəkat)','Müharibə 1941-ci ildə başlayıb, Cənubdakı hərəkat 1945-1946-cı illərdə olub, mülayimləşmə isə 1950-ci illərin ortasında başlayıb.',array['1 - 3 - 2','1 - 2 - 3','2 - 3 - 1','3 - 1 - 2'],1),
('edeb9-muharibe#23','edebiyyat','edeb-9-muharibe',3,2,'Bu dövrdə Cənub mövzusunun ədəbiyyata güclü gəlişinin səbəbi nədir?','1945-1946-cı illərdə Cənubi Azərbaycandakı milli hərəkat.',array['Cənubdakı milli hərəkat','Sənaye tikintisinin genişlənməsi','Yeni əlifbaya keçilməsi','Kosmos uçuşlarının başlanması'],1),
('edeb9-muharibe#24','edebiyyat','edeb-9-muharibe',3,2,'Müharibə dövrü üzrə «əsər - janr» cütlüyü hansı doğrudur?','«Gələcək gün» roman, «Vətən yaraları» isə hekayədir.',array['«Gələcək gün» - roman','«Gələcək gün» - hekayə','«Vətən yaraları» - roman','«Təbrizim» - roman'],1),
('edeb9-muharibe#25','edebiyyat','edeb-9-muharibe',3,2,'Səməd Vurğun və Süleyman Rüstəmin bu dövrdəki əsərlərinin ortaq cəhəti nədir?','Hər ikisi şeir janrında yazılmışdır.',array['Hər ikisi şeir janrındadır','Hər ikisi roman janrındadır','Hər ikisi dram janrındadır','Hər ikisi hekayə janrındadır'],1),
('edeb9-muharibe#26','edebiyyat','edeb-9-muharibe',3,2,'Müharibə dövrü haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Bu mərhələ XX əsrin ortalarını - 1941-1960-cı illəri əhatə edir.',array['Bu mərhələ XIX əsri əhatə edir','Müharibə mövzusu aparıcı olmuşdur','Mehdi Hüseyn nasir kimi tanınır','Mirzə İbrahimov «Gələcək gün»ü yazmışdır'],1),
('edeb9-muharibe#27','edebiyyat','edeb-9-muharibe',3,2,'Müharibə dövrü ədəbiyyatının səciyyəvi cəhəti nədir?','Publisistik pafos və mübarizəyə çağırış ruhu səciyyəvidir.',array['Publisistik pafos və çağırış ruhu','Sakit məişət təsviri','Elmi-fantastik süjet qurulusu','Klassik əruz forması'],1),
('edeb9-muharibe#28','edebiyyat','edeb-9-muharibe',3,2,'Müharibə dövrü üzrə «əsər - mövzu» cütlüyü hansı düzgündür?','«Təbrizim» Cənub həsrəti, «Vətən yaraları» isə arxa cəbhə mövzusundadır.',array['«Təbrizim» - Cənub həsrəti','«Təbrizim» - arxa cəbhə','«Vətən yaraları» - Cənub həsrəti','«Ananın öyüdü» - dəniz səfəri'],1),
('edeb9-muharibe#29','edebiyyat','edeb-9-muharibe',3,2,'«Ananın öyüdü» şeirində ana obrazının seçilməsinin səbəbi nədir?','Şeirdə vətən ana ilə eyniləşdirilir, ona görə ana obrazı seçilib.',array['Vətənin ana ilə eyniləşdirilməsi','Ailə mövzusunun dəbdə olması','Uşaq ədəbiyyatına yaxınlıq','Tarixi salnamə ənənəsi'],1),
('edeb9-muharibe#30','edebiyyat','edeb-9-muharibe',3,2,'Bu dövr yazıçıları üzrə «yazıçı - janr» cütlüyü hansı doğrudur?','Mir Cəlal hekayə ustası, Səməd Vurğun isə şairdir.',array['Mir Cəlal - hekayə ustası','Süleyman Rüstəm - hekayə ustası','Mir Cəlal - dramaturq','Səməd Vurğun - nasir'],1),
('edeb9-muharibe#31','edebiyyat','edeb-9-muharibe',3,2,'Mirzə İbrahimov və Mir Cəlalın bu dövrdəki əsərləri haqqında hansı fikir doğrudur?','Mirzə İbrahimov roman, Mir Cəlal isə hekayə yazmışdır.',array['Mirzə İbrahimov roman, Mir Cəlal hekayə yazıb','Mirzə İbrahimov hekayə, Mir Cəlal roman yazıb','Hər ikisi poema janrında yazıb','Hər ikisi dram janrında yazıb'],1),
('edeb9-ozunuderk-seir#1','edebiyyat','edeb-9-ozunuderk-seir',1,2,'«Əsgər məktubu» şeirinin müəllifi kimdir?','Şeirin müəllifi Məmməd Arazdır.',array['Məmməd Araz','Əli Kərim','Rəsul Rza','Balaş Azəroğlu'],1),
('edeb9-ozunuderk-seir#2','edebiyyat','edeb-9-ozunuderk-seir',1,2,'Bu mərhələ ədəbiyyat tarixində hansı adla tanınır?','Mərhələ milli-mənəvi özünüdərk dövrü adlanır.',array['Milli-mənəvi özünüdərk dövrü','Maarifçilik dövrü','İntibah dövrü','Repressiya dövrü'],1),
('edeb9-ozunuderk-seir#3','edebiyyat','edeb-9-ozunuderk-seir',1,2,'«Çinar ömrü» əsərinin müəllifi kimdir?','Əsərin müəllifi Rəsul Rzadır.',array['Rəsul Rza','Məmməd Araz','Əli Kərim','Sabir Rüstəmxanlı'],1),
('edeb9-ozunuderk-seir#4','edebiyyat','edeb-9-ozunuderk-seir',1,2,'«Sağ ol, ana dilim!» şeirinin müəllifi kimdir?','Şeirin müəllifi Sabir Rüstəmxanlıdır.',array['Sabir Rüstəmxanlı','Əliağa Kürçaylı','Balaş Azəroğlu','Mehdi Hüseyn'],1),
('edeb9-ozunuderk-seir#5','edebiyyat','edeb-9-ozunuderk-seir',2,2,'Özünüdərk mərhələsi hansı illəri əhatə edir?','Mərhələ 1961-1990-cı illəri əhatə edir.',array['1961-1990-cı illər','1920-1940-cı illər','1941-1960-cı illər','1991-ci ildən sonrakı illər'],1),
('edeb9-ozunuderk-seir#6','edebiyyat','edeb-9-ozunuderk-seir',2,2,'«Qaytar ana borcunu» şeirinin müəllifi kimdir?','Şeirin müəllifi Əli Kərimdir.',array['Əli Kərim','Məmməd Araz','Rəsul Rza','Əliağa Kürçaylı'],1),
('edeb9-ozunuderk-seir#7','edebiyyat','edeb-9-ozunuderk-seir',2,2,'«Şəhid meşə» şeirinin müəllifi kimdir?','Şeirin müəllifi Əliağa Kürçaylıdır.',array['Əliağa Kürçaylı','Əli Kərim','Balaş Azəroğlu','Sabir Rüstəmxanlı'],1),
('edeb9-ozunuderk-seir#8','edebiyyat','edeb-9-ozunuderk-seir',2,2,'«Buludlar» şeirinin müəllifi kimdir?','Şeirin müəllifi Balaş Azəroğludur.',array['Balaş Azəroğlu','Məmməd Araz','Süleyman Rüstəm','Anar'],1),
('edeb9-ozunuderk-seir#9','edebiyyat','edeb-9-ozunuderk-seir',2,2,'Bu dövr poeziyasının aparıcı mövzusu nədir?','Milli kimlik, ana dili və kökə bağlılıq mövzusudur.',array['Milli kimlik və ana dili','Sənaye tikintisi','Ticarət yolları','Dəniz macərası'],1),
('edeb9-ozunuderk-seir#10','edebiyyat','edeb-9-ozunuderk-seir',2,2,'«Sağ ol, ana dilim!» şeirində nə tərənnüm olunur?','Şeirdə ana dilinə məhəbbət tərənnüm olunur.',array['Ana dilinə məhəbbət','Şəhər memarlığı','Dəniz gözəlliyi','Ticarət uğuru'],1),
('edeb9-ozunuderk-seir#11','edebiyyat','edeb-9-ozunuderk-seir',2,2,'«Qaytar ana borcunu» şeirində hansı fikir önə çəkilir?','Övladın ana və vətən qarşısındakı borcu fikri önə çəkilir.',array['Övladın ana və vətən borcu','Ticarət borcunun ödənişi','Uzaq səfərin çətinliyi','Elmi tədqiqatın nəticəsi'],1),
('edeb9-ozunuderk-seir#12','edebiyyat','edeb-9-ozunuderk-seir',2,2,'Şair Məmməd Arazın vətəni hansı bölgədir?','Şairin vətəni Naxçıvanın Şahbuz bölgəsidir.',array['Naxçıvanda','Şəkidə','Göyçayda','Şuşada'],1),
('edeb9-ozunuderk-seir#13','edebiyyat','edeb-9-ozunuderk-seir',2,2,'«Əsgər məktubu» şeirinin əsas motivi nədir?','Vətən sevgisi və əsgər borcu motividir.',array['Vətən sevgisi və əsgər borcu','Şəhər həyatının rahatlığı','Ticarət səfəri təəssüratı','Elmi mübahisə mövzusu'],1),
('edeb9-ozunuderk-seir#14','edebiyyat','edeb-9-ozunuderk-seir',2,2,'Sabir Rüstəmxanlının məşhur nəsr əsəri hansıdır?','«Ömür kitabı» onun məşhur nəsr əsəridir.',array['«Ömür kitabı»','«Ağ dəvə»','«Məhşər»','«Böyük dayaq»'],1),
('edeb9-ozunuderk-seir#15','edebiyyat','edeb-9-ozunuderk-seir',2,2,'Bu dövrdə şeirin dili necə dəyişdi?','Şeirin dili sadələşdi, canlı danışıq dilinə yaxınlaşdı.',array['Sadələşib danışıq dilinə yaxınlaşdı','Ağır ərəb-fars tərkibli oldu','Bütövlükdə əruza qayıtdı','Tərcümə dilinə çevrildi'],1),
('edeb9-ozunuderk-seir#16','edebiyyat','edeb-9-ozunuderk-seir',2,2,'«Çinar ömrü» əsərində çinar obrazı nəyi bildirir?','Uzun ömrü və xalqın keçdiyi tarixi yolu bildirir.',array['Uzun ömrü və xalqın tarixini','Ticarət yolunu','Şəhər memarlığını','Dəniz sahilini'],1),
('edeb9-ozunuderk-seir#17','edebiyyat','edeb-9-ozunuderk-seir',2,2,'Əli Kərim hansı ədəbi növün nümayəndəsidir?','Əli Kərim poeziyanın nümayəndəsidir.',array['Poeziyanın','Dramaturgiyanın','Ədəbi tənqidin','Publisistikanın'],1),
('edeb9-ozunuderk-seir#18','edebiyyat','edeb-9-ozunuderk-seir',2,2,'Məmməd Arazın şeirlərində hansı ovqat üstünlük təşkil edir?','Vətənə bağlılıq və narahat düşüncə ovqatı üstünlük təşkil edir.',array['Vətənə bağlılıq və düşüncə','Yumor və zarafat','Quru elmi şərh','Sənədli xronika'],1),
('edeb9-ozunuderk-seir#19','edebiyyat','edeb-9-ozunuderk-seir',2,2,'Balaş Azəroğlunun yaradıcılığı hansı mövzu ilə bağlıdır?','Onun yaradıcılığı Cənubi Azərbaycan mövzusu ilə bağlıdır.',array['Cənubi Azərbaycan mövzusu','Kosmos mövzusu','Dəniz mövzusu','Memarlıq mövzusu'],1),
('edeb9-ozunuderk-seir#20','edebiyyat','edeb-9-ozunuderk-seir',3,2,'Özünüdərk dövrü poeziyası üzrə «əsər - müəllif» cütlüyü hansı düzgündür?','«Əsgər məktubu» Məmməd Arazın, «Çinar ömrü» Rəsul Rzanındır.',array['«Əsgər məktubu» - Məmməd Araz','«Əsgər məktubu» - Əli Kərim','«Çinar ömrü» - Məmməd Araz','«Buludlar» - Əli Kərim'],1),
('edeb9-ozunuderk-seir#21','edebiyyat','edeb-9-ozunuderk-seir',3,2,'Bu dövr şairləri haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','«Sağ ol, ana dilim!» Sabir Rüstəmxanlınındır.',array['«Sağ ol, ana dilim!» Rəsul Rzanındır','«Çinar ömrü» Rəsul Rzanındır','«Əsgər məktubu» Məmməd Arazındır','«Qaytar ana borcunu» Əli Kərimindir'],1),
('edeb9-ozunuderk-seir#22','edebiyyat','edeb-9-ozunuderk-seir',3,2,'Ədəbi mərhələlər zaman ardıcıllığı ilə necə düzülür? (1 - repressiya dövrü, 2 - özünüdərk dövrü, 3 - müharibə dövrü)','Repressiya dövrü 1920-1940, müharibə dövrü 1941-1960, özünüdərk dövrü isə 1961-1990-cı illəri əhatə edir.',array['1 - 3 - 2','1 - 2 - 3','2 - 3 - 1','3 - 1 - 2'],1),
('edeb9-ozunuderk-seir#23','edebiyyat','edeb-9-ozunuderk-seir',3,2,'1960-cı illərdən sonra milli mövzunun güclənməsinin səbəbi nədir?','Cəmiyyətdə milli özünüdərkin oyanması bu mövzunu gücləndirdi.',array['Milli özünüdərkin oyanması','Sənaye istehsalının artması','Xarici ticarətin genişlənməsi','Yeni əlifbaya keçilməsi'],1),
('edeb9-ozunuderk-seir#24','edebiyyat','edeb-9-ozunuderk-seir',3,2,'Bu dövr şairləri üzrə «şair - mövzu» cütlüyü hansı doğrudur?','Balaş Azəroğlunun yaradıcılığı Cənub mövzusu ilə bağlıdır.',array['Balaş Azəroğlu - Cənub mövzusu','Əli Kərim - Cənub mövzusu','Balaş Azəroğlu - kosmos mövzusu','Sabir Rüstəmxanlı - dəniz mövzusu'],1),
('edeb9-ozunuderk-seir#25','edebiyyat','edeb-9-ozunuderk-seir',3,2,'Rəsul Rza və Əli Kərimin yaradıcılığındakı ortaq cəhət nədir?','Hər ikisi poeziyada yenilikçi axtarışları ilə tanınır.',array['Hər ikisi poeziyada yenilikçi olmuşdur','Hər ikisi roman janrında yazmışdır','Hər ikisi dramaturq kimi tanınır','Hər ikisi ədəbi tənqidçi olmuşdur'],1),
('edeb9-ozunuderk-seir#26','edebiyyat','edeb-9-ozunuderk-seir',3,2,'Özünüdərk dövrü haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Özünüdərk dövrü 1961-1990-cı illəri əhatə edir.',array['Özünüdərk dövrü 1920-1940-cı illərdədir','Dövrün mövzusu milli kimlikdir','Məmməd Araz bu dövrün şairidir','Özünüdərk dövründə şeirin dili sadələşmişdir'],1),
('edeb9-ozunuderk-seir#27','edebiyyat','edeb-9-ozunuderk-seir',3,2,'Repressiya dövrü ilə özünüdərk dövrü poeziyasının fərqi nədir?','Özünüdərk dövründə milli mövzu daha açıq şəkildə deyilirdi.',array['Özünüdərk dövründə milli mövzu açıq deyilirdi','Repressiya dövründə milli mövzu açıq deyilirdi','Hər iki dövrdə mövzu eyni cür verilirdi','Hər iki dövrdə şeir demək olar yazılmırdı'],1),
('edeb9-ozunuderk-seir#28','edebiyyat','edeb-9-ozunuderk-seir',3,2,'Bu dövr əsərləri üzrə «əsər - mövzu» cütlüyü hansı düzgündür?','«Sağ ol, ana dilim!» ana dili, «Buludlar» isə Cənub mövzusundadır.',array['«Sağ ol, ana dilim!» - ana dili','«Əsgər məktubu» - ana dili','«Sağ ol, ana dilim!» - dəniz mövzusu','«Buludlar» - ana dili'],1),
('edeb9-ozunuderk-seir#29','edebiyyat','edeb-9-ozunuderk-seir',3,2,'Bu dövrdə ana dili mövzusunun poeziyada güclü olmasının səbəbi nədir?','Dil milli kimliyin əsası sayıldığı üçün bu mövzu güclənmişdi.',array['Dilin milli kimliyin əsası sayılması','Xarici dillərin geniş öyrənilməsi','Dərsliklərin sayının artması','Tərcümə işinin genişlənməsi'],1),
('edeb9-ozunuderk-seir#30','edebiyyat','edeb-9-ozunuderk-seir',3,2,'Bu dövr şairləri üzrə «şair - doğulduğu yer» cütlüyü hansı doğrudur?','Məmməd Araz Naxçıvanda doğulmuşdur.',array['Məmməd Araz - Naxçıvan','Əli Kərim - Naxçıvan','Məmməd Araz - Şəki','Rəsul Rza - Naxçıvan'],1),
('edeb9-ozunuderk-seir#31','edebiyyat','edeb-9-ozunuderk-seir',3,2,'Sabir Rüstəmxanlı və Məmməd Arazın yaradıcılığında ortaq mövzu hansıdır?','Hər ikisində vətən və ana dili mövzusu aparıcıdır.',array['Vətən və ana dili mövzusu','Kosmos və texnika mövzusu','Dəniz və gəmiçilik mövzusu','Ticarət və sənaye mövzusu'],1),
('edeb9-ozunuderk-nesr#1','edebiyyat','edeb-9-ozunuderk-nesr',1,3,'«Namərd gülləsi» əsərinin müəllifi kimdir?','Əsərin müəllifi İsmayıl Şıxlıdır.',array['İsmayıl Şıxlı','İsa Hüseynov','Anar','Elçin'],1),
('edeb9-ozunuderk-nesr#2','edebiyyat','edeb-9-ozunuderk-nesr',1,3,'«Talvar» əsərinin müəllifi kimdir?','Əsərin müəllifi Elçindir.',array['Elçin','Anar','İsa Hüseynov','Mehdi Hüseyn'],1),
('edeb9-ozunuderk-nesr#3','edebiyyat','edeb-9-ozunuderk-nesr',1,3,'«Keçən ilin son gecəsi» əsərinin müəllifi kimdir?','Əsərin müəllifi Anardır.',array['Anar','Elçin','İsmayıl Şıxlı','Sabir Rüstəmxanlı'],1),
('edeb9-ozunuderk-nesr#4','edebiyyat','edeb-9-ozunuderk-nesr',1,3,'«Zəhər» əsərinin müəllifi kimdir?','Əsərin müəllifi İsa Hüseynovdur.',array['İsa Hüseynov','Anar','Elçin','Mirzə İbrahimov'],1),
('edeb9-ozunuderk-nesr#5','edebiyyat','edeb-9-ozunuderk-nesr',2,3,'Bu dövr nəsrinin səciyyəvi cəhəti nədir?','Psixoloji dərinlik və milli yaddaşa müraciət səciyyəvidir.',array['Psixoloji dərinlik və milli yaddaş','Sənədli xronika üslubu','Elmi-fantastik süjet','Detektiv macəra qurulusu'],1),
('edeb9-ozunuderk-nesr#6','edebiyyat','edeb-9-ozunuderk-nesr',2,3,'Yazıçı Anar kimin övladıdır?','Anar Rəsul Rza ilə Nigar Rəfibəylinin oğludur.',array['Rəsul Rza və Nigar Rəfibəylinin','İlyas Əfəndiyevin','Mir Cəlalın','Süleyman Rüstəmin'],1),
('edeb9-ozunuderk-nesr#7','edebiyyat','edeb-9-ozunuderk-nesr',2,3,'Yazıçı Elçin kimin övladıdır?','Elçin İlyas Əfəndiyevin oğludur.',array['İlyas Əfəndiyevin','Rəsul Rzanın','Mir Cəlalın','İsmayıl Şıxlının'],1),
('edeb9-ozunuderk-nesr#8','edebiyyat','edeb-9-ozunuderk-nesr',2,3,'Aşağıdakılardan hansı Anarın əsəridir?','«Beşmərtəbəli evin altıncı mərtəbəsi» Anarın povestidir.',array['«Beşmərtəbəli evin altıncı mərtəbəsi»','«Ağ dəvə»','«Məhşər»','«Böyük dayaq»'],1),
('edeb9-ozunuderk-nesr#9','edebiyyat','edeb-9-ozunuderk-nesr',2,3,'Aşağıdakılardan hansı Elçinin romanıdır?','«Mahmud və Məryəm» Elçinin romanıdır.',array['«Mahmud və Məryəm»','«Zəhər»','«Gələcək gün»','«Qan içində»'],1),
('edeb9-ozunuderk-nesr#10','edebiyyat','edeb-9-ozunuderk-nesr',2,3,'İsa Hüseynovun Nəsimiyə həsr olunmuş romanı hansıdır?','«Məhşər» romanı Nəsiminin taleyinə həsr olunmuşdur.',array['«Məhşər»','«Talvar»','«Ağ liman»','«Böyük dayaq»'],1),
('edeb9-ozunuderk-nesr#11','edebiyyat','edeb-9-ozunuderk-nesr',2,3,'«Namərd gülləsi» hansı janrdadır?','Əsər hekayə janrındadır.',array['Hekayə janrında','Roman janrında','Poema janrında','Dram janrında'],1),
('edeb9-ozunuderk-nesr#12','edebiyyat','edeb-9-ozunuderk-nesr',2,3,'Bu dövr nəsrində hansı məsələ tez-tez qabardılır?','Mənəvi seçim və vicdan məsələsi qabardılır.',array['Mənəvi seçim və vicdan məsələsi','Ticarət rəqabəti','Hərbi taktika məsələləri','Kosmos yarışı'],1),
('edeb9-ozunuderk-nesr#13','edebiyyat','edeb-9-ozunuderk-nesr',2,3,'Anar ədəbiyyatdan başqa hansı sahədə çalışmışdır?','O, kino sahəsində - ssenari və rejissorluqla məşğul olmuşdur.',array['Kino sahəsində','Tibb sahəsində','Memarlıqda','Kimya elmində'],1),
('edeb9-ozunuderk-nesr#14','edebiyyat','edeb-9-ozunuderk-nesr',2,3,'Elçin hansı sahədə də tanınmışdır?','O, dramaturq kimi də tanınmışdır.',array['Dramaturgiyada','Aşıq şeirində','Elmi fantastikada','Uşaq nağılında'],1),
('edeb9-ozunuderk-nesr#15','edebiyyat','edeb-9-ozunuderk-nesr',2,3,'Bu dövr nəsrində kənd mövzusu necə verilir?','Kənd milli köklərin daşıyıcısı kimi verilir.',array['Milli köklərin daşıyıcısı kimi','Sadəcə iqtisadi göstərici kimi','Tarixi salnamə kimi','Fantastik məkan kimi'],1),
('edeb9-ozunuderk-nesr#16','edebiyyat','edeb-9-ozunuderk-nesr',2,3,'«Talvar» əsəri hansı ədəbi növə aiddir?','«Talvar» nəsr əsəridir.',array['Nəsrə','Poeziyaya','Dramaturgiyaya','Publisistikaya'],1),
('edeb9-ozunuderk-nesr#17','edebiyyat','edeb-9-ozunuderk-nesr',2,3,'Bu dövrün nasirləri hansı üsula geniş müraciət etdilər?','Daxili monoloq və psixoloji təhlil üsuluna müraciət etdilər.',array['Daxili monoloq və psixoloji təhlilə','Sənədli hesabat üslubuna','Qafiyəli nəsrə','Dastan qəlibinə'],1),
('edeb9-ozunuderk-nesr#18','edebiyyat','edeb-9-ozunuderk-nesr',2,3,'İsa Hüseynovun ədəbi təxəllüsü nədir?','Yazıçının təxəllüsü Muğannadır.',array['Muğanna','Xətayi','Vaqif','Hophop'],1),
('edeb9-ozunuderk-nesr#19','edebiyyat','edeb-9-ozunuderk-nesr',2,3,'Özünüdərk dövrü nəsri hansı illəri əhatə edir?','Bu nəsr 1961-1990-cı illəri əhatə edir.',array['1961-1990-cı illər','1900-1920-ci illər','1920-1940-cı illər','1991-ci ildən sonrakı illər'],1),
('edeb9-ozunuderk-nesr#20','edebiyyat','edeb-9-ozunuderk-nesr',3,3,'Özünüdərk dövrü nəsri üzrə «əsər - müəllif» cütlüyü hansı düzgündür?','«Talvar» Elçinin, «Zəhər» isə İsa Hüseynovun əsəridir.',array['«Talvar» - Elçin','«Talvar» - Anar','«Zəhər» - Elçin','«Namərd gülləsi» - Anar'],1),
('edeb9-ozunuderk-nesr#21','edebiyyat','edeb-9-ozunuderk-nesr',3,3,'Bu dövr nasirləri haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','«Məhşər» İsa Hüseynovun romanıdır.',array['«Məhşər» Anarın romanıdır','«Talvar» Elçinin əsəridir','«Zəhər» İsa Hüseynovundur','«Namərd gülləsi» İsmayıl Şıxlınındır'],1),
('edeb9-ozunuderk-nesr#22','edebiyyat','edeb-9-ozunuderk-nesr',3,3,'Bu dövr yazıçıları üzrə «yazıçı - ailə» cütlüyü hansı doğrudur?','Anar Rəsul Rzanın, Elçin isə İlyas Əfəndiyevin oğludur.',array['Anar - Rəsul Rzanın oğlu','Elçin - Rəsul Rzanın oğlu','Anar - İlyas Əfəndiyevin oğlu','İsa Hüseynov - Mir Cəlalın oğlu'],1),
('edeb9-ozunuderk-nesr#23','edebiyyat','edeb-9-ozunuderk-nesr',3,3,'Bu dövr nəsrində psixoloji təhlilin güclənməsinin səbəbi nədir?','Diqqətin ictimai plakatdan insanın daxili dünyasına yönəlməsi.',array['Diqqətin daxili dünyaya yönəlməsi','Sənədli mənbələrin çoxalması','Tarixi salnamə ənənəsi','Kino sənayesinin tələbi'],1),
('edeb9-ozunuderk-nesr#24','edebiyyat','edeb-9-ozunuderk-nesr',3,3,'Ədəbi mərhələlər zaman baxımından necə düzülür? (1 - özünüdərk dövrü, 2 - müstəqillik dövrü, 3 - müharibə dövrü)','Müharibə dövrü 1941-1960, özünüdərk dövrü 1961-1990, müstəqillik dövrü isə 1991-ci ildən sonranı əhatə edir.',array['3 - 1 - 2','1 - 2 - 3','2 - 3 - 1','1 - 3 - 2'],1),
('edeb9-ozunuderk-nesr#25','edebiyyat','edeb-9-ozunuderk-nesr',3,3,'Anar və Elçinin ədəbi mühitlə bağlılığı haqqında hansı fikir doğrudur?','Hər ikisi tanınmış ədəbi ailədən çıxmışdır.',array['Hər ikisi tanınmış ədəbi ailədən çıxmışdır','Hər ikisi ədəbiyyata kənar sahədən gəlmişdir','Biri şair, digəri bəstəkar kimi tanınır','Hər ikisi ancaq tərcümə ilə məşğul olmuşdur'],1),
('edeb9-ozunuderk-nesr#26','edebiyyat','edeb-9-ozunuderk-nesr',3,3,'Bu dövr nəsri haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Bu dövr nəsri sənədli xronika deyil, psixoloji təhlil üzərində qurulub.',array['Bu dövr nəsri sənədli xronika üslubundadır','Psixoloji təhlil bu nəsrdə güclüdür','Milli yaddaş mövzusu geniş işlənir','Anar bu dövrün nasirlərindəndir'],1),
('edeb9-ozunuderk-nesr#27','edebiyyat','edeb-9-ozunuderk-nesr',3,3,'Müharibə dövrü nəsri ilə özünüdərk dövrü nəsrinin fərqi nədir?','Birincidə cəbhə və arxa, ikincidə insanın daxili dünyası önə çıxır.',array['Birincidə cəbhə, ikincidə daxili dünya önə çıxır','Birincidə daxili dünya, ikincidə cəbhə önə çıxır','Hər ikisində eyni mövzular işlənir','Hər ikisi sənədli üslubda yazılıb'],1),
('edeb9-ozunuderk-nesr#28','edebiyyat','edeb-9-ozunuderk-nesr',3,3,'Bu dövr əsərləri üzrə «əsər - janr» cütlüyü hansı doğrudur?','«Namərd gülləsi» hekayə, «Məhşər» isə romandır.',array['«Namərd gülləsi» - hekayə','«Namərd gülləsi» - roman','«Məhşər» - hekayə','«Mahmud və Məryəm» - hekayə'],1),
('edeb9-ozunuderk-nesr#29','edebiyyat','edeb-9-ozunuderk-nesr',3,3,'«Məhşər» romanında Nəsimi mövzusuna müraciətin səbəbi nədir?','Milli tarixə və mənəvi köklərə qayıdış meyli.',array['Milli tarixə və mənəvi köklərə qayıdış','Sənədli mənbələrin çoxluğu','Xarici nəşriyyat sifarişi','Klassik dili öyrənmək məqsədi'],1),
('edeb9-ozunuderk-nesr#30','edebiyyat','edeb-9-ozunuderk-nesr',3,3,'Bu dövr yazıçıları üzrə «yazıçı - ikinci sahə» cütlüyü hansı düzgündür?','Anar kino ssenariləri yazmış, filmlərin yaranmasında iştirak etmişdir.',array['Anar - kino ssenaristi','İsmayıl Şıxlı - kino ssenaristi','Anar - opera bəstəkarı','Elçin - memar'],1),
('edeb9-ozunuderk-nesr#31','edebiyyat','edeb-9-ozunuderk-nesr',3,3,'Bu dövr nəsrində kənd və şəhər mövzusu necə qarşılaşdırılır?','Kənd köklə, şəhər isə dəyişən müasir həyatla bağlanır.',array['Kənd köklə, şəhər dəyişən həyatla bağlanır','Şəhər köklə, kənd dəyişən həyatla bağlanır','Hər ikisi eyni cür təsvir olunur','Kənd mövzusuna demək olar toxunulmur'],1),
('edeb9-mustaqillik#1','edebiyyat','edeb-9-mustaqillik',1,3,'«İstiqlal» şeirinin müəllifi kimdir?','Şeirin müəllifi Bəxtiyar Vahabzadədir.',array['Bəxtiyar Vahabzadə','Xəlil Rza Ulutürk','Qılman İlkin','Sabir Əhmədov'],1),
('edeb9-mustaqillik#2','edebiyyat','edeb-9-mustaqillik',1,3,'Bu mərhələ hansı ildən başlayır?','Mərhələ 1991-ci ildən - dövlət müstəqilliyinin bərpasından başlayır.',array['1991-ci ildən','1960-cı ildən','1941-ci ildən','1920-ci ildən'],1),
('edeb9-mustaqillik#3','edebiyyat','edeb-9-mustaqillik',1,3,'«Qaytar mənim qüdrətimi, Azərbaycan!» şeirinin müəllifi kimdir?','Şeirin müəllifi Xəlil Rza Ulutürkdür.',array['Xəlil Rza Ulutürk','Bəxtiyar Vahabzadə','Məmməd Araz','Anar'],1),
('edeb9-mustaqillik#4','edebiyyat','edeb-9-mustaqillik',1,3,'«İntiqam» əsərinin müəllifi kimdir?','Əsərin müəllifi Qılman İlkindir.',array['Qılman İlkin','Sabir Əhmədov','Elçin','İsa Hüseynov'],1),
('edeb9-mustaqillik#5','edebiyyat','edeb-9-mustaqillik',2,3,'Azərbaycan dövlət müstəqilliyini hansı ildə bərpa etmişdir?','Müstəqillik 1991-ci ildə bərpa olunmuşdur.',array['1991','1918','1936','2001'],1),
('edeb9-mustaqillik#6','edebiyyat','edeb-9-mustaqillik',2,3,'Bu dövr ədəbiyyatının aparıcı mövzusu nədir?','Müstəqillik, Qarabağ və şəhidlik mövzusudur.',array['Müstəqillik və Qarabağ mövzusu','Sənaye tikintisi','Kosmos yarışı','Dəniz ticarəti'],1),
('edeb9-mustaqillik#7','edebiyyat','edeb-9-mustaqillik',2,3,'«Dənizdən gələn səda» əsərinin müəllifi kimdir?','Əsərin müəllifi Sabir Əhmədovdur.',array['Sabir Əhmədov','Qılman İlkin','Elçin','Anar'],1),
('edeb9-mustaqillik#8','edebiyyat','edeb-9-mustaqillik',2,3,'Xəlil Rza Ulutürkün şeirlərində hansı ovqat hakimdir?','Üsyankarlıq və mübarizə ruhu hakimdir.',array['Üsyankarlıq və mübarizə ruhu','Sakit məişət ovqatı','Yumor və zarafat','Quru elmi təhlil'],1),
('edeb9-mustaqillik#9','edebiyyat','edeb-9-mustaqillik',2,3,'«İstiqlal» şeirində şair nəyi tərənnüm edir?','Şeirdə müstəqillik arzusu tərənnüm olunur.',array['Müstəqillik arzusunu','Ticarət uğurunu','Şəhər memarlığını','Dəniz gözəlliyini'],1),
('edeb9-mustaqillik#10','edebiyyat','edeb-9-mustaqillik',2,3,'20 Yanvar faciəsi hansı ildə baş vermişdir?','Faciə 1990-cı ildə baş vermişdir.',array['1990','1988','1992','1994'],1),
('edeb9-mustaqillik#11','edebiyyat','edeb-9-mustaqillik',2,3,'Bu dövr ədəbiyyatında hansı yeni mövzu meydana çıxdı?','Qaçqınlıq və işğal mövzusu meydana çıxdı.',array['Qaçqınlıq və işğal mövzusu','Sənaye briqadası mövzusu','Kolxoz quruculuğu mövzusu','Kosmos uçuşu mövzusu'],1),
('edeb9-mustaqillik#12','edebiyyat','edeb-9-mustaqillik',2,3,'Müstəqillik dövrü ədəbiyyatında sənədlilik nə hesabına artdı?','Real hadisələrə birbaşa müraciət hesabına artdı.',array['Real hadisələrə birbaşa müraciətlə','Nağıl süjetlərinin artması ilə','Əruz vəzninə qayıdışla','Xarici tərcümələrin çoxalması ilə'],1),
('edeb9-mustaqillik#13','edebiyyat','edeb-9-mustaqillik',2,3,'Bəxtiyar Vahabzadənin bu dövr şeirlərində hansı fikir önə çəkilir?','Milli istiqlal və vətəndaş məsuliyyəti fikri önə çəkilir.',array['Milli istiqlal və vətəndaş məsuliyyəti','Ticarət qaydaları','Dəniz macərası','Kosmos texnikası'],1),
('edeb9-mustaqillik#14','edebiyyat','edeb-9-mustaqillik',2,3,'Senzuranın aradan qalxması ədəbiyyatda nəyə imkan verdi?','Uzun illər qadağan olunmuş mövzuların açılmasına imkan verdi.',array['Qadağan mövzuların açılmasına','Nəşrin dayandırılmasına','Ədəbi dilin dəyişməsinə','Şeir vəzninin ləğvinə'],1),
('edeb9-mustaqillik#15','edebiyyat','edeb-9-mustaqillik',2,3,'Qılman İlkin hansı ədəbi növdə çalışmışdır?','O, əsasən nəsrdə çalışmışdır.',array['Nəsrdə','Aşıq şeirində','Bədii tərcümədə','Ədəbi tənqiddə'],1),
('edeb9-mustaqillik#16','edebiyyat','edeb-9-mustaqillik',2,3,'Sabir Əhmədov hansı ədəbi növün nümayəndəsidir?','O, nəsrin nümayəndəsidir.',array['Nəsrin','Dramaturgiyanın','Aşıq şeirinin','Ədəbi tənqidin'],1),
('edeb9-mustaqillik#17','edebiyyat','edeb-9-mustaqillik',2,3,'Bu dövrdə hansı tarixi mövzu ədəbiyyata qayıtdı?','Cümhuriyyət və repressiya həqiqətləri ədəbiyyata qayıtdı.',array['Cümhuriyyət və repressiya həqiqətləri','Kolxoz quruculuğu','Beşillik sənaye planı','Kosmos proqramı'],1),
('edeb9-mustaqillik#18','edebiyyat','edeb-9-mustaqillik',2,3,'Müstəqillik dövrü ədəbiyyatının dili necədir?','Dil sərbəstdir, publisistik ünsürlərlə zəngindir.',array['Sərbəst və publisistik','Ağır əruz dilində','Sırf tərcümə dilində','Quru rəsmi dildə'],1),
('edeb9-mustaqillik#19','edebiyyat','edeb-9-mustaqillik',2,3,'Bu dövrdə ədəbiyyatın qarşısında duran əsas vəzifə nə idi?','Milli yaddaşı bərpa etmək vəzifəsi idi.',array['Milli yaddaşı bərpa etmək','Sənaye planını yerinə yetirmək','Xarici bazar açmaq','Kosmos tədqiqatı aparmaq'],1),
('edeb9-mustaqillik#20','edebiyyat','edeb-9-mustaqillik',3,3,'Müstəqillik dövrü üzrə «əsər - müəllif» cütlüyü hansı düzgündür?','«İstiqlal» Bəxtiyar Vahabzadənin, «İntiqam» Qılman İlkinindir.',array['«İstiqlal» - Bəxtiyar Vahabzadə','«İstiqlal» - Xəlil Rza Ulutürk','«İntiqam» - Bəxtiyar Vahabzadə','«Dənizdən gələn səda» - Qılman İlkin'],1),
('edeb9-mustaqillik#21','edebiyyat','edeb-9-mustaqillik',3,3,'Müstəqillik dövrü haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Bu mərhələ 1991-ci ildən başlayır.',array['Bu mərhələ 1941-ci ildən başlayır','Qarabağ mövzusu bu dövrdə güclənmişdir','«İstiqlal» Bəxtiyar Vahabzadənindir','Senzura bu dövrdə aradan qalxmışdır'],1),
('edeb9-mustaqillik#22','edebiyyat','edeb-9-mustaqillik',3,3,'Aşağıdakı üç hadisə zaman ardıcıllığı ilə necə düzülür? (1 - müstəqilliyin bərpası, 2 - 20 Yanvar faciəsi, 3 - Xocalı faciəsi)','20 Yanvar 1990-cı ildə, müstəqilliyin bərpası 1991-ci ildə, Xocalı faciəsi isə 1992-ci ildə baş vermişdir.',array['2 - 1 - 3','1 - 2 - 3','3 - 2 - 1','2 - 3 - 1'],1),
('edeb9-mustaqillik#23','edebiyyat','edeb-9-mustaqillik',3,3,'Qarabağ mövzusunun ədəbiyyata gəlməsinin səbəbi nədir?','Torpaqların işğalı və kütləvi qaçqınlıq bu mövzunu doğurdu.',array['Torpaqların işğalı və qaçqınlıq','Sənaye tikintisinin başlanması','Yeni əlifbaya keçilməsi','Kosmos proqramının genişlənməsi'],1),
('edeb9-mustaqillik#24','edebiyyat','edeb-9-mustaqillik',3,3,'Aşağıdakı «hadisə - il» cütlüklərindən hansı düzgündür?','20 Yanvar faciəsi 1990-cı ildə baş vermişdir.',array['20 Yanvar faciəsi - 1990','20 Yanvar faciəsi - 1992','Müstəqilliyin bərpası - 1990','Xocalı faciəsi - 1990'],1),
('edeb9-mustaqillik#25','edebiyyat','edeb-9-mustaqillik',3,3,'«İstiqlal» və «Qaytar mənim qüdrətimi» şeirlərini birləşdirən cəhət nədir?','Hər ikisi milli azadlıq çağırışı üzərində qurulub.',array['Hər ikisi milli azadlıq çağırışıdır','Hər ikisi məhəbbət lirikası nümunəsidir','Hər ikisi təbiət təsviri üzərindədir','Hər ikisi uşaq şeiri nümunəsidir'],1),
('edeb9-mustaqillik#26','edebiyyat','edeb-9-mustaqillik',3,3,'Müstəqillik illərinin ədəbi mühiti barədə hansı fikir SƏHVDİR?','Müstəqillik dövründə senzura gücləndi deyil, aradan qalxdı.',array['Müstəqillik dövründə senzura gücləndi','Müstəqillik illərində qaçqınlıq mövzusu ədəbiyyata gəldi','Cümhuriyyət həqiqətləri açıldı','Şəhidlik mövzusu güclü şəkildə işləndi'],1),
('edeb9-mustaqillik#27','edebiyyat','edeb-9-mustaqillik',3,3,'Sovet dövrü ilə müstəqillik dövrü ədəbiyyatının əsas fərqi nədir?','Müstəqillik dövründə mövzu seçimi sərbəstləşdi.',array['Mövzu seçiminin sərbəstləşməsi','Mövzu seçiminin daralması','Şeir janrının tamamilə dayanması','Nəsr janrının qadağan olunması'],1),
('edeb9-mustaqillik#28','edebiyyat','edeb-9-mustaqillik',3,3,'Bu dövr şairləri üzrə «şair - əsər» cütlüyü hansı doğrudur?','«Qaytar mənim qüdrətimi» Xəlil Rza Ulutürkün şeiridir.',array['Xəlil Rza Ulutürk - «Qaytar mənim qüdrətimi»','Bəxtiyar Vahabzadə - «Qaytar mənim qüdrətimi»','Xəlil Rza Ulutürk - «İntiqam»','Qılman İlkin - «İstiqlal»'],1),
('edeb9-mustaqillik#29','edebiyyat','edeb-9-mustaqillik',3,3,'Müstəqillik dövründə repressiya mövzusunun açılmasının səbəbi nədir?','Arxivlərin açılması və senzuranın aradan qalxması.',array['Arxivlərin açılması və senzuranın qalxması','Yeni dərsliklərin yazılması','Xarici tərcümələrin artması','Teatr repertuarının dəyişməsi'],1),
('edeb9-mustaqillik#30','edebiyyat','edeb-9-mustaqillik',3,3,'Aşağıdakı «dövr - səciyyəvi mövzu» cütlüklərindən hansı düzgündür?','Qarabağ mövzusu müstəqillik dövrü ədəbiyyatı üçün səciyyəvidir.',array['Müstəqillik dövrü - Qarabağ mövzusu','Repressiya dövrü - Qarabağ mövzusu','Müstəqillik dövrü - kolxoz quruculuğu','Müharibə dövrü - Qarabağ mövzusu'],1),
('edeb9-mustaqillik#31','edebiyyat','edeb-9-mustaqillik',3,3,'Müstəqillik dövrü ilə milli-demokratik dövrün ortaq cəhəti nədir?','Hər ikisində istiqlal ideyası mərkəzi yer tutur.',array['Hər ikisində istiqlal ideyası mərkəzdədir','Hər ikisində sinfi mübarizə mərkəzdədir','Hər ikisi XIX əsrə aid dövrlərdir','Hər ikisində əruz vəzni hakimdir'],1),
('edeb9-cenub#1','edebiyyat','edeb-9-cenub',1,4,'Məhəmmədhüseyn Şəhriyarın ana dilində yazdığı ən məşhur poeması hansıdır?','Bu, «Heydərbabaya salam» poemasıdır.',array['«Heydərbabaya salam»','«Sazımın sözü»','«Səhənd dağı»','«Gələcək gün»'],1),
('edeb9-cenub#2','edebiyyat','edeb-9-cenub',1,4,'Məhəmmədhüseyn Şəhriyar hansı ölkədə yaşayıb-yaratmışdır?','Şair İranda - Cənubi Azərbaycanda yaşayıb-yaratmışdır.',array['İranda','Türkiyədə','Rusiyada','Misirdə'],1),
('edeb9-cenub#3','edebiyyat','edeb-9-cenub',1,4,'«Səhənd dağı» şeirinin müəllifi kimdir?','Şeirin müəllifi Həbib Sahirdir.',array['Həbib Sahir','Məhəmmədhüseyn Şəhriyar','Balaş Azəroğlu','Süleyman Rüstəm'],1),
('edeb9-cenub#4','edebiyyat','edeb-9-cenub',1,4,'Cənubi Azərbaycan ədəbiyyatının ana dilli qolu hansı dildə yaranır?','Bu ədəbiyyat Azərbaycan dilində yaranır.',array['Azərbaycan dilində','Ərəb dilində','Rus dilində','İngilis dilində'],1),
('edeb9-cenub#5','edebiyyat','edeb-9-cenub',2,4,'«Heydərbabaya salam»ın birinci hissəsi hansı ildə yazılmışdır?','Poemanın birinci hissəsi 1954-cü ildə yazılmışdır.',array['1954','1937','1975','1991'],1),
('edeb9-cenub#6','edebiyyat','edeb-9-cenub',2,4,'«Heydərbabaya salam» poemasında hansı dövr xatırlanır?','Poemada şairin uşaqlıq illəri xatırlanır.',array['Şairin uşaqlıq illəri','Gələcək əsr','Orta əsrlər','Antik dövr'],1),
('edeb9-cenub#7','edebiyyat','edeb-9-cenub',2,4,'«Heydərbabaya salam» poemasının vəzni hansıdır?','Poema heca vəznində yazılmışdır.',array['Heca vəzni','Əruz vəzni','Sərbəst şeir','Ağ şeir'],1),
('edeb9-cenub#8','edebiyyat','edeb-9-cenub',2,4,'«Heydərbabaya salam» poemasının dili necədir?','Dil sadə, canlı danışıq dilinə çox yaxındır.',array['Sadə, canlı danışıq dili','Ağır kitab dili','Elmi termin dili','Rəsmi sənəd dili'],1),
('edeb9-cenub#9','edebiyyat','edeb-9-cenub',2,4,'Məhəmmədhüseyn Şəhriyar hansı ildə vəfat etmişdir?','Şair 1988-ci ildə vəfat etmişdir.',array['1988','1954','1969','2001'],1),
('edeb9-cenub#10','edebiyyat','edeb-9-cenub',2,4,'Məhəmmədhüseyn Şəhriyar harada dəfn olunmuşdur?','O, Təbrizdə şairlər məqbərəsində dəfn olunmuşdur.',array['Təbrizdə şairlər məqbərəsində','Bakıda Fəxri xiyabanda','Tehranda','İstanbulda'],1),
('edeb9-cenub#11','edebiyyat','edeb-9-cenub',2,4,'«Heydərbabaya salam» Şimali Azərbaycanda necə qarşılandı?','Poema böyük maraqla qarşılandı, ona çoxlu nəzirə yazıldı.',array['Böyük maraqla qarşılandı, nəzirələr yazıldı','Diqqətdən kənarda qaldı','Oxucuya çatdırılmadı','Tez unuduldu'],1),
('edeb9-cenub#12','edebiyyat','edeb-9-cenub',2,4,'«Heydərbabaya salam» poemasında hansı obrazlar xüsusi yer tutur?','Kənd adamları və doğma təbiət obrazları xüsusi yer tutur.',array['Kənd adamları və təbiət','Saray əyanları','Dəniz kapitanları','Kosmos alimləri'],1),
('edeb9-cenub#13','edebiyyat','edeb-9-cenub',2,4,'Şəhriyarın «Səhəndiyyə» şeiri kimə müraciətlə yazılmışdır?','Şeir şair Səhəndə - Bulud Qaraçorluya müraciətlə yazılmışdır.',array['Şair Səhəndə','Nizami Gəncəviyə','Məhəmməd Füzuliyə','Molla Pənah Vaqifə'],1),
('edeb9-cenub#14','edebiyyat','edeb-9-cenub',2,4,'Cənub şairlərinin şeirlərində Araz çayı nəyin nişanıdır?','Araz iki tayın ayrılığının nişanıdır.',array['Ayrılığın nişanıdır','Bolluğun nişanıdır','Ticarətin nişanıdır','Qələbənin nişanıdır'],1),
('edeb9-cenub#15','edebiyyat','edeb-9-cenub',2,4,'Məhəmmədhüseyn Şəhriyar fars ədəbiyyatında hansı yerə sahibdir?','O, fars dilində də tanınmış şair sayılır.',array['Tanınmış şair kimi tanınır','Naməlum qalmışdır','Ancaq tərcüməçi sayılır','Nasir kimi tanınır'],1),
('edeb9-cenub#16','edebiyyat','edeb-9-cenub',2,4,'Poemanın adındakı «salam» sözü nəyi bildirir?','Şairin doğma yerlərə, dağa müraciətini bildirir.',array['Doğma yerlərə müraciəti','Rəsmi məktub formasını','Hərbi salam qaydasını','Ticarət müqaviləsini'],1),
('edeb9-cenub#17','edebiyyat','edeb-9-cenub',2,4,'Həbib Sahir hansı ədəbi növün nümayəndəsidir?','Həbib Sahir şeirin nümayəndəsidir.',array['Şeirin','Dramaturgiyanın','Ədəbi tənqidin','Publisistikanın'],1),
('edeb9-cenub#18','edebiyyat','edeb-9-cenub',2,4,'«Heydərbabaya salam» hansı janrdadır?','Əsər lirik-xatirə poemasıdır.',array['Poema','Hekayə','Dram','Roman'],1),
('edeb9-cenub#19','edebiyyat','edeb-9-cenub',2,4,'«Heydərbabaya salam» hansı bədii ovqatı ilə seçilir?','Xatirə və nostalji ovqatı ilə seçilir.',array['Xatirə və nostalji ovqatı','Detektiv gərginlik','Elmi dəqiqlik','Sənədli quruluş'],1),
('edeb9-cenub#20','edebiyyat','edeb-9-cenub',3,4,'Cənub ədəbiyyatı üzrə «əsər - müəllif» cütlüyü hansı düzgündür?','«Səhənd dağı» Həbib Sahirin, «Səhəndiyyə» isə Şəhriyarındır.',array['«Səhənd dağı» - Həbib Sahir','«Səhənd dağı» - Məhəmmədhüseyn Şəhriyar','«Heydərbabaya salam» - Həbib Sahir','«Səhəndiyyə» - Həbib Sahir'],1),
('edeb9-cenub#21','edebiyyat','edeb-9-cenub',3,4,'«Heydərbabaya salam» haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Poema ana dilində - Azərbaycan dilində yazılmışdır.',array['Poema fars dilində yazılmışdır','Poema heca vəznindədir','Poemanın birinci hissəsi 1954-cü ildəndir','Şəhriyar Təbrizdə dəfn olunmuşdur'],1),
('edeb9-cenub#22','edebiyyat','edeb-9-cenub',3,4,'Aşağıdakı üç hadisə zaman ardıcıllığı ilə necə düzülür? (1 - poemanın yazılması, 2 - şairin vəfatı, 3 - şairin doğulması)','Şəhriyar 1906-cı ildə doğulub, poemanı 1954-cü ildə yazıb, 1988-ci ildə vəfat edib.',array['3 - 1 - 2','1 - 2 - 3','2 - 3 - 1','1 - 3 - 2'],1),
('edeb9-cenub#23','edebiyyat','edeb-9-cenub',3,4,'«Heydərbabaya salam»ın hər iki tayda geniş yayılmasının səbəbi nədir?','Poema ana dilində, sadə və hər kəsə doğma dildə yazılmışdı.',array['Ana dilində və hamıya doğma olması','Fars dilində yazılması','Saray sifarişi ilə yaranması','Elmi mövzuya həsr olunması'],1),
('edeb9-cenub#24','edebiyyat','edeb-9-cenub',3,4,'Cənub şairləri üzrə «şair - əsər» cütlüyü hansı doğrudur?','«Səhəndiyyə» Şəhriyarın, «Səhənd dağı» Həbib Sahirin şeiridir.',array['Şəhriyar - «Səhəndiyyə»','Həbib Sahir - «Səhəndiyyə»','Şəhriyar - «Səhənd dağı»','Səhənd - «Heydərbabaya salam»'],1),
('edeb9-cenub#25','edebiyyat','edeb-9-cenub',3,4,'Şəhriyarın doğum ili ilə vəfat ili arasında neçə il var?','Şair 1906-cı ildə doğulub, 1988-ci ildə vəfat edib.',array['82 il','72 il','62 il','92 il'],1),
('edeb9-cenub#26','edebiyyat','edeb-9-cenub',3,4,'Cənub ədəbiyyatı haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Ana dili mövzusu bu ədəbiyyatda ən güclü mövzulardandır.',array['Bu ədəbiyyatda ana dili mövzusu zəifdir','Araz çayı ayrılıq nişanıdır','Şəhriyar Cənub ədəbiyyatının nümayəndəsidir','Həbib Sahir Cənub şairlərindəndir'],1),
('edeb9-cenub#27','edebiyyat','edeb-9-cenub',3,4,'«Heydərbabaya salam» ilə klassik divan şeirinin fərqi nədir?','Poema sadə heca vəznindədir, divan şeiri isə əruz vəznindədir.',array['Biri sadə heca, digəri əruz vəznindədir','Biri əruz, digəri sadə heca vəznindədir','Hər ikisi heca vəznindədir','Hər ikisi sərbəst şeirdir'],1),
('edeb9-cenub#28','edebiyyat','edeb-9-cenub',3,4,'Cənub ədəbiyyatı üzrə «əsər - mövzu» cütlüyü hansı düzgündür?','«Heydərbabaya salam» uşaqlıq xatirələri üzərində qurulub.',array['«Heydərbabaya salam» - uşaqlıq xatirələri','«Heydərbabaya salam» - dəniz səfəri təəssüratı','«Səhənd dağı» - kosmos tədqiqatı mövzusu','«Səhəndiyyə» - ticarət yolları mövzusu'],1),
('edeb9-cenub#29','edebiyyat','edeb-9-cenub',3,4,'Şəhriyarın ana dilində yazmasının Cənub ədəbiyyatı üçün əhəmiyyəti nədir?','Ana dilli şeirə güclü təkan vermiş, onun nüfuzunu artırmışdır.',array['Ana dilli şeirə güclü təkan verməsi','Fars şeirini daha da gücləndirməsi','Tərcümə ənənəsini başlatması','Nəsr janrının yaranmasına səbəb olması'],1),
('edeb9-cenub#30','edebiyyat','edeb-9-cenub',3,4,'Şəhriyar və Həbib Sahir haqqında hansı fikir doğrudur?','Hər ikisi Cənubi Azərbaycan ədəbiyyatının nümayəndəsidir.',array['Hər ikisi Cənubi Azərbaycan şairidir','Hər ikisi Şimalda yaşayıb-yaratmışdır','Biri şair, digəri dramaturq olmuşdur','Hər ikisi ancaq nəsr yazmışdır'],1),
('edeb9-cenub#31','edebiyyat','edeb-9-cenub',3,4,'Cənub və klassik poeziya üzrə «əsər - vəzn» cütlüyü hansı doğrudur?','«Heydərbabaya salam» heca, «Leyli və Məcnun» isə əruz vəznindədir.',array['«Heydərbabaya salam» - heca vəzni','«Heydərbabaya salam» - əruz vəzni','«Leyli və Məcnun» - heca vəzni','«Xəmsə» - heca vəzni'],1),
('edeb9-dunya#1','edebiyyat','edeb-9-dunya',1,4,'«Qoca və dəniz» əsərinin baş qəhrəmanı kimdir?','Əsərin baş qəhrəmanı qoca balıqçı Santyaqodur.',array['Santyaqo','Manolin','Robinzon','Hamlet'],1),
('edeb9-dunya#2','edebiyyat','edeb-9-dunya',1,4,'Ernest Heminquey hansı ölkənin yazıçısıdır?','Heminquey ABŞ yazıçısıdır.',array['ABŞ-ın','İngiltərənin','Fransanın','Almaniyanın'],1),
('edeb9-dunya#3','edebiyyat','edeb-9-dunya',1,4,'«Qoca və dəniz» hansı janrdadır?','Əsər povest janrındadır.',array['Povest','Qəzəl','Dastan','Faciə'],1),
('edeb9-dunya#4','edebiyyat','edeb-9-dunya',1,4,'Santyaqo peşəsinə görə kimdir?','Santyaqo balıqçıdır.',array['Balıqçı','Müəllim','Həkim','Dəmirçi'],1),
('edeb9-dunya#5','edebiyyat','edeb-9-dunya',2,4,'Santyaqonun şagirdi olan oğlanın adı nədir?','Oğlanın adı Manolindir.',array['Manolin','Nofəl','Eyvaz','Uruz'],1),
('edeb9-dunya#6','edebiyyat','edeb-9-dunya',2,4,'Santyaqo neçə gün balıq tuta bilmir?','O, səksən dörd gün balıqsız qalır.',array['84 gün','14 gün','40 gün','120 gün'],1),
('edeb9-dunya#7','edebiyyat','edeb-9-dunya',2,4,'Santyaqo hansı böyük balığı tutur?','O, nəhəng marlin balığını tutur.',array['Nəhəng marlin balığını','Balina','Nəhəng tısbağa','Səkkizayaq'],1),
('edeb9-dunya#8','edebiyyat','edeb-9-dunya',2,4,'Tutulan balığa yolda kimlər hücum edir?','Balığa köpək balıqları hücum edir.',array['Köpək balıqları','Dəniz quşları','Digər balıqçılar','Sahil gözətçiləri'],1),
('edeb9-dunya#9','edebiyyat','edeb-9-dunya',2,4,'Qoca sahilə nə ilə qayıdır?','O, balığın yalnız skeleti ilə qayıdır.',array['Balığın skeleti ilə','Bütöv balıqla','Boş qayıqla','Yeni torla'],1),
('edeb9-dunya#10','edebiyyat','edeb-9-dunya',2,4,'Əsərdəki hadisələr hansı ölkənin sahillərində cərəyan edir?','Hadisələr Kuba sahillərində cərəyan edir.',array['Kubanın','Yunanıstanın','Norveçin','Yaponiyanın'],1),
('edeb9-dunya#11','edebiyyat','edeb-9-dunya',2,4,'«Qoca və dəniz» hansı ildə nəşr olunmuşdur?','Əsər 1952-ci ildə nəşr olunmuşdur.',array['1952','1932','1962','1972'],1),
('edeb9-dunya#12','edebiyyat','edeb-9-dunya',2,4,'Ernest Heminquey hansı ildə Nobel mükafatına layiq görülmüşdür?','Yazıçı 1954-cü ildə Nobel mükafatı almışdır.',array['1954','1944','1964','1974'],1),
('edeb9-dunya#13','edebiyyat','edeb-9-dunya',2,4,'Heminqueyin yazı üslubu necə səciyyələnir?','Qısa, təmkinli cümlələr və artıq təsvirdən qaçmaq səciyyəvidir.',array['Qısa və təmkinli cümlələr','Uzun və təmtəraqlı təsvirlər','Qafiyəli nəsr','Sənədli protokol üslubu'],1),
('edeb9-dunya#14','edebiyyat','edeb-9-dunya',2,4,'«Qoca və dəniz» əsərinin əsas ideyası nədir?','İnsan iradəsinin məğlubedilməzliyi ideyasıdır.',array['İnsan iradəsinin məğlubedilməzliyi','Var-dövlət toplamağın vacibliyi','Səyahətin təhlükəsi','Ticarətin faydası'],1),
('edeb9-dunya#15','edebiyyat','edeb-9-dunya',2,4,'Santyaqo ilə Manolin arasındakı münasibət necədir?','Aralarında ustad-şagird dostluğu var.',array['Ustad-şagird dostluğu','Kəskin rəqiblik','Yaxın qohumluq','Ticarət ortaqlığı'],1),
('edeb9-dunya#16','edebiyyat','edeb-9-dunya',2,4,'Aşağıdakılardan hansı Ernest Heminqueyin əsəridir?','«Əlvida, silah!» Heminqueyin romanıdır.',array['«Əlvida, silah!»','«Ağ dəvə»','«Məhşər»','«Gələcək gün»'],1),
('edeb9-dunya#17','edebiyyat','edeb-9-dunya',2,4,'Ernest Heminquey ədəbiyyatdan başqa hansı sahədə çalışmışdır?','O, uzun müddət jurnalist kimi çalışmışdır.',array['Jurnalistikada','Memarlıqda','Tibb sahəsində','Kənd təsərrüfatında'],1),
('edeb9-dunya#18','edebiyyat','edeb-9-dunya',2,4,'Əsərdə dəniz nəyin simvolu kimi verilir?','Dəniz həyatın və mübarizə meydanının simvoludur.',array['Həyatın və mübarizənin','Ticarət yolunun','Rahatlığın','Unutqanlığın'],1),
('edeb9-dunya#19','edebiyyat','edeb-9-dunya',2,4,'Qocanın məğlub sayılmamasının səbəbi nədir?','O, hər şeyi itirsə də ruhdan düşmür.',array['Ruhdan düşməməsi','Çoxlu balıq tutması','Var-dövlət qazanması','Şəhərə köçməsi'],1),
('edeb9-dunya#20','edebiyyat','edeb-9-dunya',3,4,'«Qoca və dəniz» üzrə «obraz - rol» cütlüyü hansı düzgündür?','Manolin qocanın şagirdi, Santyaqo isə balıqçıdır.',array['Manolin - qocanın şagirdi','Santyaqo - qocanın şagirdi','Manolin - qayıq sahibi','Santyaqo - şəhər taciri'],1),
('edeb9-dunya#21','edebiyyat','edeb-9-dunya',3,4,'«Qoca və dəniz» haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Qoca sahilə balığın yalnız skeleti ilə qayıdır.',array['Qoca sahilə bütöv balıqla qayıdır','Qoca səksən dörd gün balıq tutmur','Hadisələr Kuba sahillərində keçir','Manolin qocanın şagirdidir'],1),
('edeb9-dunya#22','edebiyyat','edeb-9-dunya',3,4,'Əsərdəki üç hadisə ardıcıllıqla necə düzülür? (1 - uğursuz günlər, 2 - böyük balığın tutulması, 3 - köpək balıqlarının hücumu)','Əvvəlcə uzun uğursuz günlər keçir, sonra balıq tutulur, sonra köpək balıqları hücum edir.',array['1 - 2 - 3','2 - 1 - 3','3 - 2 - 1','2 - 3 - 1'],1),
('edeb9-dunya#23','edebiyyat','edeb-9-dunya',3,4,'Qocanın böyük balığı bütöv halda sahilə çatdıra bilməməsinin səbəbi nədir?','Yolda köpək balıqları hücum edib balığı yeyir.',array['Köpək balıqlarının hücumu','Qayığın yolda batması','Balıqçı torunun cırılması','Qocanın yolunu azması'],1),
('edeb9-dunya#24','edebiyyat','edeb-9-dunya',3,4,'Dünya ədəbiyyatı üzrə «əsər - müəllif» cütlüyü hansı doğrudur?','«Qoca və dəniz» Ernest Heminqueyin əsəridir.',array['«Qoca və dəniz» - Ernest Heminquey','«Qoca və dəniz» - Çingiz Aytmatov','«Əlvida, silah!» - Çingiz Aytmatov','«Məhşər» - Ernest Heminquey'],1),
('edeb9-dunya#25','edebiyyat','edeb-9-dunya',3,4,'Əsərin nəşri ilə yazıçının Nobel mükafatı arasında neçə il var?','Əsər 1952-ci ildə nəşr olunub, mükafat 1954-cü ildə verilib.',array['2 il','6 il','10 il','20 il'],1),
('edeb9-dunya#26','edebiyyat','edeb-9-dunya',3,4,'Ernest Heminquey haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Heminquey Amerika yazıçısıdır, ingilis deyil.',array['O, ingilis yazıçısıdır','O, Nobel mükafatı almışdır','«Qoca və dəniz» onun povestidir','O, jurnalist kimi də çalışmışdır'],1),
('edeb9-dunya#27','edebiyyat','edeb-9-dunya',3,4,'Santyaqonun itkisi ilə qələbəsi arasındakı münasibət necə izah olunur?','Maddi itkiyə baxmayaraq o, mənəvi qələbə qazanır.',array['Maddi itkiyə baxmayaraq mənəvi qələbə qazanır','Mənəvi itkiyə baxmayaraq maddi qələbə qazanır','Hər iki cəhətdən uduzmuş sayılır','Hər iki cəhətdən udmuş sayılır'],1),
('edeb9-dunya#28','edebiyyat','edeb-9-dunya',3,4,'Dünya və Azərbaycan ədəbiyyatı üzrə «əsər - janr» cütlüyü hansı doğrudur?','«Qoca və dəniz» povest, «Heydərbabaya salam» isə poemadır.',array['«Qoca və dəniz» - povest','«Qoca və dəniz» - poema','«Heydərbabaya salam» - povest','«Namərd gülləsi» - povest'],1),
('edeb9-dunya#29','edebiyyat','edeb-9-dunya',3,4,'Heminqueyin qısa cümlələrdən istifadə etməsi mətnə nə verir?','Mətnə gərginlik və təmkinli ifadə gücü verir.',array['Gərginlik və təmkinli ifadə','Nağılvari yumşaqlıq ovqatı','Elmi mətn dəqiqliyi','Rəsmi sənəd ahəngi'],1),
('edeb9-dunya#30','edebiyyat','edeb-9-dunya',3,4,'Əsərdəki «obraz - simvolik məna» cütlüklərindən hansı düzgündür?','Dəniz həyatı və mübarizə meydanını simvolizə edir.',array['Dəniz - həyat və mübarizə','Dəniz - rahatlıq və dinclik','Köpək balıqları - kömək qüvvələri','Marlin - qorxaqlıq nişanı'],1),
('edeb9-dunya#31','edebiyyat','edeb-9-dunya',3,4,'«Qoca və dəniz» ilə «Heydərbabaya salam» arasındakı əsas fərq nədir?','Biri nəsr, digəri isə şeirlə yazılmış əsərdir.',array['«Qoca və dəniz» nəsr, «Heydərbabaya salam» şeirdir','«Qoca və dəniz» şeir, «Heydərbabaya salam» nəsrdir','Hər ikisi nəsr əsəridir','Hər ikisi şeir əsəridir'],1)
),
ins as (
  insert into public.questions
    (ext_key, owner_type, subject_id, level_id, topic_id, kind,
     body, explanation, difficulty, quarter, status)
  select d.ext, 'platform', s.id, tp.level_id, tp.id, 'single',
         d.body, d.why, d.diff, d.rub, 'published'
    from d
    join public.subjects s on s.slug = d.fenn
    join public.topics   tp on tp.subject_id = s.id and tp.slug = d.topic
  on conflict (ext_key) do update
    set body = excluded.body, explanation = excluded.explanation,
        difficulty = excluded.difficulty, quarter = excluded.quarter,
        topic_id = excluded.topic_id, level_id = excluded.level_id,
        subject_id = excluded.subject_id, status = 'published'
  returning id, ext_key
)
insert into public.question_options (question_id, ord, body, is_correct)
select ins.id, o.ord, o.txt, o.ord = d.correct
  from ins
  join d on d.ext = ins.ext_key,
  lateral unnest(d.opts) with ordinality as o(txt, ord);

do $$
declare n int; k int;
begin
  select count(*) into n from public.questions
   where owner_type = 'platform' and ext_key like 'edeb9-%';
  if n <> 248 then
    raise exception 'Edebiyyat 9 suallari: 248 gozlenilirdi, % tapildi', n;
  end if;
  select count(*) into k from public.questions q
   where q.ext_key like 'edeb9-%'
     and ((select count(*) from public.question_options o
            where o.question_id = q.id) <> 4
       or (select count(*) from public.question_options o
            where o.question_id = q.id and o.is_correct) <> 1);
  if k > 0 then
    raise exception '% sualda variant qurulusu sehvdir', k;
  end if;
  select count(distinct topic_id) into k from public.questions
   where ext_key like 'edeb9-%';
  if k <> 8 then
    raise exception 'movzu sayi 8 deyil: %', k;
  end if;
  --  Her movzuda en azi 12 cetin sual olmalidir ki, muellim BIR
  --  movzudan 10 sualliq cetin test yiga bilsin
  select count(*) into k from (
    select q.topic_id from public.questions q
     where q.ext_key like 'edeb9-%' and q.difficulty = 3
     group by q.topic_id having count(*) < 12) z;
  if k > 0 then
    raise exception '% movzuda 12-den az cetin sual var', k;
  end if;
  raise notice 'Edebiyyat 9 banki: % sual, 8 movzu (her birinde 12 cetin).', n;
end $$;
