-- =====================================================================
--  69_bank_tarix_umumi10.sql : UMUMI TARIX 10 BANKI
--
--  BU FAYL ELLE YAZILMIR - tools/tarix_umumi10.py yaradir:
--      python3 tools/tarix_umumi10.py
--
--  6 movzu x 31 sual = 186.  Her movzuda 4 asan + 15 orta + 12 cetin.
--  ext_key: utarix10-...
--  ON SERT: 68_movzular_umumi_tarix10.sql islenmis olmalidir.
--  SONRA:   05_grants.sql yeniden islet.
-- =====================================================================

do $$
begin
  if not exists (select 1 from public.topics t join public.subjects s
      on s.id = t.subject_id
     where s.slug = 'umumi-tarix' and t.slug in
           ('utarix-10-qedim-serq', 'utarix-10-antik', 'utarix-10-medeniyyet')
     having count(*) = 3) then
    raise exception 'ONCE 68_movzular_umumi_tarix10.sql isledilmelidir.';
  end if;
end $$;

delete from public.question_options o
 using public.questions q
 where o.question_id = q.id
   and q.owner_type = 'platform'
   and q.ext_key like 'utarix10-%';

with d(ext, fenn, topic, diff, rub, body, why, opts, correct) as (values
('utarix10-qedim-serq#1','umumi-tarix','utarix-10-qedim-serq',1,1,'Böyük Hun dövlətinin ən məşhur xaqanı kim olmuşdur?','Böyük Hun dövlətinin ən məşhur xaqanı Mete olmuşdur.',array['Mete xaqan','Sarqon','Aşoka','Ramzes II'],1),
('utarix10-qedim-serq#2','umumi-tarix','utarix-10-qedim-serq',1,1,'Qədim Misirdə dövlət başçısı hansı adla tanınırdı?','Qədim Misirdə dövlət başçısı firon adlanırdı.',array['Firon','Satrap','Konsul','Xaqan'],1),
('utarix10-qedim-serq#3','umumi-tarix','utarix-10-qedim-serq',1,1,'Hammurapi qanunları hansı dövlətdə tərtib olunmuşdur?','Hammurapi qanunları Babil dövlətində tərtib olunmuşdur.',array['Babildə','Misirdə','Çində','Makedoniyada'],1),
('utarix10-qedim-serq#4','umumi-tarix','utarix-10-qedim-serq',1,1,'Qədim Hindistanda yaranan dünya dini hansıdır?','Qədim Hindistanda buddizm dini yaranmışdır.',array['Buddizm','Xristianlıq','İslam','Sinto'],1),
('utarix10-qedim-serq#5','umumi-tarix','utarix-10-qedim-serq',2,1,'Mete xaqan Böyük Hun dövlətində hakimiyyətə hansı ildə gəlmişdir?','Mete xaqan e.ə. 209-cu ildə hakimiyyətə gəlmişdir.',array['E.ə. 209-cu ildə','E.ə. 330-cu ildə','E.ə. 27-ci ildə','Eramızın 476-cı ilində'],1),
('utarix10-qedim-serq#6','umumi-tarix','utarix-10-qedim-serq',2,1,'Mete xaqanın ordunu bölüşdürdüyü hərbi quruluş necə adlanır?','Mete ordunu onluq sistemlə - on, yüz, min və tümən hissələrinə bölmüşdü.',array['Onluq sistem','Satraplıq sistemi','Timar sistemi','Kasta sistemi'],1),
('utarix10-qedim-serq#7','umumi-tarix','utarix-10-qedim-serq',2,1,'Çin torpaqlarını vahid imperiyada birləşdirən hökmdar kimdir?','Çin torpaqlarını Sin Şi Huandi vahid imperiyada birləşdirmişdir.',array['Sin Şi Huandi','Mete xaqan','Dara I','Sarqon'],1),
('utarix10-qedim-serq#8','umumi-tarix','utarix-10-qedim-serq',2,1,'Əhəməni imperiyasında inzibati vahidlər hansı adla tanınırdı?','Əhəməni imperiyası satraplıq adlanan inzibati vahidlərə bölünmüşdü.',array['Satraplıq','Polis','Knyazlıq','Vilayət şurası'],1),
('utarix10-qedim-serq#9','umumi-tarix','utarix-10-qedim-serq',2,1,'Əhəməni imperiyasına son qoyan sərkərdə kimdir?','Əhəməni imperiyasına Makedoniyalı İskəndərin yürüşü son qoymuşdur.',array['Makedoniyalı İskəndər','Hannibal','Mete xaqan','Yuli Sezar'],1),
('utarix10-qedim-serq#10','umumi-tarix','utarix-10-qedim-serq',2,1,'Qədim İranda yayılmış zərdüştiliyin müqəddəs kitabı hansıdır?','Zərdüştiliyin müqəddəs kitabı «Avesta»dır.',array['«Avesta»','«Talmud»','«İliada»','«Ramayana»'],1),
('utarix10-qedim-serq#11','umumi-tarix','utarix-10-qedim-serq',2,1,'Hindistanda Maurya dövlətinin ən tanınmış hökmdarı kimdir?','Maurya dövlətinin ən tanınmış hökmdarı Aşoka olmuşdur.',array['Aşoka','Kir II','Navuxodonosor','Tutmos III'],1),
('utarix10-qedim-serq#12','umumi-tarix','utarix-10-qedim-serq',2,1,'Aşoka hansı dini dövlət səviyyəsində himayə edirdi?','Aşoka buddizmi dövlət səviyyəsində himayə edirdi.',array['Buddizmi','Zərdüştiliyi','Xristianlığı','Konfutsiçiliyi'],1),
('utarix10-qedim-serq#13','umumi-tarix','utarix-10-qedim-serq',2,1,'Qədeş döyüşü hansı iki dövlət arasında baş vermişdir?','Qədeş döyüşü Misir ilə Het dövləti arasında baş vermişdir.',array['Misir və Het dövləti','Babil və Assuriya','Çin və Hindistan','Makedoniya və Karfagen'],1),
('utarix10-qedim-serq#14','umumi-tarix','utarix-10-qedim-serq',2,1,'Mesopotamiyada Akkad dövlətinin əsasını kim qoymuşdur?','Akkad dövlətinin əsasını Sarqon qoymuşdur.',array['Sarqon','Hammurapi','Aşoka','Mete xaqan'],1),
('utarix10-qedim-serq#15','umumi-tarix','utarix-10-qedim-serq',2,1,'Yeni Babil dövlətinin ən məşhur hökmdarı kimdir?','Yeni Babil dövlətinin ən məşhur hökmdarı II Navuxodonosordur.',array['II Navuxodonosor','Sin Şi Huandi','Ramzes II','Kir II'],1),
('utarix10-qedim-serq#16','umumi-tarix','utarix-10-qedim-serq',2,1,'Assuriya dövləti Mesopotamiyanın hansı hissəsində yerləşirdi?','Assuriya dövləti Mesopotamiyanın şimal hissəsində yerləşirdi.',array['Şimal hissəsində','Cənub sahillərində','Şərq dağlarında','Qərb səhralarında'],1),
('utarix10-qedim-serq#17','umumi-tarix','utarix-10-qedim-serq',2,1,'Neolit inqilabı dedikdə nə başa düşülür?','Neolit inqilabı yığıcılıq və ovçuluqdan əkinçilik və maldarlığa keçidi bildirir.',array['Əkinçilik və maldarlığa keçid','Dəmir alətlərin kəşfi','Şəhər dövlətlərinin süqutu','Yazının unudulması'],1),
('utarix10-qedim-serq#18','umumi-tarix','utarix-10-qedim-serq',2,1,'İnsanların əmək alətləri üçün istifadə etdiyi ilk metal hansıdır?','İnsanlar ilk dəfə misdən istifadə etməyə başlamışlar.',array['Mis','Dəmir','Alüminium','Nikel'],1),
('utarix10-qedim-serq#19','umumi-tarix','utarix-10-qedim-serq',2,1,'Kuşan imperiyası əsasən hansı ərazidə mövcud olmuşdur?','Kuşan imperiyası Şimali Hindistan və Orta Asiya ərazisində mövcud olmuşdur.',array['Şimali Hindistan və Orta Asiyada','Şimali Afrikada','Balkan yarımadasında','Britaniya adalarında'],1),
('utarix10-qedim-serq#20','umumi-tarix','utarix-10-qedim-serq',3,1,'Aşağıdakı hadisələri xronoloji ardıcıllıqla düzün: 1. Mete xaqanın hakimiyyətə gəlməsi 2. Çinin vahid imperiyada birləşdirilməsi 3. Əhəməni imperiyasının süqutu','Əhəməni imperiyası e.ə. 330-cu ildə, Çinin birləşdirilməsi e.ə. 221-ci ildə, Metenin hakimiyyətə gəlməsi isə e.ə. 209-cu ildə olmuşdur.',array['3 - 2 - 1','1 - 2 - 3','2 - 3 - 1','3 - 1 - 2'],1),
('utarix10-qedim-serq#21','umumi-tarix','utarix-10-qedim-serq',3,1,'Qədim Şərq üçün «hökmdar - dövlət» uyğunluğu hansı sırada düzgün verilmişdir?','Mete Böyük Hun dövlətinin, Aşoka Mauryanın, Sarqon Akkadın, Dara I isə Əhəmənilərin hökmdarıdır.',array['Mete - Böyük Hun dövləti','Aşoka - Əhəməni imperiyası','Sarqon - Maurya dövləti','Dara I - Akkad dövləti'],1),
('utarix10-qedim-serq#22','umumi-tarix','utarix-10-qedim-serq',3,1,'Qədim Şərq sivilizasiyaları haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Hammurapi qanunları Misirdə deyil, Babil dövlətində tərtib olunmuşdur.',array['Hammurapi qanunları Misirdə tərtib olunmuşdur','Əhəməni imperiyası satraplıqlara bölünmüşdü','Aşoka buddizmi himayə edirdi','Mete xaqan orduda onluq sistem tətbiq etmişdi'],1),
('utarix10-qedim-serq#23','umumi-tarix','utarix-10-qedim-serq',3,1,'Böyük Çin səddinin şimal sərhədi boyunca ucaldılmasının başlıca səbəbi nə idi?','Sədd şimaldan gələn hun süvari dəstələrinin basqınlarının qarşısını almaq üçün ucaldılmışdı.',array['Hun basqınlarının qarşısını almaq','Karvan yollarını qısaltmaq','Şəhərləri daşqından qorumaq','Məbədləri bir yerə toplamaq'],1),
('utarix10-qedim-serq#24','umumi-tarix','utarix-10-qedim-serq',3,1,'Mete xaqanın hərbi islahatının mahiyyətini düzgün göstərən fikir hansıdır?','O, ordunu onluq bölmələrə ayıraraq hər bölməni birbaşa mərkəzi hakimiyyətə tabe etmişdi.',array['Ordu onluq bölmələrə ayrılıb mərkəzə tabe edilmişdi','Ordu tayfa başçılarının sərəncamına verilmişdi','Süvari qoşundan tamam imtina olunmuşdu','Hərbi xidmət yalnız əcnəbilərə həvalə edilmişdi'],1),
('utarix10-qedim-serq#25','umumi-tarix','utarix-10-qedim-serq',3,1,'Əhəməni satraplıq sistemi ilə Hun onluq sisteminin başlıca fərqi nədir?','Satraplıq ərazi üzrə mülki-inzibati bölgü, onluq sistem isə ordunun say üzrə hərbi quruluşudur.',array['Biri ərazi-inzibati, digəri hərbi bölgüdür','Biri dini, digəri ticarət təşkilatıdır','Biri məhkəmə, digəri məktəb sistemidir','Hər ikisi yalnız vergi toplamaq üçün idi'],1),
('utarix10-qedim-serq#26','umumi-tarix','utarix-10-qedim-serq',3,1,'Hammurapi qanunlarının dünya tarixi üçün əhəmiyyətini düzgün göstərən fikir hansıdır?','Bu qanunlar yazılı hüquq normalarının bizə gəlib çatmış ən dolğun erkən nümunəsidir.',array['Yazılı hüquq normalarının erkən dolğun nümunəsidir','İlk əlifba sistemini ortaya qoymuşdur','Buddizmin əsas müddəalarını toplamışdır','Satraplıq bölgüsünü müəyyən etmişdir'],1),
('utarix10-qedim-serq#27','umumi-tarix','utarix-10-qedim-serq',3,1,'Neolit inqilabının cəmiyyət quruluşuna təsirini düzgün göstərən fikir hansıdır?','Oturaq həyata keçid artıq məhsul yaratdı, bu isə əmlak bərabərsizliyinə yol açdı.',array['Oturaq həyat, artıq məhsul və əmlak bərabərsizliyi yarandı','Əhali tamam köçəri həyata qayıtdı','İcma daxilində əmək bölgüsü aradan qalxdı','Metal alətlərdən istifadə dayandırıldı'],1),
('utarix10-qedim-serq#28','umumi-tarix','utarix-10-qedim-serq',3,1,'Qədim Şərq dövlətləri haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Akkad dövlətinin banisi Navuxodonosor deyil, Sarqondur; Navuxodonosor Yeni Babil hökmdarıdır.',array['Akkad dövlətinin banisi Navuxodonosordur','Assuriya Mesopotamiyanın şimalında yerləşirdi','Kuşan imperiyası Orta Asiyanı da əhatə edirdi','Qədeş döyüşü Misirlə Het dövləti arasında olmuşdur'],1),
('utarix10-qedim-serq#29','umumi-tarix','utarix-10-qedim-serq',3,1,'Böyük Hun dövlətinin şimal və cənub hissələrinə parçalanmasının nəticəsi nə oldu?','Parçalanmadan sonra dövlət zəiflədi, cənub hunları isə Çin təsiri altına düşdü.',array['Dövlət zəiflədi, hunların bir hissəsi Çindən asılı oldu','Dövlətin ərazisi daha da genişləndi','Çin imperiyası hunlara xərac verməyə başladı','Hunlar Hindistanı bütövlükdə ələ keçirdilər'],1),
('utarix10-qedim-serq#30','umumi-tarix','utarix-10-qedim-serq',3,1,'Qədim Şərqdə İpək yolunun açılmasının uzunmüddətli nəticəsini düzgün göstərən fikir hansıdır?','Yol yalnız mal deyil, texnologiya, din və yazı sistemlərinin də Şərqlə Qərb arasında yayılmasını təmin etdi.',array['Mallarla yanaşı bilik və dinlər də yayıldı','Ölkələr arasında əlaqə tamam kəsildi','Yalnız hərbi yürüşlər üçün istifadə olundu','Dəniz ticarətini əvəz edə bilmədi'],1),
('utarix10-qedim-serq#31','umumi-tarix','utarix-10-qedim-serq',3,1,'Aşokanın buddizmi himayə etməsinin dövlət üçün əhəmiyyəti nə idi?','Ortaq din geniş və çoxdilli imperiyada birləşdirici amilə çevrildi.',array['Çoxdilli imperiyada birləşdirici amil oldu','Ordunun sayını iki dəfə artırdı','Kasta bölgüsünü tam ləğv etdi','Ticarət yollarını bağladı'],1),
('utarix10-antik#1','umumi-tarix','utarix-10-antik',1,1,'Qədim dünyada demokratik idarəçilik hansı yunan şəhərində formalaşmışdır?','Demokratik idarəçilik Afinada formalaşmışdır.',array['Afinada','Spartada','Karfagendə','Babildə'],1),
('utarix10-antik#2','umumi-tarix','utarix-10-antik',1,1,'Makedoniyalı İskəndərin atası kim olmuşdur?','Makedoniyalı İskəndərin atası II Filipp olmuşdur.',array['II Filipp','Perikl','Solon','Hannibal'],1),
('utarix10-antik#3','umumi-tarix','utarix-10-antik',1,1,'Roma imperiyasının ilk imperatoru kim sayılır?','Roma imperiyasının ilk imperatoru Avqust sayılır.',array['Avqust','Yuli Sezar','Konstantin','Dara III'],1),
('utarix10-antik#4','umumi-tarix','utarix-10-antik',1,1,'Roma respublikasında ali məşvərət orqanı hansı idi?','Roma respublikasında ali məşvərət orqanı senat idi.',array['Senat','Xalq yığıncağı','Areopaq','Parlament'],1),
('utarix10-antik#5','umumi-tarix','utarix-10-antik',2,1,'Yunan sivilizasiyasının ən erkən mərkəzləri hansılardır?','Yunan sivilizasiyasının ən erkən mərkəzləri Krit və Miken olmuşdur.',array['Krit və Miken','Karfagen və Numidiya','Babil və Assuriya','Sparta və Korinf'],1),
('utarix10-antik#6','umumi-tarix','utarix-10-antik',2,1,'Afinada ilk geniş ictimai islahatları kim həyata keçirmişdir?','Afinada ilk geniş islahatları Solon həyata keçirmişdir.',array['Solon','Perikl','II Filipp','Avqust'],1),
('utarix10-antik#7','umumi-tarix','utarix-10-antik',2,1,'Afina demokratiyasının çiçəklənmə dövrü kimin adı ilə bağlıdır?','Afina demokratiyasının çiçəklənməsi Periklin adı ilə bağlıdır.',array['Perikl','Solon','Hannibal','Konstantin'],1),
('utarix10-antik#8','umumi-tarix','utarix-10-antik',2,1,'II Filipp yunan polislərini hansı döyüşdə məğlub etmişdir?','II Filipp yunan polislərini Xeroneya döyüşündə məğlub etmişdir.',array['Xeroneya döyüşündə','Kann döyüşündə','Qavqamela döyüşündə','Marafon döyüşündə'],1),
('utarix10-antik#9','umumi-tarix','utarix-10-antik',2,1,'Makedoniyalı İskəndər Əhəmənilər üzərində həlledici qələbəni harada qazanmışdır?','Həlledici qələbə Qavqamela döyüşündə qazanılmışdır.',array['Qavqamela döyüşündə','Xeroneya döyüşündə','Fermopil keçidində','Nesbi döyüşündə'],1),
('utarix10-antik#10','umumi-tarix','utarix-10-antik',2,1,'İskəndərin yürüşlərindən sonra formalaşan mədəniyyət necə adlanır?','Yunan və Şərq mədəniyyətlərinin qovuşmasından yaranan dövr ellinizm adlanır.',array['Ellinizm','Sxolastika','İntibah','Romanizm'],1),
('utarix10-antik#11','umumi-tarix','utarix-10-antik',2,1,'Puni müharibələri Roma ilə hansı dövlət arasında gedirdi?','Puni müharibələri Roma ilə Karfagen arasında gedirdi.',array['Karfagenlə','Misirlə','Makedoniya ilə','Babillə'],1),
('utarix10-antik#12','umumi-tarix','utarix-10-antik',2,1,'Kann döyüşündə Roma ordusunu kim məğlub etmişdir?','Kann döyüşündə Roma ordusunu Hannibal məğlub etmişdir.',array['Hannibal','II Filipp','Perikl','Sarqon'],1),
('utarix10-antik#13','umumi-tarix','utarix-10-antik',2,1,'Roma respublikasının süqutu hansı sərkərdənin adı ilə bağlıdır?','Respublikanın süqutu Yuli Sezarın adı ilə bağlıdır.',array['Yuli Sezar','Solon','Aşoka','Hannibal'],1),
('utarix10-antik#14','umumi-tarix','utarix-10-antik',2,1,'Milan ediktı ilə Roma imperiyasında nə tanındı?','Milan ediktı ilə xristianlığın sərbəst yayılmasına icazə verildi.',array['Xristianlığın sərbəst yayılması','Qulların azad edilməsi','Senatın ləğvi','Yeni vergi sisteminin qurulması'],1),
('utarix10-antik#15','umumi-tarix','utarix-10-antik',2,1,'Roma imperiyası hansı ildə Qərb və Şərq hissələrinə bölünmüşdür?','Roma imperiyası 395-ci ildə iki hissəyə bölünmüşdür.',array['395-ci ildə','313-cü ildə','476-cı ildə','1453-cü ildə'],1),
('utarix10-antik#16','umumi-tarix','utarix-10-antik',2,1,'Qərbi Roma imperiyası hansı ildə süqut etmişdir?','Qərbi Roma imperiyası 476-cı ildə süqut etmişdir.',array['476-cı ildə','395-ci ildə','800-cü ildə','1066-cı ildə'],1),
('utarix10-antik#17','umumi-tarix','utarix-10-antik',2,1,'Sparta idarəçiliyinin səciyyəvi cəhəti nə idi?','Spartada eyni vaxtda iki çar hökm sürür, idarəçilik hərbi aristokratiyanın əlində olurdu.',array['İki çarlı hərbi aristokratiya','Seçkili prezident idarəçiliyi','Kahinlərin tam hakimiyyəti','Ticarət gildiyalarının hakimiyyəti'],1),
('utarix10-antik#18','umumi-tarix','utarix-10-antik',2,1,'Roma respublikasında ali icra vəzifəsi necə adlanırdı?','Roma respublikasında ali icra vəzifəsi konsul adlanırdı.',array['Konsul','Satrap','Arxont','Xaqan'],1),
('utarix10-antik#19','umumi-tarix','utarix-10-antik',2,1,'Roma hüququnun sonrakı dövrlər üçün əhəmiyyəti nədir?','Roma hüququ Avropa hüquq sistemlərinin əsasını təşkil etmişdir.',array['Avropa hüquq sistemlərinin əsası olmuşdur','Yazının ilk nümunəsini vermişdir','Xristianlığı qadağan etmişdir','Ticarəti tamam dayandırmışdır'],1),
('utarix10-antik#20','umumi-tarix','utarix-10-antik',3,1,'Aşağıdakı hadisələri xronoloji ardıcıllıqla düzün: 1. Qərbi Roma imperiyasının süqutu 2. Xeroneya döyüşü 3. Roma imperiyasının qurulması','Xeroneya döyüşü e.ə. 338, Roma imperiyasının qurulması e.ə. 27, Qərbi Romanın süqutu isə 476-cı ilə aiddir.',array['2 - 3 - 1','1 - 2 - 3','3 - 2 - 1','2 - 1 - 3'],1),
('utarix10-antik#21','umumi-tarix','utarix-10-antik',3,1,'Antik dövr üçün «döyüş - qarşı-qarşıya duran tərəflər» uyğunluğu hansı sırada düzgündür?','Qavqamelada İskəndər Dara III ilə, Xeroneyada Makedoniya yunan polisləri ilə, Kannda isə Roma Karfagenlə üzləşmişdi.',array['Qavqamela - İskəndər və Dara III','Xeroneya - Roma və Karfagen','Kann - Afina və Sparta','Marafon - Makedoniya və Hindistan'],1),
('utarix10-antik#22','umumi-tarix','utarix-10-antik',3,1,'Antik dünya haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Roma imperiyasının ilk imperatoru Hannibal deyil, Avqustdur; Hannibal Karfagen sərkərdəsi olmuşdur.',array['Roma imperiyasının ilk imperatoru Hannibal olmuşdur','Afina demokratiyası Periklin dövründə çiçəklənmişdir','Ellinizm yunan və Şərq mədəniyyətlərinin qovuşmasıdır','Qərbi Roma 476-cı ildə süqut etmişdir'],1),
('utarix10-antik#23','umumi-tarix','utarix-10-antik',3,1,'Puni müharibələrinin Roma üçün başlıca nəticəsi nə oldu?','Karfagenin məğlubiyyətindən sonra Roma Aralıq dənizi hövzəsində hakim dövlətə çevrildi.',array['Aralıq dənizi hövzəsində hakim dövlətə çevrildi','Öz dəniz üstünlüyünü itirdi','Şərqə bütün yürüşlərdən əl çəkdi','Karfagenlə ittifaq müqaviləsi bağladı'],1),
('utarix10-antik#24','umumi-tarix','utarix-10-antik',3,1,'Afina ilə Spartanın idarə formalarını düzgün müqayisə edən fikir hansıdır?','Afinada qərarları vətəndaşların xalq yığıncağı verirdi, Spartada isə hakimiyyət hərbi aristokratiyanın əlində idi.',array['Afinada xalq yığıncağı, Spartada hərbi aristokratiya həlledici idi','Hər ikisində hakimiyyət kahinlərə məxsus idi','Afinada iki çar, Spartada bir arxont hakim idi','Hər ikisində hökmdar irsi qaydada dəyişirdi'],1),
('utarix10-antik#25','umumi-tarix','utarix-10-antik',3,1,'Aşağıdakı hadisələrdən hansı digərlərindən əvvəl baş vermişdir?','Xeroneya döyüşü e.ə. 338, Qavqamela e.ə. 331, İskəndərin ölümü e.ə. 323, Roma imperiyasının qurulması isə e.ə. 27-ci ilə aiddir.',array['Xeroneya döyüşü','Qavqamela döyüşü','Makedoniyalı İskəndərin ölümü','Roma imperiyasının qurulması'],1),
('utarix10-antik#26','umumi-tarix','utarix-10-antik',3,1,'Antik dövr üçün «şəxs - fəaliyyət sahəsi» uyğunluğu hansı sırada düzgündür?','Solon Afinada islahat keçirmiş, Hannibal Karfagen ordusuna başçılıq etmiş, Avqust isə imperiyanı qurmuşdur.',array['Solon - Afinada islahatlar','Hannibal - Afinada islahatlar','Avqust - Karfagen ordusunun başçısı','Perikl - Makedoniya ordusunun başçısı'],1),
('utarix10-antik#27','umumi-tarix','utarix-10-antik',3,1,'Ellinizm dövrünün mahiyyətini düzgün göstərən fikir hansıdır?','Ellinizm yunan mədəniyyəti ilə Şərq ənənələrinin qarşılıqlı təsirdə qovuşduğu dövrdür.',array['Yunan və Şərq mədəniyyətlərinin qovuşması dövrüdür','Yunan mədəniyyətinin tam unudulması dövrüdür','Şərq dillərinin Avropada qadağan olunması dövrüdür','Roma hüququnun formalaşdığı dövrdür'],1),
('utarix10-antik#28','umumi-tarix','utarix-10-antik',3,1,'Antik dövr haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','İskəndər Əhəmənilər üzərində həlledici qələbəni Xeroneyada deyil, Qavqamelada qazanmışdır; Xeroneyada yunan polisləri məğlub olmuşdu.',array['İskəndər Əhəmənilər üzərində qələbəni Xeroneyada qazanmışdır','Milan ediktı xristianlığa sərbəstlik verdi','Roma imperiyası 395-ci ildə ikiyə bölündü','Puni müharibələri Roma ilə Karfagen arasında getmişdir'],1),
('utarix10-antik#29','umumi-tarix','utarix-10-antik',3,1,'Roma imperiyasının 395-ci ildə bölünməsinin uzunmüddətli nəticəsi nə oldu?','Qərb hissəsi tezliklə süqut etdi, Şərq hissəsi isə Bizans adı ilə min ilə yaxın davam etdi.',array['Şərq hissəsi Bizans kimi uzun müddət yaşadı','Hər iki hissə eyni vaxtda süqut etdi','İmperiya bir əsr sonra yenidən birləşdi','Qərb hissəsi Bizansı özünə tabe etdi'],1),
('utarix10-antik#30','umumi-tarix','utarix-10-antik',3,1,'Milan ediktının qəbulunun Roma dövləti üçün əhəmiyyəti nə idi?','Təqib olunan xristianlıq qanuni dinə çevrildi və dövlətlə kilsə arasında yaxınlaşma başladı.',array['Xristianlıq qanuniləşdi, dövlətlə kilsə yaxınlaşdı','Bütün qədim məbədlər dağıdıldı','Senatın səlahiyyətləri genişləndirildi','İmperiya paytaxtı Karfagenə köçürüldü'],1),
('utarix10-antik#31','umumi-tarix','utarix-10-antik',3,1,'Romada respublikadan imperiyaya keçidin başlıca səbəbini düzgün göstərən fikir hansıdır?','Genişlənmiş ərazini və çoxsaylı ordunu köhnə respublika orqanları idarə edə bilmirdi.',array['Genişlənmiş dövləti respublika orqanları idarə edə bilmirdi','Senat özünü könüllü buraxmışdı','Xarici işğal ölkəni bütövlükdə tutmuşdu','Əhali imperator hakimiyyətini səsvermə ilə seçmişdi'],1),
('utarix10-erken-orta#1','umumi-tarix','utarix-10-erken-orta',1,2,'Avropa Hun dövlətinin ən məşhur hökmdarı kim olmuşdur?','Avropa Hun dövlətinin ən məşhur hökmdarı Atilla olmuşdur.',array['Atilla','Bumın xaqan','Xlodviq','Yustinian'],1),
('utarix10-erken-orta#2','umumi-tarix','utarix-10-erken-orta',1,2,'Göytürk xaqanlığının əsasını kim qoymuşdur?','Göytürk xaqanlığının əsasını Bumın xaqan qoymuşdur.',array['Bumın xaqan','Batı xan','Sultan Mahmud','Kiril'],1),
('utarix10-erken-orta#3','umumi-tarix','utarix-10-erken-orta',1,2,'Bizans imperiyası hansı şəhərdən idarə olunurdu?','Bizans imperiyasının paytaxtı Konstantinopol idi.',array['Konstantinopol','Dəməşq','Bağdad','Səmərqənd'],1),
('utarix10-erken-orta#4','umumi-tarix','utarix-10-erken-orta',1,2,'Frank dövlətini imperiyaya çevirən hökmdar kimdir?','Frank dövləti Karl Böyükün dövründə imperiyaya çevrilmişdir.',array['Karl Böyük','Atilla','Tonyukuk','I Xosrov'],1),
('utarix10-erken-orta#5','umumi-tarix','utarix-10-erken-orta',2,2,'Göytürk xaqanlığı hansı ildə qurulmuşdur?','Göytürk xaqanlığı 552-ci ildə qurulmuşdur.',array['552-ci ildə','744-cü ildə','800-cü ildə','1055-ci ildə'],1),
('utarix10-erken-orta#6','umumi-tarix','utarix-10-erken-orta',2,2,'Göytürklərdən qalan daş üzərindəki yazılı abidələr necə adlanır?','Bu abidələr Orxon-Yenisey abidələri adlanır.',array['Orxon-Yenisey abidələri','Rozetta daşı','Behistun kitabəsi','Kann lövhələri'],1),
('utarix10-erken-orta#7','umumi-tarix','utarix-10-erken-orta',2,2,'Göytürk abidələrində müdrik dövlət xadimi kimi anılan şəxs kimdir?','Göytürk abidələrində müdrik dövlət xadimi kimi Tonyukuk anılır.',array['Tonyukuk','Nizamülmülk','Mefodi','Sarqon'],1),
('utarix10-erken-orta#8','umumi-tarix','utarix-10-erken-orta',2,2,'Uyğur xaqanlığı hansı ildə qurulmuşdur?','Uyğur xaqanlığı 744-cü ildə qurulmuşdur.',array['744-cü ildə','552-ci ildə','651-ci ildə','843-cü ildə'],1),
('utarix10-erken-orta#9','umumi-tarix','utarix-10-erken-orta',2,2,'Xəzər xaqanlığı əsasən hansı ərazidə mövcud olmuşdur?','Xəzər xaqanlığı Şimali Qafqaz və Volqaboyu ərazilərində mövcud olmuşdur.',array['Şimali Qafqaz və Volqaboyunda','Britaniya adalarında','Şimali Afrikada','Yapon adalarında'],1),
('utarix10-erken-orta#10','umumi-tarix','utarix-10-erken-orta',2,2,'Sasani dövləti hansı ildə süqut etmişdir?','Sasani dövləti 651-ci ildə süqut etmişdir.',array['651-ci ildə','476-cı ildə','762-ci ildə','843-cü ildə'],1),
('utarix10-erken-orta#11','umumi-tarix','utarix-10-erken-orta',2,2,'Sasani hökmdarı I Xosrov nə ilə tarixdə qalmışdır?','I Xosrov inzibati və vergi islahatları ilə tarixdə qalmışdır.',array['İnzibati və vergi islahatları ilə','Amerikanın kəşfi ilə','Xaçlı yürüşləri ilə','Mətbəənin ixtirası ilə'],1),
('utarix10-erken-orta#12','umumi-tarix','utarix-10-erken-orta',2,2,'Əməvilər xilafətinin paytaxtı hansı şəhər olmuşdur?','Əməvilər xilafətinin paytaxtı Dəməşq olmuşdur.',array['Dəməşq','Bağdad','Qahirə','Buxara'],1),
('utarix10-erken-orta#13','umumi-tarix','utarix-10-erken-orta',2,2,'Abbasilər xilafətinin paytaxtı kimi salınan şəhər hansıdır?','Abbasilər xilafətinin paytaxtı kimi Bağdad şəhəri salınmışdır.',array['Bağdad','Dəməşq','Konstantinopol','Səmərqənd'],1),
('utarix10-erken-orta#14','umumi-tarix','utarix-10-erken-orta',2,2,'Bizans imperatoru Yustinianın tikdirdiyi ən məşhur məbəd hansıdır?','Yustinianın tikdirdiyi ən məşhur məbəd Ayasofyadır.',array['Ayasofya','Notr-Dam','Parfenon','Kolizey'],1),
('utarix10-erken-orta#15','umumi-tarix','utarix-10-erken-orta',2,2,'Yustinianın göstərişi ilə hazırlanan hüquq toplusu necə adlanır?','Bu toplu mülki hüquq məcəlləsi kimi tanınır.',array['Mülki hüquq məcəlləsi','Böyük azadlıq fərmanı','Hammurapi qanunları','Siyasətnamə'],1),
('utarix10-erken-orta#16','umumi-tarix','utarix-10-erken-orta',2,2,'Slavyan xalqları üçün əlifba yaradan qardaşlar kimlərdir?','Slavyan əlifbasını Kiril və Mefodi qardaşları yaratmışdır.',array['Kiril və Mefodi','Bumın və İstəmi','Osman və Orxan','Kir və Dara'],1),
('utarix10-erken-orta#17','umumi-tarix','utarix-10-erken-orta',2,2,'Tarixdə ilk müsəlman türk dövləti hansı sayılır?','Tarixdə ilk müsəlman türk dövləti Qaraxanlılar sayılır.',array['Qaraxanlılar','Göytürklər','Uyğurlar','Xəzərlər'],1),
('utarix10-erken-orta#18','umumi-tarix','utarix-10-erken-orta',2,2,'Qəznəli dövlətinin ən güclü hökmdarı kim olmuşdur?','Qəznəli dövlətinin ən güclü hökmdarı Sultan Mahmud olmuşdur.',array['Sultan Mahmud','Toğrul bəy','Batı xan','Karl Böyük'],1),
('utarix10-erken-orta#19','umumi-tarix','utarix-10-erken-orta',2,2,'Kataloniya düzündəki döyüş hansı hökmdarın yürüşü ilə bağlıdır?','Kataloniya düzündəki döyüş Atillanın Qərbə yürüşü ilə bağlıdır.',array['Atillanın','Yustinianın','Xlodviqin','Sultan Mahmudun'],1),
('utarix10-erken-orta#20','umumi-tarix','utarix-10-erken-orta',3,2,'Aşağıdakı hadisələri xronoloji ardıcıllıqla düzün: 1. Abbasilər xilafətinin qurulması 2. Göytürk xaqanlığının yaranması 3. Karl Böyükün imperator elan olunması','Göytürk xaqanlığı 552-ci ildə, Abbasilər 750-ci ildə, Karl Böyük isə 800-cü ildə imperator elan olunmuşdur.',array['2 - 1 - 3','1 - 2 - 3','3 - 2 - 1','2 - 3 - 1'],1),
('utarix10-erken-orta#21','umumi-tarix','utarix-10-erken-orta',3,2,'III-XI yüzilliklər üçün «dövlət - paytaxt» uyğunluğu hansı sırada düzgündür?','Bağdad Abbasilərin, Dəməşq Əməvilərin, Konstantinopol isə Bizansın paytaxtı olmuşdur.',array['Abbasilər xilafəti - Bağdad','Əməvilər xilafəti - Bağdad','Bizans imperiyası - Dəməşq','Frank dövləti - Konstantinopol'],1),
('utarix10-erken-orta#22','umumi-tarix','utarix-10-erken-orta',3,2,'III-XI yüzilliklərin tarixi haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Slavyan əlifbasını Bumın xaqan deyil, Kiril və Mefodi qardaşları yaratmışdır.',array['Slavyan əlifbasını Bumın xaqan yaratmışdır','Göytürk xaqanlığı 552-ci ildə qurulmuşdur','Sasani dövləti 651-ci ildə süqut etmişdir','Ayasofya Yustinianın dövründə tikilmişdir'],1),
('utarix10-erken-orta#23','umumi-tarix','utarix-10-erken-orta',3,2,'Xalqların böyük köçünün Qərbi Avropa üçün nəticəsini düzgün göstərən fikir hansıdır?','Köç Qərbi Roma imperiyasının süqutunu tezləşdirdi, onun yerində barbar krallıqları yarandı.',array['Qərbi Roma süqut etdi, yerində yeni krallıqlar yarandı','Roma imperiyası bütövlükdə möhkəmləndi','Avropada şəhər həyatı sürətlə çiçəkləndi','Bizans imperiyası dağıldı'],1),
('utarix10-erken-orta#24','umumi-tarix','utarix-10-erken-orta',3,2,'Göytürk və Uyğur xaqanlıqlarının bir-biri ilə əlaqəsini düzgün göstərən fikir hansıdır?','Uyğur xaqanlığı Göytürk xaqanlığının süqutundan sonra həmin ərazidə qurulmuşdur.',array['Uyğurlar Göytürklərin ərazisində, onlardan sonra dövlət qurdular','Uyğurlar Göytürklərdən əvvəl dövlət qurmuşdular','İki xaqanlıq eyni vaxtda mövcud olmuşdur','Uyğurlar Bizans ərazisində dövlət qurmuşdular'],1),
('utarix10-erken-orta#25','umumi-tarix','utarix-10-erken-orta',3,2,'III-XI yüzilliklərin hansı hadisəsi digərlərindən əvvəl olmuşdur?','Əməvilər 661-ci ildə, Uyğur xaqanlığı 744-cü ildə, Abbasilər 750-ci ildə, Bağdad isə 762-ci ildə salınmışdır.',array['Əməvilərin hakimiyyətə gəlməsi','Uyğur xaqanlığının qurulması','Abbasilərin hakimiyyətə gəlməsi','Bağdad şəhərinin salınması'],1),
('utarix10-erken-orta#26','umumi-tarix','utarix-10-erken-orta',3,2,'III-XI yüzilliklər üçün «hökmdar - gördüyü iş» uyğunluğu hansı sırada düzgündür?','I Xosrov vergi islahatı aparmış, Yustinian hüquq toplusu hazırlatmış, Karl Böyük isə imperator elan olunmuşdur.',array['I Xosrov - vergi islahatı','Yustinian - Bağdadın salınması','Karl Böyük - mülki hüquq məcəlləsi','Sultan Mahmud - slavyan əlifbası'],1),
('utarix10-erken-orta#27','umumi-tarix','utarix-10-erken-orta',3,2,'Orxon-Yenisey abidələrinin tarixi əhəmiyyətini düzgün göstərən fikir hansıdır?','Abidələr həm türk dilinin ən qədim yazılı nümunəsi, həm də dövrün siyasi salnaməsidir.',array['Türk dilinin ən qədim yazısı və dövrün salnaməsidir','Bizans hüququnun əsas mənbəyidir','Ərəb riyaziyyatının ilk kitabıdır','Slavyan əlifbasının ilk nümunəsidir'],1),
('utarix10-erken-orta#28','umumi-tarix','utarix-10-erken-orta',3,2,'Ərəb xilafətində Əməvilərdən Abbasilərə keçidin mahiyyətini düzgün göstərən fikir hansıdır?','Hakimiyyət mərkəzi Suriyadan İraqa keçdi, idarəçilikdə qeyri-ərəb müsəlmanların rolu artdı.',array['Mərkəz İraqa keçdi, qeyri-ərəblərin rolu artdı','Xilafət xristian dövlətinə çevrildi','Xilafətin paytaxtı Konstantinopola köçürüldü','Ərəb dili dövlət işlərindən çıxarıldı'],1),
('utarix10-erken-orta#29','umumi-tarix','utarix-10-erken-orta',3,2,'Erkən orta əsrlərdə Bizansı Qərbi Avropadan fərqləndirən başlıca cəhət nə idi?','Bizansda güclü mərkəzi hakimiyyət, şəhər həyatı və pul təsərrüfatı davam edirdi.',array['Mərkəzi hakimiyyət və şəhər həyatı davam edirdi','Ölkədə yazı və kitab istifadədən çıxmışdı','İmperator hakimiyyəti seçki ilə müəyyən olunurdu','Xristianlıq qadağan edilmişdi'],1),
('utarix10-erken-orta#30','umumi-tarix','utarix-10-erken-orta',3,2,'Erkən orta əsr türk dövlətləri haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','İlk müsəlman türk dövləti Göytürk xaqanlığı deyil, Qaraxanlılar dövlətidir.',array['İlk müsəlman türk dövləti Göytürk xaqanlığıdır','Uyğur xaqanlığı 744-cü ildə qurulmuşdur','Xəzər xaqanlığı Volqaboyunda mövcud olmuşdur','Qəznəlilərin ən güclü hökmdarı Sultan Mahmud idi'],1),
('utarix10-erken-orta#31','umumi-tarix','utarix-10-erken-orta',3,2,'Karl Böyükün 800-cü ildə imperator elan olunmasının siyasi mənası nə idi?','Qərbdə Roma imperiya ənənəsinin bərpasına iddia irəli sürülür, papa ilə ittifaq möhkəmlənirdi.',array['Qərbdə Roma imperiya ənənəsinə iddia irəli sürüldü','Bizans imperiyası ləğv edildi','Frank dövləti xilafətə tabe oldu','Avropada respublika quruluşu bərqərar oldu'],1),
('utarix10-orta-esrler#1','umumi-tarix','utarix-10-orta-esrler',1,3,'Osmanlı dövlətinin əsasını kim qoymuşdur?','Osmanlı dövlətinin əsasını Osman bəy qoymuşdur.',array['Osman bəy','Toğrul bəy','Batı xan','Uluqbəy'],1),
('utarix10-orta-esrler#2','umumi-tarix','utarix-10-orta-esrler',1,3,'Monqol imperiyasının banisi kim olmuşdur?','Monqol imperiyasının banisi Çingiz xan olmuşdur.',array['Çingiz xan','Əmir Teymur','Alp Arslan','Salahəddin Əyyubi'],1),
('utarix10-orta-esrler#3','umumi-tarix','utarix-10-orta-esrler',1,3,'Konstantinopolu 1453-cü ildə hansı Osmanlı sultanı almışdır?','Konstantinopolu Fateh Sultan Mehmet almışdır.',array['Fateh Sultan Mehmet','İldırım Bəyazid','Osman bəy','Məlikşah'],1),
('utarix10-orta-esrler#4','umumi-tarix','utarix-10-orta-esrler',1,3,'Əmir Teymur dövlətinin paytaxtı hansı şəhər idi?','Əmir Teymur dövlətinin paytaxtı Səmərqənd idi.',array['Səmərqənd','Bağdad','Dehli','Kiyev'],1),
('utarix10-orta-esrler#5','umumi-tarix','utarix-10-orta-esrler',2,3,'Böyük Səlcuq dövlətinin əsasını kim qoymuşdur?','Böyük Səlcuq dövlətinin əsasını Toğrul bəy qoymuşdur.',array['Toğrul bəy','Osman bəy','Çingiz xan','Sultan Mahmud'],1),
('utarix10-orta-esrler#6','umumi-tarix','utarix-10-orta-esrler',2,3,'Dandanakan döyüşü hansı iki dövlət arasında baş vermişdir?','Dandanakan döyüşü səlcuqlarla Qəznəlilər arasında baş vermişdir.',array['Səlcuqlarla Qəznəlilər','Osmanlılarla Bizans','Monqollarla Ruslar','Franklarla Ərəblər'],1),
('utarix10-orta-esrler#7','umumi-tarix','utarix-10-orta-esrler',2,3,'1071-ci il Malazgird döyüşündə Bizans ordusunu kim məğlub etmişdir?','Malazgird döyüşündə Bizans ordusunu Alp Arslan məğlub etmişdir.',array['Alp Arslan','Osman bəy','Batı xan','Hannibal'],1),
('utarix10-orta-esrler#8','umumi-tarix','utarix-10-orta-esrler',2,3,'«Siyasətnamə» əsərinin müəllifi kimdir?','«Siyasətnamə» Səlcuq vəziri Nizamülmülkün əsəridir.',array['Nizamülmülk','Uluqbəy','Tonyukuk','Salahəddin Əyyubi'],1),
('utarix10-orta-esrler#9','umumi-tarix','utarix-10-orta-esrler',2,3,'Osmanlı dövləti hansı ildə qurulmuşdur?','Osmanlı dövləti 1299-cu ildə qurulmuşdur.',array['1299-cu ildə','1206-cı ildə','1370-ci ildə','1453-cü ildə'],1),
('utarix10-orta-esrler#10','umumi-tarix','utarix-10-orta-esrler',2,3,'1402-ci il Ankara döyüşü kimlər arasında baş vermişdir?','Ankara döyüşü Əmir Teymurla İldırım Bəyazid arasında baş vermişdir.',array['Əmir Teymurla İldırım Bəyazid','Alp Arslanla Bizans imperatoru','Çingiz xanla Batı xan','Osman bəylə Salahəddin'],1),
('utarix10-orta-esrler#11','umumi-tarix','utarix-10-orta-esrler',2,3,'Qızıl Ordu dövlətinin əsasını kim qoymuşdur?','Qızıl Ordu dövlətinin əsasını Batı xan qoymuşdur.',array['Batı xan','Çingiz xan','Uluqbəy','Toğrul bəy'],1),
('utarix10-orta-esrler#12','umumi-tarix','utarix-10-orta-esrler',2,3,'Çingiz xan hansı ildə qurultayda xaqan elan olunmuşdur?','Çingiz xan 1206-cı ildə qurultayda xaqan elan olunmuşdur.',array['1206-cı ildə','1071-ci ildə','1299-cu ildə','1492-ci ildə'],1),
('utarix10-orta-esrler#13','umumi-tarix','utarix-10-orta-esrler',2,3,'Xaçlı yürüşləri dövründə Yerusəlimi geri qaytaran hökmdar kimdir?','Yerusəlimi Salahəddin Əyyubi geri qaytarmışdır.',array['Salahəddin Əyyubi','Fateh Sultan Mehmet','Nizamülmülk','Karl Böyük'],1),
('utarix10-orta-esrler#14','umumi-tarix','utarix-10-orta-esrler',2,3,'Dördüncü səlib yürüşü hansı şəhərin tutulması ilə nəticələnmişdir?','Dördüncü səlib yürüşü Konstantinopolun tutulması ilə nəticələnmişdir.',array['Konstantinopolun','Bağdadın','Səmərqəndin','Parisin'],1),
('utarix10-orta-esrler#15','umumi-tarix','utarix-10-orta-esrler',2,3,'Teymurilər sülaləsindən olan Uluqbəy hansı sahədə şöhrət qazanmışdır?','Uluqbəy astronomiya sahəsindəki tədqiqatları ilə şöhrət qazanmışdır.',array['Astronomiya sahəsində','Dənizçilik sahəsində','Heykəltəraşlıq sahəsində','Musiqi sahəsində'],1),
('utarix10-orta-esrler#16','umumi-tarix','utarix-10-orta-esrler',2,3,'Dehli sultanlığı hansı ildə qurulmuşdur?','Dehli sultanlığı 1206-cı ildə qurulmuşdur.',array['1206-cı ildə','1299-cu ildə','1370-ci ildə','1492-ci ildə'],1),
('utarix10-orta-esrler#17','umumi-tarix','utarix-10-orta-esrler',2,3,'Kosovo döyüşü hansı tərəflər arasında baş vermişdir?','Kosovo döyüşü osmanlılarla Balkan dövlətlərinin birləşmiş qüvvələri arasında baş vermişdir.',array['Osmanlılarla Balkan qüvvələri','Səlcuqlarla Qəznəlilər','Monqollarla Teymurilər','Franklarla normanlar'],1),
('utarix10-orta-esrler#18','umumi-tarix','utarix-10-orta-esrler',2,3,'Rekonkista hansı ildə başa çatmışdır?','Rekonkista 1492-ci ildə Qranadanın alınması ilə başa çatmışdır.',array['1492-ci ildə','1206-cı ildə','1402-ci ildə','1071-ci ildə'],1),
('utarix10-orta-esrler#19','umumi-tarix','utarix-10-orta-esrler',2,3,'Yüzillik müharibə hansı əsrləri əhatə edir?','Yüzillik müharibə XIV-XV əsrləri əhatə edir.',array['XIV-XV əsrləri','XI-XII əsrləri','IX-X əsrləri','XVI-XVII əsrləri'],1),
('utarix10-orta-esrler#20','umumi-tarix','utarix-10-orta-esrler',3,3,'Aşağıdakı hadisələri xronoloji ardıcıllıqla düzün: 1. Ankara döyüşü 2. Malazgird döyüşü 3. Konstantinopolun osmanlılar tərəfindən alınması','Malazgird 1071, Ankara 1402, Konstantinopolun alınması isə 1453-cü ilə aiddir.',array['2 - 1 - 3','1 - 2 - 3','3 - 2 - 1','2 - 3 - 1'],1),
('utarix10-orta-esrler#21','umumi-tarix','utarix-10-orta-esrler',3,3,'XI-XV yüzilliklər üçün «döyüş - il» uyğunluğu hansı sırada düzgündür?','Malazgird 1071, Ankara 1402, Kosovo 1389, Dandanakan isə 1040-cı ilə aiddir.',array['Malazgird - 1071','Dandanakan - 1402','Ankara - 1071','Kosovo - 1453'],1),
('utarix10-orta-esrler#22','umumi-tarix','utarix-10-orta-esrler',3,3,'XI-XV yüzilliklərin tarixi haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Qızıl Ordunun banisi Çingiz xan deyil, onun nəvəsi Batı xandır.',array['Qızıl Ordu dövlətinin banisi Çingiz xandır','Osmanlı dövləti 1299-cu ildə qurulmuşdur','Malazgird döyüşü 1071-ci ildə olmuşdur','Uluqbəy astronomiya ilə məşğul olmuşdur'],1),
('utarix10-orta-esrler#23','umumi-tarix','utarix-10-orta-esrler',3,3,'Malazgird döyüşünün uzunmüddətli nəticəsini düzgün göstərən fikir hansıdır?','Bizansın müdafiəsi sarsıldı və Anadolu türk tayfalarının məskunlaşmasına açıldı.',array['Anadolu türk tayfalarının məskunlaşmasına açıldı','Bizans imperiyası dərhal süqut etdi','Səlcuqlar Anadoludan geri çəkildi','Xaçlı yürüşləri dayandırıldı'],1),
('utarix10-orta-esrler#24','umumi-tarix','utarix-10-orta-esrler',3,3,'1402-ci il Ankara döyüşünün Osmanlı dövləti üçün nəticəsi nə oldu?','Məğlubiyyətdən sonra dövlət parçalandı və on ilə yaxın davam edən fasilə dövrü başladı.',array['Dövlət parçalandı, uzun fasilə dövrü başladı','Osmanlılar Səmərqəndi ələ keçirdi','Konstantinopol dərhal alındı','Teymurilər dövləti süquta uğradı'],1),
('utarix10-orta-esrler#25','umumi-tarix','utarix-10-orta-esrler',3,3,'XI-XV yüzilliklərin hansı hadisəsi digərlərindən əvvəl olmuşdur?','Çingiz xanın xaqan elan olunması 1206, Kalka döyüşü 1223, Kosovo 1389, Ankara isə 1402-ci ilə aiddir.',array['Çingiz xanın xaqan elan olunması','Kalka çayı üzərindəki döyüş','Kosovo düzündəki döyüş','Ankara yaxınlığındakı döyüş'],1),
('utarix10-orta-esrler#26','umumi-tarix','utarix-10-orta-esrler',3,3,'XI-XV yüzilliklər üçün «şəxs - dövlət» uyğunluğu hansı sırada düzgündür?','Toğrul bəy Böyük Səlcuq, Batı xan Qızıl Ordu, Osman bəy isə Osmanlı dövlətinin banisidir.',array['Toğrul bəy - Böyük Səlcuq dövləti','Batı xan - Böyük Səlcuq dövləti','Osman bəy - Qızıl Ordu','Uluqbəy - Dehli sultanlığı'],1),
('utarix10-orta-esrler#27','umumi-tarix','utarix-10-orta-esrler',3,3,'Çingiz xanın hərbi uğurlarının başlıca səbəbini düzgün göstərən fikir hansıdır?','Sərt intizam və onluq sistemlə qurulmuş sürətli süvari ordu ona üstünlük verirdi.',array['Sərt intizamlı, onluq sistemli süvari ordu','Güclü dəniz donanması','Odlu silahların üstünlüyü','Qala mühasirəsindən imtina siyasəti'],1),
('utarix10-orta-esrler#28','umumi-tarix','utarix-10-orta-esrler',3,3,'Qızıl Ordunun Şərqi Avropa üçün nəticəsini düzgün göstərən fikir hansıdır?','Rus knyazlıqları uzun müddət Qızıl Orduya tabe olub xərac verməli oldu.',array['Rus knyazlıqları uzun müddət xərac verdi','Rus knyazlıqları dərhal birləşdi','Bizans Şərqi Avropanı ələ keçirdi','Bölgədə şəhər ticarəti tamam dayandı'],1),
('utarix10-orta-esrler#29','umumi-tarix','utarix-10-orta-esrler',3,3,'Xaçlı yürüşləri və Şərq dövlətləri haqqında hansı fikir SƏHVDİR?','Dördüncü səlib yürüşü Bağdadın deyil, Konstantinopolun tutulması ilə nəticələnmişdir.',array['Dördüncü səlib yürüşü Bağdadın tutulması ilə bitmişdir','Salahəddin Əyyubi Yerusəlimi geri qaytarmışdır','Rekonkista 1492-ci ildə başa çatmışdır','Dehli sultanlığı 1206-cı ildə qurulmuşdur'],1),
('utarix10-orta-esrler#30','umumi-tarix','utarix-10-orta-esrler',3,3,'Böyük Səlcuq dövləti ilə Osmanlı dövləti arasındakı tarixi bağlılıq nədir?','Osmanlılar Anadolu Səlcuq dövlətinin varisi kimi çıxış edir, onun dövlət ənənəsini davam etdirirdi.',array['Osmanlılar Anadolu Səlcuq ənənəsinin varisi idi','Osmanlılar Səlcuqlardan əvvəl dövlət qurmuşdu','Səlcuq və Osmanlı dövlətləri eyni sülalənin iki qoludur','Osmanlılar Səlcuqları Orta Asiyadan qovmuşdu'],1),
('utarix10-orta-esrler#31','umumi-tarix','utarix-10-orta-esrler',3,3,'Xaçlı yürüşlərinin Yaxın Şərq üçün nəticəsini düzgün göstərən fikir hansıdır?','İki əsrə yaxın davam edən müharibələr bölgəni zəiflətdi, sonda səlibçilər Şərqdən çıxarıldı.',array['Bölgə zəiflədi, sonda səlibçilər Şərqdən çıxarıldı','Səlibçilər bölgədə daimi hakim oldu','Bölgədə ticarət yolları tamam bağlandı','Yerusəlim səlibçilərin əlində qaldı'],1),
('utarix10-yeni-dovr#1','umumi-tarix','utarix-10-yeni-dovr',1,4,'Otuzillik müharibə hansı sülhlə başa çatmışdır?','Otuzillik müharibə 1648-ci il Vestfaliya sülhü ilə başa çatmışdır.',array['Vestfaliya sülhü ilə','Niştadt sülhü ilə','Karlovitsa sülhü ilə','Versal sülhü ilə'],1),
('utarix10-yeni-dovr#2','umumi-tarix','utarix-10-yeni-dovr',1,4,'Rusiyada 1613-cü ildən hakimiyyətə gələn sülalə hansıdır?','Rusiyada 1613-cü ildən Romanovlar sülaləsi hakimiyyətə gəlmişdir.',array['Romanovlar','Teymurilər','Baburilər','Sinlər'],1),
('utarix10-yeni-dovr#3','umumi-tarix','utarix-10-yeni-dovr',1,4,'Hindistanda Böyük Moğol dövlətinin banisi kimdir?','Böyük Moğol dövlətinin banisi Baburdur.',array['Babur','Övrəngzeb','I Pyotr','Osman bəy'],1),
('utarix10-yeni-dovr#4','umumi-tarix','utarix-10-yeni-dovr',1,4,'Fransada mütləqiyyətin zirvəsi hansı kralın adı ilə bağlıdır?','Fransada mütləqiyyətin zirvəsi XIV Lüdovikin adı ilə bağlıdır.',array['XIV Lüdovik','IV İvan','II Yekaterina','İldırım Bəyazid'],1),
('utarix10-yeni-dovr#5','umumi-tarix','utarix-10-yeni-dovr',2,4,'Otuzillik müharibə hansı illəri əhatə edir?','Otuzillik müharibə 1618-1648-ci illəri əhatə edir.',array['1618-1648-ci illəri','1700-1721-ci illəri','1337-1453-cü illəri','1789-1799-cu illəri'],1),
('utarix10-yeni-dovr#6','umumi-tarix','utarix-10-yeni-dovr',2,4,'Rusiyada ilk dəfə çar titulunu kim qəbul etmişdir?','Rusiyada ilk dəfə çar titulunu IV İvan qəbul etmişdir.',array['IV İvan','I Pyotr','II Yekaterina','Batı xan'],1),
('utarix10-yeni-dovr#7','umumi-tarix','utarix-10-yeni-dovr',2,4,'Şimal müharibəsi hansı iki dövlət arasında getmişdir?','Şimal müharibəsi Rusiya ilə İsveç arasında getmişdir.',array['Rusiya ilə İsveç','Fransa ilə İspaniya','Osmanlı ilə Baburilər','İngiltərə ilə Hollandiya'],1),
('utarix10-yeni-dovr#8','umumi-tarix','utarix-10-yeni-dovr',2,4,'Şimal müharibəsi hansı sülhlə başa çatmışdır?','Şimal müharibəsi 1721-ci il Niştadt sülhü ilə başa çatmışdır.',array['Niştadt sülhü ilə','Vestfaliya sülhü ilə','Küçük Qaynarca müqaviləsi ilə','Aqsburq sülhü ilə'],1),
('utarix10-yeni-dovr#9','umumi-tarix','utarix-10-yeni-dovr',2,4,'Rusiya hansı ildə rəsmən imperiya elan olunmuşdur?','Rusiya 1721-ci ildə rəsmən imperiya elan olunmuşdur.',array['1721-ci ildə','1613-cü ildə','1648-ci ildə','1774-cü ildə'],1),
('utarix10-yeni-dovr#10','umumi-tarix','utarix-10-yeni-dovr',2,4,'I Pyotrun apardığı islahatların başlıca məqsədi nə idi?','İslahatların məqsədi ölkəni Avropa nümunəsində yeniləmək və gücləndirmək idi.',array['Ölkəni Avropa nümunəsində yeniləmək','Ölkəni xarici aləmdən qapamaq','Ordunu tamam buraxmaq','Paytaxtı Səmərqəndə köçürmək'],1),
('utarix10-yeni-dovr#11','umumi-tarix','utarix-10-yeni-dovr',2,4,'Osmanlı imperiyasının ilk geniş ərazi güzəşti hansı sülhlə bağlıdır?','İlk geniş ərazi güzəşti 1699-cu il Karlovitsa sülhü ilə bağlıdır.',array['Karlovitsa sülhü ilə','Niştadt sülhü ilə','Vestfaliya sülhü ilə','Utrext ittifaqı ilə'],1),
('utarix10-yeni-dovr#12','umumi-tarix','utarix-10-yeni-dovr',2,4,'Osmanlı tarixində Lalə dövrü nə ilə səciyyələnir?','Lalə dövrü Avropa ilə mədəni yaxınlaşma və ilk mətbəənin açılması ilə səciyyələnir.',array['Avropa ilə mədəni yaxınlaşma və mətbəənin açılması','Bütün xarici əlaqələrin kəsilməsi','Paytaxtın Bağdada köçürülməsi','Ordunun ləğv edilməsi'],1),
('utarix10-yeni-dovr#13','umumi-tarix','utarix-10-yeni-dovr',2,4,'Babur Hindistanda hakimiyyəti hansı döyüşdən sonra ələ almışdır?','Babur 1526-cı il Panipat döyüşündən sonra Hindistanda hakimiyyəti ələ almışdır.',array['Panipat döyüşündən sonra','Ankara döyüşündən sonra','Kosovo döyüşündən sonra','Malazgird döyüşündən sonra'],1),
('utarix10-yeni-dovr#14','umumi-tarix','utarix-10-yeni-dovr',2,4,'Böyük Moğol dövləti hansı ildə qurulmuşdur?','Böyük Moğol dövləti 1526-cı ildə qurulmuşdur.',array['1526-cı ildə','1613-cü ildə','1699-cu ildə','1721-ci ildə'],1),
('utarix10-yeni-dovr#15','umumi-tarix','utarix-10-yeni-dovr',2,4,'Küçük Qaynarca müqaviləsi hansı iki dövlət arasında bağlanmışdır?','Küçük Qaynarca müqaviləsi Osmanlı imperiyası ilə Rusiya arasında bağlanmışdır.',array['Osmanlı ilə Rusiya','Fransa ilə İsveç','İngiltərə ilə Hollandiya','İspaniya ilə Portuqaliya'],1),
('utarix10-yeni-dovr#16','umumi-tarix','utarix-10-yeni-dovr',2,4,'Fransada mütləqiyyət dövrünün simvoluna çevrilmiş saray hansıdır?','Mütləqiyyət dövrünün simvolu Versal sarayıdır.',array['Versal sarayı','Topqapı sarayı','Tac Mahal','Ayasofya'],1),
('utarix10-yeni-dovr#17','umumi-tarix','utarix-10-yeni-dovr',2,4,'XVI-XVII əsrlərdə Rusiyanın ərazi genişlənməsi əsasən hansı istiqamətdə getmişdir?','Rusiyanın genişlənməsi əsasən şərqə, Sibir istiqamətində getmişdir.',array['Şərqə, Sibir istiqamətində','Cənuba, Misir istiqamətində','Qərbə, Britaniya istiqamətində','Şimala, Qrenlandiya istiqamətində'],1),
('utarix10-yeni-dovr#18','umumi-tarix','utarix-10-yeni-dovr',2,4,'II Yekaterinanın Rusiyada yeritdiyi daxili siyasət necə adlandırılır?','Onun daxili siyasəti maarifçi mütləqiyyət adlandırılır.',array['Maarifçi mütləqiyyət','Konstitusiyalı monarxiya','Hərbi protektorluq','Parlament respublikası'],1),
('utarix10-yeni-dovr#19','umumi-tarix','utarix-10-yeni-dovr',2,4,'Vestfaliya sülhündən sonra Almaniya ərazisi hansı vəziyyətdə qaldı?','Almaniya çoxsaylı müstəqil knyazlıqlara bölünmüş halda qaldı.',array['Çoxsaylı knyazlıqlara bölünmüş halda','Vahid mərkəzləşmiş dövlət kimi','Fransanın tərkibində','Osmanlı vassalı kimi'],1),
('utarix10-yeni-dovr#20','umumi-tarix','utarix-10-yeni-dovr',3,4,'Aşağıdakı hadisələri xronoloji ardıcıllıqla düzün: 1. Vestfaliya sülhünün bağlanması 2. Küçük Qaynarca müqaviləsi 3. Niştadt sülhü','Vestfaliya sülhü 1648, Niştadt sülhü 1721, Küçük Qaynarca müqaviləsi isə 1774-cü ilə aiddir.',array['1 - 3 - 2','1 - 2 - 3','3 - 1 - 2','2 - 3 - 1'],1),
('utarix10-yeni-dovr#21','umumi-tarix','utarix-10-yeni-dovr',3,4,'XVI-XVIII yüzilliklər üçün «müqavilə - tərəflər» uyğunluğu hansı sırada düzgündür?','Niştadt sülhü Rusiya ilə İsveç, Küçük Qaynarca isə Osmanlı ilə Rusiya arasında bağlanmışdır.',array['Niştadt sülhü - Rusiya və İsveç','Vestfaliya sülhü - Rusiya və İsveç','Karlovitsa sülhü - Fransa və İngiltərə','Küçük Qaynarca - Osmanlı və İsveç'],1),
('utarix10-yeni-dovr#22','umumi-tarix','utarix-10-yeni-dovr',3,4,'XVI-XVIII yüzilliklərin tarixi haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Şimal müharibəsi Rusiya ilə İsveç arasında getmişdir, Osmanlı bu müharibənin tərəfi olmamışdır.',array['Şimal müharibəsi Rusiya ilə Osmanlı arasında getmişdir','Otuzillik müharibə Vestfaliya sülhü ilə bitmişdir','Böyük Moğol dövlətini Babur qurmuşdur','Rusiya 1721-ci ildə imperiya elan olunmuşdur'],1),
('utarix10-yeni-dovr#23','umumi-tarix','utarix-10-yeni-dovr',3,4,'Otuzillik müharibənin Almaniya torpaqları üçün nəticəsini düzgün göstərən fikir hansıdır?','Ölkə parçalanmış qaldı, əhali və təsərrüfat ağır itki verdi.',array['Ölkə parçalanmış qaldı, təsərrüfat ağır itki verdi','Vahid Alman imperiyası quruldu','Almaniya Avropanın ən güclü dövlətinə çevrildi','Alman knyazlıqları Fransaya birləşdirildi'],1),
('utarix10-yeni-dovr#24','umumi-tarix','utarix-10-yeni-dovr',3,4,'I Pyotrun islahatlarını II Yekaterinanın siyasətindən fərqləndirən cəhət nədir?','I Pyotr dövləti sərt inzibati tədbirlərlə Avropa qaydasına saldı, II Yekaterina isə maarifçi ideyalara söykənərək zadəganlara güzəştə getdi.',array['Biri sərt inzibati yolla, digəri maarifçi güzəştlərlə hərəkət edirdi','Hər ikisi dövlət idarəçiliyini parlamentə verdi','Biri ordunu buraxdı, digəri donanmanı ləğv etdi','Hər ikisi ölkəni xarici aləmdən qapadı'],1),
('utarix10-yeni-dovr#25','umumi-tarix','utarix-10-yeni-dovr',3,4,'XVI-XVIII yüzilliklərin hansı hadisəsi digərlərindən əvvəl olmuşdur?','Osmanlıların Vyana yürüşü 1683, Karlovitsa sülhü 1699, Şimal müharibəsinin başlanması 1700, Niştadt sülhü isə 1721-ci ilə aiddir.',array['Osmanlıların Vyana yürüşü','Karlovitsa sülhünün bağlanması','Şimal müharibəsinin başlanması','Niştadt sülhünün bağlanması'],1),
('utarix10-yeni-dovr#26','umumi-tarix','utarix-10-yeni-dovr',3,4,'XVI-XVIII yüzilliklər üçün «hökmdar - ölkə» uyğunluğu hansı sırada düzgündür?','I Pyotr Rusiyanın, XIV Lüdovik Fransanın, Övrəngzeb isə Böyük Moğol dövlətinin hökmdarı olmuşdur.',array['I Pyotr - Rusiya','XIV Lüdovik - Rusiya','Övrəngzeb - Fransa','IV İvan - Böyük Moğol dövləti'],1),
('utarix10-yeni-dovr#27','umumi-tarix','utarix-10-yeni-dovr',3,4,'Karlovitsa sülhünün Osmanlı tarixi üçün mənasını düzgün göstərən fikir hansıdır?','İmperiya ilk dəfə geniş ərazi güzəştinə getdi, bu isə uzunmüddətli geriləmənin başlanğıcı oldu.',array['İlk geniş ərazi güzəşti və geriləmənin başlanğıcı oldu','İmperiyanın ən böyük ərazi qazancı oldu','Osmanlının Avropadan tam çıxması demək idi','Rusiya ilə ittifaqın başlanğıcı oldu'],1),
('utarix10-yeni-dovr#28','umumi-tarix','utarix-10-yeni-dovr',3,4,'Vestfaliya sülhünün beynəlxalq münasibətlərə gətirdiyi əsas yenilik nədir?','Sülh dövlətlərin suveren bərabərliyinə əsaslanan ilk beynəlxalq münasibətlər sistemini qurdu.',array['Dövlətlərin suveren bərabərliyi prinsipini gətirdi','Bütün monarxiyaları ləğv etdi','Avropada vahid imperiya yaratdı','Koloniyaların sərhədlərini müəyyən etdi'],1),
('utarix10-yeni-dovr#29','umumi-tarix','utarix-10-yeni-dovr',3,4,'Rusiya və Şərq dövlətləri haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Rusiyada ilk çar titulunu I Pyotr deyil, IV İvan qəbul etmişdir; I Pyotr imperator titulunu almışdır.',array['Rusiyada ilk çar titulunu I Pyotr qəbul etmişdir','Lalə dövründə Osmanlıda mətbəə açılmışdır','Babur Panipat döyüşündən sonra Hindistanda hakim oldu','Versal sarayı Fransa mütləqiyyətinin simvoludur'],1),
('utarix10-yeni-dovr#30','umumi-tarix','utarix-10-yeni-dovr',3,4,'Böyük Moğol dövlətinin XVIII əsrdə zəifləməsinin daxili səbəbini düzgün göstərən fikir hansıdır?','Uzun sürən müharibələr və dini dözümsüzlük siyasəti yerli əhalinin narazılığını artırmışdı.',array['Uzun müharibələr və dini siyasət narazılığı artırdı','Ölkədə ticarət tamam qadağan olunmuşdu','Paytaxt Səmərqəndə köçürülmüşdü','Hökmdar seçki yolu ilə təyin olunurdu'],1),
('utarix10-yeni-dovr#31','umumi-tarix','utarix-10-yeni-dovr',3,4,'Rusiyanın XVIII əsrdə Baltik dənizinə çıxış qazanmasının əhəmiyyətini düzgün göstərən fikir hansıdır?','Avropa ilə birbaşa dəniz ticarəti mümkün oldu və sahildə yeni paytaxt salındı.',array['Avropa ilə birbaşa dəniz ticarəti və yeni paytaxt imkanı yarandı','Ölkə Sibirdəki torpaqlardan əl çəkməli oldu','Ölkənin xarici ticarəti tamam dayandırıldı','Rusiya Aralıq dənizi yollarına nəzarəti ələ aldı'],1),
('utarix10-medeniyyet#1','umumi-tarix','utarix-10-medeniyyet',1,4,'Cəbr elminin əsasını qoyan orta əsr Şərq alimi kimdir?','Cəbr elminin əsasını əl-Xarəzmi qoymuşdur.',array['Əl-Xarəzmi','Rembrandt','Mimar Sinan','Rene Dekart'],1),
('utarix10-medeniyyet#2','umumi-tarix','utarix-10-medeniyyet',1,4,'«Tibb qanunu» əsərinin müəllifi kimdir?','«Tibb qanunu» əsərinin müəllifi İbn Sinadır.',array['İbn Sina','Ömər Xəyyam','İsaak Nyuton','Yohan Sebastyan Bax'],1),
('utarix10-medeniyyet#3','umumi-tarix','utarix-10-medeniyyet',1,4,'Marağa rəsədxanasının banisi kimdir?','Marağa rəsədxanasının banisi Nəsirəddin Tusidir.',array['Nəsirəddin Tusi','Əl-Biruni','Qalileo Qaliley','Mimar Sinan'],1),
('utarix10-medeniyyet#4','umumi-tarix','utarix-10-medeniyyet',1,4,'Ümumdünya cazibə qanununu kəşf edən alim kimdir?','Ümumdünya cazibə qanununu İsaak Nyuton kəşf etmişdir.',array['İsaak Nyuton','İbn Rüşd','Uluqbəy','Volfqanq Mosart'],1),
('utarix10-medeniyyet#5','umumi-tarix','utarix-10-medeniyyet',2,4,'Ömər Xəyyam hansı şeir formasının ustadı sayılır?','Ömər Xəyyam rübai formasının ustadı sayılır.',array['Rübai','Sonet','Poema','Oda'],1),
('utarix10-medeniyyet#6','umumi-tarix','utarix-10-medeniyyet',2,4,'Uluqbəyin Səmərqənddə qurduğu elm ocağı nə idi?','Uluqbəy Səmərqənddə böyük rəsədxana qurmuşdu.',array['Rəsədxana','Dəniz məktəbi','Mətbəə','Xəstəxana'],1),
('utarix10-medeniyyet#7','umumi-tarix','utarix-10-medeniyyet',2,4,'Osmanlı memarlığının zirvəsi sayılan memar kimdir?','Osmanlı memarlığının zirvəsi Mimar Sinanın adı ilə bağlıdır.',array['Mimar Sinan','Nəsirəddin Tusi','Rene Dekart','Rembrandt'],1),
('utarix10-medeniyyet#8','umumi-tarix','utarix-10-medeniyyet',2,4,'Teleskopla göy cisimlərini müşahidə edən italyan alimi kimdir?','Teleskopla göy cisimlərini Qalileo Qaliley müşahidə etmişdir.',array['Qalileo Qaliley','Əl-Biruni','İbn Rüşd','Mimar Sinan'],1),
('utarix10-medeniyyet#9','umumi-tarix','utarix-10-medeniyyet',2,4,'«Düşünürəm, deməli, varam» fikri hansı mütəfəkkirə aiddir?','Bu fikir fransız filosofu Rene Dekarta aiddir.',array['Rene Dekart','İsaak Nyuton','Ömər Xəyyam','Uluqbəy'],1),
('utarix10-medeniyyet#10','umumi-tarix','utarix-10-medeniyyet',2,4,'Əl-Biruni hansı elm sahələrində şöhrət qazanmışdır?','Əl-Biruni astronomiya, coğrafiya və riyaziyyat sahələrində şöhrət qazanmışdır.',array['Astronomiya, coğrafiya və riyaziyyat','Memarlıq və heykəltəraşlıq','Musiqi və rəqs','Dənizçilik və gəmiqayırma'],1),
('utarix10-medeniyyet#11','umumi-tarix','utarix-10-medeniyyet',2,4,'XVII-XVIII əsrlərdə Avropa memarlığındakı təmtəraqlı üslub necə adlanır?','Bu təmtəraqlı üslub barokko adlanır.',array['Barokko','Qotika','Roman üslubu','Konstruktivizm'],1),
('utarix10-medeniyyet#12','umumi-tarix','utarix-10-medeniyyet',2,4,'Antik ölçü və sadəliyə qayıdışı əsas götürən XVII-XVIII əsr üslubu hansıdır?','Bu üslub klassisizm adlanır.',array['Klassisizm','Barokko','Qotika','Romantizm'],1),
('utarix10-medeniyyet#13','umumi-tarix','utarix-10-medeniyyet',2,4,'XVII əsr Hollandiya rəssamlığının ən böyük ustadı kimdir?','Hollandiya rəssamlığının ən böyük ustadı Rembrandtdır.',array['Rembrandt','Mimar Sinan','Qalileo Qaliley','Ömər Xəyyam'],1),
('utarix10-medeniyyet#14','umumi-tarix','utarix-10-medeniyyet',2,4,'Barokko musiqisinin ən görkəmli nümayəndəsi kimdir?','Barokko musiqisinin ən görkəmli nümayəndəsi Yohan Sebastyan Baxdır.',array['Yohan Sebastyan Bax','Volfqanq Amadey Mosart','Rene Dekart','İsaak Nyuton'],1),
('utarix10-medeniyyet#15','umumi-tarix','utarix-10-medeniyyet',2,4,'Vyana klassik musiqi məktəbinin tanınmış nümayəndəsi kimdir?','Vyana klassik məktəbinin tanınmış nümayəndəsi Volfqanq Amadey Mosartdır.',array['Volfqanq Amadey Mosart','Yohan Sebastyan Bax','Rembrandt','Əl-Xarəzmi'],1),
('utarix10-medeniyyet#16','umumi-tarix','utarix-10-medeniyyet',2,4,'İbn Rüşd hansı antik filosofun əsərlərinə şərhlər yazmışdır?','İbn Rüşd Aristotelin əsərlərinə şərhlər yazmışdır.',array['Aristotelin','Homerin','Herodotun','Arximedin'],1),
('utarix10-medeniyyet#17','umumi-tarix','utarix-10-medeniyyet',2,4,'Avropada işlənən rəqəmlər əslində hansı ölkədən götürülmüşdür?','Bu rəqəmlər Hindistandan götürülüb ərəblər vasitəsilə Avropaya keçmişdir.',array['Hindistandan','Misirdən','Yunanıstandan','Çindən'],1),
('utarix10-medeniyyet#18','umumi-tarix','utarix-10-medeniyyet',2,4,'İsaak Nyutonun əsas elmi əsəri necə adlanır?','Nyutonun əsas əsəri «Natural fəlsəfənin riyazi əsasları»dır.',array['«Natural fəlsəfənin riyazi əsasları»','«Tibb qanunu»','«Siyasətnamə»','«Avesta»'],1),
('utarix10-medeniyyet#19','umumi-tarix','utarix-10-medeniyyet',2,4,'XVII-XVIII əsrlərdə elmi biliklərin yayılmasına təkan verən yeni qurumlar hansılardır?','Bu dövrdə yaranan elmlər akademiyaları biliklərin yayılmasına təkan vermişdir.',array['Elmlər akademiyaları','Cəngavər ordenləri','Sex birlikləri','Monastır emalatxanaları'],1),
('utarix10-medeniyyet#20','umumi-tarix','utarix-10-medeniyyet',3,4,'Aşağıdakı hadisələri xronoloji ardıcıllıqla düzün: 1. Uluqbəy rəsədxanasının qurulması 2. Nyutonun cazibə qanununu verməsi 3. İbn Sinanın «Tibb qanunu»nu yazması','İbn Sina XI əsrdə, Uluqbəy XV əsrdə, Nyuton isə XVII əsrin sonunda fəaliyyət göstərmişdir.',array['3 - 1 - 2','1 - 2 - 3','2 - 1 - 3','3 - 2 - 1'],1),
('utarix10-medeniyyet#21','umumi-tarix','utarix-10-medeniyyet',3,4,'Orta əsrlər və yeni dövr üçün «alim - elm sahəsi» uyğunluğu hansı sırada düzgündür?','Əl-Xarəzmi cəbrin, Mimar Sinan memarlığın, Rembrandt isə rəssamlığın nümayəndəsidir.',array['Əl-Xarəzmi - cəbr','İbn Sina - memarlıq','Mimar Sinan - tibb','Rembrandt - riyaziyyat'],1),
('utarix10-medeniyyet#22','umumi-tarix','utarix-10-medeniyyet',3,4,'Orta əsrlər və yeni dövr mədəniyyəti haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','«Tibb qanunu» əsəri Ömər Xəyyamın deyil, İbn Sinanın qələmindən çıxmışdır.',array['«Tibb qanunu» əsərini Ömər Xəyyam yazmışdır','Marağa rəsədxanasını Nəsirəddin Tusi qurmuşdur','Uluqbəy Səmərqənddə rəsədxana tikdirmişdir','İbn Rüşd Aristotelə şərhlər yazmışdır'],1),
('utarix10-medeniyyet#23','umumi-tarix','utarix-10-medeniyyet',3,4,'Rəsədxanaların qurulmasının astronomiya elminə təsirini düzgün göstərən fikir hansıdır?','Uzunmüddətli müntəzəm müşahidələr ulduz cədvəllərini xeyli dəqiqləşdirdi.',array['Müntəzəm müşahidələr ulduz cədvəllərini dəqiqləşdirdi','Göy cisimlərinin öyrənilməsi dayandırıldı','Təqvim hesablamaları istifadədən çıxdı','Riyazi hesablamalara ehtiyac qalmadı'],1),
('utarix10-medeniyyet#24','umumi-tarix','utarix-10-medeniyyet',3,4,'Barokko ilə klassisizm üslublarını düzgün müqayisə edən fikir hansıdır?','Barokko təmtəraq və hərəkət, klassisizm isə antik ölçü və sadəlik üzərində qurulur.',array['Barokko təmtəraqlı, klassisizm ölçülü və sadədir','Barokko sadə, klassisizm təmtəraqlıdır','Hər ikisi orta əsr qotikasının davamıdır','Hər ikisi yalnız musiqiyə aid üslubdur'],1),
('utarix10-medeniyyet#25','umumi-tarix','utarix-10-medeniyyet',3,4,'Şərq alimlərinin Avropa elminə təsirini düzgün göstərən fikir hansıdır?','Antik mətnlər və yeni biliklər ərəb dilindən latın dilinə tərcümə yolu ilə Avropaya keçdi.',array['Biliklər ərəb dilindən latın dilinə tərcümə ilə keçdi','Avropa Şərq elmindən tamam təcrid olunmuşdu','Şərq alimləri Avropa universitetlərini idarə edirdi','Avropa öz elmini Şərqə latın dilində ötürürdü'],1),
('utarix10-medeniyyet#26','umumi-tarix','utarix-10-medeniyyet',3,4,'Yeni dövr incəsənəti haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?','Barokko musiqisinin nümayəndəsi Bax, Vyana klassik məktəbinin nümayəndəsi isə Mosartdır.',array['Vyana klassik məktəbinin nümayəndəsi Baxdır','Rembrandt Hollandiya rəssamlıq məktəbinə aiddir','Dekart yeni dövr fəlsəfəsinin görkəmli siması idi','Qaliley teleskopla göy cisimlərini müşahidə etmişdir'],1),
('utarix10-medeniyyet#27','umumi-tarix','utarix-10-medeniyyet',3,4,'Qalileyin teleskop müşahidələrinin elm tarixi üçün əhəmiyyəti nədir?','Müşahidələr günəşmərkəzli sistemin lehinə ilk birbaşa dəlilləri verdi.',array['Günəşmərkəzli sistemin lehinə dəlil verdi','Yerin kainatın mərkəzi olduğunu təsdiqlədi','Cazibə qanununu riyazi ifadə etdi','Ulduzların sayının sabit olduğunu göstərdi'],1),
('utarix10-medeniyyet#28','umumi-tarix','utarix-10-medeniyyet',3,4,'Nyuton mexanikasının elm üçün başlıca mənası nədir?','O, göy cisimlərinin və yerdəki cisimlərin hərəkətini vahid qanunlarla izah etdi.',array['Göy və yer hərəkətini vahid qanunlarla izah etdi','Astronomiya ilə fizikanı bir-birindən ayırdı','Riyaziyyatın fizikada istifadəsini məhdudlaşdırdı','Yalnız optikaya aid nəticələr verdi'],1),
('utarix10-medeniyyet#29','umumi-tarix','utarix-10-medeniyyet',3,4,'Orta əsrlər və yeni dövr üçün «usta - əsər» uyğunluğu hansı sırada düzgündür?','«Natural fəlsəfənin riyazi əsasları» Nyutonun, «Tibb qanunu» İbn Sinanın əsəridir.',array['Nyuton - «Natural fəlsəfənin riyazi əsasları»','İbn Sina - «Natural fəlsəfənin riyazi əsasları»','Ömər Xəyyam - «Tibb qanunu»','Dekart - «Siyasətnamə»'],1),
('utarix10-medeniyyet#30','umumi-tarix','utarix-10-medeniyyet',3,4,'Şərq riyaziyyatında onluq say sistemi və sıfırın yayılmasının əhəmiyyəti nədir?','Bu sistem hesablamaları xeyli asanlaşdırdı və ticarətlə elmin inkişafına təkan verdi.',array['Hesablamaları asanlaşdırıb elmin inkişafına təkan verdi','Yazının unudulmasına gətirib çıxardı','Astronomiya müşahidələrini çətinləşdirdi','Ticarət sənədlərinin tərtibini ləngitdi'],1),
('utarix10-medeniyyet#31','umumi-tarix','utarix-10-medeniyyet',3,4,'XVII-XVIII əsrlərdə elmi cəmiyyət və akademiyaların yaranmasının başlıca səbəbi nə idi?','Təcrübi biliyin sürətlə artması alimlərin nəticələri bölüşmək və yoxlamaq ehtiyacını doğurmuşdu.',array['Alimlərin nəticələri bölüşmək və yoxlamaq ehtiyacı','Universitetlərin bağlanması qərarı','Kitab çapının hər yerdə qadağan olunması','Elmdə latın dilindən imtina'],1)
),
ins as (
  insert into public.questions
    (ext_key, owner_type, subject_id, level_id, topic_id, kind,
     body, explanation, difficulty, quarter, status)
  select d.ext, 'platform', s.id, tp.level_id, tp.id, 'single',
         d.body, d.why, d.diff, d.rub, 'published'
    from d
    join public.subjects s on s.slug = d.fenn
    join public.topics   tp on tp.subject_id = s.id and tp.slug = d.topic
  on conflict (ext_key) do update
    set body = excluded.body, explanation = excluded.explanation,
        difficulty = excluded.difficulty, quarter = excluded.quarter,
        topic_id = excluded.topic_id, level_id = excluded.level_id,
        subject_id = excluded.subject_id, status = 'published'
  returning id, ext_key
)
insert into public.question_options (question_id, ord, body, is_correct)
select ins.id, o.ord, o.txt, o.ord = d.correct
  from ins
  join d on d.ext = ins.ext_key,
  lateral unnest(d.opts) with ordinality as o(txt, ord);

do $$
declare n int; k int;
begin
  select count(*) into n from public.questions
   where owner_type = 'platform' and ext_key like 'utarix10-%';
  if n <> 186 then
    raise exception 'Umumi tarix 10 suallari: 186 gozlenilirdi, % tapildi', n;
  end if;
  select count(*) into k from public.questions q
   where q.ext_key like 'utarix10-%'
     and ((select count(*) from public.question_options o
            where o.question_id = q.id) <> 4
       or (select count(*) from public.question_options o
            where o.question_id = q.id and o.is_correct) <> 1);
  if k > 0 then
    raise exception '% sualda variant qurulusu sehvdir', k;
  end if;
  select count(distinct topic_id) into k from public.questions
   where ext_key like 'utarix10-%';
  if k <> 6 then
    raise exception 'movzu sayi 6 deyil: %', k;
  end if;
  --  Her movzuda en azi 12 cetin sual olmalidir ki, muellim BIR
  --  movzudan 10 sualliq cetin test yiga bilsin
  select count(*) into k from (
    select q.topic_id from public.questions q
     where q.ext_key like 'utarix10-%' and q.difficulty = 3
     group by q.topic_id having count(*) < 12) z;
  if k > 0 then
    raise exception '% movzuda 12-den az cetin sual var', k;
  end if;
  raise notice 'Umumi tarix 10 banki: % sual, 6 movzu (her birinde 12 cetin).', n;
end $$;
