#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Edebiyyat 10 banki -> db/59_bank_edebiyyat10.sql

    8 movzu x 31 sual = 248

Movzular 58_movzular_edebiyyat9_10.sql agacina uygundur (e-derslik
kitab id 732).  Dersliyin BEDII METNI ve calismalari goturulmur -
muellif huququ ile qorunur.  Suallar eserin adi, muellifi, dovru,
janri, obrazlari ve edebiyyatsunasliq terminleri uzerinde qurulur.

CETINLIK BOLGUSU her movzuda:  4 asan + 15 orta + 12 cetin.

Isletmek:
    python3 tools/edebiyyat10.py
    python3 tools/cetinlik_analiz.py edeb10      # 0 vermelidir
"""
import io
import os

KOK = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CIXIS = os.path.join(KOK, "db", "59_bank_edebiyyat10.sql")

#  (movzu-slug, rub)
MOVZULAR = [
    ("edeb-10-sifahi",        1),
    ("edeb-10-dede-qorqud",   1),
    ("edeb-10-nizami",        2),
    ("edeb-10-nesimi-xetayi", 2),
    ("edeb-10-fuzuli",        3),
    ("edeb-10-koroglu-vaqif", 3),
    ("edeb-10-axundzade",     4),
    ("edeb-10-maarifci",      4),
]

BOLGU = {1: 4, 2: 15, 3: 12}

SUALLAR = {}

HISSE_1 = {
"edeb-10-sifahi": [
 # ---- asan (4)
 ("Şifahi xalq ədəbiyyatının əsas əlaməti nədir?",
  "Bu əsərlərin konkret müəllifi məlum olmur, xalq yaradıcılığıdır.",
  ["Müəllifinin məlum olmaması", "Kitab şəklində yazılması",
   "Bir müəllifə aid olması", "Xarici dildə yaranması"], 1, None, 1),
 ("Bayatı neçə misradan ibarətdir?",
  "Bayatı dörd misralı şeir formasıdır.",
  ["4", "2", "6", "8"], 1, None, 1),
 ("Aşıq hansı musiqi alətində çalır?",
  "Aşığın əsas aləti sazdır.",
  ["Saz", "Tar", "Kaman", "Ney"], 1, None, 1),
 ("Lətifə janrının ən məşhur qəhrəmanı kimdir?",
  "Lətifələrin əsas qəhrəmanı Molla Nəsrəddindir.",
  ["Molla Nəsrəddin", "Koroğlu", "Dədə Qorqud", "Kərəm"], 1, None, 1),
 # ---- orta (15)
 ("Bayatının hər misrasında neçə heca olur?",
  "Bayatı yeddi hecalı misralardan qurulur.",
  ["7", "5", "8", "11"], 1, None, 2),
 ("Bayatının qafiyə quruluşu necədir?",
  "Bayatıda birinci, ikinci və dördüncü misralar qafiyələnir.",
  ["a-a-b-a", "a-b-a-b", "a-a-a-a", "a-b-b-a"], 1, None, 2),
 ("«Əsli və Kərəm» hansı dastan növünə aiddir?",
  "Bu, məhəbbət dastanıdır.",
  ["Məhəbbət dastanı", "Qəhrəmanlıq dastanı", "Tarixi salnamə",
   "Mərasim nəğməsi"], 1, None, 2),
 ("Ağı nə zaman söylənir?",
  "Ağı yas mərasimində, itki üstündə söylənir.",
  ["Yas mərasimində", "Toy mərasimində", "Novruz bayramında",
   "Əkin vaxtı"], 1, None, 2),
 ("Laylay kimə oxunur?",
  "Laylay beşikdəki körpəni yatırtmaq üçün oxunur.",
  ["Beşikdəki körpəyə", "Cəbhəyə gedənə", "Gələn qonağa",
   "Bayram tonqalında"], 1, None, 2),
 ("Holavar hansı əmək sahəsi ilə bağlıdır?",
  "Holavar əkinçilikdə, cüt sürərkən oxunan nəğmədir.",
  ["Əkinçiliklə", "Balıqçılıqla", "Dəmirçiliklə", "Xalçaçılıqla"],
  1, None, 2),
 ("Sayaçı sözü hansı təsərrüfat sahəsi ilə bağlıdır?",
  "Sayaçı sözü heyvandarlıqla, qoyun sürüsü ilə bağlıdır.",
  ["Heyvandarlıqla", "Bağçılıqla", "Ticarətlə", "Ovçuluqla"], 1, None, 2),
 ("Dastanların quruluşunda hansı iki forma növbələşir?",
  "Dastanda nəsr hissəsi ilə nəzm parçaları növbələşir.",
  ["Nəzm və nəsr", "İki ayrı nəzm forması", "Nəsr və not yazısı",
   "Şeir və rəsm"], 1, None, 2),
 ("Atalar sözünün əsas xüsusiyyəti nədir?",
  "Qısa formada dərin hikmət ifadə etməsidir.",
  ["Qısa formada hikmət ifadə etməsi", "Uzun süjetli olması",
   "Sazla oxunması", "Müəllifinin bəlli olması"], 1, None, 2),
 ("Tapmaca nəyə xidmət edir?",
  "Əşyanı əlamətlərinə görə tapmağa, zehni itiləməyə xidmət edir.",
  ["Əşyanı əlamətinə görə tapmağa", "Yas mərasiminə",
   "Toy adətinə", "Əkin işinə"], 1, None, 2),
 ("«Koroğlu» hansı dastan növünə aiddir?",
  "«Koroğlu» qəhrəmanlıq dastanıdır.",
  ["Qəhrəmanlıq dastanı", "Məhəbbət dastanı", "Ailə-məişət nağılı",
   "Mərasim nəğməsi"], 1, None, 2),
 ("Nağılın ənənəvi başlanğıc ifadəsi hansıdır?",
  "Nağıllar çox vaxt «Biri var idi, biri yox idi» ilə başlayır.",
  ["«Biri var idi, biri yox idi»", "«Göydən üç alma düşdü»",
   "«Nağıl burada bitdi»", "«Zaman keçdi, illər ötdü»"], 1, None, 2),
 ("Şifahi ədəbiyyat əsərlərinin variantlarının olmasının səbəbi nədir?",
  "Əsərlər ağızdan-ağıza keçdiyi üçün hər söyləyicidə bir qədər dəyişir.",
  ["Ağızdan-ağıza keçməsi", "Kitab şəklində çap olunması",
   "Bir müəllifin yazması", "Xarici dildən tərcümə edilməsi"],
  1, None, 2),
 ("Qoşma neçə misralı bənddən ibarətdir?",
  "Qoşmanın hər bəndi dörd misradan ibarətdir.",
  ["Dörd misralı bənddən", "İki misralı bənddən",
   "Beş misralı bənddən", "Altı misralı bənddən"], 1, None, 2),
 ("Yanıltmac nəyə xidmət edir?",
  "Düzgün və aydın tələffüzün məşqinə xidmət edir.",
  ["Düzgün tələffüzün məşqinə", "Yas mərasiminə", "Əkin işinə",
   "Ov ayininə"], 1, None, 2),
 # ---- cetin (12)
 ("Aşağıdakı «janr - səciyyəvi cəhət» cütlüklərindən hansı düzgündür?",
  "Bayatı yeddi hecalı dördlükdür, qoşma isə on bir hecalıdır.",
  ["Bayatı - yeddi hecalı dördlük", "Qoşma - yeddi hecalı dördlük",
   "Bayatı - on bir hecalı dördlük", "Atalar sözü - dörd misralı şeir"],
  1, None, 3),
 ("Şifahi xalq ədəbiyyatı haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "Dastanlarda nəsrlə yanaşı nəzm parçaları da olur.",
  ["Dastanlar bütövlükdə nəsrlə söylənir",
   "Bayatı dörd misralı şeir formasıdır",
   "Ağı yas mərasimi ilə bağlıdır",
   "Holavar əkinçilik nəğməsidir"], 1, None, 3),
 ("Məhəbbət dastanı ilə qəhrəmanlıq dastanının əsas fərqi nədir?",
  "Birində eşq, digərində el və vətən uğrunda mübarizə əsasdır.",
  ["Birində eşq, digərində vətən uğrunda mübarizə",
   "Birində vətən uğrunda mübarizə, digərində eşq",
   "Biri nəzmlə, digəri bütövlükdə nəsrlə söylənir",
   "Birində nağılçı, digərində ozan iştirak edir"], 1, None, 3),
 ("Aşağıdakı «əsər - dastan növü» cütlüklərindən hansı doğrudur?",
  "«Aşıq Qərib» məhəbbət, «Koroğlu» isə qəhrəmanlıq dastanıdır.",
  ["«Aşıq Qərib» - məhəbbət dastanı", "«Koroğlu» - məhəbbət dastanı",
   "«Aşıq Qərib» - qəhrəmanlıq dastanı",
   "«Əsli və Kərəm» - qəhrəmanlıq dastanı"], 1, None, 3),
 ("Aşıqların eyni dastanı hər dəfə bir qədər fərqli söyləməsinin "
  "səbəbi nədir?",
  "Mətn yazıya köçürülmür, yaddaşda saxlanıb şifahi ötürülür.",
  ["Mətnin yaddaşda saxlanıb şifahi ötürülməsi",
   "Mətnin kitabda çap olunması",
   "Dastanların xarici dildə yazılması",
   "Musiqi alətinin vaxtaşırı dəyişməsi"], 1, None, 3),
 ("Aşağıdakı «nəğmə - məşğuliyyət» cütlüklərindən hansı düzgündür?",
  "Holavar əkinçilik, sayaçı sözü isə heyvandarlıq nəğməsidir.",
  ["Holavar - əkinçilik", "Sayaçı sözü - əkinçilik",
   "Holavar - heyvandarlıq", "Laylay - ovçuluq"], 1, None, 3),
 ("Xalq ədəbiyyatı janrları haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "Lətifə qısa, gülüş doğuran janrdır, qəhrəmanlıq əsəri deyil.",
  ["Lətifə uzun süjetli qəhrəmanlıq əsəridir",
   "Tapmaca əşyanı əlamətinə görə tanıdır",
   "Atalar sözü qısa hikmətli ifadədir",
   "Laylay körpə üçün oxunur"], 1, None, 3),
 ("Bayatı ilə qoşmanın misrasındakı heca sayı arasında neçə heca fərq var?",
  "Bayatı yeddi, qoşma on bir hecalıdır.",
  ["4 heca", "2 heca", "6 heca", "1 heca"], 1, None, 3),
 ("Aşağıdakı «obraz - əsər növü» cütlüklərindən hansı doğrudur?",
  "Dədə Qorqud oğuz eposunun, Molla Nəsrəddin lətifələrin obrazıdır.",
  ["Dədə Qorqud - oğuz eposu", "Molla Nəsrəddin - oğuz eposu",
   "Dədə Qorqud - lətifələr", "Koroğlu - məhəbbət dastanı"],
  1, None, 3),
 ("Nağılla dastan arasındakı əsas fərq nədir?",
  "Dastanda nəzm parçaları olur, nağıl isə bütövlükdə nəsrdir.",
  ["Dastanda nəzm olur, nağıl bütövlükdə nəsrdir",
   "Nağılda nəzm olur, dastan bütövlükdə nəsrdir",
   "Hər ikisi bütövlükdə nəzmlə söylənir",
   "Hər ikisi yazılı şəkildə yayılır"], 1, None, 3),
 ("Mərasim və əmək nəğmələrinin yaranmasının kökündə nə dayanır?",
  "Bu nəğmələr birbaşa əmək prosesinin özündən doğulmuşdur.",
  ["Əmək prosesinin özü", "Saray şeiri ənənəsi",
   "Yazılı ədəbiyyatın təsiri", "Qonşu ölkələrin təsiri"], 1, None, 3),
 ("Aşıq yaradıcılığı haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "Aşıq şeiri heca vəznindədir, əruz yazılı ədəbiyyatın vəznidir.",
  ["Aşıq şeiri əruz vəzninə əsaslanır",
   "Qoşma dörd misralı bənddən ibarətdir",
   "Aşığın əsas aləti sazdır",
   "Dastanlar aşıq repertuarındadır"], 1, None, 3)],

"edeb-10-dede-qorqud": [
 # ---- asan (4)
 ("«Kitabi-Dədə Qorqud» hansı xalqın eposudur?",
  "Epos oğuz türklərinin qəhrəmanlıq abidəsidir.",
  ["Oğuz türklərinin", "Ərəblərin", "Farsların", "Yunanların"],
  1, None, 1),
 ("«Kitabi-Dədə Qorqud» neçə boydan ibarətdir?",
  "Eposda on iki boy vardır.",
  ["12", "7", "20", "5"], 1, None, 1),
 ("Dədə Qorqud eposda kim kimi təsvir olunur?",
  "O, ad qoyan, məsləhət verən müdrik ozan və ağsaqqaldır.",
  ["Müdrik ozan və ağsaqqal", "Gənc döyüşçü", "Xarici ölkə elçisi",
   "Karvan taciri"], 1, None, 1),
 ("Eposun dili hansıdır?",
  "Epos oğuz türkcəsində yaranmışdır.",
  ["Oğuz türkcəsi", "Ərəb dili", "Fars dili", "Yunan dili"],
  1, None, 1),
 # ---- orta (15)
 ("Eposun neçə əlyazma nüsxəsi məlumdur?",
  "İki nüsxə məlumdur: Drezden və Vatikan nüsxələri.",
  ["İki", "Bir", "Beş", "On"], 1, None, 2),
 ("Vatikan nüsxəsində neçə boy var?",
  "Vatikan nüsxəsində altı boy vardır.",
  ["6", "12", "2", "9"], 1, None, 2),
 ("Boyların mətnindəki şeir parçaları hansı adla tanınır?",
  "Onlar soylama adlanır.",
  ["Soylama", "Qəzəl", "Rübai", "Qoşma"], 1, None, 2),
 ("«Salur Qazanın evinin yağmalandığı boy»da Qazanın həyat yoldaşı kimdir?",
  "Qazan xanın həyat yoldaşı Burla xatundur.",
  ["Burla xatun", "Nigar xanım", "Banuçiçək", "Selcan xatun"],
  1, None, 2),
 ("Həmin boyda Qazan xanın oğlunun adı nədir?",
  "Qazan xanın oğlu Uruzdur.",
  ["Uruz", "Beyrək", "Basat", "Səgrək"], 1, None, 2),
 ("Qazanın sürülərini düşməndən qoruyan obraz kimdir?",
  "Sürüləri Qaraca Çoban qoruyur.",
  ["Qaraca Çoban", "Dəli Domrul", "Qanturalı", "Yeynək"], 1, None, 2),
 ("Qaraca Çoban düşmənə qarşı hansı silahdan istifadə edir?",
  "O, sapandla daş atıb düşməni saxlayır.",
  ["Sapand", "Ox-kaman", "Qılınc", "Nizə"], 1, None, 2),
 ("Oğuz elinin xanlar xanı kimdir?",
  "Oğuzun xanlar xanı Bayandır xandır.",
  ["Bayandır xan", "Qazan xan", "Şöklü Məlik", "Dirsə xan"],
  1, None, 2),
 ("«Dirsə xan oğlu Buğac» boyunda oğlan hansı işə görə ad alır?",
  "O, meydanda buğanı öldürdüyü üçün Buğac adını alır.",
  ["Buğanı öldürdüyünə görə", "Ov quşu tutduğuna görə",
   "Qala aldığına görə", "İlk dəfə ata mindiyinə görə"], 1, None, 2),
 ("Təpəgözü məğlub edən qəhrəman kimdir?",
  "Təpəgözü Basat məğlub edir.",
  ["Basat", "Beyrək", "Uruz", "Yeynək"], 1, None, 2),
 ("Eposda qadın obrazları necə təsvir olunur?",
  "Onlar ata minən, ox atan, döyüşə qatılan igidlər kimi verilir.",
  ["Ata minib döyüşən igidlər kimi", "Yalnız ev işində",
   "Danışmayan obrazlar kimi", "Yad eldən gələnlər kimi"], 1, None, 2),
 ("«Kitabi-Dədə Qorqud»un 1300 illiyi hansı ildə qeyd olunmuşdur?",
  "Yubiley 2000-ci ildə qeyd olunmuşdur.",
  ["2000", "1990", "1975", "2010"], 1, None, 2),
 ("Eposun müqəddiməsində əsasən nədən danışılır?",
  "Dədə Qorqudun özündən və oğuz elinin adət-ənənəsindən.",
  ["Dədə Qorqud və oğuz adətlərindən", "Səfəvi dövlətindən",
   "Nizaminin həyatından", "Koroğlunun dəlilərindən"], 1, None, 2),
 ("«Dəli Domrul» boyunun əsas mövzusu nədir?",
  "İnsanın ölümlə üz-üzə gəlməsi və həyat sevgisidir.",
  ["Ölümlə üz-üzə gəlmək", "Toy mərasimi", "Ticarət səfəri",
   "Əkin işləri"], 1, None, 2),
 ("Boylarda oğuza hücum edən düşmən başçısı kimdir?",
  "Boylarda düşmən başçısı Şöklü Məlikdir.",
  ["Şöklü Məlik", "Bayandır xan", "Qaraca Çoban", "Dədə Qorqud"],
  1, None, 2),
 # ---- cetin (12)
 ("Aşağıdakı «boy - qəhrəman» cütlüklərindən hansı düzgündür?",
  "Təpəgözü Basat, buğanı isə Buğac məğlub edir.",
  ["Təpəgöz boyu - Basat", "Təpəgöz boyu - Beyrək",
   "Dəli Domrul boyu - Basat", "Buğac boyu - Uruz"], 1, None, 3),
 ("«Kitabi-Dədə Qorqud» haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "Epos oğuz türkcəsində yaranmışdır, fars dilində deyil.",
  ["Epos fars dilində yaranmışdır", "Epos on iki boydan ibarətdir",
   "Dədə Qorqud ad qoyan müdrikdir",
   "Boylarda nəzm parçaları vardır"], 1, None, 3),
 ("Drezden və Vatikan nüsxələri arasındakı fərq nədir?",
  "Drezden nüsxəsində on iki, Vatikan nüsxəsində altı boy var.",
  ["Birində on iki, digərində altı boy var",
   "Birində altı, digərində iki boy var",
   "Hər ikisində on iki boy var",
   "Biri nəzmlə, digəri nəsrlə yazılıb"], 1, None, 3),
 ("Qazan xanın evinin yağmalanmasına şərait yaradan səbəb nədir?",
  "Qazan uzun ova getmiş, ev qorunmasız qalmışdı.",
  ["Qazanın uzun ova getməsi", "Bayandır xanla mübahisəsi",
   "Burla xatunun qonaqlığa getməsi",
   "Qaraca Çobanın sürünü itirməsi"], 1, None, 3),
 ("Aşağıdakı «obraz - rol» cütlüklərindən hansı doğrudur?",
  "Qaraca Çoban sürünü qoruyur, Şöklü Məlik isə düşmən başçısıdır.",
  ["Qaraca Çoban - sürünü qoruyan", "Şöklü Məlik - sürünü qoruyan",
   "Qaraca Çoban - oğuz xanı", "Uruz - düşmən başçısı"], 1, None, 3),
 ("«Kitabi-Dədə Qorqud» ilə «Koroğlu» dastanının ortaq cəhəti nədir?",
  "Hər ikisi qəhrəmanlıq mövzusunda xalq yaradıcılığı nümunəsidir.",
  ["Hər ikisi qəhrəmanlıq mövzusundadır",
   "Hər ikisi məhəbbət dastanıdır",
   "Hər ikisinin müəllifi bəllidir",
   "Hər ikisi fars dilində yaranıb"], 1, None, 3),
 ("Boyların məzmunu haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "«Dəli Domrul» boyu ölüm və həyat sevgisindən bəhs edir.",
  ["«Dəli Domrul» boyu toy mərasimindən bəhs edir",
   "«Basat» boyunda Təpəgöz məğlub edilir",
   "«Buğac» boyunda oğlan buğanı öldürür",
   "«Salur Qazan» boyunda ev yağmalanır"], 1, None, 3),
 ("«Salur Qazanın evinin yağmalandığı boy»da hadisələr necə sıralanır? "
  "(1 - düşmənin məğlub edilməsi, 2 - Qazanın ova getməsi, "
  "3 - evin yağmalanması)",
  "Əvvəlcə Qazan ova gedir, sonra ev yağmalanır, sonda düşmən məğlub olur.",
  ["2 - 3 - 1", "1 - 2 - 3", "3 - 2 - 1", "2 - 1 - 3"], 1, None, 3),
 ("Aşağıdakı «əsər - janr» cütlüklərindən hansı düzgündür?",
  "«Kitabi-Dədə Qorqud» epos, «Dəhnamə» isə poemadır.",
  ["«Kitabi-Dədə Qorqud» - epos", "«Kitabi-Dədə Qorqud» - qəzəl",
   "«Dəhnamə» - epos", "«Sığmazam» - epos"], 1, None, 3),
 ("Eposda qadın obrazlarının döyüşkən verilməsi nəyi göstərir?",
  "Oğuz cəmiyyətində qadının yüksək mövqeyini göstərir.",
  ["Qadının cəmiyyətdəki yüksək mövqeyini",
   "Kişi obrazlarının azlığını", "Ov ənənəsinin olmamasını",
   "Yazılı ədəbiyyatın güclü təsirini"], 1, None, 3),
 ("Dədə Qorqud və Bayandır xan haqqında hansı fikir doğrudur?",
  "Dədə Qorqud ozan-ağsaqqal, Bayandır xan isə xanlar xanıdır.",
  ["Biri ozan-ağsaqqal, digəri xanlar xanıdır",
   "Biri xanlar xanı, digəri düşmən başçısıdır",
   "Hər ikisi düşmən tərəfin obrazıdır",
   "Hər ikisi çoban obrazıdır"], 1, None, 3),
 ("Aşağıdakı «boy - mövzu» cütlüklərindən hansı doğrudur?",
  "«Dəli Domrul» ölüm və həyat, «Buğac» isə ad qoyma boyudur.",
  ["Dəli Domrul boyu - ölüm və həyat", "Buğac boyu - ölüm və həyat",
   "Dəli Domrul boyu - ad qoyma", "Təpəgöz boyu - toy mərasimi"],
  1, None, 3)],
}
SUALLAR.update(HISSE_1)

HISSE_2 = {
"edeb-10-nizami": [
 # ---- asan (4)
 ("Nizami Gəncəvi hansı şəhərdə yaşayıb-yaratmışdır?",
  "Şair bütün ömrünü Gəncədə keçirmişdir.",
  ["Gəncədə", "Şamaxıda", "Təbrizdə", "Şuşada"], 1, None, 1),
 ("Nizaminin beş poemadan ibarət külliyyatı necə adlanır?",
  "Beş poema «Xəmsə» adı altında birləşir.",
  ["«Xəmsə»", "«Divan»", "«Dəhnamə»", "«Hophopnamə»"], 1, None, 1),
 ("«İskəndərnamə» hansı janrdadır?",
  "«İskəndərnamə» poemadır.",
  ["Poema", "Roman", "Hekayə", "Dram"], 1, None, 1),
 ("Nizami əsərlərini hansı dildə yazmışdır?",
  "Şair əsərlərini fars dilində qələmə almışdır.",
  ["Fars dilində", "Ərəb dilində", "Yunan dilində", "Rus dilində"],
  1, None, 1),
 # ---- orta (15)
 ("«Xəmsə»yə daxil olan ilk poema hansıdır?",
  "«Sirlər xəzinəsi» «Xəmsə»nin ilk poemasıdır.",
  ["«Sirlər xəzinəsi»", "«Yeddi gözəl»", "«İskəndərnamə»",
   "«Leyli və Məcnun»"], 1, None, 2),
 ("«İskəndərnamə» neçə hissədən ibarətdir?",
  "Poema iki hissədən ibarətdir.",
  ["İki", "Üç", "Beş", "Yeddi"], 1, None, 2),
 ("«İskəndərnamə»nin hissələri necə adlanır?",
  "Hissələr «Şərəfnamə» və «İqbalnamə» adlanır.",
  ["«Şərəfnamə» və «İqbalnamə»", "«Divan» və «Xəmsə»",
   "«Dəhnamə» və «Nəsihətnamə»", "«Şahnamə» və «Xəmsə»"], 1, None, 2),
 ("«İskəndərnamə»də Bərdə hökmdarı kimdir?",
  "Bərdə hökmdarı Nüşabədir.",
  ["Nüşabə", "Şirin", "Leyli", "Məhinbanu"], 1, None, 2),
 ("Nüşabə obrazının səciyyəvi cəhəti nədir?",
  "O, ağıllı və müdrik qadın hökmdar kimi verilir.",
  ["Ağıllı və müdrik qadın hökmdar", "Zalım hökmdar",
   "Sadə kəndli qadın", "Yad ölkə elçisi"], 1, None, 2),
 ("«İskəndərnamə»də İskəndər obrazı hansı mərhələlərdən keçir?",
  "O, əvvəlcə fateh, sonra alim-hökmdar, sonda peyğəmbər kimi verilir.",
  ["Fateh, alim, peyğəmbər", "Tacir, əsgər, çoban",
   "Şair, rəssam, memar", "Aşiq, dərviş, tacir"], 1, None, 2),
 ("Nizami yaradıcılığında hansı ideya aparıcıdır?",
  "Ədalətli hökmdar və ədalətli cəmiyyət ideyası aparıcıdır.",
  ["Ədalətli hökmdar və cəmiyyət", "Var-dövlət toplamaq",
   "Döyüş qənimətinin bölgüsü", "Səyahət macəraları"], 1, None, 2),
 ("«Xosrov və Şirin» poemasında dağı yaran aşiq obrazı kimdir?",
  "Bu obraz Fərhaddır.",
  ["Fərhad", "İskəndər", "Məcnun", "Bəhram"], 1, None, 2),
 ("«Yeddi gözəl» poemasının mərkəzində hansı hökmdar dayanır?",
  "Poemanın mərkəzində Bəhram obrazı dayanır.",
  ["Bəhram", "Xosrov", "İskəndər", "Qeys"], 1, None, 2),
 ("Nizaminin saraya bağlanmamasının səbəbi nə ilə izah olunur?",
  "Şair yaradıcılıq müstəqilliyini qorumaq istəyirdi.",
  ["Yaradıcılıq müstəqilliyini qorumaq", "Uzaq ölkədə yaşaması",
   "Saray dilini bilməməsi", "Səfər çətinliyi"], 1, None, 2),
 ("Nizamidən sonra beş poema yazmaq ənənəsi necə adlanır?",
  "Bu ənənə xəmsəçilik adlanır.",
  ["Xəmsəçilik", "Divançılıq", "Dastançılıq", "Aşıqlıq"], 1, None, 2),
 ("Nizami hansı əsrdə yaşamışdır?",
  "Şair XII əsrdə yaşamışdır.",
  ["XII əsrdə", "IX əsrdə", "XV əsrdə", "XVIII əsrdə"], 1, None, 2),
 ("«Sirlər xəzinəsi» hansı səciyyə daşıyır?",
  "Poema didaktik-fəlsəfi səciyyəlidir.",
  ["Didaktik-fəlsəfi", "Sırf məhəbbət", "Sənədli-tarixi", "Satirik"],
  1, None, 2),
 ("«Leyli və Məcnun» poemasında aşiqin əsl adı nədir?",
  "Aşiqin əsl adı Qeysdir.",
  ["Qeys", "Fərhad", "Bəhram", "Xosrov"], 1, None, 2),
 ("İskəndər uzaq səfərlərində əsasən nəyi axtarır?",
  "O, həqiqəti və kamil cəmiyyəti axtarır.",
  ["Həqiqət və kamil cəmiyyət", "Yalnız döyüş qəniməti",
   "Uzun ömür iksiri", "Yeni ticarət yolu"], 1, None, 2),
 # ---- cetin (12)
 ("Nizaminin üç poeması «Xəmsə»dəki sıra ilə necə düzülür? "
  "(1 - «İskəndərnamə», 2 - «Sirlər xəzinəsi», 3 - «Xosrov və Şirin»)",
  "«Sirlər xəzinəsi» birinci, «Xosrov və Şirin» ikinci, «İskəndərnamə» "
  "isə sonuncu poemadır.",
  ["2 - 3 - 1", "1 - 2 - 3", "3 - 2 - 1", "2 - 1 - 3"], 1, None, 3),
 ("Aşağıdakı «poema - qəhrəman» cütlüklərindən hansı düzgündür?",
  "«Yeddi gözəl»in mərkəzində Bəhram, «İskəndərnamə»də İskəndər dayanır.",
  ["«Yeddi gözəl» - Bəhram", "«Yeddi gözəl» - İskəndər",
   "«İskəndərnamə» - Bəhram", "«Xosrov və Şirin» - Qeys"], 1, None, 3),
 ("Nizami haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "«Xəmsə» beş poemadan ibarətdir.",
  ["«Xəmsə» dörd poemadan ibarətdir", "Nizami Gəncədə yaşamışdır",
   "«İskəndərnamə» iki hissəlidir", "Nüşabə Bərdə hökmdarıdır"],
  1, None, 3),
 ("«İskəndərnamə»nin iki hissəsi arasındakı fərq nədir?",
  "Birində fateh, digərində müdrik və peyğəmbər İskəndər verilir.",
  ["Birində fateh, digərində müdrik İskəndər",
   "Birində müdrik, digərində uşaqlıq illəri",
   "Hər ikisində eyni hadisələr təkrarlanır",
   "Biri nəzmlə, digəri nəsrlə yazılıb"], 1, None, 3),
 ("Nizaminin saray şairi olmaqdan uzaq durması yaradıcılığına necə təsir etdi?",
  "Fikir müstəqilliyini və hökmdarlara tənqidi baxışını qorumasına imkan verdi.",
  ["Fikir müstəqilliyini qorudu", "Əsərlərinin sayını azaltdı",
   "Onu tarixi mövzudan uzaqlaşdırdı", "Dilini xalq dilindən ayırdı"],
  1, None, 3),
 ("Nizaminin poemaları üzrə «obraz - əsər» cütlüyü hansı doğrudur?",
  "Nüşabə «İskəndərnamə»nin, Fərhad «Xosrov və Şirin»in obrazıdır.",
  ["Nüşabə - «İskəndərnamə»", "Nüşabə - «Yeddi gözəl»",
   "Fərhad - «İskəndərnamə»", "Bəhram - «Leyli və Məcnun»"],
  1, None, 3),
 ("Nizami və Füzulinin «Leyli və Məcnun» əsərləri arasındakı əsas fərq nədir?",
  "Nizaminin poeması fars, Füzulininki isə Azərbaycan dilindədir.",
  ["Biri fars, digəri Azərbaycan dilindədir",
   "Biri Azərbaycan, digəri ərəb dilindədir",
   "Hər ikisi eyni dildə yazılıb", "Biri poema, digəri dramdır"],
  1, None, 3),
 ("Nizaminin əsərləri haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "«Dəhnamə» Şah İsmayıl Xətayinin əsəridir.",
  ["«Dəhnamə» Nizaminin poemasıdır",
   "«Yeddi gözəl» Nizaminin poemasıdır",
   "«Sirlər xəzinəsi» ona məxsusdur",
   "«Xosrov və Şirin» «Xəmsə»yə daxildir"], 1, None, 3),
 ("Aşağıdakı «əsər - əsas ideya» cütlüklərindən hansı düzgündür?",
  "«İskəndərnamə»də ədalətli cəmiyyət axtarışı əsas yer tutur.",
  ["«İskəndərnamə» - ədalətli cəmiyyət axtarışı",
   "«İskəndərnamə» - tacir sərgüzəşti",
   "«Leyli və Məcnun» - ədalətli cəmiyyət axtarışı",
   "«Sirlər xəzinəsi» - döyüş salnaməsi"], 1, None, 3),
 ("Nizaminin İskəndəri peyğəmbərlik mərtəbəsinə qaldırmasının səbəbi nədir?",
  "Şair tarixi şəxsiyyət deyil, ideal insan obrazı yaratmaq istəyirdi.",
  ["İdeal insan obrazı yaratmaq istəyi",
   "Tarixi mənbələri dəqiq təkrarlamaq",
   "Saray sifarişini yerinə yetirmək",
   "Yunan ədəbiyyatını tərcümə etmək"], 1, None, 3),
 ("Üç şair yaşadıqları dövrün ardıcıllığı ilə necə düzülür? "
  "(1 - Nəsimi, 2 - Füzuli, 3 - Nizami)",
  "Nizami XII, Nəsimi XIV-XV, Füzuli isə XVI əsrdə yaşamışdır.",
  ["3 - 1 - 2", "1 - 2 - 3", "2 - 3 - 1", "1 - 3 - 2"], 1, None, 3),
 ("Nizami və Xətayi haqqında hansı fikir doğrudur?",
  "Nizami fars dilində, Xətayi isə ana dilində yazmışdır.",
  ["Biri farsca, digəri ana dilində yazmışdır",
   "Biri ana dilində, digəri ərəbcə yazmışdır",
   "Hər ikisi ana dilində yazmışdır",
   "Hər ikisi ərəb dilində yazmışdır"], 1, None, 3)],

"edeb-10-nesimi-xetayi": [
 # ---- asan (4)
 ("«Sığmazam» qəzəlinin müəllifi kimdir?",
  "Qəzəlin müəllifi İmadəddin Nəsimidir.",
  ["İmadəddin Nəsimi", "Şah İsmayıl Xətayi", "Məhəmməd Füzuli",
   "Nizami Gəncəvi"], 1, None, 1),
 ("Şah İsmayıl Xətayi hansı dövlətin banisidir?",
  "O, Səfəvi dövlətinin banisidir.",
  ["Səfəvi dövlətinin", "Qaraqoyunlu dövlətinin",
   "Şirvanşahlar dövlətinin", "Atabəylər dövlətinin"], 1, None, 1),
 ("«Dəhnamə» əsərinin müəllifi kimdir?",
  "«Dəhnamə» Şah İsmayıl Xətayinin poemasıdır.",
  ["Şah İsmayıl Xətayi", "İmadəddin Nəsimi", "Nizami Gəncəvi",
   "Molla Pənah Vaqif"], 1, None, 1),
 ("Nəsiminin şeirləri hansı vəzndədir?",
  "Nəsimi əruz vəznində yazmışdır.",
  ["Əruz vəznində", "Heca vəznində", "Sərbəst şeirdə", "Ağ şeirdə"],
  1, None, 1),
 # ---- orta (15)
 ("Nəsimi hansı təlimin ardıcılı olmuşdur?",
  "O, hürufilik təliminin ardıcılı idi.",
  ["Hürufiliyin", "Nəqşibəndiliyin", "Mövləviliyin", "Bektaşiliyin"],
  1, None, 2),
 ("Hürufilik təliminin banisi kimdir?",
  "Təlimin banisi Fəzlullah Nəimidir.",
  ["Fəzlullah Nəimi", "Şah İsmayıl", "Nizami Gəncəvi", "Əhməd Yəsəvi"],
  1, None, 2),
 ("Nəsimi harada edam olunmuşdur?",
  "Şair Hələb şəhərində edam olunmuşdur.",
  ["Hələbdə", "Bağdadda", "Təbrizdə", "Şamaxıda"], 1, None, 2),
 ("Nəsimi neçə dildə divan yaratmışdır?",
  "O, Azərbaycan, fars və ərəb dillərində divan yaratmışdır.",
  ["Üç dildə", "Bir dildə", "İki dildə", "Beş dildə"], 1, None, 2),
 ("«Sığmazam» qəzəlində şair nəyi tərənnüm edir?",
  "İnsanın böyüklüyünü və kainata sığmayan mənəvi gücünü.",
  ["İnsanın böyüklüyünü", "Var-dövləti", "Saray həyatını",
   "Ov səhnələrini"], 1, None, 2),
 ("Şah İsmayıl Xətayi hansı ildə Səfəvi dövlətinin əsasını qoymuşdur?",
  "Səfəvi dövləti 1501-ci ildə qurulmuşdur.",
  ["1501", "1405", "1600", "1747"], 1, None, 2),
 ("Xətayinin dövlətinin paytaxtı hansı şəhər idi?",
  "Paytaxt Təbriz idi.",
  ["Təbriz", "Bakı", "Gəncə", "Şamaxı"], 1, None, 2),
 ("«Dəhnamə» sözünün mənası nədir?",
  "«Dəhnamə» on məktub deməkdir.",
  ["On məktub", "Beş xəzinə", "Yeddi gözəl", "Üç nəsihət"], 1, None, 2),
 ("«Dəhnamə» ədəbiyyat tarixində nə ilə əlamətdardır?",
  "Ana dilində yazılmış ilk məhəbbət poemalarındandır.",
  ["Ana dilində ilk məhəbbət poemalarındandır", "İlk satirik poemadır",
   "İlk tarixi romandır", "İlk dram əsəridir"], 1, None, 2),
 ("Xətayi hansı vəznlərdə yazmışdır?",
  "O, həm əruz, həm də heca vəznində yazmışdır.",
  ["Həm əruz, həm heca vəznində", "Ancaq əruz vəznində",
   "Ancaq sərbəst şeirdə", "Ancaq nəsrlə"], 1, None, 2),
 ("Xətayinin müraciət etdiyi xalq şeiri formaları hansılardır?",
  "O, qoşma və gəraylı formalarında da yazmışdır.",
  ["Qoşma və gəraylı", "Sonet və rübai", "Qəsidə və mərsiyə",
   "Tapmaca və yanıltmac"], 1, None, 2),
 ("Nəsimi hansı şəhərdə doğulmuşdur?",
  "Şair Şamaxıda doğulmuşdur.",
  ["Şamaxıda", "Gəncədə", "Təbrizdə", "Bakıda"], 1, None, 2),
 ("Nəsiminin şeirlərində insanın ilahi ilə vəhdəti fikri necə ifadə olunur?",
  "Bu fikir «ənəlhəq» ifadəsi ilə verilir.",
  ["«Ənəlhəq» ifadəsi ilə", "Döyüş çağırışı ilə",
   "Ticarət qaydası ilə", "Təbiət təsviri ilə"], 1, None, 2),
 ("Şah İsmayıl şeirlərini hansı təxəllüslə yazmışdır?",
  "O, Xətayi təxəllüsü ilə yazmışdır.",
  ["Xətayi", "Füzuli", "Nəsimi", "Vaqif"], 1, None, 2),
 ("Nəsimi yaradıcılığının əsas mövzusu nədir?",
  "İnsan və onun mənəvi azadlığıdır.",
  ["İnsan və mənəvi azadlıq", "Saray mərasimləri",
   "Ticarət yolları", "Ov ənənəsi"], 1, None, 2),
 # ---- cetin (12)
 ("Aşağıdakı «şair - əsər» cütlüklərindən hansı düzgündür?",
  "«Sığmazam» Nəsiminin, «Dəhnamə» isə Xətayinin əsəridir.",
  ["Nəsimi - «Sığmazam»", "Xətayi - «Sığmazam»",
   "Nəsimi - «Dəhnamə»", "Nizami - «Dəhnamə»"], 1, None, 3),
 ("Nəsimi haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "Şair Hələbdə edam olunmuşdur, Bağdadda deyil.",
  ["Nəsimi Bağdadda edam olunmuşdur",
   "Nəsimi hürufilik təliminin ardıcılı idi",
   "«Sığmazam» onun qəzəlidir",
   "O, üç dildə divan yaratmışdır"], 1, None, 3),
 ("Nəsimi ilə Xətayinin yaradıcılığındakı əsas fərq nədir?",
  "Xətayi əruzla yanaşı heca vəzninə də müraciət etmişdir.",
  ["Xətayi heca vəzninə də müraciət etmişdir",
   "Nəsimi heca vəznində divan yaratmışdır",
   "Hər ikisi eyni vəzndə yazmışdır",
   "Xətayi əsərlərini fars dilində yazmışdır"], 1, None, 3),
 ("Nəsiminin edam olunmasının səbəbi nə idi?",
  "Onun yaydığı hürufilik təlimi dövrün rəsmi dairələrində küfr sayılırdı.",
  ["Hürufilik təliminin küfr sayılması", "Saraya vergi verməməsi",
   "Yad dövlətlə ticarət etməsi",
   "Şeirlərini fars dilində yazması"], 1, None, 3),
 ("Aşağıdakı üç hadisə zaman ardıcıllığı ilə necə düzülür? "
  "(1 - Səfəvi dövlətinin qurulması, 2 - Nəsiminin edamı, "
  "3 - Nəsiminin doğulması)",
  "Nəsimi 1369-cu ildə doğulub, 1417-ci ildə edam olunub, Səfəvi dövləti "
  "isə 1501-ci ildə qurulub.",
  ["3 - 2 - 1", "1 - 2 - 3", "2 - 3 - 1", "3 - 1 - 2"], 1, None, 3),
 ("Aşağıdakı «şəxs - fəaliyyət» cütlüklərindən hansı doğrudur?",
  "Xətayi həm şair, həm dövlət başçısı olmuşdur.",
  ["Xətayi - şair və dövlət başçısı",
   "Nəsimi - şair və dövlət başçısı",
   "Xətayi - hürufiliyin banisi",
   "Fəzlullah Nəimi - Səfəvi hökmdarı"], 1, None, 3),
 ("Nəsimi və Xətayinin doğulduğu yerlər haqqında hansı fikir doğrudur?",
  "Nəsimi Şamaxıda, Xətayi isə Ərdəbildə doğulmuşdur.",
  ["Nəsimi Şamaxıda, Xətayi Ərdəbildə",
   "Nəsimi Ərdəbildə, Xətayi Şamaxıda",
   "Nəsimi Təbrizdə, Xətayi Şamaxıda",
   "Nəsimi Ərdəbildə, Xətayi Təbrizdə"], 1, None, 3),
 ("Xətayi haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "«Dəhnamə» ana dilində - Azərbaycan dilində yazılmışdır.",
  ["«Dəhnamə» fars dilində yazılmışdır",
   "Xətayi Səfəvi dövlətinin banisidir",
   "«Dəhnamə» on məktubdan ibarətdir",
   "O, qoşma və gəraylı yazmışdır"], 1, None, 3),
 ("Nəsimi və Xətayinin əsərləri üzrə «əsər - janr» cütlüyü hansı doğrudur?",
  "«Dəhnamə» poema, «Sığmazam» isə qəzəldir.",
  ["«Dəhnamə» - poema", "«Sığmazam» - poema", "«Dəhnamə» - qəzəl",
   "«Sığmazam» - dastan"], 1, None, 3),
 ("Xətayinin ana dilində yazmasının ədəbiyyat tarixi üçün əhəmiyyəti nədir?",
  "Ana dilli şeir dövlət səviyyəsində dəstək qazanıb gücləndi.",
  ["Ana dilli şeirin güclənməsi", "Fars şeirinin yayılması",
   "Ərəb dilinin geniş öyrənilməsi",
   "Tərcümə ənənəsinin başlanması"], 1, None, 3),
 ("Aşağıdakı «əsər - yazıldığı dil» cütlüklərindən hansı doğrudur?",
  "«Dəhnamə» Azərbaycan, «Xəmsə» isə fars dilindədir.",
  ["«Dəhnamə» - Azərbaycan dili", "«Xəmsə» - Azərbaycan dili",
   "«Dəhnamə» - ərəb dili", "«İskəndərnamə» - Azərbaycan dili"],
  1, None, 3),
 ("Nizami və Nəsiminin yaşadığı dövr haqqında hansı fikir doğrudur?",
  "Nizami XII, Nəsimi isə XIV-XV əsrdə yaşamışdır.",
  ["Nizami XII, Nəsimi XIV-XV əsrdə", "Nəsimi XII, Nizami XIV-XV əsrdə",
   "Hər ikisi XII əsrdə yaşamışdır",
   "Hər ikisi XV əsrdə yaşamışdır"], 1, None, 3)],
}
SUALLAR.update(HISSE_2)

HISSE_3 = {
"edeb-10-fuzuli": [
 # ---- asan (4)
 ("Azərbaycan dilində «Leyli və Məcnun» poemasının müəllifi kimdir?",
  "Ana dilində bu poemanı Məhəmməd Füzuli yazmışdır.",
  ["Məhəmməd Füzuli", "Nizami Gəncəvi", "İmadəddin Nəsimi",
   "Şah İsmayıl Xətayi"], 1, None, 1),
 ("Füzuli neçə dildə divan yaratmışdır?",
  "Şair Azərbaycan, fars və ərəb dillərində divan yaratmışdır.",
  ["Üç dildə", "İki dildə", "Dörd dildə", "Bir dildə"], 1, None, 1),
 ("Füzuli yaradıcılığının mərkəzində hansı mövzu dayanır?",
  "Şairin yaradıcılığının mərkəzində eşq və məhəbbət dayanır.",
  ["Eşq və məhəbbət", "Ov və səyahət", "Ticarət işləri",
   "Memarlıq sənəti"], 1, None, 1),
 ("«Şikayətnamə» hansı formada yazılmışdır?",
  "«Şikayətnamə» nəsrlə yazılmışdır.",
  ["Nəsrlə", "Qəzəl formasında", "Qoşma formasında",
   "Dastan formasında"], 1, None, 1),
 # ---- orta (15)
 ("Füzulinin poemasında Məcnuna kömək etməyə çalışan obraz kimdir?",
  "Nofəl Məcnuna kömək etməyə çalışan obrazdır.",
  ["Nofəl", "İbn Səlam", "Zeyd", "Bəhram"], 1, None, 2),
 ("Leylini ailəsi kimə ərə verir?",
  "Leyli İbn Səlama ərə verilir.",
  ["İbn Səlam", "Nofəl", "Qeys", "Zeyd"], 1, None, 2),
 ("«Məni candan usandırdı» qəzəlinin rədifi hansıdır?",
  "Qəzəlin rədifi «cananım mənim»dir.",
  ["«cananım mənim»", "«gözüm mənim»", "«yarım mənim»",
   "«dostum mənim»"], 1, None, 2),
 ("«Şikayətnamə»də şair kimi tənqid edir?",
  "Əsərdə rüşvətxor məmurlar və süründürməçilik tənqid olunur.",
  ["Rüşvətxor məmurları", "Kənd əməkçilərini", "Aşıq sənətkarlarını",
   "Karvan tacirlərini"], 1, None, 2),
 ("Füzulinin «Hədiqətüs-süəda» əsəri hansı formadadır?",
  "Bu, nəsrlə yazılmış əsərdir.",
  ["Nəsr əsəridir", "Qəzəllər toplusudur", "Dastandır", "Dramdır"],
  1, None, 2),
 ("Füzuli hansı bölgədə yaşayıb-yaratmışdır?",
  "Şair Kərbəla və Bağdad bölgəsində yaşamışdır.",
  ["Kərbəla və Bağdad bölgəsində", "Gəncə və Bərdədə",
   "Şamaxı və Bakıda", "Təbriz və Ərdəbildə"], 1, None, 2),
 ("Füzulinin «Leyli və Məcnun» poeması hansı ənənənin davamıdır?",
  "Nizamidən gələn xəmsəçilik və məsnəvi ənənəsinin davamıdır.",
  ["Xəmsəçilik və məsnəvi ənənəsinin", "Aşıq dastanı ənənəsinin",
   "Xalq lətifəsi ənənəsinin", "Salnamə yazma ənənəsinin"], 1, None, 2),
 ("Füzulinin poemasında eşq necə şərh olunur?",
  "Dünyəvi eşq tədricən ilahi eşq səviyyəsinə yüksəlir.",
  ["Dünyəvi eşqdən ilahi eşqə yüksəlir", "Sadə məişət hadisəsi kimi",
   "Ticarət razılaşması kimi", "Döyüş səbəbi kimi"], 1, None, 2),
 ("Üzeyir Hacıbəyli hansı operanı Füzulinin sözləri əsasında yazmışdır?",
  "Bəstəkar «Leyli və Məcnun» operasını yazmışdır.",
  ["«Leyli və Məcnun»", "«Koroğlu»", "«Arşın mal alan»",
   "«O olmasın, bu olsun»"], 1, None, 2),
 ("Həmin opera ədəbiyyat və musiqi tarixində nə ilə əlamətdardır?",
  "O, Şərqdə yazılmış ilk operadır.",
  ["Şərqdə ilk opera olması", "İlk balet olması",
   "İlk kinofilm olması", "İlk xalq mahnısı olması"], 1, None, 2),
 ("Füzuli hansı əsrdə yaşamışdır?",
  "Şair XVI əsrdə yaşamışdır.",
  ["XVI əsrdə", "XII əsrdə", "XIX əsrdə", "XIV əsrdə"], 1, None, 2),
 ("«Bəngü Badə» əsəri hansı səciyyə daşıyır?",
  "Əsər alleqorik səciyyəlidir.",
  ["Alleqorik", "Sənədli", "Tarixi salnamə", "Elmi-praktik"],
  1, None, 2),
 ("Füzulinin ana dilində yazdığı şeirlərin dili haqqında nə demək olar?",
  "Ana dilində yüksək bədii səviyyəli, obrazlı dil yaratmışdır.",
  ["Yüksək bədii səviyyəli obrazlı dil", "Yalnız ərəb sözlərindən ibarət",
   "Sadə gündəlik danışıq dili", "Tərcümə dilinin izləri"], 1, None, 2),
 ("Məcnunun çöllərə düşməsinin səbəbi nədir?",
  "O, Leylidən ayrı salındığı üçün ağlını itirib çöllərə düşür.",
  ["Leylidən ayrı salınması", "Ticarətdə uğursuzluğu",
   "Döyüşdə məğlub olması", "Ailəsinin köçüb getməsi"], 1, None, 2),
 ("Poemanın sonunda aşiqlərin taleyi necə olur?",
  "Hər ikisi həlak olur, eşqləri isə əbədiləşir.",
  ["Hər ikisi həlak olur", "Evlənib xoşbəxt olurlar",
   "Ayrı ölkələrə köçürlər", "Bir-birini unudurlar"], 1, None, 2),
 # ---- cetin (12)
 ("«Leyli və Məcnun» poemasında «obraz - rol» cütlüklərindən hansı düzgündür?",
  "Nofəl Məcnunun himayədarı, İbn Səlam isə Leylinin əridir.",
  ["Nofəl - Məcnunun himayədarı", "İbn Səlam - Məcnunun himayədarı",
   "Nofəl - Leylinin əri", "Zeyd - Leylinin atası"], 1, None, 3),
 ("Füzuli haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "«Xəmsə» Nizami Gəncəviyə məxsusdur.",
  ["«Xəmsə» külliyyatının müəllifidir",
   "«Şikayətnamə» onun nəsr əsəridir",
   "O, üç dildə divan yaratmışdır",
   "«Leyli və Məcnun» onun poemasıdır"], 1, None, 3),
 ("Füzulinin qəzəli ilə poeması arasındakı əsas fərq nədir?",
  "Qəzəl kiçik lirik formadır, poema isə süjetli iri əsərdir.",
  ["Biri kiçik lirik forma, digəri süjetli iri əsərdir",
   "Biri süjetli iri əsər, digəri kiçik lirik formadır",
   "Hər ikisi eyni həcmdə əsərlərdir",
   "Biri nəsrlə, digəri nəzmlə yazılır"], 1, None, 3),
 ("«Şikayətnamə»nin yazılmasına səbəb olan hadisə nə idi?",
  "Şairə təyin edilmiş vəzifə haqqının verilməməsi.",
  ["Vəzifə haqqının verilməməsi",
   "Kitabının çap olunmaması", "Vətənindən sürgün edilməsi",
   "Saraya dəvət olunmaması"], 1, None, 3),
 ("Füzulinin əsərləri üzrə «əsər - janr» cütlüklərindən hansı doğrudur?",
  "«Şikayətnamə» nəsr əsəri, «Leyli və Məcnun» isə poemadır.",
  ["«Şikayətnamə» - nəsr əsəri", "«Şikayətnamə» - qəzəl",
   "«Leyli və Məcnun» - nəsr əsəri", "«Bəngü Badə» - qəzəl"],
  1, None, 3),
 ("Aşağıdakı üç hadisə zaman ardıcıllığı ilə necə düzülür? "
  "(1 - Üzeyir Hacıbəylinin operası, 2 - Füzulinin poeması, "
  "3 - Nizaminin poeması)",
  "Nizami XII əsrdə, Füzuli XVI əsrdə yazmış, opera isə 1908-ci ildə "
  "səhnəyə qoyulmuşdur.",
  ["3 - 2 - 1", "1 - 2 - 3", "2 - 3 - 1", "2 - 1 - 3"], 1, None, 3),
 ("Füzuli və Nəsiminin yazdıqları dillər haqqında hansı fikir doğrudur?",
  "Hər ikisi Azərbaycan, fars və ərəb dillərində divan yaratmışdır.",
  ["Hər ikisi üç dildə divan yaratmışdır",
   "Füzuli iki, Nəsimi bir dildə yazmışdır",
   "Hər ikisi ana dilində yazmamışdır",
   "Füzuli ana dilində əsər yazmamışdır"], 1, None, 3),
 ("Poemanın məzmunu haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "Poemanın sonunda aşiqlər qovuşmur, hər ikisi həlak olur.",
  ["Sonda aşiqlər evlənib xoşbəxt olur",
   "Məcnunun əsl adı Qeysdir",
   "Nofəl Məcnuna kömək etməyə çalışır",
   "Poema əruz vəznində yazılıb"], 1, None, 3),
 ("Aşağıdakı «şair - yaşadığı əsr» cütlüklərindən hansı düzgündür?",
  "Füzuli XVI, Nizami XII, Nəsimi isə XIV-XV əsrdə yaşamışdır.",
  ["Füzuli - XVI əsr", "Füzuli - XII əsr", "Nizami - XVI əsr",
   "Nəsimi - XVI əsr"], 1, None, 3),
 ("Füzulinin poemasının Azərbaycan ədəbiyyatı üçün əhəmiyyəti nədir?",
  "Ana dilində yazılmış ilk kamil məhəbbət poemasıdır.",
  ["Ana dilində ilk məhəbbət poeması",
   "Ədəbiyyatda ilk satirik əsər", "Ədəbiyyatda ilk nəsr nümunəsi",
   "Ədəbiyyatda ilk dram əsəri"], 1, None, 3),
 ("Füzulinin əsərləri üzrə «əsər - müəllif» cütlüyü hansı doğrudur?",
  "«Hədiqətüs-süəda» Füzulinin, «Sığmazam» isə Nəsiminin əsəridir.",
  ["«Hədiqətüs-süəda» - Füzuli", "«Hədiqətüs-süəda» - Nəsimi",
   "«Sığmazam» - Füzuli", "«Dəhnamə» - Füzuli"], 1, None, 3),
 ("Aşağıdakı «əsər - bəstəkar» cütlüklərindən hansı düzgündür?",
  "«Leyli və Məcnun» operasını Üzeyir Hacıbəyli bəstələmişdir.",
  ["«Leyli və Məcnun» operası - Üzeyir Hacıbəyli",
   "«Leyli və Məcnun» operası - Müslüm Maqomayev",
   "«Koroğlu» operası - Məhəmməd Füzuli",
   "«Arşın mal alan» - Nizami Gəncəvi"], 1, None, 3)],

"edeb-10-koroglu-vaqif": [
 # ---- asan (4)
 ("«Koroğlu» dastanının baş qəhrəmanının əsl adı nədir?",
  "Koroğlunun əsl adı Rövşəndir.",
  ["Rövşən", "Eyvaz", "Həmzə", "Dəmirçioğlu"], 1, None, 1),
 ("Koroğlunun qərargahı necə adlanır?",
  "Koroğlunun qərargahı Çənlibeldir.",
  ["Çənlibel", "Şuşa", "Bərdə", "Ərzurum"], 1, None, 1),
 ("Molla Pənah Vaqif hansı vəznə üstünlük vermişdir?",
  "Vaqif heca vəznində yazmışdır.",
  ["Heca vəzninə", "Əruz vəzninə", "Sərbəst şeirə", "Ağ şeirə"],
  1, None, 1),
 ("«Pəri» şeirinin müəllifi kimdir?",
  "«Pəri» Molla Pənah Vaqifin qoşmasıdır.",
  ["Molla Pənah Vaqif", "Məhəmməd Füzuli", "İmadəddin Nəsimi",
   "Qasım bəy Zakir"], 1, None, 1),
 # ---- orta (15)
 ("Koroğlunun atasının adı nədir?",
  "Koroğlunun atası Alı kişidir.",
  ["Alı kişi", "Həsən xan", "Cəfər paşa", "Bəlli Əhməd"], 1, None, 2),
 ("Alı kişinin gözlərini kim kor etdirmişdir?",
  "Onun gözlərini Həsən xan kor etdirmişdir.",
  ["Həsən xan", "Cəfər paşa", "Eyvaz", "Həmzə"], 1, None, 2),
 ("Koroğlunun atlarının adları hansılardır?",
  "Onun atları Qırat və Düratdır.",
  ["Qırat və Dürat", "Ağqır və Boz", "Şəbdiz və Gülgün",
   "Düldül və Rəxş"], 1, None, 2),
 ("Koroğlunun həyat yoldaşının adı nədir?",
  "Koroğlunun həyat yoldaşı Nigar xanımdır.",
  ["Nigar xanım", "Burla xatun", "Leyli", "Pəri"], 1, None, 2),
 ("«Həmzənin Qıratı qaçırması» qolunda Həmzə hansı cildə girir?",
  "Həmzə çoban cildinə girərək Çənlibelə soxulur.",
  ["Çoban cildinə", "Tacir cildinə", "Dərviş cildinə", "Elçi cildinə"],
  1, None, 2),
 ("Koroğlu atını geri qaytarmaq üçün hansı cildə girir?",
  "Koroğlu aşıq cildinə girərək düşmən sarayına daxil olur.",
  ["Aşıq cildinə", "Tacir cildinə", "Çoban cildinə", "Əsgər cildinə"],
  1, None, 2),
 ("Koroğlu obrazının səciyyəvi cəhəti nədir?",
  "O, həm igid döyüşçü, həm də saz çalıb şeir deyən aşıqdır.",
  ["Həm igid, həm aşıq olması", "Karvan taciri olması",
   "Saray məmuru olması", "Din xadimi olması"], 1, None, 2),
 ("«Koroğlu» dastanındakı bölmələr necə adlanır?",
  "Dastanın bölmələri qol adlanır.",
  ["Qol", "Boy", "Bənd", "Fəsil"], 1, None, 2),
 ("Vaqif hansı xanlıqda vəzir olmuşdur?",
  "O, Qarabağ xanlığında vəzir olmuşdur.",
  ["Qarabağ xanlığında", "Şirvan xanlığında", "Quba xanlığında",
   "Naxçıvan xanlığında"], 1, None, 2),
 ("Vaqif hansı şəhərdə yaşayıb fəaliyyət göstərmişdir?",
  "Şair Şuşada yaşayıb fəaliyyət göstərmişdir.",
  ["Şuşada", "Gəncədə", "Şamaxıda", "Bakıda"], 1, None, 2),
 ("Vaqif şeirlərində gözəlliyi necə təsvir edir?",
  "O, real, yerli gözəlləri adları ilə təsvir edir.",
  ["Real, yerli gözəlləri", "Yalnız xəyali obrazları",
   "Mifik varlıqları", "Qədim hökmdarları"], 1, None, 2),
 ("Vaqifin hansı şairlə deyişməsi məşhurdur?",
  "Onun Molla Vəli Vidadi ilə deyişməsi məşhurdur.",
  ["Molla Vəli Vidadi ilə", "Qasım bəy Zakirlə", "Aşıq Ələsgərlə",
   "Seyid Əzim Şirvani ilə"], 1, None, 2),
 ("Vaqifin «Görmədim» əsəri hansı şeir formasındadır?",
  "«Görmədim» müxəmməs formasındadır.",
  ["Müxəmməs", "Qəzəl", "Rübai", "Sonet"], 1, None, 2),
 ("Vaqif Azərbaycan şeirində hansı istiqamətin banisi sayılır?",
  "O, realist şeirin banisi sayılır.",
  ["Realizmin", "Romantizmin", "Simvolizmin", "Klassisizmin"],
  1, None, 2),
 ("Vaqifin həyatı necə sona çatmışdır?",
  "Şair 1797-ci ildə Şuşada edam edilmişdir.",
  ["Şuşada edam edilmişdir", "Sürgündə vəfat etmişdir",
   "Uzun ömür sürüb Bakıda vəfat etmişdir",
   "Xaricə mühacirət etmişdir"], 1, None, 2),
 # ---- cetin (12)
 ("«Koroğlu» dastanında «obraz - rol» cütlüklərindən hansı düzgündür?",
  "Alı kişi Koroğlunun atası, Nigar xanım isə həyat yoldaşıdır.",
  ["Alı kişi - Koroğlunun atası", "Həsən xan - Koroğlunun atası",
   "Alı kişi - Koroğlunun dəlisi", "Nigar xanım - Koroğlunun anası"],
  1, None, 3),
 ("«Koroğlu» dastanı haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "Koroğlunun qərargahı Çənlibeldir.",
  ["Koroğlunun qərargahı Şuşadır", "Koroğlunun atı Qıratdır",
   "Dastan qollardan ibarətdir", "Koroğlu saz çalıb şeir deyir"],
  1, None, 3),
 ("«Koroğlu» dastanında qəhrəmanlıq nəyin uğrunda göstərilir?",
  "Zülmə qarşı, elin haqqı və ədalət uğrunda göstərilir.",
  ["Zülmə qarşı, elin haqqı uğrunda", "Şəxsi var-dövlət uğrunda",
   "Ticarət yolları uğrunda", "Saray vəzifəsi uğrunda"], 1, None, 3),
 ("Koroğlunun Həsən xana qarşı üsyanının səbəbi nədir?",
  "Həsən xan onun atası Alı kişinin gözlərini kor etdirmişdi.",
  ["Atasının gözlərinin kor edilməsi", "Atının oğurlanması",
   "Torpaqlarının əlindən alınması", "Dostunun sürgün edilməsi"],
  1, None, 3),
 ("Dastandakı üç hadisə zaman ardıcıllığı ilə necə düzülür? "
  "(1 - Çənlibelin qurulması, 2 - Qıratın oğurlanması, "
  "3 - Alı kişinin kor edilməsi)",
  "Əvvəlcə Alı kişi kor edilir, sonra Çənlibel qurulur, daha sonra "
  "Qırat oğurlanır.",
  ["3 - 1 - 2", "1 - 2 - 3", "2 - 1 - 3", "1 - 3 - 2"], 1, None, 3),
 ("Aşağıdakı «şəxs - vəzifə» cütlüklərindən hansı doğrudur?",
  "Vaqif Qarabağ xanlığında vəzir vəzifəsində olmuşdur.",
  ["Vaqif - Qarabağ xanlığının vəziri",
   "Vidadi - Qarabağ xanlığının vəziri",
   "Vaqif - Şirvan xanlığının vəziri",
   "Zakir - Qarabağ xanlığının vəziri"], 1, None, 3),
 ("Vaqif haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "Vaqif heca vəznində yazmışdır, əruzda deyil.",
  ["Vaqif əruz vəzninə üstünlük vermişdir",
   "Vaqif Şuşada yaşayıb fəaliyyət göstərmişdir",
   "«Pəri» onun qoşmasıdır",
   "O, realist şeirin banisi sayılır"], 1, None, 3),
 ("Vaqif və Füzulinin şeir vəzni haqqında hansı fikir doğrudur?",
  "Vaqif heca, Füzuli isə əruz vəznində yazmışdır.",
  ["Vaqif hecada, Füzuli əruzda yazmışdır",
   "Vaqif əruzda, Füzuli hecada yazmışdır",
   "Hər ikisi heca vəznində yazmışdır",
   "Hər ikisi əruz vəznində yazmışdır"], 1, None, 3),
 ("Vaqifin əsərləri üzrə «əsər - forma» cütlüyü hansı düzgündür?",
  "«Görmədim» müxəmməs, «Pəri» isə qoşmadır.",
  ["«Görmədim» - müxəmməs", "«Pəri» - müxəmməs",
   "«Görmədim» - qəzəl", "«Sığmazam» - qoşma"], 1, None, 3),
 ("Vaqif şeirinin xalq arasında geniş yayılmasının səbəbi nədir?",
  "Sadə xalq dili və heca vəzni onu hamıya anlaşıqlı edirdi.",
  ["Sadə xalq dili və heca vəzni", "Fars dilində yazılması",
   "Saray mühitinə bağlılığı", "Mürəkkəb əruz quruluşu"], 1, None, 3),
 ("Xalq yaradıcılığı haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "«Koroğlu» qəhrəmanlıq dastanıdır, məhəbbət dastanı deyil.",
  ["«Koroğlu» məhəbbət dastanıdır", "«Koroğlu» qollardan ibarətdir",
   "Nigar xanım dastanın obrazıdır", "Dəlilər Çənlibeldə toplaşır"],
  1, None, 3),
 ("Erkən yeni dövr əsərləri üzrə «əsər - növ» cütlüyü hansı doğrudur?",
  "«Koroğlu» qəhrəmanlıq dastanı, «Pəri» isə qoşmadır.",
  ["«Koroğlu» - qəhrəmanlıq dastanı", "«Koroğlu» - məhəbbət dastanı",
   "«Pəri» - qəhrəmanlıq dastanı", "«Dəhnamə» - qəhrəmanlıq dastanı"],
  1, None, 3)],
}
SUALLAR.update(HISSE_3)

HISSE_4 = {
"edeb-10-axundzade": [
 # ---- asan (4)
 ("Mirzə Fətəli Axundzadə Azərbaycan ədəbiyyatında hansı sahənin banisidir?",
  "O, Azərbaycan dramaturgiyasının banisidir.",
  ["Dramaturgiyanın", "Qəzəlin", "Dastanın", "Bayatının"], 1, None, 1),
 ("«Aldanmış kəvakib» hansı janrdadır?",
  "Əsər povest - nəsr əsəridir.",
  ["Povest", "Komediya", "Qəzəl", "Dastan"], 1, None, 1),
 ("Axundzadə neçə komediya yazmışdır?",
  "O, altı komediya yazmışdır.",
  ["Altı", "Üç", "On", "İki"], 1, None, 1),
 ("Mirzə Fətəli Axundzadə hansı şəhərdə doğulmuşdur?",
  "Yazıçı Nuxada - indiki Şəkidə doğulmuşdur.",
  ["Nuxada", "Şuşada", "Gəncədə", "Bakıda"], 1, None, 1),
 # ---- orta (15)
 ("Axundzadə ömrünün böyük hissəsini harada keçirmişdir?",
  "O, ömrünün böyük hissəsini Tiflisdə keçirmişdir.",
  ["Tiflisdə", "Təbrizdə", "İstanbulda", "Peterburqda"], 1, None, 2),
 ("«Müsyö Jordan» komediyasında müsyö Jordan kimdir?",
  "O, Azərbaycana gəlmiş fransız botanik alimidir.",
  ["Fransız botanik alimi", "Yerli tacir", "Saray münəccimi",
   "Rus zabiti"], 1, None, 2),
 ("«Müsyö Jordan» komediyasında cadugər obrazı kimdir?",
  "Cadugər obrazı dərviş Məstəli şahdır.",
  ["Dərviş Məstəli şah", "Hatəmxan ağa", "Şahbaz bəy", "Müsyö Jordan"],
  1, None, 2),
 ("Şahbaz bəy hara getmək istəyir?",
  "O, təhsil almaq üçün Parisə getmək istəyir.",
  ["Parisə", "Moskvaya", "Tehrana", "Bağdada"], 1, None, 2),
 ("Şəhrəbanu xanım Məstəli şahdan nə istəyir?",
  "O, Parisin xarab olmasını, səfərin baş tutmamasını istəyir.",
  ["Parisin xarab olmasını", "Yeni ev tikməsini",
   "Xəzinə tapmasını", "Xəstəni sağaltmasını"], 1, None, 2),
 ("«Müsyö Jordan»da tənqid olunan əsas nöqsan nədir?",
  "Cadugərliyə inam və cəhalət tənqid olunur.",
  ["Cadugərliyə inam və cəhalət", "Elmi tədqiqat işi",
   "Ticarətin genişlənməsi", "Səyahət həvəsi"], 1, None, 2),
 ("«Aldanmış kəvakib»də hadisələr hansı hökmdarın dövründə keçir?",
  "Hadisələr Şah Abbasın dövründə cərəyan edir.",
  ["Şah Abbasın", "Şah İsmayılın", "Nadir şahın",
   "Ağa Məhəmməd şahın"], 1, None, 2),
 ("«Aldanmış kəvakib»də müvəqqəti şah təyin olunan şəxs kimdir?",
  "Müvəqqəti şah təyin olunan Yusif Sərracdır.",
  ["Yusif Sərrac", "Hacı Qara", "Heydər bəy", "Məstəli şah"],
  1, None, 2),
 ("«Aldanmış kəvakib»də nə tənqid olunur?",
  "Ulduz falına, münəccimlərin sözünə kor-koranə inam tənqid olunur.",
  ["Ulduz falına inam", "Ticarətin genişlənməsi",
   "Təhsilin yayılması", "Əkinçilik üsulu"], 1, None, 2),
 ("Axundzadə hansı sahədə islahat layihəsi irəli sürmüşdür?",
  "O, əlifba islahatı layihəsi irəli sürmüşdür.",
  ["Əlifba islahatı", "Vergi islahatı", "Ordu islahatı",
   "Torpaq islahatı"], 1, None, 2),
 ("«Hacı Qara» komediyasının baş obrazı hansı tipi təmsil edir?",
  "O, xəsis tacir tipini təmsil edir.",
  ["Xəsis taciri", "Fədakar müəllimi", "İgid sərkərdəni",
   "Saray şairini"], 1, None, 2),
 ("Axundzadənin fəlsəfi əsəri hansıdır?",
  "«Kəmalüddövlə məktubları» onun fəlsəfi əsəridir.",
  ["«Kəmalüddövlə məktubları»", "«Şikayətnamə»",
   "«Aldanmış kəvakib»", "«Dəhnamə»"], 1, None, 2),
 ("Axundzadə komediyalarını hansı illərdə yazmışdır?",
  "Komediyalar 1850-1855-ci illərdə yazılmışdır.",
  ["1850-1855-ci illərdə", "1800-1810-cu illərdə",
   "1890-1900-cü illərdə", "1920-1930-cu illərdə"], 1, None, 2),
 ("Axundzadə Tiflisdə hansı vəzifədə çalışmışdır?",
  "O, canişinlik idarəsində tərcüməçi işləmişdir.",
  ["Tərcüməçi", "Həkim", "Memar", "Sərkərdə"], 1, None, 2),
 ("Axundzadənin komediyaları hansı ədəbi metoda aiddir?",
  "Onun komediyaları realizmə aiddir.",
  ["Realizmə", "Romantizmə", "Simvolizmə", "Sentimentalizmə"],
  1, None, 2),
 # ---- cetin (12)
 ("Axundzadənin əsərləri üzrə «əsər - janr» cütlüyü hansı düzgündür?",
  "«Aldanmış kəvakib» povest, «Hacı Qara» isə komediyadır.",
  ["«Aldanmış kəvakib» - povest", "«Aldanmış kəvakib» - komediya",
   "«Hacı Qara» - povest", "«Müsyö Jordan» - povest"], 1, None, 3),
 ("Mirzə Fətəli Axundzadə haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "O, altı komediya yazmışdır.",
  ["On beş komediya yazmışdır",
   "O, dramaturgiyanın banisi sayılır",
   "«Aldanmış kəvakib» onun povestidir",
   "Ömrünün çoxunu Tiflisdə keçirmişdir"], 1, None, 3),
 ("Axundzadənin komediyaları ilə «Aldanmış kəvakib» arasındakı fərq nədir?",
  "Komediyalar səhnə üçün, povest isə oxucu üçün yazılmışdır.",
  ["Biri səhnə üçün, digəri oxu üçün yazılıb",
   "Biri oxu üçün, digəri səhnə üçün yazılıb",
   "Hər ikisi səhnə əsəridir", "Hər ikisi mənzum əsərdir"],
  1, None, 3),
 ("Şəhrəbanu xanımın Məstəli şaha müraciətinin səbəbi nədir?",
  "O, qızının nişanlısının Parisə getməsinin qarşısını almaq istəyir.",
  ["Nişanlının Parisə getməsinin qarşısını almaq",
   "Ailəsinə var-dövlət qazandırmaq", "Xəstə qohumunu sağaltmaq",
   "Torpaq mübahisəsini həll etmək"], 1, None, 3),
 ("Aşağıdakı üç hadisə zaman ardıcıllığı ilə necə düzülür? "
  "(1 - komediyaların yazılması, 2 - Axundzadənin doğulması, "
  "3 - «Aldanmış kəvakib»in yazılması)",
  "Axundzadə 1812-ci ildə doğulub, komediyaları 1850-1855-ci illərdə, "
  "«Aldanmış kəvakib»i isə 1857-ci ildə yazıb.",
  ["2 - 1 - 3", "1 - 2 - 3", "3 - 2 - 1", "1 - 3 - 2"], 1, None, 3),
 ("Axundzadənin əsərləri üzrə «obraz - əsər» cütlüyü hansı doğrudur?",
  "Məstəli şah «Müsyö Jordan»ın, Yusif Sərrac «Aldanmış kəvakib»in obrazıdır.",
  ["Məstəli şah - «Müsyö Jordan»", "Məstəli şah - «Hacı Qara»",
   "Yusif Sərrac - «Müsyö Jordan»",
   "Hacı Qara - «Aldanmış kəvakib»"], 1, None, 3),
 ("XIX əsr əsərləri haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "«Hacı Qara» Axundzadənin komediyasıdır.",
  ["«Hacı Qara» Füzulinin əsəridir", "«Müsyö Jordan» komediyadır",
   "«Aldanmış kəvakib» nəsr əsəridir",
   "«Kəmalüddövlə məktubları» fəlsəfi əsərdir"], 1, None, 3),
 ("Axundzadə və Vaqifin ədəbiyyat tarixindəki rolu haqqında hansı fikir doğrudur?",
  "Vaqif realist şeirin, Axundzadə isə dramaturgiyanın banisidir.",
  ["Biri realist şeirin, digəri dramaturgiyanın banisidir",
   "Biri dramaturgiyanın, digəri qəzəlin banisidir",
   "Hər ikisi dramaturgiyanın banisidir",
   "Hər ikisi realist şeirin banisidir"], 1, None, 3),
 ("Axundzadənin əlifba islahatı təklifinin əsas məqsədi nə idi?",
  "Yazını sadələşdirib savadlanmanı asanlaşdırmaq idi.",
  ["Savadlanmanı asanlaşdırmaq", "Xarici ticarəti genişləndirmək",
   "Saray yazışmasını sadələşdirmək", "Şeir vəznini dəyişmək"],
  1, None, 3),
 ("Aşağıdakı «əsər - tənqid hədəfi» cütlüklərindən hansı düzgündür?",
  "«Aldanmış kəvakib» ulduz falına inamı, «Hacı Qara» isə xəsisliyi ifşa edir.",
  ["«Aldanmış kəvakib» - ulduz falına inam",
   "«Müsyö Jordan» - ulduz falına inam",
   "«Aldanmış kəvakib» - xəsislik", "«Hacı Qara» - cadugərlik"],
  1, None, 3),
 ("«Müsyö Jordan» komediyasında Parisin xarab olması necə izah olunur?",
  "Fransadakı inqilab xəbəri Məstəli şahın caduları ilə təsadüfən üst-üstə düşür.",
  ["İnqilabla üst-üstə düşən təsadüf kimi",
   "Məstəli şahın həqiqi caduları kimi",
   "Şahbaz bəyin uydurması kimi", "Hatəmxan ağanın qərarı kimi"],
  1, None, 3),
 ("Maarifçi realizm dövrü haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "Bu dövr XIX əsrdə formalaşmışdır.",
  ["Dövr XX əsrin ortalarında formalaşıb",
   "Axundzadə bu dövrün nümayəndəsidir",
   "Dövrün əsas ideyası maarifçilikdir",
   "«Əkinçi» qəzeti bu dövrdə çıxıb"], 1, None, 3)],

"edeb-10-maarifci": [
 # ---- asan (4)
 ("«Müsibəti-Fəxrəddin» əsərinin müəllifi kimdir?",
  "Əsərin müəllifi Nəcəf bəy Vəzirovdur.",
  ["Nəcəf bəy Vəzirov", "Qasım bəy Zakir", "Seyid Əzim Şirvani",
   "Aşıq Ələsgər"], 1, None, 1),
 ("«Müsibəti-Fəxrəddin» hansı janrdadır?",
  "Əsər faciədir - Azərbaycan ədəbiyyatında ilk faciə sayılır.",
  ["Faciə", "Komediya", "Poema", "Qəzəl"], 1, None, 1),
 ("Aşıq Ələsgər hansı sənətin nümayəndəsidir?",
  "O, aşıq sənətinin görkəmli nümayəndəsidir.",
  ["Aşıq sənətinin", "Saray şeirinin", "Dramaturgiyanın", "Nəsrin"],
  1, None, 1),
 ("İlk Azərbaycan dilli qəzet hansıdır?",
  "İlk Azərbaycan dilli qəzet «Əkinçi»dir.",
  ["«Əkinçi»", "«Molla Nəsrəddin»", "«Füyuzat»", "«Kaspi»"],
  1, None, 1),
 # ---- orta (15)
 ("«Əkinçi» qəzeti hansı ildə nəşrə başlamışdır?",
  "Qəzet 1875-ci ildə nəşrə başlamışdır.",
  ["1875", "1905", "1850", "1920"], 1, None, 2),
 ("«Əkinçi» qəzetinin naşiri kimdir?",
  "Qəzetin naşiri Həsən bəy Zərdabidir.",
  ["Həsən bəy Zərdabi", "Cəlil Məmmədquluzadə", "Əli bəy Hüseynzadə",
   "Nəcəf bəy Vəzirov"], 1, None, 2),
 ("Qasım bəy Zakir hansı ədəbi ənənəni davam etdirmişdir?",
  "O, Vaqifin realist şeir ənənəsini davam etdirmişdir.",
  ["Vaqif ənənəsini", "Nizami xəmsəçiliyini", "Nəsimi hürufiliyini",
   "Ozan-aşıq dastanı ənənəsini"], 1, None, 2),
 ("Qasım bəy Zakir hansı janrlarda daha güclü olmuşdur?",
  "O, satira və təmsil janrlarında güclü olmuşdur.",
  ["Satira və təmsildə", "Elmi traktatda", "Tarixi salnamədə",
   "Musiqili komediyada"], 1, None, 2),
 ("Qasım bəy Zakir kiminlə məktublaşmışdır?",
  "O, Mirzə Fətəli Axundzadə ilə məktublaşmışdır.",
  ["M.F.Axundzadə ilə", "Nizami Gəncəvi ilə",
   "Şah İsmayıl Xətayi ilə", "Məhəmməd Füzuli ilə"], 1, None, 2),
 ("Aşıq Ələsgər hansı mahalda doğulmuşdur?",
  "Aşıq Ələsgər Göyçə mahalında doğulmuşdur.",
  ["Göyçə mahalında", "Qarabağda", "Şirvanda", "Naxçıvanda"],
  1, None, 2),
 ("Aşıq Ələsgərin əsas şeir formaları hansılardır?",
  "O, qoşma, gəraylı və təcnis formalarında yazmışdır.",
  ["Qoşma, gəraylı, təcnis", "Qəzəl, qəsidə, rübai",
   "Sonet, ballada, elegiya", "Məsnəvi, mərsiyə, mədhiyyə"],
  1, None, 2),
 ("Seyid Əzim Şirvani hansı şəhərdə yaşamışdır?",
  "O, Şamaxıda yaşayıb-yaratmışdır.",
  ["Şamaxıda", "Şuşada", "Gəncədə", "Lənkəranda"], 1, None, 2),
 ("Seyid Əzim Şirvani hansı sahədə fəaliyyət göstərmişdir?",
  "O, maarifçilik və məktəb işi ilə məşğul olmuşdur.",
  ["Maarifçilik və məktəb işi", "Hərbi xidmət", "Karvan ticarəti",
   "Memarlıq"], 1, None, 2),
 ("Seyid Əzim Şirvani hansı qəzetlə əməkdaşlıq etmişdir?",
  "O, «Əkinçi» qəzeti ilə əməkdaşlıq etmişdir.",
  ["«Əkinçi» ilə", "«Molla Nəsrəddin» ilə", "«Füyuzat» ilə",
   "«Həyat» ilə"], 1, None, 2),
 ("«Müsibəti-Fəxrəddin»in baş qəhrəmanı hansı tipi təmsil edir?",
  "Fəxrəddin maarifçi gənc tipini təmsil edir.",
  ["Maarifçi gənci", "Xəsis taciri", "Saray münəccimini",
   "Karvanbaşını"], 1, None, 2),
 ("Fəxrəddinin faciəsinin bilavasitə səbəbi nədir?",
  "O, köhnə adət olan qan davasının qurbanı olur.",
  ["Qan davası", "Ticarət borcu", "Uzaq səfər", "Ağır xəstəlik"],
  1, None, 2),
 ("«Müsibəti-Fəxrəddin» hansı ildə yazılmışdır?",
  "Əsər 1896-cı ildə yazılmışdır.",
  ["1896", "1850", "1920", "1937"], 1, None, 2),
 ("Nəcəf bəy Vəzirov hansı şəhərdə doğulmuşdur?",
  "Yazıçı Şuşada doğulmuşdur.",
  ["Şuşada", "Şamaxıda", "Nuxada", "Gəncədə"], 1, None, 2),
 ("Maarifçi realizm dövrünün əsas ideyası nədir?",
  "Maarif və elm vasitəsilə cəmiyyəti islah etmək ideyasıdır.",
  ["Maarif və elmlə cəmiyyəti islah etmək", "Keçmişə qayıtmaq",
   "Xəyali aləmə qaçmaq", "Saray həyatını tərənnüm etmək"],
  1, None, 2),
 # ---- cetin (12)
 ("XIX əsr şairləri üzrə «əsər - müəllif» cütlüyü hansı düzgündür?",
  "«Dağlar» Aşıq Ələsgərin, «Guş qıl» isə Seyid Əzim Şirvaninindir.",
  ["«Dağlar» - Aşıq Ələsgər", "«Dağlar» - Qasım bəy Zakir",
   "«Guş qıl» - Aşıq Ələsgər",
   "«Müsibəti-Fəxrəddin» - Seyid Əzim Şirvani"], 1, None, 3),
 ("XIX əsr ədəbiyyatı haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "«Müsibəti-Fəxrəddin» faciədir, komediya deyil.",
  ["«Müsibəti-Fəxrəddin» komediyadır",
   "Aşıq Ələsgər Göyçədə doğulmuşdur",
   "«Əkinçi» 1875-ci ildə nəşrə başlayıb",
   "Zakir satira ustası sayılır"], 1, None, 3),
 ("«Müsibəti-Fəxrəddin»in faciə, «Hacı Qara»nın komediya sayılmasının "
  "səbəbi nədir?",
  "Birində qəhrəman həlak olur, digəri isə gülüş doğurur.",
  ["Birində qəhrəman həlak olur, digərində gülüş doğur",
   "Birində gülüş doğur, digərində qəhrəman həlak olur",
   "Biri nəzmlə, digəri nəsrlə yazılıb",
   "Biri poema, digəri hekayədir"], 1, None, 3),
 ("Fəxrəddinin ölümü ilə müəllif nəyi göstərmək istəyir?",
  "Köhnə adətlərin maarifçi qüvvəni məhv etdiyini göstərir.",
  ["Köhnə adətlərin maarifçini məhv etdiyini",
   "Ticarətin zərərli olduğunu", "Səyahətin təhlükəli olduğunu",
   "Təhsilin lazımsız olduğunu"], 1, None, 3),
 ("Aşağıdakı üç hadisə zaman ardıcıllığı ilə necə düzülür? "
  "(1 - «Əkinçi» qəzeti, 2 - «Müsibəti-Fəxrəddin», "
  "3 - «Molla Nəsrəddin» jurnalı)",
  "«Əkinçi» 1875-ci, «Müsibəti-Fəxrəddin» 1896-cı, «Molla Nəsrəddin» "
  "isə 1906-cı ildə çıxmışdır.",
  ["1 - 2 - 3", "2 - 1 - 3", "3 - 2 - 1", "1 - 3 - 2"], 1, None, 3),
 ("XIX əsr maarifçiləri üzrə «şəxs - fəaliyyət» cütlüyü hansı doğrudur?",
  "«Əkinçi»nin naşiri Həsən bəy Zərdabi olmuşdur.",
  ["Həsən bəy Zərdabi - «Əkinçi»nin naşiri",
   "Nəcəf bəy Vəzirov - «Əkinçi»nin naşiri",
   "Həsən bəy Zərdabi - aşıq sənətkarı",
   "Aşıq Ələsgər - qəzet naşiri"], 1, None, 3),
 ("XIX əsr sənətkarları haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "Aşıq şeiri heca vəznindədir, əruzda deyil.",
  ["Aşıq Ələsgər əruz vəznində yazmışdır",
   "Seyid Əzim Şirvani Şamaxıda yaşamışdır",
   "Zakir Vaqif ənənəsini davam etdirmişdir",
   "Vəzirov «Müsibəti-Fəxrəddin»i yazmışdır"], 1, None, 3),
 ("Aşıq Ələsgər və Seyid Əzim Şirvaninin yaradıcılığı arasındakı fərq nədir?",
  "Biri şifahi aşıq, digəri yazılı ədəbiyyat nümayəndəsidir.",
  ["Biri şifahi aşıq, digəri yazılı ədəbiyyat nümayəndəsidir",
   "Biri yazılı, digəri şifahi ənənəyə bağlıdır",
   "Hər ikisi şifahi aşıq ənənəsindəndir",
   "Hər ikisi dramaturgiya ilə məşğul olmuşdur"], 1, None, 3),
 ("XIX əsr əsərləri üzrə «əsər - janr» cütlüyü hansı düzgündür?",
  "«Müsibəti-Fəxrəddin» faciə, «Dağlar» isə qoşmadır.",
  ["«Müsibəti-Fəxrəddin» - faciə", "«Müsibəti-Fəxrəddin» - komediya",
   "«Dağlar» - faciə", "«Badi-səba» - faciə"], 1, None, 3),
 ("«Əkinçi» qəzetinin nəşrinin ədəbi həyat üçün əhəmiyyəti nədir?",
  "Maarifçi fikrin geniş yayılmasına yol açdı.",
  ["Maarifçi fikrin geniş yayılmasına yol açdı",
   "Saray şeirinin güclənməsinə səbəb oldu",
   "Aşıq sənətinin yaranmasına gətirdi",
   "Dastan janrının doğulmasına səbəb oldu"], 1, None, 3),
 ("Aşağıdakı «sənətkar - yaşadığı əsr» cütlüklərindən hansı doğrudur?",
  "Aşıq Ələsgər XIX-XX əsrlərdə yaşamışdır.",
  ["Aşıq Ələsgər - XIX-XX əsrlər", "Aşıq Ələsgər - XVI əsr",
   "Nizami Gəncəvi - XIX əsr", "Məhəmməd Füzuli - XIX əsr"],
  1, None, 3),
 ("Vəzirov və Axundzadənin dramaturgiyadakı rolu haqqında hansı fikir doğrudur?",
  "Axundzadə ilk komediyaları, Vəzirov isə ilk faciəni yazmışdır.",
  ["Biri ilk komediyaları, digəri ilk faciəni yazıb",
   "Biri ilk faciəni, digəri ilk povesti yazıb",
   "Hər ikisi ilk faciəni yazıb",
   "Hər ikisi ancaq komediya yazıb"], 1, None, 3)],
}
SUALLAR.update(HISSE_4)


def yoxla():
    n = xeta = 0
    butun = set()
    movzular = set(m for m, _r in MOVZULAR)
    for movzu, siyahi in SUALLAR.items():
        assert movzu in movzular, movzu
        if len(siyahi) != 31:
            print("XETA  %s: %d sual (31 olmalidir)" % (movzu, len(siyahi)))
            xeta += 1
        say = {1: 0, 2: 0, 3: 0}
        for body, why, opts, correct, expect, diff in siyahi:
            n += 1
            if diff in say:
                say[diff] += 1
            p = []
            if len(opts) != 4: p.append("variant sayi %d" % len(opts))
            if len(set(opts)) != len(opts): p.append("tekrar variant")
            if not (1 <= correct <= 4): p.append("correct")
            if not why: p.append("izah bos")
            if diff not in (1, 2, 3): p.append("cetinlik")
            if body in butun: p.append("eyni sual iki defe")
            butun.add(body)
            if expect is not None and opts[correct - 1] != expect:
                p.append("hesablanan «%s» != variant «%s»"
                         % (expect, opts[correct - 1]))
            for t in [body, why] + opts:
                if "'" in t: p.append("apostrof var")
                if any("Ѐ" <= ch <= "ӿ" for ch in t):
                    p.append("kiril herfi var")
            if p:
                xeta += 1
                print("XETA  %s: %s\n      %s" % (movzu, body[:60], "; ".join(p)))
        if say != BOLGU:
            print("XETA  %s: cetinlik bolgusu %s (gozlenilen %s)"
                  % (movzu, say, BOLGU))
            xeta += 1
    if len(SUALLAR) != len(MOVZULAR):
        print("XETA  movzu sayi %d (%d olmalidir)"
              % (len(SUALLAR), len(MOVZULAR)))
        xeta += 1
    #  ANS qaydasi: eyni duzgun cavab metni bank uzre 2 defeden cox olmasin
    cavab = {}
    for movzu, siyahi in SUALLAR.items():
        for body, why, opts, correct, _e, _d in siyahi:
            cavab.setdefault(opts[correct - 1], []).append(movzu)
    for c, yer in sorted(cavab.items()):
        if len(yer) > 2:
            print("XETA  duzgun cavab %d defe: «%s» (%s)"
                  % (len(yer), c, ", ".join(yer)))
            xeta += 1
    print("%d sual yoxlandı, %d xəta" % (n, xeta))
    return xeta == 0, n


def sql_yaz(n):
    q = lambda t: t.replace("'", "''")
    setirler = []
    for movzu, rub in MOVZULAR:
        pay = movzu.split("-")          # edeb, 11, tenqidi, realizm
        on = "edeb" + pay[1]
        qisa = "-".join(pay[2:])
        for i, (body, why, opts, correct, _e, diff) in enumerate(SUALLAR[movzu], 1):
            setirler.append(
                "('%s-%s#%d','edebiyyat','%s',%d,%d,'%s','%s',"
                "array['%s','%s','%s','%s'],%d)"
                % (on, qisa, i, movzu, diff, rub, q(body), q(why),
                   q(opts[0]), q(opts[1]), q(opts[2]), q(opts[3]), correct))
    with io.open(CIXIS, "w", encoding="utf-8") as f:
        f.write("""-- =====================================================================
--  59_bank_edebiyyat10.sql : EDEBIYYAT 10 BANKI
--
--  BU FAYL ELLE YAZILMIR - tools/edebiyyat10.py yaradir:
--      python3 tools/edebiyyat10.py
--
--  8 movzu x 31 sual = %d.  Her movzuda 4 asan + 15 orta + 12 cetin.
--  ext_key: edeb11-...
--  ON SERT: 58_movzular_edebiyyat9_10.sql islenmis olmalidir.
--  SONRA:   05_grants.sql yeniden islet.
-- =====================================================================

do $$
begin
  if not exists (select 1 from public.topics t join public.subjects s
      on s.id = t.subject_id
     where s.slug = 'edebiyyat' and t.slug in
           ('edeb-10-sifahi', 'edeb-10-maarifci')
     having count(*) = 2) then
    raise exception 'ONCE 58_movzular_edebiyyat9_10.sql isledilmelidir.';
  end if;
end $$;

delete from public.question_options o
 using public.questions q
 where o.question_id = q.id
   and q.owner_type = 'platform'
   and q.ext_key like 'edeb10-%%';

with d(ext, fenn, topic, diff, rub, body, why, opts, correct) as (values
%s
),
ins as (
  insert into public.questions
    (ext_key, owner_type, subject_id, level_id, topic_id, kind,
     body, explanation, difficulty, quarter, status)
  select d.ext, 'platform', s.id, tp.level_id, tp.id, 'single',
         d.body, d.why, d.diff, d.rub, 'published'
    from d
    join public.subjects s on s.slug = d.fenn
    join public.topics   tp on tp.subject_id = s.id and tp.slug = d.topic
  on conflict (ext_key) do update
    set body = excluded.body, explanation = excluded.explanation,
        difficulty = excluded.difficulty, quarter = excluded.quarter,
        topic_id = excluded.topic_id, level_id = excluded.level_id,
        subject_id = excluded.subject_id, status = 'published'
  returning id, ext_key
)
insert into public.question_options (question_id, ord, body, is_correct)
select ins.id, o.ord, o.txt, o.ord = d.correct
  from ins
  join d on d.ext = ins.ext_key,
  lateral unnest(d.opts) with ordinality as o(txt, ord);

do $$
declare n int; k int;
begin
  select count(*) into n from public.questions
   where owner_type = 'platform' and ext_key like 'edeb10-%%';
  if n <> %d then
    raise exception 'Edebiyyat 10 suallari: %d gozlenilirdi, %% tapildi', n;
  end if;
  select count(*) into k from public.questions q
   where q.ext_key like 'edeb10-%%'
     and ((select count(*) from public.question_options o
            where o.question_id = q.id) <> 4
       or (select count(*) from public.question_options o
            where o.question_id = q.id and o.is_correct) <> 1);
  if k > 0 then
    raise exception '%% sualda variant qurulusu sehvdir', k;
  end if;
  select count(distinct topic_id) into k from public.questions
   where ext_key like 'edeb10-%%';
  if k <> 8 then
    raise exception 'movzu sayi 8 deyil: %%', k;
  end if;
  --  Her movzuda en azi 12 cetin sual olmalidir ki, muellim BIR
  --  movzudan 10 sualliq cetin test yiga bilsin
  select count(*) into k from (
    select q.topic_id from public.questions q
     where q.ext_key like 'edeb10-%%' and q.difficulty = 3
     group by q.topic_id having count(*) < 12) z;
  if k > 0 then
    raise exception '%% movzuda 12-den az cetin sual var', k;
  end if;
  raise notice 'Edebiyyat 10 banki: %% sual, 8 movzu (her birinde 12 cetin).', n;
end $$;
""" % (n, ",\n".join(setirler), n, n))
    print("yazildi: %s" % CIXIS)


if __name__ == "__main__":
    ok, n = yoxla()
    if not ok:
        raise SystemExit(1)
    sql_yaz(n)
