#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Edebiyyat 9 banki -> db/60_bank_edebiyyat9.sql

    8 movzu x 31 sual = 248

Movzular 58_movzular_edebiyyat9_10.sql agacina uygundur (e-derslik
kitab id 883).  Dersliyin BEDII METNI ve calismalari goturulmur.

DIQQET:  11-ci sinifde eyni muellifler var, amma DERSLIK ONLARIN
BASKA ESERLERINI verir (Sabir Vurgun "Ananin oyudu", "Vagif" yox;
R.Rza "Cinar omru", "Rengler" yox; I.Sixli "Namerd gullesi",
"Deli Kur" yox).  Suallar hemin esere gore yazilir - eks halda
edeb9 ile edeb11 arasinda pg_trgm tekrari cixir.

CETINLIK BOLGUSU her movzuda:  4 asan + 15 orta + 12 cetin.

Isletmek:
    python3 tools/edebiyyat9.py
    python3 tools/cetinlik_analiz.py edeb9      # 0 vermelidir
"""
import io
import os

KOK = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CIXIS = os.path.join(KOK, "db", "60_bank_edebiyyat9.sql")

#  (movzu-slug, rub)
MOVZULAR = [
    ("edeb-9-milli-demokratik", 1),
    ("edeb-9-repressiya",       1),
    ("edeb-9-muharibe",         2),
    ("edeb-9-ozunuderk-seir",   2),
    ("edeb-9-ozunuderk-nesr",   3),
    ("edeb-9-mustaqillik",      3),
    ("edeb-9-cenub",            4),
    ("edeb-9-dunya",            4),
]

BOLGU = {1: 4, 2: 15, 3: 12}

SUALLAR = {}

HISSE_1 = {
"edeb-9-milli-demokratik": [
 # ---- asan (4)
 ("«Azərbaycan bayrağına» şeirinin müəllifi kimdir?",
  "Şeirin müəllifi Əhməd Cavaddır.",
  ["Əhməd Cavad", "Cəfər Cabbarlı", "Səməd Vurğun", "Mikayıl Müşfiq"],
  1, None, 1),
 ("Milli-demokratik hərəkat dövrü hansı illəri əhatə edir?",
  "Dövr XX əsrin əvvəlindən 1920-ci ilə qədəri əhatə edir.",
  ["XX əsrin əvvəli - 1920-ci il", "1941-1945-ci illər",
   "1960-1990-cı illər", "1991-ci ildən sonrakı illər"], 1, None, 1),
 ("Azərbaycan Xalq Cümhuriyyəti hansı ildə qurulmuşdur?",
  "Cümhuriyyət 1918-ci ildə qurulmuşdur.",
  ["1918", "1905", "1936", "1991"], 1, None, 1),
 ("«Ana» şeirinin müəllifi kimdir?",
  "Şeirin müəllifi Cəfər Cabbarlıdır.",
  ["Cəfər Cabbarlı", "Əhməd Cavad", "Abdulla Şaiq", "Rəsul Rza"],
  1, None, 1),
 # ---- orta (15)
 ("Əhməd Cavad hansı bölgədə doğulmuşdur?",
  "Şair Şəmkir bölgəsində doğulmuşdur.",
  ["Şəmkirdə", "Xızıda", "Bakıda", "Şuşada"], 1, None, 2),
 ("Əhməd Cavad hansı dövlət rəmzinin mətn müəllifidir?",
  "O, Azərbaycan Dövlət Himninin sözlərinin müəllifidir.",
  ["Dövlət Himninin", "Dövlət Gerbinin", "Dövlət möhürünün",
   "Dövlət nişanının"], 1, None, 2),
 ("Azərbaycan Dövlət Himninin musiqisi kimə məxsusdur?",
  "Himnin musiqisi Üzeyir Hacıbəyliyə məxsusdur.",
  ["Üzeyir Hacıbəyliyə", "Müslüm Maqomayevə", "Qara Qarayevə",
   "Fikrət Əmirova"], 1, None, 2),
 ("Cümhuriyyətin üçrəngli bayrağının rəngləri hansılardır?",
  "Bayraq mavi, qırmızı və yaşıl rənglərdən ibarətdir.",
  ["Mavi, qırmızı, yaşıl", "Ağ, mavi, qırmızı",
   "Qırmızı, sarı, yaşıl", "Yaşıl, ağ, qara"], 1, None, 2),
 ("«Azərbaycan bayrağına» şeirində hansı hiss aparıcıdır?",
  "Vətənpərvərlik və istiqlal sevinci aparıcıdır.",
  ["Vətənpərvərlik və istiqlal sevinci", "Təbiət təsviri həvəsi",
   "Ticarət marağı", "Yol çətinliyi duyğusu"], 1, None, 2),
 ("«Ana» şeirinin mövzusu nədir?",
  "Şeirin mövzusu ana məhəbbəti və fədakarlığıdır.",
  ["Ana məhəbbəti və fədakarlığı", "Dəniz səyahəti",
   "Şəhər memarlığı", "Elmi kəşflər"], 1, None, 2),
 ("Cəfər Cabbarlı hansı bölgədə doğulmuşdur?",
  "Yazıçı Xızıda doğulmuşdur.",
  ["Xızıda", "Şəmkirdə", "Şamaxıda", "Lənkəranda"], 1, None, 2),
 ("Əhməd Cavad hansı ildə repressiya qurbanı olmuşdur?",
  "Şair 1937-ci ildə repressiya qurbanı olmuşdur.",
  ["1937", "1920", "1945", "1956"], 1, None, 2),
 ("Milli-demokratik dövr ədəbiyyatının aparıcı ideyası nədir?",
  "Milli oyanış və istiqlal ideyasıdır.",
  ["Milli oyanış və istiqlal", "Sənaye tərəqqisi",
   "Dəniz ticarəti", "Saray həyatı"], 1, None, 2),
 ("«Çırpınırdı Qara dəniz» şeirinin müəllifi kimdir?",
  "Şeirin müəllifi Əhməd Cavaddır.",
  ["Əhməd Cavad", "Abdulla Şaiq", "Almas İldırım", "Süleyman Rüstəm"],
  1, None, 2),
 ("Azərbaycan Xalq Cümhuriyyəti neçə il yaşamışdır?",
  "Cümhuriyyət 1918-1920-ci illərdə, iki il yaşamışdır.",
  ["İki il", "On il", "Beş il", "Bir ay"], 1, None, 2),
 ("Bu dövr ədəbiyyatının əsas mövzusu nə idi?",
  "Vətən, bayraq və azadlıq mövzusu idi.",
  ["Vətən, bayraq və azadlıq", "Kosmos və texnika",
   "Dəniz macəraları", "Saray intriqaları"], 1, None, 2),
 ("Cəfər Cabbarlı sonrakı illərdə hansı sahədə tanındı?",
  "O, sonralar dramaturq kimi tanındı.",
  ["Dramaturgiyada", "Rəssamlıqda", "Musiqi bəstəkarlığında",
   "Memarlıqda"], 1, None, 2),
 ("Əhməd Cavadın şeirlərinin dili necədir?",
  "Dili sadə, xalq danışığına yaxındır.",
  ["Sadə və xalq dilinə yaxın", "Ağır ərəb-fars tərkibli",
   "Süni tərcümə dili", "Elmi termin dili"], 1, None, 2),
 ("Bu dövrün şairləri hansı bayrağı tərənnüm edirdilər?",
  "Onlar Cümhuriyyətin üçrəngli bayrağını tərənnüm edirdilər.",
  ["Cümhuriyyətin üçrəngli bayrağını", "Qırmızı bayrağı",
   "Ağ bayrağı", "Qara bayrağı"], 1, None, 2),
 # ---- cetin (12)
 ("Milli-demokratik dövr üzrə «əsər - müəllif» cütlüyü hansı düzgündür?",
  "«Azərbaycan bayrağına» Əhməd Cavadın, «Ana» isə Cabbarlının şeiridir.",
  ["«Azərbaycan bayrağına» - Əhməd Cavad",
   "«Azərbaycan bayrağına» - Cəfər Cabbarlı",
   "«Ana» - Əhməd Cavad", "«Həyat sevgisi» - Əhməd Cavad"],
  1, None, 3),
 ("Bu dövr haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "Cümhuriyyət 1918-ci ildə qurulmuşdur.",
  ["Cümhuriyyət 1936-cı ildə qurulmuşdur",
   "Əhməd Cavad himnin sözlərini yazmışdır",
   "Cümhuriyyətin bayrağı üçrənglidir",
   "Cəfər Cabbarlı Xızıda doğulmuşdur"], 1, None, 3),
 ("Aşağıdakı üç hadisə zaman ardıcıllığı ilə necə düzülür? "
  "(1 - Əhməd Cavadın repressiyası, 2 - Cümhuriyyətin qurulması, "
  "3 - Cümhuriyyətin süqutu)",
  "Cümhuriyyət 1918-ci ildə qurulub, 1920-ci ildə süqut edib, Əhməd "
  "Cavad isə 1937-ci ildə repressiyaya məruz qalıb.",
  ["2 - 3 - 1", "1 - 2 - 3", "3 - 2 - 1", "2 - 1 - 3"], 1, None, 3),
 ("Bu dövrdə bayraq mövzusunun ədəbiyyata gəlməsinin səbəbi nədir?",
  "Müstəqil dövlətin - Xalq Cümhuriyyətinin qurulmasıdır.",
  ["Müstəqil dövlətin qurulması", "Sənaye inqilabının başlanması",
   "Yeni əlifbaya keçilməsi", "Xarici ədəbiyyatın tərcüməsi"],
  1, None, 3),
 ("Dövlət himni üzrə «şəxs - rol» cütlüyü hansı doğrudur?",
  "Sözlər Əhməd Cavadın, musiqi Üzeyir Hacıbəylinindir.",
  ["Üzeyir Hacıbəyli - himnin bəstəkarı",
   "Əhməd Cavad - himnin bəstəkarı",
   "Üzeyir Hacıbəyli - himnin sözlərinin müəllifi",
   "Cəfər Cabbarlı - himnin bəstəkarı"], 1, None, 3),
 ("İki şairin doğulduğu yerlər haqqında hansı fikir doğrudur?",
  "Əhməd Cavad Şəmkirdə, Cəfər Cabbarlı isə Xızıda doğulmuşdur.",
  ["Əhməd Cavad Şəmkirdə, Cabbarlı Xızıda",
   "Əhməd Cavad Xızıda, Cabbarlı Şəmkirdə",
   "Əhməd Cavad Bakıda, Cabbarlı Şuşada",
   "Əhməd Cavad Şuşada, Cabbarlı Bakıda"], 1, None, 3),
 ("Dövrün sərhədləri haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "Milli-demokratik dövr XX əsrin əvvəlindən 1920-ci ilə qədərdir.",
  ["Bu dövr 1960-1990-cı illəri əhatə edir",
   "Dövrün ideyası milli oyanışdır",
   "Əhməd Cavad bu dövrün şairidir",
   "Cümhuriyyət bu dövrdə qurulmuşdur"], 1, None, 3),
 ("Əhməd Cavadın repressiyaya məruz qalması nə ilə bağlı idi?",
  "O, milli istiqlal mövzusunda yazdığı üçün təqib olunurdu.",
  ["Milli istiqlal mövzusunda yazması", "Xarici dildə yazması",
   "Dram janrına keçməsi", "Tərcümə ilə məşğul olması"], 1, None, 3),
 ("Bu dövr əsərləri üzrə «əsər - mövzu» cütlüyü hansı doğrudur?",
  "«Azərbaycan bayrağına» istiqlal, «Ana» isə ana məhəbbəti mövzusundadır.",
  ["«Azərbaycan bayrağına» - istiqlal", "«Ana» - istiqlal",
   "«Azərbaycan bayrağına» - ana məhəbbəti", "«Ana» - dəniz səfəri"],
  1, None, 3),
 ("Cümhuriyyətin süqutu ilə Əhməd Cavadın repressiyası arasında "
  "neçə il var?",
  "Cümhuriyyət 1920-ci ildə süqut edib, şair 1937-ci ildə repressiyaya "
  "məruz qalıb.",
  ["17 il", "7 il", "27 il", "2 il"], 1, None, 3),
 ("Milli-demokratik dövr ilə sovet dövrü ədəbiyyatının fərqi nədir?",
  "Birincidə milli istiqlal, ikincidə sinfi ideologiya önə çəkilirdi.",
  ["Milli-demokratik dövrdə istiqlal önə çəkilirdi",
   "Sovet dövründə istiqlal önə çəkilirdi",
   "Milli-demokratik dövrdə sinfi ideologiya əsas idi",
   "Hər iki dövrdə eyni mövzular işlənirdi"], 1, None, 3),
 ("Bayraq rəngləri üzrə «rəng - məna» cütlüyü hansı düzgündür?",
  "Mavi türkçülüyü, qırmızı müasirliyi, yaşıl isə islam mədəniyyətini "
  "bildirir.",
  ["Yaşıl - islam mədəniyyəti", "Mavi - islam mədəniyyəti",
   "Yaşıl - türkçülük", "Qırmızı - islam mədəniyyəti"], 1, None, 3)],

"edeb-9-repressiya": [
 # ---- asan (4)
 ("«Anabacı» hekayəsinin müəllifi kimdir?",
  "Hekayənin müəllifi Abdulla Şaiqdir.",
  ["Abdulla Şaiq", "Mikayıl Müşfiq", "Almas İldırım", "Seyid Hüseyn"],
  1, None, 1),
 ("Mikayıl Müşfiq hansı ədəbi növün nümayəndəsidir?",
  "Müşfiq poeziyanın görkəmli nümayəndəsidir.",
  ["Poeziyanın", "Dramaturgiyanın", "Ədəbi tənqidin", "Tərcümənin"],
  1, None, 1),
 ("«Zeybək qızı» əsərinin müəllifi kimdir?",
  "Əsərin müəllifi Yusif Vəzir Çəmənzəminlidir.",
  ["Yusif Vəzir Çəmənzəminli", "Abdulla Şaiq", "Mir Cəlal", "Anar"],
  1, None, 1),
 ("1937-ci il hadisələri ədəbiyyat tarixinə hansı adla düşmüşdür?",
  "Bu illər repressiya illəri kimi tanınır.",
  ["Repressiya illəri", "Maarifçilik illəri", "İntibah dövrü",
   "Mülayimləşmə dövrü"], 1, None, 1),
 # ---- orta (15)
 ("Bu mərhələ hansı illəri əhatə edir?",
  "Mərhələ 1920-1940-cı illəri əhatə edir.",
  ["1920-1940-cı illər", "1875-1900-cü illər", "1960-1990-cı illər",
   "1991-ci ildən sonrakı illər"], 1, None, 2),
 ("Abdulla Şaiq hansı sahədə xüsusilə tanınır?",
  "O, uşaq ədəbiyyatı və pedaqoji fəaliyyəti ilə tanınır.",
  ["Uşaq ədəbiyyatı və pedaqogika", "Hərbi tarix",
   "Kimya elmi", "Memarlıq sənəti"], 1, None, 2),
 ("«Anabacı» hansı janrdadır?",
  "«Anabacı» hekayədir.",
  ["Hekayə", "Poema", "Dram", "Qəzəl"], 1, None, 2),
 ("Aşağıdakılardan hansı Yusif Vəzir Çəmənzəminlinin romanıdır?",
  "«Qan içində» onun tarixi romanıdır.",
  ["«Qan içində»", "«Gələcək gün»", "«Ağ dəvə»", "«Məhşər»"],
  1, None, 2),
 ("Yusif Vəzir Çəmənzəminli hansı şəhərdə doğulmuşdur?",
  "Yazıçı Şuşada doğulmuşdur.",
  ["Şuşada", "Bakıda", "Gəncədə", "Naxçıvanda"], 1, None, 2),
 ("Almas İldırımın həyatında hansı hadisə həlledici olmuşdur?",
  "O, vətəni tərk edib mühacirətə getmişdir.",
  ["Vətəndən mühacirətə getməsi", "Uzun müddət nazir olması",
   "Xaricdə təhsil alması", "Ordu komandiri olması"], 1, None, 2),
 ("«Əsir Azərbaycanım» şeirində hansı hiss ifadə olunur?",
  "Vətən həsrəti və əsarət ağrısı ifadə olunur.",
  ["Vətən həsrəti və əsarət ağrısı", "Bayram sevinci",
   "Ov təəssüratı", "Elmi maraq"], 1, None, 2),
 ("Mikayıl Müşfiqin taleyi necə olmuşdur?",
  "Şair repressiyanın qurbanı olmuşdur.",
  ["Repressiyanın qurbanı olmuşdur", "Uzun ömür sürmüşdür",
   "Mühacirətdə yaşamışdır", "Cəbhədə həlak olmuşdur"], 1, None, 2),
 ("«Həyat sevgisi» şeirində şair nəyi tərənnüm edir?",
  "Şeirdə yaşamaq eşqi tərənnüm olunur.",
  ["Yaşamaq eşqini", "Müharibə qələbəsini", "Ticarət uğurunu",
   "Saray həyatını"], 1, None, 2),
 ("Aşağıdakılardan hansı Mikayıl Müşfiqin şeiridir?",
  "«Yenə o bağ olaydı» Müşfiqin məşhur şeiridir.",
  ["«Yenə o bağ olaydı»", "«Təbrizim»", "«Əsgər məktubu»",
   "«İstiqlal»"], 1, None, 2),
 ("Seyid Hüseyn ədəbiyyatın hansı sahəsində də fəaliyyət göstərmişdir?",
  "O, ədəbi tənqid sahəsində də çalışmışdır.",
  ["Ədəbi tənqiddə", "Hərbi işdə", "Tibb sahəsində", "Memarlıqda"],
  1, None, 2),
 ("Proletkult cərəyanı ədəbiyyatdan nəyi tələb edirdi?",
  "O, sinfi mübarizə mövzusunu ön plana çəkməyi tələb edirdi.",
  ["Sinfi mübarizə mövzusunu", "Klassik əruz vəznini",
   "Dini mövzuları", "Saray mədhiyyəsini"], 1, None, 2),
 ("Repressiya dövründə yazıçılara qarşı hansı ittiham irəli sürülürdü?",
  "Onlar əsasən millətçilikdə ittiham olunurdular.",
  ["Millətçilikdə ittiham olunurdular", "Vergidən yayınmada",
   "Ticarət pozuntusunda", "Torpaq mübahisəsində"], 1, None, 2),
 ("Çəmənzəminli Xalq Cümhuriyyəti dövründə hansı vəzifədə olmuşdur?",
  "O, Cümhuriyyətin Türkiyədəki səfiri olmuşdur.",
  ["Türkiyədə səfir", "Maliyyə naziri", "Ordu komandiri",
   "Universitet rektoru"], 1, None, 2),
 ("Bu dövrün ədəbiyyatında hansı ziddiyyət özünü göstərir?",
  "Rəsmi ideoloji tələblə şairin daxili dünyası arasındakı ziddiyyət.",
  ["Rəsmi tələblə daxili dünya arasında", "Şəhərlə kənd arasında",
   "Elmlə ticarət arasında", "Şeirlə musiqi arasında"], 1, None, 2),
 # ---- cetin (12)
 ("Bu dövr üzrə «əsər - müəllif» cütlüklərindən hansı düzgündür?",
  "«Həyat sevgisi» Müşfiqin, «Anabacı» isə Abdulla Şaiqin əsəridir.",
  ["«Həyat sevgisi» - Mikayıl Müşfiq",
   "«Həyat sevgisi» - Abdulla Şaiq",
   "«Anabacı» - Mikayıl Müşfiq",
   "«Zeybək qızı» - Almas İldırım"], 1, None, 3),
 ("Repressiya dövrü haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "«Anabacı» hekayədir, poema deyil.",
  ["«Anabacı» poemadır", "«Anabacı» Abdulla Şaiqin əsəridir",
   "Müşfiq repressiyanın qurbanı olmuşdur",
   "Çəmənzəminli Şuşada doğulmuşdur"], 1, None, 3),
 ("Aşağıdakı üç hadisə zaman ardıcıllığı ilə necə düzülür? "
  "(1 - Çəmənzəminlinin həyatının sonu, 2 - Cümhuriyyətin süqutu, "
  "3 - Müşfiqin repressiyaya məruz qalması)",
  "Cümhuriyyət 1920-ci ildə süquta uğrayıb, Müşfiq 1937-ci ildə həbs "
  "olunub, Çəmənzəminli isə 1943-cü ildə həyatını itirib.",
  ["2 - 3 - 1", "1 - 2 - 3", "3 - 1 - 2", "2 - 1 - 3"], 1, None, 3),
 ("Almas İldırımın mühacirətə getməsinin səbəbi nədir?",
  "Sovet rejiminin təzyiqi onu vətəni tərk etməyə məcbur etmişdir.",
  ["Sovet rejiminin təzyiqi", "Xaricdə təhsil almaq istəyi",
   "Ailə ticarətinin genişlənməsi", "Diplomatik təyinat alması"],
  1, None, 3),
 ("Bu dövr yazıçıları üzrə «şəxs - tale» cütlüyü hansı doğrudur?",
  "Almas İldırım mühacirətə getmiş, Müşfiq isə repressiyaya məruz qalmışdır.",
  ["Almas İldırım - mühacirət", "Mikayıl Müşfiq - mühacirət",
   "Almas İldırım - uzun saray xidməti", "Abdulla Şaiq - mühacirət"],
  1, None, 3),
 ("Müşfiq və Çəmənzəminlinin taleyi haqqında hansı fikir doğrudur?",
  "Hər ikisi repressiyanın qurbanı olmuşdur.",
  ["Hər ikisi repressiyanın qurbanı olmuşdur",
   "Hər ikisi mühacirətdə yaşamışdır",
   "Biri mühacir, digəri nazir olmuşdur",
   "Hər ikisi uzun ömür sürmüşdür"], 1, None, 3),
 ("Dövrün ədəbi mühiti haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "Proletkult klassik əruzu deyil, sinfi mübarizə mövzusunu tələb edirdi.",
  ["Proletkult klassik əruzu tələb edirdi",
   "Dövr 1920-1940-cı illəri əhatə edir",
   "1937-ci il repressiya ili sayılır",
   "Müşfiq bu dövrün şairidir"], 1, None, 3),
 ("Abdulla Şaiq və Mikayıl Müşfiqin yaradıcılığındakı fərq nədir?",
  "Şaiq uşaq ədəbiyyatı, Müşfiq isə lirik poeziya ilə tanınır.",
  ["Şaiq uşaq ədəbiyyatı, Müşfiq lirika ilə tanınır",
   "Şaiq lirika, Müşfiq uşaq ədəbiyyatı ilə tanınır",
   "Hər ikisi dramaturq kimi tanınır",
   "Hər ikisi ədəbi tənqidçi kimi tanınır"], 1, None, 3),
 ("Bu dövr əsərləri üzrə «əsər - janr» cütlüyü hansı düzgündür?",
  "«Zeybək qızı» hekayə, «Qan içində» isə romandır.",
  ["«Zeybək qızı» - hekayə", "«Zeybək qızı» - roman",
   "«Həyat sevgisi» - hekayə", "«Qan içində» - hekayə"], 1, None, 3),
 ("Bu dövrdə bir çox şairin əsərində ikili ovqatın yaranma səbəbi nədir?",
  "Rəsmi ideoloji tələblə daxili duyğunun toqquşması.",
  ["Rəsmi tələblə duyğunun toqquşması",
   "Xarici dilin güclü təsiri", "Şeir vəzninin dəyişməsi",
   "Nəşr sayının kəskin artması"], 1, None, 3),
 ("Bu dövr şəxsiyyətləri üzrə «şəxs - vəzifə» cütlüyü hansı doğrudur?",
  "Çəmənzəminli Cümhuriyyətin Türkiyədəki səfiri olmuşdur.",
  ["Çəmənzəminli - Cümhuriyyətin səfiri",
   "Mikayıl Müşfiq - Cümhuriyyətin səfiri",
   "Çəmənzəminli - maliyyə naziri",
   "Abdulla Şaiq - Cümhuriyyətin səfiri"], 1, None, 3),
 ("Repressiya dövrü ilə milli-demokratik dövr arasındakı əsas fərq nədir?",
  "Milli-demokratik dövrdə istiqlal açıq deyilirdi, sonrakı dövrdə isə yox.",
  ["Milli-demokratik dövrdə istiqlal açıq deyilirdi",
   "Repressiya dövründə istiqlal açıq deyilirdi",
   "Hər iki dövrdə eyni sərbəstlik vardı",
   "Hər iki dövrdə mövzu seçimi sərbəst idi"], 1, None, 3)],
}
SUALLAR.update(HISSE_1)

HISSE_2 = {
"edeb-9-muharibe": [
 # ---- asan (4)
 ("«Təbrizim» şeirinin müəllifi kimdir?",
  "Şeirin müəllifi Süleyman Rüstəmdir.",
  ["Süleyman Rüstəm", "Səməd Vurğun", "Mir Cəlal", "Mehdi Hüseyn"],
  1, None, 1),
 ("«Gələcək gün» romanının müəllifi kimdir?",
  "Romanın müəllifi Mirzə İbrahimovdur.",
  ["Mirzə İbrahimov", "Mir Cəlal", "Mehdi Hüseyn", "Süleyman Rüstəm"],
  1, None, 1),
 ("Müharibə və mülayimləşmə mərhələsi hansı illəri əhatə edir?",
  "Mərhələ 1941-1960-cı illəri əhatə edir.",
  ["1941-1960-cı illər", "1920-1940-cı illər", "1961-1990-cı illər",
   "1991-ci ildən sonrakı illər"], 1, None, 1),
 ("«Ananın öyüdü» şeirinin müəllifi kimdir?",
  "Şeirin müəllifi Səməd Vurğundur.",
  ["Səməd Vurğun", "Əhməd Cavad", "Rəsul Rza", "Əli Kərim"],
  1, None, 1),
 # ---- orta (15)
 ("«Ananın öyüdü» şeirində ana oğluna nə öyüd verir?",
  "Ana oğluna vətəni namusla qorumağı öyüd verir.",
  ["Vətəni namusla qorumağı", "Ticarətlə məşğul olmağı",
   "Uzaq şəhərə köçməyi", "Təhsildən əl çəkməyi"], 1, None, 2),
 ("«Təbrizim» şeirinin mövzusu nədir?",
  "Şeirin mövzusu Cənubi Azərbaycan həsrətidir.",
  ["Cənubi Azərbaycan həsrəti", "Şəhər tikintisi", "Dəniz səfəri",
   "Elmi kəşf"], 1, None, 2),
 ("Mir Cəlalın «Vətən yaraları» əsəri hansı janrdadır?",
  "Əsər hekayə janrındadır.",
  ["Hekayə", "Poema", "Dram", "Qəzəl"], 1, None, 2),
 ("«Gələcək gün» romanı hansı bölgənin hadisələrindən bəhs edir?",
  "Roman Cənubi Azərbaycandakı hadisələrdən bəhs edir.",
  ["Cənubi Azərbaycanın", "Qarabağın", "Şirvanın", "Naxçıvanın"],
  1, None, 2),
 ("«Nişan üzüyü» əsərinin müəllifi kimdir?",
  "Əsərin müəllifi Mehdi Hüseyndir.",
  ["Mehdi Hüseyn", "Mirzə İbrahimov", "Süleyman Rüstəm", "Anar"],
  1, None, 2),
 ("İkinci Dünya müharibəsi dövrü ədəbiyyatının əsas mövzusu nə idi?",
  "Vətənin müdafiəsi və qəhrəmanlıq mövzusu idi.",
  ["Vətənin müdafiəsi və qəhrəmanlıq", "Saray həyatı",
   "Ticarət qaydaları", "Kosmos səfərləri"], 1, None, 2),
 ("Süleyman Rüstəmin yaradıcılığında hansı mövzu geniş yer tutur?",
  "Onun yaradıcılığında Cənub mövzusu geniş yer tutur.",
  ["Cənub mövzusu", "Dəniz macərası", "Memarlıq", "Kimya elmi"],
  1, None, 2),
 ("«Vətən yaraları» hekayəsində müharibənin hansı tərəfi göstərilir?",
  "Arxa cəbhədəki insan taleləri göstərilir.",
  ["Arxa cəbhədəki insan taleləri", "Dəniz döyüşləri",
   "Kosmos yarışı", "Saray çəkişməsi"], 1, None, 2),
 ("Aşağıdakılardan hansı Mirzə İbrahimovun romanıdır?",
  "«Böyük dayaq» Mirzə İbrahimovun romanıdır.",
  ["«Böyük dayaq»", "«Ağ dəvə»", "«Məhşər»", "«Qan içində»"],
  1, None, 2),
 ("Mülayimləşmə dövrü nə vaxt başlamışdır?",
  "Mülayimləşmə 1950-ci illərin ortalarında başlamışdır.",
  ["1950-ci illərin ortalarında", "1920-ci illərin əvvəlində",
   "1990-cı illərin sonunda", "1900-cü illərin əvvəlində"], 1, None, 2),
 ("Müharibə illərində şeirin əsas vəzifəsi nə idi?",
  "Xalqa ruh yüksəkliyi və mübarizə əzmi vermək idi.",
  ["Xalqa ruh yüksəkliyi vermək", "Elmi biliyi yaymaq",
   "Ticarəti təbliğ etmək", "Memarlığı öyrətmək"], 1, None, 2),
 ("«Ananın öyüdü» şeirində ana obrazı nəyi təmsil edir?",
  "Ana obrazı vətəni və xalqı təmsil edir.",
  ["Vətəni və xalqı", "Şəhər həyatını", "Ticarət mühitini",
   "Saray adətini"], 1, None, 2),
 ("Bu dövrdə Cənub mövzusunun güclənməsinin səbəbi nədir?",
  "1945-1946-cı illərdəki milli hərəkat bu mövzunu gücləndirdi.",
  ["1945-1946-cı il hadisələri", "Sənaye tikintisi",
   "Yeni əlifbaya keçid", "Kosmos uçuşları"], 1, None, 2),
 ("Mehdi Hüseyn hansı ədəbi növdə çalışmışdır?",
  "O, əsasən nəsrdə çalışmışdır.",
  ["Nəsrdə", "Aşıq şeirində", "Bədii tərcümədə", "Uşaq şeirində"],
  1, None, 2),
 ("Şəxsiyyətə pərəstiş dövrü ədəbiyyata necə təsir etmişdir?",
  "Mövzu seçimini məhdudlaşdırmış, sərbəstliyi azaltmışdır.",
  ["Mövzu seçimini məhdudlaşdırmışdır",
   "Mövzunu tamamilə sərbəstləşdirmişdir",
   "Şeir janrını aradan qaldırmışdır",
   "Nəsr janrını qadağan etmişdir"], 1, None, 2),
 # ---- cetin (12)
 ("Müharibə dövrü üzrə «əsər - müəllif» cütlüyü hansı düzgündür?",
  "«Təbrizim» Süleyman Rüstəmin, «Ananın öyüdü» Səməd Vurğunundur.",
  ["«Təbrizim» - Süleyman Rüstəm", "«Təbrizim» - Səməd Vurğun",
   "«Ananın öyüdü» - Süleyman Rüstəm", "«Gələcək gün» - Mir Cəlal"],
  1, None, 3),
 ("Bu dövr əsərləri haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "«Gələcək gün» romandır, hekayə deyil.",
  ["«Gələcək gün» hekayədir",
   "«Gələcək gün» Mirzə İbrahimovundur",
   "«Vətən yaraları» Mir Cəlalındır",
   "«Təbrizim» Süleyman Rüstəmindir"], 1, None, 3),
 ("Aşağıdakı üç hadisə zaman ardıcıllığı ilə necə düzülür? "
  "(1 - müharibənin başlanması, 2 - mülayimləşmənin başlanması, "
  "3 - Cənubdakı milli hərəkat)",
  "Müharibə 1941-ci ildə başlayıb, Cənubdakı hərəkat 1945-1946-cı "
  "illərdə olub, mülayimləşmə isə 1950-ci illərin ortasında başlayıb.",
  ["1 - 3 - 2", "1 - 2 - 3", "2 - 3 - 1", "3 - 1 - 2"], 1, None, 3),
 ("Bu dövrdə Cənub mövzusunun ədəbiyyata güclü gəlişinin səbəbi nədir?",
  "1945-1946-cı illərdə Cənubi Azərbaycandakı milli hərəkat.",
  ["Cənubdakı milli hərəkat", "Sənaye tikintisinin genişlənməsi",
   "Yeni əlifbaya keçilməsi", "Kosmos uçuşlarının başlanması"],
  1, None, 3),
 ("Müharibə dövrü üzrə «əsər - janr» cütlüyü hansı doğrudur?",
  "«Gələcək gün» roman, «Vətən yaraları» isə hekayədir.",
  ["«Gələcək gün» - roman", "«Gələcək gün» - hekayə",
   "«Vətən yaraları» - roman", "«Təbrizim» - roman"], 1, None, 3),
 ("Səməd Vurğun və Süleyman Rüstəmin bu dövrdəki əsərlərinin ortaq "
  "cəhəti nədir?",
  "Hər ikisi şeir janrında yazılmışdır.",
  ["Hər ikisi şeir janrındadır", "Hər ikisi roman janrındadır",
   "Hər ikisi dram janrındadır", "Hər ikisi hekayə janrındadır"],
  1, None, 3),
 ("Müharibə dövrü haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "Bu mərhələ XX əsrin ortalarını - 1941-1960-cı illəri əhatə edir.",
  ["Bu mərhələ XIX əsri əhatə edir",
   "Müharibə mövzusu aparıcı olmuşdur",
   "Mehdi Hüseyn nasir kimi tanınır",
   "Mirzə İbrahimov «Gələcək gün»ü yazmışdır"], 1, None, 3),
 ("Müharibə dövrü ədəbiyyatının səciyyəvi cəhəti nədir?",
  "Publisistik pafos və mübarizəyə çağırış ruhu səciyyəvidir.",
  ["Publisistik pafos və çağırış ruhu", "Sakit məişət təsviri",
   "Elmi-fantastik süjet qurulusu", "Klassik əruz forması"],
  1, None, 3),
 ("Müharibə dövrü üzrə «əsər - mövzu» cütlüyü hansı düzgündür?",
  "«Təbrizim» Cənub həsrəti, «Vətən yaraları» isə arxa cəbhə mövzusundadır.",
  ["«Təbrizim» - Cənub həsrəti", "«Təbrizim» - arxa cəbhə",
   "«Vətən yaraları» - Cənub həsrəti",
   "«Ananın öyüdü» - dəniz səfəri"], 1, None, 3),
 ("«Ananın öyüdü» şeirində ana obrazının seçilməsinin səbəbi nədir?",
  "Şeirdə vətən ana ilə eyniləşdirilir, ona görə ana obrazı seçilib.",
  ["Vətənin ana ilə eyniləşdirilməsi",
   "Ailə mövzusunun dəbdə olması", "Uşaq ədəbiyyatına yaxınlıq",
   "Tarixi salnamə ənənəsi"], 1, None, 3),
 ("Bu dövr yazıçıları üzrə «yazıçı - janr» cütlüyü hansı doğrudur?",
  "Mir Cəlal hekayə ustası, Səməd Vurğun isə şairdir.",
  ["Mir Cəlal - hekayə ustası", "Süleyman Rüstəm - hekayə ustası",
   "Mir Cəlal - dramaturq", "Səməd Vurğun - nasir"], 1, None, 3),
 ("Mirzə İbrahimov və Mir Cəlalın bu dövrdəki əsərləri haqqında hansı "
  "fikir doğrudur?",
  "Mirzə İbrahimov roman, Mir Cəlal isə hekayə yazmışdır.",
  ["Mirzə İbrahimov roman, Mir Cəlal hekayə yazıb",
   "Mirzə İbrahimov hekayə, Mir Cəlal roman yazıb",
   "Hər ikisi poema janrında yazıb",
   "Hər ikisi dram janrında yazıb"], 1, None, 3)],

"edeb-9-ozunuderk-seir": [
 # ---- asan (4)
 ("«Əsgər məktubu» şeirinin müəllifi kimdir?",
  "Şeirin müəllifi Məmməd Arazdır.",
  ["Məmməd Araz", "Əli Kərim", "Rəsul Rza", "Balaş Azəroğlu"],
  1, None, 1),
 ("Bu mərhələ ədəbiyyat tarixində hansı adla tanınır?",
  "Mərhələ milli-mənəvi özünüdərk dövrü adlanır.",
  ["Milli-mənəvi özünüdərk dövrü", "Maarifçilik dövrü",
   "İntibah dövrü", "Repressiya dövrü"], 1, None, 1),
 ("«Çinar ömrü» əsərinin müəllifi kimdir?",
  "Əsərin müəllifi Rəsul Rzadır.",
  ["Rəsul Rza", "Məmməd Araz", "Əli Kərim", "Sabir Rüstəmxanlı"],
  1, None, 1),
 ("«Sağ ol, ana dilim!» şeirinin müəllifi kimdir?",
  "Şeirin müəllifi Sabir Rüstəmxanlıdır.",
  ["Sabir Rüstəmxanlı", "Əliağa Kürçaylı", "Balaş Azəroğlu",
   "Mehdi Hüseyn"], 1, None, 1),
 # ---- orta (15)
 ("Özünüdərk mərhələsi hansı illəri əhatə edir?",
  "Mərhələ 1961-1990-cı illəri əhatə edir.",
  ["1961-1990-cı illər", "1920-1940-cı illər", "1941-1960-cı illər",
   "1991-ci ildən sonrakı illər"], 1, None, 2),
 ("«Qaytar ana borcunu» şeirinin müəllifi kimdir?",
  "Şeirin müəllifi Əli Kərimdir.",
  ["Əli Kərim", "Məmməd Araz", "Rəsul Rza", "Əliağa Kürçaylı"],
  1, None, 2),
 ("«Şəhid meşə» şeirinin müəllifi kimdir?",
  "Şeirin müəllifi Əliağa Kürçaylıdır.",
  ["Əliağa Kürçaylı", "Əli Kərim", "Balaş Azəroğlu",
   "Sabir Rüstəmxanlı"], 1, None, 2),
 ("«Buludlar» şeirinin müəllifi kimdir?",
  "Şeirin müəllifi Balaş Azəroğludur.",
  ["Balaş Azəroğlu", "Məmməd Araz", "Süleyman Rüstəm", "Anar"],
  1, None, 2),
 ("Bu dövr poeziyasının aparıcı mövzusu nədir?",
  "Milli kimlik, ana dili və kökə bağlılıq mövzusudur.",
  ["Milli kimlik və ana dili", "Sənaye tikintisi",
   "Ticarət yolları", "Dəniz macərası"], 1, None, 2),
 ("«Sağ ol, ana dilim!» şeirində nə tərənnüm olunur?",
  "Şeirdə ana dilinə məhəbbət tərənnüm olunur.",
  ["Ana dilinə məhəbbət", "Şəhər memarlığı", "Dəniz gözəlliyi",
   "Ticarət uğuru"], 1, None, 2),
 ("«Qaytar ana borcunu» şeirində hansı fikir önə çəkilir?",
  "Övladın ana və vətən qarşısındakı borcu fikri önə çəkilir.",
  ["Övladın ana və vətən borcu", "Ticarət borcunun ödənişi",
   "Uzaq səfərin çətinliyi", "Elmi tədqiqatın nəticəsi"], 1, None, 2),
 ("Şair Məmməd Arazın vətəni hansı bölgədir?",
  "Şairin vətəni Naxçıvanın Şahbuz bölgəsidir.",
  ["Naxçıvanda", "Şəkidə", "Göyçayda", "Şuşada"], 1, None, 2),
 ("«Əsgər məktubu» şeirinin əsas motivi nədir?",
  "Vətən sevgisi və əsgər borcu motividir.",
  ["Vətən sevgisi və əsgər borcu", "Şəhər həyatının rahatlığı",
   "Ticarət səfəri təəssüratı", "Elmi mübahisə mövzusu"], 1, None, 2),
 ("Sabir Rüstəmxanlının məşhur nəsr əsəri hansıdır?",
  "«Ömür kitabı» onun məşhur nəsr əsəridir.",
  ["«Ömür kitabı»", "«Ağ dəvə»", "«Məhşər»", "«Böyük dayaq»"],
  1, None, 2),
 ("Bu dövrdə şeirin dili necə dəyişdi?",
  "Şeirin dili sadələşdi, canlı danışıq dilinə yaxınlaşdı.",
  ["Sadələşib danışıq dilinə yaxınlaşdı",
   "Ağır ərəb-fars tərkibli oldu", "Bütövlükdə əruza qayıtdı",
   "Tərcümə dilinə çevrildi"], 1, None, 2),
 ("«Çinar ömrü» əsərində çinar obrazı nəyi bildirir?",
  "Uzun ömrü və xalqın keçdiyi tarixi yolu bildirir.",
  ["Uzun ömrü və xalqın tarixini", "Ticarət yolunu",
   "Şəhər memarlığını", "Dəniz sahilini"], 1, None, 2),
 ("Əli Kərim hansı ədəbi növün nümayəndəsidir?",
  "Əli Kərim poeziyanın nümayəndəsidir.",
  ["Poeziyanın", "Dramaturgiyanın", "Ədəbi tənqidin",
   "Publisistikanın"], 1, None, 2),
 ("Məmməd Arazın şeirlərində hansı ovqat üstünlük təşkil edir?",
  "Vətənə bağlılıq və narahat düşüncə ovqatı üstünlük təşkil edir.",
  ["Vətənə bağlılıq və düşüncə", "Yumor və zarafat",
   "Quru elmi şərh", "Sənədli xronika"], 1, None, 2),
 ("Balaş Azəroğlunun yaradıcılığı hansı mövzu ilə bağlıdır?",
  "Onun yaradıcılığı Cənubi Azərbaycan mövzusu ilə bağlıdır.",
  ["Cənubi Azərbaycan mövzusu", "Kosmos mövzusu", "Dəniz mövzusu",
   "Memarlıq mövzusu"], 1, None, 2),
 # ---- cetin (12)
 ("Özünüdərk dövrü poeziyası üzrə «əsər - müəllif» cütlüyü hansı düzgündür?",
  "«Əsgər məktubu» Məmməd Arazın, «Çinar ömrü» Rəsul Rzanındır.",
  ["«Əsgər məktubu» - Məmməd Araz", "«Əsgər məktubu» - Əli Kərim",
   "«Çinar ömrü» - Məmməd Araz", "«Buludlar» - Əli Kərim"],
  1, None, 3),
 ("Bu dövr şairləri haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "«Sağ ol, ana dilim!» Sabir Rüstəmxanlınındır.",
  ["«Sağ ol, ana dilim!» Rəsul Rzanındır",
   "«Çinar ömrü» Rəsul Rzanındır",
   "«Əsgər məktubu» Məmməd Arazındır",
   "«Qaytar ana borcunu» Əli Kərimindir"], 1, None, 3),
 ("Ədəbi mərhələlər zaman ardıcıllığı ilə necə düzülür? "
  "(1 - repressiya dövrü, 2 - özünüdərk dövrü, 3 - müharibə dövrü)",
  "Repressiya dövrü 1920-1940, müharibə dövrü 1941-1960, özünüdərk "
  "dövrü isə 1961-1990-cı illəri əhatə edir.",
  ["1 - 3 - 2", "1 - 2 - 3", "2 - 3 - 1", "3 - 1 - 2"], 1, None, 3),
 ("1960-cı illərdən sonra milli mövzunun güclənməsinin səbəbi nədir?",
  "Cəmiyyətdə milli özünüdərkin oyanması bu mövzunu gücləndirdi.",
  ["Milli özünüdərkin oyanması", "Sənaye istehsalının artması",
   "Xarici ticarətin genişlənməsi", "Yeni əlifbaya keçilməsi"],
  1, None, 3),
 ("Bu dövr şairləri üzrə «şair - mövzu» cütlüyü hansı doğrudur?",
  "Balaş Azəroğlunun yaradıcılığı Cənub mövzusu ilə bağlıdır.",
  ["Balaş Azəroğlu - Cənub mövzusu", "Əli Kərim - Cənub mövzusu",
   "Balaş Azəroğlu - kosmos mövzusu",
   "Sabir Rüstəmxanlı - dəniz mövzusu"], 1, None, 3),
 ("Rəsul Rza və Əli Kərimin yaradıcılığındakı ortaq cəhət nədir?",
  "Hər ikisi poeziyada yenilikçi axtarışları ilə tanınır.",
  ["Hər ikisi poeziyada yenilikçi olmuşdur",
   "Hər ikisi roman janrında yazmışdır",
   "Hər ikisi dramaturq kimi tanınır",
   "Hər ikisi ədəbi tənqidçi olmuşdur"], 1, None, 3),
 ("Özünüdərk dövrü haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "Özünüdərk dövrü 1961-1990-cı illəri əhatə edir.",
  ["Özünüdərk dövrü 1920-1940-cı illərdədir",
   "Dövrün mövzusu milli kimlikdir",
   "Məmməd Araz bu dövrün şairidir",
   "Özünüdərk dövründə şeirin dili sadələşmişdir"], 1, None, 3),
 ("Repressiya dövrü ilə özünüdərk dövrü poeziyasının fərqi nədir?",
  "Özünüdərk dövründə milli mövzu daha açıq şəkildə deyilirdi.",
  ["Özünüdərk dövründə milli mövzu açıq deyilirdi",
   "Repressiya dövründə milli mövzu açıq deyilirdi",
   "Hər iki dövrdə mövzu eyni cür verilirdi",
   "Hər iki dövrdə şeir demək olar yazılmırdı"], 1, None, 3),
 ("Bu dövr əsərləri üzrə «əsər - mövzu» cütlüyü hansı düzgündür?",
  "«Sağ ol, ana dilim!» ana dili, «Buludlar» isə Cənub mövzusundadır.",
  ["«Sağ ol, ana dilim!» - ana dili", "«Əsgər məktubu» - ana dili",
   "«Sağ ol, ana dilim!» - dəniz mövzusu", "«Buludlar» - ana dili"],
  1, None, 3),
 ("Bu dövrdə ana dili mövzusunun poeziyada güclü olmasının səbəbi nədir?",
  "Dil milli kimliyin əsası sayıldığı üçün bu mövzu güclənmişdi.",
  ["Dilin milli kimliyin əsası sayılması",
   "Xarici dillərin geniş öyrənilməsi",
   "Dərsliklərin sayının artması", "Tərcümə işinin genişlənməsi"],
  1, None, 3),
 ("Bu dövr şairləri üzrə «şair - doğulduğu yer» cütlüyü hansı doğrudur?",
  "Məmməd Araz Naxçıvanda doğulmuşdur.",
  ["Məmməd Araz - Naxçıvan", "Əli Kərim - Naxçıvan",
   "Məmməd Araz - Şəki", "Rəsul Rza - Naxçıvan"], 1, None, 3),
 ("Sabir Rüstəmxanlı və Məmməd Arazın yaradıcılığında ortaq mövzu hansıdır?",
  "Hər ikisində vətən və ana dili mövzusu aparıcıdır.",
  ["Vətən və ana dili mövzusu", "Kosmos və texnika mövzusu",
   "Dəniz və gəmiçilik mövzusu", "Ticarət və sənaye mövzusu"],
  1, None, 3)],
}
SUALLAR.update(HISSE_2)

HISSE_3 = {
"edeb-9-ozunuderk-nesr": [
 # ---- asan (4)
 ("«Namərd gülləsi» əsərinin müəllifi kimdir?",
  "Əsərin müəllifi İsmayıl Şıxlıdır.",
  ["İsmayıl Şıxlı", "İsa Hüseynov", "Anar", "Elçin"], 1, None, 1),
 ("«Talvar» əsərinin müəllifi kimdir?",
  "Əsərin müəllifi Elçindir.",
  ["Elçin", "Anar", "İsa Hüseynov", "Mehdi Hüseyn"], 1, None, 1),
 ("«Keçən ilin son gecəsi» əsərinin müəllifi kimdir?",
  "Əsərin müəllifi Anardır.",
  ["Anar", "Elçin", "İsmayıl Şıxlı", "Sabir Rüstəmxanlı"], 1, None, 1),
 ("«Zəhər» əsərinin müəllifi kimdir?",
  "Əsərin müəllifi İsa Hüseynovdur.",
  ["İsa Hüseynov", "Anar", "Elçin", "Mirzə İbrahimov"], 1, None, 1),
 # ---- orta (15)
 ("Bu dövr nəsrinin səciyyəvi cəhəti nədir?",
  "Psixoloji dərinlik və milli yaddaşa müraciət səciyyəvidir.",
  ["Psixoloji dərinlik və milli yaddaş", "Sənədli xronika üslubu",
   "Elmi-fantastik süjet", "Detektiv macəra qurulusu"], 1, None, 2),
 ("Yazıçı Anar kimin övladıdır?",
  "Anar Rəsul Rza ilə Nigar Rəfibəylinin oğludur.",
  ["Rəsul Rza və Nigar Rəfibəylinin", "İlyas Əfəndiyevin",
   "Mir Cəlalın", "Süleyman Rüstəmin"], 1, None, 2),
 ("Yazıçı Elçin kimin övladıdır?",
  "Elçin İlyas Əfəndiyevin oğludur.",
  ["İlyas Əfəndiyevin", "Rəsul Rzanın", "Mir Cəlalın",
   "İsmayıl Şıxlının"], 1, None, 2),
 ("Aşağıdakılardan hansı Anarın əsəridir?",
  "«Beşmərtəbəli evin altıncı mərtəbəsi» Anarın povestidir.",
  ["«Beşmərtəbəli evin altıncı mərtəbəsi»", "«Ağ dəvə»", "«Məhşər»",
   "«Böyük dayaq»"], 1, None, 2),
 ("Aşağıdakılardan hansı Elçinin romanıdır?",
  "«Mahmud və Məryəm» Elçinin romanıdır.",
  ["«Mahmud və Məryəm»", "«Zəhər»", "«Gələcək gün»", "«Qan içində»"],
  1, None, 2),
 ("İsa Hüseynovun Nəsimiyə həsr olunmuş romanı hansıdır?",
  "«Məhşər» romanı Nəsiminin taleyinə həsr olunmuşdur.",
  ["«Məhşər»", "«Talvar»", "«Ağ liman»", "«Böyük dayaq»"], 1, None, 2),
 ("«Namərd gülləsi» hansı janrdadır?",
  "Əsər hekayə janrındadır.",
  ["Hekayə janrında", "Roman janrında", "Poema janrında",
   "Dram janrında"], 1, None, 2),
 ("Bu dövr nəsrində hansı məsələ tez-tez qabardılır?",
  "Mənəvi seçim və vicdan məsələsi qabardılır.",
  ["Mənəvi seçim və vicdan məsələsi", "Ticarət rəqabəti",
   "Hərbi taktika məsələləri", "Kosmos yarışı"], 1, None, 2),
 ("Anar ədəbiyyatdan başqa hansı sahədə çalışmışdır?",
  "O, kino sahəsində - ssenari və rejissorluqla məşğul olmuşdur.",
  ["Kino sahəsində", "Tibb sahəsində", "Memarlıqda", "Kimya elmində"],
  1, None, 2),
 ("Elçin hansı sahədə də tanınmışdır?",
  "O, dramaturq kimi də tanınmışdır.",
  ["Dramaturgiyada", "Aşıq şeirində", "Elmi fantastikada",
   "Uşaq nağılında"], 1, None, 2),
 ("Bu dövr nəsrində kənd mövzusu necə verilir?",
  "Kənd milli köklərin daşıyıcısı kimi verilir.",
  ["Milli köklərin daşıyıcısı kimi", "Sadəcə iqtisadi göstərici kimi",
   "Tarixi salnamə kimi", "Fantastik məkan kimi"], 1, None, 2),
 ("«Talvar» əsəri hansı ədəbi növə aiddir?",
  "«Talvar» nəsr əsəridir.",
  ["Nəsrə", "Poeziyaya", "Dramaturgiyaya", "Publisistikaya"],
  1, None, 2),
 ("Bu dövrün nasirləri hansı üsula geniş müraciət etdilər?",
  "Daxili monoloq və psixoloji təhlil üsuluna müraciət etdilər.",
  ["Daxili monoloq və psixoloji təhlilə", "Sənədli hesabat üslubuna",
   "Qafiyəli nəsrə", "Dastan qəlibinə"], 1, None, 2),
 ("İsa Hüseynovun ədəbi təxəllüsü nədir?",
  "Yazıçının təxəllüsü Muğannadır.",
  ["Muğanna", "Xətayi", "Vaqif", "Hophop"], 1, None, 2),
 ("Özünüdərk dövrü nəsri hansı illəri əhatə edir?",
  "Bu nəsr 1961-1990-cı illəri əhatə edir.",
  ["1961-1990-cı illər", "1900-1920-ci illər", "1920-1940-cı illər",
   "1991-ci ildən sonrakı illər"], 1, None, 2),
 # ---- cetin (12)
 ("Özünüdərk dövrü nəsri üzrə «əsər - müəllif» cütlüyü hansı düzgündür?",
  "«Talvar» Elçinin, «Zəhər» isə İsa Hüseynovun əsəridir.",
  ["«Talvar» - Elçin", "«Talvar» - Anar", "«Zəhər» - Elçin",
   "«Namərd gülləsi» - Anar"], 1, None, 3),
 ("Bu dövr nasirləri haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "«Məhşər» İsa Hüseynovun romanıdır.",
  ["«Məhşər» Anarın romanıdır", "«Talvar» Elçinin əsəridir",
   "«Zəhər» İsa Hüseynovundur",
   "«Namərd gülləsi» İsmayıl Şıxlınındır"], 1, None, 3),
 ("Bu dövr yazıçıları üzrə «yazıçı - ailə» cütlüyü hansı doğrudur?",
  "Anar Rəsul Rzanın, Elçin isə İlyas Əfəndiyevin oğludur.",
  ["Anar - Rəsul Rzanın oğlu", "Elçin - Rəsul Rzanın oğlu",
   "Anar - İlyas Əfəndiyevin oğlu",
   "İsa Hüseynov - Mir Cəlalın oğlu"], 1, None, 3),
 ("Bu dövr nəsrində psixoloji təhlilin güclənməsinin səbəbi nədir?",
  "Diqqətin ictimai plakatdan insanın daxili dünyasına yönəlməsi.",
  ["Diqqətin daxili dünyaya yönəlməsi",
   "Sənədli mənbələrin çoxalması", "Tarixi salnamə ənənəsi",
   "Kino sənayesinin tələbi"], 1, None, 3),
 ("Ədəbi mərhələlər zaman baxımından necə düzülür? "
  "(1 - özünüdərk dövrü, 2 - müstəqillik dövrü, 3 - müharibə dövrü)",
  "Müharibə dövrü 1941-1960, özünüdərk dövrü 1961-1990, müstəqillik "
  "dövrü isə 1991-ci ildən sonranı əhatə edir.",
  ["3 - 1 - 2", "1 - 2 - 3", "2 - 3 - 1", "1 - 3 - 2"], 1, None, 3),
 ("Anar və Elçinin ədəbi mühitlə bağlılığı haqqında hansı fikir doğrudur?",
  "Hər ikisi tanınmış ədəbi ailədən çıxmışdır.",
  ["Hər ikisi tanınmış ədəbi ailədən çıxmışdır",
   "Hər ikisi ədəbiyyata kənar sahədən gəlmişdir",
   "Biri şair, digəri bəstəkar kimi tanınır",
   "Hər ikisi ancaq tərcümə ilə məşğul olmuşdur"], 1, None, 3),
 ("Bu dövr nəsri haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "Bu dövr nəsri sənədli xronika deyil, psixoloji təhlil üzərində qurulub.",
  ["Bu dövr nəsri sənədli xronika üslubundadır",
   "Psixoloji təhlil bu nəsrdə güclüdür",
   "Milli yaddaş mövzusu geniş işlənir",
   "Anar bu dövrün nasirlərindəndir"], 1, None, 3),
 ("Müharibə dövrü nəsri ilə özünüdərk dövrü nəsrinin fərqi nədir?",
  "Birincidə cəbhə və arxa, ikincidə insanın daxili dünyası önə çıxır.",
  ["Birincidə cəbhə, ikincidə daxili dünya önə çıxır",
   "Birincidə daxili dünya, ikincidə cəbhə önə çıxır",
   "Hər ikisində eyni mövzular işlənir",
   "Hər ikisi sənədli üslubda yazılıb"], 1, None, 3),
 ("Bu dövr əsərləri üzrə «əsər - janr» cütlüyü hansı doğrudur?",
  "«Namərd gülləsi» hekayə, «Məhşər» isə romandır.",
  ["«Namərd gülləsi» - hekayə", "«Namərd gülləsi» - roman",
   "«Məhşər» - hekayə", "«Mahmud və Məryəm» - hekayə"], 1, None, 3),
 ("«Məhşər» romanında Nəsimi mövzusuna müraciətin səbəbi nədir?",
  "Milli tarixə və mənəvi köklərə qayıdış meyli.",
  ["Milli tarixə və mənəvi köklərə qayıdış",
   "Sənədli mənbələrin çoxluğu", "Xarici nəşriyyat sifarişi",
   "Klassik dili öyrənmək məqsədi"], 1, None, 3),
 ("Bu dövr yazıçıları üzrə «yazıçı - ikinci sahə» cütlüyü hansı düzgündür?",
  "Anar kino ssenariləri yazmış, filmlərin yaranmasında iştirak etmişdir.",
  ["Anar - kino ssenaristi", "İsmayıl Şıxlı - kino ssenaristi",
   "Anar - opera bəstəkarı", "Elçin - memar"], 1, None, 3),
 ("Bu dövr nəsrində kənd və şəhər mövzusu necə qarşılaşdırılır?",
  "Kənd köklə, şəhər isə dəyişən müasir həyatla bağlanır.",
  ["Kənd köklə, şəhər dəyişən həyatla bağlanır",
   "Şəhər köklə, kənd dəyişən həyatla bağlanır",
   "Hər ikisi eyni cür təsvir olunur",
   "Kənd mövzusuna demək olar toxunulmur"], 1, None, 3)],

"edeb-9-mustaqillik": [
 # ---- asan (4)
 ("«İstiqlal» şeirinin müəllifi kimdir?",
  "Şeirin müəllifi Bəxtiyar Vahabzadədir.",
  ["Bəxtiyar Vahabzadə", "Xəlil Rza Ulutürk", "Qılman İlkin",
   "Sabir Əhmədov"], 1, None, 1),
 ("Bu mərhələ hansı ildən başlayır?",
  "Mərhələ 1991-ci ildən - dövlət müstəqilliyinin bərpasından başlayır.",
  ["1991-ci ildən", "1960-cı ildən", "1941-ci ildən", "1920-ci ildən"],
  1, None, 1),
 ("«Qaytar mənim qüdrətimi, Azərbaycan!» şeirinin müəllifi kimdir?",
  "Şeirin müəllifi Xəlil Rza Ulutürkdür.",
  ["Xəlil Rza Ulutürk", "Bəxtiyar Vahabzadə", "Məmməd Araz", "Anar"],
  1, None, 1),
 ("«İntiqam» əsərinin müəllifi kimdir?",
  "Əsərin müəllifi Qılman İlkindir.",
  ["Qılman İlkin", "Sabir Əhmədov", "Elçin", "İsa Hüseynov"],
  1, None, 1),
 # ---- orta (15)
 ("Azərbaycan dövlət müstəqilliyini hansı ildə bərpa etmişdir?",
  "Müstəqillik 1991-ci ildə bərpa olunmuşdur.",
  ["1991", "1918", "1936", "2001"], 1, None, 2),
 ("Bu dövr ədəbiyyatının aparıcı mövzusu nədir?",
  "Müstəqillik, Qarabağ və şəhidlik mövzusudur.",
  ["Müstəqillik və Qarabağ mövzusu", "Sənaye tikintisi",
   "Kosmos yarışı", "Dəniz ticarəti"], 1, None, 2),
 ("«Dənizdən gələn səda» əsərinin müəllifi kimdir?",
  "Əsərin müəllifi Sabir Əhmədovdur.",
  ["Sabir Əhmədov", "Qılman İlkin", "Elçin", "Anar"], 1, None, 2),
 ("Xəlil Rza Ulutürkün şeirlərində hansı ovqat hakimdir?",
  "Üsyankarlıq və mübarizə ruhu hakimdir.",
  ["Üsyankarlıq və mübarizə ruhu", "Sakit məişət ovqatı",
   "Yumor və zarafat", "Quru elmi təhlil"], 1, None, 2),
 ("«İstiqlal» şeirində şair nəyi tərənnüm edir?",
  "Şeirdə müstəqillik arzusu tərənnüm olunur.",
  ["Müstəqillik arzusunu", "Ticarət uğurunu", "Şəhər memarlığını",
   "Dəniz gözəlliyini"], 1, None, 2),
 ("20 Yanvar faciəsi hansı ildə baş vermişdir?",
  "Faciə 1990-cı ildə baş vermişdir.",
  ["1990", "1988", "1992", "1994"], 1, None, 2),
 ("Bu dövr ədəbiyyatında hansı yeni mövzu meydana çıxdı?",
  "Qaçqınlıq və işğal mövzusu meydana çıxdı.",
  ["Qaçqınlıq və işğal mövzusu", "Sənaye briqadası mövzusu",
   "Kolxoz quruculuğu mövzusu", "Kosmos uçuşu mövzusu"], 1, None, 2),
 ("Müstəqillik dövrü ədəbiyyatında sənədlilik nə hesabına artdı?",
  "Real hadisələrə birbaşa müraciət hesabına artdı.",
  ["Real hadisələrə birbaşa müraciətlə", "Nağıl süjetlərinin artması ilə",
   "Əruz vəzninə qayıdışla", "Xarici tərcümələrin çoxalması ilə"],
  1, None, 2),
 ("Bəxtiyar Vahabzadənin bu dövr şeirlərində hansı fikir önə çəkilir?",
  "Milli istiqlal və vətəndaş məsuliyyəti fikri önə çəkilir.",
  ["Milli istiqlal və vətəndaş məsuliyyəti", "Ticarət qaydaları",
   "Dəniz macərası", "Kosmos texnikası"], 1, None, 2),
 ("Senzuranın aradan qalxması ədəbiyyatda nəyə imkan verdi?",
  "Uzun illər qadağan olunmuş mövzuların açılmasına imkan verdi.",
  ["Qadağan mövzuların açılmasına", "Nəşrin dayandırılmasına",
   "Ədəbi dilin dəyişməsinə", "Şeir vəzninin ləğvinə"], 1, None, 2),
 ("Qılman İlkin hansı ədəbi növdə çalışmışdır?",
  "O, əsasən nəsrdə çalışmışdır.",
  ["Nəsrdə", "Aşıq şeirində", "Bədii tərcümədə", "Ədəbi tənqiddə"],
  1, None, 2),
 ("Sabir Əhmədov hansı ədəbi növün nümayəndəsidir?",
  "O, nəsrin nümayəndəsidir.",
  ["Nəsrin", "Dramaturgiyanın", "Aşıq şeirinin", "Ədəbi tənqidin"],
  1, None, 2),
 ("Bu dövrdə hansı tarixi mövzu ədəbiyyata qayıtdı?",
  "Cümhuriyyət və repressiya həqiqətləri ədəbiyyata qayıtdı.",
  ["Cümhuriyyət və repressiya həqiqətləri", "Kolxoz quruculuğu",
   "Beşillik sənaye planı", "Kosmos proqramı"], 1, None, 2),
 ("Müstəqillik dövrü ədəbiyyatının dili necədir?",
  "Dil sərbəstdir, publisistik ünsürlərlə zəngindir.",
  ["Sərbəst və publisistik", "Ağır əruz dilində",
   "Sırf tərcümə dilində", "Quru rəsmi dildə"], 1, None, 2),
 ("Bu dövrdə ədəbiyyatın qarşısında duran əsas vəzifə nə idi?",
  "Milli yaddaşı bərpa etmək vəzifəsi idi.",
  ["Milli yaddaşı bərpa etmək", "Sənaye planını yerinə yetirmək",
   "Xarici bazar açmaq", "Kosmos tədqiqatı aparmaq"], 1, None, 2),
 # ---- cetin (12)
 ("Müstəqillik dövrü üzrə «əsər - müəllif» cütlüyü hansı düzgündür?",
  "«İstiqlal» Bəxtiyar Vahabzadənin, «İntiqam» Qılman İlkinindir.",
  ["«İstiqlal» - Bəxtiyar Vahabzadə",
   "«İstiqlal» - Xəlil Rza Ulutürk",
   "«İntiqam» - Bəxtiyar Vahabzadə",
   "«Dənizdən gələn səda» - Qılman İlkin"], 1, None, 3),
 ("Müstəqillik dövrü haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "Bu mərhələ 1991-ci ildən başlayır.",
  ["Bu mərhələ 1941-ci ildən başlayır",
   "Qarabağ mövzusu bu dövrdə güclənmişdir",
   "«İstiqlal» Bəxtiyar Vahabzadənindir",
   "Senzura bu dövrdə aradan qalxmışdır"], 1, None, 3),
 ("Aşağıdakı üç hadisə zaman ardıcıllığı ilə necə düzülür? "
  "(1 - müstəqilliyin bərpası, 2 - 20 Yanvar faciəsi, "
  "3 - Xocalı faciəsi)",
  "20 Yanvar 1990-cı ildə, müstəqilliyin bərpası 1991-ci ildə, Xocalı "
  "faciəsi isə 1992-ci ildə baş vermişdir.",
  ["2 - 1 - 3", "1 - 2 - 3", "3 - 2 - 1", "2 - 3 - 1"], 1, None, 3),
 ("Qarabağ mövzusunun ədəbiyyata gəlməsinin səbəbi nədir?",
  "Torpaqların işğalı və kütləvi qaçqınlıq bu mövzunu doğurdu.",
  ["Torpaqların işğalı və qaçqınlıq",
   "Sənaye tikintisinin başlanması", "Yeni əlifbaya keçilməsi",
   "Kosmos proqramının genişlənməsi"], 1, None, 3),
 ("Aşağıdakı «hadisə - il» cütlüklərindən hansı düzgündür?",
  "20 Yanvar faciəsi 1990-cı ildə baş vermişdir.",
  ["20 Yanvar faciəsi - 1990", "20 Yanvar faciəsi - 1992",
   "Müstəqilliyin bərpası - 1990", "Xocalı faciəsi - 1990"],
  1, None, 3),
 ("«İstiqlal» və «Qaytar mənim qüdrətimi» şeirlərini birləşdirən cəhət nədir?",
  "Hər ikisi milli azadlıq çağırışı üzərində qurulub.",
  ["Hər ikisi milli azadlıq çağırışıdır",
   "Hər ikisi məhəbbət lirikası nümunəsidir",
   "Hər ikisi təbiət təsviri üzərindədir",
   "Hər ikisi uşaq şeiri nümunəsidir"], 1, None, 3),
 ("Müstəqillik illərinin ədəbi mühiti barədə hansı fikir SƏHVDİR?",
  "Müstəqillik dövründə senzura gücləndi deyil, aradan qalxdı.",
  ["Müstəqillik dövründə senzura gücləndi",
   "Müstəqillik illərində qaçqınlıq mövzusu ədəbiyyata gəldi",
   "Cümhuriyyət həqiqətləri açıldı",
   "Şəhidlik mövzusu güclü şəkildə işləndi"], 1, None, 3),
 ("Sovet dövrü ilə müstəqillik dövrü ədəbiyyatının əsas fərqi nədir?",
  "Müstəqillik dövründə mövzu seçimi sərbəstləşdi.",
  ["Mövzu seçiminin sərbəstləşməsi", "Mövzu seçiminin daralması",
   "Şeir janrının tamamilə dayanması",
   "Nəsr janrının qadağan olunması"], 1, None, 3),
 ("Bu dövr şairləri üzrə «şair - əsər» cütlüyü hansı doğrudur?",
  "«Qaytar mənim qüdrətimi» Xəlil Rza Ulutürkün şeiridir.",
  ["Xəlil Rza Ulutürk - «Qaytar mənim qüdrətimi»",
   "Bəxtiyar Vahabzadə - «Qaytar mənim qüdrətimi»",
   "Xəlil Rza Ulutürk - «İntiqam»", "Qılman İlkin - «İstiqlal»"],
  1, None, 3),
 ("Müstəqillik dövründə repressiya mövzusunun açılmasının səbəbi nədir?",
  "Arxivlərin açılması və senzuranın aradan qalxması.",
  ["Arxivlərin açılması və senzuranın qalxması",
   "Yeni dərsliklərin yazılması",
   "Xarici tərcümələrin artması",
   "Teatr repertuarının dəyişməsi"], 1, None, 3),
 ("Aşağıdakı «dövr - səciyyəvi mövzu» cütlüklərindən hansı düzgündür?",
  "Qarabağ mövzusu müstəqillik dövrü ədəbiyyatı üçün səciyyəvidir.",
  ["Müstəqillik dövrü - Qarabağ mövzusu",
   "Repressiya dövrü - Qarabağ mövzusu",
   "Müstəqillik dövrü - kolxoz quruculuğu",
   "Müharibə dövrü - Qarabağ mövzusu"], 1, None, 3),
 ("Müstəqillik dövrü ilə milli-demokratik dövrün ortaq cəhəti nədir?",
  "Hər ikisində istiqlal ideyası mərkəzi yer tutur.",
  ["Hər ikisində istiqlal ideyası mərkəzdədir",
   "Hər ikisində sinfi mübarizə mərkəzdədir",
   "Hər ikisi XIX əsrə aid dövrlərdir",
   "Hər ikisində əruz vəzni hakimdir"], 1, None, 3)],
}
SUALLAR.update(HISSE_3)

HISSE_4 = {
"edeb-9-cenub": [
 # ---- asan (4)
 ("Məhəmmədhüseyn Şəhriyarın ana dilində yazdığı ən məşhur poeması hansıdır?",
  "Bu, «Heydərbabaya salam» poemasıdır.",
  ["«Heydərbabaya salam»", "«Sazımın sözü»", "«Səhənd dağı»",
   "«Gələcək gün»"], 1, None, 1),
 ("Məhəmmədhüseyn Şəhriyar hansı ölkədə yaşayıb-yaratmışdır?",
  "Şair İranda - Cənubi Azərbaycanda yaşayıb-yaratmışdır.",
  ["İranda", "Türkiyədə", "Rusiyada", "Misirdə"], 1, None, 1),
 ("«Səhənd dağı» şeirinin müəllifi kimdir?",
  "Şeirin müəllifi Həbib Sahirdir.",
  ["Həbib Sahir", "Məhəmmədhüseyn Şəhriyar", "Balaş Azəroğlu",
   "Süleyman Rüstəm"], 1, None, 1),
 ("Cənubi Azərbaycan ədəbiyyatının ana dilli qolu hansı dildə yaranır?",
  "Bu ədəbiyyat Azərbaycan dilində yaranır.",
  ["Azərbaycan dilində", "Ərəb dilində", "Rus dilində",
   "İngilis dilində"], 1, None, 1),
 # ---- orta (15)
 ("«Heydərbabaya salam»ın birinci hissəsi hansı ildə yazılmışdır?",
  "Poemanın birinci hissəsi 1954-cü ildə yazılmışdır.",
  ["1954", "1937", "1975", "1991"], 1, None, 2),
 ("«Heydərbabaya salam» poemasında hansı dövr xatırlanır?",
  "Poemada şairin uşaqlıq illəri xatırlanır.",
  ["Şairin uşaqlıq illəri", "Gələcək əsr", "Orta əsrlər",
   "Antik dövr"], 1, None, 2),
 ("«Heydərbabaya salam» poemasının vəzni hansıdır?",
  "Poema heca vəznində yazılmışdır.",
  ["Heca vəzni", "Əruz vəzni", "Sərbəst şeir", "Ağ şeir"],
  1, None, 2),
 ("«Heydərbabaya salam» poemasının dili necədir?",
  "Dil sadə, canlı danışıq dilinə çox yaxındır.",
  ["Sadə, canlı danışıq dili", "Ağır kitab dili",
   "Elmi termin dili", "Rəsmi sənəd dili"], 1, None, 2),
 ("Məhəmmədhüseyn Şəhriyar hansı ildə vəfat etmişdir?",
  "Şair 1988-ci ildə vəfat etmişdir.",
  ["1988", "1954", "1969", "2001"], 1, None, 2),
 ("Məhəmmədhüseyn Şəhriyar harada dəfn olunmuşdur?",
  "O, Təbrizdə şairlər məqbərəsində dəfn olunmuşdur.",
  ["Təbrizdə şairlər məqbərəsində", "Bakıda Fəxri xiyabanda",
   "Tehranda", "İstanbulda"], 1, None, 2),
 ("«Heydərbabaya salam» Şimali Azərbaycanda necə qarşılandı?",
  "Poema böyük maraqla qarşılandı, ona çoxlu nəzirə yazıldı.",
  ["Böyük maraqla qarşılandı, nəzirələr yazıldı",
   "Diqqətdən kənarda qaldı", "Oxucuya çatdırılmadı",
   "Tez unuduldu"], 1, None, 2),
 ("«Heydərbabaya salam» poemasında hansı obrazlar xüsusi yer tutur?",
  "Kənd adamları və doğma təbiət obrazları xüsusi yer tutur.",
  ["Kənd adamları və təbiət", "Saray əyanları",
   "Dəniz kapitanları", "Kosmos alimləri"], 1, None, 2),
 ("Şəhriyarın «Səhəndiyyə» şeiri kimə müraciətlə yazılmışdır?",
  "Şeir şair Səhəndə - Bulud Qaraçorluya müraciətlə yazılmışdır.",
  ["Şair Səhəndə", "Nizami Gəncəviyə", "Məhəmməd Füzuliyə",
   "Molla Pənah Vaqifə"], 1, None, 2),
 ("Cənub şairlərinin şeirlərində Araz çayı nəyin nişanıdır?",
  "Araz iki tayın ayrılığının nişanıdır.",
  ["Ayrılığın nişanıdır", "Bolluğun nişanıdır",
   "Ticarətin nişanıdır", "Qələbənin nişanıdır"], 1, None, 2),
 ("Məhəmmədhüseyn Şəhriyar fars ədəbiyyatında hansı yerə sahibdir?",
  "O, fars dilində də tanınmış şair sayılır.",
  ["Tanınmış şair kimi tanınır", "Naməlum qalmışdır",
   "Ancaq tərcüməçi sayılır", "Nasir kimi tanınır"], 1, None, 2),
 ("Poemanın adındakı «salam» sözü nəyi bildirir?",
  "Şairin doğma yerlərə, dağa müraciətini bildirir.",
  ["Doğma yerlərə müraciəti", "Rəsmi məktub formasını",
   "Hərbi salam qaydasını", "Ticarət müqaviləsini"], 1, None, 2),
 ("Həbib Sahir hansı ədəbi növün nümayəndəsidir?",
  "Həbib Sahir şeirin nümayəndəsidir.",
  ["Şeirin", "Dramaturgiyanın", "Ədəbi tənqidin", "Publisistikanın"],
  1, None, 2),
 ("«Heydərbabaya salam» hansı janrdadır?",
  "Əsər lirik-xatirə poemasıdır.",
  ["Poema", "Hekayə", "Dram", "Roman"], 1, None, 2),
 ("«Heydərbabaya salam» hansı bədii ovqatı ilə seçilir?",
  "Xatirə və nostalji ovqatı ilə seçilir.",
  ["Xatirə və nostalji ovqatı", "Detektiv gərginlik",
   "Elmi dəqiqlik", "Sənədli quruluş"], 1, None, 2),
 # ---- cetin (12)
 ("Cənub ədəbiyyatı üzrə «əsər - müəllif» cütlüyü hansı düzgündür?",
  "«Səhənd dağı» Həbib Sahirin, «Səhəndiyyə» isə Şəhriyarındır.",
  ["«Səhənd dağı» - Həbib Sahir",
   "«Səhənd dağı» - Məhəmmədhüseyn Şəhriyar",
   "«Heydərbabaya salam» - Həbib Sahir",
   "«Səhəndiyyə» - Həbib Sahir"], 1, None, 3),
 ("«Heydərbabaya salam» haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "Poema ana dilində - Azərbaycan dilində yazılmışdır.",
  ["Poema fars dilində yazılmışdır", "Poema heca vəznindədir",
   "Poemanın birinci hissəsi 1954-cü ildəndir",
   "Şəhriyar Təbrizdə dəfn olunmuşdur"], 1, None, 3),
 ("Aşağıdakı üç hadisə zaman ardıcıllığı ilə necə düzülür? "
  "(1 - poemanın yazılması, 2 - şairin vəfatı, 3 - şairin doğulması)",
  "Şəhriyar 1906-cı ildə doğulub, poemanı 1954-cü ildə yazıb, "
  "1988-ci ildə vəfat edib.",
  ["3 - 1 - 2", "1 - 2 - 3", "2 - 3 - 1", "1 - 3 - 2"], 1, None, 3),
 ("«Heydərbabaya salam»ın hər iki tayda geniş yayılmasının səbəbi nədir?",
  "Poema ana dilində, sadə və hər kəsə doğma dildə yazılmışdı.",
  ["Ana dilində və hamıya doğma olması", "Fars dilində yazılması",
   "Saray sifarişi ilə yaranması", "Elmi mövzuya həsr olunması"],
  1, None, 3),
 ("Cənub şairləri üzrə «şair - əsər» cütlüyü hansı doğrudur?",
  "«Səhəndiyyə» Şəhriyarın, «Səhənd dağı» Həbib Sahirin şeiridir.",
  ["Şəhriyar - «Səhəndiyyə»", "Həbib Sahir - «Səhəndiyyə»",
   "Şəhriyar - «Səhənd dağı»",
   "Səhənd - «Heydərbabaya salam»"], 1, None, 3),
 ("Şəhriyarın doğum ili ilə vəfat ili arasında neçə il var?",
  "Şair 1906-cı ildə doğulub, 1988-ci ildə vəfat edib.",
  ["82 il", "72 il", "62 il", "92 il"], 1, None, 3),
 ("Cənub ədəbiyyatı haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "Ana dili mövzusu bu ədəbiyyatda ən güclü mövzulardandır.",
  ["Bu ədəbiyyatda ana dili mövzusu zəifdir",
   "Araz çayı ayrılıq nişanıdır",
   "Şəhriyar Cənub ədəbiyyatının nümayəndəsidir",
   "Həbib Sahir Cənub şairlərindəndir"], 1, None, 3),
 ("«Heydərbabaya salam» ilə klassik divan şeirinin fərqi nədir?",
  "Poema sadə heca vəznindədir, divan şeiri isə əruz vəznindədir.",
  ["Biri sadə heca, digəri əruz vəznindədir",
   "Biri əruz, digəri sadə heca vəznindədir",
   "Hər ikisi heca vəznindədir", "Hər ikisi sərbəst şeirdir"],
  1, None, 3),
 ("Cənub ədəbiyyatı üzrə «əsər - mövzu» cütlüyü hansı düzgündür?",
  "«Heydərbabaya salam» uşaqlıq xatirələri üzərində qurulub.",
  ["«Heydərbabaya salam» - uşaqlıq xatirələri",
   "«Heydərbabaya salam» - dəniz səfəri təəssüratı",
   "«Səhənd dağı» - kosmos tədqiqatı mövzusu",
   "«Səhəndiyyə» - ticarət yolları mövzusu"], 1, None, 3),
 ("Şəhriyarın ana dilində yazmasının Cənub ədəbiyyatı üçün əhəmiyyəti nədir?",
  "Ana dilli şeirə güclü təkan vermiş, onun nüfuzunu artırmışdır.",
  ["Ana dilli şeirə güclü təkan verməsi",
   "Fars şeirini daha da gücləndirməsi",
   "Tərcümə ənənəsini başlatması",
   "Nəsr janrının yaranmasına səbəb olması"], 1, None, 3),
 ("Şəhriyar və Həbib Sahir haqqında hansı fikir doğrudur?",
  "Hər ikisi Cənubi Azərbaycan ədəbiyyatının nümayəndəsidir.",
  ["Hər ikisi Cənubi Azərbaycan şairidir",
   "Hər ikisi Şimalda yaşayıb-yaratmışdır",
   "Biri şair, digəri dramaturq olmuşdur",
   "Hər ikisi ancaq nəsr yazmışdır"], 1, None, 3),
 ("Cənub və klassik poeziya üzrə «əsər - vəzn» cütlüyü hansı doğrudur?",
  "«Heydərbabaya salam» heca, «Leyli və Məcnun» isə əruz vəznindədir.",
  ["«Heydərbabaya salam» - heca vəzni",
   "«Heydərbabaya salam» - əruz vəzni",
   "«Leyli və Məcnun» - heca vəzni", "«Xəmsə» - heca vəzni"],
  1, None, 3)],

"edeb-9-dunya": [
 # ---- asan (4)
 ("«Qoca və dəniz» əsərinin baş qəhrəmanı kimdir?",
  "Əsərin baş qəhrəmanı qoca balıqçı Santyaqodur.",
  ["Santyaqo", "Manolin", "Robinzon", "Hamlet"], 1, None, 1),
 ("Ernest Heminquey hansı ölkənin yazıçısıdır?",
  "Heminquey ABŞ yazıçısıdır.",
  ["ABŞ-ın", "İngiltərənin", "Fransanın", "Almaniyanın"], 1, None, 1),
 ("«Qoca və dəniz» hansı janrdadır?",
  "Əsər povest janrındadır.",
  ["Povest", "Qəzəl", "Dastan", "Faciə"], 1, None, 1),
 ("Santyaqo peşəsinə görə kimdir?",
  "Santyaqo balıqçıdır.",
  ["Balıqçı", "Müəllim", "Həkim", "Dəmirçi"], 1, None, 1),
 # ---- orta (15)
 ("Santyaqonun şagirdi olan oğlanın adı nədir?",
  "Oğlanın adı Manolindir.",
  ["Manolin", "Nofəl", "Eyvaz", "Uruz"], 1, None, 2),
 ("Santyaqo neçə gün balıq tuta bilmir?",
  "O, səksən dörd gün balıqsız qalır.",
  ["84 gün", "14 gün", "40 gün", "120 gün"], 1, None, 2),
 ("Santyaqo hansı böyük balığı tutur?",
  "O, nəhəng marlin balığını tutur.",
  ["Nəhəng marlin balığını", "Balina", "Nəhəng tısbağa",
   "Səkkizayaq"], 1, None, 2),
 ("Tutulan balığa yolda kimlər hücum edir?",
  "Balığa köpək balıqları hücum edir.",
  ["Köpək balıqları", "Dəniz quşları", "Digər balıqçılar",
   "Sahil gözətçiləri"], 1, None, 2),
 ("Qoca sahilə nə ilə qayıdır?",
  "O, balığın yalnız skeleti ilə qayıdır.",
  ["Balığın skeleti ilə", "Bütöv balıqla", "Boş qayıqla",
   "Yeni torla"], 1, None, 2),
 ("Əsərdəki hadisələr hansı ölkənin sahillərində cərəyan edir?",
  "Hadisələr Kuba sahillərində cərəyan edir.",
  ["Kubanın", "Yunanıstanın", "Norveçin", "Yaponiyanın"], 1, None, 2),
 ("«Qoca və dəniz» hansı ildə nəşr olunmuşdur?",
  "Əsər 1952-ci ildə nəşr olunmuşdur.",
  ["1952", "1932", "1962", "1972"], 1, None, 2),
 ("Ernest Heminquey hansı ildə Nobel mükafatına layiq görülmüşdür?",
  "Yazıçı 1954-cü ildə Nobel mükafatı almışdır.",
  ["1954", "1944", "1964", "1974"], 1, None, 2),
 ("Heminqueyin yazı üslubu necə səciyyələnir?",
  "Qısa, təmkinli cümlələr və artıq təsvirdən qaçmaq səciyyəvidir.",
  ["Qısa və təmkinli cümlələr", "Uzun və təmtəraqlı təsvirlər",
   "Qafiyəli nəsr", "Sənədli protokol üslubu"], 1, None, 2),
 ("«Qoca və dəniz» əsərinin əsas ideyası nədir?",
  "İnsan iradəsinin məğlubedilməzliyi ideyasıdır.",
  ["İnsan iradəsinin məğlubedilməzliyi",
   "Var-dövlət toplamağın vacibliyi", "Səyahətin təhlükəsi",
   "Ticarətin faydası"], 1, None, 2),
 ("Santyaqo ilə Manolin arasındakı münasibət necədir?",
  "Aralarında ustad-şagird dostluğu var.",
  ["Ustad-şagird dostluğu", "Kəskin rəqiblik",
   "Yaxın qohumluq", "Ticarət ortaqlığı"], 1, None, 2),
 ("Aşağıdakılardan hansı Ernest Heminqueyin əsəridir?",
  "«Əlvida, silah!» Heminqueyin romanıdır.",
  ["«Əlvida, silah!»", "«Ağ dəvə»", "«Məhşər»", "«Gələcək gün»"],
  1, None, 2),
 ("Ernest Heminquey ədəbiyyatdan başqa hansı sahədə çalışmışdır?",
  "O, uzun müddət jurnalist kimi çalışmışdır.",
  ["Jurnalistikada", "Memarlıqda", "Tibb sahəsində",
   "Kənd təsərrüfatında"], 1, None, 2),
 ("Əsərdə dəniz nəyin simvolu kimi verilir?",
  "Dəniz həyatın və mübarizə meydanının simvoludur.",
  ["Həyatın və mübarizənin", "Ticarət yolunun", "Rahatlığın",
   "Unutqanlığın"], 1, None, 2),
 ("Qocanın məğlub sayılmamasının səbəbi nədir?",
  "O, hər şeyi itirsə də ruhdan düşmür.",
  ["Ruhdan düşməməsi", "Çoxlu balıq tutması",
   "Var-dövlət qazanması", "Şəhərə köçməsi"], 1, None, 2),
 # ---- cetin (12)
 ("«Qoca və dəniz» üzrə «obraz - rol» cütlüyü hansı düzgündür?",
  "Manolin qocanın şagirdi, Santyaqo isə balıqçıdır.",
  ["Manolin - qocanın şagirdi", "Santyaqo - qocanın şagirdi",
   "Manolin - qayıq sahibi", "Santyaqo - şəhər taciri"], 1, None, 3),
 ("«Qoca və dəniz» haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "Qoca sahilə balığın yalnız skeleti ilə qayıdır.",
  ["Qoca sahilə bütöv balıqla qayıdır",
   "Qoca səksən dörd gün balıq tutmur",
   "Hadisələr Kuba sahillərində keçir",
   "Manolin qocanın şagirdidir"], 1, None, 3),
 ("Əsərdəki üç hadisə ardıcıllıqla necə düzülür? "
  "(1 - uğursuz günlər, 2 - böyük balığın tutulması, "
  "3 - köpək balıqlarının hücumu)",
  "Əvvəlcə uzun uğursuz günlər keçir, sonra balıq tutulur, sonra "
  "köpək balıqları hücum edir.",
  ["1 - 2 - 3", "2 - 1 - 3", "3 - 2 - 1", "2 - 3 - 1"], 1, None, 3),
 ("Qocanın böyük balığı bütöv halda sahilə çatdıra bilməməsinin səbəbi nədir?",
  "Yolda köpək balıqları hücum edib balığı yeyir.",
  ["Köpək balıqlarının hücumu", "Qayığın yolda batması",
   "Balıqçı torunun cırılması", "Qocanın yolunu azması"], 1, None, 3),
 ("Dünya ədəbiyyatı üzrə «əsər - müəllif» cütlüyü hansı doğrudur?",
  "«Qoca və dəniz» Ernest Heminqueyin əsəridir.",
  ["«Qoca və dəniz» - Ernest Heminquey",
   "«Qoca və dəniz» - Çingiz Aytmatov",
   "«Əlvida, silah!» - Çingiz Aytmatov",
   "«Məhşər» - Ernest Heminquey"], 1, None, 3),
 ("Əsərin nəşri ilə yazıçının Nobel mükafatı arasında neçə il var?",
  "Əsər 1952-ci ildə nəşr olunub, mükafat 1954-cü ildə verilib.",
  ["2 il", "6 il", "10 il", "20 il"], 1, None, 3),
 ("Ernest Heminquey haqqında aşağıdakı fikirlərdən hansı SƏHVDİR?",
  "Heminquey Amerika yazıçısıdır, ingilis deyil.",
  ["O, ingilis yazıçısıdır", "O, Nobel mükafatı almışdır",
   "«Qoca və dəniz» onun povestidir",
   "O, jurnalist kimi də çalışmışdır"], 1, None, 3),
 ("Santyaqonun itkisi ilə qələbəsi arasındakı münasibət necə izah olunur?",
  "Maddi itkiyə baxmayaraq o, mənəvi qələbə qazanır.",
  ["Maddi itkiyə baxmayaraq mənəvi qələbə qazanır",
   "Mənəvi itkiyə baxmayaraq maddi qələbə qazanır",
   "Hər iki cəhətdən uduzmuş sayılır",
   "Hər iki cəhətdən udmuş sayılır"], 1, None, 3),
 ("Dünya və Azərbaycan ədəbiyyatı üzrə «əsər - janr» cütlüyü hansı doğrudur?",
  "«Qoca və dəniz» povest, «Heydərbabaya salam» isə poemadır.",
  ["«Qoca və dəniz» - povest", "«Qoca və dəniz» - poema",
   "«Heydərbabaya salam» - povest", "«Namərd gülləsi» - povest"],
  1, None, 3),
 ("Heminqueyin qısa cümlələrdən istifadə etməsi mətnə nə verir?",
  "Mətnə gərginlik və təmkinli ifadə gücü verir.",
  ["Gərginlik və təmkinli ifadə", "Nağılvari yumşaqlıq ovqatı",
   "Elmi mətn dəqiqliyi", "Rəsmi sənəd ahəngi"], 1, None, 3),
 ("Əsərdəki «obraz - simvolik məna» cütlüklərindən hansı düzgündür?",
  "Dəniz həyatı və mübarizə meydanını simvolizə edir.",
  ["Dəniz - həyat və mübarizə", "Dəniz - rahatlıq və dinclik",
   "Köpək balıqları - kömək qüvvələri", "Marlin - qorxaqlıq nişanı"],
  1, None, 3),
 ("«Qoca və dəniz» ilə «Heydərbabaya salam» arasındakı əsas fərq nədir?",
  "Biri nəsr, digəri isə şeirlə yazılmış əsərdir.",
  ["«Qoca və dəniz» nəsr, «Heydərbabaya salam» şeirdir",
   "«Qoca və dəniz» şeir, «Heydərbabaya salam» nəsrdir",
   "Hər ikisi nəsr əsəridir", "Hər ikisi şeir əsəridir"],
  1, None, 3)],
}
SUALLAR.update(HISSE_4)


def yoxla():
    n = xeta = 0
    butun = set()
    movzular = set(m for m, _r in MOVZULAR)
    for movzu, siyahi in SUALLAR.items():
        assert movzu in movzular, movzu
        if len(siyahi) != 31:
            print("XETA  %s: %d sual (31 olmalidir)" % (movzu, len(siyahi)))
            xeta += 1
        say = {1: 0, 2: 0, 3: 0}
        for body, why, opts, correct, expect, diff in siyahi:
            n += 1
            if diff in say:
                say[diff] += 1
            p = []
            if len(opts) != 4: p.append("variant sayi %d" % len(opts))
            if len(set(opts)) != len(opts): p.append("tekrar variant")
            if not (1 <= correct <= 4): p.append("correct")
            if not why: p.append("izah bos")
            if diff not in (1, 2, 3): p.append("cetinlik")
            if body in butun: p.append("eyni sual iki defe")
            butun.add(body)
            if expect is not None and opts[correct - 1] != expect:
                p.append("hesablanan «%s» != variant «%s»"
                         % (expect, opts[correct - 1]))
            for t in [body, why] + opts:
                if "'" in t: p.append("apostrof var")
                if any("Ѐ" <= ch <= "ӿ" for ch in t):
                    p.append("kiril herfi var")
            if p:
                xeta += 1
                print("XETA  %s: %s\n      %s" % (movzu, body[:60], "; ".join(p)))
        if say != BOLGU:
            print("XETA  %s: cetinlik bolgusu %s (gozlenilen %s)"
                  % (movzu, say, BOLGU))
            xeta += 1
    if len(SUALLAR) != len(MOVZULAR):
        print("XETA  movzu sayi %d (%d olmalidir)"
              % (len(SUALLAR), len(MOVZULAR)))
        xeta += 1
    #  ANS qaydasi: eyni duzgun cavab metni bank uzre 2 defeden cox olmasin
    cavab = {}
    for movzu, siyahi in SUALLAR.items():
        for body, why, opts, correct, _e, _d in siyahi:
            cavab.setdefault(opts[correct - 1], []).append(movzu)
    for c, yer in sorted(cavab.items()):
        if len(yer) > 2:
            print("XETA  duzgun cavab %d defe: «%s» (%s)"
                  % (len(yer), c, ", ".join(yer)))
            xeta += 1
    print("%d sual yoxlandı, %d xəta" % (n, xeta))
    return xeta == 0, n


def sql_yaz(n):
    q = lambda t: t.replace("'", "''")
    setirler = []
    for movzu, rub in MOVZULAR:
        pay = movzu.split("-")          # edeb, 11, tenqidi, realizm
        on = "edeb" + pay[1]
        qisa = "-".join(pay[2:])
        for i, (body, why, opts, correct, _e, diff) in enumerate(SUALLAR[movzu], 1):
            setirler.append(
                "('%s-%s#%d','edebiyyat','%s',%d,%d,'%s','%s',"
                "array['%s','%s','%s','%s'],%d)"
                % (on, qisa, i, movzu, diff, rub, q(body), q(why),
                   q(opts[0]), q(opts[1]), q(opts[2]), q(opts[3]), correct))
    with io.open(CIXIS, "w", encoding="utf-8") as f:
        f.write("""-- =====================================================================
--  60_bank_edebiyyat9.sql : EDEBIYYAT 9 BANKI
--
--  BU FAYL ELLE YAZILMIR - tools/edebiyyat9.py yaradir:
--      python3 tools/edebiyyat9.py
--
--  8 movzu x 31 sual = %d.  Her movzuda 4 asan + 15 orta + 12 cetin.
--  ext_key: edeb11-...
--  ON SERT: 58_movzular_edebiyyat9_10.sql islenmis olmalidir.
--  SONRA:   05_grants.sql yeniden islet.
-- =====================================================================

do $$
begin
  if not exists (select 1 from public.topics t join public.subjects s
      on s.id = t.subject_id
     where s.slug = 'edebiyyat' and t.slug in
           ('edeb-9-milli-demokratik', 'edeb-9-dunya')
     having count(*) = 2) then
    raise exception 'ONCE 58_movzular_edebiyyat9_10.sql isledilmelidir.';
  end if;
end $$;

delete from public.question_options o
 using public.questions q
 where o.question_id = q.id
   and q.owner_type = 'platform'
   and q.ext_key like 'edeb9-%%';

with d(ext, fenn, topic, diff, rub, body, why, opts, correct) as (values
%s
),
ins as (
  insert into public.questions
    (ext_key, owner_type, subject_id, level_id, topic_id, kind,
     body, explanation, difficulty, quarter, status)
  select d.ext, 'platform', s.id, tp.level_id, tp.id, 'single',
         d.body, d.why, d.diff, d.rub, 'published'
    from d
    join public.subjects s on s.slug = d.fenn
    join public.topics   tp on tp.subject_id = s.id and tp.slug = d.topic
  on conflict (ext_key) do update
    set body = excluded.body, explanation = excluded.explanation,
        difficulty = excluded.difficulty, quarter = excluded.quarter,
        topic_id = excluded.topic_id, level_id = excluded.level_id,
        subject_id = excluded.subject_id, status = 'published'
  returning id, ext_key
)
insert into public.question_options (question_id, ord, body, is_correct)
select ins.id, o.ord, o.txt, o.ord = d.correct
  from ins
  join d on d.ext = ins.ext_key,
  lateral unnest(d.opts) with ordinality as o(txt, ord);

do $$
declare n int; k int;
begin
  select count(*) into n from public.questions
   where owner_type = 'platform' and ext_key like 'edeb9-%%';
  if n <> %d then
    raise exception 'Edebiyyat 9 suallari: %d gozlenilirdi, %% tapildi', n;
  end if;
  select count(*) into k from public.questions q
   where q.ext_key like 'edeb9-%%'
     and ((select count(*) from public.question_options o
            where o.question_id = q.id) <> 4
       or (select count(*) from public.question_options o
            where o.question_id = q.id and o.is_correct) <> 1);
  if k > 0 then
    raise exception '%% sualda variant qurulusu sehvdir', k;
  end if;
  select count(distinct topic_id) into k from public.questions
   where ext_key like 'edeb9-%%';
  if k <> 8 then
    raise exception 'movzu sayi 8 deyil: %%', k;
  end if;
  --  Her movzuda en azi 12 cetin sual olmalidir ki, muellim BIR
  --  movzudan 10 sualliq cetin test yiga bilsin
  select count(*) into k from (
    select q.topic_id from public.questions q
     where q.ext_key like 'edeb9-%%' and q.difficulty = 3
     group by q.topic_id having count(*) < 12) z;
  if k > 0 then
    raise exception '%% movzuda 12-den az cetin sual var', k;
  end if;
  raise notice 'Edebiyyat 9 banki: %% sual, 8 movzu (her birinde 12 cetin).', n;
end $$;
""" % (n, ",\n".join(setirler), n, n))
    print("yazildi: %s" % CIXIS)


if __name__ == "__main__":
    ok, n = yoxla()
    if not ok:
        raise SystemExit(1)
    sql_yaz(n)
