#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
6-ci sinfin tebiet fennleri -> db/32_bank_fenn6.sql

    Fizika 6       4 movzu x 20 =  40
    Biologiya 6    8 movzu x 20 =  80
    Cografiya 6    7 movzu x 20 =  70
                            cemi  190

Bu fennler 6-ci sinifde baslayir - platforma banklarinin ilk fizika,
biologiya ve cografiya suallari.  Movzular 29_movzular_orta6.sql
agacina uygundur (e-derslik: fizika 546, biologiya 538, cografiya
859/860).  Suallar yalniz derslik seviyyeli, subhesiz faktlardir;
sixliq kimi hesablanan cavablar Python-da yoxlanilir.

Isletmek:
    python3 tools/fenn6.py
"""
import io
import os

KOK = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CIXIS = os.path.join(KOK, "db", "32_bank_fenn6.sql")

#  (fenn, movzu-slug, rub)
MOVZULAR = [
    ("fizika", "fiz-6-giris",    1),
    ("fizika", "fiz-6-materiya", 2),
    ("fizika", "fiz-6-madde",    3),
    ("fizika", "fiz-6-hereket",  4),
    ("biologiya", "bio-6-tedqiqat",        1),
    ("biologiya", "bio-6-huceyre",         1),
    ("biologiya", "bio-6-vegetativ",       2),
    ("biologiya", "bio-6-generativ",       2),
    ("biologiya", "bio-6-hereket-qida",    3),
    ("biologiya", "bio-6-dasinma-coxalma", 3),
    ("biologiya", "bio-6-muhit",           4),
    ("biologiya", "bio-6-rol",             4),
    ("cografiya", "cog-6-mekan",    1),
    ("cografiya", "cog-6-beledci",  1),
    ("cografiya", "cog-6-col",      2),
    ("cografiya", "cog-6-kainat",   2),
    ("cografiya", "cog-6-tebiet",   3),
    ("cografiya", "cog-6-yurdumuz", 3),
    ("cografiya", "cog-6-dunya",    4),
]

SUALLAR = {
# ========================= FIZIKA 6 ===================================
"fiz-6-giris": [
 ("Fizika elmi nəyi öyrənir?",
  "Fizika təbiət hadisələrini və onların qanunlarını öyrənir.",
  ["Təbiət hadisələrini", "Yalnız bitkiləri", "Yalnız tarixi",
   "Yalnız dilləri"], 1, None, 1),
 ("Hansı hadisə fiziki hadisədir?",
  "Buzun əriməsi — maddənin halı dəyişir, özü dəyişmir.",
  ["Buzun əriməsi", "Ağacın böyüməsi", "Dəmirin paslanması",
   "Südün turşuması"], 1, None, 2),
 ("Hansı fiziki kəmiyyətdir?",
  "Kütlə ölçülə bilən fiziki kəmiyyətdir.",
  ["Kütlə", "Sevinc", "Dad", "Yuxu"], 1, None, 2),
 ("Uzunluğun beynəlxalq sistemdə (BS) vahidi hansıdır?",
  "Uzunluğun BS vahidi metrdir.",
  ["Metr", "Kiloqram", "Saniyə", "Litr"], 1, None, 2),
 ("Zamanın BS vahidi hansıdır?",
  "Zamanın BS vahidi saniyədir.",
  ["Saniyə", "Metr", "Dərəcə", "Qram"], 1, None, 2),
 ("Mayelərin həcmini ölçmək üçün hansı cihazdan istifadə olunur?",
  "Həcm menzurka (ölçü silindri) ilə ölçülür.",
  ["Menzurka", "Tərəzi", "Xətkeş", "Kompas"], 1, None, 2),
 ("Fizikada əsas öyrənmə metodları hansılardır?",
  "Müşahidə və təcrübə əsas metodlardır.",
  ["Müşahidə və təcrübə", "Yalnız əzbərləmə",
   "Yalnız şəkil çəkmə", "Təxmin etmə"], 1, None, 2),
 ("Ölçmə nədir?",
  "Kəmiyyətin qəbul olunmuş vahidlə müqayisəsidir.",
  ["Kəmiyyətin vahidlə müqayisəsi", "Cihazın təmiri",
   "Rəqəmlərin yazılması", "Cədvəlin çəkilməsi"], 1, None, 3),
 ("Klassik mexanikanın banilərindən sayılan alim kimdir?",
  "İsaak Nyuton mexanikanın əsasını qoymuşdur.",
  ["İsaak Nyuton", "Şekspir", "Motsart", "Kolumb"], 1, None, 2),
 ("Ölçmənin dəqiqliyi nədən asılıdır?",
  "Cihazın bölgü qiymətindən asılıdır.",
  ["Cihazın bölgü qiymətindən", "Otağın rəngindən",
   "Günün vaxtından", "Ölçənin boyundan"], 1, None, 3),
],
"fiz-6-materiya": [
 ("Materiya nədir?",
  "Kainatda mövcud olan hər şey — maddə və fiziki sahə.",
  ["Kainatda mövcud olan hər şey", "Yalnız su",
   "Yalnız hava", "Yalnız işıq"], 1, None, 2),
 ("Hansı maddəyə misaldır?",
  "Su maddədir; sahələr maddə deyil, materiyanın başqa növüdür.",
  ["Su", "Maqnit sahəsi", "Elektrik sahəsi",
   "Qravitasiya sahəsi"], 1, None, 2),
 ("Fiziki cisim nədir?",
  "Maddədən təşkil olunmuş əşyadır: stol, daş, qələm.",
  ["Maddədən təşkil olunmuş əşya", "İşıq şüası",
   "Səs dalğası", "Kölgə"], 1, None, 2),
 ("Atomun mərkəzində nə yerləşir?",
  "Atomun mərkəzində nüvə yerləşir.",
  ["Nüvə", "Molekul", "Hüceyrə", "Toz"], 1, None, 2),
 ("Molekul nədir?",
  "Atomlardan təşkil olunmuş hissəcikdir.",
  ["Atomlardan təşkil olunmuş hissəcik", "Ən böyük cisim",
   "Planet", "Mineral"], 1, None, 2),
 ("Maddənin neçə əsas aqreqat halı var?",
  "Üç əsas hal: bərk, maye, qaz.",
  ["3", "2", "5", "10"], 1, None, 2),
 ("Su buxarı maddənin hansı halıdır?",
  "Buxar qaz halıdır.",
  ["Qaz", "Bərk", "Maye", "Heç biri"], 1, None, 2),
 ("Bərk cisimlərin xarakterik xüsusiyyəti nədir?",
  "Bərk cisimlər öz formasını saxlayır.",
  ["Öz formasını saxlayır", "Qabın formasını alır",
   "Bütün fəzanı doldurur", "Görünmür"], 1, None, 2),
 ("Mayelərin xarakterik xüsusiyyəti hansıdır?",
  "Maye tökuldüyü qabın formasını alır.",
  ["Qabın formasını alır", "Formasını saxlayır",
   "Sıxıla bilir", "Yalnız isti olur"], 1, None, 2),
 ("Şüşə stəkan maddədir, yoxsa cisim?",
  "Stəkan cisimdir, şüşə isə maddədir.",
  ["Cisimdir", "Maddədir", "Sahədir", "Hadisədir"],
  1, None, 3),
],
"fiz-6-madde": [
 ("Diffuziya nədir?",
  "Bir maddə hissəciklərinin digərinin arasına yayılmasıdır.",
  ["Maddələrin qarışması (yayılması)", "Suyun donması",
   "Cismin düşməsi", "İşığın sınması"], 1, None, 2),
 ("Ətrin otağa yayılması hansı hadisəyə misaldır?",
  "Qoxu hissəcikləri havada yayılır — diffuziyadır.",
  ["Diffuziyaya", "Zəlzələyə", "Cazibəyə", "Elektrikləşməyə"],
  1, None, 2),
 ("Qızdırılan cisimlər adətən nə edir?",
  "İstidən cisimlər genişlənir.",
  ["Genişlənir", "Sıxılır", "Yox olur", "Dəyişmir"],
  1, None, 2),
 ("Sıxlıq hansı düsturla hesablanır?",
  "Sıxlıq = kütlə : həcm.",
  ["Kütlə : həcm", "Kütlə × həcm", "Həcm : kütlə",
   "Kütlə + həcm"], 1, None, 3),
 ("Kütləsi 200 q, həcmi 100 sm³ olan cismin sıxlığı neçədir?",
  "200 : 100 = 2 q/sm³.",
  ["2 q/sm³", "20 q/sm³", "0,5 q/sm³", "300 q/sm³"], 1,
  "%d q/sm³" % (200 // 100), 3),
 ("Kütlənin BS vahidi hansıdır?",
  "Kütlənin BS vahidi kiloqramdır.",
  ["Kiloqram", "Metr", "Litr", "Dərəcə"], 1, None, 2),
 ("Suyun sıxlığı təxminən neçə q/sm³-dür?",
  "Suyun sıxlığı 1 q/sm³-dür.",
  ["1", "10", "100", "0,1"], 1, str(1), 3),
 ("Normal şəraitdə su neçə dərəcədə qaynayır?",
  "Su 100°C-də qaynayır.",
  ["100°C-də", "50°C-də", "0°C-də", "1 000°C-də"], 1, None, 2),
 ("Su neçə dərəcədə donur?",
  "Su 0°C-də donub buza çevrilir.",
  ["0°C-də", "100°C-də", "−100°C-də", "10°C-də"], 1, None, 2),
 ("Menzurkaya salınmış cismin həcmi necə təyin olunur?",
  "Mayenin səviyyəsinin nə qədər qalxdığına görə.",
  ["Mayenin səviyyəsinin dəyişməsinə görə", "Cismin rənginə görə",
   "Cismin səsinə görə", "Təyin etmək olmur"], 1, None, 3),
],
"fiz-6-hereket": [
 ("Mexaniki hərəkət nədir?",
  "Cismin başqa cisimlərə nəzərən vəziyyətinin dəyişməsidir.",
  ["Cismin yerdəyişməsi", "Cismin rənginin dəyişməsi",
   "Cismin əriməsi", "Cismin yanması"], 1, None, 2),
 ("Cisimləri Yerə tərəf çəkən qüvvə necə adlanır?",
  "Bu, cazibə (qravitasiya) qüvvəsidir.",
  ["Cazibə qüvvəsi", "Külək qüvvəsi", "Maqnit qüvvəsi",
   "Səs qüvvəsi"], 1, None, 2),
 ("Günəş sisteminin mərkəzində hansı göy cismi durur?",
  "Mərkəzdə Günəş yerləşir, planetlər onun ətrafında dövr edir.",
  ["Günəş", "Yer", "Ay", "Mars"], 1, None, 1),
 ("Sürtünmə ilə elektriklənmiş daraq kağız qırıntılarına necə "
  "təsir edir?",
  "Elektriklənmiş cisim yüngül cisimləri cəzb edir.",
  ["Cəzb edir", "İtələyir", "Yandırır", "Heç cür"], 1, None, 2),
 ("Maqnitin ən güclü cəzb edən hissələri necə adlanır?",
  "Maqnitin qütbləri ən güclü hissələridir.",
  ["Qütblər", "Ortası", "Alt hissəsi", "Səthi"],
  1, None, 3),
 ("Elektrik cərəyanı nədir?",
  "Yüklü hissəciklərin istiqamətlənmiş hərəkətidir.",
  ["Yüklü hissəciklərin istiqamətlənmiş hərəkəti",
   "Suyun axını", "Küləyin əsməsi", "İşığın yayılması"],
  1, None, 3),
 ("Enerji nədir?",
  "Cismin iş görmə qabiliyyətidir.",
  ["İş görmə qabiliyyəti", "Cismin rəngi", "Cismin adı",
   "Cismin forması"], 1, None, 2),
 ("Hərəkət edən cismin malik olduğu enerji necə adlanır?",
  "Hərəkət enerjisi kinetik enerjidir.",
  ["Kinetik enerji", "Potensial enerji", "Maqnit enerjisi",
   "Enerjisi olmur"], 1, None, 3),
 ("Elektrik cərəyanını keçirən materiallar necə adlanır?",
  "Cərəyanı keçirənlər naqillər (keçiricilər) adlanır.",
  ["Keçiricilər", "İzolyatorlar", "Maqnitlər", "Güzgülər"],
  1, None, 3),
 ("Toxunma ilə baş verən qarşılıqlı təsirə misal hansıdır?",
  "Topa ayaqla vurulan zərbə toxunma təsiridir.",
  ["Topa vurulan zərbə", "Ayın Yeri cəzb etməsi",
   "Maqnitin uzaqdan təsiri", "Günəşin istiliyi"], 1, None, 2),
],
# ======================== BIOLOGIYA 6 =================================
"bio-6-tedqiqat": [
 ("Biologiya elmi nəyi öyrənir?",
  "Biologiya canlı orqanizmləri öyrənir.",
  ["Canlı orqanizmləri", "Daşları", "Ulduzları", "Rəqəmləri"],
  1, None, 1),
 ("Canlıların əsas xüsusiyyətləri hansılardır?",
  "Qidalanma, tənəffüs, çoxalma, böyümə canlılara xasdır.",
  ["Qidalanma, tənəffüs, çoxalma", "Yalnız hərəkət",
   "Yalnız səs çıxarma", "Parlaqlıq"], 1, None, 2),
 ("Canlıların təsnifatında ən böyük vahidlərdən biri hansıdır?",
  "Canlılar aləmlərə bölünür.",
  ["Aləm", "Küçə", "Otaq", "Səhifə"], 1, None, 3),
 ("İnsan təsnifat sistemində hansı aləmə aid edilir?",
  "İnsan heyvanlar aləminə aiddir.",
  ["Heyvanlar aləminə", "Bitkilər aləminə", "Göbələklərə",
   "Bakteriyalara"], 1, None, 3),
 ("Bitkiləri öyrənən elm sahəsi necə adlanır?",
  "Bitkiləri botanika öyrənir.",
  ["Botanika", "Zoologiya", "Coğrafiya", "Tarix"], 1, None, 2),
 ("Heyvanları öyrənən elm necə adlanır?",
  "Heyvanları zoologiya öyrənir.",
  ["Zoologiya", "Botanika", "Fizika", "Astronomiya"],
  1, None, 2),
 ("Canlını cansızdan fərqləndirən əsas əlamət hansıdır?",
  "Canlılar qidalanır, böyüyür və çoxalır.",
  ["Qidalanıb çoxalması", "Ağır olması", "Rəngli olması",
   "Böyük olması"], 1, None, 2),
 ("Göbələklər təsnifatda hansı yeri tutur?",
  "Göbələklər ayrıca aləm təşkil edir.",
  ["Ayrıca aləmdir", "Bitkidir", "Heyvandır", "Mineraldır"],
  1, None, 3),
 ("Təbiəti öyrənərkən hansı üsullardan istifadə olunur?",
  "Müşahidə və təcrübə əsas üsullardır.",
  ["Müşahidə və təcrübədən", "Yalnız yuxudan",
   "Yalnız təxmindən", "Fal açmaqdan"], 1, None, 2),
 ("Bakteriyaları görmək üçün hansı cihaz lazımdır?",
  "Bakteriyalar yalnız mikroskopla görünür.",
  ["Mikroskop", "Teleskop", "Kompas", "Termometr"], 1, None, 2),
],
"bio-6-huceyre": [
 ("Bütün canlıların quruluş vahidi nədir?",
  "Canlılar hüceyrələrdən təşkil olunub.",
  ["Hüceyrə", "Daş", "Qum dənəsi", "Damcı"], 1, None, 1),
 ("Hüceyrənin idarəedici hissəsi hansıdır?",
  "Hüceyrəni nüvə idarə edir.",
  ["Nüvə", "Qılaf", "Kölgə", "Su"], 1, None, 2),
 ("Nüvəsi olmayan orqanizmlər necə adlanır?",
  "Nüvəsizlər prokariotlardır (məs. bakteriyalar).",
  ["Prokariotlar", "Eukariotlar", "Nəhənglər", "Parazitlər"],
  1, None, 3),
 ("Bakteriyalar hansı orqanizmlərdəndir?",
  "Bakteriyalar birhüceyrəli orqanizmlərdir.",
  ["Birhüceyrəli", "Çoxhüceyrəli", "Cansız", "Bitki"],
  1, None, 2),
 ("Virusların əsas xüsusiyyəti nədir?",
  "Viruslar yalnız canlı hüceyrədə çoxala bilir.",
  ["Yalnız canlı hüceyrədə çoxalır", "Torpaqda böyüyür",
   "Fotosintez edir", "Sərbəst qidalanır"], 1, None, 3),
 ("Hüceyrələr necə çoxalır?",
  "Hüceyrələr bölünmə yolu ilə çoxalır.",
  ["Bölünmə yolu ilə", "Yanma ilə", "Donma ilə",
   "Çoxalmır"], 1, None, 2),
 ("Çoxhüceyrəli orqanizmə misal hansıdır?",
  "İnsan milyardlarla hüceyrədən ibarətdir.",
  ["İnsan", "Bakteriya", "Amöb", "İnfuzor"], 1, None, 2),
 ("Quruluşca oxşar hüceyrələrin birliyi necə adlanır?",
  "Oxşar hüceyrələr toxuma əmələ gətirir.",
  ["Toxuma", "Qrup", "Dəstə", "Sinif"], 1, None, 2),
 ("Bitkidə su və qida maddələrini daşıyan toxuma hansıdır?",
  "Daşımanı ötürücü toxuma yerinə yetirir.",
  ["Ötürücü toxuma", "Örtük toxuması", "Mexaniki toxuma",
   "Törədici toxuma"], 1, None, 3),
 ("Birgə iş görən orqanlar nəyi əmələ gətirir?",
  "Orqanlar orqanlar sistemində birləşir.",
  ["Orqanlar sistemini", "Toxumanı", "Hüceyrəni", "Aləmi"],
  1, None, 2),
],
"bio-6-vegetativ": [
 ("Bitkinin vegetativ orqanları hansılardır?",
  "Kök, gövdə və yarpaq vegetativ orqanlardır.",
  ["Kök, gövdə, yarpaq", "Çiçək və meyvə",
   "Yalnız toxum", "Ləçəklər"], 1, None, 2),
 ("Kökün əsas funksiyaları hansılardır?",
  "Bitkini torpağa bərkidir, su və mineralları çəkir.",
  ["Bərkitmək və su çəkmək", "Fotosintez etmək",
   "Çiçək açmaq", "Meyvə vermək"], 1, None, 2),
 ("Yarpağın əsas funksiyası nədir?",
  "Yarpaqda fotosintez gedir — qida hazırlanır.",
  ["Fotosintez", "Torpağı bərkitmək", "Toxum yaymaq",
   "Su saxlamaq"], 1, None, 2),
 ("Fotosintez üçün nə lazımdır?",
  "İşıq, su və karbon qazı lazımdır.",
  ["İşıq, su və karbon qazı", "Qaranlıq və soyuq",
   "Yalnız torpaq", "Yalnız külək"], 1, None, 2),
 ("Yarpağa yaşıl rəng verən maddə hansıdır?",
  "Yaşıllığı xlorofil verir.",
  ["Xlorofil", "Nişasta", "Duz", "Şəkər"], 1, None, 2),
 ("Gövdənin funksiyası nədir?",
  "Maddələri daşıyır, yarpaq və çiçəkləri saxlayır.",
  ["Maddələri daşımaq və saxlamaq", "Toxum əmələ gətirmək",
   "Torpağı yumşaltmaq", "Heç bir funksiyası yoxdur"],
  1, None, 2),
 ("Kartof yumrusu hansı orqanın şəkildəyişməsidir?",
  "Yumru yeraltı zoğun (gövdənin) şəkildəyişməsidir.",
  ["Gövdənin (zoğun)", "Kökün", "Yarpağın", "Çiçəyin"],
  1, None, 3),
 ("Yerkökü hansı orqanın şəkildəyişməsidir?",
  "Yerkökü kökümeyvədir — kökün şəkildəyişməsidir.",
  ["Kökün", "Gövdənin", "Yarpağın", "Meyvənin"], 1, None, 3),
 ("Tumurcuq nədir?",
  "Tumurcuq rüşeym halında olan zoğdur.",
  ["Rüşeym halında zoğ", "Yetişmiş meyvə", "Quru yarpaq",
   "Kök ucu"], 1, None, 3),
 ("Kök sistemləri hansı növlərə ayrılır?",
  "Mil kök və saçaqlı kök sistemləri var.",
  ["Mil və saçaqlı", "Uzun və qısa", "İsti və soyuq",
   "Yaş və quru"], 1, None, 3),
],
"bio-6-generativ": [
 ("Bitkinin generativ (çoxalma) orqanları hansılardır?",
  "Çiçək, meyvə və toxum çoxalma orqanlarıdır.",
  ["Çiçək, meyvə, toxum", "Kök və gövdə",
   "Yalnız yarpaq", "Tumurcuqlar"], 1, None, 2),
 ("Çiçəyin parlaq rəngli hissəsi necə adlanır?",
  "Parlaq hissə ləçəklərdir (tac).",
  ["Ləçəklər", "Kök", "Gövdə", "Qabıq"], 1, None, 2),
 ("Tozlanma nədir?",
  "Tozcuğun dişiciyin ağzına düşməsidir.",
  ["Tozcuğun dişiciyə düşməsi", "Yarpağın tökülməsi",
   "Kökün böyüməsi", "Meyvənin yetişməsi"], 1, None, 3),
 ("Tozlanmada hansı həşərat mühüm rol oynayır?",
  "Arılar çiçəkdən-çiçəyə tozcuq daşıyır.",
  ["Arı", "Qarışqa yuvası", "Hörümçək", "Milçək sürfəsi"],
  1, None, 2),
 ("Toxumun içərisində nə yerləşir?",
  "Toxumda gələcək bitkinin rüşeymi var.",
  ["Rüşeym", "Daş", "Su damcısı", "Torpaq"], 1, None, 2),
 ("Meyvə çiçəyin hansı hissəsindən əmələ gəlir?",
  "Meyvə dişiciyin yumurtalığından əmələ gəlir.",
  ["Dişiciyin yumurtalığından", "Ləçəkdən", "Kasacıqdan",
   "Saplaqdan"], 1, None, 3),
 ("Hansı meyvə şirəli meyvədir?",
  "Albalı şirəli meyvədir; fındıq, qoz, paxla qurudur.",
  ["Albalı", "Fındıq", "Qoz", "Paxla"], 1, None, 2),
 ("Çiçək qrupu nədir?",
  "Xırda çiçəklərin bir yerdə toplanmasıdır.",
  ["Çiçəklərin birgə yerləşməsi", "Yarpaq dəstəsi",
   "Kök topası", "Meyvə qutusu"], 1, None, 3),
 ("Toxumlar təbiətdə necə yayılır?",
  "Külək, su və heyvanlar toxumları yayır.",
  ["Külək, su və heyvanlarla", "Yalnız insan əli ilə",
   "Yayılmır", "Telefon ilə"], 1, None, 2),
 ("Quru meyvəyə misal hansıdır?",
  "Fındıq quru meyvədir.",
  ["Fındıq", "Albalı", "Qarpız", "Pomidor"], 1, None, 2),
],
"bio-6-hereket-qida": [
 ("Heyvanlarda dayaq funksiyasını nə yerinə yetirir?",
  "Bədənə dayağı skelet verir.",
  ["Skelet", "Dəri", "Tük", "Quyruq"], 1, None, 2),
 ("Balıqlar nə ilə hərəkət edir?",
  "Balıqlar üzgəclərlə üzür.",
  ["Üzgəclərlə", "Qanadlarla", "Ayaqlarla", "Əllərlə"],
  1, None, 1),
 ("Bitkilər qidasını necə əldə edir?",
  "Fotosintez yolu ilə özləri hazırlayır.",
  ["Özləri hazırlayır (fotosintez)", "Ov edir",
   "Mağazadan alır", "Başqa bitkiləri yeyir"], 1, None, 2),
 ("Heyvanlar tənəffüs zamanı hansı qazı qəbul edir?",
  "Tənəffüsdə oksigen qəbul olunur.",
  ["Oksigeni", "Karbon qazını", "Heliumu", "Buxarı"], 1, None, 2),
 ("Balıqlar suda nə ilə tənəffüs edir?",
  "Balıqlar qəlsəmələrlə tənəffüs edir.",
  ["Qəlsəmələrlə", "Ağciyərlərlə", "Burunla", "Üzgəclərlə"], 1, None, 2),
 ("Otyeyən heyvana misal hansıdır?",
  "İnək otla qidalanır.",
  ["İnək", "Canavar", "Qartal", "Tülkü"], 1, None, 1),
 ("Ətlə qidalanan heyvan hansıdır?",
  "Şir yırtıcıdır — ətlə qidalanır.",
  ["Şir", "İnək", "Dovşan", "Keçi"], 1, None, 1),
 ("İnsanın tənəffüs orqanı hansıdır?",
  "İnsan ağciyərlərlə tənəffüs edir.",
  ["Ağciyərlər", "Mədə", "Ürək", "Böyrəklər"], 1, None, 2),
 ("Bitkilər tənəffüs edirmi?",
  "Bəli, bitkilər sutka boyu tənəffüs edir.",
  ["Bəli, daim tənəffüs edir", "Xeyr, heç vaxt",
   "Yalnız qışda", "Yalnız gündüz"],
  1, None, 3),
 ("Qidalanma orqanizmə nə verir?",
  "Enerji və inkişaf üçün maddələr verir.",
  ["Enerji və qida maddələri", "Yalnız rəng",
   "Yalnız yuxu", "Heç nə"], 1, None, 2),
],
"bio-6-dasinma-coxalma": [
 ("İnsanda qanı hərəkət etdirən orqan hansıdır?",
  "Qanı ürək hərəkət etdirir.",
  ["Ürək", "Mədə", "Ağciyər", "Dalaq"], 1, None, 1),
 ("Bitkidə su hansı istiqamətdə hərəkət edir?",
  "Su kökdən yarpaqlara doğru qalxır.",
  ["Kökdən yarpaqlara", "Yarpaqdan kökə",
   "Yalnız gövdə boyu aşağı", "Hərəkət etmir"], 1, None, 3),
 ("İfrazat nədir?",
  "Lazımsız maddələrin orqanizmdən xaric edilməsidir.",
  ["Lazımsız maddələrin xaric edilməsi", "Qida qəbulu",
   "Tənəffüs", "Hərəkət"], 1, None, 3),
 ("Toxumun cücərməsi üçün hansı şərtlər vacibdir?",
  "Su, hava və istilik lazımdır.",
  ["Su, hava və istilik", "Yalnız qaranlıq",
   "Yalnız duz", "Səs-küy"], 1, None, 2),
 ("Vegetativ çoxalma nədir?",
  "Bitkinin vegetativ orqanları ilə çoxalmasıdır.",
  ["Vegetativ orqanlarla çoxalma", "Toxumla çoxalma",
   "Yumurta ilə çoxalma", "Bölünmə ilə çoxalma"], 1, None, 3),
 ("Çiyələk hansı orqanla vegetativ çoxalır?",
  "Çiyələk bığcıqlarla çoxalır.",
  ["Bığcıqlarla", "Toxumla yalnız", "Yarpaqla", "Çiçəklə"],
  1, None, 3),
 ("Kəpənəyin inkişaf mərhələləri hansı ardıcıllıqladır?",
  "Yumurta → tırtıl → pup → kəpənək.",
  ["Yumurta, tırtıl, pup, kəpənək", "Kəpənək, pup, tırtıl",
   "Tırtıl, yumurta, kəpənək", "Pup, yumurta, tırtıl"],
  1, None, 3),
 ("Qanın funksiyalarından biri hansıdır?",
  "Qan qida və oksigen daşıyır.",
  ["Qida və oksigen daşımaq", "Sümük əmələ gətirmək",
   "Görməni təmin etmək", "Səs çıxarmaq"], 1, None, 2),
 ("İnsanda tər hansı orqan vasitəsilə xaric olur?",
  "Tər dəri vasitəsilə ifraz olunur.",
  ["Dəri ilə", "Saçla", "Dırnaqla", "Dişlə"], 1, None, 2),
 ("Heyvanlarda inkişaf necə gedir?",
  "Balalar böyüyərək yetkin fərdə çevrilir.",
  ["Bala böyüyüb yetkinləşir", "Heyvanlar dəyişmir",
   "Yalnız kiçilirlər", "İnkişaf olmur"], 1, None, 2),
],
"bio-6-muhit": [
 ("Orqanizmin yaşadığı şərait necə adlanır?",
  "Orqanizmi əhatə edən şərait yaşayış mühitidir.",
  ["Yaşayış mühiti", "Mənzil", "Sinif", "Qab"], 1, None, 2),
 ("Hansılar cansız təbiət amilləridir?",
  "İşıq, temperatur, rütubət cansız amillərdir.",
  ["İşıq, temperatur, rütubət", "Bitkilər və heyvanlar",
   "İnsanlar", "Bakteriyalar"], 1, None, 3),
 ("Dəvənin səhra həyatına uyğunlaşması nədir?",
  "Dəvə uzun müddət susuz qala bilir.",
  ["Susuzluğa davamlılıq", "Suda üzmək",
   "Ağacda yaşamaq", "Uçmaq"], 1, None, 2),
 ("Qışda xəzi ağaran heyvan hansıdır?",
  "Ağ dovşan qışda ağarır — qarda gizlənir.",
  ["Ağ dovşan", "İnək", "At", "Qoyun"], 1, None, 2),
 ("Təbii birlik nədir?",
  "Bir ərazidə birgə yaşayan orqanizmlər qrupudur (meşə, göl).",
  ["Birgə yaşayan orqanizmlər qrupu", "Bir heyvan",
   "Bir daş", "Bir bulud"], 1, None, 3),
 ("Meşələrin qırılması nəyə səbəb olur?",
  "Canlıların yaşayış yeri məhv olur.",
  ["Canlıların yaşayış yerinin itməsinə", "Havanın təmizlənməsinə",
   "Heyvanların artmasına", "Heç nəyə"], 1, None, 2),
 ("Qida zənciri nədir?",
  "Canlıların qidalanma ardıcıllığıdır.",
  ["Canlıların qidalanma ardıcıllığı", "Mağaza növbəsi",
   "Bitki kolleksiyası", "Heyvan oyunu"], 1, None, 3),
 ("«Ot → dovşan → canavar» sırası nəyə misaldır?",
  "Bu, qida zənciridir.",
  ["Qida zəncirinə", "Əlifba sırasına", "Say ardıcıllığına",
   "Təsnifata"], 1, None, 2),
 ("Su hövzələrinin çirklənməsi kimlərə zərər verir?",
  "Su canlılarına və insanlara zərər verir.",
  ["Su canlılarına və insana", "Heç kimə",
   "Yalnız daşlara", "Yalnız qayıqlara"], 1, None, 2),
 ("«Qırmızı kitab»a hansı canlılar daxil edilir?",
  "Nəsli kəsilmək təhlükəsində olan növlər.",
  ["Nəsli kəsilməkdə olanlar", "Ən çoxsaylılar",
   "Ən böyüklər", "Ev heyvanları"], 1, None, 3),
],
"bio-6-rol": [
 ("Bitkilər fotosintez zamanı atmosferə hansı qazı verir?",
  "Bitkilər oksigen ifraz edir.",
  ["Oksigen", "Karbon qazı", "Tüstü", "Metan"], 1, None, 2),
 ("Dərman bitkisinə misal hansıdır?",
  "Çobanyastığı dərman bitkisidir.",
  ["Çobanyastığı", "Kaktus", "Qamış", "Mamır"], 1, None, 2),
 ("Bal arısı insana nə verir?",
  "Arıdan bal və mum alınır.",
  ["Bal və mum", "Süd", "Yumurta", "Yun"], 1, None, 1),
 ("Hansı bitki mədəni bitkidir?",
  "Buğdanı insan əkib-becərir.",
  ["Buğda", "Yovşan", "Qanqal", "Gicitkən"], 1, None, 2),
 ("Ev heyvanları insana nə verir?",
  "Süd, ət, yumurta, yun kimi məhsullar verir.",
  ["Qida və digər məhsullar", "Heç nə",
   "Yalnız səs-küy", "Yalnız xəstəlik"], 1, None, 1),
 ("Yun hansı heyvandan alınır?",
  "Yun qoyundan qırxılır.",
  ["Qoyundan", "Toyuqdan", "Balıqdan", "Arıdan"], 1, None, 1),
 ("İpəkqurdu insana nə verir?",
  "İpəkqurdunun baramasından ipək sapı alınır.",
  ["İpək sapı", "Bal", "Süd", "Dəri"], 1, None, 3),
 ("Bağlarda zərərverici həşəratları məhv edən canlılar "
  "hansılardır?",
  "Quşlar zərərvericiləri yeyərək bağları qoruyur.",
  ["Quşlar", "Zərərvericilərin özləri", "Daşlar", "Küləklər"],
  1, None, 2),
 ("Bitkilərin insan üçün əhəmiyyətlərindən biri nədir?",
  "Bitkilər əsas qida mənbəyidir.",
  ["Qida mənbəyidir", "Yalnız kölgədir",
   "Yalnız bəzəkdir", "Əhəmiyyəti yoxdur"], 1, None, 2),
 ("Pambıqdan nə istehsal olunur?",
  "Pambıqdan parça toxunur.",
  ["Parça", "Şüşə", "Dəmir", "Plastik"], 1, None, 2),
],
# ======================== COGRAFIYA 6 =================================
"cog-6-mekan": [
 ("Coğrafiya elmi nəyi öyrənir?",
  "Yer səthini, təbiəti və əhalini öyrənir.",
  ["Yer səthini və təbiəti", "Yalnız keçmişi",
   "Yalnız rəqəmləri", "Yalnız dilləri"], 1, None, 1),
 ("Məkan dedikdə nə nəzərdə tutulur?",
  "Bizi əhatə edən və yaşadığımız ərazi.",
  ["Yaşadığımız ərazi", "Yalnız otaq", "Yalnız kosmos",
   "Yalnız dəniz"], 1, None, 2),
 ("Lokal (yerli) məkana misal hansıdır?",
  "Yaşadığımız məhəllə lokal məkandır.",
  ["Yaşadığımız məhəllə", "Bütün Yer kürəsi",
   "Günəş sistemi", "Okean"], 1, None, 2),
 ("Qlobal məkan nədir?",
  "Bütöv Yer kürəsi qlobal məkandır.",
  ["Bütün Yer kürəsi", "Bir küçə", "Bir ev", "Bir sinif"],
  1, None, 2),
 ("Azərbaycan hansı materikdə yerləşir?",
  "Azərbaycan Avrasiya materikindədir.",
  ["Avrasiyada", "Afrikada", "Amerikada", "Avstraliyada"],
  1, None, 2),
 ("Yaşadığımız məkanı hansı əlamətlər fərqləndirir?",
  "Relyefi, təbiəti və əhalisi ilə fərqlənir.",
  ["Relyefi, təbiəti, əhalisi", "Yalnız adı",
   "Yalnız rəngi", "Heç nə ilə"], 1, None, 3),
 ("Məkanın miqyası nəyi bildirir?",
  "Ərazinin böyüklük dərəcəsini bildirir.",
  ["Ərazinin böyüklüyünü", "Havanın istiliyini",
   "Əhalinin adlarını", "Suyun dadını"], 1, None, 3),
 ("«Ölkə» anlayışı hansı məkana aiddir?",
  "Ölkə bir dövlətin ərazisidir.",
  ["Dövlətin ərazisinə", "Bir otağa", "Bir planetə",
   "Bir ulduza"], 1, None, 2),
 ("Regional məkana misal hansıdır?",
  "Qafqaz bir regiondur.",
  ["Qafqaz", "Bir məktəb", "Bir həyət", "Bir mənzil"],
  1, None, 3),
 ("Məkanları öyrənmək nə üçün lazımdır?",
  "Ətraf aləmi tanımaq və düzgün istifadə etmək üçün.",
  ["Ətraf aləmi tanımaq üçün", "Yalnız qiymət almaq üçün",
   "Heç nə üçün", "Yalnız şəkil üçün"], 1, None, 2),
],
"cog-6-beledci": [
 ("Ərazinin şərti işarələrlə kiçildilmiş təsviri necə adlanır?",
  "Bu, plan və ya xəritədir.",
  ["Plan (xəritə)", "Şəkil", "Fotoalbom", "Kitab"], 1, None, 2),
 ("Miqyas nəyi göstərir?",
  "Məsafənin xəritədə neçə dəfə kiçildildiyini göstərir.",
  ["Məsafənin kiçilmə dərəcəsini", "Havanın istiliyini",
   "Əhalinin sayını", "Dağın hündürlüyünü"], 1, None, 2),
 ("Üfüqün əsas cəhətləri hansılardır?",
  "Şimal, cənub, şərq və qərb.",
  ["Şimal, cənub, şərq, qərb", "Yuxarı və aşağı",
   "Sağ və sol", "İrəli və geri"], 1, None, 2),
 ("Kompasın əqrəbi həmişə hansı cəhəti göstərir?",
  "Kompas əqrəbi şimalı göstərir.",
  ["Şimalı", "Cənubu", "Şərqi", "Qərbi"], 1, None, 2),
 ("Günəş hansı tərəfdən doğur?",
  "Günəş şərqdən doğur.",
  ["Şərqdən", "Qərbdən", "Şimaldan", "Cənubdan"], 1, None, 1),
 ("Xəritədə şimal adətən hansı tərəfdə göstərilir?",
  "Xəritənin yuxarısı şimaldır.",
  ["Yuxarıda", "Aşağıda", "Solda", "Sağda"], 1, None, 2),
 ("Xəritədəki şərti işarələr nə üçündür?",
  "Obyektləri (yol, çay, meşə) göstərmək üçün.",
  ["Obyektləri göstərmək üçün", "Bəzək üçün",
   "Rəngləmək üçün", "Heç nə üçün"], 1, None, 2),
 ("Qlobus xəritədən nə ilə üstündür?",
  "Yerin formasını təhrifsiz göstərir.",
  ["Yerin formasını düzgün göstərir", "Daha ucuzdur",
   "Cibə yerləşir", "Daha rənglidir"], 1, None, 3),
 ("Dağlar fiziki xəritədə hansı rənglə göstərilir?",
  "Dağlıq ərazilər qəhvəyi rənglə verilir.",
  ["Qəhvəyi", "Mavi", "Yaşıl", "Ağ"], 1, None, 2),
 ("Şimal yarımkürəsində günorta Günəş hansı tərəfdə olur?",
  "Günorta Günəş cənub tərəfdə olur.",
  ["Cənubda", "Şimalda", "Qərbdə", "Şərqdə"], 1, None, 3),
],
"cog-6-col": [
 ("Çöl tədqiqatı nədir?",
  "Təbiəti bilavasitə yerində öyrənməkdir.",
  ["Təbiəti yerində öyrənmək", "Evdə kitab oxumaq",
   "Televizora baxmaq", "Yuxu görmək"], 1, None, 2),
 ("Tədqiqata çıxarkən özünlə nə götürmək lazımdır?",
  "Bloknot, kompas və xəritə lazımdır.",
  ["Bloknot, kompas, xəritə", "Yalnız oyuncaq",
   "Televizor", "Çarpayı"], 1, None, 1),
 ("Hava müşahidəsində nələr qeyd olunur?",
  "Temperatur, külək və yağıntı qeyd olunur.",
  ["Temperatur, külək, yağıntı", "Yalnız quşların sayı",
   "Yalnız maşınlar", "Heç nə"], 1, None, 2),
 ("Küləyin istiqamətini hansı cihaz göstərir?",
  "Küləyin istiqamətini flüger göstərir.",
  ["Flüger", "Tərəzi", "Mikroskop", "Saat"], 1, None, 3),
 ("Yağıntının miqdarı hansı vahidlə ölçülür?",
  "Yağıntı millimetrlə ölçülür.",
  ["Millimetrlə", "Kiloqramla", "Metrlə", "Dərəcə ilə"], 1, None, 3),
 ("Müşahidə nəticələri harada qeyd olunur?",
  "Müşahidə gündəliyində (cədvəldə) qeyd olunur.",
  ["Müşahidə gündəliyində", "Yaddaşda qalır",
   "Qumun üstündə", "Heç yerdə"], 1, None, 2),
 ("Gün ərzində havanın temperaturu nə vaxt ən yüksək olur?",
  "Günortadan sonra temperatur maksimuma çatır.",
  ["Günortadan sonra", "Gecə yarısı", "Səhər tezdən",
   "Gün batan kimi"], 1, None, 3),
 ("Relyef müşahidəsində nəyə diqqət edilir?",
  "Ərazinin hündür-alçaqlığına baxılır.",
  ["Ərazinin hündür-alçaqlığına", "Mağaza qiymətlərinə",
   "Maşın markalarına", "Paltarlara"], 1, None, 2),
 ("Çayın axın sürətini sadə üsulla necə təyin etmək olar?",
  "Üzən əşyanın müəyyən məsafəni qət etmə vaxtı ilə.",
  ["Üzən əşyanın hərəkətini izləməklə", "Suyu dadmaqla",
   "Sahildə oturmaqla", "Təyin etmək olmaz"], 1, None, 3),
 ("Tədqiqat zamanı təbiətə münasibət necə olmalıdır?",
  "Təbiətə zərər vermədən öyrənmək lazımdır.",
  ["Zərər vermədən", "Budaqları qıraraq", "Zibil ataraq",
   "Yuvaları dağıdaraq"], 1, None, 1),
],
"cog-6-kainat": [
 ("Günəş sistemində neçə planet var?",
  "Günəş sistemində 8 planet var.",
  ["8", "9", "7", "12"], 1, None, 2),
 ("Yer Günəşdən neçənci planetdir?",
  "Yer Günəşdən üçüncü planetdir.",
  ["3-cü", "1-ci", "5-ci", "8-ci"], 1, None, 2),
 ("Yerə ən yaxın göy cismi hansıdır?",
  "Ay Yerə ən yaxın göy cismidir.",
  ["Ay", "Günəş", "Mars", "Venera"], 1, None, 2),
 ("Günəş hansı göy cismidir?",
  "Günəş ulduzdur.",
  ["Ulduz", "Planet", "Peyk", "Komet"], 1, None, 2),
 ("Günəş sisteminin ən böyük planeti hansıdır?",
  "Yupiter ən böyük planetdir.",
  ["Yupiter", "Yer", "Mars", "Merkuri"], 1, None, 3),
 ("«Qırmızı planet» adlandırılan planet hansıdır?",
  "Mars səthinin rənginə görə qırmızı planet adlanır.",
  ["Mars", "Venera", "Saturn", "Neptun"], 1, None, 2),
 ("Yer öz oxu ətrafında tam dövrü nə qədərə başa vurur?",
  "Bir dövr bir sutkaya (24 saata) başa gəlir.",
  ["24 saata", "1 ilə", "1 aya", "1 saata"], 1, None, 2),
 ("Ulduzlardan təşkil olunmuş nəhəng sistemlər necə adlanır?",
  "Ulduz sistemləri qalaktikalar adlanır.",
  ["Qalaktikalar", "Kometlər", "Peyklər", "Buludlar"],
  1, None, 3),
 ("Bizim qalaktikamız necə adlanır?",
  "Qalaktikamız Süd Yolu adlanır.",
  ["Süd Yolu", "Andromeda", "Qara dəlik", "Böyük Ayı"],
  1, None, 3),
 ("Günəşə ən yaxın planet hansıdır?",
  "Merkuri Günəşə ən yaxındır.",
  ["Merkuri", "Yer", "Yupiter", "Neptun"], 1, None, 3),
],
"cog-6-tebiet": [
 ("Yerin bərk qabığı necə adlanır?",
  "Bərk qabıq litosferdir.",
  ["Litosfer", "Hidrosfer", "Atmosfer", "Biosfer"],
  1, None, 3),
 ("Yerin su təbəqəsi necə adlanır?",
  "Su təbəqəsi hidrosferdir.",
  ["Hidrosfer", "Litosfer", "Atmosfer", "Stratosfer"],
  1, None, 3),
 ("Atmosfer nədir?",
  "Yeri əhatə edən hava təbəqəsidir.",
  ["Yerin hava təbəqəsi", "Yerin su təbəqəsi",
   "Dağ süxurları", "Meşə zolağı"], 1, None, 2),
 ("Canlıların yayıldığı təbəqə necə adlanır?",
  "Canlılar aləmi biosferi təşkil edir.",
  ["Biosfer", "Litosfer", "Kosmos", "Nüvə"], 1, None, 3),
 ("Vulkan püskürəndə yer səthinə nə axır?",
  "Yer səthinə lava axır.",
  ["Lava", "Süd", "Neft", "Buz"], 1, None, 2),
 ("Zəlzələ nədir?",
  "Yer qabığının titrəyişləridir.",
  ["Yer qabığının titrəməsi", "Küləyin əsməsi",
   "Yağışın yağması", "Suyun donması"], 1, None, 2),
 ("Dünyanın ən hündür dağ zirvəsi hansıdır?",
  "Everest (Comolunqma) — 8848 m.",
  ["Everest", "Bazardüzü", "Elbrus", "Alp"], 1, None, 2),
 ("Dünyanın ən böyük okeanı hansıdır?",
  "Sakit okean ən böyükdür.",
  ["Sakit okean", "Atlantik okean", "Hind okeanı",
   "Şimal Buzlu okean"], 1, None, 2),
 ("Çayın başlandığı yer necə adlanır?",
  "Çayın başlanğıcı mənbə adlanır.",
  ["Mənbə", "Mənsəb", "Sahil", "Körpü"], 1, None, 3),
 ("Küləyi yaradan əsas səbəb nədir?",
  "Havanın yerdəyişməsi (təzyiq fərqi) küləyi yaradır.",
  ["Havanın yerdəyişməsi", "Quşların uçuşu",
   "Maşınların hərəkəti", "Dənizin dadı"], 1, None, 3),
],
"cog-6-yurdumuz": [
 ("Azərbaycan hansı dənizin sahilində yerləşir?",
  "Ölkəmiz Xəzər dənizinin sahilindədir.",
  ["Xəzər", "Qara dəniz", "Aralıq dənizi", "Baltik"],
  1, None, 1),
 ("Azərbaycanın ən uzun çayı hansıdır?",
  "Kür ən uzun çayımızdır.",
  ["Kür", "Araz", "Samur", "Tərtər"], 1, None, 2),
 ("Azərbaycanın ən hündür zirvəsi hansıdır?",
  "Bazardüzü zirvəsi — 4466 m.",
  ["Bazardüzü", "Everest", "Elbrus", "Savalan"], 1, None, 2),
 ("Böyük Qafqaz dağları ölkəmizin hansı hissəsindədir?",
  "Böyük Qafqaz şimaldadır.",
  ["Şimalında", "Cənubunda", "Mərkəzində", "Şərq dənizində"],
  1, None, 2),
 ("Azərbaycan ərazisində dünyanın 11 iqlim tipindən neçəsi var?",
  "Ölkəmizdə 9 iqlim tipi müşahidə olunur.",
  ["9", "2", "11", "5"], 1, None, 3),
 ("Kür çayı hansı dənizə tökülür?",
  "Kür Xəzər dənizinə tökülür.",
  ["Xəzərə", "Qara dənizə", "Aralıq dənizinə", "Okeana"],
  1, None, 2),
 ("Naxçıvan Muxtar Respublikasının xüsusiyyəti nədir?",
  "Əsas ərazidən aralı yerləşən muxtar respublikadır.",
  ["Əsas ərazidən aralı yerləşir", "Dənizin ortasındadır",
   "Başqa materikdədir", "Şəhər deyil, kənddir"], 1, None, 3),
 ("Azərbaycan hansı vulkanların sayına görə dünyada öndədir?",
  "Palçıq vulkanlarının sayına görə birincidir.",
  ["Palçıq vulkanlarının", "Buz vulkanlarının",
   "Lava göllərinin", "Qeyzerlərin"], 1, None, 3),
 ("Araz çayı hansı çayın qoludur?",
  "Araz Kürün ən böyük qoludur.",
  ["Kürün", "Volqanın", "Nilin", "Dunayın"], 1, None, 2),
 ("Hirkan meşələrində qorunan nadir ağac hansıdır?",
  "Dəmirağac Hirkan meşələrinin nadir ağacıdır.",
  ["Dəmirağac", "Kaktus", "Palma", "Sekvoyya"], 1, None, 3),
],
"cog-6-dunya": [
 ("Dünyada neçə materik var?",
  "Altı materik var.",
  ["6", "5", "7", "4"], 1, None, 2),
 ("Ən böyük materik hansıdır?",
  "Avrasiya ən böyük materikdir.",
  ["Avrasiya", "Afrika", "Avstraliya", "Antarktida"],
  1, None, 2),
 ("Ən isti materik hansıdır?",
  "Afrika ən isti materikdir.",
  ["Afrika", "Antarktida", "Avrasiya", "Şimali Amerika"], 1, None, 2),
 ("Ən soyuq materik hansıdır?",
  "Antarktida buzla örtülü ən soyuq materikdir.",
  ["Antarktida", "Afrika", "Avstraliya", "Cənubi Amerika"],
  1, None, 2),
 ("Dünyanın ən uzun çayı hansıdır?",
  "Nil dünyanın ən uzun çayı sayılır.",
  ["Nil", "Volqa", "Kür", "Dunay"], 1, None, 3),
 ("Böyük Səhra hansı materikdədir?",
  "Böyük Səhra Afrikadadır.",
  ["Afrikada", "Avropada", "Antarktidada", "Avstraliyada"],
  1, None, 2),
 ("Dünya okeanı Yer səthinin təxminən nə qədərini tutur?",
  "Səthin təxminən 71%-ni (dörddə üçünü) su tutur.",
  ["Təxminən 71%-ni", "10%-ni", "Yarıdan azını", "99%-ni"],
  1, None, 3),
 ("Kenquru hansı materikdə yaşayır?",
  "Kenquru Avstraliyada yaşayır.",
  ["Avstraliyada", "Afrikada", "Avropada", "Antarktidada"],
  1, None, 2),
 ("Əhalisi ən çox olan qitə hansıdır?",
  "Asiya əhalisinə görə birincidir.",
  ["Asiya", "Avstraliya", "Antarktida", "Cənubi Amerika"],
  1, None, 3),
 ("Yer kürəsini qorumaq üçün insanlar nə etməlidir?",
  "Təbiətə qayğı ilə yanaşmalı, çirkləndirməməlidir.",
  ["Təbiətə qayğı ilə yanaşmalı", "Daha çox meşə qırmalı",
   "Suları çirkləndirməli", "Heç nə etməməli"], 1, None, 1),
],
}



#  Derinlesdirme: her movzuya 10 elave sual (#11-20).
ELAVE = {
"fiz-6-giris": [
 ("Temperaturu ölçən cihaz hansıdır?",
  "Temperatur termometrlə ölçülür.",
  ["Termometr", "Menzurka", "Tərəzi", "Saat"], 1, None, 1),
 ("Uzunluğu ölçmək üçün hansı alətdən istifadə olunur?",
  "Xətkeş (ölçü lenti) ilə.",
  ["Xətkeş", "Termometr", "Kompas", "Linza"], 1, None, 1),
 ("1 metr neçə santimetrdir?",
  "1 m = 100 sm.",
  ["100 sm", "10 sm", "1 000 sm", "60 sm"], 1, None, 2),
 ("Hansı hadisə fiziki yox, kimyəvi hadisədir?",
  "Yanma zamanı yeni maddə yaranır.",
  ["Kağızın yanması", "Buzun əriməsi", "Suyun buxarlanması",
   "Şüşənin sınması"], 1, None, 2),
 ("Ölçmə nəticəsi nə ilə birlikdə yazılmalıdır?",
  "Ədəd vahidlə birlikdə yazılır: 5 m.",
  ["Vahidi ilə", "Rənglə", "Şəkillə", "Heç nə ilə"],
  1, None, 2),
 ("Kütlə, uzunluq və zaman birlikdə necə adlanır?",
  "Bunlar fiziki kəmiyyətlərdir.",
  ["Fiziki kəmiyyətlər", "Fiziki cisimlər", "Hadisələr",
   "Cihazlar"], 1, None, 3),
 ("Yarım saat neçə dəqiqədir?",
  "60 : 2 = 30 dəqiqə.",
  ["30 dəqiqə", "15 dəqiqə", "45 dəqiqə", "60 dəqiqə"],
  1, None, 2),
 ("«Fizika» sözünün mənası nədir?",
  "Yunanca «fizis» — təbiət deməkdir.",
  ["Təbiət", "Hərəkət", "Ölçü", "İşıq"], 1, None, 2),
 ("Müşahidə ilə təcrübənin fərqi nədir?",
  "Təcrübədə şərait süni yaradılır və idarə olunur.",
  ["Təcrübədə şərait süni yaradılır", "Fərq yoxdur",
   "Müşahidə cihazsız olmur", "Təcrübə yalnız evdə olur"],
  1, None, 3),
 ("Kiçik uzunluqları ölçmək üçün hansı vahid işlənir?",
  "Millimetr kiçik uzunluq vahididir.",
  ["Millimetr", "Kilometr", "Ton", "Litr"], 1, None, 2),
],
"fiz-6-hereket": [
 ("Gedilən yol hansı vahidlə ölçülür?",
  "Yol uzunluq vahidi ilə — metrlə ölçülür.",
  ["Metrlə", "Saniyə ilə", "Kiloqramla", "Litrlə"],
  1, None, 2),
 ("Sürət nəyi göstərir?",
  "Vahid zamanda gedilən yolu.",
  ["Vahid zamanda gedilən yolu", "Cismin rəngini",
   "Cismin çəkisini", "Havanın temperaturunu"], 1, None, 2),
 ("Maqnit hansı metalı cəzb edir?",
  "Maqnit dəmiri (poladı) cəzb edir.",
  ["Dəmiri (poladı)", "Misi", "Alüminiumu", "Qızılı"],
  1, None, 2),
 ("Eyniadlı maqnit qütbləri bir-birinə necə təsir edir?",
  "Eyniadlı qütblər itələyir.",
  ["İtələyir", "Cəzb edir", "Təsir etmir", "Əridir"],
  1, None, 2),
 ("Şimal və cənub qütbləri qarşılaşanda nə baş verir?",
  "Müxtəlifadlı qütblər cəzb olunur.",
  ["Cəzb olunurlar", "İtələnirlər", "Qığılcım çıxır",
   "Heç nə olmur"], 1, None, 2),
 ("Elektrik cərəyanının mənbəyinə misal hansıdır?",
  "Batareya cərəyan mənbəyidir.",
  ["Batareya", "Şüşə", "Taxta", "Kağız"], 1, None, 2),
 ("Cərəyanı keçirməyən materiallar necə adlanır?",
  "Belə materiallar izolyatorlardır.",
  ["İzolyatorlar", "Keçiricilər", "Maqnitlər",
   "Yarımkeçiricilər yalnız"], 1, None, 3),
 ("Günəşin ətrafında fırlanan iri göy cisimləri hansılardır?",
  "Planetlər Günəş ətrafında fırlanır.",
  ["Planetlər", "Ulduzlar", "Qalaktikalar", "Buludlar"],
  1, None, 2),
 ("Hündürə qaldırılmış cismin enerjisi hansı enerjidir?",
  "Vəziyyətə görə potensial enerjidir.",
  ["Potensial enerji", "Kinetik enerji", "İstilik yalnız",
   "Səs enerjisi"], 1, None, 3),
 ("İşıq hansı mənbələrdən yayılır?",
  "Günəş, lampa kimi işıq mənbələrindən.",
  ["Günəş, lampa kimi mənbələrdən", "Yalnız güzgüdən",
   "Qaranlıqdan", "Daşlardan"], 1, None, 2),
],
"fiz-6-madde": [
 ("Sıxlığın BS-də vahidi hansıdır?",
  "kq/m³ ilə ölçülür.",
  ["kq/m³", "q/l", "m/san", "N/m"], 1, None, 3),
 ("Həcmi 50 sm³, sıxlığı 2 q/sm³ olan cismin kütləsi neçədir?",
  "m = ρ·V = 2 · 50 = 100 q.",
  ["100 q", "25 q", "52 q", "10 q"], 1, None, 3),
 ("Dəmir yolu relsləri arasında niyə boşluq saxlanılır?",
  "İstidə genişlənəndə əyilməsinlər deyə.",
  ["İstidə genişlənmə üçün", "Qənaət üçün",
   "Səs üçün", "Təsadüfən"], 1, None, 3),
 ("Diffuziya hansı halda daha sürətli gedir?",
  "Qazlarda molekullar sərbəstdir — diffuziya sürətlidir.",
  ["Qazlarda", "Bərk cisimlərdə", "Mayelərdə ən sürətli",
   "Heç birində"], 1, None, 3),
 ("Kütləni ölçən cihaz hansıdır?",
  "Kütlə tərəzi ilə ölçülür.",
  ["Tərəzi", "Menzurka", "Termometr", "Xətkeş"],
  1, None, 1),
 ("Qaynama zamanı mayenin temperaturu necə dəyişir?",
  "Qaynama müddətində temperatur sabit qalır.",
  ["Sabit qalır", "Daim artır", "Daim azalır",
   "Sıçrayışla dəyişir"], 1, None, 3),
 ("Buz suya çevriləndə hansı proses baş verir?",
  "Bərk haldan maye hala keçid — ərimə.",
  ["Ərimə", "Donma", "Buxarlanma", "Kondensasiya"],
  1, None, 2),
 ("1 litr neçə millilitrdir?",
  "1 l = 1000 ml.",
  ["1 000", "100", "10", "500"], 1, None, 2),
 ("Havanın əsas tərkib hissələri hansılardır?",
  "Azot və oksigen.",
  ["Azot və oksigen", "Yalnız oksigen", "Su buxarı yalnız",
   "Karbon qazı yalnız"], 1, None, 3),
 ("Şəkər suda həll olanda nə baş verir?",
  "Şəkər molekulları su molekulları arasına yayılır.",
  ["Molekullar suya yayılır", "Şəkər yox olur",
   "Su ağırlaşmır", "Yeni maddə yaranır"], 1, None, 3),
],
"fiz-6-materiya": [
 ("Maddənin qaz halının xüsusiyyəti nədir?",
  "Qaz verilən bütün qabı doldurur.",
  ["Bütün qabı doldurur", "Öz formasını saxlayır",
   "Sıxılmır", "Həmişə görünür"], 1, None, 2),
 ("Atom nədən təşkil olunub?",
  "Nüvə və onun ətrafındakı elektronlardan.",
  ["Nüvə və elektronlardan", "Yalnız işıqdan",
   "Su damcılarından", "Hüceyrələrdən"], 1, None, 2),
 ("Dəmir nəyə misaldır — maddəyə, yoxsa cismə?",
  "Dəmir maddədir, ondan cisimlər hazırlanır.",
  ["Maddəyə", "Cismə", "Hadisəyə", "Kəmiyyətə"],
  1, None, 2),
 ("Molekullar arasında nə var?",
  "Molekullar arasında boşluqlar var.",
  ["Boşluqlar", "Su", "Hava", "Heç nə, tam doludur"],
  1, None, 2),
 ("Buz, su və su buxarı nəyin müxtəlif hallarıdır?",
  "Eyni maddənin — suyun.",
  ["Eyni maddənin (suyun)", "Üç fərqli maddənin",
   "Qarışıqların", "Cisimlərin"], 1, None, 2),
 ("Maddənin halları hansılardır?",
  "Bərk, maye və qaz halları.",
  ["Bərk, maye, qaz", "İsti və soyuq", "Yaş və quru",
   "Ağır və yüngül"], 1, None, 1),
 ("Fiziki cisimlərə misal hansılardır?",
  "Qələm, stol, kitab — cisimlərdir.",
  ["Qələm, stol, kitab", "Su, dəmir, duz",
   "Yağış, külək", "İşıq, səs"], 1, None, 2),
 ("Kainatdakı bütün cisimlər nədən təşkil olunub?",
  "Hamısı maddədən təşkil olunub.",
  ["Maddədən", "Yalnız işıqdan", "Səsdən", "Rəngdən"],
  1, None, 2),
 ("Atomda mənfi yüklü hissəcik hansıdır?",
  "Elektron mənfi yüklüdür.",
  ["Elektron", "Proton", "Neytron", "Nüvə"], 1, None, 3),
 ("Ay planetdir, yoxsa peyk?",
  "Ay Yerin təbii peykidir.",
  ["Peykdir", "Planetdir", "Ulduzdur", "Kometadır"],
  1, None, 2),
],
"bio-6-tedqiqat": [
 ("Mikroskopla nəyi öyrənmək olar?",
  "Hüceyrələri və mikroorqanizmləri.",
  ["Hüceyrələri və mikroorqanizmləri", "Ulduzları",
   "Dağları", "Buludları"], 1, None, 2),
 ("Lupa nə üçün istifadə olunur?",
  "Kiçik obyektləri böyüdüb baxmaq üçün.",
  ["Kiçik obyektləri böyütmək üçün", "Səs yazmaq üçün",
   "İşıq yandırmaq üçün", "Ölçü çəkmək üçün"], 1, None, 1),
 ("Göbələkləri öyrənən elm necə adlanır?",
  "Mikologiya göbələkləri öyrənir.",
  ["Mikologiya", "Botanika", "Zoologiya", "Coğrafiya"],
  1, None, 3),
 ("Təcrübə aparmazdan əvvəl nə müəyyən edilir?",
  "Məqsəd və fərziyyə müəyyən olunur.",
  ["Məqsəd və fərziyyə", "Yalnız nəticə", "Qiymət",
   "Heç nə"], 1, None, 3),
 ("Bakteriyaları öyrənən elm hansıdır?",
  "Mikrobiologiya öyrənir.",
  ["Mikrobiologiya", "Astronomiya", "Riyaziyyat",
   "Tarix"], 1, None, 3),
 ("Canlılar hansı aləmlərə bölünür?",
  "Bitkilər, heyvanlar, göbələklər, bakteriyalar.",
  ["Bitkilər, heyvanlar, göbələklər, bakteriyalar",
   "Yalnız bitkilər və heyvanlar", "Sular və dağlar",
   "İsti və soyuq canlılar"], 1, None, 2),
 ("Herbari nədir?",
  "Qurudulmuş bitki kolleksiyasıdır.",
  ["Qurudulmuş bitki kolleksiyası", "Heyvan muzeyi",
   "Daş toplusu", "Şəkil albomu"], 1, None, 2),
 ("Canlıların böyüməsi nə deməkdir?",
  "Ölçüsünün və kütləsinin artması.",
  ["Ölçü və kütləsinin artması", "Rənginin dəyişməsi",
   "Yerinin dəyişməsi", "Səsinin artması"], 1, None, 2),
 ("«Biologiya» sözünün mənası nədir?",
  "Bios — həyat, loqos — elm: həyat haqqında elm.",
  ["Həyat haqqında elm", "Torpaq haqqında elm",
   "Ulduzlar haqqında elm", "Say haqqında elm"],
  1, None, 2),
 ("Bioloji müşahidənin nəticələri harada yazılır?",
  "Müşahidə gündəliyində (jurnalda).",
  ["Gündəlikdə (jurnalda)", "Yadda saxlanır yalnız",
   "Divarda", "Heç yerdə"], 1, None, 1),
],
"bio-6-huceyre": [
 ("Hüceyrəni xaricdən əhatə edən qat necə adlanır?",
  "Qılaf (membran) əhatə edir.",
  ["Qılaf (membran)", "Nüvə", "Sitoplazma", "Vakuol"],
  1, None, 2),
 ("Hüceyrənin daxilini dolduran yarımmaye maddə hansıdır?",
  "Sitoplazma doldurur.",
  ["Sitoplazma", "Qan", "Su yalnız", "Hava"],
  1, None, 2),
 ("Bitki hüceyrəsini heyvan hüceyrəsindən fərqləndirən nədir?",
  "Möhkəm qılaf və xloroplastlar.",
  ["Möhkəm qılaf və xloroplastlar", "Nüvənin olması",
   "Sitoplazmanın olması", "Bölünmə qabiliyyəti"],
  1, None, 3),
 ("İnfuzor-tərlik hansı orqanizmlərdəndir?",
  "Birhüceyrəli orqanizmdir.",
  ["Birhüceyrəlilərdən", "Çoxhüceyrəlilərdən",
   "Bitkilərdən", "Göbələklərdən"], 1, None, 3),
 ("Nüvəli hüceyrəyə malik orqanizmlər necə adlanır?",
  "Eukariotlar adlanır.",
  ["Eukariotlar", "Prokariotlar", "Viruslar",
   "Minerallar"], 1, None, 3),
 ("Toxumalar birləşərək nəyi əmələ gətirir?",
  "Orqanları əmələ gətirir.",
  ["Orqanları", "Hüceyrələri", "Molekulları",
   "Atomları"], 1, None, 2),
 ("Orqanlar sisteminə misal hansıdır?",
  "Həzm sistemi orqanlar sistemidir.",
  ["Həzm sistemi", "Bir hüceyrə", "Bir yarpaq",
   "Bir sümük"], 1, None, 2),
 ("Hüceyrənin bölünməsi nə üçün vacibdir?",
  "Orqanizmin böyüməsi və çoxalması üçün.",
  ["Böyümə və çoxalma üçün", "Yalnız rəng üçün",
   "Səs üçün", "Vacib deyil"], 1, None, 2),
 ("Virusları adi işıq mikroskopu ilə görmək olarmı?",
  "Xeyr — viruslar çox kiçikdir.",
  ["Xeyr, çox kiçikdirlər", "Bəli, asanlıqla",
   "Yalnız gecə olar", "Yalnız suda olar"], 1, None, 3),
 ("Sinir toxuması orqanizmdə nəyi təmin edir?",
  "Siqnalların ötürülməsini.",
  ["Siqnalların ötürülməsini", "Qidanın həzmini",
   "Sümüklərin bərkiməsini", "Dərinin rəngini"],
  1, None, 3),
],
"bio-6-vegetativ": [
 ("Mil kök sisteminə malik bitkiyə misal hansıdır?",
  "Lobyada mil kök sistemi var.",
  ["Lobya", "Buğda", "Soğan", "Qarğıdalı"], 1, None, 3),
 ("Saçaqlı kök sistemi hansı bitkilərdə olur?",
  "Taxıllarda: buğda, arpa, soğan.",
  ["Taxıllarda (buğda, soğan)", "Lobyada", "Palıdda",
   "Kaktusda"], 1, None, 3),
 ("Yarpağın damarları nə üçündür?",
  "Maddələri daşıyır və yarpağa möhkəmlik verir.",
  ["Maddələri daşımaq və möhkəmlik üçün", "Yalnız bəzək üçün",
   "Toxum yetişdirmək üçün", "Kök buraxmaq üçün"],
  1, None, 3),
 ("Soğanaq hansı orqanın şəkildəyişməsidir?",
  "Soğanaq qısalmış zoğdur.",
  ["Zoğun", "Kökün", "Yarpağın yalnız", "Çiçəyin"],
  1, None, 3),
 ("Fotosintez zamanı yarpaqda hansı üzvi maddə əmələ gəlir?",
  "Nişasta (şəkər) əmələ gəlir.",
  ["Nişasta (şəkər)", "Duz", "Dəmir", "Su"],
  1, None, 3),
 ("Su gövdə boyunca hansı hissə ilə yuxarı qalxır?",
  "Oduncağın boruları ilə.",
  ["Oduncaq borularla", "Qabıqla yalnız", "Özəklə yalnız",
   "Yarpaqla"], 1, None, 3),
 ("Yarpaq saplağı nə edir?",
  "Yarpağı gövdəyə birləşdirir.",
  ["Yarpağı gövdəyə birləşdirir", "Toxum yayır",
   "Çiçək açır", "Kök buraxır"], 1, None, 2),
 ("Kök su və mineral duzları haradan alır?",
  "Torpaqdan alır.",
  ["Torpaqdan", "Havadan", "Günəşdən", "Yarpaqdan"],
  1, None, 1),
 ("Bitkinin boy atması əsasən hansı hissələrdən gedir?",
  "Tumurcuqdan və kök ucundan.",
  ["Tumurcuq və kök ucundan", "Yarpağın ortasından",
   "Qabıqdan", "Toxumdan yalnız"], 1, None, 3),
 ("Payızda yarpaqların tökülməsi bitkiyə nə verir?",
  "Qışda suyun itkisindən qoruyur.",
  ["Suyun itkisindən qorunma", "Daha çox meyvə",
   "Yeni kök", "Heç nə"], 1, None, 3),
],
"bio-6-generativ": [
 ("Çiçəyin erkəkciyi nə hazırlayır?",
  "Erkəkcik tozcuq hazırlayır.",
  ["Tozcuq", "Toxum", "Meyvə", "Nektar yalnız"],
  1, None, 2),
 ("Dişiciyin hissələri hansılardır?",
  "Ağızcıq, sütuncuq və yumurtalıq.",
  ["Ağız, sütuncuq, yumurtalıq", "Ləçək və kasacıq",
   "Kök və gövdə", "Saplaq və qın"], 1, None, 3),
 ("Həşəratla tozlanan çiçəklər adətən necə olur?",
  "İri, ətirli və parlaq rəngli olur.",
  ["İri, ətirli və parlaq", "Görünməz", "Qoxusuz və solğun",
   "Yarpaqsız"], 1, None, 3),
 ("Mayalanmadan sonra yumurtacıqdan nə əmələ gəlir?",
  "Yumurtacıqdan toxum yaranır.",
  ["Toxum", "Yarpaq", "Kök", "Ləçək"], 1, None, 3),
 ("Toxum cücərəndə əvvəlcə hansı orqan çıxır?",
  "Əvvəlcə rüşeym kökcüyü çıxır.",
  ["Rüşeym kökcüyü", "Çiçək", "Meyvə", "Budaq"],
  1, None, 3),
 ("Şirəli meyvələrə misal hansılardır?",
  "Üzüm, pomidor şirəli meyvələrdir.",
  ["Üzüm, pomidor", "Fındıq, qoz", "Buğda dəni",
   "Palıd qozası"], 1, None, 2),
 ("Gilas və zoğal meyvələrinin daxilində nə olur?",
  "Bərk çəyirdək olur.",
  ["Çəyirdək", "Çoxlu xırda toxum", "Heç nə",
   "Yalnız şirə"], 1, None, 2),
 ("Günəbaxanın çiçək qrupu necə adlanır?",
  "Səbət çiçək qrupudur.",
  ["Səbət", "Sünbül", "Salxım", "Çətir"], 1, None, 3),
 ("Quşlar toxumların yayılmasına necə kömək edir?",
  "Meyvələri yeyib toxumları başqa yerə daşıyır.",
  ["Meyvələri yeyib toxumları daşıyır", "Toxumları əkirlər",
   "Toxumları məhv edirlər", "Kömək etmirlər"],
  1, None, 2),
 ("Həm erkəkciyi, həm dişiciyi olan çiçək necə adlanır?",
  "İkicinsli çiçək adlanır.",
  ["İkicinsli", "Təkcinsli", "Cinssiz", "Yarımçıq"],
  1, None, 3),
],
"bio-6-hereket-qida": [
 ("Quşların uçuşunu təmin edən orqanlar hansılardır?",
  "Qanadlar uçuşu təmin edir.",
  ["Qanadlar", "Üzgəclər", "Buynuzlar", "Caynaqlar yalnız"],
  1, None, 1),
 ("İlanlar necə hərəkət edir?",
  "Sürünərək hərəkət edir.",
  ["Sürünərək", "Tullanaraq", "Uçaraq", "Üzərək yalnız"],
  1, None, 1),
 ("Həm bitki, həm heyvan mənşəli qida yeyən heyvanlar necə adlanır?",
  "Hərşeyyeyənlər adlanır.",
  ["Hərşeyyeyənlər", "Otyeyənlər", "Ətyeyənlər",
   "Qidasızlar"], 1, None, 2),
 ("Bitkilərdə hərəkət varmı?",
  "Bəli — günəbaxan günəşə tərəf dönür.",
  ["Bəli, yavaş hərəkətlər var", "Xeyr, heç vaxt",
   "Yalnız gecə", "Yalnız suda"], 1, None, 3),
 ("Yaşıl bitkilər qidanı hansı prosesdə hazırlayır?",
  "Fotosintez prosesində.",
  ["Fotosintezdə", "Tənəffüsdə", "Buxarlanmada",
   "Cücərmədə"], 1, None, 2),
 ("Soxulcan torpaqda necə hərəkət edir?",
  "Bədən əzələlərini yığıb-açmaqla.",
  ["Bədən əzələlərini yığıb-açmaqla", "Qanadla",
   "Üzgəclə", "Ayaqları ilə"], 1, None, 3),
 ("Yırtıcı quşa misal hansıdır?",
  "Qartal yırtıcı quşdur.",
  ["Qartal", "Toyuq", "Göyərçin", "Sərçə"], 1, None, 2),
 ("Heyvanlarda tənəffüs orqanları hansılardır?",
  "Ağciyər, qəlsəmə, traxeya.",
  ["Ağciyər, qəlsəmə, traxeya", "Yalnız burun",
   "Yalnız dəri", "Mədə və bağırsaq"], 1, None, 3),
 ("Orqanizmdə enerji hansı prosesdə ayrılır?",
  "Qida maddələrinin parçalanmasında.",
  ["Qidanın parçalanmasında", "Yuxuda yalnız",
   "Görmə zamanı", "Səs zamanı"], 1, None, 3),
 ("Balıqların bədən forması nəyə uyğunlaşıb?",
  "Suda asan hərəkətə uyğunlaşıb.",
  ["Suda hərəkətə", "Uçuşa", "Qazmağa", "Tullanmağa"],
  1, None, 2),
],
"bio-6-dasinma-coxalma": [
 ("Qan bədəndə nə ilə hərəkət edir?",
  "Qan damarlarla axır.",
  ["Damarlarla", "Sümüklərlə", "Sinirlərlə", "Dəri ilə"],
  1, None, 2),
 ("Bitkidə hazır üzvi maddələr hansı istiqamətdə daşınır?",
  "Yarpaqlardan bütün orqanlara.",
  ["Yarpaqlardan digər orqanlara", "Yalnız kökə doğru yağışla",
   "Torpaqdan havaya", "Daşınmır"], 1, None, 3),
 ("Kartof hansı orqanla vegetativ çoxalır?",
  "Yumruları ilə çoxalır.",
  ["Yumrularla", "Bığcıqlarla", "Toxumla yalnız",
   "Yarpaqla yalnız"], 1, None, 2),
 ("Qələmlə çoxaltma nədir?",
  "Zoğ hissəsini əkməklə çoxaltma.",
  ["Zoğ hissəsi ilə çoxaltma", "Toxum səpmək",
   "Meyvə yığmaq", "Suvarma üsulu"], 1, None, 3),
 ("Toxum cücərəndə əvvəlcə nəyi udur?",
  "Toxum suyu udub şişir.",
  ["Suyu", "Torpağı", "İşığı", "Duzu"], 1, None, 2),
 ("Böyrəklər hansı funksiyanı yerinə yetirir?",
  "Qanı süzüb sidiyi xaric edir.",
  ["Sidiyi süzüb xaric edir", "Qida həzm edir",
   "Qan yaradır yalnız", "Səs çıxarır"], 1, None, 3),
 ("Quşlar necə çoxalır?",
  "Yumurta qoymaqla çoxalır.",
  ["Yumurta qoymaqla", "Bala doğmaqla", "Bölünməklə",
   "Tumurcuqlamaqla"], 1, None, 1),
 ("Ağcaqanadın inkişafı harada başlayır?",
  "Sürfələri suda inkişaf edir.",
  ["Suda", "Torpaqda", "Havada", "Qarda"], 1, None, 3),
 ("Bitkidə suyun buxarlanması hansı orqandan gedir?",
  "Əsasən yarpaqlardan.",
  ["Yarpaqdan", "Kökdən", "Toxumdan", "Çəyirdəkdən"],
  1, None, 2),
 ("Çoxalma olmasa növün taleyi necə olar?",
  "Nəsil vermez — növün nəsli kəsilər.",
  ["Nəsli kəsilər", "Daha da artar", "Dəyişməz",
   "Güclənər"], 1, None, 2),
],
"bio-6-muhit": [
 ("Canlı təbiət amillərinə nə aiddir?",
  "Digər canlıların təsiri.",
  ["Digər canlıların təsiri", "İşıq", "Temperatur",
   "Külək"], 1, None, 2),
 ("Balıqların yaşayış mühiti hansıdır?",
  "Su mühitidir.",
  ["Su mühiti", "Hava mühiti", "Torpaq mühiti",
   "Buz yalnız"], 1, None, 1),
 ("Torpaqda yaşayan canlıya misal hansıdır?",
  "Soxulcan torpaqda yaşayır.",
  ["Soxulcan", "Balina", "Qartal", "Kəpənək"],
  1, None, 1),
 ("Qida zəncirində bitki ilə qidalananlar hansı halqadır?",
  "İkinci halqa — otyeyənlərdir.",
  ["İkinci halqa (otyeyənlər)", "Birinci halqa",
   "Son halqa hökmən", "Zəncirə daxil deyil"], 1, None, 3),
 ("Kaktus hansı mühitə uyğunlaşıb?",
  "Quraq səhra mühitinə.",
  ["Quraq səhra mühitinə", "Bataqlığa", "Buzlağa",
   "Dərin suya"], 1, None, 2),
 ("Qış yuxusuna gedən heyvana misal hansıdır?",
  "Ayı qış yuxusuna gedir.",
  ["Ayı", "Canavar", "Sərçə", "İnək"], 1, None, 2),
 ("Köçəri quşlar payızda nə edir?",
  "İsti ölkələrə uçub gedirlər.",
  ["İsti ölkələrə uçur", "Qış yuxusuna gedir",
   "Suya girir", "Yuvada qalır hökmən"], 1, None, 2),
 ("Zibilin təbiətə atılması nəyə səbəb olur?",
  "Ətraf mühitin çirklənməsinə.",
  ["Mühitin çirklənməsinə", "Torpağın münbitləşməsinə",
   "Havanın təmizlənməsinə", "Heç nəyə"], 1, None, 1),
 ("Qoruqlar nə üçün yaradılır?",
  "Təbiəti toxunulmaz qorumaq üçün.",
  ["Təbiəti qorumaq üçün", "Ov etmək üçün",
   "Tikinti üçün", "Zibil üçün"], 1, None, 2),
 ("İşıq bitkilər üçün nə üçün vacibdir?",
  "Fotosintez yalnız işıqda gedir.",
  ["Fotosintez üçün", "Yatmaq üçün", "Səs üçün",
   "Vacib deyil"], 1, None, 2),
],
"bio-6-rol": [
 ("Meyvə və tərəvəzlər orqanizmi əsasən nə ilə təmin edir?",
  "Vitaminlərlə zəngindir.",
  ["Vitaminlərlə", "Yalnız yağla", "Duzla yalnız",
   "Heç nə ilə"], 1, None, 2),
 ("Süd verən ev heyvanı hansıdır?",
  "İnək süd verir.",
  ["İnək", "Toyuq", "İt", "Pişik"], 1, None, 1),
 ("Dərman bitkilərindən nə hazırlanır?",
  "Dərman preparatları hazırlanır.",
  ["Dərman preparatları", "Yalnız boya", "Şüşə",
   "Dəmir"], 1, None, 2),
 ("Zərərverici həşərata misal hansıdır?",
  "Kolorado böcəyi kartofa zərər verir.",
  ["Kolorado böcəyi", "Bal arısı", "Parabüzən",
   "Kəpənək hamısı"], 1, None, 3),
 ("Meşələr havanı necə yaxşılaşdırır?",
  "Oksigen verir, tozu tutur.",
  ["Oksigen verib tozu tutmaqla", "İstilik verməklə",
   "Səs salmaqla", "Yağış yağdırmaqla birbaşa"],
  1, None, 2),
 ("İt insana necə kömək edir?",
  "Evi və sürünü qoruyur.",
  ["Evi qoruyur", "Süd verir", "Yumurta verir",
   "Bal verir"], 1, None, 1),
 ("Toxuculuqda istifadə olunan bitki hansıdır?",
  "Pambıqdan parça toxunur.",
  ["Pambıq", "Kaktus", "Palıd", "Qamış yalnız"],
  1, None, 2),
 ("Göbələklərdən hansıları yemək olar?",
  "Yalnız yeməli göbələkləri.",
  ["Yalnız yeməli göbələkləri", "Hamısını",
   "Heç birini", "Yalnız qırmızıları"], 1, None, 2),
 ("Zəhərli göbələyə misal hansıdır?",
  "Milçəkqıran zəhərlidir.",
  ["Milçəkqıran", "Ağ göbələk", "Şampinyon",
   "Kötük göbələyi"], 1, None, 3),
 ("Ev quşlarına misal hansılardır?",
  "Toyuq, ördək, qaz.",
  ["Toyuq, ördək, qaz", "Qartal, şahin", "Sərçə, qarğa",
   "Bayquş, hophop"], 1, None, 1),
],
"cog-6-mekan": [
 ("Qədim insanlar öz yerini nəyə görə təyin edirdilər?",
  "Günəşə və ulduzlara görə.",
  ["Günəşə və ulduzlara", "Telefona", "Kompüterə",
   "Televizora"], 1, None, 2),
 ("Yaşayış məntəqələrinin əsas növləri hansılardır?",
  "Şəhər və kənd.",
  ["Şəhər və kənd", "Dağ və düzən", "Çay və göl",
   "Meşə və çöl"], 1, None, 1),
 ("Azərbaycan hansı regionda yerləşir?",
  "Cənubi Qafqaz regionunda.",
  ["Cənubi Qafqazda", "Orta Asiyada", "Şimali Avropada",
   "Afrikada"], 1, None, 2),
 ("Milli məkan dedikdə nə başa düşülür?",
  "Ölkəmizin bütöv ərazisi.",
  ["Ölkəmizin ərazisi", "Bir küçə", "Bir ev",
   "Başqa planet"], 1, None, 2),
 ("Coğrafiyanın öyrəndiyi obyektlərə nə aiddir?",
  "Dağlar, çaylar, şəhərlər və s.",
  ["Dağlar, çaylar, şəhərlər", "Yalnız kitablar",
   "Yalnız rəqəmlər", "Yalnız sözlər"], 1, None, 1),
 ("Məkanlar zamanla dəyişirmi?",
  "Bəli — təbiətin və insanın təsiri ilə.",
  ["Bəli, təbiət və insan təsiri ilə", "Xeyr, heç vaxt",
   "Yalnız gecə", "Yalnız qışda"], 1, None, 2),
 ("Doğma yurdu öyrənməyin əhəmiyyəti nədir?",
  "Vətəni tanıyıb qorumağa kömək edir.",
  ["Vətəni tanıyıb qorumaq", "Vaxt itirmək",
   "Yalnız qiymət almaq", "Əhəmiyyəti yoxdur"],
  1, None, 2),
 ("Qonşu məkan anlayışına misal hansıdır?",
  "Qonşu ölkələr.",
  ["Qonşu ölkələr", "Uzaq qalaktika", "Okean dibi",
   "Yerin nüvəsi"], 1, None, 2),
 ("Şəhər kənddən əsasən nə ilə fərqlənir?",
  "Əhalisinin çoxluğu və tikililəri ilə.",
  ["Əhalisinin çoxluğu ilə", "Havasının rəngi ilə",
   "Günəşin istiliyi ilə", "Fərqlənmir"], 1, None, 2),
 ("Xəritə məkan haqqında hansı məlumatı verir?",
  "Obyektlərin yerləşməsini göstərir.",
  ["Obyektlərin yerləşməsini", "İnsanların adlarını",
   "Kitabların sayını", "Mahnıları"], 1, None, 2),
],
"cog-6-beledci": [
 ("Günorta kölgəyə görə hansı cəhəti tapmaq olar?",
  "Günorta kölgə şimala düşür.",
  ["Günorta kölgə şimalı göstərir", "Kölgə cənubu göstərir",
   "Kölgə olmur", "Kölgə qərbi göstərir hökmən"],
  1, None, 3),
 ("Aralıq cəhətlərə misal hansıdır?",
  "Şimal-şərq aralıq cəhətdir.",
  ["Şimal-şərq", "Şimal", "Cənub", "Qərb"], 1, None, 2),
 ("Ağacların mamırlı tərəfi adətən hansı cəhəti göstərir?",
  "Mamır kölgəli — şimal tərəfdə bitir.",
  ["Şimalı", "Cənubu", "Şərqi", "Qərbi"], 1, None, 3),
 ("Plan xəritədən nə ilə fərqlənir?",
  "Kiçik ərazini iri miqyasda göstərir.",
  ["Kiçik ərazini iri miqyasda göstərir",
   "Bütün dünyanı göstərir", "Rəngsiz olur",
   "Fərqlənmir"], 1, None, 3),
 ("Fiziki xəritədə mavi rəng nəyi bildirir?",
  "Suları (çay, göl, dəniz).",
  ["Suları", "Dağları", "Meşələri", "Səhraları"],
  1, None, 2),
 ("Axşam Günəş hansı cəhətdə batır?",
  "Günəş qərbdə batır.",
  ["Qərbdə", "Şərqdə", "Şimalda", "Cənubda"],
  1, None, 1),
 ("Marşrut nədir?",
  "Hərəkət üçün seçilmiş yol.",
  ["Hərəkət yolu", "Dağ adı", "Cihaz", "Bina"],
  1, None, 2),
 ("Şərti işarələrin izahı xəritənin harasında verilir?",
  "Xəritənin legendasında.",
  ["Legendasında (izahat hissəsində)", "Arxasında hökmən",
   "Başqa kitabda", "Verilmir"], 1, None, 3),
 ("Yaşıl rəng fiziki xəritədə adətən nəyi göstərir?",
  "Alçaq düzənlikləri.",
  ["Düzənlikləri", "Dağları", "Dənizləri", "Buzlaqları"],
  1, None, 2),
 ("Addımla məsafəni necə ölçmək olar?",
  "Addım sayını addımın uzunluğuna vurmaqla.",
  ["Addımların sayını uzunluğa vurmaqla", "Gözlə təxminən",
   "Ölçmək olmaz", "Səsə görə"], 1, None, 3),
],
"cog-6-kainat": [
 ("Günəş sistemi hansı qalaktikaya daxildir?",
  "Süd Yolu qalaktikasına.",
  ["Süd Yoluna", "Andromedaya", "Heç birinə",
   "Bilinmir"], 1, None, 2),
 ("Planetlər Günəş ətrafında hansı yolla hərəkət edir?",
  "Öz orbitləri üzrə.",
  ["Orbit üzrə", "Düz xətlə", "Ziqzaqla", "Hərəkət etmir"],
  1, None, 2),
 ("Ayın Yer ətrafında tam dövrü təqribən nə qədərdir?",
  "Təqribən bir ay (27-29 gün).",
  ["Təqribən 1 ay", "1 gün", "1 il", "1 saat"],
  1, None, 3),
 ("Ulduzlar niyə gündüz görünmür?",
  "Günəşin parlaq işığı onları üstələyir.",
  ["Günəş işığı onları üstələyir", "Gündüz sönürlər",
   "Buludlar örtür hökmən", "Yerə düşürlər"], 1, None, 2),
 ("Peyk nədir?",
  "Planet ətrafında fırlanan göy cismi.",
  ["Planet ətrafında fırlanan cisim", "Ulduzun adı",
   "Qalaktika", "Buludun növü"], 1, None, 2),
 ("Saturnu digər planetlərdən fərqləndirən nədir?",
  "Parlaq halqaları var.",
  ["Parlaq halqaları", "Yaşıl rəngi", "Kvadrat forması",
   "İşıq saçması"], 1, None, 2),
 ("Yerin təbii peyki hansıdır?",
  "Ay Yerin peykidir.",
  ["Ay", "Mars", "Günəş", "Venera"], 1, None, 1),
 ("Kometa nədir?",
  "Uzun quyruqlu göy cismidir.",
  ["Quyruqlu göy cismi", "Süni peyk", "Təyyarə",
   "Bulud"], 1, None, 2),
 ("Günəş Yerə nə verir?",
  "İşıq və istilik verir.",
  ["İşıq və istilik", "Su və duz", "Səs və külək",
   "Heç nə"], 1, None, 1),
 ("Teleskop nə üçün istifadə olunur?",
  "Göy cisimlərini müşahidə etmək üçün.",
  ["Göy cisimlərini müşahidə üçün", "Mikrobları görmək üçün",
   "Səs yazmaq üçün", "Yol ölçmək üçün"], 1, None, 2),
],
"cog-6-tebiet": [
 ("Dağ ilə düzənliyin əsas fərqi nədir?",
  "Hündürlük fərqidir.",
  ["Hündürlük fərqi", "Rəng fərqi", "Ad fərqi yalnız",
   "Fərq yoxdur"], 1, None, 2),
 ("Təpə dağdan nə ilə fərqlənir?",
  "Təpə xeyli alçaq olur.",
  ["Alçaq olması ilə", "Hündür olması ilə",
   "Suyun çoxluğu ilə", "Fərqlənmir"], 1, None, 2),
 ("Göl nədir?",
  "Qurunun çökəkliyində toplanan su.",
  ["Qurunun çökəkliyində su toplusu", "Axar su",
   "Dənizin adı", "Buz dağı"], 1, None, 2),
 ("Dağın ən yüksək nöqtəsi necə adlanır?",
  "Zirvə adlanır.",
  ["Zirvə", "Ətək", "Yamac", "Dərə"], 1, None, 2),
 ("Yağıntının növləri hansılardır?",
  "Yağış, qar, dolu.",
  ["Yağış, qar, dolu", "Külək və şaxta", "Duman yalnız",
   "Şeh yalnız"], 1, None, 1),
 ("Şeh nədir?",
  "Səhər sərinlikdə əşyaların üstünə çökən su damcıları.",
  ["Əşyaların üstünə çökən su damcıları", "Qar növü",
   "Dolu dənələri", "Duz qatı"], 1, None, 3),
 ("Bitki örtüyü hansı təbəqənin tərkib hissəsidir?",
  "Canlılar aləminə — biosferə aiddir.",
  ["Biosferin", "Litosferin yalnız", "Atmosferin yalnız",
   "Heç birinin"], 1, None, 2),
 ("Okeanla dənizin fərqi nədir?",
  "Okean qat-qat böyükdür.",
  ["Okean daha böyükdür", "Dəniz daha dərindir hökmən",
   "Okean şirin suludur", "Fərq yoxdur"], 1, None, 2),
 ("Yağış necə yaranır?",
  "Buludlardakı damcılar birləşib ağırlaşır və düşür.",
  ["Bulud damcılarının birləşib düşməsindən",
   "Küləyin səsindən", "Torpağın istiliyindən",
   "Günəşin şüasından birbaşa"], 1, None, 3),
 ("Şimşək çaxanda əvvəl işıq, sonra səs gəlir — niyə?",
  "İşıq səsdən çox sürətlidir.",
  ["İşıq səsdən sürətlidir", "Səs işıqdan sürətlidir",
   "Təsadüfdür", "Səs gəlmir"], 1, None, 3),
],
"cog-6-dunya": [
 ("Avstraliya materiki ölçüsünə görə necə materikdir?",
  "Ən kiçik materikdir.",
  ["Ən kiçiyidir", "Ən böyüyüdür", "Orta ölçülüdür",
   "İkincidir"], 1, None, 2),
 ("Amerika materikləri hansılardır?",
  "Şimali və Cənubi Amerika.",
  ["Şimali və Cənubi Amerika", "Şərqi və Qərbi Amerika",
   "Böyük və Kiçik Amerika", "Bir materikdir"],
  1, None, 2),
 ("Pinqvinlər əsasən harada yaşayır?",
  "Antarktidada və cənub sularında.",
  ["Antarktidada", "Afrikada", "Avropada", "Səhrada"],
  1, None, 2),
 ("Amazon çayı hansı materikdə axır?",
  "Cənubi Amerikada.",
  ["Cənubi Amerikada", "Afrikada", "Avstraliyada",
   "Avropada"], 1, None, 2),
 ("Dünyanın ən böyük adası hansıdır?",
  "Qrenlandiya adasıdır.",
  ["Qrenlandiya", "Kipr", "Abşeron", "Madaqaskar"],
  1, None, 3),
 ("Fil və zürafə hansı materikin heyvanlarıdır?",
  "Afrika savannalarının.",
  ["Afrikanın", "Antarktidanın", "Avropanın",
   "Avstraliyanın"], 1, None, 1),
 ("Materikləri bir-birindən nə ayırır?",
  "Okean və dənizlər ayırır.",
  ["Okean və dənizlər", "Hasarlar", "Dağlar yalnız",
   "Yollar"], 1, None, 2),
 ("Asiyanın ən uca dağ sistemi hansıdır?",
  "Himalay dağlarıdır.",
  ["Himalay", "Qafqaz", "Alp", "And"], 1, None, 2),
 ("Şimal Buzlu okeanının xüsusiyyəti nədir?",
  "Ən soyuq və ən kiçik okeandır.",
  ["Ən soyuq və kiçik okeandır", "Ən isti okeandır",
   "Ən dərin okeandır", "Şirin suludur"], 1, None, 3),
 ("Müxtəlif materiklərdə təbiətin fərqli olması nədən asılıdır?",
  "İqlim şəraitindən asılıdır.",
  ["İqlimdən", "Bayraqlardan", "Dillərdən",
   "Adlardan"], 1, None, 3),
],
"cog-6-col": [
 ("Ekskursiya zamanı təhlükəsizlik üçün nə etməli?",
  "Qrupdan ayrılmamaq lazımdır.",
  ["Qrupdan ayrılmamalı", "Tək gəzməli", "Qaçmalı",
   "Yol azmalı"], 1, None, 1),
 ("Havanın temperaturu hansı cihazla ölçülür?",
  "Termometrlə ölçülür.",
  ["Termometrlə", "Flügerlə", "Kompasla", "Xətkeşlə"],
  1, None, 1),
 ("«Şimal küləyi» hansı cəhətdən əsir?",
  "Külək əsdiyi cəhətin adı ilə adlanır: şimaldan.",
  ["Şimaldan", "Cənubdan", "Şərqdən", "Qərbdən"],
  1, None, 2),
 ("Torpağın üst qatının tünd rəngi nəyi göstərə bilər?",
  "Münbitliyini (humusun çoxluğunu).",
  ["Münbitliyini", "Soyuqluğunu", "Yaşını",
   "Heç nəyi"], 1, None, 3),
 ("Müşahidələri müqayisə etmək üçün onlar necə aparılmalıdır?",
  "Eyni vaxtda və müntəzəm.",
  ["Eyni vaxtda, müntəzəm", "Təsadüfi vaxtlarda",
   "İldə bir dəfə", "Yuxuda"], 1, None, 3),
 ("Buludluluq necə qiymətləndirilir?",
  "Göy üzünün buludla örtülmə dərəcəsi ilə.",
  ["Göy üzünün örtülmə dərəcəsi ilə", "Küləyin səsi ilə",
   "Torpağın rəngi ilə", "Ölçülmür"], 1, None, 3),
 ("Çöl tədqiqatında məsafəni hansı alət ölçür?",
  "Ölçü lenti (ruletka).",
  ["Ölçü lenti (ruletka)", "Termometr", "Flüger",
   "Linza"], 1, None, 2),
 ("Bitkiləri tədqiq edərkən nə toplanır?",
  "Herbari üçün nümunələr.",
  ["Herbari nümunələri", "Daşlar yalnız", "Zibil",
   "Heç nə"], 1, None, 2),
 ("Hava proqnozu nəyə əsasən verilir?",
  "Uzunmüddətli müşahidə məlumatlarına.",
  ["Müşahidə məlumatlarına", "Təxminə", "Yuxulara",
   "Nağıllara"], 1, None, 2),
 ("Təbiətdə davranış qaydalarından biri hansıdır?",
  "Zibil atmamaq, ocağı söndürmək.",
  ["Zibil atmamaq", "Gül dərib atmaq", "Səs salmaq",
   "Yuvaları dağıtmaq"], 1, None, 1),
],
"cog-6-yurdumuz": [
 ("Azərbaycanın iki ən böyük çayı hansılardır?",
  "Kür və Araz çayları.",
  ["Kür və Araz", "Volqa və Don", "Nil və Konqo",
   "Samur və Qudyal"], 1, None, 1),
 ("Xəzər dənizi əslində nədir?",
  "Dünyanın ən böyük gölüdür.",
  ["Dünyanın ən böyük gölü", "Okean", "Çay",
   "Su anbarı"], 1, None, 3),
 ("Ölkəmizin qərbində yerləşən dağlıq sistem hansıdır?",
  "Kiçik Qafqaz dağları.",
  ["Kiçik Qafqaz", "Böyük Qafqaz", "Himalay", "Alp"],
  1, None, 2),
 ("Kür-Araz ovalığı hansı təsərrüfat üçün əlverişlidir?",
  "Əkinçilik üçün əlverişlidir.",
  ["Əkinçilik üçün", "Buzlaq turizmi üçün",
   "Dağ-mədən üçün yalnız", "Heç nə üçün"], 1, None, 2),
 ("Azərbaycanın ən böyük gölü hansıdır?",
  "Sarısu gölüdür.",
  ["Sarısu", "Göygöl", "Baykal", "Urmiya"],
  1, None, 3),
 ("Abşeron yarımadası hansı sərvətlə məşhurdur?",
  "Neft və qazla.",
  ["Neftlə", "Qızılla", "Almazla", "Gümüşlə"],
  1, None, 1),
 ("Lənkəran bölgəsinin iqlimi necədir?",
  "Rütubətli subtropik iqlim.",
  ["Rütubətli subtropik", "Qütb iqlimi", "Səhra iqlimi",
   "Tundra"], 1, None, 3),
 ("Qobustan nə ilə məşhurdur?",
  "Qayaüstü qədim rəsmlərlə.",
  ["Qayaüstü rəsmlərlə", "Şəlalələrlə", "Buzlaqlarla",
   "Meşələrlə"], 1, None, 2),
 ("Azərbaycanın milli parklarına misal hansıdır?",
  "Şirvan Milli Parkı.",
  ["Şirvan Milli Parkı", "Yelloustoun", "Serengeti",
   "Alp parkı"], 1, None, 2),
 ("Şahdağ zirvəsi hansı dağ silsiləsindədir?",
  "Böyük Qafqaz silsiləsində.",
  ["Böyük Qafqazda", "Kiçik Qafqazda", "Talış dağlarında",
   "Uralda"], 1, None, 3),
],
}
for _k, _v in ELAVE.items():
    SUALLAR[_k] = SUALLAR[_k] + _v


MOVZULAR += [
    ("fizika", "fiz-6-olcmeler", 1),
    ("fizika", "fiz-6-enerji",   4),
]

YENI_FIZ = {
"fiz-6-olcmeler": [
 ("Menzurkanın bölgü qiyməti 2 ml-dirsə, bu nə deməkdir?",
  "Qonşu bölgülər arasındakı fərq 2 ml-dir.",
  ["Qonşu bölgülər arası 2 ml-dir", "Menzurka 2 ml tutur",
   "Ən böyük qiymət 2 ml-dir", "Menzurka sınıqdır"],
  1, None, 2),
 ("BS (Beynəlxalq Sistem) hansı əsas vahidləri götürür?",
  "Uzunluq - metr, kütlə - kiloqram, zaman - saniyə.",
  ["Metr, kiloqram, saniyə", "Verst, pud, saat",
   "Mil, funt, gün", "Düym, unsiya, həftə"], 1, None, 2),
 ("2,5 m neçə santimetrdir?",
  "1 m = 100 sm, 2,5 m = 250 sm.",
  ["250 sm", "25 sm", "2 500 sm", "205 sm"], 1,
  "%d sm" % 250, 2),
 ("0,5 km neçə metrdir?",
  "1 km = 1 000 m, yarısı 500 m.",
  ["500 m", "50 m", "5 000 m", "550 m"], 1,
  "%d m" % 500, 2),
 ("1 t neçə kiloqramdır?",
  "1 ton = 1 000 kq.",
  ["1 000 kq", "100 kq", "10 kq", "10 000 kq"],
  1, None, 1),
 ("5 dəqiqə neçə saniyədir?",
  "5 × 60 = 300 saniyə.",
  ["300 saniyə", "500 saniyə", "50 saniyə", "3 000 saniyə"],
  1, "%d saniyə" % (5 * 60), 2),
 ("Sahə hansı vahidlə ölçülür?",
  "Sahənin BS vahidi kvadrat metrdir.",
  ["m²", "m³", "kq", "san"], 1, None, 2),
 ("Həcmin BS vahidi hansıdır?",
  "Həcm kub metrlə ölçülür.",
  ["m³", "m²", "litr yalnız", "metr"], 1, None, 2),
 ("Qısa zaman fasilələrini dəqiq ölçmək üçün hansı cihazdan istifadə olunur?",
  "İdman yarışlarında saniyəölçən işlədilir.",
  ["Saniyəölçən", "Tərəzi", "Menzurka", "Barometr"],
  1, None, 2),
 ("Termometrin bölgü qiyməti 1°C-dirsə, o nəyi dəqiq göstərə bilər?",
  "Belə termometr tam dərəcələri dəqiq göstərir.",
  ["Tam dərəcələri", "Dərəcənin mindəbirini",
   "Yalnız mənfi qiymətləri", "Heç nəyi"], 1, None, 3),
 ("Ölçmə zamanı gözün düzgün vəziyyəti necə olmalıdır?",
  "Göz şkala ilə eyni səviyyədə olmalıdır.",
  ["Şkala ilə eyni səviyyədə", "Şkaladan yuxarıda",
   "Şkaladan aşağıda", "Fərqi yoxdur"], 1, None, 2),
 ("125 sm neçə metrdir?",
  "125 sm = 1,25 m.",
  ["1,25 m", "12,5 m", "0,125 m", "125 m"], 1, None, 2),
 ("Kütləni tərəzidə dəqiq ölçmək üçün nədən istifadə olunur?",
  "Müxtəlif ölçülü çəki daşlarından istifadə edilir.",
  ["Çəki daşlarından", "Xətkeşdən", "Menzurkadan",
   "Termometrdən"], 1, None, 2),
 ("Ölçmə xətası nə vaxt azalır?",
  "Bölgü qiyməti kiçik olan dəqiq cihaz seçiləndə xəta azalır.",
  ["Dəqiq cihaz seçiləndə", "Tələsik ölçəndə",
   "Cihazsız təxmin edəndə", "Qaranlıqda ölçəndə"],
  1, None, 2),
 ("Mayenin həcmini menzurka ilə ölçərkən hansı səviyyə oxunur?",
  "Maye səthinin alt (çökük) xətti üzrə oxunur.",
  ["Maye səthinin alt xətti", "Qabın kənarı",
   "Ən yuxarı damcı", "Qabın dibi"], 1, None, 3),
 ("Bir neçə dəfə ölçüb orta qiymət götürmək nə üçün lazımdır?",
  "Təkrar ölçmələr xətanı azaldır.",
  ["Xətanı azaltmaq üçün", "Vaxt keçirmək üçün",
   "Cihazı yoxlamaq üçün yalnız", "Lazım deyil"],
  1, None, 3),
 ("Uzunluğun köməkçi vahidlərinə misal hansıdır?",
  "Millimetr və kilometr metrin köməkçi vahidləridir.",
  ["Millimetr və kilometr", "Kiloqram və qram",
   "Saat və saniyə", "Litr və millilitr"], 1, None, 2),
 ("2 dəqiqə neçə saniyədir?",
  "2 × 60 = 120 saniyə.",
  ["120 saniyə", "20 saniyə", "200 saniyə", "60 saniyə"],
  1, "%d saniyə" % (2 * 60), 1),
 ("Cihazın ölçmə həddi nədir?",
  "Cihazın ölçə biləcəyi ən böyük qiymətdir.",
  ["Ölçə biləcəyi ən böyük qiymət", "Cihazın çəkisi",
   "Cihazın qiyməti", "Bölgülərin sayı"], 1, None, 3),
 ("10 mm neçə santimetrdir?",
  "10 mm = 1 sm.",
  ["1 sm", "10 sm", "100 sm", "0,1 sm"], 1,
  "%d sm" % 1, 1),
],
"fiz-6-enerji": [
 ("Cismin sürətini tapmaq üçün gedilən yolu nəyə bölmək lazımdır?",
  "Sürət yolun zamana nisbətidir.",
  ["Zamana", "Kütləyə", "Həcmə", "Temperatura"],
  1, None, 2),
 ("Avtomobil 100 km yolu 2 saata qət etdi. Sürəti neçədir?",
  "100 : 2 = 50 km/saat.",
  ["50 km/saat", "200 km/saat", "102 km/saat", "98 km/saat"],
  1, "%d km/saat" % (100 // 2), 2),
 ("Piyada ilə avtomobildən hansının sürəti böyükdür?",
  "Avtomobil vahid zamanda daha çox yol gedir.",
  ["Avtomobilin", "Piyadanın", "Bərabərdir", "Bilinmir"],
  1, None, 1),
 ("Mexaniki enerjinin hansı növləri var?",
  "Kinetik və potensial enerji mexaniki enerjinin növləridir.",
  ["Kinetik və potensial", "İsti və soyuq",
   "Bərk və maye", "Müsbət və mənfi yalnız"], 1, None, 2),
 ("Sıxılmış yayın enerjisi hansı enerji növünə aiddir?",
  "Sıxılmış yay potensial enerjiyə malikdir.",
  ["Potensial enerjidir", "Kinetik enerjidir",
   "İstilik enerjisidir", "Enerjisi yoxdur"], 1, None, 3),
 ("Enerji bir növdən başqa növə keçə bilərmi?",
  "Enerji itmir, bir növdən digərinə çevrilir.",
  ["Bəli, çevrilir", "Xeyr, heç vaxt", "Yalnız qışda",
   "Yalnız suda"], 1, None, 2),
 ("Elektrik dövrəsinin əsas hissələri hansılardır?",
  "Dövrə mənbə, keçirici və istehlakçıdan ibarətdir.",
  ["Mənbə, keçirici, istehlakçı", "Yalnız lampalar",
   "Yalnız kabellər", "Yalnız açar"], 1, None, 3),
 ("Elektrik cərəyanının istilik təsirinə misal hansıdır?",
  "Elektrik sobasının qızması istilik təsiridir.",
  ["Elektrik sobasının qızması", "Kölgənin düşməsi",
   "Yağışın yağması", "Küləyin əsməsi"], 1, None, 2),
 ("Cərəyanın işıq təsirindən harada istifadə olunur?",
  "Lampalar cərəyanın işıq təsirinə əsaslanır.",
  ["Lampalarda", "Tərəzilərdə", "Xətkeşlərdə",
   "Menzurkalarda"], 1, None, 2),
 ("Açar elektrik dövrəsində nə üçündür?",
  "Açar dövrəni qapayıb-açmaq üçündür.",
  ["Cərəyanı qoşub-ayırmaq üçün", "İşığı boyamaq üçün",
   "Səs vermək üçün", "Bəzək üçün"], 1, None, 2),
 ("Külək enerjisindən müasir dövrdə nə üçün istifadə olunur?",
  "Külək turbinləri elektrik enerjisi istehsal edir.",
  ["Elektrik almaq üçün", "Yağış yağdırmaq üçün",
   "Torpağı qızdırmaq üçün", "İstifadə olunmur"],
  1, None, 2),
 ("Günəş panelləri hansı enerjini elektrik enerjisinə çevirir?",
  "Panellər işıq enerjisini elektrikə çevirir.",
  ["İşıq (Günəş) enerjisini", "Səs enerjisini",
   "Külək enerjisini", "Nüvə enerjisini"], 1, None, 2),
 ("Suyun axını hansı qurğularda elektrik enerjisi verir?",
  "Su elektrik stansiyalarında axının enerjisindən istifadə olunur.",
  ["Su elektrik stansiyalarında", "Dəyirmanlarda yalnız",
   "Hovuzlarda", "Fəvvarələrdə"], 1, None, 3),
 ("Yanacaqlar (odun, qaz) yanarkən enerji hansı formada ayrılır?",
  "Yanma zamanı istilik enerjisi ayrılır.",
  ["İstilik şəklində", "Yalnız səs şəklində",
   "Maqnit sahəsi şəklində", "Ayrılmır"], 1, None, 3),
 ("Hərəkət edən avtomobilin enerjisi hansı enerji növüdür?",
  "Hərəkətdəki cismin enerjisi kinetik enerjidir.",
  ["Kinetik enerjidir", "Potensial enerjidir",
   "Kimyəvi enerjidir", "Enerjisi yoxdur"], 1, None, 2),
 ("Sürəti dəyişməyən hərəkət necə adlanır?",
  "Sürət sabit qalırsa, hərəkət bərabərsürətlidir.",
  ["Bərabərsürətli hərəkət", "Dəyişənsürətli hərəkət",
   "Fırlanma hərəkəti", "Rəqsi hərəkət"], 1, None, 3),
 ("Velosipedçi 30 km/saat sürətlə 2 saat getdi. Nə qədər yol qət etdi?",
  "30 × 2 = 60 km.",
  ["60 km", "15 km", "32 km", "28 km"], 1,
  "%d km" % (30 * 2), 3),
 ("Enerjiyə qənaətin sadə yollarından biri hansıdır?",
  "İşlətmədikdə cihazları söndürmək enerjiyə qənaətdir.",
  ["İşlətmədikdə cihazları söndürmək", "İşığı gecə-gündüz yandırmaq",
   "Pəncərəni qışda açıq qoymaq", "Cihazları daim işlətmək"],
  1, None, 2),
 ("Cərəyanın maqnit təsirindən istifadə edən qurğu hansıdır?",
  "Elektromaqnit cərəyanın maqnit təsirinə əsaslanır.",
  ["Elektromaqnit", "Termometr", "Menzurka", "Xətkeş"],
  1, None, 3),
 ("Batareyada hansı enerji elektrik enerjisinə çevrilir?",
  "Batareyada kimyəvi enerji elektrikə çevrilir.",
  ["Kimyəvi enerji", "Səs enerjisi", "İşıq enerjisi",
   "Külək enerjisi"], 1, None, 3),
],
}
for _k, _v in YENI_FIZ.items():
    SUALLAR[_k] = _v



def yoxla():
    n = xeta = 0
    butun = set()
    movzu_fenn = {m: f for f, m, _r in MOVZULAR}
    for movzu, siyahi in SUALLAR.items():
        assert movzu in movzu_fenn, movzu
        if len(siyahi) != 20:
            print("XETA  %s: %d sual (20 olmalidir)" % (movzu, len(siyahi)))
            xeta += 1
        for body, why, opts, correct, expect, diff in siyahi:
            n += 1
            p = []
            if len(opts) != 4: p.append("variant sayi %d" % len(opts))
            if len(set(opts)) != len(opts): p.append("tekrar variant")
            if not (1 <= correct <= 4): p.append("correct")
            if not why: p.append("izah bos")
            if diff not in (1, 2, 3): p.append("cetinlik")
            if body in butun: p.append("eyni sual iki defe")
            butun.add(body)
            if expect is not None and opts[correct - 1] != expect:
                p.append("hesablanan «%s» != variant «%s»" % (expect, opts[correct - 1]))
            for t in [body, why] + opts:
                if "'" in t: p.append("apostrof var")
            if p:
                xeta += 1
                print("XETA  %s: %s\n      %s" % (movzu, body[:60], "; ".join(p)))
    hes = sum(1 for s in SUALLAR.values() for q in s if q[4] is not None)
    print("%d sual yoxlandı (%d-i hesabla təsdiqləndi), %d xəta" % (n, hes, xeta))
    return xeta == 0, n


def sql_yaz(n):
    q = lambda t: t.replace("'", "''")
    on = {"fizika": "fiz6", "biologiya": "bio6", "cografiya": "cog6"}
    setirler = []
    for fenn, movzu, rub in MOVZULAR:
        qisa = movzu.split("-", 2)[2]
        for i, (body, why, opts, correct, _e, diff) in enumerate(SUALLAR[movzu], 1):
            setirler.append(
                "('%s-%s#%d','%s','%s',%d,%d,'%s','%s',array['%s','%s','%s','%s'],%d)"
                % (on[fenn], qisa, i, fenn, movzu, diff, rub, q(body), q(why),
                   q(opts[0]), q(opts[1]), q(opts[2]), q(opts[3]), correct))
    with io.open(CIXIS, "w", encoding="utf-8") as f:
        f.write("""-- =====================================================================
--  32_bank_fenn6.sql : 6-CI SINIF - FIZIKA, BIOLOGIYA, COGRAFIYA
--
--  BU FAYL ELLE YAZILMIR - tools/fenn6.py yaradir:
--      python3 tools/fenn6.py
--
--  Fizika 6 + Biologiya 8 + Cografiya 7 = 21 movzu x 20 = %d.
--  ext_key: fiz6-/bio6-/cog6-...
--  ON SERT: 29_movzular_orta6.sql islenmis olmalidir.
--  SONRA:   05_grants.sql yeniden islet.
-- =====================================================================

do $$
begin
  if not exists (select 1 from public.topics t join public.subjects s
      on s.id = t.subject_id
     where (s.slug, t.slug) in (('fizika','fiz-6-giris'),
                                ('biologiya','bio-6-huceyre'),
                                ('cografiya','cog-6-kainat'))
     having count(*) = 3) then
    raise exception 'ONCE 29_movzular_orta6.sql isledilmelidir.';
  end if;
end $$;

delete from public.question_options o
 using public.questions q
 where o.question_id = q.id
   and q.owner_type = 'platform'
   and (q.ext_key like 'fiz6-%%' or q.ext_key like 'bio6-%%'
        or q.ext_key like 'cog6-%%');

with d(ext, fenn, topic, diff, rub, body, why, opts, correct) as (values
%s
),
ins as (
  insert into public.questions
    (ext_key, owner_type, subject_id, level_id, topic_id, kind,
     body, explanation, difficulty, quarter, status)
  select d.ext, 'platform', s.id, l.id, tp.id, 'single',
         d.body, d.why, d.diff, d.rub, 'published'
    from d
    join public.subjects s on s.slug = d.fenn
    join public.programs p on p.slug = 'orta'
    join public.levels   l on l.program_id = p.id and l.code = '6'
    join public.topics   tp on tp.subject_id = s.id and tp.slug = d.topic
  on conflict (ext_key) do update
    set body = excluded.body, explanation = excluded.explanation,
        difficulty = excluded.difficulty, quarter = excluded.quarter,
        topic_id = excluded.topic_id, level_id = excluded.level_id,
        subject_id = excluded.subject_id, status = 'published'
  returning id, ext_key
)
insert into public.question_options (question_id, ord, body, is_correct)
select ins.id, o.ord, o.txt, o.ord = d.correct
  from ins
  join d on d.ext = ins.ext_key,
  lateral unnest(d.opts) with ordinality as o(txt, ord);

do $$
declare n int; k int;
begin
  select count(*) into n from public.questions
   where owner_type = 'platform'
     and (ext_key like 'fiz6-%%' or ext_key like 'bio6-%%'
          or ext_key like 'cog6-%%');
  if n <> %d then
    raise exception 'fenn6 suallari: %d gozlenilirdi, %% tapildi', n;
  end if;
  select count(*) into k from public.questions q
   where (q.ext_key like 'fiz6-%%' or q.ext_key like 'bio6-%%'
          or q.ext_key like 'cog6-%%')
     and ((select count(*) from public.question_options o
            where o.question_id = q.id) <> 4
       or (select count(*) from public.question_options o
            where o.question_id = q.id and o.is_correct) <> 1);
  if k > 0 then
    raise exception '%% sualda variant qurulusu sehvdir', k;
  end if;
  select count(distinct topic_id) into k from public.questions
   where ext_key like 'fiz6-%%' or ext_key like 'bio6-%%'
      or ext_key like 'cog6-%%';
  if k <> 21 then
    raise exception 'movzu sayi 21 deyil: %%', k;
  end if;
  raise notice '6-ci sinif tebiet fennleri banki: %% sual, 21 movzu (fiz, bio, cog).', n;
end $$;
""" % (n, ",\n".join(setirler), n, n))
    print("yazildi: %s" % CIXIS)


if __name__ == "__main__":
    ok, n = yoxla()
    if not ok:
        raise SystemExit(1)
    sql_yaz(n)
