#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Ingilis dili 1-4 platforma banki -> db/28_bank_ing.sql

    Her sinifde 6 movzu x 10 sual = 60;  4 sinif = 240.

Movzular 14_movzular.sql agacindaki ing-1..ing-4 sluglaridir
(ibtidai sinifler ucun vahid resmi derslik yoxdur, ona gore agac
umumi kurikulum movzularidir).  Suallar sade A1 seviyyesindedir,
serhler Azerbaycancadir.  Apostrof qadagandir - "I am", "cannot"
formalari islenib.

Reqem-soz uygunluqlari SAY lugeti ile YOXLANILIR, elifba questionlari
chr()/string ile hesablanir.

DIQQET: 27_bank_sinif5.sql-in ing5- suallari ile eyni cumleler
islenmeyib.

Isletmek:
    python3 tools/ing.py
"""
import io
import os
import string

KOK = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CIXIS = os.path.join(KOK, "db", "28_bank_ing.sql")

SAY = {0: "zero", 1: "one", 2: "two", 3: "three", 4: "four", 5: "five",
       6: "six", 7: "seven", 8: "eight", 9: "nine", 10: "ten",
       11: "eleven", 12: "twelve", 14: "fourteen", 15: "fifteen",
       16: "sixteen", 20: "twenty", 30: "thirty", 40: "forty",
       50: "fifty", 60: "sixty", 90: "ninety", 100: "one hundred"}


#  (movzu-slug, sinif, rub)
MOVZULAR = [
    ("ing-1-alphabet",  "1", 1), ("ing-1-greetings", "1", 1),
    ("ing-1-numbers",   "1", 2), ("ing-1-colours",   "1", 2),
    ("ing-1-family",    "1", 3), ("ing-1-animals",   "1", 4),
    ("ing-2-numbers",   "2", 1), ("ing-2-school",    "2", 1),
    ("ing-2-body",      "2", 2), ("ing-2-food",      "2", 2),
    ("ing-2-toys",      "2", 3), ("ing-2-verbs",     "2", 4),
    ("ing-3-time",      "3", 1), ("ing-3-clothes",   "3", 1),
    ("ing-3-weather",   "3", 2), ("ing-3-house",     "3", 2),
    ("ing-3-present",   "3", 3), ("ing-3-prepositions", "3", 4),
    ("ing-4-past",      "4", 1), ("ing-4-jobs",      "4", 2),
    ("ing-4-hobbies",   "4", 2), ("ing-4-comparative", "4", 3),
    ("ing-4-questions", "4", 3), ("ing-4-reading",   "4", 4),
]

SUALLAR = {
# ========================= 1-CI SINIF =================================
"ing-1-alphabet": [
 ("İngilis əlifbasının ilk hərfi hansıdır?",
  "İngilis əlifbası A hərfi ilə başlayır.",
  ["A", "B", "Z", "C"], 1, string.ascii_uppercase[0], 1),
 ("«B» hərfindən sonra hansı hərf gəlir?",
  "Əlifbada B-dən sonra C gəlir.",
  ["C", "D", "A", "E"], 1, chr(ord("B") + 1), 1),
 ("İngilis əlifbasının sonuncu hərfi hansıdır?",
  "Əlifba Z hərfi ilə bitir.",
  ["Z", "Y", "X", "W"], 1, string.ascii_uppercase[-1], 1),
 ("«Ball» sözü hansı hərflə başlayır?",
  "Ball sözünün ilk hərfi B-dir.",
  ["B", "D", "P", "L"], 1, "ball"[0].upper(), 1),
 ("Böyük «D» hərfinin kiçik yazılışı hansıdır?",
  "D hərfinin kiçik forması d-dir.",
  ["d", "b", "p", "q"], 1, "D".lower(), 2),
 ("Hansı söz «C» hərfi ilə başlayır?",
  "Cat sözü C ilə başlayır.",
  ["cat", "dog", "egg", "fish"], 1,
  [w for w in ("cat", "dog", "egg", "fish") if w.startswith("c")][0], 2),
 ("Hansı sırada hərflər əlifba ardıcıllığı ilə düzülüb?",
  "Əlifba sırası: A, B, C.",
  ["A, B, C", "B, A, C", "C, B, A", "A, C, B"], 1, None, 2),
 ("«E» hərfindən əvvəl hansı hərf gəlir?",
  "Əlifbada E-dən əvvəl D gəlir.",
  ["D", "F", "C", "G"], 1, chr(ord("E") - 1), 2),
 ("«Dog» sözündə neçə hərf var?",
  "D-o-g: üç hərf.",
  ["3", "2", "4", "5"], 1, str(len("dog")), 1),
 ("Kiçik «g» hərfinin böyük yazılışı hansıdır?",
  "g hərfinin böyük forması G-dir.",
  ["G", "Q", "J", "C"], 1, "g".upper(), 2),
],
"ing-1-greetings": [
 ("Səhər görüşəndə ingiliscə nə deyilir?",
  "Səhər salamı: Good morning.",
  ["Good morning", "Good night", "Goodbye", "Sorry"], 1, None, 1),
 ("«Goodbye» nə deməkdir?",
  "Goodbye — sağ ol, əlvida.",
  ["Əlvida (sağ ol)", "Salam", "Təşəkkür", "Bağışla"], 1, None, 1),
 ("Gecə yatmağa gedəndə nə deyilir?",
  "Yatmazdan əvvəl: Good night.",
  ["Good night", "Good morning", "Hello", "Thanks"], 1, None, 1),
 ("«How are you?» sualına hansı cavab uyğundur?",
  "Cavab: I am fine, thank you.",
  ["I am fine, thank you.", "My name is Tural.",
   "It is a cat.", "Goodbye."], 1, None, 2),
 ("«Hi» sözü nə bildirir?",
  "Hi — dostlar arasında salamlaşmadır.",
  ["Salam", "Əlvida", "Gecən xeyrə", "Ad"], 1, None, 1),
 ("Dostunla ayrılanda nə deyirsən?",
  "Ayrılanda: Bye.",
  ["Bye", "Hello", "Good morning", "Yes"], 1, None, 1),
 ("«Nice to meet you» nə vaxt deyilir?",
  "Yeni tanış olanda deyilir.",
  ["Tanış olanda", "Yatanda", "Yemək yeyəndə", "Qaçanda"],
  1, None, 2),
 ("Özünü təqdim etmək üçün hansı cümlə işlənir?",
  "Özünü təqdim etmə: I am Aysu.",
  ["I am Aysu.", "It is a dog.", "Bye-bye.", "No, thanks."],
  1, None, 2),
 ("«Please» sözü nə üçün işlənir?",
  "Please — xahiş bildirir (zəhmət olmasa).",
  ["Xahiş üçün", "Salamlaşmaq üçün", "Ayrılmaq üçün",
   "Saymaq üçün"], 1, None, 2),
 ("«Sorry» nə deməkdir?",
  "Sorry — bağışla, üzr istəyirəm.",
  ["Bağışla", "Salam", "Sağ ol", "Bəli"], 1, None, 2),
],
"ing-1-numbers": [
 ("«One» hansı ədəddir?",
  "One — 1 deməkdir.",
  ["1", "2", "10", "0"], 1, str(1), 1),
 ("«Three» sözü hansı rəqəmi bildirir?",
  "Three — 3 deməkdir.",
  ["3", "8", "13", "2"], 1, str(3), 1),
 ("İngiliscə «beş» necə deyilir?",
  "Beş — five.",
  ["five", "four", "nine", "two"], 1, SAY[5], 1),
 ("Two + two = ? Cavabı ingiliscə deyin.",
  "2 + 2 = 4 — four.",
  ["four", "three", "five", "two"], 1, SAY[2 + 2], 2),
 ("«Seven» hansı ədəddir?",
  "Seven — 7 deməkdir.",
  ["7", "6", "17", "8"], 1, str(7), 1),
 ("Ardıcıllığı davam etdirin: one, two, three, …",
  "Üçdən sonra dörd gəlir: four.",
  ["four", "six", "ten", "one"], 1, SAY[4], 2),
 ("Doqquz ingiliscə necə deyilir?",
  "Doqquz — nine.",
  ["nine", "six", "seven", "ten"], 1, SAY[9], 1),
 ("«Six» və «eight» ədədlərindən hansı böyükdür?",
  "Six = 6, eight = 8; 8 böyükdür.",
  ["eight", "six", "Bərabərdirlər", "Bilmək olmaz"], 1,
  SAY[max(6, 8)], 2),
 ("Əllərimizdəki barmaqların sayı ingiliscə necə deyilir?",
  "İki əldə 10 barmaq — ten.",
  ["ten", "five", "two", "one"], 1, SAY[10], 2),
 ("«Zero» nə deməkdir?",
  "Zero — sıfır.",
  ["Sıfır", "On", "Bir", "Yüz"], 1, None, 2),
],
"ing-1-colours": [
 ("«Red» hansı rəngdir?",
  "Red — qırmızı.",
  ["Qırmızı", "Göy", "Yaşıl", "Sarı"], 1, None, 1),
 ("Göy rəng ingiliscə necə deyilir?",
  "Göy — blue.",
  ["blue", "black", "brown", "green"], 1, None, 1),
 ("«Green» nə deməkdir?",
  "Green — yaşıl.",
  ["Yaşıl", "Ağ", "Qara", "Çəhrayı"], 1, None, 1),
 ("Günəş adətən hansı rənglə çəkilir? (ingiliscə)",
  "Günəş sarı rənglə çəkilir — yellow.",
  ["yellow", "purple", "grey", "black"], 1, None, 2),
 ("«White» hansı rəngi bildirir?",
  "White — ağ.",
  ["Ağ", "Qara", "Qırmızı", "Göy"], 1, None, 1),
 ("Gecənin rəngi ingiliscə hansıdır?",
  "Gecə qaranlıqdır — black.",
  ["black", "white", "pink", "orange"], 1, None, 2),
 ("«Orange» sözü həm meyvə, həm də hansı rəngdir?",
  "Orange — portağal və narıncı rəng.",
  ["Narıncı", "Bənövşəyi", "Boz", "Yaşıl"], 1, None, 2),
 ("Hansı söz rəng bildirmir?",
  "Book — kitab deməkdir; pink, brown, grey rənglərdir.",
  ["book", "pink", "brown", "grey"], 1, None, 2),
 ("«Pink» nə deməkdir?",
  "Pink — çəhrayı.",
  ["Çəhrayı", "Qəhvəyi", "Göy", "Qara"], 1, None, 2),
 ("Ot (grass) adətən hansı rəngdə olur? (ingiliscə)",
  "Ot yaşıldır — green.",
  ["green", "red", "white", "blue"], 1, None, 2),
],
"ing-1-family": [
 ("«Mother» nə deməkdir?",
  "Mother — ana.",
  ["Ana", "Ata", "Bacı", "Qardaş"], 1, None, 1),
 ("Ata ingiliscə necə deyilir?",
  "Ata — father.",
  ["father", "mother", "sister", "baby"], 1, None, 1),
 ("«Baby» sözü kimi bildirir?",
  "Baby — körpə uşaq.",
  ["Körpəni", "Babanı", "Müəllimi", "Qonşunu"], 1, None, 1),
 ("«Family» sözünün mənası nədir?",
  "Family — ailə.",
  ["Ailə", "Məktəb", "Ev", "Bağça"], 1, None, 1),
 ("«Grandfather» kimdir?",
  "Grandfather — baba.",
  ["Baba", "Nənə", "Əmi", "Dayı"], 1, None, 2),
 ("«I love my family» cümləsi nə deməkdir?",
  "Mən ailəmi sevirəm.",
  ["Mən ailəmi sevirəm", "Mən məktəbə gedirəm",
   "Mənim itim var", "Mən yemək yeyirəm"], 1, None, 2),
 ("Hansı söz ailə üzvü bildirmir?",
  "Table — masa deməkdir.",
  ["table", "mother", "father", "sister"], 1, None, 2),
 ("«This is my father» cümləsində kimdən danışılır?",
  "Cümlədə atadan danışılır.",
  ["Atadan", "Anadan", "Bacıdan", "Nənədən"], 1, None, 2),
 ("Bacı ingiliscə necə deyilir?",
  "Bacı — sister.",
  ["sister", "brother", "mother", "aunt"], 1, None, 1),
 ("«Mum» və «Dad» sözləri kimləri bildirir?",
  "Mum — ana, Dad — ata (əzizləmə formaları).",
  ["Ana və atanı", "Nənə və babanı", "Bacı və qardaşı",
   "Müəllimləri"], 1, None, 2),
],
"ing-1-animals": [
 ("«Cat» hansı heyvandır?",
  "Cat — pişik.",
  ["Pişik", "İt", "Balıq", "Quş"], 1, None, 1),
 ("İt ingiliscə necə deyilir?",
  "İt — dog.",
  ["dog", "cat", "cow", "hen"], 1, None, 1),
 ("«Fish» nə deməkdir?",
  "Fish — balıq.",
  ["Balıq", "Fil", "At", "Dovşan"], 1, None, 1),
 ("«Bird» nə deməkdir?",
  "Bird — quş.",
  ["Quş", "Böcək", "İlan", "Ayı"], 1, None, 1),
 ("At ingiliscə necə deyilir?",
  "At — horse.",
  ["horse", "house", "mouse", "goose"], 1, None, 2),
 ("«Rabbit» sözünün mənası nədir?",
  "Rabbit — dovşan.",
  ["Dovşan", "Tülkü", "Canavar", "Kirpi"], 1, None, 2),
 ("Hansı söz heyvan adı deyil?",
  "Apple — alma deməkdir.",
  ["apple", "lion", "bear", "wolf"], 1, None, 2),
 ("Süd verən ev heyvanı ingiliscə necə adlanır?",
  "İnək — cow.",
  ["cow", "cat", "dog", "duck"], 1, None, 2),
 ("Ən böyük quru heyvanı ingiliscə necə deyilir?",
  "Fil — elephant.",
  ["elephant", "mouse", "rabbit", "frog"], 1, None, 2),
 ("«Chicken» nə deməkdir?",
  "Chicken — toyuq.",
  ["Toyuq", "Ördək", "Qaz", "Sərçə"], 1, None, 2),
],
# ========================= 2-CI SINIF =================================
"ing-2-numbers": [
 ("«Twenty» hansı ədəddir?",
  "Twenty — 20 deməkdir.",
  ["20", "12", "2", "22"], 1, str(20), 1),
 ("«Twelve» hansı ədəddir?",
  "Twelve — 12 deməkdir.",
  ["12", "20", "2", "10"], 1, str(12), 2),
 ("Otuz ingiliscə necə deyilir?",
  "Otuz — thirty.",
  ["thirty", "thirteen", "three", "sixty"], 1, SAY[30], 2),
 ("«Fifteen» sözü hansı ədədi bildirir?",
  "Fifteen — 15 deməkdir.",
  ["15", "50", "5", "14"], 1, str(15), 2),
 ("«Fourteen» hansı ədəddir?",
  "Fourteen — 14 deməkdir.",
  ["14", "40", "4", "44"], 1, str(14), 2),
 ("«One hundred» nə deməkdir?",
  "One hundred — 100.",
  ["100", "10", "1 000", "11"], 1, str(100), 2),
 ("Ardıcıllığı davam etdirin: ten, twenty, thirty, …",
  "Onluqlarla sayma: forty (40).",
  ["forty", "fifty", "fourteen", "ninety"], 1, SAY[40], 2),
 ("Əlli ingiliscə necə deyilir?",
  "Əlli — fifty.",
  ["fifty", "fifteen", "five", "forty"], 1, SAY[50], 2),
 ("Hansı söz «60» deməkdir?",
  "Sixty — 60.",
  ["sixty", "sixteen", "six", "seventy"], 1, SAY[60], 2),
 ("«Ninety» hansı ədədi bildirir?",
  "Ninety — 90 deməkdir.",
  ["90", "19", "9", "99"], 1, str(90), 2),
],
"ing-2-school": [
 ("«Pencil» nə deməkdir?",
  "Pencil — karandaş.",
  ["Karandaş", "Qələm", "Silgi", "Dəftər"], 1, None, 1),
 ("Dəftər ingiliscə necə deyilir?",
  "Dəftər — notebook.",
  ["notebook", "pencil", "desk", "door"], 1, None, 1),
 ("«Teacher» harada işləyir?",
  "Müəllim məktəbdə işləyir.",
  ["Məktəbdə", "Xəstəxanada", "Mağazada", "Zavodda"], 1, None, 1),
 ("«Lesson» sözünün mənası nədir?",
  "Lesson — dərs.",
  ["Dərs", "Oyun", "Yemək", "Mahnı"], 1, None, 1),
 ("Silgi ingiliscə necə deyilir?",
  "Silgi — rubber (eraser).",
  ["rubber (eraser)", "ruler", "pen", "book"], 1, None, 2),
 ("«Desk» nədir?",
  "Desk — parta.",
  ["Parta", "Lövhə", "Qapı", "Pəncərə"], 1, None, 2),
 ("«Go to school» nə deməkdir?",
  "Go to school — məktəbə getmək.",
  ["Məktəbə getmək", "Evə qayıtmaq", "Yatmaq", "Oynamaq"],
  1, None, 2),
 ("Hansı söz məktəb ləvazimatı deyil?",
  "Banana — meyvədir.",
  ["banana", "pencil", "notebook", "schoolbag"], 1, None, 2),
 ("«Classroom» nə deməkdir?",
  "Classroom — sinif otağı.",
  ["Sinif otağı", "Yataq otağı", "Mətbəx", "Həyət"], 1, None, 2),
 ("«Stand up» əmri nə bildirir?",
  "Stand up — ayağa qalx.",
  ["Ayağa qalx", "Otur", "Yaz", "Oxu"], 1, None, 2),
],
"ing-2-body": [
 ("«Head» bədənin hansı hissəsidir?",
  "Head — baş.",
  ["Baş", "Əl", "Ayaq", "Göz"], 1, None, 1),
 ("Əl ingiliscə necə deyilir?",
  "Əl — hand.",
  ["hand", "head", "hair", "ear"], 1, None, 1),
 ("«Eyes» hansı orqanlardır?",
  "Eyes — gözlər, görmək üçündür.",
  ["Gözlər", "Qulaqlar", "Əllər", "Dizlər"], 1, None, 1),
 ("«Nose» nə deməkdir?",
  "Nose — burun.",
  ["Burun", "Ağız", "Boyun", "Barmaq"], 1, None, 1),
 ("Qulaq ingiliscə necə deyilir?",
  "Qulaq — ear.",
  ["ear", "eye", "arm", "hair"], 1, None, 2),
 ("«Leg» sözünün mənası nədir?",
  "Leg — qıç (ayaq).",
  ["Qıç (ayaq)", "Qol", "Bel", "Çiyin"], 1, None, 2),
 ("«Ten ___» — barmaqlar haqqında cümləni tamamlayın.",
  "On barmaq — ten fingers.",
  ["fingers", "heads", "noses", "mouths"], 1, None, 2),
 ("«Mouth» nə deməkdir?",
  "Mouth — ağız.",
  ["Ağız", "Diş", "Dodaq", "Çənə"], 1, None, 2),
 ("Saç ingiliscə necə deyilir?",
  "Saç — hair.",
  ["hair", "hand", "ear", "eye"], 1, None, 2),
 ("Hansı söz bədən üzvü deyil?",
  "Car — maşın deməkdir.",
  ["car", "arm", "foot", "face"], 1, None, 2),
],
"ing-2-food": [
 ("«Bread» nə deməkdir?",
  "Bread — çörək.",
  ["Çörək", "Süd", "Su", "Pendir"], 1, None, 1),
 ("Süd ingiliscə necə deyilir?",
  "Süd — milk.",
  ["milk", "meat", "rice", "tea"], 1, None, 1),
 ("«Apple» hansı meyvədir?",
  "Apple — alma.",
  ["Alma", "Armud", "Banan", "Üzüm"], 1, None, 1),
 ("«Water» nə deməkdir?",
  "Water — su.",
  ["Su", "Çay", "Şirə", "Süd"], 1, None, 1),
 ("Pendir ingiliscə necə deyilir?",
  "Pendir — cheese.",
  ["cheese", "butter", "bread", "egg"], 1, None, 2),
 ("«Egg» nə deməkdir?",
  "Egg — yumurta.",
  ["Yumurta", "Ət", "Düyü", "Şorba"], 1, None, 1),
 ("Hansı söz meyvə adıdır?",
  "Banana — banan, meyvədir.",
  ["banana", "soup", "rice", "meat"], 1, None, 2),
 ("«I like tea» cümləsi nə deməkdir?",
  "Mən çay xoşlayıram.",
  ["Mən çay xoşlayıram", "Mən su içmirəm",
   "Mən yemək bişirirəm", "Mən südü sevirəm"], 1, None, 2),
 ("«Ice cream» nədir?",
  "Ice cream — dondurma.",
  ["Dondurma", "İsti şorba", "Duzlu pendir", "Qara çay"],
  1, None, 2),
 ("Hansı söz içki bildirir?",
  "Juice — şirə, içkidir.",
  ["juice", "bread", "butter", "salad"], 1, None, 2),
],
"ing-2-toys": [
 ("«Toy» sözünün mənası nədir?",
  "Toy — oyuncaq.",
  ["Oyuncaq", "Kitab", "Yemək", "Geyim"], 1, None, 1),
 ("Top ingiliscə necə deyilir?",
  "Top — ball.",
  ["ball", "doll", "car", "kite"], 1, None, 1),
 ("«Doll» nə deməkdir?",
  "Doll — kukla.",
  ["Kukla", "Top", "Kubik", "Ayı"], 1, None, 1),
 ("«Toy car» nə deməkdir?",
  "Toy car — oyuncaq maşın.",
  ["Oyuncaq maşın", "Əsl maşın", "Velosiped", "Qatar"],
  1, None, 2),
 ("Kubiklər ingiliscə necə deyilir?",
  "Kubiklər — blocks.",
  ["blocks", "books", "balls", "boxes"], 1, None, 2),
 ("«Teddy bear» hansı oyuncaqdır?",
  "Teddy bear — oyuncaq ayı.",
  ["Oyuncaq ayı", "Oyuncaq it", "Kukla", "Çərpələng"],
  1, None, 2),
 ("«Kite» nədir?",
  "Kite — çərpələng.",
  ["Çərpələng", "Təyyarə", "Quş", "Şar"], 1, None, 2),
 ("«Play with toys» nə deməkdir?",
  "Oyuncaqlarla oynamaq.",
  ["Oyuncaqlarla oynamaq", "Oyuncaqları atmaq",
   "Oyuncaq almaq", "Oyuncaq düzəltmək"], 1, None, 2),
 ("Hansı söz oyuncaq bildirmir?",
  "Window — pəncərə deməkdir.",
  ["window", "doll", "ball", "kite"], 1, None, 2),
 ("«My favourite toy» ifadəsi nə deməkdir?",
  "Mənim ən sevimli oyuncağım.",
  ["Ən sevimli oyuncağım", "Köhnə oyuncağım",
   "Qırıq oyuncaq", "Yeni kitabım"], 1, None, 2),
],
"ing-2-verbs": [
 ("«Read» feili nə deməkdir?",
  "Read — oxumaq.",
  ["Oxumaq", "Yazmaq", "Qaçmaq", "Yatmaq"], 1, None, 1),
 ("Yazmaq ingiliscə necə deyilir?",
  "Yazmaq — write.",
  ["write", "read", "sing", "eat"], 1, None, 1),
 ("«Sing» nə deməkdir?",
  "Sing — mahnı oxumaq.",
  ["Mahnı oxumaq", "Rəqs etmək", "Gülmək", "Danışmaq"],
  1, None, 1),
 ("«Dance» feilinin mənası nədir?",
  "Dance — rəqs etmək.",
  ["Rəqs etmək", "Yemək", "İçmək", "Uçmaq"], 1, None, 1),
 ("Getmək ingiliscə necə deyilir?",
  "Getmək — go.",
  ["go", "come", "sit", "stop"], 1, None, 2),
 ("«Eat» nə deməkdir?",
  "Eat — yemək (yemək yemək).",
  ["Yemək", "İçmək", "Yumaq", "Almaq"], 1, None, 1),
 ("«Drink» feili nə bildirir?",
  "Drink — içmək.",
  ["İçmək", "Yemək", "Bişirmək", "Kəsmək"], 1, None, 2),
 ("Hansı söz hərəkət (feil) bildirir?",
  "Open — açmaq, hərəkətdir.",
  ["open", "table", "red", "cat"], 1, None, 2),
 ("«Sleep» nə deməkdir?",
  "Sleep — yatmaq.",
  ["Yatmaq", "Oyanmaq", "Gəzmək", "Oxumaq"], 1, None, 2),
 ("«Look» feilinin mənası nədir?",
  "Look — baxmaq.",
  ["Baxmaq", "Eşitmək", "Tutmaq", "Atmaq"], 1, None, 2),
],
# ========================= 3-CU SINIF =================================
"ing-3-time": [
 ("«What time is it?» sualı nəyi soruşur?",
  "Saatın neçə olduğunu soruşur.",
  ["Saatın neçə olduğunu", "Havanın necə olduğunu",
   "Adını", "Yaşını"], 1, None, 2),
 ("«Monday» hansı gündür?",
  "Monday — bazar ertəsi.",
  ["Bazar ertəsi", "Bazar", "Cümə", "Şənbə"], 1, None, 1),
 ("«Sunday» nə deməkdir?",
  "Sunday — bazar günü.",
  ["Bazar günü", "Çərşənbə", "Cümə axşamı", "Bazar ertəsi"],
  1, None, 2),
 ("İngilis dilində həftə günlərinin adları necə yazılır?",
  "Günlərin adları böyük hərflə yazılır: Monday, Friday.",
  ["Böyük hərflə", "Kiçik hərflə", "Rəqəmlə", "Dırnaqda"],
  1, None, 3),
 ("«Today» sözünün mənası nədir?",
  "Today — bu gün.",
  ["Bu gün", "Sabah", "Dünən", "Həftə"], 1, None, 1),
 ("«Tomorrow» nə deməkdir?",
  "Tomorrow — sabah.",
  ["Sabah", "Bu gün", "Dünən", "Ay"], 1, None, 1),
 ("«Spring» hansı fəsildir?",
  "Spring — yaz.",
  ["Yaz", "Yay", "Payız", "Qış"], 1, None, 2),
 ("Qış ingiliscə necə deyilir?",
  "Qış — winter.",
  ["winter", "summer", "autumn", "spring"], 1, None, 1),
 ("«Yesterday» nə deməkdir?",
  "Yesterday — dünən.",
  ["Dünən", "Sabah", "İndi", "Gec"], 1, None, 2),
 ("«Week» sözü nəyi bildirir?",
  "Week — həftə (7 gün).",
  ["Həftəni", "Ayı", "İli", "Saatı"], 1, None, 2),
],
"ing-3-clothes": [
 ("«Shirt» nə deməkdir?",
  "Shirt — köynək.",
  ["Köynək", "Şalvar", "Papaq", "Corab"], 1, None, 1),
 ("Yubka ingiliscə necə deyilir?",
  "Yubka — skirt.",
  ["skirt", "shirt", "short", "sock"], 1, None, 2),
 ("«Scarf» nə deməkdir?",
  "Scarf — şərf.",
  ["Şərf", "Əlcək", "Kəmər", "Çanta"], 1, None, 2),
 ("«Jacket» hansı geyimdir?",
  "Jacket — gödəkçə.",
  ["Gödəkçə", "Don", "Ayaqqabı", "Corab"], 1, None, 2),
 ("«Put on» ifadəsi nə bildirir?",
  "Put on — geyinmək.",
  ["Geyinmək", "Soyunmaq", "Yumaq", "Ütüləmək"], 1, None, 2),
 ("«Take off» nə deməkdir?",
  "Take off — soyunmaq, çıxarmaq.",
  ["Soyunmaq (çıxarmaq)", "Geyinmək", "Almaq", "Tikmək"],
  1, None, 2),
 ("Başa taxılan yüngül geyim ingiliscə necə adlanır?",
  "Kepka — cap.",
  ["cap", "sock", "boot", "belt"], 1, None, 2),
 ("«Uniform» nə deməkdir?",
  "Uniform — (məktəb) forması.",
  ["Forma", "İdman ayaqqabısı", "Yağmurluq", "Pijama"],
  1, None, 2),
 ("Hansı söz geyim bildirmir?",
  "Spoon — qaşıq deməkdir.",
  ["spoon", "shirt", "skirt", "jacket"], 1, None, 2),
 ("«Boots» hansı geyimdir?",
  "Boots — çəkmələr.",
  ["Çəkmələr", "Əlcəklər", "Köynəklər", "Papaqlar"], 1, None, 2),
],
"ing-3-weather": [
 ("«It is sunny» cümləsi havanın necə olduğunu bildirir?",
  "Sunny — günəşli.",
  ["Günəşli", "Yağışlı", "Qarlı", "Küləkli"], 1, None, 1),
 ("«Rainy» nə deməkdir?",
  "Rainy — yağışlı.",
  ["Yağışlı", "Günəşli", "Dumanlı", "Soyuq"], 1, None, 1),
 ("Qarlı hava ingiliscə necə deyilir?",
  "Qarlı — snowy.",
  ["snowy", "sunny", "windy", "rainy"], 1, None, 1),
 ("«Windy» sözünün mənası nədir?",
  "Windy — küləkli.",
  ["Küləkli", "İsti", "Buludlu", "Aydın"], 1, None, 2),
 ("«Hot» və «cold» sözləri nəyi bildirir?",
  "Hot — isti, cold — soyuq.",
  ["İsti və soyuğu", "Gecə və gündüzü", "Yaş və qurunu",
   "Ağ və qaranı"], 1, None, 2),
 ("«Cloud» nə deməkdir?",
  "Cloud — bulud.",
  ["Bulud", "Yağış", "Günəş", "Şimşək"], 1, None, 2),
 ("«It is raining» nə deməkdir?",
  "Yağış yağır.",
  ["Yağış yağır", "Qar yağır", "Günəş çıxıb", "Külək əsir"],
  1, None, 2),
 ("Hava adətən hansı fəsildə «snowy» olur?",
  "Qar qışda yağır.",
  ["Qışda", "Yayda", "Yazda", "Payızda"], 1, None, 2),
 ("«Warm» sözünün mənası nədir?",
  "Warm — ilıq, isti.",
  ["İlıq", "Şaxtalı", "Yaş", "Qaranlıq"], 1, None, 2),
 ("«How is the weather?» sualı nəyi soruşur?",
  "Havanın necə olduğunu soruşur.",
  ["Havanın necə olduğunu", "Saatı", "Yolu", "Qiyməti"],
  1, None, 2),
],
"ing-3-house": [
 ("«House» sözü nəyi bildirir?",
  "House — ev.",
  ["Evi", "Bağı", "Yolu", "Məktəbi"], 1, None, 1),
 ("«Room» nə deməkdir?",
  "Room — otaq.",
  ["Otaq", "Dam", "Qapı", "Həyət"], 1, None, 1),
 ("«Table» hansı əşyadır?",
  "Table — masa (stol).",
  ["Masa", "Stul", "Çarpayı", "Şkaf"], 1, None, 1),
 ("«Chair» nə deməkdir?",
  "Chair — stul.",
  ["Stul", "Masa", "Xalça", "Güzgü"], 1, None, 1),
 ("«Bed» nə deməkdir?",
  "Bed — çarpayı.",
  ["Çarpayı", "Divan", "Pəncərə", "Soba"], 1, None, 1),
 ("Pəncərə ingiliscə necə deyilir?",
  "Pəncərə — window.",
  ["window", "wall", "floor", "roof"], 1, None, 2),
 ("«Lamp» nə deməkdir?",
  "Lamp — lampa (işıq).",
  ["Lampa", "Kitab", "Saat", "Vaza"], 1, None, 2),
 ("«In the room» ifadəsi nə bildirir?",
  "Otağın içində.",
  ["Otağın içində", "Otağın üstündə", "Otağın yanında",
   "Otaqdan kənarda"], 1, None, 2),
 ("Hansı əşya adətən mətbəxdə olur?",
  "Fridge — soyuducu, mətbəxdə olur.",
  ["fridge", "bed", "sofa", "wardrobe"], 1, None, 2),
 ("«Wardrobe» nə üçündür?",
  "Wardrobe — paltar şkafı.",
  ["Paltar saxlamaq üçün", "Yemək bişirmək üçün",
   "Yatmaq üçün", "Kitab oxumaq üçün"], 1, None, 2),
],
"ing-3-present": [
 ("«I play» cümləsinə «she» üçün hansı forma uyğundur?",
  "III şəxsin təkində feil «-s» qəbul edir: She plays.",
  ["She plays.", "She play.", "She playing.", "She is play."],
  1, None, 2),
 ("«He ___ to school every day.» boşluğu doldurun.",
  "He ilə: goes.",
  ["goes", "go", "going", "gone"], 1, None, 2),
 ("«They read books every evening» cümləsi hansı zamandadır?",
  "Təkrarlanan hərəkət — Present Simple (indiki sadə).",
  ["Present Simple", "Past Simple", "Gələcək", "Heç bir zaman"],
  1, None, 2),
 ("«Do you like milk?» sualına qısa cavab hansıdır?",
  "Qısa cavab: Yes, I do.",
  ["Yes, I do.", "Yes, I am.", "Yes, I can.", "Yes, it is."],
  1, None, 2),
 ("«She does not ___ TV.» boşluğu doldurun.",
  "Does not-dan sonra feilin əsas forması: watch.",
  ["watch", "watches", "watching", "watched"], 1, None, 3),
 ("Present Simple hansı hərəkəti bildirir?",
  "Adi, hər gün təkrarlanan hərəkəti bildirir.",
  ["Adi, təkrarlanan hərəkəti", "Yalnız keçmişi",
   "Yalnız bu andakını", "Heç bir hərəkəti"], 1, None, 3),
 ("«We ___ English at school.» boşluğu doldurun.",
  "We ilə feil dəyişmir: learn.",
  ["learn", "learns", "learning", "to learns"], 1, None, 2),
 ("Present Simple-da III şəxsin təkində feilə nə artırılır?",
  "He/she/it ilə feilə «-s» artırılır.",
  ["-s şəkilçisi", "-ed şəkilçisi", "-ing şəkilçisi",
   "Heç nə"], 1, None, 2),
 ("«Does he play chess?» cümləsində köməkçi feil hansıdır?",
  "Sualda köməkçi feil does-dur.",
  ["Does", "Play", "He", "Chess"], 1, None, 3),
 ("«I ___ my homework every day.» boşluğu doldurun.",
  "Do my homework — ev tapşırığını yerinə yetirmək.",
  ["do", "does", "doing", "dids"], 1, None, 2),
],
"ing-3-prepositions": [
 ("«In» sözönü nə bildirir?",
  "In — içində.",
  ["İçində", "Üstündə", "Altında", "Yanında"], 1, None, 1),
 ("«Behind» nə deməkdir?",
  "Behind — arxasında.",
  ["Arxasında", "Qarşısında", "İçində", "Arasında"], 1, None, 2),
 ("«Next to» ifadəsinin mənası nədir?",
  "Next to — yanında.",
  ["Yanında", "Uzağında", "Altında", "Üstündə"], 1, None, 2),
 ("«Between» nə bildirir?",
  "Between — ikisinin arasında.",
  ["Arasında", "İçində", "Kənarında", "Arxasında"], 1, None, 2),
 ("«In front of» nə deməkdir?",
  "In front of — qarşısında.",
  ["Qarşısında", "Arxasında", "Altında", "İçində"], 1, None, 2),
 ("«The book is in the bag» — kitab haradadır?",
  "In the bag — çantanın içində.",
  ["Çantanın içində", "Çantanın üstündə", "Masanın altında",
   "Rəfdə"], 1, None, 2),
 ("«The ball is behind the door» — top haradadır?",
  "Behind the door — qapının arxasında.",
  ["Qapının arxasında", "Qapının qarşısında",
   "Qapının üstündə", "Otağın ortasında"], 1, None, 2),
 ("Hansı söz sözönüdür (preposition)?",
  "On — sözönüdür; qalanları isim, sifət, feildir.",
  ["on", "cat", "red", "run"], 1, None, 3),
 ("«The school is near my house» cümləsində «near» nə deməkdir?",
  "Near — yaxınlığında.",
  ["Yaxınlığında", "İçində", "Uzağında", "Altında"], 1, None, 2),
 ("«Put the pen on the desk» əmrində qələm haraya qoyulmalıdır?",
  "On the desk — partanın üstünə.",
  ["Partanın üstünə", "Partanın altına", "Çantaya",
   "Pəncərəyə"], 1, None, 2),
],
# ========================= 4-CU SINIF =================================
"ing-4-past": [
 ("«Played» feili hansı zamandadır?",
  "«-ed» şəkilçisi keçmiş zamanı göstərir.",
  ["Keçmiş", "İndiki", "Gələcək", "Heç bir zaman"], 1, None, 2),
 ("«Go» feilinin keçmiş forması hansıdır?",
  "Go qaydasız feildir: went.",
  ["went", "goed", "gone to", "going"], 1, None, 2),
 ("«I was at home yesterday» cümləsində «was» nəyi bildirir?",
  "Was — keçmişdə olmağı bildirir.",
  ["Keçmişdə olmağı", "Gələcəyi", "İstəyi", "Sualı"],
  1, None, 3),
 ("«I ___ a bird in the garden.» (görmək feilinin keçmişi)",
  "See feilinin keçmişi: saw.",
  ["saw", "see", "seen", "sees"], 1, None, 2),
 ("Qaydalı feillərin keçmiş forması necə düzəlir?",
  "Sonuna «-ed» artırılır: play — played.",
  ["-ed artırmaqla", "-ing artırmaqla", "-s artırmaqla",
   "Dəyişməz qalır"], 1, None, 2),
 ("«They ___ football yesterday.» boşluğu doldurun.",
  "Yesterday keçmişi göstərir: played.",
  ["played", "play", "plays", "playing"], 1, None, 2),
 ("Keçmiş zamanda «have» feili necə olur?",
  "Have qaydasızdır: had.",
  ["had", "haved", "has", "having"], 1, None, 2),
 ("«Did you watch TV?» sualına qısa cavab hansıdır?",
  "Qısa cavab: Yes, I did.",
  ["Yes, I did.", "Yes, I do.", "Yes, I am.", "Yes, I have."],
  1, None, 3),
 ("«Come» feilinin keçmiş forması hansıdır?",
  "Come qaydasızdır: came.",
  ["came", "comed", "coming", "comes"], 1, None, 2),
 ("«Yesterday» sözü hansı zamanla işlənir?",
  "Yesterday (dünən) keçmiş zamanla işlənir.",
  ["Keçmiş zamanla", "Gələcək zamanla", "Yalnız indiki ilə",
   "Heç bir zamanla"], 1, None, 2),
],
"ing-4-jobs": [
 ("«Doctor» hansı peşə sahibidir?",
  "Doctor — həkim.",
  ["Həkim", "Müəllim", "Sürücü", "Aşpaz"], 1, None, 1),
 ("Aşpaz ingiliscə necə deyilir?",
  "Aşpaz — cook.",
  ["cook", "book", "look", "hook"], 1, None, 2),
 ("«Pilot» nəyi idarə edir?",
  "Pilot təyyarəni idarə edir.",
  ["Təyyarəni", "Qatarı", "Gəmini", "Avtobusu"], 1, None, 1),
 ("«Vet» kimləri müalicə edir?",
  "Vet — baytar, heyvanları müalicə edir.",
  ["Heyvanları", "Uşaqları", "İdmançıları", "Müəllimləri"],
  1, None, 2),
 ("«Farmer» harada işləyir?",
  "Farmer təsərrüfatda (fermada) işləyir.",
  ["Fermada", "Xəstəxanada", "Bankda", "Teatrda"], 1, None, 2),
 ("Polis ingiliscə necə deyilir?",
  "Polis — police officer.",
  ["police officer", "postman", "singer", "waiter"],
  1, None, 2),
 ("«Dentist» nəyi müalicə edir?",
  "Dentist dişləri müalicə edir.",
  ["Dişləri", "Gözləri", "Qulağı", "Ayağı"], 1, None, 2),
 ("«Builder» nə edir?",
  "Builder ev və binalar tikir.",
  ["Ev tikir", "Yemək bişirir", "Mahnı oxuyur",
   "Məktub daşıyır"], 1, None, 2),
 ("«Singer» kimdir?",
  "Singer — müğənni.",
  ["Müğənni", "Rəssam", "Yazıçı", "Həkim"], 1, None, 1),
 ("«What is your job?» sualı nəyi soruşur?",
  "Peşəni (harada işlədiyini) soruşur.",
  ["Peşəni", "Yaşı", "Ünvanı", "Adı"], 1, None, 2),
],
"ing-4-hobbies": [
 ("«Hobby» sözünün mənası nədir?",
  "Hobby — sevimli məşğuliyyət.",
  ["Sevimli məşğuliyyət", "İş", "Dərs", "Yuxu"], 1, None, 1),
 ("«Reading» hansı məşğuliyyətdir?",
  "Reading — kitab oxumaq.",
  ["Oxumaq", "Yazmaq", "Üzmək", "Qaçmaq"], 1, None, 1),
 ("«Drawing» nə deməkdir?",
  "Drawing — şəkil çəkmək.",
  ["Şəkil çəkmək", "Mahnı oxumaq", "Tikmək", "Bişirmək"],
  1, None, 1),
 ("«I like swimming» cümləsi nəyi bildirir?",
  "Danışan üzməyi xoşlayır.",
  ["Üzməyi xoşladığını", "Üzə bilmədiyini",
   "Suya girməkdən qorxduğunu", "Qaçmağı sevdiyini"],
  1, None, 2),
 ("«Collecting stamps» nə deməkdir?",
  "Marka kolleksiyası yığmaq.",
  ["Marka yığmaq", "Məktub yazmaq", "Poçta getmək",
   "Şəkil çəkmək"], 1, None, 3),
 ("«Playing chess» hansı oyundur?",
  "Chess — şahmat.",
  ["Şahmat", "Dama", "Futbol", "Loto"], 1, None, 2),
 ("«Dancing» məşğuliyyəti nədir?",
  "Dancing — rəqs etmək.",
  ["Rəqs", "İdman qaçışı", "Üzgüçülük", "Rəsm"], 1, None, 1),
 ("«My hobby is fishing» — söhbət hansı məşğuliyyətdən gedir?",
  "Fishing — balıq tutmaq.",
  ["Balıq tutmaqdan", "Quş tutmaqdan", "Gəmi sürməkdən",
   "Su içməkdən"], 1, None, 2),
 ("«Watching cartoons» nə deməkdir?",
  "Cizgi filmlərinə baxmaq.",
  ["Cizgi filmlərinə baxmaq", "Kino çəkmək",
   "Televizor almaq", "Şəkil yığmaq"], 1, None, 2),
 ("«What is your hobby?» sualına hansı cavab uyğundur?",
  "Cavab məşğuliyyət bildirməlidir: My hobby is reading.",
  ["My hobby is reading.", "I am ten.", "It is sunny.",
   "This is my mother."], 1, None, 2),
],
"ing-4-comparative": [
 ("«Big» sifətinin müqayisə forması hansıdır?",
  "Big — bigger (daha böyük).",
  ["bigger", "biggest", "more big", "big"], 1, None, 2),
 ("«Small — smaller — the smallest» sırası nəyi göstərir?",
  "Sifətin müqayisə dərəcələrini göstərir.",
  ["Müqayisə dərəcələrini", "Cəm formasını", "Zamanı",
   "Sual formasını"], 1, None, 2),
 ("«A giraffe is ___ than a horse.» boşluğu doldurun.",
  "Zürafə atdan hündürdür: taller.",
  ["taller", "tall", "the tallest", "more tall"], 1, None, 2),
 ("«Good» sifətinin müqayisə forması hansıdır?",
  "Good qaydasız sifətdir: better.",
  ["better", "gooder", "more good", "best of"], 1, None, 3),
 ("«The longest river» ifadəsi nə deməkdir?",
  "Ən uzun çay.",
  ["Ən uzun çay", "Uzun çay", "Daha uzun çay", "Qısa çay"],
  1, None, 2),
 ("Uzun sifətlərin müqayisəsində hansı söz işlənir?",
  "Uzun sifətlərlə «more» işlənir: more beautiful.",
  ["more", "-er yox, -est", "much yox, many", "the"],
  1, None, 3),
 ("«Winter is ___ than summer.» boşluğu doldurun.",
  "Qış yaydan soyuqdur: colder.",
  ["colder", "hotter", "cold", "coldest"], 1, None, 2),
 ("«Fast» sözünün müqayisə forması hansıdır?",
  "Fast — faster (daha sürətli).",
  ["faster", "fastest", "more fast", "fasting"], 1, None, 2),
 ("«The best» nə deməkdir?",
  "The best — ən yaxşı.",
  ["Ən yaxşı", "Daha pis", "Yaxşı", "Ən pis"], 1, None, 2),
 ("«Short — shorter» qaydasına uyğun cüt hansıdır?",
  "Old — older eyni qayda ilə düzəlir.",
  ["old — older", "good — better", "bad — worse",
   "beautiful — more beautiful"], 1, None, 3),
],
"ing-4-questions": [
 ("«Where» sual sözü nəyi soruşur?",
  "Where — harada, yeri soruşur.",
  ["Yeri", "Vaxtı", "Səbəbi", "Sayı"], 1, None, 1),
 ("«When» nə deməkdir?",
  "When — nə vaxt.",
  ["Nə vaxt", "Harada", "Kim", "Necə"], 1, None, 1),
 ("«Who» sual sözü nəyə aiddir?",
  "Who — kim, şəxsi soruşur.",
  ["Şəxsə", "Əşyaya", "Yerə", "Rəngə"], 1, None, 2),
 ("«Why» nə soruşur?",
  "Why — niyə, səbəbi soruşur.",
  ["Səbəbi", "Yeri", "Vaxtı", "Qiyməti"], 1, None, 2),
 ("«How many» hansı sualı verir?",
  "How many — neçə, sayı soruşur.",
  ["Sayı", "Rəngi", "Dadı", "Yaşı yox, yeri"], 1, None, 2),
 ("«___ is your birthday?» boşluğuna hansı söz uyğundur?",
  "Vaxt soruşulur: When.",
  ["When", "Who", "What colour", "How many"], 1, None, 2),
 ("«___ do you live?» boşluğunu doldurun.",
  "Yaşayış yeri soruşulur: Where.",
  ["Where", "Why", "Who", "When"], 1, None, 2),
 ("«How old is she?» sualı nəyi soruşur?",
  "How old — yaşı soruşur.",
  ["Yaşını", "Boyunu", "Adını", "Ünvanını"], 1, None, 2),
 ("«What colour is it?» sualına hansı cavab uyğundur?",
  "Rəng soruşulur: It is red.",
  ["It is red.", "It is ten.", "He is a doctor.",
   "Yes, it is."], 1, None, 2),
 ("«Is this your pen?» sualına qısa cavab hansıdır?",
  "Qısa cavab: Yes, it is.",
  ["Yes, it is.", "Yes, I do.", "Yes, I can.", "Yes, he does."],
  1, None, 2),
],
"ing-4-reading": [
 ("Mətn: «Tom has a dog. The dog is black.» Tomun iti hansı "
  "rəngdədir?",
  "Mətndə deyilir: the dog is black — qara.",
  ["Qara", "Ağ", "Qəhvəyi", "Boz"], 1, None, 1),
 ("Mətn: «Ann likes apples and pears.» Ann hansı meyvələri xoşlayır?",
  "Apples and pears — alma və armud.",
  ["Alma və armudu", "Banan və üzümü", "Gilas və əriyi",
   "Heç bir meyvəni"], 1, None, 2),
 ("Mətn: «My school is big and new.» Məktəb necədir?",
  "Big and new — böyük və təzə.",
  ["Böyük və təzə", "Kiçik və köhnə", "Uzaq və qaranlıq",
   "Bağlı"], 1, None, 2),
 ("Mətn: «We go to the park on Sundays.» Parka nə vaxt gedirlər?",
  "On Sundays — bazar günləri.",
  ["Bazar günləri", "Hər gün", "Səhərlər", "Qışda"],
  1, None, 2),
 ("Mətn: «There are five books on the desk.» Partada neçə kitab var?",
  "Five — 5 kitab.",
  ["5", "4", "15", "50"], 1, str(5), 1),
 ("Mətn: «Lala is nine. Her brother is seven.» Lalanın qardaşı "
  "neçə yaşındadır?",
  "Seven — 7 yaşındadır.",
  ["7", "9", "17", "6"], 1, str(7), 2),
 ("Mətn: «The cat sleeps on the sofa.» Pişik harada yatır?",
  "On the sofa — divanın üstündə.",
  ["Divanda", "Yerdə", "Çarpayıda", "Həyətdə"], 1, None, 2),
 ("Mətn: «I get up at eight.» Danışan saat neçədə yuxudan durur?",
  "At eight — saat 8-də.",
  ["8-də", "7-də", "9-da", "10-da"], 1, None, 2),
 ("Mətn: «Father reads a newspaper.» Ata nə oxuyur?",
  "Newspaper — qəzet.",
  ["Qəzet", "Kitab", "Jurnal", "Məktub"], 1, None, 2),
 ("Mətn: «It is winter. It is snowy.» Mətndə hansı fəsildən "
  "danışılır?",
  "Winter — qış.",
  ["Qışdan", "Yaydan", "Yazdan", "Payızdan"], 1, None, 1),
],
}


def yoxla():
    n = xeta = 0
    butun = set()
    movzu_map = {m: (s, r) for m, s, r in MOVZULAR}
    for movzu, siyahi in SUALLAR.items():
        assert movzu in movzu_map, movzu
        if len(siyahi) != 10:
            print("XETA  %s: %d sual (10 olmalidir)" % (movzu, len(siyahi)))
            xeta += 1
        for body, why, opts, correct, expect, diff in siyahi:
            n += 1
            p = []
            if len(opts) != 4: p.append("variant sayi %d" % len(opts))
            if len(set(opts)) != len(opts): p.append("tekrar variant")
            if not (1 <= correct <= 4): p.append("correct")
            if not why: p.append("izah bos")
            if diff not in (1, 2, 3): p.append("cetinlik")
            if body in butun: p.append("eyni sual iki defe")
            butun.add(body)
            if expect is not None and opts[correct - 1] != expect:
                p.append("hesablanan «%s» != variant «%s»" % (expect, opts[correct - 1]))
            for t in [body, why] + opts:
                if "'" in t: p.append("apostrof var")
            if p:
                xeta += 1
                print("XETA  %s: %s\n      %s" % (movzu, body[:60], "; ".join(p)))
    hes = sum(1 for s in SUALLAR.values() for q in s if q[4] is not None)
    print("%d sual yoxlandı (%d-i hesabla təsdiqləndi), %d xəta" % (n, hes, xeta))
    return xeta == 0, n


def sql_yaz(n):
    q = lambda t: t.replace("'", "''")
    setirler = []
    for movzu, sinif, rub in MOVZULAR:
        qisa = movzu.split("-", 2)[2]
        for i, (body, why, opts, correct, _e, diff) in enumerate(SUALLAR[movzu], 1):
            setirler.append(
                "('ing%s-%s#%d','%s','%s',%d,%d,'%s','%s',array['%s','%s','%s','%s'],%d)"
                % (sinif, qisa, i, sinif, movzu, diff, rub, q(body), q(why),
                   q(opts[0]), q(opts[1]), q(opts[2]), q(opts[3]), correct))
    with io.open(CIXIS, "w", encoding="utf-8") as f:
        f.write("""-- =====================================================================
--  28_bank_ing.sql : INGILIS DILI 1-4 PLATFORMA SUAL BANKI
--
--  BU FAYL ELLE YAZILMIR - tools/ing.py yaradir:
--      python3 tools/ing.py
--
--  Her sinifde 6 movzu x 10 = 60;  4 sinif = %d sual.
--  ext_key: ing<sinif>-<movzu>#<sira>.
--  ON SERT: 14_movzular.sql islenmis olmalidir (ing-* movzulari).
--  SONRA:   05_grants.sql yeniden islet.
-- =====================================================================

do $$
begin
  if not exists (select 1 from public.topics t join public.subjects s
      on s.id = t.subject_id
     where (s.slug, t.slug) in (('ingilis-dili','ing-1-alphabet'),
                                ('ingilis-dili','ing-4-reading'))
     having count(*) = 2) then
    raise exception 'ONCE 14_movzular.sql isledilmelidir (ing-* movzulari yoxdur).';
  end if;
end $$;

delete from public.question_options o
 using public.questions q
 where o.question_id = q.id
   and q.owner_type = 'platform'
   and (q.ext_key like 'ing1-%%' or q.ext_key like 'ing2-%%'
        or q.ext_key like 'ing3-%%' or q.ext_key like 'ing4-%%');

with d(ext, sinif, topic, diff, rub, body, why, opts, correct) as (values
%s
),
ins as (
  insert into public.questions
    (ext_key, owner_type, subject_id, level_id, topic_id, kind,
     body, explanation, difficulty, quarter, status)
  select d.ext, 'platform', s.id, l.id, tp.id, 'single',
         d.body, d.why, d.diff, d.rub, 'published'
    from d
    join public.subjects s on s.slug = 'ingilis-dili'
    join public.programs p on p.slug = 'ibtidai'
    join public.levels   l on l.program_id = p.id and l.code = d.sinif
    join public.topics   tp on tp.subject_id = s.id and tp.slug = d.topic
  on conflict (ext_key) do update
    set body = excluded.body, explanation = excluded.explanation,
        difficulty = excluded.difficulty, quarter = excluded.quarter,
        topic_id = excluded.topic_id, level_id = excluded.level_id,
        subject_id = excluded.subject_id, status = 'published'
  returning id, ext_key
)
insert into public.question_options (question_id, ord, body, is_correct)
select ins.id, o.ord, o.txt, o.ord = d.correct
  from ins
  join d on d.ext = ins.ext_key,
  lateral unnest(d.opts) with ordinality as o(txt, ord);

do $$
declare n int; k int;
begin
  select count(*) into n from public.questions
   where owner_type = 'platform'
     and (ext_key like 'ing1-%%' or ext_key like 'ing2-%%'
          or ext_key like 'ing3-%%' or ext_key like 'ing4-%%');
  if n <> %d then
    raise exception 'ing 1-4 suallari: %d gozlenilirdi, %% tapildi', n;
  end if;
  select count(*) into k from public.questions q
   where (q.ext_key like 'ing1-%%' or q.ext_key like 'ing2-%%'
          or q.ext_key like 'ing3-%%' or q.ext_key like 'ing4-%%')
     and ((select count(*) from public.question_options o
            where o.question_id = q.id) <> 4
       or (select count(*) from public.question_options o
            where o.question_id = q.id and o.is_correct) <> 1);
  if k > 0 then
    raise exception '%% sualda variant qurulusu sehvdir', k;
  end if;
  select count(distinct topic_id) into k from public.questions
   where ext_key like 'ing1-%%' or ext_key like 'ing2-%%'
      or ext_key like 'ing3-%%' or ext_key like 'ing4-%%';
  if k <> 24 then
    raise exception 'movzu sayi 24 deyil: %%', k;
  end if;
  raise notice 'Ingilis dili 1-4 banki: %% sual, 24 movzu.', n;
end $$;
""" % (n, ",\n".join(setirler), n, n))
    print("yazildi: %s" % CIXIS)


if __name__ == "__main__":
    ok, n = yoxla()
    if not ok:
        raise SystemExit(1)
    sql_yaz(n)
