#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Riyaziyyat 6 platforma banki -> db/30_bank_riy6.sql

tools/riy5.py qelibi ile: 9 movzu x 40 sual = 360, her riyazi cavab
YENIDEN HESABLANIB duzgun variantla tutusdurulur (EBOB/EKOB math.gcd
ile, ehtimallar Fraction ile, coxluqlar set ile).  Movzular
29_movzular_orta6.sql agacina uygundur (e-derslik Riyaziyyat 6,
kitab 906 + 907).

Menfi ededler «−» (U+2212) isaresi ile yazilir - tam() koməkçisi.
DIQQET: riy3/riy4/riy5 fayllarinin reqemleri tekrarlanmayib.

Isletmek:
    python3 tools/riy6.py
"""
import io
import math
import os
from fractions import Fraction

KOK = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CIXIS = os.path.join(KOK, "db", "30_bank_riy6.sql")


def fmt(n):
    return "{:,}".format(n).replace(",", " ")


def tam(n):
    """Menfi eded ucun riyazi minus isaresi."""
    return str(n).replace("-", "−")


def kesr(f):
    f = Fraction(f)
    if f.denominator == 1:
        return str(f.numerator)
    return "%d/%d" % (f.numerator, f.denominator)


def coxluq(elems):
    return "{%s}" % "; ".join(str(e) for e in sorted(elems))


RUBLAR = {
    "riy-6-natural-ededler": 1, "riy-6-nisbet-faiz": 1,
    "riy-6-tam-ededler": 2, "riy-6-koordinat": 2,
    "riy-6-coxluqlar": 3, "riy-6-ifade-tenlik": 3,
    "riy-6-ucbucaqlar": 3, "riy-6-sahe-hecm": 4,
    "riy-6-statistika": 4,
}

SUALLAR = {
"riy-6-natural-ededler": [
 ("Hansı ədəd sadə ədəddir?",
  "13-ün yalnız iki böləni var: 1 və 13.",
  ["13", "9", "15", "21"], 1,
  str([n for n in (13, 9, 15, 21)
       if sum(1 for d in range(1, n + 1) if n % d == 0) == 2][0]), 2),
 ("12 və 18 ədədlərinin ən böyük ortaq böləni (EBOB) neçədir?",
  "12 = 2·2·3; 18 = 2·3·3; ortaq vuruqlar: 2·3 = 6.",
  ["6", "3", "36", "2"], 1, str(math.gcd(12, 18)), 2),
 ("4 və 6 ədədlərinin ən kiçik ortaq bölünəni (EKOB) neçədir?",
  "4-ə və 6-ya bölünən ən kiçik ədəd 12-dir.",
  ["12", "24", "6", "2"], 1, str(4 * 6 // math.gcd(4, 6)), 2),
 ("Hansı ədəd həm 2-yə, həm də 5-ə bölünür?",
  "Sonu 0 ilə bitən ədədlər həm 2-yə, həm 5-ə bölünür: 90.",
  ["90", "85", "72", "55"], 1,
  str([n for n in (90, 85, 72, 55) if n % 2 == 0 and n % 5 == 0][0]), 2),
 ("2⁵ neçəyə bərabərdir?",
  "2⁵ = 2·2·2·2·2 = 32.",
  ["32", "10", "25", "64"], 1, str(2 ** 5), 2),
 ("Hansı ədəd 9-a qalıqsız bölünür?",
  "Rəqəmlərinin cəmi 9-a bölünən ədəd 9-a bölünür: 7+3+8 = 18.",
  ["738", "728", "745", "703"], 1,
  str([n for n in (738, 728, 745, 703) if n % 9 == 0][0]), 3),
 ("Hansı ədəd mürəkkəb ədəddir?",
  "21 = 3 · 7 — ikidən çox böləni var; 11, 17, 23 sadədir.",
  ["21", "11", "17", "23"], 1,
  str([n for n in (21, 11, 17, 23)
       if sum(1 for d in range(1, n + 1) if n % d == 0) > 2][0]), 2),
 ("56 ədədinin sadə vuruqlara ayrılışı hansıdır?",
  "56 = 2 · 2 · 2 · 7.",
  ["2 · 2 · 2 · 7", "2 · 4 · 7", "2 · 2 · 14", "7 · 8"], 1, None, 3),
 ("10² + 10 neçə edər?",
  "100 + 10 = 110.",
  ["110", "30", "1 010", "120"], 1, str(10 ** 2 + 10), 1),
 ("1 000 000 ədədi 10-un neçənci qüvvətidir?",
  "1 000 000 = 10⁶ — altı sıfır.",
  ["6", "5", "7", "100"], 1, str(len(str(10 ** 6)) - 1), 2),
],
"riy-6-nisbet-faiz": [
 ("8 : 12 nisbətini sadələşdirin.",
  "Hər iki həddi 4-ə bölək: 2 : 3.",
  ["2 : 3", "3 : 2", "4 : 6", "1 : 2"], 1,
  "%d : %d" % (8 // math.gcd(8, 12), 12 // math.gcd(8, 12)), 2),
 ("Tənasübdə x-i tapın: x : 10 = 6 : 4.",
  "x = 10 · 6 : 4 = 15.",
  ["15", "24", "60", "12"], 1, str(10 * 6 // 4), 3),
 ("Sinifdə oğlanların qızlara nisbəti 3 : 2-dir. 15 oğlan varsa, "
  "neçə qız var?",
  "Bir pay: 15 : 3 = 5; qızlar: 5 · 2 = 10.",
  ["10", "12", "6", "30"], 1, str(15 // 3 * 2), 3),
 ("300-ün 12%-i neçədir?",
  "300 : 100 = 3; 3 · 12 = 36.",
  ["36", "12", "25", "360"], 1, str(300 * 12 // 100), 2),
 ("Ədədin 40%-i 28-ə bərabərdirsə, ədədin özü neçədir?",
  "1%: 28 : 40 = 0,7; ədəd: 0,7 · 100 = 70.",
  ["70", "40", "112", "68"], 1, str(28 * 100 // 40), 3),
 ("Tənasübün əsas xassəsi hansıdır?",
  "Kənar hədlərin hasili orta hədlərin hasilinə bərabərdir.",
  ["Kənar hədlərin hasili orta hədlərin hasilinə bərabərdir",
   "Bütün hədlər bərabərdir", "Hədlərin cəmi sabitdir",
   "Hədlər həmişə cütdür"], 1, None, 2),
 ("Xəritənin miqyası 1 : 100 000-dir. Xəritədə 3 sm olan məsafə "
  "həqiqətdə neçə kilometrdir?",
  "3 · 100 000 = 300 000 sm = 3 km.",
  ["3 km", "30 km", "300 km", "1 km"], 1,
  "%d km" % (3 * 100000 // 100000), 3),
 ("45-in 60-a nisbəti hansı kəsrlə ifadə olunur?",
  "45/60 = 3/4.",
  ["3/4", "4/3", "5/6", "1/4"], 1,
  kesr(Fraction(45, 60)), 2),
 ("Qarışıqda şəkər və un 1 : 4 nisbətindədir. 500 q qarışıqda "
  "neçə qram şəkər var?",
  "Cəmi 5 pay; bir pay: 500 : 5 = 100 q.",
  ["100 q", "125 q", "400 q", "20 q"], 1,
  "%d q" % (500 // (1 + 4)), 3),
 ("20 ədədi 50-nin neçə faizidir?",
  "20/50 = 0,4 = 40%.",
  ["40%", "20%", "50%", "25%"], 1,
  "%d%%" % (20 * 100 // 50), 3),
],
"riy-6-tam-ededler": [
 ("−7 və 3 ədədlərindən hansı böyükdür?",
  "Müsbət ədəd mənfidən həmişə böyükdür.",
  ["3", "−7", "Bərabərdirlər", "Müqayisə olunmur"], 1,
  tam(max(-7, 3)), 1),
 ("|−9| (modul) neçəyə bərabərdir?",
  "Ədədin modulu onun sıfırdan məsafəsidir: 9.",
  ["9", "−9", "0", "18"], 1, tam(abs(-9)), 2),
 ("−5 + 7 neçə edər?",
  "Modullar fərqi, böyüyün işarəsi: 2.",
  ["2", "−2", "12", "−12"], 1, tam(-5 + 7), 2),
 ("−4 − 6 neçə edər?",
  "Mənfi ədəddən çıxanda modullar toplanır: −10.",
  ["−10", "2", "−2", "10"], 1, tam(-4 - 6), 2),
 ("(−3) · (−6) hasilini tapın.",
  "Mənfi ilə mənfinin hasili müsbətdir: 18.",
  ["18", "−18", "9", "−9"], 1, tam(-3 * -6), 2),
 ("−20 : 4 neçə edər?",
  "İşarələr fərqlidirsə, qismət mənfidir: −5.",
  ["−5", "5", "−16", "−24"], 1, tam(-20 // 4), 2),
 ("−2 ədədinin əks ədədi hansıdır?",
  "Əks ədədlərin cəmi sıfırdır: 2.",
  ["2", "−2", "0", "1/2"], 1, tam(2), 1),
 ("Termometr −3° göstərirdi. Temperatur 5° artdı. İndi termometr "
  "neçə dərəcəni göstərir?",
  "−3 + 5 = 2°.",
  ["2°", "−8°", "8°", "−2°"], 1, "%s°" % tam(-3 + 5), 2),
 ("−6, 0, 4 ədədləri hansı sırada düzülüb?",
  "Hər sonrakı ədəd böyükdür — artan sıradadır.",
  ["Artan", "Azalan", "Qarışıq", "Sıra yoxdur"], 1, None, 2),
 ("(−1) · (−1) · (−1) hasili neçədir?",
  "Tək sayda mənfi vuruq — nəticə mənfidir: −1.",
  ["−1", "1", "−3", "0"], 1, tam(-1 * -1 * -1), 3),
],
"riy-6-koordinat": [
 ("Koordinat oxlarının kəsişdiyi nöqtə necə adlanır?",
  "O(0; 0) — koordinat başlanğıcıdır.",
  ["Koordinat başlanğıcı", "Təpə nöqtəsi", "Mərkəz qövsü",
   "Kəsişmə bucağı"], 1, None, 2),
 ("A(3; 5) nöqtəsinin yazılışında 3 ədədi nəyi göstərir?",
  "Birinci ədəd absisdir (x koordinatı).",
  ["Absisi (x-i)", "Ordinatı (y-i)", "Məsafəni", "Bucağı"],
  1, None, 2),
 ("Üfüqi koordinat oxu necə adlanır?",
  "Üfüqi ox absis oxudur (Ox).",
  ["Absis oxu (Ox)", "Ordinat oxu (Oy)", "Simmetriya oxu",
   "Paralel ox"], 1, None, 2),
 ("B(0; 4) nöqtəsi harada yerləşir?",
  "Absisi 0 olan nöqtə ordinat oxu üzərindədir.",
  ["Ordinat oxu üzərində", "Absis oxu üzərində",
   "Başlanğıcda", "II rübdə"], 1, None, 3),
 ("Koordinat müstəvisi oxlarla neçə rübə bölünür?",
  "Oxlar müstəvini 4 rübə bölür.",
  ["4", "2", "3", "6"], 1, str(4), 1),
 ("C(−2; 3) nöqtəsi hansı rübdə yerləşir?",
  "x < 0, y > 0 olduqda nöqtə II rübdədir.",
  ["II rübdə", "I rübdə", "III rübdə", "IV rübdə"], 1, None, 3),
 ("Şaquli koordinat oxu necə adlanır?",
  "Şaquli ox ordinat oxudur (Oy).",
  ["Ordinat oxu (Oy)", "Absis oxu (Ox)", "Diaqonal ox",
   "Miqyas oxu"], 1, None, 2),
 ("D(5; 0) nöqtəsi harada yerləşir?",
  "Ordinatı 0 olan nöqtə absis oxu üzərindədir.",
  ["Absis oxu üzərində", "Ordinat oxu üzərində",
   "I rübdə", "Heç yerdə"], 1, None, 3),
 ("M(2; 7) və N(2; 1) nöqtələrindən keçən düz xətt hansı oxa "
  "paraleldir?",
  "Absislər eynidirsə, xətt Oy oxuna paraleldir.",
  ["Oy oxuna", "Ox oxuna", "Heç birinə", "Hər ikisinə"],
  1, None, 3),
 ("Hansı nöqtə III rübdə yerləşir?",
  "III rübdə hər iki koordinat mənfidir: (−4; −1).",
  ["(−4; −1)", "(4; 1)", "(−4; 1)", "(4; −1)"], 1, None, 3),
],
"riy-6-coxluqlar": [
 ("Çoxluğu təşkil edən obyektlərin hər biri necə adlanır?",
  "Çoxluğun obyektləri onun elementləridir.",
  ["Element", "Rəqəm", "Hərf", "Qrup"], 1, None, 1),
 ("A = {1; 2; 3} çoxluğunun neçə elementi var?",
  "Çoxluqda 3 element var.",
  ["3", "6", "1", "123"], 1, str(len({1, 2, 3})), 1),
 ("İki çoxluğun ortaq elementlərindən ibarət çoxluq necə adlanır?",
  "Ortaq elementlər kəsişməni əmələ gətirir.",
  ["Kəsişmə", "Birləşmə", "Fərq", "Alt çoxluq"], 1, None, 2),
 ("A = {1; 2; 3}, B = {2; 3; 4}. A ∩ B çoxluğunu tapın.",
  "Ortaq elementlər: 2 və 3.",
  ["{2; 3}", "{1; 2; 3; 4}", "{1; 4}", "{1}"], 1,
  coxluq({1, 2, 3} & {2, 3, 4}), 2),
 ("A = {1; 2}, B = {2; 5}. A ∪ B çoxluğunu tapın.",
  "Birləşməyə hər iki çoxluğun bütün elementləri daxildir.",
  ["{1; 2; 5}", "{2}", "{1; 5}", "{1; 2; 2; 5}"], 1,
  coxluq({1, 2} | {2, 5}), 2),
 ("Heç bir elementi olmayan çoxluq necə adlanır?",
  "Elementsiz çoxluq boş çoxluqdur.",
  ["Boş çoxluq", "Tam çoxluq", "Kiçik çoxluq", "Sıfır ədədi"],
  1, None, 2),
 ("Bütün elementləri başqa çoxluğa daxil olan çoxluq necə adlanır?",
  "Belə çoxluq alt çoxluqdur.",
  ["Alt çoxluq", "Üst çoxluq", "Kəsişmə", "Qalıq"], 1, None, 2),
 ("C = {a; b; c; d} çoxluğundan neçə birelementli alt çoxluq "
  "ayırmaq olar?",
  "Hər elementdən bir alt çoxluq: 4.",
  ["4", "1", "16", "2"], 1, str(len(["a", "b", "c", "d"])), 3),
 ("Cüt ədədlər çoxluğu ilə tək ədədlər çoxluğunun kəsişməsi nədir?",
  "Həm cüt, həm tək ədəd yoxdur — kəsişmə boşdur.",
  ["Boş çoxluqdur", "Bütün ədədlərdir", "Yalnız sıfırdır",
   "Yalnız 1-dir"], 1, None, 3),
 ("{5; 10; 15; 20; …} çoxluğunun elementlərini birləşdirən "
  "ümumi xassə hansıdır?",
  "Hamısı 5-ə bölünür.",
  ["5-ə bölünmə", "Cüt olma", "Tək olma", "Sadə olma"],
  1, None, 2),
],
"riy-6-ifade-tenlik": [
 ("7x − 2x ifadəsini sadələşdirin.",
  "Oxşar hədlər: (7 − 2)x = 5x.",
  ["5x", "9x", "5", "14x"], 1, None, 2),
 ("3(x + 4) mötərizəsini açın.",
  "Paylama qanunu: 3x + 12.",
  ["3x + 12", "3x + 4", "x + 12", "7x"], 1, None, 2),
 ("4x = −20 tənliyinin kökü neçədir?",
  "x = −20 : 4 = −5.",
  ["−5", "5", "−16", "−80"], 1, tam(-20 // 4), 2),
 ("x + 15 = 9 tənliyini həll edin.",
  "x = 9 − 15 = −6.",
  ["−6", "6", "24", "−24"], 1, tam(9 - 15), 2),
 ("2x + 3 = 19 tənliyinin kökü neçədir?",
  "2x = 16; x = 8.",
  ["8", "11", "16", "38"], 1, str((19 - 3) // 2), 2),
 ("x : 3 = −7 tənliyində x-i tapın.",
  "x = −7 · 3 = −21.",
  ["−21", "21", "−4", "−10"], 1, tam(-7 * 3), 2),
 ("5 − x = 12 tənliyinin kökü neçədir?",
  "x = 5 − 12 = −7.",
  ["−7", "7", "17", "−17"], 1, tam(5 - 12), 3),
 ("x > −2 bərabərsizliyini hansı ədəd ödəyir?",
  "0 ədədi −2-dən böyükdür.",
  ["0", "−3", "−5", "−10"], 1,
  str([n for n in (0, -3, -5, -10) if n > -2][0]), 2),
 ("a = −2 olduqda 3a + 11 ifadəsinin qiyməti neçədir?",
  "3 · (−2) = −6; −6 + 11 = 5.",
  ["5", "17", "−17", "−5"], 1, tam(3 * -2 + 11), 3),
 ("Ədədin 3 misli ilə 5-in cəmi 26-dır. Ədədi tapın.",
  "3x + 5 = 26; 3x = 21; x = 7.",
  ["7", "21", "31", "9"], 1, str((26 - 5) // 3), 3),
],
"riy-6-ucbucaqlar": [
 ("Üçbucağın daxili bucaqlarının cəmi neçə dərəcədir?",
  "İstənilən üçbucaqda bucaqların cəmi 180°-dir.",
  ["180°", "90°", "360°", "100°"], 1, None, 2),
 ("Bərabərtərəfli üçbucağın hər bucağı neçə dərəcədir?",
  "180 : 3 = 60°.",
  ["60°", "90°", "45°", "120°"], 1, "%d°" % (180 // 3), 2),
 ("Üçbucağın iki bucağı 50° və 60°-dirsə, üçüncü bucağı tapın.",
  "180 − 50 − 60 = 70°.",
  ["70°", "110°", "80°", "60°"], 1,
  "%d°" % (180 - 50 - 60), 2),
 ("İki tərəfi bərabər olan üçbucaq necə adlanır?",
  "İki bərabər tərəfli üçbucaq bərabəryanlıdır.",
  ["Bərabəryanlı", "Bərabərtərəfli", "Müxtəliftərəfli",
   "Düzbucaqlı"], 1, None, 2),
 ("Düzbucaqlı üçbucaqda iti bucaqların cəmi neçə dərəcədir?",
  "180 − 90 = 90°.",
  ["90°", "180°", "45°", "100°"], 1, "%d°" % (180 - 90), 3),
 ("Bütün bucaqları iti olan üçbucaq necə adlanır?",
  "Hər üç bucağı iti olan üçbucaq itibucaqlıdır.",
  ["İtibucaqlı", "Korbucaqlı", "Düzbucaqlı", "Bərabəryanlı"],
  1, None, 2),
 ("Tərəfləri 6 sm, 8 sm və 10 sm olan üçbucağın perimetri neçədir?",
  "P = 6 + 8 + 10 = 24 sm.",
  ["24 sm", "22 sm", "26 sm", "48 sm"], 1,
  "%d sm" % (6 + 8 + 10), 2),
 ("Üçbucağın bir tərəfi digər iki tərəfin cəmindən böyük ola bilərmi?",
  "Xeyr — üçbucaq bərabərsizliyinə görə ola bilməz.",
  ["Xeyr, ola bilməz", "Bəli, həmişə", "Yalnız düzbucaqlıda",
   "Yalnız bərabəryanlıda"], 1, None, 3),
 ("Bərabəryanlı üçbucağın oturacağına bitişik bucaqları necədir?",
  "Oturacaq bucaqları bərabərdir.",
  ["Bərabərdir", "Fərqlidir", "Həmişə 90°-dir", "Kor bucaqdır"],
  1, None, 3),
 ("Bucaqlarından biri kor olan üçbucaq necə adlanır?",
  "Kor bucağı olan üçbucaq korbucaqlıdır.",
  ["Korbucaqlı", "İtibucaqlı", "Düzbucaqlı", "Bərabərtərəfli"],
  1, None, 2),
],
"riy-6-sahe-hecm": [
 ("Paraleloqramın sahəsi necə hesablanır?",
  "S = oturacaq × hündürlük.",
  ["Oturacaq × hündürlük", "Tərəflərin cəmi",
   "Diaqonalların cəmi", "Perimetr × 2"], 1, None, 2),
 ("Oturacağı 10 sm, hündürlüyü 6 sm olan paraleloqramın sahəsi "
  "neçədir?",
  "S = 10 · 6 = 60 sm².",
  ["60 sm²", "30 sm²", "16 sm²", "32 sm²"], 1,
  "%d sm²" % (10 * 6), 2),
 ("Oturacağı 12 sm, hündürlüyü 5 sm olan üçbucağın sahəsini tapın.",
  "S = (12 · 5) : 2 = 30 sm².",
  ["30 sm²", "60 sm²", "17 sm²", "34 sm²"], 1,
  "%d sm²" % (12 * 5 // 2), 2),
 ("Tili 5 sm olan kubun həcmini tapın.",
  "V = 5³ = 125 sm³.",
  ["125 sm³", "25 sm³", "15 sm³", "150 sm³"], 1,
  "%d sm³" % (5 ** 3), 2),
 ("Ölçüləri 7 sm, 4 sm və 3 sm olan düzbucaqlı paralelepipedin "
  "həcmi neçədir?",
  "V = 7 · 4 · 3 = 84 sm³.",
  ["84 sm³", "14 sm³", "28 sm³", "168 sm³"], 1,
  "%d sm³" % (7 * 4 * 3), 2),
 ("1 sm² neçə kvadrat millimetrdir?",
  "1 sm = 10 mm; 10 · 10 = 100 mm².",
  ["100 mm²", "10 mm²", "1 000 mm²", "20 mm²"], 1,
  "%d mm²" % (10 * 10), 3),
 ("Trapesiyanın sahəsi necə tapılır?",
  "Oturacaqların cəminin yarısı hündürlüyə vurulur.",
  ["Oturacaqlar cəminin yarısı × hündürlük",
   "Bütün tərəflərin cəmi", "Diaqonalların hasili",
   "Oturacaqların fərqi × 2"], 1, None, 3),
 ("Sahəsi 48 sm², oturacağı 8 sm olan paraleloqramın hündürlüyü "
  "neçədir?",
  "h = S : a = 48 : 8 = 6 sm.",
  ["6 sm", "8 sm", "40 sm", "384 sm"], 1,
  "%d sm" % (48 // 8), 3),
 ("Kubun bütün tillərinin uzunluqları cəmi 36 sm-dirsə, bir til "
  "neçə santimetrdir?",
  "Kubun 12 tili var: 36 : 12 = 3 sm.",
  ["3 sm", "6 sm", "12 sm", "4 sm"], 1, "%d sm" % (36 // 12), 3),
 ("Rombun sahəsi diaqonalları ilə necə tapılır?",
  "S = diaqonalların hasilinin yarısı.",
  ["Diaqonalların hasilinin yarısı", "Diaqonalların cəmi",
   "Tərəflərin hasili", "Perimetrin yarısı"], 1, None, 3),
],
"riy-6-statistika": [
 ("Zər atılanda cüt ədəd düşməsi ehtimalı neçədir?",
  "6 üzdən 3-ü cütdür: 3/6 = 1/2.",
  ["1/2", "1/6", "1/3", "2/3"], 1, kesr(Fraction(3, 6)), 3),
 ("Ehtimal hansı qiymətlər arasında dəyişir?",
  "Ehtimal 0 ilə 1 arasında olur.",
  ["0 ilə 1 arasında", "1 ilə 10 arasında",
   "−1 ilə 1 arasında", "10 ilə 100 arasında"],
  1, None, 2),
 ("Yəqin (mütləq baş verən) hadisənin ehtimalı neçədir?",
  "Mütləq hadisənin ehtimalı 1-dir.",
  ["1", "0", "1/2", "100"], 1, str(1), 2),
 ("Qutuda 2 qırmızı və 3 mavi kürəcik var. Qırmızı kürəcik çıxarma "
  "ehtimalı neçədir?",
  "Cəmi 5 kürəcik: 2/5.",
  ["2/5", "3/5", "1/2", "2/3"], 1, kesr(Fraction(2, 5)), 3),
 ("5, 8, 8, 9, 10 sırasında moda (ən çox təkrarlanan) hansıdır?",
  "8 iki dəfə təkrarlanır.",
  ["8", "5", "10", "9"], 1,
  str(max((5, 8, 8, 9, 10), key=(5, 8, 8, 9, 10).count)), 2),
 ("12, 15, 18, 15 ədədlərinin ədədi ortası neçədir?",
  "(12 + 15 + 18 + 15) : 4 = 60 : 4 = 15.",
  ["15", "12", "60", "18"], 1,
  str((12 + 15 + 18 + 15) // 4), 2),
 ("Median nədir?",
  "Sıralanmış sıranın ortasındakı qiymətdir.",
  ["Sıralanmış sıranın ortasındakı qiymət",
   "Ən böyük qiymət", "Qiymətlərin cəmi",
   "Ən çox təkrarlanan qiymət"], 1, None, 3),
 ("3, 7, 9, 11, 20 sırasının medianı neçədir?",
  "Beş ədədin ortadakısı üçüncüdür: 9.",
  ["9", "7", "10", "11"], 1, str(sorted((3, 7, 9, 11, 20))[2]), 3),
 ("Mümkünsüz hadisənin ehtimalı neçədir?",
  "Baş verə bilməyən hadisənin ehtimalı 0-dır.",
  ["0", "1", "1/2", "−1"], 1, str(0), 2),
 ("Sütunlu diaqram nəyi göstərmək üçün əlverişlidir?",
  "Kəmiyyətləri müqayisə etmək üçün əlverişlidir.",
  ["Kəmiyyətlərin müqayisəsini", "Yalnız rəngləri",
   "Xəritəni", "Hərfləri"], 1, None, 2),
],
}



#  Derinlesdirme: her movzuya 10 elave sual (#11-20).
ELAVE = {
"riy-6-natural-ededler": [
 ("20 və 30 ədədlərinin ortaq bölənlərindən ən böyüyü hansıdır?",
  "20 = 2·2·5; 30 = 2·3·5; EBOB = 2·5 = 10.",
  ["10", "5", "60", "600"], 1, str(math.gcd(20, 30)), 2),
 ("6-ya və 8-ə bölünən ən kiçik natural ədəd neçədir?",
  "EKOB(6, 8) = 24.",
  ["24", "48", "14", "2"], 1,
  str(6 * 8 // math.gcd(6, 8)), 2),
 ("3 ədədinin dördüncü qüvvətini hesablayın.",
  "3⁴ = 3·3·3·3 = 81.",
  ["81", "12", "27", "43"], 1, str(3 ** 4), 2),
 ("Sonu 0 və ya 5 ilə bitən ədədlər hansı ədədə mütləq bölünür?",
  "Bölünmə əlaməti: 5-ə bölünür.",
  ["5-ə", "2-yə", "3-ə", "9-a"], 1, None, 2),
 ("Rəqəmlərinin cəmi 3-ə bölünən ədəd hansı ədədə bölünür?",
  "3-ə bölünmə əlaməti belədir.",
  ["3-ə", "5-ə", "10-a", "7-yə"], 1, None, 2),
 ("1-dən 20-yə qədər neçə sadə ədəd var?",
  "2, 3, 5, 7, 11, 13, 17, 19 — cəmi 8 sadə ədəd.",
  ["8 sadə ədəd", "6 sadə ədəd", "10 sadə ədəd",
   "4 sadə ədəd"], 1,
  "%d sadə ədəd" % len([n for n in range(2, 21)
    if sum(1 for d in range(1, n + 1) if n % d == 0) == 2]), 3),
 ("Hansı hasil 48-in sadə vuruqlara ayrılışıdır?",
  "48 = 2 · 2 · 2 · 2 · 3.",
  ["2 · 2 · 2 · 2 · 3", "2 · 2 · 12", "4 · 12", "6 · 8"],
  1, None, 3),
 ("Qonşu iki natural ədədin hasili 72-dirsə, bu ədədlər hansılardır?",
  "8 · 9 = 72.",
  ["8 və 9", "6 və 12", "7 və 8", "9 və 10"], 1,
  ("8 və 9" if 8 * 9 == 72 else ""), 3),
 ("10⁴ ədədini açıq şəkildə yazın.",
  "10⁴ = 10 000 (dörd sıfır).",
  ["10 000", "1 000", "100 000", "40"], 1, fmt(10 ** 4), 2),
 ("Hansı ədəd həm 3-ə, həm də 4-ə bölünür?",
  "84 = 3 · 28 = 4 · 21 — hər ikisinə bölünür.",
  ["84", "74", "92", "58"], 1,
  str([n for n in (84, 74, 92, 58) if n % 3 == 0 and n % 4 == 0][0]), 3),
],
"riy-6-nisbet-faiz": [
 ("5 : 20 nisbəti ən sadə şəkildə necə yazılır?",
  "Hər iki həddi 5-ə bölək: 1 : 4.",
  ["1 : 4", "4 : 1", "1 : 5", "2 : 5"], 1,
  "%d : %d" % (5 // math.gcd(5, 20), 20 // math.gcd(5, 20)), 2),
 ("x : 4 = 27 : 9 tənasübünü ödəyən x hansıdır?",
  "x = 4 · 27 : 9 = 12.",
  ["12", "3", "108", "31"], 1, str(4 * 27 // 9), 3),
 ("200 manatın 45 faizi neçə manatdır?",
  "200 · 45 : 100 = 90 manat.",
  ["90 manat", "45 manat", "110 manat", "9 manat"], 1,
  "%d manat" % (200 * 45 // 100), 2),
 ("25%-i 13 olan ədədi tapın.",
  "25% dörddə birdir: ədəd = 13 · 4 = 52.",
  ["52", "26", "39", "65"], 1, str(13 * 4), 3),
 ("Plan 1 : 50 000 miqyasındadır. Plandakı 4 sm həqiqətdə neçə kilometrdir?",
  "4 · 50 000 = 200 000 sm = 2 km.",
  ["2 km", "4 km", "20 km", "8 km"], 1,
  "%d km" % (4 * 50000 // 100000), 3),
 ("Nisbətin hər iki həddini eyni sıfırdan fərqli ədədə vursaq nisbət necə dəyişər?",
  "Nisbət dəyişməz.",
  ["Dəyişməz", "İki dəfə artar", "Yarıya düşər", "Sıfır olar"],
  1, None, 2),
 ("Malın qiyməti 50 manat idi, 10% bahalaşdı. Yeni qiymət neçə oldu?",
  "Artım 5 manat: 50 + 5 = 55 manat.",
  ["55 manat", "60 manat", "51 manat", "45 manat"], 1,
  "%d manat" % (50 + 50 * 10 // 100), 3),
 ("18 kitabdan 6-sı dərslikdir. Dərsliklərin bütün kitablara nisbəti hansı kəsrdir?",
  "6/18 = 1/3.",
  ["1/3", "1/6", "3/1", "6/12"], 1,
  kesr(Fraction(6, 18)), 3),
 ("İki ədəd 4 : 5 nisbətindədir. Kiçik ədəd 16-dırsa, böyüyü neçədir?",
  "Bir pay: 16 : 4 = 4; böyük ədəd: 4 · 5 = 20.",
  ["20", "17", "25", "80"], 1, str(16 // 4 * 5), 3),
 ("100% ifadəsi nəyi bildirir?",
  "Tamın hamısını — bütövü.",
  ["Bütöv tamı (hamısını)", "Yarısını", "Onda birini",
   "Heç nəyi"], 1, None, 1),
],
"riy-6-tam-ededler": [
 ("Cəmi hesablayın: −9 + 3.",
  "Modullar fərqi 6, böyük modulun işarəsi mənfi: −6.",
  ["−6", "6", "−12", "12"], 1, tam(-9 + 3), 2),
 ("12 − 20 fərqi neçədir?",
  "12 − 20 = −8.",
  ["−8", "8", "−32", "32"], 1, tam(12 - 20), 2),
 ("(−4)² neçəyə bərabərdir?",
  "(−4) · (−4) = 16.",
  ["16", "−16", "−8", "8"], 1, tam((-4) ** 2), 2),
 ("−1 ilə 2 arasında hansı tam ədədlər var?",
  "Aralıqda 0 və 1 var.",
  ["0 və 1", "Yalnız 1", "−1 və 2", "Heç biri"],
  1, None, 2),
 ("Modulu 11 olan mənfi ədəd hansıdır?",
  "|−11| = 11.",
  ["−11", "11", "−1", "0"], 1, tam(-11), 2),
 ("Ən böyük mənfi tam ədəd hansıdır?",
  "Sıfıra ən yaxın mənfi tam ədəd −1-dir.",
  ["−1", "−10", "0", "1"], 1, tam(-1), 2),
 ("(−54) : 6 neçə edər?",
  "İşarələr fərqlidir, nəticə mənfidir: −9.",
  ["−9", "9", "−48", "−60"], 1, tam(-54 // 6), 2),
 ("Temperatur −2°-dən −9°-yə düşdü. Neçə dərəcə soyudu?",
  "|−9 − (−2)| = 7°.",
  ["7°", "11°", "2°", "9°"], 1,
  "%s°" % tam(abs(-9 - (-2))), 3),
 ("Sıfırın modulu haqqında nə demək olar?",
  "|0| = 0.",
  ["Sıfıra bərabərdir", "Müsbətdir", "Mənfidir",
   "Təyin olunmur"], 1, None, 2),
 ("Kubu hesablayın: (−3)³.",
  "(−3)·(−3)·(−3) = −27.",
  ["−27", "27", "−9", "−6"], 1, tam((-3) ** 3), 3),
],
"riy-6-koordinat": [
 ("Absisi müsbət, ordinatı mənfi olan K(6; −2) nöqtəsi hansı rübdədir?",
  "x > 0, y < 0 — IV rüb.",
  ["IV rübdə", "I rübdə", "II rübdə", "III rübdə"],
  1, None, 3),
 ("Nöqtənin ikinci koordinatı necə adlanır?",
  "İkinci koordinat ordinatdır (y).",
  ["Ordinat", "Absis", "Modul", "Miqyas"], 1, None, 2),
 ("P(−3; −8) nöqtəsinin ordinatı neçədir?",
  "İkinci ədəd ordinatdır: −8.",
  ["−8", "−3", "8", "3"], 1, tam(-8), 2),
 ("(0; 0) koordinatlı nöqtə haradadır?",
  "Hər iki koordinatı sıfır olan nöqtə başlanğıcdadır.",
  ["Koordinat başlanğıcında", "I rübdə", "Ox oxunda sağda",
   "Müstəvidən kənarda"], 1, None, 2),
 ("I rübdə yerləşən nöqtənin koordinatlarının işarələri necədir?",
  "I rübdə x > 0 və y > 0.",
  ["Hər ikisi müsbətdir", "Hər ikisi mənfidir",
   "x müsbət, y mənfidir", "x mənfi, y müsbətdir"],
  1, None, 2),
 ("Ordinatları bərabər olan iki nöqtədən keçən düz xətt hansı oxa paraleldir?",
  "y-lər eynidirsə, xətt Ox oxuna paraleldir.",
  ["Ox oxuna", "Oy oxuna", "Heç birinə", "Hər ikisinə"],
  1, None, 3),
 ("Koordinat müstəvisində nöqtənin yerini göstərmək üçün neçə ədəd lazımdır?",
  "Bir cüt: absis və ordinat.",
  ["İki ədəd (x və y)", "Bir ədəd", "Üç ədəd", "Dörd ədəd"],
  1, None, 2),
 ("A(2; 3) nöqtəsinin Ox oxuna nəzərən simmetrik nöqtəsi hansıdır?",
  "Ox oxuna nəzərən ordinatın işarəsi dəyişir: (2; −3).",
  ["(2; −3)", "(−2; 3)", "(−2; −3)", "(3; 2)"],
  1, None, 3),
 ("Koordinat müstəvisində rüblər hansı istiqamətdə nömrələnir?",
  "I rübdən başlayaraq saat əqrəbinin əksinə.",
  ["Saat əqrəbinin əksinə", "Saat əqrəbi istiqamətində",
   "Soldan sağa", "Yuxarıdan aşağı"], 1, None, 3),
 ("B(−7; 0) nöqtəsi hansı ox üzərindədir?",
  "Ordinatı sıfırdır — absis oxu üzərindədir.",
  ["Absis oxu üzərində", "Ordinat oxu üzərində",
   "Heç bir oxda", "Hər iki oxda"], 1, None, 3),
],
"riy-6-coxluqlar": [
 ("B = {a; e; i} çoxluğunda neçə element var?",
  "Üç hərf — 3 element.",
  ["3 element", "1 element", "6 element", "9 element"], 1,
  "%d element" % len({"a", "e", "i"}), 1),
 ("A = {3; 6; 9}, B = {6; 9; 12}. A ∪ B çoxluğunu tapın.",
  "Bütün elementlər bir yerdə: {3; 6; 9; 12}.",
  ["{3; 6; 9; 12}", "{6; 9}", "{3; 12}", "{3; 6}"], 1,
  coxluq({3, 6, 9} | {6, 9, 12}), 2),
 ("A ⊂ B yazılışı nəyi bildirir?",
  "A çoxluğu B-nin alt çoxluğudur.",
  ["A-nın B-nin alt çoxluğu olduğunu", "A ilə B-nin bərabərliyini",
   "A-nın boş olduğunu", "B-nin A-dan kiçik olduğunu"],
  1, None, 2),
 ("N hərfi ilə hansı ədədlər çoxluğu işarələnir?",
  "N — natural ədədlər çoxluğudur.",
  ["Natural ədədlər", "Tam ədədlər", "Mənfi ədədlər",
   "Kəsrlər"], 1, None, 2),
 ("Z hərfi hansı ədədlər çoxluğunu bildirir?",
  "Z — tam ədədlər çoxluğudur.",
  ["Tam ədədlər", "Natural ədədlər", "Onluq kəsrlər",
   "Sadə ədədlər"], 1, None, 2),
 ("A = {1; 2; 3; 4; 5} çoxluğundan B = {2; 4} çıxılsa, fərq çoxluğu nə olar?",
  "A-da olub B-də olmayanlar: {1; 3; 5}.",
  ["{1; 3; 5}", "{2; 4}", "{1; 2; 3}", "{4; 5}"], 1,
  coxluq({1, 2, 3, 4, 5} - {2, 4}), 3),
 ("Çoxluğun yazılışında eyni element neçə dəfə göstərilir?",
  "Hər element yalnız bir dəfə yazılır.",
  ["Yalnız bir dəfə", "İki dəfə", "İstənilən qədər",
   "Heç yazılmır"], 1, None, 2),
 ("Həftənin günləri çoxluğunda neçə element var?",
  "Həftədə 7 gün var.",
  ["7", "5", "12", "30"], 1, str(7), 1),
 ("Boş çoxluq hansı simvolla işarələnir?",
  "∅ simvolu ilə.",
  ["∅", "∩", "∪", "⊂"], 1, None, 2),
 ("A ∪ B əməli necə adlanır?",
  "İki çoxluğun birləşməsidir.",
  ["Birləşmə", "Kəsişmə", "Fərq", "Bölmə"], 1, None, 2),
],
"riy-6-ifade-tenlik": [
 ("9x − 4x + x ifadəsini sadələşdirin.",
  "9 − 4 + 1 = 6: nəticə 6x.",
  ["6x", "5x", "14x", "6"], 1, None, 2),
 ("Paylama qanunu ilə 5(x − 2) ifadəsini açın.",
  "5x − 10.",
  ["5x − 10", "5x − 2", "5x + 10", "3x"], 1, None, 2),
 ("x − 8 = −3 tənliyinin kökü neçədir?",
  "x = −3 + 8 = 5.",
  ["5", "−5", "−11", "11"], 1, str(-3 + 8), 2),
 ("3x − 7 = 26 olduqda x-in qiymətini tapın.",
  "3x = 33; x = 11.",
  ["11", "33", "19", "7"], 1, str((26 + 7) // 3), 3),
 ("−x = 4 tənliyinin kökü neçədir?",
  "x = −4.",
  ["−4", "4", "1/4", "0"], 1, tam(-4), 2),
 ("Tənliyin kökü nədir?",
  "Tənliyi doğru bərabərliyə çevirən qiymətdir.",
  ["Tənliyi doğru bərabərliyə çevirən qiymət",
   "İstənilən ədəd", "Ən böyük ədəd", "Tənliyin uzunluğu"],
  1, None, 2),
 ("b = 3 olduqda 2b² ifadəsinin qiyməti neçədir?",
  "2 · 9 = 18.",
  ["18", "36", "12", "6"], 1, str(2 * 3 ** 2), 3),
 ("Yarısı 13-ə bərabər olan ədəd hansıdır?",
  "x : 2 = 13; x = 26.",
  ["26", "13", "6,5", "39"], 1, str(13 * 2), 2),
 ("Ədədlə dəyişənin hasilində ədəd vuruğu necə adlanır?",
  "Ədəd vuruğu əmsaldır.",
  ["Əmsal", "Kök", "Modul", "Qüvvət"], 1, None, 2),
 ("x + x + x yazılışı hansı ifadəyə bərabərdir?",
  "Üç dəfə toplama: 3x.",
  ["3x", "x³", "3 + x", "x/3"], 1, None, 1),
],
"riy-6-ucbucaqlar": [
 ("Bucaqları 45° və 85° olan üçbucağın üçüncü bucağını hesablayın.",
  "180 − 45 − 85 = 50°.",
  ["50°", "130°", "40°", "95°"], 1,
  "%d°" % (180 - 45 - 85), 2),
 ("Bərabəryanlı üçbucağın təpə bucağı 40°-dirsə, oturacaq bucaqlarından hər biri neçədir?",
  "(180 − 40) : 2 = 70°.",
  ["70°", "40°", "140°", "35°"], 1,
  "%d°" % ((180 - 40) // 2), 3),
 ("Perimetri 30 sm olan bərabərtərəfli üçbucağın tərəfi neçədir?",
  "30 : 3 = 10 sm.",
  ["10 sm", "15 sm", "90 sm", "6 sm"], 1,
  "%d sm" % (30 // 3), 2),
 ("Bir bucağı düz bucaq olan üçbucaq necə adlanır?",
  "Düz bucağı olan üçbucaq düzbucaqlıdır.",
  ["Düzbucaqlı", "İtibucaqlı", "Korbucaqlı", "Bərabərtərəfli"],
  1, None, 1),
 ("Tərəfləri 5 sm, 5 sm və 7 sm olan üçbucaq hansı növdəndir?",
  "İki tərəfi bərabərdir — bərabəryanlıdır.",
  ["Bərabəryanlı", "Bərabərtərəfli", "Müxtəliftərəfli",
   "Qurmaq olmaz"], 1, None, 2),
 ("Üçbucağın hündürlüyü qarşı tərəfə hansı bucaq altında endirilir?",
  "Hündürlük perpendikulyardır — 90° altında.",
  ["90° altında", "60° altında", "45° altında",
   "İstənilən bucaq altında"], 1, None, 2),
 ("İki bucağı 60° olan üçbucaq hansı növdəndir?",
  "Üçüncü bucaq da 60° olur — bərabərtərəflidir.",
  ["Bərabərtərəfli", "Korbucaqlı", "Düzbucaqlı",
   "Müxtəliftərəfli"], 1, None, 3),
 ("Üçbucağın perimetri necə tapılır?",
  "Üç tərəfin uzunluqları toplanır.",
  ["Tərəflərin cəmi kimi", "Tərəflərin hasili kimi",
   "Bucaqların cəmi kimi", "Sahənin yarısı kimi"],
  1, None, 1),
 ("Tərəfləri 7 sm və 3 sm olan üçbucağın üçüncü tərəfi 10 sm ola bilərmi?",
  "7 + 3 = 10 — cəm üçüncü tərəfə bərabərdir, üçbucaq alınmaz.",
  ["Xeyr, ola bilməz", "Bəli, olar", "Yalnız düzbucaqlıda",
   "Yalnız bərabəryanlıda"], 1,
  ("Xeyr, ola bilməz" if 7 + 3 <= 10 else "Bəli, olar"), 3),
 ("Bərabərtərəfli üçbucağın neçə simmetriya oxu var?",
  "Hər təpədən bir ox keçir: üç.",
  ["Üç", "Bir", "İki", "Heç bir"], 1, None, 3),
],
"riy-6-sahe-hecm": [
 ("Tərəfi 12 sm olan kvadratın sahəsi neçədir?",
  "S = 12² = 144 sm².",
  ["144 sm²", "48 sm²", "24 sm²", "121 sm²"], 1,
  "%d sm²" % (12 ** 2), 2),
 ("Uzunluğu 9 sm, eni 4 sm olan düzbucaqlının sahəsini tapın.",
  "S = 9 · 4 = 36 sm².",
  ["36 sm²", "13 sm²", "26 sm²", "72 sm²"], 1,
  "%d sm²" % (9 * 4), 2),
 ("Diaqonalları 6 sm və 8 sm olan rombun sahəsi neçədir?",
  "S = (6 · 8) : 2 = 24 sm².",
  ["24 sm²", "48 sm²", "14 sm²", "28 sm²"], 1,
  "%d sm²" % (6 * 8 // 2), 3),
 ("Tili 3 sm olan kubun tam səthinin sahəsi neçədir?",
  "Bir üz 9 sm²; altı üz: 6 · 9 = 54 sm².",
  ["54 sm²", "27 sm²", "18 sm²", "36 sm²"], 1,
  "%d sm²" % (6 * 3 ** 2), 3),
 ("Akvariumun ölçüləri 10 sm, 6 sm və 2 sm-dir. Həcmini tapın.",
  "V = 10 · 6 · 2 = 120 sm³.",
  ["120 sm³", "18 sm³", "60 sm³", "240 sm³"], 1,
  "%d sm³" % (10 * 6 * 2), 2),
 ("Bir kvadratmetrdə neçə kvadrat santimetr var?",
  "1 m = 100 sm; 100 · 100 = 10 000 sm².",
  ["10 000 sm²", "100 sm²", "1 000 sm²", "10 sm²"], 1,
  "%s sm²" % fmt(100 * 100), 3),
 ("Həcmi 64 sm³ olan kubun tili neçədir?",
  "4³ = 64 — til 4 sm.",
  ["4 sm", "8 sm", "16 sm", "32 sm"], 1,
  "%d sm" % round(64 ** (1 / 3)), 3),
 ("Sahəsi 45 sm², hündürlüyü 9 sm olan üçbucağın oturacağı neçədir?",
  "a = 2S : h = 90 : 9 = 10 sm.",
  ["10 sm", "5 sm", "36 sm", "405 sm"], 1,
  "%d sm" % (2 * 45 // 9), 3),
 ("Litr hansı kəmiyyətin ölçü vahididir?",
  "Litr həcm vahididir.",
  ["Həcmin", "Sahənin", "Uzunluğun", "Kütlənin"],
  1, None, 1),
 ("Perimetri 20 sm olan kvadratın sahəsi neçədir?",
  "Tərəf 5 sm; S = 25 sm².",
  ["25 sm²", "20 sm²", "400 sm²", "10 sm²"], 1,
  "%d sm²" % ((20 // 4) ** 2), 3),
],
"riy-6-statistika": [
 ("Zər atılanda 4-dən kiçik ədəd düşməsi ehtimalı neçədir?",
  "Uyğun üzlər: 1, 2, 3 — 3/6 = 1/2.",
  ["1/2", "1/3", "2/3", "1/4"], 1, kesr(Fraction(3, 6)), 3),
 ("10, 20, 30, 40 və 50 ədədlərinin ədədi ortası neçədir?",
  "150 : 5 = 30.",
  ["30", "50", "150", "25"], 1,
  str((10 + 20 + 30 + 40 + 50) // 5), 2),
 ("Qutuda 7 ağ və 3 qara kürəcik var. Qara kürəcik çıxarma ehtimalı neçədir?",
  "3/10.",
  ["3/10", "7/10", "3/7", "1/3"], 1, kesr(Fraction(3, 10)), 3),
 ("25, 13, 25, 8, 25 siyahısında ən çox rast gəlinən qiymət hansıdır?",
  "25 üç dəfə təkrarlanır — moda 25-dir.",
  ["25", "13", "8", "96"], 1,
  str(max((25, 13, 25, 8, 25), key=(25, 13, 25, 8, 25).count)), 2),
 ("Sikkə bir dəfə atıldıqda gerbin düşmə şansı nə qədərdir?",
  "İki bərabər imkandan biri.",
  ["1/2 (yarı-yarıya)", "1/4", "1", "2"], 1, None, 2),
 ("4, 9, 13, 20 sırasının medianı neçədir?",
  "Cüt saylı sırada ortadakı ikisinin ortası: (9 + 13) : 2 = 11.",
  ["11", "9", "13", "46"], 1, str((9 + 13) // 2), 3),
 ("Ehtimalı 1 olan hadisə necə adlanır?",
  "Mütləq baş verən hadisə yəqin hadisədir.",
  ["Yəqin hadisə", "Mümkünsüz hadisə", "Təsadüfi hadisə",
   "Qeyri-müəyyən hadisə"], 1, None, 2),
 ("Ehtimalı 0 olan hadisə necə adlanır?",
  "Baş verə bilməyən hadisə mümkünsüz hadisədir.",
  ["Mümkünsüz hadisə", "Yəqin hadisə", "Adi hadisə",
   "Kiçik hadisə"], 1, None, 2),
 ("Dairəvi diaqram nəyi göstərmək üçün əlverişlidir?",
  "Tamın hissələrə necə bölündüyünü göstərir.",
  ["Tamın hissələrə bölünməsini", "Zamanla dəyişməni",
   "Məsafəni", "Temperaturu"], 1, None, 3),
 ("Məlumat toplamaq üçün verilən suallar siyahısı necə adlanır?",
  "Bu, anketdir (sorğu vərəqidir).",
  ["Anket (sorğu vərəqi)", "Lüğət", "Cədvəl", "Xəritə"],
  1, None, 1),
],
}
for _k, _v in ELAVE.items():
    SUALLAR[_k] = SUALLAR[_k] + _v



# 40 sual/movzu proqrami: her movzuya 20 elave sual.
ELAVE40 = {
"riy-6-coxluqlar": [
 ("A = {2; 4; 6; 8} çoxluğunda neçə element var?",
  "Çoxluqda dörd ədəd sadalanıb.",
  ["4 element", "3 element", "8 element", "2 element"],
  1, None, 1),
 ("A = {1; 3; 5}, B = {3; 5; 7}. A ∩ B neçə elementlidir?",
  "Ortaq elementlər 3 və 5-dir.",
  ["2 elementli", "3 elementli", "1 elementli", "6 elementli"],
  1, None, 2),
 ("Ədədlər çoxluğu Q hərfi ilə işarələnirsə, bu hansı çoxluqdur?",
  "Q — rasional ədədlər çoxluğudur.",
  ["Rasional ədədlər", "Natural ədədlər", "Tam ədədlər",
   "Cüt ədədlər"], 1, None, 2),
 ("A ∩ B = ∅ olarsa, çoxluqlar haqqında nə deyilir?",
  "Kəsişmə boşdursa, ortaq element yoxdur.",
  ["Kəsişmirlər", "Bərabərdirlər", "Biri digərinin altıdır",
   "Hər ikisi boşdur"], 1, None, 2),
 ("{x | x < 5, x ∈ N} çoxluğunun elementlərini sadalayın.",
  "5-dən kiçik natural ədədlər: 1, 2, 3, 4.",
  ["1; 2; 3; 4", "0; 1; 2; 3; 4", "1; 2; 3; 4; 5", "2; 3; 4"],
  1, None, 3),
 ("Alt çoxluq işarəsi hansıdır?",
  "Alt çoxluq ⊂ işarəsi ilə göstərilir.",
  ["⊂", "∪", "∩", "∈"], 1, None, 1),
 ("A = {a; b}, B = {a; b}. Bu çoxluqlar haqqında nə demək olar?",
  "Elementləri eynidirsə, çoxluqlar bərabərdir.",
  ["Bərabərdirlər", "Kəsişmirlər", "A böyükdür", "B boşdur"],
  1, None, 1),
 ("İlin fəsillərini çoxluq kimi yazsaq elementlərin sayı neçə olar?",
  "Fəsillər dörddür.",
  ["4 fəsil", "12 fəsil", "3 fəsil", "6 fəsil"], 1, None, 1),
 ("A = {1; 2; 3; 4; 5; 6}, B = {2; 4; 6}. B çoxluğu A üçün nədir?",
  "B-nin bütün elementləri A-dadır.",
  ["Alt çoxluqdur", "Fərq çoxluğudur", "Birləşmədir",
   "Boş çoxluqdur"], 1, None, 2),
 ("Birləşmə əməlində elementlər necə götürülür?",
  "Hər iki çoxluğun elementləri bir dəfə yazılır.",
  ["Hər ikisindən, təkrarsız", "Yalnız birincidən",
   "Yalnız ortaqlar", "Təkrarla iki dəfə"], 1, None, 2),
 ("A çoxluğunun 3, B-nin 4 elementi var, ortaq elementləri yoxdur. A ∪ B-də neçə element var?",
  "3 + 4 = 7.",
  ["7 element", "12 element", "1 element", "4 element"],
  1, None, 2),
 ("Venn diaqramı nə üçün istifadə olunur?",
  "Çoxluqları dairələrlə əyani göstərir.",
  ["Çoxluqları əyani göstərmək üçün", "Tənlik həll etmək üçün",
   "Faiz hesablamaq üçün", "Perimetr ölçmək üçün"], 1, None, 2),
 ("Tək birrəqəmli ədədlər çoxluğunu yazın.",
  "Birrəqəmli təklər: 1, 3, 5, 7, 9.",
  ["{1; 3; 5; 7; 9}", "{1; 3; 5; 7}", "{0; 1; 3; 5; 7; 9}",
   "{2; 4; 6; 8}"], 1, None, 2),
 ("∈ simvolu nəyi bildirir?",
  "∈ — element çoxluğa daxildir deməkdir.",
  ["Elementin çoxluğa aidliyini", "Çoxluqların birləşməsini",
   "Boş çoxluğu", "Bərabərliyi"], 1, None, 1),
 ("A \ B fərq çoxluğuna hansı elementlər daxildir?",
  "A-da olub B-də olmayanlar.",
  ["Yalnız A-da olanlar", "Yalnız B-də olanlar",
   "Ortaq elementlər", "Bütün elementlər"], 1, None, 2),
 ("«5 ∉ A» yazılışı nəyi bildirir?",
  "∉ — daxil deyil işarəsidir.",
  ["5 A-ya daxil deyil", "5 A-ya daxildir", "A boşdur",
   "A-da 5 element var"], 1, None, 1),
 ("Sonsuz çoxluğa misal göstərin.",
  "Natural ədədlər sonsuzdur.",
  ["Natural ədədlər çoxluğu", "Həftənin günləri",
   "Əlifbanın hərfləri", "İlin ayları"], 1, None, 2),
 ("B = {10; 20; 30} çoxluğunun bütün elementləri hansı ədədə bölünür?",
  "Hamısı 10-un bölünənidir.",
  ["10-a", "20-yə", "30-a", "7-yə"], 1, None, 2),
 ("A = {qırmızı; yaşıl}, B = {yaşıl; mavi}. A ∪ B çoxluğunda neçə element var?",
  "Qırmızı, yaşıl, mavi — üç element.",
  ["3 element", "4 element", "2 element", "1 element"],
  1, None, 2),
 ("Çoxluqda elementlərin sırası əhəmiyyət daşıyırmı?",
  "{1; 2} = {2; 1} — sıra önəmsizdir.",
  ["Xeyr, daşımır", "Bəli, həmişə", "Yalnız ədədlərdə",
   "Yalnız hərflərdə"], 1, None, 2),
],
"riy-6-tam-ededler": [
 ("−15 + 8 cəmini tapın.",
  "Modullar fərqi 7, işarə böyüyünki: −7.",
  ["−7", "7", "−23", "23"], 1, tam(-15 + 8), 2),
 ("Mənfi ədədlə müsbət ədədin hasili hansı işarəli olur?",
  "Fərqli işarəli vuruqların hasili mənfidir.",
  ["Mənfi", "Müsbət", "Sıfır", "İşarəsiz"], 1, None, 1),
 ("Qüvvəti hesablayın: (−2)⁴ nəticəsi müsbətdir, yoxsa mənfi?",
  "Cüt qüvvətdə mənfi ədəd müsbət olur: 16.",
  ["Müsbət, 16", "Mənfi, −16", "Müsbət, 8", "Mənfi, −8"],
  1, None, 2),
 ("0 − 14 fərqi neçədir?",
  "Sıfırdan çıxanda əks işarə alınır: −14.",
  ["−14", "14", "0", "−28"], 1, tam(0 - 14), 1),
 ("|−25| modulunu tapın.",
  "Modul məsafədir, həmişə mənfi olmayan: 25.",
  ["25", "−25", "0", "5"], 1, str(abs(-25)), 1),
 ("−65 : (−5) neçə edər?",
  "Eyni işarəlilərin qisməti müsbətdir: 13.",
  ["13", "−13", "60", "−60"], 1, str(-65 // -5), 2),
 ("Temperatur gecə −6° idi, gündüz 9° oldu. Temperatur neçə dərəcə dəyişdi?",
  "9 − (−6) = 15.",
  ["15 dərəcə artdı", "3 dərəcə artdı", "15 dərəcə düşdü",
   "6 dərəcə artdı"], 1, None, 2),
 ("Mənfi ədədlər sıfırdan hansı tərəfdə yerləşir?",
  "Ədəd oxunda mənfilər soldadır.",
  ["Solda", "Sağda", "Üstündə", "Sıfırın içində"], 1, None, 1),
 ("−4 və −9 ədədlərindən hansı kiçikdir?",
  "Ədəd oxunda −9 daha soldadır.",
  ["−9", "−4", "Bərabərdirlər", "Müqayisə olunmur"],
  1, None, 2),
 ("(−7) · 8 hasilini tapın.",
  "7 · 8 = 56, işarə mənfi: −56.",
  ["−56", "56", "−15", "1"], 1, tam(-7 * 8), 2),
 ("İki mənfi ədədin cəmi hansı işarəli olur?",
  "Mənfilərin cəmi yenə mənfidir.",
  ["Mənfi olur", "Müsbət olur", "Sıfır olur", "İşarə itir"],
  1, None, 2),
 ("Əks ədədlərin cəmi neçədir?",
  "a + (−a) = 0.",
  ["Sıfır", "İki qat", "Mənfi bir", "Müsbət bir"], 1, None, 2),
 ("−18 + 18 + 24 cəmini münasib üsulla tapın.",
  "−18 + 18 = 0; qalır 24.",
  ["24", "−24", "60", "0"], 1, str(-18 + 18 + 24), 2),
 ("Bank hesabında −40 manat borc var idi, 100 manat qoyuldu. Qalıq neçədir?",
  "−40 + 100 = 60.",
  ["60 manat", "140 manat", "−60 manat", "40 manat"],
  1, None, 2),
 ("Mənfi vahidi cüt sayda dəfə vursaq nəticə nə olar?",
  "Cüt sayda mənfi vuruq müsbət verir.",
  ["Müsbət vahid (1)", "Mənfi vahid (−1)", "Sıfır",
   "Qeyri-müəyyən"], 1, None, 3),
 ("12 + (−28) cəmini tapın.",
  "Modullar fərqi 16, işarə böyüyünki: −16.",
  ["−16", "16", "−40", "40"], 1, tam(12 + (-28)), 2),
 ("Ədəd oxunda −5 ilə 5 arasındakı məsafə neçə vahiddir?",
  "5 − (−5) = 10.",
  ["10 vahid", "0 vahid", "5 vahid", "25 vahid"], 1, None, 2),
 ("Mənfi ədədin kvadratı hansı işarəli olur?",
  "Kvadrat cüt qüvvətdir — müsbət.",
  ["Həmişə müsbət", "Həmişə mənfi", "Sıfır", "İşarəsi qalır"],
  1, None, 2),
 ("−100-dən böyük, −97-dən kiçik tam ədədləri sadalayın.",
  "Aralıqda −99 və −98 var.",
  ["−99 və −98", "−98 və −96", "−100 və −97", "Yoxdur"],
  1, None, 3),
 ("Çıxmanı toplama ilə əvəz edin: 7 − 12 = 7 + (?).",
  "Çıxmaq əks ədədi toplamaqdır: 7 + (−12).",
  ["(−12)", "12", "(−7)", "19"], 1, None, 2),
],
"riy-6-ifade-tenlik": [
 ("6(x − 3) mötərizəsini açın.",
  "6·x − 6·3 = 6x − 18.",
  ["6x − 18", "6x − 3", "6x + 18", "x − 18"], 1, None, 2),
 ("8y − 3y + 2y ifadəsini sadələşdirin.",
  "8 − 3 + 2 = 7 — 7y.",
  ["7y", "3y", "13y", "9y"], 1, None, 2),
 ("2x − 5 = 23 tənliyinin kökünü tapın.",
  "2x = 28, x = 14.",
  ["14", "9", "28", "18"], 1, str((23 + 5) // 2), 2),
 ("Tənliyin hər iki tərəfini eyni sıfırdan fərqli ədədə bölsək kök dəyişərmi?",
  "Bərabərlik pozulmur, kök qalır.",
  ["Xeyr, dəyişməz", "Bəli, iki dəfə azalar",
   "Bəli, işarəsi dəyişər", "Tənlik itər"], 1, None, 2),
 ("y = 5 olduqda (y + 3)² ifadəsinin qiymətini tapın.",
  "(5 + 3)² = 8² = 64.",
  ["64", "34", "16", "28"], 1, str((5 + 3) ** 2), 2),
 ("İfadəni yazın: ədədin 4 mislindən 7 az.",
  "4x-dən 7 az: 4x − 7.",
  ["4x − 7", "4x + 7", "7 − 4x", "4(x − 7)"], 1, None, 2),
 ("Bölünəni tapın: x : 8 = −4 olarsa, x neçədir?",
  "x = 8 · (−4) = −32.",
  ["−32", "32", "−2", "4"], 1, tam(8 * -4), 2),
 ("−2(a − 6) ifadəsini açın.",
  "−2·a + (−2)·(−6) = −2a + 12.",
  ["−2a + 12", "−2a − 12", "2a + 12", "−2a − 6"], 1, None, 3),
 ("Hansı ədəd 3x + 1 = 22 tənliyinin köküdür?",
  "3x = 21, x = 7.",
  ["x = 7", "x = 21", "x = 3", "x = 8"], 1, None, 2),
 ("−12y ifadəsində əmsal neçədir?",
  "Dəyişənin qarşısındakı ədəd əmsaldır: −12.",
  ["−12", "12", "y", "1"], 1, None, 1),
 ("Oxşar hədlər hansılardır?",
  "Eyni dəyişənli hədlər oxşardır.",
  ["Eyni dəyişənli hədlər", "Bütün ədədlər",
   "Mötərizəli hədlər", "Mənfi hədlər"], 1, None, 2),
 ("5x + 20 = 0 tənliyinin kökü neçədir?",
  "5x = −20, x = −4.",
  ["−4", "4", "−20", "0"], 1, tam(-20 // 5), 2),
 ("Bərabərsizliyi həll edin: x + 3 < 7. Hansı natural ədədlər ödəyir?",
  "x < 4: 1, 2 və 3.",
  ["1, 2, 3", "1, 2, 3, 4", "4, 5, 6", "Yalnız 3"], 1, None, 3),
 ("a = 4, b = −2 olduqda a·b − 12 ifadəsinin qiymətini tapın.",
  "4·(−2) = −8; −8 − 12 = −20.",
  ["−20", "−4", "20", "4"], 1, tam(4 * -2 - 12), 3),
 ("Tənlik qurun: fikrimdə tutduğum ədədi 2-yə vurub 9 çıxdıqda 5 alınır.",
  "Ədəd x-dirsə: 2x − 9 = 5.",
  ["2x − 9 = 5", "2x + 9 = 5", "9 − 2x = 5", "2(x − 9) = 5"],
  1, None, 2),
 ("x/2 + 3 = 8 tənliyinin kökü neçədir?",
  "x/2 = 5, x = 10.",
  ["x = 10", "x = 5", "x = 16", "x = 22"], 1, None, 2),
 ("Eynilik nədir?",
  "Dəyişənin bütün qiymətlərində doğru qalan bərabərlik.",
  ["Hər qiymətdə doğru bərabərlik", "Kökü olmayan tənlik",
   "Bərabərsizlik", "Mənfi ifadə"], 1, None, 3),
 ("3(x + 2) = 3x + 6 yazılışı nəyə misaldır?",
  "Hər x üçün doğrudur — eynilikdir.",
  ["Eyniliyə", "Kökü 2 olan tənliyə", "Bərabərsizliyə",
   "Səhv yazılışa"], 1, None, 3),
 ("Mötərizə qarşısında mənfi işarə olduqda mötərizə açılarkən nə baş verir?",
  "Daxildəki hər həddin işarəsi dəyişir.",
  ["İşarələr əksinə dəyişir", "Heç nə dəyişmir",
   "Hədlər silinir", "Mötərizə qalır"], 1, None, 2),
 ("Kökü −3 olan tənliyi seçin.",
  "x + 3 = 0 üçün x = −3.",
  ["x + 3 = 0", "x − 3 = 0", "3x = 3", "x : 3 = 3"],
  1, None, 3),
],
"riy-6-koordinat": [
 ("Absisi mənfi, ordinatı müsbət olan nöqtə hansı rübdə olur?",
  "(−; +) işarələri II rübə uyğundur.",
  ["II rübdə", "I rübdə", "III rübdə", "IV rübdə"], 1, None, 2),
 ("Ordinat oxu üzərindəki nöqtələrin hansı koordinatı sıfırdır?",
  "Oy üzərində absis sıfırdır.",
  ["Absisi", "Ordinatı", "Hər ikisi", "Heç biri"], 1, None, 2),
 ("M(5; −5) nöqtəsinin absisini göstərin.",
  "Birinci koordinat absisdir: 5.",
  ["Absisi 5-dir", "Absisi −5-dir", "Absisi 0-dır",
   "Absisi 10-dur"], 1, None, 1),
 ("A(1; 2), B(4; 2), C(4; 6) nöqtələri üçbucağın təpələridir. Düz bucaq hansı təpədədir?",
  "AB üfüqi, BC şaqulidir — B-də düz bucaq.",
  ["B təpəsində", "A təpəsində", "C təpəsində",
   "Düz bucaq yoxdur"], 1, None, 3),
 ("Nöqtənin Oy oxuna nəzərən simmetriyası zamanı hansı koordinat dəyişir?",
  "Oy simmetriyasında absisin işarəsi dəyişir.",
  ["Absisin işarəsi", "Ordinatın işarəsi", "Hər ikisi",
   "Heç biri"], 1, None, 3),
 ("A(3; 0), B(9; 0) nöqtələri arasındakı məsafə neçə vahiddir?",
  "9 − 3 = 6.",
  ["6 vahid", "12 vahid", "3 vahid", "9 vahid"], 1, None, 2),
 ("Koordinat başlanğıcının koordinatları hansılardır?",
  "Başlanğıc: (0; 0).",
  ["(0; 0)", "(1; 1)", "(0; 1)", "(1; 0)"], 1, None, 1),
 ("Absisi müsbət, ordinatı mənfi nöqtələr hansı rübü doldurur?",
  "(+; −) IV rübdür.",
  ["IV rübü", "I rübü", "II rübü", "III rübü"], 1, None, 2),
 ("Şahmat taxtasındakı xanaların ünvanı (e2 kimi) nəyə bənzəyir?",
  "Hərf-rəqəm cütü koordinat kimidir.",
  ["Koordinatlara", "Kəsrlərə", "Faizlərə", "Çoxluqlara"],
  1, None, 1),
 ("Absisi sıfır olan P(0; −6) nöqtəsinin yeri haradadır?",
  "Absis 0-dırsa, nöqtə Oy üzərindədir.",
  ["Ordinat oxu üzərində", "Absis oxu üzərində", "III rübdə",
   "Başlanğıcda"], 1, None, 2),
 ("Xəritədə yerin ünvanını bildirən en və uzunluq dairələri riyaziyyatda nəyə uyğundur?",
  "İki ədədlə yer göstərmək koordinat sistemidir.",
  ["Koordinat sisteminə", "Perimetrə", "Çoxluğa", "Modula"],
  1, None, 2),
 ("A(2; 3) və B(2; 9) parçasının orta nöqtəsinin koordinatları hansılardır?",
  "Ordinatların ortası: (3 + 9) : 2 = 6 — (2; 6).",
  ["(2; 6)", "(2; 12)", "(4; 6)", "(6; 2)"], 1, None, 3),
 ("Ox oxu üzərindəki nöqtənin ordinatı neçədir?",
  "Absis oxu üzərində ordinat sıfırdır.",
  ["Sıfırdır", "Birdir", "Mənfidir", "İstənilən ola bilər"],
  1, None, 2),
 ("Hər iki koordinatı mənfi olan nöqtə hansı rübdə yerləşir?",
  "(−; −) III rübdür.",
  ["III rübdə", "I rübdə", "II rübdə", "IV rübdə"], 1, None, 2),
 ("Kompüter oyunlarında personajın ekrandakı yeri nə ilə göstərilir?",
  "Ekran nöqtələri koordinatlarla ünvanlanır.",
  ["Koordinatlarla", "Faizlə", "Kəsrlə", "Modulla"],
  1, None, 1),
 ("Simmetriya: A(7; 2)-nin absis oxuna görə əksi hansı koordinatlıdır?",
  "Ox simmetriyasında ordinatın işarəsi dəyişir: (7; −2).",
  ["(7; −2)", "(−7; 2)", "(−7; −2)", "(2; 7)"], 1, None, 3),
 ("Absis sözü koordinat sistemində nəyi bildirir?",
  "Absis — nöqtənin birinci koordinatıdır.",
  ["Birinci koordinatı", "İkinci koordinatı", "Rübün nömrəsini",
   "Oxların kəsişməsini"], 1, None, 1),
 ("K(a; b) nöqtəsi I rübdədirsə, a və b haqqında nə demək olar?",
  "I rübdə hər iki koordinat müsbətdir.",
  ["Hər ikisi müsbətdir", "Hər ikisi mənfidir",
   "a mənfi, b müsbətdir", "a müsbət, b mənfidir"], 1, None, 2),
 ("Düzbucaqlının təpələri A(1; 1), B(5; 1), C(5; 4), D(1; 4)-dür. Eni neçə vahiddir?",
  "4 − 1 = 3.",
  ["3 vahid", "4 vahid", "5 vahid", "1 vahid"], 1, None, 3),
 ("Koordinat müstəvisi hansı alimin adı ilə bağlıdır?",
  "Sistemi Rene Dekart təklif edib.",
  ["Dekartın", "Pifaqorun", "Arximedin", "Evklidin"],
  1, None, 2),
],
"riy-6-natural-ededler": [
 ("EBOB(34, 51) neçədir?",
  "34 = 2·17, 51 = 3·17 — EBOB 17-dir.",
  ["17", "34", "3", "102"], 1, None, 3),
 ("EKOB(10, 15) neçədir?",
  "10 = 2·5, 15 = 3·5 — EKOB 30-dur.",
  ["30", "150", "5", "60"], 1, None, 2),
 ("Sadə ədəd neçə bölənə malikdir?",
  "Yalnız 1-ə və özünə bölünür.",
  ["Yalnız iki bölənə", "Üç bölənə", "Bir bölənə",
   "Sonsuz bölənə"], 1, None, 1),
 ("100-ün sadə vuruqlara ayrılışı hansıdır?",
  "100 = 4 · 25 = 2·2·5·5.",
  ["2 · 2 · 5 · 5", "4 · 25", "10 · 10", "2 · 5 · 10"],
  1, None, 2),
 ("Hansı ədəd 6-ya bölünür (həm 2-yə, həm 3-ə)?",
  "252 cütdür, rəqəm cəmi 9 — 3-ə bölünür.",
  ["252", "253", "254", "255"], 1, None, 2),
 ("1-dən 10-a qədər mürəkkəb ədədləri sayın: neçə dənədir?",
  "Mürəkkəblər: 4, 6, 8, 9, 10 — beş dənə.",
  ["5 dənə", "4 dənə", "6 dənə", "3 dənə"], 1, None, 3),
 ("2² · 7 hasilinə bərabər ədəd hansıdır?",
  "4 · 7 = 28.",
  ["28", "14", "22", "56"], 1, str(2 ** 2 * 7), 2),
 ("42 ədədinin bütün bölənləri sırası hansıdır?",
  "42 = 2·3·7; bölənlər: 1, 2, 3, 6, 7, 14, 21, 42.",
  ["1, 2, 3, 6, 7, 14, 21, 42", "1, 2, 3, 7, 42",
   "2, 3, 6, 7", "1, 42"], 1, None, 3),
 ("İki sadə ədədin hasili sadə ola bilərmi?",
  "Hasil hər iki vuruğa bölünür — mürəkkəbdir.",
  ["Xeyr, mürəkkəb olur", "Bəli, həmişə", "Bəzən olur",
   "Yalnız cütlərdə"], 1, None, 3),
 ("10⁶ yazılışı hansı ədəddir?",
  "10 altı dəfə vurulur: 1 000 000.",
  ["1 000 000", "100 000", "60", "10 000 000"], 1, None, 2),
 ("Hansı ədədə bölmək olmaz?",
  "Sıfıra bölmə təyin olunmayıb.",
  ["Sıfıra", "Birə", "Özünə", "Mənfi ədədə"], 1, None, 1),
 ("45 və 60 ədədlərinin ortaq bölənlərini sadalayın.",
  "EBOB 15-dir; bölənləri: 1, 3, 5, 15.",
  ["1, 3, 5, 15", "1, 5, 9, 15", "3, 5, 12", "1, 15, 45"],
  1, None, 3),
 ("Ardıcıl üç natural ədədin cəmi həmişə hansı ədədə bölünür?",
  "n + (n+1) + (n+2) = 3n + 3 — 3-ə bölünür.",
  ["3-ə", "4-ə", "5-ə", "9-a"], 1, None, 3),
 ("Ən kiçik sadə ədəd hansıdır?",
  "Sadələrin birincisi 2-dir.",
  ["2-dir", "1-dir", "3-dür", "0-dır"], 1, None, 1),
 ("7² − 2⁴ fərqini hesablayın.",
  "49 − 16 = 33.",
  ["33", "45", "31", "17"], 1, str(7 ** 2 - 2 ** 4), 2),
 ("Kvadratı 289 olan natural ədəd hansıdır?",
  "17 · 17 = 289.",
  ["17", "19", "23", "27"], 1, None, 2),
 ("EBOB-u 1 olan ədədlər necə adlanır?",
  "Ortaq böləni yalnız 1 olanlar qarşılıqlı sadədir.",
  ["Qarşılıqlı sadə ədədlər", "Cüt ədədlər", "Tərs ədədlər",
   "Mürəkkəb ədədlər"], 1, None, 3),
 ("Bölünmə əlaməti: 4-ə bölünmə son neçə rəqəmlə yoxlanılır?",
  "Son iki rəqəmin əmələ gətirdiyi ədədə baxılır.",
  ["Son iki rəqəmlə", "Son bir rəqəmlə", "İlk rəqəmlə",
   "Rəqəmlərin cəmi ilə"], 1, None, 2),
 ("Şagirdlər 8-8 və 10-10 qruplaşanda hər dəfə tam bölünür. Ən azı neçə şagird var?",
  "EKOB(8, 10) = 40.",
  ["40 şagird", "18 şagird", "80 şagird", "20 şagird"],
  1, None, 3),
 ("İki ədədin hasili EBOB × EKOB hasilinə bərabərdirmi?",
  "a·b = EBOB(a,b) · EKOB(a,b).",
  ["Bəli, bərabərdir", "Xeyr, həmişə böyükdür",
   "Xeyr, həmişə kiçikdir", "Yalnız sadələrdə"], 1, None, 3),
],
"riy-6-nisbet-faiz": [
 ("15 : 25 nisbətini sadələşdirin.",
  "Hər həd 5-ə bölünür: 3 : 5.",
  ["3 : 5", "5 : 3", "1 : 10", "15 : 5"], 1, None, 1),
 ("Tənasüb nədir?",
  "İki nisbətin bərabərliyi tənasübdür.",
  ["İki nisbətin bərabərliyi", "İki ədədin cəmi",
   "Faizin yazılışı", "Kəsrin tərsi"], 1, None, 1),
 ("x : 6 = 28 : 8 tənasübünü həll edin.",
  "x = 6 · 28 : 8 = 21.",
  ["x = 21", "x = 24", "x = 14", "x = 42"], 1, None, 3),
 ("Ədədin 150%-i 60-dırsa, ədəd özü neçədir?",
  "60 : 1,5 = 40.",
  ["40", "90", "45", "30"], 1, str(60 * 100 // 150), 3),
 ("Miqyas 1 : 200 000 olan xəritədə 5 sm-lik parça həqiqətdə hansı məsafəni göstərir?",
  "5 × 200 000 sm = 10 km.",
  ["10 km", "1 km", "100 km", "2 km"], 1, None, 3),
 ("Nisbətdə birinci hədd necə adlanır?",
  "Birinci hədd əvvəlki hədd adlanır.",
  ["Əvvəlki hədd", "Sonrakı hədd", "Orta hədd", "Kənar hədd"],
  1, None, 2),
 ("Qarışıqda su və sirkə 5 : 1 nisbətindədir. 300 q sirkəyə neçə qram su lazımdır?",
  "300 × 5 = 1 500.",
  ["1 500 q", "300 q", "600 q", "1 000 q"], 1, None, 2),
 ("60-ın 80-ə nisbətini faizlə ifadə edin.",
  "60/80 = 3/4 = 75%.",
  ["75%", "80%", "60%", "133%"], 1, None, 2),
 ("Endirimdən sonra 80 manatlıq mal 68 manata satılır. Endirim neçə faizdir?",
  "Endirim 12 manatdır; 12/80 = 15%.",
  ["15%", "12%", "20%", "85%"], 1, None, 3),
 ("Tənasübün kənar hədlərinin hasili nəyə bərabərdir?",
  "Kənarların hasili ortaların hasilinə bərabərdir.",
  ["Orta hədlərin hasilinə", "Kənarların cəminə",
   "Sıfıra", "Nisbətin özünə"], 1, None, 2),
 ("İki ədəd 2 : 7 nisbətindədir, cəmləri 63-dür. Kiçik ədədi tapın.",
  "63 : 9 = 7; kiçik: 7 × 2 = 14.",
  ["14", "49", "18", "9"], 1, str(63 // 9 * 2), 3),
 ("1 kq qoz 12 manatdır. 250 qram neçə manatdır?",
  "250 q — kiloqramın 1/4-i: 12 : 4 = 3.",
  ["3 manat", "4 manat", "6 manat", "2,5 manat"], 1, None, 2),
 ("Faiz artımı: 40 manat 25% artsa neçə olar?",
  "Artım 10 manat; 40 + 10 = 50.",
  ["50 manat", "45 manat", "65 manat", "10 manat"], 1, None, 2),
 ("Nisbət dəyişməz qalsın deyə hər iki həddi nə etmək olar?",
  "Hər iki həddi eyni ədədə vurmaq/bölmək olar.",
  ["Eyni ədədə vurmaq və ya bölmək", "Yalnız toplamaq",
   "Yerlərini dəyişmək", "Birini silmək"], 1, None, 2),
 ("Üç nəfər mükafatı 1 : 2 : 3 nisbətində bölür. Mükafat 120 manatdırsa, ən böyük pay neçədir?",
  "120 : 6 = 20; böyük pay 3 × 20 = 60.",
  ["60 manat", "40 manat", "20 manat", "80 manat"],
  1, None, 3),
 ("Piroq reseptində un : şəkər = 3 : 1-dir. 600 q un üçün nə qədər şəkər lazımdır?",
  "600 : 3 = 200.",
  ["200 q", "300 q", "100 q", "1 800 q"], 1, None, 2),
 ("Faizi onluq kəsrə çevirin: 8% = ?",
  "8% = 8/100 = 0,08.",
  ["0,08", "0,8", "8", "0,008"], 1, None, 2),
 ("Avtomobil 240 km yolu 3 saata gedir. Orta sürəti neçədir?",
  "240 : 3 = 80.",
  ["80 km/saat", "70 km/saat", "60 km/saat", "120 km/saat"],
  1, None, 2),
 ("İki şəhər arası xəritədə 7 sm, həqiqətdə 14 km-dir. Miqyası tapın.",
  "14 km = 1 400 000 sm; 1 400 000 : 7 = 200 000.",
  ["1 : 200 000", "1 : 2 000", "1 : 20 000", "1 : 700 000"],
  1, None, 3),
 ("Nisbət hansı işarə ilə yazılır?",
  "Nisbət iki nöqtə ilə göstərilir: a : b.",
  ["İki nöqtə (:)", "Vergül", "Bərabərlik", "Faiz (%)"],
  1, None, 1),
],
"riy-6-sahe-hecm": [
 ("Tərəfi 7 sm olan kvadratın perimetri və sahəsi hansı cütdür?",
  "P = 28 sm, S = 49 sm².",
  ["28 sm və 49 sm²", "14 sm və 49 sm²", "28 sm və 14 sm²",
   "49 sm və 28 sm²"], 1, None, 2),
 ("Üçbucağın oturacağı 14 sm, hündürlüyü 5 sm-dirsə, sahəsi neçə kvadrat santimetrdir?",
  "S = 14 × 5 : 2 = 35.",
  ["35 sm²", "70 sm²", "19 sm²", "45 sm²"], 1, None, 2),
 ("1 km² neçə hektardır?",
  "1 km² = 100 ha.",
  ["100 hektar", "10 hektar", "1 000 hektar", "50 hektar"],
  1, None, 3),
 ("Yük konteynerinin ölçüləri 6 m, 5 m və 4 m-dir. Konteynerin həcmi neçə kub metrdir?",
  "V = 6 × 5 × 4 = 120.",
  ["120 m³", "15 m³", "60 m³", "120 m²"], 1, None, 2),
 ("Diaqonalları 10 sm və 12 sm olan rombun sahəsini yarımhasil düsturu ilə tapın.",
  "S = 10 × 12 : 2 = 60.",
  ["60 sm²", "120 sm²", "22 sm²", "30 sm²"], 1, None, 2),
 ("Tili 6 sm olan kubun həcmi ilə tili 3 sm olan kubun həcminin nisbətini tapın.",
  "216 : 27 = 8 : 1.",
  ["8 : 1", "2 : 1", "4 : 1", "6 : 3"], 1, None, 3),
 ("Paraleloqramda oturacaq 13 sm, hündürlük 4 sm olarsa, sahə neçə olar?",
  "S = 13 × 4 = 52.",
  ["52 sm²", "34 sm²", "26 sm²", "17 sm²"], 1, None, 2),
 ("Trapesiyanın oturacaqları 6 sm və 10 sm, hündürlüyü 5 sm-dir. Sahəsini tapın.",
  "S = (6 + 10) : 2 × 5 = 40.",
  ["40 sm²", "80 sm²", "21 sm²", "300 sm²"], 1, None, 3),
 ("1 m² neçə kvadrat desimetrdir?",
  "1 m = 10 dm; 10 × 10 = 100.",
  ["100 dm²", "10 dm²", "1 000 dm²", "10 000 dm²"], 1, None, 2),
 ("Kubun həcmi 125 sm³-dursa, bir tilinin uzunluğunu tapın.",
  "5³ = 125 — til 5 sm.",
  ["5 sm", "25 sm", "12,5 sm", "15 sm"], 1, None, 3),
 ("Otağın döşəməsi 5 m × 4 m-dir. Döşəməyə neçə kvadrat metr xalça lazımdır?",
  "5 × 4 = 20.",
  ["20 m²", "9 m²", "40 m²", "10 m²"], 1, None, 1),
 ("Sahə vahidləri sırasında 1 ar neçə kvadrat metrdir?",
  "1 ar = 100 m².",
  ["100 m²", "10 m²", "1 000 m²", "1 m²"], 1, None, 3),
 ("Divarın sahəsi 12 m²-dir. 1 banka boya 4 m² örtür. Neçə banka lazımdır?",
  "12 : 4 = 3.",
  ["3 banka", "4 banka", "8 banka", "48 banka"], 1, None, 2),
 ("Kubun tam səthi 96 sm²-dirsə, bir üzünün sahəsi neçədir?",
  "96 : 6 = 16.",
  ["16 sm²", "48 sm²", "12 sm²", "90 sm²"], 1, None, 3),
 ("Hündürlüyü tapın: paraleloqramın sahəsi 72 sm², oturacağı 9 sm-dir.",
  "72 : 9 = 8.",
  ["8 sm", "9 sm", "63 sm", "81 sm"], 1, None, 2),
 ("Üçbucağın sahəsi 30 sm², oturacağı 10 sm-dirsə, hündürlüyü neçədir?",
  "h = 2S : a = 60 : 10 = 6.",
  ["6 sm", "3 sm", "300 sm", "20 sm"], 1, None, 3),
 ("Su çəni 2 m × 1 m × 1 m ölçüsündədir. Çənə neçə litr su tutar?",
  "V = 2 m³ = 2 000 litr.",
  ["2 000 litr", "200 litr", "2 litr", "20 000 litr"],
  1, None, 3),
 ("Kvadratın sahəsi 81 sm²-dirsə, perimetri neçədir?",
  "Tərəf 9 sm; P = 36 sm.",
  ["36 sm", "81 sm", "18 sm", "27 sm"], 1, None, 3),
 ("Rombun sahə düsturunda diaqonalların hasili nəyə bölünür?",
  "S = d₁·d₂ : 2.",
  ["İkiyə", "Dördə", "Tərəfə", "Perimetrə"], 1, None, 2),
 ("Formaları fərqli, sahələri bərabər fiqurlar ola bilərmi?",
  "6×2 düzbucaqlı və 4×3 düzbucaqlı — hər ikisi 12 sm².",
  ["Bəli, ola bilər", "Xeyr, olmaz", "Yalnız kvadratlarda",
   "Yalnız dairələrdə"], 1, None, 2),
],
"riy-6-statistika": [
 ("Zərin yalnız bir üzündə 6 var. Bir atışda 6 gəlmə şansı hansı kəsrdir?",
  "Altı üzdən biri: 1/6.",
  ["1/6", "1/2", "1/3", "6/6"], 1, None, 2),
 ("Qutuda 4 yaşıl, 6 sarı kürəcik var. Sarı çıxarma ehtimalı neçədir?",
  "6/10 = 3/5.",
  ["3/5", "2/5", "6/4", "1/6"], 1, None, 2),
 ("Median tapılarkən sıra əvvəlcə nə edilir?",
  "Qiymətlər artan sırada düzülür.",
  ["Artan sırada düzülür", "Cəmlənir", "Vurulur",
   "Yarıya bölünür"], 1, None, 2),
 ("5, 9, 16, 21, 30 sırasının medianı neçədir?",
  "Beş ədədin ortadakısı üçüncüdür: 16.",
  ["16", "21", "9", "15"], 1, None, 2),
 ("Ehtimal 3/4-dürsə, hadisənin baş verməməsi ehtimalı neçədir?",
  "1 − 3/4 = 1/4.",
  ["1/4", "3/4", "1/2", "0"], 1, None, 3),
 ("Sikkə 100 dəfə atıldı, 47 dəfə gerb düşdü. Gerbin nisbi tezliyi neçədir?",
  "47/100 = 0,47.",
  ["0,47", "0,53", "47", "4,7"], 1, None, 2),
 ("Altı ədədin ədədi ortası 9-dursa, onların cəmi neçə olar?",
  "9 × 6 = 54.",
  ["54", "15", "45", "96"], 1, str(9 * 6), 2),
 ("Zamanla dəyişməni hansı diaqram daha yaxşı göstərir?",
  "Dəyişmə xətti qrafiklə izlənir.",
  ["Xətti qrafik", "Dairəvi diaqram", "Piktoqram", "Cədvəl"],
  1, None, 2),
 ("1, 2, 2, 3, 3, 3, 4 sırasında tezliyi ən yüksək qiymət hansıdır?",
  "3 üç dəfə təkrarlanır.",
  ["3-dür", "2-dir", "4-dür", "1-dir"], 1, None, 1),
 ("Sorğuda 40 nəfərdən 25%-i «bəli» deyib. Neçə nəfər «bəli» deyib?",
  "40 : 4 = 10.",
  ["10 nəfər", "25 nəfər", "4 nəfər", "15 nəfər"], 1, None, 2),
 ("36 kartlıq dəstdən bir kart çəkilir. Tuz çıxma ehtimalı neçədir (4 tuz var)?",
  "4/36 = 1/9.",
  ["1/9", "1/36", "4/9", "1/4"], 1, None, 3),
 ("Faiz cədvəlində bütün payların cəmi neçə olmalıdır?",
  "Paylar birlikdə tamı verir: 100%.",
  ["Bəli, 100% olmalıdır", "50% kifayətdir",
   "İstənilən qədər", "0% olmalıdır"], 1, None, 2),
 ("7, 7, 8, 9, 14 sırası üçün moda və median cütünü göstərin.",
  "Moda 7 (iki dəfə), median ortadakı 8-dir.",
  ["Moda 7, median 8", "Moda 8, median 7", "Moda 14, median 9",
   "Moda 7, median 9"], 1, None, 3),
 ("Mümkün hallar 20, əlverişli hallar 5-dirsə, ehtimal neçədir?",
  "5/20 = 0,25.",
  ["0,25", "0,5", "4", "0,05"], 1, None, 2),
 ("Ehtimal 1-dən böyük ola bilərmi?",
  "Ehtimal 0 ilə 1 arasındadır.",
  ["Xeyr, mümkün deyil", "Bəli, hər zaman", "Bəli, zər atanda",
   "Yalnız faizlə"], 1, None, 2),
 ("Orta qiymət hesabında bir qiymət çox böyükdürsə, ortaya necə təsir edir?",
  "Böyük qiymət ortanı artırır.",
  ["Ortanı yuxarı çəkir", "Ortanı azaldır", "Təsir etmir",
   "Ortanı sıfırlayır"], 1, None, 3),
 ("Lotereyada 200 biletdən 8-i uduşludur. Uduş ehtimalı neçədir?",
  "8/200 = 1/25.",
  ["1/25", "1/8", "1/200", "8/100"], 1, None, 3),
 ("10, 20, 33 ədədlərinin ədədi ortasını tapın.",
  "(10 + 20 + 33) : 3 = 21.",
  ["21", "20", "22", "63"], 1, str((10 + 20 + 33) // 3), 2),
 ("Nisbi tezlik hansı düsturla tapılır?",
  "Hadisənin sayı cəhdlərin sayına bölünür.",
  ["Hadisə sayı : cəhd sayı", "Cəhd sayı : hadisə sayı",
   "Hadisə sayı × cəhd sayı", "Cəhdlərin cəmi"], 1, None, 3),
 ("Ehtimalı 0,9 olan hadisə haqqında nə demək olar?",
  "0,9 çox yüksək ehtimaldır.",
  ["Çox gözləniləndir", "Mümkünsüzdür", "Yəqin deyil",
   "Ehtimalı azdır"], 1, None, 2),
],
"riy-6-ucbucaqlar": [
 ("Üçbucağın xarici bucağı ona bitişik olmayan iki daxili bucağın cəminə bərabərdirmi?",
  "Xarici bucaq teoremi bunu deyir.",
  ["Bəli, bərabərdir", "Xeyr, kiçikdir", "Xeyr, böyükdür",
   "Yalnız düzbucaqlıda"], 1, None, 3),
 ("Bucaqları 30° və 70° olan üçbucağın üçüncü bucağı neçədir?",
  "180 − 30 − 70 = 80.",
  ["80°", "100°", "70°", "90°"], 1, None, 2),
 ("Bərabəryanlı üçbucağın oturacaq bucağı 65°-dirsə, təpə bucağı neçədir?",
  "180 − 65 − 65 = 50.",
  ["50°", "65°", "115°", "25°"], 1, None, 3),
 ("Perimetri hesablayın: üçbucağın tərəfləri 4 sm, 7 sm və 9 sm-dir.",
  "4 + 7 + 9 = 20.",
  ["20 sm", "19 sm", "21 sm", "252 sm"], 1, None, 1),
 ("Düzbucaqlı üçbucaqda düz bucağı əmələ gətirən tərəflər necə adlanır?",
  "Düz bucağın tərəfləri katetlərdir.",
  ["Katetlər", "Hipotenuzlar", "Medianlar", "Oturacaqlar"],
  1, None, 2),
 ("Düzbucaqlı üçbucağın ən uzun tərəfi necə adlanır?",
  "Düz bucağın qarşısındakı tərəf hipotenuzdur.",
  ["Hipotenuz", "Katet", "Tənbölən", "Orta xətt"], 1, None, 2),
 ("Bərabəryanlı üçbucağın yan tərəfi 6 sm, oturacağı 4 sm-dirsə, perimetri neçədir?",
  "6 + 6 + 4 = 16.",
  ["16 sm", "14 sm", "10 sm", "24 sm"], 1, None, 2),
 ("Təpəni qarşı tərəfin orta nöqtəsi ilə birləşdirən parça necə adlanır?",
  "Bu parça median adlanır.",
  ["Median", "Hündürlük", "Tənbölən", "Diaqonal"], 1, None, 3),
 ("Üçbucaq bərabərsizliyi: 5 sm, 5 sm və 10 sm tərəfli üçbucaq qurmaq mümkündürmü?",
  "5 + 5 = 10 — üçüncü tərəfdən böyük deyil, qurulmur.",
  ["Xeyr, mümkün deyil", "Bəli, mümkündür",
   "Yalnız bərabəryanlı olar", "Yalnız düzbucaqlı olar"],
  1, None, 3),
 ("Bucaqlarına görə üçbucaqların növləri hansılardır?",
  "İti, düz və kor bucağa görə üç növ var.",
  ["İtibucaqlı, düzbucaqlı, korbucaqlı",
   "Bərabərtərəfli, kvadrat, romb", "Böyük, orta, kiçik",
   "Sadə, mürəkkəb, tam"], 1, None, 2),
 ("Tərəfi tapın: bərabərtərəfli üçbucağın perimetri 27 sm-dir.",
  "27 : 3 = 9.",
  ["9 sm", "13,5 sm", "3 sm", "81 sm"], 1, None, 2),
 ("Bucağı iki bərabər hissəyə bölən parça üçbucaqda necə adlanır?",
  "Bu parça tənbölən adlanır.",
  ["Tənbölən", "Median", "Hündürlük", "Orta xətt"], 1, None, 2),
 ("Düzbucaqlı üçbucağın iti bucaqlarından biri 35°-dirsə, digəri neçədir?",
  "90 − 35 = 55.",
  ["55°", "45°", "35°", "65°"], 1, None, 2),
 ("Bir üçbucaqda iki kor bucaq ola bilərmi?",
  "İki kor bucağın cəmi 180°-dən çox olardı.",
  ["Xeyr, cəm 180°-ni aşar", "Bəli, ola bilər",
   "Yalnız bərabəryanlıda", "Yalnız böyük üçbucaqda"],
  1, None, 3),
 ("Hər tərəfi fərqli olan üçbucaq necə adlanır?",
  "Bütün tərəfləri fərqli üçbucaq müxtəliftərəflidir.",
  ["Müxtəliftərəfli", "Bərabərtərəfli", "Düzbucaqlı",
   "Korbucaqlı"], 1, None, 1),
 ("İki üçbucağın bütün tərəfləri və bucaqları bərabərdirsə, onlar necədir?",
  "Belə üçbucaqlar konqruyentdir.",
  ["Konqruyentdir", "Paraleldir", "Perpendikulyar",
   "Simmetrikdir"], 1, None, 2),
 ("Bərabərtərəfli üçbucaq eyni zamanda bərabəryanlıdırmı?",
  "Üç bərabər tərəfdən ikisi də bərabərdir.",
  ["Bəli, xüsusi halıdır", "Xeyr, ayrıdır",
   "Yalnız kiçik olanda", "Yalnız iti olanda"], 1, None, 3),
 ("Üçbucağın hündürlükləri neçə nöqtədə kəsişir?",
  "Hündürlüklər bir nöqtədə kəsişir.",
  ["Bir nöqtədə", "Üç nöqtədə", "İki nöqtədə", "Kəsişmir"],
  1, None, 3),
 ("45°, 45°, 90° bucaqlı üçbucaq hansı iki növün birləşməsidir?",
  "İki bucağı bərabərdir və biri düzdür.",
  ["Bərabəryanlı və düzbucaqlı", "Bərabərtərəfli və kor",
   "Müxtəliftərəfli və iti", "Kor və düz"], 1, None, 3),
 ("Üçbucağın sahəsini tapmaq üçün oturacaq nəyə vurulub ikiyə bölünür?",
  "S = a · h : 2.",
  ["Hündürlüyə", "Perimetrə", "Digər tərəfə", "Bucağa"],
  1, None, 2),
],
}
for _k, _v in ELAVE40.items():
    SUALLAR[_k] = SUALLAR[_k] + _v


def yoxla():
    n = xeta = 0
    butun = set()
    for movzu, siyahi in SUALLAR.items():
        assert movzu in RUBLAR, movzu
        if len(siyahi) != 40:
            print("XETA  %s: %d sual (40 olmalidir)" % (movzu, len(siyahi)))
            xeta += 1
        for body, why, opts, correct, expect, diff in siyahi:
            n += 1
            p = []
            if len(opts) != 4: p.append("variant sayi %d" % len(opts))
            if len(set(opts)) != len(opts): p.append("tekrar variant")
            if not (1 <= correct <= 4): p.append("correct")
            if not why: p.append("izah bos")
            if diff not in (1, 2, 3): p.append("cetinlik")
            if body in butun: p.append("eyni sual iki defe")
            butun.add(body)
            if expect is not None and opts[correct - 1] != expect:
                p.append("hesablanan «%s» != variant «%s»" % (expect, opts[correct - 1]))
            for t in [body, why] + opts:
                if "'" in t: p.append("apostrof var")
            if p:
                xeta += 1
                print("XETA  %s: %s\n      %s" % (movzu, body[:60], "; ".join(p)))
    hes = sum(1 for s in SUALLAR.values() for q in s if q[4] is not None)
    print("%d sual yoxlandı (%d-i hesabla təsdiqləndi), %d xəta" % (n, hes, xeta))
    return xeta == 0, n


def sql_yaz(n):
    q = lambda t: t.replace("'", "''")
    setirler = []
    for movzu in RUBLAR:
        qisa = movzu.replace("riy-6-", "")
        for i, (body, why, opts, correct, _e, diff) in enumerate(SUALLAR[movzu], 1):
            setirler.append(
                "('riy6-%s#%d','%s',%d,%d,'%s','%s',array['%s','%s','%s','%s'],%d)"
                % (qisa, i, movzu, diff, RUBLAR[movzu], q(body), q(why),
                   q(opts[0]), q(opts[1]), q(opts[2]), q(opts[3]), correct))
    with io.open(CIXIS, "w", encoding="utf-8") as f:
        f.write("""-- =====================================================================
--  30_bank_riy6.sql : RIYAZIYYAT 6 PLATFORMA SUAL BANKI (orta mekteb)
--
--  BU FAYL ELLE YAZILMIR - tools/riy6.py yaradir:
--      python3 tools/riy6.py
--
--  9 movzu x 40 sual = %d.  ext_key: riy6-<movzu>#<sira>.
--  ON SERT: 29_movzular_orta6.sql islenmis olmalidir.
--  SONRA:   05_grants.sql yeniden islet.
-- =====================================================================

do $$
begin
  if not exists (
    select 1 from public.topics t
      join public.subjects s on s.id = t.subject_id
     where s.slug = 'riyaziyyat' and t.slug = 'riy-6-coxluqlar') then
    raise exception 'ONCE 29_movzular_orta6.sql isledilmelidir (riy-6-* movzulari yoxdur).';
  end if;
end $$;

delete from public.question_options o
 using public.questions q
 where o.question_id = q.id
   and q.owner_type = 'platform'
   and q.ext_key like 'riy6-%%';

with d(ext, topic, diff, rub, body, why, opts, correct) as (values
%s
),
ins as (
  insert into public.questions
    (ext_key, owner_type, subject_id, level_id, topic_id, kind,
     body, explanation, difficulty, quarter, status)
  select d.ext, 'platform', s.id, l.id, tp.id, 'single',
         d.body, d.why, d.diff, d.rub, 'published'
    from d
    join public.subjects s on s.slug = 'riyaziyyat'
    join public.programs p on p.slug = 'orta'
    join public.levels   l on l.program_id = p.id and l.code = '6'
    join public.topics   tp on tp.subject_id = s.id and tp.slug = d.topic
  on conflict (ext_key) do update
    set body = excluded.body, explanation = excluded.explanation,
        difficulty = excluded.difficulty, quarter = excluded.quarter,
        topic_id = excluded.topic_id, level_id = excluded.level_id,
        subject_id = excluded.subject_id, status = 'published'
  returning id, ext_key
)
insert into public.question_options (question_id, ord, body, is_correct)
select ins.id, o.ord, o.txt, o.ord = d.correct
  from ins
  join d on d.ext = ins.ext_key,
  lateral unnest(d.opts) with ordinality as o(txt, ord);

do $$
declare n int; k int;
begin
  select count(*) into n from public.questions
   where owner_type = 'platform' and ext_key like 'riy6-%%';
  if n <> %d then
    raise exception 'riy6 suallari: %d gozlenilirdi, %% tapildi', n;
  end if;
  select count(*) into k from public.questions q
   where q.ext_key like 'riy6-%%'
     and ((select count(*) from public.question_options o
            where o.question_id = q.id) <> 4
       or (select count(*) from public.question_options o
            where o.question_id = q.id and o.is_correct) <> 1);
  if k > 0 then
    raise exception '%% sualda variant qurulusu sehvdir', k;
  end if;
  select count(distinct topic_id) into k from public.questions
   where ext_key like 'riy6-%%';
  if k <> 9 then
    raise exception 'movzu sayi 9 deyil: %%', k;
  end if;
  raise notice 'Riyaziyyat 6 banki: %% sual, 9 movzu.', n;
end $$;
""" % (n, ",\n".join(setirler), n, n))
    print("yazildi: %s" % CIXIS)


if __name__ == "__main__":
    ok, n = yoxla()
    if not ok:
        raise SystemExit(1)
    sql_yaz(n)
