#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Riyaziyyat 7 platforma banki -> db/34_bank_riy7.sql

tools/riy6.py qelibi ile: 10 movzu x 40 sual = 400, her riyazi cavab
YENIDEN HESABLANIB duzgun variantla tutusdurulur (ehtimallar Fraction,
coxluq emelleri set, coxhedli emsallari Python hesabi ile).
Movzular 33_movzular_orta7.sql agacina uygundur (e-derslik
Riyaziyyat 7, kitab 714).

Menfi ededler «−» (U+2212) ile yazilir.  riy3-riy6 fayllarinin
reqemleri tekrarlanmayib.

Isletmek:
    python3 tools/riy7.py
"""
import io
import os
from fractions import Fraction

KOK = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CIXIS = os.path.join(KOK, "db", "34_bank_riy7.sql")


def tam(n):
    return str(n).replace("-", "−")


def dec(x):
    s = ("%.10f" % float(x)).rstrip("0").rstrip(".")
    return s.replace(".", ",").replace("-", "−")


def kesr(f):
    f = Fraction(f)
    if f.denominator == 1:
        return tam(f.numerator)
    if f.numerator < 0:
        return "−%d/%d" % (-f.numerator, f.denominator)
    return "%d/%d" % (f.numerator, f.denominator)


def coxluq(elems):
    return "{%s}" % "; ".join(str(e) for e in sorted(elems))


def fmt(n):
    return format(n, ",").replace(",", " ")


RUBLAR = {
    "riy-7-statistika": 1, "riy-7-rasional": 1,
    "riy-7-paralellik": 2, "riy-7-coxhedliler": 2,
    "riy-7-ucbucaqlar": 3, "riy-7-muxteser": 3, "riy-7-funksiya": 3,
    "riy-7-tenlikler-sistemi": 4, "riy-7-konqruyentlik": 4,
    "riy-7-situasiya": 4,
}

SUALLAR = {
"riy-7-statistika": [
 ("Məlumat toplamağın üsullarından biri hansıdır?",
  "Sorğu (anket) məlumat toplama üsuludur.",
  ["Sorğu", "Yuxu", "Təxmin", "Fal"], 1, None, 1),
 ("Nizamlı zər atılır. 3-dən kiçik ədəd düşməsi ehtimalı neçədir?",
  "Uyğun hallar: 1 və 2 — cəmi 2 hal; 2/6 = 1/3.",
  ["1/3", "1/2", "2/3", "1/6"], 1, kesr(Fraction(2, 6)), 3),
 ("Sinifdə 12 qız və 8 oğlan var. Təsadüfi seçilən şagirdin qız "
  "olması ehtimalı neçədir?",
  "12/20 = 3/5.",
  ["3/5", "2/5", "12/8", "1/2"], 1, kesr(Fraction(12, 20)), 3),
 ("A və B uyuşmayan hadisələrdirsə, «A və ya B» hadisəsinin "
  "ehtimalı necə tapılır?",
  "Uyuşmayan hadisələrin ehtimalları toplanır.",
  ["Ehtimallar toplanır", "Ehtimallar vurulur",
   "Böyüyü götürülür", "Fərqi alınır"], 1, None, 3),
 ("Hadisənin ehtimalı 0,3-dürsə, əks hadisənin ehtimalı neçədir?",
  "1 − 0,3 = 0,7.",
  ["0,7", "0,3", "0,4", "1,3"], 1, dec(1 - 0.3), 2),
 ("Proqnozlaşdırma nəyə əsaslanır?",
  "Toplanmış məlumatların təhlilinə əsaslanır.",
  ["Toplanmış məlumatların təhlilinə", "Təsadüfə",
   "Arzulara", "Heç nəyə"], 1, None, 2),
 ("4, 7, 11, 13, 15 sırasının medianı neçədir?",
  "Beş ədədin ortadakısı: 11.",
  ["11", "7", "10", "13"], 1,
  str(sorted((4, 7, 11, 13, 15))[2]), 2),
 ("Məlumatın qrafik təqdimat formalarından biri hansıdır?",
  "Diaqram məlumatı əyani göstərir.",
  ["Diaqram", "Nağıl", "Şeir", "Mahnı"], 1, None, 1),
 ("Sikkə iki dəfə atılır. Hər ikisində gerb düşməsi ehtimalı "
  "neçədir?",
  "1/2 · 1/2 = 1/4.",
  ["1/4", "1/2", "1/8", "2/4 sadələşmir"], 1,
  kesr(Fraction(1, 2) * Fraction(1, 2)), 3),
 ("10, 20 və 60 ədədlərinin ədədi ortası neçədir?",
  "(10 + 20 + 60) : 3 = 30.",
  ["30", "20", "90", "45"], 1, str((10 + 20 + 60) // 3), 2),
],
"riy-7-rasional": [
 ("Rasional ədəd hansı şəkildə yazıla bilər?",
  "m/n şəklində (m tam, n natural).",
  ["m/n kəsri şəklində", "Yalnız tam ədəd kimi",
   "Yalnız müsbət ədəd kimi", "Yazıla bilməz"], 1, None, 2),
 ("1/3 kəsrinin onluq yazılışı necədir?",
  "1 : 3 = 0,333… = 0,(3) — dövri kəsr.",
  ["0,(3)", "0,3", "0,33", "3,1"], 1, None, 3),
 ("−3,5 və −2,8 ədədlərindən hansı böyükdür?",
  "Mənfilərdə modulu kiçik olan böyükdür: −2,8.",
  ["−2,8", "−3,5", "Bərabərdirlər", "Müqayisə olunmur"], 1,
  dec(max(-3.5, -2.8)), 2),
 ("|−4,2| neçəyə bərabərdir?",
  "Modul mənfi ola bilməz: 4,2.",
  ["4,2", "−4,2", "0", "42"], 1, dec(abs(-4.2)), 2),
 ("−7/2 ədədi ədəd oxunda hansı tam ədədlər arasındadır?",
  "−7/2 = −3,5 — deməli −4 ilə −3 arasındadır.",
  ["−4 və −3", "−3 və −2", "3 və 4", "−7 və −2"], 1, None, 3),
 ("0,4(6) yazılışında mötərizə nəyi bildirir?",
  "6 rəqəminin sonsuz təkrarlandığını (dövrü).",
  ["6-nın dövr etdiyini", "Vurmanı", "Toplamanı",
   "Mənfi işarəni"], 1, None, 2),
 ("−2 < x < 3 ikiqat bərabərsizliyini hansı tam ədəd ödəyir?",
  "1 ədədi −2 ilə 3 arasındadır.",
  ["1", "−3", "4", "5"], 1,
  str([n for n in (1, -3, 4, 5) if -2 < n < 3][0]), 2),
 ("(−0,5) · 8 neçə edər?",
  "0,5 · 8 = 4; işarə mənfi: −4.",
  ["−4", "4", "−40", "−0,4"], 1, dec(-0.5 * 8), 2),
 ("−3/4 + 1/4 neçə edər?",
  "(−3 + 1)/4 = −2/4 = −1/2.",
  ["−1/2", "1/2", "−1", "−4/4"], 1,
  kesr(Fraction(-3, 4) + Fraction(1, 4)), 3),
 ("Toplamanın yerdəyişmə xassəsi nəyi deyir?",
  "a + b = b + a.",
  ["a + b = b + a", "a − b = b − a", "a · b = a + b",
   "a : b = b : a"], 1, None, 1),
],
"riy-7-paralellik": [
 ("İki paralel düz xətti üçüncü xətt kəsdikdə uyğun bucaqlar "
  "necə olur?",
  "Uyğun bucaqlar bərabər olur.",
  ["Bərabər", "Cəmi 90°", "Fərqli", "Cəmi 360°"], 1, None, 2),
 ("Paralel xətləri kəsəndə əmələ gələn birtərəfli daxili bucaqların "
  "cəmi neçədir?",
  "Birtərəfli daxili bucaqların cəmi 180°-dir.",
  ["180°", "90°", "360°", "60°"], 1, None, 3),
 ("Parçanın orta perpendikulyarı nədir?",
  "Parçanın ortasından ona perpendikulyar keçən düz xəttdir.",
  ["Ortadan keçən perpendikulyar düz xətt",
   "Parçanı uzadan xətt", "İstənilən mail", "Diaqonal"],
  1, None, 3),
 ("Nöqtədən düz xəttə qədər ən qısa məsafə hansı xətlə ölçülür?",
  "Ən qısa məsafə perpendikulyar boyuncadır.",
  ["Perpendikulyarla", "Mail ilə", "Əyri ilə",
   "İstənilən xətlə"], 1, None, 2),
 ("Mərkəzi simmetriya nəyə nəzərən simmetriyadır?",
  "Bir nöqtəyə (mərkəzə) nəzərən simmetriyadır.",
  ["Nöqtəyə nəzərən", "Düz xəttə nəzərən",
   "Müstəviyə nəzərən", "Heç nəyə nəzərən"], 1, None, 3),
 ("Bir düz xəttə perpendikulyar olan iki düz xətt bir-birinə "
  "necədir?",
  "Hər ikisi eyni xəttə perpendikulyardırsa, paraleldirlər.",
  ["Paraleldir", "Perpendikulyardır", "Kəsişir",
   "Üst-üstə düşür"], 1, None, 3),
 ("Çarpaz bucaqlar bərabərdirsə, kəsilən iki düz xətt haqqında "
  "nə demək olar?",
  "Bu, paralellik əlamətidir — xətlər paraleldir.",
  ["Paraleldirlər", "Perpendikulyardırlar",
   "Mütləq kəsişirlər", "Heç nə demək olmaz"], 1, None, 3),
 ("Uyğun tərəfləri paralel olan bucaqlar necə olur?",
  "Belə bucaqlar bərabərdir və ya cəmi 180°-dir.",
  ["Bərabər və ya cəmi 180°", "Həmişə 90°",
   "Həmişə fərqli", "Cəmi 100°"], 1, None, 3),
 ("a ∥ b və b ∥ c olarsa, a ilə c necədir?",
  "Paralellik ötürülür: a ∥ c.",
  ["a ∥ c", "a ⊥ c", "Kəsişirlər", "Bilmək olmaz"],
  1, None, 2),
 ("İki kəsişən düz xətt neçə cüt çarpaz bucaq əmələ gətirir?",
  "Kəsişmədə 2 cüt çarpaz bucaq yaranır.",
  ["2", "4", "1", "8"], 1, str(2), 3),
],
"riy-7-coxhedliler": [
 ("3x² · 4x³ hasilini tapın.",
  "Əmsallar vurulur, qüvvətlər toplanır: 12x⁵.",
  ["12x⁵", "7x⁵", "12x⁶", "7x⁶"], 1, "%dx⁵" % (3 * 4), 2),
 ("x² · x⁵ neçə olar?",
  "Eyni əsaslı qüvvətlər vurulanda üstlər toplanır: x⁷.",
  ["x⁷", "x¹⁰", "x³", "2x⁷"], 1, "x⁷", 2),
 ("Hansı ifadə birhədlidir?",
  "5xy — ədəd və dəyişənlərin hasilidir.",
  ["5xy", "x + y", "x − 1", "2x + 3"], 1, None, 2),
 ("(2x + 3) + (x − 5) cəmini sadələşdirin.",
  "2x + x = 3x; 3 − 5 = −2: 3x − 2.",
  ["3x − 2", "3x + 2", "2x − 2", "3x − 8"], 1,
  "%dx − %d" % (2 + 1, 5 - 3), 2),
 ("Çoxhədlinin standart şəkli nədir?",
  "Bütün oxşar hədləri birləşdirilmiş yazılışdır.",
  ["Oxşar hədləri birləşdirilmiş yazılış", "Ən uzun yazılış",
   "Mötərizəli yazılış", "Rəqəmsiz yazılış"], 1, None, 2),
 ("2(x + 4) − x ifadəsini sadələşdirin.",
  "2x + 8 − x = x + 8.",
  ["x + 8", "3x + 8", "x + 4", "2x + 8"], 1, None, 2),
 ("x(x + 3) hasilini açın.",
  "x · x + x · 3 = x² + 3x.",
  ["x² + 3x", "x² + 3", "2x + 3", "3x²"], 1, None, 2),
 ("6x + 9 ifadəsini vuruqlara ayırın.",
  "Ortaq vuruq 3: 3(2x + 3).",
  ["3(2x + 3)", "3(2x + 9)", "6(x + 9)", "9(6x + 1)"],
  1, None, 3),
 ("(x + 2)(x + 5) hasilində sərbəst hədd neçədir?",
  "Sərbəst hədd: 2 · 5 = 10.",
  ["10", "7", "3", "25"], 1, str(2 * 5), 3),
 ("a⁶ : a² neçə olar?",
  "Bölmədə üstlər çıxılır: a⁴.",
  ["a⁴", "a³", "a⁸", "a¹²"], 1, "a⁴", 2),
],
"riy-7-ucbucaqlar": [
 ("Üçbucağın xarici bucağı nəyə bərabərdir?",
  "Ona qonşu olmayan iki daxili bucağın cəminə.",
  ["Qonşu olmayan iki daxili bucağın cəminə",
   "Bütün bucaqların cəminə", "90°-yə", "Qonşu bucağa"],
  1, None, 3),
 ("Üçbucağın medianı nədir?",
  "Təpəni qarşı tərəfin orta nöqtəsi ilə birləşdirən parçadır.",
  ["Təpəni qarşı tərəfin ortası ilə birləşdirən parça",
   "Bucağı yarıya bölən şüa", "Perpendikulyar parça",
   "Ən uzun tərəf"], 1, None, 3),
 ("Üçbucağın hündürlüyü nədir?",
  "Təpədən qarşı tərəfə endirilən perpendikulyardır.",
  ["Təpədən qarşı tərəfə perpendikulyar",
   "Tərəflərin cəmi", "Ən qısa tərəf", "Median ilə eynidir"],
  1, None, 2),
 ("Üçbucağın iki bucağı 35° və 65°-dirsə, üçüncü bucağı tapın.",
  "180 − 35 − 65 = 80°.",
  ["80°", "100°", "90°", "70°"], 1,
  "%d°" % (180 - 35 - 65), 2),
 ("Üçbucağın iki tərəfi 3 sm və 4 sm-dirsə, üçüncü tərəf hansı "
  "aralıqda ola bilər?",
  "Üçbucaq bərabərsizliyi: 4 − 3 < x < 4 + 3.",
  ["1 sm-dən böyük, 7 sm-dən kiçik", "İstənilən uzunluqda",
   "Düz 7 sm", "3 sm-dən kiçik"], 1, None, 3),
 ("Üçbucaqda böyük bucağın qarşısında hansı tərəf durur?",
  "Böyük bucaq qarşısında böyük tərəf durur.",
  ["Böyük tərəf", "Kiçik tərəf", "Orta tərəf",
   "İstənilən tərəf"], 1, None, 2),
 ("Üçbucağın neçə medianı var?",
  "Hər təpədən bir median: 3.",
  ["3", "1", "2", "6"], 1, str(3), 2),
 ("Tərəfləri 2 sm, 9 sm və 5 sm olan üçbucaq qurmaq olarmı?",
  "2 + 5 = 7 < 9 — üçbucaq bərabərsizliyi pozulur, qurmaq olmaz.",
  ["Olmaz", "Olar", "Yalnız düzbucaqlı olar",
   "Yalnız bərabəryanlı olar"], 1,
  ("Olmaz" if 2 + 5 <= 9 else "Olar"), 3),
 ("Bərabərtərəfli üçbucaqda median, tənbölən və hündürlük necədir?",
  "Hər təpədən çəkilən bu üç xətt üst-üstə düşür.",
  ["Üst-üstə düşür", "Həmişə fərqlidir", "Kəsişmir",
   "Yalnız ikisi bərabərdir"], 1, None, 3),
 ("Üçbucağın bucaqları 2 : 3 : 4 nisbətindədirsə, böyük bucaq "
  "neçədir?",
  "Bir pay: 180 : 9 = 20; böyük bucaq: 20 · 4 = 80°.",
  ["80°", "40°", "60°", "90°"], 1,
  "%d°" % (180 * 4 // (2 + 3 + 4)), 3),
],
"riy-7-muxteser": [
 ("(a + b)² açılışı hansıdır?",
  "(a + b)² = a² + 2ab + b².",
  ["a² + 2ab + b²", "a² + b²", "a² − 2ab + b²", "2a + 2b"],
  1, None, 2),
 ("(x − 3)² açılışında orta hədd hansıdır?",
  "−2 · x · 3 = −6x.",
  ["−6x", "6x", "−9x", "−3x"], 1, "−%dx" % (2 * 3), 3),
 ("a² − b² fərqi hansı hasilə bərabərdir?",
  "Kvadratlar fərqi: (a − b)(a + b).",
  ["(a − b)(a + b)", "(a − b)²", "(a + b)²", "a·b·(a − b)"],
  1, None, 2),
 ("51² − 49² fərqini müxtəsər düsturla hesablayın.",
  "(51 − 49)(51 + 49) = 2 · 100 = 200.",
  ["200", "2", "100", "400"], 1, str(51 ** 2 - 49 ** 2), 3),
 ("(x + 4)² açılışını yazın.",
  "x² + 2·4·x + 16 = x² + 8x + 16.",
  ["x² + 8x + 16", "x² + 16", "x² + 4x + 16", "x² + 8x + 8"],
  1, "x² + %dx + %d" % (2 * 4, 4 ** 2), 2),
 ("(a + b)³ açılışında neçə hədd olur?",
  "a³ + 3a²b + 3ab² + b³ — dörd hədd.",
  ["4", "3", "2", "8"], 1, str(4), 3),
 ("x² − 25 ifadəsini vuruqlara ayırın.",
  "x² − 5² = (x − 5)(x + 5).",
  ["(x − 5)(x + 5)", "(x − 5)²", "(x + 5)²", "x(x − 25)"],
  1, None, 2),
 ("a³ + b³ cəmi hansı hasilə bərabərdir?",
  "Kublar cəmi: (a + b)(a² − ab + b²).",
  ["(a + b)(a² − ab + b²)", "(a + b)³",
   "(a + b)(a² + ab + b²)", "(a + b)(a + b)"],
  1, None, 3),
 ("99 · 101 hasilini müxtəsər düsturla tapın.",
  "(100 − 1)(100 + 1) = 10 000 − 1 = 9 999.",
  ["9 999", "10 001", "9 909", "10 000"], 1, fmt(99 * 101), 3),
 ("x² + 6x + 9 üçhədlisi hansı ifadənin kvadratıdır?",
  "x² + 2·3x + 3² = (x + 3)².",
  ["(x + 3)²", "(x + 6)²", "(x + 9)²", "(x − 3)²"], 1, None, 3),
],
"riy-7-funksiya": [
 ("y = 2x + 1 funksiyasında x = 3 olduqda y neçədir?",
  "y = 2 · 3 + 1 = 7.",
  ["7", "6", "5", "9"], 1, str(2 * 3 + 1), 2),
 ("Xətti funksiyanın qrafiki hansı xətdir?",
  "Xətti funksiyanın qrafiki düz xəttdir.",
  ["Düz xətt", "Parabola", "Çevrə", "Sınıq xətt"], 1, None, 2),
 ("y = kx + b yazılışında k nəyi bildirir?",
  "k — bucaq əmsalıdır.",
  ["Bucaq əmsalını", "Sərbəst həddi", "Funksiyanın adını",
   "Qrafikin rəngini"], 1, None, 3),
 ("y = 3x funksiyasının qrafiki hansı nöqtədən mütləq keçir?",
  "b = 0 olduğundan qrafik (0; 0)-dan keçir.",
  ["(0; 0)", "(1; 0)", "(0; 3)", "(3; 0)"], 1, None, 3),
 ("y = −x + 5 funksiyasında y = 0 olduqda x neçədir?",
  "0 = −x + 5; x = 5.",
  ["5", "−5", "0", "1"], 1, str(5), 2),
 ("Bucaq əmsalları bərabər, sərbəst hədləri fərqli xətti "
  "funksiyaların qrafikləri necədir?",
  "Belə düz xətlər paraleldir.",
  ["Paraleldir", "Kəsişir", "Üst-üstə düşür",
   "Perpendikulyardır"], 1, None, 3),
 ("Funksiya nədir?",
  "Hər x qiymətinə yeganə y qarşı qoyan uyğunluqdur.",
  ["Hər x-ə bir y qarşı qoyan uyğunluq", "İki ədədin cəmi",
   "Həndəsi fiqur", "Tənliyin kökü"], 1, None, 3),
 ("x + y = 4 tənliyinin həllərindən biri hansıdır?",
  "1 + 3 = 4 — (1; 3) cütlüyü tənliyi ödəyir.",
  ["(1; 3)", "(2; 3)", "(4; 4)", "(0; 3)"], 1, None, 2),
 ("y = 4x − 8 funksiyasının qrafiki Ox oxunu hansı nöqtədə kəsir?",
  "y = 0: 4x = 8; x = 2 — nöqtə (2; 0).",
  ["(2; 0)", "(0; 2)", "(8; 0)", "(0; −8)"], 1,
  "(%d; 0)" % (8 // 4), 3),
 ("y = 5x asılılığında asılı dəyişən hansıdır?",
  "y-in qiyməti x-dən asılıdır — asılı dəyişən y-dir.",
  ["y", "x", "5", "Heç biri"], 1, None, 2),
],
"riy-7-tenlikler-sistemi": [
 ("x + y = 5 və x − y = 1 sisteminin həlli hansıdır?",
  "Toplasaq: 2x = 6, x = 3; y = 2.",
  ["x = 3; y = 2", "x = 2; y = 3", "x = 4; y = 1",
   "x = 5; y = 0"], 1,
  "x = %d; y = %d" % ((5 + 1) // 2, (5 - 1) // 2), 3),
 ("İkidəyişənli sistemin həlli nə deməkdir?",
  "Hər iki tənliyi eyni zamanda ödəyən ədədlər cütüdür.",
  ["Hər iki tənliyi ödəyən cütlük", "İstənilən iki ədəd",
   "Yalnız birinci tənliyin kökü", "Qrafikin rəngi"],
  1, None, 2),
 ("Əvəzetmə üsulunda nə edilir?",
  "Bir dəyişən digəri ilə ifadə olunub o biri tənlikdə yerinə "
  "yazılır.",
  ["Dəyişən ifadə olunub yerinə yazılır",
   "Tənliklər silinir", "Qrafik çəkilir", "Ədədlər təxmin edilir"],
  1, None, 2),
 ("Toplama üsulunda tənliklər nə üçün toplanır?",
  "Dəyişənlərdən birini yox etmək üçün.",
  ["Bir dəyişəni yox etmək üçün", "Cavabı böyütmək üçün",
   "Qrafiki çəkmək üçün", "Səbəbsiz"], 1, None, 2),
 ("2x + y = 7 tənliyində y = 3 olarsa, x neçədir?",
  "2x = 7 − 3 = 4; x = 2.",
  ["2", "5", "4", "10"], 1, str((7 - 3) // 2), 2),
 ("Qrafik üsulda sistemin həlli nəyə uyğun gəlir?",
  "Düz xətlərin kəsişmə nöqtəsinə.",
  ["Kəsişmə nöqtəsinə", "Ox oxuna", "Başlanğıca",
   "Ən hündür nöqtəyə"], 1, None, 3),
 ("Qrafikləri paralel olan sistemin neçə həlli var?",
  "Xətlər kəsişmir — həll yoxdur.",
  ["Həlli yoxdur", "Bir həlli var", "İki həlli var",
   "Sonsuz həlli var"], 1, None, 3),
 ("x − 2y = 0 tənliyində x = 6 olduqda y neçədir?",
  "6 = 2y; y = 3.",
  ["3", "6", "12", "0"], 1, str(6 // 2), 2),
 ("Cəmi 12, fərqi 2 olan iki ədədi tapın.",
  "(12 + 2) : 2 = 7 və 12 − 7 = 5.",
  ["7 və 5", "8 və 4", "6 və 6", "10 və 2"], 1,
  "%d və %d" % ((12 + 2) // 2, (12 - 2) // 2), 3),
 ("Qrafikləri üst-üstə düşən sistemin həll sayı neçədir?",
  "Xəttin hər nöqtəsi həlldir — sonsuz sayda.",
  ["Sonsuz", "Bir", "İki", "Sıfır"], 1, None, 3),
],
"riy-7-konqruyentlik": [
 ("Konqruyent fiqurlar necə fiqurlardır?",
  "Üst-üstə qoyduqda tam üst-üstə düşən fiqurlardır.",
  ["Üst-üstə düşən (bərabər)", "Yalnız oxşar",
   "Sahələri fərqli", "Rəngi eyni"], 1, None, 2),
 ("Konqruyentliyin birinci əlaməti hansı elementlərə görədir?",
  "İki tərəf və onlar arasındakı bucağa görə.",
  ["İki tərəf və arasındakı bucağa", "Üç bucağa",
   "Bir tərəfə", "Perimetrə"], 1, None, 3),
 ("Konqruyentliyin ikinci əlaməti nəyə əsaslanır?",
  "Bir tərəf və ona bitişik iki bucağa.",
  ["Tərəf və ona bitişik iki bucağa", "Üç tərəfə",
   "İki bucağa", "Sahəyə"], 1, None, 3),
 ("Konqruyentliyin üçüncü əlaməti hansıdır?",
  "Üç tərəfə görə konqruyentlik.",
  ["Üç tərəfə görə", "Üç bucağa görə", "Perimetrə görə",
   "Hündürlüyə görə"], 1, None, 3),
 ("Bərabəryanlı üçbucaqda təpədən oturacağa çəkilən median həm "
  "də nədir?",
  "O həm hündürlük, həm də tənböləndir.",
  ["Hündürlük və tənbölən", "Yalnız median",
   "Orta xətt", "Diaqonal"], 1, None, 3),
 ("Konqruyent üçbucaqların uyğun bucaqları necədir?",
  "Uyğun bucaqlar bərabərdir.",
  ["Bərabərdir", "Fərqlidir", "Cəmi 90°-dir",
   "Müqayisə olunmur"], 1, None, 2),
 ("Konqruyent üçbucaqların perimetrləri haqqında nə demək olar?",
  "Uyğun tərəflər bərabərdir — perimetrlər də bərabərdir.",
  ["Perimetrlər bərabərdir", "Perimetrlər fərqlidir",
   "Biri iki dəfə böyükdür", "Bilmək olmaz"], 1, None, 2),
 ("△ABC ≅ △DEF yazılışında AB tərəfinə hansı tərəf uyğundur?",
  "Yazılış sırasına görə AB-yə DE uyğundur.",
  ["DE", "EF", "DF", "FE"], 1, None, 3),
 ("Konqruyentlik əlamətləri nəyi sübut etməyə imkan verir?",
  "İki üçbucağın konqruyent olduğunu.",
  ["Üçbucaqların konqruyentliyini", "Sahənin böyüklüyünü",
   "Bucağın adını", "Perimetrin uzunluğunu"], 1, None, 2),
 ("Konqruyent fiqurların sahələri necədir?",
  "Konqruyent fiqurların sahələri bərabərdir.",
  ["Sahələri bərabərdir", "Sahələri fərqlidir",
   "Sahəsi olmur", "Yalnız perimetrləri bərabərdir"],
  1, None, 2),
],
"riy-7-situasiya": [
 ("Mütləq xəta nədir?",
  "Həqiqi və təqribi qiymətlər fərqinin moduludur.",
  ["Həqiqi ilə təqribi qiymət fərqinin modulu",
   "Qiymətlərin cəmi", "Qiymətlərin hasili", "Faiz nisbəti"],
  1, None, 3),
 ("Həqiqi qiymət 50, təqribi qiymət 45-dirsə, mütləq xəta neçədir?",
  "|50 − 45| = 5.",
  ["5", "95", "45", "−5"], 1, str(abs(50 - 45)), 2),
 ("Nisbi xəta necə tapılır?",
  "Mütləq xətanın həqiqi qiymətə nisbəti kimi.",
  ["Mütləq xəta : həqiqi qiymət", "Qiymətlərin cəmi kimi",
   "Həqiqi qiymət : 100", "Təqribi qiymətin kvadratı kimi"],
  1, None, 3),
 ("Malın qiyməti 40 manatdan 50 manata qalxdı. Qiymət neçə faiz "
  "artıb?",
  "Artım 10 manat; 10/40 = 25%.",
  ["25%", "10%", "20%", "50%"], 1,
  "%d%%" % ((50 - 40) * 100 // 40), 3),
 ("240 manatın 35%-i neçə manatdır?",
  "240 · 35 : 100 = 84.",
  ["84", "35", "205", "175"], 1, str(240 * 35 // 100), 2),
 ("A = {1; 2; 3; 4}, B = {3; 4; 5}. A \\ B fərqini tapın.",
  "A-da olub B-də olmayanlar: {1; 2}.",
  ["{1; 2}", "{3; 4}", "{5}", "{1; 2; 5}"], 1,
  coxluq({1, 2, 3, 4} - {3, 4, 5}), 3),
 ("250 manatlıq mala 20% endirim edildi. Yeni qiymət neçədir?",
  "Endirim 50 manat; 250 − 50 = 200 manat.",
  ["200 manat", "230 manat", "50 manat", "210 manat"], 1,
  "%d manat" % (250 - 250 * 20 // 100), 3),
 ("Ölçmə nəticəsi 19,6 sm, həqiqi uzunluq 20 sm-dirsə, mütləq "
  "xəta neçədir?",
  "|20 − 19,6| = 0,4 sm.",
  ["0,4 sm", "4 sm", "0,6 sm", "39,6 sm"], 1,
  "%s sm" % dec(abs(20 - 19.6)), 3),
 ("A = {a; b}, B = {b; c; d}. A ∪ B çoxluğunda neçə element var?",
  "Birləşmə: {a; b; c; d} — 4 element.",
  ["4", "5", "3", "2"], 1, str(len({"a", "b"} | {"b", "c", "d"})), 3),
 ("Araşdırma məsələsinin həllində ilk addım nədir?",
  "Məsələni anlamaq, verilənləri müəyyən etmək.",
  ["Məsələni anlayıb verilənləri ayırmaq", "Cavabı yazmaq",
   "Təsadüfi hesablamaq", "Məsələni atmaq"], 1, None, 2),
],
}



#  Derinlesdirme: her movzuya 10 elave sual (#11-20).
ELAVE = {
"riy-7-statistika": [
 ("Zər bir dəfə atılır. Üzərində cüt ədəd olan üzün düşməsi ehtimalı neçədir?",
  "Cüt üzlər: 2, 4, 6 — 3/6 = 1/2.",
  ["1/2", "1/3", "1/6", "2/3"], 1, kesr(Fraction(3, 6)), 2),
 ("8, 3, 8, 6, 8 sırasının modası neçədir?",
  "Ən çox təkrarlanan qiymət 8-dir.",
  ["8", "3", "6", "33"], 1, str(8), 2),
 ("16, 4 və 10 ədədlərinin ədədi ortası neçədir?",
  "(16 + 4 + 10) : 3 = 10.",
  ["10", "30", "16", "12"], 1, str((16 + 4 + 10) // 3), 2),
 ("Qutuda 5 yaşıl və 3 sarı kürə var. Sarı kürə çıxarma ehtimalı neçədir?",
  "3/8.",
  ["3/8", "5/8", "3/5", "1/3"], 1, kesr(Fraction(3, 8)), 3),
 ("Hadisənin ehtimalı ən çoxu nə qədər ola bilər?",
  "Ehtimal 0 ilə 1 arasındadır — ən çoxu 1.",
  ["Ən çoxu 1", "Ən çoxu 100", "Sonsuz", "Ən çoxu 0,5"],
  1, None, 2),
 ("Aşağıdakı hadisələrdən hansı mümkün deyil?",
  "Zərin üzlərində 1-dən 6-ya qədər ədədlər var.",
  ["Zərdə 7 düşməsi", "Zərdə 6 düşməsi",
   "Sikkədə gerb düşməsi", "Zərdə tək ədəd düşməsi"],
  1, None, 2),
 ("Sütunlu diaqram nəyi müqayisə etmək üçün əlverişlidir?",
  "Kəmiyyətlərin böyüklüyünü əyani müqayisə edir.",
  ["Kəmiyyətlərin böyüklüyünü", "Sözlərin mənasını",
   "Rənglərin adını", "Xəritənin miqyasını"], 1, None, 2),
 ("Yağış yağma ehtimalı 0,45 olarsa, yağmama ehtimalı neçə olar?",
  "1 − 0,45 = 0,55.",
  ["0,55", "0,45", "0,65", "1,45"], 1, dec(1 - 0.45), 3),
 ("20 şagirddən 15-i sınaqdan keçib. Keçmənin nisbi tezliyi neçədir?",
  "15/20 = 3/4.",
  ["3/4", "1/4", "15/5", "4/3"], 1, kesr(Fraction(15, 20)), 3),
 ("Cədvəl, qrafik və diaqram nə üçün istifadə olunur?",
  "Məlumatı əyani və yığcam təqdim etmək üçün.",
  ["Məlumatı əyani təqdim etmək üçün", "Yer tutmaq üçün",
   "Yalnız bəzək üçün", "Məlumatı gizlətmək üçün"],
  1, None, 1),
],
"riy-7-rasional": [
 ("Ədəd oxunda −6,9 və −6,1 ədədlərindən hansı daha soldadır?",
  "Kiçik ədəd solda olur: −6,9 < −6,1.",
  ["−6,9", "−6,1", "Eyni nöqtədədirlər", "Hər ikisi sağdadır"],
  1, dec(min(-6.9, -6.1)), 2),
 ("|2,6| + |−1,2| cəmini hesablayın.",
  "2,6 + 1,2 = 3,8.",
  ["3,8", "1,4", "−3,8", "2,4"], 1, dec(2.6 + 1.2), 2),
 ("(−3) · (−7) hasili neçədir?",
  "Mənfi ilə mənfinin hasili müsbətdir: 21.",
  ["21", "−21", "10", "−10"], 1, str((-3) * (-7)), 2),
 ("−15 : 3 neçə edər?",
  "İşarələr fərqlidir — nəticə mənfidir: −5.",
  ["−5", "5", "−45", "−12"], 1, dec(-15 / 3), 2),
 ("1/2 − 3/4 fərqini hesablayın.",
  "2/4 − 3/4 = −1/4.",
  ["−1/4", "1/4", "−2/2", "−1/6"], 1,
  kesr(Fraction(1, 2) - Fraction(3, 4)), 3),
 ("Hansı kəsr sonlu onluq kəsrə çevrilir?",
  "Məxrəci yalnız 2 və 5 vuruqlarından ibarət olan kəsr: 7/20.",
  ["7/20", "1/3", "5/6", "2/7"], 1, None, 3),
 ("Vurmanın paylama xassəsi hansıdır?",
  "a(b + c) = ab + ac.",
  ["a(b + c) = ab + ac", "a + b = b + a", "a · b = b · a",
   "a − b = b − a"], 1, None, 2),
 ("0,25 kəsrini adi kəsr şəklində yazın.",
  "0,25 = 25/100 = 1/4.",
  ["1/4", "1/2", "2/5", "25/10"], 1,
  kesr(Fraction(1, 4)), 2),
 ("−11/4 kəsri hansı tam ədədlərin arasına düşür?",
  "−11/4 = −2,75 — deməli −3 ilə −2 arasındadır.",
  ["−3 və −2", "−2 və −1", "−11 və −4", "2 və 3"],
  1, None, 3),
 ("Qarşılıqlı tərs ədədlərin hasili neçədir?",
  "a · (1/a) = 1.",
  ["1", "0", "−1", "a²"], 1, str(1), 2),
],
"riy-7-paralellik": [
 ("Kəsişən iki düz xəttin əmələ gətirdiyi qonşu bucaqların cəmi neçədir?",
  "Qonşu bucaqların cəmi 180°-dir.",
  ["180°", "90°", "45°", "270°"], 1, None, 2),
 ("Çarpaz bucaqlar bir-birinə necədir?",
  "Çarpaz bucaqlar bərabərdir.",
  ["Bərabərdir", "Cəmi 180°-dir", "Fərqlidir", "Cəmi 90°-dir"],
  1, None, 2),
 ("İki perpendikulyar xətt arasındakı bucaq neçə dərəcədir?",
  "Perpendikulyarlıq 90° bucaq deməkdir.",
  ["90°", "45°", "180°", "60°"], 1, None, 1),
 ("Ox simmetriyası nəyə nəzərən simmetriyadır?",
  "Bir düz xəttə (oxa) nəzərən.",
  ["Düz xəttə nəzərən", "Nöqtəyə nəzərən", "Müstəviyə nəzərən",
   "Çevrəyə nəzərən"], 1, None, 2),
 ("Uyğun bucaqlar bərabər olarsa, kəsilən iki düz xətt haqqında hansı nəticə çıxır?",
  "Bu, paralellik əlamətlərindən biridir.",
  ["Paraleldirlər", "Perpendikulyardırlar", "Üst-üstə düşürlər",
   "Heç bir nəticə çıxmır"], 1, None, 3),
 ("Düz xətdən kənar nöqtədən ona neçə paralel düz xətt keçirmək olar?",
  "Paralellik aksiomu: yalnız bir.",
  ["Yalnız bir", "İki", "Sonsuz sayda", "Heç bir"],
  1, None, 3),
 ("Paralel düz xətlər arasındakı məsafə xətt boyunca necə dəyişir?",
  "Paralel xətlər arasındakı məsafə sabitdir.",
  ["Dəyişmir, sabitdir", "Getdikcə artır", "Getdikcə azalır",
   "Gah artır, gah azalır"], 1, None, 3),
 ("Üçbucağın daxili bucaqları cəmi teoremi hansı fikrə əsaslanaraq sübut olunur?",
  "Təpədən oturacağa paralel düz xətt çəkilir.",
  ["Paralel düz xətlərin xassəsinə", "Pifaqor teoreminə",
   "Sahə düsturuna", "Perimetr anlayışına"], 1, None, 3),
 ("İki paralel düz xətti kəsən üçüncü düz xətt necə adlanır?",
  "Belə xətt kəsən adlanır.",
  ["Kəsən", "Median", "Tənbölən", "Diaqonal"], 1, None, 2),
 ("Parçanın orta nöqtəsi onu necə bölür?",
  "Orta nöqtə parçanı iki bərabər hissəyə bölür.",
  ["İki bərabər hissəyə", "İki fərqli hissəyə",
   "Üç hissəyə", "Bölmür"], 1, None, 1),
],
"riy-7-coxhedliler": [
 ("9a²b birhədlisinin əmsalı neçədir?",
  "Ədəd vuruğu əmsaldır: 9.",
  ["9", "2", "a", "b"], 1, str(9), 2),
 ("(4x − 1) − (x + 2) fərqini sadələşdirin.",
  "4x − x = 3x; −1 − 2 = −3: 3x − 3.",
  ["3x − 3", "3x + 1", "5x − 3", "3x − 1"], 1,
  "%dx − %d" % (4 - 1, 1 + 2), 2),
 ("2x · 3y hasilini yazın.",
  "Əmsallar vurulur: 6xy.",
  ["6xy", "5xy", "6x", "23xy"], 1, "%dxy" % (2 * 3), 2),
 ("x⁸-i x³-ə bölün.",
  "Üstlər çıxılır: x⁵.",
  ["x⁵", "x¹¹", "x²⁴", "x³"], 1, None, 2),
 ("Çoxhədlinin dərəcəsi necə təyin olunur?",
  "Ən yüksək dərəcəli həddinin dərəcəsinə görə.",
  ["Ən yüksək dərəcəli həddinə görə", "Hədlərin sayına görə",
   "Ən kiçik həddinə görə", "Əmsalların cəminə görə"],
  1, None, 3),
 ("5(2a − 3) ifadəsini açın.",
  "5 · 2a − 5 · 3 = 10a − 15.",
  ["10a − 15", "10a − 3", "7a − 8", "10a + 15"], 1,
  "%da − %d" % (5 * 2, 5 * 3), 2),
 ("x² + x ifadəsini vuruqlara ayırın.",
  "Ortaq vuruq x: x(x + 1).",
  ["x(x + 1)", "x(x − 1)", "x²(x + 1)", "2x + 1"],
  1, None, 3),
 ("(x + 2)(x + 7) hasilində x-in əmsalı neçədir?",
  "Orta hədd: 2 + 7 = 9.",
  ["9", "14", "7", "5"], 1, str(2 + 7), 3),
 ("İkihədli neçə həddən ibarətdir?",
  "Adından göründüyü kimi iki həddən.",
  ["İki həddən", "Bir həddən", "Üç həddən", "Dörd həddən"],
  1, None, 1),
 ("7a + 2b − 3a cəmini sadələşdirin.",
  "7a − 3a = 4a: 4a + 2b.",
  ["4a + 2b", "6ab", "4a − 2b", "10a + 2b"], 1, None, 2),
],
"riy-7-ucbucaqlar": [
 ("Bərabəryanlı üçbucağın oturacağındakı bucaqlar necədir?",
  "Oturacaq bucaqları bir-birinə bərabərdir.",
  ["Bir-birinə bərabərdir", "Həmişə 90°-dir", "Fərqlidir",
   "Cəmi 60°-dir"], 1, None, 2),
 ("Düzbucaqlı üçbucağın iti bucaqlarından biri 30°-dirsə, digəri neçədir?",
  "İti bucaqların cəmi 90°: 90 − 30 = 60°.",
  ["60°", "70°", "150°", "30°"], 1,
  "%d°" % (90 - 30), 2),
 ("Üçbucağın tənböləni nədir?",
  "Bucağı yarıya bölüb qarşı tərəfə çatan parçadır.",
  ["Bucağı yarıya bölən parça", "Tərəfi yarıya bölən xətt",
   "Ən uzun tərəf", "Xarici bucaq"], 1, None, 2),
 ("Bərabərtərəfli üçbucaqda bir bucağın dərəcə ölçüsü neçədir?",
  "180 : 3 = 60°.",
  ["60°", "90°", "45°", "120°"], 1,
  "%d°" % (180 // 3), 2),
 ("Üçbucağın perimetri 24, iki tərəfi 7 və 9-dursa, üçüncü tərəfi tapın.",
  "24 − 7 − 9 = 8.",
  ["8", "16", "40", "2"], 1, str(24 - 7 - 9), 2),
 ("Üçbucağın medianları harada kəsişir?",
  "Üç median bir nöqtədə — ağırlıq mərkəzində kəsişir.",
  ["Bir nöqtədə (ağırlıq mərkəzində)", "Kəsişmirlər",
   "Təpə nöqtəsində", "Üçbucaqdan kənarda həmişə"],
  1, None, 3),
 ("İti bucaqlı üçbucaqda bütün bucaqlar necədir?",
  "Hamısı 90°-dən kiçikdir.",
  ["90°-dən kiçikdir", "90°-dən böyükdür", "90°-yə bərabərdir",
   "Cəmi 90°-dir"], 1, None, 2),
 ("Korbucaqlı üçbucaqda neçə kor bucaq olur?",
  "Yalnız bir bucaq 90°-dən böyük ola bilər.",
  ["Yalnız bir", "İki", "Üç", "Heç bir"], 1, None, 2),
 ("Tərəfləri 4, 6 və 8 olan üçbucaq tərəflərinə görə hansı növdəndir?",
  "Bütün tərəflər fərqlidir — müxtəliftərəflidir.",
  ["Müxtəliftərəfli", "Bərabəryanlı", "Bərabərtərəfli",
   "Düzbucaqlı"], 1, None, 2),
 ("Üçbucağın hər təpəsindən bir xarici bucaq götürülsə, onların cəmi neçə olar?",
  "Xarici bucaqların cəmi 360°-dir.",
  ["360°", "180°", "540°", "90°"], 1, None, 3),
],
"riy-7-muxteser": [
 ("(2x + 1)² açılışını yazın.",
  "4x² + 2·2x·1 + 1 = 4x² + 4x + 1.",
  ["4x² + 4x + 1", "4x² + 1", "2x² + 4x + 1", "4x² + 2x + 1"],
  1, "%dx² + %dx + 1" % (2 ** 2, 2 * 2), 3),
 ("49² + 2 · 49 · 51 + 51² cəmini müxtəsər yolla hesablayın.",
  "(49 + 51)² = 100² = 10 000.",
  ["10 000", "9 999", "5 000", "20 000"], 1,
  fmt((49 + 51) ** 2), 3),
 ("Kvadratlar fərqi kimi x² − 49 necə yazılır?",
  "x² − 7² = (x − 7)(x + 7).",
  ["(x − 7)(x + 7)", "(x − 7)²", "(x + 7)²", "x(x − 49)"],
  1, None, 2),
 ("(a − b)³ açılışında ikinci hədd hansıdır?",
  "a³ − 3a²b + 3ab² − b³ — ikinci hədd −3a²b.",
  ["−3a²b", "3a²b", "−3ab²", "−b³"], 1, None, 3),
 ("102² kvadratını müxtəsər düsturla hesablayın.",
  "(100 + 2)² = 10 000 + 400 + 4 = 10 404.",
  ["10 404", "10 004", "10 204", "10 440"], 1,
  fmt(102 ** 2), 3),
 ("Kublar fərqi düsturu a³ − b³ üçün hansı ayrılışı verir?",
  "Kublar fərqi: (a − b)(a² + ab + b²).",
  ["(a − b)(a² + ab + b²)", "(a − b)³",
   "(a − b)(a² − ab + b²)", "(a − b)(a + b)"], 1, None, 3),
 ("(x + y)(x − y) hasili nəyə bərabərdir?",
  "Kvadratlar fərqi: x² − y².",
  ["x² − y²", "x² + y²", "(x − y)²", "2x − 2y"],
  1, None, 2),
 ("Hansı ifadənin açılışı x² − 10x + 25-dir?",
  "x² − 2·5x + 5² = (x − 5)².",
  ["(x − 5)²", "(x + 5)²", "(x − 10)²", "(x − 25)²"],
  1, None, 3),
 ("1000 − 3 və 1000 + 3 vuruqlarının hasili neçədir?",
  "1000² − 3² = 1 000 000 − 9 = 999 991.",
  ["999 991", "1 000 009", "999 999", "997 003"], 1,
  fmt(997 * 1003), 3),
 ("(a + b)² və (a − b)² açılışları nə ilə fərqlənir?",
  "Yalnız orta həddin işarəsi ilə: +2ab və −2ab.",
  ["Orta həddin işarəsi ilə", "Hədlərin sayı ilə",
   "Birinci hədlə", "Heç nə ilə"], 1, None, 2),
],
"riy-7-funksiya": [
 ("x = 3 olduqda y = 5x − 4 funksiyası hansı qiyməti alır?",
  "y = 5 · 3 − 4 = 11.",
  ["11", "19", "4", "15"], 1, str(5 * 3 - 4), 2),
 ("y = kx + b yazılışında b nəyi göstərir?",
  "Qrafikin Oy oxu ilə kəsişdiyi nöqtəni (sərbəst həddi).",
  ["Sərbəst həddi (Oy ilə kəsişməni)", "Bucaq əmsalını",
   "Qrafikin uzunluğunu", "x-in qiymətini"], 1, None, 3),
 ("y = −2x funksiyası artan, yoxsa azalandır?",
  "k = −2 < 0 — funksiya azalandır.",
  ["Azalandır (k < 0)", "Artandır", "Sabitdir",
   "Gah artır, gah azalır"], 1, None, 3),
 ("Qrafiki Oy oxunu (0; 6) nöqtəsində kəsən y = 2x + b funksiyasında b neçədir?",
  "Oy ilə kəsişmə (0; b) nöqtəsidir: b = 6.",
  ["6", "2", "0", "−6"], 1, str(6), 3),
 ("y = x funksiyasının qrafiki hansı rübləri keçir?",
  "x və y eyni işarəlidir — I və III rüblər.",
  ["I və III rübləri", "II və IV rübləri", "Yalnız I rübü",
   "Bütün rübləri"], 1, None, 3),
 ("Düz mütənasiblik funksiyası hansı şəkildədir?",
  "y = kx (b = 0).",
  ["y = kx", "y = kx + b", "y = k/x", "y = x²"],
  1, None, 2),
 ("(3; 7) nöqtəsi y = 2x + 1 funksiyasının qrafiki üzərindədirmi?",
  "2 · 3 + 1 = 7 — bəli, üzərindədir.",
  ["Bəli", "Xeyr", "Yalnız x > 3 olduqda", "Bilmək olmaz"],
  1, ("Bəli" if 2 * 3 + 1 == 7 else "Xeyr"), 2),
 ("y = 4 funksiyasının qrafiki necə yerləşir?",
  "Ox oxuna paralel, ondan 4 vahid yuxarıda düz xətt.",
  ["Ox oxuna paralel düz xətt", "Oy oxuna paralel düz xətt",
   "Başlanğıcdan keçən xətt", "Parabola"], 1, None, 3),
 ("Funksiyada asılı olmayan (sərbəst) dəyişən hansıdır?",
  "x sərbəst seçilir, y ondan asılıdır.",
  ["x", "y", "k", "b"], 1, None, 2),
 ("y = x − 3 qrafikinin absis oxu ilə kəsişmə nöqtəsi hansıdır?",
  "y = 0: x = 3 — nöqtə (3; 0).",
  ["(3; 0)", "(0; 3)", "(0; −3)", "(3; 3)"], 1,
  "(%d; 0)" % 3, 3),
],
"riy-7-tenlikler-sistemi": [
 ("4x − y = 26 və y = 2 olduqda x-i tapın.",
  "4x = 26 + 2 = 28; x = 7.",
  ["7", "6", "28", "24"], 1, str((26 + 2) // 4), 2),
 ("Sistemin qrafikləri bir nöqtədə kəsişirsə, sistemin neçə həlli var?",
  "Kəsişmə nöqtəsi yeganədir — bir həll.",
  ["Bir həlli var", "Həlli yoxdur", "İki həlli var",
   "Sonsuz həlli var"], 1, None, 2),
 ("x = 2y və x + y = 18 sistemində y neçədir?",
  "2y + y = 18; 3y = 18; y = 6.",
  ["6", "9", "12", "3"], 1, str(18 // 3), 3),
 ("Əvəzetmə üsulu hansı addımla başlayır?",
  "Bir tənlikdən dəyişənlərdən biri ifadə olunur.",
  ["Bir tənlikdən dəyişənin ifadə edilməsi ilə",
   "Qrafikin çəkilməsi ilə", "Cavabın yoxlanması ilə",
   "Tənliklərin silinməsi ilə"], 1, None, 2),
 ("İki dəyişənli bir xətti tənliyin neçə həlli var?",
  "Hər x üçün bir y tapılır — sonsuz sayda cütlük.",
  ["Sonsuz sayda", "Yalnız bir", "İki", "Heç bir"],
  1, None, 3),
 ("x + y = 8 və x − y = 8 tənliklərini tərəf-tərəfə toplasaq nə alınar?",
  "y-lər ixtisar olunur: 2x = 16.",
  ["2x = 16", "2y = 16", "2x = 0", "x = 16"], 1, None, 2),
 ("(4; 1) cütlüyü x + 2y = 6 tənliyini ödəyirmi?",
  "4 + 2 · 1 = 6 — bəli, ödəyir.",
  ["Bəli", "Xeyr", "Yalnız y = 4 olsa", "Bilmək olmaz"],
  1, ("Bəli" if 4 + 2 * 1 == 6 else "Xeyr"), 2),
 ("2 dəftər və 1 qələm 8 manat, 1 dəftər və 1 qələm 5 manatdır. Dəftər neçəyədir?",
  "Fərq bir dəftərin qiymətidir: 8 − 5 = 3 manat.",
  ["3 manat", "5 manat", "2 manat", "4 manat"], 1,
  "%d manat" % (8 - 5), 3),
 ("Sistemin tənliklərinin qrafikləri hansı üç vəziyyətdə ola bilər?",
  "Kəsişər, paralel olar və ya üst-üstə düşər.",
  ["Kəsişir, paralel və ya üst-üstə düşür",
   "Yalnız kəsişir", "Yalnız paraleldir",
   "Heç bir vəziyyətdə olmur"], 1, None, 3),
 ("x + y = 16 bərabərliyində x = 4 olarsa, y-in qiyməti neçədir?",
  "y = 16 − 4 = 12.",
  ["12", "20", "4", "64"], 1, str(16 - 4), 2),
],
"riy-7-konqruyentlik": [
 ("△ABC ≅ △DEF olduqda ∠A hansı bucağa bərabərdir?",
  "Yazılış sırasına görə ∠A-ya ∠D uyğundur.",
  ["∠D", "∠E", "∠F", "Heç birinə"], 1, None, 3),
 ("Bərabəryanlı üçbucağın yan tərəfləri haqqında nə demək olar?",
  "Yan tərəflər bərabər uzunluqdadır.",
  ["Bərabər uzunluqdadır", "Həmişə fərqlidir",
   "Perpendikulyardır", "Paraleldir"], 1, None, 2),
 ("Konqruyentlik münasibəti hansı işarə ilə göstərilir?",
  "≅ işarəsi ilə.",
  ["≅", "∥", "⊥", "≈"], 1, None, 2),
 ("İki üçbucağın üç bucağı bərabərdirsə, onlar mütləq konqruyentdirmi?",
  "Xeyr — ölçüləri fərqli oxşar üçbucaqlar ola bilər.",
  ["Xeyr, oxşar ola bilərlər", "Bəli, həmişə",
   "Yalnız düzbucaqlıdırsa", "Yalnız bərabərtərəflidirsə"],
  1, None, 3),
 ("Bərabəryanlı üçbucaqda oturacağa çəkilmiş hündürlük oturacağı necə bölür?",
  "Hündürlük həm də mediandır — oturacağı yarıya bölür.",
  ["Yarıya bölür", "Üç hissəyə bölür", "Bölmür",
   "İxtiyari nisbətdə bölür"], 1, None, 3),
 ("△ABC ≅ △KLM yazılışında BC-yə hansı tərəf uyğundur?",
  "Sıraya görə B→L, C→M: BC-yə LM uyğundur.",
  ["LM", "KL", "KM", "ML tərs sırada"], 1, None, 3),
 ("Üçbucaqların konqruyentliyini sübut etmək üçün neçə əsas əlamət var?",
  "Üç əlamət: TBT, BTB, TTT.",
  ["Üç əlamət", "Bir əlamət", "Beş əlamət", "On əlamət"],
  1, None, 2),
 ("Fiqurları üst-üstə qoymaqla yoxlanan xassə hansıdır?",
  "Konqruyentlik (bərabərlik).",
  ["Konqruyentlik", "Paralellik", "Perpendikulyarlıq",
   "Simmetriya"], 1, None, 2),
 ("Formaca eyni olub ölçüləri fərqli olan fiqurlar necə adlanır?",
  "Belə fiqurlar oxşardır.",
  ["Oxşar fiqurlar", "Konqruyent fiqurlar",
   "Simmetrik fiqurlar", "Perpendikulyar fiqurlar"],
  1, None, 2),
 ("İki dairə hansı halda konqruyentdir?",
  "Radiusları bərabər olduqda üst-üstə düşür.",
  ["Radiusları bərabər olduqda", "Mərkəzləri eyni olduqda",
   "Rəngləri eyni olduqda", "Heç vaxt"], 1, None, 3),
],
"riy-7-situasiya": [
 ("Qiyməti 600 manat olan telefona 15% endirim edilib. Endirim neçə manatdır?",
  "600 · 15 : 100 = 90 manat.",
  ["90 manat", "15 manat", "510 manat", "60 manat"], 1,
  "%d manat" % (600 * 15 // 100), 2),
 ("80-in neçə faizi 20-dir?",
  "20/80 · 100 = 25%.",
  ["25%", "20%", "40%", "60%"], 1,
  "%d%%" % (20 * 100 // 80), 3),
 ("A = {2; 4; 6}, B = {4; 6; 8}. A ∩ B kəsişməsini tapın.",
  "Hər ikisində olanlar: {4; 6}.",
  ["{4; 6}", "{2; 8}", "{2; 4; 6; 8}", "{4}"], 1,
  coxluq({2, 4, 6} & {4, 6, 8}), 3),
 ("Təqribi hesablama nə vaxt istifadə olunur?",
  "Dəqiq qiymət tələb olunmadıqda və ya mümkün olmadıqda.",
  ["Dəqiq qiymət tələb olunmadıqda", "Həmişə",
   "Heç vaxt", "Yalnız həndəsədə"], 1, None, 2),
 ("3,472 ədədini yüzdə birlər mərtəbəsinə qədər yuvarlaqlaşdırın.",
  "Üçüncü rəqəm 2 < 5 — 3,47.",
  ["3,47", "3,48", "3,4", "3,5"], 1, dec(round(3.472, 2)), 3),
 ("Kütləsi 2,5 kq olan 4 bağlamanın ümumi kütləsi neçə kiloqramdır?",
  "2,5 · 4 = 10 kq.",
  ["10 kq", "8 kq", "6,5 kq", "12,5 kq"], 1,
  "%s kq" % dec(2.5 * 4), 2),
 ("Nisbi xəta adətən hansı formada ifadə olunur?",
  "Faizlə ifadə olunur.",
  ["Faizlə", "Metrlə", "Kiloqramla", "Dərəcə ilə"],
  1, None, 2),
 ("A = {1; 3; 5; 7} çoxluğunun neçə alt çoxluğu var?",
  "4 elementli çoxluğun 2⁴ = 16 alt çoxluğu var.",
  ["16", "4", "8", "12"], 1, str(2 ** 4), 3),
 ("Ailənin aylıq gəliri 1200 manat, xərci 840 manatdır. Qənaət gəlirin neçə faizidir?",
  "Qənaət 360 manat; 360/1200 = 30%.",
  ["30%", "70%", "36%", "12%"], 1,
  "%d%%" % ((1200 - 840) * 100 // 1200), 3),
 ("Məsələnin cavabını yoxlamaq nə üçün lazımdır?",
  "Nəticənin doğruluğuna əmin olmaq üçün.",
  ["Nəticənin doğruluğuna əmin olmaq üçün", "Vaxt keçirmək üçün",
   "Məsələni uzatmaq üçün", "Lazım deyil"], 1, None, 1),
],
}
for _k, _v in ELAVE.items():
    SUALLAR[_k] = SUALLAR[_k] + _v



# 40 sual/movzu proqrami: her movzuya 20 elave sual.
ELAVE40 = {
"riy-7-coxhedliler": [
 ("Birhədliləri vurun: 5x² · 2x⁴.",
  "5·2 = 10, x²·x⁴ = x⁶.",
  ["10x⁶", "7x⁶", "10x⁸", "10x²"], 1, None, 2),
 ("Qüvvətlərin bölünməsi: b⁷ : b⁴ qismətini yazın.",
  "Üstlər çıxılır: b³.",
  ["b³", "b¹¹", "b²⁸", "b⁴"], 1, None, 2),
 ("Birhədlinin əmsalını göstərin: −4a²b³.",
  "Ədəd vuruğu əmsaldır: −4.",
  ["−4", "4", "a²", "b³"], 1, None, 1),
 ("Fərqi tapıb sadələşdirin: (5x + 2) − (2x − 7).",
  "5x − 2x = 3x; 2 + 7 = 9.",
  ["3x + 9", "3x − 5", "7x + 9", "3x − 9"], 1, None, 2),
 ("Hasili yazın: 4a · 5b.",
  "4·5 = 20 — 20ab.",
  ["20ab", "9ab", "20a", "45ab"], 1, None, 1),
 ("«Üçhədli» adı ifadədəki nəyin sayını bildirir?",
  "Üçhədlidə üç hədd olur.",
  ["Hədlərin (üç hədd)", "Dəyişənlərin", "Əmsalların",
   "Mötərizələrin"], 1, None, 1),
 ("Mötərizəni açın: x(x − 8).",
  "x·x − x·8 = x² − 8x.",
  ["x² − 8x", "x² + 8x", "2x − 8", "x² − 8"], 1, None, 2),
 ("10x + 15 ifadəsini vuruqlara ayırın.",
  "Ortaq vuruq 5-dir: 5(2x + 3).",
  ["5(2x + 3)", "10(x + 15)", "5(2x − 3)", "x(10 + 15)"],
  1, None, 2),
 ("Hasil: 3a²b · 2ab nəyə bərabərdir?",
  "3·2 = 6; a²·a = a³; b·b = b².",
  ["6a³b²", "5a³b²", "6a²b", "6ab"], 1, None, 3),
 ("(x + 3)(x + 4) açılışında x-siz hədd hansıdır?",
  "Sərbəst hədd: 3 · 4 = 12.",
  ["12", "7", "34", "1"], 1, str(3 * 4), 2),
 ("Çoxhədlidə oxşar hədləri birləşdirin: 4x² + 3x − x² + 2x.",
  "4x² − x² = 3x²; 3x + 2x = 5x.",
  ["3x² + 5x", "5x² + 3x", "3x² + x", "4x² + 5x"], 1, None, 2),
 ("Qüvvətləri vurun: y⁵ · y⁵ nəticəsi hansıdır?",
  "Üstlər toplanır: y¹⁰.",
  ["y¹⁰", "y²⁵", "2y⁵", "y⁵"], 1, None, 2),
 ("Sadələşdirin: 9m − 4n + 2m.",
  "9m + 2m = 11m; −4n qalır.",
  ["11m − 4n", "7m − 4n", "11m + 4n", "7mn"], 1, None, 2),
 ("(x²)³ qüvvətini hesablayın.",
  "Üstlər vurulur: x⁶.",
  ["x⁶", "x⁵", "x⁹", "3x²"], 1, None, 2),
 ("Çoxhədlini birhədliyə vurun: 2x(3x + 5).",
  "2x·3x + 2x·5 = 6x² + 10x.",
  ["6x² + 10x", "6x + 10", "5x² + 7x", "6x² + 5"], 1, None, 2),
 ("12x³ : 4x qismətini tapın.",
  "12 : 4 = 3; x³ : x = x².",
  ["3x²", "3x³", "8x²", "4x²"], 1, None, 2),
 ("Çoxhədlinin həddi nədir?",
  "Çoxhədli hədlərin cəmidir.",
  ["Toplananlardan hər biri", "Yalnız əmsal",
   "Yalnız dəyişən", "Mötərizə"], 1, None, 1),
 ("(a + 5)(a − 2) hasilini açın.",
  "a² − 2a + 5a − 10 = a² + 3a − 10.",
  ["a² + 3a − 10", "a² − 3a − 10", "a² + 7a − 10",
   "a² + 3a + 10"], 1, None, 3),
 ("Birhədlinin dərəcəsi necə tapılır?",
  "Dəyişənlərin üstləri toplanır.",
  ["Dəyişənlərin qüvvət üstlərinin cəmi ilə",
   "Əmsalına görə", "Hədlərin sayı ilə", "Vuruqların sayı ilə"],
  1, None, 3),
 ("8x²y − 8x²y fərqi nəyə bərabərdir?",
  "Bərabər hədlərin fərqi sıfırdır.",
  ["Sıfıra", "16x²y", "x²y", "8x²"], 1, None, 1),
],
"riy-7-funksiya": [
 ("y = 3x − 2 funksiyasında x = 5 olduqda y neçədir?",
  "y = 15 − 2 = 13.",
  ["13", "15", "17", "10"], 1, str(3 * 5 - 2), 2),
 ("Funksiyanın qrafiki nədir?",
  "Qrafik — uyğun nöqtələrin çoxluğudur.",
  ["Nöqtələr çoxluğu", "Bir ədəd", "Cədvəlin adı", "Düstur"],
  1, None, 2),
 ("Mənfi əmsallı y = −4x qrafiki hansı rüblərdədir?",
  "k < 0 olduqda qrafik II və IV rüblərdən keçir.",
  ["II və IV rüblərdə", "I və III rüblərdə", "Yalnız I rübdə",
   "Bütün rüblərdə"], 1, None, 3),
 ("y = 7 funksiyasının qrafiki hansı oxa paraleldir?",
  "Sabit funksiyanın qrafiki Ox-a paraleldir.",
  ["Absis oxuna", "Ordinat oxuna", "Heç birinə",
   "Hər ikisinə"], 1, None, 2),
 ("y = k/x şəklində asılılıq necə adlanır?",
  "Bu, tərs mütənasiblikdir.",
  ["Tərs mütənasiblik", "Düz mütənasiblik", "Xətti funksiya",
   "Sabit funksiya"], 1, None, 2),
 ("Yoxlayın: y = 4x + 1 üçün x = 2 qiymətində y = 9 alınırmı?",
  "4·2 + 1 = 9 — alınır.",
  ["Bəli, alınır", "Xeyr, 8 alınır", "Xeyr, 10 alınır",
   "Yoxlamaq olmaz"], 1, None, 2),
 ("y = kx + b qrafiki k > 0 olduqda necə olur?",
  "Müsbət əmsalda funksiya artandır.",
  ["Artan", "Azalan", "Sabit", "Qapalı"], 1, None, 2),
 ("y = 6x − 12 qrafikinin Ox oxu ilə kəsişməsini tapın.",
  "y = 0: 6x = 12, x = 2 — (2; 0).",
  ["(2; 0)", "(0; 2)", "(0; −12)", "(6; 0)"], 1, None, 3),
 ("Cədvəldə hər x-ə yalnız bir y uyğundursa, bu asılılıq nədir?",
  "Hər girişə bir çıxış — funksiyadır.",
  ["Bəli, funksiyadır", "Xeyr, deyil", "Tənlikdir",
   "Bərabərsizlikdir"], 1, None, 2),
 ("y = 0,5x funksiyasında əmsal k neçədir?",
  "x-in qarşısındakı ədəd: 0,5.",
  ["0,5", "5", "x", "0"], 1, None, 1),
 ("Qrafiki koordinat başlanğıcından keçən xətti funksiya hansıdır?",
  "b = 0 olanda qrafik (0;0)-dan keçir: y = kx.",
  ["y = kx", "y = kx + 5", "y = 7", "y = x²"], 1, None, 2),
 ("y = 2x + 3 və y = 2x − 1 qrafiklərinin qarşılıqlı vəziyyəti necədir?",
  "Əmsallar eyni, sərbəst hədlər fərqli — paraleldirlər.",
  ["Paralel yerləşirlər", "Kəsişirlər", "Üst-üstə düşürlər",
   "Perpendikulyardırlar"], 1, None, 3),
 ("Funksiyanın qiymətlər çoxluğu nədir?",
  "Funksiyanın aldığı bütün y qiymətləri.",
  ["y-in aldığı qiymətlər", "x-in qiymətləri",
   "Əmsallar", "Qrafikin rəngi"], 1, None, 3),
 ("s = 60t düsturu sürəti 60 km/saat olan hərəkətdə nəyi göstərir?",
  "Yol vaxtdan asılıdır: s yolu verir.",
  ["Gedilən yolu", "Sürəti", "Vaxtı", "Təcili"], 1, None, 2),
 ("y = x + 2 qrafiki Oy oxunu hansı nöqtədə kəsir?",
  "x = 0: y = 2 — (0; 2).",
  ["(0; 2)", "(2; 0)", "(0; −2)", "(1; 3)"], 1, None, 2),
 ("Xətti funksiya qrafikini qurmaq üçün ən azı neçə nöqtə lazımdır?",
  "Düz xətt iki nöqtə ilə təyin olunur.",
  ["İki nöqtə", "Bir nöqtə", "Üç nöqtə", "Beş nöqtə"],
  1, None, 2),
 ("Sıfrı tapın: 5x − 10 = 0 olduqda x neçəyə bərabərdir?",
  "5x = 10, x = 2.",
  ["x = 2", "x = 10", "x = −2", "x = 5"], 1, None, 2),
 ("k < 0 olduqda y = kx funksiyası necə dəyişir?",
  "Mənfi əmsalda funksiya azalır.",
  ["Azalan olur", "Artan olur", "Sabit qalır", "Qırılır"],
  1, None, 2),
 ("Asılılıq cədvəlində x: 1, 2, 3; y: 5, 10, 15. Bu hansı asılılıqdır?",
  "y = 5x — düz mütənasiblik.",
  ["Düz mütənasiblik", "Tərs mütənasiblik", "Sabit funksiya",
   "Kvadratik"], 1, None, 3),
 ("Funksiya qrafikində (a; b) nöqtəsi varsa, bu nə deməkdir?",
  "x = a qiymətində funksiya b-yə bərabərdir.",
  ["x = a-da y = b-dir", "a həmişə sıfırdır",
   "b əmsaldır", "Qrafik bağlıdır"], 1, None, 3),
],
"riy-7-konqruyentlik": [
 ("İki üçbucaqda iki tərəf və aralarındakı bucaq bərabərdirsə, hansı əlamət tətbiq olunur?",
  "Bu, birinci əlamətdir (tərəf-bucaq-tərəf).",
  ["Birinci əlamət (TBT)", "İkinci əlamət", "Üçüncü əlamət",
   "Heç biri"], 1, None, 2),
 ("Konqruyent üçbucaqlarda uyğun elementlər: △ABC ≅ △MNK yazılışında ∠B-nin qarşılığı hansıdır?",
  "Yazılış sırasına görə B-yə N uyğundur.",
  ["∠N", "∠M", "∠K", "∠A"], 1, None, 2),
 ("Konqruyent parçalar hansı parçalardır?",
  "Uzunluqları bərabər parçalar konqruyentdir.",
  ["Uzunluqları bərabər parçalar", "Paralel parçalar",
   "Perpendikulyar parçalar", "Qonşu parçalar"], 1, None, 1),
 ("Üçbucağın üç tərəfi digərinin üç tərəfinə bərabərdirsə, bu hansı əlamətdir?",
  "Üç tərəfə görə — üçüncü əlamət.",
  ["Üçüncü əlamət (TTT)", "Birinci əlamət", "İkinci əlamət",
   "Bucaq əlaməti"], 1, None, 2),
 ("Konqruyent fiqurların perimetrləri fərqli ola bilərmi?",
  "Bütün ölçülər bərabərdir — perimetrlər də.",
  ["Xeyr, bərabər olur", "Bəli, fərqli olur",
   "Yalnız üçbucaqlarda", "Müəyyən olunmur"], 1, None, 2),
 ("Bərabəryanlı üçbucaqda tənbölən, median və hündürlük hansı təpədən eyni olur?",
  "Təpə bucağından çəkiləndə üçü üst-üstə düşür.",
  ["Təpə bucağından", "Oturacaq bucağından",
   "İstənilən təpədən", "Heç birindən"], 1, None, 3),
 ("BTB əlaməti hansı elementlərin bərabərliyini tələb edir?",
  "İki bucaq və aralarındakı tərəf.",
  ["İki bucaq və aralarındakı tərəfin", "Üç tərəfin",
   "Üç bucağın", "Bir tərəf və bir bucağın"], 1, None, 2),
 ("Simmetrik fiqurlar konqruyentdirmi?",
  "Simmetriya ölçüləri saxlayır.",
  ["Bəli, konqruyentdir", "Xeyr, deyil",
   "Yalnız kvadratlar", "Yalnız çevrələr"], 1, None, 2),
 ("△ABC-də AB = AC-dirsə, hansı bucaqlar bərabərdir?",
  "Bərabər tərəflərin qarşısındakı bucaqlar: ∠B və ∠C.",
  ["∠B və ∠C", "∠A və ∠B", "∠A və ∠C", "Hamısı"], 1, None, 2),
 ("«≅» işarəsi oxunuşda nə deməkdir?",
  "İşarə konqruyentliyi bildirir.",
  ["Konqruyentdir", "Paraleldir", "Perpendikulyardır",
   "Böyükdür"], 1, None, 1),
 ("Kağızı qatlayıb kəsəndə alınan iki fiqur necə olur?",
  "Qatlama ilə kəsilən fiqurlar üst-üstə düşür.",
  ["Konqruyent olur", "Fərqli olur", "Paralel olur",
   "Oxşar amma fərqli olur"], 1, None, 2),
 ("Konqruyent üçbucaqların sahələri fərqlənə bilərmi?",
  "Konqruyentlərdə bütün ölçülər eynidır — sahə də.",
  ["Xeyr, fərqlənməz", "Bəli, fərqlənər",
   "Yalnız böyüklərdə", "Sahə ölçülmür"], 1, None, 2),
 ("△ABC ≅ △PQR yazılışında AC tərəfinə hansı tərəf uyğundur?",
  "A→P, C→R — deməli PR.",
  ["PR", "PQ", "QR", "RP deyil, QP"], 1, None, 2),
 ("Bərabəryanlı üçbucağın oturacağa çəkilmiş medianı hansı iki üçbucağı yaradır?",
  "Median iki konqruyent üçbucaq əmələ gətirir.",
  ["İki konqruyent üçbucaq", "İki fərqli üçbucaq",
   "İki kvadrat", "İki paraleloqram"], 1, None, 3),
 ("Düzbucaqlı üçbucaqlar üçün xüsusi konqruyentlik əlaməti hansı elementlərlədir?",
  "Katet və hipotenuza görə əlamət var.",
  ["Katet və hipotenuzla", "İki bucaqla", "Perimetrlə",
   "Sahə ilə"], 1, None, 3),
 ("Konqruyentlik sübutunda «uyğun elementlər» nə deməkdir?",
  "Bərabər fiqurlarda qarşı-qarşıya duran elementlər.",
  ["Bir-birinə qarşı duran elementlər", "İstənilən elementlər",
   "Yalnız bucaqlar", "Yalnız tərəflər"], 1, None, 2),
 ("Tərəfi bərabər olan iki kvadrat haqqında nə demək olar?",
  "Tərəfləri bərabər kvadratlar üst-üstə düşür.",
  ["Konqruyentdirlər", "Yalnız oxşardırlar", "Fərqlidirlər",
   "Paraleldirlər"], 1, None, 2),
 ("Konqruyentliyi yoxlamağın praktik üsulu hansıdır?",
  "Fiqurları üst-üstə qoymaq olar.",
  ["Üst-üstə qoymaq", "Rəngləri tutuşdurmaq", "Çəkmək",
   "Adlarını yazmaq"], 1, None, 1),
 ("△ABC ≅ △DEF və ∠A = 50°-dirsə, ∠D neçədir?",
  "Uyğun bucaqlar bərabərdir: 50°.",
  ["50°", "40°", "130°", "100°"], 1, None, 2),
 ("Konqruyentlik əlamətləri olmasaydı, bütün elementləri ölçmək lazım gələrdimi?",
  "Əlamətlər üç elementlə kifayətlənməyə imkan verir.",
  ["Bəli, hamısını", "Xeyr, heç birini", "Yalnız bucaqları",
   "Yalnız perimetri"], 1, None, 3),
],
"riy-7-muxteser": [
 ("Fərqin kvadratı düsturunu yazın: (a − b)² = ?",
  "(a − b)² = a² − 2ab + b².",
  ["a² − 2ab + b²", "a² + 2ab + b²", "a² − b²", "a² + b²"],
  1, None, 2),
 ("Tam kvadrat: x² + 10x + 25 üçhədlisini kvadrat şəklində yazın.",
  "x² + 2·5·x + 5² = (x + 5)².",
  ["(x + 5)²", "(x − 5)²", "(x + 10)²", "(x + 25)²"],
  1, None, 2),
 ("(3x − 2)² açılışını yazın.",
  "9x² − 2·3x·2 + 4 = 9x² − 12x + 4.",
  ["9x² − 12x + 4", "9x² + 12x + 4", "3x² − 12x + 4",
   "9x² − 6x + 4"], 1, None, 3),
 ("Kvadratlar fərqi ilə hesablayın: 98 · 102.",
  "(100 − 2)(100 + 2) = 10 000 − 4 = 9 996.",
  ["9 996", "10 004", "9 896", "10 000"], 1, None, 3),
 ("Vuruqlara ayırın (kvadratlar fərqi): x² − 81.",
  "x² − 9² = (x − 9)(x + 9).",
  ["(x − 9)(x + 9)", "(x − 81)(x + 1)", "(x − 9)²",
   "(x + 9)²"], 1, None, 2),
 ("Cəmin kvadratı ilə tapın: 201² neçədir?",
  "(200 + 1)² = 40 000 + 400 + 1 = 40 401.",
  ["40 401", "40 001", "40 201", "42 001"], 1, None, 3),
 ("(y − 6)² açılışını yazıb orta həddini deyin.",
  "y² − 12y + 36 — orta hədd −12y-dir.",
  ["−12y", "12y", "−6y", "36y"], 1, None, 2),
 ("a² + 2ab + b² ifadəsi hansı hasilə bərabərdir?",
  "Bu, cəmin kvadratıdır.",
  ["(a + b)²", "(a − b)²", "(a + b)(a − b)", "a²b²"],
  1, None, 2),
 ("Kublar cəmi düsturu a³ + b³ hansı vuruqlara ayrılır?",
  "a³ + b³ = (a + b)(a² − ab + b²).",
  ["(a + b)(a² − ab + b²)", "(a + b)³",
   "(a − b)(a² + ab + b²)", "(a + b)(a² + b²)"], 1, None, 3),
 ("Fərqi (63 − 37)(63 + 37) kimi yazıb hesablayın.",
  "26 · 100 = 2 600.",
  ["2 600", "3 600", "2 000", "1 600"], 1, None, 3),
 ("(2a + 3b)(2a − 3b) hasili nəyə bərabərdir?",
  "Kvadratlar fərqi: 4a² − 9b².",
  ["4a² − 9b²", "4a² + 9b²", "2a² − 3b²", "4a − 9b"],
  1, None, 2),
 ("Müxtəsər vurma düsturları nə üçün istifadə olunur?",
  "Hesablamaları qısaldıb asanlaşdırır.",
  ["Hesablamanı sürətləndirmək üçün", "Qrafik qurmaq üçün",
   "Bucaq ölçmək üçün", "Cədvəl yazmaq üçün"], 1, None, 1),
 ("Kubun açılışı: (x + 1)³ yazılışında hədlərin sayı neçədir?",
  "x³ + 3x² + 3x + 1 — dörd hədd.",
  ["4 hədd", "3 hədd", "2 hədd", "6 hədd"], 1, None, 2),
 ("x² − 4x + 4 = 0 tənliyinin sol tərəfi hansı kvadratdır?",
  "x² − 4x + 4 = (x − 2)².",
  ["(x − 2)²", "(x + 2)²", "(x − 4)²", "(2x − 2)²"],
  1, None, 2),
 ("25a² − 16 ifadəsini vuruqlara ayırın.",
  "(5a)² − 4² = (5a − 4)(5a + 4).",
  ["(5a − 4)(5a + 4)", "(25a − 16)(a + 1)", "(5a − 4)²",
   "(5a + 4)²"], 1, None, 3),
 ("997 · 1003 hasilini hansı düsturla asan hesablamaq olar?",
  "(1000 − 3)(1000 + 3) — kvadratlar fərqi.",
  ["Kvadratlar fərqi ilə", "Cəmin kubu ilə",
   "Fərqin kvadratı ilə", "Heç bir düsturla"], 1, None, 2),
 ("(a + b)² − (a − b)² fərqi nəyə bərabərdir?",
  "Açılışların fərqi 4ab verir.",
  ["4ab", "2ab", "2a²", "0"], 1, None, 3),
 ("Tam kvadrata yığın: 45² + 2·45·55 + 55² = (45 + 55)² neçədir?",
  "100² = 10 000.",
  ["10 000", "1 000", "9 000", "11 000"], 1, None, 3),
 ("Fərqin kubu (a − b)³ açılışında işarələr necə növbələşir?",
  "Müsbət və mənfi hədlər növbələşir.",
  ["Müsbət-mənfi növbə ilə", "Hamısı müsbət",
   "Hamısı mənfi", "Təsadüfi"], 1, None, 3),
 ("x² − 1 ifadəsi hansı hasilə bərabərdir?",
  "x² − 1 = (x − 1)(x + 1).",
  ["(x − 1)(x + 1)", "(x − 1)²", "(x + 1)²", "x(x − 1)"],
  1, None, 2),
],
"riy-7-paralellik": [
 ("Paralel xətləri kəsən xəttin əmələ gətirdiyi çarpaz daxili bucaqlar necədir?",
  "Çarpaz daxili bucaqlar bərabərdir.",
  ["Bərabərdirlər", "Fərqlidirlər", "Cəmi 90°-dir",
   "Həmişə kordur"], 1, None, 2),
 ("Qonşu bucaqlardan biri 110°-dirsə, digəri neçədir?",
  "180 − 110 = 70.",
  ["70°", "110°", "90°", "80°"], 1, None, 2),
 ("a ⊥ c və b ⊥ c olarsa, a və b necədir?",
  "Eyni xəttə perpendikulyarlar paraleldir.",
  ["Paralel olurlar", "Perpendikulyar olurlar", "Kəsişirlər",
   "Üst-üstə düşürlər"], 1, None, 3),
 ("Birtərəfli daxili bucaqlardan biri 65°-dirsə, o biri neçədir?",
  "Cəm 180°: 180 − 65 = 115.",
  ["115°", "65°", "125°", "25°"], 1, None, 2),
 ("Paralellik aksiomu nəyi təsdiq edir?",
  "Kənar nöqtədən yalnız bir paralel keçir.",
  ["Yalnız bir paralel keçir", "İki paralel keçir",
   "Paralel keçmir", "Sonsuz paralel keçir"], 1, None, 3),
 ("Simmetriya oxu fiquru necə bölür?",
  "Ox fiquru iki bərabər hissəyə ayırır.",
  ["İki bərabər hissəyə", "Üç hissəyə", "Qeyri-bərabər",
   "Bölmür"], 1, None, 1),
 ("Kəsən xətt iki paralel xətlə birlikdə neçə bucaq əmələ gətirir?",
  "Hər kəsişmədə 4 — cəmi 8 bucaq.",
  ["8 bucaq", "4 bucaq", "6 bucaq", "12 bucaq"], 1, None, 2),
 ("Uyğun bucaqlardan biri 42°-dirsə, digər uyğun bucaq neçədir?",
  "Uyğun bucaqlar bərabərdir: 42°.",
  ["42°", "48°", "138°", "84°"], 1, None, 2),
 ("Mərkəzi simmetriyada fiqurun hər nöqtəsi hansı nöqtədən keçirilir?",
  "Nöqtələr simmetriya mərkəzindən keçirilir.",
  ["Simmetriya mərkəzindən", "Təpə nöqtəsindən",
   "Kənar nöqtədən", "Ox üzərindən"], 1, None, 3),
 ("Çarpaz bucaqlar 3x və 60° kimi verilibsə, x neçədir?",
  "3x = 60, x = 20.",
  ["20", "60", "30", "180"], 1, str(60 // 3), 2),
 ("Perpendikulyarlıq işarəsi hansıdır?",
  "Perpendikulyarlıq ⊥ ilə göstərilir.",
  ["⊥", "∥", "≅", "∈"], 1, None, 1),
 ("Paralel xətlər arasındakı perpendikulyar parçalar haqqında nə demək olar?",
  "Bütün belə parçalar bərabərdir.",
  ["Hamısı bərabərdir", "Getdikcə uzanır", "Qısalır",
   "Ölçülmür"], 1, None, 2),
 ("Nöqtənin düz xəttə nəzərən simmetriyasını qurmaq üçün nə çəkilir?",
  "Xəttə perpendikulyar çəkilir.",
  ["Perpendikulyar", "Paralel", "Çevrə", "Bucaq"], 1, None, 2),
 ("Birtərəfli bucaqların cəmi 180° deyilsə, kəsilən xətlər necədir?",
  "Şərt pozulursa, xətlər paralel deyil.",
  ["Paralel deyillər", "Paraleldirlər", "Perpendikulyardır",
   "Üst-üstədir"], 1, None, 3),
 ("Bucaq 90°-dən kiçikdirsə və qonşusu ilə cəmi 180°-dirsə, qonşu bucaq necə bucaqdır?",
  "Qonşu 90°-dən böyük — kor bucaqdır.",
  ["Kor bucaq", "İti bucaq", "Düz bucaq", "Tam bucaq"],
  1, None, 3),
 ("AB parçasının orta perpendikulyarı üzərindəki nöqtələr A və B-dən hansı məsafədədir?",
  "Orta perpendikulyarın nöqtələri uclardan bərabər uzaqdadır.",
  ["Bərabər məsafədə", "A-ya yaxın", "B-yə yaxın",
   "Sıfır məsafədə"], 1, None, 3),
 ("Ox simmetriyasında fiqurun ölçüləri dəyişirmi?",
  "Simmetriya ölçüləri saxlayır.",
  ["Xeyr, dəyişmir", "Bəli, böyüyür", "Bəli, kiçilir",
   "Yalnız bucaqlar dəyişir"], 1, None, 2),
 ("a ∥ b olarsa və c xətti a-nı kəsərsə, c xətti b-ni kəsərmi?",
  "Paralellərdən birini kəsən digərini də kəsir.",
  ["Bəli, kəsər", "Xeyr, kəsməz", "Yalnız perpendikulyarsa",
   "Müəyyən olunmur"], 1, None, 3),
 ("Uyğun bucaqlar kəsənə nəzərən necə yerləşir?",
  "Uyğun bucaqlar kəsənin eyni tərəfindədir.",
  ["Kəsənin eyni tərəfində", "Əks tərəflərdə",
   "Xətlərin arasında", "Mərkəzdə"], 1, None, 3),
 ("Paraleloqramın qarşı tərəfləri hansı xassəyə malikdir?",
  "Qarşı tərəflər paralel və bərabərdir.",
  ["Paralel və bərabərdir", "Perpendikulyar",
   "Yalnız bərabərdir", "Heç bir xassə yoxdur"], 1, None, 2),
],
"riy-7-rasional": [
 ("−2/5 + 4/5 cəmini tapın.",
  "(−2 + 4)/5 = 2/5.",
  ["2/5", "−2/5", "6/5", "2/10"], 1, None, 2),
 ("(−1,5) · (−9) hasilini tapın.",
  "Eyni işarəlilər müsbət verir: 13,5.",
  ["13,5", "−13,5", "10,5", "−10,5"], 1, None, 2),
 ("Modulu tapın: |−7,3| = ?",
  "Modul mənfi olmayan qiymətdir: 7,3.",
  ["7,3", "−7,3", "0", "73"], 1, None, 1),
 ("Onluğu adi kəsrə çevirin: 0,6 hansı kəsrdir?",
  "0,6 = 6/10 = 3/5.",
  ["3/5", "1/6", "6/100", "2/3"], 1, None, 2),
 ("−9/2 ədədi hansı tam ədədlər arasındadır?",
  "−9/2 = −4,5 — −5 ilə −4 arasında.",
  ["−5 ilə −4 arasında", "−4 ilə −3 arasında",
   "4 ilə 5 arasında", "−9 ilə −2 arasında"], 1, None, 3),
 ("2/9 kəsrini onluq şəklində yazsaq nə alınar?",
  "2 : 9 = 0,222... = 0,2(2).",
  ["0,2(2)", "0,29", "0,2", "2,9"], 1, None, 3),
 ("Sonsuz dövri onluq kəsr hansı ədədlər çoxluğuna aiddir?",
  "Dövri kəsrlər rasionaldır.",
  ["Rasional ədədlərə", "Yalnız tam ədədlərə",
   "Natural ədədlərə", "Heç birinə"], 1, None, 2),
 ("−0,9 · 5 hasilini tapın.",
  "0,9 · 5 = 4,5; işarə mənfi: −4,5.",
  ["−4,5", "4,5", "−45", "−0,45"], 1, None, 2),
 ("5/8 və 0,625 ədədləri haqqında nə demək olar?",
  "5 : 8 = 0,625 — bərabərdirlər.",
  ["Bərabərdirlər", "5/8 böyükdür", "0,625 böyükdür",
   "Müqayisə olunmur"], 1, None, 2),
 ("İki mənfi rasional ədəddən modulu böyük olan necədir?",
  "Modul böyükdükcə mənfi ədəd kiçilir.",
  ["Daha kiçikdir", "Daha böyükdür", "Bərabərdir",
   "Müsbətdir"], 1, None, 3),
 ("Toplamanın qruplaşdırma xassəsini göstərin.",
  "Qruplaşdırma: (a + b) + c = a + (b + c).",
  ["(a + b) + c = a + (b + c)", "a + b = b + a",
   "a(b + c) = ab + ac", "a − b = b − a"], 1, None, 2),
 ("−9,1 : (−0,7) qismətini tapın.",
  "91 : 7 = 13; eyni işarələr müsbət verir.",
  ["13", "−13", "1,3", "−1,3"], 1, None, 3),
 ("Rasional ədədlər çoxluğuna hansılar daxildir?",
  "Bütün tam və kəsr ədədlər rasionaldır.",
  ["Tam və kəsr ədədlər", "Yalnız müsbətlər",
   "Yalnız naturallar", "Yalnız onluqlar"], 1, None, 2),
 ("Fərqi tapın: 1/2 − 5/6.",
  "3/6 − 5/6 = −2/6 = −1/3.",
  ["−1/3", "1/3", "−4/6 deyil, −2/3", "−1/2"], 1, None, 3),
 ("Ədədin tərsi: −5/7-nin qarşılıqlı tərs ədədi hansıdır?",
  "Hasil 1 olmalıdır: −7/5.",
  ["−7/5", "5/7", "7/5", "−5/7"], 1, None, 2),
 ("−2,75 ədədini qarışıq ədəd şəklində yazın.",
  "−2,75 = −2 tam 3/4.",
  ["−2 tam 3/4", "−2 tam 1/4", "2 tam 3/4", "−3 tam 1/4"],
  1, None, 2),
 ("Sıfır rasional ədəddirmi?",
  "0 = 0/1 — rasionaldır.",
  ["Bəli, rasionaldır", "Xeyr, deyil", "Yalnız bəzən",
   "Müəyyən olunmur"], 1, None, 2),
 ("Müqayisə edin: −1,2 ? −1,02 — hansı böyükdür?",
  "|−1,02| < |−1,2| — deməli −1,02 böyükdür.",
  ["−1,02", "−1,2", "Bərabərdirlər", "Müqayisə olunmur"],
  1, None, 3),
 ("Mənfi ədədin tək qüvvəti hansı işarəli olur?",
  "Tək quvvətdə işarə saxlanır: mənfi.",
  ["Mənfi olur", "Müsbət olur", "Sıfır olur", "İşarəsiz"],
  1, None, 2),
 ("(2/3) · (9/4) hasilini tapın.",
  "18/12 = 3/2.",
  ["3/2", "2/3", "11/7", "18/12 sadələşməz"], 1, None, 2),
],
"riy-7-situasiya": [
 ("Soyuducu 800 manatdır, 25% endirim var. Alıcı neçə manat az ödəyir?",
  "800 × 25 : 100 = 200.",
  ["200 manat", "600 manat", "175 manat", "80 manat"],
  1, None, 2),
 ("«30 ədədi 150-nin neçə faizidir?» — cavabı tapın.",
  "30/150 = 1/5 = 20%.",
  ["20%", "30%", "15%", "50%"], 1, None, 2),
 ("Çanta 45 manat idi, qiyməti 20% artdı. Yeni qiyməti tapın.",
  "Artım 9 manat; 45 + 9 = 54.",
  ["54 manat", "50 manat", "65 manat", "9 manat"], 1, None, 2),
 ("3,916 ədədi onda birlərə qədər yuvarlaqlaşdırılsa hansı ədəd alınar?",
  "Yüzdə birlər 1 < 5 — 3,9 qalır.",
  ["3,9", "4,0", "3,92", "3,91"], 1, None, 2),
 ("Mütləq xətanı hesablayın: həqiqi 80, təqribi 78.",
  "|80 − 78| = 2.",
  ["2-dir", "78-dir", "158-dir", "0,2-dir"], 1, None, 2),
 ("C = {1; 2; 3; 4; 5; 6} və D = {2; 4; 6; 8} çoxluqlarının ortaq elementlərini göstərin.",
  "Hər ikisində olanlar: 2, 4, 6.",
  ["{2; 4; 6}", "{1; 3; 5}", "{8}", "{1; 2; 3; 4; 5; 6; 8}"],
  1, None, 2),
 ("Nisbi xəta ilə mütləq xətanın fərqi nədir?",
  "Nisbi xəta mütləq xətanın həqiqi qiymətə nisbətidir.",
  ["Nisbi xəta nisbətdir", "Fərq yoxdur",
   "Mütləq xəta faizdir", "Nisbi xəta həmişə böyükdür"],
  1, None, 3),
 ("Mağaza gündə 240 çörək satır. Həftəlik satışı təqribən neçədir?",
  "240 × 7 = 1 680.",
  ["1 680 çörək", "1 480 çörək", "2 400 çörək", "168 çörək"],
  1, None, 2),
 ("550 manat maaşın 10%-i icarəyə gedir. İcarə neçə manatdır?",
  "550 : 10 = 55.",
  ["55 manat", "50 manat", "5,5 manat", "110 manat"],
  1, None, 1),
 ("Kəmiyyəti təqribən qiymətləndirmək üçün ədədlər nə edilir?",
  "Rahat hesab üçün yuvarlaqlaşdırılır.",
  ["Yuvarlaqlaşdırılır", "Kvadrata yüksəldilir", "Silinir",
   "Tərsinə yazılır"], 1, None, 1),
 ("3 kq alma 4,5 manatdırsa, 1 kq neçəyədir?",
  "4,5 : 3 = 1,5.",
  ["1,5 manat", "13,5 manat", "1,35 manat", "3 manat"],
  1, None, 2),
 ("A = {x; y; z} çoxluğunun ikielementli alt çoxluqlarının sayı neçədir?",
  "{x;y}, {x;z}, {y;z} — üç dənə.",
  ["3 alt çoxluq", "6 alt çoxluq", "2 alt çoxluq",
   "9 alt çoxluq"], 1, None, 3),
 ("Sinifdə 25 şagirddən 40%-i idmançıdır. İdmançıların sayını tapın.",
  "25 × 40 : 100 = 10.",
  ["10 şagird", "40 şagird", "15 şagird", "4 şagird"],
  1, None, 2),
 ("Xətanı tapın: ölçülən 14,2 sm, həqiqi 14 sm.",
  "|14,2 − 14| = 0,2.",
  ["0,2 sm", "2 sm", "14 sm", "0,02 sm"], 1, None, 2),
 ("Artımı faizlə ifadə edin: bilet 8 manatdan 10 manata qalxıb.",
  "Artım 2 manat; 2/8 = 25%.",
  ["25 faiz", "20 faiz", "10 faiz", "2 faiz"], 1, None, 3),
 ("4 dost 74 manatı bərabər bölür. Hərəsinə nə düşür?",
  "74 : 4 = 18,5.",
  ["18,5 manat", "18 manat", "19 manat", "17,5 manat"],
  1, None, 2),
 ("Verilənlərə görə düstur qurmaq məsələ həllində hansı mərhələdir?",
  "Reallığı riyazi dilə çevirmək modelqurmadır.",
  ["Modelqurma", "Yoxlama", "Cavab yazma", "Oxuma"],
  1, None, 3),
 ("A ∪ B çoxluğunda 9, A-da 5, B-də 7 element var. A ∩ B-də neçə element var?",
  "5 + 7 − 9 = 3.",
  ["3 element", "2 element", "12 element", "4 element"],
  1, None, 3),
 ("600 qramlıq məhsulun 15%-i qablaşdırmadır. Qablaşdırma neçə qramdır?",
  "600 × 15 : 100 = 90.",
  ["90 qram", "85 qram", "15 qram", "600 qram"], 1, None, 2),
 ("Cavabın ağlabatan olub-olmadığını qiymətləndirmək nəyi tələb edir?",
  "Cavab təxmini qiymətlə tutuşdurulur.",
  ["Təxmini müqayisəni", "Yeni məsələni", "Qrafiki",
   "Rəngli cədvəli"], 1, None, 3),
],
"riy-7-statistika": [
 ("5, 10, 15, 20 ədədlərinin ədədi ortasını tapın.",
  "Cəm 50; 50 : 4 = 12,5.",
  ["12,5", "12", "13", "50"], 1, None, 2),
 ("Sikkə atışında yazı tərəfinin düşməsi şansı hansı kəsrdir?",
  "İki üzdən biri: 1/2.",
  ["1/2", "1/4", "2/2", "1"], 1, None, 1),
 ("2, 5, 5, 9, 14 sırasının medianını tapın.",
  "Ortadakı üçüncü qiymət 5-dir.",
  ["5-dir", "9-dur", "7-dir", "14-dür"], 1, None, 2),
 ("Zər atılır: 7 düşməsi hansı hadisədir?",
  "Zərdə 7 yoxdur — mümkünsüzdür.",
  ["Mümkünsüz hadisə", "Yəqin hadisə", "Təsadüfi hadisə",
   "Bərabərehtimallı"], 1, None, 2),
 ("Ehtimalı 0,65 olan hadisənin əks hadisəsinin ehtimalı neçədir?",
  "1 − 0,65 = 0,35.",
  ["0,35", "0,65", "0,45", "1,65"], 1, None, 2),
 ("Qutuda 6 qırmızı, 4 göy kürə var. Göy kürə çıxarma ehtimalı neçədir?",
  "4/10 = 2/5.",
  ["2/5", "3/5", "4/6", "1/10"], 1, None, 2),
 ("40 atışdan 16-sı hədəfə dəyib. Nisbi tezliyi tapın.",
  "16/40 = 0,4.",
  ["0,4", "0,16", "0,6", "4"], 1, None, 2),
 ("Median 20-dirsə, sıranın yarısı haqqında nə demək olar?",
  "Yarı qiymətlər mediandan böyük deyil.",
  ["20-dən böyük deyil", "Hamısı 20-dir", "20-dən böyükdür",
   "Sıfırdır"], 1, None, 3),
 ("Üç sınaq qiyməti: 70, 80, 90. Ortalama bal neçədir?",
  "240 : 3 = 80.",
  ["80 bal", "75 bal", "85 bal", "240 bal"], 1, None, 1),
 ("Zər iki dəfə atılır. Hər ikisində 6 düşməsi ehtimalı neçədir?",
  "1/6 · 1/6 = 1/36.",
  ["1/36", "1/12", "2/6", "1/6"], 1, None, 3),
 ("Diaqramda paylar 35%, 25%, 30% göstərilib. Qalan pay neçədir?",
  "100 − 90 = 10.",
  ["10%", "90%", "15%", "5%"], 1, None, 2),
 ("Statistik məlumatın mənbələrindən biri hansıdır?",
  "Sorğu əsas mənbələrdəndir.",
  ["Sorğu", "Təxmin", "Yuxu", "Şayiə"], 1, None, 1),
 ("6, 6, 7, 9, 12, 14 sırasının medianı neçədir?",
  "Ortadakı iki qiymətin ortası: (7 + 9) : 2 = 8.",
  ["8-ə bərabərdir", "7-yə bərabərdir", "9-a bərabərdir",
   "6-ya bərabərdir"], 1, None, 3),
 ("Ehtimal faizlə 100% olarsa, hadisə necə adlanır?",
  "Hökmən baş verən hadisə yəqindir.",
  ["Yəqin hadisə", "Mümkünsüz hadisə", "Təsadüfi hadisə",
   "Nadir hadisə"], 1, None, 2),
 ("Kənar (uc) qiymətlər hansı göstəriciyə ən çox təsir edir?",
  "Ortalama uc qiymətlərə həssasdır.",
  ["Ədədi ortaya", "Modaya", "Mediana", "Heç birinə"],
  1, None, 3),
 ("İki zər atılır, xalların cəmi ən çoxu neçə ola bilər?",
  "6 + 6 = 12.",
  ["12 xal", "6 xal", "11 xal", "36 xal"], 1, None, 2),
 ("5 oyundan 2 qələbənin tezliyini faizlə göstərin.",
  "2/5 = 40%.",
  ["40%", "20%", "50%", "25%"], 1, None, 2),
 ("Verilənlər dəsti: 3, 5, 5, 7, 10. Moda hansıdır?",
  "5 iki dəfə təkrarlanır.",
  ["Moda 5-dir", "Moda 3-dür", "Moda 10-dur", "Moda yoxdur"],
  1, None, 2),
 ("Proqnoz üçün keçmiş məlumatlar niyə vacibdir?",
  "Keçmiş meyli (tendensiyanı) göstərir.",
  ["Meyli göstərdiyi üçün", "Yer tutduğu üçün",
   "Rəngli olduğu üçün", "Vacib deyil"], 1, None, 3),
 ("1000 biletdən 1-i uduşludursa, uduş ehtimalı neçədir?",
  "1/1000.",
  ["1/1000", "1/100", "1/10", "1"], 1, None, 2),
],
"riy-7-tenlikler-sistemi": [
 ("Sistemi həll edin: cəm 10, fərq 4 olan x və y-i tapın.",
  "x = (10 + 4) : 2 = 7; y = 3.",
  ["x = 7, y = 3", "x = 6, y = 4", "x = 8, y = 2",
   "x = 5, y = 5"], 1, None, 3),
 ("Əvəzetmə ilə: y = 3x olduqda x + y = 20 tənliyindən x-i tapın.",
  "x + 3x = 20, 4x = 20, x = 5.",
  ["x = 5", "x = 4", "x = 15", "x = 20"], 1, None, 2),
 ("Sistemin həlli olan ədəd cütü hansı şərti ödəyir?",
  "Cüt hər iki tənliyi doğru edir.",
  ["Hər iki tənliyi ödəyir", "Yalnız birincini",
   "Yalnız ikincini", "Heç birini"], 1, None, 2),
 ("3x + 2y = 12 tənliyində x = 2 olduqda y-i tapın.",
  "6 + 2y = 12, y = 3.",
  ["y = 3", "y = 6", "y = 2", "y = 12"], 1, None, 2),
 ("Toplama üsulunda y-i yox etmək üçün 2x + y = 9 və x − y = 3 tənlikləri ilə nə edilir?",
  "y əmsalları əksdir — tənliklər toplanır.",
  ["Tərəf-tərəfə toplanır", "Vurulur", "Bölünür",
   "Kvadrata yüksəldilir"], 1, None, 2),
 ("İki ədədin cəmi 30, fərqi 6-dır. Böyük ədədi göstərin.",
  "(30 + 6) : 2 = 18.",
  ["18", "12", "24", "15"], 1, str((30 + 6) // 2), 3),
 ("Qrafikləri kəsişməyən sistem haqqında nə deyilir?",
  "Paralel qrafiklərdə ortaq nöqtə yoxdur.",
  ["Həlli yoxdur", "Bir həlli var", "Sonsuz həlli var",
   "İki həlli var"], 1, None, 2),
 ("Yoxlayın: x = 2, y = 3 qiymətləri 2x + y = 7 üçün uyğundurmu?",
  "4 + 3 = 7 — uyğundur.",
  ["Bəli, ödəyir", "Xeyr, 8 alınır", "Xeyr, 6 alınır",
   "Yoxlamaq olmaz"], 1, None, 2),
 ("y = 6 verilib: 5x − y = 14 tənliyindən x-in qiymətini çıxarın.",
  "5x = 20, x = 4.",
  ["x = 4", "x = 2", "x = 6", "x = 20"], 1, None, 2),
 ("Sistemin sonsuz həlli olması nəyi göstərir?",
  "Tənliklər eyni düz xətti verir.",
  ["Tənliklər eyni xətdir", "Xətlər paraleldir",
   "Həll səhvdir", "Sistem böyükdür"], 1, None, 3),
 ("1 kq alma və 1 kq armud 5 manat; 2 kq alma və 1 kq armud 7 manatdır. Alma neçəyədir?",
  "Fərq: 1 kq alma = 2 manat.",
  ["2 manat", "3 manat", "5 manat", "1 manat"], 1, None, 3),
 ("İkidəyişənli xətti tənliyin qrafiki nədir?",
  "ax + by = c qrafiki düz xətdir.",
  ["Düz xətt", "Çevrə", "Parabola", "Nöqtə"], 1, None, 2),
 ("x − y = 0 tənliyi x və y haqqında nə deyir?",
  "Fərq sıfırdırsa, x = y olur.",
  ["x = y olur", "Əks işarəlidirlər", "Hər ikisi sıfırdır",
   "Müqayisə olunmur"], 1, None, 2),
 ("Əvəzetmə üsulunda tapılmış ifadə haraya yazılır?",
  "Bir dəyişənin ifadəsi o biri tənlikdə yerinə qoyulur.",
  ["O biri tənliyə", "Kənara", "Cavaba", "Qrafikə"],
  1, None, 2),
 ("Sistem: x + y = 9, x = 2y. Kiçik ədədi tapın.",
  "3y = 9, y = 3.",
  ["Kiçik ədəd 3-dür", "Kiçik ədəd 6-dır", "Kiçik ədəd 2-dir",
   "Kiçik ədəd 4-dür"], 1, None, 3),
 ("Məsələni sistemlə həll edərkən neçə naməlum işarələnir?",
  "İki dəyişənli sistemdə iki naməlum olur.",
  ["İki naməlum", "Bir naməlum", "Üç naməlum", "Heç biri"],
  1, None, 2),
 ("0·x + 0·y = 5 tənliyinin həlli varmı?",
  "Sol tərəf həmişə 0-dır, 5 ola bilməz.",
  ["Xeyr, yoxdur", "Bəli, sonsuz", "Bəli, bir dənə",
   "x = 5 həllidir"], 1, None, 3),
 ("Qrafik üsulun çatışmazlığı nədir?",
  "Qrafikdən oxunan qiymət təqribi olur.",
  ["Dəqiqlik az olur", "Çox sürətlidir", "Həll vermir",
   "Yalnız müsbətlər tapılır"], 1, None, 3),
 ("y-i hesablayın: 2x + 3y = 16 tənliyində x = 2 verilib.",
  "4 + 3y = 16, y = 4.",
  ["y = 4", "y = 3", "y = 12", "y = 2"], 1, None, 2),
 ("Sistemin həllini qrafikdə hansı nöqtə göstərir?",
  "Həll qrafiklərin kəsişməsidir.",
  ["Kəsişmə nöqtəsi", "Başlanğıc nöqtə", "Ən yüksək nöqtə",
   "İstənilən nöqtə"], 1, None, 2),
],
"riy-7-ucbucaqlar": [
 ("Bucaqları 1 : 2 : 3 kimi bölünən üçbucağın ən böyük bucağını tapın.",
  "180 : 6 = 30; böyük bucaq 3 × 30 = 90.",
  ["90°", "60°", "30°", "120°"], 1, None, 3),
 ("Üçbucağın iki bucağı 40° və 60°-dirsə, xarici bucaqlardan ən kiçiyi neçədir?",
  "Böyük daxili 80°; ən kiçik xarici 180 − 80 = 100°.",
  ["100°", "120°", "140°", "80°"], 1, None, 3),
 ("Düzbucaqlı üçbucaqda 30°-li bucağın qarşısındakı katet hipotenuzun nə qədəridir?",
  "30° qarşısındakı katet hipotenuzun yarısıdır.",
  ["Yarısıdır", "Üçdə biridir", "Bərabərdir", "İki qatıdır"],
  1, None, 3),
 ("Üçbucağın üç tərəfi bərabərdirsə, bucaqları haqqında nə demək olar?",
  "Bərabərtərəflidə bucaqlar 60°-dir.",
  ["Hamısı 60°-dir", "Hamısı 90°-dir", "Fərqlidirlər",
   "Biri kordur"], 1, None, 2),
 ("Üçüncü tərəfin sərhədlərini tapın: iki tərəf 5 sm və 9 sm-dir.",
  "Fərqdən böyük, cəmdən kiçik: 4 < c < 14.",
  ["4 sm ilə 14 sm arasında", "5 sm ilə 9 sm arasında",
   "1 sm ilə 4 sm arasında", "İstənilən ölçüdə"], 1, None, 3),
 ("Ən qısa tərəf hansı bucağın qarşısında yerləşir?",
  "Kiçik bucağın qarşısında kiçik tərəf durur.",
  ["Ən kiçik bucağın", "Ən böyük bucağın", "Düz bucağın",
   "Kor bucağın"], 1, None, 2),
 ("Üçbucağın tənbölənləri hansı nöqtədə kəsişir?",
  "Tənbölənlər bir nöqtədə kəsişir.",
  ["Bir nöqtədə", "Üç nöqtədə", "Kəsişmir", "Təpədə"],
  1, None, 2),
 ("Bərabərtərəfli üçbucağın perimetri 36 sm-dirsə, bir tərəf neçə santimetr olar?",
  "36 : 3 = 12.",
  ["12 sm", "18 sm", "9 sm", "6 sm"], 1, None, 2),
 ("Üçbucağın bir xarici bucağı 130°-dirsə, ona bitişik daxili bucaq neçədir?",
  "180 − 130 = 50.",
  ["50°", "130°", "65°", "40°"], 1, None, 2),
 ("Bərabəryanlı üçbucağın perimetri 20 sm, oturacağı 8 sm-dirsə, yan tərəfi neçədir?",
  "(20 − 8) : 2 = 6.",
  ["6 sm", "12 sm", "8 sm", "4 sm"], 1, None, 3),
 ("Üçbucağın medianları kəsişmə nöqtəsində hansı nisbətdə bölünür?",
  "Təpədən 2 : 1 nisbətində.",
  ["2 : 1 nisbətində", "1 : 1 nisbətində", "3 : 1 nisbətində",
   "Bölünmür"], 1, None, 3),
 ("Düzbucaqlı üçbucağın iti bucaqları 4 : 1 nisbətindədirsə, böyük iti bucaq neçədir?",
  "90 : 5 = 18; böyük bucaq 4 × 18 = 72.",
  ["72°", "18°", "60°", "80°"], 1, None, 3),
 ("Üçbucağın bucaqlarından ikisi 90°-dirsə, belə üçbucaq mövcuddurmu?",
  "İki düz bucaq cəmi 180° edir, üçüncüyə yer qalmır.",
  ["Xeyr, mövcud deyil", "Bəli, mövcuddur",
   "Yalnız böyük üçbucaqlarda", "Yalnız kvadratda"],
  1, None, 2),
 ("Hipotenuz katetdən böyükdürmü?",
  "Ən böyük bucağın qarşısındakı tərəf ən uzundur.",
  ["Bəli, həmişə", "Xeyr, kiçikdir", "Bərabərdirlər",
   "Bəzən"], 1, None, 2),
 ("Bərabəryanlı üçbucağın təpə bucağı 100°-dirsə, oturacaq bucağı neçədir?",
  "(180 − 100) : 2 = 40.",
  ["40°", "80°", "50°", "100°"], 1, None, 3),
 ("Üçbucağın sahəsini hesablamaq üçün hansı iki ölçü lazımdır?",
  "S = a·h : 2 — oturacaq və hündürlük.",
  ["Oturacaq və hündürlük", "İki bucaq", "Perimetr və bucaq",
   "Üç median"], 1, None, 2),
 ("Xarici bucaq özünə bitişik daxili bucaqla birlikdə neçə dərəcə təşkil edir?",
  "Onlar qonşu bucaqlardır: 180°.",
  ["Birlikdə 180°", "Birlikdə 90°", "Birlikdə 360°",
   "Birlikdə 60°"], 1, None, 2),
 ("Üçbucağın bucaqlarının hamısı 60°-dən kiçik ola bilərmi?",
  "Cəm 180°-yə çatmazdı.",
  ["Xeyr, cəm çatmaz", "Bəli, ola bilər", "Yalnız itibucaqlıda",
   "Yalnız korbucaqlıda"], 1, None, 3),
 ("Müxtəliftərəfli üçbucaqda bərabər bucaq varmı?",
  "Tərəflər fərqlidirsə, bucaqlar da fərqlidir.",
  ["Xeyr, hamısı fərqlidir", "Bəli, ikisi bərabərdir",
   "Hamısı bərabərdir", "Biri sıfırdır"], 1, None, 2),
 ("İki üçbucağın iki bucağı uyğun olaraq bərabərdirsə, üçüncü bucaqları necədir?",
  "Cəm 180° olduğundan üçüncülər də bərabərdir.",
  ["Onlar da bərabərdir", "Fərqlidir", "Cəmi 90°-dir",
   "Müəyyən olunmur"], 1, None, 3),
],
}
for _k, _v in ELAVE40.items():
    SUALLAR[_k] = SUALLAR[_k] + _v


def yoxla():
    n = xeta = 0
    butun = set()
    for movzu, siyahi in SUALLAR.items():
        assert movzu in RUBLAR, movzu
        if len(siyahi) != 40:
            print("XETA  %s: %d sual (40 olmalidir)" % (movzu, len(siyahi)))
            xeta += 1
        for body, why, opts, correct, expect, diff in siyahi:
            n += 1
            p = []
            if len(opts) != 4: p.append("variant sayi %d" % len(opts))
            if len(set(opts)) != len(opts): p.append("tekrar variant")
            if not (1 <= correct <= 4): p.append("correct")
            if not why: p.append("izah bos")
            if diff not in (1, 2, 3): p.append("cetinlik")
            if body in butun: p.append("eyni sual iki defe")
            butun.add(body)
            if expect is not None and opts[correct - 1] != expect:
                p.append("hesablanan «%s» != variant «%s»" % (expect, opts[correct - 1]))
            for t in [body, why] + opts:
                if "'" in t: p.append("apostrof var")
            if p:
                xeta += 1
                print("XETA  %s: %s\n      %s" % (movzu, body[:60], "; ".join(p)))
    hes = sum(1 for s in SUALLAR.values() for q in s if q[4] is not None)
    print("%d sual yoxlandı (%d-i hesabla təsdiqləndi), %d xəta" % (n, hes, xeta))
    return xeta == 0, n


def sql_yaz(n):
    q = lambda t: t.replace("'", "''")
    setirler = []
    for movzu in RUBLAR:
        qisa = movzu.replace("riy-7-", "")
        for i, (body, why, opts, correct, _e, diff) in enumerate(SUALLAR[movzu], 1):
            setirler.append(
                "('riy7-%s#%d','%s',%d,%d,'%s','%s',array['%s','%s','%s','%s'],%d)"
                % (qisa, i, movzu, diff, RUBLAR[movzu], q(body), q(why),
                   q(opts[0]), q(opts[1]), q(opts[2]), q(opts[3]), correct))
    with io.open(CIXIS, "w", encoding="utf-8") as f:
        f.write("""-- =====================================================================
--  34_bank_riy7.sql : RIYAZIYYAT 7 PLATFORMA SUAL BANKI (orta mekteb)
--
--  BU FAYL ELLE YAZILMIR - tools/riy7.py yaradir:
--      python3 tools/riy7.py
--
--  10 movzu x 40 sual = %d.  ext_key: riy7-<movzu>#<sira>.
--  ON SERT: 33_movzular_orta7.sql islenmis olmalidir.
--  SONRA:   05_grants.sql yeniden islet.
-- =====================================================================

do $$
begin
  if not exists (
    select 1 from public.topics t
      join public.subjects s on s.id = t.subject_id
     where s.slug = 'riyaziyyat' and t.slug = 'riy-7-muxteser') then
    raise exception 'ONCE 33_movzular_orta7.sql isledilmelidir (riy-7-* movzulari yoxdur).';
  end if;
end $$;

delete from public.question_options o
 using public.questions q
 where o.question_id = q.id
   and q.owner_type = 'platform'
   and q.ext_key like 'riy7-%%';

with d(ext, topic, diff, rub, body, why, opts, correct) as (values
%s
),
ins as (
  insert into public.questions
    (ext_key, owner_type, subject_id, level_id, topic_id, kind,
     body, explanation, difficulty, quarter, status)
  select d.ext, 'platform', s.id, l.id, tp.id, 'single',
         d.body, d.why, d.diff, d.rub, 'published'
    from d
    join public.subjects s on s.slug = 'riyaziyyat'
    join public.programs p on p.slug = 'orta'
    join public.levels   l on l.program_id = p.id and l.code = '7'
    join public.topics   tp on tp.subject_id = s.id and tp.slug = d.topic
  on conflict (ext_key) do update
    set body = excluded.body, explanation = excluded.explanation,
        difficulty = excluded.difficulty, quarter = excluded.quarter,
        topic_id = excluded.topic_id, level_id = excluded.level_id,
        subject_id = excluded.subject_id, status = 'published'
  returning id, ext_key
)
insert into public.question_options (question_id, ord, body, is_correct)
select ins.id, o.ord, o.txt, o.ord = d.correct
  from ins
  join d on d.ext = ins.ext_key,
  lateral unnest(d.opts) with ordinality as o(txt, ord);

do $$
declare n int; k int;
begin
  select count(*) into n from public.questions
   where owner_type = 'platform' and ext_key like 'riy7-%%';
  if n <> %d then
    raise exception 'riy7 suallari: %d gozlenilirdi, %% tapildi', n;
  end if;
  select count(*) into k from public.questions q
   where q.ext_key like 'riy7-%%'
     and ((select count(*) from public.question_options o
            where o.question_id = q.id) <> 4
       or (select count(*) from public.question_options o
            where o.question_id = q.id and o.is_correct) <> 1);
  if k > 0 then
    raise exception '%% sualda variant qurulusu sehvdir', k;
  end if;
  select count(distinct topic_id) into k from public.questions
   where ext_key like 'riy7-%%';
  if k <> 10 then
    raise exception 'movzu sayi 10 deyil: %%', k;
  end if;
  raise notice 'Riyaziyyat 7 banki: %% sual, 10 movzu.', n;
end $$;
""" % (n, ",\n".join(setirler), n, n))
    print("yazildi: %s" % CIXIS)


if __name__ == "__main__":
    ok, n = yoxla()
    if not ok:
        raise SystemExit(1)
    sql_yaz(n)
