#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
1-ci sinif platforma banki -> db/23_bank_sinif1.sql

    Riyaziyyat 1        12 movzu x 10 = 120
    Azerbaycan dili 1    6 movzu x 10 =  60
    Heyat bilgisi 1      5 movzu x 10 =  50
    Informatika 1        4 movzu x 10 =  40
                                  cemi  270

tools/sinif3.py qelibi ile: her riyazi cavab YENIDEN HESABLANIB duzgun
variantla tutusdurulur, heca/sait suallari sait sayghaci ile sayilir.
Movzular 14_movzular.sql (az dili) ve 15_movzular_ederslik.sql
(riyaziyyat, heyat bilgisi, informatika) agacina uygundur.

DIQQET: movcud bank fayllarinin (db/07, 16, 17, 19, 20) cumle qelibleri
ve reqemleri TEKRARLANMAYIB - generator pg_trgm ile >= 0.95 oxsarligi
tekrar sayir.

Isletmek:
    python3 tools/sinif1.py
"""
import io
import os

KOK = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CIXIS = os.path.join(KOK, "db", "23_bank_sinif1.sql")

SAITLER = set("aeəiıoöuü")


def sait(soz):
    return sum(1 for h in soz.lower() if h in SAITLER)


def samit(soz):
    return sum(1 for h in soz.lower() if h.isalpha() and h not in SAITLER)


#  (fenn, movzu-slug, rub) - rub kitabin bolme sirasina gore
MOVZULAR = [
    ("riyaziyyat", "riy-1-elamet",       1),
    ("riyaziyyat", "riy-1-ededler-10",   1),
    ("riyaziyyat", "riy-1-muqayise",     1),
    ("riyaziyyat", "riy-1-toplama-10",   1),
    ("riyaziyyat", "riy-1-cixma-10",     2),
    ("riyaziyyat", "riy-1-ededler-20",   2),
    ("riyaziyyat", "riy-1-fiqurlar",     2),
    ("riyaziyyat", "riy-1-toplama-20",   3),
    ("riyaziyyat", "riy-1-cixma-20",     3),
    ("riyaziyyat", "riy-1-ededler-100",  3),
    ("riyaziyyat", "riy-1-olcme",        4),
    ("riyaziyyat", "riy-1-melumat",      4),
    ("az-dili", "az-1-sesler-herfler",   1),
    ("az-dili", "az-1-sait-samit",       1),
    ("az-dili", "az-1-heca",             2),
    ("az-dili", "az-1-soz-cumle",        2),
    ("az-dili", "az-1-boyuk-herf",       3),
    ("az-dili", "az-1-oxu",              4),
    ("hayat-bilgisi", "hey-1-men-kimem",        1),
    ("hayat-bilgisi", "hey-1-saglamliq",        1),
    ("hayat-bilgisi", "hey-1-insanlar-esyalar", 2),
    ("hayat-bilgisi", "hey-1-etraf-muhit",      3),
    ("hayat-bilgisi", "hey-1-ehtiyat",          4),
    ("informatika", "inf-1-esyalar",     1),
    ("informatika", "inf-1-ardicilliq",  2),
    ("informatika", "inf-1-informasiya", 3),
    ("informatika", "inf-1-kompyuter",   4),
]

SUALLAR = {
# ======================= RIYAZIYYAT 1 =================================
"riy-1-elamet": [
 ("Hansı söz əşyanın rəngini bildirir?",
  "Qırmızı rəng adıdır; böyük — ölçü, yumru — forma bildirir.",
  ["qırmızı", "böyük", "yumru", "ağır"], 1, None, 1),
 ("Top hansı formadadır?",
  "Top yumru formadadır.",
  ["Yumru", "Dördkünc", "Uzunsov", "Düz"], 1, None, 1),
 ("«Böyük — kiçik» sözləri əşyanın hansı əlamətini bildirir?",
  "Böyük və kiçik əşyanın ölçüsünü göstərir.",
  ["Ölçüsünü", "Rəngini", "Dadını", "Qoxusunu"], 1, None, 2),
 ("Kitab stolun üstündə, top isə stolun altındadır. Aşağıda hansı "
  "əşya yerləşir?",
  "Stolun altı aşağıdır — orada top var.",
  ["Top", "Kitab", "Stol", "Heç biri"], 1, None, 2),
 ("Limonun dadı necədir?",
  "Limon turş dadlı meyvədir.",
  ["Turş", "Şirin", "Duzlu", "Dadsız"], 1, None, 1),
 ("Hansı sırada yalnız rəng adları yazılıb?",
  "Sarı, yaşıl, mavi — hamısı rəngdir.",
  ["sarı, yaşıl, mavi", "böyük, kiçik, orta",
   "yumru, uzun, qısa", "isti, soyuq, ilıq"], 1, None, 2),
 ("Qar hansı rəngdə olur?",
  "Qar ağ rəngdədir.",
  ["Ağ", "Qara", "Yaşıl", "Sarı"], 1, None, 1),
 ("Fil siçanla müqayisədə necədir?",
  "Fil siçandan qat-qat böyükdür.",
  ["Böyükdür", "Kiçikdir", "Eynidir", "Qısadır"], 1, None, 1),
 ("Hansı əşyanın forması dairəyə bənzəyir?",
  "Boşqab dairə formasındadır.",
  ["Boşqab", "Kitab", "Qutu", "Qapı"], 1, None, 2),
 ("Pambıq daşla müqayisədə necədir?",
  "Pambıq yüngüldür, daş isə ağırdır.",
  ["Yüngüldür", "Ağırdır", "Bərkdir", "İtidir"], 1, None, 2),
],
"riy-1-ededler-10": [
 ("«Üç» sözü rəqəmlə necə yazılır?",
  "Üç ədədi 3 rəqəmi ilə yazılır.",
  ["3", "2", "4", "8"], 1, str(3), 1),
 ("Sayma zamanı 6-dan sonra hansı ədəd deyilir?",
  "6-dan sonra 7 gəlir.",
  ["7", "5", "8", "6"], 1, str(6 + 1), 1),
 ("Sayma zamanı 4-dən əvvəl hansı ədəd deyilir?",
  "4-dən əvvəl 3 gəlir.",
  ["3", "5", "2", "4"], 1, str(4 - 1), 1),
 ("Bir əlimizdə neçə barmaq var?",
  "Bir əldə 5 barmaq var.",
  ["5", "10", "4", "6"], 1, str(5), 1),
 ("Heç bir əşyanın olmamasını hansı ədəd göstərir?",
  "Heç nə yoxdursa, sıfır yazılır.",
  ["0", "1", "10", "5"], 1, str(0), 2),
 ("Buraxılmış ədədi tapın: 1, 2, 3, ?, 5.",
  "3-dən sonra 4 gəlir.",
  ["4", "6", "3", "5"], 1, str(4), 1),
 ("«On» sözü rəqəmlə necə yazılır?",
  "On ədədi 1 və 0 rəqəmləri ilə yazılır: 10.",
  ["10", "01", "1", "100"], 1, str(10), 1),
 ("Cərgədə Aysu birincidir, Tural ondan dərhal sonra dayanıb. "
  "Tural neçəncidir?",
  "Birincidən sonra ikinci gəlir.",
  ["İkinci", "Birinci", "Üçüncü", "Beşinci"], 1, None, 2),
 ("Ən böyük birrəqəmli ədəd hansıdır?",
  "Birrəqəmli ədədlərin ən böyüyü 9-dur.",
  ["9", "10", "8", "1"], 1, str(9), 2),
 ("Səkkiz ədədi hansı rəqəmlə göstərilir?",
  "Səkkiz 8 rəqəmi ilə yazılır.",
  ["8", "9", "6", "3"], 1, str(8), 1),
],
"riy-1-muqayise": [
 ("5 və 8 ədədlərindən hansı kiçikdir?",
  "5 ədədi 8-dən əvvəl gəlir, deməli kiçikdir.",
  ["5", "8", "Bərabərdirlər", "Bilmək olmaz"], 1, str(min(5, 8)), 1),
 ("Hansı yazılış doğrudur?",
  "3 ədədi 7-dən kiçikdir: 3 < 7.",
  ["3 < 7", "7 < 3", "3 > 7", "3 = 7"], 1, None, 2),
 ("6 = 6 yazılışı nəyi bildirir?",
  "Bərabərlik işarəsi ədədlərin bərabər olduğunu göstərir.",
  ["Ədədlər bərabərdir", "Soldakı böyükdür",
   "Sağdakı böyükdür", "Ədədlər fərqlidir"], 1, None, 2),
 ("2, 9, 5 ədədlərini artan sırada düzün.",
  "Kiçikdən böyüyə: 2, 5, 9.",
  ["2, 5, 9", "9, 5, 2", "2, 9, 5", "5, 2, 9"], 1, None, 2),
 ("Ədəd oxunda 4-dən dərhal sağda hansı ədəd durur?",
  "Ədəd oxunda sağa getdikcə ədədlər 1 vahid artır: 5.",
  ["5", "3", "6", "4"], 1, str(4 + 1), 3),
 ("«>» işarəsi necə oxunur?",
  "Açıq tərəf böyük ədədə baxır: böyükdür.",
  ["Böyükdür", "Kiçikdir", "Bərabərdir", "Toplamaq"], 1, None, 1),
 ("Aysunun 7, Turalın 4 konfeti var. Kimin konfeti çoxdur?",
  "7 ədədi 4-dən böyükdür, deməli Aysununku çoxdur.",
  ["Aysunun", "Turalın", "Bərabərdir", "Bilmək olmaz"], 1, None, 1),
 ("6, 3, 8, 5 ədədlərindən ən kiçiyi hansıdır?",
  "Sayma sırasında ən əvvəl 3 gəlir.",
  ["3", "5", "6", "8"], 1, str(min(6, 3, 8, 5)), 2),
 ("1 və 0 ədədlərindən hansı böyükdür?",
  "1 ədədi 0-dan sonra gəlir, deməli böyükdür.",
  ["1", "0", "Bərabərdirlər", "Bilmək olmaz"], 1, str(max(1, 0)), 1),
 ("Ədəd oxunda sola getdikcə ədədlər necə dəyişir?",
  "Sola getdikcə ədədlər azalır.",
  ["Azalır", "Artır", "Dəyişmir", "Gah artır, gah azalır"], 1, None, 3),
],
"riy-1-toplama-10": [
 ("2 + 3 cəmini tapın.",
  "2 + 3 = 5.",
  ["5", "4", "6", "1"], 1, str(2 + 3), 1),
 ("4 + 4 neçə edər?",
  "4 + 4 = 8.",
  ["8", "7", "9", "6"], 1, str(4 + 4), 1),
 ("Aysunun 3 şarı var idi. Anası ona 1 şar da verdi. Aysunun "
  "neçə şarı oldu?",
  "3 + 1 = 4.",
  ["4", "3", "5", "2"], 1, str(3 + 1), 1),
 ("6 + 0 neçə olar?",
  "Sıfır əlavə edəndə ədəd dəyişmir: 6.",
  ["6", "0", "7", "60"], 1, str(6 + 0), 2),
 ("1 + 8 cəmini hesablayın.",
  "1 + 8 = 9.",
  ["9", "8", "10", "7"], 1, str(1 + 8), 1),
 ("3 + 4 = 4 + ? Sual işarəsinin yerinə hansı ədəd yazılmalıdır?",
  "Toplananların yerini dəyişəndə cəm dəyişmir: 3.",
  ["3", "4", "7", "1"], 1, str(3), 3),
 ("2 + 2 + 3 ifadəsinin qiyməti neçədir?",
  "2 + 2 = 4; 4 + 3 = 7.",
  ["7", "6", "8", "4"], 1, str(2 + 2 + 3), 2),
 ("Hansı cütün cəmi 10 edir?",
  "6 + 4 = 10.",
  ["6 və 4", "5 və 4", "7 və 2", "6 və 3"], 1, None, 2),
 ("Toplananlar 5 və 1-dirsə, cəm neçədir?",
  "5 + 1 = 6.",
  ["6", "5", "4", "7"], 1, str(5 + 1), 2),
 ("Budaqda 4 quş oturmuşdu. Yanına daha 3 quş qondu. Budaqda "
  "neçə quş oldu?",
  "4 + 3 = 7.",
  ["7", "6", "8", "1"], 1, str(4 + 3), 2),
],
"riy-1-cixma-10": [
 ("7 − 2 fərqini tapın.",
  "7 − 2 = 5.",
  ["5", "6", "4", "9"], 1, str(7 - 2), 1),
 ("9 − 3 neçə edər?",
  "9 − 3 = 6.",
  ["6", "7", "5", "12"], 1, str(9 - 3), 1),
 ("5 − 5 neçə olar?",
  "Ədəddən özünü çıxanda sıfır qalır.",
  ["0", "5", "1", "10"], 1, str(5 - 5), 2),
 ("8 − 0 neçədir?",
  "Sıfır çıxanda ədəd dəyişmir: 8.",
  ["8", "0", "7", "9"], 1, str(8 - 0), 2),
 ("Turalın 6 konfeti var idi. O, 2 konfeti yedi. Neçə konfeti qaldı?",
  "6 − 2 = 4.",
  ["4", "3", "5", "8"], 1, str(6 - 2), 1),
 ("10 − 3 fərqini hesablayın.",
  "10 − 3 = 7.",
  ["7", "8", "6", "13"], 1, str(10 - 3), 1),
 ("Hansı ədədə 3 əlavə etsək, 9 alarıq?",
  "9 − 3 = 6, deməli axtarılan ədəd 6-dır.",
  ["6", "12", "5", "3"], 1, str(9 - 3), 3),
 ("8 − 5 = 3 çıxmasını yoxlamaq üçün hansı toplama uyğundur?",
  "Fərqin üstünə çıxanı gələndə çıxılan alınmalıdır: 3 + 5 = 8.",
  ["3 + 5 = 8", "8 + 5 = 13", "3 + 8 = 11", "5 − 3 = 2"], 1, None, 3),
 ("Fərq nə vaxt sıfıra bərabər olur?",
  "Bərabər ədədləri çıxanda fərq sıfırdır.",
  ["Çıxılan və çıxan bərabər olanda", "Çıxılan böyük olanda",
   "Çıxan sıfır olanda", "Heç vaxt"], 1, None, 3),
 ("Tabaqda 10 alma var idi. Uşaqlar 6 almanı götürdü. Tabaqda "
  "neçə alma qaldı?",
  "10 − 6 = 4.",
  ["4", "5", "6", "16"], 1, str(10 - 6), 2),
],
"riy-1-ededler-20": [
 ("1 onluq və 4 təklikdən ibarət ədəd hansıdır?",
  "1 onluq = 10; 10 + 4 = 14.",
  ["14", "41", "4", "104"], 1, str(10 + 4), 2),
 ("17 ədədində neçə onluq var?",
  "17 = 1 onluq və 7 təklik.",
  ["1", "7", "17", "10"], 1, str(17 // 10), 2),
 ("İrəli sayma: 15-dən sonra hansı ədəd gəlir?",
  "15 + 1 = 16.",
  ["16", "14", "17", "15"], 1, str(15 + 1), 1),
 ("Geri sayma: 18, 17, 16, ? Növbəti ədəd hansıdır?",
  "Geri sayanda hər ədəd 1 vahid azalır: 15.",
  ["15", "14", "16", "19"], 1, str(16 - 1), 2),
 ("12 və 19 ədədlərindən hansı kiçikdir?",
  "12 sayma sırasında əvvəl gəlir.",
  ["12", "19", "Bərabərdirlər", "Bilmək olmaz"], 1, str(min(12, 19)), 1),
 ("«On doqquz» ədədi rəqəmlə necə yazılır?",
  "On doqquz = 1 onluq və 9 təklik: 19.",
  ["19", "91", "9", "109"], 1, str(19), 1),
 ("13 ədədi neçə onluq və neçə təklikdən ibarətdir?",
  "13 = 1 onluq və 3 təklik.",
  ["1 onluq, 3 təklik", "3 onluq, 1 təklik",
   "13 onluq", "10 onluq, 3 təklik"], 1, None, 2),
 ("11, 15, 13 ədədlərini artan sırada düzün.",
  "Kiçikdən böyüyə: 11, 13, 15.",
  ["11, 13, 15", "15, 13, 11", "11, 15, 13", "13, 11, 15"],
  1, None, 2),
 ("20 ədədində təkliklər mərtəbəsində hansı rəqəm durur?",
  "20 = 2 onluq və 0 təklik.",
  ["0", "2", "20", "1"], 1, str(20 % 10), 3),
 ("2 onluq neçə edir?",
  "2 onluq = 20.",
  ["20", "2", "12", "22"], 1, str(2 * 10), 2),
],
"riy-1-fiqurlar": [
 ("Üç tərəfi və üç küncü olan fiqur necə adlanır?",
  "Üç tərəfi olan fiqur üçbucaqdır.",
  ["Üçbucaq", "Kvadrat", "Dairə", "Düzbucaqlı"], 1, None, 1),
 ("Velosipedin təkəri hansı fiqura bənzəyir?",
  "Təkər dairə formasındadır.",
  ["Dairəyə", "Kvadrata", "Üçbucağa", "Düzbucaqlıya"], 1, None, 1),
 ("Kvadratın neçə tərəfi var?",
  "Kvadratın 4 bərabər tərəfi var.",
  ["4", "3", "5", "6"], 1, str(4), 1),
 ("Dairəni üçbucaqdan fərqləndirən nədir?",
  "Dairənin küncü və düz tərəfi yoxdur.",
  ["Küncünün olmaması", "Rənginin fərqli olması",
   "Daha böyük olması", "Tərəflərinin çox olması"], 1, None, 2),
 ("Futbol topu hansı fəza fiqurudur?",
  "Top kürə formasındadır.",
  ["Kürə", "Kub", "Konus", "Silindr"], 1, None, 2),
 ("Çörək tən ortadan iki bərabər hissəyə bölündü. Hər hissə "
  "necə adlanır?",
  "Tamın iki bərabər hissəsindən hər biri yarıdır.",
  ["Yarı", "Tam", "Dörddə bir", "Bütöv"], 1, None, 2),
 ("Pəncərə çərçivəsi adətən hansı fiqura bənzəyir?",
  "Pəncərə düzbucaqlı formasındadır.",
  ["Düzbucaqlıya", "Dairəyə", "Üçbucağa", "Kürəyə"], 1, None, 1),
 ("Bir tam neçə yarıdan ibarətdir?",
  "İki yarı birlikdə bir tam edir.",
  ["2", "1", "3", "4"], 1, str(2), 2),
 ("Hansı fiqur fəza fiqurudur?",
  "Kub fəza fiqurudur; kvadrat, dairə, üçbucaq müstəvi fiqurlardır.",
  ["Kub", "Kvadrat", "Dairə", "Üçbucaq"], 1, None, 3),
 ("Dondurma külahı hansı fəza fiquruna bənzəyir?",
  "Külah konus formasındadır.",
  ["Konusa", "Kuba", "Kürəyə", "Silindrə"], 1, None, 3),
],
"riy-1-toplama-20": [
 ("12 + 5 neçə edər?",
  "12 + 5 = 17.",
  ["17", "16", "18", "7"], 1, str(12 + 5), 1),
 ("9 + 6 cəmini tapın.",
  "9-u 10-a tamamlayaq: 9 + 1 = 10; 10 + 5 = 15.",
  ["15", "14", "16", "13"], 1, str(9 + 6), 2),
 ("8 + 8 neçə edər?",
  "8 + 8 = 16.",
  ["16", "15", "17", "14"], 1, str(8 + 8), 2),
 ("13 + 6 cəmini hesablayın.",
  "13 + 6 = 19.",
  ["19", "18", "20", "16"], 1, str(13 + 6), 1),
 ("7 + 7 neçə olar?",
  "7 + 7 = 14.",
  ["14", "13", "15", "12"], 1, str(7 + 7), 1),
 ("10 + 8 cəmini tapın.",
  "10-un üstünə 8 gələndə 18 olur.",
  ["18", "17", "80", "19"], 1, str(10 + 8), 1),
 ("Aysu səhər 6, axşam 7 səhifə oxudu. O, cəmi neçə səhifə oxudu?",
  "6 + 7 = 13.",
  ["13", "12", "14", "1"], 1, str(6 + 7), 2),
 ("Hansı cütün cəmi 20-dir?",
  "12 + 8 = 20.",
  ["12 və 8", "12 və 7", "11 və 8", "13 və 8"], 1, None, 3),
 ("9 + 2 neçə edər?",
  "9 + 2 = 11.",
  ["11", "10", "12", "7"], 1, str(9 + 2), 1),
 ("Qutuda 14 karandaş var idi. Üstünə 6 karandaş da qoyuldu. "
  "Qutuda neçə karandaş oldu?",
  "14 + 6 = 20.",
  ["20", "19", "8", "21"], 1, str(14 + 6), 2),
],
"riy-1-cixma-20": [
 ("16 − 4 fərqini tapın.",
  "16 − 4 = 12.",
  ["12", "11", "13", "20"], 1, str(16 - 4), 1),
 ("13 − 4 neçə edər?",
  "13 − 3 = 10; 10 − 1 = 9.",
  ["9", "10", "8", "11"], 1, str(13 - 4), 2),
 ("17 − 10 neçə olar?",
  "1 onluq çıxanda təkliklər qalır: 7.",
  ["7", "8", "17", "10"], 1, str(17 - 10), 1),
 ("11 − 5 fərqini hesablayın.",
  "11 − 1 = 10; 10 − 4 = 6.",
  ["6", "7", "5", "16"], 1, str(11 - 5), 2),
 ("20 − 10 neçə edər?",
  "2 onluqdan 1 onluq çıxanda 1 onluq qalır: 10.",
  ["10", "20", "0", "12"], 1, str(20 - 10), 1),
 ("14 − 9 neçə olar?",
  "14 − 4 = 10; 10 − 5 = 5.",
  ["5", "6", "4", "23"], 1, str(14 - 9), 2),
 ("18 − 10 fərqini tapın.",
  "18 − 10 = 8.",
  ["8", "9", "18", "28"], 1, str(18 - 10), 1),
 ("6 çıxılanda 8 qalan ədəd hansıdır?",
  "8 + 6 = 14, deməli axtarılan ədəd 14-dür.",
  ["14", "2", "12", "15"], 1, str(8 + 6), 3),
 ("Avtobusda 15 sərnişin var idi. Dayanacaqda 4 sərnişin düşdü. "
  "Avtobusda neçə sərnişin qaldı?",
  "15 − 4 = 11.",
  ["11", "12", "10", "19"], 1, str(15 - 4), 2),
 ("19 − 15 neçə edər?",
  "19 − 15 = 4.",
  ["4", "5", "3", "14"], 1, str(19 - 15), 2),
],
"riy-1-ededler-100": [
 ("Onluqlarla sayma: 10, 20, 30, ? Növbəti ədəd hansıdır?",
  "Hər addımda 1 onluq artır: 40.",
  ["40", "31", "50", "35"], 1, str(30 + 10), 1),
 ("5 onluqdan ibarət ədəd hansıdır?",
  "5 onluq = 50.",
  ["50", "5", "15", "55"], 1, str(5 * 10), 2),
 ("43 ədədində neçə onluq var?",
  "43 = 4 onluq və 3 təklik.",
  ["4", "3", "43", "40"], 1, str(43 // 10), 2),
 ("67 ədədində təkliklər mərtəbəsində hansı rəqəm durur?",
  "67 = 6 onluq və 7 təklik.",
  ["7", "6", "67", "0"], 1, str(67 % 10), 2),
 ("Sayma zamanı 100-dən əvvəl hansı ədəd deyilir?",
  "100 − 1 = 99.",
  ["99", "90", "101", "98"], 1, str(100 - 1), 2),
 ("Azərbaycanın pul vahidi necə adlanır?",
  "Pul vahidimiz manatdır, xırda pul qəpikdir.",
  ["Manat", "Dollar", "Avro", "Rubl"], 1, None, 1),
 ("Yarım manat neçə qəpikdir?",
  "1 manat 100 qəpikdir; yarısı 50 qəpikdir.",
  ["50 qəpik", "5 qəpik", "100 qəpik", "10 qəpik"], 1,
  "%d qəpik" % (100 // 2), 3),
 ("Alma 30 qəpikdir. Aysu satıcıya 50 qəpik verdi. Satıcı nə "
  "qədər qaytarmalıdır?",
  "50 − 30 = 20 qəpik.",
  ["20 qəpik", "30 qəpik", "80 qəpik", "10 qəpik"], 1,
  "%d qəpik" % (50 - 30), 3),
 ("10 qəpiklik sikkələrlə 1 manat yığmaq üçün neçə sikkə lazımdır?",
  "1 manat = 100 qəpik; 100-də on dənə 10 var.",
  ["10", "5", "100", "20"], 1, str(100 // 10), 3),
 ("34 və 43 ədədlərindən hansı böyükdür?",
  "43-də 4 onluq, 34-də 3 onluq var: 43 böyükdür.",
  ["43", "34", "Bərabərdirlər", "Bilmək olmaz"], 1,
  str(max(34, 43)), 2),
],
"riy-1-olcme": [
 ("Karandaşın uzunluğunu hansı vahidlə ölçürük?",
  "Kiçik əşyaların uzunluğu santimetrlə ölçülür.",
  ["Santimetrlə", "Kiloqramla", "Litrlə", "Saatla"], 1, None, 1),
 ("Bir həftədə neçə gün var?",
  "Həftədə 7 gün var.",
  ["7", "5", "10", "12"], 1, str(7), 1),
 ("Bir ildə neçə ay var?",
  "İldə 12 ay var.",
  ["12", "10", "7", "24"], 1, str(12), 2),
 ("Uzunluğu ölçmək üçün hansı alətdən istifadə olunur?",
  "Uzunluq xətkeşlə ölçülür.",
  ["Xətkeş", "Tərəzi", "Saat", "Termometr"], 1, None, 1),
 ("Qarpız və alma tərəziyə qoyuldu. Hansı daha ağırdır?",
  "Qarpız almadan xeyli ağırdır.",
  ["Qarpız", "Alma", "Bərabərdirlər", "Bilmək olmaz"], 1, None, 1),
 ("Saat tam 3-ü göstərəndə böyük əqrəb hansı rəqəmin üstündə olur?",
  "Tam saatlarda böyük əqrəb həmişə 12-nin üstündə durur.",
  ["12", "3", "6", "9"], 1, None, 3),
 ("Bu gün çərşənbədirsə, sabah hansı gün olacaq?",
  "Çərşənbədən sonra cümə axşamı gəlir.",
  ["Cümə axşamı", "Çərşənbə axşamı", "Cümə", "Bazar"], 1, None, 3),
 ("Vedrənin və stəkanın hansının tutumu böyükdür?",
  "Vedrəyə daha çox su yerləşir.",
  ["Vedrənin", "Stəkanın", "Bərabərdirlər", "Bilmək olmaz"],
  1, None, 2),
 ("Həftənin birinci iş günü hansıdır?",
  "İş həftəsi bazar ertəsindən başlayır.",
  ["Bazar ertəsi", "Bazar", "Şənbə", "Cümə"], 1, None, 2),
 ("Karandaş 10 sm, qələm 7 sm-dir. Hansı uzundur?",
  "10 ədədi 7-dən böyükdür — karandaş uzundur.",
  ["Karandaş", "Qələm", "Bərabərdirlər", "Bilmək olmaz"], 1, None, 2),
],
"riy-1-melumat": [
 ("Piktoqramda hər şəkil 1 almanı göstərir. 4 şəkil neçə alma deməkdir?",
  "4 şəkil = 4 alma.",
  ["4", "1", "8", "2"], 1, str(4), 1),
 ("Cədvəl: Aysu — 3 kitab, Tural — 5 kitab oxuyub. Kim çox oxuyub?",
  "5 ədədi 3-dən böyükdür — Tural çox oxuyub.",
  ["Tural", "Aysu", "Bərabərdirlər", "Bilmək olmaz"], 1, None, 1),
 ("Sinifdə 4 qız və 3 oğlan var. Sinifdə cəmi neçə şagird var?",
  "4 + 3 = 7.",
  ["7", "6", "8", "1"], 1, str(4 + 3), 2),
 ("Naxış belə düzülür: 2, 4, 6, … Növbəti ədəd hansı olacaq?",
  "Hər ədəd əvvəlkindən 2 vahid çoxdur: 8.",
  ["8", "7", "10", "9"], 1, str(6 + 2), 3),
 ("Cədvəldə məlumatlar harada yerləşir?",
  "Cədvəl sətir və sütunlardan ibarətdir.",
  ["Sətir və sütunlarda", "Yalnız şəkillərdə",
   "Dairələrdə", "Xəritədə"], 1, None, 2),
 ("Diaqramda ən hündür sütun nəyi göstərir?",
  "Sütun nə qədər hündürdürsə, say o qədər çoxdur.",
  ["Ən çox olanı", "Ən az olanı", "Ən kiçiyi", "Heç nəyi"],
  1, None, 2),
 ("Hava cədvəlində 2 günəşli, 5 yağışlı gün qeyd olunub. Hansı "
  "günlər çox olub?",
  "5 ədədi 2-dən böyükdür — yağışlı günlər çox olub.",
  ["Yağışlı", "Günəşli", "Bərabər", "Bilmək olmaz"], 1, None, 2),
 ("Səbətdə 5 alma, 2 armud var. Armudlar almalardan neçə dənə azdır?",
  "5 − 2 = 3.",
  ["3", "2", "7", "4"], 1, str(5 - 2), 3),
 ("Naxışı davam etdirin: dairə, üçbucaq, dairə, üçbucaq, dairə, …",
  "Növbə ilə təkrarlanır — dairədən sonra üçbucaq gəlir.",
  ["Üçbucaq", "Dairə", "Kvadrat", "Ulduz"], 1, None, 2),
 ("Uşaqların boyu: Lalə 110 sm, Nihad 105 sm. Kim hündürdür?",
  "110 ədədi 105-dən böyükdür — Lalə hündürdür.",
  ["Lalə", "Nihad", "Bərabərdirlər", "Bilmək olmaz"], 1, None, 2),
],
# ===================== AZERBAYCAN DILI 1 ==============================
"az-1-sesler-herfler": [
 ("Azərbaycan əlifbasında neçə hərf var?",
  "Əlifbamızda 32 hərf var.",
  ["32", "23", "9", "26"], 1, None, 2),
 ("Hərf nədir?",
  "Hərf səsin yazıda göstərilən işarəsidir.",
  ["Səsin yazıdakı işarəsi", "Eşitdiyimiz səs",
   "Sözün mənası", "Cümlənin sonu"], 1, None, 2),
 ("Əlifbada «A» hərfindən sonra hansı hərf gəlir?",
  "Əlifba sırası: A, B, C…",
  ["B", "C", "D", "Z"], 1, None, 1),
 ("«Su» sözü neçə səsdən ibarətdir?",
  "S-u: iki səs.",
  ["2", "3", "1", "4"], 1, str(len("su")), 1),
 ("Əlifbamızın birinci hərfi hansıdır?",
  "Əlifba A hərfi ilə başlayır.",
  ["A", "B", "Ə", "Z"], 1, None, 1),
 ("Hansı hərf Azərbaycan əlifbasında YOXDUR?",
  "W hərfi əlifbamızda yoxdur.",
  ["W", "Ə", "Ş", "Ü"], 1, None, 2),
 ("Səsi və hərfi necə fərqləndiririk?",
  "Səsi eşidir və deyirik, hərfi yazır və görürük.",
  ["Səsi eşidirik, hərfi yazırıq", "Səsi yazırıq, hərfi eşidirik",
   "İkisi də yalnız yazılır", "İkisi də yalnız eşidilir"],
  1, None, 2),
 ("«Qız» sözündə neçə səs var?",
  "Q-ı-z: üç səs.",
  ["3", "2", "4", "5"], 1, str(len("qız")), 1),
 ("Əlifbamızın sonuncu hərfi hansıdır?",
  "Əlifba Z hərfi ilə bitir.",
  ["Z", "A", "Y", "Ü"], 1, None, 2),
 ("«A» və «a» yazılışları nəyi göstərir?",
  "Eyni hərfin böyük və kiçik yazılışıdır.",
  ["Eyni hərfin böyük və kiçik formasını", "İki müxtəlif hərfi",
   "İki müxtəlif səsi", "Rəqəmləri"], 1, None, 2),
],
"az-1-sait-samit": [
 ("Dilimizdə saitlərin sayı neçədir?",
  "Saitlər 9-dur: a, e, ə, i, ı, o, ö, u, ü.",
  ["9", "32", "23", "6"], 1, None, 2),
 ("«Ev» sözündə hansı hərf saitdir?",
  "E saitdir, v samitdir.",
  ["e", "v", "hər ikisi", "heç biri"], 1, None, 1),
 ("«Balıq» sözündəki saitləri sayın.",
  "Saitlər: a və ı — iki sait.",
  ["2", "3", "1", "5"], 1, str(sait("balıq")), 2),
 ("Tələffüz zamanı maneəyə rast gələn səslər necə adlanır?",
  "Samitlər maneə ilə tələffüz olunur.",
  ["Samitlər", "Saitlər", "Hecalar", "Sözlər"], 1, None, 3),
 ("«k» səsi saitdir, yoxsa samit?",
  "K samit səsdir.",
  ["Samitdir", "Saitdir", "Hər ikisidir", "Səs deyil"], 1, None, 1),
 ("Hansı cərgədə yalnız samit hərflər yazılıb?",
  "B, d, k — hamısı samitdir.",
  ["b, d, k", "a, ı, u", "e, m, i", "o, ö, t"], 1, None, 2),
 ("«ü» hansı səsdir?",
  "Ü sait səsdir.",
  ["Sait", "Samit", "Heca", "Söz"], 1, None, 1),
 ("Hər hecada mütləq hansı səs olmalıdır?",
  "Hecanı sait yaradır — hecada mütləq bir sait olur.",
  ["Sait", "Samit", "İki samit", "Heç bir səs"], 1, None, 3),
 ("«Ana» sözündəki saitlər hansılardır?",
  "A-n-a sözündə iki a saiti var.",
  ["a, a", "a, n", "n, n", "a, n, a"], 1, None, 2),
 ("«Qapı» sözündə neçə samit var?",
  "Samitlər: q və p — iki samit.",
  ["2", "3", "1", "4"], 1, str(samit("qapı")), 2),
],
"az-1-heca": [
 ("Sözlər hecalara nəyə görə bölünür?",
  "Sözdə neçə sait varsa, o qədər də heca var.",
  ["Saitlərin sayına görə", "Samitlərin sayına görə",
   "Hərflərin sayına görə", "Sözün uzunluğuna görə"], 1, None, 3),
 ("«Ata» sözü neçə hecadan ibarətdir?",
  "A-ta: iki heca (iki sait).",
  ["2", "1", "3", "4"], 1, str(sait("ata")), 1),
 ("«Lalə» sözünün hecalara bölünüşü hansıdır?",
  "Düzgün bölgü: la-lə.",
  ["la-lə", "lal-ə", "l-alə", "lalə-"], 1, None, 2),
 ("Birhecalı sözü seçin.",
  "«Gül» sözündə bir sait var — bir hecadır.",
  ["gül", "araba", "lalə", "kəpənək"], 1, None, 2),
 ("«Kəpənək» sözündə hecaların sayı neçədir?",
  "Kə-pə-nək: üç heca.",
  ["3", "2", "4", "7"], 1, str(sait("kəpənək")), 2),
 ("Üçhecalı söz hansıdır?",
  "A-ra-ba: üç heca; gül — bir, dəftər və kitab — iki hecadır.",
  ["araba", "gül", "dəftər", "kitab"], 1, None, 3),
 ("Sözdəki hecaların sayı nəyə bərabərdir?",
  "Heca sayı sait səslərin sayına bərabərdir.",
  ["Sait səslərin sayına", "Samit səslərin sayına",
   "Bütün hərflərin sayına", "Sözlərin sayına"], 1, None, 3),
 ("«O» sözü neçə hecadır?",
  "Tək bir sait də heca sayılır: bir heca.",
  ["1", "2", "0", "3"], 1, str(sait("o")), 2),
 ("Hansı bölgü düzgündür?",
  "Düzgün bölgü: a-na.",
  ["a-na", "an-a", "ana-", "-ana"], 1, None, 1),
 ("«Şagird» sözündə neçə heca var?",
  "Şa-gird: iki heca.",
  ["2", "3", "1", "6"], 1, str(sait("şagird")), 2),
],
"az-1-soz-cumle": [
 ("Bitmiş fikri nə ifadə edir?",
  "Cümlə bitmiş fikir bildirir.",
  ["Cümlə", "Heca", "Hərf", "Səs"], 1, None, 2),
 ("Sözlərdən cümlə qurun: «məktəbə», «Aysu», «gedir».",
  "Düzgün sıra: Aysu məktəbə gedir.",
  ["Aysu məktəbə gedir.", "Məktəbə gedir Aysu gedir.",
   "Gedir Aysu.", "Məktəbə Aysu."], 1, None, 2),
 ("«Quş uçur» cümləsində neçə söz var?",
  "Quş və uçur — iki söz.",
  ["2", "1", "3", "4"], 1, str(len("quş uçur".split())), 1),
 ("Hansı sırada bitmiş fikir ifadə olunub?",
  "«Yağış yağır.» — bitmiş fikirdir; qalanları söz birləşməsidir.",
  ["Yağış yağır.", "yaşıl yarpaq", "böyük ev", "şirin alma"],
  1, None, 2),
 ("Söz nədən ibarətdir?",
  "Söz səslərdən (yazıda hərflərdən) ibarətdir.",
  ["Səslərdən", "Cümlələrdən", "Mətnlərdən", "Rəqəmlərdən"],
  1, None, 2),
 ("«Mən kitab oxuyuram» cümləsində sözlərin sayı neçədir?",
  "Mən, kitab, oxuyuram — üç söz.",
  ["3", "2", "4", "5"], 1, str(len("mən kitab oxuyuram".split())), 2),
 ("Sual bildirən cümlənin sonunda hansı işarə qoyulur?",
  "Sual cümləsi sual işarəsi ilə bitir.",
  ["Sual işarəsi", "Nöqtə", "Vergül", "Tire"], 1, None, 2),
 ("Sözləri əlifba sırası ilə düzün: alma, banan, armud.",
  "Al… ar… ba…: alma, armud, banan.",
  ["alma, armud, banan", "banan, alma, armud",
   "alma, banan, armud", "armud, banan, alma"], 1, None, 3),
 ("Fikri aydın çatdırmaq üçün cümlədə sözlər necə düzülməlidir?",
  "Sözlər mənalı ardıcıllıqla düzülməlidir.",
  ["Mənalı ardıcıllıqla", "Qarışıq", "Əlifba sırası ilə",
   "Uzunluğuna görə"], 1, None, 2),
 ("«Ay», «ev», «su» — bunlar nədir?",
  "Hər biri ayrıca sözdür.",
  ["Sözlərdir", "Cümlələrdir", "Hecalardır", "Hərflərdir"],
  1, None, 1),
],
"az-1-boyuk-herf": [
 ("İnsan adları hansı hərflə yazılmağa başlanır?",
  "Adlar böyük hərflə yazılır.",
  ["Böyük hərflə", "Kiçik hərflə", "İstənilən hərflə", "Rəqəmlə"],
  1, None, 1),
 ("Hansı söz həmişə böyük hərflə yazılır?",
  "Bakı şəhər adıdır — xüsusi ad böyük hərflə yazılır.",
  ["Bakı", "şəhər", "küçə", "ev"], 1, None, 2),
 ("Cümləyə başlayanda birinci hərf necə yazılır?",
  "Cümlənin ilk hərfi böyük yazılır.",
  ["Böyük", "Kiçik", "Rəngli", "Qoşa"], 1, None, 1),
 ("Qızın adının düzgün yazılışını seçin.",
  "Ad böyük hərflə başlayır, qalan hərflər kiçik olur: Aysu.",
  ["Aysu", "aysu", "AYsu", "aySU"], 1, None, 2),
 ("İtin adı «Alabaş»dır. Bu ad necə yazılmalıdır?",
  "Heyvanlara verilən adlar da böyük hərflə yazılır.",
  ["Böyük hərflə", "Kiçik hərflə", "Dırnaq içində kiçik hərflə",
   "Rəqəmlə"], 1, None, 3),
 ("Hansı sıradakı sözlərin hamısı böyük hərflə yazılmalıdır?",
  "Araz, Gəncə, Aygün — hamısı xüsusi addır.",
  ["Araz, Gəncə, Aygün", "kitab, qələm, dəftər",
   "araz, gəncə, aygün", "məktəb, sinif, dərs"], 1, None, 2),
 ("«bakı şəhəri gözəldir.» cümləsində hansı səhv var?",
  "Bakı xüsusi addır və cümlənin əvvəlidir — böyük hərflə yazılmalıdır.",
  ["Bakı böyük hərflə yazılmalıdır", "Nöqtə artıqdır",
   "Söz sırası səhvdir", "Səhv yoxdur"], 1, None, 3),
 ("Kür nədir və niyə böyük hərflə yazılır?",
  "Kür çayın adıdır — çay adları xüsusi addır.",
  ["Çay adıdır, xüsusi addır", "Adi sözdür",
   "Kiçik hərflə yazılmalıdır", "Heca adıdır"], 1, None, 2),
 ("Ölkəmizin adı necə yazılır?",
  "Azərbaycan xüsusi addır — böyük hərflə yazılır.",
  ["Azərbaycan", "azərbaycan", "AZƏRbaycan", "azərBaycan"],
  1, None, 1),
 ("Hansı söz kiçik hərflə yazılır?",
  "«Şagird» ümumi sözdür; Leyla, Şəki, Qəbələ xüsusi adlardır.",
  ["şagird", "Leyla", "Şəki", "Qəbələ"], 1, None, 2),
],
"az-1-oxu": [
 ("Mətn: «Aysu bağçada gül əkdi. O, hər gün gülə su verdi.» "
  "Aysu nə əkdi?",
  "Mətndə deyilir: Aysu gül əkdi.",
  ["Gül", "Ağac", "Tərəvəz", "Çiçək toxumu"], 1, None, 1),
 ("Nağıllar adətən hansı sözlərlə başlayır?",
  "Nağılın ənənəvi başlanğıcı: biri var idi, biri yox idi.",
  ["Biri var idi, biri yox idi", "Sonra nə oldu",
   "Beləliklə bitdi", "Salam, uşaqlar"], 1, None, 2),
 ("Şeir nədən ibarət olur?",
  "Şeir misralardan ibarətdir.",
  ["Misralardan", "Cədvəllərdən", "Rəqəmlərdən", "Xəritələrdən"],
  1, None, 2),
 ("Mətn: «Tural topu atdı. Top qapıya dəydi.» Top haraya dəydi?",
  "Mətndə deyilir: top qapıya dəydi.",
  ["Qapıya", "Pəncərəyə", "Divara", "Ağaca"], 1, None, 1),
 ("Oxuduğunu yaxşı anlamaq üçün necə oxumaq lazımdır?",
  "Diqqətlə, tələsmədən oxumaq lazımdır.",
  ["Diqqətlə, tələsmədən", "Çox sürətlə", "Sözləri ötürərək",
   "Yalnız şəkillərə baxaraq"], 1, None, 2),
 ("Tapmacanın cavabını tapın: «Qışda yağar, hər yeri ağ edər».",
  "Qışda yağan və hər yeri ağardan qardır.",
  ["Qar", "Yağış", "Külək", "Duman"], 1, None, 2),
 ("«Kitab bilik mənbəyidir» cümləsi nə haqqındadır?",
  "Cümlə kitabın faydasından danışır.",
  ["Kitab haqqında", "Oyun haqqında", "Hava haqqında",
   "Yemək haqqında"], 1, None, 2),
 ("Nağıllarda tülkü adətən necə təsvir olunur?",
  "Nağıllarda tülkü hiyləgər obrazdır.",
  ["Hiyləgər", "Qorxaq", "Tənbəl", "Güclü"], 1, None, 3),
 ("Kitabın üz qabığında adətən nə yazılır?",
  "Üz qabığında kitabın adı və müəllifi göstərilir.",
  ["Kitabın adı", "Qiymətlər cədvəli", "Hava proqnozu",
   "Riyazi misallar"], 1, None, 2),
 ("Mətn: «Nərmin nənəsinə kömək etdi. Nənəsi ona təşəkkür etdi.» "
  "Nənə niyə təşəkkür etdi?",
  "Nərmin kömək etdiyi üçün nənə təşəkkür etdi.",
  ["Nərmin kömək etdiyi üçün", "Nərmin mahnı oxuduğu üçün",
   "Nərmin şəkil çəkdiyi üçün", "Səbəbsiz"], 1, None, 3),
],
# ===================== HEYAT BILGISI 1 ================================
"hey-1-men-kimem": [
 ("Yaşadığımız ölkənin adı nədir?",
  "Bizim ölkəmiz Azərbaycandır.",
  ["Azərbaycan", "Türkiyə", "Gürcüstan", "İran"], 1, None, 1),
 ("Azərbaycanın paytaxtı hansı şəhərdir?",
  "Paytaxtımız Bakı şəhəridir.",
  ["Bakı", "Gəncə", "Sumqayıt", "Şəki"], 1, None, 1),
 ("Ailənin üzvləri kimlərdir?",
  "Ailə ata, ana və uşaqlardan ibarətdir.",
  ["Ata, ana və uşaqlar", "Yalnız qonşular",
   "Sinif yoldaşları", "Müəllimlər"], 1, None, 1),
 ("Məktəbdə bizə dərs deyən şəxs kimdir?",
  "Dərsi müəllim keçir.",
  ["Müəllim", "Həkim", "Sürücü", "Aşpaz"], 1, None, 1),
 ("Dövlət bayrağımızda neçə rəng var?",
  "Bayrağımız üçrənglidir.",
  ["3", "2", "4", "5"], 1, None, 2),
 ("Bayrağımızın rəngləri hansılardır?",
  "Bayrağımız mavi, qırmızı və yaşıl zolaqlardan ibarətdir.",
  ["Mavi, qırmızı, yaşıl", "Ağ, qırmızı, qara",
   "Sarı, yaşıl, göy", "Qırmızı, ağ, mavi"], 1, None, 2),
 ("Salamlaşmaq nəyin əlamətidir?",
  "Salam vermək nəzakətli davranışdır.",
  ["Nəzakətin", "Qorxunun", "Tənbəlliyin", "Acığın"], 1, None, 1),
 ("Dərsə necə gəlmək lazımdır?",
  "Dərsə vaxtında gəlmək intizamın əlamətidir.",
  ["Vaxtında", "Gecikərək", "İstənilən vaxt", "Günortadan sonra"],
  1, None, 2),
 ("Böyüklərlə necə danışmalıyıq?",
  "Böyüklərlə hörmətlə danışmaq lazımdır.",
  ["Hörmətlə", "Qışqıraraq", "Sözünü kəsərək", "Üz döndərərək"],
  1, None, 1),
 ("Sinifdə cavab vermək istəyəndə nə etməliyik?",
  "Əl qaldırıb icazə gözləmək lazımdır.",
  ["Əl qaldırmalıyıq", "Yerimizdən qışqırmalıyıq",
   "Ayağa qalxıb qaçmalıyıq", "Partanı döyməliyik"], 1, None, 2),
],
"hey-1-saglamliq": [
 ("İnsan ətrafı hansı orqanla görür?",
  "Görmə orqanımız gözdür.",
  ["Gözlə", "Qulaqla", "Burunla", "Əllə"], 1, None, 1),
 ("Qulaqlar nə üçündür?",
  "Qulaq eşitmə orqanıdır.",
  ["Eşitmək üçün", "Görmək üçün", "Dadmaq üçün",
   "İy hiss etmək üçün"], 1, None, 1),
 ("Yatmazdan əvvəl dişlərimizlə nə etməliyik?",
  "Axşam dişləri fırçalamaq lazımdır.",
  ["Fırçalamalıyıq", "Heç nə etməməliyik", "Konfet yeməliyik",
   "Yalnız su içməliyik"], 1, None, 1),
 ("Çöldən evə gələndə ilk növbədə nə etməliyik?",
  "Bayırdan gələndə əllər sabunla yuyulmalıdır.",
  ["Əllərimizi yumalıyıq", "Dərhal yemək yeməliyik",
   "Televizora baxmalıyıq", "Yatmalıyıq"], 1, None, 1),
 ("Hansı qida sağlamlıq üçün faydalıdır?",
  "Meyvə vitaminlərlə zəngindir.",
  ["Meyvə", "Çips", "Qazlı içki", "Çoxlu konfet"], 1, None, 1),
 ("Bədənimizi təmiz saxlamaq üçün nədən istifadə edirik?",
  "Təmizlik üçün su və sabun lazımdır.",
  ["Su və sabundan", "Yalnız ətirdən", "Tozdan", "Heç nədən"],
  1, None, 2),
 ("İy hiss etmə orqanımız hansıdır?",
  "Qoxunu burunla hiss edirik.",
  ["Burun", "Göz", "Qulaq", "Dil"], 1, None, 2),
 ("Dırnaqları niyə vaxtında kəsmək lazımdır?",
  "Uzun dırnağın altına mikroblar yığılır.",
  ["Altına mikrob yığılmasın deyə", "Gözəl görünmək üçün yox",
   "Heç bir səbəb yoxdur", "Dırnaq kəsilməz"], 1, None, 2),
 ("Gecə yuxusu insana nə verir?",
  "Yuxu zamanı bədən istirahət edib güc toplayır.",
  ["İstirahət və güc", "Yorğunluq", "Xəstəlik", "Aclıq"],
  1, None, 2),
 ("Səhər yeməyini ötürmək düzgündürmü?",
  "Səhər yeməyi günə güclə başlamaq üçün vacibdir.",
  ["Düzgün deyil — səhər yeməyi vacibdir", "Düzgündür",
   "Fərqi yoxdur", "Yalnız yayda düzgündür"], 1, None, 3),
],
"hey-1-insanlar-esyalar": [
 ("Stəkan adətən hansı materialdan hazırlanır?",
  "Stəkan şüşədən hazırlanır.",
  ["Şüşədən", "Kağızdan", "Parçadan", "Pambıqdan"], 1, None, 1),
 ("Dəftər və kitab hansı materialdan hazırlanır?",
  "Dəftər və kitab kağızdan hazırlanır.",
  ["Kağızdan", "Dəmirdən", "Şüşədən", "Daşdan"], 1, None, 1),
 ("Hansı əşya taxtadan hazırlanır?",
  "Stul adətən taxtadan düzəldilir.",
  ["Stul", "Stəkan", "Corab", "Qazan"], 1, None, 1),
 ("Paltarlarımız nədən tikilir?",
  "Paltar parçadan tikilir.",
  ["Parçadan", "Şüşədən", "Daşdan", "Kağızdan"], 1, None, 1),
 ("Soyuducu nə üçündür?",
  "Soyuducu qidaları təzə və soyuq saxlayır.",
  ["Qidaları soyuq saxlamaq üçün", "Paltar yumaq üçün",
   "Otağı qızdırmaq üçün", "Musiqi dinləmək üçün"], 1, None, 1),
 ("Paltarları hansı məişət avadanlığı yuyur?",
  "Paltarları paltaryuyan maşın yuyur.",
  ["Paltaryuyan maşın", "Soyuducu", "Televizor", "Ütü"],
  1, None, 2),
 ("Dayanan topu itələsək, nə baş verər?",
  "İtələnən əşya hərəkətə gəlir.",
  ["Hərəkət edər", "Yerində qalar", "Yox olar", "Böyüyər"],
  1, None, 2),
 ("Ölkəmizdə insanlar əsasən hansı dildə danışır?",
  "Dövlət dilimiz Azərbaycan dilidir.",
  ["Azərbaycan dilində", "İngilis dilində",
   "Fransız dilində", "Ərəb dilində"], 1, None, 2),
 ("Şüşə əşyalarla necə davranmaq lazımdır?",
  "Şüşə tez sınır — ehtiyatlı olmaq lazımdır.",
  ["Ehtiyatla", "Ataraq", "Döyəcləyərək", "Fərqi yoxdur"],
  1, None, 2),
 ("Yoldaşınla oyuncaqları necə oynamaq düzgündür?",
  "Oyuncaqları bölüşmək, növbə ilə oynamaq lazımdır.",
  ["Bölüşərək, növbə ilə", "Heç kimə verməyərək",
   "Əlindən alaraq", "Gizlədərək"], 1, None, 2),
],
"hey-1-etraf-muhit": [
 ("Bir ildə neçə fəsil var?",
  "Fəsillər dörddür: yaz, yay, payız, qış.",
  ["4", "3", "5", "12"], 1, None, 1),
 ("Qar adətən hansı fəsildə yağır?",
  "Qar qışda yağır.",
  ["Qışda", "Yayda", "Yazda", "Payızda"], 1, None, 1),
 ("Yayda hava adətən necə olur?",
  "Yay ilin ən isti fəslidir.",
  ["İsti", "Soyuq", "Şaxtalı", "Qarlı"], 1, None, 1),
 ("Payızda ağacların yarpaqları nə edir?",
  "Payızda yarpaqlar saralıb tökülür.",
  ["Saralıb tökülür", "Göyərir", "Çiçək açır", "Böyüyür"],
  1, None, 1),
 ("Hansı varlıq canlıdır?",
  "Ağac böyüyür, qidalanır — canlıdır.",
  ["Ağac", "Daş", "Qum", "Dəmir"], 1, None, 2),
 ("Canlılar yaşamaq üçün nəyə möhtacdır?",
  "Canlılara su, hava və qida lazımdır.",
  ["Su, hava və qidaya", "Yalnız oyuncağa", "Televizora",
   "Heç nəyə"], 1, None, 2),
 ("Hansı varlıq cansızdır?",
  "Daş böyümür, qidalanmır — cansızdır.",
  ["Daş", "Quş", "Balıq", "Gül"], 1, None, 2),
 ("Yağışdan sonra göydə bəzən nə görünür?",
  "Günəş çıxanda göy qurşağı görünə bilər.",
  ["Göy qurşağı", "Qar dənələri", "Ulduzlar", "Ay"], 1, None, 2),
 ("Küləyin əsdiyini nədən bilirik?",
  "Külək əsəndə budaqlar yellənir.",
  ["Ağac budaqlarının yellənməsindən", "Günəşin çıxmasından",
   "Qarın əriməsindən", "Gecənin düşməsindən"], 1, None, 3),
 ("Yazda təbiətdə nə baş verir?",
  "Yazda hava istiləşir, ağaclar çiçək açır.",
  ["Ağaclar çiçək açır", "Yarpaqlar tökülür",
   "Çaylar donur", "Günlər qısalır"], 1, None, 2),
],
"hey-1-ehtiyat": [
 ("Yolu keçməzdən əvvəl əvvəlcə hansı tərəfə baxmaq lazımdır?",
  "Əvvəl sola, yolun ortasında sağa baxılır.",
  ["Sola", "Sağa", "Yuxarı", "Arxaya"], 1, None, 2),
 ("Yol üzərindəki ağ zolaqlar («zebra») nə üçündür?",
  "Zebra piyadaların yolu keçdiyi yerdir.",
  ["Piyadaların yol keçməsi üçün", "Maşınların dayanması üçün",
   "Oyun oynamaq üçün", "Bəzək üçün"], 1, None, 1),
 ("Svetoforun qırmızı işığı piyadaya nə deyir?",
  "Qırmızı işıq «dayan» deməkdir.",
  ["Dayan", "Keç", "Qaç", "Hazırlaş"], 1, None, 1),
 ("Yanğın zamanı hansı nömrəyə zəng edilir?",
  "Yanğınsöndürmə xidmətinin nömrəsi 101-dir.",
  ["101", "102", "103", "104"], 1, None, 2),
 ("Təcili tibbi yardımın nömrəsi hansıdır?",
  "Təcili tibbi yardım 103 nömrəsi ilə çağırılır.",
  ["103", "101", "102", "105"], 1, None, 2),
 ("Hansı nəqliyyat vasitəsidir?",
  "Avtobus sərnişin daşıyan nəqliyyat vasitəsidir.",
  ["Avtobus", "Stol", "Kitab", "Ağac"], 1, None, 1),
 ("Avtobusda özümüzü necə aparmalıyıq?",
  "Sakit dayanıb tutacaqdan tutmaq lazımdır.",
  ["Sakit dayanıb tutacaqdan tutmalıyıq", "Qaçıb oynamalıyıq",
   "Pəncərədən sallanmalıyıq", "Qışqırmalıyıq"], 1, None, 2),
 ("Evdə tək olanda tanımadığın adam qapını döysə, nə etməlisən?",
  "Qapını açmamaq və böyüklərə xəbər vermək lazımdır.",
  ["Qapını açmamalıyam", "Qapını dərhal açmalıyam",
   "Onunla söhbət etməliyəm", "Evə dəvət etməliyəm"], 1, None, 2),
 ("Sel təhlükəsi olanda hara getmək lazımdır?",
  "Sel zamanı hündür yerə qalxmaq lazımdır.",
  ["Hündür yerə", "Çaya yaxın yerə", "Zirzəmiyə", "Körpünün altına"],
  1, None, 3),
 ("Top oynamaq üçün təhlükəsiz yer haradır?",
  "Yoldan uzaq həyət meydançası təhlükəsizdir.",
  ["Həyət meydançası", "Yolun kənarı", "Maşın dayanacağı",
   "Körpünün üstü"], 1, None, 1),
],
# ======================= INFORMATIKA 1 ================================
"inf-1-esyalar": [
 ("Almanı təsvir edərkən onun hansı əlamətlərini deyirik?",
  "Əşya rənginə, formasına, ölçüsünə görə təsvir olunur.",
  ["Rəngini, formasını, ölçüsünü", "Yalnız qiymətini",
   "Yalnız adını", "Yalnız yerini"], 1, None, 2),
 ("Əşyanın forması dedikdə nəyi nəzərdə tuturuq?",
  "Forma — əşyanın yumru, dördkünc və s. olmasıdır.",
  ["Yumru və ya dördkünc olmasını", "Rəngini",
   "Qoxusunu", "Səsini"], 1, None, 2),
 ("İki əşyanı müqayisə edəndə nəyi tapırıq?",
  "Müqayisədə oxşar və fərqli cəhətlər tapılır.",
  ["Oxşar və fərqli cəhətləri", "Yalnız qiyməti",
   "Yalnız çəkini", "Heç nəyi"], 1, None, 2),
 ("Kitab rəfin yuxarısında, top rəfin aşağısındadır. Yuxarıda nə var?",
  "Yuxarıdakı əşya kitabdır.",
  ["Kitab", "Top", "Rəf", "Heç nə"], 1, None, 1),
 ("«Sağ» tərəfin əksi hansı tərəfdir?",
  "Sağın əksi soldur.",
  ["Sol", "Yuxarı", "Aşağı", "Ön"], 1, None, 1),
 ("Maşının hansı hissəsi onu hərəkət etdirir?",
  "Maşın təkərlər üzərində hərəkət edir.",
  ["Təkərləri", "Pəncərəsi", "Oturacağı", "Rəngi"], 1, None, 2),
 ("Hansı iki əşya formasına görə oxşardır?",
  "Top da, qarpız da yumrudur.",
  ["Top və qarpız", "Kitab və top", "Qələm və boşqab",
   "Stul və alma"], 1, None, 2),
 ("Qələm və karandaşın oxşar cəhəti nədir?",
  "Hər ikisi yazı yazmaq üçündür.",
  ["Hər ikisi yazmaq üçündür", "Hər ikisi yeyiləndir",
   "Hər ikisi geyimdir", "Oxşarlıqları yoxdur"], 1, None, 1),
 ("Fil, it və siçanı böyüklüyünə görə düzsək, birinci hansı olar?",
  "Ən böyük heyvan fildir.",
  ["Fil", "İt", "Siçan", "Hamısı eynidir"], 1, None, 2),
 ("Şagird lövhəyə üzü dayanıb. Lövhə şagirdə görə hansı tərəfdədir?",
  "Üzü lövhəyə duran adam üçün lövhə öndədir.",
  ["Öndə", "Arxada", "Sağda", "Solda"], 1, None, 3),
],
"inf-1-ardicilliq": [
 ("Hadisələri düzgün sıralayın: toxum əkilir → ? → meyvə yığılır.",
  "Toxum əkiləndən sonra bitki böyüyür, sonra meyvə yığılır.",
  ["Bitki böyüyür", "Meyvə satılır", "Qış gəlir", "Toxum atılır"],
  1, None, 2),
 ("Çay dəmləmək üçün əvvəlcə nə etmək lazımdır?",
  "Əvvəlcə çaynikə su töküb qaynatmaq lazımdır.",
  ["Su qaynatmaq", "Stəkana süd tökmək", "Çayı içmək",
   "Stəkanı yumaq"], 1, None, 2),
 ("«Gündüz» sözünün əksi nədir?",
  "Gündüzün əksi gecədir.",
  ["Gecə", "Səhər", "Axşam", "Günorta"], 1, None, 1),
 ("«Balıqlar havada uçur» fikri doğrudur, yoxsa yalan?",
  "Balıqlar suda üzür — fikir yalandır.",
  ["Yalandır", "Doğrudur", "Bəzən doğrudur", "Bilmək olmaz"],
  1, None, 1),
 ("«Qış soyuq fəsildir» fikri necə fikirdir?",
  "Qış həqiqətən soyuqdur — fikir doğrudur.",
  ["Doğrudur", "Yalandır", "Nə doğru, nə yalan", "Sualdır"],
  1, None, 1),
 ("Əvvəl ayaqqabı, sonra corab geyinmək — bu ardıcıllıq necədir?",
  "Ardıcıllıq pozulub: əvvəl corab, sonra ayaqqabı geyinilir.",
  ["Səhvdir — əvvəl corab geyinilir", "Düzgündür",
   "Fərqi yoxdur", "Hər ikisi eyni vaxtda geyinilir"], 1, None, 2),
 ("Günün hissələrini düzgün ardıcıllıqla düzün.",
  "Ardıcıllıq: səhər, günorta, axşam, gecə.",
  ["Səhər, günorta, axşam, gecə", "Gecə, günorta, səhər, axşam",
   "Axşam, səhər, gecə, günorta", "Günorta, gecə, səhər, axşam"],
  1, None, 2),
 ("Yumurtadan hansı canlı çıxır?",
  "Toyuğun yumurtasından cücə çıxır.",
  ["Cücə", "Bala pişik", "Buzov", "Dovşan"],
  1, None, 1),
 ("Hansı cüt əks əlamətləri göstərir?",
  "Uzun və qısa bir-birinin əksidir.",
  ["uzun — qısa", "uzun — hündür", "qısa — balaca", "isti — ilıq"],
  1, None, 2),
 ("Əl yumanın addımlarını sıralayın: 1) əlləri sabunla, 2) kranı aç, "
  "3) dəsmalla qurula.",
  "Düzgün sıra: kranı aç, sabunla, qurula — 2, 1, 3.",
  ["2, 1, 3", "1, 2, 3", "3, 2, 1", "1, 3, 2"], 1, None, 3),
],
"inf-1-informasiya": [
 ("Ətrafımızdan aldığımız xəbər və məlumatlar necə adlanır?",
  "Aldığımız məlumatlar informasiya adlanır.",
  ["İnformasiya", "Oyun", "İdman", "Yemək"], 1, None, 1),
 ("Televizor bizə nə çatdırır?",
  "Televizor xəbər və verilişlər — informasiya çatdırır.",
  ["İnformasiya", "Yemək", "Paltar", "Oyuncaq"], 1, None, 1),
 ("Şəkildəki informasiyanı hansı orqanla qəbul edirik?",
  "Şəkilə baxırıq — gözlə qəbul edirik.",
  ["Gözlə", "Qulaqla", "Burunla", "Dillə"], 1, None, 1),
 ("Telefonun zəng səsi bizə nə bildirir?",
  "Zəng səsi kiminsə zəng etdiyini xəbər verir.",
  ["Kiminsə zəng etdiyini", "Yağış yağacağını",
   "Yeməyin hazır olduğunu", "Heç nəyi"], 1, None, 2),
 ("İnformasiyanı başqasına hansı yollarla çatdırmaq olar?",
  "Danışmaqla, yazmaqla, şəkil çəkməklə çatdırmaq olar.",
  ["Danışmaqla, yazmaqla, şəkillə", "Yalnız yatmaqla",
   "Yalnız qaçmaqla", "Heç cür"], 1, None, 2),
 ("Yol nişanları sürücülərə nəyi bildirir?",
  "Yol nişanları yol qaydaları haqqında məlumat verir.",
  ["Yol qaydalarını", "Hava proqnozunu", "Mağaza qiymətlərini",
   "Futbol nəticələrini"], 1, None, 2),
 ("Kitabdan informasiyanı necə alırıq?",
  "Kitabı oxuyaraq məlumat alırıq.",
  ["Oxumaqla", "İyləməklə", "Silkələməklə", "Dadmaqla"],
  1, None, 1),
 ("Radio informasiyanı hansı formada çatdırır?",
  "Radionu dinləyirik — informasiya səslə gəlir.",
  ["Səslə", "Şəkillə", "Yazı ilə", "Qoxu ilə"], 1, None, 2),
 ("Sabahkı hava haqqında məlumatı haradan öyrənmək olar?",
  "Hava proqnozu havanı qabaqcadan bildirir.",
  ["Hava proqnozundan", "Yemək kitabından", "Xəritədən",
   "Riyaziyyat dərsliyindən"], 1, None, 2),
 ("Müəllimin danışdığını hansı orqanla qəbul edirik?",
  "Danışığı qulaqla eşidirik.",
  ["Qulaqla", "Gözlə", "Əllə", "Burunla"], 1, None, 1),
],
"inf-1-kompyuter": [
 ("Kompüterin ekranlı hissəsi necə adlanır?",
  "Ekranı olan qurğu monitordur.",
  ["Monitor", "Klaviatura", "Maus", "Printer"], 1, None, 1),
 ("Üzərində hərf və rəqəm düymələri olan qurğu hansıdır?",
  "Hərf və rəqəmlər klaviaturanın düymələrindədir.",
  ["Klaviatura", "Monitor", "Dinamik", "Kamera"], 1, None, 1),
 ("Kompüterdə şəkil çəkərkən ən çox hansı qurğudan istifadə olunur?",
  "Şəkil çəkmə proqramında maus ilə çəkirik.",
  ["Mausdan", "Printerdən", "Dinamikdən", "Mikrofondan"],
  1, None, 2),
 ("Kompüterdə hesablama aparmaq üçün hansı proqramdan istifadə "
  "etmək olar?",
  "Kalkulyator proqramı hesablama aparır.",
  ["Kalkulyatordan", "Şəkil çəkmə proqramından",
   "Musiqi pleyerindən", "Saatdan"], 1, None, 2),
 ("Kompüteri işə salmaq üçün nə edirik?",
  "Qoşma düyməsini basırıq.",
  ["Qoşma düyməsini basırıq", "Ekranı silkələyirik",
   "Üstünə su tökürük", "Gözləyirik"], 1, None, 1),
 ("Kompüterə ən çox nə zərər verə bilər?",
  "Su və digər mayelər kompüteri sıradan çıxarır.",
  ["Üstünə tökülən su", "Təmiz stol", "Sərin otaq",
   "Səliqəli istifadə"], 1, None, 2),
 ("Kompüterdə çox oturanda gözlərimiz nə edir?",
  "Ekrana uzun baxanda gözlər yorulur.",
  ["Yorulur", "Güclənir", "Dəyişmir", "Daha iti görür"],
  1, None, 2),
 ("Kompüterdə çəkdiyimiz şəkli harada görürük?",
  "Çəkdiyimiz şəkil ekranda (monitorda) görünür.",
  ["Ekranda", "Klaviaturada", "Mausda", "Naqildə"], 1, None, 1),
 ("Kompüter oyunlarını nə qədər oynamaq düzgündür?",
  "Oyun vaxtı məhdud olmalıdır — gözlər və bədən yorulmasın.",
  ["Müəyyən olunmuş qədər, az", "Bütün günü", "Gecə boyu",
   "Dayanmadan"], 1, None, 2),
 ("Maus düyməsini bir dəfə basmaq necə adlanır?",
  "Maus düyməsini basmaq klik adlanır.",
  ["Klik", "Yazı", "Çap", "Zəng"], 1, None, 3),
],
}


def yoxla():
    n = xeta = 0
    butun = set()
    movzu_fenn = {m: f for f, m, _r in MOVZULAR}
    for movzu, siyahi in SUALLAR.items():
        assert movzu in movzu_fenn, movzu
        if len(siyahi) != 10:
            print("XETA  %s: %d sual (10 olmalidir)" % (movzu, len(siyahi)))
            xeta += 1
        for body, why, opts, correct, expect, diff in siyahi:
            n += 1
            p = []
            if len(opts) != 4: p.append("variant sayi %d" % len(opts))
            if len(set(opts)) != len(opts): p.append("tekrar variant")
            if not (1 <= correct <= 4): p.append("correct")
            if not why: p.append("izah bos")
            if diff not in (1, 2, 3): p.append("cetinlik")
            if body in butun: p.append("eyni sual iki defe")
            butun.add(body)
            if expect is not None and opts[correct - 1] != expect:
                p.append("hesablanan «%s» != variant «%s»" % (expect, opts[correct - 1]))
            for t in [body, why] + opts:
                if "'" in t: p.append("apostrof var")
            if p:
                xeta += 1
                print("XETA  %s: %s\n      %s" % (movzu, body[:60], "; ".join(p)))
    hes = sum(1 for s in SUALLAR.values() for q in s if q[4] is not None)
    print("%d sual yoxlandı (%d-i hesabla təsdiqləndi), %d xəta" % (n, hes, xeta))
    return xeta == 0, n


def sql_yaz(n):
    q = lambda t: t.replace("'", "''")
    on = {"riyaziyyat": "riy1", "az-dili": "az1",
          "hayat-bilgisi": "hey1", "informatika": "inf1"}
    setirler = []
    for fenn, movzu, rub in MOVZULAR:
        qisa = movzu.split("-", 2)[2]
        for i, (body, why, opts, correct, _e, diff) in enumerate(SUALLAR[movzu], 1):
            setirler.append(
                "('%s-%s#%d','%s','%s',%d,%d,'%s','%s',array['%s','%s','%s','%s'],%d)"
                % (on[fenn], qisa, i, fenn, movzu, diff, rub, q(body), q(why),
                   q(opts[0]), q(opts[1]), q(opts[2]), q(opts[3]), correct))
    with io.open(CIXIS, "w", encoding="utf-8") as f:
        f.write("""-- =====================================================================
--  23_bank_sinif1.sql : 1-CI SINIF PLATFORMA SUAL BANKI
--
--  BU FAYL ELLE YAZILMIR - tools/sinif1.py yaradir:
--      python3 tools/sinif1.py
--
--  Riyaziyyat 12 + Az dili 6 + Heyat bilgisi 5 + Informatika 4
--  = 27 movzu x 10 = %d.  ext_key: riy1-/az1-/hey1-/inf1-...
--  ON SERT: 14_movzular.sql ve 15_movzular_ederslik.sql islenmis olmalidir.
--  SONRA:   05_grants.sql yeniden islet.
-- =====================================================================

do $$
begin
  if not exists (select 1 from public.topics t join public.subjects s
      on s.id = t.subject_id
     where (s.slug, t.slug) in (('riyaziyyat','riy-1-elamet'),
                                ('az-dili','az-1-heca'),
                                ('hayat-bilgisi','hey-1-etraf-muhit'),
                                ('informatika','inf-1-esyalar'))
     having count(*) = 4) then
    raise exception 'ONCE 14_movzular.sql ve 15_movzular_ederslik.sql isledilmelidir.';
  end if;
end $$;

delete from public.question_options o
 using public.questions q
 where o.question_id = q.id
   and q.owner_type = 'platform'
   and (q.ext_key like 'riy1-%%' or q.ext_key like 'az1-%%'
        or q.ext_key like 'hey1-%%' or q.ext_key like 'inf1-%%');

with d(ext, fenn, topic, diff, rub, body, why, opts, correct) as (values
%s
),
ins as (
  insert into public.questions
    (ext_key, owner_type, subject_id, level_id, topic_id, kind,
     body, explanation, difficulty, quarter, status)
  select d.ext, 'platform', s.id, l.id, tp.id, 'single',
         d.body, d.why, d.diff, d.rub, 'published'
    from d
    join public.subjects s on s.slug = d.fenn
    join public.programs p on p.slug = 'ibtidai'
    join public.levels   l on l.program_id = p.id and l.code = '1'
    join public.topics   tp on tp.subject_id = s.id and tp.slug = d.topic
  on conflict (ext_key) do update
    set body = excluded.body, explanation = excluded.explanation,
        difficulty = excluded.difficulty, quarter = excluded.quarter,
        topic_id = excluded.topic_id, level_id = excluded.level_id,
        subject_id = excluded.subject_id, status = 'published'
  returning id, ext_key
)
insert into public.question_options (question_id, ord, body, is_correct)
select ins.id, o.ord, o.txt, o.ord = d.correct
  from ins
  join d on d.ext = ins.ext_key,
  lateral unnest(d.opts) with ordinality as o(txt, ord);

do $$
declare n int; k int;
begin
  select count(*) into n from public.questions
   where owner_type = 'platform'
     and (ext_key like 'riy1-%%' or ext_key like 'az1-%%'
          or ext_key like 'hey1-%%' or ext_key like 'inf1-%%');
  if n <> %d then
    raise exception 'sinif1 suallari: %d gozlenilirdi, %% tapildi', n;
  end if;
  select count(*) into k from public.questions q
   where (q.ext_key like 'riy1-%%' or q.ext_key like 'az1-%%'
          or q.ext_key like 'hey1-%%' or q.ext_key like 'inf1-%%')
     and ((select count(*) from public.question_options o
            where o.question_id = q.id) <> 4
       or (select count(*) from public.question_options o
            where o.question_id = q.id and o.is_correct) <> 1);
  if k > 0 then
    raise exception '%% sualda variant qurulusu sehvdir', k;
  end if;
  select count(distinct topic_id) into k from public.questions
   where ext_key like 'riy1-%%' or ext_key like 'az1-%%'
      or ext_key like 'hey1-%%' or ext_key like 'inf1-%%';
  if k <> 27 then
    raise exception 'movzu sayi 27 deyil: %%', k;
  end if;
  raise notice '1-ci sinif banki: %% sual, 27 movzu (riy, az, hey, inf).', n;
end $$;
""" % (n, ",\n".join(setirler), n, n))
    print("yazildi: %s" % CIXIS)


if __name__ == "__main__":
    ok, n = yoxla()
    if not ok:
        raise SystemExit(1)
    sql_yaz(n)
