#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
7-ci sinfin humanitar fennleri -> db/35_bank_sinif7.sql

    Azerbaycan dili 7      8 movzu x 30 = 240
    Ingilis dili 7         6 movzu x 30 = 180
    Informatika 7          5 movzu x 20 = 100
    Umumi tarix 7          6 movzu x 30 = 180
                                    cemi  700

tools/sinif6.py qelibi ile.  Movzular 33_movzular_orta7.sql agacina
uygundur.  Az dili suallari 7-ci sinif qrammatikasi (feilin zamanlari
ve sekilleri, zerf, komekci nitq hisseleri, uslub), ingilis dili
derslik unitlerine uygundur.  Say sistemi suallari int(x, 2) ile
hesablanir.  Tarix suallari subhesiz derslik faktlaridir (Roma 476,
Konstantinopol 1453, Kolumb 1492, Qutenberq).

Isletmek:
    python3 tools/sinif7.py
"""
import io
import os

KOK = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CIXIS = os.path.join(KOK, "db", "35_bank_sinif7.sql")

#  (fenn, movzu-slug, rub)
MOVZULAR = [
    ("az-dili", "az-7-feil-zaman",      1),
    ("az-dili", "az-7-feil-sekil",      1),
    ("az-dili", "az-7-feil-qurulus",    2),
    ("az-dili", "az-7-zerf",            2),
    ("az-dili", "az-7-qosma-baglayici", 3),
    ("az-dili", "az-7-edat-modal",      3),
    ("az-dili", "az-7-nida",            4),
    ("az-dili", "az-7-uslub",           4),
    ("ingilis-dili", "ing-7-schools",    1),
    ("ingilis-dili", "ing-7-technology", 1),
    ("ingilis-dili", "ing-7-talent",     2),
    ("ingilis-dili", "ing-7-travel",     2),
    ("ingilis-dili", "ing-7-friends",    3),
    ("ingilis-dili", "ing-7-future",     4),
    ("informatika", "inf-7-kompyuter",       1),
    ("informatika", "inf-7-tetbiqi",         2),
    ("informatika", "inf-7-informasiya",     3),
    ("informatika", "inf-7-proqramlasdirma", 3),
    ("informatika", "inf-7-internet",        4),
]

SUALLAR = {
# ===================== AZERBAYCAN DILI 7 ==============================
"az-7-feil-zaman": [
 ("Feilin neçə zamanı var?",
  "Üç zaman: keçmiş, indiki, gələcək.",
  ["3", "2", "6", "4"], 1, None, 1),
 ("«Oxuyur» feili hansı zamandadır?",
  "-ur şəkilçisi indiki zamanı bildirir.",
  ["İndiki", "Keçmiş", "Gələcək", "Zaman bildirmir"],
  1, None, 1),
 ("İndiki zamanın şəkilçiləri hansılardır?",
  "İndiki zaman: -ır, -ir, -ur, -ür.",
  ["-ır, -ir, -ur, -ür", "-dı, -di", "-acaq, -əcək",
   "-mış, -miş"], 1, None, 2),
 ("«Gedəcəyik» feilində zaman və şəxs hansıdır?",
  "-əcək gələcək zaman, -ik I şəxsin cəmi.",
  ["Gələcək zaman, I şəxs cəm", "Keçmiş zaman, II şəxs tək",
   "İndiki zaman, III şəxs", "Zaman yoxdur"], 1, None, 3),
 ("Şühudi keçmiş zaman hansı şəkilçi ilə düzəlir?",
  "Şühudi keçmiş: -dı, -di, -du, -dü.",
  ["-dı, -di, -du, -dü", "-mış, -miş", "-ır, -ir",
   "-ar, -ər"], 1, None, 2),
 ("Nəqli keçmiş zamanın şəkilçisi hansıdır?",
  "Nəqli keçmiş: -mış, -miş, -muş, -müş.",
  ["-mış, -miş, -muş, -müş", "-dı, -di", "-sa, -sə",
   "-malı, -məli"], 1, None, 2),
 ("«Yazmışam» feili hansı keçmiş zamandadır?",
  "-mış şəkilçisi nəqli keçmişi bildirir.",
  ["Nəqli keçmiş", "Şühudi keçmiş", "İndiki", "Gələcək"],
  1, None, 3),
 ("Qeyri-qəti gələcək zaman hansı şəkilçi ilə düzəlir?",
  "Qeyri-qəti gələcək: -ar, -ər.",
  ["-ar, -ər", "-acaq, -əcək", "-ır, -ir", "-dı, -di"],
  1, None, 3),
 ("«Gələr» feili hansı zamandadır?",
  "-ər şəkilçisi qeyri-qəti gələcəyi bildirir.",
  ["Qeyri-qəti gələcək", "Qəti gələcək", "İndiki",
   "Şühudi keçmiş"], 1, None, 3),
 ("Feil zamana görə nəyə əsasən dəyişir?",
  "Hərəkətin icra vaxtına görə dəyişir.",
  ["Hərəkətin icra vaxtına görə", "Sözün uzunluğuna görə",
   "Hecaların sayına görə", "Cümlənin yerinə görə"],
  1, None, 2),
],
"az-7-feil-sekil": [
 ("Feilin neçə şəkli var?",
  "Altı şəkil: xəbər, əmr, arzu, vacib, lazım, şərt.",
  ["6", "3", "4", "10"], 1, None, 2),
 ("«Yazsa» feili hansı şəkildədir?",
  "-sa şəkilçisi şərt şəklini bildirir.",
  ["Şərt", "Əmr", "Arzu", "Vacib"], 1, None, 2),
 ("Şərt şəklinin şəkilçisi hansıdır?",
  "Şərt şəkli -sa, -sə ilə düzəlir.",
  ["-sa, -sə", "-malı, -məli", "-a, -ə", "-ası, -əsi"],
  1, None, 2),
 ("«Oxumalıyam» feili hansı şəkildədir?",
  "-malı şəkilçisi vacib şəklini bildirir.",
  ["Vacib", "Lazım", "Arzu", "Şərt"], 1, None, 3),
 ("«Kaş yazaydım» cümləsindəki feil hansı şəkildədir?",
  "Arzu şəkli -a, -ə (+ ydı) ilə düzəlir, «kaş» sözü ilə işlənir.",
  ["Arzu", "Əmr", "Xəbər", "Şərt"], 1, None, 3),
 ("Əmr şəklində feil nəyi bildirir?",
  "Əmr, xahiş, məsləhət bildirir.",
  ["Əmri və xahişi", "Yalnız keçmişi", "Yalnız arzunu",
   "Şərti"], 1, None, 2),
 ("«Get!» feili hansı şəkildədir?",
  "Şəkilçisiz əmr forması II şəxsin təkinə aiddir.",
  ["Əmr", "Xəbər", "Lazım", "Vacib"], 1, None, 1),
 ("Vacib şəklinin şəkilçisi hansıdır?",
  "Vacib şəkli: -malı, -məli.",
  ["-malı, -məli", "-sa, -sə", "-ar, -ər", "-ıb, -ib"],
  1, None, 2),
 ("Lazım şəklinin şəkilçisi hansıdır?",
  "Lazım şəkli: -ası, -əsi.",
  ["-ası, -əsi", "-malı, -məli", "-a, -ə", "-dı, -di"],
  1, None, 3),
 ("Xəbər şəkli nəyi bildirir?",
  "Hərəkətin üç zamandan birində icrasını bildirir.",
  ["Hərəkətin zamanla icrasını", "Yalnız əmri",
   "Yalnız şərti", "Yalnız arzunu"], 1, None, 3),
],
"az-7-feil-qurulus": [
 ("Quruluşca sadə feil hansıdır?",
  "«Yaz» yalnız kökdən ibarətdir.",
  ["yaz", "yazdırmaq", "söz vermək", "başa düşmək"],
  1, None, 2),
 ("Düzəltmə feillər necə yaranır?",
  "Ad və feillərə leksik şəkilçi artırmaqla.",
  ["Şəkilçi artırmaqla", "Sözü təkrarlamaqla",
   "Vurğunu dəyişməklə", "Yaranmır"], 1, None, 2),
 ("«Başa düşmək» quruluşca hansı feildir?",
  "İki sözdən ibarətdir — mürəkkəb (tərkibi) feildir.",
  ["Mürəkkəb", "Sadə", "Düzəltmə", "Feil deyil"], 1, None, 3),
 ("«Gözləmək» feili hansı nitq hissəsindən düzəlib?",
  "«Göz» ismindən -lə şəkilçisi ilə düzəlib.",
  ["İsimdən", "Sifətdən", "Saydan", "Zərfdən"], 1, None, 3),
 ("Təsirli feil hansı sualı tələb edir?",
  "Təsirli feil «kimi? nəyi?» sualını tələb edir.",
  ["Kimi? Nəyi?", "Harada?", "Nə vaxt?", "Necə?"],
  1, None, 3),
 ("«Kitab oxudu» cümləsində «oxumaq» feili təsirli, yoxsa "
  "təsirsizdir?",
  "Nəyi oxudu? — obyekt tələb edir, təsirlidir.",
  ["Təsirli", "Təsirsiz", "Heç biri", "Köməkçi"], 1, None, 3),
 ("«Yatmaq» feili təsirlidir, yoxsa təsirsiz?",
  "Obyekt tələb etmir — təsirsizdir.",
  ["Təsirsiz", "Təsirli", "Hər ikisi", "Feil deyil"],
  1, None, 3),
 ("«Bilmək» feilinin inkar forması hansıdır?",
  "İnkar -mə şəkilçisi ilə: bilməmək.",
  ["bilməmək", "bilmək yox", "nabilmək", "bilməzlik"],
  1, None, 2),
 ("«Ağarmaq» feili hansı nitq hissəsindən düzəlib?",
  "«Ağ» sifətindən -ar şəkilçisi ilə düzəlib.",
  ["Sifətdən", "İsimdən", "Saydan", "Nidadan"], 1, None, 3),
 ("Feillər şəxsə görə dəyişirmi?",
  "Bəli, feillər şəxsə və kəmiyyətə görə təsriflənir.",
  ["Bəli, təsriflənir", "Xeyr, heç vaxt",
   "Yalnız cəmdə", "Yalnız keçmişdə"], 1, None, 2),
],
"az-7-zerf": [
 ("Zərfin məna növləri hansılardır?",
  "Tərzi-hərəkət, zaman, yer və miqdar zərfləri.",
  ["Tərzi-hərəkət, zaman, yer, miqdar", "Yalnız zaman",
   "Ad, əlamət, hərəkət", "Sadə və mürəkkəb"], 1, None, 2),
 ("«Astaca» sözü hansı zərf növüdür?",
  "Necə? — tərzi-hərəkət zərfidir.",
  ["Tərzi-hərəkət", "Zaman", "Yer", "Miqdar"], 1, None, 2),
 ("«İrəli» sözü hansı zərf növüdür?",
  "Haraya? — yer zərfidir.",
  ["Yer", "Zaman", "Miqdar", "Tərzi-hərəkət"], 1, None, 2),
 ("«Çox» sözü hansı zərf növünə aiddir?",
  "Nə qədər? — miqdar zərfidir.",
  ["Miqdar", "Yer", "Zaman", "Səbəb"], 1, None, 2),
 ("«Axşamüstü» sözü hansı zərf növüdür?",
  "Nə vaxt? — zaman zərfidir.",
  ["Zaman", "Yer", "Miqdar", "Tərzi-hərəkət"], 1, None, 2),
 ("Zərflər cümlədə əsasən hansı üzv olur?",
  "Zərflər cümlədə zərflik olur.",
  ["Zərflik", "Mübtəda", "Təyin", "Xəbər olmur"],
  1, None, 3),
 ("«Qaça-qaça» sözü hansı nitq hissəsidir?",
  "Necə? — tərzi-hərəkət zərfidir.",
  ["Zərf", "Feil", "İsim", "Qoşma"], 1, None, 3),
 ("Zərf əsasən hansı nitq hissəsi ilə bağlı olur?",
  "Zərf hərəkətin əlamətini bildirir — feillə bağlıdır.",
  ["Feillə", "Yalnız isimlə", "Bağlayıcı ilə", "Nida ilə"],
  1, None, 2),
 ("«Az-az» zərfi nəyi bildirir?",
  "Miqdar bildirir.",
  ["Miqdarı", "Yeri", "Zamanı", "Rəngi"], 1, None, 2),
 ("Hansı sırada yalnız zərflər verilib?",
  "Tez, gec, indi — hamısı zərfdir.",
  ["tez, gec, indi", "tez, qaçmaq, yol", "gec, gecə, gecikmək",
   "indi, in, san"], 1, None, 3),
],
"az-7-qosma-baglayici": [
 ("«Üçün» qoşması sözə necə yazılır?",
  "Qoşmalar əsasən ayrı yazılır: vətən üçün.",
  ["Ayrı", "Bitişik", "Defislə", "Dırnaqda"], 1, None, 2),
 ("«İlə» qoşması samitlə bitən sözlərdə necə işlənir?",
  "Qısalaraq -la, -lə şəklində bitişik yazılır: qatarla.",
  ["-la, -lə şəklində bitişik", "Həmişə ayrı",
   "Defislə", "İşlənmir"], 1, None, 3),
 ("Hansı söz tabesizlik bağlayıcısıdır?",
  "«Və» tabesizlik bağlayıcısıdır.",
  ["və", "çünki", "əgər", "ona görə ki"], 1, None, 2),
 ("«Çünki» bağlayıcısı hansı məna əlaqəsini bildirir?",
  "Səbəb bildirir.",
  ["Səbəb", "Şərt", "Zaman", "Məkan"], 1, None, 2),
 ("«Əgər» bağlayıcısı nə bildirir?",
  "Şərt bildirir.",
  ["Şərt", "Səbəb", "Nəticə", "Sadalanma"], 1, None, 2),
 ("«Həm … həm də» hansı bağlayıcı növüdür?",
  "İştirak bildirən tabesizlik bağlayıcısıdır.",
  ["İştirak bağlayıcısı", "Səbəb bağlayıcısı",
   "Qoşma", "Ədat"], 1, None, 3),
 ("Qoşma cümlədə necə iştirak edir?",
  "Qoşulduğu sözlə birlikdə bir üzv olur.",
  ["Qoşulduğu sözlə birlikdə üzv olur", "Ayrıca üzv olur",
   "Üzv olmur, atılır", "Yalnız xəbər olur"], 1, None, 3),
 ("«Bilirəm ki, gələcəksən» cümləsindəki «ki» nədir?",
  "«Ki» bağlayıcıdır və ayrı yazılır.",
  ["Bağlayıcı", "Qoşma", "Ədat kimi bitişik yazılır",
   "Şəkilçi"], 1, None, 3),
 ("«Doğru», «sarı» sözləri qoşma kimi hansı halda olan sözlərlə "
  "işlənir?",
  "Yönlük halla işlənir: evə doğru, dağa sarı.",
  ["Yönlük halda", "Yiyəlik halda", "Adlıq halda",
   "Çıxışlıq halda"], 1, None, 3),
 ("«Amma» bağlayıcısından əvvəl hansı durğu işarəsi qoyulur?",
  "Qarşılaşdırma bağlayıcısından əvvəl vergül qoyulur.",
  ["Vergül", "Nöqtə", "İki nöqtə", "Heç nə"], 1, None, 2),
],
"az-7-edat-modal": [
 ("Ədat hansı vəzifəni daşıyır?",
  "Sözün və cümlənin təsir gücünü artırır.",
  ["Mənanı qüvvətləndirir", "Əşya adlandırır",
   "Hərəkət bildirir", "Say bildirir"], 1, None, 2),
 ("«Ən» ədatı nə üçün işlənir?",
  "Əlamətin üstünlük dərəcəsini yaradır: ən gözəl.",
  ["Üstünlük dərəcəsi yaratmaq üçün", "Sual vermək üçün",
   "İnkar üçün", "Sadalamaq üçün"], 1, None, 2),
 ("«Məgər» sözü hansı ədat növünə aiddir?",
  "Sual ədatıdır.",
  ["Sual ədatı", "Əmr ədatı", "Məhdudlaşdırma",
   "Qüvvətləndirmə"], 1, None, 3),
 ("«Yalnız, ancaq, təkcə» ədatları nəyi bildirir?",
  "Məhdudlaşdırma bildirir.",
  ["Məhdudlaşdırma", "Sual", "Təsdiq", "İnkar"], 1, None, 3),
 ("Modal sözlər nəyi ifadə edir?",
  "Danışanın fikrə münasibətini bildirir.",
  ["Danışanın münasibətini", "Əşyanın rəngini",
   "Hərəkətin yerini", "Sayı"], 1, None, 2),
 ("«Əlbəttə» modal sözü hansı münasibəti bildirir?",
  "Yəqinlik (əminlik) bildirir.",
  ["Yəqinlik", "Şübhə", "Kədər", "Qəzəb"], 1, None, 2),
 ("«Bəlkə» sözü nəyi ifadə edir?",
  "Güman, ehtimal bildirir.",
  ["Güman (ehtimal)", "Dəqiqlik", "Nəticə", "Sevinc"],
  1, None, 2),
 ("«Deməli» modal sözü nə bildirir?",
  "Nəticə bildirir.",
  ["Nəticə", "Şübhə", "Sual", "İnkar"], 1, None, 3),
 ("Modal sözlər yazıda necə ayrılır?",
  "Vergüllə ayrılır: Əlbəttə, gələcəyəm.",
  ["Vergüllə", "Nöqtə ilə", "Defislə", "Ayrılmır"],
  1, None, 2),
 ("«Hətta» ədatı nəyi bildirir?",
  "Qüvvətləndirmə bildirir.",
  ["Qüvvətləndirmə", "Məhdudlaşdırma", "Sual", "Şərt"],
  1, None, 3),
],
"az-7-nida": [
 ("Nida nəyi ifadə edir?",
  "Hiss və həyəcanı ifadə edir.",
  ["Hiss və həyəcanı", "Əşyanın adını", "Hərəkəti",
   "Miqdarı"], 1, None, 1),
 ("«Ay!, Of!, Vay!» sözləri hansı nitq hissəsidir?",
  "Bunlar nidalardır.",
  ["Nida", "Ədat", "Qoşma", "Zərf"], 1, None, 1),
 ("«Of» nidası adətən nəyi bildirir?",
  "Narazılıq, yorğunluq, ağrı bildirir.",
  ["Narazılıq və ağrını", "Sevinci", "Təəccübü",
   "Heç nəyi"], 1, None, 2),
 ("Nidadan sonra hansı işarələr qoyula bilər?",
  "Nida işarəsi və ya vergül qoyulur.",
  ["Nida işarəsi və ya vergül", "Yalnız nöqtə",
   "Sual işarəsi", "Heç nə"], 1, None, 3),
 ("Yamsılamalar hansı sözlərdir?",
  "Təbiət səslərini təqlid edən sözlərdir.",
  ["Səsləri təqlid edən sözlər", "Rəng bildirən sözlər",
   "Say bildirən sözlər", "Adlar"], 1, None, 2),
 ("«Şırıl-şırıl» sözü nəyə misaldır?",
  "Suyun səsini təqlid edir — yamsılamadır.",
  ["Yamsılamaya", "Nidaya", "Ədata", "Modal sözə"],
  1, None, 2),
 ("«Miyoldamaq» feili nədən yaranıb?",
  "«Miyo» yamsılamasından yaranıb.",
  ["Yamsılamadan", "Sifətdən", "Saydan", "Qoşmadan"],
  1, None, 3),
 ("«Urra!» nidası hansı hissi bildirir?",
  "Sevinc və coşqu bildirir.",
  ["Sevinc", "Qorxu", "Kədər", "Narazılıq"], 1, None, 2),
 ("Nidalar cümlə üzvü olurmu?",
  "Nidalar cümlə üzvü olmur.",
  ["Xeyr, olmur", "Bəli, mübtəda olur", "Bəli, xəbər olur",
   "Yalnız təyin olur"], 1, None, 3),
 ("«Şaqqıltı» sözü necə yaranıb?",
  "«Şaqq» yamsılamasına şəkilçi artırılıb.",
  ["Yamsılamaya şəkilçi artırmaqla", "İki kökün birləşməsi ilə",
   "Alınma sözdən", "Nidasız yaranıb"], 1, None, 3),
],
"az-7-uslub": [
 ("Bədii üslubun əsas xüsusiyyəti nədir?",
  "Bədii üslub obrazlılığa əsaslanır.",
  ["Obrazlılıq", "Quru faktlar", "Rəsmi müraciət",
   "Terminlərin çoxluğu"], 1, None, 2),
 ("Elmi üslubda nədən geniş istifadə olunur?",
  "Terminlərdən və dəqiq faktlardan.",
  ["Terminlərdən", "Bədii təsvirlərdən", "Nidalardan",
   "Dialektlərdən"], 1, None, 2),
 ("Rəsmi üslub harada işlənir?",
  "Sənədlərdə: ərizə, protokol, əmr.",
  ["Rəsmi sənədlərdə", "Nağıllarda", "Şeirlərdə",
   "Dostlarla söhbətdə"], 1, None, 2),
 ("Məişət (danışıq) üslubu harada istifadə olunur?",
  "Gündəlik ünsiyyətdə işlənir.",
  ["Gündəlik ünsiyyətdə", "Elmi məqalədə",
   "Dövlət sənədində", "Dərslikdə"], 1, None, 2),
 ("Publisistik üslub hansı sahəyə xasdır?",
  "Mətbuat və televiziyaya xasdır.",
  ["Mətbuata", "Riyaziyyata", "Məişətə", "Nağıllara"],
  1, None, 3),
 ("Ərizə hansı üslubda yazılır?",
  "Ərizə rəsmi üslubda yazılır.",
  ["Rəsmi", "Bədii", "Məişət", "Elmi"], 1, None, 2),
 ("Nitq mədəniyyəti nəyi tələb edir?",
  "Düzgün, aydın və nəzakətli danışığı.",
  ["Düzgün və nəzakətli danışığı", "Ucadan danışmağı",
   "Çox danışmağı", "Sözləri qısaltmağı"], 1, None, 2),
 ("Şeir və hekayələr hansı üsluba aiddir?",
  "Bədii üsluba aiddir.",
  ["Bədii", "Elmi", "Rəsmi", "Publisistik"], 1, None, 2),
 ("«Molekul», «reaksiya» kimi sözlər hansı üslubun əlamətidir?",
  "Terminlər elmi üslubun əlamətidir.",
  ["Elmi", "Məişət", "Bədii", "Rəsmi"], 1, None, 3),
 ("Auditoriya qarşısında çıxışda nəyə diqqət edilməlidir?",
  "Aydın tələffüzə və fikrin ardıcıllığına.",
  ["Aydın tələffüzə və ardıcıllığa", "Sürətli danışmağa",
   "Uzun cümlələrə", "Səsi qısmağa"], 1, None, 3),
],
# ====================== INGILIS DILI 7 ================================
"ing-7-schools": [
 ("Which subject teaches about the past?",
  "Keçmişi tarix (History) öyrədir.",
  ["History", "Maths", "Music", "PE"], 1, None, 2),
 ("«Science» dərsində nə öyrənilir?",
  "Science — təbiət elmləri.",
  ["Təbiət elmləri", "Rəsm", "Musiqi", "İdman"], 1, None, 2),
 ("«We ___ to do our homework every day.» (məcburiyyət)",
  "Have to — məcburiyyət bildirir.",
  ["have", "has", "are", "do"], 1, None, 2),
 ("«Timetable» sözünün mənası nədir?",
  "Timetable — dərs cədvəli.",
  ["Dərs cədvəli", "Yemək menyusu", "Xəritə", "Lüğət"],
  1, None, 2),
 ("«Break» sözü məktəb kontekstində nəyi bildirir?",
  "Break — tənəffüs.",
  ["Tənəffüsü", "İmtahanı", "Dərsi", "Jurnal"], 1, None, 2),
 ("Which is a school subject?",
  "Geography — coğrafiya dərsidir.",
  ["Geography", "Sandwich", "Window", "Garden"], 1, None, 1),
 ("«Primary school» hansı məktəbdir?",
  "Primary school — ibtidai məktəb.",
  ["İbtidai məktəb", "Universitet", "Uşaq bağçası",
   "Peşə məktəbi"], 1, None, 2),
 ("«Learn» və «teach» feillərinin fərqi nədir?",
  "Learn — öyrənmək, teach — öyrətmək.",
  ["Learn öyrənmək, teach öyrətmək", "Eyni mənadadırlar",
   "Hər ikisi oxumaqdır", "Hər ikisi yazmaqdır"], 1, None, 3),
 ("«Do you have to wear a uniform?» sualı nəyi soruşur?",
  "Forma geyinmə məcburiyyətini soruşur.",
  ["Forma geymək məcburiyyətini", "Formanın rəngini",
   "Formanın qiymətini", "Dərsin vaxtını"], 1, None, 3),
 ("«Exam» sözünün mənası nədir?",
  "Exam — imtahan.",
  ["İmtahan", "Tətil", "Oyun", "Mahnı"], 1, None, 1),
],
"ing-7-technology": [
 ("«Screen», «keyboard», «mouse» sözləri nəyə aiddir?",
  "Bunlar kompüterin hissələridir.",
  ["Kompüterə", "Mətbəxə", "İdmana", "Təbiətə"], 1, None, 1),
 ("«Turn on» ifadəsi nə deməkdir?",
  "Turn on — qoşmaq, yandırmaq.",
  ["Qoşmaq", "Söndürmək", "Sındırmaq", "Satmaq"], 1, None, 2),
 ("«Turn off» nə deməkdir?",
  "Turn off — söndürmək.",
  ["Söndürmək", "Qoşmaq", "Yükləmək", "Silmək"], 1, None, 2),
 ("«I am texting my friend.» — Danışan nə edir?",
  "Text — mesaj yazmaq.",
  ["Mesaj yazır", "Kitab oxuyur", "Yemək bişirir",
   "Velosiped sürür"], 1, None, 2),
 ("«Download» feili nə bildirir?",
  "Download — interneti yükləmək (endirmək).",
  ["Yükləmək (endirmək)", "Çap etmək", "Silmək",
   "Rəngləmək"], 1, None, 2),
 ("«Charge the phone» nə deməkdir?",
  "Telefonu enerji ilə doldurmaq.",
  ["Telefonu enerji ilə doldurmaq", "Telefonu satmaq",
   "Telefonu sındırmaq", "Telefon almaq"], 1, None, 2),
 ("«She ___ a video now.» boşluğunu doldurun.",
  "İndiki davamedici: is watching.",
  ["is watching", "watch", "watches", "watched"], 1, None, 3),
 ("«Gadget» sözü nəyi bildirir?",
  "Gadget — kiçik texniki cihaz.",
  ["Kiçik texniki cihazı", "Meyvəni", "Geyimi", "Oyunu"],
  1, None, 2),
 ("«Password» nə üçündür?",
  "Parol hesabı qoruyur.",
  ["Hesabı qorumaq üçün", "Səsi artırmaq üçün",
   "Ekranı silmək üçün", "Şəkil çəkmək üçün"], 1, None, 2),
 ("«Online» sözünün mənası nədir?",
  "Online — şəbəkəyə qoşulu.",
  ["Şəbəkəyə qoşulu", "Söndürülmüş", "Tək", "Yavaş"],
  1, None, 2),
],
"ing-7-talent": [
 ("«Talent» sözünün mənası nədir?",
  "Talent — istedad.",
  ["İstedad", "Tənbəllik", "Yorğunluq", "Qorxu"], 1, None, 1),
 ("«She sings beautifully.» — «beautifully» hansı nitq "
  "hissəsidir?",
  "-ly şəkilçili söz zərfdir (adverb).",
  ["Zərf (adverb)", "İsim", "Feil", "Say"], 1, None, 3),
 ("İngilis dilində zərf adətən necə düzəlir?",
  "Sifətə -ly artırmaqla: slow — slowly.",
  ["Sifətə -ly artırmaqla", "Feilə -ed artırmaqla",
   "İsmə -s artırmaqla", "Düzəlmir"], 1, None, 3),
 ("«Good» sifətinin zərf forması hansıdır?",
  "Good qaydasızdır: well.",
  ["well", "goodly", "gooder", "best"], 1, None, 3),
 ("«She dances ___ than me.» (daha yaxşı)",
  "Well zərfinin müqayisəsi: better.",
  ["better", "weller", "good", "well"], 1, None, 3),
 ("«Play ___ piano» ifadəsində hansı artikl işlənir?",
  "Musiqi alətləri ilə «the» işlənir: play the piano.",
  ["the", "a", "an", "Artikl işlənmir"], 1, None, 3),
 ("«Competition» nə deməkdir?",
  "Competition — yarışma, müsabiqə.",
  ["Yarışma", "İstirahət", "Dərs", "Səyahət"], 1, None, 2),
 ("«Win» feilinin mənası nədir?",
  "Win — qalib gəlmək.",
  ["Qalib gəlmək", "Uduzmaq", "Başlamaq", "Gözləmək"],
  1, None, 2),
 ("«Prize» sözü nəyi bildirir?",
  "Prize — mükafat.",
  ["Mükafatı", "Cəzanı", "Qiyməti", "Biletdir"], 1, None, 2),
 ("«What are you good at?» sualı nəyi soruşur?",
  "Nədə yaxşı (bacarıqlı) olduğunu soruşur.",
  ["Nədə bacarıqlı olduğunu", "Yaşını", "Ünvanını",
   "Adını"], 1, None, 3),
],
"ing-7-travel": [
 ("«Abroad» sözü nə deməkdir?",
  "Abroad — xaricdə.",
  ["Xaricdə", "Evdə", "Yaxında", "Aşağıda"], 1, None, 2),
 ("«Book a ticket» ifadəsi nə bildirir?",
  "Book — sifariş etmək: bilet sifariş etmək.",
  ["Bilet sifariş etmək", "Kitab oxumaq", "Bilet itirmək",
   "Bilet satmaq"], 1, None, 3),
 ("«We are going to visit Paris.» cümləsi nəyi bildirir?",
  "Going to — yaxın gələcək planı bildirir.",
  ["Gələcək planı", "Keçmiş hadisəni", "Əmri",
   "Peşmançılığı"], 1, None, 3),
 ("«Luggage» nə deməkdir?",
  "Luggage — baqaj, yük.",
  ["Baqaj", "Sərnişin", "Sürücü", "Yol"], 1, None, 2),
 ("«Airport» nədir?",
  "Airport — hava limanı.",
  ["Hava limanı", "Dəmiryol vağzalı", "Liman", "Körpü"],
  1, None, 1),
 ("«Map» nə üçün istifadə olunur?",
  "Xəritə yolu tapmağa kömək edir.",
  ["Yol tapmaq üçün", "Yemək bişirmək üçün",
   "Paltar yumaq üçün", "Mahnı oxumaq üçün"], 1, None, 1),
 ("«Foreign country» ifadəsi nə deməkdir?",
  "Foreign — xarici: xarici ölkə.",
  ["Xarici ölkə", "Doğma şəhər", "Kiçik kənd",
   "Qonşu küçə"], 1, None, 2),
 ("«How long did the journey take?» sualı nəyi soruşur?",
  "Səyahətin nə qədər çəkdiyini soruşur.",
  ["Səyahətin müddətini", "Biletin qiymətini",
   "Yolun rəngini", "Sürücünün adını"], 1, None, 3),
 ("«Guide» kimdir?",
  "Guide — bələdçi.",
  ["Bələdçi", "Aşpaz", "Həkim", "Müəllim"], 1, None, 2),
 ("«Souvenir» sözünün mənası nədir?",
  "Souvenir — xatirə hədiyyəsi.",
  ["Xatirə hədiyyəsi", "Yol çantası", "Xəritə", "Bilet"],
  1, None, 2),
],
"ing-7-friends": [
 ("«Friendship» sözünün mənası nədir?",
  "Friendship — dostluq.",
  ["Dostluq", "Düşmənçilik", "Qonşuluq", "Səyahət"],
  1, None, 1),
 ("«Trust» feili nə deməkdir?",
  "Trust — etibar etmək.",
  ["Etibar etmək", "Aldatmaq", "Unutmaq", "Qorxmaq"],
  1, None, 2),
 ("«A friend in need is a friend indeed» atalar sözünün mənası "
  "nədir?",
  "Əsl dost dar gündə tanınar.",
  ["Əsl dost dar gündə tanınar", "Dostlar çox olmalıdır",
   "Dostsuz yaşamaq olar", "Dostlar həmişə gülür"],
  1, None, 3),
 ("«Share» feilinin mənası nədir?",
  "Share — bölüşmək.",
  ["Bölüşmək", "Gizlətmək", "Almaq", "Atmaq"], 1, None, 2),
 ("«We have known each other for five years.» — Onlar nə "
  "qədərdir tanışdırlar?",
  "For five years — beş ildir.",
  ["5 il", "5 ay", "5 gün", "5 saat"], 1, None, 2),
 ("«Get on well with somebody» ifadəsi nə deməkdir?",
  "Kiminləsə yaxşı yola getmək.",
  ["Yaxşı yola getmək", "Mübahisə etmək", "Küsmək",
   "Yarışmaq"], 1, None, 3),
 ("«Support» feili dostluqda nəyi bildirir?",
  "Support — dəstək olmaq.",
  ["Dəstək olmağı", "Tərk etməyi", "Gülməyi",
   "Danlamağı"], 1, None, 2),
 ("«Loyal friend» necə dostdur?",
  "Loyal — sadiq.",
  ["Sadiq", "Yalançı", "Tənbəl", "Paxıl"], 1, None, 2),
 ("«Argue» feilinin mənası nədir?",
  "Argue — mübahisə etmək.",
  ["Mübahisə etmək", "Barışmaq", "Gülmək", "Oxumaq"],
  1, None, 2),
 ("«Make friends» ifadəsi nə deməkdir?",
  "Make friends — dostlaşmaq.",
  ["Dostlaşmaq", "Dost itirmək", "Ev tikmək",
   "Hədiyyə almaq"], 1, None, 2),
],
"ing-7-future": [
 ("Will ilə gələcək zaman necə qurulur?",
  "Will + feilin əsas forması: will go.",
  ["will + feilin əsas forması", "will + feil-ed",
   "will + feil-ing", "will işlənmir"], 1, None, 2),
 ("«People ___ live on Mars one day.» (proqnoz)",
  "Proqnoz üçün will işlənir.",
  ["will", "did", "was", "have"], 1, None, 2),
 ("«Robots will help people.» cümləsi hansı zamandadır?",
  "Will — gələcək zaman.",
  ["Gələcək", "Keçmiş", "İndiki", "Davamedici keçmiş"],
  1, None, 2),
 ("«Will you come with us?» sualına qısa cavab hansıdır?",
  "Qısa cavab: Yes, I will.",
  ["Yes, I will.", "Yes, I did.", "Yes, I am.",
   "Yes, I have."], 1, None, 2),
 ("«In the future» ifadəsi nə deməkdir?",
  "In the future — gələcəkdə.",
  ["Gələcəkdə", "Keçmişdə", "İndi", "Dünən"], 1, None, 1),
 ("«Prediction» sözü nəyi bildirir?",
  "Prediction — proqnoz, öncəgörmə.",
  ["Proqnozu", "Xatirəni", "Sualı", "Cavabı"], 1, None, 3),
 ("«Flying cars» ifadəsi nə deməkdir?",
  "Uçan maşınlar.",
  ["Uçan maşınlar", "Sürətli qatarlar", "Köhnə maşınlar",
   "Oyuncaq maşınlar"], 1, None, 2),
 ("«Space» sözünün mənası nədir?",
  "Space — kosmos.",
  ["Kosmos", "Dəniz", "Meşə", "Səhra"], 1, None, 1),
 ("«Life in the future will be different.» — Söhbət nədən gedir?",
  "Gələcək həyatın fərqli olacağından.",
  ["Gələcək həyatdan", "Keçmiş əsrlərdən", "Bu günki dərsdən",
   "Yeməkdən"], 1, None, 2),
 ("«I think it will rain» cümləsində «I think» nəyi bildirir?",
  "Danışanın fikrini (proqnozunu).",
  ["Danışanın fikrini", "Dəqiq faktı", "Əmri",
   "Keçmiş hadisəni"], 1, None, 3),
],
# ======================= INFORMATIKA 7 ================================
"inf-7-kompyuter": [
 ("Hansı qurğu giriş qurğusudur?",
  "Klaviatura məlumatı kompüterə daxil edir.",
  ["Klaviatura", "Monitor", "Printer", "Dinamik"],
  1, None, 2),
 ("Hansı qurğu çıxış qurğusudur?",
  "Monitor məlumatı istifadəçiyə göstərir.",
  ["Monitor", "Klaviatura", "Maus", "Skaner"], 1, None, 2),
 ("Prosessorun iş sürətini xarakterizə edən kəmiyyət hansıdır?",
  "Takt tezliyi prosessorun sürətini göstərir.",
  ["Takt tezliyi", "Çəkisi", "Rəngi", "Ölçüsü"], 1, None, 3),
 ("Skaner hansı qurğular qrupuna aiddir?",
  "Skaner məlumatı daxil edir — giriş qurğusudur.",
  ["Giriş", "Çıxış", "Yaddaş", "Heç biri"], 1, None, 3),
 ("Printer hansı qurğular qrupuna aiddir?",
  "Printer nəticəni kağıza çıxarır — çıxış qurğusudur.",
  ["Çıxış", "Giriş", "Emal", "Şəbəkə"], 1, None, 2),
 ("Fayl adı hansı hissələrdən ibarətdir?",
  "Addan və genişlənmədən: sekil.png.",
  ["Ad və genişlənmə", "Yalnız rəqəmlər", "Parol və ad",
   "Tarix və saat"], 1, None, 2),
 ("Qovluğun içində nələr yerləşə bilər?",
  "Fayllar və digər qovluqlar.",
  ["Fayllar və digər qovluqlar", "Yalnız şəkillər",
   "Yalnız musiqi", "Heç nə"], 1, None, 2),
 ("Faylı başqa qovluğa hansı əməllə aparmaq olar?",
  "Köçürmə (daşıma) əməli ilə.",
  ["Köçürmə (daşıma) ilə", "Silmə ilə", "Çap ilə",
   "Rəngləmə ilə"], 1, None, 2),
 ("Sistem proqram təminatına nə daxildir?",
  "Əməliyyat sistemi sistem proqram təminatıdır.",
  ["Əməliyyat sistemi", "Oyunlar", "Mətn redaktoru",
   "Kalkulyator"], 1, None, 3),
 ("Tətbiqi proqrama misal hansıdır?",
  "Mətn redaktoru tətbiqi proqramdır.",
  ["Mətn redaktoru", "Əməliyyat sistemi", "Drayver",
   "BIOS"], 1, None, 3),
],
"inf-7-tetbiqi": [
 ("Mətn redaktorunda cədvəl hansı elementlərdən qurulur?",
  "Sətir, sütun və xanalardan.",
  ["Sətir, sütun və xanalardan", "Yalnız şəkillərdən",
   "Səhifələrdən", "Düymələrdən"], 1, None, 2),
 ("Cədvəldə sətirlə sütunun kəsişməsi necə adlanır?",
  "Kəsişmə xana adlanır.",
  ["Xana", "Blok", "Slayd", "Sahə"], 1, None, 2),
 ("Mətn redaktorunda diaqram nə üçün qurulur?",
  "Ədədi məlumatı əyani göstərmək üçün.",
  ["Ədədi məlumatı əyani göstərmək üçün", "Mətni silmək üçün",
   "Səhifəni bağlamaq üçün", "Şrift dəyişmək üçün"],
  1, None, 2),
 ("Şəklin atributlarına nə daxildir?",
  "Ölçüsü və səhifədə yerləşməsi.",
  ["Ölçüsü və yerləşməsi", "Qiyməti", "Çəkisi",
   "Müəllifin yaşı"], 1, None, 3),
 ("Slaydlararası keçid effektləri nə üçündür?",
  "Nümayişi daha cəlbedici etmək üçün.",
  ["Nümayişi cəlbedici etmək üçün", "Faylı silmək üçün",
   "Mətni gizlətmək üçün", "Kompüteri sürətləndirmək üçün"],
  1, None, 2),
 ("Cədvələ yeni sətir əlavə etmək mümkündürmü?",
  "Bəli, istənilən yerə sətir əlavə etmək olar.",
  ["Bəli, istənilən yerə", "Xeyr, heç vaxt",
   "Yalnız sona", "Yalnız çap zamanı"], 1, None, 2),
 ("Diaqramın tipini seçərkən nə nəzərə alınır?",
  "Məlumatın xarakteri (müqayisə, pay, dəyişmə).",
  ["Məlumatın xarakteri", "Kompüterin rəngi",
   "Günün vaxtı", "Faylın adı"], 1, None, 3),
 ("Şəklin mətnlə «axını» nəyi müəyyən edir?",
  "Mətnin şəkli necə əhatə etdiyini.",
  ["Mətnin şəkli əhatə etməsini", "Şəklin rəngini",
   "Mətnin dilini", "Səhifənin sayını"], 1, None, 3),
 ("Slayd-şou rejimi nə üçündür?",
  "Təqdimatı tam ekranda nümayiş etdirmək üçün.",
  ["Təqdimatı nümayiş etdirmək üçün", "Fayl silmək üçün",
   "Cədvəl qurmaq üçün", "Səs yazmaq üçün"], 1, None, 2),
 ("Cədvəlin xanasına nə daxil etmək olar?",
  "Mətn və ədədlər daxil etmək olar.",
  ["Mətn və ədədlər", "Yalnız şəkil", "Heç nə",
   "Yalnız düymələr"], 1, None, 2),
],
"inf-7-informasiya": [
 ("İnformasiyanın əsas xassələrindən biri hansıdır?",
  "Doğruluq (etibarlılıq) əsas xassədir.",
  ["Doğruluq", "Rənglilik", "Ağırlıq", "Şirinlik"],
  1, None, 2),
 ("Aktual informasiya necə informasiyadır?",
  "Hazırkı vaxt üçün əhəmiyyətli olan.",
  ["Vaxtında və əhəmiyyətli", "Köhnəlmiş", "Yalan",
   "Gizli"], 1, None, 2),
 ("Onluq say sistemində neçə rəqəmdən istifadə olunur?",
  "0-dan 9-a qədər — 10 rəqəm.",
  ["10", "2", "8", "16"], 1, str(10), 2),
 ("İkilik «11» ədədinin onluq qarşılığı neçədir?",
  "1·2 + 1·1 = 3.",
  ["3", "11", "2", "4"], 1, str(int("11", 2)), 3),
 ("Bütün mərtəbələri 1 olan üçrəqəmli ikilik ədəd (111) onluq "
  "sistemdə hansı ədədə bərabərdir?",
  "1·4 + 1·2 + 1·1 = 7.",
  ["7", "111", "6", "8"], 1, str(int("111", 2)), 3),
 ("Tam informasiya nə deməkdir?",
  "Qərar üçün kifayət qədər dolğun olması.",
  ["Kifayət qədər dolğun olması", "Ən qısa olması",
   "Şəkilli olması", "Səsli olması"], 1, None, 3),
 ("Hər simvol 1 bayt olarsa, 25 simvolluq mətn neçə bayt tutar?",
  "25 · 1 = 25 bayt.",
  ["25", "8", "200", "1"], 1, str(25), 2),
 ("Səkkizlik say sistemində hansı rəqəmlər işlənir?",
  "0-dan 7-yə qədər rəqəmlər.",
  ["0-dan 7-yə qədər", "0-dan 9-a qədər", "1-dən 8-ə qədər",
   "Yalnız 0 və 1"], 1, None, 3),
 ("Say sistemi nədir?",
  "Ədədlərin yazılması qaydaları toplusudur.",
  ["Ədədlərin yazılış qaydaları", "Hərflərin siyahısı",
   "Proqram adı", "Qurğu növü"], 1, None, 2),
 ("2 bayt neçə bitdir?",
  "2 · 8 = 16 bit.",
  ["16", "2", "8", "1024"], 1, str(2 * 8), 2),
],
"inf-7-proqramlasdirma": [
 ("Altproqram nədir?",
  "Proqramın ad verilmiş ayrıca hissəsidir.",
  ["Proqramın ad verilmiş hissəsi", "Kompüter qurğusu",
   "Fayl növü", "Şəkil formatı"], 1, None, 3),
 ("Altproqram nə üçün istifadə olunur?",
  "Təkrarlanan hissəni bir dəfə yazıb dəfələrlə çağırmaq üçün.",
  ["Təkrarlanan hissəni bir dəfə yazmaq üçün",
   "Proqramı uzatmaq üçün", "Kompüteri söndürmək üçün",
   "Şrift dəyişmək üçün"], 1, None, 3),
 ("«Riyaziyyatçı Bağa» hansı işi görə bilir?",
  "Hesablamalar aparıb nəticəni ekrana yazır.",
  ["Hesablayıb nəticəni yazır", "Yalnız yatır",
   "Mahnı oxuyur", "Fayl silir"], 1, None, 2),
 ("Altproqramda dəyişən nə üçün lazımdır?",
  "Eyni altproqramı müxtəlif qiymətlərlə işlətmək üçün.",
  ["Müxtəlif qiymətlərlə işləmək üçün", "Yaddaşı silmək üçün",
   "Rəng seçmək üçün", "Lazım deyil"], 1, None, 3),
 ("Kompüterdə məsələ həllinin mərhələlərindən biri hansıdır?",
  "Alqoritmin qurulması əsas mərhələdir.",
  ["Alqoritmin qurulması", "Kompüterin satılması",
   "Ekranın silinməsi", "Qələmin itilənməsi"], 1, None, 2),
 ("ALPLogo-da «qələmi qaldır» əmri nə edir?",
  "Bağa iz qoymadan (xətt çəkmədən) hərəkət edir.",
  ["Bağa xətt çəkmədən hərəkət edir", "Bağa dayanır",
   "Xətt qalınlaşır", "Ekran təmizlənir"], 1, None, 3),
 ("Eyni fiquru müxtəlif ölçüdə çəkmək üçün nədən istifadə etmək "
  "əlverişlidir?",
  "Dəyişənli altproqramdan.",
  ["Dəyişənli altproqramdan", "Yeni kompüterdən",
   "Başqa proqramdan", "Silgidən"], 1, None, 3),
 ("«təkrar 8 [irəli 40 sağa 45]» proqramı hansı fiquru çəkər?",
  "360 : 45 = 8 dönüş — səkkizbucaqlı.",
  ["Səkkizbucaqlı", "Kvadrat", "Üçbucaq", "Dairə"], 1,
  ("Səkkizbucaqlı" if 360 // 45 == 8 else "Kvadrat"), 3),
 ("Proqramı icra etməzdən əvvəl nə etmək faydalıdır?",
  "Əmrlərin düzgünlüyünü yoxlamaq.",
  ["Əmrləri yoxlamaq", "Kompüteri silkələmək",
   "Ekranı bağlamaq", "Heç nə"], 1, None, 2),
 ("Proqramın müxtəlif qiymətlərlə yoxlanması necə adlanır?",
  "Bu, test etmə mərhələsidir.",
  ["Test etmə", "Çap etmə", "Silmə", "Rəngləmə"],
  1, None, 3),
],
"inf-7-internet": [
 ("İnternetə qoşulmaq üçün nə lazımdır?",
  "Provayderin xidməti və şəbəkə avadanlığı.",
  ["Provayder xidməti və avadanlıq", "Yalnız televizor",
   "Yalnız printer", "Heç nə"], 1, None, 2),
 ("E-poçtla böyük faylı göndərərkən nə nəzərə alınmalıdır?",
  "Qoşma faylın ölçü limiti.",
  ["Faylın ölçü limiti", "Faylın rəngi", "Günün vaxtı",
   "Kompüterin markası"], 1, None, 3),
 ("İKT nəyin qısaltmasıdır?",
  "İnformasiya-kommunikasiya texnologiyaları.",
  ["İnformasiya-kommunikasiya texnologiyaları",
   "İdman komandası", "Kitab seriyası", "Kompüter oyunu"],
  1, None, 2),
 ("Daxil olan e-məktublar hansı qovluğa düşür?",
  "Gələnlər (Inbox) qovluğuna.",
  ["Gələnlər (Inbox)", "Zibil qutusuna", "Göndərilənlərə",
   "İş masasına"], 1, None, 2),
 ("Spam nədir?",
  "Arzuolunmaz kütləvi reklam məktublarıdır.",
  ["Arzuolunmaz kütləvi məktublar", "Vacib sənədlər",
   "Dost məktubları", "Dərs cədvəli"], 1, None, 2),
 ("E-məktubu bir neçə ünvana göndərmək olarmı?",
  "Bəli, ünvanları ayıraraq göndərmək olar.",
  ["Bəli, olar", "Xeyr, olmaz", "Yalnız gecə olar",
   "Yalnız şəkilsiz olar"], 1, None, 2),
 ("İKT tibb sahəsində nəyə imkan verir?",
  "Uzaqdan müayinə və elektron qeydiyyata.",
  ["Uzaqdan müayinəyə", "Xəstəliyi artırmağa",
   "Növbələri uzatmağa", "Heç nəyə"], 1, None, 3),
 ("Onlayn təhsil nədir?",
  "İnternet vasitəsilə aparılan təhsildir.",
  ["İnternetlə təhsil", "Yalnız kitabla təhsil",
   "Təhsilin dayandırılması", "İdman növü"], 1, None, 2),
 ("Videozəng üçün hansı qurğular lazımdır?",
  "Kamera və mikrofon lazımdır.",
  ["Kamera və mikrofon", "Printer və skaner",
   "Xətkeş və qələm", "Tərəzi"], 1, None, 2),
 ("Müəllif hüququ internetdə nəyi qadağan edir?",
  "Başqasının əsərini icazəsiz yaymağı.",
  ["Əsəri icazəsiz yaymağı", "Öz şəklini çəkməyi",
   "Kitab oxumağı", "Məktub yazmağı"], 1, None, 3),
],
# ======================== UMUMI TARIX 7 ===============================
}



#  Derinlesdirme: her movzuya 10 elave sual (#11-20).
ELAVE = {
"az-7-edat-modal": [
 ("«Axı» sözü hansı nitq hissəsidir?",
  "Mənanı qüvvətləndirən ədatdır.",
  ["Ədat", "İsim", "Feil", "Zərf"], 1, None, 2),
 ("«Təəssüf ki» modal sözü hansı münasibəti bildirir?",
  "Təəssüf münasibətini.",
  ["Təəssüf", "Sevinc", "Yəqinlik", "Sual"], 1, None, 2),
 ("«Görəsən» modal sözü nəyi ifadə edir?",
  "Maraq və gümanı ifadə edir.",
  ["Maraq və gümanı", "Qəti hökmü", "Əmri", "İnkarı"],
  1, None, 2),
 ("«Da, də» ədatları hansı vəzifəni daşıyır?",
  "Mənanı qüvvətləndirir.",
  ["Qüvvətləndirmə", "İnkar", "Sual", "Bənzətmə"],
  1, None, 2),
 ("Ədatlar cümlə üzvü olurmu?",
  "Xeyr, ədatlar cümlə üzvü olmur.",
  ["Xeyr, olmur", "Bəli, mübtəda olur", "Bəli, xəbər olur",
   "Yalnız təyin olur"], 1, None, 2),
 ("«Bəli», «xeyr» sözləri hansı qrupa aiddir?",
  "Təsdiq və inkar bildirən sözlərdir.",
  ["Təsdiq və inkar ədatlarına", "İsimlərə", "Feillərə",
   "Saylara"], 1, None, 3),
 ("«Zənnimcə» sözü nəyi bildirir?",
  "Danışanın şəxsi gümanını.",
  ["Danışanın gümanını", "Dəqiq faktı", "Əmri",
   "Sual məqsədini"], 1, None, 2),
 ("«Məhz» ədatı nəyi bildirir?",
  "Dəqiqləşdirmə bildirir.",
  ["Dəqiqləşdirmə", "İnkar", "Arzu", "Bənzətmə"],
  1, None, 3),
 ("Modal sözlər cümlə üzvləri ilə qrammatik əlaqəyə girirmi?",
  "Xeyr, qrammatik əlaqəyə girmir.",
  ["Xeyr, qrammatik əlaqəyə girmir", "Bəli, uzlaşır",
   "Bəli, idarə olunur", "Yalnız xəbərlə bağlanır"],
  1, None, 3),
 ("«Şübhəsiz» modal sözü hansı qrupa aiddir?",
  "Yəqinlik bildirən modal sözlərə.",
  ["Yəqinlik bildirənlərə", "Güman bildirənlərə",
   "Təəssüf bildirənlərə", "Sual bildirənlərə"],
  1, None, 2),
],
"az-7-feil-qurulus": [
 ("«Sulamaq» feili hansı nitq hissəsindən düzəlib?",
  "Su ismindən düzəlib.",
  ["İsimdən", "Sifətdən", "Saydan", "Zərfdən"],
  1, None, 2),
 ("«Yazıb-oxumaq» quruluşca hansı feildir?",
  "İki feildən ibarət mürəkkəb feildir.",
  ["Mürəkkəb", "Sadə", "Düzəltmə", "Köməkçi"],
  1, None, 2),
 ("Düzəltmə feilə misal hansıdır?",
  "İş kökündən: işləmək.",
  ["işləmək", "yaz", "gəl", "get"], 1, None, 2),
 ("Təsirsiz feilə misal hansıdır?",
  "Gülmək təsirsiz feildir — nəyi? sualı verilmir.",
  ["gülmək", "yazmaq", "oxumaq", "gətirmək"],
  1, None, 3),
 ("Feilin inkarı hansı şəkilçi ilə düzəlir?",
  "-ma, -mə şəkilçisi ilə.",
  ["-ma, -mə", "-lar, -lər", "-çı, -çi", "-lıq, -lik"],
  1, None, 2),
 ("«Oxutdurmaq» feilində hərəkəti kim icra edir?",
  "Hərəkət başqasına etdirilir (icbar məna).",
  ["Başqası (icbar məna)", "Danışan özü", "Heç kim",
   "Yalnız dinləyən"], 1, None, 3),
 ("«Görüşmək» feilində hərəkət necə icra olunur?",
  "Qarşılıqlı — iki tərəf arasında.",
  ["Qarşılıqlı, iki tərəf arasında", "Təkbaşına",
   "Yalnız məchul", "İcrasız"], 1, None, 3),
 ("«Geyinmək» feili hansı mənanı bildirir?",
  "İş öz üzərində icra olunur (qayıdış mənası).",
  ["İş öz üzərində icra olunur", "İş başqasına aiddir",
   "Hərəkət yoxdur", "Yalnız əmr"], 1, None, 3),
 ("Feil cümlədə əsasən hansı üzv olur?",
  "Feil əsasən xəbər olur.",
  ["Xəbər", "Mübtəda", "Təyin", "Tamamlıq"],
  1, None, 2),
 ("«Qaçmaq» sözü quruluşca hansı feildir?",
  "Yalnız kökdən ibarətdir — sadədir.",
  ["Sadə", "Düzəltmə", "Mürəkkəb", "Birləşmə"],
  1, None, 2),
],
"az-7-feil-sekil": [
 ("«Oxuyasan» feili hansı şəkildədir?",
  "-a, -ə (…asan) arzu şəklidir.",
  ["Arzu", "Şərt", "Vacib", "Əmr"], 1, None, 3),
 ("«Getməliyik» sözündəki -məli şəkilçisi hansı şəkli yaradır?",
  "Vacib şəklini yaradır.",
  ["Vacib şəkli", "Arzu şəkli", "Şərt şəkli", "Xəbər şəkli"],
  1, None, 2),
 ("«Görəsi» feili hansı şəkildədir?",
  "-əsi şəkilçisi lazım şəklidir.",
  ["Lazım", "Vacib", "Arzu", "Əmr"], 1, None, 3),
 ("Əmr şəklinin II şəxs təkində şəkilçi olurmu?",
  "Xeyr: get!, yaz! — şəkilçisizdir.",
  ["Xeyr, şəkilçisizdir", "Bəli, -sın olur",
   "Bəli, -aq olur", "Bəli, -ın olur"], 1, None, 3),
 ("«Yazsan, qazanarsan» cümləsində birinci feil hansı şəkildədir?",
  "-san şərt bildirir.",
  ["Şərt şəkli", "Arzu şəkli", "Lazım şəkli",
   "Vacib şəkli"], 1, None, 2),
 ("Arzu şəklinin şəkilçisi hansıdır?",
  "-a, -ə (çox vaxt «kaş» sözü ilə).",
  ["-a, -ə (kaş ilə)", "-malı, -məli", "-sa, -sə",
   "-ası, -əsi"], 1, None, 3),
 ("Feilin şəkilləri nəyi bildirir?",
  "Hərəkətə münasibəti bildirir.",
  ["Hərəkətə münasibəti", "Əşyanın rəngini",
   "Sözün mənşəyini", "Hecaların sayını"], 1, None, 3),
 ("«Oxu!» və «Oxuyun!» formaları hansı şəxslərdədir?",
  "II şəxsin təki və cəmi.",
  ["II şəxs tək və cəm", "I şəxs tək və cəm",
   "III şəxs tək", "Şəxssizdir"], 1, None, 2),
 ("Xəbər şəklində feil hansı kateqoriyaya görə dəyişir?",
  "Zamana görə dəyişir.",
  ["Zamana görə", "Rəngə görə", "Ölçüyə görə",
   "Dəyişmir"], 1, None, 2),
 ("«Yazaq» feili hansı şəxsdə və şəkildədir?",
  "I şəxs cəm, əmr şəkli.",
  ["I şəxs cəm, əmr", "II şəxs tək, arzu",
   "III şəxs cəm, şərt", "I şəxs tək, vacib"],
  1, None, 3),
],
"az-7-feil-zaman": [
 ("«Bakıya getdik» feilində hansı keçmiş zaman var?",
  "-di şəkilçisi şühudi keçmişdir.",
  ["Şühudi keçmiş", "Nəqli keçmiş", "İndiki",
   "Gələcək"], 1, None, 2),
 ("-acaq, -əcək şəkilçiləri hansı zamanı düzəldir?",
  "Qəti gələcək zamanı.",
  ["Qəti gələcək", "Qeyri-qəti gələcək", "İndiki",
   "Keçmiş"], 1, None, 2),
 ("«Yazırdı» forması nəyi bildirir?",
  "Keçmişdə davam edən hərəkəti.",
  ["Keçmişdə davam edən hərəkəti", "Gələcək planı",
   "İndiki anı", "Əmri"], 1, None, 3),
 ("Nəqli keçmiş şühudi keçmişdən nə ilə fərqlənir?",
  "Danışan hadisəni nəql edir, şahidi olmayıb.",
  ["Hadisəni nəql etməklə (şahidlik yox)",
   "Daha qısa olması ilə", "Yalnız cəmdə işlənməklə",
   "Fərqi yoxdur"], 1, None, 3),
 ("«Bilər» feilində -ər şəkilçisi nəyi bildirir?",
  "Qeyri-qəti gələcəyi bildirir.",
  ["Qeyri-qəti gələcəyi", "Qəti gələcəyi",
   "Keçmişi", "Əmri"], 1, None, 3),
 ("Feilin zamanları hansılardır?",
  "Keçmiş, indiki və gələcək.",
  ["Keçmiş, indiki, gələcək", "Yalnız keçmiş və indiki",
   "Yalnız gələcək", "Zamanı olmur"], 1, None, 1),
 ("«Oxuyuruq» feili hansı şəxsdədir?",
  "-uq şəkilçisi I şəxsin cəmidir.",
  ["I şəxs cəmdə", "II şəxs təkdə", "III şəxs cəmdə",
   "Şəxssizdir"], 1, None, 2),
 ("«Gedirsən» feilində şəxs şəkilçisi hansıdır?",
  "-sən II şəxsin təkidir.",
  ["-sən", "-ir", "-ged", "-n"], 1, None, 2),
 ("Zaman şəkilçisindən sonra adətən hansı şəkilçi gəlir?",
  "Şəxs şəkilçisi gəlir: yaz-dı-m.",
  ["Şəxs şəkilçisi", "Leksik şəkilçi", "Cəm şəkilçisi əvvəl",
   "Heç nə"], 1, None, 3),
 ("«Yağış yağacaq» cümləsində hərəkət nə vaxt baş verəcək?",
  "Gələcəkdə baş verəcək.",
  ["Gələcəkdə", "Keçmişdə", "İndi", "Heç vaxt"],
  1, None, 1),
],
"az-7-nida": [
 ("«Bəh-bəh!» nidası hansı hissi bildirir?",
  "Bəyənmə və ləzzət hissini.",
  ["Bəyənmə (ləzzət)", "Qorxu", "Kədər", "Qəzəb"],
  1, None, 2),
 ("«Vay!» nidası adətən nəyi ifadə edir?",
  "Qorxu, təəccüb və kədəri.",
  ["Qorxu və təəccübü", "Sevinci yalnız", "Sual məqsədini",
   "Əmri"], 1, None, 2),
 ("Nidalar dəyişirmi (hallanır, təsriflənirmi)?",
  "Xeyr, nidalar dəyişmir.",
  ["Xeyr, dəyişmir", "Bəli, hallanır", "Bəli, təsriflənir",
   "Yalnız cəmlənir"], 1, None, 2),
 ("«Cik-cik» yamsılaması hansı canlının səsini bildirir?",
  "Sərçənin (quşun) səsini.",
  ["Sərçənin (quşun)", "Pişiyin", "İtin", "İnəyin"],
  1, None, 1),
 ("«Taqqıltı» ismi nədən düzəlib?",
  "Taq-taq yamsılamasından.",
  ["Taq-taq yamsılamasından", "Nidadan", "Sifətdən",
   "Saydan"], 1, None, 3),
 ("Nida cümlənin əvvəlində gələndə hansı işarə ilə ayrılır?",
  "Vergüllə ayrılır.",
  ["Vergüllə", "Nöqtə ilə", "Tire ilə", "Ayrılmır"],
  1, None, 2),
 ("«Mə-ə» yamsılaması hansı heyvana aiddir?",
  "Qoyuna (quzuya).",
  ["Qoyuna (quzuya)", "Ata", "Toyuğa", "Qazana"],
  1, None, 1),
 ("Hiss və həyəcan bildirən sözlər hansı nitq hissəsidir?",
  "Nidalardır.",
  ["Nida", "Ədat", "Bağlayıcı", "Qoşma"], 1, None, 2),
 ("Yamsılamalardan hansı nitq hissələri yarana bilər?",
  "İsim və feil yaranır: şaqqıltı, miyoldamaq.",
  ["İsim və feil", "Yalnız say", "Yalnız əvəzlik",
   "Heç nə yaranmır"], 1, None, 3),
 ("«Oxqay!» nidası nəyi bildirir?",
  "Razılıq və ləzzəti bildirir.",
  ["Razılıq və ləzzəti", "Qorxunu", "Peşmanlığı",
   "Sual məqsədini"], 1, None, 2),
],
"az-7-qosma-baglayici": [
 ("«Görə» qoşması hansı halda olan sözlə işlənir?",
  "Yönlük halla: buna görə.",
  ["Yönlük halda", "Adlıq halda", "Yerlik halda",
   "Təsirlik halda"], 1, None, 3),
 ("«Ya … ya da» hansı bağlayıcı növüdür?",
  "Bölüşdürmə bağlayıcısıdır.",
  ["Bölüşdürmə", "Birləşdirmə", "Qarşılaşdırma",
   "Səbəb"], 1, None, 2),
 ("«Ki» bağlayıcısından sonra hansı işarə qoyulur?",
  "Vergül qoyulur: bilirəm ki, …",
  ["Vergül", "Nöqtə", "Tire", "Heç nə"], 1, None, 2),
 ("Tabelilik bağlayıcısına misal hansıdır?",
  "Çünki tabelilik bağlayıcısıdır.",
  ["çünki", "və", "amma", "ilə"], 1, None, 3),
 ("«Qədər» qoşması nəyi bildirir?",
  "Məsafə və zaman həddini.",
  ["Məsafə və zaman həddini", "Səbəbi", "İnkarı",
   "Sualı"], 1, None, 2),
 ("«Ana ilə» birləşməsi bitişik yazılanda hansı formanı alır?",
  "Saitlə bitən sözdə -yla: anayla.",
  ["anayla", "anala", "anailə", "anayilə"], 1, None, 3),
 ("Bağlayıcılar cümlə üzvü sayılırmı?",
  "Xeyr, sayılmır.",
  ["Xeyr, sayılmır", "Bəli, xəbər olur",
   "Bəli, mübtəda olur", "Yalnız zərflik olur"],
  1, None, 2),
 ("«Nə … nə də» bağlayıcısı işlənən cümlədə feil hansı formada olur?",
  "Feil təsdiq formasında qalır.",
  ["Təsdiq formasında", "İnkar formasında", "Sual formasında",
   "Əmr formasında"], 1, None, 3),
 ("«Bəri» qoşması nəyi bildirir?",
  "Zamanın başlanğıcını: o vaxtdan bəri.",
  ["Zaman başlanğıcını", "Məqsədi", "Bənzətməni",
   "Kəmiyyəti"], 1, None, 3),
 ("Qoşmalar hansı sözlərə qoşulur?",
  "Ad bildirən sözlərə (isim, əvəzlik və s.).",
  ["Ad bildirən sözlərə", "Yalnız feillərə",
   "Yalnız nidalara", "Heç nəyə"], 1, None, 2),
],
"az-7-uslub": [
 ("Qəzet məqaləsi hansı üslubda yazılır?",
  "Mətbuat dili publisistik üslubdur.",
  ["Publisistik", "Bədii", "Rəsmi", "Elmi"],
  1, None, 2),
 ("Bədii üslubda hansı vasitələrdən geniş istifadə olunur?",
  "Məcazlardan və bədii təsvirlərdən.",
  ["Məcaz və bədii təsvirlərdən", "Terminlərdən",
   "Rəsmi ştamplardan", "Rəqəmlərdən yalnız"],
  1, None, 2),
 ("Elmi üslubun məqsədi nədir?",
  "Dəqiq məlumat və izah vermək.",
  ["Dəqiq məlumat vermək", "Əyləndirmək",
   "Hissləri oyatmaq", "Reklam etmək"], 1, None, 2),
 ("Danışıq üslubunda hansı sözlərə yol verilir?",
  "Sadə məişət sözlərinə.",
  ["Sadə məişət sözlərinə", "Yalnız terminlərə",
   "Yalnız rəsmi ifadələrə", "Heç bir sözə"],
  1, None, 2),
 ("Rəsmi sənəddə emosional ifadələr işlənərmi?",
  "Xeyr, rəsmi üslub quru və dəqiqdir.",
  ["Xeyr, işlənməz", "Bəli, mütləq işlənər",
   "Yalnız şeirlə", "Yalnız nida ilə"], 1, None, 2),
 ("Nitqin aydınlığı nə deməkdir?",
  "Fikrin asan başa düşülməsi.",
  ["Fikrin asan anlaşılması", "Sözlərin uzunluğu",
   "Səsin ucalığı", "Sürətli danışıq"], 1, None, 2),
 ("Çıxış zamanı jest və mimikadan necə istifadə olunmalıdır?",
  "Yerində və ölçülü şəkildə.",
  ["Yerində və ölçülü", "Həddindən artıq",
   "Heç istifadə olunmamalı", "Fasiləsiz"], 1, None, 2),
 ("«İclas», «protokol», «qərar» sözləri hansı üsluba xasdır?",
  "Rəsmi-işgüzar üsluba.",
  ["Rəsmi üsluba", "Bədii üsluba", "Məişət üslubuna",
   "Elmi üsluba yalnız"], 1, None, 2),
 ("Üslub nədir?",
  "Dildən məqsədyönlü istifadə tərzidir.",
  ["Dildən istifadə tərzi", "Sözün mənası",
   "Cümlənin uzunluğu", "Şrift növü"], 1, None, 2),
 ("Reportaj hansı üslubun janrıdır?",
  "Mətbuat janrıdır — publisistik.",
  ["Publisistik üslubun", "Rəsmi üslubun",
   "Elmi üslubun", "Məişət üslubunun"], 1, None, 3),
],
"az-7-zerf": [
 ("«Bu gün», «sabah» sözləri hansı zərf növünə aiddir?",
  "Zaman zərfləridir.",
  ["Zaman", "Yer", "Miqdar", "Tərzi-hərəkət"],
  1, None, 2),
 ("«Ora-bura» zərfi hansı növdəndir?",
  "Yer zərfidir.",
  ["Yer", "Zaman", "Miqdar", "Səbəb"], 1, None, 2),
 ("Zərf hansı suallara cavab verir?",
  "Necə? nə vaxt? harada? nə qədər?",
  ["Necə? Nə vaxt? Harada? Nə qədər?", "Kim? Nə?",
   "Hansı? Neçənci?", "Kimi? Nəyi?"], 1, None, 2),
 ("«Birdən» sözü hansı zərf növüdür?",
  "Hərəkətin tərzini bildirir.",
  ["Tərzi-hərəkət", "Yer", "Zaman yalnız", "Say"],
  1, None, 3),
 ("Quruluşca mürəkkəb zərfə misal hansıdır?",
  "Gecə-gündüz mürəkkəb zərfdir.",
  ["gecə-gündüz", "tez", "gec", "indi"], 1, None, 3),
 ("«Çoxdan» zərfi nəyi bildirir?",
  "Keçmişdən başlanan zamanı.",
  ["Keçmişdən başlanan zamanı", "Yeri", "Tərzi",
   "Sayı"], 1, None, 2),
 ("Zərf feildən başqa hansı nitq hissəsini izah edə bilər?",
  "Sifəti də izah edir: çox gözəl.",
  ["Sifəti (çox gözəl)", "Nidanı", "Qoşmanı",
   "Bağlayıcını"], 1, None, 3),
 ("«Tamamilə» sözü hansı zərfdir?",
  "Miqdar-dərəcə zərfidir.",
  ["Miqdar zərfi", "Yer zərfi", "Zaman zərfi",
   "Zərf deyil"], 1, None, 3),
 ("Zərf cümlədə xəbər ola bilərmi?",
  "Bəli: iclas sabahdır.",
  ["Bəli, ola bilər", "Xeyr, heç vaxt", "Yalnız şeirdə",
   "Yalnız sualda"], 1, None, 3),
 ("«Gündüzlər» sözü zərf kimi nəyi bildirir?",
  "Hərəkətin icra vaxtını.",
  ["Hərəkətin vaxtını", "Hərəkətin yerini",
   "Hərəkətin səbəbini", "Əşyanın rəngini"], 1, None, 2),
],
"ing-7-friends": [
 ("«Honest» sözünün mənası nədir?",
  "Honest — dürüst.",
  ["Dürüst", "Yalançı", "Tənbəl", "Qorxaq"], 1, None, 2),
 ("«Help each other» ifadəsi nə deməkdir?",
  "Bir-birinə kömək etmək.",
  ["Bir-birinə kömək etmək", "Bir-birindən qaçmaq",
   "Mübahisə etmək", "Yarışmaq"], 1, None, 2),
 ("«Best friend» kimdir?",
  "Ən yaxın dost.",
  ["Ən yaxın dost", "Yeni tanış", "Qonşu yalnız",
   "Müəllim"], 1, None, 1),
 ("«Keep a secret» ifadəsi nə bildirir?",
  "Sirr saxlamağı.",
  ["Sirr saxlamaq", "Sirr yaymaq", "Məktub yazmaq",
   "Hədiyyə almaq"], 1, None, 2),
 ("«Kindness» sözü hansı nitq hissəsidir?",
  "İsimdir — xeyirxahlıq.",
  ["İsim (xeyirxahlıq)", "Feil", "Zərf", "Say"],
  1, None, 3),
 ("«Quarrel» feilinin mənası nədir?",
  "Küsüşmək, dalaşmaq.",
  ["Küsüşmək (dalaşmaq)", "Barışmaq", "Gülmək",
   "Oxumaq"], 1, None, 2),
 ("«Forgive» feili nə deməkdir?",
  "Bağışlamaq.",
  ["Bağışlamaq", "Unutmamaq", "Cəzalandırmaq",
   "Çağırmaq"], 1, None, 2),
 ("«We have been friends since childhood.» — dostluq nə vaxtdan davam edir?",
  "Uşaqlıqdan bəri.",
  ["Uşaqlıqdan", "Keçən həftədən", "Dünəndən",
   "Gələcəkdən"], 1, None, 3),
 ("«Respect» sözünün mənası nədir?",
  "Respect — hörmət.",
  ["Hörmət", "Nifrət", "Qorxu", "Zarafat"], 1, None, 2),
 ("«A true friend never lies.» cümləsinin mənası nədir?",
  "Əsl dost heç vaxt yalan danışmaz.",
  ["Əsl dost heç vaxt yalan danışmaz",
   "Dostlar həmişə yalan danışır", "Dost tapmaq asandır",
   "Yalan faydalıdır"], 1, None, 2),
],
"ing-7-future": [
 ("«Tomorrow» sözünün mənası nədir?",
  "Tomorrow — sabah.",
  ["Sabah", "Dünən", "Bu gün", "Keçən il"], 1, None, 1),
 ("«He will not come.» cümləsi nəyi bildirir?",
  "Gələcəkdə gəlməyəcəyini.",
  ["Gəlməyəcəyini", "Gəldiyini", "Gəlməkdə olduğunu",
   "Gəlmək istədiyini"], 1, None, 2),
 ("«Shall» köməkçi feili hansı əvəzliklərlə işlənə bilər?",
  "I və we ilə: Shall we go?",
  ["I və we ilə", "He və she ilə", "They ilə yalnız",
   "It ilə yalnız"], 1, None, 3),
 ("«Next year» ifadəsi nə deməkdir?",
  "Gələn il.",
  ["Gələn il", "Keçən il", "Bu həftə", "Hər ay"],
  1, None, 1),
 ("«Maybe» sözünün mənası nədir?",
  "Maybe — bəlkə.",
  ["Bəlkə", "Mütləq", "Heç vaxt", "Dərhal"], 1, None, 2),
 ("«People will travel to space.» — cümlə nə haqqındadır?",
  "Kosmosa səyahət proqnozu.",
  ["Kosmosa səyahət", "Dəniz səyahəti", "Keçmiş hadisə",
   "Məktəb həyatı"], 1, None, 2),
 ("«Soon» sözü nə deməkdir?",
  "Soon — tezliklə.",
  ["Tezliklə", "Gec", "Dünən", "Həmişə"], 1, None, 2),
 ("«Will she help us? — Yes, she ___.»",
  "Qısa cavab: will.",
  ["will", "does", "is", "can"], 1, None, 2),
 ("«Future» sözünün mənası nədir?",
  "Future — gələcək.",
  ["Gələcək", "Keçmiş", "İndi", "Zaman deyil"],
  1, None, 1),
 ("«Technology will change our lives.» cümləsində hansı fikir var?",
  "Texnologiya həyatımızı dəyişəcək.",
  ["Texnologiya həyatı dəyişəcək", "Texnologiya itəcək",
   "Həyat dəyişməz", "Keçmiş yaxşı idi"], 1, None, 2),
],
"ing-7-schools": [
 ("«Chemistry» hansı fənndir?",
  "Chemistry — kimya.",
  ["Kimya", "Tarix", "Musiqi", "İdman"], 1, None, 1),
 ("«Rules» sözünün mənası nədir?",
  "Rules — qaydalar.",
  ["Qaydalar", "Dərslər", "Kitablar", "Oyunlar"],
  1, None, 2),
 ("«Must» feili nəyi bildirir?",
  "Məcburiyyəti, vacibliyi.",
  ["Məcburiyyəti", "İstəyi yalnız", "Keçmişi",
   "Bacarığı"], 1, None, 2),
 ("«You must not be late.» cümləsi nəyi qadağan edir?",
  "Gecikməyi qadağan edir.",
  ["Gecikməyi", "Oxumağı", "Danışmağı", "Gəlməyi"],
  1, None, 2),
 ("«Mark» sözü məktəb kontekstində nəyi bildirir?",
  "Qiyməti bildirir.",
  ["Qiyməti", "Partanı", "Çantanı", "Fasiləni"],
  1, None, 2),
 ("«Pass the exam» ifadəsi nə deməkdir?",
  "İmtahandan keçmək.",
  ["İmtahandan keçmək", "İmtahandan kəsilmək",
   "İmtahanı təxirə salmaq", "İmtahan vermək istəməmək"],
  1, None, 2),
 ("Orta məktəb ingiliscə necə adlanır?",
  "Secondary school.",
  ["secondary school", "primary school", "kindergarten",
   "university"], 1, None, 2),
 ("«Homework» sözünün mənası nədir?",
  "Ev tapşırığı.",
  ["Ev tapşırığı", "Sinif işi", "İmtahan", "Fasilə"],
  1, None, 1),
 ("«Fail» feili imtahanda nəyi bildirir?",
  "Kəsilməyi bildirir.",
  ["Kəsilməyi", "Keçməyi", "Yazmağı", "Gülməyi"],
  1, None, 2),
 ("«PE» dərsində nə edilir?",
  "Physical Education — idman dərsidir.",
  ["İdmanla məşğul olunur", "Şeir əzbərlənir",
   "Rəsm çəkilir", "Mahnı oxunur yalnız"], 1, None, 2),
],
"ing-7-talent": [
 ("«Sing» feilinin mənası nədir?",
  "Sing — mahnı oxumaq.",
  ["Mahnı oxumaq", "Rəqs etmək", "Şəkil çəkmək",
   "Qaçmaq"], 1, None, 1),
 ("«Draw well» ifadəsi nəyi bildirir?",
  "Yaxşı şəkil çəkməyi.",
  ["Yaxşı şəkil çəkməyi", "Pis yazmağı", "Tez qaçmağı",
   "Ucadan oxumağı"], 1, None, 2),
 ("«Bad» sifətinin zərf forması hansıdır?",
  "Bad — badly.",
  ["badly", "bader", "badful", "bad"], 1, None, 3),
 ("«The most talented» ifadəsi hansı dərəcədədir?",
  "Üstünlük (superlativ) dərəcəsində.",
  ["Üstünlük (superlativ)", "Adi dərəcə",
   "Müqayisə dərəcəsi", "Dərəcəsizdir"], 1, None, 3),
 ("«Perform» feili nə deməkdir?",
  "Səhnədə çıxış etmək.",
  ["Çıxış etmək", "Oturmaq", "Yazmaq", "Satmaq"],
  1, None, 2),
 ("«Audience» sözünün mənası nədir?",
  "Audience — tamaşaçılar.",
  ["Tamaşaçılar", "Aktyorlar", "Müəllimlər", "Uşaqlar yalnız"],
  1, None, 2),
 ("«Practise every day» məsləhəti nəyi tövsiyə edir?",
  "Hər gün məşq etməyi.",
  ["Hər gün məşq etməyi", "Heç məşq etməməyi",
   "Yalnız yatmağı", "Dərsi buraxmağı"], 1, None, 2),
 ("«Slow» sözünün zərf forması hansıdır?",
  "Slow — slowly.",
  ["slowly", "slowy", "slowness", "slower yalnız"],
  1, None, 2),
 ("«Champion» sözünün mənası nədir?",
  "Champion — çempion.",
  ["Çempion", "Hakim", "Tamaşaçı", "Məşqçi"], 1, None, 1),
 ("«He plays chess brilliantly.» — «brilliantly» nəyi bildirir?",
  "Hərəkətin necə icra olunduğunu.",
  ["Necə oynadığını", "Nə vaxt oynadığını",
   "Harada oynadığını", "Kiminlə oynadığını"], 1, None, 3),
],
"ing-7-technology": [
 ("«Send a message» ifadəsi nə deməkdir?",
  "Mesaj göndərmək.",
  ["Mesaj göndərmək", "Mesaj silmək", "Zəng etmək",
   "Şəkil çəkmək"], 1, None, 1),
 ("«Click» feili nə bildirir?",
  "Düyməni basmağı (kliki).",
  ["Düyməni basmağı (klik)", "Yazmağı", "Oxumağı",
   "Söndürməyi"], 1, None, 2),
 ("«Save the file» əmri nə tələb edir?",
  "Faylı yadda saxlamağı.",
  ["Faylı yadda saxlamağı", "Faylı silməyi",
   "Faylı çap etməyi", "Faylı göndərməyi"], 1, None, 2),
 ("«Delete» feilinin mənası nədir?",
  "Delete — silmək.",
  ["Silmək", "Yaratmaq", "Kopyalamaq", "Açmaq"],
  1, None, 2),
 ("«Smartphone» nədir?",
  "Ağıllı telefon.",
  ["Ağıllı telefon", "Köhnə radio", "Kalkulyator",
   "Televizor"], 1, None, 1),
 ("«He is playing a game now.» cümləsi hansı zamandadır?",
  "İndiki davamedici — Present Continuous.",
  ["Present Continuous", "Past Simple", "Future",
   "Present Simple"], 1, None, 2),
 ("«Print» feili nə deməkdir?",
  "Print — çap etmək.",
  ["Çap etmək", "Silmək", "Rəngləmək", "Bağlamaq"],
  1, None, 2),
 ("«Wi-Fi» nə üçün lazımdır?",
  "Simsiz internetə qoşulmaq üçün.",
  ["Simsiz internetə qoşulmaq üçün", "Yemək bişirmək üçün",
   "İşıq yandırmaq üçün", "Səs yazmaq üçün"], 1, None, 2),
 ("«Camera» sözünün mənası nədir?",
  "Camera — kamera, fotoaparat.",
  ["Kamera (fotoaparat)", "Mikrofon", "Çap qurğusu",
   "Klaviatura"], 1, None, 1),
 ("«Upload» feili nəyi bildirir?",
  "Faylı şəbəkəyə yükləməyi.",
  ["Şəbəkəyə yükləməyi", "Şəbəkədən endirməyi",
   "Faylı silməyi", "Ekranı bağlamağı"], 1, None, 3),
],
"ing-7-travel": [
 ("«Passport» nə üçün lazımdır?",
  "Xarici ölkəyə səfər üçün.",
  ["Xarici ölkəyə getmək üçün", "Kitab oxumaq üçün",
   "Yemək almaq üçün", "Dərs demək üçün"], 1, None, 1),
 ("«Hotel room» ifadəsi nəyi bildirir?",
  "Otel otağını.",
  ["Otel otağını", "Sinif otağını", "Mətbəxi",
   "Qarajı"], 1, None, 1),
 ("«Arrive in Baku» ifadəsi nə deməkdir?",
  "Bakıya çatmaq.",
  ["Bakıya çatmaq", "Bakıdan getmək", "Bakını sevmək",
   "Bakıda yaşamaq"], 1, None, 2),
 ("«Tourist» kimdir?",
  "Səyahət edən şəxs — turist.",
  ["Səyahətçi (turist)", "Satıcı", "Həkim", "Sürücü"],
  1, None, 1),
 ("«Postcard» nədir?",
  "Postcard — açıqça.",
  ["Açıqça", "Qəzet", "Bilet", "Pul"], 1, None, 2),
 ("«Depart» feilinin mənası nədir?",
  "Depart — yola düşmək.",
  ["Yola düşmək", "Çatmaq", "Qalmaq", "Dincəlmək"],
  1, None, 3),
 ("«We are going to fly to Istanbul.» — onlar necə gedəcəklər?",
  "Fly — təyyarə ilə.",
  ["Təyyarə ilə", "Qatarla", "Gəmi ilə", "Piyada"],
  1, None, 2),
 ("«Sea view» ifadəsi nəyi bildirir?",
  "Dəniz mənzərəsini.",
  ["Dəniz mənzərəsini", "Dağ yolunu", "Şəhər səsini",
   "Meşə havasını"], 1, None, 2),
 ("«Ticket office» nədir?",
  "Bilet kassası.",
  ["Bilet kassası", "Gözləmə zalı", "Yemək zalı",
   "Kitabxana"], 1, None, 2),
 ("«Journey by train» ifadəsi hansı səyahəti bildirir?",
  "Qatarla səyahəti.",
  ["Qatarla səyahəti", "Təyyarə ilə uçuşu",
   "Gəmi səyahətini", "Piyada gəzintini"], 1, None, 1),
],
"inf-7-informasiya": [
 ("3 bit neçə fərqli vəziyyəti kodlaşdıra bilər?",
  "2³ = 8 vəziyyət.",
  ["8", "3", "6", "2"], 1, None, 3),
 ("İnformasiyanın obyektivlik xassəsi nə deməkdir?",
  "Şəxsi rəydən asılı olmaması.",
  ["Şəxsi rəydən asılı olmaması", "Uzun olması",
   "Şəkilli olması", "Sürətli ötürülməsi"], 1, None, 3),
 ("Köhnəlmiş məlumat hansı xassəsini itirir?",
  "Aktuallığını itirir.",
  ["Aktuallığı", "Rəngini", "Səsini", "Ölçüsünü"],
  1, None, 2),
 ("Bayt bitdən neçə dəfə böyükdür?",
  "1 bayt = 8 bit.",
  ["8 dəfə", "2 dəfə", "10 dəfə", "1024 dəfə"],
  1, None, 2),
 ("Roma rəqəmləri hansı say sisteminə aiddir?",
  "Qeyri-mövqeli say sisteminə.",
  ["Qeyri-mövqeli", "Mövqeli", "İkilik", "Onluq"],
  1, None, 3),
 ("Mövqeli say sistemində rəqəmin qiyməti nədən asılıdır?",
  "Ədəddə durduğu mövqedən.",
  ["Durduğu mövqedən", "Rəngindən", "Ölçüsündən",
   "Şriftindən"], 1, None, 3),
 ("İkilik say sistemi kompüter üçün niyə əlverişlidir?",
  "İki vəziyyəti (var/yox) texniki gerçəkləşdirmək asandır.",
  ["İki vəziyyət texniki asan gerçəkləşir",
   "Daha qısa yazılır", "Daha gözəldir",
   "Təsadüfi seçilib"], 1, None, 3),
 ("50 simvolluq mesaj (hər simvol 1 bayt) nə qədər yer tutar?",
  "50 bayt yer tutar.",
  ["50 bayt", "50 bit", "5 bayt", "1 KB"], 1, None, 2),
 ("İnformasiyanın anlaşıqlılığı nədən asılıdır?",
  "Qəbul edənin hazırlıq səviyyəsindən.",
  ["Qəbul edənin hazırlığından", "Kağızın rəngindən",
   "Saatdan", "Havadan"], 1, None, 3),
 ("Onaltılıq say sistemində neçə simvol işlənir?",
  "16 simvol: 0-9 və A-F.",
  ["16 simvol", "6 simvol", "60 simvol", "10 simvol"],
  1, None, 3),
],
"inf-7-internet": [
 ("Bulud texnologiyası hansı imkanı verir?",
  "Faylları şəbəkədə saxlayıb hər yerdən açmaq.",
  ["Faylları şəbəkədə saxlamaq", "Yağış yağdırmaq",
   "Kompüteri soyutmaq", "Ekranı böyütmək"], 1, None, 3),
 ("E-hökumət xidmətləri vətəndaşa nə verir?",
  "Sənədləri onlayn almaq imkanı.",
  ["Sənədləri onlayn almaq imkanı", "Pulsuz kompüter",
   "İnternetsiz xidmət", "Yalnız oyun"], 1, None, 2),
 ("Videokonfrans nədir?",
  "Uzaqdan görüntülü görüş.",
  ["Uzaqdan görüntülü görüş", "Səssiz məktub",
   "Çap olunmuş sənəd", "Radio verilişi"], 1, None, 2),
 ("E-məktubun surətini başqa ünvana göndərmək üçün hansı sahə var?",
  "CC (surət) sahəsi.",
  ["CC (surət)", "Subject", "Parol", "Spam"],
  1, None, 3),
 ("İnternet mağazadan istifadə edərkən nəyə diqqət edilməlidir?",
  "Saytın etibarlılığına.",
  ["Saytın etibarlılığına", "Saytın rənginə",
   "Reklamın sayına", "Heç nəyə"], 1, None, 2),
 ("Şəbəkə etikası (netiket) nəyi tənzimləyir?",
  "Onlayn ünsiyyət qaydalarını.",
  ["Onlayn davranış qaydalarını", "Elektrik sərfini",
   "Kompüterin sürətini", "Şriftləri"], 1, None, 2),
 ("İKT təhsildə hansı imkanı yaradır?",
  "Elektron dərsliklər və onlayn dərslər.",
  ["Elektron dərsliklərə çıxış", "Dərsləri ləğv etmək",
   "Kitabları yandırmaq", "Heç nə"], 1, None, 2),
 ("Fişinq məktubların məqsədi nədir?",
  "İstifadəçinin şəxsi məlumatlarını ələ keçirmək.",
  ["Şəxsi məlumatları oğurlamaq", "Hədiyyə vermək",
   "Təhsil vermək", "Xəbər çatdırmaq"], 1, None, 3),
 ("Onlayn lüğətlərin üstünlüyü nədir?",
  "Sözü anında tapmaq olur.",
  ["Sürətli axtarış", "Ağır olması", "Baha olması",
   "Yavaş işləməsi"], 1, None, 2),
 ("Böyük faylı e-poçtla göndərmək mümkün olmayanda nə etməli?",
  "Bulud saxlancına yükləyib keçidi paylaşmaq.",
  ["Bulud keçidi ilə paylaşmaq", "Faylı silmək",
   "Kompüteri dəyişmək", "Çap edib göndərmək"],
  1, None, 3),
],
"inf-7-kompyuter": [
 ("Mikrofon hansı qurğular qrupuna aiddir?",
  "Səsi daxil edir — giriş qurğusudur.",
  ["Giriş", "Çıxış", "Yaddaş", "Emal"], 1, None, 2),
 ("Səsucaldan (dinamik) hansı qurğudur?",
  "Səsi xaric edir — çıxış qurğusudur.",
  ["Çıxış", "Giriş", "Yaddaş", "Şəbəkə"], 1, None, 2),
 ("Faylın ölçüsü hansı vahidlərlə ölçülür?",
  "Bayt, kilobayt, meqabaytla.",
  ["Bayt, KB, MB", "Metr, sm", "Kq, qram",
   "Saat, dəqiqə"], 1, None, 2),
 ("Faylı yenidən adlandırmaq mümkündürmü?",
  "Bəli, Rename əməli ilə.",
  ["Bəli (Rename əməli ilə)", "Xeyr, heç vaxt",
   "Yalnız silməklə", "Yalnız çap etməklə"], 1, None, 2),
 ("Kəsmə (Cut) və kopyalama (Copy) əməllərinin fərqi nədir?",
  "Kəsmədə fayl əvvəlki yerdən götürülür.",
  ["Kəsmədə fayl köhnə yerdən silinir", "Fərq yoxdur",
   "Kopyalama faylı silir", "Kəsmə iki nüsxə yaradır"],
  1, None, 3),
 ("Arxivləşdirmə nə üçün istifadə olunur?",
  "Faylların həcmini kiçiltmək üçün.",
  ["Faylın həcmini kiçiltmək üçün", "Faylı rəngləmək üçün",
   "Səsi artırmaq üçün", "Ekranı təmizləmək üçün"],
  1, None, 3),
 ("Noutbukla stolüstü kompüterin əsas fərqi nədir?",
  "Noutbuk daşınandır.",
  ["Noutbuk daşınandır", "Noutbuk proqram işlətmir",
   "Stolüstü ekransızdır", "Fərq yoxdur"], 1, None, 2),
 ("Monitorun ölçüsü nə ilə ölçülür?",
  "Ekranın dioqanalı düymlə ölçülür.",
  ["Düymlə (diaqonal)", "Kiloqramla", "Litrlə",
   "Baytla"], 1, None, 3),
 ("Proyektor hansı qurğulara aiddir?",
  "Təsviri ekrana verir — çıxış qurğusudur.",
  ["Çıxış qurğusu", "Giriş qurğusu", "Yaddaş qurğusu",
   "Şəbəkə qurğusu"], 1, None, 2),
 ("Kompüter yüklənəndən sonra görünən əsas ekran necə adlanır?",
  "İş masası adlanır.",
  ["İş masası", "Səbət", "Qovluq", "Fayl"], 1, None, 2),
],
"inf-7-proqramlasdirma": [
 ("Altproqramı çağırmaq nə deməkdir?",
  "Onu adı ilə icra etmək.",
  ["Onu adı ilə icra etmək", "Onu silmək",
   "Onu çap etmək", "Adını dəyişmək"], 1, None, 3),
 ("Beşbucaqlı çəkmək üçün dönmə bucağı neçə dərəcə olmalıdır?",
  "360 : 5 = 72 dərəcə.",
  ["72", "60", "90", "108"], 1, None, 3),
 ("Proqramda sintaksis xətası nədir?",
  "Dilin yazılış qaydasının pozulması.",
  ["Yazılış qaydasının pozulması", "Kompüterin sınması",
   "Ekranın sönməsi", "Faylın itməsi"], 1, None, 3),
 ("Məntiqi xəta nə ilə nəticələnir?",
  "Proqram işləyir, amma nəticə səhv olur.",
  ["Proqram işləyir, nəticə səhv olur",
   "Proqram heç açılmır", "Kompüter sönür",
   "Heç nə baş vermir"], 1, None, 3),
 ("Dəyişənin qiymətini proqram gedişində dəyişmək olarmı?",
  "Bəli, mənimsətmə ilə.",
  ["Bəli, mənimsətmə ilə", "Xeyr, heç vaxt",
   "Yalnız başlanğıcda", "Yalnız sonda"], 1, None, 3),
 ("Altproqrama ötürülən qiymət necə adlanır?",
  "Parametr adlanır.",
  ["Parametr", "Nəticə", "Şərh", "Fayl"], 1, None, 3),
 ("Proqramı hissələrə bölmək nəyi asanlaşdırır?",
  "Yoxlamanı və düzəlişi.",
  ["Yoxlamanı və düzəlişi", "Heç nəyi",
   "Yalnız çapı", "Yalnız rəngi"], 1, None, 3),
 ("ALPLogo-da «təmizlə» əmri nə edir?",
  "Çəkilmiş hər şeyi ekrandan silir.",
  ["Ekranı təmizləyir", "Bağanı silir",
   "Proqramı bağlayır", "Rəngi dəyişir"], 1, None, 2),
 ("«Qələmi endir» əmrindən sonra bağa necə hərəkət edir?",
  "Hərəkət edərkən xətt çəkir.",
  ["Xətt çəkərək", "Xəttsiz", "Geriyə yalnız",
   "Hərəkət etmir"], 1, None, 2),
 ("Kvadratın tərəfini dəyişən kimi versək nə qazanarıq?",
  "Eyni proqramla istənilən ölçüdə kvadrat.",
  ["İstənilən ölçüdə kvadrat çəkmək", "Heç nə",
   "Yalnız kiçik kvadrat", "Rəngli ekran"], 1, None, 3),
],
"inf-7-tetbiqi": [
 ("Cədvəldə sütun başlığı nə üçündür?",
  "Sütundakı məlumatın növünü göstərir.",
  ["Məlumatın növünü göstərmək üçün", "Bəzək üçün",
   "Yer tutmaq üçün", "Vacib deyil"], 1, None, 2),
 ("Dairəvi diaqram nə zaman seçilir?",
  "Hissələrin tamda payını göstərəndə.",
  ["Hissələrin tamda payını göstərəndə",
   "Zamanla dəyişməni göstərəndə", "Mətn yazanda",
   "Şəkil çəkəndə"], 1, None, 3),
 ("Sütunlu diaqram nə üçün əlverişlidir?",
  "Kəmiyyətləri müqayisə etmək üçün.",
  ["Kəmiyyətləri müqayisə etmək üçün", "Mahnı üçün",
   "Mətn yığmaq üçün", "Rəsm üçün"], 1, None, 2),
 ("Cədvəldən sətri silmək mümkündürmü?",
  "Bəli, sətri seçib silmək olar.",
  ["Bəli, seçib silmək olar", "Xeyr, olmaz",
   "Yalnız sonuncunu", "Yalnız birincini"], 1, None, 2),
 ("Şəkli mətndə sağa və ya sola düzləndirmək olarmı?",
  "Bəli, yerləşmə parametrləri ilə.",
  ["Bəli, yerləşmə parametrləri ilə", "Xeyr",
   "Yalnız çapda", "Yalnız slaydda"], 1, None, 2),
 ("Slaydda animasiya nəyə tətbiq oluna bilər?",
  "Mətnə və obyektlərə.",
  ["Mətn və obyektlərə", "Yalnız fona",
   "Heç nəyə", "Yalnız səsə"], 1, None, 2),
 ("Təqdimatı nümayiş rejiminə keçirən düymə hansıdır?",
  "F5 düyməsi.",
  ["F5", "Esc", "Delete", "Caps Lock"], 1, None, 3),
 ("Xanalardakı ədədlərlə hesablama üçün hansı proqram daha uyğundur?",
  "Elektron cədvəl proqramı.",
  ["Elektron cədvəl (Excel)", "Paint", "Bloknot",
   "Media pleyer"], 1, None, 3),
 ("Cədvəlin sütun eni dəyişdirilə bilərmi?",
  "Bəli, sərhədi çəkməklə.",
  ["Bəli, sərhədləri çəkməklə", "Xeyr, sabitdir",
   "Yalnız silməklə", "Yalnız yeni cədvəldə"],
  1, None, 2),
 ("Diaqramda sütunun hündürlüyü nəyi göstərir?",
  "Qiymətin böyüklüyünü.",
  ["Qiymətin böyüklüyünü", "Rəngin adını",
   "Şriftin ölçüsünü", "Heç nəyi"], 1, None, 2),
],
}
for _k, _v in ELAVE.items():
    SUALLAR[_k] = SUALLAR[_k] + _v


MOVZULAR += [
]

YENI_TARIX = {
}
for _k, _v in YENI_TARIX.items():
    SUALLAR[_k] = _v




# 30 sual/movzu proqrami: az, ing ve tarix movzularina 10 elave sual.
ELAVE30 = {
"az-7-feil-qurulus": [
 ("«Duymaq» feili quruluşca hansıdır?",
  "Kök halında olan sadə feildir.",
  ["Sadə feildir", "Düzəltmə feildir", "Mürəkkəb feildir",
   "Feil deyil"], 1, None, 1),
 ("«Qulaq asmaq» quruluşca hansı feildir?",
  "İki sözdən ibarət mürəkkəb feildir.",
  ["Mürəkkəb feildir", "Sadə feildir", "Düzəltmə feildir",
   "Köməkçi feildir"], 1, None, 2),
 ("«Yaşıllaşmaq» feili hansı nitq hissəsindən düzəlib?",
  "Yaşıl sifətindən yaranıb.",
  ["Sifətdən", "İsimdən", "Saydan", "Zərfdən"], 1, None, 2),
 ("Hansı feil «nəyi?» sualını tələb edir: gətirmək, yoxsa yatmaq?",
  "Gətirmək təsirli feildir.",
  ["Gətirmək", "Yatmaq", "Hər ikisi", "Heç biri"],
  1, None, 2),
 ("Məchul feildə iş görən bəlli olurmu?",
  "Məchulda icraçı göstərilmir.",
  ["Xeyr, bəlli olmur", "Bəli, həmişə", "Yalnız cəmdə",
   "Yalnız keçmişdə"], 1, None, 3),
 ("«Öyünmək» feili hansı məna növündədir?",
  "Hərəkət subyektin özünə qayıdır.",
  ["Qayıdış növündə", "Məchul növdə", "Qarşılıqlı növdə",
   "İcbar növdə"], 1, None, 3),
 ("«-ış» şəkilçili «baxışmaq» feili hansı icranı bildirir?",
  "Hərəkət qarşılıqlı icra olunur.",
  ["Qarşılıqlı icranı", "Tək icranı", "Məchul icranı",
   "İcra bildirmir"], 1, None, 2),
 ("Feildən feil düzəldən şəkilçiyə misal hansıdır?",
  "Yaz + dır = yazdırmaq.",
  ["-dır (yazdır)", "-lıq (dostluq)", "-çı (əkinçi)",
   "-lı (duzlu)"], 1, None, 2),
 ("«Susmaq» feilini təsirli etmək üçün hansı şəkilçi artırılır?",
  "Sus + dur = susdurmaq (kimi? nəyi?).",
  ["-dur (susdur)", "-ma (susma)", "-ub (susub)",
   "-an (susan)"], 1, None, 3),
 ("Feilin başlanğıc forması hansı şəkilçi ilə göstərilir?",
  "Məsdər: -maq, -mək.",
  ["-maq, -mək ilə", "-dı, -di ilə", "-acaq ilə",
   "-ır, -ir ilə"], 1, None, 1),
],
"az-7-feil-zaman": [
 ("«Baxmışdır» feili hansı zaman formasıdır?",
  "-mış nəqli keçmişin şəkilçisidir.",
  ["Nəqli keçmiş", "Şühudi keçmiş", "İndiki zaman",
   "Qəti gələcək"], 1, None, 2),
 ("«Gələrəm» və «gələcəyəm» formalarının fərqi nədir?",
  "Biri qeyri-qəti, digəri qəti gələcəkdir.",
  ["Qətilik dərəcəsi", "Şəxs", "Kəmiyyət", "İnkar"],
  1, None, 3),
 ("«İşləyirdilər» feilində hərəkəti neçə nəfər icra edir?",
  "-lər III şəxsin cəmini bildirir.",
  ["Çox nəfər (onlar)", "Bir nəfər", "İki nəfər",
   "Bəlli deyil"], 1, None, 2),
 ("«Mütləq gedəcəyəm» cümləsində gələcəyin hansı forması var?",
  "-əcək qəti gələcəyi bildirir.",
  ["Qəti gələcək", "Qeyri-qəti gələcək", "İndiki zaman",
   "Keçmiş zaman"], 1, None, 2),
 ("«Oxuyacaqdı» forması nəyi bildirir?",
  "Keçmişdə qalmış niyyəti bildirir.",
  ["Keçmişdə niyyəti", "Gələcək əmri", "İndiki adəti",
   "Sual çalarını"], 1, None, 3),
 ("Zaman şəkilçiləri feilin hansı hissəsinə artırılır?",
  "Kökə və ya düzəltmə əsasa artırılır.",
  ["Kökünə və ya əsasına", "Sonundakı nöqtəyə",
   "Əvvəlinə", "Şəxs şəkilçisindən sonra"], 1, None, 2),
 ("«Hazırda» sözü hansı zamanla işlənir?",
  "İndiki zamanı dəqiqləşdirir.",
  ["İndiki zamanla", "Şühudi keçmişlə", "Qəti gələcəklə",
   "Heç biri ilə"], 1, None, 2),
 ("Feilin zamanı danışıq anına görə nəyi göstərir?",
  "Hərəkətin nə vaxt baş verdiyini.",
  ["Hərəkətin vaxtını", "Hərəkətin yerini", "İcraçının adını",
   "Səbəbini"], 1, None, 1),
 ("«Deyirlər ki, gələcəkmiş» — «gələcəkmiş» nəyi bildirir?",
  "Eşidilmə, rəvayət çalarını verir.",
  ["Eşidilmə (rəvayət)", "Qətiliyi", "Əmri", "İnkarı"],
  1, None, 3),
 ("«-q» şəxs şəkilçisi hansı şəxsi bildirir («qaçdıq»)?",
  "Biz — I şəxsin cəmi.",
  ["I şəxsin cəmini", "II şəxsin təkini", "III şəxsin cəmini",
   "Şəxs bildirmir"], 1, None, 2),
],
"az-7-feil-sekil": [
 ("«Oxuyaydım» feili hansı şəkildədir?",
  "-a + ydı arzu şəklinin hekayəsidir.",
  ["Arzu şəklində", "Əmr şəklində", "Xəbər şəklində",
   "Vacib şəklində"], 1, None, 2),
 ("«Getsin» feili hansı şəxsdə əmrdir?",
  "-sın III şəxsin təkinə aiddir.",
  ["III şəxsin təkində", "I şəxsin təkində",
   "II şəxsin cəmində", "I şəxsin cəmində"], 1, None, 2),
 ("Vacib şəkli nəyi bildirir?",
  "İşin görülməsinin vacibliyini.",
  ["Görülməsi vacib işi", "Arzunu", "Şərti", "Xahişi"],
  1, None, 2),
 ("Lazım şəkli hansı çaları verir?",
  "İşin görüləcəyinin lazımlığını.",
  ["Görüləcək işin lazımlığını", "Qadağanı", "Sualı",
   "Təəccübü"], 1, None, 3),
 ("«Yağış yağsaydı» cümləsindəki feil hansı şəkildədir?",
  "-sa şərt şəklinin əlamətidir.",
  ["Şərt şəklində", "Əmr şəklində", "Lazım şəklində",
   "Xəbər şəklində"], 1, None, 2),
 ("Feil şəkilləri arasında yalnız hansı bütün zamanlara malikdir?",
  "Xəbər şəkli üç zamanda dəyişir.",
  ["Xəbər şəkli", "Əmr şəkli", "Arzu şəkli", "Şərt şəkli"],
  1, None, 3),
 ("«Oxuginən» tipli formalar hansı üsluba xasdır?",
  "Canlı danışıqda işlənir.",
  ["Danışıq üslubuna", "Elmi üsluba", "Rəsmi üsluba",
   "Publisistik üsluba"], 1, None, 3),
 ("«Gedək!» feili hansı məzmunu daşıyır?",
  "Birgə hərəkətə çağırış bildirir.",
  ["Çağırış-təklifi", "Qadağanı", "Peşmanlığı", "Sualı"],
  1, None, 2),
 ("Əmr şəklinə «-ma» artırsaq nə alınar?",
  "İnkar əmr — qadağa: getmə!",
  ["Qadağa (getmə!)", "Arzu", "Şərt", "Vaciblik"],
  1, None, 2),
 ("«Bilməliyəm» feilində şəkilçilərin ardıcıllığı necədir?",
  "Əvvəl şəkil (-məli), sonra şəxs (-yəm).",
  ["Şəkil + şəxs", "Şəxs + şəkil", "Zaman + hal",
   "Hal + mənsubiyyət"], 1, None, 3),
],
"az-7-zerf": [
 ("«Ləng» sözü hansı zərf növündəndir?",
  "Hərəkətin tərzini bildirir.",
  ["Tərzi-hərəkət zərfi", "Zaman zərfi", "Yer zərfi",
   "Miqdar zərfi"], 1, None, 2),
 ("«Hərdən» sözü hərəkətin hansı xüsusiyyətini göstərir?",
  "Arabir təkrarlanan zamanı bildirir.",
  ["Təkrarlıq (zaman)", "Yeri", "Səbəbi", "Məqsədi"],
  1, None, 2),
 ("Miqdar zərfinə misal göstərin.",
  "Bir qədər — miqdar bildirir.",
  ["Bir qədər", "Dünən", "Burada", "Sakitcə"], 1, None, 2),
 ("«Ən tez» ifadəsində zərf hansı dərəcədədir?",
  "Ən sözü üstünlük yaradır.",
  ["Üstünlük dərəcəsində", "Azaltma dərəcəsində",
   "Adi dərəcədə", "Dərəcəsiz"], 1, None, 3),
 ("«Səhər-səhər» zərfi quruluşca necədir?",
  "Sözün təkrarından yaranıb.",
  ["Mürəkkəbdir (təkrar)", "Sadədir", "Düzəltmədir",
   "Alınmadır"], 1, None, 2),
 ("«Necə oxuyur?» sualına cavab verən nitq hissəsi hansıdır?",
  "Tərz sualına zərf cavab verir.",
  ["Zərf", "Say", "Əvəzlik", "Qoşma"], 1, None, 1),
 ("«Dünənki» sözü zərf, yoxsa sifətdir?",
  "-ki şəkilçisi ilə təyin olur: sifətdir.",
  ["Sifətdir (şəkilçili)", "Zərfdir", "Feildir", "Saydır"],
  1, None, 3),
 ("«Yuxarı qalxdı» cümləsində «yuxarı» hansı məna bildirir?",
  "Hərəkətin istiqamətini göstərir.",
  ["İstiqamət (yer)", "Zaman", "Miqdar", "Səbəb"],
  1, None, 2),
 ("Zərf düzəldən «-ca, -cə» şəkilçisinə misal hansıdır?",
  "Sakit + cə = sakitcə.",
  ["Sakitcə", "Sakitlik", "Sakitləşmək", "Sakitdir"],
  1, None, 2),
 ("«Günü-gündən» zərfi nəyi bildirir?",
  "Getdikcə artmanı bildirir.",
  ["Tədricən artmanı", "Yerin adını", "Sayı", "Şərti"],
  1, None, 3),
],
"az-7-qosma-baglayici": [
 ("«Axşama kimi» ifadəsində «kimi» nəyi bildirir?",
  "Zamanın son həddini bildirir.",
  ["Zaman həddini", "Bənzətməni", "Səbəbi", "Məkanı"],
  1, None, 3),
 ("«Ki» bağlayıcısı hansı yazılış xüsusiyyətinə malikdir?",
  "Sözdən ayrı yazılır.",
  ["Ayrı yazılır", "Bitişik yazılır", "Defislə yazılır",
   "Böyük hərflə yazılır"], 1, None, 2),
 ("Bərabərhüquqlu tərəfləri hansı bağlayıcılar birləşdirir?",
  "Tabesizlik bağlayıcıları birləşdirir.",
  ["Tabesizlik bağlayıcıları", "Tabelilik bağlayıcıları",
   "Qoşmalar", "Ədatlar"], 1, None, 2),
 ("«Gah … gah da» bağlayıcısı hansı mənanı verir?",
  "Hərəkətlərin növbələşməsini bildirir.",
  ["Növbələşməni", "Səbəbi", "İnkarı", "Şərti"],
  1, None, 2),
 ("«Qayıq ilə» ifadəsi qısaldılanda hansı forma düzgündür?",
  "Samitdən sonra -la: qayıqla.",
  ["Qayıqla", "Qayıqilə", "Qayıqnan", "Qayıq-la"],
  1, None, 2),
 ("«Bundan ötrü» ifadəsində «ötrü» hansı hallı sözlə işlənib?",
  "Çıxışlıq halda olan sözlə işlənir.",
  ["Çıxışlıq hallı", "Adlıq hallı", "Yiyəlik hallı",
   "Yerlik hallı"], 1, None, 3),
 ("Qarşılaşdırma bağlayıcılarına misal hansı cütdür?",
  "Amma, lakin — qarşılaşdırma bildirir.",
  ["Amma, lakin", "Və, ilə", "Ya, ya da", "Çünki, ona görə"],
  1, None, 2),
 ("«Əgər oxusan…» cümləsində feil hansı şəkildədir?",
  "Əgər şərt bağlayıcısı ilə şərt şəkli işlənir.",
  ["Şərt şəklindədir", "Əmr şəklindədir",
   "Arzu şəklindədir", "Xəbər şəklindədir"], 1, None, 3),
 ("Qoşma ilə bağlayıcının fərqi nədir?",
  "Qoşma sözə qoşulub məna yaradır.",
  ["Qoşma sözlə işlənir", "Bağlayıcı hallanır",
   "Fərq yoxdur", "Qoşma cümlə qurur"], 1, None, 3),
 ("«Yəni» sözü hansı vəzifəni daşıyır?",
  "İzah-aydınlaşdırma bildirir.",
  ["Aydınlaşdırma bağlayıcısı", "Sual ədatı", "Nida",
   "Qoşma"], 1, None, 3),
],
"az-7-edat-modal": [
 ("«Sən ki bilirsən» cümləsində «ki» nəyi bildirir?",
  "Fikri qüvvətləndirir.",
  ["Qüvvətləndirmə çaları", "Sual", "İnkar", "Zaman"],
  1, None, 2),
 ("«Deyəsən yağış yağacaq» cümləsində «deyəsən» hansı münasibəti bildirir?",
  "Ehtimal-güman bildirir.",
  ["Güman", "Qətilik", "Sevinc", "Əmr"], 1, None, 2),
 ("«Heç» ədatı hansı mənanı gücləndirir?",
  "İnkar mənasını gücləndirir.",
  ["İnkarı", "Təsdiqi", "Sualı", "Arzunu"], 1, None, 2),
 ("«Sanki» sözü nəyi bildirir?",
  "Bənzətmə və güman çalarını verir.",
  ["Bənzətmə-güman", "Qadağa", "Sevinc", "Kədər"],
  1, None, 2),
 ("Fikrin sonunu, nəticəsini bildirən modal söz hansıdır?",
  "Nəhayət — yekun bildirir.",
  ["Nəhayət", "Bəlkə", "Guya", "Məgər"], 1, None, 2),
 ("Ədatlar hallanıb dəyişirmi?",
  "Köməkçi nitq hissələri dəyişmir.",
  ["Xeyr, dəyişmir", "Bəli, hallanır", "Bəli, cəmlənir",
   "Yalnız təsriflənir"], 1, None, 2),
 ("«Axır ki» ifadəsi hansı hissi çatdırır?",
  "Gözlənilən nəticənin rahatlığını.",
  ["Rahatlıq-sevinc", "Qorxu", "Qəzəb", "Şübhə"],
  1, None, 3),
 ("«Elə» ədatı («elə bu gün») nəyi bildirir?",
  "Dəqiqləşdirmə bildirir.",
  ["Dəqiqləşdirmə", "İnkar", "Kədər", "Bənzətmə"],
  1, None, 3),
 ("«Doğrudan da» modal sözü hansı münasibəti bildirir?",
  "Yəqinliyi təsdiq edir.",
  ["Təsdiq-yəqinlik", "Şübhə", "Təəssüf", "Güman"],
  1, None, 2),
 ("«Məni də apar» cümləsində «də» nəyi bildirir?",
  "Əlavə olunma mənası verir.",
  ["Əlavə olunmanı", "İnkarı", "Sualı", "Qadağanı"],
  1, None, 2),
],
"az-7-nida": [
 ("«Ura!» ilə «Vay!» nidalarının fərqi nədir?",
  "Biri sevinc, digəri kədər bildirir.",
  ["Sevinc və kədər", "Hər ikisi sualdır",
   "Hər ikisi əmrdir", "Fərq yoxdur"], 1, None, 2),
 ("Yamsılamadan yaranan isim: «pıçıltı» sözünün əsası nədir?",
  "Pıç-pıç yamsılamasından yaranıb.",
  ["Pıç-pıç yamsılaması", "Pıçaq sözü", "Alınma söz",
   "Şəkilçi"], 1, None, 3),
 ("İtin səsini bildirən yamsılama hansıdır?",
  "Ham-ham — it səsidir.",
  ["Ham-ham", "Mə-ə", "Cik-cik", "Miyov"], 1, None, 1),
 ("Nidalar hansı intonasiya ilə deyilir?",
  "Hiss-həyəcan intonasiyası ilə.",
  ["Hiss-həyəcanla", "Sadalama ilə", "Sualsız", "Sakit"],
  1, None, 2),
 ("«Aman!» nidası nəyi bildirir?",
  "Təlaş, kömək istəyi bildirir.",
  ["Kömək çağırışı-təlaş", "Sevinc", "Alqış", "Razılıq"],
  1, None, 2),
 ("«Gur-gur» yamsılamasından hansı feil yaranır?",
  "Guruldamaq feili yaranır.",
  ["Guruldamaq", "Gurluq", "Gurlu", "Gur"], 1, None, 2),
 ("«Of, yoruldum!» cümləsində nidadan sonra hansı işarə var?",
  "Nida vergüllə ayrılıb.",
  ["Vergül işarəsi", "Nöqtə", "Defis", "İki nöqtə"],
  1, None, 2),
 ("«Şappıltı» sözü nəyin səsini bildirir?",
  "Suya düşən əşyanın səsini.",
  ["Suya düşmənin", "Quş səsini", "Külək səsini",
   "Zəng səsini"], 1, None, 2),
 ("«Ay aman!» ifadəsi hansı nitq hissələrindəndir?",
  "İki sözdən ibarət nidadır.",
  ["Mürəkkəb nidadır", "Bağlayıcıdır", "Qoşmadır",
   "Ədatdır"], 1, None, 3),
 ("Bədii əsərlərdə nidalar nə üçün işlənir?",
  "Obrazın hisslərini canlandırır.",
  ["Emosionallıq üçün", "Cümləni qısaltmaq üçün",
   "Say bildirmək üçün", "Hallandırmaq üçün"], 1, None, 2),
],
"az-7-uslub": [
 ("Məktub hansı üsluba aid ola bilər?",
  "Şəxsi məktublar məişət üslubundadır.",
  ["Məişət üslubuna", "Elmi üsluba yalnız",
   "Rəsmi üsluba yalnız", "Heç birinə"], 1, None, 2),
 ("Elmi mətndə terminlərin rolu nədir?",
  "Fikri dəqiq çatdırır.",
  ["Dəqiqlik yaratmaq", "Bəzək vurmaq", "Gülüş doğurmaq",
   "Sirr saxlamaq"], 1, None, 2),
 ("«Külək qız kimi nazlanırdı» cümləsi hansı üsluba xasdır?",
  "Bədii təsvir vasitəsi işlənib.",
  ["Bədii üsluba", "Rəsmi üsluba", "Elmi üsluba",
   "Sənəd üslubuna"], 1, None, 2),
 ("Rəsmi məktublarda müraciət necə olmalıdır?",
  "Rəsmi qaydalara uyğun, nəzakətli.",
  ["Rəsmi və nəzakətli", "Zarafatyana", "Qısaltmalarla",
   "Dialektlə"], 1, None, 2),
 ("Nitqdə söz ehtiyatının zənginliyi nəyə xidmət edir?",
  "Fikri ifadəli çatdırmağa.",
  ["İfadəliliyə", "Sürətə", "Səhvlərə", "Uzunluğa"],
  1, None, 3),
 ("Publisistik üslubun auditoriyası kimdir?",
  "Geniş oxucu-tamaşaçı kütləsi.",
  ["Geniş kütlə", "Yalnız alimlər", "Yalnız məmurlar",
   "Yalnız uşaqlar"], 1, None, 2),
 ("Arayış almaq üçün hansı sənəd yazılır?",
  "Rəsmi üslubda ərizə yazılır.",
  ["Ərizə", "Şeir", "Hekayə", "Reportaj"], 1, None, 2),
 ("Bədii təsvir vasitələrinə nə daxildir?",
  "Epitet, təşbeh, məcaz və s.",
  ["Epitet, təşbeh, məcaz", "Düsturlar", "Cədvəllər",
   "Qanun maddələri"], 1, None, 2),
 ("Natiqin səs tonu necə olmalıdır?",
  "Aydın və yerinə görə dəyişən.",
  ["Aydın və dəyişkən", "Həmişə pıçıltı ilə",
   "Həmişə qışqırıqla", "Tam sabit"], 1, None, 3),
 ("Eyni fikir müxtəlif üslublarda ifadə oluna bilərmi?",
  "Məqsəddən asılı olaraq bəli.",
  ["Bəli, ola bilər", "Xeyr, olmaz", "Yalnız şeirdə",
   "Yalnız sənəddə"], 1, None, 2),
],
"ing-7-friends": [
 ("«Lonely» sözünün mənası nədir?",
  "Lonely — tənha.",
  ["Tənha", "Şən", "Güclü", "Səxavətli"], 1, None, 2),
 ("«Have you ever met a famous person?» sualında hansı zaman işlənib?",
  "Have + V3 — Present Perfect.",
  ["Present Perfect", "Past Simple", "Future Simple",
   "Present Continuous"], 1, None, 3),
 ("«Polite» sözünün antonimi hansıdır?",
  "Polite — rude.",
  ["rude", "kind", "calm", "brave"], 1, None, 2),
 ("«I have known him ___ 2020.»",
  "Başlanğıc nöqtə üçün since işlənir.",
  ["since", "for", "at", "in"], 1, None, 3),
 ("«Friendly» sözü necə insanı bildirir?",
  "Friendly — mehriban.",
  ["Mehriban", "Qəzəbli", "Yorğun", "Xəsis"], 1, None, 1),
 ("«Apologize» feili nə deməkdir?",
  "Apologize — üzr istəmək.",
  ["Üzr istəmək", "Gülmək", "Qaçmaq", "Danışmaq"],
  1, None, 2),
 ("«We have just finished the project.» — «just» nəyi bildirir?",
  "İşin indicə bitdiyini.",
  ["İndicə olduğunu", "Sabah olacağını", "Heç olmadığını",
   "Tez-tez olduğunu"], 1, None, 3),
 ("«Selfish» sözünün mənası nədir?",
  "Selfish — yalnız özünü düşünən.",
  ["Eqoist", "Comərd", "Sadiq", "Utancaq"], 1, None, 2),
 ("«Rely on a friend» ifadəsi nə deməkdir?",
  "Dosta güvənmək, arxalanmaq.",
  ["Dostuna arxalanmaq", "Dostu unutmaq",
   "Dostu aldatmaq", "Dostdan qaçmaq"], 1, None, 2),
 ("«Never argue» məsləhəti nəyi tövsiyə edir?",
  "Mübahisədən çəkinməyi.",
  ["Mübahisə etməməyi", "Tez qaçmağı", "Ucadan gülməyi",
   "Çox yeməyi"], 1, None, 2),
],
"ing-7-future": [
 ("«There will be no schools» proqnozu nəyi bildirir?",
  "Gələcək haqqında fərziyyədir.",
  ["Gələcəyə aid proqnozu", "Keçmiş faktı",
   "İndiki adəti", "Əmri"], 1, None, 2),
 ("«I will call you later.» — Danışan nə vəd edir?",
  "Sonra zəng edəcəyini.",
  ["Zəng etməyi", "Məktub yazmağı", "Gəlməyi",
   "Getməyi"], 1, None, 2),
 ("«Perhaps» sözünün mənası nədir?",
  "Perhaps — bəlkə də.",
  ["Bəlkə də", "Mütləq", "Heç vaxt", "Dünən"], 1, None, 2),
 ("«Everything will be online.» cümləsində «online» nəyi bildirir?",
  "İnternet üzərindən olmağı.",
  ["İnternet üzərindən", "Kağız üzərində", "Bağlı",
   "Köhnə"], 1, None, 2),
 ("«In 50 years» ifadəsi nə deməkdir?",
  "50 il sonra.",
  ["50 il sonra", "50 il əvvəl", "50 dəqiqə", "50 gün"],
  1, None, 2),
 ("«Will they build new cities? — No, they ___.»",
  "İnkar qısa cavab: will not.",
  ["will not", "do not", "are not", "did not"], 1, None, 2),
 ("«The weather will be hot tomorrow.» — Sabah hava necə olacaq?",
  "Hot — isti.",
  ["İsti", "Soyuq", "Küləkli", "Yağışlı"], 1, None, 1),
 ("«Dream about the future» ifadəsi nə deməkdir?",
  "Gələcək haqqında xəyal qurmaq.",
  ["Gələcəyi arzulamaq", "Keçmişi unutmaq",
   "Yuxu görməmək", "Dərs oxumaq"], 1, None, 2),
 ("«Change» feilinin mənası nədir?",
  "Change — dəyişmək.",
  ["Dəyişmək", "Qalmaq", "Batmaq", "Uçmaq"], 1, None, 1),
 ("«Nobody knows the future.» cümləsinin mənası nədir?",
  "Gələcək heç kimə bəlli deyil.",
  ["Gələcəyi heç kim bilmir", "Hamı gələcəyi bilir",
   "Gələcək yoxdur", "Keçmiş unudulub"], 1, None, 2),
],
"ing-7-schools": [
 ("«Uniform» sözünün mənası nədir?",
  "Uniform — məktəb forması.",
  ["Məktəb forması", "Dərs cədvəli", "İmtahan",
   "Kitabxana"], 1, None, 1),
 ("«Study hard» ifadəsi nə deməkdir?",
  "Çox səylə oxumaq.",
  ["Çox çalışmaq", "Az yatmaq", "Tez qaçmaq",
   "Ucadan danışmaq"], 1, None, 2),
 ("«Biology» fənni nəyi öyrədir?",
  "Biologiya canlıları öyrənir.",
  ["Canlıları", "Ulduzları yalnız", "Rəqəmləri",
   "Xəritələri"], 1, None, 2),
 ("«You ___ listen to the teacher.» (borc)",
  "Məcburiyyət üçün must işlənir.",
  ["must", "can", "may", "did"], 1, None, 2),
 ("«Classmate» kimdir?",
  "Classmate — sinif yoldaşı.",
  ["Sinif yoldaşı", "Müəllim", "Direktor", "Qonşu"],
  1, None, 1),
 ("«Get a good mark» ifadəsi nə deməkdir?",
  "Yaxşı qiymət qazanmaq.",
  ["Yaxşı qiymət almaq", "Pis qiymət almaq",
   "Dərsi buraxmaq", "Kitab itirmək"], 1, None, 2),
 ("«Dictionary» nə üçün istifadə olunur?",
  "Sözlərin mənasını tapmaq üçün.",
  ["Söz öyrənmək üçün", "Şəkil çəkmək üçün",
   "Hesablamaq üçün", "Oynamaq üçün"], 1, None, 2),
 ("«Geography» fənni nəyi öyrədir?",
  "Coğrafiya Yer kürəsini öyrənir.",
  ["Yer kürəsini", "Yalnız tarixi", "Yalnız musiqini",
   "Yalnız idmanı"], 1, None, 2),
 ("«Absent» sözü məktəbdə nəyi bildirir?",
  "Dərsdə iştirak etməməyi.",
  ["Dərsdə olmamağı", "Əla oxumağı", "Gec qalxmağı",
   "Tez gəlməyi"], 1, None, 2),
 ("«Revise before the exam» məsləhəti nəyi tövsiyə edir?",
  "Mövzuları təkrarlamağı.",
  ["Təkrar etməyi", "Yatmağı", "Oynamağı", "Unutmağı"],
  1, None, 2),
],
"ing-7-talent": [
 ("My favourite free-time activity is my ___.",
  "Asudə vaxt məşğuliyyəti — hobby.",
  ["hobby", "homework", "exam", "uniform"], 1, None, 1),
 ("«Fast» sözünün zərf forması hansıdır?",
  "Fast həm sifət, həm zərfdir.",
  ["fast (dəyişmir)", "fastly", "faster yalnız",
   "fastness"], 1, None, 3),
 ("«She plays the violin ___.» (gözəl)",
  "Feili zərf izah edir: beautifully.",
  ["beautifully", "beautiful", "beauty", "more beautiful"],
  1, None, 2),
 ("«Ability» sözünün mənası nədir?",
  "Ability — bacarıq.",
  ["Bacarıq", "Yorğunluq", "Tənbəllik", "Qorxu"],
  1, None, 2),
 ("«Take part in a competition» nə deməkdir?",
  "Yarışda iştirak etmək.",
  ["Yarışda iştirak etmək", "Yarışı ləğv etmək",
   "Yarışa baxmamaq", "Yarışdan qaçmaq"], 1, None, 2),
 ("«First prize» ifadəsinin mənası nədir?",
  "Birinci yerin mükafatı.",
  ["Birinci mükafat", "Son yer", "Bilet", "Cərimə"],
  1, None, 1),
 ("«Gifted child» ifadəsi hansı uşağı bildirir?",
  "Gifted — istedadlı.",
  ["İstedadlı uşağı", "Yorğun uşağı", "Balaca uşağı",
   "Qonaq uşağı"], 1, None, 2),
 ("«Loudly» sözünün mənası nədir?",
  "Loudly — ucadan.",
  ["Ucadan", "Sakitcə", "Yavaş", "Gizlicə"], 1, None, 2),
 ("«Try your best» ifadəsi nəyə çağırır?",
  "Maksimum səy göstərməyə.",
  ["Əlindən gələni etməyə", "Tez imtina etməyə",
   "Gec gəlməyə", "Az çalışmağa"], 1, None, 2),
 ("«He runs ___ than his brother.» (daha sürətli)",
  "Müqayisə dərəcəsi: faster.",
  ["faster", "fast", "fastest", "more fast"], 1, None, 2),
],
"ing-7-technology": [
 ("«Laptop» nədir?",
  "Laptop — portativ kompüter.",
  ["Portativ kompüter", "Televizor", "Soyuducu",
   "Telefon stansiyası"], 1, None, 1),
 ("«Search the Internet» ifadəsi nə deməkdir?",
  "İnternetdə axtarış aparmaq.",
  ["İnternetdə axtarmaq", "İnterneti söndürmək",
   "Kompüteri satmaq", "Şəkil çəkmək"], 1, None, 2),
 ("«Now» sözü hansı zamanın əlamətidir?",
  "İndi baş verən hərəkət — Present Continuous.",
  ["Present Continuous", "Past Simple", "Future Simple",
   "Present Perfect"], 1, None, 3),
 ("«Log in» ifadəsi nə deməkdir?",
  "Hesaba daxil olmaq.",
  ["Daxil olmaq", "Çıxmaq", "Silmək", "Çap etmək"],
  1, None, 2),
 ("«Volume» düyməsi nəyi tənzimləyir?",
  "Səsin gücünü tənzimləyir.",
  ["Səsi", "İşığı", "Rəngi", "Sürəti"], 1, None, 2),
 ("«Website» nədir?",
  "Website — internet səhifəsi.",
  ["İnternet səhifəsi", "Kitab", "Qəzet", "Lüğət"],
  1, None, 1),
 ("«Share a photo» ifadəsi nə bildirir?",
  "Şəkli başqaları ilə bölüşmək.",
  ["Şəkli paylaşmaq", "Şəkli silmək", "Şəkli çəkməmək",
   "Şəkli gizlətmək"], 1, None, 2),
 ("«Battery» sözünün mənası nədir?",
  "Battery — batareya.",
  ["Batareya", "Ekran", "Klaviatura", "Kamera"],
  1, None, 1),
 ("«Headphones» nə üçündür?",
  "Qulaqlıqla musiqi dinlənilir.",
  ["Qulaqlıqla dinləmək", "Yazı yazmaq", "Şəkil çəkmək",
   "Çap etmək"], 1, None, 2),
 ("«Turn down the music» xahişi nə deməkdir?",
  "Musiqinin səsini azaltmaq.",
  ["Səsi azaltmaq", "Səsi artırmaq", "Mahnını dəyişmək",
   "İşığı yandırmaq"], 1, None, 2),
],
"ing-7-travel": [
 ("«Boarding pass» nədir?",
  "Təyyarəyə miniş talonu.",
  ["Miniş talonu", "Yemək menyusu", "Xəritə", "Açar"],
  1, None, 3),
 ("«Delay» sözü səyahətdə nəyi bildirir?",
  "Reysin gecikməsini.",
  ["Gecikməni", "Sürəti", "Rahatlığı", "Qiyməti"],
  1, None, 2),
 ("«We are going to spend a week in Gabala.» — Nə qədər qalacaqlar?",
  "A week — bir həftə.",
  ["Bir həftə", "Bir gün", "Bir ay", "Bir il"], 1, None, 2),
 ("«Sightseeing tour» nədir?",
  "Görməli yerlərə ekskursiya.",
  ["Şəhərgəzmə turu", "İdman yarışı", "Dərs", "İmtahan"],
  1, None, 2),
 ("«Exchange money» ifadəsi nə deməkdir?",
  "Valyutanı dəyişmək.",
  ["Pul dəyişmək", "Pul itirmək", "Pul yığmaq",
   "Pul çap etmək"], 1, None, 2),
 ("«Single room» oteldə hansı otaqdır?",
  "Bir nəfər üçün otaq.",
  ["Birnəfərlik otaq", "İkinəfərlik otaq", "Zal",
   "Mətbəx"], 1, None, 2),
 ("«Departure board» hava limanında nəyi göstərir?",
  "Uçuşların vaxtını göstərir.",
  ["Uçuş vaxtlarını", "Yemək siyahısını", "Hava kütləsini",
   "Bilet qiymətini yalnız"], 1, None, 3),
 ("«Customs» sərhəddə nədir?",
  "Customs — gömrük.",
  ["Gömrük", "Mehmanxana", "Kassa", "Dayanacaq"],
  1, None, 3),
 ("«Travel light» ifadəsi nə deməkdir?",
  "Az yüklə səyahət etmək.",
  ["Az yüklə səyahət", "İşıqla getmək", "Gecə getmək",
   "Sürətli qaçmaq"], 1, None, 3),
 ("«Return ticket» nədir?",
  "Gediş və dönüş bileti.",
  ["Gediş-dönüş bileti", "Yalnız gediş", "Pulsuz bilet",
   "Muzey bileti"], 1, None, 2),
],
}
for _k, _v in ELAVE30.items():
    SUALLAR[_k] = SUALLAR[_k] + _v


def yoxla():
    n = xeta = 0
    butun = set()
    movzu_fenn = {m: f for f, m, _r in MOVZULAR}
    for movzu, siyahi in SUALLAR.items():
        assert movzu in movzu_fenn, movzu
        if len(siyahi) not in (20, 30):
            print("XETA  %s: %d sual (20 ve ya 30 olmalidir)" % (movzu, len(siyahi)))
            xeta += 1
        for body, why, opts, correct, expect, diff in siyahi:
            n += 1
            p = []
            if len(opts) != 4: p.append("variant sayi %d" % len(opts))
            if len(set(opts)) != len(opts): p.append("tekrar variant")
            if not (1 <= correct <= 4): p.append("correct")
            if not why: p.append("izah bos")
            if diff not in (1, 2, 3): p.append("cetinlik")
            if body in butun: p.append("eyni sual iki defe")
            butun.add(body)
            if expect is not None and opts[correct - 1] != expect:
                p.append("hesablanan «%s» != variant «%s»" % (expect, opts[correct - 1]))
            for t in [body, why] + opts:
                if "'" in t: p.append("apostrof var")
            if p:
                xeta += 1
                print("XETA  %s: %s\n      %s" % (movzu, body[:60], "; ".join(p)))
    hes = sum(1 for s in SUALLAR.values() for q in s if q[4] is not None)
    print("%d sual yoxlandı (%d-i hesabla təsdiqləndi), %d xəta" % (n, hes, xeta))
    return xeta == 0, n


def sql_yaz(n):
    q = lambda t: t.replace("'", "''")
    on = {"az-dili": "az7", "ingilis-dili": "ing7",
          "informatika": "inf7"}
    setirler = []
    for fenn, movzu, rub in MOVZULAR:
        qisa = movzu.split("-", 2)[2]
        for i, (body, why, opts, correct, _e, diff) in enumerate(SUALLAR[movzu], 1):
            setirler.append(
                "('%s-%s#%d','%s','%s',%d,%d,'%s','%s',array['%s','%s','%s','%s'],%d)"
                % (on[fenn], qisa, i, fenn, movzu, diff, rub, q(body), q(why),
                   q(opts[0]), q(opts[1]), q(opts[2]), q(opts[3]), correct))
    with io.open(CIXIS, "w", encoding="utf-8") as f:
        f.write("""-- =====================================================================
--  35_bank_sinif7.sql : 7-CI SINIF - AZ DILI, INGILIS DILI,
--                       INFORMATIKA, UMUMI TARIX
--
--  BU FAYL ELLE YAZILMIR - tools/sinif7.py yaradir:
--      python3 tools/sinif7.py
--
--  Az dili 8 + Ingilis dili 6 + Informatika 5
--  az/ing 14 movzu x 30 + inf 5 movzu x 20 = %d.
--  ext_key: az7-/ing7-/inf7-...
--
--  7-ci sinif tarixi BU FAYLDA DEYIL: portalda o sinif ucun yalniz
--  "Umumi tarix" derslikyi var, ona gore hemin bank 'umumi-tarix'
--  fennindedir - db/71_bank_tarix_umumi7.sql.
--  ON SERT: 33_movzular_orta7.sql islenmis olmalidir.
--  SONRA:   05_grants.sql yeniden islet.
-- =====================================================================

do $$
begin
  if not exists (select 1 from public.topics t join public.subjects s
      on s.id = t.subject_id
     where (s.slug, t.slug) in (('az-dili','az-7-feil-sekil'),
                                ('ingilis-dili','ing-7-travel'),
                                ('informatika','inf-7-internet'))
     having count(*) = 3) then
    raise exception 'ONCE 33_movzular_orta7.sql isledilmelidir.';
  end if;
end $$;

delete from public.question_options o
 using public.questions q
 where o.question_id = q.id
   and q.owner_type = 'platform'
   and (q.ext_key like 'az7-%%' or q.ext_key like 'ing7-%%'
        or q.ext_key like 'inf7-%%');

with d(ext, fenn, topic, diff, rub, body, why, opts, correct) as (values
%s
),
ins as (
  insert into public.questions
    (ext_key, owner_type, subject_id, level_id, topic_id, kind,
     body, explanation, difficulty, quarter, status)
  select d.ext, 'platform', s.id, l.id, tp.id, 'single',
         d.body, d.why, d.diff, d.rub, 'published'
    from d
    join public.subjects s on s.slug = d.fenn
    join public.programs p on p.slug = 'orta'
    join public.levels   l on l.program_id = p.id and l.code = '7'
    join public.topics   tp on tp.subject_id = s.id and tp.slug = d.topic
  on conflict (ext_key) do update
    set body = excluded.body, explanation = excluded.explanation,
        difficulty = excluded.difficulty, quarter = excluded.quarter,
        topic_id = excluded.topic_id, level_id = excluded.level_id,
        subject_id = excluded.subject_id, status = 'published'
  returning id, ext_key
)
insert into public.question_options (question_id, ord, body, is_correct)
select ins.id, o.ord, o.txt, o.ord = d.correct
  from ins
  join d on d.ext = ins.ext_key,
  lateral unnest(d.opts) with ordinality as o(txt, ord);

do $$
declare n int; k int;
begin
  select count(*) into n from public.questions
   where owner_type = 'platform'
     and (ext_key like 'az7-%%' or ext_key like 'ing7-%%'
          or ext_key like 'inf7-%%');
  if n <> %d then
    raise exception 'sinif7 suallari: %d gozlenilirdi, %% tapildi', n;
  end if;
  select count(*) into k from public.questions q
   where (q.ext_key like 'az7-%%' or q.ext_key like 'ing7-%%'
          or q.ext_key like 'inf7-%%')
     and ((select count(*) from public.question_options o
            where o.question_id = q.id) <> 4
       or (select count(*) from public.question_options o
            where o.question_id = q.id and o.is_correct) <> 1);
  if k > 0 then
    raise exception '%% sualda variant qurulusu sehvdir', k;
  end if;
  select count(distinct topic_id) into k from public.questions
   where ext_key like 'az7-%%' or ext_key like 'ing7-%%'
      or ext_key like 'inf7-%%';
  if k <> 19 then
    raise exception 'movzu sayi 19 deyil: %%', k;
  end if;
  raise notice '7-ci sinif banki: %% sual, 19 movzu (az, ing, inf).', n;
end $$;
""" % (n, ",\n".join(setirler), n, n))
    print("yazildi: %s" % CIXIS)


if __name__ == "__main__":
    ok, n = yoxla()
    if not ok:
        raise SystemExit(1)
    sql_yaz(n)
