#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
8-ci sinfin humanitar fennleri -> db/39_bank_sinif8.sql

    Azerbaycan dili 8      8 movzu x 10 =  80
    Ingilis dili 8         6 movzu x 10 =  60
    Informatika 8          6 movzu x 10 =  60
    Azerbaycan tarixi 8    4 movzu x 10 =  40
                                    cemi  240

tools/sinif7.py qelibi ile.  Movzular 37_movzular_orta8.sql agacina
uygundur.  Az dili 8-ci sinif sintaksisi (soz birlesmeleri, bas ve
ikinci dereceli uzvler, hemcins uzvler, xitab-ara sozler, tekterkibli
cumleler); tarix suallari subhesiz derslik faktlaridir (Sefeviler,
Nadir sah 1736, xanliqlar, Gulustan 1813, Turkmencay 1828).
Kodlasdirma suallari int(x, 2) ve 2**8 ile hesablanir.

Isletmek:
    python3 tools/sinif8.py
"""
import io
import os

KOK = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CIXIS = os.path.join(KOK, "db", "39_bank_sinif8.sql")

#  (fenn, movzu-slug, rub)
MOVZULAR = [
    ("az-dili", "az-8-soz-birlesmesi", 1),
    ("az-dili", "az-8-mubteda-xeber",  1),
    ("az-dili", "az-8-ikinci-uzvler",  2),
    ("az-dili", "az-8-hemcins",        2),
    ("az-dili", "az-8-xitab-ara",      3),
    ("az-dili", "az-8-cumle-novleri",  3),
    ("az-dili", "az-8-durgu",          4),
    ("az-dili", "az-8-metn-uslub",     4),
    ("ingilis-dili", "ing-8-holidays",        1),
    ("ingilis-dili", "ing-8-inventions",      1),
    ("ingilis-dili", "ing-8-hobbies",         2),
    ("ingilis-dili", "ing-8-present-perfect", 2),
    ("ingilis-dili", "ing-8-media",           3),
    ("ingilis-dili", "ing-8-environment",     4),
    ("informatika", "inf-8-informasiya",     1),
    ("informatika", "inf-8-multimedia",      1),
    ("informatika", "inf-8-proqramlasdirma", 2),
    ("informatika", "inf-8-kompyuter",       2),
    ("informatika", "inf-8-tetbiqi",         3),
    ("informatika", "inf-8-internet",        4),
    ("tarix", "tarix-8-xvi-xvii",  1),
    ("tarix", "tarix-8-xviii-1",   2),
    ("tarix", "tarix-8-xanliqlar", 3),
    ("tarix", "tarix-8-xix",       4),
]

SUALLAR = {
# ===================== AZERBAYCAN DILI 8 ==============================
"az-8-soz-birlesmesi": [
 ("Söz birləşmələri əsas tərəfinə görə hansı növlərə ayrılır?",
  "İsmi və feili birləşmələrə ayrılır.",
  ["İsmi və feili", "Sadə və mürəkkəb", "Tək və cəm",
   "Uzun və qısa"], 1, None, 2),
 ("«Dağların gözəlliyi» hansı birləşmə növüdür?",
  "Əsas tərəf isimdir — ismi birləşmədir.",
  ["İsmi", "Feili", "Zərf birləşməsi", "Cümlədir"],
  1, None, 2),
 ("«Kitab oxuyan» birləşməsi hansı növdəndir?",
  "Əsas tərəf feili sifətdir — feili birləşmədir.",
  ["Feili", "İsmi", "Say birləşməsi", "Nida"], 1, None, 3),
 ("Feili birləşmənin əsas tərəfi nə ilə ifadə olunur?",
  "Feilin təsriflənməyən formaları ilə (məsdər, feili sifət, "
  "feili bağlama).",
  ["Feilin təsriflənməyən formaları ilə", "Yalnız isimlə",
   "Bağlayıcı ilə", "Ədatla"], 1, None, 3),
 ("Birləşmənin tərəfləri arasında hansı əlaqə var?",
  "Asılı tərəf əsas tərəfə tabedir — tabelilik əlaqəsi.",
  ["Tabelilik (asılılıq)", "Bərabərlik", "Əlaqə yoxdur",
   "Yalnız məna əlaqəsi yoxdur"], 1, None, 3),
 ("«Qızıl payız» birləşməsində asılı tərəf hansıdır?",
  "«Qızıl» sözü «payız» sözünü izah edir — asılıdır.",
  ["qızıl", "payız", "hər ikisi", "heç biri"], 1, None, 2),
 ("Üçüncü növ təyini söz birləşməsinin birinci tərəfi hansı "
  "haldadır?",
  "Birinci tərəf yiyəlik haldadır: məktəbin həyəti.",
  ["Yiyəlik halda", "Adlıq halda şəkilçisiz", "Təsirlik halda",
   "Çıxışlıq halda"], 1, None, 3),
 ("«Şəhərin küçələri» neçənci növ təyini söz birləşməsidir?",
  "Hər iki tərəf şəkilçilidir — üçüncü növdür.",
  ["Üçüncü", "Birinci", "İkinci", "Beşinci"], 1, None, 3),
 ("Söz birləşməsini mürəkkəb sözdən nə fərqləndirir?",
  "Birləşmədə hər söz müstəqilliyini saxlayır və ayrı yazılır.",
  ["Sözlərin müstəqilliyini saxlaması", "Bitişik yazılması",
   "Bir vurğu daşıması", "Fərq yoxdur"], 1, None, 3),
 ("Sabit birləşmələr sərbəst birləşmələrdən nə ilə fərqlənir?",
  "Sabit birləşmənin mənası tərkib sözlərdən çıxmır.",
  ["Mənası tərkib sözlərdən çıxmır", "Daha uzun olur",
   "Yalnız şeirdə işlənir", "Fərqlənmir"], 1, None, 3),
],
"az-8-mubteda-xeber": [
 ("Mübtəda hansı halda olur?",
  "Mübtəda adlıq halda olur.",
  ["Adlıq halda", "Yiyəlik halda", "Təsirlik halda",
   "Yerlik halda"], 1, None, 2),
 ("Xəbər mübtəda ilə nəyə görə uzlaşır?",
  "Şəxsə və kəmiyyətə görə uzlaşır.",
  ["Şəxsə və kəmiyyətə görə", "Rəngə görə",
   "Uzunluğa görə", "Uzlaşmır"], 1, None, 3),
 ("«Biz kitab oxuyuruq» cümləsində xəbər hansı şəxsdədir?",
  "-uq şəxs sonluğu I şəxsin cəmidir.",
  ["I şəxs cəmdə", "II şəxs təkdə", "III şəxs cəmdə",
   "Şəxsi yoxdur"], 1, None, 2),
 ("İsmi xəbərə misal hansıdır?",
  "«Atam həkimdir» — xəbər isimlə ifadə olunub.",
  ["Atam həkimdir.", "Uşaq qaçır.", "Quş uçdu.",
   "Yağış yağacaq."], 1, None, 3),
 ("Feili xəbər nə ilə ifadə olunur?",
  "Feilin təsriflənən formaları ilə.",
  ["Feillə", "Yalnız isimlə", "Sayla", "Qoşma ilə"],
  1, None, 2),
 ("«Hava soyuqdur» cümləsində xəbər hansıdır?",
  "Hava necədir? — soyuqdur (ismi xəbər).",
  ["soyuqdur", "hava", "cümlədə xəbər yoxdur", "hər ikisi"],
  1, None, 2),
 ("Mübtəda hansı nitq hissələri ilə ifadə oluna bilər?",
  "İsim, əvəzlik, məsdər və isimləşmiş sözlərlə.",
  ["İsim, əvəzlik, məsdərlə", "Yalnız feillə",
   "Yalnız bağlayıcı ilə", "Nida ilə"], 1, None, 3),
 ("«Oxumaq faydalıdır» cümləsində mübtəda nə ilə ifadə olunub?",
  "«Oxumaq» məsdərdir.",
  ["Məsdərlə", "İsimlə", "Sifətlə", "Zərflə"], 1, None, 3),
 ("Cümlədə mübtəda buraxıla bilərmi?",
  "Bəli — şəxs sonluğundan bilinərsə: Gəlirəm (mən).",
  ["Bəli, şəxs sonluğundan bilinərsə", "Heç vaxt",
   "Yalnız şeirdə", "Yalnız sualda"], 1, None, 3),
 ("«Sən gəl» cümləsində mübtəda hansıdır?",
  "Kim gəlsin? — sən.",
  ["Sən", "Gəl", "Hər ikisi", "Mübtəda yoxdur"], 1, None, 1),
],
"az-8-ikinci-uzvler": [
 ("Vasitəsiz tamamlıq hansı halda olur?",
  "Təsirlik halda (müəyyən və qeyri-müəyyən).",
  ["Təsirlik halda", "Yönlük halda", "Yerlik halda",
   "Adlıq halda"], 1, None, 3),
 ("Vasitəli tamamlıq hansı hallarda olur?",
  "Yönlük, yerlik və çıxışlıq hallarda.",
  ["Yönlük, yerlik, çıxışlıq", "Yalnız təsirlik",
   "Yalnız adlıq", "Heç bir halda"], 1, None, 3),
 ("«Məktuba cavab yazdım» cümləsində «məktuba» hansı tamamlıqdır?",
  "Yönlük haldadır — vasitəli tamamlıqdır.",
  ["Vasitəli", "Vasitəsiz", "Təyin", "Zərflik"], 1, None, 3),
 ("Təyin əsasən hansı üzvləri izah edir?",
  "İsimlə ifadə olunan üzvləri.",
  ["İsimlə ifadə olunan üzvləri", "Yalnız xəbəri",
   "Yalnız zərfliyi", "Bağlayıcıları"], 1, None, 3),
 ("Səbəb zərfliyi hansı suala cavab verir?",
  "Niyə? Nə üçün? Nə səbəbə?",
  ["Niyə? Nə üçün?", "Harada?", "Nə zaman?", "Necə?"],
  1, None, 2),
 ("«Sevincdən ağladı» cümləsində «sevincdən» hansı zərflikdir?",
  "Niyə ağladı? — səbəb zərfliyi.",
  ["Səbəb zərfliyi", "Zaman zərfliyi", "Yer zərfliyi",
   "Tamamlıq"], 1, None, 3),
 ("Məqsəd zərfliyi hansı suala cavab verir?",
  "Nə məqsədlə? sualına.",
  ["Nə məqsədlə?", "Haradan?", "Neçə?", "Kimin?"],
  1, None, 3),
 ("«Şagird kimi danışdı» ifadəsində «şagird kimi» hansı üzvdür?",
  "Necə danışdı? — tərzi-hərəkət zərfliyi.",
  ["Tərzi-hərəkət zərfliyi", "Mübtəda", "Təyin",
   "Vasitəsiz tamamlıq"], 1, None, 3),
 ("Kəmiyyət zərfliyi nəyi bildirir?",
  "Hərəkətin miqdarını, dərəcəsini.",
  ["Hərəkətin miqdarını", "Hərəkətin yerini",
   "Əşyanın rəngini", "Şəxsi"], 1, None, 3),
 ("«Beş dəfə oxudum» cümləsində «beş dəfə» hansı üzvdür?",
  "Neçə dəfə? — kəmiyyət zərfliyi.",
  ["Kəmiyyət zərfliyi", "Tamamlıq", "Təyin", "Xəbər"],
  1, None, 3),
],
"az-8-hemcins": [
 ("Həmcins üzvlər hansı üzvlərdir?",
  "Eyni suala cavab verib eyni üzvə aid olan üzvlərdir.",
  ["Eyni suala cavab verən eyni cür üzvlər",
   "Müxtəlif suallara cavab verənlər", "Yalnız xəbərlər",
   "Yalnız mübtədalar"], 1, None, 2),
 ("«Bağda alma, armud və gavalı yetişir» cümləsində həmcins "
  "üzvlər hansılardır?",
  "Alma, armud, gavalı — həmcins mübtədalardır.",
  ["alma, armud, gavalı", "bağda, yetişir",
   "yalnız alma", "cümlədə yoxdur"], 1, None, 2),
 ("Həmcins üzvlər arasına adətən hansı işarə qoyulur?",
  "Sadalanan həmcins üzvlər vergüllə ayrılır.",
  ["Vergül", "Nöqtə", "Tire", "İki nöqtə"], 1, None, 2),
 ("Həmcins üzvləri bağlayan bağlayıcılara misal hansıdır?",
  "Və, həm, nə…nə, amma bağlayıcıları.",
  ["və, həm, amma", "çünki, əgər", "ki, deməli",
   "kaş, təki"], 1, None, 3),
 ("Təkrarlanmayan «və» bağlayıcısından əvvəl vergül qoyulurmu?",
  "Xeyr — tək «və»-dən əvvəl vergül qoyulmur.",
  ["Xeyr, qoyulmur", "Bəli, həmişə", "Yalnız şeirdə",
   "Yalnız sualda"], 1, None, 3),
 ("Ümumiləşdirici söz həmcins üzvlərdən ƏVVƏL gələndə ondan "
  "sonra hansı işarə qoyulur?",
  "İki nöqtə qoyulur.",
  ["İki nöqtə", "Tire", "Nöqtə", "Sual işarəsi"], 1, None, 3),
 ("«Hər şey: ağaclar, çiçəklər, quşlar oyandı» cümləsində "
  "ümumiləşdirici söz hansıdır?",
  "«Hər şey» həmcins üzvləri ümumiləşdirir.",
  ["Hər şey", "ağaclar", "oyandı", "quşlar"], 1, None, 3),
 ("Həmcins xəbərli cümləyə misal hansıdır?",
  "«Uşaq gülür, oynayır, oxuyurdu» — üç həmcins xəbər.",
  ["Uşaq gülür, oynayır, oxuyurdu.", "Uşaq şəkil çəkdi.",
   "Hava istidir.", "Kitab masadadır."], 1, None, 3),
 ("Ümumiləşdirici söz həmcins üzvlərdən SONRA gələndə ondan "
  "əvvəl nə qoyulur?",
  "Tire qoyulur.",
  ["Tire", "İki nöqtə", "Nöqtəli vergül", "Mötərizə"],
  1, None, 3),
 ("Həmcins üzvlər cümləyə nə verir?",
  "Fikri genişləndirir, ifadəliliyi artırır.",
  ["Genişlik və ifadəlilik", "Qısalıq", "Qeyri-müəyyənlik",
   "Heç nə"], 1, None, 2),
],
"az-8-xitab-ara": [
 ("Xitab nədir?",
  "Müraciət olunan şəxsi və ya əşyanı bildirən sözdür.",
  ["Müraciət bildirən söz", "Cümlənin xəbəri",
   "Bağlayıcı söz", "Say"], 1, None, 2),
 ("«Uşaqlar, sabahınız xeyir!» cümləsində xitab hansıdır?",
  "Müraciət «uşaqlar» sözünədir.",
  ["Uşaqlar", "sabahınız", "xeyir", "xitab yoxdur"],
  1, None, 2),
 ("Xitab cümlə üzvüdürmü?",
  "Xeyr — xitab cümlə üzvü deyil.",
  ["Xeyr, üzv deyil", "Bəli, mübtədadır", "Bəli, xəbərdir",
   "Bəli, təyindir"], 1, None, 3),
 ("Xitab yazıda nə ilə ayrılır?",
  "Vergüllə (güclü hissdə nida işarəsi ilə).",
  ["Vergüllə", "Nöqtə ilə", "Mötərizə ilə", "Ayrılmır"],
  1, None, 2),
 ("Ara sözlər nəyi ifadə edir?",
  "Danışanın fikrə münasibətini: yəqinlik, güman, nəticə.",
  ["Fikrə münasibəti (yəqinlik, güman)", "Əşyanın adını",
   "Hərəkətin yerini", "Sayı"], 1, None, 3),
 ("«Deyəsən, yağış yağacaq» cümləsində ara söz hansıdır?",
  "«Deyəsən» güman bildirən ara sözdür.",
  ["Deyəsən", "yağış", "yağacaq", "ara söz yoxdur"],
  1, None, 2),
 ("Ara sözlər yazıda necə ayrılır?",
  "Vergüllərlə ayrılır.",
  ["Vergüllərlə", "Nöqtələrlə", "Dırnaqlarla",
   "Heç nə ilə"], 1, None, 2),
 ("«Əzizim ana!» müraciəti cümlədə nə rolunu oynayır?",
  "Bu, xitabdır.",
  ["Xitab", "Mübtəda", "Tamamlıq", "Xəbər"], 1, None, 2),
 ("Ara sözü cümlə üzvündən necə fərqləndirmək olar?",
  "Ara sözə cümlə üzvü kimi sual vermək olmur.",
  ["Ona sual vermək olmur", "Ara söz həmişə sondadır",
   "Ara söz böyük hərflə yazılır", "Fərqləndirmək olmur"],
  1, None, 3),
 ("«Beləliklə» ara sözü nəyi bildirir?",
  "Nəticəni bildirir.",
  ["Nəticəni", "Gümanı", "Sevinci", "Sualı"], 1, None, 3),
],
"az-8-cumle-novleri": [
 ("Cüttərkibli cümlə hansı cümlədir?",
  "Hər iki baş üzvü (mübtəda və xəbəri) olan cümlə.",
  ["Hər iki baş üzvü olan", "Yalnız xəbəri olan",
   "Üzvsüz cümlə", "İki xəbərli cümlə"], 1, None, 2),
 ("Təktərkibli cümlədə nə olur?",
  "Baş üzvlərdən yalnız biri olur.",
  ["Baş üzvlərdən yalnız biri", "Hər iki baş üzv",
   "Yalnız ikinci dərəcəli üzvlər", "Heç bir üzv"],
  1, None, 3),
 ("«Qış. Şaxta.» — bu cümlələr hansı növdəndir?",
  "Əşyanın adını bildirən adlıq cümlələrdir.",
  ["Adlıq cümlə", "Şəxssiz cümlə", "Yarımçıq cümlə",
   "Cüttərkibli"], 1, None, 3),
 ("Mübtədası olmayan və təsəvvür edilməyən cümlə necə adlanır?",
  "Belə cümlə şəxssiz cümlədir.",
  ["Şəxssiz", "Müəyyən şəxsli", "Adlıq", "Yarımçıq"],
  1, None, 3),
 ("Müəyyən şəxsli cümlədə mübtəda niyə buraxılır?",
  "Şəxs sonluğundan kim olduğu bilinir.",
  ["Şəxs sonluğundan bilinir", "Unudulur",
   "Yazmaq qadağandır", "Buraxılmır"], 1, None, 3),
 ("«Gəlirəm» cümləsi hansı növ təktərkibli cümlədir?",
  "Şəxs sonluğu «mən»i göstərir — müəyyən şəxslidir.",
  ["Müəyyən şəxsli", "Qeyri-müəyyən şəxsli", "Adlıq",
   "Şəxssiz"], 1, None, 3),
 ("Yarımçıq cümlə nədir?",
  "Buraxılmış üzvü mətndən bərpa olunan cümlədir.",
  ["Üzvü mətndən bərpa olunan cümlə", "Səhv cümlə",
   "Uzun cümlə", "Sual cümləsi"], 1, None, 3),
 ("«Deyirlər ki, sabah qar yağacaq» — «deyirlər» hansı növ "
  "cümlənin xəbəridir?",
  "İcraçı qeyri-müəyyəndir — qeyri-müəyyən şəxsli cümlədir.",
  ["Qeyri-müəyyən şəxsli", "Müəyyən şəxsli", "Adlıq",
   "Şəxssiz"], 1, None, 3),
 ("Geniş cümlə hansı cümlədir?",
  "İkinci dərəcəli üzvləri olan cümlə.",
  ["İkinci dərəcəli üzvləri olan", "Yalnız baş üzvlü",
   "Ən uzun cümlə", "Mürəkkəb cümlə"], 1, None, 2),
 ("Müxtəsər cümləyə misal hansıdır?",
  "«Külək əsdi» — yalnız baş üzvlərdən ibarətdir.",
  ["Külək əsdi.", "Güclü külək səhərdən əsdi.",
   "Dünən şəhərdə külək əsdi.", "Külək əsdi və yağış yağdı."],
  1, None, 3),
],
"az-8-durgu": [
 ("Vasitəsiz nitq necə yazılır?",
  "Dırnaq içində, olduğu kimi yazılır.",
  ["Dırnaq içində", "Mötərizədə", "Kursivlə",
   "Sətirdən kənarda"], 1, None, 2),
 ("Müəllifin sözlərindən sonra vasitəsiz nitqdən əvvəl nə "
  "qoyulur?",
  "İki nöqtə qoyulur.",
  ["İki nöqtə", "Vergül", "Nöqtə", "Heç nə"], 1, None, 3),
 ("«Kitab — bilik mənbəyidir» cümləsində tire niyə qoyulub?",
  "Hər iki baş üzv isimlə ifadə olunub — aralarına tire qoyulur.",
  ["Mübtəda ilə xəbər arasına", "Sadalama üçün",
   "Sual üçün", "Səhv qoyulub"], 1, None, 3),
 ("Dialoqda hər replikanın əvvəlində hansı işarə qoyulur?",
  "Tire qoyulur.",
  ["Tire", "Dırnaq", "Nöqtə", "Ulduz"], 1, None, 2),
 ("Bədii əsərin adı mətndə necə yazılır?",
  "Dırnaqda yazılır: «Xəmsə».",
  ["Dırnaqda", "Mötərizədə", "Böyük hərflərlə bütöv",
   "Adi qaydada işarəsiz"], 1, None, 2),
 ("Cümlənin sonunda üç nöqtə nəyi bildirir?",
  "Fikrin bitmədiyini, davam etdiyini.",
  ["Fikrin bitmədiyini", "Sualı", "Əmri", "Sevinci"],
  1, None, 2),
 ("Vergül hansı hallarda qoyulur?",
  "Həmcins üzvlər, ara sözlər, xitablar ayrılarkən.",
  ["Həmcins üzv, ara söz, xitab ayrılarkən",
   "Hər sözdən sonra", "Yalnız cümlə sonunda",
   "Heç vaxt"], 1, None, 2),
 ("Mötərizə nə üçün işlənir?",
  "Əlavə izahat vermək üçün.",
  ["Əlavə izahat üçün", "Cümləni bitirmək üçün",
   "Sual vermək üçün", "Bəzək üçün"], 1, None, 2),
 ("Sual və güclü hiss birləşəndə hansı işarələr qoyulur?",
  "Sual və nida işarəsi birgə: ?!",
  ["?! (sual və nida)", "Yalnız nöqtə", "İki vergül",
   "Üç tire"], 1, None, 3),
 ("Dostum dedi: «Sabah gələcəyəm». — Dırnaqdakı hissə hansı "
  "nitqdir?",
  "Sözlər olduğu kimi verilib — vasitəsiz nitqdir.",
  ["Vasitəsiz nitq", "Vasitəli nitq", "Ara söz", "Xitab"],
  1, None, 3),
],
"az-8-metn-uslub": [
 ("Mətnin əsas fikri necə adlanır?",
  "Əsas fikir mətnin ideyasıdır.",
  ["İdeya (əsas fikir)", "Başlıq", "Abzas", "Sitat"],
  1, None, 2),
 ("Mətn hansı hissələrdən qurulur?",
  "Giriş, əsas hissə və nəticədən.",
  ["Giriş, əsas hissə, nəticə", "Yalnız girişdən",
   "Yalnız nəticədən", "Sözlükdən"], 1, None, 2),
 ("Mətn üzərində plan tərtib etmək nəyə kömək edir?",
  "Fikirləri ardıcıl qurmağa.",
  ["Fikirləri ardıcıl qurmağa", "Mətni qısaltmağa",
   "Sözləri saymağa", "Heç nəyə"], 1, None, 2),
 ("Esse hansı yazı növüdür?",
  "Mövzu ətrafında sərbəst düşüncə yazısıdır.",
  ["Sərbəst düşüncə yazısı", "Rəsmi sənəd",
   "Elmi hesabat", "Lüğət"], 1, None, 3),
 ("Elektron rəsmi məktubda müraciət necə olmalıdır?",
  "Nəzakətli və rəsmi olmalıdır.",
  ["Nəzakətli və rəsmi", "Zarafatyana",
   "Qısaltmalarla dolu", "Müraciətsiz"], 1, None, 2),
 ("Təsviri mətndə nə verilir?",
  "Əşya və hadisənin əlamətlərinin təsviri.",
  ["Əşya və hadisənin təsviri", "Yalnız dialoq",
   "Yalnız rəqəmlər", "Cədvəllər"], 1, None, 3),
 ("Nəqli mətn nəyi əks etdirir?",
  "Hadisələrin ardıcıllığını.",
  ["Hadisələrin ardıcıllığını", "Yalnız təsviri",
   "Yalnız mübahisəni", "Düsturları"], 1, None, 3),
 ("Mühakimə tipli mətndə nə olur?",
  "Fikir irəli sürülür və əsaslandırılır.",
  ["Fikir və onun əsaslandırılması", "Yalnız təsvir",
   "Yalnız hadisə", "Yalnız sitatlar"], 1, None, 3),
 ("Konspekt nədir?",
  "Mətnin əsas məzmununun qısa yazılışıdır.",
  ["Mətnin qısa yazılışı", "Mətnin tam köçürülməsi",
   "Şəkilli albom", "Sözlərin siyahısı"], 1, None, 2),
 ("Annotasiya nəyi bildirir?",
  "Əsərin qısa məzmununu və təyinatını.",
  ["Əsərin qısa məzmununu", "Müəllifin ünvanını",
   "Kitabın qiymətini", "Səhifə sayını"], 1, None, 3),
],
# ====================== INGILIS DILI 8 ================================
"ing-8-holidays": [
 ("«I have been to London.» cümləsi nəyi bildirir?",
  "Londonda olmaq təcrübəsini bildirir.",
  ["Londonda olma təcrübəsini", "Gələcək planı",
   "Əmri", "Peşmançılığı"], 1, None, 3),
 ("«Campsite» nə deməkdir?",
  "Campsite — düşərgə yeri.",
  ["Düşərgə yeri", "Hava limanı", "Muzey", "Bazar"],
  1, None, 2),
 ("«Seaside» nə deməkdir?",
  "Seaside — dəniz kənarı.",
  ["Dəniz kənarı", "Dağ zirvəsi", "Meşəlik", "Şəhər mərkəzi"],
  1, None, 2),
 ("«We stayed at a hotel.» — «stayed» hansı zamandadır?",
  "-ed forması Past Simple-dır.",
  ["Past Simple", "Present Perfect", "Gələcək",
   "Past Continuous"], 1, None, 2),
 ("«Excursion» sözünün mənası nədir?",
  "Excursion — ekskursiya.",
  ["Ekskursiya", "Yemək", "Sənəd", "Hədiyyə"], 1, None, 1),
 ("«Travel agency» nə üçündür?",
  "Səyahətləri təşkil etmək üçün.",
  ["Səyahət təşkil etmək üçün", "Paltar satmaq üçün",
   "Kitab çap etmək üçün", "Ev tikmək üçün"], 1, None, 2),
 ("«Journey, trip, voyage» sözlərini nə birləşdirir?",
  "Üçü də səyahət mənasındadır.",
  ["Hamısı səyahət bildirir", "Hamısı yemək bildirir",
   "Hamısı idmandır", "Ümumi cəhət yoxdur"], 1, None, 2),
 ("«Did you have a good time?» sualı nəyi soruşur?",
  "Vaxtın yaxşı keçib-keçmədiyini.",
  ["Vaxtın necə keçdiyini", "Saatın neçə olduğunu",
   "Biletin qiymətini", "Ünvanı"], 1, None, 2),
 ("«Souvenir shop» adətən harada yerləşir?",
  "Turistlərin çox olduğu yerlərdə.",
  ["Turistik yerlərdə", "Zavodlarda", "Fermalarda",
   "Xəstəxanalarda"], 1, None, 2),
 ("«Sunbathe» feili nə deməkdir?",
  "Günəş vannası qəbul etmək.",
  ["Günəş vannası qəbul etmək", "Üzmək", "Qaçmaq",
   "Yatmaq"], 1, None, 3),
],
"ing-8-inventions": [
 ("«Inventor» kimdir?",
  "Inventor — ixtiraçı.",
  ["İxtiraçı", "Müğənni", "Sürücü", "Satıcı"], 1, None, 1),
 ("«Device» sözünün mənası nədir?",
  "Device — cihaz, qurğu.",
  ["Cihaz", "İçki", "Geyim", "Bina"], 1, None, 2),
 ("«The telephone was invented by Bell.» cümləsi hansı "
  "formadadır?",
  "Was + III forma — məchul növdür (Passive).",
  ["Məchul növ (Passive)", "Əmr forması",
   "Sual forması", "Gələcək zaman"], 1, None, 3),
 ("«Create» feilinin mənası nədir?",
  "Create — yaratmaq.",
  ["Yaratmaq", "Dağıtmaq", "İtirmək", "Gizlətmək"],
  1, None, 2),
 ("«Experiment» nə deməkdir?",
  "Experiment — təcrübə, sınaq.",
  ["Təcrübə", "Bayram", "Mahnı", "Rəsm"], 1, None, 2),
 ("«Young inventors» ifadəsi kimləri bildirir?",
  "Gənc ixtiraçıları.",
  ["Gənc ixtiraçıları", "Qoca müəllimləri",
   "Peşəkar idmançıları", "Aktyorları"], 1, None, 2),
 ("«Patent» nə üçün alınır?",
  "İxtiranı hüquqi qorumaq üçün.",
  ["İxtiranı qorumaq üçün", "Ev almaq üçün",
   "Səyahət üçün", "Yemək üçün"], 1, None, 3),
 ("«Improve» feili nə deməkdir?",
  "Improve — yaxşılaşdırmaq, təkmilləşdirmək.",
  ["Təkmilləşdirmək", "Korlamaq", "Satmaq", "Saymaq"],
  1, None, 2),
 ("«Science fair» nədir?",
  "Elmi layihələrin sərgi-yarışması.",
  ["Elm sərgisi (yarışması)", "İdman meydançası",
   "Musiqi festivalı", "Kitab mağazası"],
  1, None, 3),
 ("«How does it work?» sualı nəyi soruşur?",
  "Qurğunun necə işlədiyini.",
  ["Necə işlədiyini", "Neçəyə satıldığını",
   "Harada olduğunu", "Kimin aldığını"], 1, None, 2),
],
"ing-8-hobbies": [
 ("«Photography» hansı məşğuliyyətdir?",
  "Photography — fotoçəkmə.",
  ["Fotoçəkmə", "Balıq tutma", "Qaçış", "Yemək bişirmə"],
  1, None, 2),
 ("«Origami» sənəti haradan yaranıb?",
  "Kağız qatlama sənəti Yaponiyadan yaranıb.",
  ["Yaponiyadan", "Braziliyadan", "Kanadadan",
   "Misirdən"], 1, None, 3),
 ("«Knitting» nə deməkdir?",
  "Knitting — toxuculuq (hörmə).",
  ["Toxuculuq (hörmə)", "Rəqs", "Üzgüçülük", "Rəsm"],
  1, None, 2),
 ("«I am keen on music.» ifadəsi nəyi bildirir?",
  "Musiqiyə böyük həvəsi bildirir.",
  ["Musiqiyə həvəsi", "Musiqiyə nifrəti",
   "Musiqi alətini", "Konsert biletini"], 1, None, 3),
 ("«Board games» hansı oyunlardır?",
  "Masaüstü oyunlardır: şahmat, dama.",
  ["Masaüstü oyunlar", "Su oyunları", "İdman oyunları",
   "Kompüter oyunları"], 1, None, 2),
 ("«Gardening» məşğuliyyəti nədir?",
  "Gardening — bağçılıq.",
  ["Bağçılıq", "Ovçuluq", "Dənizçilik", "Aşpazlıq"],
  1, None, 2),
 ("«Take up a hobby» ifadəsi nə deməkdir?",
  "Yeni məşğuliyyətə başlamaq.",
  ["Yeni məşğuliyyətə başlamaq", "Məşğuliyyəti atmaq",
   "Hobbini satmaq", "İstirahət etmək"], 1, None, 3),
 ("«Be interested in» ifadəsindən sonra feil hansı formada "
  "işlənir?",
  "-ing formasında: interested in reading.",
  ["-ing formasında", "-ed formasında", "will ilə",
   "Əsas formada"], 1, None, 3),
 ("«Pottery» nə deməkdir?",
  "Pottery — dulusçuluq.",
  ["Dulusçuluq", "Şirniyyat", "Xəttatlıq", "Bağça"],
  1, None, 3),
 ("«Hobbies around the world» ifadəsi nə deməkdir?",
  "Dünyadakı (müxtəlif ölkələrdəki) hobbilər.",
  ["Dünya üzrə hobbilər", "Bir kəndin işləri",
   "Dərs cədvəli", "İdman qaydaları"], 1, None, 2),
],
"ing-8-present-perfect": [
 ("Present Perfect necə düzəlir?",
  "have/has + feilin III forması.",
  ["have/has + feilin III forması", "will + feil",
   "am/is + feil-ing", "did + feil"], 1, None, 3),
 ("«She has ___ her homework.» (do feilinin III forması)",
  "Do feilinin III forması: done.",
  ["done", "did", "doing", "does"], 1, None, 2),
 ("«I have just seen him.» — «just» nə bildirir?",
  "Hərəkətin indicə baş verdiyini.",
  ["İndicə baş verməyi", "Çoxdan olmağı",
   "Heç olmamağı", "Gələcəyi"], 1, None, 3),
 ("«Ever» sözü Present Perfect-də əsasən harada işlənir?",
  "Təcrübə soruşan sual cümlələrində.",
  ["Sual cümlələrində", "Yalnız inkar cümlədə",
   "Yalnız əmrdə", "İşlənmir"], 1, None, 3),
 ("«They have lived here ___ 2010.» boşluğu doldurun.",
  "Başlanğıc nöqtə ilə: since 2010.",
  ["since", "for", "ago", "yet"], 1, None, 3),
 ("«For» və «since» sözlərinin fərqi nədir?",
  "For müddəti, since başlanğıc anı bildirir.",
  ["For müddət, since başlanğıc", "Eyni mənadadırlar",
   "For yalnız keçmişdə", "Since müddət bildirir"],
  1, None, 3),
 ("«Go» feilinin III forması hansıdır?",
  "Go — went — gone.",
  ["gone", "went", "goed", "going"], 1, None, 2),
 ("«Have you finished? — Yes, I ___.»",
  "Qısa cavab: Yes, I have.",
  ["have", "did", "am", "will"], 1, None, 2),
 ("«Never» Present Perfect-də nəyi bildirir?",
  "Təcrübənin heç vaxt olmadığını.",
  ["Heç vaxt etməməyi", "Tez-tez etməyi",
   "İndicə etməyi", "Sabah edəcəyini"], 1, None, 2),
 ("«He has already left.» — «already» nə deməkdir?",
  "Already — artıq.",
  ["Artıq", "Hələ", "Heç vaxt", "Bəzən"], 1, None, 2),
],
"ing-8-media": [
 ("«Newspaper» nə deməkdir?",
  "Newspaper — qəzet.",
  ["Qəzet", "Jurnal", "Kitab", "Məktub"], 1, None, 1),
 ("«News» sözünün mənası nədir?",
  "News — xəbərlər.",
  ["Xəbərlər", "Mahnılar", "Oyunlar", "Şəkillər"],
  1, None, 1),
 ("«Channel» televiziyada nəyi bildirir?",
  "Channel — televiziya kanalı.",
  ["Kanalı", "Ekranı", "Pultu", "Antenanı"], 1, None, 2),
 ("«Advertisement» nə deməkdir?",
  "Advertisement — reklam.",
  ["Reklam", "Xəbər", "Hava proqnozu", "Film"], 1, None, 2),
 ("«Headline» qəzetdə nədir?",
  "Headline — məqalənin başlığı.",
  ["Başlıq", "Səhifə nömrəsi", "Şəkil", "Qiymət"],
  1, None, 2),
 ("«Journalist» nə ilə məşğuldur?",
  "Xəbər və məqalələr hazırlayır.",
  ["Xəbər hazırlayır", "Xəstə müalicə edir",
   "Ev tikir", "Yemək bişirir"], 1, None, 2),
 ("«Broadcast» feili nə deməkdir?",
  "Broadcast — efirə vermək, yayımlamaq.",
  ["Yayımlamaq", "Gizlətmək", "Satmaq", "Oxumaq"],
  1, None, 3),
 ("«Social media» nə deməkdir?",
  "Sosial şəbəkələr (media).",
  ["Sosial şəbəkələr", "Dövlət qəzetləri",
   "Kitabxanalar", "Radio dalğaları"], 1, None, 2),
 ("«Interview» nədir?",
  "Interview — müsahibə.",
  ["Müsahibə", "Elan", "Krossvord", "Reseptlər"],
  1, None, 2),
 ("«Mass media» ifadəsi nəyi əhatə edir?",
  "Kütləvi informasiya vasitələrini: TV, radio, mətbuat.",
  ["Kütləvi informasiya vasitələrini", "Yalnız kitabları",
   "Yalnız telefonları", "Məktəbləri"], 1, None, 3),
],
"ing-8-environment": [
 ("«Pollution» nə deməkdir?",
  "Pollution — çirklənmə.",
  ["Çirklənmə", "Təmizlik", "Yağış", "Bitki"], 1, None, 2),
 ("«Recycle» feilinin mənası nədir?",
  "Recycle — təkrar emal etmək.",
  ["Təkrar emal etmək", "Atmaq", "Yandırmaq", "Almaq"],
  1, None, 2),
 ("«Save energy» ifadəsi nəyə çağırır?",
  "Enerjiyə qənaət etməyə.",
  ["Enerjiyə qənaətə", "Enerjini israf etməyə",
   "İşıqları yandırmağa", "Su tökməyə"], 1, None, 2),
 ("«Endangered animals» hansı heyvanlardır?",
  "Nəsli kəsilmək təhlükəsində olanlar.",
  ["Nəsli kəsilmək təhlükəsində olanlar", "Ev heyvanları",
   "Ən sürətli heyvanlar", "Ən böyük heyvanlar"],
  1, None, 3),
 ("«Plant trees» nə deməkdir?",
  "Ağac əkmək.",
  ["Ağac əkmək", "Ağac kəsmək", "Meyvə yığmaq",
   "Bağ satmaq"], 1, None, 1),
 ("«Global warming» nədir?",
  "Qlobal istiləşmə — planetin orta temperaturunun artması.",
  ["Qlobal istiləşmə", "Qlobal soyuma", "Yerli yağışlar",
   "Küləklər"], 1, None, 2),
 ("«Litter» sözü nəyi bildirir?",
  "Litter — zibil.",
  ["Zibili", "Suyu", "İşığı", "Torpağı"], 1, None, 2),
 ("«Protect wildlife» ifadəsi nə deməkdir?",
  "Vəhşi təbiəti qorumaq.",
  ["Vəhşi təbiəti qorumaq", "Heyvanları ovlamaq",
   "Meşə yandırmaq", "Zibil atmaq"], 1, None, 2),
 ("«Reduce, reuse, recycle» şüarı nəyə aiddir?",
  "Tullantıların azaldılmasına və emalına.",
  ["Tullantıların azaldılmasına", "İdman qaydalarına",
   "Yemək reseptlərinə", "Dərs cədvəlinə"], 1, None, 3),
 ("«Eco-friendly» sözünün mənası nədir?",
  "Ətraf mühitə zərər verməyən.",
  ["Ətraf mühitə zərərsiz", "Çox bahalı", "Çox sürətli",
   "Köhnəlmiş"], 1, None, 3),
],
# ======================= INFORMATIKA 8 ================================
"inf-8-informasiya": [
 ("1 qiqabayt neçə meqabaytdır?",
  "1 GB = 1024 MB.",
  ["1024", "100", "10", "8"], 1, str(2 ** 10), 3),
 ("İnformasiya prosesləri hansılardır?",
  "Toplanma, saxlanma, emal və ötürülmə.",
  ["Toplanma, saxlanma, emal, ötürülmə", "Yalnız çap",
   "Yalnız oyun", "Yalnız silmə"], 1, None, 2),
 ("Onaltılıq say sistemində neçə simvoldan istifadə olunur?",
  "16 simvol: 0-9 rəqəmləri və A-F hərfləri.",
  ["16", "10", "2", "8"], 1, str(16), 3),
 ("İkilik «100» ədədi onluq sistemdə neçədir?",
  "1·4 + 0·2 + 0·1 = 4.",
  ["4", "100", "3", "8"], 1, str(int("100", 2)), 3),
 ("Unicode kodlaşdırması nə üçündür?",
  "Bütün dillərin simvollarını vahid kodlaşdırmaq üçün.",
  ["Bütün dillərin simvollarını kodlaşdırmaq üçün",
   "Yalnız rəqəmlər üçün", "Şəkil çəkmək üçün",
   "Səs yazmaq üçün"], 1, None, 3),
 ("1 bayt ilə neçə müxtəlif simvol kodlaşdırmaq olar?",
  "2⁸ = 256 müxtəlif kod.",
  ["256", "8", "16", "1024"], 1, str(2 ** 8), 3),
 ("Kompüterdə bütün informasiya hansı formada saxlanır?",
  "İkilik kod (0 və 1) şəklində.",
  ["İkilik kodda", "Hərflərlə", "Şəkillərlə",
   "Səslə"], 1, None, 2),
 ("Onaltılıq sistemdə 9-dan böyük qiymətlər hansı simvollarla "
  "göstərilir?",
  "A-dan F-yə qədər hərflərlə.",
  ["A-F hərfləri ilə", "Ulduzlarla", "Nöqtələrlə",
   "Göstərilmir"], 1, None, 3),
 ("İnformasiyanın emalı nədir?",
  "Mövcud məlumat əsasında yeni məlumatın alınması.",
  ["Mövcud məlumatdan yenisinin alınması",
   "Məlumatın silinməsi", "Kompüterin təmiri",
   "Kabellərin dəyişilməsi"], 1, None, 3),
 ("Verilənlər bazası nə üçün istifadə olunur?",
  "Böyük həcmli məlumatı nizamlı saxlamaq üçün.",
  ["Məlumatı nizamlı saxlamaq üçün", "Oyun oynamaq üçün",
   "Şəkil çəkmək üçün", "Musiqi bəstələmək üçün"],
  1, None, 3),
],
"inf-8-multimedia": [
 ("Multimedia nədir?",
  "Mətn, səs, qrafika və videonun birləşməsidir.",
  ["Mətn, səs, qrafika və videonun birləşməsi",
   "Yalnız mətn", "Yalnız səs", "Yalnız kağız"], 1, None, 2),
 ("Hansı format səs faylı formatıdır?",
  "MP3 — səs faylı formatıdır.",
  ["MP3", "PNG", "TXT", "EXE"], 1, None, 2),
 ("Video informasiya nədən ibarətdir?",
  "Ardıcıl kadrlardan və səs cığırından.",
  ["Kadrlardan və səsdən", "Yalnız mətndən",
   "Yalnız cədvəldən", "Düsturlardan"], 1, None, 3),
 ("Hansı format qrafik (şəkil) faylı formatıdır?",
  "PNG — şəkil formatıdır.",
  ["PNG", "MP3", "WAV", "DOC"], 1, None, 2),
 ("Animasiya necə yaranır?",
  "Şəkillərin sürətlə ardıcıl göstərilməsi ilə.",
  ["Şəkillərin sürətli ardıcıl göstərilməsi",
   "Bir şəklin çapı ilə", "Mətnin oxunması ilə",
   "Səsin yüksəldilməsi ilə"], 1, None, 3),
 ("Səs redaktoru nə üçündür?",
  "Səsi yazmaq və emal etmək üçün.",
  ["Səsi yazıb emal etmək üçün", "Şəkil kəsmək üçün",
   "Mətn yazmaq üçün", "Cədvəl qurmaq üçün"], 1, None, 2),
 ("Video emal edən proqramlar necə adlanır?",
  "Video redaktorlar adlanır.",
  ["Video redaktorlar", "Kalkulyatorlar", "Brauzerlər",
   "Antiviruslar"], 1, None, 2),
 ("Təqdimata hansı multimedia elementlərini əlavə etmək olar?",
  "Səs, video və animasiya əlavə etmək olar.",
  ["Səs, video, animasiya", "Yalnız mətn",
   "Heç nə", "Yalnız cədvəl"], 1, None, 2),
 ("Təsvirin piksel sayı (ölçüsü) nəyə təsir edir?",
  "Təsvirin keyfiyyətinə və detallılığına.",
  ["Təsvirin keyfiyyətinə", "Kompüterin rənginə",
   "Səsin ucalığına", "Klaviaturaya"], 1, None, 3),
 ("Kadr tezliyi (FPS) nəyi göstərir?",
  "Saniyədə göstərilən kadrların sayını.",
  ["Saniyədəki kadr sayını", "Faylın adını",
   "Ekranın ölçüsünü", "Rənglərin sayını"], 1, None, 3),
],
"inf-8-proqramlasdirma": [
 ("Proqramlaşdırma dilinə misal hansıdır?",
  "Python geniş yayılmış proqramlaşdırma dilidir.",
  ["Python", "Windows", "Google", "Wi-Fi"], 1, None, 2),
 ("x = x + 1 yazılışı nə edir?",
  "Dəyişənin qiymətini 1 vahid artırır.",
  ["Dəyişəni 1 vahid artırır", "Dəyişəni silir",
   "Tənliyi həll edir", "Səhvdir, mümkün deyil"],
  1, None, 3),
 ("Şərt operatoru hansı açar sözlərlə yazılır?",
  "if / else (əgər / əks halda).",
  ["if / else", "print / input", "for / to",
   "start / stop"], 1, None, 2),
 ("«while» dövrü nə vaxta qədər icra olunur?",
  "Şərt doğru olduqca təkrarlanır.",
  ["Şərt doğru olduqca", "Bir dəfə", "Heç vaxt",
   "Kompüter söndürülənədək"], 1, None, 3),
 ("Proqramda mətn tipli verilən necə adlanır?",
  "Mətn tipi sətir (string) adlanır.",
  ["Sətir (string)", "Tam ədəd", "Məntiqi tip",
   "Massiv"], 1, None, 3),
 ("Tam ədədləri saxlayan verilən tipi necə adlanır?",
  "Tam tip (integer).",
  ["Tam tip (integer)", "Sətir", "Kəsr tip",
   "Simvol"], 1, None, 3),
 ("Python-da nəticəni ekrana çıxaran əmr hansıdır?",
  "print əmri nəticəni çap edir.",
  ["print", "scan", "get", "write"], 1, None, 2),
 ("Sintaksis xətası nədir?",
  "Proqramlaşdırma dilinin yazılış qaydalarının pozulması.",
  ["Dil qaydalarının pozulması", "Kompüterin xarab olması",
   "Elektrik kəsilməsi", "Düzgün nəticə"], 1, None, 3),
 ("Məntiqi tip hansı qiymətləri alır?",
  "True (doğru) və False (yalan).",
  ["True və False", "0-dan 100-ə qədər", "Yalnız mətn",
   "Rənglər"], 1, None, 3),
 ("Proqramda şərh (komment) nə üçündür?",
  "Kodu izah edir, icra olunmur.",
  ["Kodu izah etmək üçün", "Proqramı sürətləndirmək üçün",
   "Xətaları silmək üçün", "Yaddaşı artırmaq üçün"],
  1, None, 2),
],
"inf-8-kompyuter": [
 ("Ana plata (motherboard) nə üçündür?",
  "Bütün qurğuları birləşdirir.",
  ["Qurğuları birləşdirmək üçün", "Səs yazmaq üçün",
   "Şəkil çəkmək üçün", "Sənəd çap etmək üçün"],
  1, None, 3),
 ("Videokart nəyə cavabdehdir?",
  "Ekrandakı təsvirin formalaşdırılmasına.",
  ["Təsvirin formalaşdırılmasına", "Səsin yazılmasına",
   "Mətnin yoxlanmasına", "İnternet sürətinə"],
  1, None, 3),
 ("SSD yaddaşın HDD-dən üstünlüyü nədir?",
  "Daha sürətlidir, hərəkətli hissəsi yoxdur.",
  ["Daha sürətlidir", "Daha ağırdır", "Daha səslidir",
   "Fərq yoxdur"], 1, None, 3),
 ("Əməli yaddaşın (RAM) həcmi nəyə təsir edir?",
  "Eyni anda işləyən proqramların sürətinə.",
  ["Proqramların işləmə sürətinə", "Ekranın rənginə",
   "Klaviaturanın dilinə", "Korpusun ölçüsünə"],
  1, None, 3),
 ("Periferiya qurğuları hansılardır?",
  "Sistem blokuna xaricdən qoşulan qurğular.",
  ["Xaricdən qoşulan qurğular", "Yalnız prosessor",
   "Yalnız yaddaş", "Proqramlar"], 1, None, 3),
 ("Drayver nədir?",
  "Qurğunu idarə edən xüsusi proqramdır.",
  ["Qurğunu idarə edən proqram", "Kompüter sürücüsü",
   "Oyun növü", "Kabel adı"], 1, None, 3),
 ("BIOS nə vaxt işə düşür?",
  "Kompüter qoşulan kimi ilk işə düşən proqramdır.",
  ["Kompüter qoşulan kimi", "Yalnız gecə",
   "İnternet açılanda", "Heç vaxt"], 1, None, 3),
 ("Kompüterin soyutma sistemi nə üçündür?",
  "Qurğuları həddindən artıq qızmadan qorumaq üçün.",
  ["Qızmadan qorumaq üçün", "Səsi artırmaq üçün",
   "Yaddaşı silmək üçün", "Bəzək üçün"], 1, None, 2),
 ("Noutbukun mobil enerji mənbəyi nədir?",
  "Akkumulyator (batareya).",
  ["Akkumulyator", "Günəş paneli", "Külək", "Buxar"],
  1, None, 2),
 ("USB portu nə üçün istifadə olunur?",
  "Xarici qurğuları qoşmaq üçün.",
  ["Xarici qurğuları qoşmaq üçün", "Havanı dəyişmək üçün",
   "Səsi yazmaq üçün", "Ekranı işıqlandırmaq üçün"], 1, None, 2),
],
"inf-8-tetbiqi": [
 ("Elektron cədvəl proqramına misal hansıdır?",
  "Excel elektron cədvəl proqramıdır.",
  ["Excel", "Paint", "Notepad", "Chrome"], 1, None, 2),
 ("Elektron cədvəldə xananın ünvanı necə yazılır?",
  "Sütun hərfi və sətir nömrəsi ilə: A1.",
  ["Sütun hərfi + sətir nömrəsi (A1)", "Yalnız rəqəmlə",
   "Yalnız hərflə", "Ünvanı olmur"], 1, None, 2),
 ("Elektron cədvəldə düstur hansı işarə ilə başlayır?",
  "Düsturlar = işarəsi ilə başlayır.",
  ["=", "+", "%", "#"], 1, None, 2),
 ("=A1+B1 düsturu nə edir?",
  "A1 və B1 xanalarının cəmini hesablayır.",
  ["İki xananın cəmini hesablayır", "Xanaları silir",
   "Şrift dəyişir", "Sətir əlavə edir"], 1, None, 2),
 ("SUM funksiyası nə üçündür?",
  "Diapazonun cəmini hesablamaq üçün.",
  ["Cəmi hesablamaq üçün", "Rəngləmək üçün",
   "Silmək üçün", "Çap etmək üçün"], 1, None, 2),
 ("Cədvəl məlumatları əsasında nə qurmaq olar?",
  "Diaqram qurmaq olar.",
  ["Diaqram", "Ev", "Oyun", "Mahnı"], 1, None, 2),
 ("Elektron cədvəli mətn prosessorundan fərqləndirən nədir?",
  "Cədvəl avtomatik hesablamalar aparır.",
  ["Avtomatik hesablamalar", "Yalnız mətn yazması",
   "Şəkil çəkməsi", "Fərq yoxdur"], 1, None, 3),
 ("Düsturda istifadə olunan xananın qiyməti dəyişəndə nəticə "
  "necə olur?",
  "Nəticə avtomatik yenilənir.",
  ["Avtomatik yenilənir", "Dəyişmir", "Silinir",
   "Xəta verir"], 1, None, 3),
 ("Verilənləri sıralamaq (sort) nə deməkdir?",
  "Artan və ya azalan qaydada düzmək.",
  ["Artan/azalan qaydada düzmək", "Silmək",
   "Rəngləmək", "Çap etmək"], 1, None, 2),
 ("Vektor qrafikası nədir?",
  "Həndəsi obyektlərlə (xətt, əyri) qurulan təsvirdir.",
  ["Həndəsi obyektlərlə qurulan təsvir",
   "Yalnız fotoşəkil", "Mətn sənədi", "Səs faylı"],
  1, None, 3),
],
"inf-8-internet": [
 ("İnformasiya cəmiyyəti nədir?",
  "İnformasiyanın əsas resurs olduğu cəmiyyətdir.",
  ["İnformasiyanın əsas resurs olduğu cəmiyyət",
   "Yalnız kitabxanalar", "Kompüter mağazası",
   "İnternet kafe"], 1, None, 3),
 ("Bulud texnologiyası nəyə imkan verir?",
  "Məlumatı internet serverlərində saxlamağa.",
  ["Məlumatı internetdə saxlamağa", "Yağış yağdırmağa",
   "Kompüteri soyutmağa", "Ekranı böyütməyə"], 1, None, 3),
 ("Elektron hökumət xidmətləri nəyə misaldır?",
  "Onlayn dövlət xidmətlərinə.",
  ["Onlayn dövlət xidmətlərinə", "Kompüter oyununa",
   "Video redaktoruna", "Qrafik redaktora"], 1, None, 3),
 ("Kiberbullinq nədir?",
  "İnternetdə təhqir, təzyiq və qorxutmadır.",
  ["İnternetdə təhqir və təzyiq", "İdman növü",
   "Proqram adı", "Kompüter hissəsi"], 1, None, 2),
 ("Güclü parol necə olmalıdır?",
  "Uzun, hərf-rəqəm-simvol qarışığı.",
  ["Uzun və qarışıq simvollu", "Ad və soyaddan ibarət",
   "12345 kimi sadə", "Doğum tarixi"], 1, None, 2),
 ("İkifaktorlu autentifikasiya nə üçündür?",
  "Hesabın təhlükəsizliyini artırmaq üçün.",
  ["Hesabın təhlükəsizliyi üçün", "Sürəti artırmaq üçün",
   "Reklam üçün", "Yaddaş üçün"], 1, None, 3),
 ("Fişinq nədir?",
  "Saxta saytlarla şəxsi məlumatların oğurlanması.",
  ["Saxta saytlarla məlumat oğurluğu", "Balıq ovu idmanı",
   "Fayl formatı", "Şəbəkə kabeli"], 1, None, 3),
 ("Antivirus proqramı nə edir?",
  "Zərərli proqramları aşkarlayıb zərərsizləşdirir.",
  ["Zərərli proqramları aşkarlayır", "Şəkil çəkir",
   "Mahnı çalır", "Sənəd yazır"], 1, None, 2),
 ("Şəxsi məlumatların qorunması necə adlanır?",
  "Məxfilik (konfidensiallıq).",
  ["Məxfilik", "Reklam", "Yayım", "Abunəlik"], 1, None, 3),
 ("Rəqəmsal iz nədir?",
  "İstifadəçinin internetdə qalan fəaliyyət izləridir.",
  ["İnternetdə qalan fəaliyyət izləri", "Ayaq izi",
   "Printer izi", "Kağız sənəd"], 1, None, 3),
],
# ==================== AZERBAYCAN TARIXI 8 =============================
"tarix-8-xvi-xvii": [
 ("XVI əsrdə Azərbaycan torpaqları əsasən hansı dövlətin "
  "tərkibində idi?",
  "Azərbaycan Səfəvi dövlətinin tərkibində idi.",
  ["Səfəvilər", "Roma", "Monqol imperiyası", "Fransa"],
  1, None, 2),
 ("I Təhmasib dövründə Səfəvi paytaxtı haraya köçürüldü?",
  "Paytaxt Təbrizdən Qəzvinə köçürüldü.",
  ["Qəzvinə", "Bakıya", "İstanbula", "Bağdada"], 1, None, 3),
 ("Şah I Abbasın apardığı əsas islahat hansı idi?",
  "Nizami ordu yaratdı (ordu islahatı).",
  ["Ordu islahatı", "Əlifba islahatı", "Təqvim islahatı",
   "Heç bir islahat"], 1, None, 3),
 ("Osmanlı-Səfəvi müharibələrinin əsas səbəbi nə idi?",
  "Ərazi və ticarət yolları uğrunda mübarizə.",
  ["Ərazi uğrunda mübarizə", "İdman yarışı",
   "Elm mübahisəsi", "Səbəbsiz"], 1, None, 3),
 ("1555-ci il Amasiya sülhü hansı dövlətlər arasında bağlandı?",
  "Səfəvilərlə Osmanlı arasında.",
  ["Səfəvilərlə Osmanlı", "Rusiya ilə Fransa",
   "İngiltərə ilə İspaniya", "Çinlə Yaponiya"], 1, None, 3),
 ("Səfəvi ordusunun əsasını əvvəllər hansı tayfalar təşkil "
  "edirdi?",
  "Qızılbaş tayfaları təşkil edirdi.",
  ["Qızılbaş tayfaları", "Vikinqlər", "Səlibçilər",
   "Kazaklar"], 1, None, 3),
 ("XVII əsrdə Azərbaycanda hansı təsərrüfat sahəsi xüsusilə "
  "gəlirli idi?",
  "İpəkçilik mühüm gəlir mənbəyi idi.",
  ["İpəkçilik", "Kosmik sənaye", "Avtomobilqayırma",
   "Neft emalı"], 1, None, 3),
 ("Şah I Abbas paytaxtı hansı şəhərə köçürdü?",
  "Paytaxt İsfahana köçürüldü.",
  ["İsfahana", "Gəncəyə", "Şamaxıya", "Qahirəyə"],
  1, None, 3),
 ("XVII əsrdə Azərbaycan şəhərlərində hansı sənət növü şöhrət "
  "qazanmışdı?",
  "Xalçaçılıq dünyada məşhur idi.",
  ["Xalçaçılıq", "Saatsazlıq", "Gəmiqayırma",
   "Çap maşınları"], 1, None, 2),
 ("Səfəvi dövlətini kim idarə edirdi?",
  "Dövləti şah idarə edirdi.",
  ["Şah", "Prezident", "Sultan", "Parlament"],
  1, None, 1),
],
"tarix-8-xviii-1": [
 ("XVIII əsrin əvvəllərində Səfəvi dövləti hansı vəziyyətdə idi?",
  "Dövlət zəifləmiş və tənəzzülə uğramışdı.",
  ["Zəifləmişdi", "Ən qüdrətli dövründə idi",
   "Yenicə yaranmışdı", "Amerikaya köçmüşdü"], 1, None, 2),
 ("Nadir hansı ildə özünü şah elan etdi?",
  "1736-cı ildə Muğan qurultayında şah seçildi.",
  ["1736", "1918", "1501", "1828"], 1, None, 3),
 ("Nadir şahın hakimiyyəti necə bitdi?",
  "1747-ci ildə sui-qəsdlə öldürüldü.",
  ["Sui-qəsdlə öldürüldü", "Taxtdan könüllü getdi",
   "Xaricə köçdü", "Seçkidə uduzdu"], 1, None, 3),
 ("Nadir şah hansı ölkəyə məşhur yürüş etmişdi?",
  "1739-cu ildə Hindistana (Dehliyə) yürüş etdi.",
  ["Hindistana", "İspaniyaya", "Norveçə", "Yaponiyaya"],
  1, None, 3),
 ("XVIII əsrin I yarısında Azərbaycan torpaqları hansı dövlətlər "
  "arasında bölüşdürülmüşdü?",
  "Səfəvi, Osmanlı və Rusiya arasında.",
  ["Səfəvi, Osmanlı və Rusiya", "İngiltərə və Fransa",
   "Çin və Yaponiya", "Heç kim arasında"], 1, None, 3),
 ("1724-cü il İstanbul müqaviləsi kimlər arasında bağlanmışdı?",
  "Rusiya ilə Osmanlı arasında.",
  ["Rusiya ilə Osmanlı", "Səfəvilərlə Fransa",
   "İngiltərə ilə İspaniya", "Xanlıqlar arasında"],
  1, None, 3),
 ("Xəzərsahili torpaqlara yürüş edən rus çarı kim idi?",
  "I Pyotr 1722–1723-cü illərdə yürüş etdi.",
  ["I Pyotr", "II Yekaterina", "İvan Qroznı", "Nikolay"],
  1, None, 3),
 ("Nadir şahın qurduğu dövlət hansı adla tanınır?",
  "Əfşarlar dövləti adlanır.",
  ["Əfşarlar dövləti", "Səlcuq dövləti", "Atabəylər",
   "Şirvanşahlar"], 1, None, 3),
 ("Muğan qurultayı hansı məqsədlə çağırılmışdı?",
  "Nadirin şah seçilməsi üçün.",
  ["Nadirin şah seçilməsi üçün", "İdman yarışı üçün",
   "Bayram üçün", "Ticarət üçün"], 1, None, 3),
 ("Nadir şahın ölümündən sonra Azərbaycanda nə yarandı?",
  "Müstəqil xanlıqlar yarandı.",
  ["Müstəqil xanlıqlar", "Vahid imperiya",
   "Respublika", "Koloniyalar"], 1, None, 2),
],
"tarix-8-xanliqlar": [
 ("Azərbaycanda xanlıqlar hansı dövrdə yarandı?",
  "XVIII əsrin ortalarında yarandı.",
  ["XVIII əsrin ortalarında", "XII əsrdə", "XX əsrdə",
   "E.ə. V əsrdə"], 1, None, 2),
 ("Qarabağ xanlığının banisi kimdir?",
  "Xanlığı Pənahəli xan yaratmışdır.",
  ["Pənahəli xan", "Fətəli xan", "Hacı Çələbi",
   "Cavad xan"], 1, None, 2),
 ("Quba xanlığının məşhur hökmdarı kim olmuşdur?",
  "Fətəli xan Quba xanlığını gücləndirdi.",
  ["Fətəli xan", "Pənahəli xan", "Nadir şah",
   "Şah İsmayıl"], 1, None, 3),
 ("Şəki xanlığının banisi kimdir?",
  "Xanlığı Hacı Çələbi yaratmışdır.",
  ["Hacı Çələbi", "Cavad xan", "Fətəli xan",
   "İbrahimxəlil xan"], 1, None, 3),
 ("İrəvan, Naxçıvan, Gəncə — bu şəhərlər XVIII əsrdə nə idi?",
  "Ayrı-ayrı xanlıqların mərkəzləri idi.",
  ["Xanlıq mərkəzləri", "Rusiya quberniyaları",
   "Osmanlı paytaxtları", "Kəndlər"], 1, None, 2),
 ("Quba xanı Fətəli xanın əsas məqsədi nə idi?",
  "Azərbaycan torpaqlarını vahid dövlətdə birləşdirmək.",
  ["Torpaqları birləşdirmək", "Xanlığı satmaq",
   "Paytaxtı köçürmək", "Dənizçilik qurmaq"], 1, None, 3),
 ("Xanlıqları kim idarə edirdi?",
  "Xanlıqları xanlar idarə edirdi.",
  ["Xanlar", "Prezidentlər", "Qubernatorlar",
   "Sultanlar"], 1, None, 1),
 ("Ağa Məhəmməd şah Qacar harada öldürüldü?",
  "1797-ci ildə Şuşada öldürüldü.",
  ["Şuşada", "Bakıda", "Təbrizdə", "Tehranda"], 1, None, 3),
 ("Xanlıqların zəifliyinin əsas səbəbi nə idi?",
  "Ara müharibələri və vahid birliyin olmaması.",
  ["Ara müharibələri, birliyin olmaması",
   "Torpağın azlığı", "Əhalinin çoxluğu",
   "Dənizin uzaqlığı"], 1, None, 3),
 ("Şəki xanlığının mərkəzi hansı şəhər idi?",
  "Mərkəz Şəki şəhəri idi.",
  ["Şəki", "Şamaxı", "Lənkəran", "Dərbənd"], 1, None, 1),
],
"tarix-8-xix": [
 ("XIX əsrin əvvəllərində Azərbaycan uğrunda hansı dövlətlər "
  "müharibə aparırdı?",
  "Rusiya ilə Qacarlar İranı müharibə aparırdı.",
  ["Rusiya və Qacarlar İranı", "İngiltərə və Fransa",
   "Osmanlı və Misir", "Çin və Hindistan"], 1, None, 2),
 ("1813-cü ildə hansı müqavilə imzalandı?",
  "Gülüstan müqaviləsi imzalandı.",
  ["Gülüstan", "Türkmənçay", "Amasiya", "İstanbul"],
  1, None, 3),
 ("1828-ci il Türkmənçay müqaviləsi ilə nə baş verdi?",
  "Azərbaycan torpaqları iki dövlət arasında bölündü.",
  ["Azərbaycan iki hissəyə bölündü", "Xanlıqlar bərpa olundu",
   "Müharibə başladı", "Heç nə dəyişmədi"], 1, None, 3),
 ("Türkmənçay müqaviləsinə görə sərhəd hansı çay üzrə keçdi?",
  "Sərhəd Araz çayı üzrə müəyyənləşdi.",
  ["Araz", "Kür", "Volqa", "Nil"], 1, None, 3),
 ("Birinci Rusiya-İran müharibəsi hansı illərdə olmuşdur?",
  "1804–1813-cü illərdə.",
  ["1804–1813", "1918–1920", "1700–1721", "1941–1945"],
  1, None, 3),
 ("İkinci Rusiya-İran müharibəsi hansı müqavilə ilə bitdi?",
  "1828-ci il Türkmənçay müqaviləsi ilə.",
  ["Türkmənçay", "Gülüstan", "Amasiya", "Versal"],
  1, None, 3),
 ("Rusiya işğalından sonra xanlıqların taleyi necə oldu?",
  "Xanlıqlar tədricən ləğv edildi.",
  ["Ləğv edildi", "Gücləndirildi", "Birləşdirildi",
   "Müstəqil qaldı"], 1, None, 3),
 ("Gülüstan müqaviləsi harada imzalanmışdır?",
  "Qarabağın Gülüstan kəndində.",
  ["Qarabağın Gülüstan kəndində", "Moskvada",
   "Parisdə", "İstanbulda"], 1, None, 3),
 ("Gəncəni rus qoşunlarından qəhrəmancasına müdafiə edən xan "
  "kim idi?",
  "Cavad xan Gəncənin müdafiəsində həlak oldu.",
  ["Cavad xan", "Fətəli xan", "Pənahəli xan",
   "Hacı Çələbi"], 1, None, 3),
 ("Şimali Azərbaycanın Rusiyaya birləşdirilməsi hansı iki "
  "müqavilə ilə rəsmiləşdi?",
  "Gülüstan (1813) və Türkmənçay (1828) müqavilələri ilə.",
  ["Gülüstan və Türkmənçay", "Amasiya və İstanbul",
   "Versal və Yalta", "Heç bir müqavilə ilə"], 1, None, 3),
],
}


def yoxla():
    n = xeta = 0
    butun = set()
    movzu_fenn = {m: f for f, m, _r in MOVZULAR}
    for movzu, siyahi in SUALLAR.items():
        assert movzu in movzu_fenn, movzu
        if len(siyahi) != 10:
            print("XETA  %s: %d sual (10 olmalidir)" % (movzu, len(siyahi)))
            xeta += 1
        for body, why, opts, correct, expect, diff in siyahi:
            n += 1
            p = []
            if len(opts) != 4: p.append("variant sayi %d" % len(opts))
            if len(set(opts)) != len(opts): p.append("tekrar variant")
            if not (1 <= correct <= 4): p.append("correct")
            if not why: p.append("izah bos")
            if diff not in (1, 2, 3): p.append("cetinlik")
            if body in butun: p.append("eyni sual iki defe")
            butun.add(body)
            if expect is not None and opts[correct - 1] != expect:
                p.append("hesablanan «%s» != variant «%s»" % (expect, opts[correct - 1]))
            for t in [body, why] + opts:
                if "'" in t: p.append("apostrof var")
            if p:
                xeta += 1
                print("XETA  %s: %s\n      %s" % (movzu, body[:60], "; ".join(p)))
    hes = sum(1 for s in SUALLAR.values() for q in s if q[4] is not None)
    print("%d sual yoxlandı (%d-i hesabla təsdiqləndi), %d xəta" % (n, hes, xeta))
    return xeta == 0, n


def sql_yaz(n):
    q = lambda t: t.replace("'", "''")
    on = {"az-dili": "az8", "ingilis-dili": "ing8",
          "informatika": "inf8", "tarix": "tarix8"}
    setirler = []
    for fenn, movzu, rub in MOVZULAR:
        qisa = movzu.split("-", 2)[2]
        for i, (body, why, opts, correct, _e, diff) in enumerate(SUALLAR[movzu], 1):
            setirler.append(
                "('%s-%s#%d','%s','%s',%d,%d,'%s','%s',array['%s','%s','%s','%s'],%d)"
                % (on[fenn], qisa, i, fenn, movzu, diff, rub, q(body), q(why),
                   q(opts[0]), q(opts[1]), q(opts[2]), q(opts[3]), correct))
    with io.open(CIXIS, "w", encoding="utf-8") as f:
        f.write("""-- =====================================================================
--  39_bank_sinif8.sql : 8-CI SINIF - AZ DILI, INGILIS DILI,
--                       INFORMATIKA, AZERBAYCAN TARIXI
--
--  BU FAYL ELLE YAZILMIR - tools/sinif8.py yaradir:
--      python3 tools/sinif8.py
--
--  Az dili 8 + Ingilis dili 6 + Informatika 6 + Tarix 4
--  = 24 movzu x 10 = %d.  ext_key: az8-/ing8-/inf8-/tarix8-...
--  ON SERT: 37_movzular_orta8.sql islenmis olmalidir.
--  SONRA:   05_grants.sql yeniden islet.
-- =====================================================================

do $$
begin
  if not exists (select 1 from public.topics t join public.subjects s
      on s.id = t.subject_id
     where (s.slug, t.slug) in (('az-dili','az-8-hemcins'),
                                ('ingilis-dili','ing-8-media'),
                                ('informatika','inf-8-multimedia'),
                                ('tarix','tarix-8-xanliqlar'))
     having count(*) = 4) then
    raise exception 'ONCE 37_movzular_orta8.sql isledilmelidir.';
  end if;
end $$;

delete from public.question_options o
 using public.questions q
 where o.question_id = q.id
   and q.owner_type = 'platform'
   and (q.ext_key like 'az8-%%' or q.ext_key like 'ing8-%%'
        or q.ext_key like 'inf8-%%' or q.ext_key like 'tarix8-%%');

with d(ext, fenn, topic, diff, rub, body, why, opts, correct) as (values
%s
),
ins as (
  insert into public.questions
    (ext_key, owner_type, subject_id, level_id, topic_id, kind,
     body, explanation, difficulty, quarter, status)
  select d.ext, 'platform', s.id, l.id, tp.id, 'single',
         d.body, d.why, d.diff, d.rub, 'published'
    from d
    join public.subjects s on s.slug = d.fenn
    join public.programs p on p.slug = 'orta'
    join public.levels   l on l.program_id = p.id and l.code = '8'
    join public.topics   tp on tp.subject_id = s.id and tp.slug = d.topic
  on conflict (ext_key) do update
    set body = excluded.body, explanation = excluded.explanation,
        difficulty = excluded.difficulty, quarter = excluded.quarter,
        topic_id = excluded.topic_id, level_id = excluded.level_id,
        subject_id = excluded.subject_id, status = 'published'
  returning id, ext_key
)
insert into public.question_options (question_id, ord, body, is_correct)
select ins.id, o.ord, o.txt, o.ord = d.correct
  from ins
  join d on d.ext = ins.ext_key,
  lateral unnest(d.opts) with ordinality as o(txt, ord);

do $$
declare n int; k int;
begin
  select count(*) into n from public.questions
   where owner_type = 'platform'
     and (ext_key like 'az8-%%' or ext_key like 'ing8-%%'
          or ext_key like 'inf8-%%' or ext_key like 'tarix8-%%');
  if n <> %d then
    raise exception 'sinif8 suallari: %d gozlenilirdi, %% tapildi', n;
  end if;
  select count(*) into k from public.questions q
   where (q.ext_key like 'az8-%%' or q.ext_key like 'ing8-%%'
          or q.ext_key like 'inf8-%%' or q.ext_key like 'tarix8-%%')
     and ((select count(*) from public.question_options o
            where o.question_id = q.id) <> 4
       or (select count(*) from public.question_options o
            where o.question_id = q.id and o.is_correct) <> 1);
  if k > 0 then
    raise exception '%% sualda variant qurulusu sehvdir', k;
  end if;
  select count(distinct topic_id) into k from public.questions
   where ext_key like 'az8-%%' or ext_key like 'ing8-%%'
      or ext_key like 'inf8-%%' or ext_key like 'tarix8-%%';
  if k <> 24 then
    raise exception 'movzu sayi 24 deyil: %%', k;
  end if;
  raise notice '8-ci sinif banki: %% sual, 24 movzu (az, ing, inf, tarix).', n;
end $$;
""" % (n, ",\n".join(setirler), n, n))
    print("yazildi: %s" % CIXIS)


if __name__ == "__main__":
    ok, n = yoxla()
    if not ok:
        raise SystemExit(1)
    sql_yaz(n)
