#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
6-ci sinfin humanitar fennleri -> db/31_bank_sinif6.sql

    Azerbaycan dili 6      8 movzu x 20 =  80
    Ingilis dili 6         8 movzu x 20 =  80
    Informatika 6          5 movzu x 20 =  50
    Azerbaycan tarixi 6    6 movzu x 20 = 120
                                    cemi  240

tools/sinif5.py qelibi ile.  Movzular 29_movzular_orta6.sql agacina
uygundur.  Ikilik say sistemi suallari int(x, 2) ile hesablanir.
Tarix suallari yalniz derslik seviyyeli, subhesiz faktlardir
(Azixantrop, Manna-Iranzu, Atropatena-Qazaka, Albaniya-Qebele,
Sasaniler ve s.).

DIQQET: evvelki bank fayllarinin (07, 16-28) cumle qelibleri
tekrarlanmayib - generator pg_trgm ile >= 0.95 oxsarligi tekrar sayir.

Isletmek:
    python3 tools/sinif6.py
"""
import io
import os

KOK = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CIXIS = os.path.join(KOK, "db", "31_bank_sinif6.sql")

#  (fenn, movzu-slug, rub)
MOVZULAR = [
    ("az-dili", "az-6-fonetika",        1),
    ("az-dili", "az-6-yazi",            1),
    ("az-dili", "az-6-soz-luget",       2),
    ("az-dili", "az-6-isim-hal",        2),
    ("az-dili", "az-6-qosma-baglayici", 3),
    ("az-dili", "az-6-say-numerativ",   3),
    ("az-dili", "az-6-cumle-uzvleri",   4),
    ("az-dili", "az-6-soz-sirasi",      4),
    ("ingilis-dili", "ing-6-town",     1),
    ("ingilis-dili", "ing-6-food",     1),
    ("ingilis-dili", "ing-6-holiday",  2),
    ("ingilis-dili", "ing-6-stories",  2),
    ("ingilis-dili", "ing-6-journeys", 3),
    ("ingilis-dili", "ing-6-heroes",   3),
    ("ingilis-dili", "ing-6-ideas",    4),
    ("ingilis-dili", "ing-6-nature",   4),
    ("informatika", "inf-6-kompyuter",        1),
    ("informatika", "inf-6-proqram-teminati", 2),
    ("informatika", "inf-6-alqoritm",         3),
    ("informatika", "inf-6-proqramlasdirma",  3),
    ("informatika", "inf-6-internet",         4),
    ("tarix", "tarix-6-ibtidai",         1),
    ("tarix", "tarix-6-qedim-dovletler", 2),
    ("tarix", "tarix-6-erken-orta",      3),
]

SUALLAR = {
# ===================== AZERBAYCAN DILI 6 ==============================
"az-6-fonetika": [
 ("«Ağıl» sözünə saitlə başlanan şəkilçi artıranda (ağlım) hansı "
  "hadisə baş verir?",
  "İkinci hecanın saiti düşür — səsdüşümü baş verir.",
  ["Səsdüşümü", "Səsartımı", "Vurğu dəyişməsi", "Heç nə"],
  1, None, 2),
 ("«Oğul» sözü «oğlu» formasında işlənəndə hansı sait düşür?",
  "Oğul → oğlu: ikinci hecadakı «u» saiti düşür.",
  ["u", "o", "ğ", "l"], 1, None, 2),
 ("«Qapı» sözünə yönlük hal şəkilçisi artıranda (qapıya) hansı "
  "samit əlavə olunur?",
  "İki sait arasına bitişdirici «y» samiti artırılır.",
  ["y", "n", "s", "ş"], 1, None, 2),
 ("«Dostlar» sözünün tələffüzündə hansı samit düşür?",
  "Üç samit yanaşı gələndə ortadakı düşür: [doslar].",
  ["t", "d", "s", "r"], 1, None, 3),
 ("Vurğu nədir?",
  "Sözdə hecalardan birinin daha qüvvətli deyilməsidir.",
  ["Hecanın qüvvətli deyilməsi", "Sözün mənası",
   "Hərflərin sayı", "Cümlənin sonu"], 1, None, 2),
 ("Azərbaycan dilində vurğu adətən hansı hecaya düşür?",
  "Dilimizdə vurğu əsasən son hecaya düşür.",
  ["Son hecaya", "İlk hecaya", "Orta hecaya",
   "İstənilən hecaya"], 1, None, 2),
 ("«Haqq» sözünə saitlə başlanan şəkilçi artıranda necə yazılır?",
  "Qoşa samit saxlanılır: haqqı.",
  ["haqqı", "haqı", "hağı", "haqqqı"], 1, None, 3),
 ("«Stəkan» tipli sözlərin tələffüzündə bəzən nə baş verir?",
  "Söz əvvəlindəki qoşa samitin qarşısına sait artırılır: "
  "[istəkan] — səsartımı.",
  ["Səsartımı", "Səsdüşümü", "Vurğu itir", "Samit düşür"],
  1, None, 3),
 ("Danışıq səslərini öyrənən dilçilik bölməsi necə adlanır?",
  "Səsləri fonetika öyrənir.",
  ["Fonetika", "Leksika", "Qrammatika", "Orfoqrafiya"],
  1, None, 1),
 ("«Meyvə» sözündə neçə səs və neçə hərf var?",
  "M-e-y-v-ə: 5 səs, 5 hərf.",
  ["5 səs, 5 hərf", "4 səs, 5 hərf", "5 səs, 4 hərf",
   "6 səs, 5 hərf"], 1,
  "%d səs, %d hərf" % (len("meyvə"), len("meyvə")), 2),
],
"az-6-yazi": [
 ("Hansı söz defislə yazılır?",
  "Təkrar sözlər defislə yazılır: qaça-qaça.",
  ["qaça-qaça", "dəmiryol", "günəbaxan", "kitabxana"],
  1, None, 2),
 ("Sözlərin təkrarından yaranan mürəkkəb sözlər necə yazılır?",
  "Təkrardan yaranan sözlər defislə yazılır.",
  ["Defislə", "Bitişik", "Ayrı", "Dırnaqda"], 1, None, 2),
 ("Mürəkkəb şəxs adları (Əli + ağa) necə yazılır?",
  "Mürəkkəb adlar bitişik yazılır: Əlağa.",
  ["Bitişik", "Defislə", "Ayrı", "Kiçik hərflə"], 1, None, 2),
 ("Hansı mürəkkəb yer adı düzgün yazılıb?",
  "Mürəkkəb yer adları bitişik yazılır: Ağdam.",
  ["Ağdam", "Ağ-dam", "Ağ dam", "ağdam"], 1, None, 2),
 ("«Alma-armud» tipli sözlər nəyi bildirir?",
  "Yaxın əşyaların ümumiləşmiş toplusunu bildirir.",
  ["Ümumiləşmiş topluluğu", "Yalnız bir əşyanı",
   "Hərəkəti", "Rəngi"], 1, None, 3),
 ("«Foto-» hissəsi ilə başlanan alınma sözlər necə yazılır?",
  "Bitişik yazılır: fotoaparat.",
  ["Bitişik", "Defislə", "Ayrı", "Dırnaqda"], 1, None, 3),
 ("Hansı söz bitişik yazılır?",
  "Kitabxana mürəkkəb söz kimi bitişik yazılır.",
  ["kitabxana", "qaça-qaça", "az-çox", "beş-üç"], 1, None, 2),
 ("«Az çox», «azçox», «az-çox» yazılışlarından hansı düzgündür?",
  "Əks mənalı təkrar sözlər defislə yazılır: az-çox.",
  ["az-çox", "azçox", "az çox", "az. çox"], 1, None, 2),
 ("«Vitse-» hissəsi ilə düzələn vəzifə adları necə yazılır?",
  "Defislə yazılır: vitse-prezident.",
  ["Defislə", "Bitişik", "Ayrı", "Böyük hərflə bitişik"],
  1, None, 3),
 ("Hiperonim nədir?",
  "Ümumi anlayış bildirən sözdür: «meyvə» — «alma» üçün "
  "hiperonimdir.",
  ["Ümumi anlayış bildirən söz", "Əks mənalı söz",
   "Alınma söz", "Təkrar söz"], 1, None, 3),
],
"az-6-soz-luget": [
 ("Sözün başlanğıc forması necə olur?",
  "Qrammatik şəkilçilərsiz forma başlanğıc formadır.",
  ["Qrammatik şəkilçisiz", "Cəm şəkilçili", "Hal şəkilçili",
   "Mənsubiyyət şəkilçili"], 1, None, 2),
 ("«Kitablarımızdan» sözünün başlanğıc forması hansıdır?",
  "Şəkilçiləri atsaq: kitab.",
  ["kitab", "kitablar", "kitabımız", "kitabdan"], 1, None, 2),
 ("Hansı cərgədə eyniköklü sözlər verilib?",
  "Duz, duzlu, duzsuz — hamısı «duz» kökündəndir.",
  ["duz, duzlu, duzsuz", "duz, dad, tam",
   "su, çay, göl", "gəl, get, dur"], 1, None, 2),
 ("«Yazı, yazıçı, yazmaq» sözlərini birləşdirən cəhət nədir?",
  "Üçü də «yaz» kökündən yaranıb — eyniköklüdür.",
  ["Eyni kökdən yaranmaları", "Eyni şəkilçi",
   "Eyni heca sayı", "Əks mənalı olmaları"], 1, None, 2),
 ("«Su» kökündən yaranan sözü seçin.",
  "Sulu = su + lu.",
  ["sulu", "sükan", "sürü", "süd"], 1, None, 2),
 ("Sözün lüğəvi (leksik) mənasını daşıyan hissəsi hansıdır?",
  "Əsas mənanı kök daşıyır.",
  ["Kök", "Cəm şəkilçisi", "Hal şəkilçisi", "Sonluq"],
  1, None, 2),
 ("«Dənizçilik» sözündə neçə şəkilçi var?",
  "Dəniz + çi + lik: iki leksik şəkilçi.",
  ["2", "1", "3", "0"], 1, None, 3),
 ("«Başla» sözünün kökü hansıdır?",
  "Başla = baş + la.",
  ["baş", "başla", "la", "aş"], 1, None, 2),
 ("Eyniköklü sözlər hansı yolla yaranır?",
  "Kökə leksik (sözdüzəldici) şəkilçilər artırmaqla.",
  ["Kökə leksik şəkilçilər artırmaqla", "Sözü təkrarlamaqla",
   "Vurğunu dəyişməklə", "Hərfləri dəyişməklə"], 1, None, 3),
 ("«Duzlu» və «dadlı» sözləri eyniköklüdürmü?",
  "Kökləri fərqlidir (duz və dad) — eyniköklü deyil.",
  ["Xeyr, kökləri fərqlidir", "Bəli, eyniköklüdür",
   "Hər ikisi köksüzdür", "Bilmək olmaz"], 1, None, 2),
],
"az-6-isim-hal": [
 ("Dilimizdə ismin hallarının sayı neçədir?",
  "İsmin 6 halı var.",
  ["6", "5", "4", "9"], 1, None, 2),
 ("«Kitabı oxudum» cümləsində «kitabı» hansı haldadır?",
  "Nəyi? sualına cavab verir — təsirlik haldadır.",
  ["Təsirlik", "Adlıq", "Yönlük", "Yerlik"], 1, None, 2),
 ("Adlıq hal hansı suallara cavab verir?",
  "Adlıq hal «kim? nə? hara?» suallarına cavab verir.",
  ["Kim? Nə?", "Kimin? Nəyin?", "Kimə? Nəyə?", "Kimdən? Nədən?"],
  1, None, 1),
 ("«Məktəbin həyəti» birləşməsində «məktəbin» hansı haldadır?",
  "Kimin? nəyin? — yiyəlik haldadır.",
  ["Yiyəlik", "Təsirlik", "Çıxışlıq", "Adlıq"], 1, None, 2),
 ("Qeyri-müəyyən yiyəlik hala uyğun nümunə hansıdır?",
  "«Sinif otağı» — birinci tərəf şəkilçisizdir.",
  ["sinif otağı", "sinfin otağı", "sinifdə otaq",
   "sinifdən otaq"], 1, None, 3),
 ("«Evə» sözü hansı haldadır?",
  "Haraya? — yönlük haldadır.",
  ["Yönlük", "Yerlik", "Çıxışlıq", "Yiyəlik"], 1, None, 2),
 ("«Şəhərdə» sözünün halı hansıdır?",
  "Harada? — yerlik haldır.",
  ["Yerlik", "Yönlük", "Təsirlik", "Adlıq"], 1, None, 2),
 ("«Kənddən» sözü hansı haldadır?",
  "Haradan? — çıxışlıq haldadır.",
  ["Çıxışlıq", "Yerlik", "Yönlük", "Yiyəlik"], 1, None, 2),
 ("«Kitab oxuyuram» cümləsində «kitab» sözü hansı halda işlənib?",
  "Şəkilçisiz təsirlik — qeyri-müəyyən təsirlik haldadır.",
  ["Qeyri-müəyyən təsirlik", "Adlıq", "Yiyəlik", "Yerlik"],
  1, None, 3),
 ("«Suyu içdim» və «su içdim» ifadələrinin fərqi nədir?",
  "Birincidə müəyyən, ikincidə qeyri-müəyyən təsirlik hal işlənib.",
  ["Müəyyən və qeyri-müəyyən təsirlik", "Hal fərqi yoxdur",
   "Birinci cəmdir", "İkinci yiyəlikdədir"], 1, None, 3),
],
"az-6-qosma-baglayici": [
 ("Qoşma hansı nitq hissələri qrupuna aiddir?",
  "Qoşma köməkçi nitq hissəsidir.",
  ["Köməkçi", "Əsas", "İsim qrupuna", "Feil qrupuna"],
  1, None, 2),
 ("«Məktəbə qədər» birləşməsində «qədər» sözü nədir?",
  "Qədər — məsafə/hüdud bildirən qoşmadır.",
  ["Qoşma", "İsim", "Feil", "Sifət"], 1, None, 2),
 ("Bağlayıcılar nəyi bağlayır?",
  "Sözləri və cümlələri bir-birinə bağlayır.",
  ["Sözləri və cümlələri", "Yalnız hecaları",
   "Yalnız hərfləri", "Heç nəyi"], 1, None, 2),
 ("«Və, amma, lakin» sözləri hansı nitq hissəsidir?",
  "Bunlar bağlayıcılardır.",
  ["Bağlayıcı", "Qoşma", "Əvəzlik", "Zərf"], 1, None, 1),
 ("«Üçün» qoşması əsasən hansı mənanı bildirir?",
  "Üçün — məqsəd və səbəb bildirir.",
  ["Məqsəd və səbəb", "Zaman", "Rəng", "Say"], 1, None, 2),
 ("«Yağış yağdı, amma biz gəzintiyə çıxdıq» cümləsində bağlayıcı "
  "hansıdır?",
  "Amma — qarşılaşdırma bağlayıcısıdır.",
  ["amma", "yağış", "biz", "çıxdıq"], 1, None, 2),
 ("«Qədər, kimi, üçün» qoşmaları əsasən hansı sözlərə qoşulur?",
  "Qoşmalar adlara (isimlərə, əvəzliklərə) qoşulur.",
  ["Adlara", "Yalnız feillərə", "Bağlayıcılara",
   "Nidalara"], 1, None, 3),
 ("Hansı cümlədə «ilə» birgəlik bildirir?",
  "«Dostu ilə gəldi» — birlikdə gəlmə bildirir.",
  ["Dostu ilə gəldi.", "Qatarla getdi.", "Qələm ilə yazdı.",
   "Sevinclə danışdı."], 1, None, 3),
 ("Hansı cərgədə yalnız qoşmalar verilib?",
  "Kimi, qədər, üçün — hamısı qoşmadır.",
  ["kimi, qədər, üçün", "və, ki, amma", "mən, sən, o",
   "tez, gec, indi"], 1, None, 2),
 ("«Lakin» bağlayıcısı cümlələr arasında hansı əlaqəni yaradır?",
  "Lakin — qarşılaşdırma (ziddiyyət) bildirir.",
  ["Qarşılaşdırma", "Səbəb", "Zaman ardıcıllığı",
   "Bərabərlik"], 1, None, 3),
],
"az-6-say-numerativ": [
 ("Saylardan sonra gələn isimlər hansı formada işlənir?",
  "Saydan sonra isim təkdə olur: beş kitab.",
  ["Təkdə", "Cəmdə", "Yiyəlik halda", "Çıxışlıq halda"],
  1, None, 2),
 ("«Beş kitablar» ifadəsindəki səhv nədir?",
  "Saydan sonra isim cəmlənmir — «beş kitab» olmalıdır.",
  ["İsim cəmdə olmamalıdır", "Say səhv yazılıb",
   "Söz sırası səhvdir", "Səhv yoxdur"], 1, None, 2),
 ("Numerativ sözlər hansılardır?",
  "Sayla isim arasında işlənən sözlərdir: nəfər, ədəd, baş.",
  ["Sayla isim arasında işlənən sözlər", "Yalnız sıra sayları",
   "Rəng bildirən sözlər", "Bağlayıcılar"], 1, None, 3),
 ("«Üç nəfər tələbə» ifadəsində numerativ söz hansıdır?",
  "İnsanlar üçün «nəfər» numerativi işlənir.",
  ["nəfər", "üç", "tələbə", "ifadədə yoxdur"], 1, None, 2),
 ("Heyvanların sayını bildirmək üçün hansı numerativ söz işlənir?",
  "Heyvanlar üçün «baş» işlənir: on baş qoyun.",
  ["baş", "nəfər", "cild", "top"], 1, None, 3),
 ("«Dənə» numerativ sözü nə üçün işlənir?",
  "Ayrı-ayrı əşyaların sayı üçün: beş dənə alma.",
  ["Əşyaların sayı üçün", "İnsanların sayı üçün",
   "Kitabların cildi üçün", "Vaxt üçün"], 1, None, 2),
 ("Hansı ifadə düzgündür?",
  "Ayaqqabı cütlə sayılır: iki cüt ayaqqabı.",
  ["iki cüt ayaqqabı", "iki nəfər ayaqqabı",
   "iki baş ayaqqabı", "iki cild ayaqqabı"], 1, None, 2),
 ("Sıra sayları rəqəmlə necə yazılır?",
  "Şəkilçi defislə yazılır: 5-ci.",
  ["5-ci", "5ci", "5 ci", "5.ci"], 1, None, 2),
 ("«Yüzlərlə insan» ifadəsində say nəyi bildirir?",
  "Dəqiq olmayan çoxluğu bildirir.",
  ["Qeyri-müəyyən çoxluğu", "Dəqiq sayı", "Sıranı",
   "Kəsri"], 1, None, 3),
 ("«Xeyli» sözü hansı miqdarı bildirir?",
  "Xeyli — qeyri-müəyyən miqdar bildirir.",
  ["Qeyri-müəyyən miqdarı", "Dəqiq miqdarı", "Sıra sayını",
   "Kəsr sayını"], 1, None, 2),
],
"az-6-cumle-uzvleri": [
 ("Tamamlıq hansı suallara cavab verir?",
  "Tamamlıq hallara uyğun «kimi? nəyi? kimə? nəyə?» və s. "
  "suallarına cavab verir.",
  ["Kimi? Nəyi? Kimə? Nəyə?", "Necə? Nə cür?",
   "Nə vaxt? Harada?", "Neçə? Neçənci?"], 1, None, 2),
 ("«Şagird kitabı oxudu» cümləsində tamamlıq hansıdır?",
  "Nəyi oxudu? — kitabı.",
  ["kitabı", "şagird", "oxudu", "cümlədə yoxdur"], 1, None, 2),
 ("Təyin cümlədə nəyi bildirir?",
  "Təyin əşyanın əlamətini bildirir.",
  ["Əşyanın əlamətini", "Hərəkətin vaxtını",
   "Hərəkətin yerini", "Hökmü"], 1, None, 2),
 ("«Maraqlı film izlədik» cümləsində təyin hansıdır?",
  "Hansı film? — maraqlı.",
  ["maraqlı", "film", "izlədik", "cümlədə yoxdur"], 1, None, 2),
 ("Zərflik cümlədə hansı suallara cavab verir?",
  "Zərflik «necə? harada? nə vaxt?» suallarına cavab verir.",
  ["Necə? Harada? Nə vaxt?", "Kim? Nə?",
   "Kimin? Nəyin?", "Neçənci?"], 1, None, 2),
 ("«Uşaqlar həyətdə oynayır» cümləsində zərflik hansıdır?",
  "Harada oynayır? — həyətdə.",
  ["həyətdə", "uşaqlar", "oynayır", "cümlədə yoxdur"],
  1, None, 2),
 ("«Dünən qonaq gəldi» cümləsində «dünən» hansı üzvdür?",
  "Nə vaxt? — zaman zərfliyidir.",
  ["Zaman zərfliyi", "Tamamlıq", "Təyin", "Mübtəda"],
  1, None, 3),
 ("«Hansı?» sualına cavab verən cümlə üzvü hansıdır?",
  "Əlamət bildirən üzv təyindir.",
  ["Təyin", "Tamamlıq", "Zərflik", "Xəbər"], 1, None, 2),
 ("«Kitabı dostuma verdim» cümləsində «dostuma» hansı üzvdür?",
  "Kimə verdim? — tamamlıqdır.",
  ["Tamamlıq", "Təyin", "Zərflik", "Mübtəda"], 1, None, 3),
 ("İkinci dərəcəli üzvlər cümlədə nə edir?",
  "Baş üzvlərin məzmununu genişləndirib dəqiqləşdirir.",
  ["Baş üzvləri izah edib genişləndirir", "Cümləni qısaldır",
   "Yalnız bəzək üçündür", "Fikri dəyişdirir"], 1, None, 3),
],
"az-6-soz-sirasi": [
 ("Azərbaycan dilində mübtəda adətən cümlənin harasında durur?",
  "Mübtəda adətən cümlənin əvvəlində gəlir.",
  ["Əvvəlində", "Sonunda", "Yalnız ortasında",
   "Qaydası yoxdur"], 1, None, 2),
 ("«Kitabı Aysu oxudu» cümləsində söz sırası nəyi qüvvətləndirir?",
  "Önə çəkilən «kitabı» sözü məntiqi vurğu alır.",
  ["«Kitabı» sözünü", "«Oxudu» sözünü", "Heç nəyi",
   "Cümlənin sonunu"], 1, None, 3),
 ("Söz birləşməsində asılı tərəf adətən harada durur?",
  "Asılı tərəf əsas tərəfdən əvvəl gəlir: dəniz sahili.",
  ["Əsas tərəfdən əvvəl", "Əsas tərəfdən sonra",
   "Cümlənin sonunda", "İstənilən yerdə"], 1, None, 3),
 ("«Dağların zirvəsi» birləşməsində tərəflər nə ilə bağlanıb?",
  "Yiyəlik hal (-ların) və mənsubiyyət (-i) şəkilçiləri ilə.",
  ["Yiyəlik hal və mənsubiyyət şəkilçiləri ilə",
   "Yalnız vurğu ilə", "Bağlayıcı ilə", "Qoşma ilə"],
  1, None, 3),
 ("Söz sırası dəyişəndə cümlədə nə dəyişə bilər?",
  "Məna çaları və məntiqi vurğu dəyişir.",
  ["Məna çaları və vurğu", "Hərflərin sayı",
   "Sözlərin kökü", "Heç nə"], 1, None, 2),
 ("Söz birləşməsi cümlədən nə ilə fərqlənir?",
  "Birləşmə bitmiş fikir bildirmir.",
  ["Bitmiş fikir bildirməməsi ilə", "Sözlərin çoxluğu ilə",
   "Böyük hərflə", "Nöqtə ilə"], 1, None, 2),
 ("İsmi birləşmənin əsas tərəfi adətən hansı nitq hissəsi olur?",
  "Əsas tərəf isim olur: gözəl mənzərə.",
  ["İsim", "Feil", "Bağlayıcı", "Nida"], 1, None, 2),
 ("«Oxumaq arzusu» birləşməsində birinci tərəf hansı formadadır?",
  "Oxumaq — məsdərdir.",
  ["Məsdər", "Feili sifət", "Sifət", "Say"], 1, None, 3),
 ("Cümlədə sözlər arasında əlaqəni nə yaradır?",
  "Şəkilçilər və söz sırası əlaqə yaradır.",
  ["Şəkilçilər və söz sırası", "Yalnız nöqtələr",
   "Hərflərin rəngi", "Sətirlər"], 1, None, 2),
 ("«Mən məktəbə gedirəm» cümləsi hansı sıra qaydasına uyğundur?",
  "Mübtəda + tamamlıq/zərflik + xəbər sırası ilə qurulub.",
  ["Mübtəda + zərflik + xəbər", "Xəbər + mübtəda",
   "Təyin + təyin + təyin", "Sıra pozulub"], 1, None, 3),
],
# ====================== INGILIS DILI 6 ================================
"ing-6-town": [
 ("Which place sells bread and cakes?",
  "Çörək və tort çörəkxanada (bakery) satılır.",
  ["bakery", "library", "bank", "stadium"], 1, None, 2),
 ("A library is a place where we can ___.",
  "Kitabxanada kitab oxuyuruq.",
  ["read books", "swim", "buy shoes", "play football"],
  1, None, 1),
 ("There ___ a big park in our town.",
  "Təkdə: there is.",
  ["is", "are", "am", "be"], 1, None, 1),
 ("Where can we buy medicine?",
  "Dərman aptekdə satılır: at the chemist.",
  ["at the chemist", "at the bakery", "at the stadium",
   "at the cinema"], 1, None, 2),
 ("«Museum» nə üçündür?",
  "Muzeydə tarixi əşyalara baxırıq.",
  ["Tarixi əşyalara baxmaq üçün", "Yemək almaq üçün",
   "Üzmək üçün", "Avtobus gözləmək üçün"], 1, None, 1),
 ("«I ___ go to the cinema on Sundays.» (həmişə)",
  "Həmişə — always.",
  ["always", "never", "town", "where"], 1, None, 2),
 ("«Never» nə deməkdir?",
  "Never — heç vaxt.",
  ["Heç vaxt", "Həmişə", "Bəzən", "Tez-tez"], 1, None, 1),
 ("«The bank is ___ the post office and the cafe.»",
  "İkisinin arasında: between.",
  ["between", "under", "on", "up"], 1, None, 2),
 ("«Are there any shops near here?» sualına qısa cavab hansıdır?",
  "Cəmdə qısa cavab: Yes, there are.",
  ["Yes, there are.", "Yes, there is.", "Yes, it does.",
   "No, they can."], 1, None, 2),
 ("«Town» və «city» sözlərinin fərqi nədir?",
  "City böyük şəhərdir, town kiçik şəhərdir.",
  ["City daha böyükdür", "Town daha böyükdür",
   "Eyni sözlərdir", "İkisi də kənddir"], 1, None, 2),
],
"ing-6-food": [
 ("«Can I have some water, please?» cümləsi nəyi bildirir?",
  "Can burada icazə və xahiş bildirir.",
  ["Nəzakətli xahişi", "Əmri", "Qadağanı", "Təəccübü"],
  1, None, 2),
 ("Which word is a vegetable?",
  "Carrot (kök) tərəvəzdir; qalanları meyvədir.",
  ["carrot", "apple", "cherry", "peach"], 1, None, 2),
 ("«Delicious» nə deməkdir?",
  "Delicious — çox dadlı.",
  ["Çox dadlı", "Acı", "Soyuq", "Boş"], 1, None, 1),
 ("«___ likes pizza.» (o — qız)",
  "Qız üçün mübtəda əvəzliyi: She.",
  ["She", "Her", "Him", "Us"], 1, None, 2),
 ("«I see ___ every day.» (onu — oğlanı)",
  "Tamamlıq əvəzliyi: him.",
  ["him", "he", "his", "she"], 1, None, 2),
 ("«Let us make a salad» cümləsi nədir?",
  "Bu, təklifdir (gəlin salat hazırlayaq).",
  ["Təklif", "Sual", "Qadağa", "Təəssüf"], 1, None, 2),
 ("«Fry» feili nə deməkdir?",
  "Fry — qızartmaq.",
  ["Qızartmaq", "Qaynatmaq", "Doğramaq", "Soyutmaq"],
  1, None, 2),
 ("«Boil» feili hansı hərəkəti bildirir?",
  "Boil — qaynatmaq.",
  ["Qaynatmaq", "Qızartmaq", "Kəsmək", "Yumaq"], 1, None, 2),
 ("Which meal is in the middle of the day?",
  "Günorta yeməyi — lunch.",
  ["lunch", "breakfast", "dinner", "supper"], 1, None, 2),
 ("«Would you like some tea?» sualına nəzakətli cavab hansıdır?",
  "Nəzakətli qəbul: Yes, please.",
  ["Yes, please.", "Give me!", "No!", "Go away."], 1, None, 2),
],
"ing-6-holiday": [
 ("«I was in Paris last summer» cümləsi hansı zamandadır?",
  "Was — be feilinin keçmiş formasıdır: Past Simple.",
  ["Past Simple", "Present Simple", "Gələcək zaman",
   "Past Continuous"], 1, None, 2),
 ("«There ___ many tourists on the beach yesterday.»",
  "Cəmdə keçmiş: there were.",
  ["were", "was", "is", "am"], 1, None, 2),
 ("«She ___ very happy on holiday.» (keçmiş)",
  "She ilə: was.",
  ["was", "were", "are", "be"], 1, None, 2),
 ("«Beach» nə deməkdir?",
  "Beach — çimərlik.",
  ["Çimərlik", "Dağ", "Meşə", "Muzey"], 1, None, 1),
 ("«Hotel» sözünün mənası nədir?",
  "Hotel — mehmanxana.",
  ["Mehmanxana", "Xəstəxana", "Məktəb", "Mağaza"], 1, None, 1),
 ("«Sightseeing» nə deməkdir?",
  "Sightseeing — görməli yerləri gəzmək.",
  ["Görməli yerləri gəzmək", "Yemək bişirmək",
   "Ev tapşırığı etmək", "Yatmaq"], 1, None, 2),
 ("Which one do you need to travel to another country?",
  "Başqa ölkəyə pasportla gedirik.",
  ["passport", "sofa", "fridge", "pillow"], 1, None, 2),
 ("«There was a swimming pool at the hotel.» — Oteldə nə var idi?",
  "Swimming pool — üzgüçülük hovuzu.",
  ["Üzgüçülük hovuzu", "Kitabxana", "Stadion", "Meşə"],
  1, None, 2),
 ("«Suitcase» nədir?",
  "Suitcase — çamadan.",
  ["Çamadan", "Papaq", "Xəritə", "Bilet"], 1, None, 2),
 ("«What a holiday!» nidası nəyi ifadə edir?",
  "Heyranlığı bildirir: necə də gözəl tətil!",
  ["Heyranlığı", "Qəzəbi", "Yorğunluğu", "Sualı"], 1, None, 2),
],
"ing-6-stories": [
 ("«Walk» feilinin Past Simple forması hansıdır?",
  "Qaydalı feil: walked.",
  ["walked", "walking", "walks", "wolk"], 1, None, 2),
 ("«Write» feilinin keçmiş forması hansıdır?",
  "Qaydasız feil: wrote.",
  ["wrote", "writed", "written by", "writes"], 1, None, 2),
 ("«Once upon a time» ifadəsi nə deməkdir?",
  "Nağıl başlanğıcı: biri var idi, biri yox idi.",
  ["Biri var idi, biri yox idi", "Sonra görüşərik",
   "Sabahın xeyir", "Nə baş verdi"], 1, None, 2),
 ("«Tell» feilinin keçmişi hansıdır?",
  "Qaydasız feil: told.",
  ["told", "telled", "tells", "telling"], 1, None, 2),
 ("«They did not ___ the film.» boşluğu doldurun.",
  "Did not-dan sonra əsas forma: like.",
  ["like", "liked", "likes", "liking"], 1, None, 3),
 ("«___ week» (keçən həftə) — boşluğu doldurun.",
  "Keçən — last: last week.",
  ["last", "next", "this", "every"], 1, None, 2),
 ("Nağılda əsas obraz necə adlanır? (ingiliscə)",
  "Əsas qəhrəman — hero.",
  ["hero", "table", "window", "lesson"], 1, None, 1),
 ("«Begin» feilinin Past Simple forması hansıdır?",
  "Qaydasız feil: began.",
  ["began", "beginned", "begins", "begun to"], 1, None, 3),
 ("«The story ended happily.» — Hekayə necə bitdi?",
  "Happily — xoşbəxt sonluqla.",
  ["Xoşbəxt sonluqla", "Kədərlə", "Sualla", "Bitmədi"],
  1, None, 2),
 ("«First, then, finally» sözləri mətndə nə üçün işlənir?",
  "Hadisələrin ardıcıllığını göstərmək üçün.",
  ["Hadisələrin ardıcıllığı üçün", "Rəngləri saymaq üçün",
   "Sual vermək üçün", "Salamlaşmaq üçün"], 1, None, 2),
],
"ing-6-journeys": [
 ("Which is water transport?",
  "Gəmi su nəqliyyatıdır: ship.",
  ["ship", "bus", "train", "bike"], 1, None, 1),
 ("«Train» nə deməkdir?",
  "Train — qatar.",
  ["Qatar", "Təyyarə", "Gəmi", "Tramvay"], 1, None, 1),
 ("«Did they arrive on time?» sualına qısa cavab hansıdır?",
  "Past Simple sualına: Yes, they did.",
  ["Yes, they did.", "Yes, they do.", "Yes, they are.",
   "Yes, they can."], 1, None, 2),
 ("«Could» feili nəyi bildirir?",
  "Could — keçmişdə bacarığı bildirir.",
  ["Keçmişdə bacarığı", "Gələcək planı", "İndiki hərəkəti",
   "Sahibliyi"], 1, None, 3),
 ("«When I was five, I ___ already swim.» (bacarırdım)",
  "Keçmiş bacarıq: could.",
  ["could", "can", "will", "am"], 1, None, 2),
 ("«Drive» feili hansı nəqliyyat vasitəsinə aiddir?",
  "Maşını sürürük: drive a car.",
  ["Maşına", "Ata", "Velosipedə", "Qayığa"], 1, None, 2),
 ("«Ride a horse» nə deməkdir?",
  "Ata minmək.",
  ["Ata minmək", "Maşın sürmək", "Qaçmaq", "Uçmaq"],
  1, None, 2),
 ("«Where did you go last year?» sualı nə haqqındadır?",
  "Keçən ilki səyahət haqqındadır.",
  ["Keçmiş səyahət haqqında", "Gələcək plan haqqında",
   "Bu günkü dərs haqqında", "Yemək haqqında"], 1, None, 2),
 ("«By bus» ifadəsi nəyi bildirir?",
  "Avtobusla getməyi bildirir.",
  ["Avtobusla getməyi", "Avtobusu almağı",
   "Avtobusda yaşamağı", "Avtobusu yumağı"], 1, None, 2),
 ("«Journey» sözünün mənası nədir?",
  "Journey — səyahət, yol.",
  ["Səyahət", "Jurnal", "Gündəlik", "Hakim"], 1, None, 2),
],
"ing-6-heroes": [
 ("«Brave» sifəti nə deməkdir?",
  "Brave — cəsur.",
  ["Cəsur", "Qorxaq", "Tənbəl", "Yorğun"], 1, None, 1),
 ("«Kind» sözünün mənası nədir?",
  "Kind — mehriban, xeyirxah.",
  ["Mehriban", "Qəzəbli", "Paxıl", "Kobud"], 1, None, 1),
 ("Past Continuous necə düzəlir?",
  "was/were + feilin -ing forması.",
  ["was/were + feil-ing", "do + feil", "will + feil",
   "have + feil-ed"], 1, None, 3),
 ("«She ___ reading a book at 5 oclock yesterday.»",
  "She ilə Past Continuous: was reading.",
  ["was", "were", "is", "do"], 1, None, 2),
 ("«They were ___ football when it started to rain.»",
  "Past Continuous: were playing.",
  ["playing", "play", "played", "plays"], 1, None, 2),
 ("«Scared» hansı hissi bildirir?",
  "Scared — qorxmuş.",
  ["Qorxunu", "Sevinci", "Yorğunluğu", "Aclığı"], 1, None, 2),
 ("«What were you doing at 7?» sualı hansı zamandadır?",
  "Were + doing — Past Continuous.",
  ["Past Continuous", "Present Simple", "Past Simple",
   "Gələcək zaman"], 1, None, 3),
 ("«Honest» sifəti necə insanı təsvir edir?",
  "Honest — dürüst, düz danışan.",
  ["Dürüst insanı", "Yalançı insanı", "Tənbəl insanı",
   "Qəzəbli insanı"], 1, None, 2),
 ("«Was he sleeping? — No, he ___.»",
  "İnkar qısa cavab: was not.",
  ["was not", "were not", "did not", "is not"], 1, None, 2),
 ("Qəhrəman (hero) adlandırdığımız insan nə edir?",
  "Başqalarına kömək edir, cəsarət göstərir.",
  ["Başqalarına kömək edir", "Yalnız yatır",
   "Heç nə etmir", "Qaçıb gizlənir"], 1, None, 1),
],
"ing-6-ideas": [
 ("«Invent» feili nə deməkdir?",
  "Invent — ixtira etmək.",
  ["İxtira etmək", "İtirmək", "Silmək", "Yemək"], 1, None, 2),
 ("«Discover» nə deməkdir?",
  "Discover — kəşf etmək.",
  ["Kəşf etmək", "Gizlətmək", "Unutmaq", "Satmaq"], 1, None, 2),
 ("«This book is ___.» (mənimki)",
  "Yiyəlik əvəzliyi: mine.",
  ["mine", "my", "me", "I"], 1, None, 2),
 ("«Yours» nə deməkdir?",
  "Yours — səninki.",
  ["Səninki", "Mənimki", "Onunku", "Bizimki"], 1, None, 2),
 ("«While I was cooking, the phone ___.» (Past Simple)",
  "Qısa hadisə Past Simple ilə: rang.",
  ["rang", "ring", "ringing", "rings"], 1, None, 3),
 ("«Technology» sözü nəyi əhatə edir?",
  "Texniki vasitələri və ixtiraları.",
  ["Texniki vasitələri", "Yalnız kitabları",
   "Yalnız yeməkləri", "Heyvanları"], 1, None, 2),
 ("«Design» feilinin mənası nədir?",
  "Design — layihələndirmək, dizayn etmək.",
  ["Layihələndirmək", "Dağıtmaq", "Gözləmək", "Oxumaq"],
  1, None, 2),
 ("Uzun davam edən keçmiş hərəkəti hansı zaman bildirir?",
  "Davamlı hərəkət — Past Continuous.",
  ["Past Continuous", "Past Simple", "Present Simple",
   "Əmr forması"], 1, None, 3),
 ("«Screen» nə deməkdir?",
  "Screen — ekran.",
  ["Ekran", "Klaviatura", "Printer", "Naqil"], 1, None, 1),
 ("«Great idea!» ifadəsi nəyi bildirir?",
  "Fikri bəyənməni bildirir: əla fikirdir!",
  ["Bəyənməni", "Etirazı", "Qorxunu", "Yuxusuzluğu"],
  1, None, 1),
],
"ing-6-nature": [
 ("«Forest» nə deməkdir?",
  "Forest — meşə.",
  ["Meşə", "Dəniz", "Səhra", "Şəhər"], 1, None, 1),
 ("«River» sözünün mənası nədir?",
  "River — çay.",
  ["Çay", "Göl", "Dağ", "Ada"], 1, None, 1),
 ("«I want to protect nature.» — Danışan nə istəyir?",
  "Protect — qorumaq: təbiəti qorumaq istəyir.",
  ["Təbiəti qorumaq", "Təbiəti çirkləndirmək",
   "Evdə qalmaq", "Ağac kəsmək"], 1, None, 2),
 ("«Mountain» nə deməkdir?",
  "Mountain — dağ.",
  ["Dağ", "Düzənlik", "Vadi", "Sahil"], 1, None, 1),
 ("«Like, want, need» feilləri nəyi ifadə edir?",
  "Bəyənməni, istəyi və ehtiyacı bildirir.",
  ["Bəyənmə, istək və ehtiyacı", "Yalnız hərəkəti",
   "Yalnız rəngi", "Zamanı"], 1, None, 3),
 ("«We need clean air.» cümləsi nəyi bildirir?",
  "Təmiz havaya ehtiyacımızı bildirir.",
  ["Təmiz havaya ehtiyacı", "Yeməyə istəyi",
   "Oyuna dəvəti", "Yuxu vaxtını"], 1, None, 2),
 ("«Waterfall» nədir?",
  "Waterfall — şəlalə.",
  ["Şəlalə", "Quyu", "Bulaq", "Buzlaq"],
  1, None, 2),
 ("«Wild animals» ifadəsi hansı heyvanları bildirir?",
  "Wild — vəhşi (təbiətdə yaşayan) heyvanlar.",
  ["Vəhşi heyvanları", "Ev heyvanlarını", "Oyuncaqları",
   "Balıqları"], 1, None, 2),
 ("«Desert» nə deməkdir?",
  "Desert — səhra.",
  ["Səhra", "Meşə", "Bataqlıq", "Çəmənlik"], 1, None, 2),
 ("«Do not drop litter!» xəbərdarlığı nə tələb edir?",
  "Litter — zibil: zibil atmamağı tələb edir.",
  ["Zibil atmamağı", "Sürətli qaçmağı", "Səs salmamağı",
   "Su içməməyi"], 1, None, 2),
],
# ======================= INFORMATIKA 6 ================================
"inf-6-kompyuter": [
 ("İkilik say sistemində hansı rəqəmlərdən istifadə olunur?",
  "İkilik sistemdə yalnız 0 və 1 rəqəmləri var.",
  ["0 və 1", "0-dan 9-a qədər", "1 və 2", "Yalnız 1"],
  1, None, 2),
 ("1 meqabayt neçə kilobaytdır?",
  "1 MB = 1024 KB.",
  ["1024", "100", "10", "8"], 1, str(2 ** 10), 3),
 ("«101» ikilik ədədi onluq say sistemində neçədir?",
  "1·4 + 0·2 + 1·1 = 5.",
  ["5", "101", "3", "6"], 1, str(int("101", 2)), 3),
 ("Hansı vahid daha böyükdür: meqabayt, yoxsa kilobayt?",
  "1 MB = 1024 KB — meqabayt böyükdür.",
  ["Meqabayt", "Kilobayt", "Bərabərdirlər", "Müqayisə olunmur"],
  1, None, 2),
 ("Kompüterin daimi və müvəqqəti yaddaşları hansılardır?",
  "Daimi — sərt disk, müvəqqəti — əməli yaddaş.",
  ["Sərt disk və əməli yaddaş", "Monitor və maus",
   "Printer və skaner", "Dinamik və mikrofon"], 1, None, 3),
 ("Mətndəki hər simvol yaddaşda təxminən nə qədər yer tutur?",
  "Bir simvol təxminən 1 bayt yer tutur.",
  ["1 bayt", "1 kilobayt", "1 meqabayt", "100 bayt"],
  1, None, 3),
 ("İkilik «1010» yazılışının onluq qarşılığını tapın.",
  "1·8 + 0·4 + 1·2 + 0·1 = 10.",
  ["10", "1010", "4", "20"], 1, str(int("1010", 2)), 3),
 ("Verilənlərin ölçü vahidlərini kiçikdən böyüyə düzün.",
  "bit < bayt < kilobayt < meqabayt.",
  ["bit, bayt, KB, MB", "MB, KB, bayt, bit",
   "bayt, bit, MB, KB", "KB, MB, bit, bayt"], 1, None, 2),
 ("Monitordakı təsvir nələrdən yığılır?",
  "Təsvir xırda nöqtələrdən — piksellərdən ibarətdir.",
  ["Piksellərdən", "Hərflərdən", "Damcılardan", "Xətlərdən"],
  1, None, 2),
 ("Kompüter söndürüləndə hansı yaddaşın məzmunu silinir?",
  "Əməli (müvəqqəti) yaddaş təmizlənir.",
  ["Əməli yaddaşın", "Sərt diskin", "Fləş kartın",
   "Heç birinin"], 1, None, 3),
],
"inf-6-proqram-teminati": [
 ("Proqram təminatı nədir?",
  "Kompüterdə işləyən bütün proqramların məcmusudur.",
  ["Kompüter proqramlarının məcmusu", "Kompüterin qurğuları",
   "Elektrik naqilləri", "Kağız sənədlər"], 1, None, 2),
 ("Proqramı başlatmağın üsullarından biri hansıdır?",
  "Nişanı üzərində ikiqat klik etmək.",
  ["Nişan üzərində ikiqat klik", "Monitoru silkələmək",
   "Naqili çıxarmaq", "Ekranı söndürmək"], 1, None, 1),
 ("Abzasın formatlanmasına nə daxildir?",
  "Sətirlərin düzləndirilməsi və abzas boşluğu.",
  ["Düzləndirmə və abzas boşluğu", "Faylın silinməsi",
   "Kompüterin təmiri", "Şəklin çəkilməsi"], 1, None, 3),
 ("Elektron təqdimatın əsas elementi nədir?",
  "Təqdimat slaydlardan ibarətdir.",
  ["Slayd", "Cədvəl", "Qovluq", "Parol"], 1, None, 2),
 ("Slayda nələri əlavə etmək olar?",
  "Mətn, şəkil, cədvəl və digər obyektləri.",
  ["Mətn, şəkil, cədvəl", "Yalnız mətn",
   "Yalnız rəqəmlər", "Heç nə"], 1, None, 2),
 ("Təqdimat zamanı slaydlar necə göstərilir?",
  "Müəyyən olunmuş ardıcıllıqla bir-birini əvəz edir.",
  ["Müəyyən ardıcıllıqla", "Təsadüfi", "Hamısı bir yerdə",
   "Göstərilmir"], 1, None, 2),
 ("Mətnin görünüşünü yaxşılaşdırmaq üçün nəyi dəyişmək olar?",
  "Şrifti, ölçünü və rəngi dəyişmək olar.",
  ["Şrifti və ölçünü", "Kompüterin markasını",
   "Otağın rəngini", "Heç nəyi"], 1, None, 2),
 ("Cədvəl şəklində informasiya modelinə misal hansıdır?",
  "Dərs cədvəli informasiya modelidir.",
  ["Dərs cədvəli", "Futbol topu", "Qələm", "Çanta"],
  1, None, 3),
 ("Hansı proqram elektron təqdimat hazırlamaq üçündür?",
  "PowerPoint təqdimat proqramıdır.",
  ["PowerPoint", "Kalkulyator", "Saat", "Paint"], 1, None, 2),
 ("Əməliyyat sistemi ilə tətbiqi proqramın fərqi nədir?",
  "ƏS kompüteri idarə edir, tətbiqi proqram konkret iş görür.",
  ["ƏS idarə edir, tətbiqi proqram konkret iş görür",
   "Fərq yoxdur", "Tətbiqi proqram kompüteri yandırır",
   "ƏS yalnız oyundur"], 1, None, 3),
],
"inf-6-alqoritm": [
 ("Alqoritmin xassələrindən biri hansıdır?",
  "Hər addım dəqiq və birmənalı olmalıdır — müəyyənlik.",
  ["Müəyyənlik (dəqiqlik)", "Rənglilik", "Uzunluq",
   "Gizlilik"], 1, None, 2),
 ("Xətti alqoritm necə icra olunur?",
  "Addımlar ardıcıl, hər biri bir dəfə icra olunur.",
  ["Addımlar ardıcıl, bir dəfə", "Yalnız şərtlə",
   "Sonsuz təkrarla", "Sondan əvvələ"], 1, None, 2),
 ("Budaqlanan alqoritmdə nə baş verir?",
  "Şərtdən asılı olaraq yol seçilir.",
  ["Şərtə görə yol seçilir", "Addımlar silinir",
   "Alqoritm dayanmır", "Yalnız təkrar olur"], 1, None, 2),
 ("Dövri alqoritm nədir?",
  "Addımların müəyyən sayda təkrarlandığı alqoritmdir.",
  ["Addımları təkrarlanan alqoritm", "Tək addımlı alqoritm",
   "Səhv alqoritm", "Yazısız alqoritm"], 1, None, 2),
 ("«Əgər yağış yağırsa, çətir götür» — bu hansı alqoritm "
  "növüdür?",
  "Şərt var — budaqlanan alqoritmdir.",
  ["Budaqlanan", "Xətti", "Dövri", "Alqoritm deyil"],
  1, None, 2),
 ("«Hasarın 20 taxtasını rənglə» məsələsi hansı alqoritmlə "
  "həll olunur?",
  "Eyni iş 20 dəfə təkrarlanır — dövri alqoritm.",
  ["Dövri", "Xətti", "Budaqlanan", "Heç biri"], 1, None, 2),
 ("Alqoritmin sonluluq xassəsi nə deməkdir?",
  "Alqoritm sonlu sayda addımdan sonra bitməlidir.",
  ["Sonlu addımdan sonra bitməlidir", "Heç vaxt bitməməlidir",
   "Bir addımdan ibarət olmalıdır", "Yazılmamalıdır"],
  1, None, 3),
 ("Blok-sxemdə şərt (seçim) hansı fiqurla göstərilir?",
  "Şərt romb fiqurunda yazılır.",
  ["Romb", "Oval", "Düzbucaqlı", "Dairə"], 1, None, 3),
 ("Alqoritmin anlaşıqlılıq xassəsi nəyi tələb edir?",
  "İcraçı hər əmri başa düşməlidir.",
  ["İcraçının əmrləri başa düşməsini", "Rəngli yazılmasını",
   "Uzun olmasını", "Gizli qalmasını"], 1, None, 3),
 ("Alqoritmin icrasını kim və ya nə dayandıra bilər?",
  "Son addım yerinə yetiriləndə alqoritm bitir.",
  ["Son addımın icrası", "Küləyin əsməsi",
   "Kağızın rəngi", "Heç nə"], 1, None, 2),
],
"inf-6-proqramlasdirma": [
 ("Proqramda dəyişən nədir?",
  "Qiyməti dəyişə bilən adlandırılmış yaddaş sahəsidir.",
  ["Qiyməti dəyişən adlandırılmış sahə", "Sabit ədəd",
   "Kompüterin hissəsi", "Şəkil faylı"], 1, None, 3),
 ("Scratch tipli mühitlərdə proqram nədən yığılır?",
  "Hazır komanda bloklarından yığılır.",
  ["Bloklardan", "Kağızdan", "Naqillərdən", "Şəkillərdən"],
  1, None, 2),
 ("Proqramda «əgər … onda …» konstruksiyası nəyi həyata keçirir?",
  "Şərtə görə seçimi (budaqlanmanı).",
  ["Seçimi (budaqlanmanı)", "Təkrarı", "Səs yazısını",
   "Çapı"], 1, None, 2),
 ("Dövr (təkrarlama) əmri nə üçün istifadə olunur?",
  "Eyni əmrləri dəfələrlə icra etmək üçün.",
  ["Əmrləri təkrarlamaq üçün", "Proqramı silmək üçün",
   "Ekranı söndürmək üçün", "Fayl axtarmaq üçün"], 1, None, 2),
 ("Kvadrat çəkmək üçün «irəli get, sağa dön 90» əmrlərini neçə "
  "dəfə təkrarlamaq lazımdır?",
  "Kvadratın 4 tərəfi var: 4 dəfə.",
  ["4", "3", "6", "90"], 1, str(4), 2),
 ("ALPLogo-da «təkrar 6 [irəli 50 sağa 60]» proqramı hansı fiquru "
  "çəkər?",
  "360 : 60 = 6 dönüş — altıbucaqlı alınır.",
  ["Altıbucaqlı", "Kvadrat", "Üçbucaq", "Dairə"], 1, None, 3),
 ("Dəyişənə qiymət vermək əməliyyatı necə adlanır?",
  "Qiymət vermə mənimsətmə adlanır.",
  ["Mənimsətmə", "Silmə", "Çapetmə", "Axtarış"], 1, None, 3),
 ("Proqramlaşdırma mühitində musiqi necə səsləndirilir?",
  "Not və səs əmrlərinin ardıcıllığı ilə.",
  ["Not əmrlərinin ardıcıllığı ilə", "Mikrofonu sındırmaqla",
   "Ekranı boyamaqla", "Səsləndirmək olmur"], 1, None, 2),
 ("Proqramdakı səhv necə adlanır?",
  "Proqram səhvi xəta (baq) adlanır.",
  ["Xəta (baq)", "Blok", "Slayd", "Kursor"], 1, None, 2),
 ("Dövrün icrası nə vaxt dayanır?",
  "Verilmiş təkrar sayı bitəndə dayanır.",
  ["Təkrar sayı bitəndə", "Heç vaxt", "Kompüter istəyəndə",
   "Təsadüfi anda"], 1, None, 2),
],
"inf-6-internet": [
 ("İnternetdə axtarış üçün açar sözlər necə seçilməlidir?",
  "Qısa və dəqiq sözlər daha yaxşı nəticə verir.",
  ["Qısa və dəqiq", "Çox uzun cümlələr", "Təsadüfi hərflər",
   "Yalnız rəqəmlər"], 1, None, 2),
 ("Elektron poçt ünvanında hansı işarə mütləq olur?",
  "E-poçt ünvanında @ işarəsi olur.",
  ["@", "%", "&", "№"], 1, None, 1),
 ("E-məktuba fayl əlavə etmək necə adlanır?",
  "Əlavə olunan fayl qoşma (attachment) adlanır.",
  ["Qoşma (attachment)", "Slayd", "Blok", "Kursor"],
  1, None, 2),
 ("İnformasiya resursları ilə işin ilk mərhələsi nədir?",
  "Əvvəlcə axtarışın məqsədi müəyyən edilir.",
  ["Məqsədi müəyyən etmək", "Nəticəni çap etmək",
   "Kompüteri söndürmək", "Şəkil çəkmək"], 1, None, 3),
 ("Brauzerin ünvan sətrinə nə yazılır?",
  "Saytın ünvanı (URL) yazılır.",
  ["Saytın ünvanı", "Parol", "Ev ünvanı", "Telefon nömrəsi"],
  1, None, 2),
 ("Naməlum göndəricidən gələn e-məktubun qoşmasını açmaq olarmı?",
  "Olmaz — virus ola bilər.",
  ["Olmaz — virus ola bilər", "Olar, təhlükəsizdir",
   "Yalnız gecə olar", "Yalnız şəkildirsə olar"], 1, None, 2),
 ("«WWW» qısaltması nəyi bildirir?",
  "World Wide Web — Dünya hörümçək toru.",
  ["World Wide Web", "Windows Word Work",
   "Web Windows World", "Wide Word Web"], 1, None, 3),
 ("E-məktubda «Mövzu» (Subject) sətri nə üçündür?",
  "Məktubun nə haqqında olduğunu qısa bildirmək üçün.",
  ["Məktubun mövzusunu bildirmək üçün", "Parol yazmaq üçün",
   "Şəkil çəkmək üçün", "Heç nə üçün"], 1, None, 2),
 ("Axtarış nəticələrindən etibarlı olanı necə seçmək olar?",
  "Rəsmi və tanınmış mənbələrə üstünlük verilir.",
  ["Rəsmi mənbələrə üstünlük verməklə", "İlk çıxana inanmaqla",
   "Ən rəngli sayta girməklə", "Təsadüfi seçməklə"],
  1, None, 3),
 ("İnternet hesabının parolunu kimə demək olar?",
  "Parol yalnız valideynlə bölüşülə bilər, başqa heç kimə.",
  ["Yalnız valideynə", "Bütün dostlara", "İnternetdəki tanışlara",
   "Hamıya"], 1, None, 2),
],
# ==================== AZERBAYCAN TARIXI 6 =============================
"tarix-6-ibtidai": [
 ("«E.ə.» qısaltması nə deməkdir?",
  "Eramızdan əvvəl deməkdir.",
  ["Eramızdan əvvəl", "Ən əvvəl", "Erkən əsr", "Əsrdən əvvəl"],
  1, None, 1),
 ("100 il hansı zaman vahidini təşkil edir?",
  "100 il bir əsrdir (yüzillik).",
  ["Əsr", "Minillik", "Onillik", "Ay"], 1, None, 1),
 ("Azıx mağarasında tapılmış qədim insan necə adlandırılır?",
  "Azıx mağarasının qədim sakini azıxantrop adlanır.",
  ["Azıxantrop", "Neandertal", "Firon", "Sərkərdə"], 1, None, 2),
 ("İbtidai insanlar əvvəlcə harada yaşayırdılar?",
  "İlk insanlar mağaralarda məskunlaşırdılar.",
  ["Mağaralarda", "Çoxmərtəbəli binalarda", "Gəmilərdə",
   "Qalalarda"], 1, None, 1),
 ("Qobustan qayaüstü rəsmləri nəyi əks etdirir?",
  "Qədim insanların həyatını: ov, rəqs, qayıqlar.",
  ["Qədim insanların həyatını", "Müasir şəhərləri",
   "Kosmik gəmiləri", "Dəmir yollarını"], 1, None, 2),
 ("İbtidai insanlar niyə birlikdə (icma halında) yaşayırdılar?",
  "Tək yaşamaq təhlükəli idi — birgə ovlanıb qorunurdular.",
  ["Birgə ovlanmaq və qorunmaq üçün", "Şəhər salmaq üçün",
   "Ticarət üçün", "Yarış üçün"], 1, None, 2),
 ("Əkinçilik və maldarlıq yarananda insanların həyatında nə "
  "dəyişdi?",
  "İnsanlar oturaq həyata keçdilər.",
  ["Oturaq həyata keçdilər", "Mağaraya qayıtdılar",
   "Ovçuluğu tam atdılar və ac qaldılar", "Heç nə dəyişmədi"],
  1, None, 2),
 ("Tunc dövrü hansı dövrdən sonra başlayır?",
  "Əvvəl daş dövrü, sonra tunc dövrü gəlir.",
  ["Daş dövründən", "Dəmir dövründən", "Orta əsrlərdən",
   "Müasir dövrdən"], 1, None, 2),
 ("Tarixi hadisələrin zamanını öyrənən sahə necə adlanır?",
  "Zaman hesabını xronologiya öyrənir.",
  ["Xronologiya", "Biologiya", "Coğrafiya", "Astronomiya"],
  1, None, 3),
 ("Erkən dövlətlər hansı ehtiyacdan yaranırdı?",
  "İdarəetmə və müdafiə ehtiyacından.",
  ["İdarəetmə və müdafiə ehtiyacından", "Oyun üçün",
   "Bayram keçirmək üçün", "Təsadüfən"], 1, None, 2),
],
"tarix-6-qedim-dovletler": [
 ("Manna dövləti hansı ərazidə yaranmışdır?",
  "Manna Urmiya gölü ətrafında yaranmışdır.",
  ["Urmiya gölü ətrafında", "Xəzərin şimalında",
   "Qara dəniz sahilində", "Kür çayının mənbəyində"],
  1, None, 3),
 ("Manna dövləti təxminən nə vaxt yaranmışdır?",
  "Manna e.ə. IX əsrdə yaranmışdır.",
  ["E.ə. IX əsrdə", "Eramızın X əsrində", "1918-ci ildə",
   "E.ə. I əsrdə"], 1, None, 3),
 ("Atropatena dövlətinin banisi kimdir?",
  "Dövləti sərkərdə Atropat yaratmışdır.",
  ["Atropat", "İranzu", "Cavanşir", "Babək"], 1, None, 3),
 ("Albaniyada IV əsrdə hansı din dövlət dini elan olundu?",
  "Albaniyada xristianlıq qəbul edildi.",
  ["Xristianlıq", "Buddizm", "Şamanizm", "Heç bir din"],
  1, None, 3),
 ("Skiflər Azərbaycan ərazisində hansı qurumu yaratmışdılar?",
  "Skif (işğuz) padşahlığı yaranmışdı.",
  ["Skif padşahlığı", "Roma imperiyası", "Misir fironluğu",
   "Xanlıq"], 1, None, 3),
 ("Manna dövlətinin qüdrətli hökmdarı kim olmuşdur?",
  "İranzu Mannanın qüdrətli hökmdarı idi.",
  ["İranzu", "Atropat", "Tomris", "Nadir şah"], 1, None, 3),
 ("Qədim dövlətlərin əhalisi əsasən nə ilə məşğul olurdu?",
  "Əkinçilik və maldarlıq əsas təsərrüfat sahələri idi.",
  ["Əkinçilik və maldarlıqla", "Kosmik tədqiqatlarla",
   "Kino çəkilişi ilə", "Neft hasilatı ilə"], 1, None, 2),
 ("Atropatenanın paytaxtı hansı şəhər idi?",
  "Paytaxt Qazaka şəhəri idi.",
  ["Qazaka", "Bakı", "Gəncə", "Şamaxı"], 1, None, 3),
 ("Albaniya ərazisindən axan əsas çay hansı idi?",
  "Kür çayı Albaniyanın əsas çayı idi.",
  ["Kür", "Nil", "Dunay", "Volqa"], 1, None, 2),
 ("Azərbaycan e.ə. VI əsrdə hansı imperiyanın tərkibinə "
  "qatılmışdı?",
  "Əhəmənilər imperiyasının tərkibinə qatılmışdı.",
  ["Əhəmənilər", "Roma", "Osmanlı", "Monqol"], 1, None, 3),
],
"tarix-6-erken-orta": [
 ("III əsrdə Azərbaycan hansı imperiyanın hakimiyyəti altına "
  "düşdü?",
  "Azərbaycan Sasani imperiyasının tərkibinə qatıldı.",
  ["Sasanilər", "Roma", "Osmanlı", "Britaniya"], 1, None, 2),
 ("Feodal münasibətləri nəyə əsaslanırdı?",
  "İri torpaq sahibliyinə əsaslanırdı.",
  ["Torpaq sahibliyinə", "Zavod istehsalına",
   "İnternet ticarətinə", "Dəniz quldurluğuna"], 1, None, 3),
 ("Sasani imperiyası hansı ölkənin ərazisində yaranmışdı?",
  "Sasanilər dövləti İran ərazisində yaranmışdı.",
  ["İranda", "Misirdə", "Yunanıstanda", "Hindistanda"],
  1, None, 2),
 ("Feodalizmdə torpağın əsas sahibləri kimlər idi?",
  "Torpaqlar feodallara məxsus idi.",
  ["Feodallar", "Kəndlilər", "Uşaqlar", "Tacirlər"],
  1, None, 2),
 ("Asılı kəndlilər feodal üçün nə edirdilər?",
  "Torpağı becərir, vergi və mükəlləfiyyətlər ödəyirdilər.",
  ["Torpağı becərib vergi verirdilər", "Dövləti idarə edirdilər",
   "Orduya komandanlıq edirdilər", "Heç nə etmirdilər"],
  1, None, 2),
 ("Mehranilər sülaləsi harada hakimiyyətdə olmuşdur?",
  "Mehranilər Albaniyada hakimiyyətdə idilər.",
  ["Albaniyada", "Misirdə", "Romada", "Çində"], 1, None, 3),
 ("Cavanşir hansı dövlətin hökmdarı idi?",
  "Cavanşir Albaniya dövlətinin hökmdarı idi.",
  ["Albaniyanın", "Mannanın", "Səfəvilərin", "Osmanlının"],
  1, None, 3),
 ("Sasanilər dövründə Azərbaycanda hansı din geniş yayılmışdı?",
  "Zərdüştilik (atəşpərəstlik) yayılmışdı.",
  ["Zərdüştilik", "Buddizm", "Protestantlıq", "Şintoizm"],
  1, None, 3),
 ("Atəşgahlar nə idi?",
  "Od (atəş) məbədləri idi.",
  ["Od məbədləri", "Bazarlar", "Məktəblər", "Limanlar"],
  1, None, 2),
 ("Sasani hakimiyyətinə qarşı üsyanların əsas səbəbi nə idi?",
  "Ağır vergilər və zülm üsyanlara səbəb olurdu.",
  ["Ağır vergilər və zülm", "Bayramların çoxluğu",
   "Torpağın bolluğu", "Səbəb yox idi"], 1, None, 3),
],
}



#  Derinlesdirme: her movzuya 10 elave sual (#11-20).
ELAVE = {
"az-6-fonetika": [
 ("«Burun» sözü mənsubiyyətlə işlənəndə (burnum) hansı hadisə baş verir?",
  "Sait düşür — səsdüşümü hadisəsidir.",
  ["Səsdüşümü", "Səsartımı", "Vurğu dəyişməsi", "Heç nə"],
  1, None, 2),
 ("«Ailəyə» sözündə hansı bitişdirici samit işlənib?",
  "Sait qoşalaşmasın deyə y artırılır: ailə-y-ə.",
  ["y", "n", "s", "k"], 1, None, 2),
 ("Ahəng qanunu nəyə əsaslanır?",
  "Sözdə saitlərin qalın və ya incəliyə görə uyuşmasına.",
  ["Saitlərin uyuşmasına", "Samitlərin sayına",
   "Vurğunun yerinə", "Hecaların sayına"], 1, None, 2),
 ("«Səhər» sözündə vurğu hansı hecaya düşür?",
  "Vurğu son hecaya düşür: sə-hər.",
  ["İkinci (son) hecaya", "Birinci hecaya", "Hər ikisinə",
   "Heç birinə"], 1, None, 2),
 ("«Sinif» sözünə saitlə başlanan şəkilçi artıranda necə yazılır?",
  "İkinci sait düşür: sinfi.",
  ["sinfi", "sinifi", "siniffi", "sinifyi"], 1, None, 3),
 ("«Alın» sözü mənsubiyyət şəkilçisi ilə necə işlənir?",
  "Sait düşür: alnı.",
  ["alnı", "alını", "alının", "alnnı"], 1, None, 3),
 ("Sözlərin tələffüz qaydalarını hansı lüğət göstərir?",
  "Orfoepiya lüğəti tələffüzü göstərir.",
  ["Orfoepiya lüğəti", "Orfoqrafiya lüğəti", "İzahlı lüğət",
   "Tərcümə lüğəti"], 1, None, 2),
 ("Sözlərin düzgün yazılış qaydalarını hansı bölmə öyrənir?",
  "Orfoqrafiya yazı qaydalarını öyrənir.",
  ["Orfoqrafiya", "Orfoepiya", "Leksika", "Sintaksis"],
  1, None, 2),
 ("«Nəqliyyat» sözündə hansı qoşa samit var?",
  "Nəqliyyat sözündə yy qoşa yazılır.",
  ["yy", "qq", "ll", "tt"], 1, None, 3),
 ("«Metr» tipli sözlərin tələffüzündə sonda nə baş verir?",
  "Tələffüzdə sait artırılır: metir.",
  ["Səsartımı", "Səsdüşümü", "Vurğu itir", "Samit düşür"],
  1, None, 3),
],
"az-6-soz-luget": [
 ("«Daş» kökündən yaranan söz hansıdır?",
  "Daşlı — daş kökündən düzəlib.",
  ["daşlı", "dişli", "düşərgə", "dəstə"], 1, None, 2),
 ("«Yol, yolçu, yoldaş» sözlərinin ortaq cəhəti nədir?",
  "Hamısı yol kökündən yaranıb.",
  ["Eyni kökdən yaranmaları", "Eyni şəkilçiləri",
   "Cəm olmaları", "Alınma olmaları"], 1, None, 2),
 ("«Məktəblilərdən» sözünü başlanğıc formaya salın.",
  "Qrammatik şəkilçilər atılır: məktəbli.",
  ["məktəbli", "məktəb", "məktəblilər", "məktəbdən"],
  1, None, 3),
 ("«Sulu» sözündə hansı şəkilçi var?",
  "-lu leksik şəkilçisidir.",
  ["-lu (leksik)", "-su (kök)", "-ulu", "-l (qrammatik)"],
  1, None, 2),
 ("«Baş» sözü ilə «başlıq» sözünün əlaqəsi nədir?",
  "Başlıq baş kökündən düzəlib.",
  ["Kök və düzəltmə söz", "Sinonimlər", "Antonimlər",
   "Əlaqəsizdirlər"], 1, None, 2),
 ("Kök şəkilçisiz müstəqil işlənə bilərmi?",
  "Bəli — kök müstəqil sözdür.",
  ["Bəli, müstəqil işlənir", "Xeyr, heç vaxt",
   "Yalnız cəmdə", "Yalnız şeirdə"], 1, None, 2),
 ("«Dəmir — dəmirçi — dəmirçilik» cərgəsi necə yaranıb?",
  "Kökə ardıcıl leksik şəkilçilər artırılıb.",
  ["Ardıcıl şəkilçi artırmaqla", "Sözləri birləşdirməklə",
   "Təkrarla", "Alınma yolu ilə"], 1, None, 3),
 ("«Gül» sözünə hansı şəkilçi artırsaq peşə adı yaranar?",
  "Gülçü — gül becərən.",
  ["-çü", "-lük", "-süz", "-də"], 1, None, 2),
 ("Lüğəvi məna daşımayan hissə hansıdır?",
  "Şəkilçinin lüğəvi mənası yoxdur.",
  ["Şəkilçi", "Kök", "Söz", "Cümlə"], 1, None, 2),
 ("«Duz» kökünə «-suz» şəkilçisi artıranda hansı məna yaranır?",
  "Yoxluq mənası: duzsuz.",
  ["Yoxluq (duzsuz)", "Çoxluq", "Peşə", "Məkan"],
  1, None, 2),
],
"az-6-isim-hal": [
 ("Yiyəlik hal hansı suallara cavab verir?",
  "Kimin? nəyin? suallarına.",
  ["Kimin? Nəyin?", "Kimə? Nəyə?", "Kimdə? Nədə?",
   "Kimdən? Nədən?"], 1, None, 2),
 ("«Hara?» sualına ismin hansı halı cavab verir?",
  "Yönlük hal hara? sualına da cavab verir.",
  ["Yönlük", "Adlıq", "Yerlik", "Yiyəlik"], 1, None, 2),
 ("«Ağacda» sözü hansı haldadır?",
  "-da şəkilçisi yerlik halın göstəricisidir.",
  ["Yerlik", "Yönlük", "Çıxışlıq", "Təsirlik"],
  1, None, 2),
 ("Çıxışlıq hal hansı şəkilçilərlə düzəlir?",
  "-dan, -dən şəkilçiləri ilə.",
  ["-dan, -dən", "-da, -də", "-a, -ə", "-ı, -i"],
  1, None, 2),
 ("Yiyəlik halın şəkilçiləri hansılardır?",
  "-ın, -in, -un, -ün (samitdən sonra).",
  ["-ın, -in, -un, -ün", "-a, -ə", "-dan, -dən",
   "-lar, -lər"], 1, None, 2),
 ("Adlıq halda isim hansı formada olur?",
  "Hal şəkilçisi olmur — şəkilçisiz formadadır.",
  ["Şəkilçisiz", "-ı şəkilçili", "-da şəkilçili",
   "-dan şəkilçili"], 1, None, 2),
 ("«Qapını» sözü hansı haldadır?",
  "-nı şəkilçisi müəyyən təsirlik halı göstərir.",
  ["Təsirlik", "Yiyəlik", "Yerlik", "Adlıq"],
  1, None, 2),
 ("İsim nəyə görə hallanır?",
  "Cümlədəki vəzifəsinə (əlaqəsinə) görə.",
  ["Cümlədəki vəzifəsinə görə", "Hecaların sayına görə",
   "Rənginə görə", "Təsadüfən"], 1, None, 3),
 ("«Evdən məktəbə» ifadəsində hansı hallar işlənib?",
  "Evdən — çıxışlıq, məktəbə — yönlük.",
  ["Çıxışlıq və yönlük", "Adlıq və yiyəlik",
   "Yerlik və təsirlik", "Yalnız adlıq"], 1, None, 3),
 ("Hal şəkilçiləri hansı şəkilçilər qrupuna aiddir?",
  "Söz yaratmır — qrammatik şəkilçilərdir.",
  ["Qrammatik", "Leksik", "Sözdüzəldici", "Heç biri"],
  1, None, 2),
],
"az-6-say-numerativ": [
 ("«Nəfər» numerativ sözü kimlər üçün işlənir?",
  "İnsanların sayı üçün işlənir.",
  ["İnsanlar üçün", "Heyvanlar üçün", "Əşyalar üçün",
   "Bitkilər üçün"], 1, None, 2),
 ("Cansız əşyaların sayında «dənə» ilə yanaşı hansı numerativ işlənir?",
  "Ədəd sözü də işlənir: beş ədəd dəftər.",
  ["ədəd", "nəfər", "baş", "nüsxə yalnız"], 1, None, 2),
 ("Kəsr saylar nəyi bildirir?",
  "Tamın hissəsini bildirir.",
  ["Tamın hissəsini", "Sıranı", "Təxmini sayı",
   "Yalnız çoxluğu"], 1, None, 2),
 ("«Yarım» sözü hansı say növünə aiddir?",
  "Tamın yarısını bildirir — kəsr saydır.",
  ["Kəsr saya", "Sıra sayına", "Miqdar sayına yalnız",
   "Saya aid deyil"], 1, None, 3),
 ("«Onlarla ağac əkildi» cümləsində «onlarla» nəyi bildirir?",
  "Qeyri-müəyyən çoxluğu bildirir.",
  ["Qeyri-müəyyən çoxluğu", "Dəqiq sayı", "Sıranı",
   "Kəsri"], 1, None, 2),
 ("Miqdar sayları hansı suallara cavab verir?",
  "Neçə? nə qədər? suallarına.",
  ["Neçə? Nə qədər?", "Neçənci?", "Necə?", "Harada?"],
  1, None, 2),
 ("«2-ci» yazılışı düzgündürmü?",
  "Bəli, sıra sayı belə yazılır.",
  ["Bəli, düzgündür", "Xeyr, səhvdir", "Yalnız 2ci olar",
   "Yalnız «ikinci» yazılar"], 1, None, 2),
 ("«Beş-altı adam» ifadəsi hansı miqdarı bildirir?",
  "Təxmini miqdarı bildirir.",
  ["Təxmini miqdarı", "Dəqiq miqdarı", "Sıranı",
   "Kəsri"], 1, None, 2),
 ("Sıra sayları hansı şəkilçilərlə düzəlir?",
  "-ıncı, -inci, -uncu, -üncü.",
  ["-ıncı, -inci, -uncu, -üncü", "-lar, -lər",
   "-dan, -dən", "-çı, -çi"], 1, None, 2),
 ("«Cüt» numerativ sözü hansı əşyalar üçün işlənir?",
  "Qoşa işlənən əşyalar üçün: bir cüt corab.",
  ["Qoşa işlənən əşyalar üçün", "Tək əşyalar üçün",
   "Yalnız insanlar üçün", "Maye üçün"], 1, None, 3),
],
"az-6-qosma-baglayici": [
 ("«Sonra» qoşması hansı halda olan sözlə işlənir?",
  "Çıxışlıq halla: dərsdən sonra.",
  ["Çıxışlıq halla", "Adlıq halla yalnız", "Təsirlik halla",
   "Yerlik halla"], 1, None, 3),
 ("«Həm … həm də» hansı növ bağlayıcıdır?",
  "Birləşdirmə bağlayıcısıdır.",
  ["Birləşdirmə", "Qarşılaşdırma", "Bölüşdürmə", "İnkar"],
  1, None, 2),
 ("«Və ya» bağlayıcısı hansı əlaqəni bildirir?",
  "Seçmə-bölüşdürmə əlaqəsini.",
  ["Bölüşdürmə (seçmə)", "Qarşılaşdırma", "Səbəb",
   "Nəticə"], 1, None, 2),
 ("«Kimi» qoşması əsasən hansı mənanı bildirir?",
  "Bənzətmə mənasını: aslan kimi.",
  ["Bənzətmə", "Zaman yalnız", "Məkan", "Say"],
  1, None, 2),
 ("«Dərsdən əvvəl» birləşməsində qoşma hansıdır?",
  "Əvvəl sözü qoşmadır.",
  ["əvvəl", "dərs", "-dən", "heç biri"], 1, None, 2),
 ("Qoşmalar aid olduqları sözlə necə yazılır?",
  "Ayrı yazılır: səhərə qədər.",
  ["Ayrı yazılır", "Bitişik yazılır", "Defislə yazılır",
   "Dırnaqda yazılır"], 1, None, 2),
 ("«Çünki» bağlayıcısı hansı əlaqəni bildirir?",
  "Səbəb bildirir.",
  ["Səbəb", "Bənzətmə", "Birləşdirmə", "Zaman"],
  1, None, 2),
 ("«Nə … nə də» bağlayıcısı cümləyə hansı mənanı verir?",
  "İnkar mənasını verir.",
  ["İnkar", "Təsdiq", "Sual", "Əmr"], 1, None, 2),
 ("Köməkçi nitq hissələrinin əsas xüsusiyyəti nədir?",
  "Müstəqil leksik mənası olmur.",
  ["Müstəqil mənasının olmaması", "Cümlə üzvü olmaları",
   "Hallanmaları", "Cəmlənmələri"], 1, None, 3),
 ("«Ancaq» sözü hansı bağlayıcıların sinonimidir?",
  "Amma, lakin bağlayıcılarının.",
  ["Amma, lakin", "Və, ilə", "Çünki, ona görə",
   "Yaxud, və ya"], 1, None, 2),
],
"az-6-cumle-uzvleri": [
 ("Mübtəda cümlədə nəyi bildirir?",
  "Haqqında danışılanı (iş görəni).",
  ["İş görəni (haqqında danışılanı)", "Hərəkətin yerini",
   "Əşyanın əlamətini yalnız", "Sayı"], 1, None, 2),
 ("Mübtəda ilə xəbər arasındakı uzlaşma nəyə əsaslanır?",
  "Şəxsə və kəmiyyətə görə.",
  ["Şəxsə və kəmiyyətə görə", "Rəngə görə",
   "Hecaya görə", "Uzlaşmır"], 1, None, 3),
 ("«Quşlar yuva qurur» cümləsində xəbər hansıdır?",
  "Hərəkəti bildirən söz: qurur.",
  ["qurur", "quşlar", "yuva", "cümlə"], 1, None, 2),
 ("«Dünən», «bu gün» sözləri hansı zərfliyi yaradır?",
  "Zaman zərfliyi olur.",
  ["Zaman zərfliyi", "Yer zərfliyi", "Tərz zərfliyi",
   "Təyin"], 1, None, 2),
 ("«Sürətlə qaçdı» cümləsində «sürətlə» hansı zərflikdir?",
  "Hərəkətin tərzini bildirir.",
  ["Tərzi-hərəkət", "Zaman", "Yer", "Səbəb"],
  1, None, 2),
 ("Tamamlıq hansı hallarda olan sözlərlə ifadə olunur?",
  "Adlıq və yiyəlikdən başqa hallarda.",
  ["Adlıq və yiyəlikdən başqa hallarda", "Yalnız adlıqda",
   "Yalnız yiyəlikdə", "Halsız sözlərlə"], 1, None, 3),
 ("«Yaşıl yarpaqlar» birləşməsində «yaşıl» cümlədə hansı üzv olur?",
  "Əlamət bildirir — təyindir.",
  ["Təyin", "Mübtəda", "Xəbər", "Zərflik"], 1, None, 2),
 ("«Harada?» sualına hansı üzv cavab verir?",
  "Yer zərfliyi cavab verir.",
  ["Yer zərfliyi", "Tamamlıq", "Təyin", "Mübtəda"],
  1, None, 2),
 ("Cümlədə «nəyi?» sualı verilərsə hansı üzvü tapırıq?",
  "Nəyi? sualına tamamlıq cavab verir.",
  ["Tamamlıq", "Təyin", "Zərflik", "Xəbər"], 1, None, 2),
 ("Müəyyən təsirlik halda tamamlıq hansı şəkilçiləri daşıyır?",
  "-ı, -i, -u, -ü şəkilçilərini.",
  ["-ı, -i, -u, -ü", "-da, -də", "-dan, -dən",
   "-ın, -in"], 1, None, 3),
],
"az-6-soz-sirasi": [
 ("Azərbaycan dilində xəbər cümlənin adətən hansı yerində gəlir?",
  "Xəbər adətən sonda durur.",
  ["Sonunda", "Əvvəlində", "Ortasında hökmən",
   "İstənilən yerdə fərqsiz"], 1, None, 2),
 ("Təyin təyin etdiyi sözə nəzərən harada durur?",
  "Təyin olunandan əvvəl gəlir.",
  ["Əvvəl", "Sonra", "Cümlənin sonunda", "Ayrıca sətirdə"],
  1, None, 2),
 ("«Aysunun kitabı» birləşməsi hansı birləşmə növüdür?",
  "Əsas tərəfi isimdir — ismi birləşmədir.",
  ["İsmi birləşmə", "Feili birləşmə", "Cümlə",
   "Frazeologizm"], 1, None, 2),
 ("Feili birləşmənin əsas tərəfi hansı nitq hissəsi olur?",
  "Əsas tərəf feil (məsdər, feili sifət) olur.",
  ["Feil", "İsim", "Sifət", "Say"], 1, None, 2),
 ("«Kitab oxumaq» birləşməsi hansı növdəndir?",
  "Əsas tərəf məsdərdir — feili birləşmədir.",
  ["Feili birləşmə", "İsmi birləşmə", "Sadə cümlə",
   "Mürəkkəb söz"], 1, None, 2),
 ("Söz sırasının pozulması nəyə səbəb ola bilər?",
  "Fikir çətin anlaşılar.",
  ["Fikrin çətin anlaşılmasına", "Sözlərin itməsinə",
   "Hərflərin dəyişməsinə", "Heç nəyə"], 1, None, 2),
 ("«Sabah biz muzeyə gedəcəyik» cümləsində zaman zərfliyi harada durur?",
  "Cümlənin əvvəlində gəlib.",
  ["Cümlənin əvvəlində", "Cümlənin sonunda",
   "Xəbərdən sonra", "Cümlədə yoxdur"], 1, None, 2),
 ("Söz birləşməsində əsas tərəf adətən hansı mövqedə olur?",
  "Asılı tərəfdən sonra — sonda durur.",
  ["Sonda duran tərəfdir", "Əvvəldə duran tərəfdir",
   "Ortada olur", "Mövqeyi yoxdur"], 1, None, 3),
 ("Cümləni genişləndirmək üçün nə əlavə olunur?",
  "İkinci dərəcəli üzvlər əlavə olunur.",
  ["İkinci dərəcəli üzvlər", "Yalnız nida",
   "Yalnız bağlayıcı", "Hərflər"], 1, None, 2),
 ("«Mənim dostum» birləşməsində asılı tərəf hansıdır?",
  "Mənim — asılı tərəfdir.",
  ["mənim", "dostum", "hər ikisi", "heç biri"],
  1, None, 2),
],
"az-6-yazi": [
 ("«Qara + qaş» sözlərindən yaranan mürəkkəb söz necə yazılır?",
  "Bitişik yazılır: qaraqaş.",
  ["Bitişik (qaraqaş)", "Defislə (qara-qaş)",
   "Ayrı (qara qaş)", "Dırnaqda"], 1, None, 2),
 ("«Tez-tez» sözü niyə defislə yazılır?",
  "Təkrar sözlərdən yarandığı üçün.",
  ["Təkrar söz olduğu üçün", "Alınma olduğu üçün",
   "Xüsusi ad olduğu üçün", "Səhvən"], 1, None, 2),
 ("«Şimal-qərb» tipli istiqamət bildirən sözlər necə yazılır?",
  "Belə sözlər defislə yazılır.",
  ["Defislə yazılır", "Bitişik yazılır", "Ayrı yazılır",
   "Böyük hərflə bitişik"], 1, None, 2),
 ("«İstiot» sözü hansı sözlərdən yaranıb?",
  "İsti və ot sözlərindən.",
  ["isti və ot", "ist və iot", "isti və od", "is və tiot"],
  1, None, 2),
 ("Bitişik yazılan mürəkkəb sözü seçin.",
  "Əlüzyuyan bitişik yazılır.",
  ["əlüzyuyan", "əl-üzyuyan", "əl üz yuyan", "əl-üz-yuyan"],
  1, None, 2),
 ("Dar, konkret anlayış bildirən söz necə adlanır?",
  "Hiponim adlanır (alma — meyvə sözünün hiponimidir).",
  ["Hiponim", "Hiperonim", "Omonim", "Antonim"],
  1, None, 3),
 ("«BMT» tipli qısaltmalar necə adlanır?",
  "İxtisarlar (abreviaturalar) adlanır.",
  ["İxtisarlar (abreviatura)", "Mürəkkəb sözlər",
   "Qoşmalar", "Şəkilçilər"], 1, None, 3),
 ("Mürəkkəb sözlər neçə kökdən ibarət olur?",
  "İki və daha artıq kökdən.",
  ["İki və daha artıq", "Yalnız bir", "Yalnız üç",
   "Kökü olmur"], 1, None, 2),
 ("«Günə + baxan» sözləri birləşəndə hansı söz yaranır?",
  "Günəbaxan mürəkkəb sözü.",
  ["günəbaxan", "günə-baxan", "günə baxan", "gün-baxan"],
  1, None, 2),
 ("Sitatlar hansı işarə ilə göstərilir?",
  "Dırnaq işarəsi ilə.",
  ["Dırnaq işarəsi ilə", "Vergüllə", "Tire ilə yalnız",
   "Mötərizə ilə"], 1, None, 2),
],
"ing-6-food": [
 ("Which word is a fruit?",
  "Apple (alma) meyvədir.",
  ["apple", "carrot", "potato", "onion"], 1, None, 1),
 ("«Sweet» sözünün mənası nədir?",
  "Sweet — şirin.",
  ["Şirin", "Acı", "Duzlu", "Turş"], 1, None, 2),
 ("«Cut the bread» nə deməkdir?",
  "Çörəyi kəs.",
  ["Çörəyi kəs", "Çörəyi bişir", "Çörəyi at",
   "Çörək al"], 1, None, 2),
 ("«I am hungry» cümləsi nəyi bildirir?",
  "Ac olmağı bildirir.",
  ["Ac olmağı", "Yorğun olmağı", "Susamağı",
   "Sevincli olmağı"], 1, None, 2),
 ("Which drink is usually hot?",
  "Çay isti içilir.",
  ["tea", "juice", "cola", "ice water"], 1, None, 1),
 ("«Salt» sözünün mənası nədir?",
  "Salt — duz.",
  ["Duz", "Şəkər", "Un", "İstiot"], 1, None, 1),
 ("«He ___ not like fish.»",
  "III şəxs təkdə: does not.",
  ["does", "do", "is", "are"], 1, None, 2),
 ("«Menu» nədir?",
  "Yeməklərin siyahısı.",
  ["Yeməklərin siyahısı", "Mətbəx aləti", "Süfrə",
   "Aşpaz"], 1, None, 2),
 ("«Taste» feilinin mənası nədir?",
  "Taste — dadmaq.",
  ["Dadmaq", "Tökmək", "Doğramaq", "Yumaq"], 1, None, 2),
 ("«Some milk» ifadəsində «some» nəyi bildirir?",
  "Qeyri-müəyyən miqdarı bildirir.",
  ["Qeyri-müəyyən miqdarı", "Dəqiq litri", "Rəngi",
   "Temperaturu"], 1, None, 3),
],
"ing-6-heroes": [
 ("«Strong» sifəti nə deməkdir?",
  "Strong — güclü.",
  ["Güclü", "Zəif", "Balaca", "Qoca"], 1, None, 1),
 ("«He was watching TV at 8 in the evening.» cümləsi hansı zamandadır?",
  "Was + -ing — Past Continuous.",
  ["Past Continuous (davamedici keçmiş)", "Present Simple",
   "Past Simple", "Future"], 1, None, 2),
 ("«While» bağlayıcısı hansı mənanı verir?",
  "Olarkən, o zaman ki.",
  ["Olarkən (o vaxt ki)", "Çünki", "Amma", "Sonra"],
  1, None, 2),
 ("«Firefighter» kimdir?",
  "Yanğınsöndürən.",
  ["Yanğınsöndürən", "Müəllim", "Aşpaz", "Sürücü"],
  1, None, 1),
 ("«Save» feilinin mənası nədir?",
  "Save — xilas etmək.",
  ["Xilas etmək", "İtirmək", "Qorxutmaq", "Atmaq"],
  1, None, 2),
 ("«We ___ walking in the park at 5.»",
  "We ilə: were.",
  ["were", "was", "is", "am"], 1, None, 2),
 ("«Helpful» sifəti necə insanı bildirir?",
  "Kömək etməyi sevən insanı.",
  ["Kömək edən insanı", "Tənbəl insanı", "Qorxaq insanı",
   "Yalançı insanı"], 1, None, 2),
 ("What does a doctor do?",
  "Həkim insanları müalicə edir.",
  ["Helps sick people", "Cooks food", "Drives a bus",
   "Paints walls"], 1, None, 2),
 ("«I was not sleeping.» cümləsi nəyi bildirir?",
  "Keçmişdə davam edən hərəkətin inkarını.",
  ["Yatmırdım (inkar)", "Yatırdım", "Yatacağam",
   "Yataram"], 1, None, 2),
 ("«Polite» sözünün mənası nədir?",
  "Polite — nəzakətli.",
  ["Nəzakətli", "Kobud", "Səsli", "Yavaş"], 1, None, 2),
],
"ing-6-holiday": [
 ("«We visited a museum.» — feil hansı zamandadır?",
  "Visited — Past Simple.",
  ["Past Simple", "Present Continuous", "Future",
   "Past Continuous"], 1, None, 2),
 ("«Ticket» sözünün mənası nədir?",
  "Ticket — bilet.",
  ["Bilet", "Çanta", "Xəritə", "Açar"], 1, None, 1),
 ("«Sea» nə deməkdir?",
  "Sea — dəniz.",
  ["Dəniz", "Göl", "Çay", "Dağ"], 1, None, 1),
 ("«We took photos» nə deməkdir?",
  "Şəkil çəkdik.",
  ["Şəkil çəkdik", "Şəkil sildik", "Şəkil aldıq mağazadan",
   "Şəkil satdıq"], 1, None, 2),
 ("«Where did you stay?» sualı nəyi soruşur?",
  "Harada qaldığını.",
  ["Harada qaldığını", "Nə yediyini", "Kimi gördüyünü",
   "Nə vaxt qayıtdığını"], 1, None, 2),
 ("«Sunny» sözü havanı necə təsvir edir?",
  "Günəşli hava.",
  ["Günəşli", "Yağışlı", "Küləkli", "Qarlı"], 1, None, 1),
 ("«Trip» sözünün mənası nədir?",
  "Trip — səfər, gəzinti.",
  ["Səfər (gəzinti)", "Yuxu", "Dərs", "Yemək"],
  1, None, 2),
 ("«Souvenir» nədir?",
  "Səfərdən gətirilən xatirə hədiyyəsi.",
  ["Xatirə hədiyyəsi", "Sənəd", "Nəqliyyat növü",
   "Yemək adı"], 1, None, 2),
 ("«Last month» ifadəsinin mənası nədir?",
  "Keçən ay.",
  ["Keçən ay", "Gələn ay", "Bu ay", "Hər ay"],
  1, None, 1),
 ("«Camp» sözü nəyi bildirir?",
  "Camp — düşərgə.",
  ["Düşərgəni", "Oteli", "Muzeyi", "Limanı"], 1, None, 2),
],
"ing-6-ideas": [
 ("«Clever» sözünün mənası nədir?",
  "Clever — ağıllı.",
  ["Ağıllı", "Yorğun", "Ac", "Qəmgin"], 1, None, 1),
 ("«This computer is ___.» (bizimki)",
  "Bizimki — ours.",
  ["ours", "our", "us", "we"], 1, None, 3),
 ("«Whose book is this?» sualı nəyi soruşur?",
  "Kitabın kimə aid olduğunu.",
  ["Kitabın kimin olduğunu", "Kitabın rəngini",
   "Kitabın qiymətini", "Kitabın adını"], 1, None, 2),
 ("«Idea» sözünün mənası nədir?",
  "Idea — fikir, ideya.",
  ["Fikir (ideya)", "Alət", "Otaq", "Səs"], 1, None, 1),
 ("«He was reading when I came.» cümləsində hansı zamanlar işlənib?",
  "Davam edən keçmiş + bitmiş keçmiş.",
  ["Past Continuous və Past Simple", "İki Present Simple",
   "Future və Past", "İki Past Simple"], 1, None, 3),
 ("«Robot» insanlara nə ilə kömək edir?",
  "Ağır və darıxdırıcı işləri görür.",
  ["İşləri yüngülləşdirir", "Yemək yeyir", "Yatır",
   "Oxuyur yalnız"], 1, None, 2),
 ("«Theirs» nə deməkdir?",
  "Theirs — onlarınkı.",
  ["Onlarınkı", "Bizimki", "Səninki", "Mənimki"],
  1, None, 3),
 ("«Useful» sifəti nə deməkdir?",
  "Useful — faydalı.",
  ["Faydalı", "Zərərli", "Boş", "Köhnə"], 1, None, 2),
 ("«Internet» ixtirası insanlara nə verdi?",
  "Sürətli məlumat mübadiləsi imkanı.",
  ["Sürətli məlumat mübadiləsi", "Yalnız oyun",
   "Yalnız musiqi", "Heç nə"], 1, None, 2),
 ("«Hers» sözü nəyi bildirir?",
  "Hers — onunku (qadın haqqında).",
  ["Onunku (qadın)", "Onunku (kişi)", "Bizimki",
   "Sizinki"], 1, None, 3),
],
"ing-6-journeys": [
 ("Which is air transport?",
  "Təyyarə hava nəqliyyatıdır.",
  ["plane", "ship", "train", "bus"], 1, None, 1),
 ("Təyyarələrin endiyi yer ingiliscə necə adlanır?",
  "Hava limanı — airport.",
  ["airport", "port", "station", "garage"],
  1, None, 1),
 ("«Station» sözünün mənası nədir?",
  "Station — vağzal, stansiya.",
  ["Vağzal (stansiya)", "Mağaza", "Məktəb", "Park"],
  1, None, 2),
 ("«We ___ to Ganja last week.» (getdik)",
  "Go feilinin keçmişi: went.",
  ["went", "go", "gone", "goes"], 1, None, 2),
 ("«Could you swim when you were six?» sualına qısa cavab hansıdır?",
  "Yes, I could.",
  ["Yes, I could.", "Yes, I can.", "No, I am not.",
   "Yes, I do."], 1, None, 3),
 ("«Map» nə üçün lazımdır?",
  "Yolu tapmaq üçün.",
  ["Yol tapmaq üçün", "Yemək üçün", "Yazmaq üçün",
   "Geymək üçün"], 1, None, 1),
 ("«Fast train» ifadəsinin mənası nədir?",
  "Sürətli qatar.",
  ["Sürətli qatar", "Köhnə qatar", "Boş qatar",
   "Uzun yol"], 1, None, 2),
 ("«On foot» ifadəsi necə getməyi bildirir?",
  "Piyada getməyi.",
  ["Piyada", "Maşınla", "Təyyarə ilə", "Gəmi ilə"],
  1, None, 2),
 ("«Arrive» feilinin mənası nədir?",
  "Arrive — çatmaq.",
  ["Çatmaq", "Yola düşmək", "Dayanmaq", "İtirmək"],
  1, None, 2),
 ("«Bicycle» sözünün qısa forması hansıdır?",
  "Bike — velosiped.",
  ["bike", "bic", "cycle car", "bus"], 1, None, 2),
],
"ing-6-nature": [
 ("«Lake» nə deməkdir?",
  "Lake — göl.",
  ["Göl", "Dəniz", "Çay", "Bulaq"], 1, None, 1),
 ("«Pollution» sözü nəyi bildirir?",
  "Pollution — çirklənmə.",
  ["Çirklənməni", "Təmizliyi", "Yağışı", "Küləyi"],
  1, None, 2),
 ("«Plant a tree» nə deməkdir?",
  "Ağac əkmək.",
  ["Ağac əkmək", "Ağac kəsmək", "Ağaca dırmaşmaq",
   "Ağac satmaq"], 1, None, 2),
 ("«Sky» sözünün mənası nədir?",
  "Sky — səma.",
  ["Səma", "Torpaq", "Dəniz", "Bulud yalnız"], 1, None, 1),
 ("«Recycling» nə üçün vacibdir?",
  "Tullantılar yenidən emal olunur, təbiət qorunur.",
  ["Təbiəti qorumaq üçün", "Daha çox zibil üçün",
   "Pul xərcləmək üçün", "Vacib deyil"], 1, None, 2),
 ("«Bear» hansı heyvandır?",
  "Bear — ayı.",
  ["Ayı", "Dovşan", "Tülkü", "Canavar"], 1, None, 1),
 ("«Island» nə deməkdir?",
  "Island — ada.",
  ["Ada", "Yarımada", "Körfəz", "Sahil"], 1, None, 2),
 ("«We must not cut down trees.» cümləsi nəyi qadağan edir?",
  "Ağacları kəsməyi.",
  ["Ağac kəsməyi", "Ağac əkməyi", "Gəzməyi",
   "Su içməyi"], 1, None, 2),
 ("«Weather» sözünün mənası nədir?",
  "Weather — hava.",
  ["Hava", "Su", "Torpaq", "Külək yalnız"], 1, None, 1),
 ("«Grass» nə deməkdir?",
  "Grass — ot.",
  ["Ot", "Gül", "Kol", "Yarpaq"], 1, None, 1),
],
"ing-6-stories": [
 ("«Go» feilinin Past Simple forması hansıdır?",
  "Go — went.",
  ["went", "goed", "gone", "going"], 1, None, 2),
 ("«See» feilinin keçmiş forması hansıdır?",
  "See — saw.",
  ["saw", "seed", "seen", "sees"], 1, None, 2),
 ("«Character» sözü hekayədə nəyi bildirir?",
  "Hekayənin obrazını.",
  ["Obrazı", "Səhifəni", "Müəllifi yalnız", "Qiyməti"],
  1, None, 2),
 ("«The end» ifadəsi nə deməkdir?",
  "Son.",
  ["Son", "Başlanğıc", "Orta", "Davamı var"], 1, None, 1),
 ("«Did you read the story? — Yes, I ___.»",
  "Qısa cavab: did.",
  ["did", "do", "read not", "was"], 1, None, 2),
 ("«Yesterday» sözünün mənası nədir?",
  "Yesterday — dünən.",
  ["Dünən", "Sabah", "Bu gün", "Keçən il"], 1, None, 1),
 ("«Fairy tale» nə deməkdir?",
  "Fairy tale — nağıl.",
  ["Nağıl", "Qəzet", "Məktub", "Reklam"], 1, None, 2),
 ("«He did not go to school.» cümləsi nəyi bildirir?",
  "Keçmişdə getmədiyini.",
  ["Məktəbə getmədiyini", "Məktəbə getdiyini",
   "Məktəbə gedəcəyini", "Məktəbi sevdiyini"], 1, None, 2),
 ("«Ago» sözü hansı zamanla işlənir?",
  "Two days ago — Past Simple ilə.",
  ["Past Simple ilə", "Future ilə", "Present Continuous ilə",
   "Heç biri ilə"], 1, None, 3),
 ("«Read» feilinin keçmiş forması necə yazılır?",
  "Yazılış eyni qalır: read.",
  ["read (eyni yazılışla)", "readed", "red yalnız",
   "reads"], 1, None, 3),
],
"ing-6-town": [
 ("«Hospital» nədir?",
  "Hospital — xəstəxana.",
  ["Xəstəxana", "Məktəb", "Mağaza", "Kitabxana"],
  1, None, 1),
 ("«Post office» nə üçündür?",
  "Məktub və bağlama göndərmək üçün.",
  ["Məktub göndərmək üçün", "Yemək almaq üçün",
   "Film izləmək üçün", "İdman üçün"], 1, None, 2),
 ("«Opposite» sözünün mənası nədir?",
  "Opposite — qarşısında.",
  ["Qarşısında", "Yanında", "Arxasında", "İçində"],
  1, None, 2),
 ("«Turn left» əmri nə deməkdir?",
  "Sola dön.",
  ["Sola dön", "Sağa dön", "Düz get", "Dayan"],
  1, None, 1),
 ("«Usually» sözünün mənası nədir?",
  "Usually — adətən.",
  ["Adətən", "Heç vaxt", "Dərhal", "Tezliklə"],
  1, None, 2),
 ("«Sometimes» nə deməkdir?",
  "Sometimes — bəzən.",
  ["Bəzən", "Həmişə", "Dünən", "Sabah"], 1, None, 2),
 ("Where can we watch a film?",
  "Filmi kinoteatrda izləyirik.",
  ["At the cinema", "At the bakery", "At the bank",
   "At the chemist"], 1, None, 1),
 ("«Street» sözünün mənası nədir?",
  "Street — küçə.",
  ["Küçə", "Ev", "Meydan", "Bina"], 1, None, 1),
 ("«How can I get to the park?» sualı nəyi soruşur?",
  "Parka gedən yolu.",
  ["Yolu", "Vaxtı", "Qiyməti", "Havanı"], 1, None, 2),
 ("«Bridge» nə deməkdir?",
  "Bridge — körpü.",
  ["Körpü", "Yol", "Tunel", "Çəpər"], 1, None, 1),
],
"inf-6-alqoritm": [
 ("Alqoritmin kütləvilik xassəsi nə deməkdir?",
  "Eyni tipli bütün məsələlərə tətbiq oluna bilməsi.",
  ["Oxşar məsələlərin hamısına tətbiq olunması",
   "Yalnız bir məsələyə aid olması", "Uzun olması",
   "Şəkilli olması"], 1, None, 3),
 ("Xətti alqoritmə məişətdən misal hansıdır?",
  "Çay dəmləmə ardıcıllığı addım-addım icra olunur.",
  ["Çay dəmləmə ardıcıllığı", "Tənliyin qrafiki",
   "Şəkil çəkmək istəyi", "Təsadüfi seçim"], 1, None, 2),
 ("«Əgər hava soyuqdursa, palto gey, əks halda gödəkçə» — burada neçə yol var?",
  "İki mümkün yol var.",
  ["2", "1", "3", "4"], 1, None, 2),
 ("Dövri alqoritmdə təkrarlanan hissə necə adlanır?",
  "Dövrün gövdəsi adlanır.",
  ["Dövrün gövdəsi", "Dövrün başlığı", "Şərt bloku",
   "Son blok"], 1, None, 3),
 ("Alqoritmi icra edən qurğu və ya canlı necə adlanır?",
  "İcraçı adlanır.",
  ["İcraçı", "Müəllif", "Proqramçı", "İstifadəçi yalnız"],
  1, None, 2),
 ("Blok-sxemdə oxlar nəyi göstərir?",
  "Addımların icra istiqamətini.",
  ["İcra istiqamətini", "Rəngi", "Səhvləri", "Sürəti"],
  1, None, 2),
 ("Tam budaqlanmada neçə budaq olur?",
  "Hə və yox — iki budaq.",
  ["İki (hə və yox)", "Bir", "Həmişə üç", "Sonsuz"],
  1, None, 2),
 ("Alqoritmin diskretlik xassəsi nə deməkdir?",
  "Ayrı-ayrı addımlardan ibarət olması.",
  ["Ayrı-ayrı addımlardan ibarət olması",
   "Bir bütöv hərəkət olması", "Sonsuz olması",
   "Sözsüz olması"], 1, None, 3),
 ("Budaqlanan alqoritmdə şərt ödənmədikdə nə baş verir?",
  "Digər (əks) budaq icra olunur.",
  ["Digər budaq icra olunur", "Proqram silinir",
   "Kompüter sönür", "Şərt təkrar yoxlanır sonsuz"],
  1, None, 3),
 ("«Alqoritm» sözü hansı alimin adı ilə bağlıdır?",
  "IX əsr alimi Əl-Xarəzminin adından yaranıb.",
  ["Əl-Xarəzmi", "Nyuton", "Arximed", "Mendeleyev"],
  1, None, 3),
],
"inf-6-kompyuter": [
 ("Bir qiqabaytda neçə meqabayt var?",
  "1 GB = 1024 MB.",
  ["1024", "100", "10", "1000000"], 1, None, 3),
 ("Kompüterin «beyni» sayılan qurğu hansıdır?",
  "Prosessor bütün hesablamaları aparır.",
  ["Prosessor", "Monitor", "Klaviatura", "Printer"],
  1, None, 2),
 ("Verilənlərin emalını hansı qurğu yerinə yetirir?",
  "Emalı prosessor aparır.",
  ["Prosessor", "Səs ucaldıcı", "Maus", "Kamera"],
  1, None, 2),
 ("Səs informasiyası kompüterdə hansı formada saxlanır?",
  "Rəqəmsal (ikilik) kodda.",
  ["Rəqəmsal (ikilik) kodda", "Kağızda", "Lentdə yalnız",
   "Saxlanmır"], 1, None, 3),
 ("Şəkil çox böyüdüləndə nə görünür?",
  "Ayrı-ayrı piksellər görünür.",
  ["Piksellər", "Hərflər", "Notlar", "Heç nə"],
  1, None, 2),
 ("Fləş kart nə üçün istifadə olunur?",
  "Məlumatı daşımaq və saxlamaq üçün.",
  ["Məlumat daşımaq üçün", "Şəkil çəkmək üçün",
   "Səs yazmaq üçün yalnız", "İşıqlandırma üçün"],
  1, None, 2),
 ("Hər simvol 1 bayt tutursa, 10 simvolluq söz nə qədər yer tutar?",
  "10 simvol — 10 bayt.",
  ["10 bayt", "1 bayt", "10 bit", "1 KB"], 1, None, 3),
 ("Onluq 7 ədədi ikilik say sistemində necə yazılır?",
  "7 = 4 + 2 + 1 = 111.",
  ["111", "101", "110", "100"], 1, None, 3),
 ("Verilənlər hansı qurğuda uzunmüddətli saxlanır?",
  "Sərt diskdə saxlanır.",
  ["Sərt diskdə", "Əməli yaddaşda", "Prosessorda",
   "Monitorda"], 1, None, 2),
 ("Klaviatura və maus hansı qurğular qrupuna aiddir?",
  "Daxiletmə qurğularıdır.",
  ["Daxiletmə qurğularına", "Xaricetmə qurğularına",
   "Yaddaş qurğularına", "Səs qurğularına"], 1, None, 2),
],
"inf-6-internet": [
 ("Sayt ünvanındakı «.az» hissəsi nəyi bildirir?",
  "Azərbaycan milli domenini.",
  ["Azərbaycan domenini", "Saytın rəngini",
   "Saytın yaşını", "Parolu"], 1, None, 3),
 ("E-məktub yazanda hansı nəzakət qaydasına əməl olunur?",
  "Salamlaşmaq və mövzunu göstərmək.",
  ["Salamlaşmaq və mövzunu yazmaq", "Böyük hərflərlə qışqırmaq",
   "İmzasız göndərmək", "Boş göndərmək"], 1, None, 2),
 ("Arzuolunmaz kütləvi reklam məktubları necə adlanır?",
  "Belə məktublar spam adlanır.",
  ["Spam", "Qoşma", "Domen", "Parol"], 1, None, 2),
 ("Sosial şəbəkədə tanımadığın şəxsin dostluq təklifinə nə etməli?",
  "Qəbul etməmək daha təhlükəsizdir.",
  ["Qəbul etməməli", "Dərhal qəbul etməli",
   "Ünvanını verməli", "Şəklini göndərməli"], 1, None, 2),
 ("Axtarışda dırnaq içində yazılan ifadə nəyi bildirir?",
  "Dəqiq ifadənin axtarılmasını.",
  ["Dəqiq ifadəni axtarmağı", "Şəkil axtarmağı",
   "Səs axtarmağı", "Heç nəyi"], 1, None, 3),
 ("Onlayn lüğət və ensiklopediyalar hansı resurslara aiddir?",
  "Təhsil (informasiya) resurslarına.",
  ["Təhsil resurslarına", "Oyun resurslarına",
   "Reklamlara", "Spama"], 1, None, 2),
 ("Eyni məktubu iki fərqli ünvana yollamaq mümkündürmü?",
  "Bəli, ünvanları əlavə etməklə.",
  ["Bəli, ünvanları əlavə etməklə", "Xeyr, olmaz",
   "Yalnız gecə olar", "Yalnız şəkilsiz olar"],
  1, None, 2),
 ("İnternetdə müəllif hüququ nəyi qoruyur?",
  "Yaradıcı işləri (mətn, şəkil, musiqi).",
  ["Yaradıcı işləri", "Parolları", "Kompüterin rəngini",
   "Elektrik xəttini"], 1, None, 3),
 ("Həddindən artıq internet istifadəsi nəyə səbəb ola bilər?",
  "Asılılığa və vaxt itkisinə.",
  ["Asılılığa", "Güclənməyə", "Yaxşı yuxuya",
   "Heç nəyə"], 1, None, 2),
 ("Etibarlı parol necə olmalıdır?",
  "Uzun, hərf və rəqəmlərdən ibarət.",
  ["Uzun, hərf və rəqəmli", "Ad günü tarixi",
   "Yalnız 123", "Öz adın"], 1, None, 2),
],
"inf-6-proqram-teminati": [
 ("Hansı proqramlar sistem proqram təminatını təşkil edir?",
  "Əməliyyat sistemi və drayverlər.",
  ["Əməliyyat sistemi və drayverlər", "Yalnız oyunlar",
   "Yalnız mətn redaktoru", "Şəkillər"], 1, None, 3),
 ("Aşağıdakılardan hansı tətbiqi proqramdır?",
  "Mətn redaktoru tətbiqi proqramdır.",
  ["Mətn redaktoru", "Drayver", "Əməliyyat sistemi",
   "BIOS"], 1, None, 2),
 ("Slaydda başlıq nə üçündür?",
  "Slaydın mövzusunu bildirmək üçün.",
  ["Mövzunu bildirmək üçün", "Bəzək üçün yalnız",
   "Yer tutmaq üçün", "Vacib deyil"], 1, None, 2),
 ("Təqdimatda keçid effektləri nə verir?",
  "Slaydlararası keçidi canlandırır.",
  ["Slaydlar arası keçidi canlandırır", "Mətni silir",
   "Kompüteri sürətləndirir", "Səhvləri düzəldir"],
  1, None, 2),
 ("Mətnin düzləndirilməsi növləri hansılardır?",
  "Sola, sağa, mərkəzə və eninə görə.",
  ["Sola, sağa, mərkəzə, eninə", "Yalnız sola",
   "Yalnız mərkəzə", "Yuxarı-aşağı"], 1, None, 3),
 ("Şriftin ölçüsü hansı vahidlə göstərilir?",
  "Punktla ölçülür.",
  ["Punktla", "Metrlə", "Baytla", "Dərəcə ilə"],
  1, None, 3),
 ("Mətn sənədinə cədvəl əlavə etmək olarmı?",
  "Bəli, cədvəl menyusundan.",
  ["Bəli, cədvəl menyusundan", "Xeyr, olmaz",
   "Yalnız şəkil kimi", "Yalnız çapdan sonra"],
  1, None, 2),
 ("Slaydda həddindən çox mətn yazmaq nə üçün pisdir?",
  "Dinləyici oxuya bilmir, diqqət yayınır.",
  ["Oxumaq çətinləşir", "Kompüter sınır",
   "Rənglər itir", "Pis deyil"], 1, None, 2),
 ("Qurğunu idarə edən xidməti proqram necə adlanır?",
  "Belə proqram drayver adlanır.",
  ["Drayver", "Oyun proqramı", "Şəkil faylı", "Qovluq"],
  1, None, 3),
 ("Proqramın kompüterə yüklənməsi prosesi necə adlanır?",
  "Quraşdırma (install) adlanır.",
  ["Quraşdırma (install)", "Silinmə", "Çap", "Kopyalama"],
  1, None, 2),
],
"inf-6-proqramlasdirma": [
 ("ALPLogo-da «irəli 100» əmri nə edir?",
  "Bağanı 100 addım irəli aparır.",
  ["Bağanı 100 addım irəli aparır", "Bağanı silir",
   "Rəngi dəyişir", "Proqramı bağlayır"], 1, None, 2),
 ("Üçbucaq çəkmək üçün təkrar əmrində dönmə bucağı neçə olmalıdır?",
  "360 : 3 = 120 dərəcə.",
  ["120", "90", "60", "45"], 1, None, 3),
 ("Dəyişənin adı necə başlamalıdır?",
  "Hərflə başlamalıdır.",
  ["Hərflə", "Rəqəmlə", "Boşluqla", "Nöqtə ilə"],
  1, None, 3),
 ("Proqramda «say = say + 1» əməliyyatı nə edir?",
  "Sayğacın qiymətini bir artırır.",
  ["Sayğacı bir artırır", "Sayğacı sıfırlayır",
   "Proqramı dayandırır", "Səhv verir hökmən"],
  1, None, 3),
 ("Musiqi əmrində notun uzunluğu nəyi bildirir?",
  "Səsin davametmə müddətini.",
  ["Səsin davametmə müddətini", "Səsin rəngini",
   "Notun adını", "Mahnının sözlərini"], 1, None, 3),
 ("Scratch mühitində personaj necə adlanır?",
  "Sprayt adlanır.",
  ["Sprayt", "Slayd", "Sətir", "Sxem"], 1, None, 2),
 ("«Bayraq klikləndikdə» bloku nə edir?",
  "Proqramın icrasını başladır.",
  ["Proqramı başladır", "Proqramı silir",
   "Səsi artırır", "Rəngi dəyişir"], 1, None, 2),
 ("Şərt blokundakı yoxlama hansı cavabları verə bilər?",
  "Hə (doğru) və ya yox (yalan).",
  ["Hə və ya yox cavabı", "Yalnız rəqəm",
   "Yalnız mətn", "Şəkil"], 1, None, 3),
 ("Alqoritmi proqram şəklində yazan şəxs necə adlanır?",
  "Proqramçı adlanır.",
  ["Proqramçı", "Rəssam", "Bəstəkar", "Sürücü"],
  1, None, 1),
 ("Proqramda xətanı tapıb düzəltmə prosesi necə adlanır?",
  "Sazlama (debugging) adlanır.",
  ["Sazlama (debugging)", "Formatlama", "Çap",
   "Kopyalama"], 1, None, 3),
],
"tarix-6-ibtidai": [
 ("Daş dövrü hansı mərhələlərə bölünür?",
  "Paleolit, mezolit və neolit.",
  ["Paleolit, mezolit, neolit", "Tunc və dəmir",
   "Qədim və yeni", "Bölünmür"], 1, None, 3),
 ("İbtidai icmada əmək bölgüsü kimlər arasında idi?",
  "Kişilər və qadınlar arasında.",
  ["Kişilər və qadınlar arasında", "Uşaqlar arasında yalnız",
   "Dövlətlər arasında", "Yox idi"], 1, None, 2),
 ("Ovçuluqda mezolit dövründə hansı alət meydana gəldi?",
  "Ox və yay ovçuluğu asanlaşdırdı.",
  ["Ox və yay", "Traktor", "Dəmir qılınc", "Tüfəng"],
  1, None, 2),
 ("Neolit dövründə insanlar nəyi öyrəndilər?",
  "Əkinçilik və dulusçuluğu.",
  ["Əkinçilik və dulusçuluğu", "Yazı makinasını",
   "Gəmiçiliyi yalnız", "Heç nəyi"], 1, None, 2),
 ("Qəbilə nədir?",
  "Qohum icmaların birliyidir.",
  ["Qohum icmaların birliyi", "Bir ailə", "Bir şəhər",
   "Bir dövlət"], 1, None, 2),
 ("Tayfa birlikləri hansı məqsədlə yaranırdı?",
  "Birgə müdafiə və təsərrüfat üçün.",
  ["Birgə müdafiə üçün", "Oyun üçün", "Səyahət üçün",
   "Ticarət qadağası üçün"], 1, None, 2),
 ("Eramızdan əvvəlki tarixlər hansı sıra ilə sayılır?",
  "E.ə. tarixlər azalan sıra ilə gedir.",
  ["Azalan sıra ilə", "Artan sıra ilə", "Qarışıq",
   "Sayılmır"], 1, None, 3),
 ("Mis dövründən sonra hansı dövr gəlir?",
  "Tunc dövrü gəlir.",
  ["Tunc dövrü", "Daş dövrü", "Dəmir dövrü əvvəl",
   "Buz dövrü"], 1, None, 2),
 ("Sənətkarlığın ayrılması nəyə səbəb oldu?",
  "Mübadilənin və ticarətin yaranmasına.",
  ["Mübadilənin yaranmasına", "Ovçuluğun bitməsinə",
   "Yazının itməsinə", "Heç nəyə"], 1, None, 3),
 ("Arxeoloji qazıntılarda tapılan əşyalar necə adlanır?",
  "Maddi mədəniyyət abidələri.",
  ["Maddi mədəniyyət abidələri", "Yeni məhsullar",
   "Sənədlər yalnız", "Xəritələr"], 1, None, 2),
],
"tarix-6-qedim-dovletler": [
 ("Manna hansı dövlətlərlə mübarizə aparırdı?",
  "Assuriya və Urartu ilə.",
  ["Assuriya və Urartu ilə", "Roma ilə", "Çinlə",
   "Misirlə"], 1, None, 3),
 ("Atropatena dövlətinin adı nədən yaranmışdır?",
  "Sərkərdə Atropatın adından.",
  ["Atropatın adından", "Dağın adından", "Çayın adından",
   "Şəhərin adından"], 1, None, 2),
 ("Qəbələ hansı dövlətin paytaxtı idi?",
  "Albaniyanın paytaxtı idi.",
  ["Albaniyanın", "Mannanın", "Atropatenanın",
   "Skif padşahlığının"], 1, None, 2),
 ("Atropatena hansı hadisədən sonra müstəqil dövlət oldu?",
  "Makedoniyalı İsgəndərin yürüşlərindən sonra.",
  ["İsgəndərin yürüşlərindən sonra", "Neft tapılandan sonra",
   "Xanlıqlardan sonra", "Sovet dövründən sonra"],
  1, None, 3),
 ("Qədim dövlətlərdə ordunun əsasını kimlər təşkil edirdi?",
  "Süvarilər və piyadalar.",
  ["Süvarilər və piyadalar", "Təyyarəçilər", "Dənizçilər yalnız",
   "Tankçılar"], 1, None, 2),
 ("Albaniya əhalisi hansı tayfalardan ibarət idi?",
  "26 tayfadan: albanlar, utilər və başqaları.",
  ["26 tayfadan (albanlar, utilər və b.)", "Bir tayfadan",
   "Yalnız köçərilərdən", "Yalnız yunanlardan"],
  1, None, 3),
 ("Mannanın paytaxtı hansı şəhər idi?",
  "İzirtu şəhəri idi.",
  ["İzirtu", "Qazaka", "Qəbələ", "Bakı"], 1, None, 3),
 ("Əhəmənilər dövründə ölkə hansı vahidlərlə idarə olunurdu?",
  "Satraplıqlara bölünmüşdü.",
  ["Satraplıqlar şəklində", "Xanlıqlar şəklində",
   "Respublikalarla", "Şəhər dövlətləri ilə"], 1, None, 3),
 ("Atropatenada hansı din geniş yayılmışdı?",
  "Zərdüştilik yayılmışdı.",
  ["Zərdüştilik", "Buddizm", "Xristianlıq", "İslam"],
  1, None, 2),
 ("Atropatena iqtisadiyyatı hansı sahələrdə inkişaf etmişdi?",
  "Sənətkarlıq və ticarətdə.",
  ["Sənətkarlıq və ticarətdə", "Yalnız balıqçılıqda",
   "Neft emalında", "Turizmdə"], 1, None, 2),
],
"tarix-6-erken-orta": [
 ("Albaniyada V əsrdə hansı mədəni hadisə baş verdi?",
  "Alban əlifbası yaradıldı.",
  ["Alban əlifbası yaradıldı", "Dəmir yolu çəkildi",
   "Universitet açıldı", "Qəzet çıxdı"], 1, None, 3),
 ("Ərəb xilafəti Azərbaycanı hansı əsrdə işğal etdi?",
  "VII əsrdə işğal etdi.",
  ["VII əsrdə", "III əsrdə", "XII əsrdə", "XX əsrdə"],
  1, None, 2),
 ("İslam dini Azərbaycanda nə vaxtdan yayılmağa başladı?",
  "Ərəb işğalından sonra.",
  ["Ərəb işğalından sonra", "Sasanilərdən əvvəl",
   "XX əsrdə", "Skiflər dövründə"], 1, None, 2),
 ("Xürrəmilər hərəkatının rəhbəri kim idi?",
  "Babək rəhbərlik edirdi.",
  ["Babək", "Cavanşir", "Atropat", "İranzu"],
  1, None, 2),
 ("Babək hərəkatı təqribən nə qədər davam etdi?",
  "20 ildən artıq davam etdi.",
  ["20 ildən artıq", "2 il", "100 il", "6 ay"],
  1, None, 3),
 ("Ərəblərin qeyri-müsəlmanlardan aldığı can vergisi necə adlanırdı?",
  "Cizyə adlanırdı.",
  ["Cizyə", "Xərac yalnız torpaqdan", "Gömrük", "Bac"],
  1, None, 3),
 ("Girdiman dövləti hansı sülalə ilə bağlıdır?",
  "Mehranilər sülaləsi ilə.",
  ["Mehranilərlə", "Səfəvilərlə", "Əhəmənilərlə",
   "Atabəylərlə"], 1, None, 3),
 ("Feodal cəmiyyətində əsas sərvət nə idi?",
  "Torpaq əsas sərvət idi.",
  ["Torpaq", "Neft", "Kağız pul", "Qızıl yalnız"],
  1, None, 2),
 ("Natural təsərrüfat nə deməkdir?",
  "Hər şeyin öz təsərrüfatında istehsal olunması.",
  ["Hər şeyin öz təsərrüfatında istehsalı",
   "Hər şeyin bazardan alınması", "Fabrik istehsalı",
   "Xarici ticarət"], 1, None, 3),
 ("Bəzz qalası ilə bağlı hərəkat necə adlanırdı?",
  "Xürrəmilər hərəkatı.",
  ["Xürrəmilər hərəkatı", "Dekabristlər", "Səlib yürüşü",
   "Qızılbaşlar"], 1, None, 2),
],
}
for _k, _v in ELAVE.items():
    SUALLAR[_k] = SUALLAR[_k] + _v


MOVZULAR += [
    ("tarix", "tarix-6-manna",      2),
    ("tarix", "tarix-6-atropatena", 2),
    ("tarix", "tarix-6-albaniya",   3),
]

YENI_TARIX = {
"tarix-6-manna": [
 ("Manna haqqında məlumatlar hansı yazı növü ilə yazılmış mənbələrdədir?",
  "Assur və Urartu mixi yazıları Manna haqqında əsas mənbədir.",
  ["Mixi yazılarla", "Heroqliflərlə", "Latın əlifbası ilə",
   "Runik yazı ilə"], 1, None, 2),
 ("Manna hökmdarı İranzunun oğulları kimlər idi?",
  "İranzudan sonra oğulları Aza və Ullusunu hakimiyyətdə oldular.",
  ["Aza və Ullusunu", "Atropat və Oris", "Toğrul və Çağrı",
   "Kir və Dara"], 1, None, 3),
 ("Manna hökmdarı Ullusunu hansı dövlətlə müttəfiqlik edirdi?",
  "Ullusunu Assuriya ilə yaxınlaşaraq ölkəni qorumağa çalışırdı.",
  ["Assuriya ilə", "Roma ilə", "Misirlə", "Bizansla"],
  1, None, 3),
 ("Həsənli təpəsindən tapılmış məşhur Manna abidəsi hansıdır?",
  "Həsənlidən tapılan qızıl cam Manna incəsənətinin şah əsəridir.",
  ["Qızıl cam", "Daş heykəl", "Gümüş qılınc", "Saxsı küpə"],
  1, None, 2),
 ("Manna sənətkarlığında hansı sahə xüsusilə inkişaf etmişdi?",
  "Metalişləmə - qızıl, gümüş və tunc emalı yüksək səviyyədə idi.",
  ["Metalişləmə", "Şüşəüfürmə", "Kağız istehsalı",
   "Zərgərlik yalnız"], 1, None, 2),
 ("Manna dövləti hansı dövlətin tərkibinə qatılmaqla süqut etdi?",
  "E.ə. VII əsrin sonunda Manna Midiyaya birləşdirildi.",
  ["Midiyanın", "Romanın", "Osmanlının", "Sasanilərin"],
  1, None, 2),
 ("Manna ordusunun əsas silahları nə idi?",
  "Döyüşçülər ox, nizə və qalxanla silahlanırdı.",
  ["Ox, nizə və qalxan", "Top və tüfəng", "Yalnız daşlar",
   "Qılınc yalnız"], 1, None, 2),
 ("Manna hökmdarı ölkəni necə idarə edirdi?",
  "Vilayətlərə hökmdarın təyin etdiyi canişinlər başçılıq edirdi.",
  ["Canişinlər vasitəsilə", "Seçkili şuralarla",
   "Kahinlər vasitəsilə yalnız", "İdarə olunmurdu"], 1, None, 3),
 ("Manna əhalisinin dini inancları nə ilə bağlı idi?",
  "Əhali təbiət qüvvələrinə sitayiş edirdi.",
  ["Təbiət qüvvələrinə sitayişlə", "Xristianlıqla",
   "İslamla", "Buddizmlə"], 1, None, 2),
 ("Manna incəsənətinə aid qiymətli tapıntılar haradan aşkar olunub?",
  "Həsənli və Ziviyə abidələrindən zəngin tapıntılar əldə edilib.",
  ["Həsənli və Ziviyədən", "Qobustandan", "Bakıdan",
   "İçərişəhərdən"], 1, None, 2),
 ("Ziviyə dəfinəsi nə ilə məşhurdur?",
  "Ziviyədən qızıl və gümüş əşyalar tapılmışdır.",
  ["Qızıl və gümüş əşyalarla", "Daş kitabələrlə",
   "Gil qablarla yalnız", "Dəmir alətlərlə"], 1, None, 3),
 ("Manna e.ə. VII əsrdə hansı köçəri tayfaların hücumlarına məruz qalırdı?",
  "Şimaldan gələn skif və kimmer tayfaları Mannaya hücumlar edirdi.",
  ["Skiflərin və kimmerlərin", "Ərəblərin", "Monqolların",
   "Slavyanların"], 1, None, 3),
 ("Manna hökmdarı Ahşeri dövründə dövlətdə nə baş verdi?",
  "Ahşerinin dövründə üsyanlar güclənmiş, dövlət zəifləmişdi.",
  ["Üsyanlar gücləndi", "Dövlət ən qüdrətli oldu",
   "Paytaxt dəyişdirildi", "Yeni əlifba yaradıldı"], 1, None, 3),
 ("Manna şəhərlərinin ətrafına nə çəkilirdi?",
  "Şəhərlər müdafiə divarları ilə əhatə olunurdu.",
  ["Müdafiə divarları", "Su kanalları yalnız",
   "Üzüm bağları", "Daş yollar"], 1, None, 2),
 ("Manna dövləti təxminən neçə əsr mövcud olmuşdur?",
  "E.ə. IX əsrdən VII əsrin sonunadək - təqribən üç əsr.",
  ["Təxminən üç əsr", "Yarım əsr", "On əsr", "Bir əsr"],
  1, None, 3),
 ("Manna əkinçiliyində hansı bitkilər becərilirdi?",
  "Taxıl və üzüm becərilməsi geniş yayılmışdı.",
  ["Taxıl və üzüm", "Kartof və pomidor", "Çay və sitrus",
   "Pambıq yalnız"], 1, None, 2),
 ("Manna maldarlığında hansı sahə xüsusilə məşhur idi?",
  "Manna atları qonşu ölkələrdə də yüksək qiymətləndirilirdi.",
  ["Atçılıq", "Dəvəçilik", "Quşçuluq", "Arıçılıq"],
  1, None, 2),
 ("Mannada suvarma sistemləri nə üçün qurulurdu?",
  "Kanallar əkin sahələrini su ilə təmin edirdi.",
  ["Əkin sahələrini su ilə təmin etmək üçün",
   "Gəmiçilik üçün", "Balıqçılıq üçün",
   "Şəhərləri bəzəmək üçün"], 1, None, 2),
 ("Manna dövləti Azərbaycan tarixində hansı əhəmiyyəti daşıyır?",
  "Manna Azərbaycan ərazisində ilk güclü dövlət qurumudur.",
  ["İlk güclü dövlət qurumu kimi", "Son orta əsr dövləti kimi",
   "Yalnız şəhər dövləti kimi", "Əhəmiyyəti yoxdur"], 1, None, 2),
 ("Assuriya hökmdarları Mannaya yürüşləri zamanı nəyi ələ keçirirdilər?",
  "Yürüşlərdə qənimət və mal-qara aparılırdı.",
  ["Qənimət və mal-qara", "Kitabxanaları", "Gəmiləri",
   "Neft quyularını"], 1, None, 3),
],
"tarix-6-atropatena": [
 ("Atropat əvvəllər hansı imperiyanın canişini idi?",
  "Atropat Əhəmənilər imperiyasının Midiya canişini olmuşdu.",
  ["Əhəmənilərin", "Romanın", "Assuriyanın", "Osmanlının"],
  1, None, 2),
 ("Atropatena dövləti təxminən hansı dövrdə yaranmışdır?",
  "Dövlət e.ə. IV əsrin sonunda müstəqilləşdi.",
  ["E.ə. IV əsrin sonunda", "E.ə. XV əsrdə", "Eramızın V əsrində",
   "XVIII əsrdə"], 1, None, 2),
 ("Atropatenanın Fraaspa qalası hansı dövlətin hücumuna qarşı müdafiə olundu?",
  "Roma qoşunları Fraaspanı ala bilmədilər.",
  ["Romanın", "Misirin", "Hindistanın", "Çinin"], 1, None, 3),
 ("E.ə. 36-cı ildə Atropatenaya yürüş edən Roma sərkərdəsi kim idi?",
  "Mark Antoninin yürüşü uğursuzluqla nəticələndi.",
  ["Mark Antoni", "Yuli Sezar", "Pompey", "Neron"],
  1, None, 3),
 ("Atropatena ordusunun əsas zərbə qüvvəsini nə təşkil edirdi?",
  "Atropatena öz süvariləri ilə məşhur idi.",
  ["Süvarilər", "Fil qoşunu", "Donanma", "Muzdlular yalnız"],
  1, None, 2),
 ("Atropatena adı zaman keçdikcə hansı ada çevrilmişdir?",
  "Atropatena adı tədricən Azərbaycan adına çevrilmişdir.",
  ["Azərbaycan adına", "Albaniya adına", "Midiya adına",
   "Xəzər adına"], 1, None, 2),
 ("Atropatenada zərb olunan pullar nəyi göstərir?",
  "Pul zərbi ticarətin inkişafından xəbər verir.",
  ["Ticarətin inkişafını", "Yazının olmamasını",
   "Ordunun zəifliyini", "Əkinçiliyin tənəzzülünü"], 1, None, 3),
 ("Atropatena hansı beynəlxalq yolların üzərində yerləşirdi?",
  "Ölkədən Şərqlə Qərbi birləşdirən ticarət yolları keçirdi.",
  ["Şərqlə Qərbi birləşdirən yolların", "Dəniz yollarının yalnız",
   "Şimal buz yollarının", "Heç bir yolun"], 1, None, 3),
 ("Atropatenada atəşpərəstlərin baş məbədi harada yerləşirdi?",
  "Zərdüştiliyin əsas məbədi paytaxt Qazakada idi.",
  ["Qazakada", "Bakıda", "Təbrizdə", "Dərbənddə"], 1, None, 3),
 ("Zərdüştiliyin müqəddəs kitabı necə adlanır?",
  "Zərdüştilərin müqəddəs kitabı «Avesta»dır.",
  ["«Avesta»", "«Quran»", "«İncil»", "«Tövrat»"], 1, None, 2),
 ("Atropatena e.ə. I əsrdə hansı dövlətlə müttəfiq kimi Romaya qarşı vuruşurdu?",
  "Atropatena Parfiya ilə birlikdə Roma yürüşlərini dəf edirdi.",
  ["Parfiya ilə", "Misirlə", "Assuriya ilə", "Çinlə"],
  1, None, 3),
 ("Atropatenanın hərbi qüdrətini göstərən əsas fakt hansıdır?",
  "Güclü Roma ordusunun yürüşü dəf edilmişdi.",
  ["Roma yürüşünün dəf edilməsi", "Çinin fəthi",
   "Misirin tutulması", "Donanmanın yaradılması"], 1, None, 2),
 ("Atropatenanın oturaq əhalisi əsasən nə ilə məşğul olurdu?",
  "Münbit torpaqlarda əkinçilik və bağçılıq inkişaf etmişdi.",
  ["Əkinçilik və bağçılıqla", "Dənizçiliklə",
   "Ovçuluqla yalnız", "Mədənçiliklə yalnız"], 1, None, 2),
 ("Atropatenada sənətkarlığın hansı sahələri inkişaf etmişdi?",
  "Dulusçuluq və toxuculuq geniş yayılmışdı.",
  ["Dulusçuluq və toxuculuq", "Saatsazlıq", "Kitab çapı",
   "Şüşə istehsalı yalnız"], 1, None, 2),
 ("Atropatena III əsrdə hansı dövlətin tərkibinə qatıldı?",
  "Ölkə Sasani imperiyasının tərkibinə daxil edildi.",
  ["Sasanilərin", "Romanın", "Misirin", "Xəzərlərin"],
  1, None, 2),
 ("Atropatenanın təbii sərvətlərindən biri nə idi?",
  "Mənbələr ərazidə çıxan yanar mayedən - neftdən bəhs edir.",
  ["Neft (yanar maye)", "Almaz", "Uran", "Kömür yalnız"],
  1, None, 3),
 ("Atropatena cəmiyyətində yüksək təbəqəni kimlər təşkil edirdi?",
  "Əyanlar və kahinlər cəmiyyətin yuxarı təbəqəsi idi.",
  ["Əyanlar və kahinlər", "Qullar", "Sənətkarlar",
   "Çobanlar"], 1, None, 3),
 ("Atropatena haqqında məlumat verən antik müəllif kimdir?",
  "Yunan coğrafiyaşünası Strabon Atropatenanı təsvir etmişdir.",
  ["Strabon", "Nizami", "Firdovsi", "Homer yalnız"],
  1, None, 3),
 ("«Kiçik Midiya» adlanan ərazi hansı dövlətə uyğun gəlir?",
  "Antik müəlliflər Atropatenanı Kiçik Midiya da adlandırırdılar.",
  ["Atropatenaya", "Albaniyaya", "Mannaya", "Assuriyaya"],
  1, None, 3),
 ("Atropatena süvarilərinin əsas silahı nə idi?",
  "Süvarilər nizə və kamanla silahlanırdı.",
  ["Nizə və kaman", "Top", "Tüfəng", "Balta yalnız"],
  1, None, 2),
],
"tarix-6-albaniya": [
 ("Albaniya dövləti təxminən hansı dövrdə yaranmışdır?",
  "Albaniya e.ə. IV-III əsrlərdə formalaşmışdır.",
  ["E.ə. IV-III əsrlərdə", "XII əsrdə", "E.ə. XX əsrdə",
   "Eramızın X əsrində"], 1, None, 2),
 ("Albaniyanın paytaxtı V əsrdə hansı şəhərə köçürüldü?",
  "Paytaxt Qəbələdən Bərdəyə köçürüldü.",
  ["Bərdəyə", "Gəncəyə", "Şamaxıya", "Naxçıvana"],
  1, None, 2),
 ("E.ə. 66-65-ci illərdə Albaniyaya yürüş edən Roma sərkərdəsi kim idi?",
  "Pompeyin qoşunları Albaniyaya daxil olmuşdu.",
  ["Pompey", "Mark Antoni", "Sezar", "Oktavian"],
  1, None, 3),
 ("Roma yürüşləri zamanı alban qoşununa kim başçılıq edirdi?",
  "Alban hökmdarı Oris Pompeyə qarşı vuruşmuşdur.",
  ["Oris", "Atropat", "İranzu", "Cavanşir"], 1, None, 3),
 ("Albaniyada xristianlığı dövlət dini elan edən hökmdar kimdir?",
  "IV əsrdə hökmdar Urnayr xristianlığı qəbul etdi.",
  ["Urnayr", "Oris", "Babək", "Şah İsmayıl"], 1, None, 2),
 ("«Alban tarixi» əsərinin müəllifi kimdir?",
  "Musa Kalankatlı Albaniyanın tarixini qələmə almışdır.",
  ["Musa Kalankatlı", "Strabon", "Herodot", "Nizami"],
  1, None, 3),
 ("Albaniyanın ilk xristian məbədlərindən biri hansıdır?",
  "Amaras məbədi ilk kilsələrdən sayılır.",
  ["Amaras məbədi", "Atəşgah", "Möminə xatın", "Şirvanşahlar sarayı"],
  1, None, 3),
 ("Alban tayfa birliyinə daxil olan tayfalardan biri hansı idi?",
  "Utilər alban tayfa birliyinə daxil idi.",
  ["Utilər", "Franklar", "Slavyanlar", "Ərəblər"],
  1, None, 2),
 ("Albaniyada balıqçılığın inkişafı hansı təbii şəraitlə bağlı idi?",
  "Kür çayı və Xəzər dənizi balıqla zəngin idi.",
  ["Kür və Xəzərlə", "Səhraların çoxluğu ilə",
   "Dağların hündürlüyü ilə", "Meşələrlə"], 1, None, 2),
 ("Albaniyada IV əsrədək əhali nəyə sitayiş edirdi?",
  "Əhali Aya və Günəşə sitayiş edirdi.",
  ["Aya və Günəşə", "Yalnız oda", "Heykəllərə yalnız",
   "Heç nəyə"], 1, None, 2),
 ("Albaniya hansı iki böyük çayın hövzəsində yerləşirdi?",
  "Ölkənin əsas torpaqları Kür və Araz hövzəsində idi.",
  ["Kür və Araz", "Nil və Konqo", "Volqa və Don",
   "Dəclə və Fərat"], 1, None, 2),
 ("Sasanilər Albaniyanı idarə etmək üçün kimləri təyin edirdilər?",
  "Ölkəyə Sasani mərzbanları göndərilirdi.",
  ["Mərzbanları", "Konsulları", "Sultanları", "Xanları"],
  1, None, 3),
 ("Alban kilsəsi hansı statusa malik idi?",
  "Alban kilsəsi müstəqil (avtokefal) kilsə idi.",
  ["Müstəqil (avtokefal) kilsə idi", "Roma kilsəsinə tabe idi",
   "Fəaliyyət göstərmirdi", "Yalnız monastır idi"], 1, None, 3),
 ("Albaniyada ipəkçilik hansı bölgədə xüsusilə inkişaf etmişdi?",
  "Şəki-Qəbələ bölgəsi ipəkçiliyi ilə tanınırdı.",
  ["Şəki-Qəbələ bölgəsində", "Muğanda yalnız",
   "Abşeronda", "Naxçıvanda"], 1, None, 3),
 ("Qəbələ təxminən nə qədər müddət Albaniyanın paytaxtı olmuşdur?",
  "Qəbələ təqribən 600 il paytaxt olaraq qalmışdır.",
  ["Təxminən 600 il", "50 il", "10 il", "2000 il"],
  1, None, 3),
 ("Albaniya ərazisində geniş yayılmış qədim dəfn abidələri hansılardır?",
  "Arxeoloqlar çoxlu küp qəbirləri aşkar etmişlər.",
  ["Küp qəbirləri", "Ehramlar", "Mavzoleylər", "Kurqansız düzlər"],
  1, None, 3),
 ("Albaniyanın şimal sərhədlərini qorumaq üçün hansı istehkam sistemi vardı?",
  "Dərbənd səddi şimal hücumlarının qarşısını alırdı.",
  ["Dərbənd səddi", "Çin səddi", "Roma valı", "Bakı qalası"],
  1, None, 2),
 ("Albaniyada zərgərlik və şüşə məmulatları istehsalı nəyi göstərir?",
  "Bu tapıntılar sənətkarlığın yüksək inkişafını sübut edir.",
  ["Sənətkarlığın inkişafını", "Yazının olmamasını",
   "Ticarətin dayanmasını", "Əhalinin azlığını"], 1, None, 3),
 ("Alban yazısı hansı əsrdə yaradılmışdır?",
  "Alban əlifbası V əsrdə tərtib olunmuşdur.",
  ["V əsrdə", "XX əsrdə", "E.ə. X əsrdə", "XV əsrdə"],
  1, None, 2),
 ("Antik müəlliflər Albaniyanın təbiətini necə təsvir edirdilər?",
  "Mənbələr Albaniyanı münbit və məhsuldar ölkə kimi təsvir edir.",
  ["Münbit və məhsuldar ölkə kimi", "Səhra kimi",
   "Buzlaq kimi", "Yaşayışsız ada kimi"], 1, None, 3),
],
}
for _k, _v in YENI_TARIX.items():
    SUALLAR[_k] = _v



def yoxla():
    n = xeta = 0
    butun = set()
    movzu_fenn = {m: f for f, m, _r in MOVZULAR}
    for movzu, siyahi in SUALLAR.items():
        assert movzu in movzu_fenn, movzu
        if len(siyahi) != 20:
            print("XETA  %s: %d sual (20 olmalidir)" % (movzu, len(siyahi)))
            xeta += 1
        for body, why, opts, correct, expect, diff in siyahi:
            n += 1
            p = []
            if len(opts) != 4: p.append("variant sayi %d" % len(opts))
            if len(set(opts)) != len(opts): p.append("tekrar variant")
            if not (1 <= correct <= 4): p.append("correct")
            if not why: p.append("izah bos")
            if diff not in (1, 2, 3): p.append("cetinlik")
            if body in butun: p.append("eyni sual iki defe")
            butun.add(body)
            if expect is not None and opts[correct - 1] != expect:
                p.append("hesablanan «%s» != variant «%s»" % (expect, opts[correct - 1]))
            for t in [body, why] + opts:
                if "'" in t: p.append("apostrof var")
            if p:
                xeta += 1
                print("XETA  %s: %s\n      %s" % (movzu, body[:60], "; ".join(p)))
    hes = sum(1 for s in SUALLAR.values() for q in s if q[4] is not None)
    print("%d sual yoxlandı (%d-i hesabla təsdiqləndi), %d xəta" % (n, hes, xeta))
    return xeta == 0, n


def sql_yaz(n):
    q = lambda t: t.replace("'", "''")
    on = {"az-dili": "az6", "ingilis-dili": "ing6",
          "informatika": "inf6", "tarix": "tarix6"}
    setirler = []
    for fenn, movzu, rub in MOVZULAR:
        qisa = movzu.split("-", 2)[2]
        for i, (body, why, opts, correct, _e, diff) in enumerate(SUALLAR[movzu], 1):
            setirler.append(
                "('%s-%s#%d','%s','%s',%d,%d,'%s','%s',array['%s','%s','%s','%s'],%d)"
                % (on[fenn], qisa, i, fenn, movzu, diff, rub, q(body), q(why),
                   q(opts[0]), q(opts[1]), q(opts[2]), q(opts[3]), correct))
    with io.open(CIXIS, "w", encoding="utf-8") as f:
        f.write("""-- =====================================================================
--  31_bank_sinif6.sql : 6-CI SINIF - AZ DILI, INGILIS DILI,
--                       INFORMATIKA, AZERBAYCAN TARIXI
--
--  BU FAYL ELLE YAZILMIR - tools/sinif6.py yaradir:
--      python3 tools/sinif6.py
--
--  Az dili 8 + Ingilis dili 8 + Informatika 5 + Tarix 3
--  = 27 movzu x 20 = %d.  ext_key: az6-/ing6-/inf6-/tarix6-...
--  ON SERT: 29_movzular_orta6.sql islenmis olmalidir.
--  SONRA:   05_grants.sql yeniden islet.
-- =====================================================================

do $$
begin
  if not exists (select 1 from public.topics t join public.subjects s
      on s.id = t.subject_id
     where (s.slug, t.slug) in (('az-dili','az-6-fonetika'),
                                ('ingilis-dili','ing-6-town'),
                                ('informatika','inf-6-internet'),
                                ('tarix','tarix-6-ibtidai'))
     having count(*) = 4) then
    raise exception 'ONCE 29_movzular_orta6.sql isledilmelidir.';
  end if;
end $$;

delete from public.question_options o
 using public.questions q
 where o.question_id = q.id
   and q.owner_type = 'platform'
   and (q.ext_key like 'az6-%%' or q.ext_key like 'ing6-%%'
        or q.ext_key like 'inf6-%%' or q.ext_key like 'tarix6-%%');

with d(ext, fenn, topic, diff, rub, body, why, opts, correct) as (values
%s
),
ins as (
  insert into public.questions
    (ext_key, owner_type, subject_id, level_id, topic_id, kind,
     body, explanation, difficulty, quarter, status)
  select d.ext, 'platform', s.id, l.id, tp.id, 'single',
         d.body, d.why, d.diff, d.rub, 'published'
    from d
    join public.subjects s on s.slug = d.fenn
    join public.programs p on p.slug = 'orta'
    join public.levels   l on l.program_id = p.id and l.code = '6'
    join public.topics   tp on tp.subject_id = s.id and tp.slug = d.topic
  on conflict (ext_key) do update
    set body = excluded.body, explanation = excluded.explanation,
        difficulty = excluded.difficulty, quarter = excluded.quarter,
        topic_id = excluded.topic_id, level_id = excluded.level_id,
        subject_id = excluded.subject_id, status = 'published'
  returning id, ext_key
)
insert into public.question_options (question_id, ord, body, is_correct)
select ins.id, o.ord, o.txt, o.ord = d.correct
  from ins
  join d on d.ext = ins.ext_key,
  lateral unnest(d.opts) with ordinality as o(txt, ord);

do $$
declare n int; k int;
begin
  select count(*) into n from public.questions
   where owner_type = 'platform'
     and (ext_key like 'az6-%%' or ext_key like 'ing6-%%'
          or ext_key like 'inf6-%%' or ext_key like 'tarix6-%%');
  if n <> %d then
    raise exception 'sinif6 suallari: %d gozlenilirdi, %% tapildi', n;
  end if;
  select count(*) into k from public.questions q
   where (q.ext_key like 'az6-%%' or q.ext_key like 'ing6-%%'
          or q.ext_key like 'inf6-%%' or q.ext_key like 'tarix6-%%')
     and ((select count(*) from public.question_options o
            where o.question_id = q.id) <> 4
       or (select count(*) from public.question_options o
            where o.question_id = q.id and o.is_correct) <> 1);
  if k > 0 then
    raise exception '%% sualda variant qurulusu sehvdir', k;
  end if;
  select count(distinct topic_id) into k from public.questions
   where ext_key like 'az6-%%' or ext_key like 'ing6-%%'
      or ext_key like 'inf6-%%' or ext_key like 'tarix6-%%';
  if k <> 27 then
    raise exception 'movzu sayi 27 deyil: %%', k;
  end if;
  raise notice '6-ci sinif banki: %% sual, 27 movzu (az, ing, inf, tarix).', n;
end $$;
""" % (n, ",\n".join(setirler), n, n))
    print("yazildi: %s" % CIXIS)


if __name__ == "__main__":
    ok, n = yoxla()
    if not ok:
        raise SystemExit(1)
    sql_yaz(n)
