#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
5-ci sinfin qalan fennleri -> db/27_bank_sinif5.sql

    Azerbaycan dili 5      8 movzu x 10 =  80
    Ingilis dili 5         8 movzu x 10 =  80
    Informatika 5          5 movzu x 10 =  50
    Azerbaycan tarixi 5    5 movzu x 10 =  50
                                    cemi  260

tools/sinif3.py qelibi ile.  Movzular 25_movzular_orta5.sql agacina
uygundur.  Ingilis dili suallari sade A1 seviyyesindedir; apostrof
qadagan oldugu ucun "cannot", "The mother of my mother" kimi formalar
islenib.  Tarix suallari yalniz derslik seviyyeli, subhesiz faktlardir.

DIQQET: movcud bank fayllarinin (db/07, 16, 17, 19, 20, 23, 24) cumle
qelibleri tekrarlanmayib - generator pg_trgm ile >= 0.95 oxsarligi
tekrar sayir.

Isletmek:
    python3 tools/sinif5.py
"""
import io
import os
import string

KOK = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CIXIS = os.path.join(KOK, "db", "27_bank_sinif5.sql")

QALIN = set("aıou")
INCE = set("əeiöü")


def aheng_pozan(sozler):
    """Qalin ve ince saitleri qarisiq islenen (aheng qanununa tabe
    olmayan) sozleri qaytarir."""
    netice = []
    for w in sozler:
        saitler = [h for h in w.lower() if h in QALIN | INCE]
        if any(h in QALIN for h in saitler) and any(h in INCE for h in saitler):
            netice.append(w)
    return netice


def qosa_samitli(sozler):
    return [w for w in sozler
            if any(w[i] == w[i + 1] for i in range(len(w) - 1))]


#  (fenn, movzu-slug, rub)
MOVZULAR = [
    ("az-dili", "az-5-fonetika",       1),
    ("az-dili", "az-5-soz-menasi",     1),
    ("az-dili", "az-5-soz-qurulusu",   2),
    ("az-dili", "az-5-luget",          2),
    ("az-dili", "az-5-isim",           3),
    ("az-dili", "az-5-sifet-say-feil", 3),
    ("az-dili", "az-5-evezlik-tesrif", 4),
    ("az-dili", "az-5-cumle",          4),
    ("ingilis-dili", "ing-5-who-am-i",   1),
    ("ingilis-dili", "ing-5-everywhere", 1),
    ("ingilis-dili", "ing-5-home",       2),
    ("ingilis-dili", "ing-5-family",     2),
    ("ingilis-dili", "ing-5-daily-life", 3),
    ("ingilis-dili", "ing-5-school",     3),
    ("ingilis-dili", "ing-5-clothes",    4),
    ("ingilis-dili", "ing-5-movement",   4),
    ("informatika", "inf-5-informasiya", 1),
    ("informatika", "inf-5-kompyuter",   2),
    ("informatika", "inf-5-tetbiqi",     3),
    ("informatika", "inf-5-alqoritm",    4),
    ("informatika", "inf-5-internet",    4),
    ("tarix", "tarix-5-qedim",      1),
    ("tarix", "tarix-5-dovletler",  2),
    ("tarix", "tarix-5-qalalar",    3),
    ("tarix", "tarix-5-respublika", 3),
    ("tarix", "tarix-5-medeniyyet", 4),
]

SUALLAR = {
# ===================== AZERBAYCAN DILI 5 ==============================
"az-5-fonetika": [
 ("Söz sonunda «b» hərfi ilə yazılan samit necə tələffüz olunur?",
  "Söz sonunda cingiltili «b» kar qarşılığı «p» kimi deyilir: "
  "kitab — [kitap].",
  ["«p» kimi", "«b» kimi", "«m» kimi", "Tələffüz olunmur"],
  1, None, 2),
 ("«Qonaq» sözünün sonundakı «q» səsi tələffüzdə necə deyilir?",
  "Çoxhecalı sözlərin sonunda «q» səsi [x] kimi deyilir: [qonax].",
  ["«x» kimi", "«q» kimi", "«k» kimi", "«ğ» kimi"], 1, None, 2),
 ("«Dovşan» sözündə «ov» birləşməsi necə tələffüz olunur?",
  "«Ov» birləşməsi uzun [o:] kimi deyilir: [do:şan].",
  ["Uzun «o» kimi", "Yazıldığı kimi", "«av» kimi", "«uv» kimi"],
  1, None, 3),
 ("«Palıd» sözünün sonunda hansı səs tələffüz olunur?",
  "Söz sonunda cingiltili «d» kar [t] kimi deyilir: [palıt].",
  ["[t]", "[d]", "[z]", "[c]"], 1, None, 2),
 ("Hecanı yaradan səslər hansılardır?",
  "Sözdə neçə sait varsa, o qədər heca var — hecanı sait yaradır.",
  ["Saitlər", "Samitlər", "Kar samitlər", "Cingiltili samitlər"],
  1, None, 1),
 ("Hansı sözdə qoşa samit yazılır?",
  "«Səkkiz» sözü qoşa «k» ilə yazılır.",
  ["səkkiz", "dəniz", "qələm", "kitab"], 1,
  qosa_samitli(["səkkiz", "dəniz", "qələm", "kitab"])[0], 2),
 ("«Çörək» sözünə «-i» şəkilçisi artıranda söz necə yazılır?",
  "Saitlə başlanan şəkilçi artırılanda söz sonundakı «k» «y» ilə "
  "əvəz olunur: çörəyi.",
  ["çörəyi", "çörəki", "çörəgi", "çörəqi"], 1, None, 2),
 ("«Papaq» sözünə mənsubiyyət şəkilçisi artıranda hansı yazılış "
  "düzgündür?",
  "Saitlə başlanan şəkilçidə söz sonundakı «q» «ğ» ilə əvəz olunur: "
  "papağı.",
  ["papağı", "papaqı", "papakı", "papaxı"], 1, None, 2),
 ("Hansı sözün deyilişi ilə yazılışı fərqlənir?",
  "«Qonaq» [qonax] kimi deyilir; su, ana, gül yazıldığı kimi deyilir.",
  ["qonaq", "su", "ana", "gül"], 1, None, 3),
 ("Hansı sözdə sait uzun tələffüz olunur?",
  "Bəzi alınma sözlərdə sait uzun deyilir: [a:lim].",
  ["alim", "salam", "qapı", "dəniz"], 1, None, 3),
],
"az-5-soz-menasi": [
 ("Sözün leksik mənası nədir?",
  "Leksik məna sözün bildirdiyi əsas mənadır.",
  ["Sözün bildirdiyi əsas məna", "Sözün şəkilçisi",
   "Sözün heca sayı", "Sözün yazılışı"], 1, None, 2),
 ("«Dəmir iradə» birləşməsində «dəmir» sözü hansı mənadadır?",
  "İradə metaldan ola bilməz — söz məcazi mənadadır (möhkəm).",
  ["Məcazi", "Həqiqi", "Heç bir mənada", "Say mənasında"],
  1, None, 2),
 ("Hansı birləşmədə «şirin» sözü məcazi mənada işlənib?",
  "Söhbətin dadı olmur — «şirin söhbət» məcazidir.",
  ["şirin söhbət", "şirin çay", "şirin alma", "şirin konfet"],
  1, None, 2),
 ("Omonimlər necə sözlərdir?",
  "Omonimlər deyilişi eyni, mənaları tamam fərqli sözlərdir.",
  ["Deyilişi eyni, mənaları fərqli", "Mənaca yaxın",
   "Əks mənalı", "Eyni mənalı"], 1, None, 2),
 ("«Yaz» sözünün omonimliyi hansı cütlükdə görünür?",
  "«Yaz» həm fəsil adı, həm də yazmaq feilinin əmr formasıdır.",
  ["Fəsil adı və yazmaq əmri", "Fəsil adı və ay adı",
   "İki fəsil adı", "İki feil forması"], 1, None, 3),
 ("Çoxmənalı söz hansıdır?",
  "«Dil» — insan orqanı, danışıq dili, açar dili və s.",
  ["dil", "stol", "dəftər", "pəncərə"], 1, None, 2),
 ("Hansı birləşmədə «qızıl» sözü HƏQİQİ mənada işlənib?",
  "«Qızıl üzük» doğrudan qızıldan hazırlanır.",
  ["qızıl üzük", "qızıl payız", "qızıl əllər", "qızıl söz"],
  1, None, 2),
 ("Qrammatik məna sözə nə ilə verilir?",
  "Qrammatik məna şəkilçilərlə (cəm, hal, şəxs) yaranır.",
  ["Şəkilçilərlə", "Vurğu ilə", "Hərflərin sayı ilə",
   "Sözün kökü ilə"], 1, None, 3),
 ("Omonim cütü seçin.",
  "«Bal» — şirin qida və «bal» — qiymət balı.",
  ["bal (qida) — bal (qiymət)", "gözəl — qəşəng",
   "isti — soyuq", "ev — bina"], 1, None, 2),
 ("Məcazi məna nitqdə əsasən nəyə xidmət edir?",
  "Məcazlar nitqi obrazlı və təsirli edir.",
  ["Obrazlılığa və təsirliliyə", "Sözü qısaltmağa",
   "Yazını çətinləşdirməyə", "Heç nəyə"], 1, None, 2),
],
"az-5-soz-qurulusu": [
 ("Sözün dəyişməyən əsas hissəsi necə adlanır?",
  "Sözün əsas hissəsi kökdür, şəkilçilər ona artırılır.",
  ["Kök", "Şəkilçi", "Heca", "Sait"], 1, None, 1),
 ("«Kitabça» sözündə «-ça» hansı şəkilçidir?",
  "«-ça» yeni söz yaradır — leksik şəkilçidir.",
  ["Leksik", "Qrammatik", "Cəm", "Hal"], 1, None, 3),
 ("«Məktəblər» sözündə «-lər» hansı şəkilçidir?",
  "«-lər» yalnız cəmlik bildirir — qrammatik şəkilçidir.",
  ["Qrammatik", "Leksik", "Söz yaradan", "Kök"], 1, None, 3),
 ("Ahəng qanunu nədir?",
  "Sözdə qalın saitdən sonra qalın, incədən sonra incə sait gəlir.",
  ["Saitlərin bir-birini izləmə qaydası", "Samitlərin düzülüşü",
   "Cümlə qaydası", "Durğu işarəsi qaydası"], 1, None, 2),
 ("Hansı söz ahəng qanununa tabe DEYİL?",
  "«İşıq» sözündə incə «i» ilə qalın «ı» yanaşı gəlir.",
  ["işıq", "dəniz", "yarpaq", "ördək"], 1,
  aheng_pozan(["işıq", "dəniz", "yarpaq", "ördək"])[0], 3),
 ("Quruluşuna görə sadə söz hansıdır?",
  "«Dağ» yalnız kökdən ibarətdir.",
  ["dağ", "dağlıq", "dəmiryol", "gözlük"], 1, None, 2),
 ("Düzəltmə söz hansıdır?",
  "«Duzlu» = duz + leksik şəkilçi «-lu».",
  ["duzlu", "duz", "günəbaxan", "yol"], 1, None, 2),
 ("Mürəkkəb söz hansıdır?",
  "«Günəbaxan» iki kökün birləşməsindən yaranıb.",
  ["günəbaxan", "baxan", "günlük", "baxış"], 1, None, 2),
 ("İki cür yazılan şəkilçi hansıdır?",
  "«-lar, -lər» iki cür yazılan şəkilçidir; «-lıq, -lik, -luq, -lük» "
  "dörd cürdür.",
  ["-lar, -lər", "-lıq, -lik, -luq, -lük", "-çı, -çi, -çu, -çü",
   "-sız, -siz, -suz, -süz"], 1, None, 3),
 ("«Dənizçi» sözünün kökü hansıdır?",
  "«-çi» şəkilçisini atsaq, kök «dəniz» qalar.",
  ["dəniz", "dənizçi", "çi", "də"], 1, None, 1),
],
"az-5-luget": [
 ("Sinonimlər necə sözlərdir?",
  "Sinonimlər yazılışı fərqli, mənaca yaxın sözlərdir.",
  ["Mənaca yaxın", "Əks mənalı", "Deyilişi eyni",
   "Mənasız"], 1, None, 1),
 ("«Gözəl» sözünün sinonimi hansıdır?",
  "Gözəl — qəşəng — göyçək mənaca yaxındır.",
  ["qəşəng", "çirkin", "böyük", "gedir"], 1, None, 1),
 ("«Dost» sözünün antonimi hansıdır?",
  "Dostun əksi düşməndir.",
  ["düşmən", "yoldaş", "qonşu", "qohum"], 1, None, 1),
 ("Hansı cüt antonimdir?",
  "Xeyir və şər əks mənalı sözlərdir.",
  ["xeyir — şər", "igid — cəsur", "ev — otaq", "yol — cığır"],
  1, None, 2),
 ("Alınma sözlər hansılardır?",
  "Başqa dillərdən dilimizə keçən sözlər alınma sözlərdir.",
  ["Başqa dillərdən keçən sözlər", "Ən qədim sözlər",
   "Uydurma sözlər", "Yalnız adlar"], 1, None, 2),
 ("Hansı söz alınma sözdür?",
  "«Kompüter» ingilis dilindən keçib.",
  ["kompüter", "su", "daş", "əl"], 1, None, 2),
 ("Sözlərin mənasını öyrənmək üçün hansı lüğətdən istifadə olunur?",
  "Sözlərin mənasını izahlı lüğət açıqlayır.",
  ["İzahlı lüğətdən", "Telefon kitabçasından",
   "Riyaziyyat cədvəlindən", "Xəritədən"], 1, None, 2),
 ("Lüğətdə sözlər hansı qaydada düzülür?",
  "Lüğətlərdə sözlər əlifba sırası ilə verilir.",
  ["Əlifba sırası ilə", "Uzunluğuna görə", "Mənasına görə",
   "Təsadüfi"], 1, None, 1),
 ("«Cəsur» sözünə mənaca yaxın söz hansıdır?",
  "Cəsur — igid — qoçaq sinonimlərdir.",
  ["igid", "qorxaq", "yavaş", "zəif"], 1, None, 2),
 ("Orfoqrafiya lüğəti nəyi göstərir?",
  "Orfoqrafiya lüğəti sözlərin düzgün yazılışını verir.",
  ["Sözlərin düzgün yazılışını", "Sözlərin mənasını",
   "Şəhərlərin adlarını", "Ədədlərin cədvəlini"], 1, None, 2),
],
"az-5-isim": [
 ("Nitq hissələri hansı qruplara bölünür?",
  "Nitq hissələri əsas və köməkçi olmaqla iki qrupdur.",
  ["Əsas və köməkçi", "Uzun və qısa", "Asan və çətin",
   "Birinci və ikinci"], 1, None, 2),
 ("Canlı və cansız varlıqların adını bildirən əsas nitq hissəsi "
  "hansıdır?",
  "Varlıqların adını isim bildirir.",
  ["İsim", "Sifət", "Feil", "Zərf"], 1, None, 1),
 ("Toplu isim hansıdır?",
  "«El» təklikdə çoxluq (insanlar toplusu) bildirir.",
  ["el", "kitablar", "ağac", "qələm"], 1, None, 3),
 ("«Kitabım» sözündə «-ım» şəkilçisi nəyi bildirir?",
  "«-ım» I şəxsə aidliyi — mənsubiyyəti bildirir.",
  ["Mənsubiyyəti", "Cəmliyi", "Zamanı", "İnkarlığı"], 1, None, 2),
 ("«Məktəbimiz» sözü neçənci şəxsin mənsubiyyətini bildirir?",
  "«-imiz» I şəxsin cəmini bildirir: bizim məktəb.",
  ["I şəxsin cəmini", "II şəxsin təkini", "III şəxsin cəmini",
   "Heç bir şəxsi"], 1, None, 3),
 ("«Xəzər, Nizami, Şuşa» isimlərinin ortaq cəhəti nədir?",
  "Üçü də xüsusi isimdir və böyük hərflə yazılır.",
  ["Hamısı xüsusi isimdir", "Hamısı ümumi isimdir",
   "Hamısı toplu isimdir", "Hamısı cəmdədir"], 1, None, 2),
 ("«Atası» sözündə mənsubiyyət hansı şəxsə aiddir?",
  "«-sı» III şəxsin təkini bildirir: onun atası.",
  ["III şəxsə", "I şəxsə", "II şəxsə", "Heç bir şəxsə"],
  1, None, 3),
 ("Ümumi isim hansıdır?",
  "«Şəhər» eyni cinsli əşyaların ümumi adıdır.",
  ["şəhər", "Bakı", "Gəncə", "Şuşa"], 1, None, 2),
 ("«Sürü» sözü hansı isim növüdür?",
  "«Sürü» təklikdə çoxluq bildirir — toplu isimdir.",
  ["Toplu isim", "Xüsusi isim", "Cəm isim", "Feil"], 1, None, 2),
 ("İsim cümlədə ən çox hansı üzv olur?",
  "İsim əşya bildirdiyi üçün ən çox mübtəda olur.",
  ["Mübtəda", "Xəbər olmur", "Yalnız təyin", "Üzv olmur"],
  1, None, 3),
],
"az-5-sifet-say-feil": [
 ("Əşyanın əlamətini bildirən əsas nitq hissəsi hansıdır?",
  "Əlaməti sifət bildirir.",
  ["Sifət", "İsim", "Say", "Zərf"], 1, None, 1),
 ("Miqdar və sıra bildirən nitq hissəsi necə adlanır?",
  "Miqdar və sıranı say bildirir.",
  ["Say", "Sifət", "Feil", "Əvəzlik"], 1, None, 1),
 ("«Beşinci» sözü hansı say növüdür?",
  "«-inci» şəkilçisi sıra bildirir.",
  ["Sıra sayı", "Miqdar sayı", "Kəsr sayı", "Say deyil"],
  1, None, 2),
 ("Hansı söz miqdar sayıdır?",
  "«On» miqdar bildirir; onuncu, birinci, sonuncu — sıra bildirir.",
  ["on", "onuncu", "birinci", "sonuncu"], 1, None, 2),
 ("Hərəkət bildirən əsas nitq hissəsi hansıdır?",
  "Hərəkəti feil bildirir.",
  ["Feil", "İsim", "Sifət", "Say"], 1, None, 1),
 ("«Sabah» sözü hansı nitq hissəsidir?",
  "«Sabah» hərəkətin zamanını bildirir — zərfdir.",
  ["Zərf", "İsim", "Sifət", "Say"], 1, None, 3),
 ("Zərf nəyi bildirir?",
  "Zərf hərəkətin tərzini, yerini, zamanını bildirir.",
  ["Hərəkətin tərzini, yerini, zamanını", "Əşyanın adını",
   "Əşyanın sayını", "Əşyanın sahibini"], 1, None, 2),
 ("«Tez» sözü hərəkətin nəyini bildirir?",
  "«Tez qaçdı» — hərəkətin tərzini bildirir.",
  ["Tərzini", "Yerini", "Səbəbini", "Sahibini"], 1, None, 2),
 ("«Danışdı» feili hansı zamandadır?",
  "«-dı» şəkilçisi keçmiş zaman bildirir.",
  ["Keçmiş", "İndiki", "Gələcək", "Zaman bildirmir"], 1, None, 2),
 ("Gələcək zaman şəkilçisi hansıdır?",
  "Gələcək zaman «-acaq, -əcək» ilə düzəlir.",
  ["-acaq, -əcək", "-dı, -di", "-ır, -ir", "-mış, -miş"],
  1, None, 2),
],
"az-5-evezlik-tesrif": [
 ("Məsdər hansı şəkilçi ilə düzəlir?",
  "Məsdər «-maq, -mək» şəkilçisi ilə düzəlir.",
  ["-maq, -mək", "-lar, -lər", "-çı, -çi", "-dı, -di"],
  1, None, 2),
 ("«Oxumaq» sözü feilin hansı formasıdır?",
  "«-maq» şəkilçili forma məsdərdir.",
  ["Məsdər", "Feili sifət", "Feili bağlama", "Əmr forması"],
  1, None, 2),
 ("Əvəzlik nəyi əvəz edir?",
  "Əvəzlik ismi, sifəti, sayı əvəz edir.",
  ["İsmi, sifəti, sayı", "Yalnız feili", "Durğu işarələrini",
   "Şəkilçiləri"], 1, None, 2),
 ("«Mən, sən, o» hansı əvəzliklərdir?",
  "Bunlar şəxs əvəzlikləridir.",
  ["Şəxs əvəzlikləri", "İşarə əvəzlikləri", "Sual əvəzlikləri",
   "Qeyri-müəyyən əvəzliklər"], 1, None, 1),
 ("«Bu, o, həmin» əvəzlikləri hansı növdəndir?",
  "Bunlar işarə əvəzlikləridir.",
  ["İşarə", "Şəxs", "Sual", "İnkar"], 1, None, 2),
 ("«Kim?, nə?» əvəzlikləri hansı növə aiddir?",
  "Sual bildirən əvəzliklər sual əvəzlikləridir.",
  ["Sual", "Şəxs", "İşarə", "Təyin"], 1, None, 2),
 ("Feili sifət nəyi bildirir?",
  "Feili sifət hərəkətlə bağlı əlaməti bildirir.",
  ["Hərəkətlə bağlı əlaməti", "Yalnız zamanı",
   "Əşyanın sayını", "Sözün kökünü"], 1, None, 3),
 ("«Yazılmış məktub» birləşməsində «yazılmış» sözü nədir?",
  "Hərəkətdən yaranan əlamət — feili sifətdir.",
  ["Feili sifət", "Məsdər", "Sifət deyil, isim", "Zərf"],
  1, None, 3),
 ("Feili bağlama hansı şəkilçilərlə düzəlir?",
  "Feili bağlama «-ıb, -ib, -ub, -üb», «-araq, -ərək» ilə düzəlir.",
  ["-ıb, -ib, -araq, -ərək", "-maq, -mək", "-lar, -lər",
   "-lıq, -lik"], 1, None, 3),
 ("Təsriflənməyən feil formaları hansılardır?",
  "Məsdər, feili sifət və feili bağlama şəxsə görə dəyişmir.",
  ["Məsdər, feili sifət, feili bağlama", "Keçmiş, indiki, gələcək",
   "Tək və cəm", "Əmr və xəbər"], 1, None, 3),
],
"az-5-cumle": [
 ("Söz birləşməsi nədir?",
  "İki və daha artıq müstəqil sözün məna və qrammatik bağlılığıdır.",
  ["İki və artıq sözün məna bağlılığı", "Bir sözün təkrarı",
   "Hərflərin yığını", "Şəkilçilər toplusu"], 1, None, 2),
 ("Frazeoloji birləşmə hansıdır?",
  "«Ağzını açmamaq» — susmaq mənasında sabit birləşmədir.",
  ["ağzını açmamaq", "qapını açmaq", "kitabı açmaq",
   "pəncərəni açmaq"], 1, None, 3),
 ("«Dabanına tüpürmək» frazeologizmi nə deməkdir?",
  "Bu ifadə «sürətlə qaçmaq» mənasında işlənir.",
  ["Sürətlə qaçmaq", "Yavaş getmək", "Ayaqqabı geyinmək",
   "Dayanmaq"], 1, None, 3),
 ("Mübtəda hansı suallara cavab verir?",
  "Mübtəda «kim? nə?» suallarına cavab verir.",
  ["Kim? Nə?", "Necə?", "Nə vaxt?", "Harada?"], 1, None, 2),
 ("Xəbər cümlədə nəyi bildirir?",
  "Xəbər mübtəda haqqında məlumatı (hökmü) bildirir.",
  ["Mübtəda haqqında məlumatı", "Yalnız zamanı",
   "Sözün mənasını", "Durğu işarəsini"], 1, None, 2),
 ("Sadə cümlədə neçə qrammatik əsas olur?",
  "Sadə cümlənin bir qrammatik əsası olur.",
  ["1", "2", "3", "Heç biri"], 1, None, 2),
 ("Mürəkkəb cümlə necə yaranır?",
  "İki və daha artıq sadə cümlənin birləşməsindən yaranır.",
  ["Sadə cümlələrin birləşməsindən", "Bir sözdən",
   "Yalnız suallardan", "Şəkilçilərdən"], 1, None, 2),
 ("«Yağış yağdı və hava sərinləşdi» cümləsi hansı növdür?",
  "İki qrammatik əsas var — mürəkkəb cümlədir.",
  ["Mürəkkəb", "Sadə", "Söz birləşməsi", "Cümlə deyil"],
  1, None, 3),
 ("Cümlənin ikinci dərəcəli üzvləri hansılardır?",
  "Tamamlıq, təyin və zərflik ikinci dərəcəli üzvlərdir.",
  ["Tamamlıq, təyin, zərflik", "Mübtəda və xəbər",
   "İsim və feil", "Sait və samit"], 1, None, 3),
 ("«Maraqlı kitab» birləşməsində əsas tərəf hansıdır?",
  "Birləşmənin əsas (ikinci) tərəfi «kitab» sözüdür.",
  ["kitab", "maraqlı", "hər ikisi", "heç biri"], 1, None, 3),
],
# ====================== INGILIS DILI 5 ================================
"ing-5-who-am-i": [
 ("Choose the correct sentence.",
  "Düzgün forma: My name is Aysel.",
  ["My name is Aysel.", "My name are Aysel.",
   "Me name is Aysel.", "My names is Aysel."], 1, None, 1),
 ("How old ___ you?",
  "«You» ilə «are» işlənir: How old are you?",
  ["are", "is", "am", "be"], 1, None, 1),
 ("I ___ from Azerbaijan.",
  "«I» ilə «am» işlənir: I am from Azerbaijan.",
  ["am", "is", "are", "not"], 1, None, 1),
 ("Which word is a country?",
  "Italy ölkə adıdır, qalanları dil və millət adlarıdır.",
  ["Italy", "Italian", "English", "French"], 1, None, 2),
 ("What do we say when we meet someone?",
  "Görüşəndə «Hello» deyilir.",
  ["Hello", "Goodbye", "Good night", "Thanks"], 1, None, 1),
 ("«Eleven» sözü hansı ədədi bildirir?",
  "Eleven — 11 deməkdir.",
  ["11", "12", "7", "10"], 1, str(11), 1),
 ("What is the plural of «book»?",
  "Cəm forma «-s» ilə düzəlir: books.",
  ["books", "bookes", "bookies", "book"], 1, "book" + "s", 2),
 ("___ is your name?",
  "Ad soruşanda «What» işlənir.",
  ["What", "Who", "Where", "When"], 1, None, 1),
 ("«Teacher» sözünün mənası nədir?",
  "Teacher — müəllim deməkdir.",
  ["Müəllim", "Şagird", "Həkim", "Sürücü"], 1, None, 1),
 ("Which word means «şagird»?",
  "Şagird — student (pupil).",
  ["student", "doctor", "driver", "singer"], 1, None, 1),
],
"ing-5-everywhere": [
 ("How many letters are there in the English alphabet?",
  "İngilis əlifbasında 26 hərf var.",
  ["26", "32", "24", "30"], 1, str(len(string.ascii_lowercase)), 2),
 ("Which letter comes after «P»?",
  "Əlifbada P-dən sonra Q gəlir.",
  ["Q", "R", "O", "S"], 1, chr(ord("P") + 1), 2),
 ("Choose the correct spelling.",
  "Düzgün yazılış: window.",
  ["window", "windou", "vindow", "wındow"], 1, None, 2),
 ("People speak English in ___.",
  "İngilis dili Böyük Britaniya və ABŞ-da əsas dildir.",
  ["the UK and the USA", "only Azerbaijan", "no country",
   "only space"], 1, None, 2),
 ("When do we say «Good morning»?",
  "«Good morning» səhər deyilir.",
  ["In the morning", "At night", "In the evening",
   "After lunch"], 1, None, 1),
 ("What is «qapı» in English?",
  "Qapı — door.",
  ["door", "window", "wall", "floor"], 1, None, 1),
 ("Find the number «ten».",
  "Ten — 10 deməkdir.",
  ["10", "5", "2", "100"], 1, str(10), 1),
 ("Which word means «kitabxana»?",
  "Library — kitabxana deməkdir.",
  ["library", "hospital", "market", "garden"], 1, None, 2),
 ("How do you spell the word for «pişik»?",
  "Pişik — cat: c-a-t.",
  ["c-a-t", "k-a-t", "c-e-t", "s-a-t"], 1, None, 1),
 ("What do we answer to «Thank you»?",
  "Təşəkkürə «You are welcome» cavabı verilir.",
  ["You are welcome.", "Good night.", "How are you?",
   "It is a book."], 1, None, 2),
],
"ing-5-home": [
 ("There ___ a sofa in the living room.",
  "Təkdə «there is» işlənir.",
  ["is", "are", "am", "have"], 1, None, 2),
 ("There ___ two beds in the room.",
  "Cəmdə «there are» işlənir.",
  ["are", "is", "am", "be"], 1, None, 2),
 ("We cook food in the ___.",
  "Yemək mətbəxdə (kitchen) bişirilir.",
  ["kitchen", "bedroom", "bathroom", "garage"], 1, None, 1),
 ("We sleep in the ___.",
  "Yataq otağı — bedroom.",
  ["bedroom", "kitchen", "garden", "hall"], 1, None, 1),
 ("Which word means «altında»?",
  "Under — altında deməkdir.",
  ["under", "on", "in", "next to"], 1, None, 2),
 ("«Bathroom» sözünün mənası nədir?",
  "Bathroom — hamam otağı.",
  ["Hamam otağı", "Qonaq otağı", "Yataq otağı", "Mətbəx"],
  1, None, 1),
 ("Choose the word for «divar».",
  "Divar — wall.",
  ["wall", "roof", "door", "floor"], 1, None, 2),
 ("«On» sözü hansı mənanı bildirir?",
  "On — üstündə deməkdir.",
  ["Üstündə", "Altında", "İçində", "Yanında"], 1, None, 2),
 ("Choose the short answer: Is there a garden?",
  "Qısa cavab: Yes, there is.",
  ["Yes, there is.", "Yes, there are.", "Yes, it does.",
   "No, he is not."], 1, None, 2),
 ("Which room has a TV and a sofa?",
  "Televizor və divan qonaq otağında olur.",
  ["living room", "bathroom", "kitchen", "garage"], 1, None, 2),
],
"ing-5-family": [
 ("My mother and my father are my ___.",
  "Ana və ata birlikdə — parents.",
  ["parents", "brothers", "sisters", "friends"], 1, None, 1),
 ("The mother of my mother is my ___.",
  "Ananın anası — grandmother (nənə).",
  ["grandmother", "aunt", "sister", "daughter"], 1, None, 2),
 ("«Qardaş» sözünün ingiliscə qarşılığı hansıdır?",
  "Qardaş — brother.",
  ["brother", "sister", "father", "uncle"], 1, None, 1),
 ("The brother of my father is my ___.",
  "Atanın qardaşı — uncle (əmi).",
  ["uncle", "cousin", "grandfather", "nephew"], 1, None, 2),
 ("«Sister» sözünün mənası nədir?",
  "Sister — bacı deməkdir.",
  ["Bacı", "Qardaş", "Ana", "Nənə"], 1, None, 1),
 ("Have you got a sister? — Yes, I ___.",
  "Qısa cavab: Yes, I have.",
  ["have", "am", "is", "does"], 1, None, 2),
 ("This is my brother. ___ name is Tural.",
  "Oğlan üçün «his» işlənir.",
  ["His", "Her", "Its", "My"], 1, None, 2),
 ("This is my sister. ___ name is Lale.",
  "Qız üçün «her» işlənir.",
  ["Her", "His", "Our", "Your"], 1, None, 2),
 ("Mother, father and two children — how many people are in the "
  "family?",
  "2 + 2 = 4 — four.",
  ["Four", "Three", "Five", "Two"], 1, None, 2),
 ("«Aunt» sözü kimi bildirir?",
  "Aunt — xala və ya bibi deməkdir.",
  ["Xalanı və ya bibini", "Əmini", "Nənəni", "Qonşunu"],
  1, None, 2),
],
"ing-5-daily-life": [
 ("I wake ___ at seven in the morning.",
  "«Wake up» — yuxudan oyanmaq.",
  ["up", "on", "in", "at"], 1, None, 2),
 ("She ___ breakfast every morning.",
  "«She» ilə feil «-s» qəbul edir: has.",
  ["has", "have", "is", "does not"], 1, None, 2),
 ("We go to school ___ the morning.",
  "«In the morning» — səhər vaxtı.",
  ["in", "on", "at", "under"], 1, None, 2),
 ("«Axşam» sözünün ingiliscə qarşılığı hansıdır?",
  "Axşam — evening.",
  ["evening", "morning", "afternoon", "night"], 1, None, 1),
 ("He ___ his teeth in the morning.",
  "«He» ilə: brushes.",
  ["brushes", "brush", "brushing", "is brush"], 1, None, 2),
 ("Sixty minutes make one ___.",
  "60 dəqiqə bir saatdır: hour.",
  ["hour", "day", "week", "minute"], 1, None, 2),
 ("«Nahar etmək» ingiliscə necə deyilir?",
  "Nahar etmək — have lunch.",
  ["have lunch", "have breakfast", "go to bed", "wash hands"],
  1, None, 2),
 ("They ___ football after school.",
  "«They» ilə feil dəyişmir: play.",
  ["play", "plays", "playing", "is play"], 1, None, 2),
 ("«Get up» ifadəsinin mənası nədir?",
  "Get up — yuxudan durmaq.",
  ["Yuxudan durmaq", "Yemək yemək", "Dərs oxumaq", "Yatmaq"],
  1, None, 1),
 ("How many days are there in a week?",
  "Həftədə 7 gün var: seven.",
  ["Seven", "Five", "Six", "Ten"], 1, None, 1),
],
"ing-5-school": [
 ("We write with a ___.",
  "Qələmlə yazırıq: pen.",
  ["pen", "bag", "desk", "chair"], 1, None, 1),
 ("«Dərslik» sözünün ingiliscə qarşılığı hansıdır?",
  "Dərslik — textbook.",
  ["textbook", "notebook", "sketchbook", "cookbook"], 1, None, 2),
 ("We do sums in the ___ lesson.",
  "Hesablamalar riyaziyyat dərsində aparılır: Maths.",
  ["Maths", "Music", "Art", "History"], 1, None, 2),
 ("«Open your books» nə deməkdir?",
  "Open your books — kitablarınızı açın.",
  ["Kitablarınızı açın", "Kitablarınızı bağlayın",
   "Ayağa durun", "Sakit olun"], 1, None, 1),
 ("The teacher writes on the ___.",
  "Müəllim lövhədə yazır: board.",
  ["board", "window", "chair", "bag"], 1, None, 1),
 ("Which school subject is «rəsm»?",
  "Rəsm dərsi — Art.",
  ["Art", "Maths", "PE", "English"], 1, None, 2),
 ("We put our books in a ___.",
  "Kitablar çantaya qoyulur: bag.",
  ["bag", "cup", "shoe", "clock"], 1, None, 1),
 ("«Ruler» nə üçün istifadə olunur?",
  "Ruler — xətkeş, xətt çəkmək üçündür.",
  ["Xətt çəkmək üçün", "Yemək üçün", "Oynamaq üçün",
   "Silmək üçün"], 1, None, 2),
 ("Our English lesson is ___ Monday.",
  "Günlərlə «on» işlənir: on Monday.",
  ["on", "in", "at", "under"], 1, None, 2),
 ("What do we say to come into the classroom?",
  "İcazə istəyəndə: May I come in?",
  ["May I come in?", "Good night!", "See you!",
   "It is a pen."], 1, None, 2),
],
"ing-5-clothes": [
 ("She is wearing a red ___. (don)",
  "Don — dress.",
  ["dress", "sock", "glove", "boot"], 1, None, 1),
 ("«Papaq» sözünün ingiliscə qarşılığı hansıdır?",
  "Papaq — hat.",
  ["hat", "coat", "shirt", "skirt"], 1, None, 1),
 ("What ___ he wearing?",
  "İndiki davamedici zaman: What is he wearing?",
  ["is", "are", "am", "do"], 1, None, 2),
 ("In winter we wear a warm ___. (palto)",
  "Palto — coat.",
  ["coat", "T-shirt", "dress", "cap"], 1, None, 2),
 ("«Shoes» sözünün mənası nədir?",
  "Shoes — ayaqqabı.",
  ["Ayaqqabı", "Corab", "Köynək", "Şalvar"], 1, None, 1),
 ("___ they wearing school uniforms?",
  "«They» ilə sual «Are» ilə başlayır.",
  ["Are", "Is", "Am", "Does"], 1, None, 2),
 ("We wear ___ on our hands in winter.",
  "Əllərə əlcək taxılır: gloves.",
  ["gloves", "socks", "hats", "boots"], 1, None, 2),
 ("«T-shirt» nədir?",
  "T-shirt — qısaqol köynək.",
  ["Qısaqol köynək", "Qış paltosu", "İdman ayaqqabısı",
   "Baş örtüyü"], 1, None, 1),
 ("He is wearing blue ___. (şalvar)",
  "Şalvar — trousers.",
  ["trousers", "gloves", "scarves", "hats"], 1, None, 2),
 ("Which one do we wear on our feet?",
  "Ayağa corab geyinilir: socks.",
  ["socks", "hats", "scarves", "rings"], 1, None, 2),
],
"ing-5-movement": [
 ("I can ___ a bike.",
  "Velosiped sürmək — ride a bike.",
  ["ride", "eat", "read", "sing"], 1, None, 2),
 ("«Üzmək» feilinin ingiliscə qarşılığı hansıdır?",
  "Üzmək — swim.",
  ["swim", "run", "jump", "fly"], 1, None, 1),
 ("Can you play chess? — Yes, I ___.",
  "Qısa cavab: Yes, I can.",
  ["can", "am", "have", "play"], 1, None, 2),
 ("We play ___ with a racket.",
  "Raketka ilə tennis oynanılır.",
  ["tennis", "football", "chess", "golf"], 1, None, 2),
 ("«Run» feilinin mənası nədir?",
  "Run — qaçmaq.",
  ["Qaçmaq", "Oturmaq", "Yatmaq", "Yazmaq"], 1, None, 1),
 ("Birds can ___.",
  "Quşlar uça bilir: fly.",
  ["fly", "read", "drive", "write"], 1, None, 1),
 ("Fish cannot ___.",
  "Balıqlar üzə bilir, amma yeriyə bilmir: walk.",
  ["walk", "swim", "eat", "move"], 1, None, 2),
 ("Which verb means «tullanmaq»?",
  "Tullanmaq — jump.",
  ["jump", "sit", "sleep", "stand"], 1, None, 1),
 ("We play football with a ___.",
  "Futbol topla oynanılır: ball.",
  ["ball", "racket", "book", "pen"], 1, None, 1),
 ("«Get moving» ifadəsi bizi nəyə çağırır?",
  "Get moving — hərəkətə başla!",
  ["Hərəkətə", "Yuxuya", "Yeməyə", "Susmağa"], 1, None, 2),
],
# ======================= INFORMATIKA 5 ================================
"inf-5-informasiya": [
 ("İnformasiyanın kodlaşdırılması nədir?",
  "Məlumatın şərti işarələrlə göstərilməsidir.",
  ["Məlumatın şərti işarələrlə göstərilməsi",
   "Məlumatın silinməsi", "Kompüterin təmiri",
   "Şəklin çəkilməsi"], 1, None, 2),
 ("Morze əlifbası nəyə misaldır?",
  "Nöqtə və tire ilə yazı — kodlaşdırmadır.",
  ["Kodlaşdırmaya", "Rəsm əsərinə", "Musiqiyə", "İdmana"],
  1, None, 2),
 ("İnformasiyanın ən kiçik ölçü vahidi hansıdır?",
  "Ən kiçik vahid bitdir.",
  ["Bit", "Bayt", "Metr", "Litr"], 1, None, 2),
 ("1 bayt neçə bitdir?",
  "1 bayt = 8 bit.",
  ["8", "2", "10", "100"], 1, str(8), 2),
 ("İnformasiya modeli nədir?",
  "Obyektin vacib əlamətlərini əks etdirən təsviridir.",
  ["Obyektin vacib əlamətlərinin təsviri", "Obyektin özü",
   "Kompüter qurğusu", "Oyun proqramı"], 1, None, 3),
 ("Xəritə nəyin informasiya modelidir?",
  "Xəritə yer səthinin modelidir.",
  ["Yer səthinin", "Kompüterin", "İnsanın", "Kitabın"],
  1, None, 2),
 ("Kompüterdə informasiya hansı işarələrlə saxlanılır?",
  "Kompüter ikilik say sistemində — 0 və 1 ilə işləyir.",
  ["0 və 1 ilə", "Hərflərlə", "Notlarla", "Rənglərlə"],
  1, None, 3),
 ("Hansı vahid daha böyükdür: bit, yoxsa bayt?",
  "1 bayt 8 bitə bərabərdir — bayt böyükdür.",
  ["Bayt", "Bit", "Bərabərdirlər", "Müqayisə olunmur"],
  1, None, 2),
 ("Mətn informasiyası nə ilə kodlaşdırılır?",
  "Mətn əlifbanın hərfləri ilə yazılır (kodlaşdırılır).",
  ["Hərflərlə", "Yalnız şəkillərlə", "Yalnız səslə",
   "Qoxu ilə"], 1, None, 2),
 ("1 kilobayt neçə baytdır?",
  "1 KB = 1024 bayt.",
  ["1024", "100", "10", "8"], 1, str(2 ** 10), 3),
],
"inf-5-kompyuter": [
 ("Fayl nədir?",
  "Yaddaşda ad altında saxlanılan məlumat toplusudur.",
  ["Ad altında saxlanılan məlumat", "Kompüterin hissəsi",
   "Elektrik naqili", "Ekranın rəngi"], 1, None, 2),
 ("Faylları qruplaşdırmaq üçün nədən istifadə olunur?",
  "Fayllar qovluqlarda saxlanılır.",
  ["Qovluqdan", "Printerdən", "Dinamikdən", "Mausdan"],
  1, None, 1),
 ("İş masasındakı kiçik şəkilciklər necə adlanır?",
  "Proqram və faylların işarələri nişan (ikon) adlanır.",
  ["Nişanlar (ikonlar)", "Pəncərələr", "Fayllar", "Düymələr"],
  1, None, 2),
 ("Proqram pəncərəsini bağlamaq üçün hansı düymə basılır?",
  "Pəncərənin künclərindəki X (bağla) düyməsi.",
  ["X (bağla) düyməsi", "Boşluq düyməsi", "Rəqəm düyməsi",
   "Ok düyməsi"], 1, None, 1),
 ("Menyu nədir?",
  "Menyu əmrlərin siyahısıdır.",
  ["Əmrlərin siyahısı", "Şəkil növü", "Oyun adı",
   "Qurğu adı"], 1, None, 2),
 ("Əməli yaddaş nə üçündür?",
  "İşlək proqramları müvəqqəti saxlamaq üçündür.",
  ["İşlək proqramları müvəqqəti saxlamaq üçün",
   "Şəkil çəkmək üçün", "Səs ucaltmaq üçün",
   "Ekranı təmizləmək üçün"], 1, None, 3),
 ("Məlumatı uzun müddət saxlayan qurğu hansıdır?",
  "Sərt disk məlumatı daimi saxlayır.",
  ["Sərt disk", "Monitor", "Maus", "Mikrofon"], 1, None, 2),
 ("Pəncərəni bütün ekrana açan düymə necə adlanır?",
  "Böyütmə (maximize) düyməsi pəncərəni tam açır.",
  ["Böyütmə düyməsi", "Bağlama düyməsi", "Silmə düyməsi",
   "Enter düyməsi"], 1, None, 2),
 ("Faylın adında nöqtədən sonra yazılan hissə necə adlanır?",
  "Nöqtədən sonrakı hissə genişlənmə (uzantı) adlanır.",
  ["Genişlənmə (uzantı)", "Qovluq", "Parol", "Nişan"],
  1, None, 3),
 ("Kompüteri idarə edən əsas proqram necə adlanır?",
  "Bütün işi əməliyyat sistemi idarə edir.",
  ["Əməliyyat sistemi", "Oyun proqramı", "Şəkil redaktoru",
   "Kalkulyator"], 1, None, 3),
],
"inf-5-tetbiqi": [
 ("Şəklin bir hissəsini köçürmək üçün əvvəlcə nə etmək lazımdır?",
  "Əvvəlcə fraqment seçilir, sonra köçürülür.",
  ["Fraqmenti seçmək", "Şəkli silmək", "Proqramı bağlamaq",
   "Printeri qoşmaq"], 1, None, 2),
 ("Qrafik redaktorda düz xətt hansı alətlə çəkilir?",
  "Xətt aləti düz xətt çəkir.",
  ["Xətt aləti ilə", "Silgi ilə", "Mətn aləti ilə",
   "Ləkə aləti ilə"], 1, None, 1),
 ("Şəklin fraqmentini döndərmək mümkündürmü?",
  "Seçilmiş fraqmenti döndərmək və əymək olar.",
  ["Bəli, seçib döndərmək olar", "Xeyr, heç vaxt",
   "Yalnız çap edəndə", "Yalnız silərkən"], 1, None, 2),
 ("Mətnin formatlanması nədir?",
  "Mətnin görkəminin (şrift, ölçü, rəng) dəyişdirilməsidir.",
  ["Mətnin görkəminin dəyişdirilməsi", "Mətnin silinməsi",
   "Kompüterin söndürülməsi", "Şəklin çəkilməsi"], 1, None, 2),
 ("Yazını qalın etmək üçün hansı düymədən istifadə olunur?",
  "B (Bold) düyməsi yazını qalın edir.",
  ["B (Bold)", "X (bağla)", "Esc", "Tab"], 1, None, 2),
 ("Mətn sənədinə şəkil əlavə etmək olarmı?",
  "Bəli, şəkilli mətn yaratmaq mümkündür.",
  ["Bəli, olar", "Xeyr, olmaz", "Yalnız qışda",
   "Yalnız printerlə"], 1, None, 1),
 ("Silgi aləti nə edir?",
  "Silgi şəklin lazımsız hissəsini silir.",
  ["Şəklin hissəsini silir", "Şəkli böyüdür", "Səs yazır",
   "Faylı bağlayır"], 1, None, 1),
 ("Mətndə bir sözü seçdirmək üçün nə edilir?",
  "Söz mausla sürüşdürülərək seçdirilir.",
  ["Mausla üzərindən sürüşdürülür", "Kompüter söndürülür",
   "Printer qoşulur", "Ekran silinir"], 1, None, 2),
 ("Rəngləmə («çəllək») aləti nə üçündür?",
  "Qapalı sahəni seçilmiş rənglə doldurur.",
  ["Qapalı sahəni rənglə doldurmaq üçün", "Mətn yazmaq üçün",
   "Faylı silmək üçün", "Səsi artırmaq üçün"], 1, None, 2),
 ("Hazır şəkli sənədə haradan əlavə etmək olar?",
  "Yaddaşdakı fayldan əlavə etmək olar.",
  ["Fayldan (yaddaşdan)", "Printerdən", "Dinamikdən",
   "Klaviaturanın altından"], 1, None, 2),
],
"inf-5-alqoritm": [
 ("Alqoritmi hansı üsullarla təqdim etmək olar?",
  "Sözlə, cədvəllə və blok-sxemlə təqdim olunur.",
  ["Sözlə, cədvəllə, blok-sxemlə", "Yalnız şəkillə",
   "Yalnız musiqi ilə", "Heç cür"], 1, None, 2),
 ("Blok-sxemdə alqoritmin başlanğıcı hansı fiqurla göstərilir?",
  "Başlanğıc və son oval fiqurla göstərilir.",
  ["Oval", "Düzbucaqlı", "Romb", "Üçbucaq"], 1, None, 3),
 ("Proqram nədir?",
  "Kompüterin başa düşdüyü dildə yazılmış alqoritmdir.",
  ["Kompüter dilində yazılmış alqoritm", "Kompüterin hissəsi",
   "Elektrik cihazı", "Oyun qaydası"], 1, None, 2),
 ("«Bağa» icraçısı ekranda nə edir?",
  "Bağa hərəkət edərək arxasınca xətt çəkir.",
  ["Hərəkət edib xətt çəkir", "Mahnı oxuyur",
   "Fayl silir", "Mətn yazır"], 1, None, 2),
 ("Bağa 100 addım irəli gedib 90° dönməyi 4 dəfə təkrarlasa, "
  "hansı fiqur alınar?",
  "Dörd bərabər tərəf və dörd düz bucaq — kvadrat.",
  ["Kvadrat", "Üçbucaq", "Dairə", "Beşbucaqlı"], 1, None, 3),
 ("Proqramda səhv olarsa, kompüter nə edər?",
  "Kompüter yazılanı icra edir — səhv nəticə alınar.",
  ["Səhv nəticə verər", "Səhvi özü düzəldər",
   "Kompüter əriyər", "Heç nə dəyişməz"], 1, None, 2),
 ("Blok-sxemdə icra addımı (əməliyyat) hansı fiqurda yazılır?",
  "Əməliyyatlar düzbucaqlıda yazılır.",
  ["Düzbucaqlıda", "Ovalda", "Dairədə", "Ulduzda"], 1, None, 3),
 ("Bağaya «sağa dön 90» əmri verildi. O nə edəcək?",
  "Bağa yerindəcə 90 dərəcə sağa dönəcək.",
  ["90 dərəcə sağa dönəcək", "100 addım gedəcək",
   "Xətti siləcək", "Dayanacaq"], 1, None, 2),
 ("Kompüter proqramları hansı dildə yazılır?",
  "Proqramlar proqramlaşdırma dillərində yazılır.",
  ["Proqramlaşdırma dilində", "Yalnız ana dilində",
   "Heç bir dildə", "Quş dilində"], 1, None, 2),
 ("Bağa üçbucaq çəkmək üçün hər dönüşdə neçə dərəcə dönməlidir?",
  "Tam dövr 360°; üç dönüş: 360 : 3 = 120°.",
  ["120°", "90°", "60°", "180°"], 1, "%d°" % (360 // 3), 3),
],
"inf-5-internet": [
 ("İnternet nədir?",
  "Dünyadakı kompüterləri birləşdirən ümumdünya şəbəkəsidir.",
  ["Ümumdünya kompüter şəbəkəsi", "Bir kompüterin adı",
   "Oyun proqramı", "Televiziya kanalı"], 1, None, 1),
 ("Veb-səhifələri açmaq üçün hansı proqramdan istifadə olunur?",
  "Veb-səhifələr brauzerdə açılır.",
  ["Brauzerdən", "Kalkulyatordan", "Şəkil redaktorundan",
   "Saatdan"], 1, None, 2),
 ("İnternetdə məlumat tapmaq üçün nədən istifadə olunur?",
  "Axtarış sistemləri məlumatı tapmağa kömək edir.",
  ["Axtarış sistemindən", "Printerdən", "Silgidən",
   "Tərəzidən"], 1, None, 2),
 ("Saytın internetdəki ünvanı necə adlanır?",
  "Hər saytın öz internet ünvanı (URL) var.",
  ["İnternet ünvanı (URL)", "Ev ünvanı", "Poçt qutusu",
   "Telefon nömrəsi"], 1, None, 2),
 ("«Dünya hörümçək toru» (WWW) nədir?",
  "Bir-birinə keçidlərlə bağlı veb-səhifələr sistemidir.",
  ["Bir-birinə bağlı veb-səhifələr sistemi",
   "Hörümçəklərin yuvası", "Kompüter oyunu",
   "Elektrik şəbəkəsi"], 1, None, 3),
 ("İnternetdə tanımadığın adama hansı məlumatı vermək OLMAZ?",
  "Ev ünvanı və şəxsi məlumatlar gizli saxlanmalıdır.",
  ["Ev ünvanını və şəxsi məlumatları", "Sevimli rəngini",
   "Sevimli fəslini", "Sevimli kitabının adını"],
  1, None, 2),
 ("İnformasiya resursu nədir?",
  "Məlumat mənbəyidir: kitabxana, sayt, arxiv.",
  ["Məlumat mənbəyi", "Elektrik mənbəyi", "Su mənbəyi",
   "İşıq lampası"], 1, None, 2),
 ("Elektron poçt nə üçündür?",
  "İnternetlə məktub göndərib almaq üçündür.",
  ["Məktub göndərib almaq üçün", "Paltar yumaq üçün",
   "Şəkil çəkmək üçün", "Fayl silmək üçün"],
  1, None, 2),
 ("Keçid (link) nə edir?",
  "Klik ediləndə başqa səhifəyə aparır.",
  ["Başqa səhifəyə aparır", "Kompüteri söndürür",
   "Şəkli silir", "Səsi artırır"], 1, None, 2),
 ("İnternetdəki hər məlumata inanmaq olarmı?",
  "Xeyr — məlumatın mənbəyini yoxlamaq lazımdır.",
  ["Xeyr, mənbəni yoxlamaq lazımdır", "Bəli, hamısı doğrudur",
   "Yalnız gecə olar", "Yalnız şəkillərə inanmaq olar"],
  1, None, 2),
],
# ==================== AZERBAYCAN TARIXI 5 =============================
"tarix-5-qedim": [
 ("Tarix elmi nəyi öyrənir?",
  "Tarix bəşəriyyətin keçmişini öyrənir.",
  ["Keçmişi", "Yalnız gələcəyi", "Bitkiləri", "Ulduzları"],
  1, None, 1),
 ("Keçmişdən qalan maddi abidələri qazıntılarla öyrənən alimlər "
  "necə adlanır?",
  "Qazıntı aparan alimlər arxeoloqlardır.",
  ["Arxeoloqlar", "Coğrafiyaçılar", "Riyaziyyatçılar",
   "Həkimlər"], 1, None, 2),
 ("Azərbaycan ərazisində ilk insan məskənlərindən biri hansıdır?",
  "Azıx mağarası ən qədim insan düşərgələrindəndir.",
  ["Azıx mağarası", "Qız qalası", "Şəki sarayı",
   "İçərişəhər"], 1, None, 2),
 ("İlk əmək alətləri hansı materialdan hazırlanırdı?",
  "Ən qədim alətlər daşdan idi.",
  ["Daşdan", "Plastikdən", "Şüşədən", "Poladdan"], 1, None, 1),
 ("Ən qədim insanların ilk məşğuliyyətləri nə idi?",
  "Qədim insanlar ovçuluq və yığıcılıqla dolanırdılar.",
  ["Ovçuluq və yığıcılıq", "Kompüter proqramlaşdırması",
   "Dəmiryol tikintisi", "Kitab çapı"], 1, None, 2),
 ("Azərbaycanın ən qədim dövlətlərindən biri hansıdır?",
  "Manna Azərbaycan ərazisindəki qədim dövlətdir.",
  ["Manna", "Roma", "Misir", "Çin"], 1, None, 2),
 ("Atropatena dövləti Azərbaycanın hansı hissəsində yaranmışdı?",
  "Atropatena cənub torpaqlarında yaranmışdı.",
  ["Cənubunda", "Yalnız şimalında", "Dənizin ortasında",
   "Ərazidən kənarda"], 1, None, 3),
 ("Albaniya dövləti Azərbaycanın hansı hissəsində yerləşirdi?",
  "Qafqaz Albaniyası şimal torpaqlarını əhatə edirdi.",
  ["Şimalında", "Yalnız cənubunda", "Qərb okeanında",
   "Başqa qitədə"], 1, None, 3),
 ("Odun kəşfi qədim insanlara nə verdi?",
  "Od istilik, işıq və yırtıcılardan qorunma verdi.",
  ["İstilik, işıq və qorunma", "Kompüter", "Təyyarə",
   "Televizor"], 1, None, 1),
 ("Dövlət nə üçün lazımdır?",
  "Dövlət ölkəni idarə edir və qoruyur.",
  ["Ölkəni idarə etmək və qorumaq üçün", "Yalnız bayram keçirmək üçün",
   "Oyun oynamaq üçün", "Heç nə üçün"], 1, None, 2),
],
"tarix-5-dovletler": [
 ("Ərəb işğalçılarına qarşı üsyana başçılıq edən qəhrəman kimdir?",
  "Babək azadlıq hərəkatının başçısı idi.",
  ["Babək", "Nizami", "Füzuli", "Vaqif"], 1, None, 2),
 ("Səfəvi dövlətinin banisi kimdir?",
  "Səfəvi dövlətini Şah İsmayıl Xətai yaratdı.",
  ["Şah İsmayıl Xətai", "Qara Yusif", "Nadir şah",
   "Teymur"], 1, None, 2),
 ("Atabəylər dövlətinin banisi kimdir?",
  "Atabəylər dövlətini Şəmsəddin Eldəniz qurmuşdur.",
  ["Şəmsəddin Eldəniz", "Uzun Həsən", "Babək", "Sara xatun"],
  1, None, 3),
 ("Qaraqoyunlu dövlətinin tanınmış hökmdarı kimdir?",
  "Qara Yusif Qaraqoyunlu dövlətinin hökmdarı olub.",
  ["Qara Yusif", "Şah İsmayıl", "Nadir şah", "Cavanşir"],
  1, None, 3),
 ("Ağqoyunlu dövlətinin qüdrətli hökmdarı kim olmuşdur?",
  "Uzun Həsən (Həsən padşah) Ağqoyunlu hökmdarı idi.",
  ["Uzun Həsən", "Qara Yusif", "Babək", "Şəmsəddin Eldəniz"],
  1, None, 3),
 ("«Şərqin son fatehi» adlandırılan hökmdar kimdir?",
  "Nadir şah Əfşar «Şərqin son fatehi» adlanır.",
  ["Nadir şah", "Şah İsmayıl", "Uzun Həsən", "Qara Yusif"],
  1, None, 3),
 ("Dövlət işlərində, danışıqlarda ad çıxarmış Azərbaycan qadını "
  "kimdir?",
  "Sara xatun Ağqoyunlu sarayının tanınmış diplomatı idi.",
  ["Sara xatun", "Tomris", "Kleopatra", "Janna"], 1, None, 3),
 ("XVIII əsrin ortalarında Azərbaycan hansı kiçik dövlətlərə "
  "parçalandı?",
  "Ölkə ayrı-ayrı xanlıqlara bölündü.",
  ["Xanlıqlara", "Ştatlara", "Krallıqlara", "Koloniyalara"], 1, None, 2),
 ("Səlcuqlar hansı xalqın yaratdığı dövlət idi?",
  "Səlcuq dövlətini oğuz türkləri qurmuşdu.",
  ["Oğuz türklərinin", "Romalıların", "Misirlilərin",
   "Vikinqlərin"], 1, None, 3),
 ("Səfəvilər dövlətinin ilk paytaxtı hansı şəhər idi?",
  "Səfəvilərin ilk paytaxtı Təbriz olmuşdur.",
  ["Təbriz", "Bakı", "Gəncə", "Şamaxı"], 1, None, 3),
],
"tarix-5-qalalar": [
 ("Bakının rəmzi sayılan qədim qala-abidə hansıdır?",
  "Qız qalası Bakının rəmzidir.",
  ["Qız qalası", "Çıraq qala", "Əlincə qalası", "Gülüstan qalası"],
  1, None, 1),
 ("İçərişəhər hansı şəhərdə yerləşir?",
  "İçərişəhər Bakının qədim hissəsidir.",
  ["Bakıda", "Gəncədə", "Şəkidə", "Naxçıvanda"], 1, None, 1),
 ("Qalalar əsasən nə üçün tikilirdi?",
  "Qalalar düşməndən müdafiə üçün tikilirdi.",
  ["Müdafiə üçün", "İdman üçün", "Yalnız bəzək üçün", "Anbar üçün"], 1, None, 1),
 ("«Azərbaycanın taxtı» adlandırılan şəhər hansıdır?",
  "Təbriz uzun müddət paytaxt olduğu üçün belə adlanıb.",
  ["Təbriz", "Sumqayıt", "Mingəçevir", "Lənkəran"], 1, None, 3),
 ("Qədim şəhərlər ən çox harada salınırdı?",
  "Şəhərlər ticarət yolları üstündə, su mənbələri yanında yaranırdı.",
  ["Ticarət yolları üstündə", "Buzlaqların içində",
   "Vulkanların ağzında", "Dəniz dibində"], 1, None, 2),
 ("Naxçıvandakı məşhur qədim türbə hansıdır?",
  "Möminə xatın türbəsi Naxçıvan memarlığının incisidir.",
  ["Möminə xatın türbəsi", "Qız qalası", "Şirvanşahlar sarayı",
   "Atəşgah"], 1, None, 3),
 ("Qəbələ hansı qədim dövlətin paytaxtı olmuşdur?",
  "Qəbələ Qafqaz Albaniyasının paytaxtı idi.",
  ["Albaniyanın", "Romanın", "Misirin", "Yunanıstanın"],
  1, None, 3),
 ("Şəki şəhərindəki məşhur tarixi saray hansıdır?",
  "Şəki xan sarayı dünya şöhrətli abidədir.",
  ["Şəki xan sarayı", "Qış sarayı", "Yay sarayı",
   "Buz sarayı"], 1, None, 2),
 ("Şuşa qalasını kim saldırmışdır?",
  "Şuşanı Qarabağ xanı Pənahəli xan saldırıb.",
  ["Pənahəli xan", "Nadir şah", "Şah İsmayıl", "Babək"],
  1, None, 3),
 ("Karvansaralar nə üçün tikilirdi?",
  "Karvansaralar tacirlərin və karvanların dincəlməsi üçün idi.",
  ["Tacirlərin dincəlməsi üçün", "Dərs keçmək üçün",
   "İdman yarışları üçün", "Gəmi saxlamaq üçün"], 1, None, 2),
],
"tarix-5-respublika": [
 ("Müsəlman Şərqində ilk demokratik respublika hansıdır?",
  "Azərbaycan Xalq Cümhuriyyəti Şərqdə ilk respublikadır.",
  ["Azərbaycan Xalq Cümhuriyyəti", "Roma Respublikası",
   "Fransa Respublikası", "Afina dövləti"], 1, None, 2),
 ("Azərbaycan Xalq Cümhuriyyəti neçənci ildə yaranmışdır?",
  "AXC 1918-ci il mayın 28-də elan olundu.",
  ["1918", "1920", "1991", "1945"], 1, None, 2),
 ("Azərbaycan Xalq Cümhuriyyəti neçənci ildə sovet işğalı ilə "
  "süqut etdi?",
  "1920-ci ilin aprelində sovet Rusiyası Azərbaycanı işğal etdi.",
  ["1920", "1918", "1939", "1969"], 1, None, 3),
 ("Azərbaycan dövlət müstəqilliyini neçənci ildə bərpa etdi?",
  "Müstəqillik 1991-ci ildə bərpa olundu.",
  ["1991", "1981", "2001", "1970"], 1, None, 2),
 ("Azərbaycan xalqının ümummilli lideri kimdir?",
  "Heydər Əliyev ümummilli lider sayılır.",
  ["Heydər Əliyev", "Nizami Gəncəvi", "Babək", "Uzun Həsən"],
  1, None, 1),
 ("44 günlük Vətən müharibəsi neçənci ildə baş verdi?",
  "Vətən müharibəsi 2020-ci ildə oldu.",
  ["2020", "2016", "1994", "2003"], 1, None, 2),
 ("Vətən müharibəsində Azərbaycan Ordusunun Ali Baş Komandanı "
  "kim idi?",
  "Prezident İlham Əliyev Ali Baş Komandan idi.",
  ["İlham Əliyev", "Nadir şah", "Şah İsmayıl", "Pənahəli xan"],
  1, None, 2),
 ("8 Noyabr Azərbaycanda hansı gün kimi qeyd olunur?",
  "8 Noyabr — Şuşanın azad edildiyi Zəfər Günüdür.",
  ["Zəfər Günü", "Bilik Günü", "Novruz bayramı",
   "Dövlət Bayrağı Günü"], 1, None, 2),
 ("Aprel döyüşləri neçənci ildə olmuşdur?",
  "Aprel döyüşləri 2016-cı ildə baş verib.",
  ["2016", "2020", "1918", "1991"], 1, None, 3),
 ("İkinci Dünya müharibəsində qələbəyə Azərbaycan ən çox nə ilə "
  "töhfə verdi?",
  "Cəbhə Bakı nefti ilə təmin olunurdu.",
  ["Bakı nefti ilə", "Qızıl külçələrlə", "Gəmilərlə",
   "Kosmik texnika ilə"], 1, None, 3),
],
"tarix-5-medeniyyet": [
 ("Azərbaycan xalqının qəhrəmanlıq dastanı hansıdır?",
  "«Kitabi-Dədə Qorqud» xalqımızın qəhrəmanlıq dastanıdır.",
  ["«Kitabi-Dədə Qorqud»", "«Robinzon Kruzo»",
   "«Min bir gecə»", "«İliada»"], 1, None, 2),
 ("«Xəmsə» əsərinin müəllifi kimdir?",
  "Beş poemadan ibarət «Xəmsə»ni Nizami Gəncəvi yazıb.",
  ["Nizami Gəncəvi", "Üzeyir Hacıbəyli", "Lütfi Zadə",
   "Həsən bəy Zərdabi"], 1, None, 2),
 ("«Azərbaycan tarixinin atası» sayılan alim kimdir?",
  "Abbasqulu ağa Bakıxanov ilk elmi tarix əsərini yazıb.",
  ["Abbasqulu ağa Bakıxanov", "Nizami Gəncəvi",
   "Şah İsmayıl", "Babək"], 1, None, 3),
 ("İlk Azərbaycan qəzeti necə adlanırdı?",
  "İlk milli qəzetimiz «Əkinçi» idi.",
  ["«Əkinçi»", "«Molla Nəsrəddin»", "«Kommunist»",
   "«Azərbaycan»"], 1, None, 2),
 ("«Əkinçi» qəzetini kim nəşr edirdi?",
  "Qəzeti Həsən bəy Zərdabi nəşr edirdi.",
  ["Həsən bəy Zərdabi", "Üzeyir Hacıbəyli", "Nizami",
   "Bakıxanov"], 1, None, 3),
 ("Şərqdə ilk operanın («Leyli və Məcnun») müəllifi kimdir?",
  "Üzeyir Hacıbəyli Şərqdə ilk operanı yaratdı.",
  ["Üzeyir Hacıbəyli", "Həsən bəy Zərdabi", "Lütfi Zadə",
   "Nadir şah"], 1, None, 2),
 ("«Qeyri-səlis məntiq» nəzəriyyəsinin müəllifi, dünya şöhrətli "
  "alim kimdir?",
  "Lütfi Zadə dünya şöhrətli Azərbaycan alimidir.",
  ["Lütfi Zadə", "Nyuton", "Eynşteyn", "Arximed"], 1, None, 3),
 ("Nizami Gəncəvi hansı şəhərdə yaşayıb-yaratmışdır?",
  "Nizami bütün ömrünü Gəncədə keçirib.",
  ["Gəncədə", "Parisdə", "İstanbulda", "Qahirədə"], 1, None, 2),
 ("«Kitabi-Dədə Qorqud» dastanında nə vəsf olunur?",
  "Dastanda oğuz igidlərinin qəhrəmanlığı vəsf olunur.",
  ["Oğuz igidlərinin qəhrəmanlığı", "Kosmik uçuşlar",
   "Dəniz səyahətləri", "İdman yarışları"], 1, None, 3),
 ("Üzeyir Hacıbəylinin məşhur musiqili komediyası hansıdır?",
  "«Arşın mal alan» dünyada tanınan komediyadır.",
  ["«Arşın mal alan»", "«Hamlet»", "«Otello»", "«Karmen»"],
  1, None, 3),
],
}


def yoxla():
    n = xeta = 0
    butun = set()
    movzu_fenn = {m: f for f, m, _r in MOVZULAR}
    for movzu, siyahi in SUALLAR.items():
        assert movzu in movzu_fenn, movzu
        if len(siyahi) != 10:
            print("XETA  %s: %d sual (10 olmalidir)" % (movzu, len(siyahi)))
            xeta += 1
        for body, why, opts, correct, expect, diff in siyahi:
            n += 1
            p = []
            if len(opts) != 4: p.append("variant sayi %d" % len(opts))
            if len(set(opts)) != len(opts): p.append("tekrar variant")
            if not (1 <= correct <= 4): p.append("correct")
            if not why: p.append("izah bos")
            if diff not in (1, 2, 3): p.append("cetinlik")
            if body in butun: p.append("eyni sual iki defe")
            butun.add(body)
            if expect is not None and opts[correct - 1] != expect:
                p.append("hesablanan «%s» != variant «%s»" % (expect, opts[correct - 1]))
            for t in [body, why] + opts:
                if "'" in t: p.append("apostrof var")
            if p:
                xeta += 1
                print("XETA  %s: %s\n      %s" % (movzu, body[:60], "; ".join(p)))
    hes = sum(1 for s in SUALLAR.values() for q in s if q[4] is not None)
    print("%d sual yoxlandı (%d-i hesabla təsdiqləndi), %d xəta" % (n, hes, xeta))
    return xeta == 0, n


def sql_yaz(n):
    q = lambda t: t.replace("'", "''")
    on = {"az-dili": "az5", "ingilis-dili": "ing5",
          "informatika": "inf5", "tarix": "tarix5"}
    setirler = []
    for fenn, movzu, rub in MOVZULAR:
        qisa = movzu.split("-", 2)[2]
        for i, (body, why, opts, correct, _e, diff) in enumerate(SUALLAR[movzu], 1):
            setirler.append(
                "('%s-%s#%d','%s','%s',%d,%d,'%s','%s',array['%s','%s','%s','%s'],%d)"
                % (on[fenn], qisa, i, fenn, movzu, diff, rub, q(body), q(why),
                   q(opts[0]), q(opts[1]), q(opts[2]), q(opts[3]), correct))
    with io.open(CIXIS, "w", encoding="utf-8") as f:
        f.write("""-- =====================================================================
--  27_bank_sinif5.sql : 5-CI SINIF - AZ DILI, INGILIS DILI,
--                       INFORMATIKA, AZERBAYCAN TARIXI
--
--  BU FAYL ELLE YAZILMIR - tools/sinif5.py yaradir:
--      python3 tools/sinif5.py
--
--  Az dili 8 + Ingilis dili 8 + Informatika 5 + Tarix 5
--  = 26 movzu x 10 = %d.  ext_key: az5-/ing5-/inf5-/tarix5-...
--  ON SERT: 25_movzular_orta5.sql islenmis olmalidir.
--  SONRA:   05_grants.sql yeniden islet.
-- =====================================================================

do $$
begin
  if not exists (select 1 from public.topics t join public.subjects s
      on s.id = t.subject_id
     where (s.slug, t.slug) in (('az-dili','az-5-fonetika'),
                                ('ingilis-dili','ing-5-family'),
                                ('informatika','inf-5-internet'),
                                ('tarix','tarix-5-qedim'))
     having count(*) = 4) then
    raise exception 'ONCE 25_movzular_orta5.sql isledilmelidir.';
  end if;
end $$;

delete from public.question_options o
 using public.questions q
 where o.question_id = q.id
   and q.owner_type = 'platform'
   and (q.ext_key like 'az5-%%' or q.ext_key like 'ing5-%%'
        or q.ext_key like 'inf5-%%' or q.ext_key like 'tarix5-%%');

with d(ext, fenn, topic, diff, rub, body, why, opts, correct) as (values
%s
),
ins as (
  insert into public.questions
    (ext_key, owner_type, subject_id, level_id, topic_id, kind,
     body, explanation, difficulty, quarter, status)
  select d.ext, 'platform', s.id, l.id, tp.id, 'single',
         d.body, d.why, d.diff, d.rub, 'published'
    from d
    join public.subjects s on s.slug = d.fenn
    join public.programs p on p.slug = 'orta'
    join public.levels   l on l.program_id = p.id and l.code = '5'
    join public.topics   tp on tp.subject_id = s.id and tp.slug = d.topic
  on conflict (ext_key) do update
    set body = excluded.body, explanation = excluded.explanation,
        difficulty = excluded.difficulty, quarter = excluded.quarter,
        topic_id = excluded.topic_id, level_id = excluded.level_id,
        subject_id = excluded.subject_id, status = 'published'
  returning id, ext_key
)
insert into public.question_options (question_id, ord, body, is_correct)
select ins.id, o.ord, o.txt, o.ord = d.correct
  from ins
  join d on d.ext = ins.ext_key,
  lateral unnest(d.opts) with ordinality as o(txt, ord);

do $$
declare n int; k int;
begin
  select count(*) into n from public.questions
   where owner_type = 'platform'
     and (ext_key like 'az5-%%' or ext_key like 'ing5-%%'
          or ext_key like 'inf5-%%' or ext_key like 'tarix5-%%');
  if n <> %d then
    raise exception 'sinif5 suallari: %d gozlenilirdi, %% tapildi', n;
  end if;
  select count(*) into k from public.questions q
   where (q.ext_key like 'az5-%%' or q.ext_key like 'ing5-%%'
          or q.ext_key like 'inf5-%%' or q.ext_key like 'tarix5-%%')
     and ((select count(*) from public.question_options o
            where o.question_id = q.id) <> 4
       or (select count(*) from public.question_options o
            where o.question_id = q.id and o.is_correct) <> 1);
  if k > 0 then
    raise exception '%% sualda variant qurulusu sehvdir', k;
  end if;
  select count(distinct topic_id) into k from public.questions
   where ext_key like 'az5-%%' or ext_key like 'ing5-%%'
      or ext_key like 'inf5-%%' or ext_key like 'tarix5-%%';
  if k <> 26 then
    raise exception 'movzu sayi 26 deyil: %%', k;
  end if;
  raise notice '5-ci sinif banki: %% sual, 26 movzu (az, ing, inf, tarix).', n;
end $$;
""" % (n, ",\n".join(setirler), n, n))
    print("yazildi: %s" % CIXIS)


if __name__ == "__main__":
    ok, n = yoxla()
    if not ok:
        raise SystemExit(1)
    sql_yaz(n)
