#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
2-ci sinif platforma banki -> db/24_bank_sinif2.sql

    Riyaziyyat 2         9 movzu x 20 = 180
    Azerbaycan dili 2    7 movzu x 20 = 140
    Heyat bilgisi 2      6 movzu x 20 = 120
    Informatika 2        4 movzu x 20 =  80
                                  cemi  520

tools/sinif1.py qelibi ile: her riyazi cavab YENIDEN HESABLANIB duzgun
variantla tutusdurulur.  Vurma/bolme YALNIZ 2-5 cedveli cercivesinde
(2-ci sinif proqrami).  Movzular 14_movzular.sql (az dili, riy 2) ve
15_movzular_ederslik.sql (heyat bilgisi, informatika) agacina uygundur.

DIQQET: movcud bank fayllarinin (db/07, 16, 17, 19, 20, 23) cumle
qellibleri ve reqemleri TEKRARLANMAYIB - generator pg_trgm ile >= 0.95
oxsarligi tekrar sayir.  Xususile 07_seed_tests (6x7, 9x8, 4x9, 5x6,
3x8, 8x6, 56:8) ve 19_bank_riy3 (7x4, 9x6, 8x8, 36:4, 42:6) reqemleri
islenmeyib.

Isletmek:
    python3 tools/sinif2.py
"""
import io
import os

KOK = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CIXIS = os.path.join(KOK, "db", "24_bank_sinif2.sql")

SAITLER = set("aeəiıoöuü")


def sait(soz):
    return sum(1 for h in soz.lower() if h in SAITLER)


def samit(soz):
    return sum(1 for h in soz.lower() if h.isalpha() and h not in SAITLER)


#  (fenn, movzu-slug, rub) - rub kitabin bolme sirasina gore
MOVZULAR = [
    ("riyaziyyat", "riy-2-ededler-100",   1),
    ("riyaziyyat", "riy-2-toplama-cixma", 1),
    ("riyaziyyat", "riy-2-vurma",         2),
    ("riyaziyyat", "riy-2-vurma-cedveli", 2),
    ("riyaziyyat", "riy-2-bolme",         3),
    ("riyaziyyat", "riy-2-zaman",         3),
    ("riyaziyyat", "riy-2-olcu",          3),
    ("riyaziyyat", "riy-2-fiqurlar",      4),
    ("riyaziyyat", "riy-2-mesele",        4),
    ("az-dili", "az-2-soz-novleri",   1),
    ("az-dili", "az-2-ad-bildiren",   1),
    ("az-dili", "az-2-elamet",        2),
    ("az-dili", "az-2-hereket",       2),
    ("az-dili", "az-2-cumle-novleri", 3),
    ("az-dili", "az-2-durgu",         3),
    ("az-dili", "az-2-yazi-qaydasi",  4),
    ("hayat-bilgisi", "hey-2-men-mektebim", 1),
    ("hayat-bilgisi", "hey-2-deyerler",     1),
    ("hayat-bilgisi", "hey-2-materiallar",  2),
    ("hayat-bilgisi", "hey-2-yer-kuresi",   3),
    ("hayat-bilgisi", "hey-2-canlilar",     3),
    ("hayat-bilgisi", "hey-2-ehtiyat",      4),
    ("informatika", "inf-2-obyekt",      1),
    ("informatika", "inf-2-informasiya", 2),
    ("informatika", "inf-2-alqoritm",    3),
    ("informatika", "inf-2-kompyuter",   4),
]

SUALLAR = {
# ======================= RIYAZIYYAT 2 =================================
"riy-2-ededler-100": [
 ("«Altmış beş» ədədi rəqəmlə necə yazılır?",
  "60 + 5 = 65.",
  ["65", "56", "605", "55"], 1, str(60 + 5), 1),
 ("78 ədədində onluqların sayı neçədir?",
  "78 = 7 onluq və 8 təklik.",
  ["7", "8", "78", "70"], 1, str(78 // 10), 2),
 ("9 onluq və 2 təklikdən ibarət ədəd hansıdır?",
  "9 onluq = 90; 90 + 2 = 92.",
  ["92", "29", "902", "11"], 1, str(9 * 10 + 2), 2),
 ("56-dan bilavasitə əvvəl gələn ədədi yazın.",
  "56 − 1 = 55.",
  ["55", "57", "46", "54"], 1, str(56 - 1), 1),
 ("Ən kiçik ikirəqəmli ədəd hansıdır?",
  "İkirəqəmli ədədlər 10-dan başlayır.",
  ["10", "11", "99", "1"], 1, str(10), 2),
 ("40, 60, 50 ədədlərini azalan sırada düzün.",
  "Böyükdən kiçiyə: 60, 50, 40.",
  ["60, 50, 40", "40, 50, 60", "50, 60, 40", "60, 40, 50"],
  1, None, 2),
 ("83 və 38 ədədlərindən hansı kiçikdir?",
  "38-də 3 onluq, 83-də 8 onluq var: 38 kiçikdir.",
  ["38", "83", "Bərabərdirlər", "Bilmək olmaz"], 1,
  str(min(83, 38)), 2),
 ("Onluqlarla geriyə sayma: 90, 80, 70, ? Növbəti ədəd hansıdır?",
  "Hər addımda 1 onluq azalır: 60.",
  ["60", "50", "65", "80"], 1, str(70 - 10), 2),
 ("Hansı ədəd təkdir?",
  "Sonu 1, 3, 5, 7, 9 ilə bitən ədədlər təkdir: 31.",
  ["31", "14", "32", "48"], 1, None, 2),
 ("76 ədədi mərtəbə toplananlarının cəmi kimi necə yazılır?",
  "76 = 7 onluq + 6 təklik = 70 + 6.",
  ["70 + 6", "7 + 6", "70 + 60", "76 + 0"], 1, None, 3),
],
"riy-2-toplama-cixma": [
 ("34 + 23 neçə edər?",
  "34 + 23 = 57.",
  ["57", "56", "67", "11"], 1, str(34 + 23), 1),
 ("48 + 27 cəmini tapın.",
  "8 + 7 = 15, biri onluğa keçir: 48 + 27 = 75.",
  ["75", "65", "74", "615"], 1, str(48 + 27), 2),
 ("65 − 31 fərqini tapın.",
  "65 − 31 = 34.",
  ["34", "35", "44", "96"], 1, str(65 - 31), 1),
 ("72 − 46 neçə edər?",
  "2-dən 6 çıxmır, onluqdan borc alınır: 72 − 46 = 26.",
  ["26", "36", "34", "24"], 1, str(72 - 46), 2),
 ("80 − 37 fərqini hesablayın.",
  "80 − 37 = 43.",
  ["43", "53", "47", "117"], 1, str(80 - 37), 2),
 ("25 + 25 neçə edər?",
  "25 + 25 = 50.",
  ["50", "40", "45", "55"], 1, str(25 + 25), 1),
 ("Cəm 70-dir, toplananlardan biri 42-dir. O biri toplananı tapın.",
  "70 − 42 = 28.",
  ["28", "32", "112", "38"], 1, str(70 - 42), 3),
 ("19 + 19 neçə edər?",
  "19 + 19 = 38.",
  ["38", "28", "37", "39"], 1, str(19 + 19), 2),
 ("Hansı ifadənin qiyməti 100-dür?",
  "64 + 36 = 100.",
  ["64 + 36", "54 + 36", "64 + 26", "74 + 36"], 1, None, 3),
 ("53 + 20 neçə olar?",
  "Onluqlar toplanır: 53 + 20 = 73.",
  ["73", "55", "63", "83"], 1, str(53 + 20), 1),
],
"riy-2-vurma": [
 ("3 + 3 + 3 + 3 cəmini vurma ilə necə yazmaq olar?",
  "3 ədədi 4 dəfə toplanır: 3 × 4.",
  ["3 × 4", "3 × 3", "4 × 4", "3 + 4"], 1, None, 1),
 ("2 × 5 yazılışı nə deməkdir?",
  "2 ədədinin 5 dəfə toplanması deməkdir.",
  ["2-nin 5 dəfə toplanması", "2 ilə 5-in cəmi",
   "5-dən 2-nin çıxılması", "2-nin 5-ə bölünməsi"], 1, None, 2),
 ("4 + 4 + 4 = 4 × ? Sual işarəsinin yerinə hansı ədəd yazılmalıdır?",
  "4 ədədi 3 dəfə toplanıb: 4 × 3.",
  ["3", "4", "12", "2"], 1, str(3), 2),
 ("Vurma əməlinin nəticəsi necə adlanır?",
  "Vurmanın nəticəsi hasildir.",
  ["Hasil", "Cəm", "Fərq", "Qismət"], 1, None, 2),
 ("Ədədi 1-ə vuranda nə alınır?",
  "İstənilən ədədi 1-ə vuranda ədədin özü alınır.",
  ["Ədədin özü", "Sıfır", "1", "Ədədin iki misli"], 1, None, 1),
 ("6 × 0 neçə olar?",
  "Sıfıra vurmanın hasili həmişə sıfırdır.",
  ["0", "6", "60", "1"], 1, str(6 * 0), 2),
 ("2 × 3 və 3 × 2 hasilləri haqqında nə demək olar?",
  "Vuruqların yeri dəyişəndə hasil dəyişmir.",
  ["Hasilləri bərabərdir", "Birincisi böyükdür", "İkincisi böyükdür",
   "Müqayisə etmək olmaz"], 1, None, 2),
 ("Hər boşqabda 2 kotlet olmaqla 5 boşqabda neçə kotlet var?",
  "2 × 5 = 10.",
  ["10", "7", "2", "25"], 1, str(2 * 5), 2),
 ("Vuruqlar 5 və 3-dürsə, hasil neçədir?",
  "5 × 3 = 15.",
  ["15", "8", "53", "2"], 1, str(5 * 3), 2),
 ("Hansı yazılış vurma əməlidir?",
  "«×» işarəsi vurmanı göstərir.",
  ["2 × 6", "2 + 6", "6 − 2", "6 : 2"], 1, None, 1),
],
"riy-2-vurma-cedveli": [
 ("2 × 7 neçə edər?",
  "2 × 7 = 14.",
  ["14", "12", "16", "9"], 1, str(2 * 7), 1),
 ("3 × 6 hasilini tapın.",
  "3 × 6 = 18.",
  ["18", "15", "21", "9"], 1, str(3 * 6), 2),
 ("4 × 8 neçə edər?",
  "4 × 8 = 32.",
  ["32", "28", "36", "12"], 1, str(4 * 8), 2),
 ("5 × 5 hasilini hesablayın.",
  "5 × 5 = 25.",
  ["25", "20", "30", "10"], 1, str(5 * 5), 1),
 ("3 × 9 neçə edər?",
  "3 × 9 = 27.",
  ["27", "24", "30", "12"], 1, str(3 * 9), 2),
 ("4 × 4 hasilini tapın.",
  "4 × 4 = 16.",
  ["16", "12", "20", "8"], 1, str(4 * 4), 1),
 ("4 × 3 neçə olar?",
  "4 × 3 = 12.",
  ["12", "9", "16", "7"], 1, str(4 * 3), 1),
 ("5 × 7 hasilini hesablayın.",
  "5 × 7 = 35.",
  ["35", "30", "40", "12"], 1, str(5 * 7), 2),
 ("3 × 3 neçə edər?",
  "3 × 3 = 9.",
  ["9", "6", "12", "33"], 1, str(3 * 3), 1),
 ("5-ə vurmanın hasili həmişə hansı rəqəmlərlə bitir?",
  "5-in cədvəlində hasillər 5, 10, 15, 20… — sonu 0 və ya 5 olur.",
  ["0 və ya 5", "1 və ya 2", "Yalnız 5", "İstənilən rəqəmlə"],
  1, None, 3),
],
"riy-2-bolme": [
 ("10 : 2 neçə edər?",
  "10 : 2 = 5, çünki 2 × 5 = 10.",
  ["5", "4", "8", "20"], 1, str(10 // 2), 1),
 ("12 : 3 qismətini tapın.",
  "12 : 3 = 4.",
  ["4", "3", "6", "9"], 1, str(12 // 3), 1),
 ("18 : 2 neçə olar?",
  "18 : 2 = 9.",
  ["9", "8", "16", "7"], 1, str(18 // 2), 2),
 ("28 : 4 qismətini hesablayın.",
  "28 : 4 = 7.",
  ["7", "6", "8", "24"], 1, str(28 // 4), 2),
 ("40 : 5 neçə edər?",
  "40 : 5 = 8.",
  ["8", "7", "9", "35"], 1, str(40 // 5), 2),
 ("15 : 5 qismətini tapın.",
  "15 : 5 = 3.",
  ["3", "5", "10", "4"], 1, str(15 // 5), 1),
 ("30 : 5 neçə olar?",
  "30 : 5 = 6.",
  ["6", "5", "7", "25"], 1, str(30 // 5), 2),
 ("8 fındıq 4 dələyə bərabər bölündü. Hər dələyə neçə fındıq düşdü?",
  "8 : 4 = 2.",
  ["2", "4", "12", "32"], 1, str(8 // 4), 2),
 ("Bölmə əməlinin nəticəsi necə adlanır?",
  "Bölmənin nəticəsi qismətdir.",
  ["Qismət", "Hasil", "Cəm", "Fərq"], 1, None, 2),
 ("Bölmə hansı əməlin tərsidir?",
  "Bölmə vurmanın tərs əməlidir.",
  ["Vurmanın", "Toplamanın", "Çıxmanın", "Heç birinin"],
  1, None, 3),
],
"riy-2-zaman": [
 ("Saatın qısa (kiçik) əqrəbi nəyi göstərir?",
  "Kiçik əqrəb saatı, böyük əqrəb dəqiqəni göstərir.",
  ["Saatı", "Dəqiqəni", "Saniyəni", "Günü"], 1, None, 2),
 ("Bir gecə-gündüz (sutka) neçə saatdır?",
  "Sutkada 24 saat var.",
  ["24", "12", "60", "7"], 1, str(24), 2),
 ("Həftənin neçə dərs günü var?",
  "Şagirdlər həftədə 5 gün oxuyur.",
  ["5", "7", "6", "4"], 1, None, 1),
 ("Saat 9-dan saat 11-ə qədər neçə saat keçir?",
  "11 − 9 = 2 saat.",
  ["2", "3", "20", "1"], 1, str(11 - 9), 2),
 ("Film saat 3-də başladı və 2 saat çəkdi. Film saat neçədə bitdi?",
  "3 + 2 = 5-də.",
  ["5-də", "6-da", "4-də", "1-də"], 1, "%d-də" % (3 + 2), 2),
 ("Payızdan sonra hansı fəsil gəlir?",
  "Fəsillərin sırası: yaz, yay, payız, qış.",
  ["Qış", "Yaz", "Yay", "Yenə payız"], 1, None, 1),
 ("Bir ay təxminən neçə həftədir?",
  "Ayda təxminən 4 həftə var.",
  ["4", "2", "10", "12"], 1, None, 2),
 ("Böyük əqrəb 6-nın üstündə olanda deyirik: saatın …",
  "30 dəqiqə keçib — saatın yarısıdır.",
  ["yarısı", "tamamı", "rübü", "sonu"], 1, None, 3),
 ("Hansı daha uzundur: 1 saat, yoxsa 100 dəqiqə?",
  "1 saat = 60 dəqiqə; 100 > 60, deməli 100 dəqiqə uzundur.",
  ["100 dəqiqə", "1 saat", "Bərabərdirlər", "Bilmək olmaz"],
  1, None, 3),
 ("Sentyabr ilin neçənci ayıdır?",
  "Sentyabr 9-cu aydır.",
  ["9-cu", "8-ci", "10-cu", "1-ci"], 1, None, 2),
],
"riy-2-olcu": [
 ("1 desimetr neçə santimetrdir?",
  "1 dm = 10 sm.",
  ["10 sm", "100 sm", "1 sm", "5 sm"], 1, "%d sm" % 10, 2),
 ("1 metr neçə desimetrdir?",
  "1 m = 10 dm.",
  ["10 dm", "100 dm", "2 dm", "60 dm"], 1, "%d dm" % 10, 2),
 ("3 metr neçə desimetrdir?",
  "3 × 10 = 30 dm.",
  ["30 dm", "3 dm", "300 dm", "13 dm"], 1, "%d dm" % (3 * 10), 2),
 ("Mayeləri hansı vahidlə ölçürük?",
  "Maye litrlə ölçülür.",
  ["Litrlə", "Metrlə", "Kiloqramla", "Saatla"], 1, None, 1),
 ("Kütləni ölçən cihaz hansıdır?",
  "Kütlə tərəzi ilə ölçülür.",
  ["Tərəzi", "Xətkeş", "Saat", "Stəkan"], 1, None, 1),
 ("Bir səbətdə 5 kq, o birində 3 kq kartof var. Birlikdə neçə "
  "kiloqramdır?",
  "5 + 3 = 8 kq.",
  ["8 kq", "2 kq", "15 kq", "53 kq"], 1, "%d kq" % (5 + 3), 2),
 ("70 sm və 7 dm uzunluqlarını müqayisə edin.",
  "7 dm = 70 sm — bərabərdirlər.",
  ["Bərabərdirlər", "70 sm uzundur", "7 dm uzundur",
   "Müqayisə etmək olmaz"], 1, None, 3),
 ("Qapının hündürlüyünü hansı vahidlə ölçmək əlverişlidir?",
  "Böyük uzunluqlar metrlə ölçülür.",
  ["Metrlə", "Santimetrlə", "Litrlə", "Kiloqramla"], 1, None, 2),
 ("Hansı daha ağırdır: 1 kq dəmir, yoxsa 1 kq pambıq?",
  "Hər ikisi 1 kq-dır — kütlələri bərabərdir.",
  ["Bərabərdirlər", "Dəmir", "Pambıq", "Bilmək olmaz"],
  1, None, 3),
 ("50 sm + 50 sm birlikdə neçə metr edir?",
  "50 + 50 = 100 sm = 1 m.",
  ["1 m", "10 m", "100 m", "55 m"], 1, "%d m" % ((50 + 50) // 100), 3),
],
"riy-2-fiqurlar": [
 ("Düzbucaqlının qarşı tərəfləri necədir?",
  "Düzbucaqlıda qarşı tərəflər bərabərdir.",
  ["Bərabərdir", "Fərqlidir", "Əyridir", "Yoxdur"], 1, None, 2),
 ("Üçbucağın tərəflərinin sayı ilə təpələrinin sayı necədir?",
  "Hər ikisi 3-dür — bərabərdir.",
  ["Bərabərdir — 3 və 3", "Tərəf çoxdur", "Təpə çoxdur",
   "Tərəfi yoxdur"], 1, None, 2),
 ("Hansı fiqurun 4 təpəsi var?",
  "Kvadratın 4 təpəsi var.",
  ["Kvadratın", "Üçbucağın", "Dairənin", "Ovalın"], 1, None, 1),
 ("Kubu kvadratdan nə fərqləndirir?",
  "Kub fəza fiqurudur, kvadrat müstəvi fiqurdur.",
  ["Kub fəza fiqurudur", "Kub daha kiçikdir",
   "Kvadratın üzləri var", "Heç nə"], 1, None, 3),
 ("Konserv bankası hansı fəza fiquruna bənzəyir?",
  "Banka silindr formasındadır.",
  ["Silindrə", "Kuba", "Konusa", "Piramidaya"], 1, None, 2),
 ("Kəpənəyin açılmış qanadları bir-birinə görə necədir?",
  "Qanadlar güzgüdəki kimi eynidir — simmetrikdir.",
  ["Simmetrikdir", "Tamam fərqlidir", "Biri yumrudur",
   "Müqayisə olunmur"], 1, None, 3),
 ("Dairə və kürədən hansı müstəvi fiqurdur?",
  "Dairə müstəvi, kürə fəza fiqurudur.",
  ["Dairə", "Kürə", "Hər ikisi", "Heç biri"], 1, None, 2),
 ("Altıbucaqlının neçə tərəfi var?",
  "Altıbucaqlının 6 tərəfi var.",
  ["6", "5", "8", "3"], 1, str(6), 1),
 ("Yumurta hansı fiqura bənzəyir?",
  "Yumurta oval formadadır.",
  ["Ovala", "Kvadrata", "Üçbucağa", "Düzbucaqlıya"], 1, None, 1),
 ("Sınıq xətt nələrdən ibarətdir?",
  "Sınıq xətt bir-birinə birləşən parçalardan ibarətdir.",
  ["Parçalardan", "Dairələrdən", "Nöqtələrsiz əyridən",
   "Kürələrdən"], 1, None, 2),
],
"riy-2-mesele": [
 ("Rəfdə 45 kitab var idi. 12 kitab götürüldü. Rəfdə neçə kitab qaldı?",
  "45 − 12 = 33.",
  ["33", "34", "57", "43"], 1, str(45 - 12), 1),
 ("Bir boşqabda 5 peçenye var. 3 belə boşqabda birlikdə neçə "
  "peçenye var?",
  "5 × 3 = 15.",
  ["15", "8", "10", "35"], 1, str(5 * 3), 2),
 ("Aysu 27 səhifə oxudu, Tural ondan 5 səhifə az oxudu. Tural "
  "neçə səhifə oxudu?",
  "«5 az» — çıxma deməkdir: 27 − 5 = 22.",
  ["22", "32", "23", "5"], 1, str(27 - 5), 2),
 ("Lalənin 6 qələmi var. Nihadın qələmləri ondan 2 dəfə çoxdur. "
  "Nihadın neçə qələmi var?",
  "«2 dəfə çox» — vurma deməkdir: 6 × 2 = 12.",
  ["12", "8", "4", "62"], 1, str(6 * 2), 3),
 ("Ana 16 konfeti 2 qardaşa bərabər payladı. Hər birinə neçə "
  "konfet düşdü?",
  "16 : 2 = 8.",
  ["8", "14", "18", "32"], 1, str(16 // 2), 2),
 ("Avtobusda 24 sərnişin var idi. 8 nəfər düşdü, 5 nəfər mindi. "
  "İndi avtobusda neçə sərnişin var?",
  "24 − 8 = 16; 16 + 5 = 21.",
  ["21", "11", "27", "16"], 1, str(24 - 8 + 5), 3),
 ("Bir dondurma 1 manatdır. 5 dondurma neçə manatdır?",
  "1 × 5 = 5 manat.",
  ["5 manat", "6 manat", "1 manat", "4 manat"], 1,
  "%d manat" % (1 * 5), 1),
 ("Sinifdə 14 oğlan və 13 qız oxuyur. Sinifdə cəmi neçə şagird var?",
  "14 + 13 = 27.",
  ["27", "26", "1", "28"], 1, str(14 + 13), 1),
 ("Nərminin 90 qəpiyi var idi. 40 qəpiyə çörək aldı. Neçə qəpiyi "
  "qaldı?",
  "90 − 40 = 50 qəpik.",
  ["50 qəpik", "40 qəpik", "60 qəpik", "130 qəpik"], 1,
  "%d qəpik" % (90 - 40), 2),
 ("Hovuzda 9 ördək üzürdü. Daha 7 ördək gəldi. Hovuzda neçə "
  "ördək oldu?",
  "9 + 7 = 16.",
  ["16", "15", "2", "17"], 1, str(9 + 7), 1),
],
# ===================== AZERBAYCAN DILI 2 ==============================
"az-2-soz-novleri": [
 ("Sözlər mənasına görə hansı qruplara bölünür?",
  "Ad, əlamət və hərəkət bildirən sözlərə bölünür.",
  ["Ad, əlamət, hərəkət bildirən sözlərə", "Qısa və uzun sözlərə",
   "Böyük və kiçik sözlərə", "Asan və çətin sözlərə"], 1, None, 2),
 ("«Dovşan» sözü hansı qrupa aiddir?",
  "Dovşan heyvanın adıdır — ad bildirən sözdür.",
  ["Ad bildirən", "Əlamət bildirən", "Hərəkət bildirən",
   "Heç birinə"], 1, None, 1),
 ("«Yumşaq» sözü nə bildirir?",
  "Yumşaq əşyanın əlamətidir.",
  ["Əlamət", "Ad", "Hərəkət", "Say"], 1, None, 1),
 ("«Tullanır» sözü nə bildirir?",
  "Tullanmaq hərəkətdir.",
  ["Hərəkət", "Ad", "Əlamət", "Yer"], 1, None, 1),
 ("«Kim?» sualına hansı sözlər cavab verir?",
  "İnsan bildirən adlar «kim?» sualına cavab verir.",
  ["İnsan bildirən adlar", "Əşya bildirən adlar",
   "Əlamət bildirən sözlər", "Hərəkət bildirən sözlər"],
  1, None, 2),
 ("«Quş — balaca — uçur» sırasında sözlər hansı qaydada düzülüb?",
  "Quş — ad, balaca — əlamət, uçur — hərəkət.",
  ["Ad, əlamət, hərəkət", "Hərəkət, ad, əlamət",
   "Əlamət, ad, hərəkət", "Ad, hərəkət, əlamət"], 1, None, 3),
 ("Cansız əşyanın adına hansı sual verilir?",
  "Əşyalara «nə?» sualı verilir.",
  ["Nə?", "Kim?", "Necə?", "Nə edir?"], 1, None, 2),
 ("«Şirin, turş, duzlu» sözləri nəyi bildirir?",
  "Bu sözlər dadı — əşyanın əlamətini bildirir.",
  ["Dadı (əlaməti)", "Əşyanın adını", "Hərəkəti", "Sayı"],
  1, None, 2),
 ("«Oxuyur» sözünə hansı sualı veririk?",
  "Hərəkət bildirən sözlərə «nə edir?» sualı verilir.",
  ["Nə edir?", "Kim?", "Necə?", "Neçə?"], 1, None, 1),
 ("«Bakı, kitab, quş» sözlərini birləşdirən cəhət nədir?",
  "Üçü də addır — ad bildirən sözlərdir.",
  ["Hamısı ad bildirir", "Hamısı əlamət bildirir",
   "Hamısı hərəkət bildirir", "Ümumi cəhətləri yoxdur"],
  1, None, 2),
],
"az-2-ad-bildiren": [
 ("Ad bildirən sözlər nəyi göstərir?",
  "İnsanların və əşyaların adını göstərir.",
  ["İnsan və əşyaların adını", "Yalnız rəngi",
   "Yalnız hərəkəti", "Yalnız sayı"], 1, None, 1),
 ("Hansı söz əşyanın adıdır?",
  "Stol əşyadır; qırmızı — əlamət, yazır — hərəkətdir.",
  ["stol", "qırmızı", "yazır", "tez"], 1, None, 1),
 ("İnsan bildirən ada hansı sual verilir?",
  "İnsanlara «kim?» sualı verilir.",
  ["Kim?", "Nə?", "Necə?", "Hara?"], 1, None, 1),
 ("«Nə?» sualına cavab verən sözü seçin.",
  "Dəftər əşyadır — «nə?» sualına cavab verir.",
  ["dəftər", "uca", "gülür", "yavaş"], 1, None, 2),
 ("Hansı cərgədə yalnız ad bildirən sözlər var?",
  "Çanta, qayçı, güzgü — hamısı əşya adıdır.",
  ["çanta, qayçı, güzgü", "çanta, təzə, kəsir",
   "qayçı, iti, parlaq", "güzgü, baxır, hamar"], 1, None, 2),
 ("«Həkim» sözü nəyi bildirir?",
  "Həkim peşə sahibidir — insanı bildirir.",
  ["Peşə sahibini (insanı)", "Əşyanı", "Əlaməti", "Hərəkəti"],
  1, None, 2),
 ("Şəhər adları hansı qrupa daxildir?",
  "Şəhər adları da ad bildirən sözlərdir.",
  ["Ad bildirən sözlərə", "Əlamət bildirən sözlərə",
   "Hərəkət bildirən sözlərə", "Heç bir qrupa"], 1, None, 2),
 ("«Çay» sözü neçə mənada işlənə bilər?",
  "Çay həm içki, həm də axar su mənasında işlənir.",
  ["İki mənada", "Yalnız bir mənada", "Heç bir mənada",
   "Yalnız ad kimi işlənmir"], 1, None, 3),
 ("«Quzular» sözü neçə quzunu bildirir?",
  "-lar şəkilçisi çoxluq bildirir: birdən çox.",
  ["Birdən çox", "Yalnız bir", "Heç bir", "Yalnız iki"],
  1, None, 2),
 ("Hansı söz insan adı DEYİL?",
  "Alma meyvədir; Lalə, Samir, Aygün insan adlarıdır.",
  ["alma", "Lalə", "Samir", "Aygün"], 1, None, 3),
],
"az-2-elamet": [
 ("Əlamət bildirən sözlər əşyanın nəyini göstərir?",
  "Rəngini, dadını, formasını, ölçüsünü göstərir.",
  ["Rəngini, dadını, formasını", "Yalnız adını",
   "Yalnız hərəkətini", "Yalnız sayını"], 1, None, 2),
 ("«Cavan» və «qoca» sözləri bir-birinə görə necədir?",
  "Bu sözlər əks mənalıdır.",
  ["Əks mənalıdır", "Eyni mənalıdır", "Hər ikisi addır",
   "Hər ikisi hərəkətdir"], 1, None, 2),
 ("Alma haqqında hansı söz əlamət bildirMİR?",
  "«Yeyilir» hərəkətdir; şirin, qırmızı, yumru əlamətdir.",
  ["yeyilir", "şirin", "qırmızı", "yumru"], 1, None, 3),
 ("«Hündür» sözü hansı suala cavab verir?",
  "Əlamət bildirən sözlərə «necə?» sualı verilir.",
  ["Necə?", "Kim?", "Nə edir?", "Hara?"], 1, None, 1),
 ("Hansı cərgədə yalnız əlamət bildirən sözlər var?",
  "Geniş, təmiz, şirin — hamısı əlamətdir.",
  ["geniş, təmiz, şirin", "geniş, otaq, təmiz",
   "şirin, bal, arı", "təmiz, yuyur, su"], 1, None, 2),
 ("«Dərin göl» ifadəsində hansı söz əlamət bildirir?",
  "Göl necədir? — dərin.",
  ["dərin", "göl", "hər ikisi", "heç biri"], 1, None, 1),
 ("Qarın rəngini bildirən söz hansıdır?",
  "Qar ağ rəngdədir.",
  ["ağ", "soyuq", "yağır", "qış"], 1, None, 1),
 ("«Ağır» sözünün əksi hansı sözdür?",
  "Ağırın əksi yüngüldür.",
  ["yüngül", "böyük", "bərk", "hündür"], 1, None, 2),
 ("Əşyanı dəqiq təsvir etmək üçün hansı sözlərdən istifadə olunur?",
  "Əlamət bildirən sözlər təsviri dəqiqləşdirir.",
  ["Əlamət bildirən sözlərdən", "Yalnız adlardan",
   "Yalnız hərəkət sözlərindən", "Saylardan"], 1, None, 3),
 ("«Dadlı» sözü əşyanın hansı əlamətini bildirir?",
  "Dadlı — dad əlamətidir.",
  ["Dadını", "Rəngini", "Formasını", "Ölçüsünü"], 1, None, 1),
],
"az-2-hereket": [
 ("Hərəkət bildirən sözlər hansı suala cavab verir?",
  "Hərəkət bildirən sözlərə «nə edir?» sualı verilir.",
  ["Nə edir?", "Necə?", "Kim?", "Hansı?"], 1, None, 1),
 ("Hansı söz hərəkət bildirir?",
  "Qaçır — hərəkətdir.",
  ["qaçır", "sürətli", "yol", "idmançı"], 1, None, 1),
 ("«Yarpaq yerə düşdü» cümləsində hərəkət bildirən söz hansıdır?",
  "Yarpaq nə etdi? — düşdü.",
  ["düşdü", "yarpaq", "yerə", "cümlədə belə söz yoxdur"],
  1, None, 2),
 ("Hansı cərgədə yalnız hərəkət bildirən sözlər var?",
  "Yazır, oxuyur, çəkir — hamısı hərəkətdir.",
  ["yazır, oxuyur, çəkir", "yazır, qələm, dəftər",
   "oxuyur, kitab, maraqlı", "çəkir, şəkil, rəngli"], 1, None, 2),
 ("«Gəldi» sözünün əks mənalısı hansıdır?",
  "Gəlmək ↔ getmək.",
  ["getdi", "çatdı", "yaxınlaşdı", "dayandı"], 1, None, 2),
 ("Hansı söz «balıq» sözünə uyğun hərəkətdir?",
  "Balıq suda üzür.",
  ["üzür", "uçur", "qaçır", "oxuyur"], 1, None, 1),
 ("«Danışır» sözü nəyi bildirir?",
  "Danışmaq hərəkətdir.",
  ["Hərəkəti", "Əşyanın adını", "Əlaməti", "Rəngi"], 1, None, 1),
 ("«Aşpaz yemək …» — nöqtələrin yerinə hansı söz uyğundur?",
  "Aşpaz yemək bişirir.",
  ["bişirir", "dadlı", "mətbəx", "qazan"], 1, None, 2),
 ("Hansı söz hərəkət bildirMİR?",
  "«Gözəl» əlamətdir; baxır, gülür, yazır hərəkətdir.",
  ["gözəl", "baxır", "gülür", "yazır"], 1, None, 3),
 ("«Top yuvarlanır» cümləsində hərəkəti edən nədir?",
  "Yuvarlanan topdur.",
  ["Top", "Yuvarlanır", "Cümlə", "Heç nə"], 1, None, 2),
],
"az-2-cumle-novleri": [
 ("Məlumat vermək üçün işlədilən cümlə necə adlanır?",
  "Məlumat bildirən cümlə nəqli cümlədir.",
  ["Nəqli cümlə", "Sual cümləsi", "Nida cümləsi", "Söz birləşməsi"],
  1, None, 2),
 ("«Sən neçənci sinifdə oxuyursan?» — bu hansı cümlədir?",
  "Sual verilir — sual cümləsidir.",
  ["Sual cümləsi", "Nəqli cümlə", "Nida cümləsi", "Cümlə deyil"],
  1, None, 1),
 ("Nida cümləsi nəyi ifadə edir?",
  "Sevinc, təəccüb kimi güclü hissləri bildirir.",
  ["Güclü hissləri", "Adi məlumatı", "Yalnız sualı",
   "Heç nəyi"], 1, None, 2),
 ("«Yaşasın Azərbaycan!» cümləsinin sonunda hansı işarə qoyulub?",
  "Hiss bildirən cümlənin sonunda nida işarəsi olur.",
  ["Nida işarəsi", "Nöqtə", "Sual işarəsi", "Vergül"], 1, None, 2),
 ("Sual cümləsini seçin.",
  "«Hara gedirsən?» — sual verilir.",
  ["Hara gedirsən?", "Hava istidir.", "Nə gözəl çiçək!",
   "Kitabı oxudum."], 1, None, 1),
 ("«Payız gəldi.» cümləsinin növü hansıdır?",
  "Adi məlumat verilir — nəqli cümlədir.",
  ["Nəqli", "Sual", "Nida", "Əmr"], 1, None, 2),
 ("Hansı cümlə sevinc hissi bildirir?",
  "«Nə gözəl gün!» — sevinc ifadə edir.",
  ["Nə gözəl gün!", "Bu gün hava necədir?",
   "Dərs saat 9-da başlayır.", "Kitab stolun üstündədir."],
  1, None, 2),
 ("Sual cümlələrində çox vaxt hansı sözlər işlənir?",
  "Kim, nə, hara, nə vaxt sual sözləridir.",
  ["kim, nə, hara, nə vaxt", "gözəl, şirin, dadlı",
   "gəldi, getdi, gördü", "bir, iki, üç"], 1, None, 2),
 ("«Qapını bağla» cümləsi nəyi bildirir?",
  "Bu cümlə əmr və ya xahiş bildirir.",
  ["Əmr və ya xahişi", "Adi məlumatı", "Sualı", "Təəccübü"],
  1, None, 3),
 ("Cümlənin üç əsas növünü sadalayın.",
  "Cümlələr nəqli, sual və nida cümlələrinə bölünür.",
  ["Nəqli, sual, nida", "Uzun, qısa, orta",
   "Asan, çətin, qarışıq", "Birinci, ikinci, üçüncü"],
  1, None, 2),
],
"az-2-durgu": [
 ("Nöqtə hansı cümlənin sonunda qoyulur?",
  "Nəqli cümlə nöqtə ilə bitir.",
  ["Nəqli cümlənin", "Sual cümləsinin", "Nida cümləsinin",
   "Heç birinin"], 1, None, 1),
 ("Sual işarəsi nə vaxt işlədilir?",
  "Cümlədə sual veriləndə sonda sual işarəsi qoyulur.",
  ["Sual veriləndə", "Sevinc bildiriləndə",
   "Sadalama olanda", "Heç vaxt"], 1, None, 1),
 ("Sadalanan sözlərin arasına hansı işarə qoyulur?",
  "Sadalamada vergül işlənir.",
  ["Vergül", "Nöqtə", "Nida işarəsi", "Sual işarəsi"], 1, None, 2),
 ("«Bazardan alma armud üzüm aldıq» cümləsində hansı işarələr "
  "çatışmır?",
  "Sadalanan sözlərin arasına vergül qoyulmalıdır.",
  ["Vergüllər", "Nöqtələr", "Sual işarələri", "Heç nə çatışmır"],
  1, None, 2),
 ("Nida işarəsi hansı cümlədə düzgün işlənib?",
  "«Ura, qar yağdı!» — sevinc bildirir.",
  ["Ura, qar yağdı!", "Bu gün bazar günüdür!",
   "Sən haralısan!", "Kitab masanın üstündədir!"], 1, None, 3),
 ("Hansı işarə cümlənin bitdiyini göstərir?",
  "Nöqtə cümlənin sonunu bildirir.",
  ["Nöqtə", "Vergül", "Defis", "Dırnaq"], 1, None, 1),
 ("«Sabah hava necə olacaq» — cümlənin sonuna nə qoyulmalıdır?",
  "Sual verilir — sual işarəsi qoyulur.",
  ["Sual işarəsi", "Nöqtə", "Nida işarəsi", "Vergül"], 1, None, 2),
 ("Durğu işarələri nə üçün lazımdır?",
  "Fikri düzgün, aydın çatdırmaq üçün.",
  ["Fikri aydın çatdırmaq üçün", "Yazını uzatmaq üçün",
   "Bəzək üçün", "Heç nə üçün"], 1, None, 2),
 ("Hansı sırada yalnız durğu işarələri sadalanıb?",
  "Nöqtə, vergül, sual işarəsi — durğu işarələridir.",
  ["nöqtə, vergül, sual işarəsi", "hərf, heca, söz",
   "ad, əlamət, hərəkət", "sait, samit, heca"], 1, None, 2),
 ("«Əhməd, kitabı mənə ver» cümləsində vergül nəyi ayırır?",
  "Vergül müraciət olunan şəxsin adını ayırır.",
  ["Müraciəti (çağırışı)", "Sadalamanı", "Cümlənin sonunu",
   "Sualı"], 1, None, 3),
],
"az-2-yazi-qaydasi": [
 ("Sözün düzgün yazılışını seçin.",
  "Düzgün yazılış: çörək.",
  ["çörək", "çorək", "çörəg", "cörək"], 1, None, 2),
 ("Şəxs adları ilə yanaşı daha hansı adlar böyük hərflə yazılır?",
  "Şəhər, kənd, çay adları da böyük hərflə yazılır.",
  ["Şəhər və kənd adları", "Meyvə adları", "Rəng adları",
   "Heç bir ad"], 1, None, 2),
 ("Sətrin sonuna sığmayan sözü nəyə görə bölürük?",
  "Söz yalnız hecalara görə bölünüb keçirilir.",
  ["Hecalara görə", "Hərflərə görə", "İstənilən yerdən",
   "Saitlərinə görə yox, təsadüfi"], 1, None, 2),
 ("Həftə günlərinin adları (bazar ertəsi, cümə…) necə yazılır?",
  "Həftə günlərinin adları kiçik hərflə yazılır.",
  ["Kiçik hərflə", "Böyük hərflə", "Dırnaqda", "Rəqəmlə"],
  1, None, 3),
 ("«Günəşli» sözü hansı sözdən yaranıb?",
  "Günəş sözünə -li şəkilçisi artırılıb.",
  ["günəş", "gün", "şəkil", "işıq"], 1, None, 2),
 ("Hansı söz böyük hərflə yazılmalıdır: (xəzər) dənizi?",
  "Xəzər dənizin xüsusi adıdır.",
  ["Xəzər", "dənizi", "hər ikisi kiçik", "heç biri"], 1, None, 2),
 ("«məktəbə gedirəm» sözləri cümlə kimi yazılanda nə dəyişməlidir?",
  "Cümlə böyük hərflə başlar, sonda nöqtə qoyular.",
  ["Baş hərf böyük olmalı, sonda nöqtə qoyulmalı",
   "Heç nə dəyişməməli", "Bütün hərflər böyük olmalı",
   "Sözlər bitişik yazılmalı"], 1, None, 2),
 ("«Nənə» sözündə neçə «n» hərfi var?",
  "N-ə-n-ə: iki n hərfi.",
  ["2", "1", "3", "4"], 1, str("nənə".count("n")), 1),
 ("Vərəqdə yazıya haradan başlayırıq?",
  "Yazı soldan sağa yazılır.",
  ["Soldan sağa", "Sağdan sola", "Aşağıdan yuxarı",
   "Ortadan"], 1, None, 1),
 ("Hansı say qoşa samitlə yazılır?",
  "«Yeddi» sözündə qoşa d samiti var.",
  ["yeddi", "altı", "beş", "on"], 1, None, 3),
],
# ===================== HEYAT BILGISI 2 ================================
"hey-2-men-mektebim": [
 ("Sinif otağının təmizliyinə kim cavabdehdir?",
  "Sinfin səliqəsi bütün şagirdlərin işidir.",
  ["Bütün şagirdlər", "Yalnız növbətçi", "Yalnız müəllim",
   "Heç kim"], 1, None, 1),
 ("Dərs zamanı müəllimi necə dinləməliyik?",
  "Müəllimi diqqətlə, sözünü kəsmədən dinləmək lazımdır.",
  ["Diqqətlə", "Yataraq", "Danışa-danışa", "Oynayaraq"],
  1, None, 1),
 ("Dərs üçün hansı ləvazimatlar lazımdır?",
  "Kitab, dəftər, qələm əsas dərs ləvazimatlarıdır.",
  ["Kitab, dəftər, qələm", "Top və ip", "Oyuncaqlar",
   "Telefon və planşet"], 1, None, 1),
 ("Növbətçi şagird nə edir?",
  "Növbətçi sinfin səliqəsinə və lövhəyə baxır.",
  ["Sinfin səliqəsinə baxır", "Dərs keçir",
   "Qiymət yazır", "Evə tez gedir"], 1, None, 2),
 ("Tənəffüsdə özümüzü necə aparmalıyıq?",
  "Qaçmadan, başqalarına mane olmadan istirahət etməliyik.",
  ["Mədəni, başqalarına mane olmadan", "Dəhlizdə qaçaraq",
   "Qışqıraraq", "İtələşərək"], 1, None, 2),
 ("Kitabxanadan götürülən kitabla necə davranmalıyıq?",
  "Kitabı səliqəli saxlayıb vaxtında qaytarmaq lazımdır.",
  ["Səliqəli saxlayıb vaxtında qaytarmalıyıq",
   "Səhifələrini qatlamalıyıq", "Üstündə şəkil çəkməliyik",
   "Qaytarmamalıyıq"], 1, None, 2),
 ("Dərs cədvəli nəyi göstərir?",
  "Hansı gün hansı dərslərin olacağını göstərir.",
  ["Günlər üzrə dərsləri", "Hava proqnozunu",
   "Yemək siyahısını", "Qiymətləri"], 1, None, 2),
 ("Yoldaşın dərsi başa düşmürsə, nə etməlisən?",
  "Yoldaşa kömək etmək dostluğun əlamətidir.",
  ["Kömək etməliyəm", "Gülməliyəm", "Müəllimə şikayət etməliyəm",
   "Fikir verməməliyəm"], 1, None, 1),
 ("İnsanlar bir-birindən nə ilə fərqlənir?",
  "Görkəmi, xasiyyəti, maraqları ilə fərqlənir.",
  ["Görkəmi və xasiyyəti ilə", "Heç nə ilə",
   "Yalnız adı ilə", "Yalnız yaşı ilə"], 1, None, 2),
 ("Birlikdə iş görəndə nəyə əməl etməliyik?",
  "İşi bölüşdürüb bir-birimizi dinləməliyik.",
  ["Bir-birimizi dinləməliyik", "Hərə öz bildiyini etməlidir",
   "Yalnız bir nəfər işləməlidir", "Mübahisə etməliyik"],
  1, None, 2),
],
"hey-2-deyerler": [
 ("Dövlətimizin rəmzləri hansılardır?",
  "Bayraq, gerb və himn dövlət rəmzləridir.",
  ["Bayraq, gerb, himn", "Kitab, qələm, dəftər",
   "Dağ, çay, meşə", "Ev, məktəb, bağça"], 1, None, 2),
 ("Dövlət himni səslənəndə nə etməliyik?",
  "Himn səslənəndə ayağa qalxıb hörmətlə dinləmək lazımdır.",
  ["Ayağa qalxıb dinləməliyik", "Oturub danışmalıyıq",
   "Gülməliyik", "Otaqdan çıxmalıyıq"], 1, None, 2),
 ("Düzgünlük (doğruçuluq) nə deməkdir?",
  "Doğruçuluq yalan danışmamaq deməkdir.",
  ["Yalan danışmamaq", "Çox danışmaq", "Sirr saxlamamaq",
   "Tez qaçmaq"], 1, None, 1),
 ("Verdiyin sözü tutmaq nəyin əlamətidir?",
  "Sözünə əməl edən adam etibarlıdır.",
  ["Etibarlılığın", "Qorxaqlığın", "Tənbəlliyin", "Paxıllığın"],
  1, None, 2),
 ("Hər uşağın hansı hüququ var?",
  "Hər uşağın oxumaq (təhsil almaq) hüququ var.",
  ["Təhsil almaq hüququ", "Başqasını incitmək hüququ",
   "Qaydaları pozmaq hüququ", "Heç bir hüququ yoxdur"],
  1, None, 3),
 ("Yalan danışmaq nəyə gətirib çıxarır?",
  "Yalançıya bir daha inanmırlar — etibar itir.",
  ["Etibarın itməsinə", "Dostluğun möhkəmlənməsinə",
   "Hörmətin artmasına", "Heç nəyə"], 1, None, 2),
 ("Sağlam qidalanma necə olmalıdır?",
  "Qidalar müxtəlif və faydalı olmalıdır.",
  ["Müxtəlif və faydalı", "Yalnız şirniyyatdan ibarət",
   "Yalnız çörəkdən ibarət", "Gündə bir dəfə"], 1, None, 2),
 ("Otağı niyə havalandırırıq?",
  "Təmiz hava sağlamlıq üçün lazımdır.",
  ["Təmiz hava üçün", "Səs-küy üçün", "Toz artsın deyə",
   "İşıq gəlsin deyə"], 1, None, 2),
 ("Başqasının əşyasını icazəsiz götürmək olarmı?",
  "İcazəsiz götürmək olmaz — bu, pis əməldir.",
  ["Olmaz", "Olar", "Yalnız gizlicə olar",
   "Yalnız oyuncaqları olar"], 1, None, 1),
 ("Xəstələnəndə kimə müraciət edirik?",
  "Xəstəni həkim müalicə edir.",
  ["Həkimə", "Sürücüyə", "Satıcıya", "Rəssama"], 1, None, 1),
],
"hey-2-materiallar": [
 ("Hansı material təbii materialdır?",
  "Daş təbiətdə hazır şəkildə var; şüşə, plastik, kağız insan "
  "əməyi ilə alınır.",
  ["Daş", "Şüşə", "Plastik", "Kağız"], 1, None, 2),
 ("Dəmir əşyalar hansı xassəyə malikdir?",
  "Dəmir bərk və möhkəmdir.",
  ["Bərkdir və möhkəmdir", "Yumşaqdır", "Şəffafdır",
   "Suda əriyir"], 1, None, 2),
 ("Süngər suya salınanda nə edir?",
  "Süngər suyu hopdurur (canına çəkir).",
  ["Suyu hopdurur", "Suyu itələyir", "Suyu dondurur",
   "Suyu qaynadır"], 1, None, 2),
 ("Plastilindən nə üçün asanlıqla fiqur düzəltmək olur?",
  "Plastilin yumşaqdır və istənilən formanı alır.",
  ["Yumşaq olduğu üçün", "Bərk olduğu üçün",
   "Şəffaf olduğu üçün", "Maqnit olduğu üçün"], 1, None, 2),
 ("Odun yanında hansı material tez alışdığı üçün təhlükəlidir?",
  "Kağız tez alışan materialdır.",
  ["Kağız", "Daş", "Dəmir", "Şüşə"], 1, None, 2),
 ("Buz otaq istiliyində nə olur?",
  "Buz istidə əriyib suya çevrilir.",
  ["Əriyir", "Bərkiyir", "Böyüyür", "Dəyişmir"], 1, None, 1),
 ("Su donanda nəyə çevrilir?",
  "Soyuqda su buza çevrilir.",
  ["Buza", "Buxara", "Duza", "Yağa"], 1, None, 1),
 ("Qayçı ilə işləyərkən nəyə diqqət etməliyik?",
  "İti alətlərlə ehtiyatla işləmək lazımdır.",
  ["Ehtiyatlı olmağa", "Sürətli olmağa", "Gözüyumulu işləməyə",
   "Heç nəyə"], 1, None, 1),
 ("Elektrik cihazlarını kim işə salmalıdır?",
  "Uşaqlar elektrik cihazlarını böyüklərin nəzarəti ilə işlətməlidir.",
  ["Böyüklər və ya onların nəzarəti ilə uşaqlar",
   "Uşaqlar təkbaşına", "Heç kim", "Yalnız qonaqlar"], 1, None, 2),
 ("Dəmir qaşıq suya salınanda nə baş verir?",
  "Dəmir sudan ağırdır — batır.",
  ["Batır", "Üzür", "Əriyir", "Buxarlanır"], 1, None, 3),
],
"hey-2-yer-kuresi": [
 ("Hansı göy cismi işıq mənbəyidir?",
  "Günəş özü işıq saçır — işıq mənbəyidir.",
  ["Günəş", "Ay", "Yer", "Buludlar"], 1, None, 2),
 ("Süni işıq mənbəyi hansıdır?",
  "Lampanı insan yaradıb — süni mənbədir.",
  ["Lampa", "Günəş", "Ulduzlar", "İldırım"], 1, None, 2),
 ("Yer hansı sistemin planetidir?",
  "Yer Günəş sisteminin planetidir.",
  ["Günəş sisteminin", "Ay sisteminin", "Ulduz yağışının",
   "Heç bir sistemin"], 1, None, 3),
 ("Yer kürəsinin səthinin çox hissəsini nə örtür?",
  "Yerin çox hissəsi su ilə örtülüdür.",
  ["Su", "Qum", "Meşə", "Buz"], 1, None, 2),
 ("Xəritədə və qlobusda su hansı rənglə göstərilir?",
  "Dənizlər və okeanlar mavi rənglə göstərilir.",
  ["Mavi", "Yaşıl", "Qəhvəyi", "Qırmızı"], 1, None, 2),
 ("Yerin quru hissəsində nələr yerləşir?",
  "Quruda dağlar, düzənliklər, meşələr var.",
  ["Dağlar və düzənliklər", "Yalnız okeanlar",
   "Yalnız buludlar", "Heç nə"], 1, None, 2),
 ("Gecə göy üzündə nələri görürük?",
  "Gecə Ay və ulduzlar görünür.",
  ["Ayı və ulduzları", "Günəşi", "Göy qurşağını",
   "Heç nəyi"], 1, None, 1),
 ("Canlılar su olmadan yaşaya bilərmi?",
  "Su bütün canlılar üçün həyat mənbəyidir.",
  ["Yaşaya bilməz", "Yaşayar", "Yalnız qışda yaşayar",
   "Yalnız heyvanlar yaşayar"], 1, None, 1),
 ("Şəhəri kənddən fərqləndirən əsas cəhət nədir?",
  "Şəhərdə çoxmərtəbəli binalar və çoxlu insan olur.",
  ["Çoxmərtəbəli binalar və çox insan", "Təmiz hava",
   "Heyvanların çoxluğu", "Bağların çoxluğu"], 1, None, 2),
 ("Çaylar axıb hara tökülür?",
  "Çaylar dənizlərə və göllərə tökülür.",
  ["Dənizlərə və göllərə", "Dağlara", "Buludlara",
   "Quyulara"], 1, None, 2),
],
"hey-2-canlilar": [
 ("Bitkilər, heyvanlar və insanlar hansı qrupa aiddir?",
  "Hamısı qidalanır, böyüyür, çoxalır — canlıdır.",
  ["Canlılara", "Cansızlara", "Əşyalara", "Materiallara"],
  1, None, 1),
 ("Bitkinin hansı hissəsi torpağın altında olur?",
  "Kök torpağın altındadır.",
  ["Kökü", "Gövdəsi", "Yarpağı", "Çiçəyi"], 1, None, 1),
 ("Toxum əkiləndə ondan nə çıxır?",
  "Toxumdan cücərti çıxıb bitkiyə çevrilir.",
  ["Cücərti", "Daş", "Yumurta", "Heç nə"], 1, None, 2),
 ("Hansı heyvan ev heyvanıdır?",
  "İnəyə insan qulluq edir — ev heyvanıdır.",
  ["İnək", "Canavar", "Tülkü", "Ayı"], 1, None, 1),
 ("Hansı heyvan vəhşi heyvandır?",
  "Canavar meşədə sərbəst yaşayır.",
  ["Canavar", "İnək", "Toyuq", "Qoyun"], 1, None, 1),
 ("Quşların bədəni nə ilə örtülüdür?",
  "Quşların bədənini lələk örtür.",
  ["Lələklə", "Tüklə deyil, pulcuqla", "Yalnız dəri ilə",
   "Qabıqla"], 1, None, 2),
 ("Balıqlar harada yaşayır?",
  "Balıqlar yalnız suda yaşaya bilir.",
  ["Suda", "Meşədə", "Səhrada", "Yuvada"], 1, None, 1),
 ("İnəyin balası necə adlanır?",
  "İnəyin balası buzovdur.",
  ["Buzov", "Quzu", "Çəpiş", "Bala it"], 1, None, 2),
 ("Bitkinin böyüməsi üçün nə lazımdır?",
  "Bitkiyə işıq, su və hava lazımdır.",
  ["İşıq, su və hava", "Yalnız qaranlıq", "Yalnız külək",
   "Musiqi"], 1, None, 2),
 ("Hansı heyvan qışda yuxuya gedir?",
  "Ayı qış yuxusuna yatır.",
  ["Ayı", "Sərçə", "İnək", "At"], 1, None, 2),
],
"hey-2-ehtiyat": [
 ("Velosiped sürərkən başımıza nə taxmalıyıq?",
  "Dəbilqə başı zədədən qoruyur.",
  ["Dəbilqə", "Papaq", "Heç nə", "Yaylıq"], 1, None, 1),
 ("Açıq elektrik naqilinə toxunmaq niyə təhlükəlidir?",
  "Cərəyan vura bilər.",
  ["Cərəyan vurar", "Rəngi əlimizə keçər", "Soyuqdur",
   "Heç bir təhlükəsi yoxdur"], 1, None, 2),
 ("Yol maşınlar üçündür, bəs səki kimlər üçündür?",
  "Səki ilə piyadalar gedir.",
  ["Piyadalar üçün", "Velosipedlər üçün", "Maşınlar üçün",
   "Heç kim üçün"], 1, None, 1),
 ("Suda batan adamı görən uşaq nə etməlidir?",
  "Özü suya atılmamalı, dərhal böyükləri çağırmalıdır.",
  ["Böyükləri çağırmalıdır", "Özü suya atılmalıdır",
   "Baxıb getməlidir", "Şəkil çəkməlidir"], 1, None, 3),
 ("Meşədə tapılan naməlum göbələyi yığmaq olarmı?",
  "Naməlum göbələk zəhərli ola bilər.",
  ["Olmaz — zəhərli ola bilər", "Olar", "Yalnız yağışdan sonra olar",
   "Yalnız böyük göbələkləri olar"], 1, None, 2),
 ("Mağazada azıb ailəsini itirən uşaq nə etməlidir?",
  "Yerindən uzaqlaşmayıb işçidən və ya polisdən kömək istəməlidir.",
  ["İşçidən və ya polisdən kömək istəməlidir",
   "Ağlayıb qaçmalıdır", "Tanımadığı adamla getməlidir",
   "Gizlənməlidir"], 1, None, 2),
 ("Kibrit və alışqanla oynamaq nəyə səbəb ola bilər?",
  "Od yanğına səbəb olur.",
  ["Yanğına", "Sevincə", "Oyunun maraqlı olmasına",
   "Heç nəyə"], 1, None, 1),
 ("Təmizlik vasitələri (kimyəvi maddələr) harada saxlanmalıdır?",
  "Uşaqların əli çatmayan yerdə saxlanmalıdır.",
  ["Uşaqların əli çatmayan yerdə", "Yemək rəfində",
   "Oyuncaqların içində", "Stolun üstündə"], 1, None, 2),
 ("Bütün təhlükəli hallar üçün vahid çağrı nömrəsi hansıdır?",
  "112 — vahid təcili çağırış nömrəsidir.",
  ["112", "212", "911 deyil, 511", "100"], 1, None, 3),
 ("Kağıza qənaət etmək üçün nə etmək olar?",
  "Vərəqin hər iki üzündən istifadə etmək olar.",
  ["Vərəqin hər iki üzünə yazmaq", "Vərəqləri cırıb atmaq",
   "Təzə dəftər almaq", "Heç nə yazmamaq"], 1, None, 2),
],
# ======================= INFORMATIKA 2 ================================
"inf-2-obyekt": [
 ("İnformatikada ətrafımızdakı əşya və varlıqlar necə adlanır?",
  "Ətrafımızdakı hər şey obyekt adlanır.",
  ["Obyekt", "Proqram", "Rəqəm", "Cümlə"], 1, None, 1),
 ("Obyekti tanımaq üçün nəyi bilmək lazımdır?",
  "Obyekt əlamətləri ilə tanınır.",
  ["Əlamətlərini", "Qiymətini", "Yaşını", "Səsini"], 1, None, 2),
 ("Hansı obyekt insan əli ilə yaradılıb?",
  "Evi insan tikir; dağ, çay, ağac təbiət obyektləridir.",
  ["Ev", "Dağ", "Çay", "Ağac"], 1, None, 2),
 ("Hansı obyekt təbiət obyektidir?",
  "Çay təbiətdə özü yaranıb.",
  ["Çay", "Stol", "Maşın", "Telefon"], 1, None, 2),
 ("«Quş uçur» — burada obyektin nəyi göstərilib?",
  "Uçmaq quşun hərəkətidir.",
  ["Hərəkəti", "Rəngi", "Ölçüsü", "Qiyməti"], 1, None, 2),
 ("Obyektləri bir qrupda birləşdirmək üçün onların nəyi olmalıdır?",
  "Qrup oxşar əlamətlərə görə yaradılır.",
  ["Oxşar əlamətləri", "Eyni rəngi olması vacibdir",
   "Eyni qiyməti", "Heç nəyi"], 1, None, 2),
 ("«Alma, armud, gavalı» obyektlərini hansı ad altında birləşdirmək "
  "olar?",
  "Üçü də meyvədir.",
  ["Meyvələr", "Tərəvəzlər", "Oyuncaqlar", "Geyimlər"],
  1, None, 1),
 ("Hansı obyekt «nəqliyyat» qrupuna aid DEYİL?",
  "Ağac bitkidir; avtobus, qatar, gəmi nəqliyyatdır.",
  ["Ağac", "Avtobus", "Qatar", "Gəmi"], 1, None, 2),
 ("İki obyekti fərqləndirmək üçün nəyə baxırıq?",
  "Fərqləndirici əlamətlərinə baxırıq.",
  ["Fərqli əlamətlərinə", "Yalnız adlarına",
   "Yalnız yerlərinə", "Heç nəyə"], 1, None, 3),
 ("«Sərçə, qartal, göyərçin» qrupuna daha hansı obyekt uyğundur?",
  "Qrup quşlardan ibarətdir — qaranquş da quşdur.",
  ["Qaranquş", "Kəpənək", "Balıq", "Dovşan"], 1, None, 3),
],
"inf-2-informasiya": [
 ("Mətn, şəkil və səs — bunlar nəyin formalarıdır?",
  "İnformasiya mətn, şəkil, səs formasında olur.",
  ["İnformasiyanın", "Oyunun", "Əşyanın", "Rəngin"], 1, None, 2),
 ("Kitabdakı yazı hansı formada informasiyadır?",
  "Yazı mətn formasında informasiyadır.",
  ["Mətn", "Səs", "Video", "Qoxu"], 1, None, 1),
 ("Dərslikdəki xəritə hansı formada informasiyadır?",
  "Xəritə qrafik (şəkil) informasiyadır.",
  ["Şəkil (qrafik)", "Səs", "Mətn", "Rəqəm deyil, dad"],
  1, None, 2),
 ("Qədim insanlar məlumatı saxlamaq üçün nəyin üzərinə yazırdılar?",
  "Qədimdə daş və gil lövhələrə yazırdılar.",
  ["Daş və gil lövhələrə", "Kompüterə", "Telefona",
   "Televizora"], 1, None, 2),
 ("Müasir dövrdə informasiya ən çox nə ilə ötürülür?",
  "İndi məlumat telefon və internetlə ötürülür.",
  ["Telefon və internetlə", "Göyərçinlə", "Tonqal tüstüsü ilə",
   "Çaparla"], 1, None, 2),
 ("Yaddaş kartı (fləş kart) nə üçündür?",
  "İnformasiyanı saxlamaq üçün qurğudur.",
  ["İnformasiyanı saxlamaq üçün", "Yemək bişirmək üçün",
   "Şəkil çəkmək üçün", "Otağı işıqlandırmaq üçün"], 1, None, 2),
 ("Şagird kitab oxuyur. O, informasiyanı nə edir?",
  "Oxuyan adam informasiyanı qəbul edir (alır).",
  ["Qəbul edir", "Ötürür", "Silir", "İtirir"], 1, None, 3),
 ("Müəllim mövzunu danışır. O, informasiyanı nə edir?",
  "Danışan adam informasiyanı ötürür.",
  ["Ötürür", "Qəbul edir", "Saxlayır", "Gizlədir"], 1, None, 3),
 ("Hansı cihazla səsi yazıb saxlamaq olar?",
  "Diktofon (telefonun səsyazması) səsi yazır.",
  ["Diktofonla", "Xətkeşlə", "Tərəzi ilə", "Qayçı ilə"],
  1, None, 2),
 ("Multfilm hansı informasiya formalarını birləşdirir?",
  "Multfilmdə həm görüntü, həm səs var.",
  ["Şəkil və səsi", "Yalnız mətni", "Yalnız qoxunu",
   "Heç birini"], 1, None, 2),
],
"inf-2-alqoritm": [
 ("Müəyyən işi görmək üçün addımların ardıcıllığı necə adlanır?",
  "Ardıcıl addımlar alqoritm adlanır.",
  ["Alqoritm", "Cümlə", "Oyun", "Rəqəm"], 1, None, 1),
 ("Alqoritmin hər bir göstərişi necə adlanır?",
  "Alqoritm addımlardan (əmrlərdən) ibarətdir.",
  ["Addım (əmr)", "Hərf", "Səhifə", "Şəkil"], 1, None, 2),
 ("Süd içmək alqoritmində ilk addım hansıdır?",
  "Əvvəlcə stəkana süd tökülür, sonra içilir.",
  ["Stəkana süd tökmək", "Stəkanı yumaq", "Südü içmək",
   "Stəkanı yerinə qoymaq"], 1, None, 2),
 ("«Sağa dön, 2 addım irəli get» — bunlar nədir?",
  "İcraçıya verilən əmrlərdir.",
  ["İcraçıya verilən əmrlər", "Tapmacalar", "Nağıl",
   "Mahnı sözləri"], 1, None, 2),
 ("Robot hansı göstərişləri yerinə yetirir?",
  "Robot yalnız ona verilən əmrləri icra edir.",
  ["Ona verilən əmrləri", "Öz istədiyini",
   "Heç bir göstərişi", "Yalnız səsli musiqini"], 1, None, 2),
 ("Alqoritmi yerinə yetirən şəxs və ya qurğu necə adlanır?",
  "Alqoritmi icra edən icraçı adlanır.",
  ["İcraçı", "Tamaşaçı", "Müəllif", "Rəssam"], 1, None, 2),
 ("«5 böyükdür 3-dən» mülahizəsi necə mülahizədir?",
  "5 həqiqətən 3-dən böyükdür — mülahizə doğrudur.",
  ["Doğru", "Yalan", "Qeyri-müəyyən", "Sual"], 1, None, 2),
 ("«Sabah yağış yağacaq» mülahizəsi necə mülahizədir?",
  "Sabahkı hava dəqiq bilinmir — mülahizə qeyri-müəyyəndir.",
  ["Qeyri-müəyyən", "Doğru", "Yalan", "Əmr"], 1, None, 3),
 ("Evdən məktəbə bir neçə yol var. Alqoritm üçün adətən hansı yol "
  "seçilir?",
  "Ən qısa və təhlükəsiz yol seçilir.",
  ["Ən qısa təhlükəsiz yol", "Ən uzun yol", "Ən dar yol",
   "Təsadüfi yol"], 1, None, 3),
 ("Çanta yığmaq alqoritmi hansı addımla bitir?",
  "Ləvazimat yığılandan sonra çanta bağlanır.",
  ["Çantanı bağlamaq", "Kitabları çıxarmaq", "Çantanı açmaq",
   "Dəftər almaq"], 1, None, 2),
],
"inf-2-kompyuter": [
 ("Kompüterin «beyni» adlandırılan hissəsi hansıdır?",
  "Prosessor bütün hesablamaları aparır.",
  ["Prosessor", "Monitor", "Maus", "Naqil"], 1, None, 3),
 ("Skaner nə edir?",
  "Skaner kağızdakı şəkli və yazını kompüterə köçürür.",
  ["Kağızdakı şəkli kompüterə köçürür", "Səs yazır",
   "Mətni kağıza çapır", "Otağı işıqlandırır"], 1, None, 2),
 ("Dinamiklər nə üçündür?",
  "Dinamiklər səsi eşitdirir.",
  ["Səsi eşitdirmək üçün", "Şəkil göstərmək üçün",
   "Yazı yazmaq üçün", "Kağız kəsmək üçün"], 1, None, 1),
 ("Mikrofon nə üçün istifadə olunur?",
  "Mikrofon səsi kompüterə daxil edir.",
  ["Səsi kompüterə daxil etmək üçün", "Səsi eşitdirmək üçün",
   "Şəkil çəkmək üçün", "Mətni silmək üçün"], 1, None, 2),
 ("Kompüter işə düşəndə ekranda açılan əsas görüntü necə adlanır?",
  "Əsas ekran iş masası adlanır.",
  ["İş masası", "Pəncərə deyil, qapı", "Kitab səhifəsi",
   "Lövhə"], 1, None, 3),
 ("Kompüterdə şəkil çəkmək üçün hansı proqramdan istifadə olunur?",
  "Şəkil qrafik redaktorda çəkilir.",
  ["Qrafik redaktordan", "Kalkulyatordan", "Saatdan",
   "Musiqi pleyerindən"], 1, None, 2),
 ("Mausun sol düyməsini iki dəfə ardıcıl basmaq necə adlanır?",
  "İki ardıcıl basma ikiqat klik adlanır.",
  ["İkiqat klik", "Uzun basma", "Sürüşdürmə", "Yazma"],
  1, None, 3),
 ("Kompüter sinfində hansı qaydaya əməl edilməlidir?",
  "Yaş əllə cihazlara toxunmaq olmaz.",
  ["Yaş əllə cihaza toxunmamaq", "Qaçıb oynamaq",
   "Naqilləri dartmaq", "Ekrana barmaqla döymək"], 1, None, 2),
 ("İşi bitirəndə kompüteri necə söndürməliyik?",
  "Kompüter qaydasına uyğun söndürülməlidir.",
  ["Qaydasına uyğun, düzgün", "Naqili dartmaqla",
   "Ekranı örtməklə", "Söndürməyə ehtiyac yoxdur"], 1, None, 2),
 ("Gözlərin yorulmaması üçün fasilədə nə etmək faydalıdır?",
  "Ekrandan ayrılıb uzağa baxmaq gözləri dincəldir.",
  ["Uzağa baxmaq", "Ekrana daha yaxın baxmaq",
   "Gözləri ovuşdurub davam etmək", "Qaranlıqda oturmaq"],
  1, None, 3),
],
}


ELAVE_AZ_HEY = {
"az-2-ad-bildiren": [
 ("Peşə bildirən sözü seçin.",
  "«Müəllim» peşə sahibini bildirir.",
  ["müəllim", "yaşıl", "qaçır", "şirin"], 1, None, 1),
 ("İnsan bildirən sözü seçin.",
  "«Şagird» insan bildirir, «kim?» sualına cavab verir.",
  ["şagird", "daş", "külək", "kitab"], 1, None, 1),
 ("Heyvan adı bildirən söz hansıdır?",
  "«Dovşan» heyvan adıdır.",
  ["dovşan", "sürətli", "tullanır", "yumşaq"], 1, None, 1),
 ("«Bağça» sözü nəyi bildirir?",
  "Bağça yerin adını bildirir.",
  ["Yerin adını", "Hərəkəti", "Əlaməti", "Sayı"], 1, None, 2),
 ("Hansı cərgədə yalnız heyvan adları var?",
  "At, dəvə, keçi — hamısı heyvandır.",
  ["at, dəvə, keçi", "at, yəhər, çöl", "keçi, ot, süd",
   "dəvə, isti, qum"], 1, None, 2),
 ("«Qələmlər» sözü neçə əşyanı bildirir?",
  "-lər şəkilçisi çoxluq bildirir.",
  ["Birdən çoxunu", "Yalnız birini", "Heç birini",
   "Yarısını"], 1, None, 2),
 ("Hansı söz bitki adıdır?",
  "«Palıd» ağac — bitki adıdır.",
  ["palıd", "uçur", "hündür", "qaya"], 1, None, 2),
 ("«Müəllim, həkim, aşpaz» sözlərinin ümumi cəhəti nədir?",
  "Hamısı peşə bildirən sözlərdir.",
  ["Hamısı peşə bildirir", "Hamısı heyvan adıdır",
   "Hamısı hərəkətdir", "Hamısı rəngdir"], 1, None, 2),
 ("Əşya adlarına hansı sual verilir?",
  "Cansız əşyalara «nə?» sualı verilir.",
  ["Nə?", "Kim?", "Necə?", "Nə edir?"], 1, None, 1),
 ("«Ayı» sözü hansı sözlər qrupundandır?",
  "Heyvan adı — ad bildirən sözdür.",
  ["Ad bildirən sözlərdən", "Əlamət bildirənlərdən",
   "Hərəkət bildirənlərdən", "Heç birindən"], 1, None, 2),
],
"az-2-cumle-novleri": [
 ("«Qar nə gözəl yağır!» — bu hansı cümlədir?",
  "Hiss-həyəcan bildirir — nida cümləsidir.",
  ["Nida cümləsi", "Sual cümləsi", "Nəqli cümlə",
   "Söz birləşməsi"], 1, None, 2),
 ("«Kitabı oxudunmu?» cümləsinin növü hansıdır?",
  "Sual verilir — sual cümləsidir.",
  ["Sual cümləsi", "Nəqli cümlə", "Nida cümləsi",
   "Əmr cümləsi"], 1, None, 1),
 ("Xahiş bildirən cümləyə misal hansıdır?",
  "«Zəhmət olmasa» sözü xahiş bildirir.",
  ["Zəhmət olmasa, qapını ört.", "Qapı bağlıdır.",
   "Qapı hara açılır?", "Nə möhkəm qapı!"], 1, None, 2),
 ("Nəqli cümləyə misal hansıdır?",
  "Məlumat verir, sonunda nöqtə qoyulur.",
  ["Hava bu gün istidir.", "Hava necədir?",
   "Nə isti hava!", "Pəncərəni aç!"], 1, None, 2),
 ("«Əla, qalib gəldik!» cümləsi hansı hissi bildirir?",
  "Cümlə sevinc hissini ifadə edir.",
  ["Sevinci", "Kədəri", "Qorxunu", "Yorğunluğu"], 1, None, 2),
 ("«Sabah hara gedəcəyik?» sualına uyğun cavab cümləsi hansıdır?",
  "Suala nəqli cümlə ilə cavab verilir.",
  ["Sabah muzeyə gedəcəyik.", "Hara gedirsən?",
   "Nə yaxşı!", "Get!"], 1, None, 2),
 ("Hansı cümlədə qorxu hissi ifadə olunub?",
  "«Vay» nidası qorxu bildirir.",
  ["Vay, ilan!", "İlan sürünür.", "İlan haradadır?",
   "İlanlar uzundur."], 1, None, 2),
 ("Cümlənin növü nəyə görə müəyyənləşir?",
  "Cümlələr məqsədinə görə növlərə ayrılır.",
  ["Məqsədinə görə", "Uzunluğuna görə", "Hərf sayına görə",
   "Rənginə görə"], 1, None, 3),
 ("«Dur ayağa!» cümləsi nə bildirir?",
  "Bu cümlə əmr bildirir.",
  ["Əmri", "Məlumatı", "Sualı", "Təəccübü"], 1, None, 2),
 ("Danışıqda səsin yüksəlib-alçalması nəyi dəyişə bilər?",
  "İntonasiya cümlənin məqsədini dəyişə bilər.",
  ["Cümlənin məqsədini", "Hərflərin sayını",
   "Sözlərin yazılışını", "Heç nəyi"], 1, None, 3),
],
"az-2-durgu": [
 ("«Yaşasın sülh» cümləsinin sonuna hansı işarə qoyulmalıdır?",
  "Nida cümləsidir — nida işarəsi qoyulur.",
  ["Nida işarəsi", "Nöqtə", "Vergül", "Heç nə"], 1, None, 2),
 ("Vergül hansı hallarda işlədilir?",
  "Sadalamada və müraciətdən sonra vergül qoyulur.",
  ["Sadalamada və müraciətdə", "Cümlənin sonunda",
   "Hər sözdən sonra", "Heç vaxt"], 1, None, 2),
 ("«Aslan, sən hara gedirsən?» cümləsində vergül nədən sonra qoyulub?",
  "Müraciət olunan addan sonra vergül qoyulur.",
  ["Müraciətdən sonra", "Feldən sonra", "Sual sözündən sonra",
   "Təsadüfən"], 1, None, 3),
 ("Hansı cümlədə durğu işarəsi düzgün qoyulub?",
  "Sual cümləsinin sonunda sual işarəsi olmalıdır.",
  ["Sən kitabı oxudunmu?", "Sən kitabı oxudunmu.",
   "Sən kitabı, oxudunmu", "Sən kitabı oxudunmu,"], 1, None, 2),
 ("«Mağazadan çörək, süd, yağ aldıq» cümləsində vergüllər nəyi ayırır?",
  "Vergüllər sadalanan sözləri ayırır.",
  ["Sadalanan sözləri", "Cümlələri", "Hecaları",
   "Hərfləri"], 1, None, 2),
 ("Nöqtə, sual və nida işarələri harada qoyulur?",
  "Bu işarələr cümlənin sonunda qoyulur.",
  ["Cümlənin sonunda", "Cümlənin əvvəlində",
   "Sözün ortasında", "Sətrin əvvəlində"], 1, None, 1),
 ("«Ah necə gözəl mənzərə» cümləsində hansı işarələr çatışmır?",
  "Nidadan sonra vergül, cümlənin sonunda nida işarəsi olmalıdır.",
  ["Vergül və nida işarəsi", "İki nöqtə", "Sual işarəsi",
   "Heç nə"], 1, None, 3),
 ("Cümlənin sonundakı işarəni görməsək, nəyi bilmərik?",
  "Sonda hansı işarənin olması cümlənin məqsədini göstərir.",
  ["Cümlənin məqsədini", "Sözlərin sayını", "Hərfləri",
   "Hecaları"], 1, None, 3),
 ("«Adın nədir» yazısını cümləyə çevirmək üçün sona nə əlavə olunmalıdır?",
  "Sual cümləsidir — sual işarəsi qoyulmalıdır.",
  ["Sual işarəsi", "Nöqtə", "Vergül", "Defis"], 1, None, 2),
 ("Kitab adları yazıda nə ilə fərqləndirilir?",
  "Əsər adları dırnaq içində yazılır.",
  ["Dırnaq işarəsi ilə", "Nida işarəsi ilə", "Nöqtə ilə",
   "Rəqəmlə"], 1, None, 3),
],
"az-2-elamet": [
 ("«İsti çay» ifadəsində əlamət bildirən söz hansıdır?",
  "«İsti» çayın əlamətini bildirir.",
  ["isti", "çay", "ifadə", "söz"], 1, None, 1),
 ("«Qoca» sözünün əks mənalısı hansıdır?",
  "Qoca — cavan əks mənalıdır.",
  ["cavan", "yaşlı", "böyük", "hündür"], 1, None, 2),
 ("Limonun dadını bildirən söz hansıdır?",
  "Limon turşdur.",
  ["turş", "sarı", "yumru", "kiçik"], 1, None, 1),
 ("«Balaca» sözünə hansı sualı veririk?",
  "Əlamət bildirən sözlərə «necə?» sualı verilir.",
  ["Necə?", "Kim?", "Nə edir?", "Hara?"], 1, None, 2),
 ("Formanı bildirən söz hansıdır?",
  "«Yumru» əşyanın formasını bildirir.",
  ["yumru", "şirin", "səsli", "sürətli"], 1, None, 2),
 ("«Şirin söz» ifadəsində «şirin» nəyi bildirir?",
  "Burada «şirin» sözün xoş olduğunu bildirir.",
  ["Sözün xoş olduğunu", "Sözün dadını", "Sözün rəngini",
   "Sözün sayını"], 1, None, 3),
 ("Hansı cərgədə əks mənalı sözlər cütü verilib?",
  "Böyük və kiçik əks mənalıdır.",
  ["böyük — kiçik", "böyük — iri", "kiçik — balaca",
   "geniş — enli"], 1, None, 2),
 ("Pambıq hansı rəngdədir?",
  "Pambıq ağ rəngdədir.",
  ["ağ", "qara", "göy", "qırmızı"], 1, None, 1),
 ("«Uzun ip» və «qısa ip» — iplər nəyə görə fərqlənir?",
  "İplər uzunluğuna görə fərqlənir.",
  ["Uzunluğuna görə", "Rənginə görə", "Dadına görə",
   "Səsinə görə"], 1, None, 2),
 ("Əlamət bildirən sözlər nitqi necə edir?",
  "Belə sözlər nitqi dəqiq və zəngin edir.",
  ["Daha dəqiq və zəngin", "Qarışıq", "Yoxsul",
   "Mənasız"], 1, None, 2),
],
"az-2-hereket": [
 ("«Uçur» sözü hansı canlıya uyğundur?",
  "Quş uçur.",
  ["quşa", "balığa", "ilana", "qarışqaya"], 1, None, 1),
 ("«Yazır, pozur, çəkir» sözlərinin ümumi cəhəti nədir?",
  "Hamısı hərəkət bildirir.",
  ["Hamısı hərəkət bildirir", "Hamısı ad bildirir",
   "Hamısı əlamət bildirir", "Hamısı rəngdir"], 1, None, 2),
 ("«Oxuyur» sözünün əvvəlinə hansı sözü artırsaq cümlə alınar?",
  "«Şagird oxuyur» — bitmiş fikir alınır.",
  ["Şagird", "Yaşıl", "Şirin", "Beş"], 1, None, 2),
 ("Cümləni tamamlayın: «Külək …»",
  "Küləyin hərəkəti: əsir.",
  ["əsir", "yağır", "oxuyur", "bişirir"], 1, None, 1),
 ("«Açır» sözünün əksi hansıdır?",
  "Açır — bağlayır əks mənalıdır.",
  ["bağlayır", "itələyir", "silir", "yuyur"], 1, None, 2),
 ("İtin hərəkətinə uyğun söz hansıdır?",
  "İt hürür.",
  ["hürür", "miyoldayır", "uçur", "üzür"], 1, None, 1),
 ("«Yağış …» cümləsini hansı söz tamamlayır?",
  "Yağış yağır.",
  ["yağır", "əsir", "oxuyur", "gülür"], 1, None, 1),
 ("Hansı sözə «nə edir?» sualı vermək olar?",
  "«Qaçır» hərəkət bildirir.",
  ["qaçır", "hündür", "meşə", "sarı"], 1, None, 1),
 ("«Süpürür» hərəkətini adətən nə ilə edirlər?",
  "Döşəməni süpürgə ilə süpürürlər.",
  ["Süpürgə ilə", "Qaşıqla", "Kitabla", "Şarla"], 1, None, 2),
 ("«Dayandı» sözü hərəkətin nəyini bildirir?",
  "Hərəkətin bitdiyini bildirir.",
  ["Bitdiyini", "Başladığını", "Sürətini", "Rəngini"],
  1, None, 3),
],
"az-2-soz-novleri": [
 ("«Pişik», «yumşaq», «miyoldayır» sözlərini qruplara ayırın: hansı düzgündür?",
  "Pişik — ad, yumşaq — əlamət, miyoldayır — hərəkət.",
  ["Ad, əlamət, hərəkət", "Hərəkət, ad, əlamət",
   "Əlamət, hərəkət, ad", "Hamısı addır"], 1, None, 3),
 ("«Göy» sözü hansı qrupa aiddir?",
  "Rəng bildirir — əlamət bildirən sözdür.",
  ["Əlamət bildirən", "Hərəkət bildirən", "Say bildirən",
   "Cümlə"], 1, None, 2),
 ("«Qaynayır» sözü nə bildirir?",
  "Qaynamaq hərəkətdir.",
  ["Hərəkət", "Əlamət", "Ad", "Rəng"], 1, None, 2),
 ("«Körpü» sözü hansı qrupdandır?",
  "Əşyanın adıdır.",
  ["Ad bildirən", "Əlamət bildirən", "Hərəkət bildirən",
   "Say"], 1, None, 2),
 ("Sözləri qruplaşdırarkən nəyə əsaslanırıq?",
  "Sözlər mənasına görə qruplaşdırılır.",
  ["Mənasına", "Uzunluğuna", "Rənginə", "Səsinə"],
  1, None, 2),
 ("«Nə edir?» sualına cavab verən söz hansıdır?",
  "«Yuyur» hərəkət bildirir.",
  ["yuyur", "sabun", "təmiz", "əl"], 1, None, 2),
 ("«Gözəl, çirkin, təmiz» sözləri hansı qrupdandır?",
  "Hamısı əlamət bildirir.",
  ["Əlamət bildirən sözlər", "Ad bildirən sözlər",
   "Hərəkət bildirən sözlər", "Cümlələr"], 1, None, 2),
 ("Əşyanın adını, əlamətini və hərəkətini bildirən sözlərdən nə qurulur?",
  "Sözlərdən cümlə qurulur.",
  ["Cümlə", "Hərf", "Səs", "Rəqəm"], 1, None, 2),
 ("«Aslan» sözü insan adı kimi işlənərsə, necə yazılar?",
  "Şəxs adları böyük hərflə yazılır.",
  ["Böyük hərflə", "Kiçik hərflə", "Rəqəmlə", "Dırnaqda"],
  1, None, 3),
 ("«Sürətli» və «yavaş» sözləri nəyi müqayisə etməyə kömək edir?",
  "Bu sözlər hərəkətin sürətini bildirir.",
  ["Sürəti", "Rəngi", "Dadı", "Sayı"], 1, None, 3),
],
"az-2-yazi-qaydasi": [
 ("«Çiçəkli» sözü hansı sözdən yaranıb?",
  "«Çiçək» sözünə şəkilçi artırılıb.",
  ["çiçək", "çiy", "çəki", "içki"], 1, None, 2),
 ("«Dəftər» sözünün düzgün yazılışı hansıdır?",
  "Söz «dəftər» kimi yazılır.",
  ["dəftər", "dəftar", "deftər", "dəfdər"], 1, None, 1),
 ("«çəmən» sözü cümlənin əvvəlində necə yazılmalıdır?",
  "Cümlənin ilk sözü böyük hərflə başlanır: Çəmən.",
  ["Çəmən", "çəmən", "ÇƏMƏN", "çəmƏn"], 1, None, 2),
 ("Dağ adı olan «savalan» necə yazılmalıdır?",
  "Dağ adları xüsusi addır: Savalan.",
  ["Savalan", "savalan", "saValan", "savaLAN"], 1, None, 2),
 ("«Səkkiz» sözündə hansı hərf qoşadır?",
  "Sözdə «k» hərfi qoşa yazılır.",
  ["k", "s", "ə", "z"], 1, None, 2),
 ("Sözü sətrə sığdırmaq mümkün olmayanda nə edirik?",
  "Sözü hecalarla bölüb yeni sətrə keçiririk.",
  ["Hecalarla bölüb keçiririk", "Sözü atırıq",
   "Hərfləri sıxışdırırıq", "Sözü yarıda kəsirik"], 1, None, 2),
 ("«İldırım» sözü şəxs adı kimi işlənəndə necə yazılır?",
  "Şəxs adı olanda böyük hərflə yazılır.",
  ["Böyük hərflə — İldırım", "Kiçik hərflə — ildırım",
   "Dırnaqda", "Rəqəmlə"], 1, None, 3),
 ("Yazı yazarkən dəftərdə nəyə əməl etməliyik?",
  "Səliqəyə və sətir xəttinə əməl olunmalıdır.",
  ["Səliqəyə və sətir xəttinə", "Sürətə", "Rəngə",
   "Heç nəyə"], 1, None, 1),
 ("Küçə adları necə yazılır?",
  "Küçə adları xüsusi addır, böyük hərflə yazılır.",
  ["Böyük hərflə yazılır", "Kiçik hərflə yazılır",
   "Rəqəmlə yazılır", "Yazılmır"], 1, None, 2),
 ("Sözləri aydın oxumaq üçün hərflər necə yazılmalıdır?",
  "Hərflər aydın və səliqəli yazılmalıdır.",
  ["Aydın və səliqəli", "Çox xırda", "Bir-birinə qarışıq",
   "Tələsik"], 1, None, 1),
],
"hey-2-canlilar": [
 ("Qoyunun balası necə adlanır?",
  "Qoyunun balası quzudur.",
  ["Quzu", "Buzov", "Çəpiş", "Bala"], 1, None, 1),
 ("Bitkinin yerüstü hissələri hansılardır?",
  "Gövdə, yarpaq və çiçək torpağın üstündədir.",
  ["Gövdə, yarpaq, çiçək", "Yalnız kök", "Torpaq və su",
   "Daş və qum"], 1, None, 2),
 ("Hansı quş köçəri quşdur?",
  "Qaranquş payızda isti ölkələrə köçür.",
  ["Qaranquş", "Sərçə", "Toyuq", "Qarğa"], 1, None, 2),
 ("Heyvanları qidasına görə hansı qruplara bölmək olar?",
  "Otyeyən və ətyeyən heyvanlar var.",
  ["Otyeyən və ətyeyən", "Uçan və yazan", "Böyük və sarı",
   "İsti və soyuq"], 1, None, 2),
 ("Ağac və kol bir-birindən nə ilə fərqlənir?",
  "Ağacın bir qalın gövdəsi, kolun çoxlu nazik gövdəsi olur.",
  ["Ağacın bir qalın gövdəsi olur", "Kol daha hündürdür",
   "Ağacın yarpağı olmur", "Fərqlənmirlər"], 1, None, 3),
 ("Hansı canlı sürünərək hərəkət edir?",
  "İlan sürünərək hərəkət edir.",
  ["İlan", "Sərçə", "Dovşan", "Balıq"], 1, None, 1),
 ("Yumurtadan çıxan toyuq balası necə adlanır?",
  "Toyuğun balası cücədir.",
  ["Cücə", "Quzu", "Buzov", "Çəpiş"], 1, None, 1),
 ("Bitkilər insanlara nə verir?",
  "Bitkilər qida və təmiz hava mənbəyidir.",
  ["Qida və təmiz hava", "Yalnız kölgə", "Heç nə",
   "Yalnız oduncaq"], 1, None, 2),
 ("Pişik hansı qrupa aiddir: ev, yoxsa vəhşi heyvan?",
  "Pişik evdə saxlanılan heyvandır.",
  ["Ev heyvanıdır", "Vəhşi heyvandır", "Quşdur",
   "Balıqdır"], 1, None, 1),
 ("Qış yuxusuna gedən heyvana misal hansıdır?",
  "Kirpi də ayı kimi qış yuxusuna gedir.",
  ["Kirpi", "Toyuq", "At", "Keçi"], 1, None, 2),
],
"hey-2-deyerler": [
 ("Gerb və bayraq nəyin rəmzidir?",
  "Bayraq, gerb və himn dövlətin rəmzləridir.",
  ["Dövlətin", "Məktəbin", "Ailənin", "Şəhərin"], 1, None, 2),
 ("Böyüklərə yer vermək, salam vermək nəyin göstəricisidir?",
  "Bu davranışlar hörmətin göstəricisidir.",
  ["Hörmətin", "Qorxunun", "Tənbəlliyin", "Paxıllığın"],
  1, None, 1),
 ("Yoldaşına verdiyin sözü unutmaq necə qiymətləndirilir?",
  "Sözün üstündə durmamaq etibarsızlıqdır.",
  ["Etibarsızlıq kimi", "Qəhrəmanlıq kimi", "Zarafat kimi",
   "Nəzakət kimi"], 1, None, 2),
 ("Uşaqların oynamaq və istirahət hüququ varmı?",
  "Hər uşağın oynamaq və istirahət hüququ var.",
  ["Bəli, var", "Xeyr, yoxdur", "Yalnız yayda",
   "Yalnız bazar günü"], 1, None, 2),
 ("Səhvini boynuna almaq nəyin əlamətidir?",
  "Səhvi etiraf etmək cəsarət və düzlükdür.",
  ["Cəsarətin və düzlüyün", "Zəifliyin", "Qorxaqlığın",
   "Tərbiyəsizliyin"], 1, None, 2),
 ("Kimsəsiz və xəstə insanlara kömək etmək necə adlanır?",
  "Təmənnasız yaxşılıq xeyirxahlıqdır.",
  ["Xeyirxahlıq", "Paxıllıq", "Laqeydlik", "İsrafçılıq"],
  1, None, 2),
 ("Milli bayramımıza misal hansıdır?",
  "Novruz xalqımızın milli bayramıdır.",
  ["Novruz", "Ad günü", "İdman günü", "Tətil"], 1, None, 1),
 ("Ailə üzvləri bir-birinə necə yanaşmalıdır?",
  "Ailədə qayğı və sevgi olmalıdır.",
  ["Qayğı və sevgi ilə", "Laqeyd", "Kobud", "Paxıl"],
  1, None, 1),
 ("Təmiz və səliqəli geyinmək nəyə hörmətdir?",
  "Səliqə özünə və ətrafdakılara hörmətdir.",
  ["Özünə və ətrafdakılara", "Heç nəyə", "Yalnız güzgüyə",
   "Yalnız qonaqlara"], 1, None, 3),
 ("Su və çörəyi israf etmək düzgündürmü?",
  "Nemətləri israf etmək olmaz.",
  ["Xeyr, israf olmaz", "Bəli, olar", "Bəzən olar",
   "Fərqi yoxdur"], 1, None, 1),
],
"hey-2-ehtiyat": [
 ("Qaynar qazana toxunmaq nəyə səbəb olar?",
  "Qaynar əşya yanığa səbəb olur.",
  ["Yanığa", "Sevincə", "Heç nəyə", "Sağlamlığa"], 1, None, 1),
 ("Dərman qutusu uşaq üçün nə üçün təhlükəlidir?",
  "Özbaşına içilən dərman zəhərlənməyə səbəb ola bilər.",
  ["Zəhərlənmə ola bilər", "Dadlı olduğu üçün",
   "Rəngli olduğu üçün", "Təhlükəsizdir"], 1, None, 2),
 ("Yağışdan sonra sürüşkən yolda necə hərəkət etməliyik?",
  "Sürüşkən yerdə ehtiyatla, yavaş getmək lazımdır.",
  ["Ehtiyatla, yavaş", "Qaçaraq", "Tullanaraq",
   "Gözübağlı"], 1, None, 1),
 ("Balkonun məhəccərindən sallanmaq olarmı?",
  "Hündürlükdən yıxılmaq təhlükəsi var.",
  ["Qəti olmaz", "Olar", "Yalnız gündüz olar",
   "Böyük uşaqlara olar"], 1, None, 1),
 ("Küçədə tanımadığın adamın verdiyi yeməyi götürmək olarmı?",
  "Yad adamdan heç nə götürmək olmaz.",
  ["Olmaz", "Olar", "Şirniyyatdırsa olar",
   "Ac olanda olar"], 1, None, 2),
 ("Evdə suyu açıq qoyub getmək nəyə səbəb ola bilər?",
  "Açıq qalan su daşqın yarada bilər.",
  ["Su daşqınına", "Yanğına", "Zəlzələyə", "Küləyə"],
  1, None, 2),
 ("Pəncərədən əşya atmaq nə üçün təhlükəlidir?",
  "Atılan əşya aşağıdakı insanlara dəyə bilər.",
  ["Aşağıdakılara dəyə bilər", "Pəncərə sınar",
   "Külək aparar", "Təhlükəsizdir"], 1, None, 2),
 ("İsti sobaya yaxın oynamaq olarmı?",
  "Sobaya toxunmaq yanıq təhlükəsidir.",
  ["Olmaz, yanıq təhlükəsi var", "Olar, maraqlıdır",
   "Yalnız qışda olar", "Fərqi yoxdur"], 1, None, 1),
 ("Elektrik cihazını işlək vəziyyətdə qoyub evdən çıxmaq nəyə səbəb ola bilər?",
  "Nəzarətsiz cihaz yanğın törədə bilər.",
  ["Yanğına", "Sərinliyə", "Qənaətə", "Heç nəyə"],
  1, None, 2),
 ("Dəniz kənarında uşaq təkbaşına suya girə bilərmi?",
  "Suya yalnız böyüklərin yanında girmək olar.",
  ["Xeyr, yalnız böyüklərlə", "Bəli, sərbəst",
   "Bəli, dayazda", "Bəli, isti olanda"], 1, None, 2),
],
"hey-2-materiallar": [
 ("İnsan tərəfindən hazırlanan materiala misal hansıdır?",
  "Plastik təbiətdə yoxdur, insan istehsal edir.",
  ["Plastik", "Daş", "Ağac", "Su"], 1, None, 2),
 ("Şüşə stəkan yerə düşəndə nə baş verir?",
  "Şüşə kövrəkdir — sınır.",
  ["Sınır", "Böyüyür", "Yumşalır", "Heç nə olmur"],
  1, None, 1),
 ("Yun bizə hansı heyvandan alınır?",
  "Yun qoyundan qırxılır.",
  ["Qoyundan", "Toyuqdan", "Balıqdan", "İlandan"],
  1, None, 1),
 ("Taxta suya salınanda nə edir?",
  "Taxta yüngüldür — suda üzür.",
  ["Üzür (batmır)", "Dərhal batır", "Əriyir", "Yanır"],
  1, None, 2),
 ("Kağızı hansı alətlə kəsirik?",
  "Kağız qayçı ilə kəsilir.",
  ["Qayçı ilə", "Qaşıqla", "Xətkeşlə", "Fırça ilə"],
  1, None, 1),
 ("Şokolad günəş altında qalanda nə olur?",
  "İstidə şokolad əriyir.",
  ["Əriyir", "Bərkiyir", "Böyüyür", "Ağarır"], 1, None, 1),
 ("Hansı əşyanı maqnit özünə çəkər?",
  "Maqnit dəmir əşyaları çəkir.",
  ["Dəmir sancaq", "Taxta kubik", "Rezin top",
   "Kağız vərəq"], 1, None, 2),
 ("Palçıq qurudulanda necə olur?",
  "Quruyan palçıq bərkiyir.",
  ["Bərkiyir", "Əriyir", "Uçur", "Şəffaflaşır"], 1, None, 2),
 ("Hansı material istidə formasını asan dəyişir?",
  "Plastilin yumşaqdır, asan forma alır.",
  ["Plastilin", "Daş", "Şüşə", "Dəmir"], 1, None, 2),
 ("Pəncərə şüşəsinin əsas xassəsi nədir?",
  "Şüşə şəffafdır — işıq keçirir.",
  ["Şəffaf olması", "Yumşaq olması", "Elastik olması",
   "Maqnit olması"], 1, None, 2),
],
"hey-2-men-mektebim": [
 ("Dərsə gecikməmək üçün nə etməliyik?",
  "Vaxtında oyanıb hazırlaşmaq lazımdır.",
  ["Vaxtında oyanıb hazırlaşmalıyıq", "Gec yatmalıyıq",
   "Tələsməməliyik", "Dərsə getməməliyik"], 1, None, 1),
 ("Lövhəyə cavab verən yoldaşımızı necə dinləməliyik?",
  "Yoldaşı sakit və diqqətlə dinləmək lazımdır.",
  ["Sakit və diqqətlə", "Gülərək", "Danışaraq",
   "Mane olaraq"], 1, None, 1),
 ("Məktəbin həyətindəki ağaclara münasibət necə olmalıdır?",
  "Ağacları qorumaq lazımdır.",
  ["Qorumalıyıq", "Budaqlarını qırmalıyıq",
   "Üstünə çıxmalıyıq", "Laqeyd olmalıyıq"], 1, None, 1),
 ("Dərsdə söz demək istəyəndə nə edirik?",
  "Əl qaldırıb icazə gözləyirik.",
  ["Əl qaldırırıq", "Qışqırırıq", "Ayağa qalxıb danışırıq",
   "Yoldaşı itələyirik"], 1, None, 1),
 ("Sinif yoldaşının əşyasını istifadə etmək istəyəndə nə etməliyik?",
  "Əvvəlcə icazə istəmək lazımdır.",
  ["İcazə istəməliyik", "Səssiz götürməliyik",
   "Gizlətməliyik", "Evə aparmalıyıq"], 1, None, 1),
 ("Məktəbdə kitablar hansı otaqda saxlanılır və oxucuya verilir?",
  "Kitabxanada kitablar saxlanılır və verilir.",
  ["Kitabxanada", "İdman zalında", "Yeməkxanada",
   "Dəhlizdə"], 1, None, 1),
 ("İdman dərsinə hansı geyimdə gəlmək lazımdır?",
  "İdman dərsi üçün idman forması geyinilir.",
  ["İdman formasında", "Bayram paltarında", "Pijamada",
   "Paltoda"], 1, None, 1),
 ("Tənəffüsdə qaçıb itələşmək nəyə səbəb ola bilər?",
  "İtələşmə zədələnmə ilə nəticələnə bilər.",
  ["Zədələnməyə", "Sevincə", "Mükafata", "Heç nəyə"],
  1, None, 2),
 ("Dərsdən sonra sinifdə işığı yanılı qoymaq düzgündürmü?",
  "Çıxanda işığı söndürmək lazımdır.",
  ["Xeyr, söndürmək lazımdır", "Bəli, qoymaq olar",
   "Fərqi yoxdur", "Yalnız qışda söndürülür"], 1, None, 2),
 ("Məktəbdə şagirdin əsas vəzifəsi nədir?",
  "Şagirdin əsas işi oxumaq və öyrənməkdir.",
  ["Oxumaq və öyrənmək", "Oynamaq", "Yatmaq",
   "Televizora baxmaq"], 1, None, 1),
],
"hey-2-yer-kuresi": [
 ("Gündüzü gecədən fərqləndirən nədir?",
  "Gündüz Günəş işığı olur.",
  ["Günəş işığının olması", "Küləyin olması",
   "Yağışın olması", "Heç nə"], 1, None, 2),
 ("Dağlar hansı hissədə yerləşir: quruda, yoxsa suda?",
  "Dağlar Yerin quru hissəsindədir.",
  ["Quruda", "Suda", "Buludlarda", "Ayda"], 1, None, 1),
 ("Yaşıl rəng xəritədə adətən nəyi bildirir?",
  "Yaşıl rəng meşə və düzənlikləri göstərir.",
  ["Meşə və düzənlikləri", "Dənizləri", "Dağ zirvələrini",
   "Şəhərləri"], 1, None, 2),
 ("Yer kürəsinin modelinə nə deyilir?",
  "Yerin kiçildilmiş modeli qlobusdur.",
  ["Qlobus", "Xəritə", "Kompas", "Təqvim"], 1, None, 2),
 ("Günəş olmasa, Yerdə nə baş verər?",
  "Günəşsiz işıq və istilik olmaz — həyat dayanar.",
  ["Həyat olmaz", "Heç nə dəyişməz", "Daha isti olar",
   "Bitkilər çoxalar"], 1, None, 3),
 ("Çayda su hansı istiqamətdə hərəkət edir?",
  "Çay suyu yuxarıdan aşağıya axır.",
  ["Yuxarıdan aşağıya axır", "Aşağıdan yuxarıya",
   "Dairə üzrə", "Hərəkət etmir"], 1, None, 2),
 ("Kənddə insanlar əsasən nə ilə məşğul olur?",
  "Kənddə əkinçilik və heyvandarlıq geniş yayılıb.",
  ["Əkinçilik və heyvandarlıqla", "Metro tikintisi ilə",
   "Gəmiçiliklə", "Heç nə ilə"], 1, None, 2),
 ("Ulduzlar nə vaxt daha yaxşı görünür?",
  "Ulduzlar gecə aydın görünür.",
  ["Gecə", "Günorta", "Səhər", "Yağışda"], 1, None, 1),
 ("Hava nə üçün bütün canlılara lazımdır?",
  "Canlılar hava ilə nəfəs alır.",
  ["Nəfəs almaq üçün", "Yatmaq üçün", "Bəzək üçün",
   "Lazım deyil"], 1, None, 1),
 ("Səhər Günəş hansı tərəfdən görünməyə başlayır?",
  "Günəş şərq tərəfdən doğur.",
  ["Şərq tərəfdən", "Qərb tərəfdən", "Şimal tərəfdən",
   "Cənub tərəfdən"], 1, None, 2),
],
}
for _k, _v in ELAVE_AZ_HEY.items():
    SUALLAR[_k] = SUALLAR[_k] + _v



ELAVE_INF_RIY = {
"inf-2-alqoritm": [
 ("Alqoritmdə addımların yerini dəyişsək nə ola bilər?",
  "Sıra pozulanda nəticə düzgün alınmaya bilər.",
  ["Nəticə düzgün alınmaya bilər", "Heç nə dəyişməz",
   "Alqoritm sürətlənər", "Daha yaxşı olar"], 1, None, 2),
 ("«Əvvəl», «sonra», «axırda» sözləri alqoritmdə nəyi bildirir?",
  "Bu sözlər addımların sırasını göstərir.",
  ["Addımların sırasını", "Rəngləri", "İcraçının adını",
   "Səsi"], 1, None, 2),
 ("İcraçı əmri necə yerinə yetirməlidir?",
  "İcraçı əmri dəqiq, olduğu kimi yerinə yetirir.",
  ["Dəqiq, olduğu kimi", "İstədiyi kimi", "Yarımçıq",
   "Tərsinə"], 1, None, 2),
 ("«2 + 2 = 5» mülahizəsi necə mülahizədir?",
  "2 + 2 = 4 olduğundan bu mülahizə yalandır.",
  ["Yalan", "Doğru", "Qeyri-müəyyən", "Sual"], 1, None, 2),
 ("Kompüter oyununda personajı hərəkət etdirən əmrlər nəyi təşkil edir?",
  "Ardıcıl əmrlər alqoritmin addımlarıdır.",
  ["Alqoritmin addımlarını", "Şəkilləri", "Musiqini",
   "Rəngləri"], 1, None, 3),
 ("Yemək hazırlamaq üçün resept nəyə bənzəyir?",
  "Resept addım-addım göstəriş verir — alqoritmdir.",
  ["Alqoritmə", "Nağıla", "Şeirə", "Mahnıya"], 1, None, 2),
 ("Alqoritm harada istifadə olunur?",
  "Alqoritmlər həyatın hər sahəsində işlədilir.",
  ["Gündəlik həyatda və texnikada", "Yalnız kosmosda",
   "Heç yerdə", "Yalnız oyunlarda"], 1, None, 2),
 ("«Qapını aç» — bu nədir?",
  "İcraçıya verilən bir əmrdir.",
  ["Əmr", "Sual", "Nağıl", "Tapmaca"], 1, None, 1),
 ("Mülahizə nədir?",
  "Doğru və ya yalan olduğunu söyləmək mümkün olan fikirdir.",
  ["Doğru və ya yalan olan fikir", "Yalnız sual",
   "Yalnız şəkil", "Rəqəmlər sırası"], 1, None, 3),
 ("Robotlar insanlara harada kömək edir?",
  "Robotlar ağır və təhlükəli işlərdə insanı əvəz edir.",
  ["Ağır və təhlükəli işlərdə", "Yalnız oyunlarda",
   "Yuxuda", "Heç yerdə"], 1, None, 2),
],
"inf-2-informasiya": [
 ("Səsli məktub hansı formada informasiyadır?",
  "Səslə çatdırılan məlumat səs informasiyasıdır.",
  ["Səs", "Mətn", "Şəkil", "Rəqəm"], 1, None, 2),
 ("Şeiri əzbər söyləyəndə informasiya hansı formada ötürülür?",
  "Danışıq səslə ötürülür.",
  ["Səslə", "Yazı ilə", "Şəkillə", "Jestlə"], 1, None, 2),
 ("Fotoaparat nəyi qeydə alır?",
  "Fotoaparat görüntünü çəkib saxlayır.",
  ["Şəkli (görüntünü)", "Qoxunu", "Dadı", "İstiliyi"],
  1, None, 1),
 ("İnformasiyanı itirməmək üçün nə etmək lazımdır?",
  "Məlumatı yazmaq və ya yadda saxlamaq lazımdır.",
  ["Saxlamaq (yazmaq)", "Unutmaq", "Silmək", "Atmaq"],
  1, None, 2),
 ("Televerilişdə diktor xəbər oxuyur. Tamaşaçı informasiyanı nə edir?",
  "Tamaşaçı məlumatı qəbul edir.",
  ["Qəbul edir", "Ötürür", "Silir", "Yaradır"], 1, None, 2),
 ("İnsan beyni informasiya ilə nə edir?",
  "Beyin məlumatı qəbul edib saxlayır və emal edir.",
  ["Saxlayır və emal edir", "Yalnız silir", "Heç nə etmir",
   "Çap edir"], 1, None, 3),
 ("Hansı qurğu ilə şəkli kağızdan kompüterə köçürmək olar?",
  "Skaner kağızdakı təsviri kompüterə köçürür.",
  ["Skanerlə", "Dinamiklə", "Mausla", "Qulaqlıqla"],
  1, None, 2),
 ("Məlumatı uzaqdakı adama ən sürətli necə çatdırmaq olar?",
  "Telefon zəngi məlumatı dərhal çatdırır.",
  ["Telefonla zəng etməklə", "Məktub yazıb poçtla",
   "Piyada gedərək", "Gözləyərək"], 1, None, 2),
 ("Qəzet və jurnallar hansı informasiya mənbəyidir?",
  "Qəzet yazılı informasiya mənbəyidir.",
  ["Yazılı mənbə", "Səsli mənbə", "Dadlı mənbə",
   "Qoxulu mənbə"], 1, None, 2),
 ("İnformasiya formalarına misal sıra hansıdır?",
  "İnformasiya mətn, səs və şəkil formasında olur.",
  ["Mətn, səs, şəkil", "Stol, stul, şkaf",
   "Qırmızı, sarı, göy", "Bir, iki, üç"], 1, None, 2),
],
"inf-2-kompyuter": [
 ("Kompüterin bütün hissələri nəyə qoşulur?",
  "Qurğular sistem blokuna birləşdirilir.",
  ["Sistem blokuna", "Pəncərəyə", "Stola", "Çantaya"],
  1, None, 2),
 ("Printer nə üçündür?",
  "Printer mətni və şəkli kağıza çap edir.",
  ["Mətni kağıza çap etmək üçün", "Səs yazmaq üçün",
   "Şəkil çəkmək üçün", "Oyun oynamaq üçün"], 1, None, 1),
 ("Kompüterdə vaxtı və tarixi harada görmək olar?",
  "Saat ekranın küncündə görünür.",
  ["Ekranın küncündə", "Klaviaturanın altında",
   "Mausun içində", "Kabeldə"], 1, None, 2),
 ("Veb-kamera nə üçün istifadə olunur?",
  "Veb-kamera görüntünü ötürür.",
  ["Görüntünü ötürmək üçün", "Mətn çap etmək üçün",
   "Səs gücləndirmək üçün", "İşıq yandırmaq üçün"],
  1, None, 2),
 ("Kompüter virusları nəyə zərər verir?",
  "Viruslar proqramlara və fayllara zərər verir.",
  ["Proqramlara və fayllara", "Stola", "Elektrik xəttinə",
   "Otağa"], 1, None, 3),
 ("Mausun təkərciyi (çarxı) nə üçündür?",
  "Çarxla səhifəni yuxarı-aşağı sürüşdürürük.",
  ["Səhifəni sürüşdürmək üçün", "Səs açmaq üçün",
   "Şəkil çəkmək üçün", "Kompüteri söndürmək üçün"],
  1, None, 2),
 ("Kompüterdə mətn yazarkən hansı qurğudan istifadə edirik?",
  "Mətn klaviatura ilə yığılır.",
  ["Klaviaturadan", "Dinamikdən", "Kameradan",
   "Printerdən"], 1, None, 1),
 ("Ekranda əmrləri göstərən kiçik ox necə adlanır?",
  "Ekrandakı ox kursordur.",
  ["Kursor", "Klaviş", "Fayl", "Virus"], 1, None, 2),
 ("Kompüterlə iş zamanı hər 30 dəqiqədən bir nə edilməlidir?",
  "Gözlərin dincəlməsi üçün fasilə verilməlidir.",
  ["Fasilə", "Səsi artırmaq", "Oyunu dəyişmək",
   "İşığı söndürmək"], 1, None, 2),
 ("Kompüteri tozdan qorumaq üçün nə etmək olar?",
  "Cihazı təmiz saxlamaq lazımdır.",
  ["Təmiz saxlamaq", "Su ilə yumaq", "Örtüb heç işlətməmək",
   "Günəşə qoymaq"], 1, None, 2),
],
"inf-2-obyekt": [
 ("«Stol, stul, şkaf» obyektlərini hansı ad altında birləşdirmək olar?",
  "Hamısı mebeldir.",
  ["Mebel", "Meyvələr", "Nəqliyyat", "Geyim"], 1, None, 1),
 ("Obyektin adı, əlamətləri və hərəkətləri onun nəyini təşkil edir?",
  "Bunlar obyektin xüsusiyyətləridir.",
  ["Xüsusiyyətlərini", "Kölgəsini", "Çəkisini yalnız",
   "Qiymətini"], 1, None, 3),
 ("Hansı obyekt canlıdır?",
  "Sərçə canlı obyektdir.",
  ["Sərçə", "Daş", "Stol", "Qələm"], 1, None, 1),
 ("«Günəş, ay, ulduz» obyektləri hansı qrupa aiddir?",
  "Hamısı göy cismidir.",
  ["Göy cisimləri", "Mebel", "Heyvanlar", "Nəqliyyat"],
  1, None, 2),
 ("Avtomobil hansı obyektdir: təbii, yoxsa süni?",
  "Avtomobili insan yaradıb — süni obyektdir.",
  ["Süni (insan yaradıb)", "Təbii", "Canlı", "Bitki"],
  1, None, 2),
 ("«Qırmızı, yumru, şirin» — bu sözlər almanın nəyidir?",
  "Bunlar almanın əlamətləridir.",
  ["Əlamətləri", "Hərəkətləri", "Adları", "Qrupları"],
  1, None, 2),
 ("Obyektlər qruplara nəyə görə ayrılır?",
  "Qruplaşdırma ümumi əlamətlərə əsaslanır.",
  ["Ümumi əlamətlərə görə", "Təsadüfən", "Rəng sırasına görə",
   "Adların uzunluğuna görə"], 1, None, 2),
 ("«Çəkmə, ayaqqabı, səndəl» qrupuna hansı obyekt AID DEYİL?",
  "Papaq ayaq geyimi deyil.",
  ["Papaq", "Çəkmə", "Səndəl", "Ayaqqabı"], 1, None, 2),
 ("«Sinif, lövhə, parta» obyektləri harada yerləşir?",
  "Bu obyektlər məktəbdədir.",
  ["Məktəbdə", "Xəstəxanada", "Bazarda", "Meşədə"],
  1, None, 1),
 ("İki obyektin oxşarlığını tapmaq üçün nəyi müqayisə edirik?",
  "Obyektlərin əlamətləri müqayisə olunur.",
  ["Əlamətlərini", "Kölgələrini", "Qiymətlərini",
   "Səslərini"], 1, None, 2),
],
"riy-2-ededler-100": [
 ("«Otuz doqquz» ədədi rəqəmlə necə yazılır?",
  "Otuz doqquz — 39.",
  ["39", "93", "30", "309"], 1, str(39), 1),
 ("45 ədədində təkliklərin sayı neçədir?",
  "45: 4 onluq, 5 təklik.",
  ["Beş", "Dörd", "On", "Sıfır"], 1, None, 2),
 ("6 onluq və 6 təklikdən ibarət ədəd hansıdır?",
  "60 + 6 = 66.",
  ["66", "6", "606", "60"], 1, str(66), 2),
 ("70-dən bilavasitə sonra gələn ədəd hansıdır?",
  "70 + 1 = 71.",
  ["71", "69", "80", "72"], 1, str(70 + 1), 1),
 ("İkirəqəmli ədədlərin ən böyüyü neçədir?",
  "Ən böyük ikirəqəmli ədəd 99-dur.",
  ["99", "10", "90", "100"], 1, str(99), 2),
 ("Verilən ədədlərdən hansı cüt ədəddir?",
  "48 cüt ədəddir — 2-yə bölünür.",
  ["48", "31", "17", "53"], 1, None, 2),
 ("24, 42, 40 ədədlərini artan sırada düzün.",
  "24 < 40 < 42.",
  ["24, 40, 42", "42, 40, 24", "40, 24, 42",
   "24, 42, 40"], 1, None, 2),
 ("«80 + 9» cəmi hansı ədədi verir?",
  "80 + 9 = 89.",
  ["89", "98", "80", "17"], 1, str(80 + 9), 1),
 ("«52» ədədi sözlə necə oxunur?",
  "52 — əlli iki.",
  ["Əlli iki", "İyirmi beş", "Əlli", "Beş iki"], 1, None, 2),
 ("34 ədədində onluqlar mərtəbəsindəki rəqəm hansıdır?",
  "34: onluqlar mərtəbəsində 3 durur.",
  ["Üç", "Dörd", "Otuz dörd", "Sıfır"], 1, None, 2),
],
"riy-2-toplama-cixma": [
 ("42 + 36 cəmini tapın.",
  "42 + 36 = 78.",
  ["78", "77", "88", "76"], 1, str(42 + 36), 1),
 ("90 − 45 fərqini hesablayın.",
  "90 − 45 = 45.",
  ["45", "55", "35", "50"], 1, str(90 - 45), 2),
 ("27 + 27 neçə edər?",
  "27 + 27 = 54.",
  ["54", "44", "52", "56"], 1, str(27 + 27), 2),
 ("Fərq 30, çıxan 20-dirsə, çıxılan neçədir?",
  "Çıxılan = 30 + 20 = 50.",
  ["50", "10", "40", "60"], 1, str(30 + 20), 3),
 ("36 − 18 neçə edər?",
  "36 − 18 = 18.",
  ["18", "16", "20", "28"], 1, str(36 - 18), 2),
 ("55 + 15 cəmini hesablayın.",
  "55 + 15 = 70.",
  ["70", "60", "65", "75"], 1, str(55 + 15), 1),
 ("Toplama ilə yoxlayın: 60 − 24 = 36. Hansı doğrudur?",
  "Fərq üstəgəl çıxan çıxılanı verməlidir.",
  ["36 + 24 = 60", "36 + 60 = 24", "24 − 36 = 60",
   "60 + 24 = 36"], 1, None, 3),
 ("81 − 50 neçə olar?",
  "81 − 50 = 31.",
  ["31", "30", "41", "21"], 1, str(81 - 50), 1),
 ("Cəm 100-dür. Toplananlardan biri 55-dirsə, o biri neçədir?",
  "100 − 55 = 45.",
  ["45", "55", "50", "35"], 1, str(100 - 55), 3),
 ("İki onluq üstəgəl üç onluq neçə onluq edir?",
  "2 onluq + 3 onluq = 5 onluq.",
  ["5 onluq", "6 onluq", "23 onluq", "1 onluq"], 1, None, 2),
],
"riy-2-vurma": [
 ("«5 × 3» yazılışına uyğun toplama hansıdır?",
  "5 × 3 — üç dənə 5-in cəmidir.",
  ["5 + 5 + 5", "5 + 3", "3 + 3 + 3 + 3 + 3 + 3",
   "5 + 5"], 1, None, 2),
 ("Vuruqlar 4 və 5-dirsə, hasil neçədir?",
  "4 × 5 = 20.",
  ["20", "9", "45", "25"], 1, str(4 * 5), 2),
 ("Sıfırla vurmanın nəticəsi həmişə neçə olur?",
  "İstənilən ədəd 0-a vurulanda 0 alınır.",
  ["0", "1", "Ədədin özü", "10"], 1, None, 2),
 ("Hər qutuda 2 top olmaqla 7 qutuda neçə top var?",
  "2 × 7 = 14 top.",
  ["14", "9", "27", "12"], 1, str(2 * 7), 2),
 ("Vurmanın yerdəyişmə xassəsi hansı bərabərlikdə göstərilib?",
  "Vuruqların yeri dəyişəndə hasil dəyişmir.",
  ["4 × 6 = 6 × 4", "4 + 6 = 6 + 4", "4 × 6 = 4 + 6",
   "6 × 4 = 6 + 4"], 1, None, 3),
 ("2 × 9 hasili hansı toplamaya bərabərdir?",
  "2 × 9 — doqquz dənə 2-nin cəmidir.",
  ["Doqquz dənə 2-nin cəminə", "İki dənə 9-un fərqinə",
   "2 + 9 cəminə", "9 − 2 fərqinə"], 1, None, 3),
 ("«Cüt-cüt» sayma (2, 4, 6, 8, …) hansı vurmaya uyğundur?",
  "İki-iki sayma 2-yə vurmadır.",
  ["2-yə vurmaya", "5-ə vurmaya", "3-ə vurmaya",
   "Bölməyə"], 1, None, 2),
 ("Vurmada vuruqların yerini dəyişəndə hasil necə olur?",
  "Hasil dəyişmir.",
  ["Dəyişmir", "Böyüyür", "Kiçilir", "Sıfır olur"],
  1, None, 2),
 ("Hansı əməl eyni toplananların cəmini qısa yazmağa imkan verir?",
  "Eyni ədədlərin təkrar cəmi vurma ilə yazılır.",
  ["Vurma", "Çıxma", "Bölmə", "Müqayisə"], 1, None, 2),
 ("1 × 13 neçə edər?",
  "1-ə vurulanda ədədin özü alınır: 13.",
  ["13", "1", "14", "31"], 1, str(1 * 13), 1),
],
"riy-2-vurma-cedveli": [
 ("7 × 4 hasilini hesablayın.",
  "7 × 4 = 28.",
  ["28", "24", "11", "47"], 1, str(7 * 4), 1),
 ("3 × 7 hasilini tapın.",
  "3 × 7 = 21.",
  ["21", "24", "10", "37"], 1, str(3 * 7), 1),
 ("4 × 6 neçə edər?",
  "4 × 6 = 24.",
  ["24", "26", "10", "46"], 1, str(4 * 6), 1),
 ("5 × 4 hasilini hesablayın.",
  "5 × 4 = 20.",
  ["20", "9", "25", "54"], 1, str(5 * 4), 1),
 ("5 × 8 hasilini tapın.",
  "5 × 8 = 40.",
  ["40", "45", "13", "58"], 1, str(5 * 8), 2),
 ("3 × 10 neçə edər?",
  "3 × 10 = 30.",
  ["30", "13", "33", "20"], 1, str(3 * 10), 2),
 ("5 × 6 hasilini tapın.",
  "5 × 6 = 30.",
  ["30", "25", "11", "56"], 1, str(5 * 6), 1),
 ("4 × 9 neçə olar?",
  "4 × 9 = 36.",
  ["36", "32", "13", "49"], 1, str(4 * 9), 2),
 ("6 × 6 hasilini hesablayın.",
  "6 × 6 = 36.",
  ["36", "30", "12", "66"], 1, str(6 * 6), 2),
 ("Hasil 26, vuruqlardan biri 2-dirsə, o biri neçədir?",
  "26 : 2 = 13.",
  ["13", "12", "24", "28"], 1, str(26 // 2), 3),
],
"riy-2-bolme": [
 ("10 alma 5 uşağa bərabər bölündü. Hər uşağa neçə alma düşdü?",
  "10 : 5 = 2 alma.",
  ["2 alma", "5 alma", "15 alma", "3 alma"], 1,
  "%d alma" % (10 // 5), 2),
 ("İki bərabər hissəyə bölmək hansı ədədə bölmək deməkdir?",
  "Yarıya bölmək 2-yə bölməkdir.",
  ["2-yə", "5-ə", "10-a", "3-ə"], 1, None, 2),
 ("9 konfet 3 uşağa bərabər paylanıldı. Hər uşağa neçə konfet düşdü?",
  "9 : 3 = 3 konfet.",
  ["3 konfet", "9 konfet", "6 konfet", "12 konfet"], 1,
  "%d konfet" % (9 // 3), 2),
 ("Bölünən 22, bölən 2 olarsa, qismət neçədir?",
  "22 : 2 = 11.",
  ["11", "20", "24", "12"], 1, str(22 // 2), 2),
 ("10 : 5 və 10 : 2 qismətləri eynidirmi?",
  "10 : 5 = 2, 10 : 2 = 5 — fərqlidir.",
  ["Xeyr, fərqlidir", "Bəli, eynidir", "Hər ikisi 10-dur",
   "Bilinmir"], 1, None, 3),
 ("33 : 3 neçə edər?",
  "33 : 3 = 11.",
  ["11", "10", "13", "30"], 1, str(33 // 3), 2),
 ("Bölmə ilə vurma arasında hansı əlaqə var?",
  "Bölmə vurmanın tərs əməlidir.",
  ["Biri o birinin tərsidir", "Heç bir əlaqə yoxdur",
   "Eyni əməldir", "Hər ikisi toplamadır"], 1, None, 3),
 ("12 : 4 = 3 bərabərliyini yoxlayan vurma hansıdır?",
  "Qismət vurulanda bölünən alınmalıdır: 3 × 4 = 12.",
  ["3 × 4 = 12", "12 × 4 = 3", "3 × 12 = 4",
   "4 + 3 = 12"], 1, None, 3),
 ("Sinifdəki 16 şagird 2 komandaya bərabər bölündü. Hər komandada neçə şagird var?",
  "16 : 2 = 8 şagird.",
  ["8 şagird", "16 şagird", "4 şagird", "6 şagird"], 1,
  "%d şagird" % (16 // 2), 2),
 ("Sıfırı istənilən ədədə böləndə nə alınır?",
  "0 : n = 0.",
  ["Sıfır", "Ədədin özü", "Bir", "Bölmək olmur"],
  1, None, 3),
],
"riy-2-fiqurlar": [
 ("Beşbucaqlının neçə təpəsi var?",
  "Beşbucaqlının 5 təpəsi var.",
  ["Beş", "Dörd", "Altı", "Üç"], 1, None, 2),
 ("Saatın siferblatı adətən hansı fiqurdadır?",
  "Siferblat dairə formasındadır.",
  ["Dairə", "Kvadrat", "Üçbucaq", "Oval"], 1, None, 1),
 ("Kürəyə bənzəyən əşya hansıdır?",
  "Qlobus kürə formasındadır.",
  ["Qlobus", "Kitab", "Qapı", "Xətkeş"], 1, None, 2),
 ("Yol nişanlarının bəziləri hansı fiqur formasındadır?",
  "Bir çox xəbərdarlıq nişanı üçbucaq formasındadır.",
  ["Üçbucaq", "Ulduz", "Xətt", "Nöqtə"], 1, None, 2),
 ("Simmetrik fiqura misal hansıdır?",
  "Kəpənəyin qanadları simmetrikdir.",
  ["Kəpənək", "Daş parçası", "Bulud", "Ləkə"], 1, None, 2),
 ("Qapı hansı fiqura bənzəyir?",
  "Qapı düzbucaqlı formasındadır.",
  ["Düzbucaqlıya", "Dairəyə", "Üçbucağa", "Kürəyə"],
  1, None, 1),
 ("Sınıq xəttin düz xətdən fərqi nədir?",
  "Sınıq xətt qırıqlardan ibarətdir.",
  ["Düz deyil, qırıqlardan ibarətdir", "Daha uzundur",
   "Rənglidir", "Fərqi yoxdur"], 1, None, 2),
 ("Piramidanın yan üzləri hansı fiqurdur?",
  "Piramidanın yan üzləri üçbucaqdır.",
  ["Üçbucaqdır", "Dairədir", "Ovaldır", "Kürədir"],
  1, None, 3),
 ("Fəza fiquruna misal hansıdır?",
  "Silindr fəza fiqurudur.",
  ["Silindr", "Kvadrat", "Dairə", "Parça"], 1, None, 2),
 ("Fiqurları müstəvi və fəza fiqurlarına ayıran əsas cəhət nədir?",
  "Fəza fiqurlarının həcmi olur.",
  ["Həcminin olub-olmaması", "Rəngi", "Adı",
   "Çəkisi"], 1, None, 3),
],
"riy-2-olcu": [
 ("2 metr neçə desimetrdir?",
  "1 m = 10 dm, 2 m = 20 dm.",
  ["20 dm", "2 dm", "200 dm", "12 dm"], 1,
  "%d dm" % (2 * 10), 2),
 ("5 litr su və 3 litr su birlikdə neçə litrdir?",
  "5 + 3 = 8 litr.",
  ["8 litr", "5 litr", "2 litr", "53 litr"], 1,
  "%d litr" % (5 + 3), 2),
 ("1 dm 5 sm neçə santimetrdir?",
  "10 + 5 = 15 sm.",
  ["15 sm", "5 sm", "10 sm", "50 sm"], 1,
  "%d sm" % (10 + 5), 2),
 ("Uzun məsafələr hansı vahidlə ölçülür?",
  "Uzun məsafələr metrlə (və kilometrlə) ölçülür.",
  ["Metrlə", "Qramla", "Litrlə", "Dəqiqə ilə"], 1, None, 2),
 ("Tərəzinin gözləri bərabərdirsə, kütlələr necədir?",
  "Gözlər tarazlıqdadırsa, kütlələr bərabərdir.",
  ["Bərabərdir", "Fərqlidir", "Sıfırdır", "Bilinmir"],
  1, None, 2),
 ("Səbətdə 4 kq alma var idi, 2 kq da əlavə olundu. İndi neçə kiloqramdır?",
  "4 + 2 = 6 kq.",
  ["6 kq", "2 kq", "8 kq", "42 kq"], 1,
  "%d kq" % (4 + 2), 2),
 ("1 litr süddən 2 stəkan doldu. Hansının tutumu böyükdür: litr qabı, yoxsa stəkan?",
  "Litr qabına daha çox maye yerləşir.",
  ["Litr qabının", "Stəkanın", "Bərabərdir", "Bilinmir"],
  1, None, 3),
 ("Boyumuzu hansı vahidlə ölçürük?",
  "İnsanın boyu santimetrlə ölçülür.",
  ["Santimetrlə", "Litrlə", "Kiloqramla", "Saatla"],
  1, None, 1),
 ("Hansı daha yüngüldür: 1 kq pambıq, yoxsa 2 kq pambıq?",
  "1 kq həmişə 2 kq-dan yüngüldür.",
  ["1 kq pambıq", "2 kq pambıq", "Bərabərdirlər",
   "Bilinmir"], 1, None, 2),
 ("Metrdən böyük məsafə vahidi hansıdır?",
  "Şəhərlərarası məsafə kilometrlə ölçülür.",
  ["Kilometr", "Santimetr", "Desimetr", "Millimetr"],
  1, None, 2),
],
"riy-2-mesele": [
 ("Bağda 35 alma ağacı və 20 armud ağacı var. Cəmi neçə ağac var?",
  "35 + 20 = 55 ağac.",
  ["55 ağac", "15 ağac", "35 ağac", "50 ağac"], 1,
  "%d ağac" % (35 + 20), 2),
 ("Rəfdəki 60 dəftərdən 25-i satıldı. Rəfdə nə qədər dəftər qaldı?",
  "60 − 25 = 35 dəftər.",
  ["35 dəftər", "85 dəftər", "45 dəftər", "25 dəftər"], 1,
  "%d dəftər" % (60 - 25), 2),
 ("Hər səhifədə 2 şəkil olmaqla 6 səhifədə neçə şəkil var?",
  "2 × 6 = 12 şəkil.",
  ["12 şəkil", "8 şəkil", "26 şəkil", "10 şəkil"], 1,
  "%d şəkil" % (2 * 6), 2),
 ("Aysu 8 yaşındadır. Qardaşı ondan 3 yaş böyükdür. Qardaşı neçə yaşındadır?",
  "8 + 3 = 11 yaşında.",
  ["11 yaşında", "5 yaşında", "24 yaşında", "10 yaşında"],
  1, "%d yaşında" % (8 + 3), 2),
 ("20 qəpiyə saqqız, 30 qəpiyə peçenye alındı. Cəmi nə qədər ödənildi?",
  "20 + 30 = 50 qəpik.",
  ["50 qəpik", "10 qəpik", "40 qəpik", "60 qəpik"], 1,
  "%d qəpik" % (20 + 30), 2),
 ("Qutuda 18 kubik var. Onların yarısı qırmızıdır. Neçə kubik qırmızıdır?",
  "18 : 2 = 9 kubik.",
  ["9 kubik", "18 kubik", "6 kubik", "8 kubik"], 1,
  "%d kubik" % (18 // 2), 3),
 ("Avtobusda 14 sərnişin var idi. 6 nəfər də mindi. İndi neçə sərnişin var?",
  "14 + 6 = 20 sərnişin.",
  ["20 sərnişin", "8 sərnişin", "16 sərnişin",
   "21 sərnişin"], 1, "%d sərnişin" % (14 + 6), 2),
 ("Bir həftə 7 gündürsə, 2 həftə neçə gündür?",
  "7 × 2 = 14 gün.",
  ["14 gün", "9 gün", "7 gün", "21 gün"], 1,
  "%d gün" % (7 * 2), 2),
 ("Nihadın 40 qəpiyi var. Dondurma 55 qəpikdir. Almağa nə qədər çatmır?",
  "55 − 40 = 15 qəpik.",
  ["15 qəpik", "95 qəpik", "25 qəpik", "5 qəpik"], 1,
  "%d qəpik" % (55 - 40), 3),
 ("Sinifdə 27 şagird var. 14-ü oğlandırsa, neçəsi qızdır?",
  "27 − 14 = 13 qız.",
  ["13 qız", "41 qız", "14 qız", "12 qız"], 1,
  "%d qız" % (27 - 14), 2),
],
"riy-2-zaman": [
 ("Dəqiqələri saatın hansı əqrəbi göstərir?",
  "Uzun (böyük) əqrəb dəqiqələri göstərir.",
  ["Uzun (böyük) əqrəb", "Qısa əqrəb", "Saniyə əqrəbi yalnız",
   "Heç biri"], 1, None, 2),
 ("İlin birinci ayı hansıdır?",
  "İl yanvarla başlayır.",
  ["Yanvar", "Mart", "Dekabr", "Sentyabr"], 1, None, 1),
 ("İlin sonuncu ayı hansıdır?",
  "İl dekabrla bitir.",
  ["Dekabr", "Yanvar", "Noyabr", "Avqust"], 1, None, 1),
 ("Dərs 45 dəqiqə çəkirsə, yarım saatdan çoxdur, yoxsa az?",
  "45 dəq > 30 dəq — çoxdur.",
  ["Çoxdur", "Azdır", "Bərabərdir", "Bilinmir"], 1, None, 2),
 ("Saat 7-də başlayan cizgi filmi 1 saat çəkdi. Film saat neçədə bitdi?",
  "7 + 1 = 8.",
  ["8-də", "6-da", "9-da", "7-də"], 1, None, 2),
 ("Həftənin dördüncü günü hansıdır?",
  "Bazar ertəsindən sayanda dördüncü gün cümə axşamıdır.",
  ["Cümə axşamı", "Çərşənbə", "Cümə", "Şənbə"], 1, None, 3),
 ("Mart, aprel, may hansı fəslin aylarıdır?",
  "Bu aylar yaz fəslinə aiddir.",
  ["Yazın", "Qışın", "Yayın", "Payızın"], 1, None, 1),
 ("Bir sutkanın yarısı neçə saatdır?",
  "24 : 2 = 12 saat.",
  ["12 saat", "6 saat", "24 saat", "10 saat"], 1,
  "%d saat" % (24 // 2), 2),
 ("Nahar adətən günün hansı hissəsində olur?",
  "Nahar günortada yeyilir.",
  ["Günortada", "Gecə yarısı", "Sübh tezdən", "Axşamüstü"],
  1, None, 1),
 ("İlin 8-ci ayı hansıdır?",
  "Səkkizinci ay avqustdur.",
  ["Avqust", "İyul", "Sentyabr", "Aprel"], 1, None, 2),
],
}
for _k, _v in ELAVE_INF_RIY.items():
    SUALLAR[_k] = SUALLAR[_k] + _v



MOVZULAR += [("informatika", "inf-2-proqramlar", 4)]
YENI_INF = {
"inf-2-proqramlar": [
 ("Mətnin rəngini və ölçüsünü dəyişmək necə adlanır?",
  "Mətnin görünüşünün dəyişdirilməsi formatlama adlanır.",
  ["Formatlama", "Silmə", "Çap etmə", "Kopyalama"],
  1, None, 2),
 ("Şrift nədir?",
  "Şrift hərflərin yazılış formasıdır.",
  ["Hərflərin yazılış forması", "Kompüterin hissəsi",
   "Oyun proqramı", "Kabel növü"], 1, None, 2),
 ("Qrafik redaktorda nə yaradılır?",
  "Qrafik redaktorda şəkillər çəkilir.",
  ["Şəkillər", "Musiqi", "Cədvəllər yalnız", "Oyunlar"],
  1, None, 1),
 ("Mətnli şəkil nədir?",
  "İçində yazı olan şəkil mətnli şəkil adlanır.",
  ["İçində yazı olan şəkil", "Səsli şəkil",
   "Hərəkətli oyun", "Boş vərəq"], 1, None, 2),
 ("Kalkulyator proqramında hansı əməllər yerinə yetirilir?",
  "Toplama, çıxma, vurma və bölmə əməlləri aparılır.",
  ["Toplama, çıxma, vurma, bölmə", "Yalnız yazı",
   "Yalnız şəkil", "Heç bir əməl"], 1, None, 1),
 ("Proqram pəncərəsi ekranda nəyə bənzəyir?",
  "Pəncərə düzbucaqlı sahə şəklində açılır.",
  ["Düzbucaqlı sahəyə", "Dairəyə", "Ulduza",
   "Üçbucağa"], 1, None, 2),
 ("İş masasında proqramlar nə ilə göstərilir?",
  "Hər proqramın öz nişanı (ikonu) var.",
  ["Nişanlarla (ikonlarla)", "Rəqəmlərlə", "Səslə",
   "Kölgə ilə"], 1, None, 2),
 ("Proqramı açmaq üçün nişanın üzərində nə edilir?",
  "Nişan üzərində ikiqat klik edilir.",
  ["İkiqat klik", "Uzun fit", "Ekranı silmək",
   "Düyməni saxlamaq"], 1, None, 2),
 ("Mətndə başlığı fərqləndirmək üçün nə etmək olar?",
  "Başlığı qalın şriftlə yazmaq olar.",
  ["Qalın şriftlə yazmaq", "Kiçiltmək", "Silmək",
   "Gizlətmək"], 1, None, 2),
 ("Yazının rəngini dəyişəndə mətnin mənası dəyişirmi?",
  "Rəng yalnız görünüşü dəyişir.",
  ["Xeyr, yalnız görünüşü dəyişir", "Bəli, tam dəyişir",
   "Mətn silinir", "Mətn böyüyür"], 1, None, 2),
 ("Şəkilə yazı əlavə etmək üçün hansı alətdən istifadə olunur?",
  "Mətn (A) aləti şəklə yazı əlavə edir.",
  ["Mətn (A) aləti", "Silgi", "Doldurma", "Lupa"],
  1, None, 2),
 ("Kompüterdə misalların cavabını yoxlamaq üçün hansı proqram köməkçidir?",
  "Kalkulyator proqramı hesablamada kömək edir.",
  ["Kalkulyator", "Qrafik redaktor", "Saat", "Oyun"],
  1, None, 1),
 ("Mətn redaktorunda yeni sətir necə yaranır?",
  "Enter düyməsi yeni sətrə keçirir.",
  ["Enter düyməsi ilə", "Boşluqla", "Silgi ilə",
   "Mausu tərpətməklə"], 1, None, 2),
 ("Proqramda görülən işi geri qaytarmaq mümkündürmü?",
  "Geri qaytarma əmri son əməliyyatı ləğv edir.",
  ["Bəli, geri qaytarma əmri var", "Xeyr, heç vaxt",
   "Yalnız şənbə günü", "Yalnız oyunlarda"], 1, None, 3),
 ("Şəkli böyütmək üçün qrafik redaktorda nə edilir?",
  "Şəklin ölçüsü dəyişdirilir.",
  ["Ölçüsü dəyişdirilir", "Şəkil silinir",
   "Kompüter yenidən qoşulur", "Rəng dəyişdirilir"],
  1, None, 3),
 ("Mətn və şəkli birləşdirmək nə üçün lazımdır?",
  "Şəkil yazını daha əyani və aydın edir.",
  ["Yazını əyani etmək üçün", "Yaddaşı doldurmaq üçün",
   "Printeri yormaq üçün", "Lazım deyil"], 1, None, 3),
 ("Proqram pəncərəsinin yuxarısında nə yazılır?",
  "Pəncərənin başlığında proqramın adı olur.",
  ["Proqramın adı", "İstifadəçinin yaşı", "Havanın istiliyi",
   "Mahnının sözləri"], 1, None, 2),
 ("Yazılmış mətn kompüterdə hansı formada saxlanılır?",
  "Mətn fayl şəklində yaddaşda saxlanılır.",
  ["Fayl şəklində", "Kağız şəklində", "Səs şəklində",
   "Saxlanılmır"], 1, None, 3),
 ("Bir proqramdan başqasına keçmək mümkündürmü?",
  "Pəncərələri dəyişməklə proqramlar arasında keçmək olar.",
  ["Bəli, pəncərələri dəyişməklə", "Xeyr, mümkün deyil",
   "Yalnız kompüteri söndürməklə", "Yalnız ustanın köməyi ilə"],
  1, None, 3),
 ("Proqramla işi bitirəndə nə etmək lazımdır?",
  "İşi yadda saxlayıb proqramı bağlamaq lazımdır.",
  ["İşi saxlayıb proqramı bağlamaq", "Ekranı örtmək",
   "Mausu çıxarmaq", "Heç nə"], 1, None, 2),
],
}
for _k, _v in YENI_INF.items():
    SUALLAR[_k] = _v



def yoxla():
    n = xeta = 0
    butun = set()
    movzu_fenn = {m: f for f, m, _r in MOVZULAR}
    for movzu, siyahi in SUALLAR.items():
        assert movzu in movzu_fenn, movzu
        if len(siyahi) != 20:
            print("XETA  %s: %d sual (20 olmalidir)" % (movzu, len(siyahi)))
            xeta += 1
        for body, why, opts, correct, expect, diff in siyahi:
            n += 1
            p = []
            if len(opts) != 4: p.append("variant sayi %d" % len(opts))
            if len(set(opts)) != len(opts): p.append("tekrar variant")
            if not (1 <= correct <= 4): p.append("correct")
            if not why: p.append("izah bos")
            if diff not in (1, 2, 3): p.append("cetinlik")
            if body in butun: p.append("eyni sual iki defe")
            butun.add(body)
            if expect is not None and opts[correct - 1] != expect:
                p.append("hesablanan «%s» != variant «%s»" % (expect, opts[correct - 1]))
            for t in [body, why] + opts:
                if "'" in t: p.append("apostrof var")
            if p:
                xeta += 1
                print("XETA  %s: %s\n      %s" % (movzu, body[:60], "; ".join(p)))
    hes = sum(1 for s in SUALLAR.values() for q in s if q[4] is not None)
    print("%d sual yoxlandı (%d-i hesabla təsdiqləndi), %d xəta" % (n, hes, xeta))
    return xeta == 0, n


def sql_yaz(n):
    q = lambda t: t.replace("'", "''")
    on = {"riyaziyyat": "riy2", "az-dili": "az2",
          "hayat-bilgisi": "hey2", "informatika": "inf2"}
    setirler = []
    for fenn, movzu, rub in MOVZULAR:
        qisa = movzu.split("-", 2)[2]
        for i, (body, why, opts, correct, _e, diff) in enumerate(SUALLAR[movzu], 1):
            setirler.append(
                "('%s-%s#%d','%s','%s',%d,%d,'%s','%s',array['%s','%s','%s','%s'],%d)"
                % (on[fenn], qisa, i, fenn, movzu, diff, rub, q(body), q(why),
                   q(opts[0]), q(opts[1]), q(opts[2]), q(opts[3]), correct))
    with io.open(CIXIS, "w", encoding="utf-8") as f:
        f.write("""-- =====================================================================
--  24_bank_sinif2.sql : 2-CI SINIF PLATFORMA SUAL BANKI
--
--  BU FAYL ELLE YAZILMIR - tools/sinif2.py yaradir:
--      python3 tools/sinif2.py
--
--  Riyaziyyat 9 + Az dili 7 + Heyat bilgisi 6 + Informatika 4
--  = 27 movzu x 20 = %d.  ext_key: riy2-/az2-/hey2-/inf2-...
--  ON SERT: 14_movzular.sql ve 15_movzular_ederslik.sql islenmis olmalidir.
--  SONRA:   05_grants.sql yeniden islet.
-- =====================================================================

do $$
begin
  if not exists (select 1 from public.topics t join public.subjects s
      on s.id = t.subject_id
     where (s.slug, t.slug) in (('riyaziyyat','riy-2-vurma-cedveli'),
                                ('az-dili','az-2-durgu'),
                                ('hayat-bilgisi','hey-2-yer-kuresi'),
                                ('informatika','inf-2-obyekt'))
     having count(*) = 4) then
    raise exception 'ONCE 14_movzular.sql ve 15_movzular_ederslik.sql isledilmelidir.';
  end if;
end $$;

delete from public.question_options o
 using public.questions q
 where o.question_id = q.id
   and q.owner_type = 'platform'
   and (q.ext_key like 'riy2-%%' or q.ext_key like 'az2-%%'
        or q.ext_key like 'hey2-%%' or q.ext_key like 'inf2-%%');

with d(ext, fenn, topic, diff, rub, body, why, opts, correct) as (values
%s
),
ins as (
  insert into public.questions
    (ext_key, owner_type, subject_id, level_id, topic_id, kind,
     body, explanation, difficulty, quarter, status)
  select d.ext, 'platform', s.id, l.id, tp.id, 'single',
         d.body, d.why, d.diff, d.rub, 'published'
    from d
    join public.subjects s on s.slug = d.fenn
    join public.programs p on p.slug = 'ibtidai'
    join public.levels   l on l.program_id = p.id and l.code = '2'
    join public.topics   tp on tp.subject_id = s.id and tp.slug = d.topic
  on conflict (ext_key) do update
    set body = excluded.body, explanation = excluded.explanation,
        difficulty = excluded.difficulty, quarter = excluded.quarter,
        topic_id = excluded.topic_id, level_id = excluded.level_id,
        subject_id = excluded.subject_id, status = 'published'
  returning id, ext_key
)
insert into public.question_options (question_id, ord, body, is_correct)
select ins.id, o.ord, o.txt, o.ord = d.correct
  from ins
  join d on d.ext = ins.ext_key,
  lateral unnest(d.opts) with ordinality as o(txt, ord);

do $$
declare n int; k int;
begin
  select count(*) into n from public.questions
   where owner_type = 'platform'
     and (ext_key like 'riy2-%%' or ext_key like 'az2-%%'
          or ext_key like 'hey2-%%' or ext_key like 'inf2-%%');
  if n <> %d then
    raise exception 'sinif2 suallari: %d gozlenilirdi, %% tapildi', n;
  end if;
  select count(*) into k from public.questions q
   where (q.ext_key like 'riy2-%%' or q.ext_key like 'az2-%%'
          or q.ext_key like 'hey2-%%' or q.ext_key like 'inf2-%%')
     and ((select count(*) from public.question_options o
            where o.question_id = q.id) <> 4
       or (select count(*) from public.question_options o
            where o.question_id = q.id and o.is_correct) <> 1);
  if k > 0 then
    raise exception '%% sualda variant qurulusu sehvdir', k;
  end if;
  select count(distinct topic_id) into k from public.questions
   where ext_key like 'riy2-%%' or ext_key like 'az2-%%'
      or ext_key like 'hey2-%%' or ext_key like 'inf2-%%';
  if k <> 27 then
    raise exception 'movzu sayi 27 deyil: %%', k;
  end if;
  raise notice '2-ci sinif banki: %% sual, 27 movzu (riy, az, hey, inf).', n;
end $$;
""" % (n, ",\n".join(setirler), n, n))
    print("yazildi: %s" % CIXIS)


if __name__ == "__main__":
    ok, n = yoxla()
    if not ok:
        raise SystemExit(1)
    sql_yaz(n)
